### ISSUE TITLE
Chain and chord exception handling

### ISSUE THREAD

**Issue by meowcoder** [celery/celery#1014]
For example this simple chain:

``` python
result = (add.s('1', 2) | mul.s(3))()
result.state # 'PENDING'
result.get() 
# Never returns or raises any exception on client-side.
# Expected result:
result.state # 'FAILURE' or something
result.get()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
# skipped
TypeError: cannot concatenate 'str' and 'int' objects

# Here is a hacky workaround:
def check_exception(fn):
    def wrapper(*args, **kw):
        lst = list(args) + list(kw.values())
        exceptions = [x for x in lst if isinstance(x, Exception)]
        if exceptions:
            return exceptions[0]

        try:
            return fn(*args, **kw)
        except Exception, exc:
            return exc
    return wrapper

@celery.task(name='add')
@check_exception
def add(x, y):
    return x + y

# in this case return value is:
TypeError("unsupported operand type(s) for +: 'int' and 'str'")
# which is also acceptable, even though raise would be more appropriate
```

Well, actually get() blocks,  as for chain I don't know what's happening to it, looks like it just vanishes into the void, at least I don't see any scheduled or active tasks.

Am I doing something wrong or is this a bug?

**UPDATE**

``` python
@celery.task(name='test-chain')
def test_chain(x):
    finish = finished.s()

    a = add.s(x, 2)
    a.link_error(finish)

    b = mul.s(3)
    b.link_error(finish)

    return celery.chain(a, b, finish)
```

This code actually kinda works, I get to wait for finish subtask, instead of never executed mul subtask, and I get result every time.
Verbose and not pretty, but it's ok, I guess.

Now there is another issue:

``` python
@celery.task(name='filter_exceptions')
def filter_exceptions(args):
    for exception in filter(isexception, args):
        raise exception

    return args

exception_filter = filter_exceptions.s()
projects = celery.group([get_project.s(id) for id in projects])

header = celery.group(
    get_submission.s(submission.id),
    get_jira_issue.s(str(submission.sub_ticket))
)

task = (header | exception_filter | projects)
```

Is there any way to avoid exception_filter? Without it get_project subtasks might receive (Exception, issue) tuple as first argument, where as I want get_project subtasks not to execute at all.

**Comment by jurrian** [comment]
In Celery 4.1.0 I noticed that you can do `node.get(propagate=True, follow_parents=True)` which should do the same thing as `propagate_chain_get` I guess.

However, I noticed that doing `node = x.delay()` `node.get(propagate=True, follow_parents=True)` kept hanging since the task was still in the PENDING state while it had FAILED seconds later.

So I ended up doing:
```
def propagate_chain_get(terminal_node, timeout=None):
    for node in reversed(list(terminal_node._parents())):
        try:
            node.get(propagate=True, timeout=timeout)
        except:
            pass
```
It's a bit hacky, accessing a protected member, but it does the job..

**Comment by auvipy** [comment]
could you send a pr with your proposed solution for review?

**Comment by jurrian** [comment]
@auvipy I guess we first need to determine the proper behaviour of `follow_parents`: in the [docs](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.AsyncResult.get) it only says:

> follow_parents (bool) – Re-raise any exception raised by parent tasks.

So my interpretation is that if you do `x.get(propagate=True, follow_parents=True)`, it will iterate through it's parent tasks and will re-raise if any exception that might, so it won't wait forever when one of the parents fails. This should give the same behaviour as `propagate_chain_get` proposed by Ask.

If this is true, I think I can come up with a pull request to fix it for the right behaviour.
Please confirm.

**Comment by thedrow** [comment]
I believe you are correct.
