### ISSUE TITLE
Celery events are not removed from MongoDB broker

### ISSUE THREAD

**Issue by rmihael** [celery/celery#1047]
We're using Celery with MongoDB both as broker and results backend in production with quite a success. However recently we found that Mongo database used for Celery queues grown up to 50+ GBs. After short investigation I found that 99.9% of all documents in "messages" collection are belonging to "celeryev" queue.

Our workers have events enabled in order for Celery Flower frontend to work. I always assumed that event got wiped after consuming, but looks like I was wrong.

Celery report is as follows:

[root@app1 nimble]# bin/celery report

software -> celery:3.0.9nimble (Chiastic Slide) kombu:2.4.7nimble py:2.7.3
            billiard:2.7.3.12 pymongo:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:mongodb results:mongodb

I believe that we see exactly the same behavior as in #436. I see three different celeryev queues, but we only have one single listener active (Flower):

    SECONDARY> db.messages.distinct("queue", {queue: /^celeryev/})
    [
        "celeryev.2a304cc3-78b8-451c-9728-99d0c09ccde1",
        "celeryev.3cbbd9b5-b967-4297-8a50-f3313dae0650",
        "celeryev.d94fb4c0-8ab4-4d12-9469-f93e090a7631"
    ]

I also see a lot of "worker.heartbeat" routing keys in documents in these queues. Probably that's the majority of all events.

Distribution between these three queues is quite uniform:

    SECONDARY> db.messages.group({key: {queue: true}, cond: {queue: /^celeryev/}, reduce: function(obj,prev) { prev.csum += 1; }, initial: { csum: 0 }})
    [
        {
            "queue" : "celeryev.2a304cc3-78b8-451c-9728-99d0c09ccde1",
            "csum" : 21619432
        },
        {
            "queue" : "celeryev.3cbbd9b5-b967-4297-8a50-f3313dae0650",
            "csum" : 14117210
        },
        {
            "queue" : "celeryev.d94fb4c0-8ab4-4d12-9469-f93e090a7631",
            "csum" : 18428199
        }
    ]

I'm wondering, is it possible to use same fix for MongoDB as was used for Redis in #436?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by rgant** [comment]
It would be good to warn people about this trying to use mongodb as the broker. I have a message collection with 19 million records created in the last 7 days. I'd consider mongodb to not be a viable broker for celery.

**Comment by rgant** [comment]
In case anyone ever finds this ticket again. I am making the messages collection in mongodb used by celery a cappedCollection following these instructions: https://docs.mongodb.com/v2.6/core/capped-collections/#convert-a-collection-to-capped

I don't know that it will work, or if it is the best idea. But it has to be better than allowing the mongodb to blow up to 100GB on disk.

**Comment by jeffwidman** [comment]
@rgant You could submit a PR adding a warning to the docs. I bet @ask would merge it, as he'd certainly prefer to have fewer issues against faulty brokers.

**Comment by antonyc** [comment]
@rgant you should use TTL, it's a more correct solution.

**Comment by rgant** [comment]
@antonyc At least with the version of Celery I am using there isn't a suitable column for MongoDB's TTL feature. To use that feature you need a date typed value and an index. Since Celery itself is creating the documents I don't think this is as simple of a change as using a capped collection which can be applied without any additional fields.

**Comment by antonyc** [comment]
Try to read https://github.com/celery/kombu/issues/537 - the PR connected to this ticket. in version 4.0 of kombu TTL is added to celery messages collection through broker preferences.

**Comment by rgant** [comment]
Sounds great when 4.0 is released I can give this a shot.

**Comment by antonyc** [comment]
I checked it and it works.

**Comment by mindojo-victor** [comment]
I have 644792 documents in `messages` collection with `queue: 'celeryev.*'` fields. I have Kombu 4.0.2. What do I need to set up that old messages would be removed?

**Comment by buxizhizhoum** [comment]
> Try to read [celery/kombu#537](https://github.com/celery/kombu/pull/537) - the PR connected to this ticket. in version 4.0 of kombu TTL is added to celery messages collection through broker preferences.

Hi @antonyc , could you please share an example about how to config ttl?  I searched the document of celery and only find one that is related: `event_queue_ttl`, but it seems not work, the `message` collection of my mongodb is still increase after I set this value, is there  any point that I am missing?

**Comment by alexNMD** [comment]
Do you have news about that ?
The parameter "event_queue_ttl" seem to not be the solution. 
Because no ttl is added to document inside "messages" collection in MongoDB

And CappedCollection is only for "message.broadcast", so I don't how to solve this unstoppable growing of MongoDB Broker database...
