### ISSUE TITLE
Feature: Prefer local workers to leverage data locality

### ISSUE THREAD

**Issue by erikvanzijst** [celery/celery#1127]
I'd be curious to learn if there's any interest for the ability to have Celery consume jobs on specific workers for the benefit of improved data locality.

In our setup we have a large number of compute nodes, each running our application, as well as a host of celery workers. When new jobs are dispatched from these machines, they usually end up on a worker on a different host.

Many of our jobs perform very heavy file system reads in the same (NFS-based) directories as the code that originally dispatched the task. When the task is consumed by a another machine, it will find a cold NFS cache, making execution significantly slower than had the task been picked up by a worker on the same machine that spawned it.

I suspect there will be other examples where local processing would provide performance gains.

What I'd look for is a way to add a "hint" to a task that tells Celery to consume the task on the host that spawned it, provided that host has idle workers available. If it doesn't, or if celery isn't even running on that node, another node should consume it as per normal.

Such hint might even extend to the process level, where a subtask spawned by another task would get consumed by the same worker process as its parent task, such that it can take full advantage of any in-process caching.

**Comment by daniel-cohen** [comment]
@ask  I know this is an old thread, but I couldn't find any other reference to anything similar to this.
I have bunch of dependant tasks which I need to run on the same host as they start with a download of a 100-300GB file (and I can't transfer that file around). 

Is there a way to make sure that all subsequent task in a group/chord etc. run under the same host which picked up the first task ? (preferably without manually/arbitrarily picking one)
And then if a task fails or the host dies, the entire "group" can be run on a different host maybe ?

**Comment by odedfos** [comment]
I'm looking for the same thing exactly as @daniel-cohen described. Is it possible with celery?

**Comment by ask** [comment]
You can use worker direct to send to a specific worker.  Only the task itself can reroute, so you can only do this when calling a group/chord.

**Comment by ask** [comment]
worker direct: http://docs.celeryproject.org/en/latest/configuration.html#celery-worker-direct

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
