### ISSUE TITLE
Feature: Support for per-task timezone in scheduler

### ISSUE THREAD

**Issue by rslinckx** [celery/celery#1139]
I would like each of my scheduled tasks to define its own timezone and use that information to compute the sleep time in is_due()

What I did is the following:
* Subclass schedules.crontab() to accept a 'tz' argument which overrides the default 'tz' property
* Change the nowfun to: 

    self.nowfun = lambda: self.tz.normalize(pytz.utc.localize(datetime.utcnow()))

That way the 'now' for that particular task is the task-local time

* Override remaining_estimate() to change its return value. Instead of returning remaining() as defined in celery.utils.timeutils.remaining i change it to:

    def remaining(start, ends_in, now, tz):
        end_date = tz.normalize(tz.localize((start + ends_in).replace(tzinfo=None)))
        return end_date - now

This way I force the computed next date to be in the local time and then compute the real time difference between now in local time and end_date in local time.

The problem I'm trying to solve while doing this is the following (assuming timezone Europe/Brussels):
* A scheduled task is set to run every day at 9am
* The last_run_at was 2012-10-27 9am
* The next run is computed to be 2012-10-28 9am (start + ends_in)
* The remaining will then be 86400 seconds (1 day)

BUT, because of the time change that occured the night between 27 and 28 october, the real remaining time should be 86400+3600 (1day + 1hour). That's what the code snippet above does. It marks the next run to be an absolute local time in the time zone at that moment, ie 9am in the new timezone not the old one. Then the difference is properly computed.

I'm not sure if this could one day land in celery itself in some form, in the meantime i'll keep using my workaround, but it would be nice to have some options in the schedule to compute the remaining time while taking into account that task's particular timezone.

**Comment by linar-jether** [comment]
Working snippet:
```python
# Workaround to set timezone per task
class TzAwareCrontab(crontab):
    from celery.utils import timeutils

    def __init__(self, minute='*', hour='*', day_of_week='*', day_of_month='*', month_of_year='*', tz=pytz.UTC,
                 app=None):
        self.tz = tz

        nowfun = lambda: self.tz.normalize(pytz.utc.localize(datetime.utcnow()))

        super(TzAwareCrontab, self).__init__(minute, hour, day_of_week, day_of_month, month_of_year, nowfun, app)

    def remaining_estimate(self, last_run_at, ffwd=timeutils.ffwd):
        def remaining(start, ends_in, now):
            end_date = self.tz.normalize(self.tz.localize((start + ends_in).replace(tzinfo=None)))
            return end_date - now

        return remaining(*self.remaining_delta(last_run_at, ffwd=ffwd))


TzAwareCrontab(hour=7, minute=59,
                                   tz=pytz.timezone('US/Eastern'))
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
