### ISSUE TITLE
Feature: Custom content-type settings in remote (http) tasks

### ISSUE THREAD

**Issue by saidimu** [celery/celery#1202]
Right now the only way to set a custom content-type in `remote (http) tasks` is to create to override two classes: `HttpDispatch` and `HttpDispatchTask` along the lines of http://pastebin.com/XXaDWmC7

This seems unnecessarily complex for what is normally a very simple matter when dealing with http requests.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by auvipy** [comment]
closing as low prio. reopen again when needed
