### ISSUE TITLE
Workers die after an hour or so

### ISSUE THREAD

**Issue by ChrisHughes** [celery/celery#1209]
Hi all,

Been running into a very strange problem on a gunicorn / django / rabbitmq / celery server.

After about an hour of running well, some workers will stop accepting tasks, returning instead "WorkerLostError: Worker exited prematurely".

When this occurs, my message queue is not full and memory / cpu use are at normal levels. Other worker instances seem to work fine.

The function of this server is to take screenshots of webpages using a modified version of webkit2png running inside the worker instances (pyqt). However before this I was using cutycapt (a standalone program) called from the worker, and the same problem existed, so it rules out the actual work being done on the worker as a cause.

My setup is as follows:

Ubuntu 12.10 running stock (ubuntu repository) nginx, gunicorn and django. RabbitMQ 3.0.2, celery 3.0.15 and django-celery 3.0.11.

Using gunicorn, I run 4 django instances. I separately run 20 celery workers from a python wrapper that manages the workers and checks they don't crash, out of these 20 one is a 'beat' worker. I then run 4 instances of Xvfb in a similar python wrapper as a service, and the 20 workers connect to an available x-server at random.

I know Xvfb is not the problem here, as when a worker dies, the ratio is not 1:5 (given 20 workers to 4 instances of Xvfb), usually it's 1 or 2 of the 20 workers. I use the -noreset parameter on Xvfb to prevent a known memory leak.

My celery configuration in settings.py is as follows:

CELERY_RESULT_BACKEND = "amqp"
This number must be 1 - as QApplication
requires all GUI-related tasks to be on main threads
CELERYD_CONCURRENCY=1  
CELERY_IMPORTS = ("djangoproject.workers.apppreview")
BROKER_POOL_LIMIT = None
Reqiure soft and hard time limits to be defined
Could be related to this bug https://github.com/celery/celery/issues/1177
CELERYD_TASK_SOFT_TIME_LIMIT = 30
CELERYD_TASK_TIME_LIMIT = 120

I can only have a concurrency of one for each worker, as pyqt requires all work be done on a main application thread, not a sub-thread. However before when I was using cutycapt, I had 10 threads per worker and still ran into this issue.

I'm calling the tasks from django like this:

@never_cache
def generate_screenshot(request):
url = request.GET.get('url', 'app.project.com/home')
result = apppreviewworker.generate_screenshot.delay(url)
data = result.get()
return HttpResponse(data, mimetype="image/png")

And the worker's code is something like this (the older version of this was calling a command with os.system and waiting for the result and still ran into this issue):

@celery.task(name="apppreview.generate_screenshot")
def generate_screenshot(url):
global server_number, qt4app, renderer
if not server_number: lease_server_number()
QApplication.processEvents()
data = renderer.render_to_bytes(url)
return data

When the server goes down, I'm getting this error logged to the worker's log file:

[2013-02-22 13:31:56,779: ERROR/MainProcess] consumer: Cannot connect to amqp://guest@...:5672//: [Errno 111] Connection refused.

Trying again in 4.00 seconds...

[2013-02-22 13:32:03,168: CRITICAL/MainProcess] Task apppreview.generate_screenshot[4565d74c-83ef-4f67-b7d3-a417f90d383a] INTERNAL ERROR: error(111, 'Connection refused')

and on django's end, I get this:

2013-02-24 16:30:06 [14461] [CRITICAL] WORKER TIMEOUT (pid:14484)

I'm at the point where I have to move on and no longer use celery / rabbitmq is I can't get this working soon - as uptime for this server is critical, and it's down about 30% of the time requiring ~20 restarts a day.

I really need some help from the community here in tracking this down, this is an elusive issue and I've read through the various outstanding bugs, googled this problem and done all 
the troubleshooting I can with what information is out there. Any thoughts on this would be very much appreciated.

**Comment by v-chinta** [comment]
after celery upgrade to latest version 5.3.6, noticing workers dying after 1 hour time. (. Signal: 37,  Exitcode: 155 & Signal: 65,  Exitcode: 155). no change in code.
