### ISSUE TITLE
Deadlock with Billiards

### ISSUE THREAD

**Issue by AnonymousHelper** [celery/celery#1218]
Celery 3.0.13
Biliiards 2.7.3.19

Workers consuming 10,000 tasks a day.
We kill a worker after executing 1 task. Max_Task_Per_Child = 1

Overtime, we deadlocked workers.
Can't get a pystack for you. 
In the Stack Trace, it shows that the deadlock happens while billiards is trying to acquire a lock.
#0  0x0000003cff40c0ed in sem_wait () from /lib64/libpthread.so.0
#1  0x00002b180708129a in Billiard_semlock_acquire (self=0x3d165f9340, args=<value optimized out>, kwds=<value optimized out>) at Modules/_billiard/semaphore.c:312

Strace shows the processes in a futex wait state.

What sort of data can help you debug this problem?

**Comment by j0hnsmith** [comment]
@mvikharev https://github.com/celery/celery/issues/1218#issuecomment-17158803 helped me find my problem, thanks.
