### ISSUE TITLE
Feature: Allow recycling worker after a configurable period

### ISSUE THREAD

**Issue by idanz** [celery/celery#1277]
Currently there is a configuration to recycle the worker after a certain amount of tasks (MAX_TASKS_PER_CHILD).

It would be useful to add a similar mechanism for recycling the worker after a given amount of time.
The constraint doesn't have to be strict and can be checked only in the end of a task like the MAX_TASKS_PER_CHILD settings.
The reason for this is that when the size of tasks varies significantly, it is hard to set the correct MAX_TASKS_PER_CHILD for dealing with memory leaks for example. In that case I prefer the worker to recycle itself after a given amount of runtime.

**Comment by alekibango** [comment]
MAX_USED_RSS_MEMORY  would also be sweet!

i mean, i do not want to wait until all my ram is gone. Recycle worker soon enough.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
