### ISSUE TITLE
Merging celery-redis-unixsocket

### ISSUE THREAD

**Issue by blaze33** [celery/celery#1283]
celery-redis-unixsocket allows you to use a redis broker connected to an unix socket (like `/tmp/redis.sock`). Especially useful when you can't open a tcp connection.

I'm looking for some advice/tips/recommendations on how to merge https://github.com/piquadrat/celery-redis-unixsocket here given that @ask agreed in principle. I could make some time to do the work if I had some advice on how to proceed.

There is an open issue for this: https://github.com/piquadrat/celery-redis-unixsocket/issues/3. Thanks!

**Comment by DmytroLitvinov** [comment]
Hello @ask .

Does unix socket work for result backend(redis)? I see it works for broker.
I can't find in official [docs Celery 4.2.2](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#results) about that.
