### ISSUE TITLE
@task time_limit/soft_time_limit doesn't override defaults

### ISSUE THREAD

**Issue by rrauenza** [celery/celery#1300]
3.0.17, billiard .26:

I made a task to test this:

```
@celery.task(time_limit=5, soft_timeout_limit=4)                                
def demo(self):                                                                 
    import time                                                                 
    count = 0                                                                   
    while count < 1000:                                                         
        time.sleep(1)                                                           
        count += 1                                                              
        print count               
```

And in my settings:

```
CELERYD_TASK_TIME_LIMIT=timedelta(hours=24).total_seconds()                       
CELERYD_TASK_SOFT_TIME_LIMIT=CELERYD_TASK_TIME_LIMIT * 0.99     
```

The task will count all the way up to 1000, UNLESS I ^C or restart the worker, at which point I get a message that a HardTimeout (of 5 secs) occurred (which should have occurred long long long ago).

If I change 

```
CELERYD_TASK_TIME_LIMIT=None
CELERYD_TASK_SOFT_TIME_LIMIT=None
```

Then the behavior is correct.

So whether set or not, it appears the task does pick up the local time_limit setting -- but it seems like the billiard monitoring/timeout thread either isn't running or has the wrong timeout.

Adding some logging in billiard:

   if self.timeout is not None or self.soft_timeout is not None:  
            import logging  
            logging.warning("Starting _timeout_handler(): %s, %s", self.timeout, self.soft_timeout)
            self._start_timeout_handler()  
        else:  
            logging.warning("NOT Starting _timeout_handler(): %s, %s", self.timeout, self.soft_timeout)

I do get this:

```
[2013-04-10 15:53:38,635: WARNING/MainProcess] Starting _timeout_handler(): 86400.0, 85536.0
```

So I kind of wonder if the threaded _timeout_handler is looking at the global values... but the event handler (i.e., worker shutdown) is looking at the task's specific values.

**Comment by ecmascriptguru** [comment]
Hi @ask 
The **--time-limit** option doesn't work on my window machine at all. It did work with `time.sleep(<num>)` but doesn't work with real process to scrap something at all.

Let me share the code here
```
@celery.task(bind=True, time_limit=2, soft_time_limit=1)
def find_email(self, id, user_id, wait, job_id):
    time.sleep(wait)
    hunter = Hunter(self)
    try:
        hunter.run(id, user_id, job_id)
        return {'candidate_id': id, 'user_id': user_id, 'status': 'Completed'}
    except SoftTimeLimitExceeded as e:
        print("Soft Time Limit reach!")
        print(str(e))
        hunter.stop()
        return {'candidate_id': id, 'user_id': user_id, 'status': 'Failed'}
```

According to instructions, it should raise the **SoftTimeLimitExceeded** after 1 second but I can't get at all. Would you like to invest a few minutes for me?

Thanks,
Alexis

**Comment by rrauenza** [comment]
@ecmascriptguru  See http://docs.celeryproject.org/en/latest/userguide/workers.html

> Note:  Time limits don’t currently work on platforms that don’t support the SIGUSR1 signal.

I think Windows may fall in that category?

Regardless, you're asking in an issue that isn't related to your problem.  I suggest asking over at StackOverflow where @ask also responds, but you can also get a larger audience.
