### ISSUE TITLE
Feature: Redis: Restore unacked on broker reconnection

### ISSUE THREAD

**Issue by gfronza** [celery/celery#1307]
Hi,

In my application I use ETA tasks to send future emails and I noticed that sometimes some of these tasks never got executed. After investigating the issue, I may have found what is causing it (at least now I'm able to reproduce the problem). If the worker lose the connection with redis server and then reconnect, tasks that were already scheduled (ETA) will not execute anymore. It's like the worker is not putting tasks back to queue.

To reproduce the problem:
 1) Submit an ETA task
 2) Kill redis-server process
 3) Start redis-server again
 4) At this point, the ETA task will not executed anymore.

Thanks.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by carolinux** [comment]
I want to add that I also experienced this behavior. This thread is helpful, because it suggests switching to rabbitmq as something that will specifically fix the problem.
