### ISSUE TITLE
on_revoke task workflow

### ISSUE THREAD

**Issue by naftulikay** [celery/celery#1360]
It'd be very nice to be able to define tasks that have a logic flow to be executed if and when a task is revoked by `revoke()`:

```
def MyTask(Task):

    def run(self):
        time.sleep(randint(10, 1000) / 1000.0)
        print "Hello, Werld!"

    def on_revoke(self, terminate, signal):
        # do cleanup
        pass
```

Thus, when running the task, it would be able to execute code when revoked.

**Comment by vesnikos** [comment]
just for consistency this should added on the Task. I am already using before_publish signal to prep the backend and it feels like an anti-pattern spreading logic in two different places

**Comment by auvipy** [comment]
> just for consistency this should added on the Task. I am already using before_publish signal to prep the backend and it feels like an anti-pattern spreading logic in two different places

do you have any implementation idea in mind?
