### ISSUE TITLE
Fetch tasks for multiple brokers

### ISSUE THREAD

**Issue by liviubunda** [celery/celery#1431]
Hello,

I'm interested if you have considered adding a feature to support receiving tasks from multiple brokers at the same time.

In this kind of configuration, every worker node listens to multiple brokers and receives tasks from all them.

If you have, maybe you can share why you chose not to implement it and any potential workarounds to this situation.

Thanks,
Liviu

**Comment by ask** [comment]
#1560 was much easier to solve, so this is not fixed with the closing of that issue.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
