### ISSUE TITLE
Celery-multi don't start work

### ISSUE THREAD

**Issue by rafaelnovello** [celery/celery#1449]
Hi!

I'm trying to use celery multi to start N workers but when I use it the workers don't start. It's look like the workers don't receive the job, like in the issue #620

I tried with manage.py (Django project) and with celery command directly like this examples:

``` shell
$ ./manage.py celery multi start 5 -E -B -l INFO  -Q:1-3 contacts -Q:4,5 campaigns,celery
```

and

``` shell
$ celery multi start 5 -E -B -l INFO  -Q:1-3 contacts -Q:4,5 campaigns,celery
```

In both the output was the same:

``` shell
celeryd-multi v3.0.19 (Chiastic Slide)
> Starting nodes...
    > celery1.note: OK
    > celery2.note: OK
    > celery3.note: OK
    > celery4.note: OK
    > celery5.note: OK
```

I have started trying with eventlet but it don't work too.

I'm using:
- celery 3.0.19
- django-celery 3.0.17
- rabbitmq 3.0.2

Am I doing something wrong? Can someone help?

Best Regards!

**Comment by jklemm** [comment]
Same behaviour here.. Is there a solution to this case?
