### ISSUE TITLE
urllib2.urlopen in a task fails with CoreFoundation fork error, leaving celeryd defunct (Mac OS X)

### ISSUE THREAD

**Issue by gthb** [celery/celery#146]
This task:

```
import urllib2
@task
def bomb_celeryd():
    urllib2.urlopen('http://anything.com/').read()
```

breaks my celeryd worker completely:

```
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

This occurs 17 times in the celeryd output (not as log statements), and then this gets logged:

[2010-07-08 01:48:10,472: INFO/PoolWorker-2] child process calling self.run()

presumably because the worker process PoolWorker-1 has died. But the new worker does not process any tasks; celeryd is defunct. It responds to Ctrl-C with:

```
[2010-07-08 13:00:52,124: WARNING/MainProcess] celeryd: Hitting Ctrl+C again will terminate all running tasks!
[2010-07-08 13:00:52,126: WARNING/MainProcess] celeryd: Warm shutdown (MainProcess)
[2010-07-08 13:00:52,699: INFO/PoolWorker-2] process shutting down
[2010-07-08 13:00:52,699: INFO/PoolWorker-2] process exiting with exitcode 0
```

but then hangs and must be killed with `kill -9`.

This is on Mac OS X 10.5.8, running Python 2.5.4 with multiprocessing 2.6.2.1, celery from git master HEAD (with just these three surely unrelated changes: gthb/celery@975b3981e71f4eb0936a, gthb/celery@e1936b10bace795a5752, gthb/celery@280cbb4839007acb11a3).

[Apparently](http://dready.org/blog/2010/03/11/debugging-without-source-on-mac/) `urllib` and `urllib2` use the `CoreFoundation` API on Mac OS X to auto-detect proxy settings, and Mac OS X doesn't allow you to do that on the child side of a fork unless you `exec` first.

Hopefully celeryd can at least be made robust to this error, so that it doesn't totally crash. There's no telling what other python libraries might use `CoreFoundation` and mangle celeryd in the same way.

**Comment by robalar** [comment]
Just hit this issue with macOS 11.4 and celery 4.4.0. Running celery with `celery_dummy_proxy=TEST` prepended fixed the issue. I'm guessing [this function](https://github.com/celery/celery/blob/f915f111b3c218a629d021a982adcc6658c87d50/celery/apps/worker.py#L270) is not getting hit for some reason?
