### ISSUE TITLE
Question: how to capture stdout of remote celery worker?

### ISSUE THREAD

**Issue by pavel-paulau** [celery/celery#1462]
I have a setup with multiple remote Celery workers. In the main program which is starting tasks via apply_async I need continuous access to stdout of active remote workers.

Is it possible using only Celery API?

http://stackoverflow.com/questions/17549598/how-to-capture-stdout-of-remote-celery-worker

**Comment by jan-schulz-k24** [comment]
@pavel-paulau Did you get that to work (stdout of celery task streamed to the submitter of the task)?

**Comment by pavel-paulau** [comment]
Nope.

**Comment by georgepsarakis** [comment]
You could store the log record output as the task result probably and then print it in the task producer.
