### ISSUE TITLE
Task retry does not work.

### ISSUE THREAD

**Issue by dlutcat** [celery/celery#1492]
I run a test about retry feature like below:

``` python
from jobs.celeryapp import celery

@celery.task(name="crons.spider.add")
def add(x, y):
    try:
        raise Exception('This is a Exception')
        return x + y
    except Exception, exc:
        raise add.retry(exc=exc, countdown=5, max_retries=2)
```

`add.retry` did not work.
After debugging the source of `celery.app.task`, I found the process was intercepted by `celery.utils.maybe_reraise` method ([source position on github.com](https://github.com/celery/celery/blob/master/celery/app/task.py#L587)), and Exception was reraised instead of raising `RetryTaskError`. 

So, why and how to fix this?

**Comment by rajendrakrp** [comment]
@ask: Even for me 'retry' isn't working. I have tried example given in http://docs.celeryproject.org/en/3.0/userguide/tasks.html#retrying not using 'bind'. I'm using 3.0.21 version.
 
I can't use `bind=True` as it doesn't work in 3.0.21 version.
