### ISSUE TITLE
Celery beat lockfile has incorrect PID

### ISSUE THREAD

**Issue by orf** [celery/celery#1507]
I run Celery beat on Windows server 2008R2 via a bat script:

    cd /path/to/app
    manage.py celery beat

This spawns a console window and runs celery beat. However if I close the console window and re-run the bat script it won't start because it thinks it is already running. This is because the PID it writes to the file is actually the PID of conhost.exe (which is always running) and not the python executable. Changing the bat script to

    cd /path/to/app
    python manage.py celery beat

results in the correct behaviour. I'm not sure how its picking up the PID of conhost.exe, as far as I can tell it just uses os.getpid().

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
