### ISSUE TITLE
TypeError: next expected at least 1 arguments, got 0

### ISSUE THREAD

**Issue by canercandan** [celery/celery#1512]
It is a bit strange the next function got well an entry non-None object but still raise the error: <pre>TypeError: next expected at least 1 arguments, got 0</pre>

<pre>
python3 manage.py celery worker -B
 
 -------------- celery@candan-leria v3.1.0rc3 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-3.10.3-1-ARCH-x86_64-with-arch
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> broker:      amqp://guest@localhost:5672//
- ** ---------- .> app:         default:0x7f03926e4f90 (djcelery.loaders.DjangoLoader)
- ** ---------- .> concurrency: 4 (processes)
- *** --- * --- .> events:      OFF (enable -E to monitor this worker)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

/usr/lib/python3.3/site-packages/django_celery-3.1.0b2-py3.3.egg/djcelery/loaders.py:132: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2013-08-17 13:41:00,150: WARNING/MainProcess] /usr/lib/python3.3/site-packages/django_celery-3.1.0b2-py3.3.egg/djcelery/loaders.py:132: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2013-08-17 13:41:00,151: WARNING/MainProcess] /usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2013-08-17 13:41:00,151: WARNING/MainProcess] celery@candan-leria ready.
[2013-08-17 13:41:04,184: WARNING/Beat] entry:
[2013-08-17 13:41:04,184: WARNING/Beat] <ModelEntry: add-every-5-seconds celerytest.tasks.add(*[16, 16], **{}) {4}>
[2013-08-17 13:41:04,186: ERROR/Beat] Message Error: next expected at least 1 arguments, got 0
['  File "./manage.py", line 10, in <module>\n    execute_from_command_line(sys.argv)\n', '  File "/usr/lib/python3.3/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line\n    utility.execute()\n', '  File "/usr/lib/python3.3/site-packages/django/core/management/__init__.py", line 392, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n', '  File "/usr/lib/python3.3/site-packages/django_celery-3.1.0b2-py3.3.egg/djcelery/management/commands/celery.py", line 22, in run_from_argv\n    [\'{0[0]} {0[1]}\'.format(argv)] + argv[2:])\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/celery.py", line 729, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/base.py", line 300, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/celery.py", line 721, in handle_argv\n    return self.execute(command, argv)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/celery.py", line 677, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/worker.py", line 155, in run_from_argv\n    return self(*args, **options)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/base.py", line 263, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bin/worker.py", line 183, in run\n    hostname=hostname, pool_cls=pool_cls, loglevel=loglevel, **kwargs\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/worker/__init__.py", line 191, in start\n    self.blueprint.start(self)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bootsteps.py", line 119, in start\n    step.start(parent)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/bootsteps.py", line 352, in start\n    return self.obj.start()\n', '  File "/usr/lib/python3.3/site-packages/billiard-3.3.0.0rc1-py3.3.egg/billiard/process.py", line 132, in start\n    self._popen = Popen(self)\n', '  File "/usr/lib/python3.3/site-packages/billiard-3.3.0.0rc1-py3.3.egg/billiard/forking.py", line 109, in __init__\n    code = process_obj._bootstrap()\n', '  File "/usr/lib/python3.3/site-packages/billiard-3.3.0.0rc1-py3.3.egg/billiard/process.py", line 279, in _bootstrap\n    self.run()\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 491, in run\n    self.service.start(embedded_process=True)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 429, in start\n    interval = self.scheduler.tick()\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 198, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 184, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 181, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 219, in apply_async
    entry = self.reserve(entry)
  File "/usr/lib/python3.3/site-packages/django_celery-3.1.0b2-py3.3.egg/djcelery/schedulers.py", line 178, in reserve
    new_entry = Scheduler.reserve(self, entry)
  File "/usr/lib/python3.3/site-packages/celery-3.1.0rc3-py3.3.egg/celery/beat.py", line 212, in reserve
    new_entry = self.schedule[entry.name] = next(entry)
TypeError: next expected at least 1 arguments, got 0
</pre>

**Comment by rbarlow** [comment]
I experienced a very similarly strange traceback with mongoengine on Python 3.5: https://github.com/MongoEngine/mongoengine/issues/1197

I wonder if this is a Python 3 problem. Might be interesting to see if we can come up with a way to reproduce it with simple Python code (that doesn't use any libraries).
