### ISSUE TITLE
Broadcasting task with MongoDB falls under the on_control hook

### ISSUE THREAD

**Issue by m-vdb** [celery/celery#1514]
see https://groups.google.com/forum/#!topic/celery-users/A-MQMUI_WLo for more info.

This makes it impossible to broadcast a task, because it falls under the on_control handler (see https://github.com/celery/celery/blob/3.0/celery/worker/consumer.py#L561) instead of under the on_task.

I'll try to figure out where the problem is, but not sure I'll succeed !

Thanks

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
