### ISSUE TITLE
celery multi stop does not work when pidfiles are given with the --pidfile:<n> syntax

### ISSUE THREAD

**Issue by bluebomber** [celery/celery#1542]
When I issue a command like the following (with the per-worker pidfile argument syntax):

celery multi start 2 -Q:1 queue1 -n:1 worker1 --logfile:1=/perm/log/worker1.log --pidfile:1=/perm/log/worker1.pid -Q:2 queue2 -n:2 worker2 --logfile:2=/perm/log/worker2.log --pidfile:2=/perm/log/worker2.pid

then issue a command identical to the above, except that "start" has been replaced with "stop":

celery multi **stop** 2 -Q:1 queue1 -n:1 worker1 --logfile:1=/perm/log/worker1.log --pidfile:1=/perm/log/worker1.pid -Q:2 queue2 -n:2 worker2 --logfile:2=/perm/log/worker2.log --pidfile:2=/perm/log/worker2.pid

the stop signal is never delivered to the workers. I can confirm that after the first command, the correct pidfiles are created and contain the correct pids.

**Comment by dejlek** [comment]
It is slightly inconsistent behaviour at the moment...
If you do what you say (celery multi start worker1 worker2) then there is no need for worker%n.log as it will produce workerworker1.log, etc. However, if you do celery multi start 2, then it will give correct names... This surprised me.
