### ISSUE TITLE
How can I in-/decrease concurrency without re-starting celery using eventlet?

### ISSUE THREAD

**Issue by outermedia-cbo** [celery/celery#1547]
Hi,

I start celery like:

```
celery multi start 4 -P eventlet -c:1-4 64 -A myApp
```

That starts 4 workers with 64 (green) threads per worker.
Now I want to reduce the number of concurrent threads per worker to 32. 

It appears that autoscale and pool_shrink do not work:

```
AttributeError("'TaskPool' object has no attribute 'shrink'",)
```

or

```
AttributeError: 'Control' object has no attribute 'autoscale'
```

Is this even possible? 

Regards,
Christoph

**Comment by ankushrgv** [comment]
I have a single task in my tasks.py and an infinite repeating while loop in it. 
There are 4 workers running the same task at the same time but i want only one worker to do so.
So how i'm I supposed to reduce the number of workers from 4 to 1.??
