### ISSUE TITLE
FEATURE: Let Celery support multiple broker URL settings.

### ISSUE THREAD

**Issue by bluebomber** [celery/celery#1560]
Some AMQP implementations provide for more than one broker URL for clients to use. For example, RabbitMQ-Bigwig, a Heroku add-on, publishes both a TX_URL (optimized for publisher connections) and an RX_URL (optimized for consumer connections).

Currently a Celery application instance cannot (directly) be configured to take advantage of such a setup. It would be nice to be able to configure a Celery instance with multiple URL settings, e.g., TX_BROKER_URL, RX_BROKER_URL.

**Comment by ask** [comment]
Implemented by 6038ff2aa315384c04652fd6733a61462d3536b0
