### ISSUE TITLE
Sometimes Celery Hangs, HowTo diagnose?

### ISSUE THREAD

**Issue by mogadanez** [celery/celery#1561]
last  record in  log: 
[2013-10-02 11:50:17,243: INFO/MainProcess] Got task from broker: simpleTask[eea9ca97-cfe0-4321-8d3b-b2ddb6918618]

"celery status" command  not work too  -> hangs too.

Celery: 3.0.23
Sever: Debian 3.2.46-1+deb7u1 x86_64 GNU/Linux
Backend: amqp

**Comment by davidrenne** [comment]
Yes @ask full disk caused mine.  But even after I cleaned up space it still was hanging.  So I rebooted the machine and that seemed to fix it.  But I probably could have just rebooted the worker service.  But I wasnt sure what was the problem.

**Comment by dagisus** [comment]
hey, i got an issue using celery 3.0.23 with django and rabbitmq, i got 2 servers feeding the rabbitmq Q and 1 celery server with 4 workers, previously this setup was working fine using Redis, now that we started using rabbit, with 1 server, the workers were idle, CPU was down and the Q wasn´t being worked, i doble the workers and this seamed to solve the issue (funnt thing, increasing from 4 to 6 didn´t change the problem at all and CPU was down), then today i connected the second server and had the same problem with 8 workers, i started increasing to 10, 12.... until i hit 16 and at that point the Q started to be processed. is this a known issue in celery 3.0.23? do we need to set things diferently?

**Comment by Prathameshrodi-searce** [comment]
HI my Celery queue recieves the task but however doesn't process it.
Any Idea why this might happen??

**Comment by wilderchen** [comment]
maybe it helps to diagnose the issue with the following link address http://memos.ml/

**Comment by Harinib-Kore** [comment]
> HI my Celery queue recieves the task but however doesn't process it. Any Idea why this might happen??

did you find any solution
