### ISSUE TITLE
Proposal for new REST backend and REST Kombu transport

### ISSUE THREAD

**Issue by tliron** [celery/celery#1576]
This is already written, and I'm planning a pull request for both projects.

The basic concept is that all Kombu messages and Celery results are sent via RESTful HTTP (or HTTPS) to a server, which would actually handle the storage/retrieval of data. This provides three important advantages:

1) More flexible deployment: dealing with HTTP is often much easier in "cloud" deployments, instead of each middleware's unique network transport.

2) It is possible to implement the server in non-CPython technologies. For our needs, we have a server based on Prudence and server-side JavaScript, which then stores data to MongoDB.

3) It's possible to implement specialized backends and hooks. Our server is designed to gather message and task statistics and store data in unique formats that make more sense for our implementation.

It would be a nice addition to Celery, we believe!

However, there are two possible issues:

1) The REST communication is all in JSON. However, both Kombu and Celery have slightly awkward JSON encoding: message bodies are sometimes double encoded as JSON strings. We've solved all these problems by introducing a "raw" encoding supported by both Kombu and Celery, with a few small workarounds. However, for this to work well it's necessary to add jsonpickle as a dependency for Kombu. jsonpickle can properly handle encoding of Python classes, which are used by Celery to handle exceptions, and also for Kombu applications trying to send specialized messages. The nice thing is that alljson is used throughout the Kombu/Celery codebase, so it would be used throughout. It's a good library. Would this be acceptable for Kombu?

2) Our Prudence-based server might best be shared with the community as a separate github project, as it's not Python-based. However, I think it would be nice if our contribution included a small Python-based reference server as a starting point for users. We don't have one yet... if you're willing to wait some more, we can contribute it later on. For now we want to make sure that REST is supported.

**Comment by alukach** [comment]
For tracking purposes, the above mentioned PR is #1581.
