### ISSUE TITLE
Feature Request: link_error/link with chains

### ISSUE THREAD

**Issue by alexhayes** [celery/celery#1593]
I'm currently on Celery 3.0.24 and would like to perform the following:

``` python
(task1.s() | task2.s()).apply_async(link_error=notifysomeone.si('Oops, an error occured'))
```

If either `task1` or `task2` error I'd like `notifysomeone` to handle the error.

At the moment this behaviour seems achievable with:

``` python
t = notifysomeone.si('Oops, an error occured')
(task1.s().set(link_error=t) | task2.s().set(link_error=t)).apply_async()
```

However this seems a little verbose.

**Comment by loic** [comment]
@ask, should this behaviour be documented? I'm happy to write a patch if needed.

**Comment by ask** [comment]
@loic That would be great!

**Comment by itayB** [comment]
does this behaviour works for 3.1 as well?
