### ISSUE TITLE
Linking immutable tasks is not serilised

### ISSUE THREAD

**Issue by ibeex** [celery/celery#1601]
When trying to make chain tasks using `s = add.si(2, 2)` then `s.link(mul.si(4))` `...` calls first task and when first task is over all other tasks in chain are sent to workers, `chain` primitive works correct, all tasks are serilized. Celery 3.0.24

Here is demonstration code and log from worker.
http://pastie.org/8430868

**Comment by lyf2000** [comment]
Using with reduce:
```python
head = migrate_menu_task.s(ids[0])
reduce(
  lambda x, y: x.link(y),
  [head, *(migrate_menu_task.si(id) for id in ids[1:])],
)
head.apply_async()
```
