### ISSUE TITLE
Feature Request: Better syslog support for workers

### ISSUE THREAD

**Issue by Tinche** [celery/celery#1625]
As far as I can see, Celery currently supports logging to syslog by hooking a custom setup function into the after_setup_logger signal which then sets up a syslog handler (as described at http://oriolrius.cat/blog/2013/09/06/celery-logs-through-syslog/).

This is fine but is definitely not user friendly. Gunicorn would be a good example of comprehensive syslog support (command line arguments):
<pre>
--log-syslog
--log-syslog-to
--log-syslog-prefix
--log-syslog-facility
</pre>

There is precedent for improving logging support already: #321 :)

I'd be willing to give this a shot if I could get some support (through the mailing list maybe?)

**Comment by mpaolini** [comment]
Has this gone forward? I'd like to see this happening and I am willing to contribute. Just asking to make sure no one else is working on it...

**Comment by ask** [comment]
@mpaolini That would be awesome! No one is working on this AFAIK!

**Comment by dAnjou** [comment]
Where would one start implementing this? A little guidance would be nice.

**Comment by ask** [comment]
There are some suggested command-line arguments in the first post.
The worker program is implemented in celery/bin/worker.py, this handles command-line arguments
and setting things up from the command-line.  From there it's celery/apps/worker.py which is the application including setting up logging, environment signal handlers etc.  That again uses celery.worker.WorkController which is the actual worker.

All logging is set up in celery/app/log.py, which uses some utils in celery/utils/log.py

**Comment by dAnjou** [comment]
Thank you very much!

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://animalds.sk/servant.php?vqp9>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://sewakostumbandung.com/hundred.php?xp>

 

info@whywouldwe.com

**Comment by jirutka** [comment]
+1

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
