### ISSUE TITLE
--autoreload not working since 3.1, change to non-blocking inotify needed

### ISSUE THREAD

**Issue by AdrianLC** [celery/celery#1658]
The option is ignored because of the changes in autoreload.py from [this in 3.0](https://github.com/celery/celery/blob/3.0/celery/worker/autoreload.py#L55-L58)
to [the current code](https://github.com/celery/celery/blob/master/celery/worker/autoreload.py#L56-L57).

According to Ask, if we want this option available again, a patch is needed for:

* Changing the implementation, and use the non-blocking methods of pyinotify instead.
* Add the watcher to the event loop.

**Comment by squebe** [comment]
I wrote [this quick python script](https://gist.github.com/squebe/2270faa611ac647e2696) to unsafely reload celery on my development environment.  Celery is running in a docker container on a shared folder.  Its a temporary fix while developing, nothing else really seemed to work for me.  Hope it helps.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.  We will remove the docs for --autoreload and --autoscale in 4.0 (it will still be there, but no documented)

**Comment by alanhamlett** [comment]
At least put a note in the docs saying `--autoreload` doesn't actually work?

**Comment by ask** [comment]
I put that in my todo list like a year ago.  Currently I'm hard at work on Celery 4 which is nearly complete, and the option will be invisible, and undocumented in master very soon.

**Comment by xeor** [comment]
*bump* :)

```
~ # celery worker --autoreload                     
usage: celery worker [options]                     
celery: error: unrecognized arguments: --autoreload

~ # celery --version                               
4.1.0 (latentcall)                                 
```

**Comment by opyate** [comment]
For anyone landing here and doing local dev with Celery who'd still like auto reloads when making code changes:

Put this dependency in your build/Dockerfile/etc:
```
pip install watchdog
```

Then your compose.yml `command` changes to:

```
    command: >
      watchmedo auto-restart
      --directory=./whatever
      --patterns="*.py"
      --recursive
      -- celery -A whatever worker
```
