### ISSUE TITLE
Chord callback never fired with nested canvas objects

### ISSUE THREAD

**Issue by naftulikay** [celery/celery#1662]
**System Info**
Ubuntu 12.04, Celery 3.1.4, Redis 2.6.16

**Celery Configuration**

```
import djcelery
djcelery.setup_loader()

BROKER_URL = "amqp://guest:guest@localhost:5672/"

CELERY_DEFAULT_QUEUE = 'rtshiurim'
CELERY_RESULT_BACKEND = 'redis://'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_CHORD_PROPAGATES = False
```

I seem to have come across a chord callback deadlock across various result backends including the Django database backend, the Redis backend, and the MongoDB backend. (I have tried all three by commenting out the result backend, setting it to `redis://`, and setting it to `mongodb://`, respectively)
### Reproducing the Issue

I'm using some pretty simple tasks to reproduce the issue:

```
from time import sleep

import celery

@celery.task
def generate():
    sleep(1.0)
    print "Generate done!"
    return 'result'

@celery.task
def lower(result):
    sleep(1.0)
    print "Lower done!"
    return result.lower()

@celery.task
def upper(result):
    sleep(1.0)
    print "Upper done!"
    return result.upper()

@celery.task
def upload(result):
    sleep(1.0)
    print "Upload done for: %s!" % (result,)
    return 'upload'

@celery.task
def callback(results):
    print "It's all done! %s" % (results,)
```

To reproduce the issue, generate a chord like this:

```
from tasks import generate, lower, upper, upload, callback
from celery import chain, chord, group

chord(header=chain(
    generate.s(),
    group(
        chain(lower.s(), upload.s()),
        chain(upper.s(), upload.s())
    ), body=callback.s()
).delay()
```

When I run this, I see the following log output from my celery worker:

```
[2013-11-17 23:11:10,063: WARNING/Worker-8] Generate done!
[2013-11-17 23:11:11,103: WARNING/Worker-3] Lower done!
[2013-11-17 23:11:11,106: WARNING/Worker-8] Upper done!
[2013-11-17 23:11:12,128: WARNING/Worker-5] Upload done for: RESULT!
[2013-11-17 23:11:12,132: WARNING/Worker-8] Upload done for: result!
```

However, the `callback` task is never called. 

Again, I've tested this with the Redis, MongoDB, and Django database backends and can't seem to get the callback to run.

I assume that what's happening behind the scenes is that (in Redis' case), the counter is never properly decremented or incremented as the group tasks are finished. I assume that this is caused by `celery.result.GroupResult` not fully crawling the tasks for their children, but I'm not sure.

I'm looking into this one, but I'm still getting familiar with the Celery codebase. Can anyone else reproduce this issue?

**Comment by carolinux** [comment]
I also couldn't get the chord to execute properly, no matter what backend I used. So I cheated, I suppose by implementing the logic manually.

 I think chords are implemented internally the same way (with polling) at least for some backends. This code below now uses a group to execute the tasks, and when the group has finished, it executes the callback. Correct me if I'm wrong but I believe this is exactly what chords are.

```
   import time

   from celery import group

    tasks = [a list of celery task signatures] # this would be the actual chords
    ret = group(tasks).apply_async() 
    while(True):
        if ret.ready():
            # TODO: here should check for failure!
            results = [r.result for r in ret.results]
            inputs_to_callback = results
            # now I execute the callback task! :D
            return callback_task.s(inputs_to_callback, kwarg1=1, kwarg2="foo").apply() # this returns a celery.result.EagerResult
        time.sleep(2)
```
