### ISSUE TITLE
mingle: searching for neighbors

### ISSUE THREAD

**Issue by vpukhanov** [celery/celery#1664]
Hello.
I'm using djcelery and djkombu. When I'm starting celery like this  
    `python3 manage.py celeryd --loglevel=info`
or like this  
    `python3 manage.py celery worker --loglevel=info`

everything stops on this
    `[2013-11-18 19:27:22,624: INFO/MainProcess] mingle: searching for neighbors`

and this never ends.  

I'm using Lubuntu 13.10 with Python 3.3

**Comment by romanukyan** [comment]
@zebulon2 Same cause for me. Things are back to normal after freeing up space

**Comment by jason-kane** [comment]
ooh, just ran into this the issue was a rabbitmq partition.  One more thing to check if you see this symptom.
