### ISSUE TITLE
3.1.4, Substantial drift from celery

### ISSUE THREAD

**Issue by uschen** [celery/celery#1666]
There are two workers on two different servers which have different timezones (UTC and PT)

I tried different combines of celery configs for:

```
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
```

however, got exactly the same "substantial drift"

```
[2013-11-18 13:42:09,672: WARNING/MainProcess] Substantial drift from celery@worker1 may mean clocks are out of sync.  Current drift is
53998 seconds.  [orig: 2013-11-18 13:42:09.672848 recv: 2013-11-17 22:42:11.689954]
```

**Comment by speedplane** [comment]
I ran into this same issue. Running `sudo pip install --upgrade django-celery celery` seemed to fix it.
