### ISSUE TITLE
RabbitMQ Result BackEnd: PRECONDITION_FAILED - inequivalent arg 'x-expires'for queue

### ISSUE THREAD

**Issue by uschen** [celery/celery#1698]
try to task.get()
and got this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ENV/lib/python3.3/site-packages/celery/result.py", line 136, in get
    interval=interval)
  File "ENV/lib/python3.3/site-packages/celery/backends/amqp.py", line 152, in wait_for
    meta = self.consume(task_id, timeout=timeout)
  File "ENV/lib/python3.3/site-packages/celery/backends/amqp.py", line 221, in consume
    no_ack=True, accept=self.accept) as consumer:
  File "ENV/lib/python3.3/site-packages/kombu/messaging.py", line 357, in __init__
    self.revive(self.channel)
  File "ENV/lib/python3.3/site-packages/kombu/messaging.py", line 369, in revive
    self.declare()
  File "ENV/lib/python3.3/site-packages/kombu/messaging.py", line 379, in declare
    queue.declare()
  File "ENV/lib/python3.3/site-packages/kombu/entity.py", line 505, in declare
    self.queue_declare(nowait, passive=False)
  File "ENV/lib/python3.3/site-packages/kombu/entity.py", line 531, in queue_declare
    nowait=nowait)
  File "ENV/lib/python3.3/site-packages/amqp/channel.py", line 1250, in queue_declare
    (50, 11),  # Channel.queue_declare_ok
  File "ENV/lib/python3.3/site-packages/amqp/abstract_channel.py", line 75, in wait
    return self.dispatch_method(method_sig, args, content)
  File "ENV/lib/python3.3/site-packages/amqp/abstract_channel.py", line 93, in dispatch_method
    return amqp_method(self, args)
  File "ENV/lib/python3.3/site-packages/amqp/channel.py", line 232, in _close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-expires'for queue '0d8118c5bae241919a4d991ec65db1a8' in vhost 'cg': received the value '3600000' of type 'signedint' but current is the value '360000' of type 'signedint'
```

config:

```
BROKER_POOL_LIMIT = 10
CELERYD_FORCE_EXECV = True
CELERY_TASK_RESULT_EXPIRES = 360
CELERYD_POOL_RESTARTS = True
```

**Comment by gitaarik** [comment]
I'm getting this error now suddenly after upgrading from 3.x to 4.x. The error I'm getting is actually:

```amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'myqueuename' in vhost '/': received the value '10000' of type 'signedint' but current is none```

I don't understand what you mean with the clients and workers agreeing. I haven't set any custom settings for Celery. I have these packages installed:

```
celery==4.0.2
Django==1.10.5
django-celery-beat==1.0.1
django-celery-results==1.0.1
```

Why is this error happening exactly and how can I prevent it?

**Comment by gitaarik** [comment]
I tried setting `CELERY_TASK_RESULT_EXPIRES` to different values but it doesn't seem to make any difference.

**Comment by gitaarik** [comment]
Ok, I figured it out... It was because there was still a 3.1 worker running in another virtualenv. Once I stopped that one the worker in the virtualenv with Celery 4.0 didn't get this error anymore.

I'm wondering now if I need two worker processes anyway, probably not. It's for 2 different projects, which both have their own virtualenv, but maybe I should run celery workers in another separate virtualenv?

**Comment by gollapudirakesh** [comment]
hiiii

**Comment by radiantone** [comment]
Hi. I'm running into this. So what I can't understand is this. If a queue is already declared, and say has some value of x-expires. Why I can't just refer to that queue by name? Celery wants to re-declare it everywhere. If I have a "dumb" client that wants to do this, IT CAN'T

```
        sig = app.signature("my.task.name", args=args, queue="my.queue", kwargs=kwargs)
```
Celery insists that every client know in advanced how a queue was created. I just think this is not good. The attributes of the queue are not needed by a client wanting to put a task on a queue. The broker manages the queue, not the client. If it already exists. Then it already exists. Client need not try to re-declare it from scratch in my opinion.

**Comment by ives1227** [comment]
I realize this is old and closed but wanted to let you know that I discovered a solution for anyone banging their head.  You have to create a kombu.Queue instance and pass it the no_declare=True argument.  Then it won't try to recreate the queue.
`myqueue = Queue("my.queue", no_declare=True)`

In my case I was using Celery's send_task so it would look like this:
`app1.send_task("task.name", args=[], kwargs={},queue=myqueue)`

**Comment by auvipy** [comment]
> I realize this is old and closed but wanted to let you know that I discovered a solution for anyone banging their head. You have to create a kombu.Queue instance and pass it the no_declare=True argument. Then it won't try to recreate the queue. `myqueue = Queue("my.queue", no_declare=True)`
> 
> In my case I was using Celery's send_task so it would look like this: `app1.send_task("task.name", args=[], kwargs={},queue=myqueue)`

is there anything you want to contribute in celery about what you shared? like documentation or code example improvement?
