### ISSUE TITLE
After using AsyncResult.get(..) it seems to miss task state change

### ISSUE THREAD

**Issue by tenuki** [celery/celery#1699]
I'm trying to execute a task and get its output. Also I want to timeout only if the task is not yet started to execute (using `track_started=True`, I want to timeout only if task state is `PENDING`).

While trying to archive that, I found I can't get the task state in some cases. I reduced it to the minimal example in order to test it.

FYI: I'm using celery 3.0.24.

The task, in te.py:

```
@celery.task(track_started=True)
def new():
    print 'started..'
    time.sleep(3)
    new.update_state(state="PROGRESS")
    print 'progress..'
    time.sleep(3)
```

The tests:

```
UnaHora = 60*60

def _new(queue):
    #c = te.new.delay() # I need to use apply_async(..)
    c = te.new.apply_async(expires=UnaHora, queue=queue)
    r = None
    while not r=='SUCCESS':
        r = c.state
        print 'state: '+r
        time.sleep(0.4)
    print 'state: '+r
    sys.exit(-1)

def _new2(queue):
    c = te.new.apply_async(expires=UnaHora, queue=queue)
    while True:
        try:
            r = c.get(timeout=0.4)
            break
        except exceptions.TimeoutError, e:
            print 'state: ',c.state
    print 'state: ',c.state
    sys.exit(-1)

def _new3(queue):
    c = te.new.apply_async(expires=UnaHora, queue=queue)
    try:
        c.get(timeout=0.4)
    except:
        pass
    while not c.status=='SUCCESS':
        print 'state: '+c.status
        time.sleep(0.4)
    print 'state: '+c.status
    sys.exit(-1)
```

The output if you run the first test, _new(), is what we expect:

```
state: PENDING
state: STARTED
state: STARTED
state: STARTED
state: STARTED
state: STARTED
state: STARTED
state: STARTED
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: SUCCESS
```

The output if you run the second test, _new2(), is:

```
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: SUCCESS
```

And finally, the output for the third test, _new3() is:

```
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PENDING
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: PROGRESS
state: SUCCESS
```

I can't find any explanation for this, indeed it took to me a while to figure out it was not a `track_started=yes` failure..

ps: I'm using rabbitmq-server 3.1.3-1.

**Comment by koupass** [comment]
Hi,
I am using falcon and celery, I want to raise exceptions and pass it to the falcon reponce methode if celery queued job fails. my code is  the same as:


delete.apply_async((niam,DeleteAllocatedSpace,uid), queue='user_Q', countdown=2)

and the delete function is:
@app.task(track_started=True)
def delete(_iam,DeleteAllocatedSpace,uid):
#delete user
