### ISSUE TITLE
Docs not clear on distribution

### ISSUE THREAD

**Issue by quantoid** [celery/celery#1707]
The tutorials and other documentation don't really make it clear that workers can be on other hosts, remote from the ones invoking tasks. It's not obvious how execution on a task function gets to and from the remote host. Perhaps this is obvious to those already familiar with RabbitMQ, but since the word "distributed" is in the website title I reckon it's worth making it more obvious.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
