### ISSUE TITLE
Child worker process should send WORKER_UP message within 2 seconds

### ISSUE THREAD

**Issue by anti-social** [celery/celery#1715]
In our project we have global data which loaded in `Loader.on_worker_process_init` method. Sometimes it takes more than 2 seconds. In that case when child process dies `AsynPool` starts new one and then kills it.

There are many messages in logs:

```
Timed out waiting for UP message from <Worker(Worker-6, started daemon)>
```

Moving data loading into `worker_process_init` signal handler doesn't help.
Now I moved loading data into `Loader.on_task_init`.

Maybe there should be option or setting which could set `AsynPool._proc_alive_timeout` attribute?
Or perhaps add information in docs that `worker_process_init` signal and `Loader.on_worker_process_init` should be executed within 2 seconds.

**Comment by bryanhelmig** [comment]
We hit this too @ask - it might be pretty handy to have this as a configuration option. Lots of head scratching as a result...

**Comment by kotrakrishna** [comment]
@oppianmatt  Thanks for the monkey patch script.

**Comment by jpays** [comment]
In case someone is still having that kind of problem, you can upgrade to 4.4.2 and use the new configuration option "worker_proc_alive_timeout" to increase init timeout.

**Comment by michaelosthege** [comment]
It looks like `worker_proc_alive_timeout` does not affect the AsynPool? maybe I'm missing something, but according to [the search results](https://github.com/search?q=repo%3Acelery%2Fcelery%20worker_proc_alive_timeout&type=code) there's no code linking `proc_alive_timeout` to [the `PROC_ALIVE_TIMEOUT` constant](https://github.com/celery/celery/blob/55c9fc0a0a34e86eada71bdec0fa420714c63d8d/celery/concurrency/asynpool.py#L75) that was monkeypatched in the comment above.

This was not [our actual issue (in the context of an Apache Airflow Celery setup)](https://github.com/apache/airflow/pull/58869#issuecomment-3818650321), but I think my comment is still valid.

**Comment by auvipy** [comment]
> It looks like `worker_proc_alive_timeout` does not affect the AsynPool? maybe I'm missing something, but according to [the search results](https://github.com/search?q=repo%3Acelery%2Fcelery%20worker_proc_alive_timeout&type=code) there's no code linking `proc_alive_timeout` to [the `PROC_ALIVE_TIMEOUT` constant](https://github.com/celery/celery/blob/55c9fc0a0a34e86eada71bdec0fa420714c63d8d/celery/concurrency/asynpool.py#L75) that was monkeypatched in the comment above.
> 
> This was not [our actual issue (in the context of an Apache Airflow Celery setup)](https://github.com/apache/airflow/pull/58869#issuecomment-3818650321), but I think my comment is still valid.

Interested to know more here. if you have time to dig more?

**Comment by michaelosthege** [comment]
> Interested to know more here. if you have time to dig more?

sorry, we lost a whole day debugging already.
