### ISSUE TITLE
gevent + requests.get sometimes stuck indefinitely with soft time limit

### ISSUE THREAD

**Issue by idank** [celery/celery#1754]
I'm using gevent with a pool of size 50 with a pretty simple task:

``` python
@celery.task
def check(url):
  try:
    return requests.get(url, allow_redirects=True, timeout=30, verify=False).status_code == requests.codes['ok']
  except:
    return False
```

Every now and then some tasks will get stuck indefinitely, presumably because of slow/unresponsive web servers. I can't seem to reproduce it on a particular url, but when sending 10k+ tasks, around 5 will get stuck.

I tried turning on soft timeout limits in my config, but these hangs seem immune to them.

I did manage to get a bunch of stacktraces from the workers' greenlets, see this gist https://gist.github.com/idank/8069444, the interesting ones are those that include the `check` function. On this particular run, two got stuck.

So after all that said, I'm not sure all of this is Celery's fault, except the soft timeout not being enforced. The timeout param passed into requests.get is also being mysteriously ignored, so it's possibly related to how Celery spawns greenlets? Beats me. It might be worth trying to reproduce this with grequests to see if the timeout param is always enforced there.

**Comment by jaddison** [comment]
I'm not one to poke sleeping dogs, but I've run into this a couple of times recently. Using redis as broker, gevent as the pool manager.  Running everything in supervisord.

Versions:
```
python 2.7.6

amqp==1.4.6
billiard==3.3.0.19
celery==3.1.17
django-celery==3.1.16
django-redis==3.8.3
gevent==1.0.1
greenlet==0.4.5
kombu==3.0.24
redis==2.10.3
```

It may or may not be related, but I've also recently started using the HUP signal to restart the workers - maybe this is what randomly puts things in a 'hangable' state?

Once it gets into the hanged state, restarting supervisord ensures both gunicorn and celery restart successfully and celery picks up where it left off it seems.
