### ISSUE TITLE
No more @periodic_task decorators?

### ISSUE THREAD

**Issue by yuvadm** [celery/celery#1764]
In a Django application, it's possible to define app-specific tasks with decorators, but all `periodic_task` decorators seem to have been removed.

``` python
# proj/app/tasks.py
from proj.celery import app

@app.task
def my_task():
    pass

# why no @app.periodic_task?
def my_periodic_task():
    pass
```

This used to be possible using `from celery.task import periodic_task` but seems to be deprecated. Why is this? Isn't there an elegant way to define periodic_tasks without manually updating the `CELERYBEAT_SCHEDULE`?

**Comment by stuaxo** [comment]
Hi,
    Has the new API been implemented ?
    I have large amounts of legacy tasks from another system, where the schedule is embedded in their source.

S

**Comment by stuaxo** [comment]
Ignore this, the version I have still seems to have it.

**Comment by belgacea** [comment]
Maybe not elegant but functionnal and testable..
