### ISSUE TITLE
Recommend using a virtualenv for installing dependencies when contributing

### ISSUE THREAD

**Issue by bsdlp** [celery/celery#1783]
In the documentation, it is noted that there are Python package dependencies for tools related to contributing to Celery.

Instead of installing these dependencies system-wide, is it a better idea to have a brief explanation of virtualenv and recommend using it?

For example, packages related to tests:

http://docs.celeryproject.org/en/master/contributing.html#running-the-unit-test-suite

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.  Please submit a patch if you can.
