### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by reclosedev** [celery/celery#1800]
[Redis-py v2.9.0](https://pypi.python.org/pypi/redis/) introduced [Redis Sentinel](http://redis.io/topics/sentinel) support. 

I wrote basic transport and backend for it, as a workaround: https://gist.github.com/reclosedev/8460004

``` python
from utils.celery_sentinel import register_celery_alias
register_celery_alias()
...
redis_url = 'redis-sentinel://'
celery = Celery(..., broker=redis_url, backend=redis_url)
celery.conf.update(
    CELERY_REDIS_SENTINEL_SENTINELS=...,
    CELERY_REDIS_SENTINEL_SERVICE_NAME=...,
    CELERY_REDIS_SENTINEL_SOCKET_TIMEOUT=...,
    CELERY_REDIS_SENTINEL_SENTINEL_TIMEOUT=...,
    BROKER_TRANSPORT_OPTIONS={
        'service_name': ...,
        'sentinels': ...,
        'sentinel_timeout': ...,
        'socket_timeout': ...,
    }
)
```

I could make pull request (without `register_celery_alias()` hack) to this repository and kombu, but not sure if it's proper way to implement backend and transport. Also, I don't know how to cover it with tests.

**Comment by jbisbee** [comment]
@ask, I see this bug was closed, but was it ever addressed?  Getting ready to hook in the gist above but wanted to see if sentinel support was ever supported with BROKER_TRANSPORT_OPTIONS as suggested?

**Comment by brouberol** [comment]
Is there any plan to officially support redis sentinels in celery or kombu? That'd truly be an awesome feature.

**Comment by fgimian** [comment]
Huge +1 from me, would really like to see this in celery :smile:

**Comment by brouberol** [comment]
I'm willing to properly implement this into celery to get things moving. @ask, would you mind giving me pointers about how you would like this to be done? If not, I'll start anyway, and we'll see if that suits you.

**Comment by jbisbee** [comment]
@brouberol/@ask - Working on putting in the [celery_sentinel.py gist](https://gist.github.com/reclosedev/8460004) into action now as I need sentinel support for my worker pool.  Post updates here if you can or I can follow your forked project.

**Comment by jbisbee** [comment]
The above gist is wrong in how is creates an Sentinel instance  

In gist

    sentinel = Sentinel(self.sentinels, self.password, self.sentinel_timeout, self.min_other_sentinels)

From redis/sentinel.py (class Sentinel)

    def __init__(self, sentinels, min_other_sentinels=0, sentinel_kwargs=None,
                 **connection_kwargs):

Also I can't find any reference to self.sentinel_timeout, only self.socket_timeout.  Even after grepping   all my local install of redis.py, so I'm removing it.

**Comment by brouberol** [comment]
I have been looking at Kombu (without too much time to dive, nor success
I might add). Adding redis+sentinel as a backend has to be done at the
celery level, but AFAIU, the redis+sentinel transport must be
implemented in kombu.

I'll look some more into it, but if anyone familiar with the kombu
codebase could give me general pointers, that'd be of immense help.

--
B


On Thu, Apr 16, 2015, at 05:54 AM, Jeff Bisbee wrote:
> The above gist is wrong in how is creates an Sentinel instance


> In gist


> sentinel = Sentinel(self.sentinels, self.password,
> self.sentinel_timeout, self.min_other_sentinels)
>
> From redis/sentinel.py (class Sentinel)


> def __init__(self, sentinels, min_other_sentinels=0,
> sentinel_kwargs=None,
             **connection_kwargs):
>
> Also I can't find any reference to self.sentinel_timeout, only
> self.socket_timeout. Even after grepping all my local install of
> redis.py, so I'm removing it.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/celery/celery/issues/1800#issuecomment-93632060

**Comment by reclosedev** [comment]
@jbisbee I've updated gist to current version.

**Comment by jbisbee** [comment]
@reclosedev I don't see mention of sentinel_timeout (looked high and low).  Can you link to the in within the [redis.py](https://github.com/andymccurdy/redis-py) github project?  Didn't see anything in the docs or the code to support the parameter and just curious as to how I missed it.

Also, thank you very much for the updated gist.  I'm sure others who stumble upon this old post will thank you as well :+1:

**Comment by reclosedev** [comment]
@jbisbee
``sentinel_timeout`` is passed to ``Sentinel`` ``sentinel_kwargs`` ``socket_timeout``
https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py#L158-L162
https://gist.github.com/reclosedev/8460004#file-celery_sentinel-py-L43
https://gist.github.com/reclosedev/8460004#file-celery_sentinel-py-L65

So 
CELERY_REDIS_SENTINEL_SENTINEL_TIMEOUT - timeout for sentinel client, which queries current master and slaves.
CELERY_REDIS_SENTINEL_SOCKET_TIMEOUT - timeout for redis client, which executes real commands.

**Comment by jim-bo** [comment]
Any plans on merging this to master?

**Comment by brouberol** [comment]
To be honest, I did not take the time to address this issue, as I initially wanted to.

**Comment by jim-bo** [comment]
Gotya. I'm still working on getting the gist to work. I keep getting a no-attribute error "AttributeError: 'SentinelChannel' object has no attribute 'sentinels'" when starting up the celery application. If i'm able to work through the issues and stress the sentinel operations I may be able to try and finalize the patches to kombu and celery. I wanna make sure it really is giving us High Availability before I try and pretty it up.

**Comment by miki725** [comment]
In case others are still looking for a solution, @dealertrack just open-sourced a library which adds support for both a broker and results backend. Source is at https://github.com/dealertrack/celery-redis-sentinel and docs are at http://celery-redis-sentinel.readthedocs.org/en/latest/. Any feedback will be appreciated.

Also would like to express thanks to @ask. His answers in IRC were very helpful in understanding how celery works while creating the lib.

Im not too familiar with the celery internals and this was my first stab however if the implementation is any decent, we would not mind opening up a PR to celery itself. Would that be something useful to the community?

**Comment by ask** [comment]
@miki725 Thank you for the kind words, and great work!  It definitely sounds like something that can be part of the library

**Comment by xavierhardy** [comment]
any news, please? The PR has been stuck for a while. :(

**Comment by xavierhardy** [comment]
OK, I guess we can close this as it is supported since 4.0
http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#redis-support-for-sentinel
