### ISSUE TITLE
Redis: group should use a pipeline when apply_async'ing subtasks

### ISSUE THREAD

**Issue by idank** [celery/celery#1803]
Enqueuing a few hundred (not to mention thousands and more) initiates a redis command per task in the group which can cause significant overhead, sometimes making the entire apply_async take in the order of minutes. Using a redis pipeline can greatly improve performance here.

Doing the enqueue in another celery task in the background isn't really the solution because that also has significant overhead due to serializing the arguments of each subtask (again), and it only moves the problem to a different queue/worker.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
