### ISSUE TITLE
ETA tasks lost with redis

### ISSUE THREAD

**Issue by scott-coates** [celery/celery#1810]
I've been trying for a couple of weeks to fix this issue I'm getting where eta tasks are being intermittently dropped.

```
software -> celery:3.1.8 (Cipater) kombu:3.0.10 py:2.7.4
            billiard:3.3.0.14 py-amqp:1.4.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

I'm using redis for the transport.

I've narrowed it down and can reproduce it. When I open up flower, I see several (20+) tasks scheduled. On Heroku, I issue the `SIGTERM` command and the worker begins to shutdown. If I issue this shutdown while tasks are still running, then the issue will arrise. 

Upon booting up the worker, I can go into flower and will see 0 (or a few) of my eta tasks. I believe these scheduled tasks which reside in the `unacked` HASH are never successfully written to the `celery` HASH in redis.

I am sure the redis instance is not going down abruptly. I am using RedisLive to monitor it and it has been up for several days. Similarily, I'm sure Heroku is not going down or running out of memory.

Going through the code, I believe this is an issue with kombu retrieving the tasks from `unacked` and celery not putting them back into `celery`.

**Comment by morrissimo** [comment]
Saw this behavior today:
 1. task enqueued with countdown=30:
```python
my_task.apply_async((arg1, arg2, arg3), countdown=30)
```
 2. celery restart issued
 3. task never runs :/

Versions and settings:
* celery 3.1.11
* django 1.6.11
* redis 2.8.19 (on AWS ElastiCache)
* celery settings:
```
CELERY_ACKS_LATE = True
CELERY_RESULT_BACKEND = <redis_url>
BROKER_URL = <redis_url>
BROKER_TRANSPORT_OPTIONS = {'fanout_prefix': True}
CELERYD_HIJACK_ROOT_LOGGER = False
CELERYD_TASK_TIME_LIMIT = 300 
CELERYD_SOFT_TASK_TIME_LIMIT = 250  # Keep this less than the hard limit
CELERY_ALWAYS_EAGER = True
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
CELERY_SEND_TASK_ERROR_EMAILS = True
```

Those commenters that switched to RabbitMQ: was that the only change you made to address this issue? Have you seen any more occurrences since you made that switch?

**Comment by safwanebrahim** [comment]
@ask i got the same issue. During a task run when i restart worker (TERM signal), all the eta set tasks are lost but the started task will complete execution.

@jessepollak  Moving to RabbitMQ would solve our issue?

**Comment by ask** [comment]
@safwanebrahim what version are you on?  Worker shutdown logs? Configuration?  Does it happen consistently?

**Comment by safwanebrahim** [comment]
i use 3.1.18 (Cipater). yea it happens consistently. Please check https://github.com/celery/kombu/issues/533 for more details

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by scythargon** [comment]
Still happens in 2019

**Comment by jheld** [comment]
Specifically that the task still remains in the unacked set?

**Comment by arpansharma** [comment]
Still happens in 2021

**Comment by auvipy** [comment]
you can also try to help fix the issue

**Comment by torotil** [comment]
I have provided a test case in https://github.com/celery/kombu/issues/533

**Comment by Nusnus** [comment]
Celery v5.5 has a new soft shutdown feature and a new flag `worker_enable_soft_shutdown_on_idle`, which helps mitigate this issue with Redis (and SQS) by adding a short window before the cold shutdown terminates the worker to finish handling the worker teardown gracefully. It’s not an ideal solution, but it helps eliminate the problem in most cases.

- [Soft Shutdown PR](https://github.com/celery/celery/pull/9213)
- [worker_enable_soft_shutdown_on_idle PR](https://github.com/celery/celery/pull/9231)
- Documentation: [Feature](https://docs.celeryq.dev/en/latest/userguide/workers.html#stopping-the-worker), [Flags](https://docs.celeryq.dev/en/latest/userguide/configuration.html#worker-soft-shutdown-timeout)
