### ISSUE TITLE
Get celery task id before calling `delay`

### ISSUE THREAD

**Issue by myisis** [celery/celery#1813]
In my application, I use a table to keep track and store additional information of launched tasks (call it application task table). In some cases, I need the ID of the created application task record in the actual celery task. The problem is that this application task record is only created once the task is launched (because the celery task id is part of the application task ID record) and that it'll be hard to pass in the task ID into a running task.

In essence, I need the celery task id to create the application task record, and I need the application task id to create the celery task.

Is there any robust way of resolving this chicken-and-egg problem? One way I can think of is to stop the execution somehow until I created the application task record (in the caller of `task_function.delay()`), but I can't think of a way to do this with celery out of the box or how to pass the application task id to the task.

Any thoughts, pointers, hints on that? - Thanks a lot!

**Comment by kevlarr** [comment]
I know this is old, but it was awesome to see that I wasn't the only one with a use case like this - and also awesome to see several (good) solutions!
