### ISSUE TITLE
[Feature] Celery should warn when rabbitmq has run out of resources

### ISSUE THREAD

**Issue by zebulon2** [celery/celery#1828]
I gather this is not celery's problem, but it could be nice that when celery starts, it notifies the user with rabbitmq error messages, such as disk free space limit issues. In example, if rabbitmq has under 1GB of free filesystem (by default), then it does not passes messages anymore to celery, and it may be a difficult one to debug for the user. Is it possible to have this?

PS: there is a feature in RabbitMQ that allows the client to be notified of message blocking when resources are too low, as explained here: http://www.rabbitmq.com/connection-blocked.html Is it something Celery could take advantage of?

**Comment by mdomans** [comment]
@ask This is actually a very serious problem I'm having to deal with. I'm actually interested is there any plan of changes that need to be made or a github issue for that particular change for kombu?

**Comment by thedrow** [comment]
Not currently. We'd rather track and resolve crashes first.
If you can spend the time figuring out how to implement this feature, then by all means please do.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.  We may revisit at the point when py-amqp is rewritten to use asyncio.
