### ISSUE TITLE
Celery worker over SSL

### ISSUE THREAD

**Issue by jonathanlabanca** [celery/celery#1859]
Hi there, 

Several days ago I try to configure a celery worker running under SSL with a self-signed certificate. The broker that I using is RabbitMQ and try debugging all configurations without receiving errors in the certificate or in the configuration. 

I configuring my worker without ssl and tasks are processed smoothly, but reactivating celery with ssl are not be processed again. 

After various tests, a few hours ago can resolve the problem by adding the parameter "- without-mingle" to my startup script. 

The line ran in both cases (with SSL and without SSL) was as follows:

/usr/bin/celery worker -A project -B -E -l DEBUG --uid=celery --gid=celery --workdir=/usr/local/celery/ --pidfile=/var/run/celery/%n.pid --logfile=/var/log/celery/%n.log 

Currently executed following to operate under SSL:

/usr/bin/celery worker -A project -B -E -l DEBUG --uid=celery --gid=celery --workdir=/usr/local/celery/ --pidfile=/var/run/celery/%n.pid --logfile=/var/log/celery/%n.log --without-mingle

Have any idea that can generate this problem?
Regards.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
