### ISSUE TITLE
request.headers not available when tasks are run eagerly

### ISSUE THREAD

**Issue by scheler** [celery/celery#1874]
Hi,
request.headers not available when tasks are run eagerly. Looking at the "apply" method at https://github.com/celery/celery/blob/master/celery/app/task.py it looks like this because "headers" is not a supported key.  Is this done on purpose or can "headers" be made available too?

thanks.

**Comment by charlax** [comment]
Looks like this regressed. I'm having the same issue with 3.1.17 and 3.1.19.

**Comment by ask** [comment]
Do you have an example? Because it works for me here
