### ISSUE TITLE
ResultSet.add() doesn't work

### ISSUE THREAD

**Issue by amuzeev** [celery/celery#1883]
I try to add AsyncResult object to GroupResult and I get Exception.

Code:

job = group([task1, task2])
result = job.apply_async()
result.save()

task_id = task3.apply_async()
r = task3.AsyncResult(task_id)

result.add(r)

Traceback:

File "XXXXXXXXXXXXXXXX/lib/python2.7/site-packages/celery/result.py", line 376, in add
    self.results.append(result)
AttributeError: 'tuple' object has no attribute 'append'

**Comment by inoks** [comment]
As pointed in [docs](http://docs.celeryproject.org/en/v4.0.0/reference/celery.result.html#celery.result.GroupResult):
> Like ResultSet, but with an associated id.

So expected behavior for me is to behave same way as `ResultSet` with extra functionality of saving/restoring result.
