### ISSUE TITLE
Should map and starmap be renamed?

### ISSUE THREAD

**Issue by budlight** [celery/celery#1887]
I don't really think these 2 primitives really live up to what it seems they should imply in the context of a "distributed task queue".  I understand the reason why someone might want the map and starmap functions since they create a single task, but I don't really get the advantage to them as it would be trivial for the user to write the function to simply support a list of inputs.  To me the term "map" here implies something like a map-reduce algorithm which this is definitely not.  A chord is effectively a form of map-reduce which really just makes the naming boggling. 

I think the naming of chord should stick as it makes enough since, but having map and starmap alludes that there is a map-reduce function IMO.  

http://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers

**Comment by tim-schilling** [comment]
Except that ```task.map(list)``` doesn't allow the tasks to run concurrently. All of the tasks run on the same worker one after another. If this shouldn't be the case I can open up a new issue.
