### ISSUE TITLE
ability to change ignore_result when calling tasks?

### ISSUE THREAD

**Issue by uschen** [celery/celery#1904]
can we change the `ignore_result` property of a task when calling the task (apply_async)? like:

```
@celery.task(ignore_result=True)
def mytask(a, b):
  return 'something'
```

```
mytask.apply_async(1,2, ignore_result=False)
```

**Comment by Chive** [comment]
@ionelmc using ``Ignore`` would mean that the task status would also not be updated which is kinda like a side effect of wanting to ignore it's result. :+1: to add this feature to the core.

**Comment by vgavro** [comment]
I think for more clean API this should be included to apply_async options. Found this ticket after assumption that this should work (before looking in celery source).

**Comment by TimDumol** [comment]
For future readers: I think this has been addressed in https://github.com/celery/celery/pull/4709

**Comment by TimDumol** [comment]
For future readers: I think this has been addressed in https://github.com/celery/celery/pull/4709

**Comment by TimDumol** [comment]
For future readers: I think this has been addressed in https://github.com/celery/celery/pull/4709
