### ISSUE TITLE
Documentation: Please provide more, complete code examples

### ISSUE THREAD

**Issue by DoOaf2SrUS9L6** [celery/celery#1910]
I'm new to both Python and Celery (but not to programming) and I'm interested in using Celery 3.1 to distribute work across a bunch of worker nodes.

I've struggled the last week with getting a grasp of Celery and I've read everything I've come over on Google, including the available online documentation (which is fairly extensive for an open source project I must say -- great work!)

Unfortunately I'm having a hard time to find good examples with _complete_ code.  Most examples I've found, both in the official documentation and on various Slideshares, are mostly code snippets or stuff that's run from the Python interpreter.  Additionally, the internet seems to lack creativity and there's very few examples of actual code -- most things you find while googling are "blogspam" where people have copied the "add two numbers" thing from the official documentation and added their own often-not-so-great explaination around it.

What I feel lacking in the official documentation are more complete examples that includes filenames, directory layouts, better naming and explaination of conventions.  More of what's already available in the *Next steps* in the online docs.

On Google I've found presentations where they used the Task class to create subclasses, something that's also mentioned in the official documentation [http://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-task-classes].  I'd be happy to see a complete example where this is actually used.

Finally, since Celery brands itself as a distributed task queue it would be nice with more extensive examples of how to implement a simple client/director and worker/actor with working code and running (i.e, terminal output) examples of both the *client* and the *worker*.

Thanks for listening.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
