### ISSUE TITLE
-Ofair doesn't disable prefetching

### ISSUE THREAD

**Issue by frasergraham** [celery/celery#1933]
The docs for 3.1 claim:

"You can disable this prefetching behavior by enabling the -Ofair worker option:

```
$ celery -A proj worker -l info -Ofair
```

With this option enabled the worker will only write to workers that are available for work, disabling the prefetch behavior."

but when I use that option I still get tasks pre-fetched to my workers, the prefetching problem that can occur with tasks that can take a long time to run as described in that section of the documentation is still plaguing me. 

Is there really no way to disable prefetching entirely?

**Comment by wolever** [comment]
I've run some experiments, and at least with the Redis broker, neither `-Ofair` nor `CELERYD_PREFETCH_MULTIPLIER = 1`.

To demonstrate this:

1. Set `CELERYD_PREFETCH_MULTIPLIER = 1`
1. Queue up 5 tasks that will each take a few seconds (ex, `time.sleep(5)`)
2. Start watching the length of the task queue in Redis: `watch redis-cli -c llen default`
4. Start `celery worker -c 1 -Ofair`
5. Notice that the queue length in Redis will immediately drop from `5` to `3`

The worker is *definitely* prefetching one task.

**Comment by Cediddi** [comment]
I'm also having the exact issue @wolever 's having. Could you solve your issue David, if so, how did you solve it?

**Comment by codingjoe** [comment]
Same here

**Comment by Cediddi** [comment]
Seems like 4.0 does solve this issue. I'm on rc7 and the default behavior is really -Ofair.

**Comment by codingjoe** [comment]
There actually wasn't an issue with version 3 ether. It is the ETA tasks as a worker needs to increase the time counter. So the first worker who's up will usually consume all eta tasks and count them.
