### ISSUE TITLE
celery on gevent ignores soft and/or hard timeout

### ISSUE THREAD

**Issue by tbg** [celery/celery#1958]
On gevent, the soft time limit seems to be ignored. Sometimes even the hard one! The examples are pretty basic but I didn't find anything on the internet and in the docs it says the gevent worker pool is supported for the soft and hard timeouts.

Before I go on, this is always run with the gevent worker. Using the default worker, everything is as expected.
Config:
CELERYD_TASK_TIME_LIMIT = 30,
CELERYD_TASK_SOFT_TIME_LIMIT = 20,
software -> celery:3.1.9 (Cipater) kombu:3.0.14 py:2.7.3
            billiard:3.3.0.16 py-amqp:1.4.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Task #1:

```
@shared_task(ignore_result=False)
 def ping():
     while True:
         print "x"
         time.sleep(1)
```

Outcome: gets killed with the hard limit, ignoring the soft limit.

Task #2: just remove the "time.sleep" from Task #1.
Will run forever, ignoring both time limits.

I'm assuming that happens because there's never a context switch from the active greenlet in the second case (time gets monkey patched, I think). So there's never an entry point for the hard timeout to kick in. I'm wondering though why the soft timeout is not triggered in the first case? Is it perhaps triggered, but the exception doesn't get where it's supposed to?

Appreciate any feedback on this, and in particular on what works and doesn't with gevent.

Thanks,
Tobias

**Comment by deeTEEcee** [comment]
Unless I'm reading the docs wrong, http://docs.celeryproject.org/en/latest/userguide/workers.html says otherwise. Under "Time Limits", pool support: prefork/gevent is written. If that's not the case for soft, we should probably indicate that.

**Comment by zhangchenchen** [comment]
Approved, this is not cool. the docs mislead me, i waste hours reading the source code.

**Comment by auvipy** [comment]
can anyone send a pr for docs improvement?

**Comment by CedoAlteram** [comment]
The easiest way to do this is to override the hard timeouts for use with the gevent pool. Otherwise, your jobs might just terminate and nothing happens to them. This at least gives you some control over what happens to those terminated jobs. 

`class MyRequest(Request):
    def on_timeout(self, soft, timeout):
        super(MyRequest, self).on_timeout(soft, timeout)
        if not soft:
           logger.warning(
               'A hard timeout was enforced for task %s',
               self.task.name
           )


class MyTask(Task):
    Request = MyRequest  # you can use a FQN 'my.package:MyRequest'

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print('{0!r} failed: {1!r}'.format(task_id, exc))


def run_time_job():
    a = random.randrange(0, 20)
    print('sleeping for', a)
    time.sleep(a)


@app.task(base=MyTask, soft_time_limit=5, time_limit=10)
def add(x, y):
    results = None
    try:
        run_time_job()
        results = x + y
    except SoftTimeLimitExceeded:
        print('time limit exceeded')
        redis_db.sadd('failed_jobs', 'failed at {} + {}'.format(x, y))
    except TimeLimitExceeded:
        raise KeyError()
    return results`

This is especially important as soft timeouts with the gevent pool wont catch the soft timeout exception.
