### ISSUE TITLE
Document and Test SSL Support to MongoDB Result Backend

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#1974]
SSL support *should* work for MongoDB, but it is not documented or tested.  The [MongoDB results backend](https://github.com/celery/celery/blob/master/celery/backends/mongodb.py) uses PyMongo underneath which seems able to handle SSL; it should be as simple as docs and testing that need to be put in place.  This feature-request outlines an approach to get this working.

PyMongo expects options set as key/value pairs [as shown here](http://api.mongodb.org/python/current/examples/authentication.html#mongodb-x509).  The options portion of the [CELERY_MONGODB_BACKEND_SETTINGS](http://celery.readthedocs.org/en/latest/configuration.html#celery-mongodb-backend-settings) Celery option should allow the correct options to be set allowing this to be configured with no code changes.

1.  Documentation needs to be written [here](http://celery.readthedocs.org/en/latest/configuration.html#mongodb-backend-settings) indicating that SSL works, and show an example here.

2.  Testing needs to be done using the documented example.

3.  Unit tests should be written to ensure that if those options are set correctly, that they are passed through correctly to the PyMongo constructor.

**Comment by ask** [comment]
Please open a pull request if you want to work with it, but we have way too many issues open, and MongoDB is not even officially supported at this point :(

**Comment by bmbouter** [comment]
This specific issues isn't very important, but let me present a case for why bugs like this should not be closed. Pulp currently has [956 open issues](https://pulp.plan.io/issues). It's tempting to close the ones we won't get to soon (or maybe ever) because it can be overwhelming, but closing them doesn't change the fact that it is an issue. Someone in the community might fix it. Perhaps users will look at open bugs and make decisions for what they will use? Maybe future development decisions will be guided by the bug counts for different components. There is nothing wrong with a large bug list. In fact it's a good thing because it means that a project has problems but they are known problems. Knowing about problems is a much better situation than using software and thinking it has no problems when it really does.

This isn't isn't important enough for the time it took to write this, but more generally for discussion about Celery/Kombu bugs overall. In the broader sense, what do you think about these ideas?

I didn't know the MongoDB results backend wasn't officially supported. I didn't see a note to that effect in the docs. Maybe I overlooked it. Can you point me at it? We've been using it in production so to hear that it's not officially supported after we've deployed it is scary.

**Comment by ask** [comment]
>I didn't know the MongoDB results backend wasn't officially supported. I didn't see a note to that effect >in the docs. Maybe I overlooked it. Can you point me at it? We've been using it in production so to hear >that it's not officially supported after we've deployed it is scary.

See the top warning here: http://docs.celeryproject.org/en/latest/getting-started/brokers/mongodb.html
http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html
middle of preface: (`Note that I have also moved many broker transports into experimental status:...`)
http://docs.celeryproject.org/en/latest/whatsnew-3.1.html#preface

@daevaorn and others fixed a lot of mongodb issues so the situation is a bit better since then, but 
it's still using the fallback thread-based worker, which means deadlocks will happen if worker child processes are killed.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
