### ISSUE TITLE
update_state fails when calling tasks synchronously

### ISSUE THREAD

**Issue by kevcampb** [celery/celery#1977]
Calling a task directly via the call method is supposed to be supported, see

http://celery.readthedocs.org/en/latest/userguide/calling.html

```
calling (__call__)

Applying an object supporting the calling API (e.g. add(2, 2)) means that the task will be executed in the current process, and not by a worker (a message will not be sent).
```

However, if that task uses update_state to record the task progress

```
  File "analysis/tasks.py", line 155, in test_classifier
    self.update_state(state='PROGRESS', meta={'log_so_far': getTranscript()})
```

It will then result in an exception being raised

```
  File "python2.7/site-packages/celery/backends/base.py", line 364, in get_key_for_task
    return self.task_keyprefix + self.key_t(task_id)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This isn't an issue if we use delay()

**Comment by claytondaley** [comment]
I 100% agree in principle, but not necessarily in practice.  I'm using 3rd party code that has a `@shared_task` that calls `current_task.update_state`.  If this were my code I'd simply redesign it.  Unfortunately, the preexisting code is out of my control.

It seems to me that there should be a simple way to avoid this error.

**Comment by claytondaley** [comment]
In similar situations, [fabric](http://www.fabfile.org/) would use a [context manager](http://docs.fabfile.org/en/1.14/api/core/context_managers.html).  For example:

```
with celery.tasks.no_updates():
    3rd_party_task()
```

I haven't looked at the `fabric` implementation to see if it requires something architectural (like a centralized settings class that propagates context) or something simple/local.
