### ISSUE TITLE
celery still fills celeryev even when CELERY_SEND_EVENTS = False

### ISSUE THREAD

**Issue by jamesonjlee** [celery/celery#2005]
I upgraded from 3.0.24 to 3.1.11 and I noticed on RabbitMQ 3.3.0, Erlang R14B04 a slew of Delivery (noack) showing up.

I noticed that with about 30 workers, I had about 500/s being sent and consumed on celeryev. Setting `CELERY_SEND_EVENTS = False` didn't turn off the celeryev being overrun.

I played around and noticed the rates were around:
10 workers -> 6/s per worker
20 workers -> 12/s per worker
30 workers -> 16/s per worker
50 workers -> 20/s per worker

I dug in the code and found https://github.com/celery/celery/blob/master/celery/worker/consumer.py#L499 where it's always set to true.

git blame showed before 3.1.0 it was `self.send_events = send_events` but was set to true (for Gossip?).  Shouldn't it still be inheriting from CELERY_SEND_EVENTS? or am I understanding what celeryev is suppose to be used for incorrectly?

**Comment by chrono** [comment]
It was fun to see our production celery rabbit suddenly push 10k messages per second (running about 140 workers). Quite some gossip.
