### ISSUE TITLE
init script uses su, and this is causes issues for logind Linux systems

### ISSUE THREAD

**Issue by CameronNemo** [celery/celery#2042]
Using su to set credentials has the negative side effect of creating a full blown logind session on systems that have systemd-logind installed (read: Debian Jessie, Arch, Fedora, some Gentoo, RHEL 7, Ubuntu 13.04+). This can cause major issues, including the inhibition of suspend and possibly even shutdown. Something like start-stop-daemon can be used instead, but that is not portable, unfortunately.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.  I guess upstream package authors should be responsible for init scripts.
