### ISSUE TITLE
Batches tasks do not call callbaks

### ISSUE THREAD

**Issue by bmampaey** [celery/celery#2062]
When calling a batch task with apply_async, and passing another task as callback, the callback never gets called.

```
from __future__ import absolute_import
from celery import Celery
from celery.contrib.batches import Batches
from celery.utils.log import get_task_logger

log = get_task_logger("test")

app = Celery('app', broker='amqp://', backend='amqp://')

# Optional configuration, see the application user guide.
app.conf.update(
	CELERY_TASK_RESULT_EXPIRES=3600
)

@app.task(base=Batches, flush_every=2, flush_interval=2, track_started = True)
def batch(requests):
	log.debug("batch")
	for request in requests:
		app.backend.mark_as_done(request.id, request.args[0] + "+batch")

@app.task()
def regular(arg):
	log.info("regular")
	return arg + "+regular"

if __name__ == '__main__':
	app.start()
```

```
In [1]: from test_batch import batch, regular
In [2]: d = batch.apply_async(("",), link = regular.s())
In [3]: d.get()
Out[3]: '+batch'
```

If creating a chain with a batch followed by another task, the call never returns. But I see in the logs that batch has been called.
```
In [4]: c = batch.s() | regular.s()

In [5]: c.delay("").get()
```

The opposite chain works as expected though.
```
In [9]: c =  regular.s() | batch.s()

In [10]: c.delay("").get()
Out[10]: '+regular+batch'
```

**Comment by torotil** [comment]
It might be worth noting the maintenance state in the official documentation. Also a link to known-issues would be great. (What can the existing solution do and what does it not do?) There is nothing worse than false promises.

**Comment by ask** [comment]
Thanks! I guess it won't hurt to support dates without time information.

**Comment by ask** [comment]
Wups, wrong issue :(

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Batches will be removed from 4.0 to reflect this.
