### ISSUE TITLE
Rate limiting doesn't work as expected

### ISSUE THREAD

**Issue by adampl** [celery/celery#2068]
I've limited one of my tasks to `10/s`, but despite 48 worker processes running on a very strong machine (6 cores / 12 threads, 24 GB RAM), only about 3 tasks finish each second. Average task runs for about 2 seconds, because it makes a HTTP request and saves some data to a database.

I have 3 queues, but currently only one is used. I'm using Python 3.3, Celery 3.1.11, Kombu 3.0.18, AMQP transport and Redis backend.

This setup has already experienced very high loads, including database-intensive tasks. When I remove the limit, the rate increases to more than 20 tasks per second. None of the system resources is utilized in more than 10%, so I suppose the problem must be with the `rate_limit` itself.

How does the rate limit exactly work? Does it really limit the _rate_ at which tasks are consumed from the queue, or it's the maximum _amount_ of tasks running concurrently?

If my task takes about 2 seconds and the rate limit is 10/s, then about 20 tasks should be running at the same time, while it's only from 5 to 7!

Does the number of queues divide the rate limit?

**Comment by slidenerd** [comment]
SO basically when the concurrency is 4, you are saying that 10/s will apply to each one separately or would 10/s still apply to the whole thing. Basically all I want to know is how rate limits are honored. If I had to ping an API 300 times per second, regardless of whether i use multiple processes or green threads , are the limits honored?

**Comment by auvipy** [comment]
ask this to irc/mailing list
