### ISSUE TITLE
Bugs in RPC implementation

### ISSUE THREAD

**Issue by carlhoerberg** [celery/celery#2074]
We at CloudAMQP aren't users of Celery  but we've have noticed that several of our clients that are using Celery 3.1.11 sometimes creates thousands of temporary queues in RabbitMQ (with made up names like 000133babbaa99badf, instead of server generated names like amq.gen-000000), with auto_delete, durable and expiration (set to 24h), and they all bound to the same routing key. (We suggest auto_delete, exclusive, non durable for temp queues). 

Now sometimes these temp queues doesn't get any subscribers, but will receive a lot of messages, and because no consumers ever connects to it, it won't be auto deleted. This causes outages, where these temp queues together accumulate many millions of messages and the server runs out of RAM. 

So question is, why doesn't temp queues always get a subscriber? 

If this is RPC we also recommend you to create a temp queues, set the "reply-to" header to the queue name when publishing the request, and than the responder can reply to that queue, and you don't have to do any bindings for that queue. Also make the reply queue exclusive and auto_delete, and make sure that a consumer _always_ starts consuming from it, so that it gets deleted later.

**Comment by thedrow** [comment]
@ask Is this a feature request or should it be closed?

**Comment by ask** [comment]
amqp result backend should not be used, I think the documentation updates are good enough to discourage this.
