### ISSUE TITLE
Celery workers stop consuming from RabbitMQ

### ISSUE THREAD

**Issue by maraujop** [celery/celery#2077]
Hi there,

In one of our systems we have 2 celery machines consuming from a RabbitMQ 3.1.2. These nodes consume from the same virtual host and two different queues. We are running celery processes and we had `-c 4` set and all processes consuming from all queues. 

One of the queues (queue B) contains tasks that are thrown against an external system that sometimes takes too long to answer. We have a hard time limit set to 300seconds that kicks in. After several hard time outs, workers stop consuming from queues.

If we do `inspect active` or `inspect scheduled` nothing appears. When we do `inspect stats`, `prefetch_count` is 4.

After finding this out, we tried a work around, launching 4 celery workers with `-c 1`, 2 consuming from one queue `-Q A` and 2 from the other `-Q B`. It usually takes from 12-24 hours until workers from queue B halt. Restarting those celery processes makes the workers consume back from the queue.

Here you can see our grafana (on top of our statsd). A message is sent every time `run` method is called:

![captura de pantalla 2014-06-06 a la s 09 48 55](https://cloud.githubusercontent.com/assets/252257/3197739/325bc5a8-ed4f-11e3-9f34-b09eafee7398.png)

As you can see today at 2am our workers (consuming from B) stop doing their job, A consumer workers continue consuming. At the same time our Sentry registered several hard time outs for the task type that B workers execute:

![captura de pantalla 2014-06-06 a la s 09 51 34](https://cloud.githubusercontent.com/assets/252257/3197870/4cd234c0-ed50-11e3-8941-443cf4d4a77a.png)

I could probably set a timeout in our task so that it retries before it gets killed, however it makes us very anxious the fact that workers stop consuming and we would like to debug the issue itself. 

We are using **celery 3.1.11**, with **django-celery 3.1.10** and **amqp 1.4.5**. Our celery settings are:

```
    BROKER_URL = 'sensitive data'

    CELERYD_HIJACK_ROOT_LOGGER = False
    CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
    CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'

    CELERY_STORE_ERRORS_EVEN_IF_IGNORED = True
    CELERY_ACKS_LATE = True

    # Infinite connection retries with Broker if connection lost
    BROKER_CONNECTION_MAX_RETRIES = 0
    CELERYD_TASK_TIME_LIMIT = 300

    CELERYBEAT_SCHEDULE = {
        'sync': {
            'task': 'sync',
            'schedule': crontab(minute=0, hour='8,9,10,14'),
        },
    }

    CELERY_DEFAULT_QUEUE = 'celery'
    CELERY_QUEUES = (
        Queue('A', Exchange('A'), routing_key='A'),
        Queue('B', Exchange('B'), routing_key='B'),
    )
```

Let us know if there is anything else you need or we can do to help you figure this out.

Thanks, cheers
Miguel

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
