### ISSUE TITLE
MongoDB result backend does not support json serializer.

### ISSUE THREAD

**Issue by jaggerwang** [celery/celery#2081]
The related configuration as follows:
CELERY_RESULT_BACKEND = 'mongodb://localhost:27017/'
CELERY_MONGODB_BACKEND_SETTINGS = {
    'database': 'celery',
    'taskmeta_collection': 'task_meta'
}
CELERY_ACCEPT_CONTENT = ['json', 'msgpack']
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
The error message is ".../lib/python3.4/site-packages/celery/app/trace.py:364: RuntimeWarning: Exception raised outside body: TypeError('data must be an instance of bytes',):".

When changed result serializer to msgpack, it works.
CELERY_RESULT_SERIALIZER = "msgpack"

**Comment by saritasa** [comment]
Yes this is very confusing that everything in mongo is in binary format:

> db.jobs.find().pretty()
{
        "_id" : "efb85a6d-b126-4da9-aad1-846d369f0da0",
        "status" : "SUCCESS",
        "date_done" : ISODate("2015-01-15T21:20:27.345Z"),
        "traceback" : BinData(0,"gAJOLg=="),
        "result" : BinData(0,"gAJ9cQEoVQdtZXNzYWdlcQJVEnlvdSBnb3QgYSBuZXcgc2hmdHEDVQpyZWNlcGllbnRzcQRdcQUoVQZEbWl0cnlxBlUFQm9yeWFxB1UESGllbnEIZVUHY3JlYXRlZHEJVRoyMDE1LTAxLTE1IDEzOjIwOjI3LjM0NTAwMHUu"),
        "children" : BinData(0,"gAJdcQEu")
}

however configuration has this:
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT    = ['json']
CELERY_TIMEZONE          = 'America/Los_Angeles'
CELERY_ENABLE_UTC        = True
CELERYD_PREFETCH_MULTIPLIER = 128

as a result there is no mongo shell usage to query results of tasks/jobs, instead you need to write Python script to "SCAN" the collection and if you have thousands of jobs, from which you want to extract results only of specific jobs - this is performance hit on Mongodb

```python
import pprint, pickle, json
from jobs.tasks.app import app, t_push_notification
pp = pprint.PrettyPrinter(indent=4)

message = 'you got a new shft'
recepients = ['Dmitry', 'Borya', 'Hien']

t_push_notification.delay(message, recepients)

for t in  app.backend.collection.find():
    res = json.loads(t['result'])
    print t
    print res
```

which will give me:

```python
{u'status': u'SUCCESS', u'date_done': datetime.datetime(2015, 1, 15, 21, 25, 26, 327000), u'traceback': Binary('null', 0), u'result': Binary('{"message": "you got a new shft", "recepients": ["Dmitry", "Borya", "Hien"], "created": "2015-01-15 13:25:26.327000"}', 0), u'_id': u'3af42e8f-e76f-485d-9d66-1569c94d6958', u'children': Binary('[]', 0)}
{u'message': u'you got a new shft', u'recepients': [u'Dmitry', u'Borya', u'Hien'], u'created': u'2015-01-15 13:25:26.327000'}


```

also this is not fixed per  source code:
http://celery.readthedocs.org/en/latest/_modules/celery/backends/mongodb.html

```python
def _store_result(self, task_id, result, status,
                      traceback=None, request=None, **kwargs):
        """Store return value and status of an executed task."""
        meta = {'_id': task_id,
                'status': status,
                'result': Binary(self.encode(result)),
                'date_done': datetime.utcnow(),
                'traceback': Binary(self.encode(traceback)),
                'children': Binary(self.encode(
                    self.current_task_children(request),
                ))}
        self.collection.save(meta)

        return result
```

so it does write in Binary only in Celery 3.1.17, but in the latest commits

https://github.com/celery/celery/blob/b2d948db5125bfcfe00eeb5362ba3c35f35e42f0/celery/backends/mongodb.py

this is fixed

```python
 def _store_result(self, task_id, result, status,
                      traceback=None, request=None, **kwargs):
        """Store return value and status of an executed task."""

        meta = {'_id': task_id,
                'status': status,
                'result': self.encode(result),
                'date_done': datetime.utcnow(),
                'traceback': self.encode(traceback),
                'children': self.encode(
                    self.current_task_children(request),
                )}

        try:
            self.collection.save(meta)
        except InvalidDocument as exc:
            raise EncodeError(exc)

        return result
```

**Comment by saritasa** [comment]
I have replaced 

celery/backends/mongodb.py from 3.1.17 with https://github.com/celery/celery/blob/b2d948db5125bfcfe00eeb5362ba3c35f35e42f0/celery/backends/mongodb.py

and got this in mongo

```python
{
        "_id" : "fab82f90-9b4a-4f41-9423-fbb94bf75390",
        "status" : "SUCCESS",
        "date_done" : ISODate("2015-01-15T21:41:17.154Z"),
        "traceback" : "null",
        "result" : "{\"message\": \"you got a new shft\", \"recepients\": [\"Dmitry\", \"Borya\", \"Hien\"], \"created\": \"2015-01-15 13:41:17.154000\"}",
        "children" : [ ]
}
```

it's better, but still impossible to query from the shell, the fix is to change *_store_result* to:

```python
    def _store_result(self, task_id, result, status,
                      traceback=None, request=None, **kwargs):
        """Store return value and status of an executed task."""

        meta = {'_id': task_id,
                'status': status,
                'result': result,
                'date_done': datetime.utcnow(),
                'traceback': self.encode(traceback),
                'children': self.encode(
                    self.current_task_children(request),
                )}

        try:
            self.collection.save(meta)
        except InvalidDocument as exc:
            raise EncodeError(exc)

        return result
```

and now I'm getting

```javascript
{
        "_id" : "3835aaec-6526-42f4-a1dd-376477aaa8d7",
        "status" : "SUCCESS",
        "date_done" : ISODate("2015-01-15T21:42:09.623Z"),
        "traceback" : "null",
        "result" : {
                "message" : "you got a new shft",
                "recepients" : [
                        "Dmitry",
                        "Borya",
                        "Hien"
                ],
                "created" : "2015-01-15 13:42:09.623000"
        },
        "children" : "[]"
}
```

now querying is possible:

```javascript
> db.jobs.find({'result.recepients':'Dmitry'}, {_id:1})
{ "_id" : "3835aaec-6526-42f4-a1dd-376477aaa8d7" }
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to support MongoDB.

**Comment by thedrow** [comment]
@jmmills See https://github.com/celery/celery/pull/1990#issuecomment-193037308

**Comment by wargx** [comment]
For my project it is also crucial as requirement is to filter/analyze stuff inside result object,
but this is actually not a huge problem as there is solution without spikes, 3rd parties 
or any patches to Celery code. General idea is to use custom serializer, here is code snippet:
```
# -*- coding: utf-8 -*-
from kombu.serialization import register

register('mongodb', lambda obj: obj, lambda obj: obj,
         content_type='application/mongo-json', content_encoding='utf-8')
```
and then use it for Celery app configuration
```
CELERY_RESULT_SERIALIZER = 'mongodb'
```
