### ISSUE TITLE
CELERYBEAT_SCHEDULE does not work when set schedule as crontab(minute=x, hour=y)

### ISSUE THREAD

**Issue by pxnj63** [celery/celery#2091]
app.conf.update(
    CELERYBEAT_SCHEDULE = {
                "runs-test-a": {
                    "task": "tasks.test_cron",
                    "schedule": crontab(minute=23, hour=15),
                    "args": ()
                },
                "runs-test-b": {
                    "task": "tasks.test_cron",
                    'schedule': crontab(minute='*/15'),
                    "args": ()
                },
             },
            )

I use the conf as above,  runs-test-a  does not work,  but  runs-test-b  work fine.

I supose it is the crontab func issue.

**Comment by guilhermecarvalhocarneiro** [comment]
Hi,

I am using so
    BROKER_URL="amqp://transparencia:***********/transparencia",
    CELERY_RESULT_BACKEND="amqp://localhost//",
    CELERY_TASK_SERIALIZER='json',
    CELERY_ACCEPT_CONTENT=['json'],
    CELERY_RESULT_SERIALIZER='json',
    CELERY_TIMEZONE='America/Araguaina',
    CELERY_ENABLE_UTC=True,
    CELERYBEAT_SCHEDULE={
        'arquivos_importar_arquivo': {
            'task': 'arquivo.tasks.importar_arquivo',
            'schedule': crontab(minute=2, hour=11),
            'args': ()
            },
    }

But not work. 

When i configuration schedule this contrab() ou contrab(minute='*/5') is working. 

Where i'm wrong?

Sorry my english :)

**Comment by PMickael** [comment]
Did you start worker with --beat ? 

I'm closing this issue, If you still have a problem, open you're own issue
