### ISSUE TITLE
Celery does not emit any signals for unrecognized tasks

### ISSUE THREAD

**Issue by djsmith42** [celery/celery#2092]
If I send a Celery worker an unrecognized task (e.g., my client and worker code are out of sync), I expected Celery to emit celery.signals.task_failure, but it does not. Perhaps a new signal: celery.signals.task_unrecognized or celery.signals.task_rejected.

**Comment by djsmith42** [comment]
Woohoo! Nice!

**Comment by adnanmuttaleb** [comment]
Is there solution now?

**Comment by auvipy** [comment]
try 4.4.x ?
