### ISSUE TITLE
Can not stop Celery if there are active tasks

### ISSUE THREAD

**Issue by serj-p** [celery/celery#2098]
Hi!

I'm running Celery 3.1.8 with RabbitMQ broker. There are few nodes running celery and they are using the same queue. When I try to stop Celery on particular node by sending SIGTERM to the master process it sometimes stops, sometimes not. When it hangs, the master process and all the child processes are sleeping.
Celery's `inspect active` on the specific node shows that there are no active tasks. It also stops consuming new tasks from the queue.

I have an impression that, if there are no active tasks, Celery will stop normally. But if it's currently executing a task, it cannot be stopped by sending SIGTERM to the master process.

I currently use `stopasgroup` in `supervisord`'s config to also stop worker processes but this is wrong since some tasks may be currently in execution and results may be lost. 

What should I investigate to find the reason for such behaviour?

I run Celery this way:

``` bash
bin/celery worker --config celeryconfig -Q high-priority -c 10 --hostname=high-priority.%%h --without-gossip --without-heartbeat
```

A typical task looks the following way:

``` python
@app.task(acks_late = True, max_retries = 12, default_retry_delay = MIN_RETRY_DELAY)
def do_work(ids_list):
     pass
```

My Celery config looks like this:

``` python
from kombu import Queue
BROKER_URL = settings.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = settings.CELERY_BACKEND_URL
HA_POLICY = 'all'
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERYD_FORCE_EXECV = True
CELERY_DISABLE_RATE_LIMITS = True
CELERY_TASK_RESULT_EXPIRES = 1 * 24 * 3600  # 1 days
CELERY_MAX_CACHED_RESULTS = 100
CELERY_IGNORE_RESULT = False
CELERY_STORE_ERRORS_EVEN_IF_IGNORED = True

HIGH_PRIORITY = {'queue': 'high-priority', 'routing_key': 'high-priority'}
LOW_PRIORITY = {'queue': 'low-priority', 'routing_key': 'low-priority'}
CELERY_DEFAULT_QUEUE = LOW_PRIORITY['queue']
CELERY_QUEUES = (
    Queue(HIGH_PRIORITY['queue'], routing_key=HIGH_PRIORITY['routing_key']),
    Queue(LOW_PRIORITY['queue'], routing_key=LOW_PRIORITY['routing_key']),
)
CELERY_ROUTES = (
    {'do_work': HIGH_PRIORITY},
)
CELERY_IMPORTS = tuple(["nimble_search.es"])
sys.executable = os.path.join(os.path.dirname(__file__), "..", "bin", "python")
```

**Comment by semmel87** [comment]
Imagine you have a long running task. Is there a possibility to react on this event in the program? I mean does the running task receive some signal or similar?
