### ISSUE TITLE
problems with autoscaling on windows

### ISSUE THREAD

**Issue by gimoh** [celery/celery#2106]
There appears to be an issue with worker autoscaling on Windows.  We've noticed that, even with the simple add task (with some time.sleep added) from the tutorial, when a worker scales down, it won't scale back up whenever new tasks are scheduled.

The command used to start the worker is:

    celery worker --app=foo --autoscale=8,0 --loglevel=debug -O fair

but we've tried different combination of options, only autoscale (or its absence) makes a difference.  The last lines in worker's output are:

    [2014-06-19 15:35:51,944: INFO/MainProcess] Received task: ...
    [2014-06-19 15:35:51,944: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x000000000351DF98> (args:...)
    [2014-06-19 15:35:52,740: INFO/MainProcess] Scaling up 1 processes.
    [2014-06-19 15:35:52,740: DEBUG/MainProcess] basic.qos: prefetch_count->3

(or something along those lines) after which it just hangs forever.

If you have any hints on how to help debug this, that would be very welcome :)

BTW, I checked other similar bug reports, like #1845 or #1266 or #2077 or  #597 but they don't appear to match exactly.

Output of `celery inspect report`:

    -> celery@HGVPUBLISHER: OK

        software -> celery:3.1.12 (Cipater) kombu:3.0.19 py:2.7.6
                    billiard:3.3.0.17 py-amqp:1.4.5
        platform -> system:Windows arch:64bit, WindowsPE imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:amqp results:disabled

        CELERYD_PREFETCH_MULTIPLIER: 1
        CELERY_RESULT_PERSISTENT: True
        BROKER_URL: 'amqp://test:********@rabbit:5672/test'
        CELERY_IMPORTS: ['tasks']
        CELERY_INCLUDE:
            ('tasks', 'celery.app.builtins')

(note that result backend is really 'amqp', not sure why it's not showing up in there)

**Comment by illagrenan** [comment]
I've just ran into this issue. +1 for adding a note to documentation or even some warning similar to `-B` on Windows:

```
-B option does not work on Windows.  Please run celery beat as a separate service.
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
