### ISSUE TITLE
MongoDb as backend abyssmal performance in ReplicaSet

### ISSUE THREAD

**Issue by GoingTharn** [celery/celery#2115]
Celery's performance with a replicaset backend is pretty terrible from 3.1.6 to 3.1.12.

I average 1.0s/task on 3.1.6, and 20s+ on the 3.1.12 branch.

Furthermore, mongo URIs no longer work in the latest branch due to a bug in kombu splitting on the comma in the URI.

**Comment by thedrow** [comment]
We need more information in order to look into this regarding both issues.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support MongoDB.
