### ISSUE TITLE
chord with chain as body Fails With Default Settings

### ISSUE THREAD

**Issue by npilon** [celery/celery#2118]
Demo application:

https://github.com/LexMachinaInc/canvas_kaboom

Specific failure case:

https://github.com/LexMachinaInc/canvas_kaboom/blob/master/canvas_kaboom/chord_chain.py#L22

In celery 3.1.x, using a chain as the body of a chord fails with an exception inside ```on_chord_part_return```. Because of where this occurs, this exception is logged but not reported through standard channels. (```CELERY_SEND_TASK_ERROR_EMAILS```, the ```task_failure``` signal, etc) This works fine in 3.0.x and when writing a similar structure using group:

https://github.com/LexMachinaInc/canvas_kaboom/blob/master/canvas_kaboom/group_upgrades.py#L22

Attempting to run all three of these test cases against https://github.com/celery/celery/commit/792a23184e55a14ba197fdcf5f1b1f8a768ee226 fails at the end of the "producing" tasks in all cases.

What seems to be happening in 3.1 is that the chain Signature is being properly converted back from a dictionary form, but the contents of the chain aren't.

**Comment by thedrow** [comment]
@gcarothers I have no idea but I'm following your recommendation.

**Comment by rrauenza** [comment]
I am seeing something similar to this with celery==4.2.1.

My signal handler works fine with a simple task failure, but doesn't in a chord:

[2018-09-06 12:52:10,343: ERROR/ForkPoolWorker-3] Chord callback for 'd12f723b-54e2-4509-98ee-21a32885e53b' raised: ChordError(u'Dependency a813c3d5-04e5-4842-9793-0c84e1644774 raised IntegrityError(....)',)

My chord is started ...

```
c = chord([foo.si(foo_id) for foo_id in foo_ids], done.si(bar_id))                                  
return c.delay()   
```

This task works fine with the signal capture:

```
@app.task(bind=True)
def failing_task(self, key=None):
    raise Exception("Hello world!")
```

**Comment by auvipy** [comment]
can you try the master branch?
