### ISSUE TITLE
Implement pattern and matcher arguments for remote control

### ISSUE THREAD

**Issue by malinoff** [celery/celery#2122]
Hi Ask,

As you said in IRC, this feature may be useful.
Example:

``` python
app.control.ping(pattern=r'.*(frontend|db).*', matcher='pcre')
```

**Comment by thedrow** [comment]
@ask @malinoff Can we look at this again?

**Comment by malinoff** [comment]
I'd like to think about this a little bit more. I don't know why, but I have a though about revising whole remote control...

**Comment by jheld** [comment]
This looks really cool.

If I'm reading correctly, it means if we had N number of worker nodes with a similar name (say a matching prefix), we could specify just that set, without knowing ahead of time their names? So critical-node-0, critical-node-1, etc, then do a glob or regex for that pattern?

If so, is there any reason not to include this feature? It seems there is talk of refactoring remote control/pidbox...but until then, why not add this?

**Comment by thedrow** [comment]
We didn't have the time to implement this.
PRs are welcome.

**Comment by jheld** [comment]
I think this PR implements what is being asked of: https://github.com/celery/celery/pull/5319

**Comment by auvipy** [comment]
> I think this PR implements what is being asked of: #5319

yup seems so. closing for now. thanks
