### ISSUE TITLE
documation fix for django 1.7 "App registry isn't ready yet"

### ISSUE THREAD

**Issue by thenewguy** [celery/celery#2126]
The celery app file needs to call django.setup in django 1.7 or you get an exception stating "App registry isn't ready yet" when a task is run.

See https://docs.djangoproject.com/en/dev/releases/1.7/#standalone-scripts

The documentation for first steps with django (http://docs.celeryproject.org/en/master/django/first-steps-with-django.html) need to be updated to reflect this.

**Comment by kolis** [comment]
I have the same problem, I updated to django 1.7 and now I get the AppRegistryNotReady exception. I'm using the old django-celery setup.

I am using celeryd daemon to launch the workers. Note that if I launch them manually using
`python manage.py celery worker --loglevel=info`
it does work. But when using the 'celery multi' command, which is used by celeryd, I get the AppRegistryNotReady exception.

**Comment by findsarfaraz** [comment]
I am also facing the same issue. 
raise AppRegistryNotReady("Models aren't loaded yet.")

Celery documentation has many links which shows different ways to integrate celery with DJANGO. One says include celery.py in main project. Other has djcelery thing. Everyone thing just melt down to confusion. 

I have documented my issue in the following link. Has anyone fixed it please reply.

https://groups.google.com/forum/#!topic/django-users/c_LOQ_nUvmw

**Comment by illagrenan** [comment]
I have same problem (`AppRegistryNotReady: Models aren't loaded yet.`) on Windows `8.1` and Django `1.7` using `djcelery==3.1.16`.

This worked for me:

```bash
$ (env) pip uninstall celery
$ (env) pip install celery
```

Btw I agree with @findsarfaraz – the documentation about integrating Celery with Django is confusing.

**Comment by mkuchen** [comment]
@ask I'm facing the same issue.  I just upgraded Django from 1.6 to 1.7 (using Heroku/foreman for local development).  Celery version is 3.1.17.  I also have django-celery installed, version 3.1.16.

My wsgi.py file uses the proper application syntax:

```python
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

...and my Procfile is as follows:
```Procfile
web: newrelic-admin run-program gunicorn -c gunicorn.py.ini wsgi:application
scheduler: newrelic-admin run-program celery beat --loglevel=INFO --app=api.celery:app
worker: newrelic-admin run-program celery worker -Q celery -E --loglevel=INFO --maxtasksperchild=200 --app=api.celery:app
periodic: newrelic-admin run-program celery worker -Q periodic -E --loglevel=INFO --maxtasksperchild=200 --app=api.celery:app
```

When I remove the `scheduler`, `worker`, and `periodic` lines, `foreman start` executes properly and runs without a hitch.  But when I add the Celery commands back in, I get:
```
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

However, when I run from my command line:
```
foreman run python manage.py celery worker -Q celery -E --loglevel=INFO --maxtasksperchild=200 --app=api.celery:app
```
It runs properly.  Any thoughts here?  It seems to have something to do with the way Celery is loading Django's translations module.

**Comment by mkuchen** [comment]
@limpbrains @sreedharbukya @ask I was able to fix the error by changing my `celery.py` file.  It was originally:

```python
# ...
app = Celery('api')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')
# ...
```

I just switched those 2 lines and the issue was resolved, so:
```python
# ...
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')
app = Celery('api')
# ...
```

Hope this helps somebody!

**Comment by adambratt** [comment]
@mkuchen hahaha of all people.

Well you just helped me!

**Comment by adambratt** [comment]
@mkuchen Haha, well it fixed it for me!

**Comment by mkuchen** [comment]
@adambratt say whaaaat!  What a coincidence.  IIRC you were the one who introduced me to Celery in the first place.  Talk about full-circle!

**Comment by barneyjackson** [comment]
Still experiencing this issue running Linux 14.04, Django 1.7, Celery 3.1.18. Is there a known fix/workaround/upgrade for this @ask? The [change history](http://docs.celeryproject.org/en/latest/changelog.html) in the docs implies 3.1.14/15 fixes it.

**Comment by nilliams** [comment]
Adding what worked for me in case it helps anyone:

None of the above solutions I've read in this and other threads worked for me. I'm running Django 1.8, Celery 3.1.18, django-celery 3.1.6 and starting workers via `manage.py celery`.

What appeared to magically fix the `"Models aren't loaded yet."` problem for me was disabling `CELERYD_FORCE_EXECV` as strongly recommended in the celery 3.1.7 release notes: http://docs.celeryproject.org/en/latest/changelog.html#version-3-1-17

(Even though the 2 things don't seem like they should be related).

**Comment by ask** [comment]
I don't think this is an actual issue anymore, more about some common pitfalls when integrating django/celery
