### ISSUE TITLE
apply_async's link_error param expects a list?

### ISSUE THREAD

**Issue by jakab922** [celery/celery#2130]
So I have this gist -> https://gist.github.com/jakab922/7654deeb632e2759ffa9

The python trace is pasted as a comment on the bottom. Also if I wrap the err_task in the options2 dictionary in a list then all works fine. I don't know if that's the correct way to handle this. So my question would be if I add a link_error attribute to apply_async of a Task/Signature does it have to be a list or a task? I suspect it has to be a task and my example in the gist should not fail, hence I raised the issue.

**Comment by thedrow** [comment]
@ask Is this a bug or should it be closed?

**Comment by ask** [comment]
Probably the difference between send_task and Task.apply_async used when using anon signatures in 3.1.  In 4.0 the same code path is used for send_task and Task.apply_async.
