### ISSUE TITLE
workers stop consuming on celery 3.1.12

### ISSUE THREAD

**Issue by unohoo** [celery/celery#2136]
I am running celery 3.1.12 with redis broker. I have been noticing that my worker processes stop consuming tasks after a random amount of time. I have tried running the celery worker both with supervisord and as a 'nohup' job in the background. the same behavior in both cases. 
Here's the command i use:

 /<virtual-env>/bin/python manage.py celery worker -Ofair --concurrency=4 --loglevel=DEBUG --logfile=/var/log/celery/worker_debug.log

I have also tried using the autoscale option but that produces the same results as well.

If I run the redis-cli client to get the number of tasks in the broker, I get 3343:
/redis-2.8.11/src/redis-cli -h localhost -p 6379 -n 0 llen celery

> > 3343

If i run python manage.py celery inspect active I see that each of the processes for the worker have a task. 

However, if I check the worker logs, they dont seem to be doing anything.  No worker output was generated in the last 1.5 hours. The only output was some celery debugging info:

[2014-07-10 11:01:52,216: DEBUG/MainProcess] pidbox received method dump_active(safe=False) [reply_to:{u'routing_key': u'858872a1-3590-3077-b870-95ec7d19fee5', u'exchange': u'reply.celery.pidbox'} ticket:28d61520-e98f-4f5a-adc1-2dadc2903f79]
[2014-07-10 11:02:11,304: DEBUG/MainProcess] pidbox received method dump_schedule(safe=False) [reply_to:{u'routing_key': u'd025528e-41cf-3020-8658-86ccd9d8a827', u'exchange': u'reply.celery.pidbox'} ticket:8be95596-85d9-4b2f-86ee-c697736870f0]

**Comment by chrisspen** [comment]
I also have this same problem in Celery 3.1.18. Running `celery -A proj inspect active` for my app results in the error:

    Unrecognized command-line arguments: inspect, active

My logs also show a bunch of `pidbox received method dump_active(safe=False)`. The only workaround seems to be to continually restarting Celery. Celery 4 seems to have even more bugs, so I don't want to upgrade. Was a fix for this ever found?
