### ISSUE TITLE
self not passed to link_error for task methods

### ISSUE THREAD

**Issue by alexhayes** [celery/celery#2137]
It appears that for task methods (ie.. `celery.contrib.methods.task`) if used as `link_error` the first argument passed is the `task_id` not `self`, as one would naturally expect.

For example:

```python
from celery.contrib.methods import task
class MyClass(object):

    @task()
    def raises(self):
        raise Exception('Hi')

    @task()
    def on_raise(self, task_id):
        ...
```

If one was to create the following:

```python
m = MyClass()
m.raises.s().apply_async(link_error=m.on_raise.s())
```

It fails, complaining that `TypeError: on_raise() takes at least 2 arguments (1 given)`.

It appears that `task_id` is passed as the first argument and `self` is not passed at all.

As a workaround the signature to `on_raise` can be changed as follows:

```python
    @task()
    def on_raise(task_id, self):
        ...
```

And then `self` passed into the `link_error` callback:

```python
m = MyClass()
m.raises.s().apply_async(link_error=m.on_raise.s(m))
```

However this just seems a little odd for a task method.

Is this an issue or intended behaviour?

**Comment by nuklea** [comment]
Have same issue, when pass subtask by `link` argument. @alexhayes did you find solution?

**Comment by nuklea** [comment]
When `CELERY_ALWAYS_EAGER = True` all works fine.

**Comment by alexhayes** [comment]
I decided to write a decorator to handle this, it's a bit of a hack
solution which is pretty ugly but at least it works - see
https://bitbucket.org/alexhayes/django-toolkit/src/c8c6e3e96627bfa8d8526b2cf324672b9291d10d/django_toolkit/celery/decorators.py?at=master#cl-3

I'm working on a much better solution in #2600 which works for
`apply_async` but not `apply` at the moment and it would be easy to make
this work for normal classes (as opposed to django models) however I
haven't had a chance to do this and I'm also waiting on feedback about my
approach.

All this may be in vain however because @ask has stated that unfortunately
method based tasks are considered a failed experiment and will be removed
in 3.2.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.  Task methods have been removed for 4.0
