### ISSUE TITLE
celery.exe can't run

### ISSUE THREAD

**Issue by JayceM6** [celery/celery#2144]
Fatal error in launcher: Unable to create process using '""D:\Program Files\Python\Python27\python.exe"" "D:\Program Fil
es\Python\Python27\Scripts\celery.exe" '

In celery.exe, #!"D:\Program Files\Python\Python27\python.exe"
I think, it should be #!D:\Program Files\Python\Python27\python.exe
In windows 7 x64 sp1, python 2.7.8, celery 3.1.13

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
