### ISSUE TITLE
celery events and celery flower not show full result content

### ISSUE THREAD

**Issue by tolorr** [celery/celery#2161]
Hello, I updated the last version of celery anb celery flower.

I have a problem. I need monitor the task results (full result). I use Flower for this purpose, but after update, Flower not show full result content. Only show a small part of result.

I've tried Celery events, but I have the same problem.

I had celery==3.0.23 and flower==0.5.2. with this versions no problem

Any Idea?

Thank's!

**Comment by netinsideout** [comment]
ask, flower is monitoring software or something different? I need to monitor output, flower can not help me.

**Comment by thedrow** [comment]
Flower is a monitoring tool that uses celery events. Celery events are limited in size in order to avoid performance issues.
You might be able to customize flower by sending the result's key in the results backend and fetching the result from there.
