### ISSUE TITLE
Invoking chord in process on worker seems to block worker

### ISSUE THREAD

**Issue by dwt** [celery/celery#2165]
Hi there,

we're still debugging this, but it seems like executing a chord in process on a worker may deadlock it.

Now I get that workers invoking sub tasks like chords synchronously on workers has the potential to deadlock them, but I we're executing them in process, so that shouldn't be the reason.

Is that some kind of expected behavior? The docs don't seem to mention this.

**Comment by thedrow** [comment]
@rbu @dwt Can you guys provide a failing test case?

**Comment by rbu** [comment]
We did not reduce the problem, but in pseudo code it looked like this:

```py
@celery.task
def much_work(...):
     # computation
     # database etc

@celery.task
def generate_and_execute_much_work(...):
    outer_tasks = []
    for outer in range(100):
        inner_tasks = []
        for inner in range(100):
            inner_tasks.append(much_work.si(...))
        outer_tasks.append(chord(inner_tasks))
    
     for task in outer_tasks:
         task.apply()
```

Now, executing ```generate_and_execute_much_work()``` through Celery would hang for us sometimes. Note, we were executing the chords asynchronously before, but we ran into #2011

**Comment by rbu** [comment]
@thedrow, I cannot provide a failing test unfortunately. We have since abandoned chords and groups altogether since they created more hassle and bugs than executing long-running jobs in a single thread.

**Comment by thedrow** [comment]
@rbu In that case I have to close this issue since I haven't got enough information to work on.
Are you guys sure you can't take a look at your repository and extract a test case out of the historic code?

**Comment by dwt** [comment]
Sorry, the code in question isn't open source, so we can't give access to it. Also quite some bits of our infrastructure have changed since this bug happened, so we're very hesitant to now invest time to reproduce this.

**Comment by thedrow** [comment]
I'm sorry it took us so long to respond.
We'll try to do better.
