### ISSUE TITLE
Role of django-celery is unclear

### ISSUE THREAD

**Issue by cpbotha** [celery/celery#2174]
The django-celery github page at https://github.com/celery/django-celery states:

```
Warning

THIS PROJECT IS NO LONGER REQUIRED

Please follow the new tutorial at:

http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

django-celery provides Celery integration for Django; Using the Django ORM and cache backend for storing results, autodiscovery of task modules for applications listed in INSTALLED_APPS, and more.
```

It sounds like we should _not_ be using the django-celery project.

However, it seems it is necessary to install at least for the django management commands, and for using the Django ORM / caching as results backend. (the "no longer required" message links to a new manual, but that also recommends using django-celery to use the django ORM as results backend http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-the-django-orm-cache-as-a-result-backend )

Could this text be clarified? What exactly is the status of the django-celery project?

(I'm asking, because I ran into a django 1.7rc2 vs django-celery bug: https://code.djangoproject.com/ticket/23133 -- however, the issue of model validate() vs django setup() seems to have been resolved in the celery django fixups https://github.com/celery/celery/pull/1981 but not in django-celery )

**Comment by mikeumus** [comment]
Django-Celery is still very useful in theory (if I could get it showing tasks) simply for that fact of [recycling awesome code](https://github.com/celery/django-celery/pull/381#event-336002928) that allows to set schedules of tasks and task reporting. Very awesome. I'm of the camp that it shouldn't be labeled too harshly as "No longer required", maybe "django-celery is a supplemental module giving many nice features to django admin like scheduling of tasks."  

Left a comment on this in https://github.com/celery/django-celery/issues/335 as well. 

django-celery, Live long and prosper.
