### ISSUE TITLE
Running Celery from Cygwin for Use with Supervisord

### ISSUE THREAD

**Issue by jfhawkin** [celery/celery#2175]
I am trying to daemonize celery (+celery flower) with supervisord in a venv using cygwin. The command " celery worker -A runLogProject --loglevel=INFO " works in the windows shell, but not the cygwin shell. It just gives me the warning about pickling being deprecated in celery 3.2 without starting a server. My supervisord log file also says celery.exe is not an executable file.

**Comment by thedrow** [comment]
I don't think we're going to support this any time soon.
If you feel strongly about it, please comment.
