### ISSUE TITLE
Retry does not work in SQLAlchemy broker

### ISSUE THREAD

**Issue by gthb** [celery/celery#2177]
It appears that task retry does not work at all with the SQLAlchemy broker — is this a known issue? It seems from #1899 that it is expected to work, and retry is not mentioned in http://docs.celeryproject.org/en/latest/getting-started/brokers/sqlalchemy.html#limitations so I guess not.

I was testing retry in a Task class that boils down to:

```
class RunJob(Task):

    def run(self, *args, **kwargs):
        try:
            ...
        except ConcurrentJobException, concexc:
            raise self.retry(exc=concexc, countdown=RETRY_SECS, max_retries=RETRY_MAX)
```

and after the retry is raised, the task is never invoked again with the SQLAlchemy broker; the row in `celery_taskmeta` gets updated with `status='RETRY'`, but no new rows appear in `kombu_message`, so the task just stays in status RETRY.

Then tried out the same task code with a RabbitMQ broker; that way retry works just fine.

**Comment by thedrow** [comment]
@gthb Any updates on this issue?

**Comment by gthb** [comment]
No, I haven't had time (or need) to follow up on this.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
