### ISSUE TITLE
unique task delivered to two workers concurrently

### ISSUE THREAD

**Issue by lefthandmagic** [celery/celery#2183]
*Reposting from the user-group as I didn't receive any response there. Also had tried the IRC. Please do let me know if this is a known issue/i'm doing something stupid/potential fix*

Hi,

   I currently have a celery deployment with three workers (each with a concurrency of 6) & one celerybeat instance.  My celery overrides are as below:

celery:
  CELERY_TASK_SERIALIZER: json
  CELERY_ACCEPT_CONTENT: [json]
  BROKER_URL: "redis//**/ - some value here
  CELERY_RESULT_BACKEND: "redis://**/" - some value here 
  CELERY_DEFAULT_QUEUE: 'mydefault'
  # the docs say the rate-limiting subsystem is expensive and to disable if it's not being used
  CELERY_DISABLE_RATE_LIMITS: true
  # The majority of tasks don't need this; it can be enabled on a per-task basis if needed
  CELERY_IGNORE_RESULT: true
  # acknowledge after the task is completed (to reserve one task at a time)
  CELERY_ACKS_LATE: true
  # prefetch only one task per process
  CELERYD_PREFETCH_MULTIPLIER: 1
  CELERY_IMPORTS:
    - wall_e.jobs.executor
  CELERYBEAT_MAX_LOOP_INTERVAL: 30

I use only one queue. 

I ran into a bizarre incident yesterday where a task(d9468ec2-e24e-4dcb-9b6f-e56bfda1d523) that was queued got received by two workers (running on different hosts) with approximately 2 min interval difference (04:42:38,454 vs 04:44:27,279) . 

The task is idempotent, however a race in the task caused one to error out (which is ok..without catastrophic issues). But i want to understand why this could've happened.

This was an one-off incident.

logs from worker#1 

wall_e-celery.err.1:[2014-08-01 04:42:38,454: INFO/MainProcess] Received task: wall_e.jobs.executor.run_wall_e_task[d9468ec2-e24e-4dcb-9b6f-e56bfda1d523]

wall_e-celery.err.1:[2014-08-01 04:46:24,078: INFO/MainProcess] Task wall_e.jobs.executor.run_wall_e_task[d9468ec2-e24e-4dcb-9b6f-e56bfda1d523] succeeded in 225.623367734s: None

logs from worker#2

wall_e-celery.err.1:[2014-08-01 04:44:27,279: INFO/MainProcess] Received task: wall_e.jobs.executor.run_wall_e_task[d9468ec2-e24e-4dcb-9b6f-e56bfda1d523]

wall_e-celery.err.1:[2014-08-01 04:46:23,945: ERROR/MainProcess] Task wall_e.jobs.executor.run_wall_e_task[d9468ec2-e24e-4dcb-9b6f-e56bfda1d523] raised unexpected: ProgrammingError('relation "sessions_87c542352e" does not exist\n',)

Any explanation for this incident, and recommendations on how this can be avoided will be great. 

Thank you,

Praveen

https://groups.google.com/forum/#!topic/celery-users/se5NREw2sVk

**Comment by thedrow** [comment]
@lefthandmagic What's the status here?
Is there something actionable we can fix?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

It's Redis so you have to expect things to be inconsistent...
