### ISSUE TITLE
Hard time limits on Windows will eventually stop the worker

### ISSUE THREAD

**Issue by abarton** [celery/celery#2195]
software -> celery:3.1.9 (Cipater) kombu:3.0.15 py:3.3.4
            billiard:3.3.0.17 py-amqp:1.4.5
platform -> system:Windows arch:64bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

The Celery worker is killing the child process on a hard time limit exception but not restarting them. After a hard time limit has been thrown enough times to kill all the children the worker parent process stops.

The lost log entry before the worker stops will be for a hard time limit:

```2014-08-12 20:55:05,974 - celery.worker.job - ERROR - Hard time limit (10s) exceeded for sometask[9dc380c6-d82d-4cd4-9e0b-840e092d323c]```

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
