### ISSUE TITLE
Empty group restores as AsyncResult.

### ISSUE THREAD

**Issue by schinckel** [celery/celery#2202]
When attempting to restore a group that was empty, we get an `AsyncResult` instead of a `GroupResult`:

    from celery import group
    from celery.result = GroupResult

    # This is actually a simplification: the list comprehension used here
    # may evaluate to empty.
    job = group([])
    result = job.apply_async()

    GroupResult.save(result)

Then, in another thread, possibly:

    task = GroupResult.restore(result.id)

IMHO: this should be a `GroupResult` with an empty list for `.results`, but it's coming back as an `AsyncResult`.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

GroupResult.restore and .save should not be used anymore.  I've removed use within celery itself already, and it's a bad pattern to use since it's difficult to clean up from.

**Comment by schinckel** [comment]
So how do we persist group results then? It's still documented as working, with no mention of deprecation at http://celery.readthedocs.io/en/latest/reference/celery.result.html#celery.result.GroupResult

**Comment by ask** [comment]
You could save the list of results in a database yourself.  The existing methods are using pickle so it's not really safe as it works currently.

We have no resources to work on fixing problems with the implementation, and neither to find a better solution at this point.  It's not just this feature, I closed 200 issues today to try and get some future focus.  

I haven't made the change in the code yet, we cannot deprecate it in time for the 4.0 release, but I can remove the feature from documentation to avoid new users finding out about it.

I would like to have a solution for it, but this being open source we have no money to throw at it and no companies to help us.  Only a shit ton of issues that bring me down every day to the point of just choosing one to work on is difficult.  I have 24000 unread mails in my inbox, and all I can do is just look at them fly by.

**Comment by schinckel** [comment]
No worries. Thanks for your time in actually responding to my further questions (and thanks for celery!)

I'll see if I can come up with a nice pattern for saving and supply a documentation PR at some point.

**Comment by red-hood** [comment]
Hi,

I am currently using Celery 4.0.2 and seem to suffer from the same issue mentioned here. @ask wrote

**Comment by red-hood** [comment]
Hi,

I am currently using Celery 4.0.2 and seem to suffer from the same issue mentioned here. @ask wrote:

> GroupResult.restore and .save should not be used anymore. I've removed > use within celery itself already, and it's a bad pattern to use since it's 
> difficult to clean up from.

Does this still hold true for Celery 4.0.2? If so, wouldn't it make sense to mention it in the documention and maybe also emit a warning when the methods are used?

**Comment by AlexHill** [comment]
Hi,

Ran into this today.

Changing one line in `result_from_tuple` appears to do the trick. `nodes` here is an empty list when a group result is being restored, which evaluates False so the branch returning `GroupResult` is never hit:

```
        if nodes is not None:  # instead of just "if nodes"
            return app.GroupResult(
                res, [result_from_tuple(child, app) for child in nodes],
            )
```
