### ISSUE TITLE
Tasks stuck in received state

### ISSUE THREAD

**Issue by jclark360** [celery/celery#2206]
We had a large set of tasks run last night (~1 million), and for some reason the python process is hung waiting for the AsyncResult to return.  We effectively queue all 1 million up and wait on them to complete.   I'm trying to figure out why we're still waiting, given flower tells me the broker is empty yet when I go to Tasks I see dozens in Received state...   Any ideas on what to look at to try and figure out how these tasks got "stuck" or are unaccounted for?

**Comment by thedrow** [comment]
@jclark360 Can you provide us with a failing test case?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
