### ISSUE TITLE
Celery crashes on load in python 2.7.6

### ISSUE THREAD

**Issue by pnurkkala** [celery/celery#2211]
But I think I have the versions that have the patch fixes.. 

Hello. 

Upon running python manage.py celery worker (with appropriate settings, etc) 

I get this: "Unrecoverable error: TypeError('unpack_from() argument 1 must be string or read-only buffer, not memoryview',)"

Which I found reports about here: 
https://github.com/celery/celery/issues/1637

My python version is 2.7.6
celery==3.1.13
django-celery==3.1.10

So when I run the command, I get that above error message. However, my local computer is python 2.7.5 and it works perfectly. Any sense of what could be causing this?

**Comment by thedrow** [comment]
This was resolved. See @ask's comment in #1637.
