### ISSUE TITLE
Execute code before worker instantiation

### ISSUE THREAD

**Issue by Femaref** [celery/celery#2215]
I'm currently running a flask app, encapsulated in a class, so something like:

    class FlaskFoo:
      def __init__(self, config):
        self.config = config

      def create_app(self):
        app = Flask(__name__)
        app.config.from_pyfile(self.config)

        return app

In server.py:

    foo = FlaskFoo(config)
    foo.run()

However, the celery workers require the celery variable to be available on a module. Is there a way to keep the style I'm using, while still being able to run celery with it? I.e. is there a way to execute code during the startup process which would result in the celery variable?

**Comment by thedrow** [comment]
You can use the [worker_init](http://celery.readthedocs.org/en/latest/userguide/signals.html#worker-init) signal.
