### ISSUE TITLE
Messages dispatched to a dedicated queue may be rejected by the broker

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2216]
I am using the Qpid broker, but this should be reproducible with RabbitMQ.

1) Start a single celeryd worker with a single worker process, and configure that worker to use `CELERY_WORKER_DIRECT = True`
2) Start an interactive python shell in a terminal and import a task that the worker knows about
3) Use apply async to dispatch specifically into that queue (ie: 'foo').  `my_task.apply_async((param_one,), queue=foo)`
4) Observe the task runs (as expected)
5) Restart the worker
6) Dispatch another task (redo step 3)
7) Observe that the task from step 6 is never run

The Celery router that is being used in the terminal performs a bind of the queue 'foo' to the exchange 'foo' with the bind key 'foo'. This appears to be the responsibility of the sender, and is only done once. The binding is deleted when the worker restarts because the default behavior of dedicated queue is to auto-delete the queue when the worker stops, and create it again when the worker starts. Step 5 above causes the queue to be recreated, and the expectation of the dispatcher that the queue 'foo' is still bound to exchange 'foo' with bind key 'foo'.

There are several possible ways to resolve this:
1. I expected apply_async with queue=foo specified to not need to dispatch on an exchange at all, and instead dispatch onto a queue by name without specifying an exchange. This should cause kombu to do the right thing, and it would end up in the queue!
2. We could use the [`CELERY_ROUTES`](http://celery.readthedocs.org/en/latest/configuration.html#celery-worker-direct) configuration to specify that our tasks need to be dispatched on to the C.dq exchange. I would really prefer not to do this because we have a lot of tasks, and we write new ones, and delete old ones.
3. We could use apply_async with the `exchange='C.dq'` parameter and queue, but [the docs](http://celery.readthedocs.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.apply_async) say the exchange parameter is typically not used with queue specified. Also our different tasks use dedicated queue, but many don't so this would be difficult for similar reasons as option 2.
4. The dedicated queue could gratutiously create the bind of queue 'foo' to exchange 'foo' with binding key 'foo' upon startup. If the clients additionally do this, it should have no effect on the broker.

**Comment by ask** [comment]
Since we changed `worker_direct` to be auto_delete=False this should no longer be an issue?

**Comment by bmbouter** [comment]
I haven't been able to revisit the discussion until now, but what about users who then do want to have `worker_direct` to be auto_delete=True. Having auto_delete=False is better for my purposes, but it should be configurable. Without even knowing much about that codepath having it be configurable should be easy.

Can you remind me of exactly which version the auto_delete was switched to True for `worker_direct` please? At least that way I can know which behaviors to expect where.

**Comment by bmbouter** [comment]
@auvipy I'm not sure, sorry.

**Comment by auvipy** [comment]
closing this for now, will reopen if it pop up again
