### ISSUE TITLE
chain/chord with failed task get stuck in celery.chord_unlock

### ISSUE THREAD

**Issue by tebeka** [celery/celery#2219]
See discussion on celery-users [here](https://groups.google.com/d/msg/celery-users/blNq6PO2BXw/lhosbcwaa3IJ).

To rehash:
Assuming a complex canvas like [in this example](https://gist.github.com/tebeka/9df9c9d9b0b41d46d335#file-ch-py) and running it [like this](https://gist.github.com/tebeka/9df9c9d9b0b41d46d335#file-run-py). Then every second Celery outputs 

```
    [2014-08-21 14:31:55,425: INFO/MainProcess] Received task: celery.chord_unlock[076bb3d7-f934-4c8a-a7f5-c86e2239ae60] eta:[2014-08-21 11:31:56.424264+00:00]
```

Calling `list(res.collect())` blocks. I tried switching to redis backend, the `chord_unlock` messages are not there but `list(res.collect())` is still stuck.

**Comment by sukrit007** [comment]
+1 if we this can be addressed in celery codebase. For now I will try the workaround mentioned in the discussion.

**Comment by daniel-cohen** [comment]
I can confirm this is still an issue with 3.1.18.

Not sure what: "  # generic error handling here..." means in the Jon's solution on the mentioned thread.
Are you not going to the mark the task as failed in that case ?

**Comment by jeremyll** [comment]
+1

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Maybe fixed in master, let's see if it comes back after 4.0 release.
