### ISSUE TITLE
Unable to create chord: "TypeError: group object got multiple values for keyword argument 'task_id'"

### ISSUE THREAD

**Issue by aneilbaboo** [celery/celery#2225]
On celery master (2fddb876e1), when attempting to run a chord :

```python
from celery import Celery, group

app = Celery()

@app.task
def add(x,y): 
    return x+y

@app.task
def xsum(seq):
    return sum(seq)

c = (group([add.si(1,1), add.si(2,2)]) | xsum.s())
c.delay()
```

The method _apply_chord_incr generates an exception ```TypeError: group object got multiple values for keyword argument 'task_id'``` on the call to header:

```
def _apply_chord_incr(self, header, partial_args, group_id, body,
                      result=None, options={}, **kwargs):
    self.save_group(group_id, self.app.GroupResult(group_id, result))
    return header(*partial_args, task_id=group_id, **options or {})
```

The options dict already has a value for task_id (a different value from group_id).

I tried removing the task_id key from options:

```
def _apply_chord_incr(self, header, partial_args, group_id, body,
                      result=None, options={}, **kwargs):
    self.save_group(group_id, self.app.GroupResult(group_id, result))
    if options.get('task_id'):
        del options['task_id']
    return header(*partial_args, task_id=group_id, **options or {})
```

Which fixes the immediate error, but when I attempt to .get() the result, the program hangs.

I also tried removing the task_id=group_id keyword argument, but still get a hang.

**Comment by aarcro** [comment]
I think I'm seeing this too. My chord with two tasks in the header raises this twice:

    [2015-07-10 20:03:25,658: ERROR/ForkPoolWorker-1] Chord callback '3d0dd6ef-b966-40a5-9aff-213a9e38d8bc' raised: ValueError('3d0dd6ef-b966-40a5-9aff-213a9e38d8bc',)

Which happens because around line 550 in celery/backends/base.py, there are no deps returned.
```
547  	        gid = task.request.group
548  ->	        if not gid:
549  	            return
550  	        key = self.get_key_for_chord(gid)
551  	        try:
552  	            deps = GroupResult.restore(gid, backend=task.backend)
553  	        except Exception as exc:
```

I'm throwing darts, so while I was in the debugger I tried to get GroupResults for the corollation ID, but that failed as well. So I think either that `task.request.group` value needs to be different, or something needs to have gotten in to the backed (redis for me) before we get to this code.
