### ISSUE TITLE
Worker not shutting down properly

### ISSUE THREAD

**Issue by john-jana** [celery/celery#2232]
Hi,
We are running celery (v 3.1.10) with gevent (v 1.0.1) and using a redis backend.  When trying to shutdown the worker (using SIGTERM), we keep seeing the WorkerShutdown exception, except that it only kills the individual task (which doesn't seem like the correct behaviour) - the worker just continues processing new tasks.  This doesn't happen every time (sometimes is shuts down normally), and we have been unable to replicate the problem in a dev environment.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
