### ISSUE TITLE
Celery + Rabbitmq heartbeat

### ISSUE THREAD

**Issue by jclark360** [celery/celery#2236]
We've ran into an issue while doing some testing with 2 rabbitmq instances sitting behind an AWS elb to replace our redis cluster.   The issue is that the ELB will timeout the connection that celery has to the broker while putting messages into the queue...  Below is a more logical explanation..
- Workflow queues a bunch of celery tasks
- Workflow waits for those tasks to complete
- Workflow starts to queue more celery tasks 
- Connection is already dropped by the ELB and celery probably reconnects and we lose a bunch of tasks 
- Somehow celery reconnects to the broker and a portion of the tasks make it through.

To see what was going on we set some debug output around each method.delay() call we were doing and observed that after a couple of hundred calls to the task.delay() one of the calls will take tens of seconds, which is where its probably timing out on the socket and reconnecting.  Those messages are lost, anything after that point is fine.

We have all the reliability stuff turned on, acks late, heartbeat... Is this a real issue or just life with rabbit behind a elb with celery?  Note that if we connect directly to the rabbit instance, there are zero issues.

**Comment by slowder** [comment]
>However, if you enable confirm_publish on your celery configuration it seems to solve the problem (with a performance penalty).

For reference, the solution mentioned above is this:

`BROKER_TRANSPORT_OPTIONS = {'confirm_publish': True}`

**Comment by aniket03** [comment]
@jclark360 But why does ELB reset connection with the celery workers. And can we not set the reset time to prevent the same. Or if possible use heartbeat time > reset time used by ELB.

**Comment by ggchangan** [comment]
@ask is there any method to solve celery+aws elb+redis where the airflow worker will hung when the tcp connections terminated by aws elb after tcp idle time  configured on aws elb.

**Comment by auvipy** [comment]
ask no longer maintain this project actively. if you have any question post it on mailing list or IRC
