### ISSUE TITLE
Redis broker not working. Celery 3.1.13

### ISSUE THREAD

**Issue by sv1jsb** [celery/celery#2240]
Hi all,

I've set:
BROKER_URL='redis://localhost:6379/0'

and when the task is to "transferred" to redis i get this error:

<pre>
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
    conn = self.Connection(**opts)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/andreas/venvs/custom/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
</pre>

which shows that it's using pyamqp and not redis for transport.

Flower shows correct configuration and Transport.

When broker changed to aqmp everything works fine.

Setup:
Celery 3.1.3
Django 1.6.7
Ubuntu 14.04

Best regards,
Andreas

**Comment by picturedots** [comment]
Same problem not being able to connect to Redis.  I'm running
Django 1.8.1
celery 3.1.18
Redis 2.8.17

When I have the setting
BROKER_URL = 'redis://localhost:6379/0'
I'm getting an except that shows ampq connection errors.  This problem will go away if I turn on rabbitMQ and restart everything with BROKER_URL removed.

Strangely enough my celery worker task, started with
celery -A wine_kloud worker -l info
successfully connects with Redis, showing 
[2015-05-17 03:19:27,491: INFO/MainProcess] Connected to redis://localhost:6379/0

It seems like this is the same bug as https://github.com/celery/celery/issues/1655
which speculates the issue is related to the way that environment variables are initialized from inside Django.  My celery.py is exactly as specified in the documentation.

For now I'm going to switch to rabbitMQ, which is annoying because I need to use Redis for something anyway.

**Comment by approxit** [comment]
I had similar problem with RabbitMQ. I spend 3 days digging this issue with same traceback and I found the answer! Finally!

Shared tasks was causing the problem. My project was not properly configured to use shared tasks. I just accidentally ommit proj/proj/\__init\__.py configuration. [Let's go back to the docs!](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html):

**proj/proj/\__init\__.py:**

```python
from __future__ import absolute_import

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app
```

**Comment by zekus** [comment]
any idea on how to fix this?

**Comment by ask** [comment]
DId you try the solution above?

Shared tasks needs your app to be initialized first, in under no circumstance should you add `django.setup` to the celery.py file.

**Comment by zekus** [comment]
it was an initialization issue due to the weird directory configuration I inherited in the project I am working on. it's solved for me creating a project directory as per modern django standard directory layout and moving django configs together with the celery configuration in the project folder.

**Comment by luisincrespo** [comment]
I'm running into the same problem:

Django==1.9.6
celery[redis]==3.1.23

My `proj/celeryapp.py`:

```
from __future__ import absolute_import, unicode_literals

import os

from celery import Celery

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config')
os.environ.setdefault('DJANGO_CONFIGURATION', 'Local')

import configurations  # noqa
configurations.setup()

from django.conf import settings  # noqa

app = Celery('proj')

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

My `proj/__init__.py`:

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app  # noqa
```

My settings:

```
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'US/Eastern'
```

My `proj/app/tasks.py`:

```
from celery.decorators import task

@task(name='test')
def test():
    return 2 + 2
```

The celery worker is running as expected, and discovering my tasks, but whenever I actually perform a `test.delay()` in my django code, I get the following error:

`Exception Value: [Errno 61] Connection refused`

As it is trying to connect to:

`amqp://guest:**@127.0.0.1:5672//`

And that is not the correct `BROKER_URL`. Any clues about what I'm missing?

Thanks.

**Comment by DeSiden** [comment]
Same problem here

Django 1.10.2
Redis 3.2.5
Celery 4.0.0
Python 3.5

Celery starts showing redis as transport, but when i use a .delay() shared_task it says "_[Errno 111] Connection refused_" and in django debug log it says "_Exception Location: 	/usr/lib/python3.5/site-packages/amqp/transport.py in _connect, line 144_" so it seems to be using amqp and not redis at all.

**Folder structure**
```
webapp # inside this i'm running celery --app=celeryapp:app worker --loglevel=INFO -E
    + apps
    |    - app
    |       -tasks.py
    - __init__.py
    - settings.py
```

__init.py__
```
from __future__ import absolute_import, unicode_literals
from .celeryapp import app as celery_app

__all__ = ['celery_app']
```
**settings.py**
```
BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```
**celeryapp.py**
```
from __future__ import absolute_import, unicode_literals
import os
import django
from celery import Celery, shared_task
from django.conf import settings

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')
django.setup()

app = Celery('.') # because i'm running celery in the same folder of celeryapp.py
app.config_from_object('settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```
**apps/app/tasks.py**
```
from __future__ import absolute_import
from celery import shared_task

@shared_task
def test(param):
	print("celery test")
```

If someone knows how to solve this it would be appreciated, thanks

**Comment by amdrgoncalves** [comment]
Hi guys. I had a similar problem of connection refused with Redis + celery + django. For me, the problem was that django settings were not being set before the task call. So default behavior of celery worker is to try to connect to RabbitMQ and so the connection refused problem. I fixed by forcing django settings to be loaded before the task is ran:

import os
import sys
import django 

sys.path.append("/home/ubuntu/MYPROJECT")
os.environ["DJANGO_SETTINGS_MODULE"] = "MYPROJECT.settings"
django.setup()

That fixed for me.  I hope it helps.

**Comment by VinayMandal** [comment]
If anyone facing the hangs issue while using shared_task as Hecsall faced, please check the answer I have in https://stackoverflow.com/questions/30272845/celery-worker-hangs-without-any-error#51627068.

**Comment by mhipo1364** [comment]
I think it's `CELERY_BROKER_URL` not `BROKER_URL`
