### ISSUE TITLE
cannot import name Celery issue with Django project layout

### ISSUE THREAD

**Issue by thenewguy** [celery/celery#2243]
On Ubuntu 12.04 running Python 2.7.3 using celery==3.1.13 I get the following error when setting up celery:
```
ImportError: Could not import settings 'foo.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name Celery
```

My `foo.celery` file is written as suggested in http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html 

```
from __future__ import absolute_import

import os

from celery import Celery

from django.conf import settings

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'foo.settings')

app = Celery('foo')

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

```

Renaming `foo.celery` to `foo.celery_config` fixed the issue for me.

Before the rename the project worked fine in other environments.  Not sure why the absolute import isn't being respected, but renaming the file seems to have worked for me.

Is there any particular reason the docs suggest naming the config file with the same name used for the celery package?

**Comment by Deepakdubey90** [comment]
Hi,
i'm getting import error "ImportError: cannot import name 'Celery'". in celery.py file.
how to fix it..?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
