### ISSUE TITLE
Niether `group` or `chord` can be inspected while used inside `chain`

### ISSUE THREAD

**Issue by pySilver** [celery/celery#2246]
Hello,

I'm experiencing strange behaviour while using group inside a chain.
Environment:
* Result Backend: Redis
* CELERY_IGNORE_RESULT: True/False (does not matter)
* Celery version: 3.1.14

*tasks.py*
```python
from project.celery import app

@app.task
def x_main_image():
    logger.warn("Downloading main image..")
    sleep(10)
    return True


@app.task
def x_get_image(i=0):
    logger.warn("Getting additional image %s" % i)
    sleep(10)
    return True


@app.task
def x_thumbnails():
    logger.warn("Creating thumbs for all collected images")
    sleep(10)
    return True


@app.task
def x_status():
    logger.warn("Discovering status for product")
    sleep(10)
    return True

def dummy_chain():
    return chain(
        x_main_image.si(),
        group(x_get_image.si(i) for i in range(5)),
        x_thumbnails.si(),
        x_status.si(),
    )()
```

So I want to:
* execute `x_main_image`
* nextly, couple of `x_get_image` tasks in parralel
* then create thumbnails for collected images using `x_thumbnails`
* then change some object status using `x_status`

Execution works fine, however I also need an abiltiy to terminate running tasks at any point of time – and this does not work :(

sample code:
```python
In [1]: from project import tasks
In [2]: x = tasks.dummy_chain()
In [3]: while x:
   ...:     print x.task_name, x.task_id
   ...:     x = x.parent
   ...:
project.tasks.x_thumbnails 00b0d7a2-b1ec-4065-bee7-bcefe09300c0
project.tasks.x_main_image 12ead8ba-025c-446d-a73d-df57cfb201ce
```

So I'm missing tasks for
* group (expecting GroupResult)
* x_status

I assume this two were somehow converted into chord, however I cannot retrieve them from anywhere...

I've also tried something like this:
```python
@app.task
def _noop(*args, **kwargs):
    logger.warn("Group task has finished!")
    return True

def dummy_chain():
    return chain(
        x_main_image.si(),
        chord(group(x_get_image.si(i) for i in range(5)), _noop.si()),
        x_thumbnails.si(),
        x_status.si(),
    )()
```

But this neither solves the situation:

```python
In [1]: from project import tasks

In [2]: x = tasks.dummy_chain()

In [3]: while x:
   ...:     print x.task_name, x.task_id
   ...:     x = x.parent
   ...:
project.tasks.x_status 9c82d579-80ea-415b-ad4c-7c2ab427c7d4
project.tasks.x_thumbnails 2d806b58-6b96-410a-ab5d-01e17736efc6
project.tasks._noop ed5c81aa-ae33-4afe-88b5-94690eea40e8
project.tasks.x_main_image 780c6c51-e094-4a6c-b183-39ceae7a0841
```

while `project.tasks._noop` is here I cannot access it's parent, so I cannot retrieve GroupResult and revoke it when it's required.

Is it desired behaviour?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Maybe it's fixed in master, we'll see if it comes back after 4.0 release.
