### ISSUE TITLE
Celery workers die when django project is on pythonpath

### ISSUE THREAD

**Issue by edmcdonagh** [celery/celery#2247]
Windows 7 Pro 64 bit; Python 2.7.8; Django 1.6; Celery 3.1.13

If my django project is installed using pip (current version `pip install --pre openrem==0.4.3b5`, requires django 1.6 installed first as not ready for 1.7), then Celery can be started, connects to RabbitMQ, imports tasks, then each worker is killed as soon as it is created.

OpenREM folder structure has an openrem top folder with an openrem project folder inside, as per typical Django project.

If the top folder has a different name to the inner project folder, or if the top folder is not on the Python path (ie is placed in Documents or similar), then Celery starts and works normally.

More information at https://groups.google.com/forum/#!topic/celery-users/i4sxrsfFStc

Works fine on Ubuntu (system wide install or virtualenv), doesn't work on Win7 (system wide install or virtualenv, tried two computers).

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
