### ISSUE TITLE
Celery doesn't start any nodes when used with --autoreload

### ISSUE THREAD

**Issue by pashinin** [celery/celery#2249]
I wanted to use this `--autoreload` option. But just after I add it I have:

```
celery -A proj status
Error: No nodes replied within time constraint.
```

Before that:

```
celery -A proj status
celery@hostname: OK

1 node online.
```

So now when I call `celery call tasks.taskname` RabbitMQ recieves this message (I can see this). But will only execute it when I restart Celery without `--autoreload`

Celery is started as `celery -A proj worker --loglevel=INFO --autoreload`. Used inside a Django 1.7 project.

PS: worker.log has absolutely the same log when I run the command - tasks are discovered, and this message is printed:

```
[2014-09-10 18:46:27,230: WARNING/MainProcess] celery@hostname ready.
```

But no messages are delivered to this worker from RabbitMQ in case of `--autoreload`.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Autoreload will be undocumented in 4.0 release
