### ISSUE TITLE
After upgrade to Celery 3.1 our messages are not being picked up. 

### ISSUE THREAD

**Issue by gotpredictions** [celery/celery#2256]
We have 8 workers in the master queue, of which one is currently used.  It is waiting for completion of 3 other messages submitted into the queue, and we can see them with inspect reserved as below. 

However they are not being handed off to any worker even though 7 of them are free.  I understand a single machine may pre_fetch them, but that machine itself has 3 more workers doing nothing.  It only started happening upgrade to 3.1 from 3.0 

Please advise us if anything can be done? 

(analytics-server_env)gnana@ip-10-0-15-117:/opt/gnana/analytics-server$ celery -A gnana inspect reserved
-> b@ip-10-0-15-117: OK
    - empty -
-> w@ip-10-0-14-184: OK
    - empty -
-> m@ip-10-0-14-184: OK
    - empty -
-> w@ip-10-0-15-117: OK
    - empty -
-> b@ip-10-0-14-184: OK
    - empty -
-> m@ip-10-0-15-117: OK
    * {u'args': u"[[u'xxx', u'xxx.com', u'administrative.domain']]", u'time_start': None, u'name': u'tasks.answers.combined_results_for_day', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'master', u'exchange': u'master'}, u'hostname': u'm@ip-10-0-15-117', u'acknowledged': False, u'kwargs': u"{u'target_key': u'main', u'daily_dose': [], u'target': u'bookings', u'trace': u'3c63a2a8-5ddc-4054-b9f8-7c8783b27032'}", u'id': u'd405d9e0-067a-47d6-8bea-9d8999042e61', u'worker_pid': None}
    * {u'args': u"[[u'xxx', u'xxx.com', u'administrative.domain']]", u'time_start': None, u'name': u'tasks.answers.combined_results_for_day', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'master', u'exchange': u'master'}, u'hostname': u'm@ip-10-0-15-117', u'acknowledged': False, u'kwargs': u"{u'target_key': u'main', u'daily_dose': [], u'target': u'bookings', u'trace': u'3c63a2a8-5ddc-4054-b9f8-7c8783b27032'}", u'id': u'0362d63c-45f1-45f8-b8c3-6c428a22e0f1', u'worker_pid': None}
    * {u'args': u"[[u'xxx', u'xxx.com', u'administrative.domain']]", u'time_start': None, u'name': u'tasks.answers.combined_results_for_day', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'master', u'exchange': u'master'}, u'hostname': u'm@ip-10-0-15-117', u'acknowledged': False, u'kwargs': u"{u'target_key': u'main', u'daily_dose': [], u'target': u'bookings', u'trace': u'3c63a2a8-5ddc-4054-b9f8-7c8783b27032'}", u'id': u'5bb8fe84-e54d-414d-a312-e466445accd2', u'worker_pid': None}
(analytics-server_env)gnana@ip-10-0-15-117:/opt/gnana/analytics-server$

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
