### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by eromoe** [celery/celery#2267]
I'm using  Django Database as broker on windows 7.
According to the doc http://docs.celeryproject.org/en/latest/getting-started/brokers/django.html
I add below code to settings:
```
INSTALLED_APPS += ('kombu.transport.django',)
BROKER_URL = 'django://'
```

But it throw error `[Errno 10061] No connection could be made because the target machine actively refused it` when I call  `some_function.delay(*args)`

It seems celery could not connect to django db.Doesn't it `uses the Django DATABASE_* settings for database`?  How can I solve this problem?

**Comment by alecr95** [comment]
For anyone else having this problem, I had a similar problem which ended up being because my __init__.py file was not set up correctly. I fixed it by changing the contents of the file to: 

```
from __future__ import absolute_import

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app  # noqa
```
