### ISSUE TITLE
Attempting to get task data from backend when `CELERY_ALWAYS_EAGER=True` should raise an exception

### ISSUE THREAD

**Issue by turtlemonvh** [celery/celery#2275]
## Short description

Getting the result of a task according to [the FAQ instructions](http://docs.celeryproject.org/en/v2.2.5/faq.html#how-do-i-get-the-result-of-a-task-if-i-have-the-id-that-points-there) fails in a non-obvious way when `CELERY_ALWAYS_EAGER` is `True`.

## Full description

In `celery.app.task.Task.apply_async`, if `CELERY_ALWAYS_EAGER` is `True`, `Task.apply` is called instead of `app.base.Celery.send_task`.  `send_task` hits the backend store (the queue) but `apply` just runs the task locally.

*This is fine* (but could be improved upon - see "Solution Option 3", below).  It makes sense that retrieving the status of a task from the backend would not be possible if the backend is never touched.

Unfortunately, functions for checking state fail in a non-obvious way that can be confusing to users.

The base function (see `celery.backends.database.DatabaseBackend._get_task_meta_for`) defaults to returning a new `Task` object with `status = states.PENDING` and `result = None` if nothing is found in the backend. This function is called by `BaseBackend.get_task_meta`, which is called by `BaseBackend.get_status`, which is the function that is used in the `AsyncResult.state` property to get task state, and also in [`AsyncResult.ready()`](http://celery.readthedocs.org/en/latest/reference/celery.result.html#celery.result.AsyncResult.ready).

Thus, for tasks which the system does not know about, the result of a query for their state is not an `Exception`, but a new object with a valid state and empty results field.

### Solution Option 1

I think the most straightforward solution is to be explicit and raise an error if the user attempt to check the state of a task via the backend when `CELERY_ALWAYS_EAGER` is `True`.

This could be fixed by raising an exception (possibly `QueueNotFound`, maybe a new exception) in `celery.backends.base.BaseBackend.get_task_meta` if `CELERY_ALWAYS_EAGER` is `True`.  For example:

    if self.conf.CELERY_ALWAYS_EAGER:
        raise QueueNotFound("Cannot access backend when CELERY_ALWAYS_EAGER is True")

Without this change, [this FAQ response](http://docs.celeryproject.org/en/v2.2.5/faq.html#how-do-i-get-the-result-of-a-task-if-i-have-the-id-that-points-there) can be a bit confusing:

> How do I get the result of a task if I have the ID that points there?
> 
> Answer: Use Task.AsyncResult:

When `CELERY_ALWAYS_EAGER` is `True`, it looks like the task is hanging because the state is always `PENDING`, even though the execution may have succeeded.

### Solution Option 2

Another path forward is to update the docs to explicitly mention that a task **cannot be retrieved** from celery when running with `CELERY_ALWAYS_EAGER`.  The user must store the result of running `apply_async` on the task.

I don't consider this a real solution, but more of a stopgap if more discussion is required.

### Solution Option 3

Store `EagerResult` objects in celery's cache and allow the user to retrieve results from there.  Since celery is already looking in the cache in `BaseBackend.get_task_meta` this should be reasonable to implement.

## Conclusion

I hope this format of issue is acceptable.  I didn't see where this specific scenario fit in the [Contribution Guidelines](https://github.com/celery/celery/blob/master/CONTRIBUTING.rst).

Please let me know if more documentation is required here, or if an example application demonstrating the issue would be helpful.

**Comment by anton-107** [comment]
+1 for this issue:
it's impossible to test the APIs that use celery for async jobs with CELERY_ALWAYS_EAGER set to true (because when you retrieve a task by a task id this task's status will always be PENDING, even though the task is being run)

**Comment by birdonfire** [comment]
@turtlemonvh thank you for the awesome writeup. I just ran into this, and finding this issue prevented further interaction between my head and my desk.

**Comment by turtlemonvh** [comment]
Awesome - thanks @ask!
