### ISSUE TITLE
[RFE] CELERYD_WAIT_ON_SHUTDOWN

### ISSUE THREAD

**Issue by bowlofeggs** [celery/celery#2277]
It appears that a Celery worker will wait for any current task it has to complete before responding to a shutdown event. This is a sane default, but it would be nice if users could configure the worker to cancel the current task when it receives SIGTERM rather than waiting for it to complete.

I propose a new boolean setting called CELERYD_WAIT_ON_SHUTDOWN. It should default to True to maintain current behaviour, but if users wish to set it to False it would stop the worker much more quickly.

We (The Pulp Team) may be able to find some time to contribute a pull request to accomplish this. If you (The Celery Team) agree that this is a good proposal, let us know via a comment on here and we will see if we can get started on it.

Thanks for all your hard work!

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
