### ISSUE TITLE
celery daemon crashes while unpickling message from a worker

### ISSUE THREAD

**Issue by 1st1** [celery/celery#2294]
Whole celery daemon crashes if a worker returns a message that cannot be unpickled.

The problem is in the bellow snippet of code of `asyncpool.ResultHandler._recv_message()` method:

```python
if readcanbuf:
    message = load(BytesIO(bufv))
else:
    bufv.seek(0)
    message = load(bufv)
if message:
    callback(message)
```

Basically, the code assumes that whatever was pickled can be always unpickled. However, this is wrong for some python2 cases, like the following one:

```python
import pickle

class MyError(Exception):
    def __init__(self, code):
        self.code = code

pickled = pickle.dumps(MyError(42), -1)

# The script will crash on this line:
pickle.loads(pickled)
```

So if a worker uses some library which has an exception that lacks a proper `__reduce__`, you have a chance of celery master process being crashed too.

**Comment by thedrow** [comment]
I don't think we have a way properly detect this problem.
I have to agree with @ask.
