### ISSUE TITLE
celery multi or daemon in a virtual environment

### ISSUE THREAD

**Issue by dblado** [celery/celery#2308]
I've started experimenting w/ celery and running into an issue that I thought you might be able to help me with -- secret code for all the google searching has turned up nothing  :)

My environment:
/opt/vendop/virtenv (symlink to a dated virtenv for easy rollback)
/opt/vendop/live (django app symlink to something like www6 for easy rollback)

This work just fine

```
$ celery worker -A vendop
```

This however does not:

```
$ celery multi restart w1 -A vendop
```

Using 'multi' starts the process:

```
/opt/vendop/virt_3_6_14/bin/python27 -m celery worker -n w1@ip-10-165-3-72 -A vendop --logfile=w1.log --pidfile=w1.pid
```

When I run that I get a long stacktrace that ends with:

```
ImportError: No module named urls
```

Sounds to me like it's not running in the virtual environment -- evidenced further by this running just fine (just the above command w/ the path to python27 removed):

```
celery worker -n w1@ip-10-165-3-72 -A vendop --logfile=w1.log --pidfile=w1.pid
```

Any thoughts would be greatly appreciated.  Thanks!

**Comment by kristaps** [comment]
I just experienced the problem today. What worked for me was to use the undocumented start command `--executable` option to set the desired python interpreter:
```
celery multi start --executable=/my/venv/bin/python ...
```

**Comment by istinspring** [comment]
got same problem in 2019

```/Users/myuser/.virtualenvs/facial/bin/python -m celery multi start 1 -A grabscrapers.work.celery --logfile=var/log/ig_profiles_%n.log -pidfile=var/run/ig_profiles_%n.pid
celery multi v4.4.0rc3 (cliffs)
> Starting nodes...
/usr/local/opt/python/bin/python3.7: No module named celery
        > celery1@bookair.local: * Child terminated with exit code 1
FAILED```

celery==4.4.0rc3
