### ISSUE TITLE
celeryd service _uuid() not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by danigosa** [celery/celery#2311]
The function:
```bash
_chuid () {
    su "$CELERYD_USER" -c "$CELERYD_MULTI $*"
}
```
Does not do anything on Ubuntu 14.04 Trusty Server. **One working solution is using sudo instead(only tested in Trusty)**:

```bash
_chuid () {
    sudo -u $CELERYD_USER bash -c "$CELERYD_MULTI $*"
}
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by rogerthat94** [comment]
I actually had this exact issue today on Ubuntu 14.04.4 LTS. I recreated the user I was running celery under with the instructions in this tutorial: http://tech.willandskill.se/using-celery-with-django-and-redis-on-ubuntu-14-04/

I believe my issue was that the user I was running celery with did not have a home directory.
