### ISSUE TITLE
"celery purge" only works on one queue

### ISSUE THREAD

**Issue by SeanHayes** [celery/celery#2321]
I'm using celery==3.1.11 with django-celery==3.1.10 and Django==1.6.5.

Running "./manage.py celery purge --help" says:
"Erase all messages from all known task queues."

I ran "./manage.py celery purge". I had about 600000 messages in a queue, but got the following message:
"No messages purged from 1 queue"

Eventually I found this, which worked for the queue:
"./manage.py celery amqp queue.purge myqueue"

**Comment by risicle** [comment]
This combined with the fact that the `purge` command doesn't take a `-Q` argument are a serious failing.

**Comment by sidja** [comment]
Those tasks might have been already prefetched by workers. To find out is this so, try to run amount of tasks more than active workers multplied by prefetch multiplier (see below), and check what result is returned by celery.control.purge(). You can control amount of prefetched tasks using config parameters  [CELERYD_PREFETCH_MULTIPLIER ](http://docs.celeryproject.org/en/latest/userguide/optimizing.html#reserve-one-task-at-a-time)and CELERY_ACKS_LATE.


CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
