### ISSUE TITLE
Chord for a group with retries invokes callback before group finishes

### ISSUE THREAD

**Issue by sukrit007** [celery/celery#2324]
Celery : **3.1.16 **

**Given**: Chord with group tasks(a, b) and call back  c
chord ( group(a,b), c)

**And**: Task a, b are retryable (They retry on exception)

**When**: I call chord ,  the callback task c gets invoked  and  a throws exception and retries.

**Then**: Chord does not wait for results for the retry and calls the callback even before task "a" could finish.

Ideally I would expect callback to be called when a,b finish the retry logic and are successful.

**Comment by thedrow** [comment]
It has been a very long time since this issue was opened and it had no feedback since.
We'd love to get this resolved but we need your help in doing so.
I'm going to close this. Feel free to comment with more details and I'll reopen.
