### ISSUE TITLE
Chords sometimes don't return result

### ISSUE THREAD

**Issue by dbrgn** [celery/celery#2326]
I have a lot of chord based tasks running on a production server. Each task in the chord returns a dictionary of items, one of them being the "account_id".

Sometimes, this is what the result data in the chord callback looks like:

```python
In [4]: [d.get('account_id') for d in data]
Out[4]: 
[None,
 1539274129,
 1309375512,
 7692079390,
 9570420075,
 3436773248,
 1606634713,
 4535015133,
 1957718274,
 3276797600]
```

This is what a regular task return value looks like:

```python
In [5]: data[-1]
Out[5]: 
{'ad_url_count': 18,
 'user_id': 14,
 'check_fails': [],
 'check_warnings': [],
 'account_id': 3276797600,
 'keyword_url_count': 0}
```

But in the first case the following is returned:

```python
In [6]: data[0]
Out[6]: {'hostname': 'celery@celery-0.ip-172-31-0-93', 'pid': 28209}
```

Any ideas what the problem could be? I'm on Celery 3.1.15.

**Comment by inactivist** [comment]
This issue's current state is 'open' yet the commit message for d6c0407 says it closes this issue.  Please clarify.
