### ISSUE TITLE
PENDING tasks are not abortable

### ISSUE THREAD

**Issue by dbrgn** [celery/celery#2335]
I'm working on a system where I use lots of chords with long-running tasks in the head. I want to be able to abort them.

I played around with the AbortableTasks from contrib, and while that works great for STARTED tasks, it doesn't seem to work for PENDING tasks. The tasks' state is changed to ABORTED, but apparently the `is_aborted()` flag still returns `False`, as the tasks are still processed even though I check for that flag at the beginning of the task execution.

Using `.revoke()` is not a solution either because it prevents the chord callback from running.

Would it be possible to make PENDING tasks abortable (meaning that the `is_aborted()` flag works for PENDING tasks too)?

**Comment by dolugen** [comment]
> I've been planning to remove celery.contrib.abortable
When is this going to happen? Are you suggesting people should implement this themselves? I discovered this package so late and now wondering if I should start using it.

**Comment by ask** [comment]
@dolugen I guess you can use it, as long as you don't use `CELERY_TRACK_STARTED` and don't store any other custom states from outside of the task class.

If I remove it in 4.0 then I will just upload a library on PyPI to support it, or provide a short copypaste solution that you can change to.

**Comment by ask** [comment]
Much better if you can store the flag in redis of course :)

**Comment by dolugen** [comment]
@ask Oh well, I do use `CELERY_TRACK_STARTED` and there is a custom state for tracking progression.

> Much better if you can store the flag in redis of course :)

Ok, so that it wouldn't interfere with the actual Celery states.

**Comment by dolugen** [comment]
> store the flag in redis

To `abort()` and check `is_aborted()` with that would mean changing `AbortableAsyncResult`'s methods ([set to, read from redis](https://github.com/celery/celery/blob/master/celery/contrib/abortable.py#L136)). Or is there a cleaner way?
