### ISSUE TITLE
test run and manage.py

### ISSUE THREAD

**Issue by idella** [celery/celery#2338]
Running the latest version testsuite results in

Ran 1690 tests in 37.930s

FAILED (failures=1, errors=61, skipped=15)

I don't know what happened in recent releases but something seems to have changed.
The errors are full of 

    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.

which in my experience means the setup for django requirements are simply not present.  I added exporting of DJANGO_SETTINGS_MODULE="django.conf" which had no impact.  There are in fact 3 manage.py files all under the examples folder. Do you think you could work the package to have manage.py included and ready to fore in the source so the testsuite runs out of the box?  There may be some things not present in my setup which in my exp. means the testsuite lacks robustness.  Run by straight 'nosetests' or by python setup.py test yielded the same result from the source.  Packages the like of south generally require a manage.py to run the testsuite. There are others but i don't have a ready list at hand.

The test phase in this package will be left restricted from this point until it yields at minimum some acceptably low fail / error rate.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
