### ISSUE TITLE
Chain as chord body on redis broken (when new_join=1)

### ISSUE THREAD

**Issue by cheif** [celery/celery#2339]
Hi, I'm using celery with a redis-backend and just tried to create a chord which had a chain as a callback, but it seems like this implementation is broken.

```
@task
def ret_one():
    return 1

@task
def chain1(res):
    return res*2

@task
def chain2(res):
    return res+2

tasks = [ret_one.s() for _ in range(10)]
body = chain1 | chain2

chord(tasks, body).delay()
```

In this case the chord-call seems to fail, since the redis handler for result tries to get 'chord_size' from the signature of the chain, which raises KeyError. https://github.com/celery/celery/blob/master/celery/backends/redis.py#L222

A simpler example:

```
from celery.canvas import maybe_signature
d = {'subtask_type': 'chain', 'kwargs': {'tasks': ()}, 'options': {}, 'chord_size': 11}
s = maybe_signature(d)
s['chord_size'] <== raises KeyError
```

This seems to work when subtask_type isn't set, i.e. the callback is a normal task. But raises on all different types of tasks.

I'm not really sure if this is a bug, or if I'm doing something wrong, but it seems like the other backends don't look for callback['chord_size'] atleast, and the documentation doesn't mention that you can't use chains as the body for a chord.

**Comment by aarcro** [comment]
https://github.com/celery/kombu/pull/497

Fix for kombu when using this option.
