### ISSUE TITLE
Windows: Chains broken with Celery 3.1.16 and Redis broker

### ISSUE THREAD

**Issue by flavianh** [celery/celery#2344]
File "[python install]\lib\site-packages\amqp\transport.py", line
95, in __init__
    raise socket.error(last_err)

Yes, it calls a function from amqp even though I set redis as a broker and a backend
 -------------- celery@Jack_Dalton v3.1.1 (Cipater)
---- **** -----
--- * ***  * -- Windows-8-6.2.9200
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> broker:      redis://:**@distant.redis.server:6379
0
- ** ---------- .> app:         my_app:0x2a65a50
- ** ---------- .> concurrency: 2 (prefork)
- *** --- * --- .> events:      OFF (enable -E to monitor this worker)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery

I reverted to Celery 3.1.1 and it works fine. 

Is 3.1.16 __really__ stable?

**Comment by RemiDesgrange** [comment]
@ask can you elaborate please ? I still have the bug on win7/8 and celery 3.1.19 with this sample :
```python
# file celeryTest.py
import json
from flask import Flask, Blueprint, abort, jsonify, request, session
from celery import Celery


app = Flask('celeryTest')
app.config.update(
SECRET_KEY = 'not_a_secret',
REDIS_URL = 'redis://localhost',
CELERY_BROKER_URL='redis://localhost',
CELERY_RESULT_BACKEND='redis://localhost',
)

def make_celery(app):
    celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    TaskBase = celery.Task
    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery

celery = make_celery(app)

@celery.task
def add(x, y):
    return x + y

@app.route("/")
def hello_world():
    res = add.apply_async((1,2), link=add.s(10))
    return str(res.get())

if __name__ == "__main__":
    app.run(debug=True)
```

Work perfecly on linux and not on windows, in advance, thanks !!

**Comment by ask** [comment]
You're using `app.conf.update` here which means the configuration changes need to be pickled,
it's better to use `app.config_from_object('proj.celeryconfig') for a configuration module called `celeryconfig.py`, or `app.config_from_object('celeryTest:app.conf')` to use the flask app config directly.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
