### ISSUE TITLE
Celery task dispatch on app engine

### ISSUE THREAD

**Issue by pbhowmic** [celery/celery#2345]
Here is my scenario. My celery worker is running on Google Compute Engine which is also running my RabbitMQ broker. my web-pages are being handled by Google App Engine. I want to dispatch tasks from GAE that the worker on GCE operates on. I run into issues with Celery on GAE mostly around billiard because GAE is hostile to multiprocessing and does not support ctypes. Never mind the ctypes issue now but I really see no reason *task dispatch* should not happen from GAE, logically there is no reason why multiprocessing should be allowed to get in the way. What can you do to help that happen?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
