### ISSUE TITLE
Celery doesn't clean up worker child processes

### ISSUE THREAD

**Issue by makmanalp** [celery/celery#2353]
Hello,

Caveat: this is a bit of a stretch since I'm not sure if this is the right place to ask - or whether if this is expected behavior. Worst case, we can close the bug and leave it for posterity.

I have some celery tasks that spawn selenium webworkers to do some tasks, and in production I've often observed those tasks ending, but the child processes spawned from those tasks remain.

This behavior doesn't seem to happen without autoscale for some reason, but that may be tangential and only because I manage to continuously saturate CPU with autoscale enabled.

The issues seem to start happening when the celery tasks throw SoftTimeLimitExceeded. 

Then the autoscaling winds down, and workers are killed, but the phantomjs processes remain:

```
ubuntu   18063  0.0  0.8 2273120 33584 ?       Sl   20:45   0:00 /usr/lib/phantomjs/phantomjs --debug=false --load-images=false --disk-cache=true --max-disk-cache-size=100000 --webdriver=33706
ubuntu   20444  0.0  0.9 2273060 35584 ?       Sl   21:36   0:00 /usr/lib/phantomjs/phantomjs --debug=false --load-images=false --disk-cache=true --max-disk-cache-size=100000 --webdriver=38956
```

Is there (or should there be) some behavior that dictates that child processes of workers should be killed?

The odd thing is that when I check those zombies, their ppid is set to 1, but as they're running it seems that they're actually set to the worker.

Here's the actual code being used: https://github.com/cid-harvard/atlas-economic-complexity/blob/5b16429548ed1e7942bdfccc81ba07bf451d53b5/django_files/atlas/celery_tasks.py#L62

I can spend more time fiddling and trying to whittle down a more reproducible test case later on if needed.

Thanks,
~mali

**Comment by JioHooney** [comment]
@makmanalp  Hi,
How did you solve it?

**Comment by makmanalp** [comment]
@JioHooney I don't remember, unfortunately!
