### ISSUE TITLE
group([chain(group(task(), task()), group(...)), chain(group(...), group(...))]) construct never finishes

### ISSUE THREAD

**Issue by mittagessen** [celery/celery#2354]
I've got several chains containing groups which should run in parallel. As far as I can tell these chains run perfectly well (celery -l DEBUG and generated output on the file system)  but the ready() function of the GroupResult and AsyncResults returns always false. Unfortunately, the chains' children fields are empty making debugging what is happening inside the inner groups quite hard. 

A very simple test case displaying this behavior:

```python
from celery import Celery

app = Celery(main='tasks', broker='redis://')
app.config_from_object(celeryconfig)

@app.task(name=u'A')
def A():
    print('A')
```

A test case that fails:

```python
>>> from celery import group, chain
>>> chain1 = chain(group([tasks.A.si(), tasks.A.si()]), group([tasks.A.si(), tasks.A.si()]))
>>> r = group([chain1, chain1])()
>>> r.save()
...
>>> r.ready()
False
>>> r.results[0].ready()
False
```

On the other hand if the interior group contains just a single task the return values are as expected:

```python
>>> chain1 = chain(group([tasks.A.si()]), group([tasks.A.si()]))
>>> r = group([chain1, chain1])()
>>> r.save()
>>> r.ready()
True
>>> r.results[0].ready()
True
```

I've tried running this example against 3.1.16 an the current git master branch using the redis message broker:

```
software -> celery:3.1.16 (Cipater) kombu:3.0.23 py:2.7.8
            billiard:3.3.0.18 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379

BROKER_URL: 'redis://127.0.0.1:6379//'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ENABLE_UTC: True
CELERY_TIMEZONE: 'Europe/Berlin'
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: 'redis://127.0.0.1:6379'
```

**Comment by asaidomar** [comment]
Perhaps I encounter the same issue http://stackoverflow.com/questions/28191762/celery-workflow-chain-of-group-of-chain-stucks-to-return-result.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Maybe it's fixed in master, we'll see if it comes back after 4.0 release.

**Comment by glormph** [comment]
Possibly related to this, if I run

    @app.task
    def taskname():
       print('ok')

    group(task.s() for x in range(3)
    [c.ready() for c in children]`
I get `[True, False, False]` in 3.1.23, but `[False, False, False]` in 4.0.0.rc3

Also if I add more tasks, only the first child finishes. The worker does however run the tasks without a problem as shown in stdout. On OSX with rpc backend to a remote RabbitMQ.
