### ISSUE TITLE
Status of a workflow with a group inside a chain inside a group is always PENDING

### ISSUE THREAD

**Issue by jonblack** [celery/celery#2368]
Given the following tasks:

```python
from __future__ import print_function
import time

from celery import Celery

app = Celery()
app.config_from_object('celeryconfig')

@app.task
def task1(*args, **kwargs):
    print("beg task1")
    time.sleep(5)
    print("end task1")
    return "res_task1"

@app.task
def task2(*args, **kwargs):
    print("beg task2")
    time.sleep(5)
    print("end task2")
    return "res_task2"

@app.task
def task3(*args, **kwargs):
    print("beg task3")
    time.sleep(5)
    print("end task3")
    return "res_task3"

@app.task
def task4(*args, **kwargs):
    print("beg task4")
    time.sleep(5)
    print("end task4")
    return "res_task4"

if __name__ == '__main__':
    app.worker_main()
```

And the following workflow:

```python
from __future__ import print_function

import pprint
import time

from celery import group
from celery import chain
from celery import chord

import simple_tasks as t

#workflow = chain(t.task1.s(), t.task2.s())  # works
#workflow = chain(group(t.task1.s(), t.task2.s()))  # works
#workflow = chain(group(t.task1.s(), t.task2.s()), t.task3.s())  # works
#workflow = group(chain(t.task1.s(), t.task2.s()), t.task3.s())  # works
workflow = group(
    chain(
        group(t.task1.s(), t.task2.s()),
        t.task3.s()
    ),
    t.task4.s()
)  # fails

result = workflow.delay()

def print_status(ar):
    print("{} ".format(type(ar)), end='')

    if hasattr(ar, 'state'):
        print("{} {} ({})".format(ar.task_name, ar.id, ar.state))
    else:
        print("{}".format(ar.id))

    if ar.parent:
        print_status(ar.parent)

    if ar.children:
        for ar in ar.children:
            print_status(ar)

while not result.ready():
    print_status(result)
    time.sleep(5)
else:
    print_status(result)
```

`result.ready()` is always `False` because the `AsyncResult` for the chain is always `PENDING`.

The `chain`, according to the documentation, should be upgraded to a `chord`:

> Chaining a group together with another task will automatically upgrade it to be a chord.

However, the `task_name` for the `AsyncResult` is still `celery.chain`, suggesting otherwise:

    <class 'celery.result.GroupResult'> 12ef698e-7eef-4de7-b808-18d6abde0b78
    <class 'celery.result.AsyncResult'> celery.chain e8fbb648-096b-44ea-8be5-5c4570270c05 (PENDING)
    <class 'celery.result.AsyncResult'> simple_tasks.task4 a1575e7b-a225-43df-8f5d-f257d4c39ffc (PENDING)

If I change the workflow to explicitly use a `chord`, it works:

```python
workflow = group(
    chord(
        group(t.task1.s(), t.task2.s()),
        t.task3.s()
    ),
    t.task4.s()
)  # works
```

I'm using the following configuration:

```python
BROKER_URL = "amqp://guest:guest@localhost:5672//"
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERY_IMPORTS = ("simple_tasks", )
CELERY_RESULT_BACKEND = "redis://localhost/9"
CELERY_TASK_RESULT_EXPIRES = 300
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_CHORD_PROPAGATES = True
```

I've seen this problem in the current 3.1.16 release, the current 3.1.16 branch, and in the current master (3.2.0a1).

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Could be fixed in master, let's see it comes back after 4.0 release.

**Comment by k1p0d** [comment]
I'm also experiencing a chain task that its status remains PENDING even though all the tasks has been successfully completed. here is my workflow - 
`        exec_workflow = group(
            chain(task1.s(),task2.s()),
            chain(task3.s(),
                  group(
                      task4.s(),
                      task5.s()
                  )
            )
        )`

The second chain is the problematic one. What i tried to acheive is execute task4 and task5 once task3 is compeleted. Any idea on how to acheive this?
