### ISSUE TITLE
Breakpoint signal not working for workers

### ISSUE THREAD

**Issue by surbas** [celery/celery#2371]
Hello

Per http://celery.readthedocs.org/en/latest/tutorials/debugging.html#index-2 one should be able to set an rdb trace on any worker by signaling with SIGUSR2 `kill -USR2 <worker pid>`. Sadly this only works for the parent process, and none of the workers, because after forking (in after_fork()), billiard sets all terminal signals to '_shutdown_cleanup'

The signals that get set to this are determined in billard/common.py

TERMSIGS_DEFAULT = (
    'SIGHUP',
    'SIGQUIT',
    'SIGTERM',
    'SIGUSR1',
    'SIGUSR2'
)

TERMSIGS_FULL = (
    'SIGHUP',
    'SIGQUIT',
    'SIGTRAP',
    'SIGABRT',
    'SIGEMT',
    'SIGSYS',
    'SIGPIPE',
    'SIGALRM',
    'SIGTERM',
    'SIGXCPU',
    'SIGXFSZ',
    'SIGVTALRM',
    'SIGPROF',
    'SIGUSR1',
    'SIGUSR2',
)  

Anyway what if when setting up the rdb signal in `install_rdb_handler()` located in cerery/apps/worker.py we use SIGWINCH instead. Happy to supply a patch if you agree. Another signal would be needed also to reenable `cry()` on workers.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by LPiner** [comment]
From what I can tell this is still occurring. If you're not going to fix it please update the docs to reflect such.

http://docs.celeryproject.org/en/latest/userguide/debugging.html
