### ISSUE TITLE
ValueError: filedescriptor out of range in select, like previous #1768

### ISSUE THREAD

**Issue by PMickael** [celery/celery#2373]
Hello,

I'm using celery 3.1.16, and I get this error sometimes with 2 worker and --autoscale=1,100 :
> [WARNING/MainProcess] Traceback (most recent call last):
> [WARNING/MainProcess] File "/usr/lib/python2.7/multiprocessing/util.py", line 261, in _run_finalizers
> [WARNING/MainProcess] finalizer()
> [WARNING/MainProcess] File "/usr/lib/python2.7/multiprocessing/util.py", line 200, in __call__
> [WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
> [WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1567, in _terminate_pool
> [WARNING/MainProcess] cls._help_stuff_finish(*help_stuff_finish_args)
> [WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/concurrency/asynpool.py", line 1218, in _help_stuff_finish
> [WARNING/MainProcess] readable, _, again = _select(inqR, timeout=0.5)
> [WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/concurrency/asynpool.py", line 140, in _select
> [WARNING/MainProcess] r, w, e = select.select(readers, writers, err, timeout)
> [WARNING/MainProcess] ValueError: filedescriptor out of range in select()

It is a problem about open file ? Or something like that, I need to know what exactly is this error to find a way to Fix it.

Thanks

**Comment by nitin-tm** [comment]
@ask why did this change is not included in the recent celery release of 3.1.23 ,We thought this fix is included in the recent release. We are still facing this issue after new release.

**Comment by thedrow** [comment]
@nitin-tm Feel free to cherry-pick and issue a PR.
We're trying to release 4.0 and that's our main focus.

I don't know why it wasn't included. Let's wait for @ask to reply.

**Comment by nitin-tm** [comment]
@ask could you please reply ?
