### ISSUE TITLE
auto_delete=True doesn't apply to exchanges

### ISSUE THREAD

**Issue by DXist** [celery/celery#2376]
Celery version: 3.1.x
Task backend: RabbitMQ

I include app version into names of task queues and exchanges. This approach allows me to point apps with different versions into the same RabbitMQ cluster.

Exchange declaration:
```
default_exchange = Exchange(exchange_name, type='direct', auto_delete=True, durable=False)
```

auto_delete flag is used because I want RabbmitMQ to cleanup old exchanges automatically when there is no workers/queues using them.

According to a Rabbimq management console created exchanges don't  have auto_delete attribute and stay uncleaned.

**Comment by ask** [comment]
I'm not sure, but afair it was said there were problems using it, but maybe that has changed now.
