### ISSUE TITLE
user_preload_options not persisting in Windows

### ISSUE THREAD

**Issue by nathanhilbert** [celery/celery#2386]
I've been debugging the [OpenSpending project](https://github.com/openspending/openspending) to be run on windows with a dependency of celery.  The issue is that there is a database call during a task and an .ini file that is read through a custom method with the user_preload_options signal; however, in Windows, it seems when the task is run it is calling a different instance of the defined app where the ini file was not loaded, so it throws that there is no connection to the database.  I've thrown in a few debug statements throughout the code, one of which is called every time the app is imported that prints the address in memory.  Earlier in the app the execution shows 
```
----------------Here is my app ID <Celery openspending.tasks:0x4f58208>
```
Later I see this in the rest of the output
```
---------------Here is my app ID <Celery openspending.tasks:0x5166630>
```
I put this print out at the bottom of [this file](https://github.com/openspending/openspending/blob/master/openspending/tasks/celery.py) in the openspending file.  The app can be found [here](https://github.com/openspending/openspending/tree/master/openspending/tasks) and the previous conversation about this topic is here https://github.com/openspending/openspending/issues/825.
Any help would be much appreciated.  OpenSpending does in Ubuntu 12.04.

**Comment by ask** [comment]
Windows does not have fork, so the child process does not inherit the memory of the parent process.

So you need to find a workaround for passing this to the child processes, it's possible that setting an environment variable will work in Windows, but I'm not sure.
