### ISSUE TITLE
what is `celeryev.ea0d5c79-aecc-4379-978f-0d4caceb3535` in rabbitmq vhost queues

### ISSUE THREAD

**Issue by tallmad** [celery/celery#2387]
I use rabbitmq as my celery broker.
Following is the output `sudo rabbitmqctl -p zeus list_queues`

```
celeryev.ea0d5c79-aecc-4379-978f-0d4caceb3535   51292
celeryev.eee27df8-028e-470a-9eaf-228ca18505a3   0
celeryev.f3edf603-3315-4ea0-9bc7-6f1ee0d4448a   0
dms 4
dms@p-meepo-3.celery.pidbox 0
dms@p-service-6.celery.pidbox   0
dms@p-service-7.celery.pidbox   0
dms@p-service-8.celery.pidbox   0
```

I also use rabbitmqmon to monitor my rabbitmq. 
This queue `celeryev.ea0d5c79-aecc-4379-978f-0d4caceb3535` has incoming messags, but no devlier/get messags.

Anyone could tell me  why?? Thanks a lot.

**Comment by gnomohf** [comment]
Found this useful option: just limit the amount of messages on queues celeryev*

```
rabbitmqctl set_policy limit_celeryev_queues "^celeryev\." '{"max-length":1000000}' --apply-to queues
```
