### ISSUE TITLE
Celery user requiring login unnecessarily

### ISSUE THREAD

**Issue by bpostlethwaite** [celery/celery#2390]
https://github.com/celery/celery/blob/3.1/extra/generic-init.d/celeryd#L232-L234

should be 

_chuid () {
    su -s /bin/bash "$CELERYD_USER" -c "$CELERYD_MULTI $*"
}
(or /bin/sh)

otherwise Celery complains about "This account is currently not available" if the USER does not have login privileges.

On some production systems it is advisable to not have login rights set for User account meant for Server systems.

**Comment by fluffels** [comment]
I can confirm this issue. Ubuntu 14.04.02 LTS. Celery 3.1.17 (installed via virtualenv / pip).

**Comment by fluffels** [comment]
This is present in the celerybeat init.d script as well, by the way.

**Comment by mlissner** [comment]
@bpostlethwaite, thanks for the fix here. This would have driven me crazy! Same exactly problem here.

**Comment by ask** [comment]
`su` is the only platform independent solution for doing setuid, but su -s does not exist on all platforms.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by dtwilliamson** [comment]
A conditional could cover the alternatives.
