### ISSUE TITLE
task retry in chain of groups breaks order of execution

### ISSUE THREAD

**Issue by peterdemin** [celery/celery#2393]
Hi,

I created following Minimal Reproducible Example to illustrate what I believe is a bug:
https://gist.github.com/peterdemin/abebf85892e248ca88a6

Here is little explanation of steps taken to reproduce:
1. create chain of groups of tasks;
2. apply async;
3. raise retry inside task(s) of first group;
4. watch, how tasks of second group are finished before those in first group.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
