### ISSUE TITLE
django celery admin time shift

### ISSUE THREAD

**Issue by sodrian** [celery/celery#2394]
Hi,
I have strange time shift in djcelery task admin area. The django project's settings for time zone is TIME_ZONE = 'US/Pacific'. Celery has CELERY_TIMEZONE = TIME_ZONE and CELERY_ENABLE_UTC = False. Backend that stores tasks tombstones is psql and is timezone aware. Yet there are strange results for tombstones:
When server time is 30th November 2014 22:53, 
The task detail has - Event received at: Dec. 1, 2014, 6:53 a.m.
On psql level 2014-12-01 06:53:36.046572-08
I've played with celery settings enough but still can't get adequate result.

**Comment by ask** [comment]
The django-celery admin monitor is no longer supported, please use flower: https://github.com/mher/flower
