### ISSUE TITLE
You are running the worker with superuser privileges....Why?

### ISSUE THREAD

**Issue by no13bus** [celery/celery#2395]
My command is `celery -A tasks worker -l info -c 1000 -P gevent` and my celery version is v3.1.17.
But here is the alerting message.
`/usr/local/lib/python2.7/dist-packages/celery/platforms.py:766: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!`
`Please specify a different user using the -u option`

My settings is below:
`
CELERYD_POOL_RESTARTS = True
CELERYD_FORCE_EXECV = True
CELERY_ACCEPT_CONTENT = ['json']
`

**Comment by maulikmrydotinfotech** [comment]
ZXX
