### ISSUE TITLE
CELERY_QUEUES should be named CELERY_TASK_QUEUES

### ISSUE THREAD

**Issue by davidstrauss** [celery/celery#240]
CELERY_QUEUES is a confusing name because it implies that it's configuration for all queues in use by Celery, when it's really only for task queues.

**Comment by gsmafra** [comment]
[Docs](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_queues) are now showing CELERY_TASK_QUEUES, but the correct name is still CELERY_QUEUES (as of 4.1.0)
