### ISSUE TITLE
New Task class for app model is Iterable but crashes during iteration

### ISSUE THREAD

**Issue by jtillman** [celery/celery#2403]
Going from the old version of a Task to the new app based Task. We have some middleware that inspects arguments and when passing tasks, we started failing because the Task falsely claims it is iterable.

def inspect_arg(arg):
    if isinstance(arg, collections.Iterable):
        for sub_arg in arg:
            inspect_arg(sub_arg)

I believe this has to do with the Proxy code that we copied into celery.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
