### ISSUE TITLE
Chord callback is executed while tasks are in retry state

### ISSUE THREAD

**Issue by IlianIliev** [celery/celery#2405]
The code looks like:

```
chunk_tasks = []
for index, chunk in enumerate(chunks):
    chunk_tasks.append(
                import_chunk.s(meta.pk, chunk, start_row, has_labels=has_labels)
            )
g = group(chunk_tasks)
chord(g)(import_completed.s(meta.pk))
```

However some of the import chunk tasks can fail and be retried several times. The problem is that the import_completed which should be called after all tasks are completed is called while some of the tasks in the group are still in the retry state.
Is this a bug or I have missed setting up something?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
