### ISSUE TITLE
Unable to get a results backend with Django 1.7

### ISSUE THREAD

**Issue by ghost** [celery/celery#2412]
I have a django project that I have updated from Django 1.6 to Django 1.7.

I have had celery working with rabbitmq as broker, and redis results backend on Django 1.6.

I can see the celery workers know about redis in their output. I can also see that Django's CELERY_RESULT_BACKEND is set to 'redis://'

However when I attempt to use the AsyncResult().ready() I get an error:

```
AttributeError at /concierge/stage/one/async/'
DisabledBackend' object has no attribute '_get_task_meta_for'
```

**Comment by yamatt** [comment]
I'm having a similar issue here. What was the resolution?

**Comment by savingschampion** [comment]
In my case it was because celery was not loading the settings.py correctly.
We had a project that started on Django 0.9 or something.

**Comment by yamatt** [comment]
I suspect in my instance it is not reading the configuration correctly either although I don't have the legacy Django issue you have. I'll start investigating in that direction.

**Comment by yamatt** [comment]
So the solution we have managed to make work is to ignore the advice about the `config_from_object` and `app.conf.update` stuff in [First Steps with Django](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html) and use:

    from django.conf import settings
    app = Celery('test', backend=settings.CELERY_RESULTS_BACKEND, broker=settings.BROKER_URL)

**Comment by micahhausler** [comment]
@yamatt not sure if this has anything to do with it, but shouldn't your backend setting be `CELERY_RESULT_BACKEND`, not `CELERY_RESULTS_BACKEND` ?
