### ISSUE TITLE
pyamqp: No timeout on DNS lookups

### ISSUE THREAD

**Issue by sadjad** [celery/celery#2417]
Hi all,

I'm using Celery 3.1.17. I have two machines and a RabbitMQ message broker on first machine. When I'm running Celery worker in prefork mode in second machine and I call send_task or apply_async, it just gets stuck (RabbitMQ is on the first machine and still full of resources). But when I switch to `-P solo`, the problem goes away.

Any thoughts on this?

Bests,
Sadjad

**Comment by sadjad** [comment]
Any updates on this?
I still have the problem and I have to run Celery in solo mode...

**Comment by sadjad** [comment]
If found the source of the problem. When running in Prefork mode, the AMQP library, get stuck on getaddrinfo function (I think it's a similar issue to: http://stackoverflow.com/questions/1212716/python-interpreter-blocks-multithreaded-dns-requests).

I still don't have a solution for that...

**Comment by sadjad** [comment]
It happens here: https://github.com/celery/py-amqp/blob/7ef76ecde592dd7043b0f3703de7e22e2211f15c/amqp/transport.py#L74

@ask, do you have any idea why this happens?

Thank you very much.

**Comment by thedrow** [comment]
It seems that you have a DNS issue in your environment causing this to happen.
```socket.getaddrinfo()``` has no timeout argument and we need to introduce a timeout there.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

It's impossible to set a timeout for getaddrinfo, you need to reimplement the whole thing using async I/O. There are libraries for this, but nothing we can depend no by defualt.
