### ISSUE TITLE
cassandra backend

### ISSUE THREAD

**Issue by josh-devops-center** [celery/celery#2418]
Hi,

I see a [cassandra backend](http://docs.celeryproject.org/en/latest/internals/reference/celery.backends.cassandra.html) though not listed in the documentation for [broker overview](http://celery.readthedocs.org/en/latest/getting-started/brokers/index.html#broker-overview). Also there is configuration doc [here](http://docs.celeryproject.org/en/2.4/configuration.html#conf-cassandra-result-backend).

Can we reliably use Cassandra? Also is Monitoring and Remote Control supported?

Thanks!

**Comment by thedrow** [comment]
We have a cassandra results storage backend but no broker as far as I know.
