### ISSUE TITLE
Redis broker, manual routing, default topic exchange sends messages to all workers

### ISSUE THREAD

**Issue by AdrianLC** [celery/celery#2427]
Hello,

(I tested this also with rabbitmq and the issue only occurs with the redis broker.)

When setting up manual routing for 2 workers and 1 queue each, following the [example](https://celery.readthedocs.org/en/latest/userguide/routing.html#manual-routing) from the docs.

My settings where:
```python
    BROKER_URL = 'redis://localhost:6379/0'
    BROKER_TRANSPORT_OPTIONS = {
        'fanout_prefix': True,
        'fanout_patterns': True,
        'visibility_timeout': 3600,
    }
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0',

    # Queues and routing:
    from kombu import Queue

    CELERY_QUEUES = (
        Queue('albert', routing_key='albert.#'),
        Queue('roger', routing_key='roger.#'),
    )
    CELERY_DEFAULT_QUEUE = 'albert'
    CELERY_DEFAULT_ROUTING_KEY = 'albert.default'
    CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
```

And launching the workers with:
```bash
celery worker -A albert -l DEBUG -Q albert -n albert
celery worker -A roger -l DEBUG -Q roger -n roger
```
celery sends a single task with `routing_key='roger.feeds'` to: 
`['roger', 'albert', 'roger', 'roger', 'albert', 'albert', 'roger']`
(That's 3 times to "albert" worker and 4 to "roger")

I followed the issue up to [this method](https://github.com/celery/kombu/blob/v3.0.24/kombu/transport/virtual/exchange.py#L77) from kombu's virtual topic exchange.
The `table` at that point was: 
```python
[('roger', '', 'roger'), ('albert.#', '', 'albert'), ('roger.#', '^roger\\..*?$', 'roger'), ('', '', 'roger'), ('', '', 'albert'), ('albert.#', '^albert\\..*?$', 'albert'), ('albert', '', 'albert'), ('roger.#', '', 'roger')]
```

Luckily I found out that changing the default exchange's name fixes the issue.
`CELERY_DEFAULT_EXCHANGE = 'default'` so it could be a matter of passing default attributes from one place to another...

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
