### ISSUE TITLE
task's result always block on get() with state pending

### ISSUE THREAD

**Issue by ztqsurfing** [celery/celery#2428]
* environment: windows7
* backend & msg queue: rabbitmq

***

Tasks can be processed properly and results are printed in the command line, but when try to get() the **result** the process is blocked, and the state of **result** is always pending. backend is set up properly, and possible problem mentioned in troubleshooting are checked.
While searching, get a solution of adding option **'--pool=solo'** while launch the worker, the reason is still unknown. So is there a way to using multi-thread pool with this situation?

Thanks a lot

**Comment by ask** [comment]
On Windows you need to configure the result backend in the configuration, not as an argument to `Celery`:

    `app = Celery()`
    `app.config_from_object('celeryconfig')


`celeryconfig.py`:

    CELERY_RESULT_BACKEND = 'redis://'

**Comment by premanandaembed** [comment]
Not working
