### ISSUE TITLE
Redis Broker connected, but no task imported

### ISSUE THREAD

**Issue by tanzaho** [celery/celery#2432]
Hi,

I ran into a strange issue today (and spent few hours before posting here, so please excuse if I am missing important information on this first post). I got a working installation with Celery 3.1.17, Django and Redis as broker. 

In a wrong manipulation, I downgraded Celery to 3.1.13, then re-updated it to 3.1.17 (with some dependencies downgrade/update too). After that, it seemed that **Celery is not seeing tasks stored in Redis**.

* Redis is effectively storing tasks (I directly checked in the DB)
* Celery connects to Redis with no apparent problem : 

```
 -------------- celery@ubuntu v3.1.17 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-3.5.0-43-generic-x86_64-with-Ubuntu-12.04-precise
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:        my_app_name:0x2e9d510
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
```

* I can send task manually and they are queued in Redis
* At launch, Celery autodiscovers and lists the available tasks from my application
* If use Django as the broker, everything worked as expected, task are queued and executed

Flower and events did not help me.

I am trying to understand why Celery cannot see the tasks queued in Redis. Any idea ?

---

Settings.py
```
...
import djcelery
djcelery.setup_loader()

# Redis Config
BROKER_URL = 'redis://localhost:6379/1'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}  # 1 hour.
CELERY_RESULT_BACKEND= 'redis://localhost:6379/2'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
...

```

**Comment by Lothiraldan** [comment]
Do you have 
```
from gevent import monkey
monkey.patch_all()
```

In your config file? If yes, try to remove these lines, it may works better, I had the same problem and lost my evening finding the solution

**Comment by tanzaho** [comment]
Hi @Lothiraldan ,
I'm not sure since I changed to rabbitmq in the meantime to avoid the issue.

I'll close this issue, but your comment might be useful for other members in the future.
Thanks for your input.
