### ISSUE TITLE
changing user does not execute .profile

### ISSUE THREAD

**Issue by amichay** [celery/celery#2433]
Hello,

We're running Celery on AWS w/ SQLAlchemy connecting to Postgresql instance on RDS. The configuration parameters to properly configure and authenticate are exposed in our .profile . However the init script calls 'su' instead of 'su -' . I changed this locally and it's now properly working. I wonder if there are any possible consequences or reason why to do this differently?

Thanks much for this create script !

Best,
Amichay

**Comment by ask** [comment]
Environment variables will be inherited when using `su`, but using a login shell is not really a convention for daemons.

We only use su here, because that's the only portable way to execute something as another user, but we would use a pure `setuid` if it was available.
