### ISSUE TITLE
Mark celery-with-redis as python3 compatible.

### ISSUE THREAD

**Issue by collinanderson** [celery/celery#2434]
Could we add the "Python :: 3" classifier to setup.py for celery-with-redis?

That would help python 3 checkers, for example:
https://caniusepython3.com/project/celery-with-redis

**Comment by ask** [comment]
celery-with-redis is no longer used actually, but I cannot just remove it out of fear from breaking peoples installs.

The new way to install celery with redis is:

```
pip install celery[redis]

```

Would be nice if PyPI had some way to deprecate packages.
