### ISSUE TITLE
Qpid transport using unicode username does not work with flower

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2439]
When using Kombu 3.0.24 or newer with Celery, the Qpid transport may be used. If the Qpid transport is used with Flower and the celery broker string contains a username (as it does by default), then Flower cannot be used to monitor Celery.

The root cause of this issue is in the underlying qpid.messaging library, and the issue is being resolved by the Qpid community as issue [QPID-6197](https://issues.apache.org/jira/browse/QPID-6197). Once that JIRA is resolved, the dependency on PyPi needs to be updated with the fix. Once that is done, this issue can be closed.

**Comment by ask** [comment]
What's the status of this?

**Comment by bmbouter** [comment]
This has been fixed in the underlying dependency so I am closing this bug now. If a user determines this is not resolved, please re-open the bug.
