### ISSUE TITLE
Celery documentation translation

### ISSUE THREAD

**Issue by iT2afL0rd** [celery/celery#2444]
Hi Ask,

Is there any officially request to translate Celery documentation into Chinese ?
If not, I would like to start it as a open source project in Github.
May I get your opinion on it ?
Thanks.

**Comment by malinoff** [comment]
@ask what do you think? Should we use a dedicated service for this, like https://www.transifex.com/?

**Comment by thedrow** [comment]
Transifex is a good idea :+1:

**Comment by ask** [comment]
It would be great, but we won't have the resources to do this.  Maybe we're lucky and someone does it, but there's no way I have time for this at least :(
