### ISSUE TITLE
403 Forbidden Error on websocket connection

### ISSUE THREAD

**Issue by rkyleg** [celery/celery#2445]
Platform: Python2.6, Centos6, Reverse proxying with nginx, celery v3.1.17

I got a 403 Forbidden error on the websocket connection to '/update-workers'. I was able to resolve this  by adding this code to the websocket handler:

    def check_origin(self, origin):
            return True

Can this be added?

**Comment by ask** [comment]
websocket handler? I didn't know we had any of this? :)

**Comment by ask** [comment]
Oh, i'm guessing this is an issue for Flower, and you mean `/update-dashboard`.

Please create an issue on https://github.com/mher/flower instead :)
