### ISSUE TITLE
Celerybeat startup info reports incorrect broker string when configuration is added to the celery app object from within the Scheduler

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2447]
We start celery with the following command:

/bin/python /usr/bin/celery beat --scheduler=pulp.server.async.scheduler.Scheduler

Here is a link to the [Scheduler](https://github.com/pulp/pulp/blob/master/server/pulp/server/async/scheduler.py#L241). That code imports our file [celery_instance.py which instantiates the Celery app and configures it](https://github.com/pulp/pulp/blob/master/server/pulp/server/async/celery_instance.py#L17). The configuraiton includes setting the broker string which is correctly used by celery workers and celery beat. Everything works for us except that celerybeat incorrectly reports the broker string when it starts.

The actual broker string being used here is qpid://guest@ec2-54-22-180-132.eu-west-1.compute.amazonaws.com:5672//, however when celerybeat starts up it shows:
```
Configuration ->
. broker -> amqp://guest@localhost:5672//
. loader -> celery.loaders.default.Loader
. scheduler -> pulp.server.async.scheduler.Scheduler
. logfile -> [stderr]@%INFO
. maxinterval -> now (0s)
```

The broker string is incorrect. After some debugging I've determined that in [beat.startup_info](https://github.com/celery/celery/blob/master/celery/apps/beat.py#L128) the self.app points to a celery app that was created earlier in the codepath, but the one that we configure is actually scheduler.app which is returned in line 128.

I expected that we could set these options on our app directly, and since our app is on the codepath prior to the printing of this banner I expect it to use the configured celery app. Instead it is using the unconfigured celery app. I expect we can configure the app elsewhere and have it just work because the (docs recommend doing that)[http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html#entries].

**Comment by bmbouter** [comment]
I've found a workaround by adding the app specifically using the `--app` option for celerybeat. Celery could improve this area by having the celery app actually be a singleton. If it truly is a singleton, then when I modify it in another code path the reference stored at Beat.app would point to the correct version.

**Comment by dralley** [comment]
Hi @bmbouter :)

I've just independently discovered that the same problem applies to the maxinterval property, and ran across this issue while debugging.  Everything written above applies to the maxinterval property as well, and likely very others.

**Comment by ask** [comment]
@bmbouter We could change it to use `scheduler.app` but then there's a mismatch where the command-line interface layer uses one app, and the scheduler another, and I think that's something that you should avoid even though it works currently.   I imagine there could be some point where we want to use the app for something before the Scheduler is created.

So:

```shell
   $ celery -A proj beat
```

is always how you should use any celery command.  We would like to make that mandatory, but we cannot as we maintain compatibility from the time when only a `celeryconfig.py` module was used.  We could probably remove that in 5.0.

**Comment by ask** [comment]
@dralley: Thanks!  I fixed the max interval part so that should work in master now.
