### ISSUE TITLE
Celery Beat with worker not controlled by crontab

### ISSUE THREAD

**Issue by amosunfemi** [celery/celery#2448]
When i started celery schedule job with worker the process runs continuously instead of working based on rule set in the crontab. 

On Mac OS 10.9, it works perfectly. This anomaly only happens on Ubuntu instance on AWS.

**Comment by thedrow** [comment]
Can you provide a working test case that reproduces that problem?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
