### ISSUE TITLE
running a worker in the command line with LIGHT background color: looks terrible

### ISSUE THREAD

**Issue by jabbalaci** [celery/celery#2449]
In the terminal I prefer light background. However, the result is unreadable: http://i.imgur.com/j7xL1uT.png . Is there a color theme for light backgrounds? Thanks.

**Comment by jabbalaci** [comment]
OK, I found it. Use the `-C` option to disable colors.

**Comment by ask** [comment]
This depends on the terminal colors though and most terminal emulators will use a more sensible color-scheme for a light background theme.   I use the Solarized color scheme, which comes with support for heaps of different software: http://ethanschoonover.com/solarized
