### ISSUE TITLE
Overriding the socket.error exception thrown when a broker isn't running.

### ISSUE THREAD

**Issue by brianbs** [celery/celery#2452]
Whenever I attempt to connect to a rabbitmq broker that is refusing connections or isn't running I am getting a socket.error exception.  I'd instead like to throw another custom exception that says specifically there is an error connecting to rabbitmq.  I've taken a look into inheriting the Celery class but there is a ton of decorator magic going on in the task function that I'm having trouble understanding. Do you have any simple solutions into overriding that exception?

**Comment by ask** [comment]
socket.error is coming from the amqp library.

If you want to do this just for when calling tasks then you should just override `Celery.send_task`
