### ISSUE TITLE
Add timestamp and celery hostname in the backend metadata.

### ISSUE THREAD

**Issue by proofit404** [celery/celery#2456]
In case to configure remote celery node by processing result of task we need to know celery hostname and task finish timestamp.  Currently we add this information into result dictionary and on_failure handler. But this solution doesn't work in case of task callbacks if HardTimeLimit is raised.

Currently we subclass AMQPBackend and add this information.

**Comment by traut** [comment]
:+1: currently there is no out-of-the-box ways to know when task started, when it finished and where it was running.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
