### ISSUE TITLE
CELERY_TASK_PUBLISH_RETRY_POLICY doesn't change retry delay (3.1.17)

### ISSUE THREAD

**Issue by thuey** [celery/celery#2457]
I'm probably doing something wrong, but no matter what I do, I can't change the retry delay for tasks. I've tried this:
<pre>
CELERY_TASK_PUBLISH_RETRY_POLICY = {
         "max_retries": 3,
         "interval_start": 0,
         "interval_step": 0.2,
         "interval_max": 0.2}
</pre>
and this:
<pre>
add.apply_async((4,4),  retry=True, retry_policy={
	    'max_retries': 3,
	    'interval_start': 0,
	    'interval_step': 0.2,
	    'interval_max': 0.2,
	})
</pre>
No matter what I do, the retry delay is always 180s, which appears to come from the task's <code>default_retry_delay</code> option.

**Comment by marians** [comment]
@thuey As it seems, `CELERY_TASK_PUBLISH_RETRY_POLICY` is not related to retrying task execution. It deals with communication between celery and the broker.

I don't know which context you are in. I'm using Celery in a Flask context and for me tuning the delay worked by directly setting the task's `default_retry_delay` attribute this way:

```
@celery.task(default_retry_delay=2, max_retries=3)
def get_random_success():
    """
    This task will fail in 50 percent of all calls
    and then be retried.
    """
    succeed = random.choice((True, False))
    if succeed == False:
        raise get_random_success.retry()
    return succeed
```

**Comment by thuey** [comment]
@marians You were right. After reading the documentation again for <code>CELERY_TASK_PUBLISH_RETRY_POLICY</code>, it makes sense: "Defines the default policy when retrying publishing a task message in the case of connection loss or other connection errors." I hadn't caught the part about it just being for connection problems. Using <code>default_retry_delay</code> worked. Thanks!

**Comment by marians** [comment]
@thuey Glad I could help!
