### ISSUE TITLE
Celery tasks no retrying as wanted.

### ISSUE THREAD

**Issue by minuscorp** [celery/celery#2460]
Hello.

I'm doing a retry loop with tasks on my system that do a background processing starting when the user wants it (reason why I cannot use scheduled tasks), so one task looks like this:
```python
@app.task(bind=True)
def twitter_extraction(self, ...):
    print "Starting tweet extraction for "+search_process
    while 1:
        try:
            extractor.extract(keywords)
        except:
            print "Finished tweet extraction for "+search_process
            self.retry(countdown=60*2, max_retries=10000)
        print "Finished tweet extraction for "+search_process
        self.retry(countdown=60*2, max_retries=10000)
```
I've tried the next options to do the retry:
-> ```raise self.retry(countdown=60*2, max_retries=10000)```
-> ```raise self.retry(exc=Exception('retry'), countdown=60*2, max_retries=10000)```
-> ```current.retry(countdown=60*2, max_retries=100000)```
-> ```twitter_extraction.retry(countdown=60*2, max_retries=10000)```

Only the last one works, but it creates a NEW task with a new ID, and I need to revoke those task when the user wants it, so i register the ID of the task once it starts to be able to revoke it whenever I want, but I can't revoke with the last of the options because It hasn't started yet and It'll start even when the user didn't want to.

>UPDATE: Even the last of the options doesn't work now, it was a mistake.

What are the options here to make a task to retry himself with same ID and that actually works?

Thank you.

**Comment by minuscorp** [comment]
Even more, I've tried to make a dumb_task like this:

```python
@app.task(bind=True)
def dumb_task(self):
    print "DUMB"
    time.sleep(15)
    self.retry(max_retries=10000, countdown=30)
```

Called it like this:
```
dumb_task.apply_async(queue="%s"%company.pk, retry=True)
```

And the task only is executed once, giving me a traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/revuelta/web/piar/web/gui/tasks.py", line 57, in dumb_task
    self.retry(max_retries=10000, countdown=30)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 680, in retry
    raise ret
Retry: Retry in 30s
```

Which seems to be correct. But in Flower the task keeps in RETRY state and is never executed again by any worker (I can't see the "DUMB" message and the retries parameter is with value 1 all the time)

What I'm doing wrong?

BTW, I'm working in Debian with latest Celery version.

Thank you.

**Comment by ask** [comment]
How is the queue defined when you have `queue="%s"%company.pk`?

When the client sends the task, it will look up this queue name in `CELERY_QUEUES` to get the `exchange` and `routing_key` pair.

Then the worker receives the task message, with `delivery_info` containing the same pair.
When you retry the task is sent to the same exchange/routing_key by using the delivery info,
but it cannot declare the queue (since it does not know the name, nor the attributes of the queue).

Maybe you should try:

   `self.retry(max_retries=1000, countdown=30, queue=company.pk)`

**Comment by minuscorp** [comment]
It turns out that I've never achieved to run properly the ``` retry ``` because of how is my application designed (**dynamic** worker spawn under request in user private queues, which matches with the priamry key of the user who creates it, that's why the ``` company.pk ``` parameter).

Instead of ```retry``` I'm just publishing new tasks with a fixed ```countdown``` if the client has already running any workers for him. My use case it's like the user rents some computational power to make some already defined tasks by the server, and that computational power has to be managed by the user (in number and state (running or stopped)) for as long as the user wants to, paying an amount for time and number of workers working just for him.

I think the problem itself couldn't be fixed but I did this workaround. Also I let you know that including the capability of letting someone spawn workers on several predefined computers would be awesome, automatic scaling is the future!

Regards

**Comment by ask** [comment]
Thanks for reporting back!
