### ISSUE TITLE
CELERY_MAX_CACHED_RESULTS doesn't work with Redis backend

### ISSUE THREAD

**Issue by adampl** [celery/celery#2461]
If I understand the docs correctly, the [`CELERY_MAX_CACHED_RESULTS`](http://celery.readthedocs.org/en/latest/configuration.html#celery-max-cached-results) should limit the number of results stored in the result backend, regardless of the `CELERY_TASK_RESULT_EXPIRES`. I've analyzed the code and I'm almost sure that the Redis backend doesn't respect this limit. I suppose this is why it has no effect on the number of results stored in our Redis server. Please clarify this for me.

**Comment by neggert** [comment]
I think I'm seeing this issue as well. Checking manually with redis-cli, I see many more results than the `CELERY_MAX_CACHED_RESULTS` setting.

**Comment by camilonova** [comment]
I'm seeing this as well, how can we add support for it?

**Comment by ikks** [comment]
We are getting the same issue

**Comment by ask** [comment]
`CELERY_MAX_CACHED_RESULTS` does not limit the number of results stored in the backend, it limits the number of AsyncResults cached in the client.

This is only needed by the old 'amqp' result backend, as you can only retrieve the result once there. If you use Redis you can safely remove the cache.
