### ISSUE TITLE
Specifying module only for -A when starting worker, gives unexpected results when module contains multiple apps

### ISSUE THREAD

**Issue by tueabra** [celery/celery#2467]
If a module contains multiple apps, and the worker is started `-A module` (without `.appname`), both apps are started and will process tasks. Instead, the worker quit with a warning.

It might be intentional though, in which case there is a problem with settings between the apps.

In the following test, both apps will return a value, even though one of them has `CELERY_IGNORE_RESULT` set to `True`.

```python
from celery import Celery


class Config(object):
    CELERY_BACKEND = 'amqp'
    CELERY_RESULT_BACKEND = 'amqp'


app1 = Celery('app1')
app1.config_from_object(Config)
app1.conf.CELERY_IGNORE_RESULT = True


app2 = Celery('app2')
app2.config_from_object(Config)


@app1.task(name='app1.test')
def test1():
    return "Test1"


@app1.task(name='app2.test')
def test2():
    return "Test2"


if __name__ == '__main__':
    print app1.send_task('app1.test').get()
    print app1.send_task('app2.test').get()
```

(Run with `celery worker -A filename` and `python filename.py`).

**Comment by ask** [comment]
The worker will only use one app, but as long as it's using the one with IGNORE_RESULT=False the result will be ignored.

The caller will have no effect on the workers IGNORE_RESULT_SETTING.

I wouldn't use the `-A proj` shortcut unless you are using the default layout of `app = Celery()`.  Having multiple apps in the same module and using the shortcut is undefined behavior.
