### ISSUE TITLE
Celery + redis broker memory overuse in case of bulk task push

### ISSUE THREAD

**Issue by codescrapper** [celery/celery#2468]
Config: 2 workers with concurrency=4 on different machines. Redis memory = 4GB.

Scenario is something like this:

1. Push around 700 tasks (using another task) instantly to the queue named XYZ. Total expected size of data ~ 200MB. Each task is a single API call (takes around 2 secs)
2. Memory used grows exponentially till eviction starts. It also makes a list named XYZ for some metadata.

This I think is classic example of consuming tasks slower than producing them. Can't get my head around this. Would appreciate any help regarding this.

**Comment by codescrapper** [comment]
Okay I just stopped my worker and noticed that if I push 5 tasks with size of each task as 10kb. It puts 5 values in queue XYZ. Size of 4th index is 50kb. 3rd is 40kb ...0th is 10kb. This causes memory overuse. 

Any reason for this behaviour?

**Comment by ask** [comment]
For me there is only ever 1 member in the unacked_key for every task received, so I'm not sure what keys you mean specifically.

**Comment by ask** [comment]
The size of each item in the `unacked` key is also consistent.

Are you sure this is not a chain? The first task in a chain will contain all the rest of the tasks, the next task
will contain n-1 tasks, the next after that n-2 and so on.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
