### ISSUE TITLE
userguide database transaction section is outdated

### ISSUE THREAD

**Issue by thraxil** [celery/celery#2472]
The section on database transactions for tasks: http://celery.readthedocs.org/en/latest/userguide/tasks.html#database-transactions

Recommends using `@transaction.commit_manually` on django views to make sure the transaction commits before the task is sent. `@transaction.commit_manually` was deprecated in Django 1.6 and will be removed completely in 1.8: https://docs.djangoproject.com/en/1.7/topics/db/transactions/#changes-from-django-1-5-and-earlier

**Comment by malinoff** [comment]
Looks like this issue is actually fixed, closing.
