### ISSUE TITLE
Worker hang and generating huge logs in worker  

### ISSUE THREAD

**Issue by smbasha47** [celery/celery#2474]
Hello All,

We use Celery to run R (Analytics) jobs in background. We urgently need help in following areas on consulting basis. Anyone willing to help us, please contact with your hourly rates, thank you and appreciated,

Consultant should be able to help us in this situation:

1)	Ability with good understanding and impact of the settings of these flags. Our app settings      (default setting)
             a.	CELERYD_FORCE_EXECV = False (False)
             b.	CELERY_ACKS_LATE = True (None)
             c. 	CELERYD_PREFETCH_MULTIPLIER = 1 (4)
             d.	CELERYD_CONCURRENCY = 1 (No. of CPU cores)
2)	We have three problems
             a.	Celery hangs when time taking workers initiated
             b.	Some jobs get locked up
             c. 	Some jobs create plenty of logs.
The behaviour of these problems alter based on above flag settings.

Anyone with experience in Celery with above flags would be of timely help for us.

Appreciated
Basha.

**Comment by smbasha47** [comment]
we are getting very frequently bellow issue when task executing more time 


Traceback (most recent call last):
  File "/home/linuxadmin/.virtualenvs/intuceo/local/lib/python2.7/site-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).

**Comment by maximilianr** [comment]
@smbasha47 that last error may be python running out of memory - that's what it was for us

**Comment by thedrow** [comment]
For the jobs that get locked up can you use SIGUSR1 to get a traceback?

**Comment by smbasha47** [comment]
one of R library causing the issue. it is not celery issue

Thanks for your support

**Comment by thedrow** [comment]
Is this issue resolved? How?

**Comment by smbasha47** [comment]
when i turned this flag to  CELERYD_FORCE_EXECV = True i am getting above issue after removing this  flag it starting working 

Thanks 
Basha

**Comment by thedrow** [comment]
Oh you shouldn't be doing that unless you are already experiencing deadlocks.
