### ISSUE TITLE
prefork based concurrency: sporadic delayed start of forked children

### ISSUE THREAD

**Issue by dankilman** [celery/celery#2476]
Sporadically, in our test environment, when the celery worker is started (we are using version 3.1.17, the worker it is started with: `-Ofair --concurrency=2`), the forked children suffer a 30 seconds delay before being added to the parent inqueues.
Investigation reveals the following:
During the `_global_after_fork` that runs on the forked processes, specifically, when connections inherited from the parent process are closed, internally, at the `amqp` module level; if `concurrency` at least 2 and one child process starts the `channel.close` before another child process starts the `connection.close`; it will "steal" the response of the connection close of the other process (this is because both child processes share the same connection) and things will block for 30 seconds. This seems like some socket default timeout, but I couldn't figure out where exactly. After these 30 seconds, the `connection.close` will fail and right after it, the `channel.close` of the other process will proceed and normal execution will proceed. 

Now, this is more of an annoyance than it is bug, as tests started failing sporadically. We eventually worked around this issue by increasing some test timeout, but a general fix for this will be greatly appreciated. 

Thanks.

**Comment by thedrow** [comment]
I saw something similar when I tried to use celery with a very high concurrency of 128 children.
It took celery a couple of minutes (sometimes more) to start handling tasks.
I had no idea what was the root cause of the issue but yes, it is annoying.

**Comment by dankilman** [comment]
I forgot to mention that this only started occurring after upgrading from version 3.0.24

**Comment by ask** [comment]
py-amqp will be using `Connection.collect()` now instead of `.close()` in after forker handlers, which means it just closes the socket and avoids the shutdown dance.
