### ISSUE TITLE
Workers stop consuming tasks. AssertionError in asynpool.

### ISSUE THREAD

**Issue by DevJac** [celery/celery#2480]
I get the following traceback from my worker and then the worker stops consuming tasks. I have confirmed that there are several thousand messages in the RabbitMQ celery queue, the worker is not consuming them.

I started my worker with the following command:

`celery worker -A project -l info -n worker1.%h -Ofair --autoscale=50,1 --maxtasksperchild=100  --beat`

I am using the `-Ofair` flag because I was also experiencing another breaking bug (https://github.com/celery/celery/issues/1845) and found `-Ofair` to be a workaround.

```
2015-02-02 23:08:08,442 - ERROR - 15875:MainProcess - Unrecoverable error: AssertionError()
Traceback (most recent call last):
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/kombu/async/hub.py", line 274, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/kombu/async/hub.py", line 136, in fire_timers
    entry()
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/kombu/async/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/home/djacobs/.virtualenvs/workflow/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 521, in verify_process_alive
    assert proc.outqR_fd in hub.readers
AssertionError
```

**Comment by thedrow** [comment]
Do you have a test case that reproduces this issue?

**Comment by DevJac** [comment]
I have the following Python file named `a.py`:

```
from time import sleep
from celery import Celery
from conf import celery_settings


# If this is True, all tasks will be executed locally by blocking until the
# task returns. apply_async() and Task.delay() will return an EagerResult
# instance, which emulates the API and behavior of AsyncResult, except the
# result is already evaluated. That is, tasks will be executed locally instead
# of being sent to the queue. This can be useful for automated tests.
# See: http://docs.celeryproject.org/en/latest/configuration.html#celery-always-eager
CELERY_ALWAYS_EAGER = False


CELERY_IGNORE_RESULTS = True


CELERY_TASK_SERIALIZER = 'json'


CELERY_ACCEPT_CONTENT = ['json']


CELERY_TRACK_STARTED = True


CELERY_DISABLE_RATE_LIMITS = True


CELERY_ACKS_LATE = False


CELERYD_PREFETCH_MULTIPLIER = 1


CELERYD_MAX_TASKS_PER_CHILD = 1


CELERYD_HIJACK_ROOT_LOGGER = False


BROKER_URL = 'redis://{}:{}/{}'.format('localhost', 6379, 0)


BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600,
                            'fanout_prefix': True,
                            'fanout_patterns': True}


app = Celery()
app.config_from_object('a')


@app.task(name='demo_task')
def demo_task(sleep_time):
    sleep(sleep_time)


if __name__ == '__main__':
    for _ in xrange(1000):
        demo_task.apply_async(args=(5,))
```

I start the celery workers with the following command: `celery -A "a.app" worker --autoscale=50,1 -Ofair`

Then I run `a.py` and it will consistently produce the assertion error on my computer and shutdown all the workers.

**Comment by DevJac** [comment]
I am on Celery 3.1.18.

**Comment by thedrow** [comment]
Which operating system are you on?

**Comment by DevJac** [comment]
Linux Mint, latest version. Python 2.7.

**Comment by thedrow** [comment]
Reproduced.

**Comment by thedrow** [comment]
Oh wait this might be an *autoscaling* issue.

**Comment by thedrow** [comment]
So far I have been stressing the workers and the assertion error doesn't occur when you do specify autoscaling but don't specify -Ofair.
So that might provide a workaround for your issue.

**Comment by DevJac** [comment]
Note, I have seen this when using RabbitMQ as well.

**Comment by thedrow** [comment]
Even if -Ofair is not specified?

**Comment by DevJac** [comment]
In the original post I was using RabbitMQ, and I was also using -Ofair. I noticed this ticket got tagged with Redis, and I wanted to point out that this issue is not specific to Redis.

To answer your question: I have only seen this issue when -Ofair is specified. My guess would be that it is an issue related to -Ofair.

**Comment by thedrow** [comment]
@DevJac Please open another issue then.
This isn't reproducible with the Redis broker unless both autoscaling and -Ofair are specified.

**Comment by djacobs-verisys** [comment]
I am DevJac. I think we have a misunderstanding. I agree with you that this issue only occurs when both autoscaling and -Ofair are specified. My point is that the AssertionError can occur when using RabbitMQ as well.

**Comment by ask** [comment]
I'm only able to reproduce this when `--maxtasksperchild` is set?

**Comment by thedrow** [comment]
@ask I was able to reproduce this with just ```--autoscale``` and ```-Ofair``` with Redis as a broker.

**Comment by ask** [comment]
thedrow: How long did that take you? Did you use the stress test suite?  I guess how often it scales down could have an effect.

**Comment by thedrow** [comment]
It took less than a minute but I sent a lot of tasks at once.

**Comment by ask** [comment]
A lot of tasks, with pauses in between?  Lots of tasks does not reproduce it here

**Comment by thedrow** [comment]
No pauses. Are you on Linux?

**Comment by ask** [comment]
No, I'm on OS X!  Have you been able to reproduce this using the stress test suite? It would be nice if you used that since then we can test for regressions later.

**Comment by thedrow** [comment]
I did not reproduce it using the stress tests.
I was able to reproduce it on linux with redis and the ```--autoscale``` and ```-Ofair``` parameters.

**Comment by ask** [comment]
Sadly we don't have the resources to work on this, so we are undocumenting the autoscale feature for 4.0.
