### ISSUE TITLE
couchbase backend ValueFormatError

### ISSUE THREAD

**Issue by amg84** [celery/celery#2488]
I've configured celery to use the couchbase backend and I am getting a couchbase.exceptions.ValueFormatError whenever celery accesses the database, it looks like the key is a byte string rather than a unicode string: couchbase.exceptions.ValueFormatError: <Must be unicode or string, C Source=(src/convert.c,93), OBJ=b'celery-task-meta-e4c9050e-d29f-4be7-b7a6-e504b2c49319'>. I'm using python 3, JSON for serialisation and RabbitMQ as a broker.

software -> celery:3.1.16 (Cipater) kombu:3.0.24 py:3.4.2
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:couchbase://192.168.0.183:8091/celery

CELERY_ACCEPT_CONTENT: ['json']
CELERY_RESULT_SERIALIZER: 'json'
CELERY_TASK_SERIALIZER: 'json'

**Comment by amg84** [comment]
I compared the redis backend code to the couchbase backend and they both pass the key to the underlying libraries in the same way, the difference here is the redis library can cope with byte strings:
>>> import redis
>>> r = redis.StrictRedis(host='localhost', port=6379, db=0)
>>> r.get(b"celery-task-meta-8ad70ef7-839d-4877-ad34-f613db6bf821")
b'{"result": null, "children": [], "status": "SUCCESS", "traceback": null}'

**Comment by Smirl** [comment]
Also seeing this issue. The same set up as amg84. +1 to get this fixed.

**Comment by ask** [comment]
What key is this? Please include tracebacks!

**Comment by Smirl** [comment]
I think that I fixed this in https://github.com/celery/celery/pull/2660

**Comment by ask** [comment]
Ok, yeah, that makes sense.  Thanks!

**Comment by meteozond** [comment]
@ask Correct me if i'm wrong but your fix covers only key type case nor value.
