### ISSUE TITLE
SSL support (or documentation missing?)

### ISSUE THREAD

**Issue by mieciu** [celery/celery#2490]
Hi,

I'm using Django+Celery (celery==3.1.17) stack with AMQP backend in RabbitMQ. I would like to migrate my stuff to another RMQ backend, which requires SSL certificate authentication. 

I've seen one example on web (StackOverflow, not the docs):
```
 BROKER_USE_SSL={
     'ca_certs': os.environ['RMQ_TEST_CA_CERT'],
     'keyfile': os.environ['RMQ_TEST_CLIENT_KEY'],
     'certfile': os.environ['RMQ_TEST_CLIENT_CERT'],
     'cert_reqs': ssl.CERT_REQUIRED,
 }
```
But it does not work.

Also it seems like `BROKER_URL`  variable doesn't like `amqps://` protocol prefix:
`KeyError: 'No such transport: amqps.  Did you mean amqp?'`

All I can find in documentation is `BROKER_USE_SSL = True`, but what about certificate configuration?

**Comment by jeffx** [comment]
I'm encountering the same issue.  Currently trying to resolve the issue using BROKER_TRANSPORT_OPTIONS but not having much success.  You have any luck solving it for your solution? 

I realize this is from February, but it still seems relevant.

**Comment by ask** [comment]
Hey! The configuration option is documented now: http://docs.celeryproject.org/en/latest/configuration.html#broker-use-ssl

**Comment by jeffx** [comment]
Yeah.  My bad.  I did RTFM, but I was going from an SSL error to a different error assuming it was still an SSL error.  Once I read the logfile, I realized my real problem (trying to access a vhost the user didn't have access to).

Thanks!

**Comment by ask** [comment]
Good to hear :)

**Comment by j127** [comment]
In case anyone finds this, I think the documentation page is now here:
https://docs.celeryq.dev/en/latest/userguide/configuration.html

My problem went away when I used `rediss` (extra "s") and added `?ssl_cert_reqs=required` to the URL.
