### ISSUE TITLE
Channel errors recover through reconnection which is unecessary

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2491]
Celery 3.1 uses Kombu 3.0. Kombu 3.0 defines two error classes for errors raised by the transport.

`recoverable_connection_errors`
`recoverable_channel_errors`

The Kombu 3.0 interface is not very well documented, but there is [this post](http://comments.gmane.org/gmane.comp.python.amqp.celery.user/4854) which describes it some. There is also the [attribute docs here](http://kombu.readthedocs.org/en/3.0/reference/kombu.connection.html?highlight=recoverable_channel_errors#kombu.connection.Connection.recoverable_channel_errors).

From my testing it seems that Celery does not use the newer 3.0 style error classes. It should be safe to start using them immediately because Kombu falls back to the 2.0 style if a transport doesn't support the new style. Celery seems to use the old style `connection_error` and `channel_error`. Celery not using the new style causes channel errors to completely interrupt the connection which is not very efficient considering the Kombu 3.0 style is available as a requirement of Celery 3.1.

Another alternative would be to have Celery rely on Kombu for retry behaviors entirely since it does seem to support automatic retry through the use of decorators. I'm not as sure of how to do this though.

**Comment by auvipy** [comment]
@bmbouter is it still the case for kombu 4.x ?

**Comment by bmbouter** [comment]
@auvipy I'm not sure

**Comment by auvipy** [comment]
will reopen if pop up again.
