### ISSUE TITLE
worker_direct: Support for configurable auto_delete of queues.

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2492]
Normal, default use of Celery dispatches tasks as durable. They survive broker restarts, and celery component restarts (workers, celerybeat). I expect the [CELERY_WORKER_DIRECT](http://celery.readthedocs.org/en/latest/configuration.html#celery-worker-direct) queues to carry a similar durability, but instead any messages that are present on a worker direct queue are lost when either the worker dies/restarts or the broker dies/restarts.

To reproduce:
1) Dispatch a task onto a dedicated queue for a worker, and have it halt when it runs so the task never completes.
2) Dispatch a second task onto that same dedicated queue. Have it stay on the queue and not be received by the worker by starting it with `-c 1`.
3) Use a broker specific tool to list the number of messages in each queue.
4) Send a SIGKILL to the celery worker so that all celery processes are stopped
5) Verify the worker was stopped, and then start the worker again
6) List the number of messages in the queues and observe that the message that was in the dedicated queue is now gone

What type of workarounds can be done to avoid this behavior? What options are there to fix this in Celery?

**Comment by ask** [comment]
The queues are durable, it's just that they are auto_delete=True.

I guess the reasoning being that it would automatically clean up after temporary workers,
but it probably makes more sense to remove that flag.

**Comment by bmbouter** [comment]
@ask Can this issue be reopened? I have a proposal.

I think the behavior of `CELERY_WORKER_DIRECT` is a desired configuration point for celery users. There are valid use cases where you want workers to keep their queues in tact for when they restart and valid use cases where you want them to be auto-deleted. I propose the following:

1. negative commit  097dd74 and merge to master
2. Introduce a setting which controls the auto-deleting behavior of `CELERY_WORKER_DIRECT`. It could be called `CELERY_WORKER_DIRECT_AUTO_DELETE_QUEUE`. Introduce this on the 3.1 dev branch and have it default to 'True'. 3.1.x behavior of was to auto delete so it is backward compatible.
3. Add a release note  and docs for (2)
4. merge the code from (2) and some portion of the updated docs from (3) into the master branch to preserve the feature into the 4.0 release line.

**Comment by ask** [comment]
```
  <asksol>	bmbouter: a huge issue is that worker_direct() won't actually have access to the configuration
[15:12:23]  <asksol>	but I guess we could make it lazy and use a WorkerDirectQueue type so that send_task fills it out later
[15:13:45]  <asksol>	The setting name is too specialized I also think, it would be better if there was a CELERY_WORKER_DIRECT_QUEUE, that enables you to set the queue/exchange settings
[15:13:56]  <bmbouter>	yes I agree
[15:13:58] 	citizen-stig (~citizen-s@89.221.207.219) left IRC (Ping timeout: 250 seconds)
[15:14:03]  <asksol>	CELERY_WORKER_DIRECT_QUEUE = {'auto_delete': True}
```

**Comment by ask** [comment]
Note that there is nothing stopping you from doing this in 3.1 already:

```
from kombu import Queue, Exchange
from celery import signals

#: Exchange for worker direct queues.
WORKER_DIRECT_EXCHANGE = Exchange('worker_direct')

#: Format for worker direct queue names.
WORKER_DIRECT_QUEUE_FORMAT = '{hostname}.direct'


def worker_direct(queue):
    if not isinstance(queue, Queue):
        queue = Queue(
            WORKER_DIRECT_QUEUE_FORMAT.format(hostname=queue),
            WORKER_DIRECT_EXCHANGE,
            queue,
        )
    return queue


@signals.celeryd_after_setup.connect
def setup_direct_queue(sender, instance, **kwargs):
    instance.app.amqp.queues.select_add(worker_direct(sender))
```
