### ISSUE TITLE
Synchronously calling a task from within a task with __call__ overridden uses wrong task ID

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2494]
When we use Celery, we have tasks that we want to record book-keeping records for in our database when they start/stop/state, etc. It's convenient to add this behavior to specific tasks by having them use base=CustomTask where CustomTask is a class that inherits from celery.Task. In our CustomTask object we override `__call__` so that we can record that the call occurred. Consider this gist [0](https://gist.github.com/anonymous/cfd7872903c6f24e905c#file-async_call_sync_example-py-L4).

Single calls to these tasks work as expected, but if you have two tasks and execute the first one asynchonously (using delay) and call the second one synchronously (not using celery) then the second one shows up with the same task id as the first. That causes the book-keeping to incorrectly record these events. I expected the second task would receive a new task id since it is a separate task that expects book-keeping to occur.

It does seem celery has a codepath for exactly the situation where `__call__` is overridden and super is called [1](https://github.com/celery/celery/blob/a6ff6c1d62d8747c60eb665e915b568755ab2f90/celery/app/trace.py#L575). Would that be the place to add some logic to ensure that a synchronous call `__call__` would generate a new task id?

Also what are some alternatives to overriding `__call__`?

**Comment by ask** [comment]
Since the super causes `push_request` to be called, the new request does not exist when you are around the call (i.e. before and after).

I'm not sure what the best option is, it depends on what you are trying to do I guess.

**Comment by ask** [comment]
I think the best way to solve gist 0 would be to use a decorator, instead of overriding __call__.

To support overriding to do this we would have to create another level of indirection, so `self.__call__ -> self.execute -> self.run` and we would like to avoid that at this point.
