### ISSUE TITLE
When using object methods as tasks, is the whole object pickled and sent to the worker on a call to method.delay(..)?

### ISSUE THREAD

**Issue by phdowling** [celery/celery#2495]
I'm asking because this probably makes a big difference if my task involves, say, a neural network. In that case, large numpy matrices might be sent back and forth frequently between caller and worker, correct?

**Comment by ask** [comment]
The experimental celery.contrib.methods feature has been removed in 4.0 due to having way to many bugs to be useful.

**Comment by phdowling** [comment]
Just in case anyone still wants this: I wrote my own workaround for this. See https://github.com/phdowling/Celery-Remote-Methods

This allows you to call methods on remote objects via `obj.method_name_delay()` (breaking celery naming convention), and the state of the underlying object only gets transferred to the worker on the first call. Not really sure if this is even useful in any scenario though.
