### ISSUE TITLE
Workers stop processing tasks

### ISSUE THREAD

**Issue by zachsnow** [celery/celery#2505]
Every couple of weeks our worker stops processing tasks.  Nothing amiss in the celery logs, just one minute they are ticking along nicely, the next there are no more log entries at all. All the relevant processes are still running. Restarting the worker works fine and everything starts up again.

Running the most recent version:
```
celery==3.1.17
kombu==3.0.24
billiard==3.3.0.19
```

Using with Django, with Redis as broker. The only thing we've set is `CELERY_RESULT_BACKEND`, `BROKER_URL` (to the same value), and `BROKER_TRANSPORT_OPTIONS` (setting custom `priority_steps`) -- no other changes from the defaults there. When starting a worker we set `--maxtasksperchild=100`, `--concurrency=16` and set logging and select a queue, but that's all.

Running `celery status` does indeed respond, and shows 2 nodes are online (we run two workers with the above settings -- only 1 has ever "died", the one that gets significantly more traffic).

Wondering what kind of information I should collect next time it happens so that I can start tracking this down (I can't reproduce on a test setup so far). Cheers.

**Comment by joostdevries** [comment]
@zachsnow are you also seeing high CPU usage? Because that might indicate it's a dupe of #1845

**Comment by zachsnow** [comment]
@joostdevries I'm not, everything is idle.

**Comment by denisonfire** [comment]
@zachsnow there is something in the redis logs?

**Comment by zachsnow** [comment]
@denisonfire unfortunately not, as far as redis is concerned it seems to have been running fine.

**Comment by tigeronk2** [comment]
Check if my comment in https://github.com/celery/celery/issues/2469 helps.

**Comment by mikesun** [comment]
Similar at all to my issue? https://github.com/celery/celery/issues/2464

**Comment by zachsnow** [comment]
@mikesun yes that looks about right.

**Comment by zachsnow** [comment]
This looks like it is a duplicate of #2464.

**Comment by matt-dalton** [comment]
We have suddenly starting experiencing this with Celery 4.4.7 with Redis. I tried to post this in the duplicate issue but it was locked.

It bizarrely just suddenly started happening every few hours. We've tried:

- Removing `worker_max_tasks_per_child`
- Setting `Ofair` through `celery worker --uid celery -A my_app --loglevel=INFO -E -O fair`

Any other recent pearls of wisdom? Did you manage to fix this @zachsnow ?

**Comment by auvipy** [comment]
> I tried to post this in the duplicate issue but it was locked.

I have unlocked the dupl issue

**Comment by zachsnow** [comment]
Sorry @matt-dalton, reviewing our commit history it seems that, at the time, we believed `-Ofair` solved our problem. At this point enough things have changed that I don't believe our experience is going to prove helpful to you, apologies.

**Comment by trianglesis** [comment]
It now happened to me too:
celery=5.3.4
RabbitMQ 3.12.4

Trying to play with queues and worker pool restart - nothing helps. There are no errors or indicators that can help track the root cause.
