### ISSUE TITLE
Fail of last task from chain doesn't fail the chain

### ISSUE THREAD

**Issue by auuron** [celery/celery#2513]
Example:
tasks = (
    task1.si(*args, **kwargs),
    task2.si(*args, **kwargs),
    task3whichraiseserror.si(*args, **kwargs)
)
chain(*tasks).apply()

Result: Error is raised in task3whichraiseserror, but doesn't propagate the error.

Example 2:
tasks = (
    task1.si(*args, **kwargs),
    task2.si(*args, **kwargs),
    task3whichraiseserror.si(*args, **kwargs),
    task4(*args, **kwargs)
)
chain(*tasks).apply()

Result: Everything works fine (Error is propagated, last task is not run)

**Comment by caio1982** [comment]
Sorry, why was this closed without an explanation? Is this expected behavior? If so, where is this documented? I have the same issue and I do not understand why.
