### ISSUE TITLE
log spew with groups and chains

### ISSUE THREAD

**Issue by vkastala** [celery/celery#2516]
We do have something like below for task execution:

chain(
      group( (a | b | c),(d | b | c) ),
      chain((e | b | c),(e | b |c)),
      (f | b | c),
      (g | b |c),
      (h | b | c),
 )

a to h are tasks of which some can execute for few hours.

things are executing fine but when the first group (of (abc) and (dbc)) are executing we do see a spew of following message until that group finishes:

DEBUG Task accepted: celery.chord_unlock[34651b4d-42d9-43ab-beae-6e570d16e601] pid:6260
[2015-02-25 11:46:04,493: DEBUG/MainProcess] ???[???]: Task accepted: celery.chord_unlock[34651b4d-42d9-43ab-beae-6e570d
16e601] pid:6260
INFO Task celery.chord_unlock[34651b4d-42d9-43ab-beae-6e570d16e601] retry: Retry in 1s
[2015-02-25 11:46:04,493: INFO/MainProcess] ???[???]: Task celery.chord_unlock[34651b4d-42d9-43ab-beae-6e570d16e601] ret
ry: Retry in 1s

before the messages there is this msg which indicates about task pool of the next set of tasks after the group task:
2015-02-25 11:37:18,020: DEBUG/MainProcess] ???[???]: TaskPool: Apply <function _fast_trace_task at 0x036E38F0> (args:(
celery.chord_unlock', '34651b4d-42d9-43ab-beae-6e570d16e601', ('ce98a802-ad4e-4d20-b01f-4284d98851c3', ............

>pip freeze
Django==1.6.1
MySQL-python==1.2.4
amqp==1.4.6
celery==3.1.9
django-celery==3.1.10
kombu==3.0.23
simplejson==3.3.3

started celery in the following way:
celery -A <project> worker -l info

if I were to execute all of them in chain (as shown below) we do not see any spew:
chain(
      (a | b | c),
      (d | b | c),
      (e | b | c),
      (e| b | c),
      (f | b |c),
      (g | b |c),
      (h | b |c),
   )

We do understand that these are debug messages but is there a way to disable these for long running tasks?
Especially in cases where the tasks inside the group take very long time ( in matter of couple of hrs) logs are being filled up with these messages.

Please do let me know if you need more information.

--Venkat

**Comment by thedrow** [comment]
The chord_unlock task is related to chord management. It says that it will retry when a result is available. I don't think that we can move that message to debug since all task executions are recorded at INFO level but we can check.

**Comment by ask** [comment]
If the tasks run for hours, then change the implicit chords (`group() | task.s()`) into explicit chords and set the interval argument `chord(group(), task.s()).set(interval=60)` to have the chord unlock task wake up every 60 seconds instead.

The problem with logging is that there is either too much of it, or too little of it, and either way it does not contain the information you need.

Python logging also has the ability to let you filter out things, so I suggest you look at the Python logging documentation.
