### ISSUE TITLE
Some of the backends tests are disabled

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2517]
Our CI skips the tests for MongoDB, CouchDB, Riak and SQLAlchemy.
We need to enable them back and fix the tests if they fail.

**Comment by thedrow** [comment]
@ask Have we removed all these results backends? Can we close this issue?

**Comment by ask** [comment]
I didn't remove the result backends, I only removed the broker transports.  We could consider removing some of them, but I don't know which ones, and many of them seem to be working.

**Comment by thedrow** [comment]
So let's re-enable the tests. I'll take of it this weekend.

**Comment by ask** [comment]
They're all pretty much enabled now:

```
MISSING FROM CI REQS:
set([u'extras/auth.txt',
     u'extras/couchbase.txt',
     u'extras/librabbitmq.txt',
     u'extras/pyro.txt',
     u'extras/zeromq.txt',
     u'extras/zookeeper.txt'])
```
