### ISSUE TITLE
--without-gossip causes hung workers and one permanently unacked message

### ISSUE THREAD

**Issue by xtfxme** [celery/celery#2519]
Using the exact same fail case in #2518, but simply reversing the last two steps and appending `--without-gossip` causes workers to enter a permanent fail scenario where the worker will pull a message but never ack or process it, effectively locking the worker.  Steps to reproduce are duplicated here:

```python
# jsonresults.py
from celery.app.base import Celery

CELERY_RESULT_BACKEND = 'amqp'

app = Celery(config_source=__name__)

@app.task
def hello():
    raise ValueError('go away')
```

caller (adds a message before worker is running):

```python
import jsonresults
# this will NEVER return! not calling get() makes no difference; bug in worker not caller
jsonresults.hello.delay().get()
```

worker:

```
# python -m celery --app=jsonresults:app worker --without-gossip
```

**Comment by xtfxme** [comment]
Using `--without-heartbeat` has the same effect, and `librabbitmq` transport has the same problem.

I'm having a hard time pinning this one down... seems bug could be in kombu or lower.  I've been able to determine that the unacked message is in fact properly read by the transport, but the `basic_deliver` occurs while **waiting** for a `basic_qos_ok` message from the server. The message is queued properly for delivery to the channel, but the channel is never notified after the `basic_qos_ok` finally comes and is handled.

Heartbeats and/or gossip cause unrelated `basic_publish` chatter; this might be draining the incoming queue (pure speculation at this point).

Can anyone confirm this behavior?

**Comment by twork-veracode** [comment]
Yes! I just ran into the exact same issue. However, removing `--without-gossip` did not fix my problem. Here's what I'm experiencing:

1. Start worker
2. Queue task
3. Task starts, no questions asked

1. Queue task
2. Start worker
3. Task is pulled from the queue, but never started and never asked, resulting in a worker that is effectively hung forever

**Comment by twork-veracode** [comment]
Also, have you seen https://github.com/celery/celery/issues/1847 ?

**Comment by xtfxme** [comment]
Ah nice, thanks for the link -- that definitely looks like the same problem.
