### ISSUE TITLE
Calling a group signature applies the tasks to workers, rather than running them in the current process

### ISSUE THREAD

**Issue by MaximilianR** [celery/celery#2521]
I have a group signature, `group_signature`, and when I run `group_signature()`, the tasks are applied and evaluated by the workers - i.e. the same behavior as had I run `group_signature.delay()`

My understanding from the [docs](http://celery.readthedocs.org/en/latest/userguide/canvas.html#signatures) is that the tasks should be evaluated in the local process. Is that understanding correct? 

I can post my code etc if I that is correct, if anyone wants to attempt to replicate.

Thanks,
Max

**Comment by thedrow** [comment]
Sorry for the late response. Please do post your code.

**Comment by ask** [comment]
group is a task that applies other tasks, and group.__call__ executes that task.  It's the same with the other canvas primitives.
