### ISSUE TITLE
Multiprocess & multi-thread worker type 

### ISSUE THREAD

**Issue by diwu1989** [celery/celery#2524]
There's a multi-process worker type, and there's a threadpool multi-thread worker type.

Can you enhance the multi-process worker type to include multi-thread as well? So that we can configure it to be N processes, with each running M threads?

**Comment by PMickael** [comment]
You can do this by using multi, `celery multi start 3 -c 3 --pool=eventlet` will start 3 process with 3 thread each

**Comment by diwu1989** [comment]
cool thanks!
