### ISSUE TITLE
RPC Backend results in messages with old consumer tags being delivered, and ignores them.

### ISSUE THREAD

**Issue by vinodc** [celery/celery#2529]
When using the RPC results backend, I have noticed that messages are sometimes delivered with stale consumer tags by RabbitMQ, resulting in the requestor never obtaining the result. This occurs most often when there are several (10+) results waiting on the results queue to be consumed.

The AMQP backend [consumes](https://github.com/celery/celery/blob/3.1/celery/backends/amqp.py#L227) data with a new Consumer each time. This Consumer's `__enter__` [sets](https://github.com/celery/kombu/blob/master/kombu/messaging.py#L565) a new consumer tag, and `__exit__` [cancels](https://github.com/celery/kombu/blob/master/kombu/messaging.py#L401) consuming with that tag. The next time we attempt to drain events, we are reusing the same binding with a new consumer tag and pyamqp shows that messages are delivered with the old consumer tag (hitting [this line](https://github.com/celery/py-amqp/blob/master/amqp/channel.py#L1614) in the code) and never result in the Consumer's callback being called. Therefore, these messages never make it into the RPC backend's `_cache` and subsequent `get()` calls do not obtain the data.

As an attempt to solve this, I modified the rpc backend code to reuse the same Consumer object each time, and also not cancel consuming on `__exit__`.  While this resolved the problem when data was retrieved serially, it did not work when using gevent to obtain results from within multiple greenlets simultaneously, as only one of the greenlets drained all the events and existing result objects waiting on `get()` were not updated.

Were there any thoughts on how to resolve this problem?

**Comment by ask** [comment]
Fixed in master
