### ISSUE TITLE
Beat _Process class raise Exception on _Popen

### ISSUE THREAD

**Issue by PMickael** [celery/celery#2530]
Hi,

With last version of billiard / celery there is a problem to start beat with a worker like this :
celery -A app worker --beat

`Unrecoverable error: TypeError('_Popen() takes exactly 1 argument (2 given)',)`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 208, in start`
`    self.blueprint.start(self)`
`  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start`
`    step.start(parent)`
`  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start`
`    return self.obj.start()`
`  File "/usr/local/lib/python2.7/dist-packages/billiard/process.py", line 124, in start`
`    self._popen = self._Popen(self)`
`TypeError: _Popen() takes exactly 1 argument (2 given)`

Changing import here https://github.com/celery/celery/blob/master/celery/beat.py#L24 by
`from billiard.context import Process`
Make it works, but I don't know If it's really a good solution.

Mickael

**Comment by risingsunomi** [comment]
I got the same issue when using the dev version of celery because of the version on pip not working with django 1.8 [2582](https://github.com/celery/celery/issues/2582) shows this issue I was getting before using the celery dev version. After running

>pip install https://github.com/celery/celery/zipball/master#egg=celery --upgrade
>pip install https://github.com/celery/billiard/zipball/master#egg=billiard --upgrade
>pip install https://github.com/celery/py-amqp/zipball/master#egg=amqp --upgrade
>pip install https://github.com/celery/kombu/zipball/master#egg=kombu --upgrade

I got celery to finally launch but got this error

```
[2015-04-17 11:10:13,366: CRITICAL/MainProcess] Unrecoverable error: TypeError('_Popen() takes exactly 1 argument (2 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 208, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
TypeError: _Popen() takes exactly 1 argument (2 given)
```

I am going to try this fix and see if it works

**Comment by risingsunomi** [comment]
After going to 
>/usr/local/lib/python2.7/dist-packages/celery/beats.py

And changing
>from billiard.process import Process
to
>from billiard.context import Process

celery started normally with the command
>celery -A proj worker -l info -B

So this fix works. 

Thanks Mickael

**Comment by bastbnl** [comment]
This issue popped up on me today when I started Django 1.10 with celery==3.1.23, billiard==3.5.0.0 and kombu==3.0.35 using python 2.7.

risingsunomis' solution was almost ok; I had to work on **/usr/local/lib/python2.7/dist-packages/celery/beat.py** instead of /usr/local/lib/python2.7/dist-packages/celery/beats.py

**Comment by smcoll** [comment]
Same issue for me, after upgrading some requirements.  i'm using the same versions @bastbnl reported, except i'm on Django 1.8.14.

**Comment by bastbnl** [comment]
The issue is back again when using celery==1.3.24 with Django==1.10.2 and billiard==3.5.0.1.

**Comment by auvipy** [comment]
billiard 3.50.1 needed celery 4.0.0rc4

**Comment by hakanw** [comment]
+1 after updating billiard, amqp and kombu to latest but staying on latest stable celery 3.x
