### ISSUE TITLE
Reload on RSS

### ISSUE THREAD

**Issue by joshowen** [celery/celery#2532]
Are there any plans to add a reload on rss flag, like [uwsgi has](http://uwsgi-docs.readthedocs.org/en/latest/Options.html#reload-on-rss)?  It is very helpful for memory constrained environments like Heroku.

**Comment by joshowen** [comment]
I see this was implemented in these PRs:
https://github.com/celery/celery/pull/2366
https://github.com/celery/billiard/pull/126

Any plans to merge them?

**Comment by joshowen** [comment]
@ask any thoughts on adding a reload on rss flag like uwsgi has?  We use the gevent workers, but sometimes our memory usage increases and causes paging, which really hurts on Heroku, and since the memory is never released, continues to slow down future tasks.  UWSGI restarts the process containing the greenlets if its RSS is over a set threshold (after the requests its working on have returned)

**Comment by alexhayes** [comment]
While it's obviously not exactly the feature you're asking about I've found that the [--maxtasksperchild](http://celery.readthedocs.org/en/latest/userguide/workers.html#max-tasks-per-child-setting) flag is helpful if you have memory issues with workers.

**Comment by joshowen** [comment]
That doesn't work with gevent unfortunately.

**Comment by thedrow** [comment]
Both PRs need rebasing and I'll need @ask to take a look since I don't know much about the mechnisms you guys are using to restart tasks that take to much memory.
Also, I'd rather hold off adding new features until we resolve our more critical bugs.

**Comment by joshowen** [comment]
Thanks.  The PRs won't work with gevent, but its a start :)

**Comment by ask** [comment]
The pull requests were merged.

it's impossible to support this for gevent, for that you would need to look at what is supported for whatever tool you are using to deploy the worker.
