### ISSUE TITLE
Needs more maintainers

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2534]
Celery isn't advancing as fast as it should.
We need more maintainers to merge and review pull requests, answer issues and push this awesome project forwards.
Right now @ask acts as the only maintaner for this project and he's only one person that can contribute so many commits.
What do you guys think about recruiting maintainers on a quarterly basis like Django REST Framework does?

**Comment by chrisgogreen** [comment]
I'm just starting to use Celery but am willing to contribute. Which issue should I look at first?

**Comment by thedrow** [comment]
There are issues with task consumption where celery simply freezes or stop processing tasks.
I think that they should be dealt with ASAP.

**Comment by chrisgogreen** [comment]
existing issue numbers?

**Comment by thedrow** [comment]
Yup.

**Comment by maximilianr** [comment]
+1 - there are 50+ outstanding pull requests and hundreds of issues...
I know from our end we'd be happy to buy consulting services to solve some of the problems we have, and those solutions could go back to the community. I see other people asking too, so that could be a way of getting some of the issues dealt with.

**Comment by thedrow** [comment]
@ask Are you ok with recruiting more maintainers?
I'm willing to help to recruit them and raise funds for a paid internship.

**Comment by PMickael** [comment]
Hi, I will be pleased to help with this issue too.

**Comment by ask** [comment]
> On Mar 19, 2015, at 12:07 PM, PMickael <notifications@github.com> wrote:
> 
> Hi, I will be pleased to help with this issue too.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/celery/celery/issues/2534#issuecomment-83527169>.
> 

Need all the help we can get!  Especially triaging issues etc.

I can give repository access/commit to anyone interested in this, just tell me what you want to work on!

-- 
Ask Solem
twitter.com/asksol | +44 07454281208

**Comment by PMickael** [comment]
I actually work on/with celery and billiard, so maybe on this 2 repo if possible.

**Comment by ask** [comment]
> On Mar 19, 2015, at 12:37 PM, PMickael <notifications@github.com> wrote:
> 
> I actually work on/with celery and billiard, so maybe on this 2 repo if possible.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/celery/celery/issues/2534#issuecomment-83538963>.
> 

I’ve given you access to all the repos now, there should be a mail from Github sent to you.

With access to all of them you can jump into anything you feel you want to help out with.
There is little chance for disaster as I review changes before releases anyway, so don’t
be too afraid to break something.  it can always be fixed :)

-- 
Ask Solem
twitter.com/asksol | +44 07454281208

**Comment by PMickael** [comment]
Thanks, I will try to help only where I'm confident with.

**Comment by PMickael** [comment]
Seem like I don't have enough right, I can't merge a pull request or close an issue.

**Comment by ask** [comment]
@PMickael Sorry, seems I didn't properly add you to the umbrella team, please try now!e

**Comment by malinoff** [comment]
@ask hi, I can and would like to help with reviewing and accepting patches too.

**Comment by ask** [comment]
@malinoff, Hey mate! I've invited you now, and think you should have access.  Just tell me if something is not working, or you need more access

**Comment by malinoff** [comment]
@ask thank you!

**Comment by thedrow** [comment]
@ask I think we should keep this issue a bit longer so that we'll recruit at least two more maintainers.
What do you think?

**Comment by ask** [comment]
Yeah! Definitely, we are still recruiting :)

**Comment by thedrow** [comment]
Maybe we should edit the README to point to this issue?

**Comment by ask** [comment]
> On May 8, 2015, at 7:47 PM, Omer Katz <notifications@github.com> wrote:
> 
> Maybe we should edit the README to point to this issue?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/celery/celery/issues/2534#issuecomment-100324956>.
> 

I really doubt that would be benefitial, e.g the docs have had donation links for years now and still only receive about $30 in a year ;)

-- 
Ask Solem
twitter.com/asksol | +44 07454281208

**Comment by thedrow** [comment]
Just bumping this so that people will still see it.

**Comment by raghuramos1987** [comment]
I'm pretty new to celery. But I would like to pitch in and learn more. Both from contribution and reviews.

**Comment by thedrow** [comment]
@raghuramos1987 Please start by investigating the issues mentioned by @chrisgogreen above and trying to fix them.

**Comment by raghuramos1987** [comment]
looking more into this... [2621](https://github.com/celery/celery/issues/2621) also seems to be something which should be part of this list.

**Comment by rattrayalex** [comment]
Perhaps listing active maintainers on the README, along with an ask for more, could help encourage others to join? Devs are often more eager to contribute time than money for open-source projects in my experience.

**Comment by thedrow** [comment]
@rattrayalex I completely agree.
Pull Request anyone?

**Comment by rattrayalex** [comment]
Awesome. I'll try to submit a PR using the maintainers who volunteered above, so that @ask can just tell me where I'm wrong'?

**Comment by madhugb** [comment]
Need Some heads up, I am using celery from 4 5 months. Never tried to dig deep, will definitely try to contribute.

**Comment by thedrow** [comment]
Since I see there hasn't been many people who volunteered I'm willing to help maintain celery.
I can't promise more than what I already do right now except merging pull requests when they are ready since I'm pretty busy with other open source projects and my day job but if it will help move the project forwards I'm in.

**Comment by ask** [comment]
@thedrow, That's good news!  I invited you now so you should receive a mail from GitHub

**Comment by thedrow** [comment]
Thanks :)

**Comment by thedrow** [comment]
@madhugb We need people looking into issues and helping people out (and the maintainers) to figure out what's the proper fix for something.

**Comment by madhugb** [comment]
@thedrow Sure, I am willing to get my hands dirty :-)

**Comment by thedrow** [comment]
@madhugb You could also write a test for https://github.com/celery/celery/pull/2660 so that it will be merged.

**Comment by jackyfkc** [comment]
I guess if someone could write a series of articles to introduce the internals of Celery. 

Some parts of source code looks somewhat weird (like the treatment of timezone is a little fuzzed) when I attempt to supporting remote control the beats ( Add/Update/Delete job at run time )

**Comment by madhugb** [comment]
I agree with @jackyfkc I am finding it hard to figure things out. May be a block diagram would help.

**Comment by thedrow** [comment]
@ask is probably the guy to ask to do this since he knows the codebase best.

**Comment by ask** [comment]
How would a block diagram help? :)

The code is fairly well organized into specific sections, if there is anything specific you want to know then I can try to explain it.

The difficult parts will probably be `celery.concurrency.asynpool` (good luck!), the result backends (outdated terminology), and `celery.app.trace` (task execution).

Timezones are messy since there were no guidelines at the time when I started that work: the only recommendation was to use naive datetimes until you actually need to present the time to a user/externally, and that naive datetimes† are assumed to be in UTC time.

This is the case with celery, unless you have `CELERY_ENABLE_UTC` set which means that naive datetimes are assumed to be in local time (`celery.utils.timeutils.LocalTimezone`)

All the timezone related code is in `celery.utils.timeutils`, this could definitely be cleaned up but everything shares the same code.


Beat supporting remote control commands (pidbox) will be tricky as the beat process is blocking.  When it's busy blocking (e.g. `time.sleep()`ing, or publishing a task message), then it cannot also be consuming
remote control commands.  Similarly, when it's processing remote control commands it cannot schedule periodic tasks.


† datetime with no timezone set (`dt.tzinfo is None`).

**Comment by jackyfkc** [comment]
@ask, It would be great if you would like to share the internals of the above three topics.
> The difficult parts will probably be celery.concurrency.asynpool (good luck!), the result backends  (outdated terminology), and celery.app.trace (task execution)

By the way, relating to remote control on beat, my solution is simple, using multi-threading, a main thread is used to accepting remote commands, together with a worker thread to run the original beat loop (celery.beat.Service.start).

As you said, this would  introduce latency (due to time.sleep() or publishing a task message) on dealing the new incoming commands. An improved method would be using a new loop which handle both incoming commands and time events, and put the expired tasks (required to publish) into a queue. The actual publish works are done asynchronously in a new thread or process.

**Comment by maximilianr** [comment]
@ask I'm not sure this is helpful feedback in response to your post, but regardless: We love celery, and it's a truly beautiful app. That said, we do find it extremely complicated. Maybe it needs to be that complicated, I don't know. We're a small team of varying technical abilities, and we have had a fair amount of pain getting it to work well. 

I think it would be worth reflecting on why there are a number of people working on RQ, when it seems to be dominated by celery in features. I'd imagine simplicity is a bit part of it. We've also considered using products such as IronWorker, Domino & AWS Lambda to abstract some of the complication away.

Separately, we'd also be happy to pay for support. I know there are a fair number of enterprise customers (namely Instagram) who use celery, so potentially they could be a reasonable market for this.

**Comment by thedrow** [comment]
@maximilianr While we'd love to have people pay for support I don't think it's possible right now since none of us have the time to invest in celery more than we currently do. If we had commercial support we could keep this project viable and alive.
If hiring someone is an option that would be lovely but that would have to be someone who has proven he knows his way around Celery's code base and the only one around that does is @ask and he is pretty busy right now as far as I know.
We do have a kickstarter planned that is waiting for more ideas, feedback and developers willing to commit to put work into it. See #2655.

**Comment by malinoff** [comment]
@maximilianr about RQ, this project is very opinionated, starting with only Redis support as broker. Because of this it is simple (of course) and docs are great.
Celery tries to be configurable and

**Comment by malinoff** [comment]
Sorry, wrong button :)

**Comment by dabaitu** [comment]
Hi guys, is there a jira board for issues where people can pick up tasks? I love python, and have heard about Celery recently. I hope to contribute. Thanks!

**Comment by malinoff** [comment]
@dabaitu github issues

**Comment by thedrow** [comment]
@dabaitu You can find the board at https://waffle.io/celery/celery

**Comment by dabaitu** [comment]
Thanks! @malinoff @thedrow

**Comment by thedrow** [comment]
@ask Do you feel we have enough maintainers? Do we need more active maintainers?

**Comment by ask** [comment]
@thedrow, We always need more, but we are definitely in better shape :o)

**Comment by ask** [comment]
And have to mention that @auvipy has recently been managing django-celery, and he's exceeding expectations.  @auvipy I've given you access to all repositories in the Celery org, could you please add yourself to the committers section in `docs/contributing.rst`?

**Comment by auvipy** [comment]
thanks you :) I will :dancer:

**Comment by auvipy** [comment]
and i will help to maintain other umbrella projects too as I also use them :)

**Comment by berkerpeksag** [comment]
I can also help with triaging issues and reviewing pull requests (especially the ones about documentation and Python 3.)

**Comment by auvipy** [comment]
@ask a core python developer like @berkerpeksag in the team should be more useful

**Comment by auvipy** [comment]
@berkerpeksag i need ur suggestions/help in porting @celery/librabbitmq to python3

**Comment by thedrow** [comment]
@auvipy Frankly I'd rather someone port the library to CFFI so that'd it be able to run on PyPy as well. I don't know if it will beat the pure python version but it might.

**Comment by auvipy** [comment]
@thedrow  i was also checking cffi as an option

**Comment by ask** [comment]
@berkerpeksag Happy to have you here! I sent an invitation to the Celery github team, please accept :)

**Comment by georgepsarakis** [comment]
@thedrow @ask I believe I can also help with issue triage and reviewing pull requests. Not sure how much time I can dedicate, but I will try to be as active as possible.

By the way, kombu and celery are great projects!

**Comment by thedrow** [comment]
@georgepsarakis I just sent an invite.

**Comment by georgepsarakis** [comment]
@thedrow just accepted, thanks!
