### ISSUE TITLE
Celery + Django. Invalid Values for sys.stdout and sys.stderror Throws TypeError

### ISSUE THREAD

**Issue by DavidMuller** [celery/celery#2536]
I am trying to install celery with Django 1.8b2 (following the [celery + django install instructions](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html#starting-the-worker-process)).

Trying to launch a celery worker like

```shell
celery -A my_project worker -l info
```

causes a TypeError if Django's SystemCheck system needs to output an error message:

```python
  File "/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/celery/fixups/django.py", line 162, in validate_models
    cmd.check()
  File "/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/django/core/management/base.py", line 530, in check
    self.stderr.write(msg, lambda x: x)
TypeError: function takes exactly 1 argument (2 given)
``` 

As astutely noted by a Django maintainer (see [ticket] (https://code.djangoproject.com/ticket/24477#comment:1)), the following [line in `celery/fixups/django.py` incorrectly sets the values for `BaseCommand.stdout` and `BaseCommand.stderr`](https://github.com/celery/celery/blob/master/celery/fixups/django.py#L161) :

> Management's commands `self.stderr` and `self.stdout` should be instances of `OutWrapper` whose `write()` method support more than one argument (in this instance, a style_func argument used for formatting).

**Comment by cmaring** [comment]
When will this be released?

**Comment by vinograd19** [comment]
This commit https://github.com/celery/celery/commit/8a2c3b18a754b13b8458c71bd976d1d74a0cbbb4 does the fix

**Comment by ryanhiebert** [comment]
Running into this issue when trying to upgrade my project to the release version of Django 1.8. I'd definitely appreciate if this got released to PyPI soon.
