### ISSUE TITLE
Expand task result stored information

### ISSUE THREAD

**Issue by camilonova** [celery/celery#2540]
We are storing task results so we can review them at the admin site of a Django project, when the returned string is long it gets stripped like:

![task_detail](https://cloud.githubusercontent.com/assets/202559/6713958/b46c7c46-cd63-11e4-92c1-8ec0f4e8b841.png)

Looking at the result field on the models it is a TextField, so is capable of storing more text than is doing right now, can you tell how can I do to see there the full text and not the stripped one?

At first I was thinking about the admin interface, but when I retrieve the data in the python shell it shows the same striped content, so seems the result is stripped when is going to be saved, maybe you are using pickle or something to serialize it, but I'm not sure.

**Comment by jerzyk** [comment]
What you have here is task status, not task result. This is only a diagnostic information written here by the camera. If you want to get results properly, use AsyncResult ([documentation](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.AsyncResult))
```
task_result = AsyncResult(task_id)

result = task_result.get()

```

**Comment by camilonova** [comment]
@ask Thanks bro :beers:
