### ISSUE TITLE
Specifying per worker pool implementation with `celery multi`

### ISSUE THREAD

**Issue by amirrustam** [celery/celery#2548]
Currently it is not possible to specify per worker pool implementation (-P) with `celery multi`. Per worker or per worker range settings are available for the queue (-Q) and concurrency (-c) settings. To be clear you can't do something like this:

````
$ celery -A proj multi start 2 -P:1 gevent -P:2 prefork -c:1 1000 -c:2 4 -Q:1 queue1 -Q:2 queue2
````
The -Q and -c arguments are valid, but not the -P arguments where one worker is set to use the gevent pool and another is set to use prefork. To specify per worker pool implementation you must do two independent `celery worker commands`:

````
$ celery -A proj worker start -P gevent -Q:queue1 -c 500
$ celery -A proj worker start -P prefork -Q:queue2 -c 4
````

However, running multiple `celery worker` commands to specify per worker pool types makes things difficult within the celeryd deamon configuration file. As shown in the Daemonization section of the docs (http://celery.readthedocs.org/en/latest/tutorials/daemonizing.html?highlight=celeryd_nodes#example-configuration):

Multiple workers can be specified like so within the config file (/etc/default/celeryd):

CELERYD_NODES="worker1 worker2"

And additional command line arguments can be specified like so:

CELERYD_OPTS="-Q:worker1 queue1, -Q:worker2, -c:worker1 1000 -c:worker2 4"

BUT there is no `CELERYD_OPTS` for each worker. Internally the daemonization script is going to be using `celery multi` (right?). So workers are not started with independent `celery worker` commands in this scenario.

__It would great if flexibility of the -P argument could match -Q and -c where you can specify per work and per worker range settings.__

*P.S. @ask if you don't have any objections to this proposal I would be happy to find some time and submit a pull request for this.*

**Comment by PMickael** [comment]
Would be nice, I will merge it if you want to do it.

**Comment by amirrustam** [comment]
I'm glad it's a worthwhile addition. I will follow up once I got something.

**Comment by thedrow** [comment]
I was under the impression that this is possible.
@ask am I not correct?

**Comment by ask** [comment]
I just tried this here, and it works just fine.   All of the worker arguments supports the special format, including -P

**Comment by thedrow** [comment]
@amirrustam How did you try to invoke celery multi?

**Comment by PMickael** [comment]
I think it's just a doc update who is needed, I also thought that wasn't possible, but actually it works, I rewrite a start service for my own usage, and also add `killrestart`, maybe I will do an update, It's really usefull in my case, where tasks take a while to be execute and sometimes code is update and I want to restart process immediatly (maybe there is a better solution also but I didn't find any).

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by d3prof3t** [comment]
Hi @ask , is there any plans of picking this up?
