### ISSUE TITLE
Nested chords result in celery.chord_unlock looping endlessly

### ISSUE THREAD

**Issue by TauPan** [celery/celery#2554]
I'm seeing something related to #1700 and #2219, but with nested chords/groups if all tasks succed.

I don't know yet how to reproduce this. The reason I use nested chords is that I have some high-level and low-level tasks, both of which require some degree of parallelism and synchronisation, so a chord is a natural choice on both levels.

**Comment by TauPan** [comment]
I'll try to come up with a more concrete example, but I'd also appreciate some ideas what might cause this, so I can create an example.

celery 3.1.17
rabbitmq as broker (3.1.5)
django-celery 3.1.17, using django cache as result backend, however I'm quite sure I've seen the same behaviour with redis as result backend
python 2.6 and python 2.7

**Comment by TauPan** [comment]
I've just failed to reproduce this with redis as result backend. So much for my memory.

No idea if this happens with other result backends as well, I'm going to switch back to redis.

**Comment by aphillipo** [comment]
I experience this.  Did you close this bug because you found a solution?

**Comment by TauPan** [comment]
I closed it because I couldn't find a simple way to reproduce it and switching to redis fixed it, so it's too much trouble to keep this open.

**Comment by aphillipo** [comment]
I can get away with a chain(group([]), finally)  so I'll just do that.  Switching backend makes no difference for me!  Thanks.

**Comment by thedrow** [comment]
This sounds pretty severe.
@aphillipo Can you provide a test case that consistently fails?
