### ISSUE TITLE
canvas results are sometimes missing

### ISSUE THREAD

**Issue by jerzyk** [celery/celery#2556]
celery 3.1.17 and 3.2.a2, redis as broker and result backend

very simple tasks definitions:
```python
@shared_task
def t1(a):
    return "t1: {}".format(a)

@shared_task
def t2(a):
    return "t2", a
```

create and call a `chord`
```python
In [3]: g = chord([t2.s(1), t2.s(2), t2.s(3)], t1.s())

In [4]: g.delay().get()
Out[4]: u"t1: [[u't2', 1], [u't2', 2], [u't2', 3]]"
```

everything fine, results as expected, so let's chain this with one more task:
```python
In [5]: g1 = g | t1.s() 

In [6]: g1.delay().get()
Out[6]: u"t1: [[u't2', 1], [u't2', 2], [u't2', 3]]"
```

ups... no change - wrong, result is exactly as it came from the `chord` not a new chain, let's try this with function `chain`

```python
In [7]: g1 = chain(g, t1.s())

In [8]: g1.delay().get()
Out[8]: u"t1: [[u't2', 1], [u't2', 2], [u't2', 3]]"
```

same story, so `|` and `chain` works here exactly same

let's add one more task to the chain:
```python
In [9]: g1 = g | t1.s() | t1.s()

In [10]: g1.delay().get()
Out[10]: u"t1: t1: t1: [[u't2', 1], [u't2', 2], [u't2', 3]]"
```

ups... now everything is fine again, even "missing" intermediate result

**Comment by traut** [comment]
I see exactly same issue - a chain that connects a chord and a task returns result of a chord, though task also executes

**Comment by ask** [comment]
All examples provided works in the master branch!
