### ISSUE TITLE
task.retry connects to localhost instead of celeryconfig.BROKER_URL

### ISSUE THREAD

**Issue by svstuns** [celery/celery#2562]
I have the following scenario:
- rabbitmq installed on server A
- celery installed on 2 different servers, B & C

A task defined by me uses the .retry call to retry calls that fail.
What happens is that the .retry call tries to re-queue the message by connecting to the localhost instead of the server where rabbitmq is installed.
This happens even though the BROKER_URL is correctly set in the celeryconfig.py file.
Also, celery is able to receive messages from rabbit without issues (thus the task is able to run 'till the retry call).

As a note, this does not happen when celery and rabbitmq are installed on the same server (for obvious reasons, since retry connects to localhost, thus the same machine).

Also, I was able to solve this by using the celery.messaging.establish_connection method and passing the connection that gets create by this call to the .retry method, that is then passed to the apply_async call. But I am a bit worried about creating connections manually, I would prefer celery does it, since it might do additional stuff that I am not aware off.

Other details:
- celery version: latest
- python version: both 3.3 and the latest version
- platform: windows 7, x64
- error stack trace:
```
----------------------------------------------------
[2015-03-31 10:23:52,197: WARNING/MainProcess] Task tasks.subscribe[e6fa9242-3b4c-4906-a898-24e393a9d60b] reject requeue=False: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "\python33\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "\python33\lib\site-packages\celery\app\trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "\Scripts\emailServiceProvider.py", line 43, in subscribe
    raise self.retry(exc=exc)
  File "\python33\lib\site-packages\celery\app\task.py", line 678, in retry
    raise Reject(exc, requeue=False)
celery.exceptions.Reject: (OSError(ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061),), False)
----------------------------------------------------
```

**Comment by ask** [comment]
Make sure you use bind=True, and `self.retry` not Task.retry, as documented in the latest task userguide:
http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying

**Comment by soufiaane** [comment]
i am having the same issue,
@svstuns can you show me how did you managed to work around this issue ?

config:
- celery version: 3.1.20
- python version: 3.5.1 x64
- platform: windows 10, x64
- error stack trace:

> [2016-04-17 15:23:48,487: WARNING/MainProcess] Task report_hotmail[48bf1447-c581-4f39-b5d4-81541320b306] reject requeue=False: [WinError 10061] No connection could be made because the target machine actively refused it
> Traceback (most recent call last):
>   File "C:\Python35\lib\site-packages\celery\app\trace.py", line 240, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "C:\Python35\lib\site-packages\celery\app\trace.py", line 438, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "C:\Reporting\tasks.py", line 1790, in report_hotmail
>     raise self.retry(exc=exc, max_retries=3, countdown=0,throw=False)
>   File "C:\Python35\lib\site-packages\celery\app\task.py", line 694, in retry
>     raise Reject(exc, requeue=False)
> celery.exceptions.Reject: (OSError(ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None),), False)

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by svstuns** [comment]
@soufiaane What I did is I forced the task to read the configs again, check this piece:

**Comment by svstuns** [comment]
@ask I am using Bind=true and self.retry, I know that without the bind thing it does not work. Seem to me that the problem lies somewhere else in the celery code.
