### ISSUE TITLE
ignore_result=True in add_unlock_chord_task preventing all backend reporting?

### ISSUE THREAD

**Issue by kylemacfarlane** [celery/celery#2563]
I followed the startup guide using the Django model backend from django-celery. However despite the worker saying that tasks were running I was getting no results.

I traced the reason down to `publish_result` in `celery.app.trace.build_tracer` always being `False`, which was caused by `ignore_result` always being `True`.

The source of this seems to be here: https://github.com/celery/celery/blob/053858c267e4770d5e2976d1ab14a73e9d86db75/celery/app/builtins.py#L60 as changing`ignore_result` to `False` here seems to fix the problem.

    @app.task(name='celery.chord_unlock', max_retries=None, shared=False,
              default_retry_delay=1, ignore_result=True, lazy=False, bind=True)

There's a lot of existing issues with missing results but they seem to be mostly on Windows while I'm using Linux.

**Comment by thedrow** [comment]
Can you please provide a working test case that reproduces the problem?
@ask why does the task needs to ignore it's result?

**Comment by ask** [comment]
Nothing is waiting for the result of the unlock_chord task, what is pertinent is the result of the chord callback

**Comment by thedrow** [comment]
So what could cause the worker to hang if ignore_result is True for chord_unlock?

**Comment by ask** [comment]
Do you know the traceback of where it's hanging?

**Comment by thedrow** [comment]
@kylemacfarlane Do you have a traceback for us or an example we can use to reproduce the problem?

**Comment by kylemacfarlane** [comment]
I'll see if I can repeat the problem tomorrow.

**Comment by kylemacfarlane** [comment]
I figured it out and it's not anything to do with unlock_chord.

The problem is that `PeriodicTask` doesn't obey the global ignore result setting: https://github.com/celery/celery/blob/v3.1.18/celery/task/base.py#L147

Two ways to fix the problem:

1. Explicitly set `ignore_result=False` for all my periodic tasks (bit of a pain).
2. Completely remove line 147 which seems to make periodic tasks obey `CELERY_IGNORE_RESULT`.

**Comment by thedrow** [comment]
I think that the correct behaviour is to ignore the result unless CELERY_IGNORE_RESULT is specified.
Ignoring the result of a periodic task makes sense since usually no one would use it.

**Comment by kylemacfarlane** [comment]
For me it wasn't working even with CELERY_IGNORE_RESULT set to False. The only way to get results from periodic tasks is like `@periodic_task(ignore_result=False)` or equivalent.

If the difference between tasks and periodic tasks is on purpose then it should probably be mentioned either in the result backend docs or the periodic tasks docs.

**Comment by ask** [comment]
Periodic tasks don't store results, as you don't have programmatic access to the id of the task.

@periodic_task is deprecated, and is no longer documented, you now define periodic tasks in the schedule.
