### ISSUE TITLE
Task stuck in local memory after cancel_consumer

### ISSUE THREAD

**Issue by averwind** [celery/celery#2564]
I am trying to enforce load balancing on our chains by first checking how many chains of that kind are running at the time. If there are more than N in progress we tell all the workers to stop listening to the queue for this type of chain via cancel_consumer and then retry the task with countdown=0. Once a chain of that kind finishes it simply notifies all workers to start listening the queue again via add_consumer.

The behavior that I am seeing is that once in a while a task would get stuck in the local memory of a worker. I saw this behavior even for a task that has never been retried. Even when it starts listening to the queue again the task is still not processed. Unless I kill the worker the task is not sent back to rabbitmq queue. 

My theory is that right when a cancel_consumer is done one of the main worker process fetches a chain but then it notices that it no longer listens to that queue and as a result it doesn't pass the task to the prefork process.

Is there anyway for the main process to send this chain back when it finds out that it no longer should accept tasks from that queue?

FYI I am using acks_late=True, RabbitMQ 3.5.0

**Comment by averwind** [comment]
Unable to see the tasks via inspect command, it always shows empty for the workers. But from the Rabbit's management plugin I can see that there are unack messages and restarting the worker(s) with the tasks solves the problem.

So far tried -P solo, -Ofair but neither helped. Prefetch multiplier is set at 1.

**Comment by averwind** [comment]
well instead of Retry using Reject works just fine. Unfortunately this also means I am losing the ability keep track of how many times a task has been rejected.

**Comment by averwind** [comment]
Played around a bit more same is happening for Reject as well. We were able to come up with a simple producer and 1 worker and replicate the issue without any Reject/Retry. You may have to run it a few times to get a message stuck in unack state which can be observed on RabbitMQ management screen.

Also acks_late isn't making any difference. It looks like the somehow the task doesn't even make it to the celery level (reserved, scheduled, ready are all empty) and kombu layer holds onto the message.

PRODUCER:
from celery import Celery
app = Celery('testsk')
app.config_from_object('testconfig')
for i in xrange(2):
  result = app.send_task('testsk_tasks.testlog', args=['Hello', ], exchange='sk_exch', routing_key="sk_queue")
  app.control.cancel_consumer('sk_queue', reply=False)
  app.control.add_consumer('sk_queue', exchange='sk_exch', routing_key='sk_queue', reply=False)



WORKER:
from celery import Celery
from celery.utils.log import get_task_logger
from kombu import Exchange, Queue
import sys

app = Celery('testsk_tasks')
app.config_from_object('testconfig')
app.conf.CELERY_QUEUES = (Queue('sk_queue', Exchange('sk_exch', type='direct'), routing_key='sk_queue'), )

logger = get_task_logger(__name__)

@app.task(bind=True, queue='sk_queue')
def testlog(self, message):
  logger.info('Request = {0}'.format(self.request))
  logger.info('Message = {0}'.format(message))

if __name__ == '__main__':
  options = [
      "worker",
      "--hostname", "testsk_tasks.%h",
      "--loglevel", "info",
  ]
  options.extend( sys.argv[1:])
  print options
  app.worker_main(options)

**Comment by averwind** [comment]
Did a bit more digging and looks like a possible solution is explained below:

"Then, after cancelling the consumer, keep hold of the cancelled consumer 
tag (ctag) and if you see any deliveries appearing with that ctag, just 
nack+requeue them immediately. There should not be more of them than 
your prefetch setting. "

http://rabbitmq.1065348.n5.nabble.com/What-happens-to-messages-delivered-just-before-canceling-consume-td13439.html

**Comment by averwind** [comment]
any suggestions about this one besides keeping the prefetch multiplier at 1 and using only one process and making sure you are not rejecting/requeueing a message before cancel_consumer is completed?

**Comment by thedrow** [comment]
This is probably an issue with Kombu instead of Celery but I'm not 100% sure.
This is a tough one. I'll have to dig through the code.

**Comment by ask** [comment]
Seems this behavior originates all the way back from amqplib:
https://github.com/barryp/py-amqplib/blob/master/amqplib/client_0_8/channel.py#L2058-L2060
