### ISSUE TITLE
gossip and "substantial drift" errror even though UTCOFFSET is correct

### ISSUE THREAD

**Issue by patrickwolf** [celery/celery#2565]
We got 3 branches in 3 timezones here: STR, LAX, PEK. When starting and also periodically afterwards the workers encounter the "a substantial drift was encountered" error. This occurs even though the UTC offset is set correctly in all branches.
When starting the worker with the option "--without-gossip" this error doesn't occur.
Could it be that the code within "gossip" doesn't check for UTC offset?

For example in STR I get:
>[celery.redirected] celery@str_worker ready. (WARNING)
>[celery.events.state] Substantial drift from celery@pek_worker may mean clocks are out of sync.  Current drift is 21600 seconds.  [orig: 2015-04-04 00:27:54.082000 recv: 2015-04-04 06:27:54.175000]
> [celery.events.state] Substantial drift from celery@lax_worker may mean clocks are out of sync.  Current drift is 32401 seconds.  [orig: 2015-04-04 00:27:55.049000 recv: 2015-04-03 15:27:54.959000]

Looking at the drift it shows that its exactly the UTC offset:
21600 seconds = 6 hours / str utcoffset=-2 / pek utoffset=-8 = 6 hours
32401 seconds = 9 hours / str utcoffset=-2 / lax utoffset=7 = 9 hours

The interesting thing is that the UTC offset is set correctly as "events -d" shows

(celery) S:\>celery events -d
-> evdump: starting capture...

> celery@str_worker [2015-04-04 09:35:12.005000] heartbeat: active=0, clock=30275192, 
freq=2.0, loadavg=[0.0, 0.0, 0.0], local_received=1428107712.07, 
pid=4800, processed=0, sw_ident=py-celery, sw_sys=Windows, sw_ver=3.1.17, utcoffset=-2

> celery@lax_worker [2015-04-04 00:35:12.033000] heartbeat: active=2, clock=30275192, 
freq=2.0, loadavg=[0.0, 0.0, 0.0], local_received=1428107712.01, 
pid=3676, processed=6364, sw_ident=py-celery, sw_sys=Windows, sw_ver=3.1.17, utcoffset=7

> celery@pek_worker [2015-04-04 15:35:13.424000] heartbeat: active=0, clock=30275194, 
freq=2.0, loadavg=[0.0, 0.0, 0.0], local_received=1428107713.03, 
pid=2576, processed=0, sw_ident=py-celery, sw_sys=Windows, sw_ver=3.1.17, utcoffset=-8

related: #2482, https://groups.google.com/forum/#!topic/celery-users/LD8chTf1iP0

```
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.2
            billiard:3.3.0.19 redis:2.10.3
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:redis://192.168.210.29:6379/0

BROKER_TRANSPORT_OPTIONS: {    'visibility_timeout': 3600}
CELERY_TASK_SERIALIZER: 'json'
CELERY_ENABLE_UTC: True
CELERY_ACCEPT_CONTENT: ['json', 'yaml']
CELERY_RESULT_SERIALIZER: 'json'
CELERYD_HIJACK_ROOT_LOGGER: False
BROKER_URL: 'redis://192.168.210.29:6379/0'
CELERY_RESULT_BACKEND: 'redis://192.168.210.29:6379/0'
CELERYD_POOL_RESTARTS: True
```

**Comment by thedrow** [comment]
Have you checked if ntpd is set up correctly?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
