### ISSUE TITLE
Backend through current_app doesn't work

### ISSUE THREAD

**Issue by soggychips** [celery/celery#2568]
I have my app declared in a separate script from my tasks, which uses backend='amqp://' when instantiating the Celery instance. 

<b>celery_app.py</b>

    app = Celery('proj',
             broker='amqp://',
             backend='amqp://',
             include=['proj.tasks'])

In my tasks script I import celery.current_app and use the "@current_app.task" decorator string for my task functions.

When I invoke a function, the result's ".backend" property says it's of type celery.backends.base.DisabledBackend. 

<b>tasks,py</b>:

    from celery import current_app
    from celery.contrib.methods import task_method
    class A:
        @current_app.task(filter=task_method)
	    def add(self,x, y):
	        return x + y

python shell:

    >>> a = A()
    >>> s = a.add.delay(5,3)
    >>> s.backend
    <celery.backends.base.DisabledBackend object at 0x2904dd0>

In order to fix this, I have to <b>also</b> import the app from my other script. This seems buggy, as current_app should be grabbing that instance already.

<b>tasks,py</b>:

    from proj.celery_app import app
    from celery.contrib.methods import task_method
    from celery import current_app
    class A:
        @current_app.task(filter=task_method)
	    def add(self,x, y):
	        return x + y

python shell:

    >>> a = A()
    >>> s = add.delay(2,2)
    >>> s.backend
    <celery.backends.amqp.AMQPBackend object at 0x1a81fd0>

**Comment by traut** [comment]
@soggychips how would `current_app` know where to find an instance if you're not importing your `proj.cepery_app` and workers are running in a separate process?

**Comment by soggychips** [comment]
@traut Perhaps I don't understand what `current_app` is, then. If I need to import `proj.celery_app`, then why do I need to also import `current_app`? Seems unintuitive.

**Comment by traut** [comment]
`current_app` is just a pointer (or proxy) to a celery application created in current thread. So if you don't create app yourself and just try to access `current_app`, you will get a default instance that may not allow you to execute your tasks

**Comment by soggychips** [comment]
@traut thanks. I'm pretty sure the above example wouldn't work unless I imported current_app as well as the app from celery_app.py . I'll double check later and update this issue appropriately.

**Comment by ask** [comment]
Using `current_app` is not recommended, it's mostly there for backward compatibility from the time when there were no apps.

You should pass app instances around explicitly, or use `@shared_task`.

For the latter you need to make sure the app is properly created (and thus defined as the current_app), in any program endpoints (webserver, command-line scripts, etc), before importing the modules that depend on it.
