### ISSUE TITLE
Docs could use improvement for splitting tasks.py into multiple files

### ISSUE THREAD

**Issue by jvanasco** [celery/celery#2570]
I needed to split my tasks.py into mutiple files, and ran into an issue.  I kept getting an ImportError

```
ImportError: No module named celery
```

After a lot of digging, I finally realize what the issue was -- the file `tasks/__init__.py` file MUST have an instance of the Celery 'app' in it.

```
app = Celery('tasks')
```

That object got migrated a `tasks/utils.py` file which everything else included, so the app broke.

The fix was easy, simply importing the app into `tasks/__init__.py`:

```
from .utils import app
```

**Comment by malinoff** [comment]
@jvanasco I believe this page describes everything http://celery.readthedocs.org/en/latest/getting-started/next-steps.html#about-the-app-argument
What do you think?

**Comment by jvanasco** [comment]
That's a really weird spot to put and structure that information!

1. Within the Getting Started:

	It's not mentioned at all when the app is first introduced:
		http://celery.readthedocs.org/en/latest/getting-started/first-steps-with-celery.html#application
		
	That introduction links to another "next steps" that sets up the layout
		http://celery.readthedocs.org/en/latest/getting-started/next-steps.html#project-layout

	That layout section describes everything, but the app!

	
2, It's not mentioned at all in the "User Guide"

	It's not in the Worker's Guide:
		http://docs.celeryproject.org/en/master/userguide/workers.html
	
	It's not in the Application Guide: 
		http://docs.celeryproject.org/en/master/userguide/application.html


3. That section is titled "about the --app argument"

	The `--app` arg is used to override the standard behavior. 

	It's defining core functionality in an override section

	It would make a lot more sense if it were titled "About the Celery app (and --app argument override)"
 

Would you be open to a PR that slightly reorganizes some of this and adds some hotlinks?

**Comment by malinoff** [comment]
Sure, any docs improvements are welcome!

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by arjunnambiartc** [comment]
@jvanasco ...i have the similar requirement to split up tasks.py into multiple tasks each corresponding to a view. Can you please share you django project structure so that I have an idea as to how you went about doing that ?

**Comment by shashank-iitj** [comment]
+1 Would love some docs/guides on how to split a monolithic task.py file into smaller files.

**Comment by auvipy** [comment]
any taker for this?

**Comment by gregbrowndev** [comment]
Splitting _tasks.py_ into a package of tasks is quite straight forward. You just need to import the tasks into the _\_\_init\_\_.py_ module.

Example:

```
django_app
| tasks
   | __init__.py
   | filesystem_tasks.py
| admin.py
| url.py
```

where _tasks/filesystem_tasks.py_ contains:

```py
from __future__ import absolute_import, unicode_literals
from celery import shared_task

@shared_task
def add(x, y):
    return x + y
```

and _tasks/\_\_init\_\_.py_ contains:

```py
from .filesystem_tasks import *
```

Credit: https://stackoverflow.com/a/42371345/5221078

I'm finding this approach useful to better organise Canvas workflow tasks.

**Comment by amard33p** [comment]
@gregbrowndev You may also write a task detector function that automatically imports tasks from all python files under `tasks` dir when the celery app is initialised:  
https://stackoverflow.com/a/22208391/2230070
You can even go one step further and only import tasks which are `@shared_task` or `@app.task` decorated.
But IMO both approaches are hackish and should be supported natively in Celery.
