### ISSUE TITLE
Nested group-chain-group structure never succeeds

### ISSUE THREAD

**Issue by traut** [celery/celery#2573]
The structure like 
```
workflow = chain(
    t.task1.s(),
    chord(
        [
            t.task2.s(),
            chain(
                t.task3.s(),
                chord(
                    [t.task4.s(), t.task5.s()],
                    t.task6.s()
                )
            )
        ],
        t.task7.s()
    )
)
```
never succeeds. Task `t.task7` is never called, while other tasks succeed just fine. 

Replacing chords with groups did nothing. When I remove the inner chord, workflow finishes without any problems. Workflow also succeeds if I remove an inner chain.

The exact code that can be used to reproduce this issue as well as log messages are in [this gist](https://gist.github.com/traut/fcf5d76e07dd3ed6e54d)

**Comment by traut** [comment]
I suspect that this issue is related to #2556 because this configuration works just fine:
```
workflow = chain(
    t.task1.s(),
    chord(
        [
            t.task2.s(),
            chain(
                t.task3.s(),
                chord(
                    [t.task4.s(), t.task5.s()],
                    t.task6.s()
                ),
                t.task3.s(),
                t.task4.s()
            )
        ],
        t.task7.s()
    )
)
```
Note 2 added tasks `t.task3` and `t.task4` calls after inner chord. The workflow will not work without them or with only one task there. This configuration still hangs: 

```
workflow = chain(
    t.task1.s(),
    chord(
        [
            t.task2.s(),
            chain(
                t.task3.s(),
                chord(
                    [t.task4.s(), t.task5.s()],
                    t.task6.s()
                ),
                t.task3.s()
            )
        ],
        t.task7.s()
    )
)
```

**Comment by Brandl** [comment]
Just came across the same issue - Confirmed

**Comment by glebkuznetsov** [comment]
Hello. Is there any progress on this? I ran into what might be a related issue today. I have something of the form:

    group1 | group2 | task1 | task2

'task2' doesn't get executed even though everything else succeeds.

Interestingly, if either `group1` or `group2` is composed of a single task, then the full pipeline succeeds. Does that give a clue into what is going on?

**Comment by glebkuznetsov** [comment]
Example of failure:
    
    from celery import Celery
    from celery import chain
    from celery import group

    app = Celery('bug')
    app.config_from_object('debug_celeryconfig')

    @app.task
    def t(v):
        print v
        return v


    if __name__ == '__main__':

        # This works.
        group_1 = group([
            t.si('group_1_task_1'),
            t.si('group_1_task_2'),
        ])
        group_2 = group([
            t.si('group_2_task_1'),
        ])
        addtl_task_1 = t.si('addtl_task_1')
        addtl_task_2 = t.si('addtl_task_2')
        pipeline = group_1 | group_2 | addtl_task_1 | addtl_task_2
        assert pipeline.delay().get() == 'addtl_task_2'

        # This fails.
        group_1 = group([
            t.si('group_1_task_1'),
        ])
        group_2 = group([
            t.si('group_2_task_1'),
            t.si('group_2_task_2'),
        ])
        addtl_task_1 = t.si('addtl_task_1')
        addtl_task_2 = t.si('addtl_task_2')
        pipeline = group_1 | group_2 | addtl_task_1 | addtl_task_2
        assert pipeline.delay().get() == 'addtl_task_2'

        # This also fails.
        group_1 = group([
            t.si('group_1_task_1'),
            t.si('group_1_task_2')
        ])
        group_2 = group([
            t.si('group_2_task_1'),
            t.si('group_2_task_2') # NEW
        ])
        addtl_task_1 = t.si('addtl_task_1')
        addtl_task_2 = t.si('addtl_task_2')
        pipeline = group_1 | group_2 | addtl_task_1 | addtl_task_2
        assert pipeline.delay().get() == 'addtl_task_2'

**Comment by thedrow** [comment]
@glebkuznetsov Can you please submit the failing test cases in a form of a PR?
That will certainly help resolve this issue?

**Comment by merwan** [comment]
@thedrow This issue is blocking for us. I can provide a PR for a failing test case and I can also work on a fix but I need a bit of guidance. Could you please tell me which kind of PR you expect for the failing test? Following code is a failing case with Redis as broker and backend, but it also fails with amqp as broker and backend. It passes when `CELERY_ALWAYS_EAGER = True`
```
from celery import Celery
from celery import group

app = Celery(
    'tasks',
    backend='redis://?new_join=1',
    broker='redis://'
)


@app.task
def t(v):
    print(v)
    return v


if __name__ == '__main__':

    # This doesn't work.
    group_1 = group([
        t.si('group_1_task_1'),
        t.si('group_1_task_2'),
    ])
    group_2 = group([
        t.si('group_2_task_1'),
    ])
    addtl_task_1 = t.si('addtl_task_1')
    pipeline = group_1 | group_2 | addtl_task_1
    result = pipeline.delay().get()
    assert result == 'addtl_task_1'
```

**Comment by averwind** [comment]
trying to chain groups will probably not work as you expect them to. See:

https://github.com/celery/celery/issues/1671#issuecomment-39901321

**Comment by actionless** [comment]
is anyone working on fixing it?

here is my example,
it's hanging when trying to do `result.get()` (ie `result.join_native()`) on waiting for results of inner group (`KeyValueStorage.get_many`) but works when doing  `result.join()`
```
job = group(
    group(
        add.s(16, 16),
        add.s(32, 32)
    ),
    (
        add.s(2, 2)
        |
        add.s(4)
    )
)
result = job.apply_async()
```

here is more complicated example, it hangs everytime, but on different routine (`BaseBackend.wait_for`)
```
job = group(
   (
        group(
            add.s(16, 16),
            add.s(32, 32)
        )
        |
        add.s(4)
    ),
    (
        add.s(2, 2)
        |
        add.s(4)
    )
)
result = job.apply_async()
```

**Comment by actionless** [comment]
@merwan how did you resolved your blocker? did you found some workaround? or some other similar library?

**Comment by thedrow** [comment]
I'd be happy to guide people regarding to how we're going to fix it.
@actionless Can you demonstrate how this fixes the issues?

**Comment by actionless** [comment]
@thedrow to reproduce the problem and workaround you can use the last example i provided (group(chord, chain))

but it seems to be another unrelated to redis issue with "parsing" complicated task workflows (group-chain-group) -- it can be workarounded by using chord instead of group for nested taskset

**Comment by ask** [comment]
These examples work for me in master.

Please open a new issue if you can reproduce a problem in that version!
