### ISSUE TITLE
celerybeat ignores BROKER_HEARTBEAT

### ISSUE THREAD

**Issue by tommerw** [celery/celery#2574]
setting BROKER_HEARTBEAT has no effect for the celerybeat process

Using celerybeat v3.1.17 with RabbitMQ broker.

To reproduce:

1) celeryconfig.py:

BROKER_URL = 'amqp://admin:admin@localhost:5672//'
BROKER_HEARTBEAT = 5

2) tasks.py:

app = Celery()
app.config_from_object('celeryconfig')

@app.task
def test_task():
    print 'Hello Celery'

3) run the following two commands:

celery -A tasks worker -l debug
celery -A tasks beat -l debug

We can see the heartbeat in the rabbitmq UI.  For the worker process a heartbeat of 5 seconds was set:

![image](https://cloud.githubusercontent.com/assets/6978335/7127692/791caff0-e1fc-11e4-9f6f-b3811bdde248.png)

For the beat process, no heartbeat was set:

![image](https://cloud.githubusercontent.com/assets/6978335/7127701/9f9e0b7e-e1fc-11e4-87c9-1b134d0ad90f.png)

**Comment by ask** [comment]
Clients don't support heartbeats, so this depends on the implementation of that (which is tricky in synchronous environments)

**Comment by tommerw** [comment]
I don't understand the comment about clients not supporting heartbeats.  Kombu supports heartbeats out of the box and, in fact, the celery worker supports heartbeats.  Only the celery beat process does not support it.

A simple solution would be to update celery.app.base.py, line 376 from 

heartbeat=heartbeat

to 

heartbeat=heartbeat or BROKER_HEARTBEAT

We is this not a valid fix?

**Comment by juretta** [comment]
@ask I'm seeing a similar problem where the heartbeat setting is being ignored on connections being used to publish tasks unless https://github.com/juretta/celery/commit/2f74646deb60d2b6bbf8d062b4504c0907aed948 is applied (not using celerybeat).

Should I open a separate issue for this?
