### ISSUE TITLE
Chaining Celery Task Methods Error

### ISSUE THREAD

**Issue by soggychips** [celery/celery#2577]
http://stackoverflow.com/questions/29664703/chaining-celery-task-methods-error

I'm trying to chain together two task_methods using celery, but I get the following error. Note, I don't get this error when chaining **regular** celery tasks together, **only task_methods** (class functions). I can't tell if the `self` object isn't being passed or if the result from the first task isn't being passed.

Here is my project layout:

    proj/__init__.py
        celery_app.py
        tasks.py

tasks.py:

    from __future__ import absolute_import
    from celery import current_app
    from celery.contrib.methods import task_method
    from proj.celery_app import app

    class A:

        def __init__(self):
            self.something = 'something'

        @current_app.task(filter=task_method)
        def add(self,x, y):
            return x + y

        @current_app.task(filter=task_method)
        def show(self,s):
            print s
            return s

celery_app.py:

    from __future__ import absolute_import
    from celery import Celery

    app = Celery('proj',
             broker='amqp://',
             backend='amqp://',
             include=['proj.tasks'])

    app.conf.update(
        CELERY_TASK_RESULT_EXPIRES=3600,
    )

    if __name__ == '__main__':
        app.start()

error:

    >>> from proj.tasks import A
    >>> a = A()
    >>> s = (a.add.s(1,2) | a.show.s()).delay().get()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.6/site-packages/celery/result.py", line 175, in get
        raise meta['result']
    TypeError: show() takes exactly 2 arguments (1 given)

Here's the error from the celery worker:

    [2015-04-15 19:57:52,338: ERROR/MainProcess] Task proj.tasks.show[e1e5bc12-6d36-46cd-beb7-fd92a0a5f5c2] raised unexpected: TypeError('show() takes exactly 2 arguments (1 given)',)
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
      File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
    TypeError: show() takes exactly 2 arguments (1 given)

Has anyone successfully chained task_methods with celery? Thanks!

**Comment by soggychips** [comment]
I've found a workaround, although a better solution is still desired:

First, revise tasks.py:

    ...
    def show(s,self):
        print s
        return s
    ...


Then you can call `s = (a.add.s(1,1) | a.show.s(a) ).delay().get()`, setting s to 2.

Interestingly enough, calling `s = (a.add.s(1,1) | a.show.s(self=a) ).delay().get()` spits back the following error:

`TypeError: s() got multiple values for keyword argument 'self'`

This is not ideal, since the show function can not be called unless in a chain.

For example, the following issues:

    >>> a.show(s='test')
    TypeError: show() got multiple values for keyword argument 's'

and

    >>> a.show(s='test',self=a)
    TypeError: __call__() got multiple values for keyword argument 'self'

**Comment by ask** [comment]
Task methods will no longer be supported in 3.2.  I think you can consider it a failed expiriment :(

**Comment by alexhayes** [comment]
Removing task methods in 3.2 would be extremely disappointing and I think goes against the [API>RCP precedence rule](http://docs.celeryproject.org/en/latest/internals/guide.html#the-api-rcp-precedence-rule).

I think I have a relatively simple solution to this problem in #2600 which could also resolve this issue. I've still got some issues I'm working through but I hope to have these resolved along with accompanying tests.

**Comment by soggychips** [comment]
> Task methods will no longer be supported in 3.2. I think you can consider it a failed experiment :(

That is a bummer. I'm using task methods for class functions that rely heavily on inheritance. Losing task methods in 3.2 would cause me to rewrite my entire application. I guess I'll be sticking with celery 3.1
