### ISSUE TITLE
Rabbit MQ Message not reading Using Load balancer

### ISSUE THREAD

**Issue by dilipaim11** [celery/celery#2581]
Hi 
I am using RMQ  which is cluster and over LB, 
In the receiving side if i give machine IP in Receive.host for individual server , its work fine .
But if i give LB name in Receive.host on that case - 
its read all the message which available in queue, 
But once the queue is empty and idle for 1 minute after that if any new message which is coming  in to the Queue , my processing service not able to read that message . 
Points - Heart Beat message still coming from processing service 
If i restart the processing service than again it will read all message .

Processing service is .net Window Service . 

Any suggestion will be helpful to. 
Thanks
Dilip

**Comment by malinoff** [comment]
Sorry, but it seems that your question is not related to celery, but rabbitmq directly. Consider asking on rabbitmq mailing list (http://www.rabbitmq.com/contact.html).
