### ISSUE TITLE
Request point release on 3.1 tree for issue #2536 fix

### ISSUE THREAD

**Issue by bierdybard** [celery/celery#2582]
Hello,

The problem reported under issue #2536 prevents projects using Django + Celery from migrating to 1.8 unless they manually patch the issue. Requesting a point release on the 3.1 tree to resolve this launch error with Django 1.8.

**Comment by ask** [comment]
Will work on that tomorrow

**Comment by jcalazan** [comment]
+1 Just ran into this issue as well with Django 1.8.

**Comment by ieatkittens** [comment]
Would be greatly appreciated - also dealing with this!

**Comment by adonisnafeh** [comment]
running into the same issue, looking forward for the release

**Comment by TauPan** [comment]
I've backported the patch from 8a2c3b1 to 3.1.17:

```patch
diff --git a/celery/fixups/django.py b/celery/fixups/django.py
index c1ae62e..e6ab7ed 100644
--- a/celery/fixups/django.py
+++ b/celery/fixups/django.py
@@ -158,7 +158,13 @@ class DjangoWorkerFixup(object):
         except ImportError:
             from django.core.management.base import BaseCommand
             cmd = BaseCommand()
-            cmd.stdout, cmd.stderr = sys.stdout, sys.stderr
+            try:
+                # since django 1.5
+                from django.core.management.base import OutputWrapper
+                cmd.stdout = OutputWrapper(sys.stdout)
+                cmd.stderr = OutputWrapper(sys.stderr)
+            except ImportError:
+                cmd.stdout, cmd.stderr = sys.stdout, sys.stderr
             cmd.check()
         else:
             num_errors = get_validation_errors(s, None)
```

Seems to work here.

Maybe that helps a bit. ;)

**Comment by ask** [comment]
3.1.18 is now on PyPI, please test asap

**Comment by mtchavez** [comment]
Looks like it fixed this issue for me using `celery==3.1.18` :+1:

**Comment by ieatkittens** [comment]
Fixed my issue as well - running perfectly with Django 1.8 so far.

**Comment by ask** [comment]
Thanks for reporting in! Glad to hear it's working (so far)

**Comment by jcalazan** [comment]
Fixed mine as well, thanks! :+1:
