### ISSUE TITLE
WorkerLostError with --autoscale

### ISSUE THREAD

**Issue by TauPan** [celery/celery#2587]
If I use --autoscale in a project spawning a lot of tasks causing high cpu load (100%)  I receive these errors:

```python
[2015-04-21 12:40:42,932: ERROR/MainProcess] Task project.mytask[96757297-5b2e-4bc9-8613-c75f28a8e23c] raised unexpected: WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
```

Parameter given was --autoscale=48,1 on a machine with 4 cores (tasks are not particularly cpu heavy, hence the "overcommit"). As soon as I give --concurrency=48 instead of autoscale, the errors disappear.

I've no good idea how to reproduce this with a minimal project at the moment.

Machine in question is a VM running CentOS 6.6, x86_64, python 3.4 (from IUS). Further modules:

```
anyjson >= 0.3.3
celery==3.1.17
Django==1.8
django-celery==3.1.16
psycopg2 >= 2.6
lxml==3.4.2
python-dateutil==2.4.2
cpe==1.0.5
redis==2.10.3
suds-jurko==0.6
odslib>=1.0.2
mod_wsgi>=4.4.11
django-guardian==1.2.5
```

I'm using django-celery only because of the convenient command line access, result backend is redis 2.8.17, broker is rabbitmq 3.1.5.

If you suspect django-celery might be causing the problem, I can easily test without it.

**Comment by thedrow** [comment]
Are you using -Ofair? It could be related to #2480.

**Comment by TauPan** [comment]
Hope, not using -Ofair.

Omer Katz <notifications@github.com> schrieb am Sa., 20. Juni 2015 10:22:

**Comment by thedrow** [comment]
I need to have a reproducible test case for this in order to resolve this bug.

**Comment by TauPan** [comment]
Sorry, as written above, no idea how exactly to reproduce this, and not
willing to spend the extra time, as autoscaling is not important at all for
me.

You can just close this issue as not reproducible, hopefully others
affected will still find it.

Omer Katz <notifications@github.com> schrieb am Sa., 20. Juni 2015 11:29:
