### ISSUE TITLE
Custom Exchanges are not declared with the channels

### ISSUE THREAD

**Issue by traut** [celery/celery#2588]
It looks like examples of Queue/Exchanges configuration, provided in documentation, do not work. 

This configuration will not work:
```python
custom_exchange = Exchange('custom_exchange', type='topic')
 
class TaskRouter(object):
 
    def route_for_task(self, task, *args, **kwargs):
        print "Routing %s" % task
        return {
            'exchange': custom_exchange,
            'routing_key': str(task)
        }
 
ROUTING_CONFIG = {
    'CELERY_QUEUES': (
        Queue('simple', exchange=custom_exchange, routing_key='simple.#'),
        Queue('complex', exchange=custom_exchange, routing_key='complex.#'),
    ),
    'CELERY_ROUTES': (TaskRouter(),)
}
```
Workers will not receive any tasks. Tasks definitions and other code needed to reproduce the issue are in the gist - https://gist.github.com/afca78902d3da6b2b219

**Comment by traut** [comment]
adding `queue` to the result of `route_for_task` fixes the problem, but I consider it a workaround.

Looking through the code, I suspect it works like that:
* when `queue` value is specified in `TaskRouter.route_for_task` result, it gets added to `declare` property inside [`AMQP.publish_task`](https://github.com/celery/celery/blob/master/celery/app/amqp.py#L445).
* because `declare` is not empty, `Producer` will declare everything from that list, so queue entity will be  declared in [Producer._publish](https://github.com/celery/kombu/blob/master/kombu/messaging.py#L184).
* As a part of `Queue` entity declaration, its callback `when_bound` will be called in parent class' method [`MaybeChannelBond.maybe_bind`](https://github.com/celery/kombu/blob/master/kombu/abstract.py#L76)
* Finally, inside `Queue.when_bound`, an exchange instance associated with that queue will be [binded to the channel](https://github.com/celery/kombu/blob/master/kombu/entity.py#L505).

Proper approach would be to attach all exchanges specified inside `publish_task` method:
```python
if exchange and isinstance(exchange, Exchange):
    exchange.binding().declare(producer.channel)

if queue and isinstance(queue, Queue) and queue.exchange:
    queue.exchange.binding().declare(producer.channel)
```

**Comment by traut** [comment]
another workaround is to bind exchanges manually:
```python
custom_exchange = Exchange('custom', type='topic')
custom_exchange.binding().declare(celeryapp.connection())
```

**Comment by traut** [comment]
also, another workaround is
```python
custom_exchange = Exchange('custom', type='topic')
custom_exchange.binding().declare(celeryapp.connection())
```
That will work even though `.connection()` returns a new connection every time. It works because exchanges are stored in [`Transport.state`](https://github.com/celery/kombu/blob/master/kombu/transport/virtual/__init__.py#L780) _static_ field (that contains instance of `BrokerState`), so every newly created connection will use the same state.

**Comment by ask** [comment]
You use the `queue` argument if you want the queues to be declared.  If you don't want them to declared, or want to declare manually you use the `exchange`+`routing_key` pair.

You can also use:

    task.apply_async(declare=[exchange])

and the `declare` key can also be returned from a router

**Comment by ask** [comment]
That is, `exchange` + `routing_key` provides you with the full flexibility of amqp, for better or worse,
and `queue` will be sufficient for 99% of users.

**Comment by traut** [comment]
@ask Just `echange` and `routing_key` pair does not force celery/kombu to declare the exchange. With `declare` field it works, but I still looks nasty.

In the end my router should return `declare`, `exchange` and `routing_key`:
```python
class TaskRouter(object):

    def route_for_task(self, task, *args, **kwargs):
        print "Routing %s" % task
        return {
            'declare': [custom_exchange],
            'exchange': custom_exchange,
            'routing_key': str(task)
        }
```
In theory, `route_for_task` method can be executed thousands of times, so returning `declare` every time seems excessive to me. Setting `queue` in a task is not always an option, especially if custom router is used (task may not know where it is going to be executed)

Unfortunately `declare` field is [not mentioned](http://celery.readthedocs.org/en/latest/search.html?q=declare&check_keywords=yes&area=default) in documentation except implicitly in API doc strings.

So the fix for that issue can be at least updated documentation.
