### ISSUE TITLE
tasks are not started till some event

### ISSUE THREAD

**Issue by oxpa** [celery/celery#2590]
Hello.

I couldn't find any help aside from here, sorry.
I'm having an issue, when I have 10 workers with concurrency of 1 and only 2 running tasks.

I'm using celery with redis backend. Versions are:
>billiard (3.3.0.19)
celery (3.1.17)
redis (2.10.3)

I'm launching my workers like:
```python -m celery multi start 10 -c 1 -A Worker.worker --pidfile=/var/run/worker%n.pid --logfile=/var/log/worker.log --loglevel="DEBUG"```

First of all, it starts 20 processes, two for each worker. Is it a normal situation?

I'm submitting tasks from a flask application like:
```result = chain(tasks, app=app.celery).delay()```
where tasks is an array of consequential tasks I need to perform.
I'm sure tasks are waiting "somewhere in the celery": usually, I can see several tasks from a chain performed. And if there is a long running task, others will wait for it to end. I can't find any reason or similar feature of these hangs. 

I'm sure I have 4 tasks to perform, 10 workers and only two tasks running. Where should I look at in this case?  What information can I provide for you to help me debugging?

**Comment by malinoff** [comment]
> First of all, it starts 20 processes, two for each worker. Is it a normal situation?
Yes. The first process in the parent (or controller) process which launches the pool of child processes - in your case (-c 1) the size of the pool is 1.

**Comment by oxpa** [comment]
As a note:
I tried using ```--autoscale``` and various concurrency settings like ```-c 10```, but the behaviour (when there are idle workers and not started tasks) persists

**Comment by ask** [comment]
You should use the inspect command to investigate this:

    celery -A proj inspect active
    celery -A proj inspect reserved
    celery -A proj inspect scheduled

**Comment by oxpa** [comment]
```bash
celery -A proj inspect active
celery -A proj inspect reserved
```
Showed that a worker had an active and a reserved task. Then, careful reading through output of:
```
celery -A proj inspect conf
```
Revealed "CELERYD_PREFETCH_MULTIPLIER" which was 4. With it set to 1 everything works well. Thank you for helping!
