### ISSUE TITLE
Docs need to update release date for 3.1.18

### ISSUE THREAD

**Issue by frewsxcv** [celery/celery#2593]
http://docs.celeryproject.org/en/latest/changelog.html#version-3-1-18

> release-date:	TBD

**Comment by rlr** [comment]
Also, it isn't tagged in git yet.

**Comment by thedrow** [comment]
@rlr Can you open a new issue about it to ensure it's more visible?

**Comment by ask** [comment]
Thanks! Probably Read the Docs had problems building the documentation as the release date was set before the release.  The version is tagged in git now.

**Comment by thedrow** [comment]
@ask Then this issue should be closed no?
