### ISSUE TITLE
celery.beat._Threaded does not set `app` correctly

### ISSUE THREAD

**Issue by jackyfkc** [celery/celery#2594]
The code is in ~~celery/bin/celery.py~~ celery/beat.py, Line 535

    class _Threaded(Thread):
        """Embedded task scheduler using threading."""

        def __init__(self, *args, **kwargs):
            super(_Threaded, self).__init__()
            self.service = Service(*args, **kwargs)
            self.daemon = True
            self.name = 'Beat'

        def run(self):
            self.service.start()

        def stop(self):
            self.service.stop(wait=True)

we need to set **app** instance correctly, or we will use the default `app` instance in the newly created thread

Here is my solution

    class _Threaded(Thread):
        """Embedded task scheduler using threading."""
    
        def __init__(self, *args, **kwargs):
            super(_Threaded, self).__init__()
            self.service = Service(*args, **kwargs)
            self.daemon = True
            self.name = 'Beat'
            self._app = kwargs['app']
    
        def run(self):
            self._app.set_current()  # Caution: It is important to set app as current
            self.service.start()
    
        def stop(self):
            self.service.stop(wait=True)

**Comment by malinoff** [comment]
Hello, @jackyfkc 
First of all, this code is in [celery.beat](https://github.com/celery/celery/blob/master/celery/beat.py#L535), not in `celery.bin.celery`.

Why is it important to set app as current there? Do you have any specific error?

**Comment by jackyfkc** [comment]
I have attempted to run beat as embed service (as a thread); and also set **CELERY_TIMEZONE = 'Asia/shanghai'** in celeryconfig.py file. 

After start the beat service, I have found that the created beat thread use the default celery configuration where CELERY_TIMEZONE is set to UTC.
