### ISSUE TITLE
ProducerPool or ConnectionPool reset?

### ISSUE THREAD

**Issue by variable** [celery/celery#2595]
I am investigating why our celery instance sometimes not putting all the tasks messages onto RabbitMQ, eg, 99 instead of 100

So I dove into the code and eventually stumble on to celery/app/amqp.py, I was debugging by adding extra publish method to an non-existing exchange, see below:

        log.warning(111111111)
        self.publish(
            body,
            exchange=exchange, routing_key=routing_key,
            serializer=serializer or self.serializer,
            compression=compression or self.compression,
            headers=headers,
            retry=retry, retry_policy=_rp,
            reply_to=reply_to,
            correlation_id=task_id,
            delivery_mode=delivery_mode, declare=declare,
            **kwargs
        )
        log.warning(222222222)

        self.publish(
            body,
            exchange='celery2', routing_key='celery1',
            serializer=serializer or self.serializer,
            compression=compression or self.compression,
            headers=headers,
            retry=retry, retry_policy=_rp,
            reply_to=reply_to,
            correlation_id=task_id,
            delivery_mode=delivery_mode, declare=declare,
            **kwargs
        )
        log.warning(333333333)

Then tried to trigger 100 tasks from project code, and then result was only 1 message got put into the celery queue, the log messages were successful, which means no exceptions were raised.

I think it's caused by ProducerPool or ConnectionPool that have broken instances with non-existing exchange. Could anyone please provide some insight?

**Comment by ask** [comment]
Sending a message in AMQP is asynchronous for some crazy reason, so you will not receive the 'exchange not found' error until you perform some synchronous operation later (like queue_declare, or similar).

I haven't seen any synchronous amqp clients handling this case, but we could solve it by
polling the fd using select/poll after the publish operation is done.   It will not be pretty, but could work until the async rewrite is finished.

Note that usually people will use automatic routing in Celery, where this is much less likely to happen.

**Comment by ask** [comment]
Oops. ,you would have to poll the fd __before__ calling publish, since obviously the error may happen much later

**Comment by ask** [comment]
Try this! Note that  you have to use pyamqp://

**Comment by variable** [comment]
After setting BROKER_POOL_LIMIT to None seems have fixed the problem. But yes, it's not an ideal solution.

**Comment by variable** [comment]
The original purpose to debug this was we are having intermittent messages not being pushed to the celery queue. I guess it was caused by network issue which resulted something not found (eg. exchange).

**Comment by ask** [comment]
The only real solution to this as long as AMQP publish is asynchronous is to use publisher confirms: `BROKER_TRANSPORT_OPTIONS={'confirm_publish': True}`

It does impact performance though.
