### ISSUE TITLE
More documentation on broker internals needed

### ISSUE THREAD

**Issue by alvinchow86** [celery/celery#2601]
It would be really, really useful to provide some documentation about implementation details for the common brokers that Celery supports, such as Redis and RabbitMQ. 

For instance in RabbitMQ, I see that there's a queue made for each Celery queue, but there are all these `celery@<HOSTNAME>.pidbox` queues and `celeryev....` queues, and it's not clear what they do. Knowing this is essential for debugging issues with the broker server. 

Similar issue with Redis.

**Comment by patseng** [comment]
+1

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
