### ISSUE TITLE
invalid eta value '2015-12-05': int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by sttwister** [celery/celery#2605]
celery==3.1.10
kombu==3.0.24

If I pass an ETA to task with the value of datetime.datetime(2015, 12, 4, 22, 0, tzinfo=<UTC>), the worker throws the following error:

> Received invalid task message: invalid eta value '2015-12-05': int() argument must be a string or a number, not 'NoneType'
> The message has been ignored and discarded.
>
> Please ensure your message conforms to the task
message protocol as described here: http://bit.ly/hYj41y
>
> The full contents of the message body was:
> {'utc': True, 'chord': None, 'args': (<Agency: goldenkey>, 4398), 'retries': 0, 'expires': None, 'task': 'activities.tasks.send_activity_reminder', 'callbacks': None, 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': '2015-12-05', 'id': '123bb2d4-b1a5-4193-a51d-eb5d5bf7d117'} (3739b)

The local timezone is UTC+2, so the task should be executed exactly at midnight.

What's going on?

Thanks!

**Comment by ask** [comment]
> On May 4, 2015, at 10:51 AM, Felix Kerekes <notifications@github.com> wrote:
> 
> datetime.datetime(2015, 12, 4, 22, 0, tzinfo=

This date is `2015-12-04T22:00:00` in ISO-8601 format, not `2015-12-05`



-- 
Ask Solem
twitter.com/asksol | +44 07454281208

**Comment by sttwister** [comment]
Yes that's right, and that's probably the source of this problem.

But this is how the `eta` parameter gets sent in the message body (although it's being passed a datetime which is exactly the one I wrote in the description).

So then the problem must somewhere in the messaging / broker part ?

**Comment by ask** [comment]
Not in the worker at least, and my Python version returns the correct value for `atetime.datetime(2015, 12, 4, 22, 0, tzinfo=None).isoformat()`

**Comment by thedrow** [comment]
Can you please provide a test case where this fails for you?

**Comment by sttwister** [comment]
In the end, it seems it was a rarely occuring problem in my code. I was passing a `date` instead of a `datetime` to the `eta` parameter.

Still, the message was sent to the broker without problem, and the error only occurred when the worker received the task.

Perhaps `date` eta values shouldn't be allowed to be passed on to the broker. I can supply a pull request if this sounds like a fine solution.

**Comment by ask** [comment]
Thanks!  I guess it won't hurt to support dates without time information ;)

Fixed by b225f93  (had wrong issue number in commit, aaargh)
