### ISSUE TITLE
Django celery 100% cpu consumption

### ISSUE THREAD

**Issue by rahul16101989** [celery/celery#2608]
Hello . i have created two task that push database hardly means update , add 53000 record in a minute using celery periodic task. 

Configuration : 

celery = Celery('hello', backend='amqp', broker='django://') 
celery.conf.update(
    CELERY_TASK_SERIALIZER='json',
    CELERY_ACCEPT_CONTENT=['json', 'pickle'],  # Ignore other content
    CELERY_RESULT_SERIALIZER='json',
    CELERY_TIMEZONE='Europe/Madrid', #London
    CELERY_ENABLE_UTC=True,
    CELERYD_MAX_TASKS_PER_CHILD = 1,
    CELERY_TASK_RESULT_EXPIRES = 1800,
    CELERY_IGNORE_RESULT = True,
    CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend',
)

But when ever task goes to complete it consume 100% cpu .
Please help me out from this issue. also i  am using all updated software of  django-celery celery pytz billiard kombu anyjson amqp

Checked with amqp and kombu.

**Comment by joostdevries** [comment]
@rahul16101989 
- Does this happen for other tasks (or is there just one task)?
- Does the task complete or does it go to 100% before completion?
- Could you share the code for the task?

**Comment by rahul16101989** [comment]
Does this happen for other tasks (or is there just one task)?  
Feedback : all tasks. (there is two tasks )
Does the task complete or does it go to 100% before completion?
Feedback : after completion of task it goes 100% at a time when pulling next task.
Could you share the code for the task?
Feedback : i will send it.
  thanks for reply.

**Comment by rahul16101989** [comment]
HI i have observed lot and find its issue with my task that update lots 50000 data in 2 minute that make cpu high. Any suggestion related hardware that we need to use (yes i know that is not a part of celery but if you can then please). 
Thanks.

**Comment by malinoff** [comment]
@rahul16101989 you should profile and do performance testing to identify resources you need. Celery is a framework, its performance highly depends on your custom code.
