### ISSUE TITLE
SQL too many connections for group task. Celery 3.1.17, kombu 3.0.24

### ISSUE THREAD

**Issue by professorDante** [celery/celery#2611]
Running a grouped task, which processes 8000 items and updates certain attributes. Split into batches of 100. So about 90 tasks:

```python
stock_chunks = [stock_ids[x:x + 100] for x in xrange(0, len(stock_ids), 100)]
        group(celery_get_update_stock_chunk_snap_quotes.s(stock_chunk) for stock_chunk in stock_chunks)()
```

I use Djangos in_bulk to access the DB to get the stocks in the atomic task:

```python
stock_chunks_bulk_lists = Stock.objects.in_bulk(stock_chunk_ids)
```

To my understanding, this should only create 1 DB connection per task. I have SQL connections set to 150, but I am hitting the 'too many connections' issue with this grouping. Interestingly it only occurs when the SQL cache connections is empty. The issue goes away after a while, as the task is run every 15 mins.

Autoscaling used with two workers in supervisor:

```ini
[program:worker1]
command={{ PYTHON }} {{ PROJECT_DIR }}/manage.py celery worker -l info --autoscale=3,1 -n worker1.%%h
numprocs=1
stdout_logfile={{ PROJECT_DIR }}/worker1.log
stderr_logfile={{ PROJECT_DIR }}/worker1.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=998

[program:worker2]
command={{ PYTHON }} {{ PROJECT_DIR }}/manage.py celery worker -l info --autoscale=3,1 -n worker2.%%h
numprocs=1
stdout_logfile={{ PROJECT_DIR }}/worker2.log
stderr_logfile={{ PROJECT_DIR }}/worker2.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=998
```

Are the connections not being disconnected in Celery? I don't know how celery will make an SQL connection for grouped tasks.

**Comment by thedrow** [comment]
The connections should be closed after the task is finished.
Can you please provide a failing test case that reproduces this problem?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
