### ISSUE TITLE
Access to AMQP user_id?

### ISSUE THREAD

**Issue by wmertens** [celery/celery#2612]
it would be nice from an authentication standpoint to have access in the task to the user_id field that AMQP has.

Is that possible without changing Celery? If not, is that something that would be accepted as a PR?

**Comment by thedrow** [comment]
Yes that's something that would be accepted as a PR.

**Comment by wmertens** [comment]
Ok, unfortunately I'm not working on the project that needed this for now,
although I might be in the coming months.

You can close this (or leave it open as sometthing to implement) and if I
get around to implementing it I'll send a PR.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
