### ISSUE TITLE
force_execv interferes with DjangoWorkerFixup 

### ISSUE THREAD

**Issue by kevinchevalier** [celery/celery#2613]
When starting workers, if force_execv is set, then worker_init is never called in the new process.  This means that DjangoWorkerFixup is never installed in the new process. 

Because of this, DjangoWorkerFixup cannot close the DB connection before and after each task.  This means that a worker process uses the same DB Connection forever, even if it times out.  This has caused errors where one task failing can make other tasks fail to reach the DB.

**Comment by kevinchevalier** [comment]
Using Django, and setting CELERYD_FORCE_EXECV = True and running this task will show the bug.

    @app.task
    def debug_task():
        from django.db import connection
        cur = connection.cursor()
        cur.execute('SELECT CONNECTION_ID()')
        print "DB Connection ID %s" % cur.fetchone()[0]

The connection ID should be different each time, because the DjangoWorkerFixup should close on the task_prerun signal, but it is not.

**Comment by kevinchevalier** [comment]
I am using 

OSX 10.9.5
Python 2.7.5
Celery 3.1.18
Django 1.8.1

Django settings.py relevant: 

    BROKER_URL = 'redis://localhost'
    CELERYD_CONCURRENCY=1
    CELERYD_FORCE_EXECV = True

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Please don't use FORCE_EXECV on POSIX platforms.
