### ISSUE TITLE
force_execv causes fixups to run twice on workers.

### ISSUE THREAD

**Issue by kevinchevalier** [celery/celery#2614]
If force_execv is set, then fixups are run twice on worker subprocesses.

They are run once when the App is read from the parent process and unpickled.   https://github.com/celery/celery/blob/master/celery/app/base.py#L189

It is then run again when the worker process is _bootstrapped.  The App is created from the config, and the fixup is run again.  Normally this is during an import of a file that defines the app, like celery_setup.py.

If the fixup attaches to signals, like DjangoFixup, then two listeners are attached to the signal, from the same fixup.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Please don't use FORCE_EXECV on POSIX  platforms.
