### ISSUE TITLE
worker exits with exitcode 70 on SIGUSR2 interfering with CELERY_RDBSIG=1

### ISSUE THREAD

**Issue by bcavagnolo** [celery/celery#2615]
I'm using the latest releases of billiard (3.3.0.20) and celery (3.1.18) and wish to use the CELERY_RDBSIG=1 feature to debug worker processes. But when I send SIGUSR2, I get this in the output:

```
[2015-05-12 18:41:36,846: ERROR/MainProcess] Process 'Worker-1' pid:9003 exited with 'exitcode 70'
```

I dug into the billiard source and found that billiard.pool:Worker.after_fork is calling billiard.common.reset_signals which installs billiard.common._shutdown_cleanup as a signal handler for SIGUSR2. (It seems that SIGUSR2 is among billiard's own list of "TERMSIGS," which seems a bit odd. Why should SIGUSR2 indicate termination?)

reset_signals is called _after_ the process initializer, so adding platform.signals in the worker_process_init event as described [for an older version of celery](http://stackoverflow.com/questions/8138642/notify-celery-task-of-worker-shutdown) does not work either.

Anyway, I can work around this by monkey patching billiard in my application code, but it seems like there should be a better way.

**Comment by thedrow** [comment]
I think that this issue should go to billiard instead.
Also, since you have a valid fix care to provide a pull request?

**Comment by thedrow** [comment]
How did you resolve this?
Can you at least provide a code example?

**Comment by adongy** [comment]
I have encountered the same issue with
```
billiard==3.3.0.23
celery==3.1.23
```

I use django so I run celery with `python manage.py celery ...`.
I solved this issue by monkey-patching in my Django settings `billiard.common.TERMSIGS_DEFAULT`

The relevant code looks like
```
# Recent versions of billiard have TERMSIGS_DEFAULT as a set() while 3.3.0.23 uses a tuple()
import billiard.common
TERMSIGS_CUSTOM = list(billiard.common.TERMSIGS_DEFAULT)
TERMSIGS_CUSTOM.remove('SIGUSR2')
billiard.common.TERMSIGS_DEFAULT = type(billiard.common.TERMSIGS_DEFAULT)(TERMSIGS_CUSTOM)
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by tadas-subonis** [comment]
Same issue here with 3.1.25 (can move to 4.0 because it doesn't support windows).

**Comment by madprogrammer** [comment]
Issue still present in billiard==3.5.0.2, celery=4.0.2

**Comment by thedrow** [comment]
We're happy to accept PRs to billiard that will resolve this issue.

**Comment by 0x2b3bfa0** [comment]
I ended up adding the following to my Django [settings file](https://docs.djangoproject.com/en/5.0/topics/settings):

```python
from billiard.common import TERMSIGS_DEFAULT

TERMSIGS_DEFAULT -= {"SIGUSR2"}
```

* https://github.com/celery/celery/issues/2615#issuecomment-207085293
