### ISSUE TITLE
No control over connection pool hard limit

### ISSUE THREAD

**Issue by yuvadm** [celery/celery#2616]
I'm running a very simple celery scenario with one recurring task and the following config:

```python
app = Celery('foo')

pool = redis.ConnectionPool.from_url(REDIS_URL, max_connections=3)
redis = redis.Redis(connection_pool=pool)  # the task also uses redis for applicative uses

app.conf.update(
    BROKER_URL=REDIS_URL,
    BROKER_POOL_LIMIT=5,
    BROKER_TRANSPORT_OPTIONS = {
        'max_connections': 5,
    },
    CELERYD_CONCURRENCY=1,
    CELERY_REDIS_MAX_CONNECTIONS=5,
    CELERY_TASK_SERIALIZER='json',
    CELERY_ACCEPT_CONTENT=['json'],
    CELERY_TIMEZONE = 'UTC',
    CELERYBEAT_SCHEDULE = {
        'my-task': {
            'task': 'foo.tasks.mytask',
            'schedule': timedelta(minutes=1)
        },
    }
)
```

No matter which configuration I use, I see constant usage of 9 redis connections coming from celery (in addition to my application which seems to use 1 more connection), which is very problematic for me as I have a hard limit on 10 connections (a common limit on free hosted redis plans.)

The only place the magic number 9 comes from seems to be the task list:
```
[tasks]
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . foo.tasks.mytask
```

Am I configuring this wrong? Or is this a bug? What's the best practices for limiting celery broker connections to a hard limit of `N`?

**Comment by PMickael** [comment]
Hi, maybe it's because of pidbox connection + hearbeat, try with this option  --without-heartbeat --without-gossip
I don't think you can stop pidbox

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
