### ISSUE TITLE
Using non-prefork pooling causes AttributeError

### ISSUE THREAD

**Issue by dylanlingelbach** [celery/celery#2619]
After a recent deploy we started seeing the following stack trace when trying to consume and process a message:

```
[2015-05-13 16:46:54,581: CRITICAL/MainProcess] Task core.tasks.incoming.incoming[dc3093c2-41f9-47a0-853e-90b17a696c6e] INTERNAL ERROR: AttributeError("'group' object has no attribute 'tasks'",)
Traceback (most recent call last):
  File "/srv/core_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 284, in trace_task
    signature(callbacks[0], app=app).delay(retval)
  File "/srv/core_env/local/lib/python2.7/site-packages/celery/canvas.py", line 175, in delay
    return self.apply_async(partial_args, partial_kwargs)
  File "/srv/core_env/local/lib/python2.7/site-packages/celery/canvas.py", line 501, in apply_async
    tasks = _maybe_clone(self.tasks, app=self._app)
AttributeError: 'group' object has no attribute 'tasks'
```

This error doesn't reproduce if we use prefork concurrency. I'm new to celery so wasn't able to track down the root cause. I also, unfortunately don't have time to try to reproduce a minimal repro.

Here is some additional info:

OS: Ubuntu 14.04.1 LTS
Celery version: 3.1.17 (Cipater)
Python version: 2.7.6

The core.tasks.incoming.incoming task is running as the first item in a chain of two other tasks. We initiate the task chain with the following code:

```
def chain(message, initial_task):
    g = [task2.s(), task3.s()]
    main_chain = initial_task.s() | group(g)
    main_chain.delay(result)
```

Let me know if you need any more information

**Comment by dylanlingelbach** [comment]
One important point I forgot to mention. The biggest change in our `core.tasks.incoming.incoming` task between when this worked and when it didn't was the removal of any I/O ops in the task.

Specifically when it worked we were saving to the DB in that task. Our change was to move that save to the DB to a separate task so `core.tasks.incoming.incoming` no longer does any I/O.

**Comment by dylanlingelbach** [comment]
Updated the title as I also have this issue with solo.

**Comment by thedrow** [comment]
I'm sorry it took so long to get a response.
By non-prefork pooling you mean gevent and eventlet?
Can you please provide me a failing test case I can work with?

**Comment by dylanlingelbach** [comment]
@thedrow - no worries! We initially saw this with eventlet pooling but, if I remember correctly, I saw it with other, non-prefork pooling strategies as well. Sorry for not remembering here, it's been a busy month :smile: 

@gtowne and I were talking about getting you a minimal repro yesterday as we are hitting this again. We will try to get you something soon  Will a minimal repro instead of a test case be ok?

**Comment by thedrow** [comment]
Yes. That would be awesome.

**Comment by dylanlingelbach** [comment]
@thedrow - sorry it took me so long to get back to you. I created a minimal repro for this issue here:
https://github.com/Evzdrop/celery-2619-repro

You should be able to clone that repo, `pip install -r requirements.txt` and then reproduce the error by running the following:

`python manage.py push_tasks` to start pushing tasks to the queue
`celery -A repro -l debug worker -P eventlet`

The current config assumes you have an instance of RabbitMQ and Postgres running locally but that can be overridden.

The general error seems to be that if we are running on `eventlet` concurrency a task can't queue up its results for a group. 

We work around this in production by inserting the "echo" queue which runs with pre-fork concurrency between the task chain and the group of tasks.

Let me know if you need anything else here.

**Comment by thedrow** [comment]
I'm going to take a look over this during the weekend.

**Comment by dylanlingelbach** [comment]
Thanks @thedrow - let me know if you need anything else from me on it

**Comment by ask** [comment]
Hey! I managed to reproduce this using your example repository on celery 3.1.17, but it works non-stop on the latest celery 4 build and no errors to be seen after running for 4 hours.

So since you've been waiting well over a year, already (sorry for that), I guess we will just focus on getting 4.0 out ASAP

**Comment by dylanlingelbach** [comment]
@ask - great, thanks! The workaround I mention above has been working well for us so we aren't blocked. Looking forward to Celery 4!
