### ISSUE TITLE
Make minute & hour required parameters to crontab

### ISSUE THREAD

**Issue by AlexRiina** [celery/celery#2622]
As you can see in the documentation, it is easy to get into a scary situation

`crontab(day_of_week='sunday') 	Execute every minute (!) at Sundays`
http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html

I've seen this come up twice now (once with only `hours=7` and once with `day_of_week='mon'`) and if there is a note in the documentation, it must have come up a number of times before. Fortunately, it seems like an opportunity for an easy interface improvement.

I think a good option is `__init__(self, minute, hour, day_of_week='*', ...)`.

**Comment by PMickael** [comment]
It's not a good solution, for backward compatibility first.
And also it's cron logic, by default it's * and you have to add a limit to * by defining specific value.
