### ISSUE TITLE
multi + logfiles with pathname variable %I

### ISSUE THREAD

**Issue by konradxyz** [celery/celery#2628]
Celery multi seems to create unnecessary empty logfile when using variable pathnames.

Example:
```
ls -l /tmp/celery
celery multi start c --logfile=/tmp/celery/cel%I.log --autoscale=5,2
ls  /tmp/celery
```
First ls output:
```
total 0
```
Second ls output:
 ```
cel%I.log  cel-1.log  cel-2.log  cel.log
```

I do not know what is the purpose of cel%I.log file.
Is this working as intended?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
