### ISSUE TITLE
Using http for rabbitmq broker

### ISSUE THREAD

**Issue by mmobini** [celery/celery#2630]
Hi

Is there any way to use http as transport protocol of rabbitmq? (as not listed in the doc)
http://kombu.readthedocs.org/en/latest/userguide/connections.html#connection-urls

I ask this because we cant use non-http protocols as our country rate limit such messages. 
I know http is not a messaging protocol but rabbitmq itself supports it.
https://www.rabbitmq.com/protocols.html

**Comment by thedrow** [comment]
Unfortunately that is not possible.
If you have the time, you can contribute a transport to Kombu.
