### ISSUE TITLE
Beat not sending tasks from Schedule

### ISSUE THREAD

**Issue by colinmcintosh** [celery/celery#2636]
I have a custom Scheduler class that creates ScheduleEntry items and calls merge_inplace to setup the schedule. These are scheduled using a crontab() object. I'm passing ~6000 schedule items to merge_inplace and after merge_inplace self.schedule contains all of the items.

When the time comes around that the Tasks should be ran only a small fraction are sent to workers. (~200-400).

I'm using Redis as the backend. 

Any idea what I might be doing wrong or a place someone can point me towards to get started?

**Comment by thedrow** [comment]
Care to share the code?
