### ISSUE TITLE
Celery package should explicitly have pymongo 2.7 dependency

### ISSUE THREAD

**Issue by sona1111** [celery/celery#2640]
When installing the pip package "celery[mongodb]", pymongo3.0.2 is installed by default, but this version of pymongo seems to have significant changes which produce many errors from celery when using. For someone who is new to celery it was rather difficult to find what I was doing wrong. Manually installing pymongo==2.7 with pip has fixed the issue, so I would suggest that for now the pip dependencies should be changed to automatically install this version of pymongo when installing the package "celery[mongodb]".

**Comment by ask** [comment]
Closing this, as we don't have the resources to support MongoDB.
