### ISSUE TITLE
Show current task name/id in process title of the worker

### ISSUE THREAD

**Issue by ThiefMaster** [celery/celery#2642]
At least on linux systems it's rather easy to chance the process title that shows up in `ps`. It would be nicer if Celery showed name and ID of the task a worker currently processes in there.

**Comment by thedrow** [comment]
I don't see any of the maintainers spending time on this right now.
Celery is supposed to be very performant and spending CPU cycles seems unnecessary.
I'm pretty sure you can provide it as an external app if you hook into the [prerun_task](http://celery.readthedocs.org/en/latest/userguide/signals.html#task-prerun) signal.

**Comment by ThiefMaster** [comment]
nope
