### ISSUE TITLE
Add common ancestor for all celery exceptions

### ISSUE THREAD

**Issue by JocelynDelalande** [celery/celery#2643]
It's hard catching a « celery error », because you have to list all celery errors in some var and use `except (e, CELERY_ERROR_LIST)`.

My suggestion is to add two classes : `celery.exceptions.CeleryError` and `celery.exceptions.CeleryWarning`, and to use them for all classes in *celery.exceptions*.

**Comment by ask** [comment]
Hmm, well we also have errors coming from kombu, py-amqp, librabbitmq and so on.  I'm not sure when this is useful, but I guess it doesn't hurt either.

**Comment by JocelynDelalande** [comment]
Thanks :)
