### ISSUE TITLE
Multi start incorrectly  ignores repeated arguments

### ISSUE THREAD

**Issue by llvilanova** [celery/celery#2647]
Hi! I'm using ``app.user_options["worker"].add`` with an option that uses ``action="callback"`` to define an argument that is passed to the worker multiple times, and my code accumulates it into a list. This works if I start each worker manually ("celery worker"), but not if I start them all at the same time ("celery multi start")

The problem is that the option parser for "multi start" is at some point accumulating arguments into an ordered dict, and this ignores all but the last value I pass for that argument.

My objective is to serialize my Flask app configuration and pass it to celry workers. Since I need some variables that are not celery-specific, I cannot use  the form ``celery multi start -- VAR1=VAL1...``.

I think this behaviour deserves being considered as a bug, but in the meantime, is there a somewhat clean work-around to this? Thanks!

**Comment by thedrow** [comment]
Sorry that we were unresponsive.
I'm currently working through our backlock triaging issues.
Can you provide a failing test case or the command that triggers this issue?

**Comment by llvilanova** [comment]
The detailed problem is as follows. I have a user-defined `--config-var` argument that is accumulated into a list (`_config_var` function below), and then used to set the values of the app instance's configuration (`ConfigVars.__init__`). This is a snippet of what I'm using:

````python
from celery.bin import Option
from celery.bootsteps import Step
import logging
import optparse

from .. import celery as app  # custom celery.Celery subclass to work with Flask contexts
from .. import create_app  # creates local Flask app instance and binds celery to it using its config

def _config_var(option, opt, value, parser):
    arg = value.split("=", 1)
    if len(arg) != 2:
        raise optparse.OptionValueError(
            "%r does not have the 'variable=value' format" % value)
    parser.values.config_var.append(tuple(arg))

app.user_options["worker"].add(
    Option("--config-var", default=[],
           action="callback", callback=_config_var, type=str,
           nargs=1, metavar="VARIABLE=VALUE",
           help="set variable value on configuration"),
)

class ConfigVars(Step):
    def __init__(self, worker, config_var, *args, **kwargs):
        from ..config import load
        config = load("production", None, dict(config_var))
        logging.basicConfig(level=config["LOGGING"])
        create_app(config)

        # import modules with tasks
        # ...
````

If I use `celery worker -A ... --config-var VAR1=val1 --config-var VAR2=val2` both `VAR1` and `VAR2` are set accordingly on my app's configuration object. If I instead use `celery multi start -A ... --config-var VAR1=val1 --config-var VAR2=val2`, only `VAR2` is set, since the option parser for `multi start` accumulates the arguments (`config-var`) into a dict, and thus only the last value (`VAR2=val2`) is passed.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
