### ISSUE TITLE
celery worker not working though rabbitmq has queue buildup

### ISSUE THREAD

**Issue by sanjaytalreja** [celery/celery#2653]
I am getting in touch with celery and I wrote a task by following Tutorial:

https://www.digitalocean.com/community/tutorials/how-to-use-celery-with-rabbitmq-to-queue-tasks-on-an-ubuntu-vps
 but somehow worker not getting up and I get following log After entering command:

    celery worker -A tasks -l debug
I get a log:

    Running a worker with superuser privileges when the
    worker accepts messages serialized with pickle is a very bad idea!

    If you really want to continue then you have to set the C_FORCE_ROOT
    environment variable (but please think about this before you do).

    User information: uid=0 euid=0 gid=0 egid=0
And here is my task:

    from celery import Celery
    app = Celery('tasks', backend='amqp',broker='amqp://sanjay:**@localhost:5672//')

    @app.task
    def gen_prime(x):
        multiples = []
        results = []
        for i in xrange(2, x+1):
            if i not in multiples:
                results.append(i)
                for j in xrange(i*i, x+1, i):
                    multiples.append(j)
        return results
Though in rabbitmq admin console I see some queue build up when I try to generate prime numbers in ipython console but i am not getting result back on the console.

Here is my console action:

    >>> from tasks import gen_prime
    >>> pr=gen_prime.delay(10000)
    >>> pr.ready()
    False
    >>> 
    >>> pr.ready()
    False
    >>> pr.ready()
    False
I am trying to solve this one from last 3 days but I was not able to solve it.

**Comment by thedrow** [comment]
What happens if you use a lower number? Say 10.

**Comment by sanjaytalreja** [comment]
@thedrow still it is not responding..

**Comment by wbar** [comment]
I can't reproduce it.

(IPython console): 

    In[1]: from my_project import tasks
    In[2]: result = tasks.gen_prime.delay(100)
    In[3]: result.ready()
    Out[4]: True
    In[5]: result.get()
    Out[5]: 
    [2,
     3,
     5,
     7,
     11,
     13,
     17,
     19,
     23,
     29,
     31,
     37,
     41,
     43,
     47,
     53,
     59,
     61,
     67,
     71,
     73,
     79,
     83,
     89,
     97]

Have you set `ignore_result=True` or `CELERY_IGNORE_RESULT = True` in settings? This will ignore result.

Do you have a `CELERY_BACKEND_RESULT = 'amqp'`  to store results? 

From my perspective, ticket should be closed.

**Comment by thedrow** [comment]
@wbar is correct.
Check the documentation for results backends.
