### ISSUE TITLE
The Couchbase results backend should normalize bytes keys to string 

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2654]
According to #2489 the Couchbase python library raises ValueFormatError when attempting to set a key that using a bytes string.
However #2489 provided the wrong fix for it.
@Smirl suggested to use the str_t method that belogs to the result backend which is the correct fix.

**Comment by Smirl** [comment]
@thedrow You can see my changes in PR #2660 :)

**Comment by Smirl** [comment]
I have noticed that the couchbase tests are skipped on travis because the couchbase python client is not installed. @thedrow is this something that you can add? 

Otherwise we should raise a new issue for this and close this one?

**Comment by thedrow** [comment]
You are right and I have already filed #2517 about it.
Feel free to help.
