### ISSUE TITLE
Celery worker dies without any logging + pid-file is not removed.

### ISSUE THREAD

**Issue by AstrogentA** [celery/celery#2657]
Hello.
Our app based on celery + rabbitmq.
software -> celery:3.0.19 (Chiastic Slide) kombu:2.5.10 py:2.7.5,  billiard:2.7.3.28 py-amqp:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:amqp 
it has 4 workers. 2 workers are started with eventlet option, e.g.:
```
celeryd-multi start  worker1 -l debug --pidfile=$HOME/var/run/celeryd_worker1.pid --logfile=$LOG/celery/celeryd_worker1.log -Q:worker1  worker1   -n:worker1 worker1.$HOSTNAME -P:worker1 eventlet   -c:worker1 1000 -I:worker1 worker1
```
Usually once in a week one of those eventlet workers would just disappear. Our observations:
- process whith PID saved in celeryd_worker1.pid file does not exist
- celeryd_worker1.pid file is not removed
- in rabbitmq logging we see warning "connection_closed_abruptly"
- in celery own logging see that message was delivered ("Got task from broker), but not acknowledged (no logging that 'Task succeeded in X s'.
- CELERYD_ACKS_LATE=false

We did try to add logging @signasl.worker_shutdown, but it did not seem to work even at normal shutdown --> no logging generated.
In the early beginning we enabled core dumps on the system, but no core-files were generated when celery worker crashed, making us suspecting celery to handle an exception and exit without notification.

Recently, we started to measure CPU-usage and observed a CPU-leakage at both eventlet workers, and a memory leak for only one worker. A memory leak was caused by a making png-pictures, which also was CPU-intense.
Now we disabled a step casing the memory leak and running the app fro 3 days. We started to suspect something like 'running out of file descriptors'. At rabbitmq we see it uses 20-30 file descriptors and socket descriptors at the same time (everything runs on the same machine).

All in all, we have regularly crashing workers, but running out of ideas.
Any thoughts on this matter?
Thanks in advance.

**Comment by thedrow** [comment]
I suggest that you'll try [sysdig](http://www.sysdig.org/).
It's the best tool to debug system problems when all else fails.
What you need to do is to export all the stuff that sysdig records.
The command to do so is:
```
sysdig –w myfile.scap
```
You can than find out which system calls occur and which file descriptors go missing and to which processes they belong to.

Have you tried running without using multi workers but with simply using two different processes?
Have you tried replacing eventlet with gevent? Is that possible?

The memory leak can be debugged with valgrid if the png picture generation is done in C or [pympler](https://pythonhosted.org/Pympler/) if it's done in Python.

I unfortunately haven't got much information to work with here.

Would it be possible to create a test case that reproduces this issue?

**Comment by thedrow** [comment]
Any luck reproducing this issue?

**Comment by AstrogentA** [comment]
Guys, thanks a lot for reacting. My apologies for not coming back immediately.
Here is my reaction.
The only way to reproduce the issue is ... wait until it crashes. It is completely unpredictable and we have no test case to demonstrate this.
Sysdig, valgrid and pympler are not present on our system and we are not allowed to install them. Therefore it is so difficult to to trace this issue.
We did not try geventlet because our app is used in production and crashes there. We cant reproduce those crashes on our test system (but we also can't generate a comparable to production load with identical content of tasks).
Running without multi workers was not tried (see args. above).
Current status:
- we disabled the process (within some tasks) which generated png files. Memory leak has gone, however we still can not conclude that celery won't no longer crash. It is being monitored.

We suspect the certain celery process running also out of file descriptors. We started to measure it, but currently we only have data with png-generation disabled and it looks like after all tasks are executed, the number of used file descriptors per PID returns to its original (idle) state.
We plan to enable png-generation back and continue with measuring file descriptors.
To be updated.

**Comment by AstrogentA** [comment]
Just a short update. After disabling .png generation we didn't see crashing workers. However, we had to regularly restart the app. This means that celery was not contentiously running and didn't approach a theoretical moment (after one week) of crash.
To be continued.

**Comment by AstrogentA** [comment]
Yet another update. After disabling .png generation everything works stable. No more crashes. Suspected root cause: running out of file handlers. I'm going to close this issue. Thnaks.
