### ISSUE TITLE
With current_app.Task class in Django: Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)',) [type:u'application/x-python-serialize' encoding:u'binary' headers:{}]

### ISSUE THREAD

**Issue by jhg** [celery/celery#2662]

**Comment by thedrow** [comment]
What's the problem here?
What are you doing?
Pasting the error doesn't really help me debug your problem.

**Comment by thedrow** [comment]
I'm closing this because I can't figure what's the problem exactly.
Feel free to comment with more information and I'll reopen.

**Comment by jhg** [comment]
When use with Django, using current_app this don't have all configuration of app

**Comment by malinoff** [comment]
@jhg try to show a sample of code that generates the error. This will definitely help.

**Comment by jhg** [comment]
In `proj/celery.py`:
```python
from __future__ import absolute_import

import os

from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')

from django.conf import settings

app = Celery('myweb')

app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.task(bind=True)
def debug_task(self):
    print('Request name: {0!r}'.format(self.request))
```

In `other/tasks.py`:
```python
from __future__ import absolute_import

from celery import current_app
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

class MyDebugTask(current_app.Task):
    def run(self, **kwargs):
        print('Request: {0}'.format(self.name))
```

In `proj/apps.py`:
```python
from __future__ import absolute_import
from django.apps import AppConfig

class Proj(AppConfig):
    name = 'proj'
    verbose_name = "Web for test Celery"

    def ready(self):
        from proj.celery import app as celery_app
```

In `proj/__init__.py`:
```python
default_app_config = 'proj.apps.Proj'
```

I run celery worker with:
```
celery -A proj worker -l info
```

And I test to call task from django shell with:
```python
from other.tasks import MyDebugTask
a=MyDebugTask()
a.delay()
```

**Comment by thedrow** [comment]
We'll need to see your Django settings.
Have you configured your task serializer?

**Comment by jhg** [comment]
Yes @thedrow :
```python
# Celery settings

BROKER_URL = 'amqp://guest:guest@localhost//'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```

**Comment by malinoff** [comment]
@jhg you're experiencing this issue because when you do
```python
from other.tasks import MyDebugTask
a=MyDebugTask()
a.delay()
```
you're using default app. You need to import `proj.celery` so your app will be set as 'current'.

**Comment by jhg** [comment]
@malinoff I'm importing proj.celery in app ready, for import this when Django project setup and for can use current_app for write uncouple Django app (as with share_task and share task do all good but I like use class for more powerfull) if I import proj.celery Django app not is uncouple. I don't understand why current_app don't find current app (and how don't find current app use default app).

Celery need a class that work as share_task or that current_app in Django find current app.

**Comment by malinoff** [comment]
@jhg then you should've posted complete code sample how you run your tasks, because from your previous snippet it is obvious that you're using default app instead of yours.

**Comment by jhg** [comment]
@malinoff I test it running manage.py shell that open a Django shell, then this run ready method of Proj, then run `from proj.celery import app as celery_app`, next step is wait that I write commands, then I write:
```
from other.tasks import MyDebugTask
a=MyDebugTask()
a.delay()
```

When I use with mana.py runserver Django setup and then execute `from proj.celery import app as celery_app`, next step is a loop for wait requests, then I in views import MyDebugTask and use:
```
a=MyDebugTask()
a.delay()
```

Django when setup itself run `from proj.celery import app as celery_app` always.

**Comment by thedrow** [comment]
Why aren't you using MyDebugTask.delay() instead?

**Comment by malinoff** [comment]
@jhg I believe that ``other/tasks.py`` is imported before you set your app as current (by importing ``proj/celery.py``), which means that it is using ``default_app.Task`` instead of yours app. You can check it by putting a ``print('Imported!')`` right after ``from celery import current_app`` in ``other/tasks.py``.

**Comment by malinoff** [comment]
@thedrow ``delay`` is instance method, not class method.

**Comment by thedrow** [comment]
@malinoff My bad.

**Comment by jhg** [comment]
@malinoff I will go to try that, please don't close this and today or tomorrow I say here result of test with print. Resolve this I think is interesting for use in uncouple apps Django `current_app.Task` for use class and not only `shared_task`. I will test `print('Imported!)` in `other/tasks.py` and `print('Configured!)` in `proj/apps.py` where import Celery app.

**Comment by JimJty** [comment]
I ran into this issue also. My temp fix was to put:
`from proj.celery import app as celery_app`
in my settings.py file, that way it is decoupled for me.

**Comment by pchomik** [comment]
I had the same issue. 
I made change proposed by @malinoff and problem disappears.

**Comment by jhg** [comment]
I find error with test of @malinoff the problem is that Django app that import celery.py is after of app with tasks in INSTALLED_APPS settings, I move it to before of tasks Django app, in first position, and work good. Is important that Django app that import celery app be the first, before of all Django apps with tasks.

Only an ask, why shared_task work without import celery app before? It's possible create a class that work like a shared_task but as class?

**Comment by rlam3** [comment]
adding 'application/x-python-serialize' to CELERY_ACCEPT_CONTENT seems to work ... not sure if this the right thing to do .

**Comment by thedrow** [comment]
That's the pickle serializer. It's insecure to use it on unsanitized user input.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
