### ISSUE TITLE
Create a new Cassandra results backend based on python-driver

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2669]
[pycassa](https://github.com/pycassa/pycassa) is pretty old and it doesn't support CQL or Cassandra's native protocol.
We need to implement a new results driver based on DataStax's [python-driver](https://github.com/datastax/python-driver).

**Comment by piotrmaslanka** [comment]
I am currently working on it. I will submit a pull request on ready.

**Comment by thedrow** [comment]
Great! Thanks.

**Comment by piotrmaslanka** [comment]
So far my working version is [here](https://github.com/piotrmaslanka/celery/tree/new-cassandra-backend). No tests written yet, will eventually get back to it.

**Comment by thedrow** [comment]
Looks good. The old Cassandra backend should raise a deprecation warning.

**Comment by piotrmaslanka** [comment]
I believe this issue should be closed.

**Comment by thedrow** [comment]
Yes. Thanks.
