### ISSUE TITLE
Cancelling next subtasks in chain

### ISSUE THREAD

**Issue by PhilipGarnero** [celery/celery#2675]
Hello ! First of all, thank you for this project. I saved a lot of time thanks to it.

Let me explain my little problem now:
I want to be able to cancel the next subtasks in a chain.
I can already do so thanks to [this solution](http://stackoverflow.com/questions/17461374/celery-stop-execution-of-a-chain/21106596#21106596) but this method is not documented and not working with eager mode.
I tracked the problem down to [here](https://github.com/celery/celery/blob/master/celery/app/trace.py#L385) for the current working workaround but it seems that eager mode problem is located [there](https://github.com/celery/celery/blob/master/celery/canvas.py#L473).
Stopping a chain doesn't look like it is implemented and is more like a hack people found for the moment.
This is quite an useful feature, could we find a way to implement this in future versions ? Like raising an exception inside substasks or something like that ?

Anyway, thank you for your work =)

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
