### ISSUE TITLE
Ping returns empty despite functioning workers

### ISSUE THREAD

**Issue by embolalia** [celery/celery#2678]
I've been having this problem where after generally some number of days, but occasionally much more quickly, `app.control.ping()` starts returning an empty list despite the workers still being functional. There are no errors in the log; it just stops saying it received it. I'm guessing that's right, and it's not that the worker is broken but that the ping isn't getting sent to it for some reason.

I've been able to reproduce this with the setup below, on Ubuntu and Python 2.7.9. I've tried it on redis versions 2.6.13 and 2.2.12.

Worker command:
```
env/bin/celery worker --config celeryconfig -l DEBUG -E --without-gossip --without-mingle  --logfile celery.log
```
In virtualenv with these packages installed:
```
pymongo==2.8
celery==3.1.17
redis==2.10.3
amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.20
kombu==3.0.26
pytz==2015.4
```
celeryconfig.py:
```py
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

CELERY_IMPORTS = (
    'tasks',
)

BROKER_URL = 'redis://localhost:6379/5'

CELERY_RESULT_BACKEND = 'mongodb://localhost:27017/celery_testing'
CELERY_MONGODB_BACKEND_SETTINGS = {
    "database": "celery_testing",
}

CELERYD_CONCURRENCY = 1
```
tasks.py
```py
from celery import Celery
import celeryconfig

app = Celery(__name__)
app.config_from_object(celeryconfig)

@app.task()
def ping_task():
    return True
```
celery -A tasks report
```
software -> celery:3.1.17 (Cipater) kombu:3.0.26 py:2.7.9
billiard:3.3.0.20 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:mongodb://localhost:27017/celery_testing

CELERY_MONGODB_BACKEND_SETTINGS: {
    'database': '********'}
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_IMPORTS:
    ('tasks',)
BROKER_URL: 'redis://localhost:6379/5'
CELERYD_CONCURRENCY: 1
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: 'mongodb://localhost:27017/celery_testing'
```
Testing like so:
```py
import time
from tasks import app

while True:
    result = app.control.ping()
    failed = 0
    while not result:
        failed += 1
        print 'it broke {}'.format(failed)
        if failed > 60:
            raise Exception('it really broke')
        result = app.control.ping()
    time.sleep(5)
```

This is the last line from the log file; there are no errors.
```
[2015-06-22 16:37:33,842: DEBUG/MainProcess] pidbox received method ping() [reply_to:{u'routing_key': u'920bdd94-da89-35ad-a0c1-fad1337fa129', u'exchange': u'reply.celery.pidbox'} ticket:e9dceb44-b76c-42a3-a566-82b2e507c39c]
```

**Comment by jackyfkc** [comment]
I do not fully understand your test code. It seems that there is a bug in your test code, if the result of app.control.ping() is empty, the inner loop will repeat 61 times and then raise Exception. If so, the entire test app exit?

``` python
 while not result:
        failed += 1
        print 'it broke {}'.format(failed)
        if failed > 60:
            raise Exception('it really broke')
```

**Comment by embolalia** [comment]
Copy paste failure on my part. There's supposed to be a `result = app.control.ping()` in the inner loop, so that, if it fails, it tries 60 more times to get a response, and then exits (so I can see at a glance that it's dead) if it doesn't. I figure failing once might be a hiccup, and not necessarily related; I wanted to be sure that it's the same persistent failure that I see in reality.

**Comment by thedrow** [comment]
You are running without Gossip so that's why the worker does not answer your ping.
Try removing ```--without-gossip```.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
