### ISSUE TITLE
celery add_consumer fails with mongodb backend

### ISSUE THREAD

**Issue by jianbin-wei** [celery/celery#2684]
use following test.py

if we run the worker first as:  celery worker -A test --loglevel info --concurrency=1
and run the producer later as: python test.py
the call to add_consumer will always fail.

If reverse the order, add_consumer will succeed.

It is because the broadcast_cursor within transport/mongodb.py does not handle the empty messages.broadcast collection when it first starts.  When add_consumer is called first, the broadcast_cursor behaves as expected.

```python
from celery import Celery
import time

app = Celery("hello", broker="mongodb://127.0.0.1:27017/task")

@app.task(name="hello")
def hello():
    print "hello world"

if __name__ == "__main__":
    while True:
        hello.apply_async((), queue="test_queue")
        message = app.control.add_consumer("test_queue", reply=True)
        print(message)
        time.sleep(2)
```

**Comment by thedrow** [comment]
I'll take a look later.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support MongoDB.
