### ISSUE TITLE
AMQPNotImplementedError when using Chords

### ISSUE THREAD

**Issue by aphillipo** [celery/celery#2685]
Exceptions from within chords (using the json serializer) have been fixed on master as I understand it.

So I've finally managed to get master installed after many attempts at getting the correct pip commands and order.  Not sure that the dcos are working for me.

But I now have a new issue with Celery master as follows:
```python
    {
        u'utc': True,
        u'chord': {
            u'chord_size': 1, u'task': None, u'args': [],
            u'options': {
                u'reply_to': u'0c1662c5-57a8-3822-8558-4993929fb820',
                u'serializer': u'json',
                u'task_id': u'f0eb21c2-915c-46cc-8b07-2ce0ab5be5bf',
                u'root_id': None
            },
            u'subtask_type': None,
            u'kwargs': {
                u'test_id': 266
            },
            u'immutable': False
        },
        u'args': [],
        u'retries': 0,
        u'expires': None,
        u'task': None,
        u'callbacks': None,
        u'errbacks': None,
        u'timelimit': [None, None],
        u'taskset': u'219b745f-24db-4abf-85a4-f99051a2f46a',
        u'kwargs': {
            u'asset_id': 122,
            u'test_id': 266
        },
        u'eta': None,
        u'id': u'7b7a762a-6b36-49f8-906b-2c5b946c5bc1'
    }
```
Followed by:
```
    Traceback (most recent call last):
    File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/worker/consumer.py", line 476, in on_task_received
        strategy = strategies[type_]
    KeyError: None
```
And then I get:

    Task celery.chord_unlock[6749ccac-b58a-49b6-8a20-9715e5f0e85c] retry: AMQPNotImplementedError(None, 'Unknown AMQP method (60, 72)', None, '')
    Received task: celery.chord_unlock[6749ccac-b58a-49b6-8a20-9715e5f0e85c]  eta:[2015-07-02 16:56:21.198393+00:00] 

Forever?

I'm really struggling to use the advanced features of celery if I'm honest...

**Comment by thedrow** [comment]
That's definitely a bug. Do you have an example test case you can share?

**Comment by aphillipo** [comment]
I'll try to set up a test case now...

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
AMQP result backend should not be used anymore: use rpc for RPC, or a database backend for persistent results.
