### ISSUE TITLE
Debugging Celery Guide

### ISSUE THREAD

**Issue by aphillipo** [celery/celery#2686]
Guys, I have to say it's very difficult to debug celery issues; I'm really not sure if things are being hidden from me somehow because tasks are definitely failing somehow and I think the exceptions from within the subtasks of a chord are not showing up.

Can you give us some advice on the best way to see what's going on in all the parts?  How do the devs debug this stuff if errors are seemingly disappearing?

I love the functionality of celery but I'm really struggling to get access to it.

Ta.

**Comment by thedrow** [comment]
Have you tried running with ```-l DEBUG```?

**Comment by aphillipo** [comment]
I think there are just hidden exceptions within my groups and chord subtasks.  This means that I never get stuff written to the database.  I am running with debug on, yes.  I'll close this because I'll just wrap everything in a try: ... except: and log the errors to a file.
