### ISSUE TITLE
.get() on AsyncResult fails when task is retried

### ISSUE THREAD

**Issue by PhilipGarnero** [celery/celery#2687]
```python
#test.py
from celery import Celery
from time import sleep

app = Celery('tasks', broker='redis://0', backend='redis://1')

@app.task(bind=True, max_retries=None)
def task_b(self, x):
    sleep(5)
    if x == 1:
        raise self.retry()
    else:
        return x
```
```python
>>> import test
>>> test.task_b.delay(1).get()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/result.py", line 171, in get
    no_ack=no_ack,
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 218, in wait_for
    meta = self.get_task_meta(task_id)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 517, in _get_task_meta_for
    return self.decode_result(meta)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 193, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 189, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 172, in exception_to_python
    from_utf8(exc['exc_type']), __name__)(exc['exc_message'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This doesn't seem to be linked to the backend as I tried with redis and mongodb with no difference.

I think I found where this comes from:
When I print meta before this [line](https://github.com/celery/celery/blob/8fc32a58240c74fe9a2d993152f369935ba13722/celery/backends/base.py#L188), it gives me
```python
{'status': 'RETRY',
 'traceback': 'Traceback (most recent call last): blablabla Retry: Retry in 180s\n',
 'result': None,
 'children': [[['508b05a3-9c33-4a85-adb0-a3ec3ee80cd6', None], None]]}
```
And then as `RETRY` is in `self.EXCEPTION_STATES` it will try to transform result to an exception, causing the error as result is None.
What should we do here ? Remove retry from `self.EXCEPTION_STATES` or add a way to handle it in [exception_to_python](https://github.com/celery/celery/blob/8fc32a58240c74fe9a2d993152f369935ba13722/celery/backends/base.py#L168) ?

**Comment by thedrow** [comment]
First of all why are you using master instead of the latest released Celery version?
Does it happen in Celery 3.1.x?
Second, it seems that the task you provided will retry forever. I'm not sure it makes sense as a test case. That's probably why you don't get a result but the correct behaviour would be to block forever or until a timeout occurs if you specified one.

**Comment by PhilipGarnero** [comment]
I had the same issue with the last released version so I tried using master.
This is just an example, my original task would retry indefinitely until an HTTP call succeeds or an error occurs. When the HTTP call succeeds on the first time, the task is not retried and .get() works perfectly fine. However, if the HTTP call returns 'pending', the task is retried and I get this error.
Don't worry about that, lets focus on the issue here. Does removing `RETRY` from `self.EXCEPTION_STATES` is enough to fix the issue without breaking something else ?

**Comment by thedrow** [comment]
I have no idea. We can try and see what happens.

**Comment by PhilipGarnero** [comment]
Removing RETRY from [states.EXCEPTION_STATES](https://github.com/celery/celery/blob/master/celery/states.py#L146) fixed it.
The tests are still passing but I don't know if it will break something untested.
@ask what do you think ?

**Comment by ask** [comment]
Retry is still an "exception state" though, it's just that it can also be None which it doesn't account for.

It will otherwise be kept out of the waiting loop here:
https://github.com/celery/celery/blob/master/celery/backends/base.py#L219-L221
