### ISSUE TITLE
apply_async() hangs indefinitely when RabbitMQ server hits vm_memory_high_watermark and begins flow control

### ISSUE THREAD

**Issue by rudeb0t** [celery/celery#2689]
When RabbitMQ server hits the `vm_memory_high_watermark` setting (defaults at 0.4 or 40% of RAM) it begins throttling publishers as documented here: https://www.rabbitmq.com/memory.html When a task.apply_async() is called against this RabbitMQ server, it will hang indefinitely and if called in an WSGI application it will cause 504 gateway timeout errors if the WSGI application is proxied. The WSGI process **still** runs however and **will continue to run in the background** using up DB connections, RAM and CPU.

**How to reproduce:**
1. Set up RabbitMQ. Set `vm_memory_high_watermark` to 0 in the config file before starting the server or `rabbitmqctl set_vm_memory_high_watermark 0` from the command line.
2. Create a small project with a simple async task. Call `apply_async()`.

The `apply_async()` call will hang. It is not unusual for the first call of `apply_async()` to hang, usually it submits. But then a second call will hang.

**Expected Result:**

`apply_async()` should honor `BROKER_CONNECTION_TIMEOUT` and raise an exception if the broker takes too long to accept and acknowledge the message.

**Comment by thedrow** [comment]
I have seen this behaviour myself. If I remember correctly it's a problem with librabbitmq.
If you use amqp it should respect the timeout.

**Comment by rudeb0t** [comment]
I have both amqp 1.4.6 and librabbitmq 1.6.1 installed. From the manual:

> The transport part is the broker implementation to use, and the default is amqp, which uses librabbitmq by default or falls back to pyamqp if that is not installed.

So if I uninstall librabbitmq, it will use amqp instead and this problem goes away? What do I lose by using amqp instead of librabbitmq?

**Comment by thedrow** [comment]
Performance if you're not running on PyPy.
@ask What was the problem with the timeouts in librabbitmq?

**Comment by malinoff** [comment]
@rudeb0t you can specify `amqp` transport explicitly without removing `librabbitmq` like that:
```
CELERY_BROKER = "amqp://guest:guest@localhost:5672/vhost/"
```

**Comment by rudeb0t** [comment]
@malinoff My `BROKER_URL` is already `'amqp://user:passwd@rabbitmq:5672/queue'` does this mean this is a bug in the `amqp` library as well?

@thedrow We cannot use PyPy because we use some libraries that are are either incompatible with it or have not been tested to have full compatibility.

**Comment by malinoff** [comment]
Okay, so this is definitely should be fixed - currently you can't force `amqp` lib if `librabbitmq` is installed.
I've created https://github.com/celery/kombu/issues/494 for that case.

**Comment by ask** [comment]
You should use `pyamqp://` if you want to avoid using librabbitmq!

**Comment by djsmith42** [comment]
+1

Tonight an AWS availability zone had a network issue that caused packets to be dropped between AZ's. The result was that our Python web workers hung trying to publish Celery tasks to RabbitMQ. We are using `pyamqp://user:password@host`.

**Comment by efarrer** [comment]
+1

**Comment by killermonk** [comment]
+1

**Comment by dankuna** [comment]
+1

**Comment by thinkski** [comment]
+1

**Comment by ask** [comment]
@djsmith42 Are you sure this is not related to the task publish retry policy settings?
http://docs.celeryproject.org/en/latest/configuration.html#celery-task-publish-retry

**Comment by djsmith42** [comment]
@ask I have that configured as:

```
CELERY_TASK_PUBLISH_RETRY_POLICY = {'max_retries': 3}
```

Would that explain this?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by dvaldivia** [comment]
This came back in 4.1 release

**Comment by imaia** [comment]
I believe to have been affected by this issue; using celery 4.0.2

**Comment by auvipy** [comment]
could you verify on master?
