### ISSUE TITLE
worker settings: allow max cummulative tasks time limit

### ISSUE THREAD

**Issue by cezio** [celery/celery#2690]
Hi!

We're running celery tasks that are taking significant amount of time (1-2 hours at least), and because of external conditions, they can leak memory. There is a CELERYD_MAX_TASKS_PER_CHILD setting, which would respawn workers after specific amount of tasks executed. However, in our case, workable value here would be 1. We are running also other tasks, which are executed much quicker (but still takes them few minutes to complete), so that setting in this context doesn't have much sense. 

I suggest adding another worker setting: CELERYD_MAX_TASKS_TIME_PER_CHILD, which would respawn worker when specific work time exceeded.

**Comment by thedrow** [comment]
I recommend running with celery multi and different queues for the longer and shorter running tasks.
That way you'll be able to specify the max tasks per child to the worker who only runs the longer running queues.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
