### ISSUE TITLE
Timestamps from workers in different timezones incorrect despite correct utcoffset

### ISSUE THREAD

**Issue by scobb** [celery/celery#2694]
celery==3.1.18
django==1.7.7
rabbitmq-server 3.5.3-1
python==2.7.8
flower==0.8.0

I have a worker in PDT, server in MDT, another worker in MDT. MDT machines all appear at correct time, PDT appears an hour behind.

Results of `./manage.py celery events -d`:
#worker running on the server
celery@webserver-1.MDT[2015-07-07 18:33:49.766440] heartbeat: clock=2712542, freq=5, local_received=1436294029.77, pid=19825, sw_ident=py-celery, sw_sys=Linux, sw_ver=3.1.18, utcoffset=6
#worker running on a windows machine in PDT
celery@worker.PDT [2015-07-07 17:33:49.657000] heartbeat: clock=2712542, freq=5, local_received=1436294029.77, pid=41100, sw_ident=py-celery, sw_sys=Windows, sw_ver=3.1.18, utcoffset=7
#worker running on a windows machine in MDT, not on server
celery@worker.MDT [2015-07-07 18:33:49.999000] heartbeat: clock=2712542, freq=5, local_received=1436294029.8, pid=6476, sw_ident=py-celery, sw_sys=Windows, sw_ver=3.1.18, utcoffset=6

Thanks in advance for any assistance.

**Comment by thedrow** [comment]
Is ntpd set up correctly?
Have you specified ```CELERY_UTC_ENABLED=True```?

**Comment by scobb** [comment]
I was under the impression `CELERY_ENABLE_UTC` defaulted to True in this version of celery, but I added it explicitly to the settings files, and still no dice. 

I have ntpd running on the server; is there a quick way to determine "correct" setup?

**Comment by thedrow** [comment]
I haven't had much experience with ntpd so I don't know. I see that windows is involved. Does windows support ntpd or something similar?
Oh I now see that you're right. CELERY_ENABLE_UTC is enabled by default.
I'll need more information about your setup.
How are you running celery? What happens if you run celery in a linux machine instead of running it in windows on that time zone?
Does the problem occur with celery beat, worker or just the events?

**Comment by scobb** [comment]
Looks like "windows time service" is the equivalent of ntpd. It's running on the windows workers as well.

We're running celery as a service on windows and supervisor-managed daemon on ubuntu. I'll try to get access to a linux worker in a different timezone, but we don't currently have one set up.

The original impetus behind this was that flower is showing that tasks started immediately by workers appear to have started an hour ago. Not sure if that answers your last question, because I'm not sure if flower uses events.

**Comment by thedrow** [comment]
flower does use events.

**Comment by scobb** [comment]
Okay, it does look like this event is limited to windows machines only. A worker running on ubuntu reports times that are properly adjusted, both in flower and the interactive events display.

**Comment by scobb** [comment]
Following up because I'm still looking for a solution. Is there additional information I can provide?

Thanks!

Steve

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
