### ISSUE TITLE
Confusing behaviour when SoftTimeLimitExceeded is raised from task 

### ISSUE THREAD

**Issue by dansondergaard** [celery/celery#2696]
Hi,

In my Celery task I catch the `SoftTimeLimitExceeded` exception and clean up appropriately. I then re-raise the exception with `raise SoftTimeLimitExceeded()` such that the task.result is the exception. I of course have `from celery.exceptions import SoftTimeLimitExceeded` at the top of my file.

I now want to report to the user that the task timed out, so I wish to check if task.result is an instance of SoftTimeLimitExceeded. Basically, I have this in my Flask app:

    if g.task.state in ('FAILURE', 'REVOKED'):
        app.logger.debug(type(g.task.result))
        app.logger.debug(isinstance(g.task.result, SoftTimeLimitExceeded))
        if isinstance(g.task.result, SoftTimeLimitExceeded):
            app.logger.debug('is instance!')
            flash(('This error occurred since your job exceeded the time limit.'
                   'Technical details can be found below.'), 'danger')
        return render_template('failure.html', task=g.task)

Now weird things happen. The first line that is logged is:

    <class 'celery.backends.base.SoftTimeLimitExceeded'>

The second is:

    False

So it seems that really some other exception is being raised, even though I raise exactly the exception I import. I then looked at `celery.backends.base` and found no reference to the exception in question. I wasn't able to import it with `from celery.backends.base import SoftTimeLimitExceeded`.

What's happening here?

**Comment by thedrow** [comment]
I'm not sure that this is the exception you want to raise. Maybe [abortable tasks](http://celery.readthedocs.org/en/latest/reference/celery.contrib.abortable.html) could help.
I think that this exception is only being used in Celery internally.

**Comment by dansondergaard** [comment]
@thedrow It may be slightly "unorthodox", but I don't see why it shouldn't be possible.

The problem is not really that I want to abort the task, but that I want to detect if the task failed due to a `SoftTimeLimitExceeded` exception being raised so that the user can be informed.

I don't think this is an uncommon thing to want, so maybe there's a better way to do it than to re-raise the exception.
