### ISSUE TITLE
Add AUTOSCALE_KEEPALIVE to celery conf

### ISSUE THREAD

**Issue by PhilipGarnero** [celery/celery#2697]
Right now, this parameter for the Autoscaler class is set to 30 by default unless you specify it as an environment variable. See this [line](https://github.com/celery/celery/blob/a7c168d6df82bcd060e02e647a916d61627959dc/celery/worker/autoscale.py#L36).
I think it could be a plus to add it in celery conf as CELERYD_AUTOSCALE_KEEPALIVE for example

**Comment by thedrow** [comment]
Feel free to issue a pull request :)

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Autoscale will be undocumented in 4.0 to avoid people using it, as we don't have the resources
to fix the issues related to it.
