### ISSUE TITLE
GroupResult.restore is Thread Local

### ISSUE THREAD

**Issue by jennaliu** [celery/celery#2701]
When I tried to restore a previously saved GroupResult like the following in another thread, res.ready() always returns false.
```python
res = celery.GroupResult.restore(result_id)
res.ready()
```
After digging into the code for a bit. I found out that the problem was caused by the unpickle_backend function in [celery/ backends/base.py](https://github.com/celery/celery/blob/master/celery/backends/base.py). When a result is restored, the app parameter is set to be current_app, which in another thread is recreated using the default setting. Therefore it ignores my own CELERY_MONGODB_BACKEND_SETTINGS

The quick way to fixed it is to call celery.set_current() in every new thread before using restore. It should be documented somewhere so that other people would not waste hours finding out why it doesn't work.

**Comment by thedrow** [comment]
The threadpool is an experimental feature.
I'm not sure what celery.set_current() is and where to call it.
@malinoff @ask Care to advise?

**Comment by malinoff** [comment]
@jennaliu all you need to do is to call restore like this: `celery.GroupResult.restore(result_id, backend=celery.backend)`

**Comment by jennaliu** [comment]
@malinoff That doesn't work. unpickle_backend still gets called. Here is the stacktrace
```
  /usr/lib/python3.4/threading.py(888)_bootstrap()
-> self._bootstrap_inner()
  /usr/lib/python3.4/threading.py(920)_bootstrap_inner()
-> self.run()
  /usr/lib/python3.4/threading.py(868)run()
-> self._target(*self._args, **self._kwargs)
  /usr/lib/python3.4/concurrent/futures/thread.py(65)_worker()
-> work_item.run()
  /usr/lib/python3.4/concurrent/futures/thread.py(54)run()
-> result = self.fn(*self.args, **self.kwargs)
  /home/junlanvm/yanstein-api/search_server/rinalogy/v1/handlers/predict.py(20)get_status()
-> res = celery.GroupResult.restore(result_id, celery.backend)
  /usr/local/lib/python3.4/dist-packages/celery/result.py(806)restore()
-> ).restore_group(id)
  /usr/local/lib/python3.4/dist-packages/celery/backends/base.py(319)restore_group()
-> meta = self.get_group_meta(group_id, cache=cache)
  /usr/local/lib/python3.4/dist-packages/celery/backends/base.py(312)get_group_meta()
-> meta = self._restore_group(group_id)
  /usr/local/lib/python3.4/dist-packages/celery/backends/mongodb.py(187)_restore_group()
-> 'result': self.decode(obj['result']),
  /usr/local/lib/python3.4/dist-packages/celery/backends/base.py(198)decode()
-> accept=self.accept)
  /usr/local/lib/python3.4/dist-packages/kombu/serialization.py(184)loads()
-> return decode(data)
  /usr/local/lib/python3.4/dist-packages/kombu/serialization.py(345)unpickle()
-> return pickle_loads(str_to_bytes(s))
  /usr/local/lib/python3.4/dist-packages/kombu/serialization.py(64)pickle_loads()
-> return load(BytesIO(s))
  /usr/local/lib/python3.4/dist-packages/celery/backends/base.py(55)unpickle_backend()
-> return cls(*args, app=current_app._get_current_object(), **kwargs)
> /usr/local/lib/python3.4/dist-packages/celery/backends/mongodb.py(76)__init__()
-> config = self.app.conf.get('CELERY_MONGODB_BACKEND_SETTINGS')
```

**Comment by malinoff** [comment]
Okay, so then setting your app as current in each thread is basically what you should do.
http://stackoverflow.com/a/26530569/1702062 is related.

I think we should definitely document that behavior in http://celery.readthedocs.org/en/latest/userguide/application.html

**Comment by thedrow** [comment]
@malinoff Why do you think this is a documentation issue?

**Comment by malinoff** [comment]
@thedrow because `_state.py` is not documented anywhere. And `current_app` is `threading.Local` instance attribute.
