### ISSUE TITLE
Delay'd task changing data types

### ISSUE THREAD

**Issue by aarcro** [celery/celery#2703]
```python
>>> generator({0: 'test'})
generate: {0: 'test'}
{0: 'test'}
>>> generator.s({0: 'test'})
celery_capillary.tasks.generator({0: 'test'})
>>> generator.s({0: 'test'}).apply().get()
generate: {0: 'test'}
{0: 'test'}
>>> generator.s({0: 'test'}).delay().get()
{'0': 'test'}
```

generator is a simple task that takes one positional argument and returns it. For some reason, running the task through a worker causes the keys in my dictionary to change from int to string. I'm on celery master, with simplejson installed and CELERY_TASK_SERIALIZER=json.

I thought this was a regression from v3.1.17, but it turns out CELERY_TASK_SERIALIZER just changed default from pickle to json.

The more I think about this, I don't know if there's anything to do about it. json serializes dicts to objects I assume, which can only have strings for the field names. :(

So my own solution might just be use Pickle.

**Comment by aarcro** [comment]
CELERY_TASK_SERIALIZER and CELERY_RESULT_SERIALIZER both need to be 'pickle'

**Comment by thedrow** [comment]
You can always try the [JSONPickle](https://github.com/jsonpickle/jsonpickle) package.
No promises there but it might help you represent your objects in JSON better,
You'll have to register the serializer youself using Kombu. See https://kombu.readthedocs.org/en/latest/userguide/serialization.html#creating-extensions-using-setuptools-entry-points
Let me know how it goes. We might release a 3rd party package that uses jsonpickle if it works fine.
