### ISSUE TITLE
Task headers aren't copied on retry

### ISSUE THREAD

**Issue by KimiNewt** [celery/celery#2706]
When retrying a task manually, the original task's headers and delivery info is not copied over (though they can be explicitly passed). I'm not sure if that's the intended behaviour (could not find any documentation about it), but it surprised me as I assumed it would be automatically copied.

```python
self.retry(exc=exc) # Does not pass headers
self.retry(exc=exc, headers=self.request.headers) # Explicitly pass headers
```

**Comment by thedrow** [comment]
@ask What are the headers? What's the default?
I'm not familiar with this one so I'm leaving it to you.
