### ISSUE TITLE
Specifying interval/countdown for a chord which is part of a canvas

### ISSUE THREAD

**Issue by averwind** [celery/celery#2708]
Does anyone have an example on how to make unlock_chord to use a custom interval & countdown when the chord is in a canvas? We currently have a function which builds a canvas and returns it which we execute afterwards. i.e.

chain(add.subtask(args=(3,4)), chord(header,callback))

**Comment by thedrow** [comment]
Can you please explain the usecase?

**Comment by averwind** [comment]
Not everyone needs an aggressive countdown and retry of 1 second. The countdown was made modifiable with:

https://github.com/celery/celery/pull/1155

But I am not sure how to use this change when we are talking about a canvas.

**Comment by stuaxo** [comment]
I am also creating a canvas, consisting of a chord with various tasks inside it.   Is it currently not possible to schedule this to run at a particular time ?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
