### ISSUE TITLE
AsyncResult.get() hangs because GroupResults are built multiple times.

### ISSUE THREAD

**Issue by aarcro** [celery/celery#2710]
In my branch https://github.com/aarcro/celery/tree/trace-print I added some print statements which helped me find what I can only assume is a bug (or two).

```
# Expected result: [[1, 2, 3], [1, 99]]
wf = generator.s(1) | group(concat.s(2) | concat.s(3), concat.s(99))
wf.apply().get()
[[2, 3], [1, 99]]
```

First issue: For some reason, the result of the original task isn't being passed to chain, which is the first item in the group.

```
wf.delay().get()
```
Second issue: This hangs forever, but I think I know why! Take a look at the detailed trace link below, and you can see that the tasks and results get created twice. In the console session `res = wf.delay()` gets back a GroupResult as you would expect since it's the last item in the chain.

BUT When the worker executes the first task `generator.s(1)` the group is re-built spawning new tasks (which get executed) and result objects.

So in the console we have an AsyncResult for the chain `concat.s(2) | concat.s(3)` which will never complete. And the worker has executed a second copy of that chain that the console can never find.

AND the return value from `generator.s(1)` was still not passed a the first positional arg to the chain `concat.s(2) | concat.s(3)`, though it does get passed correctly to `concat.s(99)`

Detailed testing results and task code here: https://gist.github.com/aarcro/51790c3ac95ac1f787f2#file-more_troubles-py-L171

All day in rdb and I found this, but I'm not clear on how to prevent it.

**Comment by aarcro** [comment]
Passing the result as a positional arg turns out not to be related to the main issue here. I opened https://github.com/celery/celery/pull/2712 for that.

**Comment by aarcro** [comment]
Digging into this further, I see that GroupResults have a save and restore method, but they aren't being called. Probably they should be?

**Comment by aarcro** [comment]
At https://github.com/celery/celery/blob/master/celery/canvas.py#L396 Where do the task_id's that are in `[t.options for t in tasks]` go? It seems like they are needed so that executing the group doesn't recreate the tasks.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
