### ISSUE TITLE
Infinite loop in scheduler crontab

### ISSUE THREAD

**Issue by romuald** [celery/celery#2714]
When a *"bogus"* date is used as crontab (eg: *every April, 31st at noon*) , trying to retrieve the  next occurrence of the cron will trigger an infinite loop

Example:

```python
cron = crontab(day_of_month=31, month_of_year=4)
cron.remaining_estimate(datetime.now())
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
