### ISSUE TITLE
celery with mongodb backend error

### ISSUE THREAD

**Issue by hongbinbao** [celery/celery#2721]
After I upgraded to the latest version of mongodb (as broker) from 2.x to 3.0.1
my celery task launch failed:
"celery worker --beat --app=my.celerytask.task1:worker -G task1.cfg"

and I am getting the following error:
**[2015-07-13 11:16:10,029: ERROR/Beat] beat: Connection error: command SON([('create', u'messages.broadcast'), ('capped', True), ('size', 100000.0)]) failed: collection already exists. Trying again in 32.0 seconds...

[2015-07-13 11:16:42,190: ERROR/MainProcess] consumer: Cannot connect to mongodb://x.x.x.x:27017 mytask-db: command SON([('create', u'messages.broadcast'), ('capped', True), ('size', 100000.0)]) failed: collection already exists.*

Still failed. even I drop the collection of "messages.broadcast"  in mongodb. 
thanks.

**Comment by gotpredictions** [comment]
I am running into the same issue.  Is there a known solution or workaround for this?

**Comment by hongbinbao** [comment]
use Redis or RabbitMQ

**Comment by yasek** [comment]
Hi!
What is the status of this issue?
I'm running into it right now. I want to add, it doesn't reproduce in pdb.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support MongoDB.

**Comment by varelaz** [comment]
This bug is related to pymongo, when collections list is empty in some cases:
https://jira.mongodb.org/browse/PYTHON-790
