### ISSUE TITLE
How to do silent installation  celery and pika on windows

### ISSUE THREAD

**Issue by UmAravind** [celery/celery#2723]
I want to do silent installof celery and pika on windows. i have downloaded "celery-3.1.18.tar" and "pika-0.9.14.tar" and extracted. when i say "pip install pika " on my batch file it is asking for proxy and not able to proceed installation. is there any way to install these without connecting to the internet. 

Thanks
Uma

**Comment by PMickael** [comment]
That's not a celery issue http://stackoverflow.com/ will be better for this type of question.
http://lmgtfy.com/?q=how+to+install+python+package+without+internet
