### ISSUE TITLE
Task result is truncated to 128 chars by workers

### ISSUE THREAD

**Issue by AEtrade** [celery/celery#2724]
Currently  when worker executes the task it returns truncated result  value.

Actual result length is > 128 characters but when accessing this task info through Flower API  its getting truncated .

Is there any parameter where we can increase the truncated length from 128 chars to more OR  suppress truncate feature.

Appreciate your help

Example:

Expected Result:
----------------------
'Hello How are you 1 Hello How are you 2 Hello How are you 3 Hello How are you 4 Hello How are you 5 Hello How are you 6 Hello How are you 7.
.
Observed Result:
----------------------
'Hello How are you 1 Hello How are you 2 Hello How are you 3 Hello How are you 4 Hello How are you 5 Hello How are you 6...

Thanks,
AEtrade.

**Comment by thedrow** [comment]
Can you provide me with a test case that I can use to reproduce your problem?

**Comment by jaylik** [comment]
Same problem here - with same versions on Windows result on database is not getting truncated but on Linux it does.

**Comment by thedrow** [comment]
I think that the task's result is truncated only on event messages. If you get the result using ```result.get()``` you'll get the full result.
@jaylik Am I correct?

**Comment by ask** [comment]
Yeah, events truncate the task result, this is because the events are used exclusively for monitoring.  We may be able to make this character limit configurable.

**Comment by AEtrade** [comment]
Wondering when are you planning to push this feature. It will be really useful if we can have the task event result length configurable.

**Comment by centralniak** [comment]
+1

Please do. 

I think it's a terrible idea to truncate using a hard limit. For me a truncated result is just as unhelpful as no result at all.

**Comment by ask** [comment]
It's available in the master branch:

    app.Task.resultrepr_maxsize = 2000`

**Comment by AEtrade** [comment]
Thank you!!

**Comment by laixintao** [comment]
I was searching for this configuration for the whole night, seriously this should be documented.

**Comment by laixintao** [comment]
Please take a look: https://github.com/celery/celery/pull/5635

@ask @auvipy
