### ISSUE TITLE
Celery hangs

### ISSUE THREAD

**Issue by StagnantIce** [celery/celery#2726]
Celery 3.18 hangs after 20-25 minutes, after restart all works fine.

This problem very popular, logs empty.

**Comment by StagnantIce** [comment]
celery -A robot.celeryd.tasks inspect active

{u'args': u'[]', u'time_start': 3569535.416336562, u'name': u'robot.celeryd.tasks.MakeScreenshot', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'celery', u'exchange': u'celery'}, u'hostname': u'scrapy-w1@vs01.aft.ru', u'acknowledged': True, u'kwargs': u"{'spider_name': 'shop_megafon_ru', 'city': u'\\u0425\\u0430\\u0431\\u0430\\u0440\\u043e\\u0432\\u0441\\u043a', 'cookies': [{u'domain': u'.shop.megafon.ru', u'name': 'homeRegion', u'value': 'khb', u'expiry': None, u'path': u'/', u'secure': False}], 'data_id': 6146428L, 'url': u'http://khb.shop.megafon.ru/mobile/86634.html', 'timeout': 30, 'page_id': 11754L, 'transaction_id': 853}", u'id': u'962854bf-d45b-464e-b32b-f559927dd618', u'worker_pid': 11706}

        software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.9
                    billiard:3.3.0.19 py-amqp:1.4.6
        platform -> system:Linux arch:64bit, ELF imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:amqp results:amqp
        
        BROKER_PASSWORD: '********'
        BROKER_USER: 'pmt'
        CELERYD_CONCURRENCY: 1
        CELERY_BACKEND: 'amqp'
        BROKER_VHOST: 'pmt_host'
        CELERY_IGNORE_RESULT: True
        BROKER_HOST: 'localhost'
        CELERY_INCLUDE: 
            ('celery.app.builtins', 'robot.celeryd.tasks')
        BROKER_PORT: 5672

**Comment by StagnantIce** [comment]
In rabbitMQ i have
=INFO REPORT==== 28-Jul-2015::10:06:38 ===
accepting AMQP connection <0.30974.14> (127.0.0.1:52743 -> 127.0.0.1:5672)

=WARNING REPORT==== 28-Jul-2015::10:06:39 ===
closing AMQP connection <0.30974.14> (127.0.0.1:52743 -> 127.0.0.1:5672):
connection_closed_abruptly

**Comment by StagnantIce** [comment]
celery status return OK

**Comment by StagnantIce** [comment]
3 Workers end own tasks, one worker hung on selenium:
POST http://127.0.0.1:58449/hub/session/271a9be3-2449-4ef7-b0d3-3afcfd29bc93/elements {"using": "css selector", "sessionId": "271a9be3-2449-4ef7-b0d3-3afcfd29bc93", "value": "body"}

And celery hungs..

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
