### ISSUE TITLE
In Celery 3.1.18, rpc backend fail to avoid creating resulting queue per task.

### ISSUE THREAD

**Issue by ghosert** [celery/celery#2729]
I found the amqp backend in old Celery 3.0.24, it creates resulting queue per task, so after reading this: http://docs.celeryproject.org/en/master/whatsnew-3.1.html#new-rpc-result-backend
I upgrade Celery to 3.1.18, as it's said:

> New RPC result backend
This new experimental version of the amqp result backend is a good alternative to use in classical RPC scenarios, where the process that initiates the task is always the process to retrieve the result. 

>It uses Kombu to send and retrieve results, and each client uses a unique queue for replies to be sent to. This avoids the significant overhead of the original amqp result backend which creates one queue per task.

But this is not the case when I tested it as below:

tasks.py
```
celery = Celery('tasks', backend='rpc')
@celery.task
def mul(x, y):
    return x * y
```

test_tasks.py
```
result = mul.delay(2, 3)
print "mul.delay(x, y)={0}".format(result.get())
```

start worker
```
celery -A tasks worker -l info
```

Observe queues in rabbitmq
```
sudo rabbitmqctl list_queues
```

Run test
```
python test_tasks.py
```

So every time I run this test, I could see a new resulting queue created.  It's just opposite to the docs. And further more if I switch rpc to amqb like this:
```
celery = Celery('tasks', backend='amqp')
```

And try the test once again, I could see the resulting queue created, but soon it's auto deleted in Celery 3.1.18, that's exactly what I want. Just curious why the behavior is not like what docs said and amqp backend works while rcp backend does not work.

**Comment by ask** [comment]
A queue for _every client_, so if you have a process sending just one task then exiting, and you call that many times you will have one queue per task.
