### ISSUE TITLE
Retry BUG in windows with prefork concurrency option after v3.1.12

### ISSUE THREAD

**Issue by allenling** [celery/celery#2732]
This issue is that the Celery class in child process would not  be initialized with broker parameters we specified in Celery class, not in the BROKER_URL in celeryconfig.py,  in father process, and in child process would lost broker connection, so retry would not work out.

This is related with pull request #2650, which be merged as temporal solution.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by ask** [comment]
Edit: We don't have the resources to support Windows at all.  This will be the policy going forward unless this situation changes.
