### ISSUE TITLE
Some part of the tasks not executed

### ISSUE THREAD

**Issue by craynot** [celery/celery#2733]
Hi
We use celery==3.1.18, Django==1.6.1 and redis==2.8.0

We have just some test-tasks -

<pre>
@task
def test1():
   CeleryLog.objects.create(log='test1')
   for x in [0,1,2,3,4]:
       print 'test1_{0}'.format(x)
       time.sleep(1)
   return 'test1'

@task
def test2():
   CeleryLog.objects.create(log='test2')
   for x in [0,1,2,3,4]:
       time.sleep(1)
       print 'test2_{0}'.format(x)
   return 'test2'

...

@task
def test7():
   CeleryLog.objects.create(log='test7')
   for x in [0,1,2,3,4]:
       time.sleep(1)
       print 'test7_{0}'.format(x)
   return 'test7'
</pre>

Then we start initiation of a task (launch) one by one -

<pre>
test1.delay()
test2.delay()
test3.delay()
test4.delay()
test5.delay()
test6.delay()
test7.delay()
</pre>

After the initiation of a task all active tasks get to processing, if we look at them through the manage.py celery inspect active. 
They appear in the base as well. 
http://storage3.static.itmages.com/i/15/0728/h_1438084232_4782426_0d2861e699.png

but in fact only some part of the tasks carries out , in this case tasks 1,3,4,6 were carried out.

Records in workflows (logs)  of celery, test objects CeleryLog and recoords of the Result in djcelery_taskstate give testimony to it. 

<pre>
CeleryLog.objects.create(log='test7') - doesn’t carry out
print 'test7_{0}'.format(x) - doesn’t get into the workflows
</pre>

http://storage3.static.itmages.com/i/15/0728/h_1438084844_9211030_ccadb27bd2.png
http://storage2.static.itmages.com/i/15/0728/h_1438084854_6135433_32a067e4a1.png
http://storage3.static.itmages.com/i/15/0728/h_1438084863_1128467_d1887789ee.png
http://storage1.static.itmages.com/i/15/0728/h_1438084876_9261332_b501bbeb61.png
http://storage2.static.itmages.com/i/15/0728/h_1438084886_5168678_8d8c740e36.png
http://storage3.static.itmages.com/i/15/0728/h_1438084896_7981064_468fb3a16f.png
http://storage1.static.itmages.com/i/15/0728/h_1438084907_5403718_7d46db2ecd.png

config celery

<pre>
[program:XXX_celery]
command=/home/XXXXXX/env/bin/python /home/XXXXXX/application/manage.py celery worker -Ofair -l DEBUG -E --autoreload --concurrency=4
user=XXX
stdout_logfile=/home/XXXXXX/logs/celery.log
stderr_logfile=/home/XXXXXX/logs/celery_err.log
directory=/home/XXXXXX/application
autostart=true
autorestart=true
redirect_stderr=true
killasgroup=true

[program:XXX_celerybeat]
command=/home/XXXXXX/env/bin/python /home/XXXXXX/application/manage.py celery beat --schedule /tmp/XXX_celerybeat --pidfile /tmp/XXX_celerybeat.pid
user=XXX
stdout_logfile=/home/XXXXXX/logs/celerybeat.log
stderr_logfile=/home/XXXXXX/logs/celerybeat_err.log
directory=/home/XXXXXX/application
autostart=true
autorestart=true
redirect_stderr=true
startsecs=10
stopwaitsecs = 10
numprocs=1

program:XXX_celerycam]
command=/home/XXXXXX/env/bin/python /home/XXXXXX/application/manage.py celerycam --frequency=10.0
user=XXX
numprocs=1
directory=/home/XXXXXX/application
stdout_logfile=/home/XXXXXX/logs/celerycam.log
stderr_logfile=/home/XXXXXX/logs/celerycam_err.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 120
priority=998 (edited)
</pre>

We will be grateful for the help. 
Thanks

**Comment by ask** [comment]
I would suspect having a broken worker instance running some where, taking these tasks hostage but not reporting them.

Have you terminated all the workers you started properly?

A simple way to verify is to use a different queue: start worker with `-Q testq` and call the tasks using `task1.apply_async(queue='testq')`

**Comment by jackric** [comment]
@craynot did you find a resolution to this? Did ask's suggestion work?

**Comment by craynot** [comment]
@jackric problem was solved by using rabbitmq instead of redis

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
