### ISSUE TITLE
Some suggestions about celery

### ISSUE THREAD

**Issue by jackyfkc** [celery/celery#2734]
I have used celery for about one year, and the following are some tips that we hope that the later celery could support.

The first two are relating to celery event

1. Allows `events.EventReceiver` to specify the durable property of the queue [the built-in is transient] so that the monitor tools like flower will not lost events during restart or crash

2. Send `task-failed` event when the worker received an unknown task instead of just log it

3. It would be great to add a new extension to create a celery worker directory structure for the given app name, like what `django-admin startapp` does

4. Support `apache kafka` as a new broker

**Comment by malinoff** [comment]
Celery is developed by contributors and their contributions, pull requests are welcome.

**Comment by ask** [comment]
2 is fixed in master, for 3 there is already an open issue in Kombu.

For the rest, please open individual feature requests, so that they can be properly tracked!
