### ISSUE TITLE
Getting a weird error from redis, trying to interpret task status as int.

### ISSUE THREAD

**Issue by bigblind** [celery/celery#2736]
I've posted this issue as a question on StackOverflow: http://stackoverflow.com/q/31543804/675311

**Comment by bigblind** [comment]
I solved this issue for myself by switching from a Chord to a Group, where the body of the chord is executed by each task in the group individually. Leads to more computation, but simpler code. I'll investigate going back to a group if we run into scalability issues.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
