### ISSUE TITLE
Exception in task signal causing worker to hang

### ISSUE THREAD

**Issue by averwind** [celery/celery#2738]
The behavior that I am currently seeing is that if there is an exception in a signal itself (http://celery.readthedocs.org/en/latest/userguide/signals.html#task-signals) the worker is not acknowledging the task it was processing. As a result the worker is stuck. Is there a setting that I am missing or is there a convention to wrap signals in a try block always?

**Comment by ask** [comment]
That's a good convention, I guess it must be the same in Django, as that's where the signal code comes from.

But I see no reason why we shouldn't just log the errors in a signal handler, so I have changed it for 4.0
