### ISSUE TITLE
Celery doesn't understand decorators

### ISSUE THREAD

**Issue by benjaoming** [celery/celery#2739]
Thanks for a great *proj*!

Using the same decorator twice puts the task pointer of the second task to point at the first task!

Am I misunderstanding something? IMO my test code should be a valid set of tasks?

## Test code

```python
def my_decorator(func):
    def inner(*args, **kwargs):
        return func(*args, **kwargs)
    return inner


@app.task(bind=True)
@my_decorator
def debug_task1(self):
    print('debug_task1 reporting')


@app.task(bind=True)
@my_decorator
def debug_task2(self):
    print('debug_task2 reporting')

```

## Output
```
[2015-08-01 18:18:38,176: WARNING/MainProcess] celery@foss4ever ready.
[2015-08-01 18:18:39,254: INFO/MainProcess] Received task: proj.celery.inner[252d3cbb-4b3c-4301-bcb0-325d4f5c7af4]
[2015-08-01 18:18:40,178: WARNING/Worker-2] debug_task1 reporting
[2015-08-01 18:18:40,180: INFO/MainProcess] Task proj.celery.inner[252d3cbb-4b3c-4301-bcb0-325d4f5c7af4] succeeded in 0.00298562200624s: None
[2015-08-01 18:18:40,308: INFO/MainProcess] Received task: proj.celery.inner[9e148599-0d9b-403f-bf85-97e722dba087]
[2015-08-01 18:18:40,311: WARNING/Worker-3] debug_task1 reporting
[2015-08-01 18:18:40,313: INFO/MainProcess] Task proj.celery.inner[9e148599-0d9b-403f-bf85-97e722dba087] succeeded in 0.00253374400199s: None
```

I notice that celery only registers one task. Here is the output of `celery -A proj worker`:

```
(snip)
[tasks]
  . proj.celery.inner
```

## Workaround example

```
# Celery doesn't understand decorators
# https://github.com/celery/celery/issues/2739
def my_decorator(func):
    def inner(*args, **kwargs):
        return func(*args, **kwargs)
    return inner


@app.task(bind=True)
def debug_task1(self):
    @my_decorator
    def work():
        print('debug_task1 reporting')
    work()


@app.task(bind=True)
def debug_task2(self):
    @my_decorator
    def work():
        print('debug_task2 reporting')
    work()
```

**Comment by benjaoming** [comment]
...to understand what I was trying to achieve, I was working on a decorator for exclusive access and locks, inspired by [The Cookbook](http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time).

```python
def exclusive_task(timeout):

    def wraps(func):

        def inner(*args, **kwargs):
            # The cache key consists of the task name and the MD5 digest
            # of the feed URL.
            feed_url_hexdigest = md5(";".join(map(str, args))).hexdigest()
            lock_id = '{0}-lock-{1}'.format(func.__name__, feed_url_hexdigest)

            return_value = None
            if cache.add(lock_id, 'true', timeout):
                try:
                    return_value = func(*args, **kwargs)
                finally:
                    cache.delete(lock_id)
                return return_value

        return inner

    return wraps
```

**Comment by malinoff** [comment]
Python is funny language - sometimes it behaves _extremely_ obvious, sometimes not. This is the latter case.

Let me explain what's going on here. When you apply your decorator, it returns the inner function instead of decorated function - and this is simply how decorators work.
Thus instead of making tasks from your functions, you're making tasks from the inner function, and since you don't specify task names explicitly, `@task` decorator simply choses `inner` name.

To make this work, you should either specify task names explicitly:
```python
def my_decorator(func):
    def inner(*args, **kwargs):
        return func(*args, **kwargs)
    return inner


@app.task(name='debug_task1', bind=True)
@my_decorator
def debug_task1(self):
    print('debug_task1 reporting')


@app.task(name='debug_task1', bind=True)
@my_decorator
def debug_task2(self):
    print('debug_task2 reporting')
```
or apply `@task` decorator first, before any other decorators:
```python
def my_decorator(func):
    def inner(*args, **kwargs):
        return func(*args, **kwargs)
    return inner


@my_decorator
@app.task(bind=True)
def debug_task1(self):
    print('debug_task1 reporting')


@my_decorator
@app.task(bind=True)
def debug_task2(self):
    print('debug_task2 reporting')
```

**Comment by benjaoming** [comment]
@malinoff thanks for the suggestion of using the `name` kwarg, that surely is a better work-around.

But by closing the issue, do you mean that there is no way that we can make Celery understand decorators? Because my understanding was that Celery was using the `func.__name__` property or likewise to generate a key/value store with function pointers -- meaning that one function with the same name (`inner`) overwrites the other. Maybe there is a solution to this?

Moving the decorator will not solve anything, I'm afraid.. because it will receive the output of `app.task` or `shared_task` and thus not the actual callback.

**Comment by malinoff** [comment]
> But by closing the issue, do you mean that there is no way that we can make Celery understand decorators?
I showed you 2 ways of making decorators to work. There is a third way which I actually forgot - you should decorate your `inner` function with `functools.wrap`, so it will receive the name of the wrapped function and everything will work.

> Because my understanding was that Celery was using the func.__name__ property or likewise to generate a key/value store with function pointers -- meaning that one function with the same name (inner) overwrites the other.
This is what exactly happens.

> Moving the decorator will not solve anything, I'm afraid.. because it will receive the output of app.task or shared_task and thus not the actual callback.
Are you sure you need the actual callback or you need the `calling api`? Because task objects support `calling api` - you can call them like general functions.

**Comment by benjaoming** [comment]
Thanks for explaining again! And thanks for the functools proposal, that must surely be the preferred way!

So just a quick proposal, shoot it down if it doesn't make sense.

I wrote:
> > meaning that one function with the same name (inner) overwrites the other. Maybe there is a solution to this?

What if Celery didn't overwrite anything? Would it be able to just append something to avoid overwriting? So the first becomes, `inner` and the second becomes `inner2` ? That would make decorators work as expected, although at the cost of meaningful labels.

**Comment by malinoff** [comment]
The algorithm of doing this isn't pretty obvious for me. What if I'll write `inner1` inner function? How it should be interpreted?
These are just 2 questions, but I can (although I really don't want to) ask more. If you still think this is a good suggestion - try to implement it and write unit tests using https://hypothesis.readthedocs.org/en/latest/

**Comment by benjaoming** [comment]
If it's with good reason that Celery doesn't use unique labels, and this is indeed the explanation (not sure yet), then I don't wanna patch it :)

But if someone can convince me that it's desired, I wouldn't mind trying.

It could, however, be more desirable to improve the documentation, was thinking about forementioned [example in The Cookbook](http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time) could exemplify using a best practice custom decorator for exclusive access.

**Comment by malinoff** [comment]
The question is who ensure uniqueness of label. As framework, celery lets the programmer decide how to name (to label) his tasks. And we have nothing to deal with misusing decorators or whatever else.

**Comment by benjaoming** [comment]
@malinoff the use of the function name as the label is an implicit choice that does not necessarily strike the programmer as obvious. Of course, using `functools.wraps` is generally a good idea for decorators.

I can update The Cookbook example if at least someone would weigh in with a positive remark about that idea, otherwise I'll let it pass :)

**Comment by malinoff** [comment]
This choice is pretty obvious for most of people and can be easily overridden via `name` argument.

Please understand that you're literally the first user who complains about current task naming algorithm. I'm not gonna continue this conversation explaining the basics again and again.

Celery is open-source and community-driven application, so if you want to update the cookbook - you're welcome, simply fork & make PR. Community and core contributors then will decide is it worth to accept your PR or not.

**Comment by benjaoming** [comment]
@malinoff I'm not complaining about anything? I just don't want to work on something that initially wasn't appreciated.
