### ISSUE TITLE
Celery mongo backend fails with greentlet + pymongo > 3.0

### ISSUE THREAD

**Issue by sukrit007** [celery/celery#2743]
**Given**:
 A celery worker configured to use greelet and mongo backend using pymongo > 3.0

**When**:
I execute any task that requires backend

**Then**:
My task fails with error
```
ConfigurationError: Unknown option use_greenlets
```

**Cause**:
use_greenlets option was removed in pymongo 3.0.

[https://github.com/celery/celery/blob/master/celery/backends/mongodb.py#L161](https://github.com/celery/celery/blob/master/celery/backends/mongodb.py#L161)

We possibly need to check the version of pymongo prior to passing this option.

See:  [http://emptysqua.re/blog/it-seemed-like-a-good-idea-at-the-time-pymongo-use-greenlets](http://emptysqua.re/blog/it-seemed-like-a-good-idea-at-the-time-pymongo-use-greenlets/)

**Comment by thedrow** [comment]
@celery/celeryproject Don't close this until I cherry pick it into master as well

**Comment by ask** [comment]
Hey @sukrit007, can you please add your name to https://github.com/celery/celery/edit/master/CONTRIBUTORS.txt ?

**Comment by ask** [comment]
Cherry picked into master

**Comment by sukrit007** [comment]
@ask  done.  PR:  https://github.com/celery/celery/pull/2887
