### ISSUE TITLE
Document multiple broker URLs in Broker Settings

### ISSUE THREAD

**Issue by wohlgejm** [celery/celery#2749]
The [Broker Settings](http://celery.readthedocs.org/en/latest/configuration.html#broker-settings) do not document the ability to specify multiple broker URLs. This is important with the addition of Broker Failover Strategy to the docs since the failover strategy will use another broker URL if specified. This feature, along with an example, should be included in the docs.

**Comment by ask** [comment]
Was there ever a pull request opened for this?

**Comment by thedrow** [comment]
It was https://github.com/celery/celery/commit/356f142f9a5744e1862e07f7af7ad0cc4b09d6ae
