### ISSUE TITLE
Document headers argument

### ISSUE THREAD

**Issue by juanrossi** [celery/celery#2750]
At the moment there's no much information regarding headers argument for apply_async (and I think also applies to retry).

I found out about this reading the changelog for version 3.1, but maybe it could be specified as an optional property for apply_async in the documentation.

I can provide the PR for this if you want. Let me know if you agree.

**Comment by malinoff** [comment]
Docs improvements are always welcome!

**Comment by juanrossi** [comment]
@malinoff Awesome. I'm trying to build the changes I applied but I'm getting the following error:

```
$ make html
mkdir -p .build/html .build/doctrees
sphinx-build -b html -d .build/doctrees   . .build/html
Running Sphinx v1.3.1

Extension error:
Could not import extension celery.contrib.sphinx (exception: cannot import name get_fdmax)
make: *** [html] Error 1
```

I searched a little but wasn't able to find any information regarding that error. I'm using Mac OS X 10.10.3 with virtualenv (All docs requirements installed) and Python 2.7.6. Should I use Python 3? Thanks.

**Comment by malinoff** [comment]
https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#building-the-documentation

**Comment by juanrossi** [comment]
I followed those steps and got that error

**Comment by malinoff** [comment]
@juanrossi yeah sorry, you need Celery installed to build docs.

**Comment by juanrossi** [comment]
@malinoff worked great with celery installed, thanks. I added the PR.
