### ISSUE TITLE
Celery multiple execution of jobs

### ISSUE THREAD

**Issue by kapilratnani** [celery/celery#2754]
We use celery beat executor to schedule jobs. Due to a bug in our start/stop/restart script somehow we had multiple instances of celery processes running. All jobs started executing 4 times. 
Is there a better way to avoid this kind of behavior?

**Comment by chrisgogreen** [comment]
I might have had a similar problem. https://github.com/celery/celery/issues/2746

**Comment by malinoff** [comment]
Do not introduce bugs in your startup scripts.
