### ISSUE TITLE
Celery chain and retries not working

### ISSUE THREAD

**Issue by donzeno23** [celery/celery#2759]
Celery subtasks being retried as part of a chain are put behind the queue of tasks.

```
run_task1.s(args, kwargs).set(exchange='tb', routing_key='tb.q1')
run_task2.s(args, kwargs).set(exchange='tb', routing_key='tb.q1')

suite_chain = (run_task1, run_task2)
suite_result = suite_chain.apply_async()

```

If `run_task1` fails and it retried, it gets put behind `run_task2`.  I would expect that if `run_task1` fails it is retried before `run_task2` is started.

**Comment by ask** [comment]
Does your task actually raise the Retry exception?

If the task does not raise the exception, (i.e. `self.retry(throw=False)` then the worker will have no idea the task was retried

**Comment by czchen** [comment]
I also encounter this issue when using `self.retry(args=...)`. Do I need to add `throw=False` for this particular scenario?

Also, this issue is the same as #2393.

**Comment by czchen** [comment]
After carefully examining the result, we found that our issue is not about broken dependency in retry, but the duplication of retry task. For example:

```python
(task1.s() | task2.s())
```

When `task1` retires, sometimes there will be more than one `task1` in job queue after retry, so the log will confuse us to think that `task2` executes before `task1` finishes. Actually `task2` executes before one `task1` finishes, but there are more `task1` is created during retry.

**Comment by ask** [comment]
Thanks for the update!  Does that resolve the issue so it can be closed?

**Comment by donzeno23** [comment]
This wasn't the same issue I was seeing. I was getting task1 fails, then task2 starts and the 'failed' task1 gets put behind in the queue.  There weren't any other task1's in the queue.  But I'll will attempt to reproduce this and let everyone know if this is no longer the case.

**Comment by ask** [comment]
callbacks/chains do not go forward if the previous task fails, same with retries (as long as the task actually raises `Retry`).

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by Sinkler** [comment]
> When task1 retires, sometimes there will be more than one task1 in job queue after retry, so the log will confuse us to think that task2 executes before task1 finishes. Actually task2 executes before one task1 finishes, but there are more task1 is created during retry.

@czchen hello! did you find causes of this? probably we have something similar now and it blows my mind 😞

**Comment by chaufmaurice** [comment]
Hello,
Same thing on on v4.1.0 😞, Chain continues even with a task raising an exception (or a retry).
Is it a normal behavior ?

**Comment by davidemoro** [comment]
Hi, issue still there in 4.2.1. Is there any plan for this fix?

**Comment by davidemoro** [comment]
@auvipy sorry for the noise, it worked fine! You can close again this issue, thanks

**Comment by auvipy** [comment]
thanks @daevaorn :dancer:
