### ISSUE TITLE
ImproperlyConfigured when using custom user

### ISSUE THREAD

**Issue by fchevitarese** [celery/celery#2761]
Hi! 

Im getting an error and o dug over thousands of sites looking for a solution, but i got none. 
When i use a custom user model to manage my users i got this error.

Removing it, celery works as it should =D 

I'm using the settings explained on the docs website. Im using the last version of celery and, Django version 1.7.8 

I tried the last version of Django but the problem persists... 

File "/home/fred/.virtualenvs/datagoal/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 141, in get_user_model
    raise ImproperlyConfigured("AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL)

Here's a link with the full traceback.

https://gist.github.com/fchevitarese/20ddedcb9ac47e383355

Thanks in advance! =D

**Comment by malinoff** [comment]
You probably need to run south migrations to upgrade your DB to respect Django ORM changes.

I'm closing this because the original issue isn't related to Celery.
