### ISSUE TITLE
Chord of Chords - Timeout

### ISSUE THREAD

**Issue by dvfabbri** [celery/celery#2766]
I am trying to create a chord followed by multiple other chords. However, this produces a timeout exception if a chord takes longer than 3 seconds. I believe this is caused by the following line of code:

https://github.com/celery/celery/blob/master/celery/backends/base.py#L583

Is there a good way to allow for chords of chords without this timeout issue?

**Comment by malinoff** [comment]
@dvfabbri first of all, please do not use emails for questions you can ask right here.
Secondly, assigning a label doesn't imply that we will resolve this issue as soon as possible - celery is  maintained by volunteers in our free time, so please be patient.

**Comment by thedrow** [comment]
Why do you believe that https://github.com/celery/celery/blob/master/celery/backends/base.py#L583 is the source of the problem?

**Comment by dvfabbri** [comment]
@thedrow Looks like the line # changed.  See  ret = j(timeout=3.0, propagate=propagate)

https://github.com/celery/celery/blob/master/celery/backends/base.py#L596

**Comment by thedrow** [comment]
Can you demonstrate it with a test case?
Something that is easily reproducible, possibly with sleep() or a similar mechanism.

**Comment by dvfabbri** [comment]
@thedrow @jacobwegner

Something like:

def f():
  print 'hi'

chord( chord(time.sleep(10))(f) )

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
