### ISSUE TITLE
Chord fails because of RuntimeError

### ISSUE THREAD

**Issue by anmannin** [celery/celery#2768]
Chord fails because of RuntimeError when chaining with big group of tasks.
 
Command:

chain(group(tasks), task2.si(argument)).apply_async()

Output from redis-cli monitor command:

1439885187.635801 [2 10.255.36.9:59002] "PUBLISH" "celery-task-meta-4a2081a1-949e-4747-b5c9-a17477c6dd40" "{\"status\": \"FAILURE\", \"result\": {\"exc_type\": \"ChordError\", \"exc_message\": \"RuntimeError('dictionary changed size during iteration',)\"}, \"traceback\": \"Traceback (most recent call last):\\n  File \\\"/usr/local/site-packages/celery/backends/base.py\\\", line 568, in on_chord_part_return\\n    culprit = next(deps._failed_join_report())\\nStopIteration: RuntimeError('dictionary changed size during iteration',)\\n\", \"children\": []}"

'tasks' is a list of tasks that only sleeps for 1 second and print something out. All the tasks in 'tasks' seems to be called. 'task2' is never called because of this problem.

Problem happens always when 'tasks' has 400 entries. This problem is random with 10 entries.

We are using python 2.7.5, celery 3.1.18, RabbitMQ  3.5.0 as broker and Redis 2.8.19 as results backend.

We have concurrency of 4 (workers) with 2 different celery instances. So altogether 8 concurrent workers.

**Comment by ask** [comment]
We need the output from the worker logs, otherwise it's impossible to know what the traceback is!

One of the tasks in the chord group failed, so there must have been a traceback

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
