### ISSUE TITLE
Workers not starting tasks

### ISSUE THREAD

**Issue by tclinken** [celery/celery#2771]
I am running Celery 3.1.18 with a RabbitMQ broker. My Celery workers are receiving tasks, but they are not starting the tasks, even though the workers are not busy. All tasks just stay in the reserved state, indefinitely.

**Comment by malinoff** [comment]
Have you tried `-O fair`?
http://celery.readthedocs.org/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings

**Comment by tclinken** [comment]
-O fair does not fix the problem, but I believe it is a problem with prefork, because running with -P solo works fine.

**Comment by malinoff** [comment]
Ok, we will need more information: your code, configuration, how you run workers, logs and other useful info like `inspect.active`.

**Comment by tclinken** [comment]
My configuration is:

CELERY_SEND_EVENTS = True
CELERY_SEND_TASK_SENT_EVENT = True
CELERY_IGNORE_RESULT = True
CELERY_DEFAULT_EXCHANGE = 'default'
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_CREATE_MISSING_QUEUES = True
CELERY_ACCEPT_CONTENT = ['pickle']

I am starting my workers with celery multi start 1.

The worker logs are showing that the workers receive the tasks, but they do not show that the task is starting. Checking inspect.active shows no active tasks. All tasks are reserved once they reach the worker.

**Comment by ask** [comment]
Are you sure they are not ETA/countdown tasks?  Please include worker logs with `-l debug` enabled.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
