### ISSUE TITLE
database unavailable after worker timed out, but worker still accepts tasks

### ISSUE THREAD

**Issue by keturn** [celery/celery#2772]
I expect this to be hard to reproduce, but I'm going to try to write down what I see, and maybe we can figure something out.

Logs indicate a worker failed to start up, and was SIGKILL'd:

```
Aug 18 12:37:30 app/cache.2:  [2015-08-18 12:37:30,222: ERROR/MainProcess] Timed out waiting for UP message from <Worker(Worker-4, started daemon)> 
Aug 18 12:37:33 app/cache.2:  [2015-08-18 12:37:33,488: ERROR/MainProcess] Process 'Worker-4' pid:20 exited with 'signal 9 (SIGKILL)' 
Aug 18 12:37:34 app/cache.2:  [2015-08-18 12:37:34,518: WARNING/Worker-5] /app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: OperationalError('SSL SYSCALL error: Bad file descriptor\n',): 
```

Worker-3 had been up and processing jobs for some time. I don't know why it tried to bring up Worker-4, but I assume it was because it hit CELERYD_MAX_TASKS_PER_CHILD.

I don't know why it timed out bringing up Worker-4. It didn't do so for workers 1–3, the loadavg was not high, nor was it running out of memory.

That wouldn't have been so bad, but it was immediately followed by this:

Aug 18 12:37:34 app/cache.2:  [2015-08-18 12:37:34,518: WARNING/Worker-5] /app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: OperationalError('SSL SYSCALL error: Bad file descriptor\n',): 

So apparently Worker-5 did boot even though Worker-4 did not, but its database connection is in some bad state.

We use the database result backend; it was running in to that error trying to `mark_as_failure` the task result. It seems likely that the task was a failure because the task also failed to access the database.

That first OperationalError was logged under WARNING/Worker-5, but it was followed by many from CRITICAL/MainProcess:

Aug 18 12:37:34 app/cache.2:  [2015-08-18 12:37:34,529: CRITICAL/MainProcess] Task django_cached_field.tasks.offload_cache_recalculation[3e177728-e1c8-4d55-b3ca-8428087aadcb] INTERNAL ERROR: OperationalError('SSL SYSCALL error: Bad file descriptor\n',) 

and a **lot** more of those messages followed, as the worker continued to accept tasks, fail them, and then fail to store the failure result.

We do have CELERY_DB_REUSE_MAX set.

Likely related psycpopg issue: https://github.com/psycopg/psycopg2/issues/263

our celery config: https://gist.github.com/keturn/465ab53a77cc2f3e3022

versions:

billiard==3.3.0.20
celery==3.1.18
django-celery==3.1.16
kombu==3.0.26
psycopg2==2.6.1

running on heroku cedar-14

**Comment by keturn** [comment]
the logs also show this:

Aug 18 12:37:26 app/postgres.11298:  [DATABASE] could not receive data from client: Connection reset by peer 

four seconds before the timeout error. But I have no idea if it was referring to a celery client on that dyno or something else completely different.

**Comment by keturn** [comment]
Sentry logged over 500 of these events for us today, which is perhaps interesting given that our CELERY_DB_REUSE_MAX is only 100.

They did stop and normal operation resumed, eventually.

They were all from the same dyno.

**Comment by keturn** [comment]
I turned off CELERY_DB_REUSE_MAX after that incident.

Today we saw a similar event:

Aug 20 10:35:17 app/worker.1:  [2015-08-20 10:35:17,051: ERROR/MainProcess] Timed out waiting for UP message from <Worker(Worker-4, started daemon)> 
Aug 20 10:35:17 app/worker.1:  [2015-08-20 10:35:17,269: WARNING/MainProcess] Substantial drift from celery@03051db1-b07a-4547-b34e-e1f1ef13bf66 may mean clocks are out of sync.  Current drift is 
Aug 20 10:35:17 app/worker.1:  83 seconds.  [orig: 2015-08-20 10:35:17.058757 recv: 2015-08-20 10:33:54.087299] 
Aug 20 10:35:17 app/worker.1:  [2015-08-20 10:35:17,054: INFO/MainProcess] Received task: admingroups.tasks.log_viewing[d0908194-a06d-402c-afbb-50074059b747] 
Aug 20 10:35:17 app/worker.1:  [2015-08-20 10:35:17,540: ERROR/MainProcess] Process 'Worker-3' pid:18 exited with 'signal 9 (SIGKILL)' 
Aug 20 10:35:17 app/worker.1:  [2015-08-20 10:35:17,530: ERROR/MainProcess] Process 'Worker-4' pid:19 exited with 'signal 9 (SIGKILL)' 
Aug 20 10:35:23 app/worker.1:  [2015-08-20 10:35:22,706: WARNING/Worker-5] /app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: OperationalError('SSL SYSCALL error: Bad file descriptor\n',): 

but only a few instances, unlike the other day where it kept taking tasks in that state and racked up 500 such errors.

**Comment by ionelmc** [comment]
Could it be possible that your VM is very slow? (eg: you have too many workers per dyno or something like that)

Can you reproduce this issue locally?

**Comment by ionelmc** [comment]
About the `OperationalError('SSL SYSCALL error: Bad file descriptor\n',)` error. Is it possible that you're trying to setup some sort of SSL connection (database?) at import time? It may be possible that it makes the workers "slow to start" (thus the second failure with the `Timed out waiting for UP message`).

Also, your settings look funny. You don't configure any broker?

**Comment by keturn** [comment]
Hmm, some settings may have been scrubbed on export. We do set BROKER_URL to our RabbitMQ URL.

I can't think of a reason why database connection would happen at *import* time, but that's a thing I can check for. 

But the tracebacks for those OperationalErrors haven't been at import time, they've been trying to write to the result store:
```
  File "celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "celery/backends/base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
[…]
```

I am guessing, that since that is an on_error branch, there was some *other* error that happened first, which is being masked by this one.

It'd probably be helpful if we could get the original error logged to Sentry before this on_error handler goes off and breaks.

(that traceback was from an hour ago)

I don't have a local or otherwise consistent reproduction for this issue.

**Comment by mitchelljkotler** [comment]
@keturn Did you ever resolve this issue?  I am seeing almost exactly the same issue in my app

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
