### ISSUE TITLE
Result backend not working properly on Windows

### ISSUE THREAD

**Issue by michaelzhou0723** [celery/celery#2774]
I have this problem under Celery 3.1.18, Python 3.4, WIndows 8. The result backend I use is redis. When I try out the example in First Step with Celery, the log shows that the task succeeds, but calling ready() or get() hangs there and the worker raises WinError 10061(ConnectionRefused).

Strangely, when I later set app.conf.CELERY_RESULT_BACKEND instead of making it a keyword argument in celery.Celery(), everything suddenly works. I've also tried adding --pool=solo and it works as well.

Is this a bug or I made something wrong?

**Comment by blamarvt** [comment]
Have you had any luck in isolating this issue? It looks like it's a Windows-only issue and that it's been broken (according to my tests) since 3.1.13.

I suggest using 3.1.12 as that seems to be the latest stable version to work on Windows.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
