### ISSUE TITLE
AMQP keep-alives not sent on Windows

### ISSUE THREAD

**Issue by blamarvt** [celery/celery#2776]
I'm unsure if this is a bug or an undocumented/unsupported feature for Windows. If it's the latter it would be nice to have official documentation updated to describe what is and is not supported on Windows. I had no response to my celery-users message a couple months ago: https://groups.google.com/forum/#!searchin/celery-users/heartbeat%7Csort:date/celery-users/OmmCPRdaBaE/i7m4OskoXcQJ

Could it be possible that heartbeats might be implemented in another place other than the eventloop? Will offer bounty if this is accepted as a bug/feature.

Confirmation one way or another would be extremely helpful. Thanks!

**Comment by mervynzhang** [comment]
we have the same problem too on Windows, if we enable amqp heartbeat, we get a lot of "Connection to broker lost"
 app = Celery('tasks', broker='amqp://192.168.99.102:32771?heartbeat=11')

[2016-05-15 14:31:36,997: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection

n...

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
