### ISSUE TITLE
Chain tasks registered on a different celery app

### ISSUE THREAD

**Issue by laginha** [celery/celery#2778]
Hi guys!

I was reading your docs and the section [Avoid launching synchronous subtasks](http://celery.readthedocs.org/en/latest/userguide/tasks.html#avoid-launching-synchronous-subtasks) caught my eye. 

The `chain` examples always use subtasks that are registered on the same celery-app. However that is not always the case. I often call for a task registered on a different celery-app, hosted on a remote machine.

So, if I shouldn't do something like this:

```python
@app.task
def taskname():
    app.send_task('add', args=(2,2), queue='queuename').get()
    app.send_task('add', args=(1,3), queue='queuename').get()
```

what should I do instead? 

I searched a bit on the web and found [here](https://groups.google.com/forum/#!topic/celery-users/glyt7XYHnD4) what could be a solution to the problem:

```python
from celery import chain

@app1.task
def add(*args):
    return sum(*args)

@app1.task 
def chain_helper(*args): 
    return chain(*args).apply_async()
```

```python
from celery import subtask

subtasks = [
    subtask("tasks.add", (2,2)), 
    subtask("tasks.add", (1,3)),
]
app2.send_task("chain_helper", args=subtasks, queue='queuename') 
```

However this will only work if all chainable tasks are on the same celery-app. If that is not the case I'm back to the previous undesirable solution.

What do you think is the best approach?

Thanks

**Comment by ask** [comment]
The easiest way to solve this is to create placeholder tasks:

```
@app.task(name="tasks.add")
def add(x, y):
    pass
```

`add.s() | add.s()`.


This way you can also have documentation, and argument verification (in 3.2) for the tasks.

**Comment by laginha** [comment]
I see... 
If I want to specify a different queue for each subtask, should I do it like this?

```python
add.subtask(args, queue='queuename') | add.subtask(args, queue='other_queuename')
```

Thanks

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by Aeon** [comment]
Can we reopen this? Is there a solution for this type of workflow?

**Comment by Chris7** [comment]
@Aeon I routinely do this like this:

```
from celery import signature
x = signature('app_name.xxx.task_name', args=(1,2,3), kwargs={'blah': 'blah'}, queue='queue-to-use') | signature('app2_name.xxxx'...., queue='some-other-queue')
x.apply_async()
```

**Comment by Aeon** [comment]
Thanks @Chris7
