### ISSUE TITLE
Worker with embedded beat doesn't work on python 3

### ISSUE THREAD

**Issue by atleta** [celery/celery#2780]
Hi,

I've just run into this: when running the worker with an embedded beat (for development purposes), the worker just doesn't pick up the tasks on python 3. Took a while to triangulate, but I verified that this happens only on python 3 (tried with 3.4). The exact same code works on python 2. Also, if I start a separate worker process, then that one does pick up the tasks.

Also, with python 3 and only the worker running beat embedded, celery inspect will time out. Seems like the worker is indeed blocked or never started. (I don't know the internals.)

  Cheers,
    Laszlo

**Comment by atleta** [comment]
Indeed it's the --autoreload that kills it. With or without a beat. But still only on python3(.4)

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Autoreload will be undocumented in 4.0.
