### ISSUE TITLE
Is there way to specify expiry when creating a celery task?

### ISSUE THREAD

**Issue by pcompassion** [celery/celery#2786]
Specifically I use `shared_task` decorator to create a celery task.
I tried the obvious `@shared_task(expires=3)` but it doesn't seem to work.

Is there a way to tell this task is supposed to expire ** seconds after it is received as you can do with `apply_async` in calling time?

I tried to see what @shared_decorator does by looking at the code, but it wasn't obvious... 

(I copied the question from SO, cause it didn't get enough attention. http://stackoverflow.com/questions/32217358/is-there-way-to-specify-expiry-when-creating-a-celery-task)

**Comment by ask** [comment]
Definitely works for me here if I specify an expires argument to the `@shared_task` decorator:

<pre>
[2015-09-04 13:03:12,007: INFO/MainProcess] Received task: proj.tasks.add[974c2c16-fb0b-4159-9f97-82a556046457]   expires:[2015-09-04 20:03:14.679377+00:00]
</pre>

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
