### ISSUE TITLE
Send 'task-failed' event when consumer receives an unknown message, task or invalid task

### ISSUE THREAD

**Issue by martinxsliu** [celery/celery#2791]
We had an issue where if the celery task wasn't properly imported by the worker's app, then the `AsyncResult` returned by the `task.apply_async` call does not reflect the fact that the task had failed to run. The `result.state` and `result.ready()` looked as if the task was still incomplete.

After digging through the code for some time, I saw that the `on_unknown_message`, `on_unknown_task`, and `on_invalid_task` callbacks, defined [here](https://github.com/celery/celery/blob/84061be2618119f77bf33964fade33ca6521904c/celery/worker/consumer.py#L453-L493), simply tells the broker to reject the message, without sending any events back to the task caller that the task has been rejected. This leads to a potential situation where the caller is waiting for a state change that is never going to happen.

Can we remedy this issue by sending a `task-failed` or a `task-rejected` event so that the task caller is made aware of the failure?

**Comment by averwind** [comment]
I was actually about to open an issue trying to figure out why it is behaving this way as well, may be @ask had something in mind.

**Comment by sireeshk** [comment]
We are using signals to track tasks, can a signal also be generated when this happens?

**Comment by ask** [comment]
We are first able to do this now in master with the new message protocol, but I haven't had the chance to make the changes yet.

The result is tricky, as the result backend is actually connected to the task and different tasks can technically have different result backends.  I was working on a reply_to header that would replace the default backend, and this would also solve that issue.

**Comment by ask** [comment]
Closed by 20424c5561bc9a99c624da5c8e98b4fcefc1fdcd
