### ISSUE TITLE
The "cbor" serializer

### ISSUE THREAD

**Issue by tailhook** [celery/celery#2795]
The [CBOR](http://cbor.io/) is an RFC-standard serializer that is similar for performance characteristics to msgpack. So I think celery should support cbor out of the box.

So is anyone working on it? Is contribution of cbor serializer welcome?  (or perhaps celery doesn't want to grow number of serializers supported?)

**Comment by thedrow** [comment]
We're not going to merge new features for the 3.2 release but it's possible to discuss adding it for 3.3.
I'm not familiar with the format though. Is it new? Is it widely used?
You can provide it as a 3rd party library quite easily.

**Comment by ask** [comment]
I'm going to close this for now, as I don't think anyone is working on it.

New serializers are wanted, but they can also exist as separate PyPI projects.

Using setuptools entry points you can define new serializers in setup.py, and Celery can use them by name.

**Comment by thedrow** [comment]
@ask We can migrate these projects to the celery organization if they are popular.
