### ISSUE TITLE
Difficulty setting db to "/1" in settings (redis backend/broker)

### ISSUE THREAD

**Issue by rschwiebert** [celery/celery#2798]
We have not been able to make our celery app use db 1 in our redis backend. When making the celery object, we supply something of the form "redis://hostname/1" for both the broker_url and backend keywords in the Celery object. We discovered in operation that everything pointed at redis://hostname/0.

Then we scoured the documentation, confirming the following settings existed, and/or adding them with app.conf.update:

BROKER_URL =  'redis://hostname/1'
CELERY_RESULT_BACKEND = 'redis://hostname/1'
BROKER_VHOST = "1"
CELERY_REDIS_DB =1

The string 1 and integer 1 settings are set that way because that's what I found in the documentation (I might not be able to find that documentation again.)

Then I manually edited the backends/redis.py file to log out what value it caught for the db attribute in the RedisBackend _init_ method.  The log said it received a value of None.

We have effectively run out of ideas for trying to get this thing to point at /1 rather than /0. Any ideas?

**Comment by ask** [comment]
The Redis result backend will not receive a db argument in the constructor, unless you instantiated it manually, the URL is parsed in `_params_from_url`.


    >>> Celery(backend='redis://localhost/4').backend.connparams
    {'db': 4,
     'host': 'localhost',
     'max_connections': None,
     'password': None,
     'port': 6379,
     'socket_timeout': None}

Looks like it's working from here, unless redis-py changed the name of the db parameter.

**Comment by rschwiebert** [comment]
I forgot to mention the discovery of this problem, in case it helps. 

The Celery app was put on /1 because another set of celery tasks was already using /0 . We discovered that the Flower monitor on this app though the broker was at /0, and we discovered that the workers from this app were picking up (and discarding) tasks from the /0 queue. All of the configuration to /1 above was an effort to fix the apparent problem that this app apparently runs on /0 regardless of what we do.

**Comment by rschwiebert** [comment]
Later, we discovered that the /0 and /1 issue might have been due to some caching, and clearing that cache permitted the broker and backends to display their correct database. However, we still see the same problematic behavior that the worker with broker /1 picks up messages from the broker on /0 (and promptly discards them.)

**Comment by ask** [comment]
Did you enable the `fanout_patterns` and `fanout_prefix` setting as described here:
http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#caveats ?

Note that this must be enabled not only for workers, but also for clients and flower itself.

**Comment by rschwiebert** [comment]
@ask There are two app objects, and in both of them we have fanout_prefix and fanout_patterns set to True. As far as I know, this is what all workers and flowers are looking at. In what other locations should it be set?

**Comment by ask** [comment]
I'm not aware of any, but anything consuming events from Redis.  The best solution it to always use -A app, where app is configured the same.
