### ISSUE TITLE
How to use memory as transport backend ? 

### ISSUE THREAD

**Issue by mayuroks** [celery/celery#2799]
I have seen celery redis examples. They work out of the box. But I have a requirement where I cant use redis since its an external package.

Hence I am trying to use memory as transport URL, like this

**# tasks.py**
```python
from celery import Celery

app = Celery(
    backend='db+sqlite:///results.sqlite',
    broker='memory://localhost:8000//'
)

@app.task
def say_hello():
    print "Hello"
```

In a **new python shell** when I do, 
```
from tasks import app

app.send_task('tasks.say_hello')
```

It just doesn't work. Celery doesn't show that it even received any task let alone executing it. Is there a good solution.

**Comment by moggers87** [comment]
The memory broker won't work between multiple processes - they don't share the same memory. You might want to look at the SQLAlchemory and Django brokers if you don't want to install Redis

**Comment by thedrow** [comment]
The memory backend is used only for fast functional testing. You can use it to run https://github.com/celery/celerytest inside your tests.
I don't think it was meant to be used in production.

**Comment by ask** [comment]
Yeah, the memory backend is just using local memory.  What you want is IPC
