### ISSUE TITLE
how to start a celery worker cluster?

### ISSUE THREAD

**Issue by BlueKarl** [celery/celery#2800]
How to start a celery worker cluster?  like a redis cluter, it can work togther for the same task。
thx for a lot if your reply~

**Comment by kakiezhang** [comment]
Basically, it might not be used like you said, but you can try the threads pool instead. Let the backend task to do this thing.

**Comment by BlueKarl** [comment]
I have tried  "celery multi start 2 -A xxxxx -c 10 -l warning",but i don't have permission to write "celery1.log". could you list an example of it about threads pool ?

**Comment by kakiezhang** [comment]
You have not permission to write the celery log, it's probably that you didn't give the right privileges to the folder your command was executed. Right now, you could try the chmod cmd to correct it.

And BTW, Using the multi mod can't stand for that the consumer can together worker with the same task.

**Comment by BlueKarl** [comment]
could you list an example of it about threads pool ?

**Comment by BlueKarl** [comment]
now, my celery worker need to horizontal expansion for my programs , one worker can't support my task generated large amounts of data. so i need two or more worker work togther for my task.  but i have no idea for this   ~.~

**Comment by kakiezhang** [comment]
Make sure that you have read the documents, and it has lots of examples. You can read this: https://celery.readthedocs.org/en/latest/userguide/workers.html , it simply told you how to start workers with celery multi.

**Comment by thedrow** [comment]
If you create two workers that are subscribed to the same worker they will distribute tasks with themselves.
If you need something specific, feel free to ask on our IRC channel.
