### ISSUE TITLE
Django 1.8 migration Error

### ISSUE THREAD

**Issue by Gocht** [celery/celery#2801]
I installed `django_celery` as [documented here](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-the-django-orm-cache-as-a-result-backend), but when I run `python manage.py migrate` i get:

    django.db.utils.OperationalError: (1050, "Table 'djcelery_crontabschedule' already exists")

I don't understand why if I've just added djcelery to INSTALLED_APPS

**Comment by sblancov** [comment]
It could be that 'djcelery_crontabschedule' table existed in your database before you execute `python manage.py migrate`.

I have not seen any 'migrations' directory in celery project... so it is probably that you had tried to install celery twice. The first time, you created all tables (or some of them) and the second time you got that error.

Anyway, try to provide information about your environment... OS, Python version, Django version, celery version, type of database... it could be helpful.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

The models in django-celery will be moved to a new project, deprecating django-celery entirely.
