### ISSUE TITLE
Mention BROKER_USE_SSL setting in security documentation.

### ISSUE THREAD

**Issue by JocelynDelalande** [celery/celery#2804]
http://celery.readthedocs.org/en/latest/userguide/security.html do not mention the fact you can encrypt the broker connection end to end, with `BROKER_USE_SSL` setting, is that on purpose ?

I could give a try to writing the paragraph if that seems relevant.

**Comment by ask** [comment]
If you could work on  this, that would be great :)

**Comment by JocelynDelalande** [comment]
Working on it, but blocked by #2809

**Comment by JocelynDelalande** [comment]
Closing, as #2817 got merged.
