### ISSUE TITLE
Lots of disowned celery processes accumulating

### ISSUE THREAD

**Issue by mverrilli** [celery/celery#2806]
celery (3.1.18)
billiard (3.3.0.20)

on Solaris.  

Running with -c 128 -Ofair --maxtasksperchild=20  

The task is not complex but it is long running (can take seconds to minutes to run) and does connect to a queue using kombu.  This has no threading or forking within it, just scan a directory, look for matches and toss a message on a different message queue.  It's also a very frequently used tasks, hundreds of times per minute.

I have noticed I am getting a lot of extra celery processes.  I am running 4 celery processes with the above settings, which should result in 516 total processes or so.  I keep finding every day that I have almost 2000 of these.  I verified they are the same process and not some other Celery process I might have by inspecting the arguments.  The processes are disowned from any parent. 

Are there any known issues here or ways that you know of that would allow me to track this down?

**Comment by ask** [comment]
Are they semaphore cleanup processes installed by billiard maybe?

Make sure you are not using CELERYD_FORCE_EXECV=True

**Comment by mverrilli** [comment]
I just noticed this was still open, sorry.  I'm not seeing this happen quite as often, but I'm also not bringing up and down my celery tasks.  I suspect it might have to do with that during shutdown of workers using supervisord. It's probably my setup if no one else is having the issue and I'll dig more into it when I get some time.
