### ISSUE TITLE
Propagate worker signals to children

### ISSUE THREAD

**Issue by mverrilli** [celery/celery#2807]
A useful feature would be if we could propagate signals caught by the main down to the children. (whether via signal or event handler). This would allow long running tasks to exit more gracefully and at known good exit points. It would also allow us to print out some debug info on the child usr1, etc.

Often I end up waiting for eternity for workers to stop. I can't kill them because it'll mess things up, and I have to let it runs its course.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by Chronial** [comment]
This would be a very useful feature to have on heroku, where celery is frequently (on every deploy, every config change and at least once every 24h) killed with `SIGTERM`, and there's nothing you can do about that.
