### ISSUE TITLE
Missing dependencies in requirements/docs.txt

### ISSUE THREAD

**Issue by JocelynDelalande** [celery/celery#2809]
Tried to build celery docs [following the doc](http://docs.celeryproject.org/en/master/contributing.html#building-the-documentation), I stumbled uppon that error:
```
$ make htmlmkdir -p .build/html .build/doctrees
sphinx-build -b html -d .build/doctrees   . .build/html
Running Sphinx v1.3.1

Extension error:
Could not import extension celery.contrib.sphinx (exception: cannot import name get_fdmax)
Makefile:30: recipe for target 'html' failed
make: *** [html] Error 1
```

Note that celery is installed in my virtualenv, alongside with doc dependencies.

**Comment by malinoff** [comment]
Are you sure you have enabled your virtualenv before running make?

**Comment by JocelynDelalande** [comment]
@malinoff pretty sure, I can run a console from the same shell and `import celery` without any issue.

**Comment by valentinzberea** [comment]
What worked for me was to `pip install -r requirements/dev.txt`

**Comment by JocelynDelalande** [comment]
@valentinzberea Thanks, worked for me too… So this is a **documentation bug**.

**Comment by ask** [comment]
The doc requirements in docs now depends on `-r dev.txt`
