### ISSUE TITLE
Error Email：can not receive emails

### ISSUE THREAD

**Issue by Lingling7** [celery/celery#2814]
I'm a python django and celery beginner, I want to set up the celery on local. For now, I'm setting the error email for all the failure tasks. What I have done are as below, please help me! Thanks!

1. add these code to setting.py
```python
CELERY_SEND_TASK_ERROR_EMAILS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Name and email addresses of recipients
ADMINS = (
    ('test', '...@....com'),
)

EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='...@gmail.com'
EMAIL_HOST_PASSWORD='...'
EMAIL_PORT=587
EMAIL_USE_TLS = True

# since I test this in local, I just simply added these items
```

2. add this in tasks.py
```python
    @app.task(name="test_exception",error_whitelist=[])
```

**Comment by Lingling7** [comment]
I changed 
```python
    @app.task(name="test_exception",error_whitelist=[])
```
to
```python    
   @app.task(send_error_emails = True)
```
I can use send_email now, but still can not automatically send the error email about tasks.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Error emails will be undocumented in 4.0 release.
