### ISSUE TITLE
The celery don't call callback function when i use whoosh in celery

### ISSUE THREAD

**Issue by ArrowZQ** [celery/celery#2816]
The celery don't call callback function when i use whoosh in celery. Througth debug i found when execute some code of whoosh(for example: QueryParser.parse()), the celery don't call callback. i don't know why?but the celery execute correct and return correct result to result backend.
whoosh === 2.7.0
celery ====3.1.18

**Comment by czpython** [comment]
can you post an example of how the callback is being used?
