### ISSUE TITLE
Celery workers hang forever when there is a network / DNS unreachable issue.

### ISSUE THREAD

**Issue by GDICommander** [celery/celery#2822]
Hello,

We are investigating an issue where the Celery workers stop processing new tasks when there is a network issue (domain names not resolvable - probably a DNS issue). Rebooting the workers fixes the problem, but we want to avoid that.

"celerybeat" is the scheduler that pushes tasks to the broker (Redis) and the workers consume from it. When the unresolvable domain names issue occurs, "beat" reports the problems in its logs and resumes scheduling tasks to Redis when the domain names can be resolved again. However, the workers (celeryd) do not log anything on the network issue and hang, even though their log level is "info". Here is the command used to run the workers:

    /opt/virtualenvs/RendezVousPortal/bin/python -m celery worker --concurrency=10 -l info -n worker@msr-rdv-portal-api01.ubisoft.onbe --autoscale=10,1 --app=papi_celery --loglevel=INFO --logfile=/var/www/papi_celery/logs/papi_celery_worker.log --pidfile=/var/run/celery/worker.pid

The workers do not die when the issue occurs.

Note: when I shut down Redis on my dev machine and I put back online, all components (beat, workers) react correctly, there is no stoppage or hanging from the workers).

Unfortunately, I am currently unable to reproduce the problem, as this issue has been reported on a production deployment that uses Celery and obviously I cannot put our live deployment down without complaints from clients. I will attempt to reproduce this problem locally with all the components (beat, workers, Redis) on my local machine and attempt to simulate unreachable domain names / DNS unreachable issues (any help on this would also be appreciated :) ).

We are using the following versions of Celery and its dependencies:

    billiard==3.3.0.20
    celery==3.1.18
    greenlet==0.4.7
    hiredis==0.2.0
    kombu==3.0.26
    redis==2.10.3

Has someone seen this issue before?

Have a good day!

**Comment by mwalker** [comment]
Sounds similar to #2906 etc.

**Comment by ask** [comment]
You can try the solution in #2906

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
