### ISSUE TITLE
Multiple celery workers for multiple Django apps on the same machine

### ISSUE THREAD

**Issue by debnet** [celery/celery#2832]
Hi people,

I have 2 Django projects (at different branchs/versions) on the same machine and both use celery for asynchronous tasks.

I figure thanks to __sentry__ that tasks from app A are sent to workers of app B. Each application runs under a different unix user and workers/wsgi run through __supervisor__.

Here the different configurations:

* __Application A__

- Supervisor

```ini
[program:demo-a-worker]
command=/home/demo_a/start_worker.sh
numprocs=1
directory=/home/demo_a
autostart=true
autorestart=true
user=demo_a
redirect_stderr=true
stdout_logfile=/var/log/demo_a/worker.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
```

- Script

```bash
exec $PYENV/celery worker -A mydjangoproject -B -Q demo_a --loglevel=INFO --hostname demo_a.%h
```

* __Application B__

- Supervisord

```ini
[program:demo-b-worker]
command=/home/demo_b/start_worker.sh
numprocs=1
directory=/home/demo_b
autostart=true
autorestart=true
user=demo_b
redirect_stderr=true
stdout_logfile=/var/log/demo_b/worker.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
```

- Script

```bash
exec $PYENV/celery worker -A mydjangoproject -B -Q demo_b --loglevel=INFO --hostname demo_b.%h
```

* Celery configuration in `mydjangoproject`

```python
# Set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mydjangoproject.settings')
os.environ.setdefault("DJANGO_CONFIGURATION", "Dev")

# Load environment configuration
from configurations import importer
importer.install()


class Celery(celery.Celery):
    """
    Celery configuration class
    """
    def on_configure(self):
        # Get Raven configuration from Django settings
        if not hasattr(settings, 'RAVEN_CONFIG'):
            return
        # Initialize Raven client
        client = raven.Client(**settings.RAVEN_CONFIG)
        # Register a custom filter to filter out duplicate logs
        register_logger_signal(client)
        # Hook into the Celery error handler
        register_signal(client)


# Initialize Celery application
app = Celery('mydjangoproject')

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object('django.conf:settings')

# Auto-discover celery tasks inside Django applications
from django.conf import settings
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

* __Settings__

```python
    # Celery configuration
    BROKER_URL = values.Value('redis://localhost:6379/0')
    BROKER_TRANSPORT_OPTIONS = {
        'visibility_timeout': 3600,
        'fanout_prefix': True,
        'fanout_patterns': True,
    }
    CELERY_TASK_SERIALIZER = 'pickle'
    CELERY_RESULT_SERIALIZER = 'pickle'
    CELERY_RESULT_BACKEND = values.Value('redis')
    CELERY_TASK_RESULT_EXPIRES = 3600
    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
    CELERY_DISABLE_RATE_LIMITS = True
    CELERY_CHORD_PROPAGATES = True
    CELERY_ALWAYS_EAGER = values.BooleanValue(True)
    CELERY_DEFAULT_QUEUE = values.Value('celery', environ_name='QUEUE_NAME')
```

Values are environment configuration, in production CELERY_ALWAYS_EAGER=False and queue name is the same as in the command line.

I take care that each worker has its own name and queue but it seems not to solve the issue.

Thanks!

**Comment by ask** [comment]
They both use the same virtual host, so they share the same message bus.

If that is unwanted then use separate virtual hosts for the two instances:
`redis://localhost:6379/0`  & `redis://localhost:6379/1`

**Comment by marco-santamaria** [comment]
I have a similar setup with two different django projects (`app1` and `app2`) in two different virtualenvs on the same server.
Even if I use different names for the workers and different broker urls, when I run `celery events -A app1` I see listed workers and tasks for both the projects.

**Comment by triplegrr** [comment]
You can do something like this. I had this issue and it solved the problem for me.

```
# at the end of settings.py
project_name = "name_of_your_project"
from kombu import Exchange, Queue
CELERY_QUEUES = (
    Queue(
        project_name,
        Exchange(project_name),
        routing_key=project_name
    ),
)
```

You can then start your celry worker as such
`celery -A project_name worker -Q project_name`
This will ensure that each celery worker is only listening on the queue for each project. This should solve your problem

**Comment by rajagopalx** [comment]
If you are using rabbitmq as broker use the below:

1) Create VirtualHost

`sudo rabbitmqctl add_vhost our_app_vhost`

2) Add user / password pair

`sudo rabbitmqctl add_user username password`

3) Grant permissions to our user on our vhost:

`sudo rabbitmqctl set_permissions -p our_app_vhost username ".*" ".*" ".*"`

4) If you want to give our user access to management backend execute this command:

`sudo rabbitmqctl set_user_tags username management`

5) Now you can add BROKER_URL to your Django app settings:

`BROKER_URL = 'amqp://username:password@localhost:5672/our_app_vhost'`


Taken from https://timonweb.com/posts/run-multiple-django-apps-with-celery-on-one-server-with-rabbitmq-vhosts/
