### ISSUE TITLE
Support Redis + TLS URLs

### ISSUE THREAD

**Issue by dstufft** [celery/celery#2833]
redis-py supports redis instances which are secured by TLS by using `rediss://`URLs instead of `redis://` URLs. Celery should support this too.

**Comment by ask** [comment]
Does it not have an option for that? Or is this a special option that can only be set in the new url format?

**Comment by dstufft** [comment]
Celery doesn't know that rediss:// (note the two s) is a redis backend. See https://github.com/pypa/warehouse/blob/master/warehouse/celery.py

**Comment by ask** [comment]
Yeah, but we don't pass this URL to Redis, we need an option to set

**Comment by dstufft** [comment]
https://github.com/pypa/warehouse/blob/master/warehouse/celery.py#L38

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by lern** [comment]
Any plan to support the `rediss://` schema?

**Comment by thedrow** [comment]
Feel free to contribute it.

**Comment by smcoll** [comment]
How does this issue correspond to #3831?

**Comment by thedrow** [comment]
@smcoll Someone contributed SSL support for the redis result backend.
I can't recall if support was added to the broker as well.

**Comment by chriskuehl** [comment]
It should work fine, we're using SSL on the broker and the backend for Redis. Broker support has been around for a while (not sure when it was added), backend support for SSL was added in #3831. I think this ticket can be closed.

Here are the docs:
http://docs.celeryproject.org/en/latest/userguide/configuration.html

The relevant options are `redis_backend_use_ssl` and `broker_use_ssl` (which has a section on redis).

**Comment by dstufft** [comment]
Those options existed when I originally opened this issue, but this issue isn't about supporting TLS at all, it was specifically about supporting ``rediss://`` URLs to turn on the TLS support.

**Comment by chriskuehl** [comment]
The backend option definitely didn't exist when you opened the ticket (I added it in #3831 only a few months ago). But that's a good point, maybe the ticket should be re-opened.

**Comment by remeika** [comment]
I think this ticket should actually be broken out into two closely-related issues:

- Add Redis + TLS connections to broker_url setting (#4694)
- Add Redis + TLS connections to result_backend setting (#4695)

Celery processes the value of `result_backend` in its own code, and directly instantiates a redis connection from redis-py. But the value of `broker_url` is passed to Kombu, which also must be patched.

**Comment by gonzalodiaz** [comment]
+1 We need the fix from Kombu as well.

**Comment by thedrow** [comment]
Since @remeika has split the remaining tasks into issues and some of them are done I'm going to close this issue.
We can keep tracking the progress of this feature request in #4694.
