### ISSUE TITLE
Task priorities

### ISSUE THREAD

**Issue by malthe** [celery/celery#2835]
The documentation says that Celery [does not support task priorities](http://docs.celeryproject.org/en/master/faq.html#does-celery-support-task-priorities), but there is a ``priority`` argument that takes an integer 0-9.
```
        :keyword priority: The task priority, a number between 0 and 9.
                           Defaults to the :attr:`priority` attribute.
```

What gives?

Also, does Celery support queue priorities?

That is, if you say ``-Q hiprio,loprio`` does that mean that queue ``<hiprio>`` is looked at first?

The documentation is lacking.

**Comment by lexqt** [comment]
Moreover doc says:
> Does celery support task priorities?
> Answer: No. In theory, yes, as AMQP supports priorities. However RabbitMQ doesn’t implement them yet.

But as of version 3.5.0 ( https://www.rabbitmq.com/changelog.html ) RabbitMQ supports priority queues
https://www.rabbitmq.com/priority.html

**Comment by ask** [comment]
`hipri` is not looked at first, the messages are consumed in the order in which they were published when using RabbitMQ.

The idea of using priority queues like this is that you send high priority tasks to a dedicated queue, and you have more workers consuming from the high priority queue than low priority ones, or the machines consuming from the hipri queue is more powerful, or similar.
