### ISSUE TITLE
SIGTERM and Heroku

### ISSUE THREAD

**Issue by ryanhiebert** [celery/celery#2839]
When shutting down a Dyno, Heroku sends SIGTERM to _all_ processes on that Dyno. Unfortunately, Celery doesn't handle this well, because it uses SIGTERM internally to force the workers to shutdown.

In an IRC conversation with @ask, he said, to the confirmation of Heroku's behavior WRT SIGTERM:

> wow, thanks. that's horrible
> so then we need some way to redifine all SIGTERM usages related to child processes in the code to SIGQUIT and block sigterm, which is not exactly pretty

I'm not sure which branch this work should be done on, but I'm hoping that it can get into the 3.1 release branch, since 3.2 is very slow coming.

**Comment by ask** [comment]
With these billiard/celery patches you should be able to start the worker with:

    $ REMAP_SIGTERM=SIGQUIT celery -A proj worker -l info

**Comment by ryanhiebert** [comment]
@ask: Thank you so very much for this. It's going to make my life much easier. Looking forward to the next release!

**Comment by ryanhiebert** [comment]
It looks like this is in the master branch. Will it be backported to 3.1, or released in 3.2?

**Comment by hheimbuerger** [comment]
I'm also plagued by this and would love to see a backport into 3.1.

Or has anyone already found a well-tested fork with the patches?

**Comment by ryanhiebert** [comment]
I haven't. I believe this is 4.0 (master), which says it's in "beta", though I'm not sure if there's been a beta release yet, I haven't been keeping up. I've been meaning to give master a go and see if it's usable, but I haven't gotten around to it yet.

**Comment by hheimbuerger** [comment]
For me, there's no chance that I'm gonna upgrade to a 4.0 any time soon (unless it's a drop-in replacement, which is probably unlikely for something that has been worked on for so long). I just recently had way too many message queue issues (none of which were directly Celery's fault), so I need some peace and distance from this for a while and focus on core business. ;)

However, without these patches I can see me soon recovering Celery tasks every morning that got lost over night. That's not a very nice thought either, so then I might rather try to fork and backport.

**Comment by hheimbuerger** [comment]
@ask Am I right to assume that this wasn't part of the Celery 3.1.23 release earlier today? (It doesn't appear to be on the [3.3 branch of billiard](https://github.com/celery/billiard/commits/3.3).)

Would you generally be willing to accept pull requests for backports of these fixes into the billiard 3.3.x and the celery 3.1.x lines?

**Comment by dtran320** [comment]
@ryanhiebert @hheimbuerger What workaround did you guys end up coming up with for this? We're running `celery 3.1.23` on Heroku, and up until now, we've just been making sure our tasks are idempotent, but we recently implemented a feature that needs to set a marker in a S3 bucket, which gets really messed up when Hirefire sends `SIGTERM` to our workers, so this is a big blocker :(

**Comment by ryanhiebert** [comment]
For me personally, I've been being quite careful to not interrupt processes. It's a royal pain, and I'll be upgrading to Celery 4 as soon as I have the time to upgrade.

**Comment by hheimbuerger** [comment]
@dtran320 Yeah, I haven't fixed it yet either, sadly. :(

It's a real issue for me. My workaround is to have Papertrail report all terminated tasks into Slack immediately when they happen. Then I manually investigate each one of them and try to rerun the most essential lost operations manually. But that isn't always possible, so it still leads to degraded service for our customers occasionally... not to mention that it costs me quite some time on a daily basis to do this manual investigation.

I was always planning to backport this into Celery 3.1.x. But of course that's quite a challenge (probably not to do the actual backport, but I have no idea how to test it and how to get it right).
So on the side, I was hoping that Celery 4.x is getting ready in time. Then again, it appears that Celery 4.x might drop some features we're using, so I'm not sure I'll ever be able to upgrade...

**Comment by mkuchen** [comment]
👍  for handling the (bad) way Heroku handles SIGTERMing the sub-processes. I'm encountering this behavior on Celery 3.1.23 with Heroku, which is causing unexpected task failures. I have a lot of business logic running in the tasks that are getting terminated and it's causing lots of headaches for me.

**Comment by mkuchen** [comment]
cc @ask - if I upgrade to the latest Celery release (4.0.2) will that handle graceful shutdown if SIGTERM is sent to child processes? Thanks for all your feedback on this issue.

**Comment by ryanhiebert** [comment]
@mkuchen : In order for it to handle that gracefully, you'll need to set the `REMAP_SIGTERM=SIGQUIT` in your environment.

**Comment by ryanhiebert** [comment]
But yes, It's in Celery 4.

**Comment by hheimbuerger** [comment]
@mkuchen To clarify, you need to *both* upgrade to Celery 4.x *and then* set that environment variable!

**Comment by mkuchen** [comment]
@ryanhiebert @hheimbuerger that's great news. I'll venture to say a few other Celery users on Heroku will be happy about that too. Thanks guys.

**Comment by Chronial** [comment]
Nice work Heroku – was looking for a contact but found that it's already in [the article](https://devcenter.heroku.com/articles/celery-heroku#using-remap_sigterm). Maybe mention that this works only in celery ≥ 4?
