### ISSUE TITLE
Redis based scheduler

### ISSUE THREAD

**Issue by asmodehn** [celery/celery#2842]
The persistent scheduler, currently in celery (3.1) is quite limited.

Since celery now support redis by default, what would be needed to have a redis based scheduler available by default as well ?
This way we could dynamically modify the schedule, while beat is running, by simply editing redis content.

So something like that : https://github.com/asmodehn/celerybeatredis

If I could get some guidance about how to integrate this kind of feature in celery ( contrib ? ), I ll be happy to do it.

Or maybe there is something already in the works in another branch ?

**Comment by ask** [comment]
It would be great to have this, and also a way to store ETA/countdown tasks in Redis.

Looking at the Django-celery database scheduler and the mentioned celerybeatredis projects are probably good tips.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
