### ISSUE TITLE
Remove Legacy Python (python2) support

### ISSUE THREAD

**Issue by malinoff** [celery/celery#2849]
Note that this will also remove `Jython` and `Pypy` support until they do not support python3.3+

**Comment by thedrow** [comment]
If that's for 5.0.0 I'm +1 on this as long as PyPy catches up.
If it doesn't I think there's more value in keeping Python 2.7 support than harm.
For 4.x we'll have to keep 2.7.x support.

**Comment by malinoff** [comment]
Why? Anybody who wants py2 will be able to install celery 3.x

**Comment by thedrow** [comment]
Because PyPy provides too many advantages to forgo. That will mean that we'll have to abandon all those who have high performance requirements to use an unmaintained version of celery.

**Comment by malinoff** [comment]
I never said that 3.x should be completely abandoned. It's up to @ask whether should it be abandoned and unmaintained or not.
But from my perspective, it won't be that difficult to cherry-pick commits from 4.x branch into 3.x on demand.

**Comment by thedrow** [comment]
Even Django is not Python 3.x only.
This is milestoned as 5.0. I think that it will be the right time re-evaluate the situation.

**Comment by ask** [comment]
I moved the milestones after malinoff created this issue, so 3.2 is now 4.0, and 4.0 is now 5.0

**Comment by thedrow** [comment]
If it's two versions from now and PyPy catches up I'm +1. Almost nobody uses Jython these days so I'm not going to take it into much consideration.

**Comment by ask** [comment]
It's already announced in the whatsnew 4.0 document that Celery 5 will be Python 3.6+ only.

I imagine it will take some time to get there, and I want us to use typing, async/await and all the new great stuff.  Celery 4 will support Python 2 indefinitely.

**Comment by thedrow** [comment]
By the time we'll get to implementing Celery 5 I hope that PyPy will catch up.
PyPy3 has already released an alpha version of 3.3.

**Comment by auvipy** [comment]
I was thinking why celery 5's min requirement can be python 3.5?

**Comment by thedrow** [comment]
We'll have to see which PyPy version of Python 3 will be supported.

**Comment by auvipy** [comment]
pypy supports 3.5 now. after 4.2 release, if you agree I will start working on dropping 2.7 from master, and start working on v5 @thedrow

**Comment by auvipy** [comment]
yes 4.x series will be an LTS till jan 2020 :) and with python 2.7 support

**Comment by auvipy** [comment]
I will do it right after the release of 4.2 :1st_place_medal:
