### ISSUE TITLE
Fallback to synchronous if queue isn't available.

### ISSUE THREAD

**Issue by brianbister** [celery/celery#2855]
I looked through the docs and couldn't find any way to elegantly fallback to executing the code synchronously if the process attempts to connect to the queue and fails.  Right now a lot of my code looks something like this:

```
try:
  task_to_execute.delay()
except socket.error:
  task_to_execute()
```

Perhaps I'm going about this the wrong way but is it possible to pass in an additional flag to fallback to synchronous if no connection is made?  I've thought about adding a decorator to the call to do this behavior but there are some exceptions where I may or may not want to fallback.  Something like

```
task_to_execute.delay(fallback_sync=True)
``` 

would be ideal.  But if there are other alternatives that are already implemented that would work as wellm too.

**Comment by diwu1989** [comment]
this is pretty dangerous to have in a production system isn't it? the eager mode is more for testing and debugging, if you have a catastrophic queue failure on production, wouldn't you want to just let the error bubble up and hit your new relic?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
