### ISSUE TITLE
two celery beat instances generate duplicated tasks

### ISSUE THREAD

**Issue by feifangit** [celery/celery#2856]
I started two celery beat instances on two servers (for HA purpose).
These 2 instances were generating duplicated periodic tasks.

Any suggestion?

**Comment by drabaioli** [comment]
This is how celery beat works. The most popular solution is to launch only one instance. The less popular solution is to reiplement celery.beat.Scheduler such that multiple schedulers synchronize, and launch celery beat with the `-S` option.

**Comment by ask** [comment]
There are also some solutions for this on this issue tracker, look in the pull requests.  And there's some discussion on the mailing-list.
