### ISSUE TITLE
Task.retry() parameter max_retries is not honored in subsequent task execution attempts

### ISSUE THREAD

**Issue by paul-pearce** [celery/celery#2857]
I would expect the following task to run forever. 
```
@task(bind=True)
def add(self, x, y):
    raise self.retry(max_retries=self.max_retries+1)
```

Instead if finishes after the default max number of retries plus 1.

I believe the issue is here: https://github.com/celery/celery/blob/master/celery/app/task.py#L617. signature_from_request() generates a new signature taking into account request.retries (which is always increasing) but does not pass along the new max_retries value.

(Clearly the above example is not desirable behavior. It's a degenerate case of a bug I'm dealing with.)

**Comment by drabaioli** [comment]
Hi,

I would expect the code snippet you shared to retry exactly `self.max_retries+1`, where max_retries is the default value, unless explicitly set to a different value before the first execution of the task.

As the documentation states [here](https://github.com/celery/celery/blob/master/celery/app/task.py#L561) to have an infinite number of retries you have to set `max_retries` to `None`

**Comment by paul-pearce** [comment]
Hey @drabaioli,

My goal is not to create an infinite number of retries. I was just trying to show a degenerate example that exposes the behavior.

Specifically, I'm concerned that max_retries values are not being propagated. It seems like desirable behavior would be for all subsequent executions of the task should use the most recent max_retries value. Example (again, this is not a desirable practice, just trying to show the behavior):

```
@app.task(bind=True)
def add(self, x, y):
    if self.request.retries == 0:
        print "ping with changed max retries"
        raise self.retry(countdown=1, max_retries = self.max_retries + 10)
    else:
        print "ping"
        raise self.retry(countdown=1)

add.apply_async((1,2))
```

On the first execution max_retries is set to 12. On all other invocations the value is not specified. The net result is 4 pings ignoring the initial increase.

I raise this because In my pipeline there is a condition that triggers a task retry that should not count towards the maximum number of retries (external event that will pass shortly). There is currently no way to express this via retry().

Thanks.

**Comment by ask** [comment]
`max_retries` is local state, so the value will always be `self.max_retries` + 1.

You could do something like:

    @app.task(bind=True)
    def add(self, x, y, max_retries=1):
        raise self.retry(kwargs={'max_retries': max_retries + 1}, max_retries=max_retries + 1)

**Comment by paul-pearce** [comment]
Hmm. This is counterintuitive. I might suggest a documentation note specifying that this is local state. Happy to submit a pull request if you're open to the doc change.

**Comment by ask** [comment]
Yeah, would be nice if you submit a doc patch!
