### ISSUE TITLE
Batches does work within chord header.

### ISSUE THREAD

**Issue by bharris47** [celery/celery#2861]
#### Config
* broker = rabbitmq
* backend = memcached (multiple elasticache nodes)

I have a chord with 3 tasks in the header and a single task in the body. One of the tasks is a `Batches` task. All 3 tasks get executed and succeed, but the chord callback (body) never gets called. I have confirmed that the chord works as expected after converting the `Batches` task in the header to a simple `Task`.

Let me know what other info I can provide, but this should be pretty easily reproduced.

**Comment by bharris47** [comment]
Also, to publish results from the `Batches` task I am using the documented approach (`app.backend.mark_as_done(request.id, response)`)

**Comment by mes5k** [comment]
I see similar behavior in 4.0.0 rc1 without batches. See #2922.

**Comment by ask** [comment]
If you're on master (development) you should try using: `mark_as_done(request.id, response, request)` instead.

That won't help in 3.1 though

**Comment by ask** [comment]
Closing, this as this is fixed.  You need to store the result, but that is required for completing chords anyway.
