### ISSUE TITLE
use celery  with scrapy  producing unexpected log

### ISSUE THREAD

**Issue by night1008** [celery/celery#2876]
hello, I use  celery with scrapy , and I have already config the scrapy and celery log level, for example, --loglevel=error, but it always produce all the debug log to stdout or file, I look the source code, it come from the scrapy/scrapy/logformatter.py, it's not my want.Can you tell me what it happend?

**Comment by ask** [comment]
The worker will only configure the root logger, and the `celery.*` loggers.

I would guess scrapy is configuring their logger to be loglevel DEBUG, which is not a good convention for a library.

**Comment by night1008** [comment]
Thanks for your reply!
You are right. The unexpected log in scrapy is all DEBUG level.
I user the ```logging.Logger.manager.loggerDict```, print all loggers.
Before invoke scrapy spider, it logs once, but after that, it logs twice, also in spider.
```
@task.task(bind=True)
def run_spider(self, **custom_config):
    logging.error('===== before spider')  
    process = CrawlerProcess(setting)
    process.crawl(Spider)
    process.start()
    logging.error('===== after spider')    
```
As above code, it will print '===== before spider' once and '===== after spider' twice.

**Comment by ask** [comment]
Possibly scrapy is adding new handles to the root logger also, which would mean logs are printed twice if both handlers are set to STDOUT (celery redirects stdout to its own logger).

`CrawlerProcess` calls `scrapy.utils.log.configure_logging`:
https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L213

which then adds a handler to the root logger without checking that if a handler already exists:
https://github.com/scrapy/scrapy/blob/master/scrapy/utils/log.py#L98-L101

So you need to disable that `install_root_handler` somehow, but `CrawlerProcess` does not easily let you do that.

To me it looks as if the only option (apart from patching upstream) is to subclass `CrawlerProcess` and copy+paste the __init__ constructor:

    from scrapy import crawlers

    class CrawlerProcess(crawler.CrawlerProcess):

        def __init__(settings=None, install_root_handler=False):
            crawler.CrawlerRunner.__init__(self, settings)
            crawler.install_shutdown_handler(self._signal_shutdown)
            crawler.configure_logging(self.settings, install_root_handler=install_root_handler)
            crawler.log_scrapy_info(self.settings)

**Comment by David-Guillot** [comment]
@ask your explanation is very logical, and your solution seems fine, but it doesn't work for me (Celery 4.0.2, Scrapy 1.4.0). The constructor is called, it bypasses the original constructor correctly, but Celery console is still full of annoying Scrapy debug messages... Would anyone know what did i miss?
