### ISSUE TITLE
couchbase backend - transcoder

### ISSUE THREAD

**Issue by siniG** [celery/celery#2882]
Hi!
Currently CouchBaseBackend does not support settings a transcoder. When creating the the object, Couchbase Celery settings does not take into account any transcoder settings (e.g. custom transcoder settings). Furthermore, the Couchbase Python library used is an old version 1.x and not 2.x and thus settings keys/values does not work.
I suggest adding a configuration file property "transcoder" to set up the transcoder path in order to create an object.

**Comment by ask** [comment]
Could you write a patch for this, and open a pull request?

**Comment by siniG** [comment]
No problem, already have something written, but will do some more debugging, fork it and send it your way

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

If there's a pull request open related to this, I will get to it soon!
