### ISSUE TITLE
Starting celery with supervisord and --logfile option doesn't run scheduled tasks

### ISSUE THREAD

**Issue by bykof** [celery/celery#2886]
If I start celery with 
```
exec celery worker --beat -E --schedule=/var/www/application/run/celerybeat-schedule -A src --logfile=/var/www/application/logs/celery.log
```
the worker is running and everything works fine unless the scheduled tasks I defined in CELERYBEAT_SCHEDULE.

but if I remove the logfile option and run:
```
exec celery worker --beat -E --schedule=/var/www/application/run/celerybeat-schedule -A src
```
the scheduled tasks start working. 

I couldn't believe that the logfile option produces an error but I tried it many times and the error confirms. 

Can you explain why?

**Comment by bykof** [comment]
I have to add that I made all settings like your instructions on the website.
Also I use the latest celery with redis broker and result backend

**Comment by ask** [comment]
Try running the worker command as the target user, maybe? outside of supervisord.

Could be a permission problem, but you could also try starting `celery worker` and `celery beat` separately.

**Comment by bykof** [comment]
If I try to run them seperately it works. But this is not how I want my system to run... because of provisioning restrictions. Thank you for your help I will just let the logfile option out and be happy :)
