### ISSUE TITLE
Documentation is CC-BY-NC-SA-3.0, not fit for inclusion in Debian

### ISSUE THREAD

**Issue by fladi** [celery/celery#2890]
I have been informed ([Debian Bug #803117](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803117)) that the documentation included in the source tarball of celery can not be included in the Debian package archive. This is because the license used (CC-BY-NC-SA-3.0) is not compatible with the Debian Free Software Guidelines (DFSG). The problem is caused by this clause:

**"You may not use this work for commercial purposes."**

As it stands right now, I will have to drop the whole documentation from the Debian package which I consider to be less than favorable. Is there any chance that the documentation could be distributed under a more free license? If you need help in choosing a different license, there is a list of [DFSG-compatible](https://wiki.debian.org/DFSGLicenses#The_Big_DFSG-compatible_Licenses) licenses.

**Comment by thedrow** [comment]
I think that the intention is to disallow selling the documentation or some other method of monetizing it (e.g. creating a site that adds advertisements).
We'll have to consider how to do this.

**Comment by fladi** [comment]
I can understand that, but this would still be in violation of the [DFSG](https://www.debian.org/social_contract), section 6:

> No Discrimination Against Fields of Endeavor
>
>The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

I'll wait for a few days to see what what can be done about this before dropping the documentation from the Debian package.

**Comment by ask** [comment]
Thanks for reporting this!

What @thedrow says was the original intention, including the fear of an employer taking the work in which case I would at least have the documentation, but I didn't really consider that Debian wouldn't be able to distribute it.

I changed the license to CC-BY-SA 4.0, which seemed to be the least confusing of them.
The changes were applied to the master, and 3.1 branches, but I'm not sure how they would take effect for Debian, do I need to do a release?

If someone would chose to publish the work in an online bookstore or similar to earn a few pennies, then they should already feel bad.  At least I hope :)

**Comment by jvanasco** [comment]
IMHO you should drop the docs and keep the old license.  Put in a placeholder linking people to the "non-commercial use" documentation.  Anyone who needs the docs can easily get them online or they can be offered as part of the non-free / contrib repositories.

The bigger problem with Debian's policy isn't that it allows for monetized mirrors -- but that you end up with a bunch of shady publishers selling "The ____ book", which is 30 pages of text written by a tech writer followed by 300 pages of the docs printed out verbatim (see most o'reilley and wiley books).

**Comment by fladi** [comment]
@ask Thanks for this quick and simple solution. A new release (i.e. 3.1.20) would be the easiest way to get this change into the Debian package.

@jvanasco Just linking to some online resource, even if it is the official documentation is not encouraged as it makes people dependent on this service and its implications (e.g. hosting availability, privacy, ...). This would open up a whole other can of worms with the DFSG ...

**Comment by malinoff** [comment]
I honestly don't get the idea of packaging frameworks into system-wide repositories. As release engineer (devops) I would never accept deployment based on celery (or, for example, django) installed system-wide.

**Comment by fladi** [comment]
@malinoff FYI: [Outsourcing your webapp maintenance to Debian](https://feeding.cloud.geek.nz/posts/outsourcing-webapp-maintenance-to-debian/)

Just because you would not use it does not mean that there are no use-cases for system-wide packages. But this is already derailing this issue. Closing it as @ask already solved it by switching to a different license. Thanks again!

**Comment by brianmay** [comment]
Hello,

There is a mistake in the new documentation. docs/copyright.rst has:

> All rights reserved.  This material may be copied or distributed only
subject to the terms and conditions set forth in the
> `Creative Commons Attribution-ShareAlike 4.0 International`
<http://creativecommons.org/licenses/by-nc-sa/3.0/us/>`_ license.

i.e. it refers to version 4 of the license, but the link is for version 3 of the license.

Please fix.

Thanks

**Comment by brianmay** [comment]
I believe the correct link is https://creativecommons.org/licenses/by-sa/4.0/legalcode
