### ISSUE TITLE
Celery is not taking the locale from environment

### ISSUE THREAD

**Issue by alculquicondor** [celery/celery#2893]
I'm having troubles with simple things like calling `open(filename)` where filename is a unicode string with non-ascii characters.

This task returns `(None, None)`

```python
import locale
@task(name='dummy')
def dummy():
    return locale.getdefaultlocale()
```

This is `locale` output:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

The output from `manage.py celeryd --version` is:

```
1.6.11
celery 3.1.7
django-celery 3.1.1
```

Python version is `2.7.3`

I can't easily update celery on my current situation. Is it possible that I'm missing a configuration parameter or I need to set some environment variable manually? In the later case, where should I do that? I'm running celeryd with supervisor. Setting LANG in environment configuration appears to not have any effect.

**Comment by ask** [comment]
Running `LANG=en_US.UTF-8 celery -A proj worker -l info`, works with that task here.

Not sure I can see any changes since that version that would effect this though.

**Comment by alculquicondor** [comment]
Thank you, it worked.

I was using `celeryd` before, but I'm not sure if that was the issue. The weird thing is that in my developing machine I don't need to set up the environment variable and it works.
