### ISSUE TITLE
chunks and queue

### ISSUE THREAD

**Issue by karpitsky** [celery/celery#2899]
I tried to apply queue to chunks, but it looks like it isn't working.

Task:
```
@celery.task
def new_task(value):
    print value
```

Config:
```
celery worker --app=my_app --loglevel=INFO -Q update
```

Execute:
```
new_task.chunks([(1,), (2,)], 1).apply_async(queue="update")
```
Two tasks are executed in default queue

Simple task routing works correctly:
```
new_task.s(1).apply_async(queue="update")
```

**Comment by ask** [comment]
Passing queue argument to groups will be supported in 4.0 (and is in master), but for previous versions
you have to set it for each task:

    chunks = new_task_chunks([(1,), (2,)], 1).group()
    [t.set(queue='update') for t in chunks.tasks]
    chunks.apply_async()
