### ISSUE TITLE
RPC backend auto_delete=True not in 3.1.19

### ISSUE THREAD

**Issue by Hexadite-Max** [celery/celery#2902]
The fix for https://github.com/celery/celery/issues/2001 was merged into master but is not under 3.1.* although introduced over a year ago

**Comment by ask** [comment]
It's possibly backwards incompatible, so will be released with 4.0

**Comment by Hexadite-Max** [comment]
I have been playing with RPC queues, using the auto_delete, does indeed have some unexpected results - as soon as any `AsyncResult` uses `get()` this will cause the queue to get deleted, as this will be the only consumer at the moment, so workers won't be able to post results. On the other hand using the `state` and `result` properties of `AsyncResult` won't actually trigger auto_delete as they don't create a consumer and access the queue directly.
So it seems to me that the two options to cleanup RPC client queues:
- don't use auto_delete and call `delete()` on the queue on process shutdown/exit
- use auto_delete, and run a watching thread to consume all results, this way on process exit the queue will get auto deleted

I am now working on the second option, let me know if it's of interest.

**Comment by ewang** [comment]
@ask The fix for this seems to just set expiration on the queue. If the worker process never quits, then doesn't the queue never get deleted and messages will simply pile up?
