### ISSUE TITLE
Need to separate my web and worker to different repos but celery seems to be the blocker

### ISSUE THREAD

**Issue by mwaaas** [celery/celery#2909]
I need to separate my app stack to have web and worker as separate micro service i.e they both run in different infrastructure and both have different repository .

The blocker am getting is how am adding message into the queue i.e task.add.delay(a,b)    this means the task add should be in web , I can easily  replace the way am pushing messages to rabbitmqp by using pika python package but then I will loose other functionality such as chain  i.e chain = add(a,b) | send_result() ; chain()

Is there a way of pushing messages to rabbitmq with celery without having the task defined on the code

**Comment by malinoff** [comment]
@mwaaas yes, take a look at [send_task](https://github.com/celery/celery/blob/v3.1.19/celery/app/base.py#L332-L361) method.

**Comment by mwaaas** [comment]
@malinoff  how do I use chain with the send_task method

like how would I do this 
    chain = task.add() | send_result()
    chain()

**Comment by malinoff** [comment]
@mwaaas at that point, I'd suggest to make "stubs" of your tasks, i.e.
```python
@app.task
def add(x, y):
    pass

@app.task
def send_result(result):
    pass
```
So basically such stubs won't do anything useful, but provide you a way to not mess with celery internals and call your tasks as usual.

**Comment by ami-fairfly** [comment]
we're using Signature and it works perfectly 
docs.celeryproject.org/en/latest/reference/celery.html#celery.signature
