### ISSUE TITLE
chord unlock hangs/link_error not called on SIGTERM

### ISSUE THREAD

**Issue by gorlins** [celery/celery#2911]
Using rabbitmq/redis backend with prefork pool, I'm finding that link_error callbacks and any chord unlocking will not be called when a task dies with SystemExit or receives SIGKILL/SIGTERM.  In my production systems I am experiencing frequent chord unlock hangs related to the OOM killer and I am attempting to recreate the problem here.

An example problem:

```
@shared_task(bind=True)
def debug_task(self, *args, **kwargs):
    """Simple debugging task. Just prints info about the request."""
    print 'Request: {0!r}'.format(self.request), args, kwargs
    return True

@shared_task(bind=True, acks_late=True)
def debug_kill(self, soft=True, sig=None):
    """Kills this process

    :param bool soft: if ```sig``` is not provided, will kill with ```SIGTERM```
        (otherwise uses ```SIGKILL```)

    :param int sig: directly specify the signal to use

    """
    try:
        print 'Killing from', self.request
        if sig is None:
            if soft:
                sig = signal.SIGTERM
            else:
                sig = signal.SIGKILL

        os.kill(os.getpid(), sig)

    finally:
        print 'well that was no fun'

# Here, the child correctly dies but callback is never executed, worker remains alive
s = debug_kill.s(soft=False); s.link_error(debug_task.s()); r = s.delay()  

```

Similarly, a chord result on killed tasks will hang, despite ```chord_result.parent.ready()==True```.  However, if I create a 'manual chord' using a group result polling technique as mocked out in the docs where it discusses other result backends and chord behavior, the chord works since the group result is 'ready'.

I can 'fix' the problem if the task is retried or alters the exception:

```
class ExceptAllTask(Task):

    def __call__(self, *args, **kwargs):
        try:
            return super(ExceptAllTask, self).__call__(*args, **kwargs)
        except SystemExit:

            print 'handling SystemExit'
            self.retry(args=args, kwargs=kwargs, max_retries=5, throw=False)
            os.kill(os.getpid(), signal.SIGINT)  # Not sure if this does anything, but I can't reraise

@shared_task(bind=True, acks_late=True, base=ExceptAllTask)
def debug_kill(...):
    # In production, I do some deduplication here and can return the previous task result (which is an exception)
    ...

c = chord([
    debug_kill.s(soft=True), 
    debug_kill.s(soft=False), 
    debug_task.subtask(args=('inside chord',), acks_late=True)], 
    debug_task.s()); 
c.link_error(debug_task.s('chord unlocked after failure')); 
cr = c.delay()  # all executed immediately, but error callback returns 3 minutes later
```

The last case inserts a 3 minute delay between the failure and callback, which I cannot account for but I assume is related to some timeout setting in rabbit/redis, and allows for chords to be unlocked.  In production, my tasks go through a deduplication step since they are not idempotent, but testing this seems to work to trigger link_error and unlock the chord.  I am not, however, successful at using this technique on a singular task to ensure that link_error is called.

Is this behavior a feature or a bug?  Is there another recommended way, other than excepting SystemExit, to ensure that error callbacks are handled in every case?  If I have ```CELERYD_MAX_TASKS_PER_CHILD=1``` is there a risk to ignoring a system shutdown request in the child?

```
$ ./python manage.py celery report

software -> celery:3.1.18 (Cipater) kombu:3.0.28 py:2.7.10 billiard:3.3.0.20 librabbitmq:1.6.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:redis
```

**Comment by ask** [comment]
This was fixed in the development version!

**Comment by gorlins** [comment]
thanks @ask, can you point me to a commit/doc/other issue if this is a dupe?  anything i can use before the next release that is better than the hack above?

**Comment by ask** [comment]
e6fb53488e017ce3b4bd9aab1437b0ea1c2ef9fc I believe
