### ISSUE TITLE
crontab(hour=3) in CELERYBEAT_SCHEDULE is not Pythonic

### ISSUE THREAD

**Issue by hakanw** [celery/celery#2912]
I woke up to an avalanche of errors in my production environment after switching from

`timedelta(hour=24)` for something running once every day, to: `crontab(hour=3)`

It turned out, of course, that it started a job _every minute_ at 3 am. I would argue that this is unexpected behavior from a Python standpoint, where you are used to default parameters set to zero, for example:

`datetime.timedelta(hours=3)` is the same as `datetime.timedelta(hours=3, minutes=0, seconds=0)`. It is the same in other situations where you specify time in other parts of the stdlib.

I know the reason for this is probably that it is inherited from Linux crontab behaviour, and that the default value there is "*", but I don't think it is very pythonic in this situation (given the argument and example above) and thus that the default value for the `minute` argument in `crontab` should be set to `0`.

**Comment by ask** [comment]
I agree, but I didn't write it and It will be incredibly difficult to solve in a backward compatible manner

**Comment by hakanw** [comment]
@ask what about a warning of deprecation or ambiguity, and then in another major version you change so the default parameter if it's not provided is 0?

**Comment by mverrilli** [comment]
`crontab` functionality seems well known by anyone who uses unix, and while it isn't pythonic, it is cronish (leaving aside the unnecessary breakage from the change).  I'd rather see a new class added than to change `crontab` itself.  Just my 2 cents.

**Comment by ask** [comment]
Some ambiguity about consistency here with the values of `day_of_week`, `day_of_month` and `month_of_year`, as I'm guessing we don't want these to default to 0.

**Comment by PMickael** [comment]
An other solution will be to only have 1 arg
```python
crontab_unix(`0 * * * * *`)
```
```
* * * * * *
| | | | | | 
| | | | | +-- Year              (range: 1900-3000)
| | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
| | | +------ Month of the Year (range: 1-12)
| | +-------- Day of the Month  (range: 1-31)
| +---------- Hour              (range: 0-23)
+------------ Minute            (range: 0-59)
```

**Comment by georgepsarakis** [comment]
@hakanw the enhancement applies only for the `minute` argument. I guess you could something like:

```
class hour_crontab(crontab):
        def __init__(self, hour='*', **kwargs):
            kwargs['minute'] = 0
            super(hour_crontab, self).__init__(**kwargs)
```
