### ISSUE TITLE
Recover tasks after workers exited prematurely......

### ISSUE THREAD

**Issue by Reamon** [celery/celery#2921]
I am using spot instance servers and I understand why my workers exited prematurely after the servers automatically shutdown,.. What I cannot understand is that, When the spot servers started again, I already lost the tasks. carried by my workers before.. Is there any way to recover the tasks???? Thanks.

**Comment by Reamon** [comment]
Is there anybody could give some idea about this?

**Comment by ask** [comment]
In the 4.0 development version you can use http://docs.celeryproject.org/en/master/configuration.html#task-reject-on-worker-lost in combination with acks_late.

I would recommend not killing the child worker processes, though...

**Comment by Reamon** [comment]
I will try. Thanks!

**Comment by fuhrysteve** [comment]
update link http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-reject-on-worker-lost

**Comment by RangerWolf** [comment]
> 

hello， does it work? I tried `task-reject-on-worker-lost=True` with Celery 5.2.3 and seems it won't work~
