### ISSUE TITLE
Results are never acknowledged if querying task state before getting result

### ISSUE THREAD

**Issue by arnauorriols** [celery/celery#2924]
In AMQP/Rpc backends, due to the following 2 facts:
* Task meta is cached once it is received
* get_task_meta polls the queue with no_ack=False

In a use flow where first the task state is queried and only once the task state is SUCCESS, the result is fetched with AsyncResult.get(), result messages are never removed from the queue (nor queues are ever auto_deleted in the case of AMQP backend). The following snippet illustrates this use case:
```python
async_result = my_task.apply_async()
while async_result.status != 'SUCCESS':
    print "Task not finished, go take a nap'
# Here all the task meta, including result, has been cached, although the message 
# has been queried with a basic.get without being acked nor auto-deleting the queue.
result = async_result.get()  # From cache, won't consume queue nor ack the message
```

**Comment by timeu** [comment]
I think I ran into the same issue.
in my case I have two chained tasks and if the parent task crashes and I query the state of either the parent or the child task state stays `PENDING` and in the rabbitmq broker I have one non ackowledged message. 

```
chain = (task1.si() | task2.si())()
chain.state and chain.parent.state  #  always return `PENDING` 
chain.get()  # hang forever
```

It only works if I call `get` before querying the `state` 

```
chain.get()
chain.state # returns PENDING
chain.parent.state # return 'FAILURE'
```

**Comment by ask** [comment]
@timeu: Your hanging case works for me in master now with the RPC backend.
