### ISSUE TITLE
When using solo pool, prefetch_count is computed with the concurrency setting (even though this setting is redundant) 

### ISSUE THREAD

**Issue by arnauorriols** [celery/celery#2925]
I've noticed that when using the solo pool, the prefetch_count of the AMQP channel is still computed using the concurrency slots configured with the option --concurrency, although this option is redundant for this kind of pool, and one might incorrectly assume it defaults to 1. 

Is this intended, or it is a bug?

**Comment by thedrow** [comment]
You can specify the prefetch multiplier normally. Is there another behaviour you'd expect?

**Comment by arnauorriols** [comment]
My apologies for the lack of clarity of the first post. Multiple rewritings made it quite unexplanatory. 

What I meant, is that given that the prefetch_count is computed as ```CELERY_PREFETCH_MULTIPLIER * concurrency-slots```, under the scenario of a worker configured with ```CELERY_PREFETCH_MULTIPLIER = N```, when using the pool 'solo', I would expect ```concurrency-slots``` to always be 1, independently of the value of the --concurrency option of the worker command, and as such the prefetch count would equal ```N```. 

Turns out my assumptions weren't true, even with the pool 'solo' the ```concurrency-slots``` variable is coupled to the --concurrency command option, which defaults to the number of CPUs of the machine. So, in a machine with 4 CPUs, launching a worker with CELERY_PREFETCH_MULTIPLIER = 1 like this:

    $ celery worker -A app -P solo

Will set the consumer with a global prefetch count of 4, although the de-facto concurrency of the worker is 1 process. Furthermore, if I launch the worker like this:

    $ celery worker -A app -P solo -c 1

The global prefetch count will be 1, which is what I would expect even without using the -c option.

**Comment by thedrow** [comment]
Yes, this is a bug.
