### ISSUE TITLE
Ensuring a task is only executed one at a time - bug

### ISSUE THREAD

**Issue by EQato** [celery/celery#2926]
During the execution of the code from the celery cookbook in this link: http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#cookbook-task-serial I encountered the same problem that locking actually should resolve. If the task would last more than the timeout then it will delete the lock for another task that might be running. This will happen if we are using the lock in a periodic task. 
I resolved it in this way: 

    from datetime import datetime, timedelta 
    @task(bind=True)
    def import_feed(self, feed_url):
    # The cache key consists of the task name and the MD5 digest
    # of the feed URL.
    feed_url_hexdigest = md5(feed_url).hexdigest()

    lock_id = '{0}-lock-{1}'.format(self.name, feed_url_hexdigest)

    # cache.add fails if the key already exists
    acquire_lock = lambda: cache.add(lock_id, 'true', LOCK_EXPIRE)
    # memcache delete is very slow, but we have to use it to take
    # advantage of using add() for atomic locking
    release_lock = lambda: cache.delete(lock_id)
    time = datetime.now() + timedelta(seconds=timeout)

    logger.debug('Importing feed: %s', feed_url)
    if acquire_lock():
        try:
            feed = Feed.objects.import_feed(feed_url)
        finally:
            if time >= datetime.now()
                   release_lock()
        return feed.url

    logger.debug(
        'Feed %s is already being imported by another worker', feed_url)

**Comment by ask** [comment]
Thanks, I think the only safe way here is to not exceed the timeout.

You could do something like `if cache.get() == me: delete.lock()` to ensure you are only releasing
your own lock, but those two operations would need to be atomic for that to work reliably and there's
no way to do that in memcached that I know of.

This is used in a network so wall clock time is unreliable (the clocks on the machine setting the lock, and the clock on the memcached machine are different).  I subtracted 3 seconds from the timeout to lave some room, but that is not exactly a perfect fix.
