### ISSUE TITLE
Celery prefork memory leak

### ISSUE THREAD

**Issue by ami-fairfly** [celery/celery#2927]
We are running Celery with Django using the following command:
python manage.py celery worker -Q some_queue -l INFO -n some_worker —concurrency=1 

The flow is as such - (assume `CELERYD_MAX_TASKS_PER_CHILD = 1`):
1. When running celery, a master process is spawned (about 60MB RAM)
2. Child process is immediately forked from it (also 60MB)
3. Master process pulls a task from the queue and hands it over to the child
3. The child process finishes handling a task and is terminated by the master process and it's memory is freed
4. Master process now pulls another task from the queue and it's memory increases to 72MB
5. Child process is forked from the master queue (also 72MB)

...and so on and so forth.

So in fact, the master process is never restarted, only the children do. But every message it takes increases it's memory usage and thus after a while we run out of memory.

We have tried the following settings to no avail:
`CELERYD_PREFETCH_MULTIPLIER = 1`
`CELERY_ACKS_LATE = True`
`CELERYD_MAX_TASKS_PER_CHILD = 1`
`-Ofair`

**Comment by ami-fairfly** [comment]
Also happens when running with `-P solo`, only on the same master process. memory usage increases infinitely

**Comment by ask** [comment]
What broker transport is this?

**Comment by czpython** [comment]
I'm experiencing the same issues with rabbitmq as a broker and redis as result storage.

**Comment by ami-fairfly** [comment]
@ask RabbitMQ as backend storage. No result storage.Using pyamqp.

**Comment by ami-fairfly** [comment]
Tried it with librabbitmq, same effect. The main process' memory keeps inflating even with restarting children. Attaching images that I hope will help of the memory growth over time and the process distribution in htop

![screen shot 2015-11-26 at 11 03 42 am](https://cloud.githubusercontent.com/assets/11014714/11419044/95ada4c4-942d-11e5-8eae-000fa34282cc.png)
![screen shot 2015-11-26 at 11 05 01 am](https://cloud.githubusercontent.com/assets/11014714/11419045/95afcfd8-942d-11e5-80b4-eff69d684553.png)

**Comment by ask** [comment]
I need more information about configuration used as neither -P solo or prefork leaks for me here.

**Comment by eldar-fairfly** [comment]
@ask (I'm working on the same issue with @ami-fairfly), 
which extra configuration would you like to know?
```celery (3.1.18), djnago-celery (3.1.16)```

**Comment by ami-fairfly** [comment]
which extra configuration would you like to know?
celery (3.1.18), djnago-celery (3.1.16)

**Comment by ask** [comment]
Any Celery configuration options used, including arguments when starting the worker

**Comment by ami-fairfly** [comment]
Sure thing, here we go.

This is the celeryconfig.py:
```
CELERYD_HIJACK_ROOT_LOGGER = False

BROKER_URL = settings.RABBIT_URL

BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600 * 24}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_IGNORE_RESULT = True

# Setup queues:
CELERY_QUEUES = (Queue("existing"),
                 Queue("new"),
                 Queue("mailing"))

CELERY_DEFAULT_EXCHANGE = 'fairfly'
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERY_MESSAGE_COMPRESSION = "gzip"

# Worker directory:
CELERY_IMPORTS = (
    "dashboard.tasks",
    "user_center.tasks",
    "queue_tasks.tasks.search_tasks",
)

CELERY_ALWAYS_EAGER = False

CELERYD_POOL_RESTARTS = True
CELERYD_MAX_TASKS_PER_CHILD = 10
```

This is how we run the worker:
`python manage.py celery worker -Q result_processing -l INFO -n result_processor.%n --concurrency=2`

As mentioned above, we have tried playing around with the different settings but to no avail.

Please let me know if I can provide any more information

**Comment by ami-fairfly** [comment]
One more thing worth mentioning is that the result processing task handles a pretty large JSON - around 2MB, although gzipped it is only 60kb-ish. Not sure if that has anything to do with it.

**Comment by eldar-fairfly** [comment]
+1

**Comment by noam-fairfly** [comment]
+1

**Comment by ami-fairfly** [comment]
@ask thoughts?

**Comment by ask** [comment]
I was running with the bigdata stress test here, which sends thousands of tasks at 60MB each. The compression part could be relevant as that is something I did not enable

**Comment by ami-fairfly** [comment]
@ask  Interesting. We tried both GZIP and BZIP2 and they both cause this.

**Comment by ami-fairfly** [comment]
@ask could you please share your configuration and the bigdata stress test?

**Comment by ask** [comment]
@ami-fairfly The stress test suite is here: https://github.com/celery/celery/tree/master/funtests/stress

I think it contains enough information to get running.  For testing with 3.1 you will have to `git checkout 3.1` first.

I ran it with the default configuration and:

   celery -A stress worker --maxtasksperchild=10 -b pyamqp://

**Comment by ask** [comment]
You are missing the configuration where compression is not enabled at all, btw!

**Comment by ami-fairfly** [comment]
@ask Thanks! Will try it out.

So you think it might be the compression?

**Comment by ami-fairfly** [comment]
@ask I have tried running the stress tests and even put load on the memory by creating big objects. No leak.

Is there a difference between running `python manage.py celery worker` and `celery -A ....`?

**Comment by ask** [comment]
@ami-fairfly: There is definitely a difference, the first one loads Django earlier, and may set up things that the latter won't.

Are you 100% sure `settings.DEBUG` is not enabled?

**Comment by ami-fairfly** [comment]
@ask Thank you for the help! Its definitely not something to take for granted.

I just double checked and `DEBUG` is `False`.
So the Celery stress test is not leaking but Celery + Django is leaking. 
Running our code outside of celery is not leaking. 

I'm not sure how to proceed from here. Our workers are dropping like flies :)

We thought about creating a child process for the task and then killing it but Celery does not allow that.

**Comment by ask** [comment]
I'm pretty sure I managed to reproduce this on Linux.

Memory would grow quite quickly with processes exiting, but I didn't see it grow unbounded (I couldn't get the machine to run out of memory).

Definitely looks like the same problem, and the above fix should fix it, but if not, please do report back :)

I'm guessing it didn't reproduce on OS X because of the memory compression enabled there.

**Comment by ami-fairfly** [comment]
@ask awesome! We'll check it out, thanks!

**Comment by ananyashandilya1102** [comment]
@ask Can you confirm the version of celery in which this memory leak issue has been fixed?

**Comment by auvipy** [comment]
can you check v4.2rc4 or 4.1.1?

**Comment by sivang** [comment]
also experiencing similar, is there a fix release / workaround for that?
