### ISSUE TITLE
Weird lines in celery/extra/systemd/celery.conf

### ISSUE THREAD

**Issue by dAnjou** [celery/celery#2931]
Hi,

I'm talking about these two in https://github.com/celery/celery/blob/v3.1.19/extra/systemd/celery.conf:
```
d /run/celery 0755 user users -
d /var/log/celery 0755 user users -
```
There's no comment that explains what they do and it's really hard to find something with only the information given. People in `#systemd` helped me figuring it out. Apparently [`d` is a *type* for *tmpfiles.d*](http://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#d). But `celery.conf` doesn't seem to be a *tmpfile*(?)

So, what's happening here?

@Anarchist666 Sorry to bother you directly but you put those lines in there.

**Comment by Anarchist666** [comment]
Yes, celery.conf is config for tmpfiles.d from /usr/lib/tmpfiles.d/ directory.

In the original commit https://github.com/celery/celery/commit/630c8fbbcc67ee805536363be6e3a58af54e2d2f /etc/conf.d/celery, /usr/lib/tmpfiles.d/celery.conf and /usr/lib/systemd/system/celery.service

I don't know why the files celery and celery.conf were merged.

19.11.2015, 23:31, "Max Ludwig" <notifications@github.com>:

**Comment by Anarchist666** [comment]
In the commit https://github.com/celery/celery/commit/0314421e26a39d122e550e1a42704da879fbdce3 file celery was renamed to celery.conf and merged with existing celery.conf.

**Comment by dAnjou** [comment]
@Anarchist666 All that still doesn't explain what these lines are for or what they do.

**Comment by ask** [comment]
The doc you point to suggests `d` creates a directory if it doesn't exist, `d path mode userid groupid age` ?

The age parameter is defined as:

<pre>
The date field, when set, is used to decide what files to delete when cleaning. If a file or directory is older than the current time minus the age field, it is deleted. The field format is a series of integers each followed by one of the following suffixes for the respective time units: s, m or min, h, d, w, ms, and us, meaning seconds, minutes, hours, days, weeks, milliseconds, and microseconds, respectively. Full names of the time units can be used too.

If multiple integers and units are specified, the time values are summed. If an integer is given without a unit, s is assumed.

When the age is set to zero, the files are cleaned unconditionally.

The age field only applies to lines starting with d, D, v, q, Q, C, x and X. If omitted or set to "-", no automatic clean-up is done.

If the age field starts with a tilde character "~", the clean-up is only applied to files and directories one level inside the directory specified, but not the files and directories immediately inside it.
</pre>

Possibly it's a shortcut used by some init scripts, and I would guess most init scripts starts as a copy+paste job from another ;)

**Comment by dAnjou** [comment]
Sorry, I phrased that poorly. I read of course the page that I linked.

I guess the overall issue that I have with these two lines is that I don't know why they're in that file. It's also confusing that it says `/etc/conf.d/celery` in `celery.service` while the file is actually called `celery.conf`. I doubt that this works, but even if it works it's at least irritating.

I'm trying to say that this folder could use a README file explaining how to use the files. Or at least some comments. I would write this myself but I still have no idea why these lines are needed.

**Comment by Anarchist666** [comment]
Old README file that existed at the same time included explanations. But he also was removed.
These lines are needed for create folders for LOG and PID files for celery if they not exist. 
Is not it obvious? Read systemd and celery documentation. Again these lines in the file should not be. They're not located due to my commits.

**Comment by dAnjou** [comment]
Ok, so there have been some misunderstandings even on @ask's side who moved things around without realizing what they are actually for. This *non*-obvious it is.

In the very near future I will daemonize Celery workers on our Debian Jessie servers and I will try to update these files and [the documentation](http://docs.celeryproject.org/en/stable/tutorials/daemonizing.html#usage-systemd) if that's alright.

**Comment by Anarchist666** [comment]
Oh, I thought it was removed. If updating these files and documentation makes them better, it is a good idea. Maintainer the distribution that i use did so: https://projects.archlinux.org/svntogit/community.git/tree/trunk/celery.tmpfiles.d?h=packages/python-celery . Perhaps it would be useful
