### ISSUE TITLE
Sphix dont create documantation of tasks

### ISSUE THREAD

**Issue by arleincho** [celery/celery#2932]
Hi everyone.

i have project running with Tornado and some tasks with celery.
today i'm trying to generate doc with sphinx, but, the tasks of celery module not listed into documentation files.

i'm putting in config.py the extension of celery for sphinx, but nevertheless not is generated the doc...

can you help me?

tasks.py
```python
@app.task(ignore_restult=True)
def ftpDeleteDir(directoryDelete, config):

    try:
        logger.info('inicia el ftp en %s' % config['host'])
        ftp = FTP(config['host'])
        logger.info('instlancia el ftp')
        ftp.login(config['user'], config['pass'])
        logger.info('se loguea al %s con user:%s and pass: %s' % (ftp, config['user'], config['pass']))

        try:
            ftp.rmd(directoryDelete)
            logger.info("Elimina el directorio: %s" % (directoryDelete))
        except Exception, e:
            logger.error("Error Eliminando SFTP: %s" % e)
            pass

        ftp.close()
    except Exception, e:
        logger.error("Error conectando SFTP: %s" % e)
        pass
```

---
conf.py
```python
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'celery.contrib.sphinx'
]
```

**Comment by ask** [comment]
It works here, what's the contents of the .rst file for this tasks module?

**Comment by SheepGotoHeaven** [comment]
I've encountered a similar issue with a Flask application running Celery.
My own .rst file, for reference:

```
ygg.local package
=================

Submodules
----------

ygg.local.analysisengine module
-------------------------------

.. automodule:: ygg.local.analysisengine
    :members:
    :undoc-members:
    :show-inheritance:
```
    
Hope this helps

**Comment by SheepGotoHeaven** [comment]
Ah, I didn't have celery.contrib.sphinx. Removing my comments from this thread as they're irrelevant cruft. Sorry to bother you, @ask

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
