### ISSUE TITLE
Search on docs.celeryproject.org disabled?

### ISSUE THREAD

**Issue by WoLpH** [celery/celery#2933]
For some reason the search on http://docs.celeryproject.org/ is disabled while http://celery.readthedocs.org/ does have search. Since the Python docs search is executed clientside it shouldn't introduce any extra serverload so I'm wondering if this was an explicit decision or whether it's just an incorrect flag or something :)

Since docs.celeryproject.org is the default search result in Google, it would be useful ;)

**Comment by ask** [comment]
It works for me here now, maybe it was some build problem or something?

**Comment by WoLpH** [comment]
Indeed, appears to be working again. Thanks for the response :)

**Comment by ask** [comment]
Thanks for the report!
