### ISSUE TITLE
logging to journald

### ISSUE THREAD

**Issue by afterdesign** [celery/celery#2934]
Hi.

So I'm trying to make celery work with systemd. I'm especially interested with logging everything into journald which can get logs from stdout/stderr and it's storing informations in binary format.

So the main problem is that I'm unable to get _all_ the loggers (and I see that there are a lot of them) within celery/kombu and to make them use my own logger (using python systemd logging library).

I don't want to use log file per worker with ```--logfile``` method. I even tried not to use ```celery multi``` and go with simple for and run ```celery worker -D``` but after detaching all of the logs are silenced up and without adding log file there is no option to get informations what is happening.

I tried to grab all the loggers and make them do what I want but this is almost impossible IMVHO.
Is there a way to make celery workers to write everything to syslog or to stdout/stderr ?

**Comment by ask** [comment]
A critical part of daemonization is closing stdin,stdout,stderr to detach from the controlling terminal.
There's no way around that, so if you want to keep stdout/stderr you will need to use systemd's mechanism for detaching (which is recommended over -D anway)
