### ISSUE TITLE
RDB not working

### ISSUE THREAD

**Issue by andrewfam** [celery/celery#2937]
<pre>
from celery.contrib import rdb
from celery.decorators import periodic_task
from celery.schedules import crontab
from celery.utils.log import get_task_logger

from collections import defaultdict

logger = get_task_logger(__name__)

#lets aggregate and send all unreaded messages to supervisors
@periodic_task(
    run_every=crontab(minute='*/1'),
    name="gen_notifications", 
    ignore_result=True
)
def send_aggregated_notify_on_email():
    rdb.set_trace()
    logger.info("Saved image from Flickr")
    from django.contrib.auth.models import User
    from django.utils import timezone
    from django.core.urlresolvers import reverse

    from utils.emails import send_unread_notifications
    from notifications.models import Notification

    nots = Notification.objects.filter(read=False)
    not_user_dict = defaultdict(dict)
    
</pre>
  This doesn't seem to work. 

settings.py
<pre>
CELERY_RDB_PORT = 6900
</pre>
Can't do telnet localhost 6900

**Comment by ask** [comment]
`CELERY_RDB_PORT` is an environment variable, not a setting!

**Comment by andrewfam** [comment]
Um this still doesn't solve my problem. 
Running the below, I can't access rdb
CELERY_RDB_PORT=6900 celery -A dpms beat -l info

**Comment by andrewfam** [comment]
I've figured it out. you need to run the workers to view the stuff
