### ISSUE TITLE
DuplicateNodenameWarning with no obvious reason

### ISSUE THREAD

**Issue by fillest** [celery/celery#2938]
Sometimes (maybe about once a day or so - conditions are unknown) we are getting `site-packages/celery/app/control.py:36: DuplicateNodenameWarning: Received multiple replies from node name: 'name'. Please make sure you give each node a unique nodename using the `-n` option. pluralize(len(dupes), 'name'), ', '.join(sorted(dupes)),`.
This happens on different independent hosts (each has its own celery), they have similar setup but run mostly different celery task code.

The most strange is that this started to happen only recently and we can't recall if we changed anything significant - except we changed worker count multiple times (can't correlate it strongly regarding the timeline though).
We use redis as the broker. We tried to reset the host (delete redis db and any celery state files like beat schedule and so on) and update celery packages to the latest version. The warning still occures.

On each host there is redis (configured for full persistence), beat, flower and multiple workers which use the local redis. Supervised by supervisord. On the first the run-commands are like this:
```
CELERY_CONFIG_MODULE="celeryconfig_dev" ... bin/celery -A libs.celery_ worker -Q celery -Ofair --loglevel=info
(same command, generated automatically by deploy) ... -Q fast ...
... -Q social ...
```
On the second:
```
(same command but with different CELERY_CONFIG_MODULE) ... -Q celery ...
... -Q saver ...
... -Q social ...
```

Packages: `amqp-1.4.7 anyjson-0.3.3 billiard-3.3.0.21 celery-3.1.19 kombu-3.0.29 pytz-2015.7`

**Comment by fillest** [comment]
Damn, I've just read the docs again http://docs.celeryproject.org/en/latest/userguide/workers.html#starting-the-worker -- I must specify `-n` if I run multiple workes on the same host, am I right?
Sorry for the false alarm then, gonna close the ticken and try `-n` first

**Comment by ask** [comment]
Yep, every worker needs a unique nodename.  `celery -A proj worker -l info -n worker2@%h`

**Comment by fillest** [comment]
Is there any special handling of `-n` value, by the way? I've set `-n` to same values as `-Q`, e.g. `celery`, `saver`, `social`, is it ok?
