### ISSUE TITLE
Result Backend not work in Windows 7, Celery version after 3.1.12

### ISSUE THREAD

**Issue by JetDrag** [celery/celery#2941]
Win7,RabbitMQ,3.5.5,Celery version after 3.1.12. Even specify the backend arg, when we want to 

result = task.delay()
result.get()

nothing returned……

**Comment by ask** [comment]
Try using the CELERY_RESULT_BACKEND setting instead of the bakend argument to `Celery(backend=)`

**Comment by dkdndes** [comment]
Hi #JetDrag, have a look at the end of trail in #897, it should work then.

**Comment by JetDrag** [comment]
Many Thanks, I'm now using Pika now to run tasks in distributed enviroument due to its simple and writing in pure Python. I'll try it later.

发送自 Outlook Mobile




On Thu, Dec 17, 2015 at 2:10 AM -0800, "Peter Rosemann" <notifications@github.com> wrote:












Hi #JetDrag, have a look at the end of trail in #897, it should work then.

**Comment by JetDrag** [comment]
I have tried. Nothing changed. It seems the backend object don't init normally. Peter have fixed it.

发送自 Outlook Mobile




On Fri, Dec 4, 2015 at 5:29 PM -0800, "Ask Solem Hoel" <notifications@github.com> wrote:












Try using the CELERY_RESULT_BACKEND setting instead of the bakend argument to Celery(backend=)

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
