### ISSUE TITLE
header of chords are still added to request.children even if add_to_parent=False

### ISSUE THREAD

**Issue by AnthonyDeroche** [celery/celery#2946]
Hello, 

First I create links between tasks with link and link_error attributes. Chains are not suitable with my need since I might need to build loops (task 1 chained to task 0 and vice versa). Tasks linked to each others are added to request.children on parent's task, which is actually the default behavior (trail=True). 

Then, I want to create tasks within a task (created in the first step) that are not added to request.children in parent task (I'm aware of synchronous subtasks). So I use add_to_parent = False on apply_async. It turns out that the header of chords is still added to children even if add_to_parent is set to False which might be a bug. I tried to use trail=False when starting the task and restored it to True at the end, to make sure that callbacks being called post-run are still added to children. It works.

Thanks.

**Comment by ask** [comment]
Seems to be fixed in master, as I verified `chord([..], xsum.s()).apply_async(add_to_parent=False)` works.

In general it's probably better to use `@task(trail=False)`, instead of selecting which tasks to add!
