### ISSUE TITLE
avoid copy when using canvas

### ISSUE THREAD

**Issue by hevy-CC4477** [celery/celery#2948]
I wanted to use the features of canvas (group, chord, chain ...) to manage my workflow.

If we take the graph just behind, I didn't succeed to find a way to execute it without having double nodes for the dependencies.
![graph](https://cloud.githubusercontent.com/assets/7586111/11546638/5c8c7dca-9903-11e5-9c17-199a349622bc.png)

Does someone know how to execute it this graph using canvas? How could I handle that?

**Comment by hevy-CC4477** [comment]
The only nice solution that I found is: to derive from class Task in "celery/app/task.py" creating a GraphTask. In this class I will have a list of parent and children and override the after_return function allowing me to handle any graph.

**Comment by hevy-CC4477** [comment]
I could also derive from DependencyGraph in 'celery/datastructures.py'  and Task.

**Comment by ask** [comment]
Duplicate of #893 I believe?

**Comment by hevy-CC4477** [comment]
I ask you a question on the other issue, depending on your answer I will tell you if it's a duplicate or not.

**Comment by hevy-CC4477** [comment]
Thanks

**Comment by neoascetic** [comment]
@hevy-CC4477 could you please share or `GraphTask`?
