### ISSUE TITLE
Celerybeat init script gives wrong message for status check

### ISSUE THREAD

**Issue by ezarowny** [celery/celery#2956]
The celerybeat example init script currently reports that the service is up when no pid file can be found when it should report the service as being down.

I created a small PR to fix this here: https://github.com/celery/celery/pull/2955

**Comment by ezarowny** [comment]
Now that I think about it, I wonder if the [celeryd init script](https://github.com/celery/celery/blob/master/extra/generic-init.d/celeryd) could use a separate bash file existence check as well. Something like:

```bash
if [ ! -e $pidfile ]; then
    echo "${SCRIPT_NAME} down: no pidfiles found"
    one_failed=true
    break
fi

if [ ! -r $pidfile ]; then
    echo "${SCRIPT_NAME} is in unknown state, user cannot read pid file"
    one_failed=true
    break
fi
```

I wouldn't mind adding that to the existing PR or making another.

**Comment by ask** [comment]
The celery init script uses `celery multi`, which could take care of that, and there can actually be multiple pidfiles in this case.

**Comment by ezarowny** [comment]
Well, I meant within the loop that already exists. It was only doing a -r check. I see where you're coming from though. :+1:

**Comment by ask** [comment]
Oh, yeah, there's a custom status check there... I guess the best would be if this was delegated to a `celery multi status` command
