### ISSUE TITLE
"Unknown syntax" error in celery amqp basic.publish command

### ISSUE THREAD

**Issue by starplanet** [celery/celery#2965]
This issue has been mentioned in issue:#2013 which has been closed, but the problem is still there. 
I reopen the issue.
when following celery 3.1.19 amqp tutorial, I get the following:
11> basic.publish "This is a test message!' testexchange testkey
string indices must be integers, not unicode

I use redis as broker and backend. My environment is:
ubuntu 14.04, celery 3.1.19

I scrutinize the celery source code, I found the problem occurs in function _prepare_spec in celery/bin/amqp.py file below:

if isinstance(conn.connection, Connection):
            self.amqp['basic.publish'] = Spec(('msg', Message),
                                              ('exchange', str),
                                              ('routing_key', str),
                                              ('mandatory', bool, 'no'),
                                              ('immediate', bool, 'no'))
The function will judge whether conn.connection is a instance of amqp.Connection, but when I use redis as broker,
conn.connection is a instance of kombu.transport.redis.transport, their ancestor are not the same.

In addition, even I force to change 'msg' type to Message, It will still report "message object doesn't have getitem attribute". Because I found kombo.transport.redis.transport class will get message by message['body'] dictionary method, amqp.Message doesn't define getitem method.

It is really a serious bug which is not solved in newest version yet.

**Comment by ask** [comment]
It's not compatible with redis, this is a command meant for amqp only really.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
