### ISSUE TITLE
CELERY_ALWAYS_EAGER = True adds tasks to queue in addition to running it locally

### ISSUE THREAD

**Issue by ketanbhatt** [celery/celery#2969]
I am running tests with CELERY_ALWAYS_EAGER = True.

The tasks get executed locally like they are supposed to, but they get added to the queue too and get executed by a worker again (and this worker uses a different DB then the test DB and is problematic for my application).

I am using RabbitMQ as the broker.

**Comment by ask** [comment]
I don't think it's possible for a task to execute both locally and be sent to the queue, unless you call them twice.  Are you 100% sure this is happening?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Please don't use ALWAYS_EAGER, mock your tasks instead in tests.
