### ISSUE TITLE
Subclass Autoscaler not working 

### ISSUE THREAD

**Issue by alaa89** [celery/celery#2970]
I am trying to use the CELERYD_AUTOSCALER option with a celery app. 
I subclassed the Autoscaler class as follows:
```
class CustomAutoscaler(Autoscaler):
    def __init__(self):
        Autoscaler.__init__(self, "prefork", 20, 4)
```
And I was trying to use it by specifying its path as follows
```
 CELERYD_AUTOSCALER='celery.worker.autoscale:CustomAutoscaler',
```
 but it does not seem to be working and no autoscaling is active.
__PS__: I am running celery python  
```
import celery
app = celery.Celery()
app.conf.update(
        BROKER_URL=broker ,
        CELERY_RESULT_BACKEND=backend ,
        CELERY_TASK_SERIALIZER='json',
        CELERYD_AUTOSCALER='celery.worker.autoscale:CustomAutoscaler',
        CELERY_IMPORTS=imports or [],
        CELERYD_CONCURRENCY=concurrency,
        CELERYD_HIJACK_ROOT_LOGGER=False,
)
```

**Comment by ask** [comment]
The component won't created unless you specify an ``--autoscale`` argument to the worker.

The pool argument here is also wrong, as it must be passed the worker Pool instance and not a string.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

The autoscale feature will be undocumented in 4.0.
