### ISSUE TITLE
graceful restart causes eventlet queues to silently drop chain/chord tasks 

### ISSUE THREAD

**Issue by rayalan** [celery/celery#2973]
Background: I have a deployment sequence consisting of 

```python
chain(pre_deployment.s(...), chord([deploy_task1.s(...), ..., deploy_taskN.s(...)], post_deployment.s(...)].apply_async
```
The basic concept is something like: Send an e-mail announcing the start of deployment, run the deployment process, send an e-mail announcing the end of deployment. 

One of the deployments the task knows how to do is to restart itself. Basically, it calls into a script that does this:
```
export EVENTLET_HUB=poll
celery multi restart $WORKER_COUNT \
     -c:1 25 -Q:1 celery \
     -c:2 10 -Q:2 celeryq_threaded \
     -A frogcelery.celery --pool:1=eventlet \
     --no-color --loglevel=DEBUG --logfile=log/%N%I.log --pidfile=run/%N.pid
```
The deployment code in general works. However, when redeploying my celery application, I notice that the e-mail notification is never sent. More investigation shows that the chain/chord seems to be disappearing, and that post_deployment never triggers (before or after the restart) even though all the deploy tasks complete.

After some experimentation, I tried disabling the eventlet queue and went with this:
```
export EVENTLET_HUB=poll
celery multi restart $WORKER_COUNT \
    -c:1 25 -Q:1 celery \
    -c:2 10 -Q:2 celeryq_threaded \
    -A frogcelery.celery \
    --no-color --loglevel=DEBUG --logfile=log/%N%I.log --pidfile=run/%N.pid
``` 
and voila, after a restart, celery finished running the chord. 

My conclusion is that something about graceful restart combined with eventlet isn't properly saving the chord/task, causing it to disappear rather than be run when the celery application comes back up.

---
A few background notes:
* I'm using eventlet to conserve memory while waiting on non-CPU intensive tasks.
* The threaded/non-threaded queue split is because I'm using Fabric for deployment, and Fabric assumes that it can to fully take over the process and doesn't play nicely with eventlet.
* EVENTLET_HUB=poll is because we're deploying via Fabric, and Fabric doesn't play nice with the default epoll hub that eventlet provides because epoll doesn't work on non-file sockets (and Fabric is talking via TCP/IP to other hosts). 
* Solution tested with celery 3.1.19; problem also observed with 3.1.18.

**Comment by ask** [comment]
How does it "restart itself", and how does it ensure the currently running tasks are completed before restarting?

**Comment by rayalan** [comment]
The celery restart task is running a Fabric command to trigger the restart this way:
```python
run("""sh -c '((nohup ./celeryctl restart &> /dev/null) &)'""", pty=False)
```
which is basically syntactic sugar to launch a background task with no stdin/stdout/stderr dependencies so that celeryctl keeps running in the background after the fabric session finishes. So after the restart task has finished launching celeryctl, the restart task is finished. 

Now there's a background copy of celery multi restart running, which goes about doing the normal things it does to ensure that celery shuts down gracefully (which, I believe, is using the appropriate signals for graceful shutdown).

**Comment by ask** [comment]
Does it drop tasks if you restart normally?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
