### ISSUE TITLE
documentation about configuration of log levels and log formats is mangled

### ISSUE THREAD

**Issue by papahippo** [celery/celery#2974]
http://docs.celeryproject.org/en/master/configuration.html#logging
...makes no mention of CELERYD_LOG_LEVEL but the section ...
http://docs.celeryproject.org/en/master/configuration.html#std:setting-worker_task_log_format
...seems to relate partly to this.
(It is easier to see by reading that page carefully than to explain fully!)

**Comment by ask** [comment]
The `CELERYD_LOG_LEVEL` and `CELERYD_LOG_FILE` options are deprecated and has been removed in 4.0.  It makes more sense to set these things from the command-line option.

That task log format is not changed by the `--loglevel` argument, so that part is definitely wrong.
