### ISSUE TITLE
Keeping Results has no support for Django ORM

### ISSUE THREAD

**Issue by alexandrevicenzi** [celery/celery#2975]
Hi,

Keeping Results Docs point to Django ORM support, but there's no code for this. Only SQLAlchemy is supported for database option. Django ORM is available only for Broker.

**Wrong:**

[Keeping Results](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results)

**Right:**

[CELERY_RESULT_BACKEND](http://docs.celeryproject.org/en/latest/configuration.html?highlight=database#celery-result-backend)

**Comment by ask** [comment]
The Django database result backend lives in the `django-celery` package

**Comment by alexandrevicenzi** [comment]
@ask ok, but I can't find no mention to this package. Am I missing something?

**Comment by hoffer2github** [comment]
if you use celery with djcelery, just set 
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend'
or if you don't use djcelery, you can use mysql directly
CELERY_RESULT_BACKEND = 'db+mysql://root:123456@localhost/test'

but there is a REPEATABLE-READ problem you must be careful
![image](https://cloud.githubusercontent.com/assets/16578180/12371952/d7b0734e-bc80-11e5-848f-32e1a9b580dd.png)
http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-result

you can find more description in celery document
http://docs.celeryproject.org/en/latest/configuration.html?highlight=celery_result_backend#database-backend-settings

**Comment by ask** [comment]
This is also documented here: 
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-the-django-orm-cache-as-a-result-backend

It's increasingly common to use the sqlalchemy result backend also with Django now, and there are so many steps necessary to set up the Django result backend.

**Comment by ask** [comment]
We'll be moving the django-celery models to a new project, and this will be documented in the Django tutorial.
