### ISSUE TITLE
Celery does not start properly with django 

### ISSUE THREAD

**Issue by shashank9487** [celery/celery#2977]
i am using `celery==3.1.19` ,`Django==1.8.4` , `django-celery==3.1.17`, `redis==2.10.5` stack. Configured everything but when i started celery worker with this command `celery -A config worker --loglevel=INFO` 

It shows me the task name and info log:

[tasks]
  . parts.tasks.add
  . parts.tasks.debug_task

[2015-12-30 17:06:08,544: INFO/MainProcess] Connected to redis://localhost:6379/0
[2015-12-30 17:06:08,550: INFO/MainProcess] mingle: searching for neighbors
[2015-12-30 17:06:09,555: INFO/MainProcess] mingle: all alone
 
That's it, celery stopped automatically after this, don't know how to debug it

**Comment by ask** [comment]
Stopped automatically? Use --loglevel=debug perhaps?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
