### ISSUE TITLE
'unknown message' when --queues is specified with a custom step

### ISSUE THREAD

**Issue by fernandogrd** [celery/celery#2979]
When running a custom step and specifying a queue with -Q option, I got 'unknown message' error every two messages are received.

```
[2015-12-30 21:40:24,258: WARNING/MainProcess] Received message: {'hello': '0'}
[2015-12-30 21:40:26,261: WARNING/MainProcess] Received and deleted unknown message. Wrong destination?!?

The full contents of the message body was: body: {'hello': '1'} (14b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{'routing_key': 'routing_key', 'exchange': 'custom', 'delivery_tag': 1, 'consumer_tag': 'None5', 'redelivered': False} headers={}}


[2015-12-30 21:40:28,264: WARNING/MainProcess] Received message: {'hello': '2'}
```

**How I'm running it:**
```
celery worker -A basic_test -Q custom --loglevel=debug
```

If I run without specifying the queue, it works as expected:
```
celery worker -A basic_test --loglevel=debug
```

A very similar behavior is described by this question in the mailing list:
https://groups.google.com/forum/#!topic/celery-users/E0ysKe43CFg

I'm using Python 3.5.1 with celery==3.1.19. I have also tested with Python 2.7

I could reproduced it by using a slightly modified version of extending docs to display the number of the iteration:

```
from celery import Celery
from celery import bootsteps
from kombu import Consumer, Exchange, Queue

my_queue = Queue('custom', Exchange('custom'), 'routing_key')

app = Celery(broker='amqp://guest:guest@broker:5672/')


class MyConsumerStep(bootsteps.ConsumerStep):

    def get_consumers(self, channel):
        return [Consumer(channel,
                         queues=[my_queue],
                         callbacks=[self.handle_message],
                         accept=['json'])]

    def handle_message(self, body, message):
        print('Received message: {0!r}'.format(body))
        message.ack()
app.steps['consumer'].add(MyConsumerStep)

def send_me_a_message(self, who='world!', producer=None):
    with app.producer_or_acquire(producer) as producer:
        producer.publish(
            {'hello': who},
            serializer='json',
            exchange=my_queue.exchange,
            routing_key='routing_key',
            declare=[my_queue],
            retry=True,
        )

if __name__ == '__main__':
    for i in range(1000):
        import time; time.sleep(2)
        send_me_a_message('celery', who=str(i))
```

**Comment by ask** [comment]
The error is coming from the task consumer, which would not be able to handle this message since it's not a proper task message.

You should not deliver this message to a task queue consumed by a worker using the -Q option.

**Comment by fernandogrd** [comment]
Hum, I see, that's a pity, I would like to use -Q to have multiple workers with different priorities for custom messages. 

Thanks for the feedback.

ps.: Just for the record, in my staging environment I had one rabbitmq that was used with other celery workers, so I ended up using -X celery to exclude default celery queues.

**Comment by robertobarreda** [comment]
@ask I see same behaviour using celery with django config (CELERY_QUEUES)
and executing the worker like:

  celery worker -A controlplane.celery -l info

Only solved by emptying CELERY_QUEUES and defining the queues in the ConsumerStep

**Comment by ask** [comment]
The `-Q` option is for the task consumer, if you have add custom consumers as bootsteps then you would need to define a custom command-line option for that consumer.

Celery wouldn't even be able to know what consumer the names in -Q refers to.  E.g. `-Q foo,bar`, is bar here a task queue or a queue used by a custom consumer?  It's impossible to distinguish them.

**Comment by ask** [comment]
In 4.0 CELERY_QUEUES is also renamed `task_queues` so it's more clear that this refer to task queues only.
