### ISSUE TITLE
How to measure the task's duration

### ISSUE THREAD

**Issue by norbertpy** [celery/celery#2981]
So I wanna know how long it takes for a task to be processed and finished successfully. Flower UI shows `Runtime` of each task but there is no API that I can get that for batch of tasks. Ironically, the `task_postrun` and `task_prerun` signals are not called and I don't know why.

Is there a simple way to measure the duration? Thanks.

**Comment by ask** [comment]
Flower should have the `/api/task/info/<id>/` endpoint, is the runtime not included there?

prerun and postrun are called inside the worker, is that were you expected them to be called?

**Comment by feifangit** [comment]
you probably can find the workaround here: https://github.com/celery/celery/issues/479

**Comment by norbertpy** [comment]
Thanks.
