### ISSUE TITLE
utils.timeutils.utcoffset incorrect for DST time zones in winter months

### ISSUE THREAD

**Issue by jrichards99** [celery/celery#2983]
def utcoffset(time=_time):
    if time.daylight:
        return time.altzone // 3600
    return time.timezone // 3600

This is wrong. This currently returns 4 for EST time zone (should be 5 during winter months).  The value of time.daylight simply indicates if the timezone is one that HAS daylight savings time, not that it is currently active. The value of time.altzone is the time if DST was currently active.  In the winter months it is not.

End result is this code always assumes DST is active if available.The suggested way to check for DST active is "time.localtime().tm_isdst".

**Comment by rbarlow** [comment]
I believe this was the cause of https://github.com/celery/celery/issues/1802#issuecomment-161916587
