### ISSUE TITLE
will it be more suitable to let user set capacity in rate_limit control algorithm of Token Bucket?

### ISSUE THREAD

**Issue by hoffer2github** [celery/celery#2988]
Recently, I used celery's rate_limit option to control special task rate limit. 
There is a phenomenon that it takes a long time to finished all the tasks even though I set big rate.
Then I read the source code,  and I found that celery use Token Bucket Algorithm to control rate limit with set constant capacity parameter equal to 1, which let Token Bucket Algorithm evolve into least time interval control. I think it's the reason why my tasks tasks long time to finished.
Ex, if I set rate_limit=100/m, if I start 50 tasks at once, it will takes me at least 30s to finished all these tasks.
So I doubt, is it more suitable to let user set capacity. Ex: if I set rate_limit=100/m, let capacity to be 100, then the first 100 tasks finished very soon, the other tasks wait for the next minute.

**Comment by ask** [comment]
That sounds useful! Not sure if by separate setting or simply allowing the bucket type to be configured on the task class  `Task.RatelimitBucket` or something.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
