### ISSUE TITLE
celery recreate connection to Mongo backend each time when task result is stored

### ISSUE THREAD

**Issue by vklindukh** [celery/celery#2992]
When celery configured to store task results into Mongo backend (CELERY_RESULT_BACKEND and CELERY_MONGODB_BACKEND_SETTINGS properties defined) it opens and closes connection to Mongo each time when new record is written to Mongo.

It causes too many sockets in TCP_WAIT state during high task execution rate and finally celery unable to connect to Mongo for a while because of no free sockets available:
```
python2.7/site-packages/pymongo/mongo_client.py", line 378, in __init__ raise ConnectionFailure(str(e)) ConnectionFailure: [Errno 99] Cannot assign requested address
```
To fix it we may want to eliminate process_cleanup() from celery/backends/mongodb.py and let celery process to reuse self._connection instead of recreating it each time when new task result is going to be stored into mongo backend:
```
index 8935d0d..e217639 100644
--- a/celery/backends/mongodb.py
+++ b/celery/backends/mongodb.py
@@ -162,14 +162,6 @@ class MongoBackend(BaseBackend):
 
-    def process_cleanup(self):
-        if self._connection is not None:
-            # MongoDB connection will be closed automatically when object
-            # goes out of scope
-            del(self.collection)
-            del(self.database)
-            self._connection = None
```

**Comment by ask** [comment]
Closed by #2993
