### ISSUE TITLE
feature request - timestamp on startup log output

### ISSUE THREAD

**Issue by jvanasco** [celery/celery#3010]
Small request- it would be great if the worker's startup log output included the date/time.

I'm talking about the routine in here: https://github.com/celery/celery/blob/8866282482942cb3ebcb214dca25fa0cc2cbb284/celery/apps/worker.py

that creates this output:
	 -------------- celery@myserver v3.1.19 (Cipater)
	---- **** ----- 
	--- * ***  * -- Linux-4.1.5-x86_64-linode61-x86_64-with-Ubuntu-12.04-precise
	-- * - **** --- 
	- ** ---------- [config]
	- ** ---------- .> app:         tasks:0x7c9efd0
	- ** ---------- .> transport:   redis://localhost:6379/3
	- ** ---------- .> results:     redis://localhost:6379/4
	- *** --- * --- .> concurrency: 6 (prefork)
	-- ******* ---- 
	--- ***** ----- [queues]
	 -------------- .> myapp        exchange=myapp(direct) key=myapp

As for the reason why, sometimes my process dies.  I haven't figured out why.  The only reason I know this, is that Supervisord show it up for a few hours (not days, like other processes).  I'd love to see the timestamp of the startup in the logs, this way I can check all those times against other logs and try to see what is happening.

**Comment by ask** [comment]
The banner is not part of the normal logging, which does have timestamps, but I added the time now.  Makes sense if whatever is catching stdout is not adding timestamps.

**Comment by jvanasco** [comment]
thanks a ton!

You better describe the situation too -- timestamps were on everything via STDOUT, except the banner.
