### ISSUE TITLE
Worker doesn't process tasks when starting it with --autoreload

### ISSUE THREAD

**Issue by atleta** [celery/celery#3013]
I'm running celery in development mode with the following arguments:
celery -A my_package worker --autoreload -B -l info

and found that it just keeps adding the tasks to rabbitmq but they never get to run. I tried it with a separate scheduler and task runner process, but even then it doesn't work. After restarting without the autoreload option it will start processing all the queued tasks. (Also, when using the autoreload, it will keep running with near 100% CPU utilization.

This happens with both the current version on PyPI (3.1.19) and the bit earlier one that I have in my project requirements (3.1.18).

**Comment by syradium** [comment]
Have tried using it with cpython? In fact I was never able to make `autoreload` work at all.

**Comment by fuzzybear3965** [comment]
I have also been having problems using celery with autoreload. I'm using `Celery 3.1.23 (Cipater)` and `pyinotify 0.9.6` with the following OS configuration: `Linux _somehostname_ 4.2.0-35-generic_ #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Autoreload will be undocumented for the 4.0 release.
