### ISSUE TITLE
task request header not forwarded on retry

### ISSUE THREAD

**Issue by cjh1** [celery/celery#3017]
Inside a signal handler connected to ‘before_task_publish’ it seems that the headers argument is empty if the task being sent is a retry ( i.e. retries > 0 ). @ask gave the following possible work around:
```
self.retry(headers=self.request.headers)
```
However, this does not help in my case as the retry is being performed by celery, the task in question is celery.chord_unlock.

**Comment by ask** [comment]
Fixed in 3.1 branch, was already fixed in master
