### ISSUE TITLE
acks_late=True does not ack all messages

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#3019]
Dispatch the same task many times from multiple processes and have 1 celery worker. The messages to ack upon completion are tracked using the `delivery_tag` attribute in the `properties` section of a celery message. Per the [API section of the docs](http://docs.celeryproject.org/en/latest/userguide/routing.html#hands-on-with-the-api) the delivery tag is an integer and is described as:

```
Note the delivery tag listed in the structure above; Within a connection channel, 
every received message has a unique delivery tag, This tag is used to acknowledge 
the message. Also note that delivery tags are not unique across connections, so 
in another client the delivery tag 1 might point to a different message than in 
this channel.
```

The 1 celery worker will read in many messages and if it receives two of the same values for `delivery_tag` before the first one has acked, the first one will not be acked by celery. Even if celery did ack it, many transports likely store the original message so it can be acked and likely track that by `delivery_tag` also.

The easiest thing to do is to have the message acking be tracked by uuid (I think). That change should be safe for all transports right?

@ask What do you recommend?

**Comment by bmbouter** [comment]
I'm going to implement a workaround in the `Qpid` transport for Kombu, which will resolve the problem there. It seems like a design error so we should fix it more broadly in celery itself.

**Comment by ask** [comment]
Two messages cannot have the same delivery tag, and if it's the same message with the same delivery tag, acking the tag will ack the message (they are the same message)

**Comment by ask** [comment]
Within the same channel obviously, if we are talking across channels/connections then they are duplications.

But duplications are fine with late_ack, they are only to be used with idempotent tasks.

**Comment by bmbouter** [comment]
@ask The duplicates occur by having multiple Channels be used for message production, so we agree on how the duplicates are occuring.

It's true that a late_ack tasks must be idempotent, but if all tasks complete, no crashes occur, and no unexpected exceptions are raised I expect all acks to occur. Anything less is a bug. Here is a rough recap of what I observed in celery's ack handling when receiving a message (1) from two senders (A, B).:

message 1 is received from dispatcher A
message 1 is received from dispatcher B
message 1 from dispatcher A completes and is acked
message 1 from dispatcher B completes but is NOT acked

I expect there to be 0 unacked messages in the queue since all messages succeeded.

**Comment by ask** [comment]
If the messages originate from multiple producer channels, then they are not the same message?

I.e message 1 from A and message 1 from B cannot have the same delivery tag, since they are not coming from the same producer channel.

**Comment by bmbouter** [comment]
The messages are different, and originating from multiple producer channels, but they have the same delivery_tag.

Perhaps this is unique to the Qpid transport based on how it implemented delivery_tags. It uses count() which has each producer channel start at 1 and iterate up. Given that having two producers who start at the same time would easily cause colliding delivery_tag.

@ask Is this problem caused by how delivery_tag is implemented? Is it unique to the Qpid transport How is this not a problem for other transports like rabbitMQ?

**Comment by ask** [comment]
Delivery tags are assigned by the server in amqp:
http://amqp.readthedocs.org/en/latest/reference/amqp.channel.html#amqp.channel.Channel.basic_ack

The kombu virtual transports uses UUID4s:
https://github.com/celery/kombu/blob/master/kombu/transport/virtual/__init__.py#L518-L519

**Comment by bmbouter** [comment]
OK this seems specific to the Qpid transport. I'm closing this and opening a new issue against Kombu which will be specific to the Qpid transport.

**Comment by bmbouter** [comment]
@ask thanks for the input!
