### ISSUE TITLE
celery purge does not purge active or reserved tasks

### ISSUE THREAD

**Issue by jhh3000** [celery/celery#3023]
stack:
- django
- redis

when i run `python manage.py celery inspect active`, there is always at least 1 active task
when i run `python manage.py celery inspect reserved`, there is always a 4 task backlog

when i run `python manage.py celery purge -f` the output is:
`Purged n messages from 1 known task queue.` where n is usually a large number (e.g., 89)

and then i will run `redis-cli flushall` and get an OK

when i then re-run `inspect active` or `inspect reserved`, the same tasks from before purging are still there.

is this a bug or is it an artifact of the redis broker not syncing up or something?

**Comment by syradium** [comment]
@jhh3000  are you saying that it purges 0 tasks or it purges only some specific ones? I am not sure how it should purge active tasks  though.

Also please specify celery version you are using.

**Comment by jhh3000** [comment]
I'm using version 3.1.17. It makes sense that Celery would be unable to purge tasks in progress (active). But I would expect that the reserved queue would be cleared after a purge. Maybe my understanding of the purge command is incorrect. I would expect a `purge -f` to remove all reserved tasks, such that when I re-run `inspect reserved`, there are 0 tasks.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Purge is a broker operation only, it only clears the queue in the broker.  It's maybe possible to implement it, but we don't have the resources to work on that for the foreseeable future.

**Comment by alexandernst** [comment]
Why close it? Leave it open and put a label such as `help wanted`
