### ISSUE TITLE
chord() fails to wrap results in list with redis backend and only one subtask

### ISSUE THREAD

**Issue by eli-green** [celery/celery#3028]
With the following code and redis 3.1.18 (we're due for an update, I know):

```python
@task
def generator(num):
    return num


@task
def consumer(*results):
    return repr(results)


gen1 = generator.s(1)
gen2 = generator.s(2)

single = (group([gen1]) | consumer.s('1'))
multi = (group([gen1, gen2]) | consumer.s('2'))
```

Running in eager mode, I get:
```
>>> single().get()
"([1], '1')"
>>> multi().get()
"([1, 2], '2')"
```

Whereas if I run against our redis broker:
```
>>> single().get()
u"(1, u'1')"
>>> multi().get()
u"([1, 2], u'2')"
```

As you can see, the value passed to single() is a bare integer, not a list as it is (and as I would expect) in eager mode.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
