### ISSUE TITLE
Why we should not do delay a task within task?

### ISSUE THREAD

**Issue by AndreLobato** [celery/celery#3031]
The reason I am asking this is because I need to have a more control over a set of tasks then the usual GroupSet or ChainSet would give me, I've implemented a dependency logic within the group were a task can fail, but later be recovered (fixed then retried) so the dependents would still be executed and the parent to monitor them all. Also my tasks do receive arguments based on times from the parent task, handling as relative countdowns and ETAs. I've being used this strategy for a while in (sic*) production. Despite I've noticed is not the recommended way of doing this. Therefore I would like to better understand this limitation as sometimes (never in production - lucky?) I get into a deadlock state and gets tasks stuck as RECEIVED, as predicted (#310), even using 0fair. 

So as this is a important feature for me, I wish to understand better why this happen and if there is a way to solve this.

Is there a problem when apply_async or is to retrieve the results? 

Ps.: When waiting for tasks I am using .ready() to check, so it never blocks.

Versions:
amqp==1.4.8
celery==3.1.19
billiard==3.3.0.22
kombu==3.0.30

Cheers

Andre

**Comment by alekibango** [comment]
if i understood correctly your question,
main problem with subtasks within a task is this:
- task is blocked waiting for subtask(s).

This might possibly lead into partial or full deadlock, as many/all workers might wait for subtasks, none of which will be done (as workers wait for subtasks instead of working hard).
It is not making the job tree  (big task with subtasks) much safer.  Try to think up better way of managing state (in external DB?), or (better) define tasks in a way that you do not need state management at all. 
It is generally better to have your workers working, not waiting for other workers.

if you really need complicated relations between workers, you also might take look at other tools. For example ZMQ is very nice low level library for writing your own  solution.

**Comment by AndreLobato** [comment]
The reason I am doing is because the nature of my tasks are very long and no frequent big tasks (weather forecast system). So one task could potentially last for hours (a numerical model running). To be honest has been working quite well for the past 5 months in production, but I was interested to avoid any potentials flaws. I still don't understand how this could lead to dead locks, since the states and results are setted in the database and mostly of times 99,9% i guess the worker have no problem in write to it. 

For dealing with this process I have essentially 'head'  machines and 'nodes' machines which do the computing, so the head workers are responsible to manage the tasks running in the nodes. I have all integrated with a customized flower interface, and the tasks are all configured using yaml.

Cheers

**Comment by ask** [comment]
It only applies to the prefork pool, and will only lead to deadlock if there are no worker processes left to handle the request you are waiting for (like if -c is 10, and there are 10 tasks waiting for other tasks).

- You can use the eventlet/gevent pools to avoid it (but your code can also introduce
  deadlocks there, so be careful).
- You can use a timeout for the requests: `add.delay().get(timeout=1)`
- Always use the worker -Ofair argument when using the prefork pool and waiting for other tasks.
- You can route the waiting tasks and the dependency tasks to different queues (where no worker
  consumes from both queues).

**Comment by AndreLobato** [comment]
Thanks for the tips Ask! :+1:

**Comment by AndreLobato** [comment]
Ok after understanding a bit better this problem, I might have the feeling I am actually hitting a dead lock situation at 1 (out of 2) production environment.  So to be more clear how the task is being processed. 

On the producer task basically I never call AsyncResult.get(), as the result is not important at this point. I only check if a task is complete with AsyncResult.ready() and query the state once is ready by AsyncResult.state. 

But I am suspicious that my producer worker is getting into a partial deadlock because at some point, after a few hours working, and completing a few tasks the workers rises a "Broken pipe" error then raises RecoverableConnectionError: Socket was disconnected, then reconnects again right after. Looks all good, heartbeats are ok, and the running tasks still running. But the next task this worker receives, never gets executed even having plenty of free processes, on flower the tasks are stated as "Reserved". Others tasks after this one, may get executed, but also could end up in the same state. 

The problem is that I never managed to reproduce this in development, and other thing I don't quite get it is why this happens with one server but not the other. 

I tried to use Eventlet, but is missing a very important feature to me which is the ability to terminate a  running task.

I am also using -Ofair option and CELERY_PREFETCH_MULTIPLIER=1

**Comment by alekibango** [comment]
@AndreLobato:  i cant really say what is the problem now, but here are few ideas from my experience with celery:

- doublecheck timeout values. there might be some not so high defaults.
- Really, really try hard not to use AsyncResult objects in workers.  Local programming is hard enough. Do not rely on remote code to answer you in time correctly. Problems in distributed computing WILL come and if you are not able to brush them off by running your task again, you are in trouble.  Sometimes its broken cable, failed ipv6 connectivity,  misconfigured firewall, bugs in code or versions... memory or drive corruption, buggy hypervisors, or crazy admins...  when your app will grow, you will meet with those weekly, or even daily. Make your application survive that and make it faster by not waiting for remote side to answer you right now.

Celery  really excells at asynchronic tasks. Do not try to synchronize them or build consensus mechanisms or locks or master tasks (they can also fail).  Embrace asynchronicity. Maybe read something about CRDT. Make reliability asynchronous, without locks and blocking.  
It will make your app much better. and you will sleep better at night.

**Comment by AndreLobato** [comment]
Thanks for replies. I will close this issue as I identified that my problem was not related to tasks/workers getting deadlock, but a different one related with a worker loosing connection with the broker and after that, the very next task it do receives but don't execute, or maybe execute several hours later. All of mentioned above I will consider for any further project.
