### ISSUE TITLE
NullPool always used for SQLAlchemy even with prefork

### ISSUE THREAD

**Issue by simonpercivall** [celery/celery#3032]
Running celery 3.1.20 with SQLAlchemy backend, I've noticed that the `_after_fork` function of `SessionManager` is never run, even with the `prefork` pool implementation. This, of course, means that connections will be opened and closed for each operation.

Simple print debugging shows that the fork happens before the `_after_fork` method is registered.

**Comment by ask** [comment]
The session shouldn't be created before the prefork pool starts anyway, so I wouldn't be surprised if it's not registered: that's a good thing.
