### ISSUE TITLE
Celery with mysqlclient result backend on Mac OS X hangs for 5 seconds on connection open

### ISSUE THREAD

**Issue by simonpercivall** [celery/celery#3033]
Not really sure where this issue belongs …

Running Celery (prefork) 3.1.20 with SQLAlchemy result backend and the `mysqlclient` lib (or `mysql-python`) on Mac OS X 10.11, after the first "loop" in `kombu.async.hub:Hub.create_loop`, the `store_result` calls will stall for 5 seconds for each new task received. The stalls seem to happen in `mysql_real_connect`. The issue disappears completely if a `time.sleep(0.1)` is inserted anywhere after `events = poll(poll_timeout)` (but before `store_result`, of course).

**Comment by auvipy** [comment]
if the issue still persist in master plz ping here to reopen.
