### ISSUE TITLE
Eventlet worker hangs at 100% CPU in recvfrom loop

### ISSUE THREAD

**Issue by AndreCimander** [celery/celery#3037]
We are experiencing random worker hangs in our eventlet pools (50 threads each) on our Ubuntu 14.04 worker (kernel 3.19.0-33-generic).

The stacktrace of every hanging worker process just contains a loop of 

> recvfrom(socketnumber,  "", 1, 0, NULL, NULL)  =  0

with two established connections to the redis broker.

__pip packages__
redis = 3.0.6
celery = 3.1.20
kombu = 3.0.33
eventlet = 0.18.1

`
BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 36000,  
    'fanout_prefix': True,      
    'fanout_patterns': True, 
    'socket_timeout': 30,
    'max_connections': 250,
}
`

We tried to set a connection timeout of 900 seconds on the redis server, but the connection seems to be active. Any help and tips are highly welcome, it's becoming a little frustrating...

**Comment by thedrow** [comment]
Can you provide debug logs and the Python version?
What happens if you use less eventlets? Did you try with 1 or 2?
Does the same problem occur with gevent or the prefork pool?

**Comment by AndreCimander** [comment]
Sorry for the delayed answer, it's a bit hectic around here. We are using Python 2.7.9.

At least I've somewhat good news, after a long time in the tweak-and-debugging hell I tried the classic "have you tried to turn it off and on again?", rebooted all production servers and, lo and behold, our workers stopped hanging. So, either a kernel upgrade or a clean reload of all modules helped solving our problems, at least for now. We had one or two crashes, but those are easy to detect and correct.

**Comment by thedrow** [comment]
I'm going to close this issue for now. If it regresses comment here and I'll reopen.
