### ISSUE TITLE
Celery advanced example : Behavior trees

### ISSUE THREAD

**Issue by asmodehn** [celery/celery#3040]
As a : 
- complex example for advanced tutorial
- complete test to validate the completeness of celery features
- something that could be useful for others

I am wondering if anyone tried to implement [behavior trees](https://en.wikipedia.org/wiki/Behavior_tree_(artificial_intelligence,_robotics_and_control) with celery.

It would be useful for anyone wanting to "program" complex distributed system and give it an whole AI feel...

**Comment by ask** [comment]
This would be interesting!  I don't have the time to work on it, but would like to see it contributed!

You could try the mailing list maybe, or take a go at it.
