### ISSUE TITLE
Unrecoverable error: ValueError invalid literal for int() with base 10: '53473,ds053473-a1.{snip}.mongolab.com'

### ISSUE THREAD

**Issue by m-vdb** [celery/celery#3045]
This breaks mongo backend, because of https://github.com/celery/celery/commit/33f1dc829223da5499e05e271a6d49edde7ffc68. I believe `maybe_sanitize_url` doesn't play well with replica sets...

Full backtrace:
```
ValueError: invalid literal for int() with base 10: '53473,{snip}.mongolab.com'
  File "celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "celery/bootsteps.py", line 119, in start
    self.on_start()
  File "celery/apps/worker.py", line 170, in on_start
    string(self.colored.cyan(' \n', self.startup_info())),
  File "celery/apps/worker.py", line 232, in startup_info
    self.app.conf.CELERY_RESULT_BACKEND or 'disabled',
  File "kombu/utils/url.py", line 63, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "kombu/utils/url.py", line 58, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
```

**Comment by thedrow** [comment]
Is that a problem with the results backend or the broker or both?
Also can you share a failing test case? Preferably in a form of a PR?
I'm tempted to blame Python's urlparse but I'd like to verify.

**Comment by m-vdb** [comment]
In this case I guess only the result backend is impacted, but I guess whenever `maybe_sanitize_url()` is used with a replicaset connection URI it could fail. I'll try providing a PR today

**Comment by m-vdb** [comment]
there you go @thedrow :smile:

**Comment by asiebert** [comment]
Note that this issue is very similar to https://github.com/celery/kombu/issues/375
Indeed, `urlparse` should not be used for Mongo URIs

**Comment by thedrow** [comment]
Any suggestion on how to fix this?

**Comment by m-vdb** [comment]
From what I understand, `maybe_sanitize_url()` is used to remove sensitive parts from the url. In the case of mongoDB, with a replica set connection, url will look like: `mongodb://user:password@host0.com:43437,host1.com:43437/work4us?replicaSet=rs&ssl=true`. By splitting on the coma and taking the first part, you'll always get the username and password. So you can sanitize that part and re-append the second part to the result. Something like:
```
results_url = self.app.conf.CELERY_RESULT_BACKEND
if "," in results_url:
    first_part, second_part = results_url.split(",", 1)
    results_url = ",".join([maybe_sanitize_url(first_part), second_part)
else:
    results_url = maybe_sanitize_url(results_url)
```
of course I would move that in a utils function, something like `maybe_sanitize_results_url()`. What do you think @thedrow ?

**Comment by m-vdb** [comment]
other thing: should it be done at `kombu` level or `celery` level?

**Comment by thedrow** [comment]
@m-vdb @mbox has encountered a similar problem with the memcached results backend.
Maybe you guys want to collaborate on a patch for these issues?
I'm not sure if this should be part of kombu or celery.
@ask What do you think?

**Comment by m-vdb** [comment]
yes totally :)
as for celery or kombu => if kombu supports mongodb/memcached, then it should be done in kombu, but I'm not sure it does, does it?

**Comment by asiebert** [comment]
@ask is most likely the best qualified to answer this, but considering backends are handled by `kombu`, their connection string manipulations (i.e. sanitization) should probably be handled there as well?

**Comment by ask** [comment]
The result backends do not typically use kombu.

Maybe the best solution is to have something like `backend.as_uri(include_password=False)`, that would also be helpful for the `task.apply_async(reply_to=url)` feature I've been working on.

**Comment by m-vdb** [comment]
ok I'll work on a patch. Basically:
- add `url=None` kwargs in [BaseBackend.__init__](https://github.com/celery/celery/blob/e71c5eff0202fd3260e6a67c991897b28a77aced/celery/backends/base.py#L94-L96)
- define `BaseBackend.as_uri(include_password=False)` method that will return the uri, sanitized or not with password
- define `MongoBackend.as_uri(include_password=False)` method that will do the job for mongo replica urls

**Comment by thedrow** [comment]
Sounds good.

**Comment by ask** [comment]
The same is required for the cache backends (Issue #3068), and a failing test case was submitted by @mbox in #3073 that probably should be included in the fix
