### ISSUE TITLE
One error in task group raises StopIteration

### ISSUE THREAD

**Issue by sampeka** [celery/celery#3051]
I'm trying to iterate over the results of a `TaskSet` or `group`, logging errors as they occur or processing the result. However, for some reason any error in a group of tasks causes a StopIteration to be raised.

Heres a simple example:

```
@shared_task
def doomed_to_fail():
    raise Exception()


def main():
    tasks = group(doomed_to_fail.s() for _ in range(20)).apply_async()
    results = tasks.iterate()
    outstanding_tasks = 20
    while True:
        try:
            result = next(results)
        except StopIteration:
            print("Done with %d remaining..." % outstanding_tasks)
            break
        except Exception:
            pass
        finally:
            outstanding_tasks -= 1
```

If you call `main` you will see the loop exists with 19 outstanding tasks. Is this desirable behaviour? If it is, how do I do what I'm trying to achieve?

Edit:
Just found out that `iterate` takes a `propagate` parameter, might be worth updating the docs here:
http://celery.readthedocs.org/en/next/reference/celery.result.html#celery.result.TaskSetResult.iterate

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
