### ISSUE TITLE
Broadcast stops working after worker gets too many "missed heartbeat"

### ISSUE THREAD

**Issue by rudeb0t** [celery/celery#3056]
Whenever a worker node gets too many "missed heartbeat" from other worker nodes it stops responding or receiving broadcast messages and requires a restart of the celery worker process in order to begin processing broadcast messages again. The log output from the celery worker **stops** at the "missed heartbeat" messages and no longer responds to broadcast messages until it is restarted.

Version and configuration information:

**Celery:** 3.1.20
**Broker:** RabbitMQ
**Broker connection:** amqp (not pyamqp)

**Comment by rudeb0t** [comment]
Additional information about this issue:

It appears that when the node's connection to RabbitMQ is degraded enough resulting in slow sending of heartbeat event, the node appears to disconnect or stop listening to its broadcast queue.

**Comment by ask** [comment]
Do you know why the RabbitMQ connection degrades?

**Comment by rudeb0t** [comment]
Our provider had a couple of hardware issues with their routers recently causing dropped packets. There had also been a few instances of their routers resetting after scheduled maintenance. I have not been able to test if manually disabling the interface over which RabbitMQ connections is made will also have the same effect. I will try to find an isolated node in our cluster and test this.

**Comment by ask** [comment]
Please try to enable the CELERY_EVENT_QUEUE_TTL, CELERY_EVENT_QUEUE_EXPIRES options.

They will be enabled by default in celery 4.0.

We don't currently have the resources to investigate this issue, so closing :(
