### ISSUE TITLE
unacknowledged tasks are not processed on forceful terminate of worker threads

### ISSUE THREAD

**Issue by Lokesh235** [celery/celery#3057]
I am using Celery with rabbitmq as broker. 
Problem:  After running for sometime the celery worker threads are getting stuck and stop processing because of which I have to do forceful kill of Main Thread and restart it manually. This leads to loss of tasks which were in task queues.
Tried method: I tried force terminate(Ctr+c) with 'acks_delay=True' option for task to check whether this will process the tasks which were unacknowledged when Main thread was killed or not, but it is not working and unacknowledged tasks were never processed again.

Please tell any possible solution to kill the worker thread which is stuck and reprocess the unacknowledged task. Also, please tell any way, if there is any, of restarting the Main thread automatically.

**Comment by harikishan** [comment]
Same Issue for me..below are the my project settings

Celery Dependencies & Versions:
celery==3.1.18
amqp==1.4.7
kombu==3.0.26
pika==0.9.13

    BROKER_URL = "RabbitMQ Broker URL"
    CELERY_ACKS_LATE = True
    CELERY_DEFAULT_QUEUE = 'default-queue'
    CELERY_EVENT_QUEUE_TTL = 10
    CELERY_EVENT_QUEUE_EXPIRES = 15
    CELERY_IGNORE_RESULT = True
    CELERYD_PREFETCH_MULTIPLIER = 1
    CELERYD_MAX_TASKS_PER_CHILD = 20
    CELERY_SEND_TASK_SENT_EVENT = True

**Comment by sephioh** [comment]
I have the same issue. I think is related to this issue as well: https://github.com/celery/celery/issues/2839

**Comment by ask** [comment]
acks_late tasks are acknowledged if the child process is killed to avoid a super fast message loop.

See this new feature coming in 4.0: http://docs.celeryproject.org/en/master/configuration.html#task-reject-on-worker-lost
