### ISSUE TITLE
Celery multi doesn't start workers

### ISSUE THREAD

**Issue by iterq1** [celery/celery#3060]
Hi!

I'm trying to start multiple workers on server with command from celery docs `celery multi start Leslie -E`. But it only shows:

```
celery multi v3.1.17 (Cipater)
> Starting nodes...
    > Leslie@test: OK
```
and exits.
And there are no workers in output of `ps aux | grep celery`. It also creates Leslie.log, but it's empty.
On local machine it works fine, I see 5 workers as expected.

**Comment by iterq1** [comment]
I've not found the reason why `multi` is not working, but it can be solved by using multiple configs of upstart, supervisor etc.

**Comment by ask** [comment]
This points to some misconfiguration/environment issue, try using:

    $ C_FAKEFORK=1 celery multi start Leslie -E
