### ISSUE TITLE
Add documentation on pool implementations

### ISSUE THREAD

**Issue by hheimbuerger** [celery/celery#3061]
I've been struggling to find any information about the different pool implementations, e.g. a more thorough explanation what each of them does and what the advantages and disadvantages are.

My search started with [this note in the configuration documentation](http://docs.celeryproject.org/en/latest/configuration.html#celeryd-pool):

> CELERYD_POOL: Never use this option to select the eventlet or gevent pool. You must use the -P option instead

Note that the "-P option" is not a link and I couldn't find any real information about it in the documentation. If you search for it, you'll get [this](http://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html?highlight=#cmdoption-celery-worker-P):

> Pool implementation: prefork (default), eventlet, gevent, solo or threads.

But no information what any of these mean.

There's some more information in the [changelog for 3.1](http://docs.celeryproject.org/en/latest/whatsnew-3.1.html#prefork-pool-improvements):

> The pool now uses async I/O to send work to the child processes.

Which pool is this? Do I have to do anything to get these improvements?

Is there more information somewhere (besides the source) that I missed? Or could some this be added? In the meantime, any articles I could refer to to learn more?

**Comment by ask** [comment]
In general the rule of thumb is: Prefork pool for CPU-bound tasks,  eventlet/gevent for I/O-bound tasks.

I would like to have documentation for this, but sadly eventlet/gevent is not something you can enable and forget.  There are lots of pitfalls and quirks that you must be aware of, so you need to
do some research.  I started one guide here: http://docs.celeryproject.org/en/latest/userguide/concurrency/eventlet.html

>Note that the "-P option" is not a link and I couldn't find any real information about it in the >documentation. If you search for it, you'll get this:

Thanks, I specified that it belongs to the `celery worker` command.

>>The pool now uses async I/O to send work to the child processes.
> Which pool is this? Do I have to do anything to get these improvements?

The title of this section is "Perfork Pool Improvements", and begins with:

>These improvements are only active if you use an async capable transport. This means only RabbitMQ >(AMQP) and Redis are supported at this point and other transports will still use the thread-based >fallback implementation.

Qpid and SQS will be added to the list of async capable transports in 4.0

**Comment by edouardtheron** [comment]
Just ran into this thread, thanks @ask for some clarification in the doc.

I see in the doc that one can also use Gevent as a pool implementation, but I fail to find anything related to the setting of Gevent in a Celery context anywhere on the web.

Is it recommended with the same "warning flags" as Eventlet?

**Comment by aminkashiri** [comment]
Have you found anything? @edthrn
