### ISSUE TITLE
Data Loss and Late response using RabbitMQ in linux

### ISSUE THREAD

**Issue by mohitbhagwani94** [celery/celery#3063]
I am trying to setup a Django-celery in cluster environment. In the below configuration:

Machine A - Celery Worker 1
Machine B - Celery Worker 2
Machine C - RabbitMQ
I am able successfully configure the above setup without any error. But there is some delay and data loss (task missing) in the cluster setup

Example 
I put 5 task(t1,t2,t3,t4,t5) in queue.
Only t3, t4 is successfully executed, but t1, t2 and t5 got lost.

Reference: http://www.avilpage.com/2014/11/scaling-celery-sending-tasks-to-remote.html

Please suggest for clustering which one is better rabbitmq or redis?

I've looked on numerous blogs and forums and none of the solutions I found helped in my case.

**Comment by ask** [comment]
What do you mean by clustering?  You only list one RabbitMQ instance here?

Maybe the tasks were hijacked by a broken worker?  Have you properly shut down all old workers?
These can be left running in a misconfigured state, and is commonly seen when tasks disappear in a pattern (every n tasks, depending on the number of alive/broken instances).

Another possible reason is message routing problems.  Did you set up manual routing, or mess with the routing table in any way?  Flush the rabbitmq-server (removes all data!)

**Comment by mohitbhagwani94** [comment]
Sorry for the Late Reply.
My issue is solved there was no problem in configuration part. Due to some intranet issue, I was not able to get the task.
Everything is working fine.

Sorry for creating a useless issue.
