### ISSUE TITLE
Possible message typo

### ISSUE THREAD

**Issue by alexandrevicenzi** [celery/celery#3064]
I was just wondering if the message *Task can be retried* from [here](https://github.com/celery/celery/blob/master/celery/app/task.py#L625) wasn't to be *Task can't be retried*.

It's a little bit strange the error *Retry: Task can be retried*

**Comment by ask** [comment]
This error is only raised if the task is execute outside of a worker, or using .apply/always_eager:  It's up to the caller to decide.

This error can occur in the worker if somehow the task.request.called_directly flag is set for some wrong reason.

**Comment by alexandrevicenzi** [comment]
Yes @ask, I was just asking if the message is right, doesn't seem to be.
