### ISSUE TITLE
Supports AMQP heartbeat for async(eventlet/gevent) worker class

### ISSUE THREAD

**Issue by piglei** [celery/celery#3077]
Celery supports configurable [AMQP heartbeat](http://docs.celeryproject.org/en/latest/configuration.html#broker-heartbeat) feature, and it works well under prefork worker class. But when I using eventlet/gevent as worker class, it turns out this feature was completely disabled, in 2 ways:

- `Consumer.amqpheart` was set to 0 in [consumer.py](https://github.com/celery/celery/blob/master/celery/worker/consumer/consumer.py#L192-L198)
- Missing of `hub.call_repeatedly(heartbeat / hbrate, hbtick, hbrate)` like call under **asynloop()** function, which is the consumer looper function of eventlet/gevent mode.

IMHO, AMQP heartbeat is a nice feature, especially when I need quick broker failover under unreliable network condition. **So, why it's disabled for eventlet/gevent worker class? Are there any deeper reason/consideration?**

Thanks.

PS: Experimentally fixed this by adding `timer2.Timer().add_repeatedly(...)` in `asynloop` function, it worked.

**Comment by ask** [comment]
There's no reason really, it's just something that needs to be implemented.

I think someone started working on it, but they had a more ambitious attempt at using heartbeats
for tasks sending tasks, and publishing results also.

**Comment by ask** [comment]
Closed by 7193f391c3abac1b2a0de1b3175e1f2abddf095f
