### ISSUE TITLE
Revoke list causes unbounded memory growth

### ISSUE THREAD

**Issue by djsmith42** [celery/celery#3086]
Celery version tested: **3.1.16** and **3.1.20**
OS: **Ubuntu 12.04** (OS version should not matter)
Note: I am **not** using `--statedb`.

**Background:**

According to `celery/worker/state.py`, the revoke list should be limited to 50,000 entries after 3 hours:

```python
REVOKES_MAX = 50000
REVOKE_EXPIRES = 10800
revoked = LimitedSet(maxlen=REVOKES_MAX, expires=REVOKE_EXPIRES)
```

But this does not happen in practice.

**To reproduce:**

1. Revoke a lot of tasks (any ID will work):

  ```python
  app.control.revoke(['test-task-id-{}'.format(n) for n in xrange(100000)])
  # Revoking tasks one-at-a-time also reproduces the problem, but slower
  ```

2. Dump the revoke list:

  ```python
  for host, revokes in app.control.inspect(timeout=2).revoked().items():
        print host, len(revokes)
  ```

3. Come back 3+ hours later and revoke 1 task, and note that the list is still over 200,000.

**Workaround:**

If I modify the code like this, the tasks are limited to 50,000 in memory, no matter how many tasks I revoke:

```python
REVOKES_MAX = 50000
REVOKE_EXPIRES = None # Changed from 10800
revoked = LimitedSet(maxlen=REVOKES_MAX, expires=REVOKE_EXPIRES)
```

**Impact:**

Our production servers were using over 1GB of memory due to an accumulated 1 million revoked tasks after a few weeks of uptime. This became 15GB because we have 15 pre-fork worker processes which eventually re-spawned and inherited the 1GB of memory from the master process. In our cluster of 5 servers, restarting a server does not help because it mingles with the other servers on startup and reloads all the revokes into memory. We had to shut down every server in our cluster to get them all purged from memory.

**Quirks:**

When I play with `LimitedSet` in a Python shell, the expiration feature seems to behave as I expect. If I create a `LimitedSet(maxlen=3, expires=3)` and add 3 integers, wait 3 seconds, and add 1 more, there are only 3 integers in the set, as expected. I don't understand why this issue is manifesting like it is.

**Comment by djsmith42** [comment]
Here is a failing unit test. Did I understand how `LimitedSet` is supposed to work? If this test were passing, I think the unbounded memory growth would not be happening:

```python
from celery.datastructures import LimitedSet
from time import time

def test_limited_set():
    s = LimitedSet(maxlen=3, expires=10)
    s.add(1)
    s.add(2)
    s.add(3)
    s.add(4, now=lambda: time() + 11)
    assert len(s) == 3 # actual len: 4
```

**Comment by djsmith42** [comment]
Eureka! New finding.

If you change the steps above, and instead do this:

```python
for n in xrange(100000):
    time.sleep(1)
    app.control.revoke('test-task-id-{}'.format(n))
```

The revoke list does indeed stabilize at 50,000 and stop increasing. Note that I tested with `maxlen=50` and `expires=60`, and it actually stabilized at 60 (not 50).

So I think this might be working as expected, at least in Celery 3.1.20 (I didn't test this last case in 3.1.16).

**Comment by djsmith42** [comment]
Tested in 3.1.16, and it works the same. So I think this is probably a bug. If a bunch of revokes happen in rapid succession, they will never be purged, and it will lead to unbounded memory growth.

**Comment by djsmith42** [comment]
And I just learned that when workers mingle with each other and sync revoked task IDs, this resets the insertion date on each task ID, effectively restarting the timer on that task such that it won't be purged because it is now considered young.

When syncing revoked task IDs, I think Celery should **also** sync the insertion dates. I realize this would require a bit of re-work, but I think it's probably important in order to fix this.

@ask What do you think?

**Comment by alekibango** [comment]
hi guys, i reported the reason for this problem and proposed solution in issue #3095, noticed your issue later. i will later today try to send patch which will solve this for good.

**Comment by thedrow** [comment]
If I understand correctly https://github.com/celery/celery/commit/e0221e9f69a08674c8a019a90b224223560161f7 has fixed this issue.
Closing. Please comment if the problem persists.
