### ISSUE TITLE
allow specifying --backend from cmdline 

### ISSUE THREAD

**Issue by alekibango** [celery/celery#3091]
When you want to test somethign running against other then normal server, 
using cmdline is much easier then editing config.  Especially if config is imported from zipped file.

i would love to be able to use:

`celery worker --broker=...   --backend=...  ...`

Note: `--broker`  is already supported. So imho `--backend` should be added too. 

I would try to write code, but first please lets agree if this is good idea or not.

**Comment by ask** [comment]
Sounds like a good idea!  Please open up a pull request!
