### ISSUE TITLE
Feature request - Allow tasks to have a list of allowed hosts to accept messages from

### ISSUE THREAD

**Issue by dimm0** [celery/celery#3092]
With messages signing serializer enabled, I'd like to be able to specify the list of hosts which are allowed to execute the task. The sender host could be verified based on the signing certificate.

Is there a way to get such information from inside a task? If not, can I store the certificate information in context object?

I'd appreciate any tips on implementing this

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
