### ISSUE TITLE
Task from task on windows uses wrong broker

### ISSUE THREAD

**Issue by fatal10110** [celery/celery#3093]
Hi all, I have some issue on windows (linux and osx are ok) with subtasks...

I'm running some `@shared_task` (Let's call it task1) from my django project using `delay` to resize some image , then I'm running another `@shared_task`(Let's call it task2)  from task1, to upload the image.

```
@shared_task
def task1(*args, async=True):
     **resize**
     task2.delay(*images)

@shared_task
def task2(*args):
    ** upload **
```

task1 is using the right broker(connection) and also accepting tasks from it.(task1.app.connection()) - 
`localhost:6379` (redis)
But for some reason the task2 is trying to connect to wrong broker(task2.app.connection()) - `localhost:5672` (rabbit?).

```
$ python manage.py celery worker -A some_app

-------------- celery@office-comp v3.1.20 (Cipater)
---- **** ----- 
--- * ***  * -- Windows-10-10.0.10586
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         some_app:0x467e4a8
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     djcelery.backends.database:DatabaseBackend
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
-------------- .> celery           exchange=celery(direct) key=celery
```

What i'm doing wrong? it happens only on win machine :(

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
