### ISSUE TITLE
LimitedSet is not really limiting as it should be

### ISSUE THREAD

**Issue by alekibango** [celery/celery#3095]
in worker/control.py:
```py
Panel.register                                                                 
def hello(state, from_node, revoked=None, **kwargs):                            
    if from_node != state.hostname:                                             
        logger.info('sync with %s', from_node)                                  
        if revoked:                                                             
            worker_state.revoked.update(revoked)                                
        return {'revoked': worker_state.revoked._data,                          
                'clock': state.app.clock.forward()}
```
worker_state.revoked  is  LimitedSet.... used  in worker/state.py:
```py
revoked = LimitedSet(maxlen=REVOKES_MAX, expires=REVOKE_EXPIRES)```
```
where LimitedSet is defined in datastructures.py.

Problem is this: using update on LimitedSet will not purge old entries out.
When we add one item into LimitedSet, it will stay the same size (which could be > maxlen).
The only  way to make the size limited is to call method `purge()`

Unit tests on LimitedSet (in tests/utils/test_datastructures.py)  are not using `expires`, they only use LimitedSet(maxlen=...). Also there are no tests on `s2.update(s1._data)` -- like it is used in file `worker/control.py`

Examples:
```py
In [155]: s1 = LimitedSet(maxlen=5)

In [156]: for i in range(200): s1.add(i)

In [157]: s1
Out[157]: LimitedSet(5)
```

now with expires:

```py
In [158]: s_exp=LimitedSet(maxlen=5, expires=5)

In [159]: for i in range(300): s_exp.add(i)

In [160]: s_exp
Out[160]: LimitedSet(300)

In [161]: s_exp.add(500)

In [162]: s_exp
Out[162]: LimitedSet(300)
In [163]: s_exp.purge()

In [164]: s_exp
Out[164]: LimitedSet(5)
```
As you can see, until we call purge, the LimitedSet class is not really living up to its name. Sadly this can eat lots of memory,

**Proposed solution:**

1.  Few more Unittests are needed.
2. when LimitedSet object has expires, 
  - run purge after every update which will make it longer than maxlen.
  - run purge(limit=None) after every add,  if we are longer then maxlen when method add starts.

**Comment by alekibango** [comment]
the above code is with stable version, git version is different, but also wrong.
Git version will not remove items if they are not expired, even if we have too many of them.
It deletes only one on adding (if the first is expired), so the list can grow too.

Also, revoking gets dictionary of  {key: expires}, but just adds key -- so it will possibly never be expired when workers will talk to each other often enough,
Trying to figure out how to fix this.
Probably **enforcing max number of items will be best we can do** (do not allow more items if we overflow, even if they are not expired yet).

**Comment by thedrow** [comment]
https://github.com/celery/celery/commit/e0221e9f69a08674c8a019a90b224223560161f7 fixed this issue.
The problem has been fixed. Please comment if it isn't.
