### ISSUE TITLE
Consumer priority

### ISSUE THREAD

**Issue by Rajlaxmi** [celery/celery#3098]
Hi,
To implement data locality, I need consumer priorities in my celery - rabbitmq set up, i.e, consumer picking up tasks from certain queue with a preference.

I found that Rabbitmq supports consumer priority: [https://www.rabbitmq.com/consumer-priority.html]

In the rabbitmq example code (provided in the link), x-priority argument has been and provided to basicConsume. Can this be implemented in celery?

**Comment by Rajlaxmi** [comment]
How do I create multiple consumers of different priority for a specific queue?
Let's say I have two consumers: consumer1, consumer2.
Priorities:
consumer1's priority: celery - 0, hipri - 10
consumer2's priority: celery - 10, hipri - 0

**Comment by Rajlaxmi** [comment]
Thanks a lot!

**Comment by cepacia** [comment]
this infor is useful for me! thanks a lot!

**Comment by shkai** [comment]
CELERY_QUEUES = (
    Queue('celery', Exchange('celery', type='direct'), routing_key='celery',
          consumer_arguments={'x-priority': 0}),
    Queue('hipri', Exchange('hipri', type='direct'), routing_key='hipri',
          consumer_arguments={'x-priority': 10}),
)
run celey worker -Q celery,hipri. But they still consume according to polling.
I want queue hipri to consume before queue celery
