### ISSUE TITLE
Multi workers at different redis's vhost

### ISSUE THREAD

**Issue by wuyadong** [celery/celery#3101]
ENV:
flower   -> flower:0.8.4 tornado:4.2 babel:2.2.0
software -> celery:3.1.22 (Cipater) kombu:3.0.34 py:3.4.4
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
Redis 2.6.9

I'm testing our application, Flower shows two workers. 
![2016-03-09 9 58 57](https://cloud.githubusercontent.com/assets/1622276/13622952/e2a8ac9a-e5dd-11e5-9181-64766cdbf874.png)

The first celery worker is another application running on  ` redis://localhost:6379/4` . The second is my testing application running on ` redis://localhost:6379/2`.

At first, I wondered this flower's issue and i saw the flower's code, get workers list from celery:

```python
for name, worker in self.application.events.state.workers.items():
                info[name] = worker.alive
            self.write(info)
```

Debug trace :

![2016-03-09 10 16 45](https://cloud.githubusercontent.com/assets/1622276/13623268/5ca4f100-e5e0-11e5-8414-7288a814f5af.png)

Then, I used rabbitmq as broker and set different vhost. Flower only show one worker that i'm testing.

**Comment by ask** [comment]
Please see http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#caveats
