### ISSUE TITLE
The sender field in the celeryd_after_setup signal is not the hostname, as documented

### ISSUE THREAD

**Issue by rbarlow** [celery/celery#3104]
The documentation for celeryd_after_setup says that the sender parameter will be the hostname of the worker:

http://docs.celeryproject.org/en/latest/userguide/signals.html#celeryd-after-setup

However, on my test box it is different:

resource_manager@/root

My worker's name is resource_manager, but I am surprised to see nothing after the @ symbol and even more surprised to see the /root.

The example in that same documentation calls this the "node name", so perhaps that is really what is going on. I suggest that the documentation be fixed to match what is happening, but I also find the lack of hostname after @ to be a problem. This is on Fedora Rawhide with Celery 3.1.20.

**Comment by rbarlow** [comment]
I wonder if that /root is getting there instead of the hostname somehow? Could that be a bug?

**Comment by ask** [comment]
nodename/hostname is set by --hostname.  As far as I can tell, If that value is /root then you must either have set it explicitly or that is the value returned by `socket.gethostname`

**Comment by rbarlow** [comment]
Thank you for the pointer @ask. It turned out that systemd's %%h macro seems to be resolving to root on Fedora Rawhide and it is indeed being passed with --hostname. I apologize for the noise.
