### ISSUE TITLE
eventlet,CELERYD_MAX_TASKS_PER_CHILD not work?

### ISSUE THREAD

**Issue by meegoLi** [celery/celery#3105]
celery setting:
![image](https://cloud.githubusercontent.com/assets/13941825/13658125/4513dbd0-e6af-11e5-8a31-23682be4fc07.png)

memory is high!
![image](https://cloud.githubusercontent.com/assets/13941825/13658151/6c840014-e6af-11e5-8f0c-24aac9467c44.png)

This led worker to work very slowly.How to release the memory?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Eventlet pool does not support --maxtasksperchild, and we don't have the resources to implement it.
