### ISSUE TITLE
CELERY_TRACK_SENT ?

### ISSUE THREAD

**Issue by asmodehn** [celery/celery#3112]
Although my case might be a bit borderline, I find myself needing CELERY_TRACK_SENT = True.
That would do something similar to [CELERY_TRACK_STARTED](http://docs.celeryproject.org/en/latest/configuration.html#celery-track-started)
 but for the [task-sent](http://docs.celeryproject.org/en/latest/userguide/monitoring.html#task-sent) event.

Basically in a setup where there are much more tasks than worker (happens to me because my workers - robots - are always full with long exclusive tasks, not because I have a crazy amount of tasks), it becomes important to report to the user the amount of tasks in broker queues, so that he can react on it.

Examining the broker can be complex, depends on broker technology, and depends too much on architecture...

However if celery could write a "SENT" in the result DB (maybe with the options used to send it), the same way it writes a "STARTED" state, one could deduce the state of the broker queues just by checking the result database...

This is just an idea, but the main point is to be able to monitor the tasks that haven't reach a worker yet.

Note : In my case the "reserved" queue on worker is usually empty. Since workers can "disappear" from the network, keeping the tasks in queue on broker until the last moment (when they can be started) makes more sense I think... But then I am in need of a way to monitor it.

**Comment by ask** [comment]
You can quite easily add this using the `before_task_publish` signal:
http://docs.celeryproject.org/en/latest/userguide/signals.html#before-task-publish

```
from celery import states
from celery.signals import before_task_publish

@before_task_publish.connect
def store_pending_state(body, headers, **kwargs):
     task_id = headers.get('id') or body.get('id')
     app.backend.store_result(task_id, None, states.PENDING)
```

I don't really want to add this to core unless it's becoming a common pattern.

**Comment by asmodehn** [comment]
Indeed I was looking at events or signals to find where would be the best place to do this. I have a few bootsteps launched in different configurations... but having this signal connected directly in the app would ensure all task producer would have the same behavior.

Since I am using redis, I could also base64.decode the body of the each message in the queue, but using a before_task_publish signal seems cleaner.

Thanks a lot !

**Comment by asmodehn** [comment]
I realized a piece of information is missing here.
The goal is to be able to track the time and flow of a task ( mostly to report to the user / requester ): 
- it was sent to this queue at that time
- it was started by this worker at that time
- it was finished at that time.
There is not this kind of time information passed around from what I could see, so I'm implementing something custom.

**Comment by asmodehn** [comment]
I just realized this is the kind of information that is already exposed via flower.
So I'll change my python celery client to do REST requests and leverage flower implementation, instead of directly trying to get the data out of the backend DB.
Since I am looking at implementing some kind of user feedback anyway, it makes sense I think.

**Comment by ask** [comment]
Yeah, flower/events is the best tools for this job :)
