### ISSUE TITLE
Celery loglevel

### ISSUE THREAD

**Issue by jomach** [celery/celery#3113]
Hello guys, 

Wenn I run celery with : 

celery worker --loglevel=info --app=reds.tasks:app --environment=dev --local=True -Q celery,high_priority_queue,normal_priority_queue,low_priority_queue

wenn a task comes in i get  : [2016-03-11 11:33:23,914: DEBUG/MainProcess] TaskPool

Why is this happening ? It shouldn't because I started it with loglevel info. the problem is that  for every task that comes to the task pool all the args are dumped, some times in the args are sensitive information.

**Comment by jomach** [comment]
Just find out why. If you don't specify any --logfile the Mainprocess will be in debug mode.

**Comment by jomach** [comment]
So the problem is still there. If someone knows out to fix it..

**Comment by ask** [comment]
Logging is tricky to get right, and there are many libraries out there not following best practices.
Most likely some library is setting the loglevel of the root logger.

If the root loglevel is DEBUG there should be lots of debug messages at startup, not just
this message.  If it's only this message, then it may a bug in celery.

If all loggers are configured as DEBUG you would need to find what sets the level.
The only way to track who sets the level as far as I know, is monkey patching
logging.Logger.setLevel to print a traceback (you would have to monkey patch this before any libraries are loaded):

    import logging, traceback
    class DebugLogger(logging.Logger):
        def setLevel(self, level):
            print('>>> SET LEVEL: %r'  % (level,))
            traceback.print_stack()
            return super(DebugLogger, self).setLevel(level)
    logging.Logger = DebugLogger
```

This doesn't account for anything setting `logger.level = DEBUG` directly (bypassing setLevel), and also not `logging.Handler.setLevel` (not sure why that is possible).

There should be lots

**Comment by jomach** [comment]
Hi, 

So the whole workers are fine.  It is only really this message showing up.  So probably a Bug ? 

Regards.

**Comment by jomach** [comment]
I will try with the latest version of celery we are on 3.1 

Jorge Machado 
Jorge@jmachado.me

**Comment by jomach** [comment]
So I find out it was in our code with set_celery_logging_level....  is no bug.

**Comment by yanjiangdi** [comment]
how to fix this problem?

**Comment by yanjiangdi** [comment]
when I run celery with :

celery multi start w_online -A service.tasks  -c 8 --loglevel=FATAL --logfile=${LOG_PATH}/celery.log

when a task comes in i get : 
[2018-09-14 15:51:19,745: TRACE/ForkPoolWorker-1] End Calc [house_code:101103229329] [house_type:SELL] [Cost Time: 91 ms]

Why is this happening ? It shouldn't because I started it with loglevel TRACE. the problem is that for every task that comes to the task pool all the args are dumped, some times in the args are sensitive information.
