### ISSUE TITLE
CELERY_TIMEZONE issues

### ISSUE THREAD

**Issue by shridharkini6** [celery/celery#3115]
I tried setting timezone as CELERY_TIMEZONE= "Asia/Calcutta" , but doesnt returns actual time of this timezone. When my system time is 16:51, Cipator event shows it as 11:21....but from pytz library returns correct time.
>>> from datetime import datetime
>>> from pytz import timezone

>>> eastern = timezone('Asia/Calcutta')
>>> fmt = '%Y-%m-%d %H:%M:%S'
>>> loc_dt = eastern.localize(datetime.now())
>>> print(loc_dt.strftime(fmt))
2016-03-12 13:42:21

**Comment by ask** [comment]
What exactly does not return the time of this timezone?

**Comment by shridharkini6** [comment]
I expect Celery events to record time when Celery worker gets a request. When i modified the CELERY_TIMEZONE="Asia/Calcutta", it doesnt logs the actual time of Asia/Calcutta when it gets an request. Since Celery depends on pytz library for its time setting, i expect it to return the time for Culcutta region. But it returns some other timezone time.
Is there anyway to debug it...

**Comment by ask** [comment]
Python logging is separate and will just use the local time
