### ISSUE TITLE
Redis broker : specifying exchange in route fails

### ISSUE THREAD

**Issue by asmodehn** [celery/celery#3117]
I am using Celery 3.1.20 with redis v2.8.4.

This route works ( the queue is created in redis ): 
```
CELERY_ROUTES =
    'my_tasks.task1': {
        'queue': 'taskqueue'
    },
```

This route does NOT work ( queue not created - no visible error message ) : 
from http://docs.celeryproject.org/en/latest/userguide/routing.html#routers

```
CELERY_DEFAULT_EXCHANGE = 'topic_exchange'
CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_ROUTES =
    'my_tasks.task1': {
        'exchange': CELERY_DEFAULT_EXCHANGE,
        'exchange_type': CELERY_DEFAULT_EXCHANGE_TYPE,
        'routing_key': 'taskqueue'
    },
```

This route also does NOT work : 
```
CELERY_DEFAULT_EXCHANGE = 'topic_exchange'
CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_ROUTES =
    'my_tasks.task1': {
        'queue': 'taskqueue',
        'exchange': CELERY_DEFAULT_EXCHANGE,
        'exchange_type': CELERY_DEFAULT_EXCHANGE_TYPE,
        'routing_key': 'taskqueue'
    },
```

Wether I define:
```
CELERY_QUEUES =  (
    Queue('taskqueue',    routing_key='taskqueue'),
)
```
or
```
CELERY_QUEUES =  ()
```
doesn't seem to make any difference...

I am testing different way of routing tasks with redis, but I wasn't able to get exchange_type 'topic' and routing_keys from the router to determine which queue the task will end up in.

I realize having a [sscce](http://sscce.org/) would help but I didn't have time to investigate more.
I will just use queues and direct exchange for my usecase since I don't have many tasks, it will probably be enough for now.

**Comment by ask** [comment]
The queue is only declared if you specify `queue`.  Specifying only the exchange/routing_key pair means you bypass CELERY_QUEUES, though you can specify a list of entities to declare using `declare`.

Just like in amqp there's no error message if you specify an exchange/routing_key pair and the message is unroutable: use celery's automatic routing if you want safety.

This configuration works well for topic routing here:

```

from kombu import Exchange, Queue

CELERY_QUEUES = [
      Queue('topicq',
              exchange=Exchange('topicq', type='topic'),
              routing_key='test.*'),
]
CELERY_ROUTES = {
    'proj.tasks.add': {
        'queue': 'topicq',
        'routing_key': 'test.foo',
    },
}
```

Using topic routing is almost never needed though, so unless you have a compelling reason to I'd urge you to just use the automatic routing facilities!

**Comment by asmodehn** [comment]
Thanks for the detailed explanation.
I had assumed that declaring the queue in routes was not needed, if the routing key was matching on the same exchange as the ones setup in CELERY_QUEUES. My mental picture of celery configuration vs logical network topology might be off...
Anyway I ll come back to this only if I m stuck with automatic routing then.

**Comment by ask** [comment]
In that case the route needs to be declared by something else (e.g. a worker).

Most virtual transports don't support this, but redis does actually store the routing table in the database (with 4.0 and automatic routing it bypasses this completely, which is much faster)

If the queue was indeed declared, then I'm not sure why it wouldn't work, but it's possible that it has something to do with your example not using patterns (topic binding keys have globs like foo.*).
