### ISSUE TITLE
Dynamic worker for dynamic queue

### ISSUE THREAD

**Issue by mazlumagar** [celery/celery#3119]
Hi,
I'm creating dynamic queue on real time with django from the database changes.  After, I want assign different worker for these queues on real time. Can I do that? How?

Thank you..

**Comment by asmodehn** [comment]
I believe the answer is using a bootstep for each of your consumers. http://docs.celeryproject.org/en/latest/userguide/extending.html#consumer
You can then use it to decide when to listen to a queue with `consmer.add_task_queue` and `consumer.cancel_task_queue`

**Comment by mazlumagar** [comment]
Thank you for answer. 
But I did not understand How to use? Can you help?

**Comment by mazlumagar** [comment]
To be exact; What I need to do is to increase the number of workers dynamically (Suppose that I have 20 of them at start and I need to increase the number to 80) and assign new queues. I also do not want to use autoscale because I need to exactly specify which queue I want to use. The above example 'which I believe' does not increase the number of workers but allows me to assign queues dynamically.

**Comment by ask** [comment]
There are remote control commands for this, please see the Workers/Monitoring guide.  I think it's there, or if it's not there's source code in celery/worker/control.py for add_consumer/cancel_consumer.

**Comment by shwetabhsharan** [comment]
@mazlum Did you find a solution for this problem?
