### ISSUE TITLE
django-celery: last chord callback is not being called

### ISSUE THREAD

**Issue by embedded1** [celery/celery#3123]
I have the following workflow:

```py
work = chain(taskA, taskB)
return work()
taskB: creates the following workflow:
work = group(**group(taskC, taskD) | taskE), group(taskC, taskD**) | taskE)) | taskF
return work()
```

and the inner `group(bold)` creates another `group(taskG, taskH, ..) | taskV`
The problem I see is that `taskF` is not being called. all other inner tasks have completed.

I'm using latest `djang-celery`

does anyone know what went wrong?

Thanks

**Comment by rajadain** [comment]
See #3191 for potential workaround.

**Comment by bruno-rino** [comment]
This workaround worked for me! Thanks!

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Django.

**Comment by bruno-rino** [comment]
Even though the title of the issue starts with "django", it also happends with plain celery 3.1.23
