### ISSUE TITLE
support dynamic parameters for broker transport 

### ISSUE THREAD

**Issue by feifangit** [celery/celery#3124]
In the doc of `BROKER_TRANSPORT_OPTIONS`(http://docs.celeryproject.org/en/latest/configuration.html?highlight=broker_transport_options#broker-transport-options), it says,
```
A dict of additional options passed to the underlying transport.
See your transport user manual for supported options (if any).
```

My redis connection is killed by firewall at night because there's no data on over the connection.
I'm trying to set `socket_keepalive` and `socket_keepalive_options` (https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L475) to my underlying redis connection. but I found the parameters can not passed to redis. only few of them are supported in `celery`/`kombu`.

Did I miss something? Any existing configuration at celery level can handle the "idle connection be killed by firewall" issue?

Thanks,

**Comment by ask** [comment]
Fixed by celery/kombu@fbaf61f1eee2d074538e571428b676e679d1a424
