### ISSUE TITLE
Versions 3.1.22 and 3.1.23 are missing in a docs/history/changelog-3.1.rst

### ISSUE THREAD

**Issue by svetlyak40wt** [celery/celery#3126]

**Comment by svetlyak40wt** [comment]
But they somehow appeared at web version of documentation: http://docs.celeryproject.org/en/latest/changelog.html#version-3-1-23

What is the main source for the changelog in the documentation?

**Comment by ask** [comment]
The main source for the 3.1 Changelog is https://github.com/celery/celery/tree/3.1/Changelog

This will be merged back into docs/history/changelog-3.1.rst from time to time in the master branch.
