### ISSUE TITLE
Specify queue for callbacks

### ISSUE THREAD

**Issue by Chris7** [celery/celery#3127]
I am using send_task to call a task running on a remote machine (different codebase). However, the remote machine places the callback in the default queue. I would like to be able to specify which queue the callback is placed in, since the task is not present on the remote machine and thus raises an error.

I can fix this by proving CELERY_ROUTES in both applications, but this seems prone to error and additional upkeep versus being able to specify this with send_task.

Edit: I've found this can be achieved by linking signature() calls.

**Comment by ask** [comment]
This is possible as your edit states:
```
add.apply_async((2, 2), link=add.s(4).set(queue='foo'))
add.s(2, 2) | add.s(4).set(queue='foo'))
```
