### ISSUE TITLE
celery worker without consumers

### ISSUE THREAD

**Issue by obforfair** [celery/celery#3131]
Hi ，
I am use celery with redis as broker and run 60 command at a time,but sometimes receive this problem:
Traceback (most recent call last):
  File "/apps/home/rd/cron/.pycron/lib/python2.7/site-packages/celery/app/trace.py", line 299, in trace_task
    state, retval, uuid, args, kwargs, None,
  File "pycron/tasks.py", line 39, in after_return
    callback(status, kwargs['command'])
  File "pycron/util/tool.py", line 24, in task
    raise e
KeyError: u"Message for queue '3b8c4471-68dc-3414-b4af-9090b5807fc1.reply.celery.pidbox' without consumers: {u'body': u'eyJjZWxlcnkxQGFsLWJqLXNlYXJjaC1sb2dhbmFseXNpczAxOnB5dGhvbiI6IFt7ImV4Y2x1c2l2ZSI6IGZhbHNlLCAibmFtZSI6ICJweXRob246YWwtYmotc2VhcmNoLWxvZ2FuYWx5c2lzMDEiLCAiZXhjaGFuZ2UiOiB7Im5hbWUiOiAicHl0aG9uOmFsLWJqLXNlYXJjaC1sb2dhbmFseXNpczAxIiwgImR1cmFibGUiOiB0cnVlLCAiZGVsaXZlcnlfbW9kZSI6IDIsICJwYXNzaXZlIjogZmFsc2UsICJhcmd1bWVudHMiOiBudWxsLCAidHlwZSI6ICJkaXJlY3QiLCAiYXV0b19kZWxldGUiOiBmYWxzZX0sICJkdXJhYmxlIjogdHJ1ZSwgInJvdXRpbmdfa2V5IjogInB5dGhvbjphbC1iai1zZWFyY2gtbG9nYW5hbHlzaXMwMSIsICJhbGlhcyI6IG51bGwsICJxdWV1ZV9hcmd1bWVudHMiOiBudWxsLCAiYXV0b19kZWxldGUiOiBmYWxzZSwgImJpbmRpbmdfYXJndW1lbnRzIjogbnVsbCwgImJpbmRpbmdzIjogW10sICJub19hY2siOiBmYWxzZX1dfQ==', u'headers': {u'ticket': u'03b951a8-dfe6-4f2f-9693-0fe6c14ec378', u'clock': 11475}, u'content-type': u'application/json', u'properties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routing_key': u'3b8c4471-68dc-3414-b4af-9090b5807fc1', u'exchange': u'reply.celery.pidbox'}, u'delivery_mode': 1, u'delivery_tag': u'c8f787f9-aa51-40e0-88b3-5c09106d76fe'}, u'content-encoding': u'utf-8'}"

**Comment by ask** [comment]
This is fixed in 4.0rc

**Comment by arpheno** [comment]
I have exactly this problem. What should I do?
