### ISSUE TITLE
Thread Safe @after_setup_task_logger.connect call

### ISSUE THREAD

**Issue by timeu** [celery/celery#3133]
As far as I can tell the `@after_setup_task_logger.connect` is called for each task but shared among all worker processes. 
I am trying to use a custom LogHandler in order to send specific log message (ones that contain information about the progress of a specific task back to the RabbitMQ broker using [pika](https://pypi.python.org/pypi/pika) in order to display the progress on the client side). 

Something along these lines: 

```Python
class CeleryProgressLogHandler(logging.StreamHandler):

    def __init__(self,BROKER):
        self.BROKER = BROKER
        self.channel = None
        self._connect()
        logging.StreamHandler.__init__(self)
    
    def emit(self,record):
        if 'progress' in record.__dict__ and 'id' in record.__dict__:
            self._connect() # just in case if the connection is lost
            id = record.__dict__['id']
            queue = 'updates_%s' % id
            try:
                progress = record.__dict__['progress']
                msg = self.format(record)
                if 'task' in record.__dict__:
                    msg = record.__dict__['task']
                state = record.__dict__.get('state','RUNNING')
                body = {'progress':progress,'task':msg,'state':state}
                self.channel.basic_publish(exchange='',routing_key=queue,body=json.dumps(body))
            except Exception as err:
                print(err)
                pass
    def _connect(self):
        if not self.channel or self.channel.connection.is_open == False or self.channel.is_open == False:
            print('Connect')
            self.channel = pika.BlockingConnection(pika.ConnectionParameters(self.BROKER)).channel()
```

The nice thing about this approach is that I can use log messages this way: 

```Python
logger.info('Computing something',extra={'progress':50,'id':id})
logger.info('Finished Task',extra={'progress':100,'id':id})
```

This works fine as long as only one process is running on a specific worker. However as soon as multiple processes are running concurrently, I sometimes get error messages from the `channel.basic_publis` call: 

```
[2016-03-26 19:19:29,593: ERROR/Worker-2] Fatal Socket Error: BrokenPipeError(32, 'Broken pipe')
[2016-03-26 19:19:29,593: WARNING/Worker-2] [Errno 2] No such file or directory

[2016-03-26 19:19:29,724: ERROR/Worker-3] Fatal Socket Error: BrokenPipeError(32, 'Broken pipe')
[2016-03-26 19:19:29,724: WARNING/Worker-3] [Errno 2] No such file or directory
```

I belive this is because the pika connection is shared among multiple workers and [pika's connections are not thread safe](http://pika.readthedocs.org/en/0.10.0/faq.html). 

Currently I can only see 2 workarounds (neither of them very satisfactory): 

1. Run the worker with --concurrency=1 and run more workers (not best for scaling purposes)
2. Instead of using a LogHandler use a specific class that is instantiated when the task is run and send the message from there (more verbose because now I have log messages + calls to the that class and  I need to pass it to my other libraries)

Is there maybe another way to solve the issue of sending task progress updates to the RabbitMQ broker without relying to [custom states](http://celery.readthedocs.org/en/latest/userguide/tasks.html#custom-states). I can't really use custom states because I need to send the progress updates to a different queue.

**Comment by ask** [comment]
You would have to use one connection/loghandler for each logger, or use a connection pool in the
shared handler.

Using pika is not ideal in this situation as you cannot reuse connections in the existing kombu connection pool, so you will need less connections to the broker if you used kombu and `with app.connection_or_acquire()`

**Comment by timeu** [comment]
@ask Thanks for the info: 

So if I understood you correctly I can do something like this: 

```python
class CeleryProgressLogHandler(logging.StreamHandler):

    def __init__(self,app,analysis_type):
        self.app = app
        logging.StreamHandler.__init__(self)
    
    def emit(self,record):
        if 'progress' in record.__dict__ and 'id' in record.__dict__:
            with self.app.connection_or_acquire() as conn:
                exchange = Exchange('',channel = conn.channel())
                message = exchange.Message(json.dumps(body))
                exchange.publish(message,routing_key=queue)
```
I tried the above snippet and although it works, it seems to be quite inefficient to aquire a connection for each emitted log message. I guess there is no other way ?
