### ISSUE TITLE
Celerybeat cannot recover from DB OperationalError

### ISSUE THREAD

**Issue by bajhn** [celery/celery#3135]
Celerybeat seems to be unable to recover from an _OperationalError_ when the database goes away, but it won't die, either, so my supervisord doesn't restart it, leaving me ... stuck. I would love it if there were some way to tell celerybeat to restart on a database error, but it may also be a bug that bothers other people.

When I shut down mysqld during testing, I got this traceback, and even though I restarted the database, the error persists until celerybeat is restarted.

> [2016-03-25 16:29:26,104: INFO/MainProcess] Scheduler: Sending due task runs-every-60-seconds (myapp_statistics.tasks.update_reports)
[2016-03-25 16:29:26,106: ERROR/MainProcess] Database gave error: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/opt/myapp/env/lib/python2.7/site-packages/djcelery/schedulers.py", line 178, in schedule_changed
    transaction.commit()
  File "/opt/myapp/env/lib/python2.7/site-packages/django/db/transaction.py", line 42, in commit
    get_connection(using).commit()
  File "/opt/myapp/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 242, in commit
    self._commit()
  File "/opt/myapp/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
  File "/opt/myapp/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/myapp/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
OperationalError: (2006, 'MySQL server has gone away')

I'm running this environment:
Python 2.7.11
Django 1.9.4
djcelery 3.1.17
celery 3.1.19
MySQLdb 1.2.3 (the Python package)
MySQL server 5.1 (yeah, I know it's outdated)
CentOS 6.5 (customer requirement)

Here are what I believe are the relevant CELERY related variables from my setup:
```python
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend' 
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_ROUTES = {"myapp_background.tasks.update_reports": {"queue": "update_reports"}}
CELERYBEAT_SCHEDULE = {
    "runs-every-60-seconds": {
        "task": "myapp_background.tasks.update_reports",
        "schedule": timedelta(seconds=60)
    },
}
```

Here's the command line out of the supervisord config:
```ini
command=/opt/myapp/env/bin/python /opt/myapp/manage.py celerybeat -l info 
--pidfile=/opt/myapp/run/celerybeat.pid
```

Thank you for any wisdom you may provide.

**Comment by ask** [comment]
What broker transport are you using?

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Django.

**Comment by erez-rabih** [comment]
I am having the same issue.
Process is hung and no jobs are being performed.

I am using a Redis broker.

**Comment by dmk23** [comment]
Why is this being closed? This is a real problem

**Comment by chrisspen** [comment]
I also just started experiencing this after I upgraded to Celery 4.1.

**Comment by belek** [comment]
Same problem, any solutions?

**Comment by brianjsw** [comment]
This is a big problem causing outages in production for us as well.
