### ISSUE TITLE
Support for python 3.4 and 3.5 in celery 3.1?

### ISSUE THREAD

**Issue by edwardotis** [celery/celery#3143]
Hello,

The pypi docs say that the latest version of python3 to be supported by celery is 3.3.
https://pypi.python.org/pypi/celery/

The latest release of python 3.3 was 3.3.6, released on 2014-10-12
https://www.python.org/downloads/

Is this an oversight in documentation, or are Python 3.4.x and Python 3.5.x truly considered unsupported, untested versions of Python for Celery 3.1.x?

Thanks,

Ed

**Comment by ask** [comment]
The trove classifiers are already listing 3.4 as a version:

https://github.com/celery/celery/blob/3.1/setup.py#L75

The classifiers are sent to PyPI every time we make a release.

Not sure if it's safe to use 3.5 as a classifier yet, as PyPI often take months to add new ones.

**Comment by ask** [comment]
We'll just wait for the 4.0 release, as an incentive to get it out the door.
