### ISSUE TITLE
get_leaf() hangs when waiting for chords to complete -  djcelery.backends.database:DatabaseBackend

### ISSUE THREAD

**Issue by mikeengland** [celery/celery#3146]
I am trying to wait for a chord to finish using get_leaf(), however it seems to hang indefinitely. I am using the djcelery.backends.database:DatabaseBackend provided by the django-celery module. I have noticed that this project seems to be deprecated, however the Celery documentation states that it is needed to use Django Models as a back-end (http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html).

I tried the same code with Redis as a results back-end and it worked perfectly. Is there a chance this bug can get fixed or is it now recommended that we don't use django-celery and therefore not the djcelery.backends.database:DatabaseBackend at all (in which case, it should be removed from the Celery documentation.).

Thanks!

**Comment by mikeengland** [comment]
I have also tried this with djcelery.backends.cache:CacheBackend and MongoDB - both hang. RPC does not work with this use case as it doesn't support chords. However, using a Cache Results Back-end pointing directly to Memcached works fine as well as using a Redis Results back-end

**Comment by ask** [comment]
Sadly we don't have the resources to maintain the memcache result backend, so I have to close :(
