### ISSUE TITLE
problem with json serializer when mix chain and group

### ISSUE THREAD

**Issue by wtayyeb** [celery/celery#3154]
Hi.

Why the below snippest throw `EncodeError: keys must be a string` when using json serializer?

It works well with pickle serializer, but json serializer cannot do this simple workflow.

any idea or fix?

    @task
    def task1(msg):
        return msg + ' *'

    sig = task1.s() | group(task1.s(), task1.s())
    tsk = sig.apply_async(args=['text'])
    print tsk.get()

expected result is like pickle serializer result as below:

    [u'text * *', u'text * *']

using celery 3.1.23, python 2.7.6

[full traceback here](http://pastebin.com/yBKvEiuR)

**Comment by ask** [comment]
The Python json implementation does not allow for subclasses of dict, so the only solution right now is to use simplejson.
