### ISSUE TITLE
Revoked but not receive

### ISSUE THREAD

**Issue by obforfair** [celery/celery#3155]
Hi 
I was use celery 3.1.19, with two worker to receive a queue,and beat send one task every 10 minutes, task expires is 15s.but now have a question,sometimes worker will revoked task but no receive log , and the server is not busy.

the worker:
/apps/home/rd/cron/.pycron/bin/python -m celery worker -A pycron -c 800 -l info -Q cron -P eventlet --logfile=./tmp/cron_2.log --pidfile=./tmp/cron_2.pid --hostname=celery2@cron

this is my celery config:
BROKER_URL = 'redis://xxxx'
CELERY_RESULT_BACKEND = 'db+mysql:xxx'
CELERYD_CONCURRENCY = 1000
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_TRACK_STARTED = True
CELERY_SEND_TASK_SENT_EVENT = True
CELERY_DISABLE_RATE_LIMITS = True
CELERY_DEFAULT_QUEUE = 'cron'
BROKER_TRANSPORT_OPTIONS = {'fanout_prefix': True}
CELERY_TASK_RESULT_EXPIRES = 0

**Comment by ask** [comment]
If you're lucky the revoke check will happen before the received log actually.  I guess there's no reason not to log both.
