### ISSUE TITLE
Result Backend can't parse postgresql password with slashes in 3.1.23

### ISSUE THREAD

**Issue by lightcapda** [celery/celery#3156]
This issue appears related to [issue 3045](https://github.com/celery/celery/issues/3045) which resulted in [this fix](https://github.com/celery/celery/commit/f8bcdfed799e0e041118b19d450104e0eb761d9c).

Basically a celery postgres backend which contains a "/" in the password fails to parse the database port correctly.  This was functional in 3.1.19.  Example:

> db_user = "db_user"
> db_password = "+aaaa/zzzz"
> db_host = "db_host"
> db_table = "db_table"
> backend = "db+postgresql://{}:{}@{}/{}".format(
>     db_user,
>     db_password,
>     db_host,
>     db_table
> )
> celery.Celery(backend=backend)

Then, on startup, this error will occur:

> [2016-04-08 13:20:46,478: ERROR/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: '+aaaa'",)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/celery/worker/**init**.py", line 206, in start
>     self.blueprint.start(self)
>   File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
>     self.on_start()
>   File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 169, in on_start
>     string(self.colored.cyan(' \n', self.startup_info())),
>   File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 230, in startup_info
>     results=self.app.backend.as_uri(),
>   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 118, in as_uri
>     url = maybe_sanitize_url(self.url or '')
>   File "/usr/local/lib/python2.7/site-packages/kombu/utils/url.py", line 64, in maybe_sanitize_url
>     return sanitize_url(url, mask)
>   File "/usr/local/lib/python2.7/site-packages/kombu/utils/url.py", line 59, in sanitize_url
>     return as_url(*_parse_url(url), sanitize=True, mask=mask)
>   File "/usr/local/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url
>     return (scheme, unquote(parts.hostname or '') or None, parts.port,
>   File "/usr/lib64/python2.7/urlparse.py", line 113, in port
>     port = int(port, 10)
> ValueError: invalid literal for int() with base 10: '+aaaa'

Thank you for the support.

**Comment by Chronial** [comment]
Have you tried urlencoding it?

**Comment by thedrow** [comment]
Is this true with master?

**Comment by Chronial** [comment]
This is not a vaid bug. 

The URI `scheme://user:p/w@host:123/path` should be parsed as `scheme='scheme', host='user:p', path='/w@host:123/path'`.

The password part [is not allowed to contain slashes](https://tools.ietf.org/html/rfc3986#page-49), you need to percent-encode them.
