### ISSUE TITLE
Documentation: max_retries description error in the "Calling Tasks" docs

### ISSUE THREAD

**Issue by luyizhao** [celery/celery#3164]
See the description of the `max_retries` key here: http://docs.celeryproject.org/en/latest/userguide/calling.html#retry-policy

It states that `A value of 0 or None means it will retry forever.`. Believe that a value of 0 doesn't actually cause infinite retries though so the description should be changed to:
```
A :const:`None` means it will retry forever.
```

**Comment by ask** [comment]
Thanks!
