### ISSUE TITLE
celery.service and celery.conf don't work 

### ISSUE THREAD

**Issue by ifishlin** [celery/celery#3165]
Hi, I use the celery.service and celery.conf on centos 7
But I can't make it work, it always stop immediately and produce an empty log fie.
It confuses me that  I can run the same start command in shell but can't make it work in celery.service.
(I know there is a description in tutorial about this situation, but they can't run it in shell either)

In order to clearify problem, I make my celery.service as simpler as possible.
Here is my error msg.
```
??celery.service - Celery Service
   Loaded: loaded (/usr/lib/systemd/system/celery.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2016-04-13 11:23:05 EDT; 7s ago
  Process: 10543 ExecStop=/home/celery/py2.7/bin/celery multi stopwait test (code=exited, status=0/SUCCESS)
  Process: 10531 ExecStart=/home/celery/py2.7/bin/celery multi start test -A mysite (code=exited, status=0/SUCCESS)
 Main PID: 10541 (code=exited, status=0/SUCCESS)

Apr 13 11:23:05 localhost.localdomain systemd[1]: Starting Celery Service...
Apr 13 11:23:05 localhost.localdomain celery[10531]: celery multi v3.1.23 (Cipater)
Apr 13 11:23:05 localhost.localdomain celery[10531]: > Starting nodes...
Apr 13 11:23:05 localhost.localdomain celery[10531]: > test@localhost.localdomain: OK
Apr 13 11:23:05 localhost.localdomain systemd[1]: Started Celery Service.
Apr 13 11:23:05 localhost.localdomain celery[10543]: celery multi v3.1.23 (Cipater)
Apr 13 11:23:05 localhost.localdomain celery[10543]: > test@localhost.localdomain: DOWN
```

here is my celery.service.
```
Description=Celery Service
After=network.target

[Service]
Type=forking
User=celery
Group=celery
WorkingDirectory=/home/celery/mysite

ExecStart=/home/celery/py2.7/bin/celery multi start test -A mysite
ExecStop=/home/celery/py2.7/bin/celery multi stopwait test
ExecReload=/home/celery/py2.7/bin/celery multi restart test -A mysite

[Install]
WantedBy=multi-user.target

```

I always feel bad to setup celery on centos 7. Does anyone have clues? 

thanks

**Comment by DDevine** [comment]
I am seeing the exact same issue with a similar service file.

**Comment by DDevine** [comment]
Just found the solution. In my case it was that I did not specify a User/Group. Celery refuses to run workers as root. 
Try setting the environment variable C_FAKEFORK and seeing what errors are visible. If you must run as root you have to set C_FORCE_ROOT.

**Comment by ask** [comment]
Yeah, please try to run the service with the C_FAKEFORK environment variable set.  Daemonization problems are usually caused by permission problems.

**Comment by ask** [comment]
We don't have the resources to maintain a CentOS init script so it's been in removed in 4.0.
