### ISSUE TITLE
Rate_limit not imposing the limit specified

### ISSUE THREAD

**Issue by rusudorin** [celery/celery#3166]
I have two rabbitmq nodes each providing queues for 5 nodes who are running Celery.

Each of the 10 worker nodes run Celery with a concurrency of 4.

When I broadcast a rate_limit to each Celery, the rate does not seem to be the imposed one.

The code I use to broadcast the rate_limit:

> app = Celery('tasks', broker="amqp://%s:%s@%s/%s" % (config.rabbit_user, config.rabbit_pass, rabbit_ip, config.rabbit_vhost))
> 
> app.control.broadcast('rate_limit', arguments={'task_name': 'tasks.read', 'rate_limit': '100/s'})
> 

From my understanding this limit is per worker instance and not global, therefor I'm expecting 100 messages per second for each celery worker of the 10 nodes. Normally they are consuming about 500-600 per second, yet after the broadcast I get about 1.6 per second on every node. I checked the log and it's about 8 messages every 5 seconds.

Raising the limit to 200/s I'm getting anywhere between 2/s and 2.4/s.

I've tested with 12000/m, which would result in about 200/s, yet I'm getting anywhere between 2 and 3 per second.

**Comment by ask** [comment]
Closed by d23c8c297a27d872d44638a5b96a952af5332b80

**Comment by ask** [comment]
Note: requires celery/kombu@946c59c55953375ab72cd821335e21adc3293109

**Comment by MiracleYyds** [comment]
I ran into the same problem, I configured 'rate_limit': '128/s' and started 16 concurrent processes by default, but from the log printing, it seems that only 2 tasks are being processed per second

**Comment by auvipy** [comment]
> I ran into the same problem, I configured 'rate_limit': '128/s' and started 16 concurrent processes by default, but from the log printing, it seems that only 2 tasks are being processed per second. If I remove the limits and set worker_disable_rate_limits = True, all tasks are done almost instantaneously

would you mind sharing more detail of the versions of celery you are using? and any script & setup to reproduce your described issue?

**Comment by MiracleYyds** [comment]
thank you. Through many tests, when adding tasks quickly, the parameter countdown=1 is passed in, which can prevent multiple worker processes from processing only 2 or 3 tasks per second to a large extent. But the new problem is that when I add 256 tasks, almost always after the 190th, it becomes about 1 task per second.
**my env like this: python==3.11, celery==5.2.7**

**producer.py**

        
    from tasks import add
    import asyncio
   
    async def main():
        results = []
        for i in range(256):
            # result = add.apply_async(args=(3, 3), countdown=1, expires=1800)
            result = add.apply_async(args=(3, 3), expires=1800)   # without countdown, consumption would be slow
            results.append((i, result))
    
        for i, result in results:
            while not result.ready():
                await asyncio.sleep(0.1)
            print(i, result.status, result.get())
    
    
    if __name__ == '__main__':
        asyncio.run(main())


**tasks.py**

      from celery import Celery
      import time
      
      app = Celery('tasks', broker='redis://localhost:6379/0')
      app.config_from_object('celery_config')
      
      
      @app.task()
      def add(x, y):
          # time.sleep(0.05)
          return x + y

**celery_config.py**

        from kombu import Exchange, Queue
        
        broker_url = 'redis://localhost:6379/0'
        result_backend = 'redis://localhost:6379/0'
        result_expires = 60
        task_default_queue = 'default'
        
        task_annotations = {
            'tasks.add':
                {
                    'rate_limit': '10/s' 
                }
        }
        
        task_queues = (
            Queue('default', Exchange('default'), routing_key='default'),
            Queue('add', Exchange('add'), routing_key='add'),
        )
        
        task_routes = {
            'tasks.add': {
                'queue': 'add',
                'routing_key': 'add',
            },
        }

**Comment by MiracleYyds** [comment]
> > I ran into the same problem, I configured 'rate_limit': '128/s' and started 16 concurrent processes by default, but from the log printing, it seems that only 2 tasks are being processed per second. If I remove the limits and set worker_disable_rate_limits = True, all tasks are done almost instantaneously
> 
> would you mind sharing more detail of the versions of celery you are using? and any script & setup to reproduce your described issue?

thank you. Through many tests, when adding tasks quickly, the parameter countdown=1 is passed in, which can prevent multiple worker processes from processing only 2 or 3 tasks per second to a large extent. But the new problem is that when I add 256 tasks, almost always after the 190th, it becomes about 1 task per second.
**my env like this: python==3.11, celery==5.2.7**

**producer.py**

        
    from tasks import add
    import asyncio
   
    async def main():
        results = []
        for i in range(256):
            # result = add.apply_async(args=(3, 3), countdown=1, expires=1800)
            result = add.apply_async(args=(3, 3), expires=1800)   # without countdown, consumption would be slow
            results.append((i, result))
    
        for i, result in results:
            while not result.ready():
                await asyncio.sleep(0.1)
            print(i, result.status, result.get())
    
    
    if __name__ == '__main__':
        asyncio.run(main())


**tasks.py**

      from celery import Celery
      import time
      
      app = Celery('tasks', broker='redis://localhost:6379/0')
      app.config_from_object('celery_config')
      
      
      @app.task()
      def add(x, y):
          # time.sleep(0.05)
          return x + y

**celery_config.py**

        from kombu import Exchange, Queue
        
        broker_url = 'redis://localhost:6379/0'
        result_backend = 'redis://localhost:6379/0'
        result_expires = 60
        task_default_queue = 'default'
        
        task_annotations = {
            'tasks.add':
                {
                    'rate_limit': '10/s' 
                }
        }
        
        task_queues = (
            Queue('default', Exchange('default'), routing_key='default'),
            Queue('add', Exchange('add'), routing_key='add'),
        )
        
        task_routes = {
            'tasks.add': {
                'queue': 'add',
                'routing_key': 'add',
            },
        }

**Comment by auvipy** [comment]
I am not fully sure celery would behave properly with async await as of yet

**Comment by MiracleYyds** [comment]
With random blocking testing, I think I can probably understand this phenomenon. While this is the simplest example of testing, if rate-limit is enabled, there is an instantaneous task-count boundary problem when each task is run, if their execution times are very close together, then there is the illusion that only one or two task is processed per second
