### ISSUE TITLE
Celery instance don't update backend value due to cached_property

### ISSUE THREAD

**Issue by sofigern** [celery/celery#3171]
firstly I create instance
```
celery = Celery('tasks')
```
secondary, make update of configs
```
result_backend = 'redis://{host}:{port}'.format(**redis_conf)
    obj = {
        'BROKER_URL':
            'amqp://{username}:{password}@{host}:{port}/{virtual_host}'.format(
                **rabbit_conf
            ),
        'BROKER_POOL_LIMIT': 100,
        'CELERY_ACKS_LATE': True,
        'CELERY_DISABLE_RATE_LIMITS': True,
        'CELERY_RESULT_BACKEND': result_backend,
        'CELERY_TRACK_STARTED': True,
        'CELERY_TASK_RESULT_EXPIRES': 86400,  # 24 hours expiry
        'CELERY_TASK_SERIALIZER': 'json',
        'CELERY_QUEUES': queues,
        'CELERYBEAT_SCHEDULE': {},
    }
celery.config_from_object(obj)
```
and I get AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for' when I try get
```
celery.backend
```
It's because of cached property used. It became to work when I change this line to @property https://github.com/celery/celery/blob/master/celery/app/base.py#L1094

As quick hack I just delete properties before conf updating, as this 
```
    cached_properties = [member for member, _ in
                         getmembers(Celery, lambda m: isinstance(m, cached_property))]
    for member in cached_properties:
        delattr(celery, member)
```
but it's still silly bug for me anyway.

**Comment by ask** [comment]
The example you give here works well for me, most likely you must have accessed the backend before configuring the app, and this is not part of the example?

In general you shouldn't be using the app before it's configured (except for defining tasks that is)

**Comment by sofigern** [comment]
Yea, you are right. Trying to simplify example I've lost backend usage, sorry for this. But as I understand I can't make config_from_* operations before initialisation of Celery entity so I expect get new configurations by calling this methods for this entity either I've made property calls or haven't. As for me it's not clear delighted in method docstr. Or probably it would be moved into constructor if usage of it is not expected after initialisation. Thanks for the answer and your care to my problem!

**Comment by ask** [comment]
In master you can now make changes directly to `app.conf` without causing the app to be finalized.
