### ISSUE TITLE
Does Django broker still have these limitations ?

### ISSUE THREAD

**Issue by garyelephant** [celery/celery#3172]
I read from this [doc](http://docs.celeryproject.org/en/latest/getting-started/brokers/django.html) that using django as message broker having these limitations(especially the third):

The Django database transport does not currently support:

*    Remote control commands (celery events command, broadcast)
*    Events, including the Django Admin monitor.
*    Using more than a few workers (can lead to messages being executed multiple times).

**Comment by ask** [comment]
Yeah, the documentation is accurate

**Comment by ask** [comment]
Using Django SQL as broker is also no longer supported in Celery 4, as we don't have the resources to maintain it.
