### ISSUE TITLE
Celery task does not able to invoke ggplot2 functions.

### ISSUE THREAD

**Issue by saurabhraut** [celery/celery#3173]
invoking ggplot functions using 'grDevices' as follows does not work with celery tasks ,
grdevices = importr('grDevices')
grdevices.png(file=path_to_file, width=width, height=height)

it gives segmentation error as ,
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).

**Comment by ask** [comment]
This seems more like a fork-safety issue in the ggplot library, which are problems celery cannot do anything about.  It needs to be fixed in ggplot so that processes using fork can use it.
