### ISSUE TITLE
task time limits set through apply_async or app.control.time_limit are ignored in Celery 4.0.0rc2

### ISSUE THREAD

**Issue by aauroy** [celery/celery#3174]
Runtime set time limits seem to be ignored in Celery 4.0.0rc2. Setting up a global time limit through celery settings (such as `app.conf.task_soft_time_limit = 5`) seems to be working fine though.

##### celery report output
```
➜  celery -A tasks report

software -> celery:4.0.0rc2 (0today8) kombu:4.0.0a1 py:3.5.1
            billiard:3.5.0.0rc1 py-amqp:2.0.0rc2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: 'amqp://guest:********@192.168.99.100:5672//'
```

##### Sample code
```python
app = Celery('hello', broker='amqp://guest@192.168.99.100//')

@app.task
def sleeper():
    try:
        print('before sleep')
        time.sleep(10)
        print('after sleep')
    except SoftTimeLimitExceeded:
        print('timeout !')
```
##### With `Task.apply_async`
* Calling the `sleeper` task with `soft_time_limit=4` and `time_limit=7`:
```
>>> from tasks import sleeper, app
>>> sleeper.apply_async(args=[], kwargs={}, soft_time_limit=4, time_limit=7)
```
* Worker output (`sleeper` exec took 10 seconds):
```
[2016-04-21 16:45:33,687: INFO/MainProcess] Received task: tasks.sleeper[7e0f01fb-9303-43f6-9f55-bbbfa60e75d8]
[2016-04-21 16:45:34,097: WARNING/PoolWorker-4] before sleep
[2016-04-21 16:45:44,098: WARNING/PoolWorker-4] after sleep
[2016-04-21 16:45:44,101: INFO/PoolWorker-4] Task tasks.sleeper[7e0f01fb-9303-43f6-9f55-bbbfa60e75d8] succeeded in 10.003044539000257s: None
```
##### With `app.control.time_limit`
* Setting up new time limits with `app.control.time_limit`, then calling the `sleeper` task:
```
>>> app.control.time_limit('tasks.sleeper', soft=4, hard=7, reply=True)
[{'celery@xxxxxxxx.local': {'ok': 'time limits set successfully'}}]
>>> sleeper.apply_async()
```
* Worker output - the updated settings were received but the `sleeper` exec still took 10 seconds:
```
[2016-04-21 16:45:55,023: INFO/MainProcess] New time limits for tasks of type tasks.sleeper: soft=4 hard=7
[2016-04-21 16:46:04,655: INFO/MainProcess] Received task: tasks.sleeper[e823ca12-eabe-43a3-ab41-a624d35ad2a5]
[2016-04-21 16:46:06,151: WARNING/PoolWorker-7] before sleep
[2016-04-21 16:46:16,152: WARNING/PoolWorker-7] after sleep
[2016-04-21 16:46:16,154: INFO/PoolWorker-7] Task tasks.sleeper[e823ca12-eabe-43a3-ab41-a624d35ad2a5] succeeded in 10.003133935999358s: None
```

**Comment by ask** [comment]
Thanks for such a detailed and beautifully formatted report, it's appreciated!

**Comment by kharazi** [comment]
I'm using same version of code, but still ignoring it.

**Comment by wja513** [comment]
@ask @kharazi So do I:
1. Set time-limit like this,`celery -A proj --workdir=/opt/celeryproject control -d w1@hengyirong.com time_limit proj.tasks.sleep 5 6`,
2. Then execute `sleep.apply_async((12, ), timelimit=[5,4]) ` has no effect.

Only use decorator can works。
```python
@app.task(time_limit=12, soft_time_limit=12) 
def sleep(seconds):
    time.sleep(seconds)
```

Environment:
python3.5.2
celery4.0.2

**Comment by wja513** [comment]
@ask @kharazi So do I:
Task defination:
```python
@app.task
def sleep(seconds):
    time.sleep(seconds)
```
1. Set time-limit in an individual console,`celery -A proj --workdir=/opt/celeryproject control -d w1@hengyirong.com time_limit proj.tasks.sleep 4 5`.

> [2017-02-16 14:57:31,575: INFO/MainProcess] New time limits for tasks of type proj.tasks.sleep: soft=4.0 hard=5.0


2. Then execute `sleep.apply_async((10, ))`, **has no effect**,not raise exception.

> [2017-02-16 14:58:05,484: INFO/MainProcess] Received task: proj.tasks.sleep[524f7f4c-4480-4c5f-81c3-b64abcb292f2]  
> [2017-02-16 14:58:15,501: INFO/PoolWorker-1] Task proj.tasks.sleep[524f7f4c-4480-4c5f-81c3-b64abcb292f2] succeeded in 10.011694854998495s: None

3. But execute `sleep.apply_async((10, ), soft_time_limit=4, time_limit=5)` ,work as expected,`raise SoftTimeLimitExceeded`.
> [2017-02-16 14:59:53,670: ERROR/PoolWorker-1] Task proj.tasks.sleep[57d4f22f-1111-472e-a405-8e40f133243c] raised unexpected: SoftTimeLimitExceeded()


Environment:
python3.5.2
celery4.0.2

**Comment by kishan3** [comment]
My task is set up like this. But it's not taking custom time limit how do I achieve different time limits for different tasks?
```
@async_runner.app.task(
    name='advertiser_offers_verification_interactors.verify_advertiser_offers_async',
    time_limit=5400)
def verify_advertiser_offers_async():
    async_runner.send_task(
        task_fn=verify_all_advertisers_offers,
        queue='advertiser_offers_verification',
        options=async_runner.DEFAULT_RETRY_POLICY
    )
```
