### ISSUE TITLE
Logging per task ID

### ISSUE THREAD

**Issue by mekanix** [celery/celery#3182]
I'd like to implement logging of tasks to MongoDB but such that task ID is part of that document for later searching. If every task (and it's logs) are to be saved under one document, it sounds logical that I should be able to pass task ID somehow, but I can't find the way how. Is this even possible and if not, what would be recommended way of doing things like this?

**Comment by ask** [comment]
Using a task logger the ID and name of the task is included automatically:

    from __future__ import absolute_import, unicode_literals

    from celery.utils.log import get_task_logger
    
    logger = get_task_logger(__name__)

    @app.task
    def add(x, y):
        logger.error('foo bar')
