### ISSUE TITLE
Documentation issue: relevancy of Visibility Timeout for periodic tasks

### ISSUE THREAD

**Issue by edanayal** [celery/celery#3183]
Hi,
In http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html, I found: _"Periodic tasks will not be affected by the visibility timeout, as this is a concept separate from ETA/countdown"_
However, in my celery-redis system, I have a long periodic task (issued by beat) that does get retried after 1 hour because it did not yet complete. After extending the Visibility Timeout I can see that there's no retry after 1 hour.
So, I think this line in the documentation might not be accurate, or maybe it refers to some other case?
Thanks!

**Comment by ask** [comment]
This is documented in the caveats section here I think: http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html

Periodic tasks are just regular tasks scheduled by the beat service, the scheduling of the periodic tasks are not affected by the visibility timeout.  But if they have a countdown, or retries then the visibility timeout will matter just as for regular tasks.

Task retries are not related to the visiblity_timeout either, the only problem would be if the retry countdown/ETA setting is greater than the timeout.

**Comment by ask** [comment]
And oh, if you have acks_late enabled, then the task won't be removed until after it's finished executing.  This means that a long running task with acks_late=True may be redelivered.

**Comment by auvipy** [comment]
anyone up for updating the docs? or this should be closed?
