### ISSUE TITLE
Using Worker in same process of the main app makes tasks think they are called from another task

### ISSUE THREAD

**Issue by amol-** [celery/celery#3189]
I wanted to manage the Worker that runs the tasks in a separate thread of the same application that offloads them. The target is to replace previous `Thread().start()` calls to offload some work maintaining the same convenience with added guarantee of tracking and recovering tasks execution.

The issue is that `task_join_will_block` just reads a global module variable, so tasks think that they got called from inside another task and issue a warning.

I have been able to replicate the problem with this snippet:

```
import celery
capp = celery.Celery('testapp',
                     broker='mongodb://localhost/celery_test_broker',
                     backend='mongodb://localhost/celery_test_results')

import celery.app
celery.app.set_default_app(capp)

import threading
import celery.worker
worker = celery.worker.WorkController(app=capp, pool_cls='solo')
threading.Thread(target=worker.start).start()

# Wait for Worker to be fully up and running
import time
time.sleep(1)

@capp.task(name='testapp.sometaskwithresult')
def sometask_withresult(a, b):
   return a+b

# Update list of available tasks as task has been created after worker has started.
worker.reload()

print '\n\nRESULT:', sometask_withresult.apply_async((1, 2)).get(timeout=2)

worker.stop()
```

Running the snippet will lead to

```
.../lib/python2.7/site-packages/celery/result.py:45: RuntimeWarning: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

In Celery 3.2 this will result in an exception being
raised instead of just being a warning.

  warnings.warn(RuntimeWarning(E_WOULDBLOCK))


RESULT: 3
```

As this is currently just a warning I can probably ignore it as everything seems to be working as expected (as there isn't any task actually waiting for another task) but I'm concerned about the fact that it will be switched to an exception actually breaking this.

**Comment by ask** [comment]
I think the only way to solve that would be to make it the global thread-local variable
