### ISSUE TITLE
Tasks events don't ensure connection on broker failover

### ISSUE THREAD

**Issue by AndreLobato** [celery/celery#3190]
At the moment when using a RabbitMQ Cluster with mirrored queues there is a fail-over feature in the workers which will try to reconnect on the next subsequent queue. This is all great and is working fine. The problem comes when I have a task that send events during execution. So after loosing connection with the broker and fail-over to the next host, the task will fail, rising a exception of Connection lost. This maybe is a undesirable effect since a fail over should be transparent and not cause havoc in the running tasks.

So looking in the code is noticeable that the only problem comes from the [celery.events.Events.default_dispatcher](https://github.com/celery/celery/blob/master/celery/events/__init__.py#L433)  method which still returns a connection instance from the primary connection host, even if the worker has already switched to the next fail-over host. 

The solution is quite simple as the connection object have a method called "ensure_connection", and if called before passing to the Dispatched method, will use the correct connection string.

e.g.

```
@contextmanager
    def default_dispatcher(self, hostname=None, enabled=True,
                           buffer_while_offline=False):
        with self.app.amqp.producer_pool.acquire(block=True) as prod:
            prod.connection.ensure_connection()
            with self.Dispatcher(prod.connection, hostname, enabled,
                                 prod.channel, buffer_while_offline) as d:
                yield d
```

This is great but does not completely solve the problem, since is possible to send_event be called before fail-over complete, so is necessary a to handle the Connection error without rising a exception, maybe only issuing a warning?

So in the [Task.send_event](https://github.com/celery/celery/blob/master/celery/app/task.py#L758) method should handle the Connection Lost error

Would a PR be wanted for this case? 

I'm happy to do it, if this idea doesn't go against any design principle

**Comment by ask** [comment]
A patch would be good :)
