### ISSUE TITLE
Eventlet: app.control.inspect().active_queues() error

### ISSUE THREAD

**Issue by obforfair** [celery/celery#3193]
HI all:
I use celery 3.1.23
sometimes when app.control.inspect().active_queues()  cause this error:

load_queues 数据出错Traceback (most recent call last):
File "pycron/util/tool.py", line 16, in task
return f(_args, *_kwargs)
File "pycron/pycron.py", line 403, in load_queues
load_queues(retry)
File "pycron/util/tool.py", line 24, in task
raise e
RuntimeError: Second simultaneous read on fileno 26 detected. Unless you really know what you're doing, make sure that only one greenthread can read any particular socket. Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=; THAT THREAD=FdListener('read', 26, , )

**Comment by ask** [comment]
It looks like this is coming from pycron?

`active_queues` shouldn't cause anything in pycron to be called, so are sure this is not a traceback from a task executing at this point?  Is the trace back complete?

**Comment by auvipy** [comment]
can you verify this on master? adding this to celery 5 milestone for further investigation
