### ISSUE TITLE
Celery 4.0.0rc2 worker crash at startup with Windows

### ISSUE THREAD

**Issue by fbm** [celery/celery#3196]
Hi,

I'm trying to run a Celery Worker in a Windows 7 system.
`celery -A firstapp.mycelery worker --include firstapp.tasks -Q node_2`
=> worker crashes at launch

```
File "C:\Python27\Scripts\automate_it_agent\lib\site-packages\billiard\connection.py", line 40, in <module> WAIT_OBJECT_0 = _winapi.WAIT_OBJECT_0
AttributeError: type object '_multiprocessing.win32' has no attribute 'WAIT_OBJECT_0'
```

`celery -A firstapp.mycelery worker --include firstapp.tasks -Q node_2 -P solo`
=> worker works

Here is my package list

- alabaster (0.7.7)
- amqp (2.0.0rc2)
- anyjson (0.3.3)
- Babel (2.3.4)
- billiard (3.5.0.0rc1)
- boto (2.40.0)
- celery (4.0.0rc2)
- imagesize (0.7.1)
- kombu (4.0.0a1)
- pip (8.1.1)
- pytz (2016.4)
- requests (2.10.0)
- setuptools (20.10.1)
- six (1.10.0)
- vine (1.1.0)
- wheel (0.29.0)

**Comment by ask** [comment]
Sadly we don't have the resources to support Windows any more :(

**Comment by prog-rajkamal** [comment]
@fbm  did you manage to work around this issue? I am facing this exact issue, Any help is appreciated.

**Comment by fbm** [comment]
Hi,

Unfortunately no. 

Sorry, I can't help you.

Fbm

**Comment by auvipy** [comment]
@prog-rajkamal did you try the master branch?

**Comment by gautamkumar94** [comment]
use celery version 3.1.25 . celery haven given support to windows for version  celery==4.0 n above
