### ISSUE TITLE
Can't inspect SQS workers 

### ISSUE THREAD

**Issue by fbm** [celery/celery#3197]
I'm trying to inspect running workers using: 
`$ celery -A firstapp.mycelery inspect active`

If backend is RabbitMQ
=> Celery returns running workers
If backend is SQS
=> Celery returns "Error: No nodes replied within time constraint."

Package list:
- amqp (1.4.9)
- anyjson (0.3.3)
- billiard (3.3.0.23)
- boto (2.40.0)
- celery (3.1.23)
- contextlib2 (0.5.3)
- kombu (3.0.35)
- pip (1.5.6)
- pytz (2016.4)
- raven (5.15.0)
- setuptools (3.6)
- wsgiref (0.1.2)

**Comment by thiagofelix** [comment]
As described in the [docs](http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html)
> SQS does not yet support worker remote control commands

I also had hard time until find this information. Basically you can't inspect the state of any woker in the cluster.
You can keep a eye on CloudWatch or use [Redis](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html)/Elasticache as broken which has monitoring support.

**Comment by ask** [comment]
Yeah, SQS doesn't support broadcast and as far as I know no support for that is planned either :(

**Comment by thiagofelix** [comment]
Perhaps it would be also good to set [CELERY_ENABLE_REMOTE_CONTROL](http://docs.celeryproject.org/en/latest/configuration.html) to False when using SQS so you prevent celery from creating useless queues.
