### ISSUE TITLE
task decorator doesn't inherit from .Task in Windows

### ISSUE THREAD

**Issue by panuhorsmalahti** [celery/celery#3202]
The docs state "All tasks inherit from the app.Task class.", this works fine in Linux and Mac OS X, but for some reason it doesn't work in Windows for us.

Our current workaround is manually specifying the base class for the task:
```python
@celery_app.task(base=celery_app.Task)
```

We create the celery app like this:
```python
def create_celery():
    app = create_app(False)
    celery = Celery(app.import_name, broker=app.config["CELERY_BROKER_URL"])
    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask
    return celery

celery_app = create_celery()

@celery_app.task()
def run_task():
    # ...
```

Directly inheriting from the neutral base class celery.Task didn't work either. We're using Celery with Flask.

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
