### ISSUE TITLE
heartbeat/keepalive not work on Windows

### ISSUE THREAD

**Issue by mervynzhang** [celery/celery#3206]
If we enable amqp heartbeat, we get a lot of "Connection to broker lost", the same code works on Linux.

app = Celery('tasks', broker='amqp://192.168.99.102:32771?heartbeat=11')

[2016-05-15 14:31:36,997: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection

Could anyone help to fix this issue? Thanks

**Comment by mervynzhang** [comment]
BTW, I tested kombu on Windows, the same amqp connection's heartbeat works fine. So it looks like a celery issue.

    url = 'amqp://192.168.99.102:32771?heartbeat=11'
    with Connection(url) as conn:
        try:
            worker = Worker(conn)
            worker.run()

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
