### ISSUE TITLE
example init.d script has errors

### ISSUE THREAD

**Issue by tde3000** [celery/celery#3208]
> /etc/init.d/celery: 42: /etc/init.d/celery: [[: not found

because it's interpreted by sh and not bash

**Comment by alexkiousis** [comment]
You can add an x after the #!/bin/sh -e on the top line to get better output

**Comment by jonaldomo** [comment]
I'm having the same problem.  I added the X and can see this:

+ dirname /etc/init.d/celeryd
+ [[ /etc/init.d == /etc/rc0.d /etc/rc1.d /etc/rc2.d /etc/rc3.d /etc/rc4.d /etc/rc5.d /etc/rc6.d /etc/rcS.d ]]
/etc/init.d/celeryd: 42: /etc/init.d/celeryd: [[: not found
