### ISSUE TITLE
celery status can't find workers unless I add -A option

### ISSUE THREAD

**Issue by alexmojaki** [celery/celery#3209]
Please see http://stackoverflow.com/questions/37214056/how-do-i-run-celery-flower-without-the-a-option where I've explained the issue.

**Comment by ask** [comment]
celery will use the default configuration if no app option is set and no `celeryconfig` module is defined.  This is for backward compatibility with older version of Celery which did not have apps.

Configuration will affect the way celery uses the broker and queues, so make sure you always specify the app.
