### ISSUE TITLE
[django] Celerybeat issues crontab'ed task on invalid date after USE_TZ activated

### ISSUE THREAD

**Issue by lociii** [celery/celery#3219]
A celery task defined to be run once a month using celerybeat

`run_every = crontab(minute=0, hour=5, day_of_month=1)`

is run immediately (on the 17th) when we switched from

`USE_TZ = False`

to

`USE_TZ = True`

Does anyone know a reason for this behaviour? How can we prevent that in the future?

Thanks

**Comment by ask** [comment]
The regular celery scheduler stores a reference to the timezone used, and will wipe the schedule when it changes.  The Django database scheduler does not however, so if you change the timezone you need to clear the last_run_at fields in the database:

    PeriodicTask.objects.update(last_run_at=None)

**Comment by lociii** [comment]
Thanks for the answer. I still don't get why the task has been executed.

If I put some example code without timezone awareness
```python
from celery.schedules import crontab
import pytz

cron = crontab(day_of_month=1, hour=5, minute=0)
cron.nowfun = lambda: datetime.datetime(2016, 5, 17, 16, 0, 0, tzinfo=None)
last_run_at = datetime.datetime(2015, 5, 1, 5, 0, 0, tzinfo=None)
cron.is_due(last_run_at)
```
which results in
```python
schedstate(is_due=True, next=1249200.0)
```
what leads to
```python
datetime.datetime(2016, 5, 17, 16, 0, 0, tzinfo=None) + relativedelta(seconds=1249200)
// datetime.datetime(2016, 6, 1, 3, 0)
```
which is exacly 5am CEST that I expect

If I make the "now" value timezone aware
```python
from celery.schedules import crontab
import pytz

cron = crontab(day_of_month=1, hour=5, minute=0)
cron.nowfun = lambda: pytz.timezone('Europe/Berlin').localize(datetime.datetime(2016, 5, 17, 16, 0, 0))
last_run_at = datetime.datetime(2015, 5, 1, 5, 0, 0, tzinfo=None)
cron.is_due(last_run_at)
```
which results in
```python
schedstate(is_due=True, next=1256400.0)
```
what leads to
```python
pytz.timezone('Europe/Berlin').localize(datetime.datetime(2016, 5, 17, 16, 0, 0)) + relativedelta(seconds=1256400)
// datetime.datetime(2016, 6, 1, 5, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)
```
which is exactly the date I expect.

If I also make last_run_at timezone aware
```python
from celery.schedules import crontab
import pytz

cron = crontab(day_of_month=1, hour=5, minute=0)
cron.nowfun = lambda: pytz.timezone('Europe/Berlin').localize(datetime.datetime(2016, 5, 17, 16, 0, 0))
last_run_at = pytz.timezone('Europe/Berlin').localize(datetime.datetime(2016, 5, 1, 5, 0, 0))
cron.is_due(last_run_at)
```
which results in
```python
schedstate(is_due=False, next=1256400.0)
```
what leads to
```python
pytz.timezone('Europe/Berlin').localize(datetime.datetime(2016, 5, 17, 16, 0, 0)) + relativedelta(seconds=1256400)
// datetime.datetime(2016, 6, 1, 5, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)
```
which is exactly the date I expect.

I really don't get where it goes wrong. Sorry :-)

**Comment by ask** [comment]
hmm, I think maybe your test is too synthetic.  The behavior of `app.now()` changes when USE_TZ is False, if I remember correctly naive timezones are assumed to be in UTC and forced to be aware with timezone=pytz.utc

**Comment by ask** [comment]
In the database scheduler `obj.last_run_at = make_aware(obj.lasta_run_at)`.

The timezone handling should really be reviewed, it's a huge mess but every time I fixed a bug it broke for someone else, so it kind of escalated that way :)

**Comment by linar-jether** [comment]
See this issue for a workaround to schedule tasks at different timezones
https://github.com/celery/celery/issues/1139#issuecomment-192828732

**Comment by ask** [comment]
We are aware that this can be improved, but we don't have the resources to work on this in any foreseeable future :(

**Comment by rrauenza** [comment]
Came across a similar situation -- my interval based recurring tasks weren't getting triggered anymore after turning on USE_TZ.  Examination of the djcelery objects showed that last_run_at was now in the future... by about an hour I think. Which seemed odd because I'm in California...

Solved with...

```
for t in djcelery.models.PeriodicTask.objects.all():
    if t.last_run_at > timezone.now():
        t.last_run_at = timezone.now()
        t.save()
```
