### ISSUE TITLE
ImportError: cannot import name promise

### ISSUE THREAD

**Issue by j0hnsmith** [celery/celery#3225]
`pip install -r requirements.txt` where the content is

```
celery==3.1.23
librabbitmq==1.6.1
```

results in `amqp==2.0.0` being installed, which leads to

```
 File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/celery/app/base.py", line 19, in <module>
    from amqp import promise
ImportError: cannot import name promise
```

Installing just celery locks the `amqp` version appropriately.

**Comment by rraya** [comment]
+1

I have the same error

**Comment by ask** [comment]
Seems librabbitmq is breaking the version contract that kombu mandates: amqp>1.4,<2.0.

The quickest way to fix this currently is by adding that dependency in your project requirements:

<pre>
amqp>1.4,<2.0
</pre>

I will be working on getting a new release of librabbitmq out

**Comment by ask** [comment]
2.0.1 is out and should be compatible, but you really should be using amqp 1.4 still, as I'm seeing some kind of performance regression here (not sure if it's reproduceable elsewhere, investigating)

**Comment by rraya** [comment]
Thanks a lot for your time!

For the moment, I'm going to use ampq 1.4 and wait until see how evolve 2.0.X versions

**Comment by hackdna** [comment]
Looks like librabbitmq v2.0.1 is still not available: https://pypi.python.org/pypi/librabbitmq
