### ISSUE TITLE
[3.1.23] cannot abort a group of AbortableTask

### ISSUE THREAD

**Issue by samlesu** [celery/celery#3229]
I'm trying to abort a group of tasks and cannot achieve to do it.

I've implemented a simple producer using the *usage example* from the [documentation](http://docs.celeryproject.org/en/latest/reference/celery.contrib.abortable.html). 

It is working as expected when launching a single task.
But when launching a group of tasks, it appears that the results are of the class **AsyncResult** and not of the class **AbortableAsyncResult**.

I've been running the following code:
```
    results = group(long_running_task.s() for i in xrange(2))()
    print 'results: {}'.format(type(results))

    # abort the task after 3 seconds
    time.sleep(3)
    for result in results.children:
        print 'result: {}'.format(type(result))
        print isinstance(result, AbortableAsyncResult)
        result.abort()
```

And I've got the following output:
> result: <class 'celery.result.AsyncResult'>
> False
> Traceback (most recent call last):
>   File "producer.py", line 21, in <module>
>     result.abort()
> AttributeError: 'AsyncResult' object has no attribute 'abort'

Am I doing something wrong or this is an issue?

**Comment by ask** [comment]
`.children` is serialized using `AsyncResult.as_tuple()` and restored back, but it does not contain any information about what type of AsyncResult the result is, this would also be unsafe when using json.

I think the best way is to explicitly convert these into AbortableAsyncResult, or alternatively have an abort_task function instead:

    children = [AbortableAsyncResult(r.id, app=r.app) for r in results.children]

**Comment by samlesu** [comment]
Thanks for your prompt answer and the provided details.
Your solution is working perfectly.

**Comment by ask** [comment]
Btw, heads up Abortable task has been removed for 4.0.  Good news it's very simple to add the code to your project, or even publish an extension library to PyPI for others to share and maintain.  We just need to move some stuff out of Celery as it's taking a toll maintaining the lesser used features.
