### ISSUE TITLE
4.0.0rc2: 'from celery import *' fails in Python 2.7

### ISSUE THREAD

**Issue by akuchling** [celery/celery#3231]
`celery/__init__.py` does `from __future__ import unicode_literals`.  This means that __all__ contains Unicode strings, and Python 2.7 complains about it:

```-> python
Python 2.7.10+ (2.7:2a3c0ad52b99, Jul  6 2015, 12:10:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Item in ``from list'' not a string
>>> 
```

**Comment by ask** [comment]
I'm aware of this.  It's pretty silly how awkward this makes unicode_literals ;)

I don't know why anyone would do `from celery import *` though?
