### ISSUE TITLE
Worker name prefixed with @ and celery

### ISSUE THREAD

**Issue by m3talstorm** [celery/celery#3234]
```
$ celery -A testing worker --loglevel=info --hostname=worker1

 -------------- celery@worker1 v3.1.23 (Cipater)
---- **** -----
--- * ***  * -- Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         testing:0x7f0a67718b50
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . testing.add

[2016-06-04 00:58:14,821: INFO/MainProcess] Connected to redis://localhost:6379//
[2016-06-04 00:58:14,827: INFO/MainProcess] mingle: searching for neighbors
[2016-06-04 00:58:15,833: INFO/MainProcess] mingle: all alone
[2016-06-04 00:58:15,838: WARNING/MainProcess] celery@worker1 ready.
[2016-06-04 00:58:17,363: INFO/MainProcess] Events of group {task} enabled by remote.
```

Why is the worker name prefixed with **_celery@_** when I explicitly give it a hostname?

The examples for adding and removing consumers in: 

http://docs.celeryproject.org/en/latest/userguide/workers.html#queues

Will not work because of this

**Comment by ask** [comment]
`celery` is the default node name, you can set it as you please, e.g.:  `-n worker2@%h`.

The examples will work you just have to specify the fully qualified name, including the @.

**Comment by azhar31** [comment]
i am running the redis,celery worker,flask app server in docker, i am giving worker name =>the name of  my machine, i want to run some python script as a celery task which are available on the machine which i am using as the celery worker,when i calling the script ,it is giving error:path not found

**Comment by thedrow** [comment]
@azhar31 It's not possible to assist you in this fashion.
If you have a problem, please open an issue and mention this issue as a related issue.
