### ISSUE TITLE
celery, flask sqlalchemy: DatabaseError: (DatabaseError) SSL error: decryption failed or bad record mac

### ISSUE THREAD

**Issue by jainankit** [celery/celery#3238]
Related issues:
https://github.com/celery/celery/issues/1564 and
https://github.com/celery/celery/issues/634

I'm using celery 3.1.20 and having similar issue to the one mentioned above even though I'm closing the connection after each task:

```
@task_postrun.connect
def close_session(*args, **kwargs):
    # Flask SQLAlchemy will automatically create new sessions for you from 
    # a scoped session factory, given that we are maintaining the same app
    # context, this ensures tasks have a fresh session (e.g. session errors 
    # won't propagate across tasks)
    d.session.remove()

@task_prerun.connect
def on_task_init(*args, **kwargs):
    d.engine.dispose()
```

I'm still seeing this error. I believe this is related to celery forking and sharing a database connection, but then it should be fixed with above approach? Is there a way to force celery to create new database connection during fork?

Note that I'm running this on AWS (with two servers accessing same database). Database itself is hosted on it's own server (not RDS). The total celery background tasks running are 6 (2+4). Flask frontend is running using gunicorn. Also I see this behavior intermittently and not consistently.

**Comment by pyankoff** [comment]
+1, having the same issue

**Comment by claudiowilson** [comment]
having the same issue :/

**Comment by ask** [comment]
Fork-safety is really something that should be handled by SQLAlchemy and drivers, not a bug in Celery.

The Celery SQLAlchemy result backend uses `multiprocessing.util.register_after_fork`:

https://github.com/celery/celery/blob/3.1/celery/backends/database/session.py

Note that the first argument to `register_after_fork` is an object, and the second is the callback to call
after fork.  The callback will not be called If the object in the first argument is collected by the gc, so make sure you choose an object that is bound to the lifetime of the session.

**Comment by jainankit** [comment]
Thanks @ask but don't you think if this is an issue with forking, my above solution should fix it. `db.engine.dispose()` should dispose off all connections in pool and start afresh before every task. It's not ideal but that's what I tried to fix this issue. Where do you suggest I use `register_after_fork`?

Here's my main/__init__.py code

```
'''
Initialize Flask-Celery for background tasks.
'''
from celery import Celery

def make_celery(app):
    celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    TaskBase = celery.Task
    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask
    return celery

celery = make_celery(app)
```

**Comment by jainankit** [comment]
@ask please diregard my last message. I did a bit more reading. I still don't know why SQLAlchemy session would be reused considering I'm doing `session.remove()` after each task.

That said, what is the signal triggered after celery is done forking? Perhaps I should be re-initializing engine and session there? My understanding is `worker_process_init` should work based on:
http://docs.celeryproject.org/en/latest/userguide/signals.html#worker-process-init

What do you think?

**Comment by ask** [comment]
If it works outside of Celery then it's probably a forking issue :)

We've seen it several times before, even in something as ubiquitous as sqlite where a particular version on macOS, initialized a global struct in the parent process but did not clean it up for the child (or maybe it was cleaned but a global pointer to a member was remaining).  The result was a segmentation fault in that case, but it can manifest in any number of ways.

Could it be that some SSL variable defined in the parent remains after opening a new connection in the child, leading to the inability to decrypt this data?

**Comment by ask** [comment]
The `worker_process_init` signal should indeed be suitable, but using register_after_fork would also fix it for programs other than the celery worker.

**Comment by jainankit** [comment]
Interesting. Yes, the problem is only happening in celery, so most likely related to forking. I'm still wondering what difference does it make when sharing `session` vs sharing `engine` during fork. When I tried to recreate session using:
`db.session = db.create_scoped_session()`
before calling the task, it potentially solved the issue.
```

def __call__(self, *args, **kwargs):
        with app.app_context():
                database.session = database.create_scoped_session()
                try:
                    response = TaskBase.__call__(self, *args, **kwargs)
                finally:
                    database.session.remove()
                return response
```

My concern though is why did it not work if I instead just did:
`db.session.remove()` after the task. It should just create a new session on the next task?

PS: When I say it potentially solved the problem, I started having issues with exceeding the connection pool for db which can both be good or bad at this point :)

**Comment by claudiowilson** [comment]
I've fixed it for myself: I was being very silly and using the same application context. You should be using create_app to create the application context for your workers. @jainankit I suspect the same thing is happening to you. See my answer [here](http://stackoverflow.com/questions/37801766/correctly-managing-postgresql-connections-in-celery-task-for-flask-sqlalchemy-an)

**Comment by pyankoff** [comment]
Oh, seems like `with app.app_context(): database.session.remove()` fixed it for me too. Thank you!

**Comment by ask** [comment]
We should have a section in the documentation for Flask, maybe someone could just create a page for it and add this information there?

**Comment by jainankit** [comment]
@claudiowilson I'm not sure I follow. If you look at my code above your comment, I was already creating a new app_context for every task (in `__call__` method). The only thing I'm not doing is using "`create_app`" to create app context. I'm not sure if that affects it. So my code looks like this:

`app/__init__.py`
```
app = Flask(__name__)
app.config...
database = SQLAlchemy(app)
...

def make_celery(app):
  class ContextTask(TaskBase):
     abstract = True
     def __call__(self, *args, **kwargs):
          with app.app_context():
               return TaskBase.__call__(self, *args, **kwargs)
celery = make_celery(app)
```

`tasks/__init__.py`
```
from app import celery
@celery.task()
def do_something():
     send_message()
```

`app/views.py`
```
from app import app
import tasks
@app.route('/index')
def index():
    tasks.do_something.delay()
```

Since tasks/__init__.py is imported in views anyways, defining celery inside tasks shouldn't change anything. What do you think?

**Comment by claudiowilson** [comment]
@jainankit Yes, that would be the problem. SQLAlchemy is configured with the database from the app context in app/__init__.py. Each process should be using it's own application context. In the case of celery, you're sharing that same app context for each worker because you're only creating the application context once and reusing it. Each worker should have it's own application.

**Comment by jainankit** [comment]
@claudiowilson @ask I'm still not sure how initializing the app object using create_app solves this problem. It has to do something with the way celery is forked. Just switching from:

`app = Flask(__name__)`
to
```
def create_app():
  app = Flask(__name__)
  return app

def make_celery():
  celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
  return celery

app = create_app()

celery = make_celery()
```

should not change the behavior of the execution. How is it creating a new context in latter case for celery with forking? i understand if somehow we recreate the app_context in `worker_process_init` (after worker initialization).

**Comment by jainankit** [comment]
Thanks @claudiowilson can you share some of your code? I'm looking whatever is [here.](http://stackoverflow.com/questions/37801766/correctly-managing-postgresql-connections-in-celery-task-for-flask-sqlalchemy-an), and the main difference i see is you do `create_app` in `make_celery`. Does that mean the create_app is called twice for the web app (once when you call `create_app` when starting server and the other time when `tasks.py` is loaded and make_celery is executed?

Also depending on how fork is done, the worker might initiate the `celery` object with `make_celery` in tasks.py before forking as well?

Lastly is there a reason to pass `app=None` to `make_celery`, looks like you never pass `app` to the method, so it will always initialize new app context.

Appreciate your help.

**Comment by herman5** [comment]
@jainankit Did you get this resolve? I'm currently facing the same issue.

@claudiowilson any chance you could share some additional example code for your solution?
