### ISSUE TITLE
OOM command not allowed when used memory > 'maxmemory'

### ISSUE THREAD

**Issue by Skyross** [celery/celery#3239]
Hi guys!

Hope you can explain us some strange behavior that we are already solved in our ugly way.

We had some periodic tasks that used default queue `celery`. We have changed `CELERY_DEFAULT_QUEUE` to non-default. We using following configuration: Django + Celery + Redis. We using `celerybeat-schedule` file by default and it's wasn't ever cleaned. Also we didn't clear Redis after changing that variable. 
So we faced with that error and researched that our Redis raised up to limits of `used_memory` and our previous default queue `celery` was about 500Mb. So it's looks like it contains only periodic tasks and queue always growing up and never consumed by workers.

So our dirty solution: we manually cleaned  `celery` queue from Redis and deleted one `celery\x06\x16\x06\x16celery` value from `_kombu.binding.celery` set in Redis. So it's looks like fixed now.

Could you please explain or give us any feedback about the reasons and any kind of solution about this issue.

Kind regards,
Alexander

**Comment by ask** [comment]
Sounds like you simply routed the celerybeat tasks to the 'celery' queue instead of the queue you configured?  Did you remember to restart beat after the change of default queue?

**Comment by Skyross** [comment]
Thank you for that fast reply. We configured `CELERY_DEFAULT_QUEUE = 'low'` and added some non-periodic tasks to `CELERY_ROUTES` where we configured queue names only so we don't add any `routing_key` or `exchange` like it mention in [docs here](http://docs.celeryproject.org/en/latest/userguide/routing.html).
I'm found today that `celery` processes stopping in server update script by sending `SIGKILL` instead of `SIGTERM`. Could it be a reason of this problem?

**Comment by ask** [comment]
If you just change the default queue to `low` without adding an entry for that queue in `CELERY_QUEUES`, then you will keep the routing_key=`celery` and exchange=`celery` for this new queue also.

That means you have two queues with this exchange/routing_key pair, and messages will be delivered in duplicate to both queues. 

You should have configured the queue also, something like this:

    from kombu import Queue, Exchange

    CELERY_QUEUES = [Queue('low', Exchange('low'), routing_key='low')]

I'm guess this would be less of an issue in master where we don't use a routing table for simple name-to-name mappings in Redis anymore.
