### ISSUE TITLE
edit rdb telnet banner so it can be copy/pasted

### ISSUE THREAD

**Issue by jvanasco** [celery/celery#3243]
If using the remote debugger, the banner looks like this:

    Remote Debugger:6900: Please telnet into 127.0.0.1 6900.

This could be improved by *slightly* altering the string so it can be copy/pasted

This can't be copy pasted

    telnet into 127.0.0.1 6900.

but this can

    telnet 127.0.0.1 6900

https://github.com/celery/celery/blob/aee706ad5a743e3a51ed40f827bc02e61947902d/celery/contrib/rdb.py#L75-L80

    - {self.ident}: Please telnet into {self.host} {self.port}.
    + {self.ident}: Ready to connect: telnet {self.host} {self.port}

**Comment by ask** [comment]
That's a nice feature!  Note that you can edit code on github now and submit a pull request directly.  Would be happy if you could submit this :)

**Comment by jvanasco** [comment]
I'll just do a branch based PR.  I can't figure out the web ux ;/

**Comment by ask** [comment]
AFAIK you just go to the file in the github tree view, and click the "Pencil icon" next to the trashcan icon.  Have to admit I haven't used it myself, just have noticed people are using it often.

**Comment by jvanasco** [comment]
It does that by automagically forking with the edit.  I had an old fork I forgot about though, so I needed to somehow merge in the past 2+ years of changes via the Web UI... which I could not figure out.  It was easier to just do the old way.

**Comment by ask** [comment]
Ah yeah, the implementation in Github is rather awkward the way it creates a real fork :(

This issue is now fixed, thanks for helping out :)
