### ISSUE TITLE
Chord unlock in endless retry loop even though all previous tasks and callbacks succeed

### ISSUE THREAD

**Issue by manneorama** [celery/celery#3246]
## Versions

celery==3.1.20
kombu==3.0.35
billiard==3.3.0.23
amqp==1.4.9
pymongo==2.8.1
## Setup

Backend: MongoDB (Redis ran out of memory pretty fast)
Broker: RabbitMQ
Workers: 6 worker machines with concurrency set to 8

We're using celery as a framework for distributing a library to worker nodes for running tests on that particular library. Commonly, the task canvas looks something like this:

```python
# this code runs as a celery task of its own called 'bootstrap'
# takes a user spec and turns it into a task canvas
# generate canvas (groups are commonly not trivial, but consist of celery.chains internally)
groups, callbacks = generate_celery_tasks_from_spec(...)

# add callback or dummy task
visibe_chain = celery.chain([group | (callback or dummy.si()) for group, callback in zip(groups,     callbacks)])
# add another callback to notify user via slack
full_chain = celery.chain([visible_chain, notify_slack.si(**notify_kwargs)])

# go
full_chain.apply_async()
```

Since we discovered that letting unhandled exceptions bubble all the way up to celery itself will lead to chords that never unlock, we've taken the greatest care not to do that. Instead we catch all exceptions and celery thinks that all tasks are succesful.
## Problem

Even though we never let exceptions bubble up to celery, chords still hang now and again, for no apparent reason. Just now I'm looking at `celery inspect active` output and see two chord unlocks that have been bouncing around the system for 24+ hours even though no exceptions have been raised. If I keep doing `celery inspect active` I see that the chord unlock task just bounces around on different workers but never completes. This messes up our internal bookkeeping because our notification tasks are never executed, and is frankly extremely frustrating.
## Example of chord unlock bouncing around

http://pastebin.com/bKQC6US9

I would really appreciate any suggestions for how to debug this to determine if we are doing something we shouldn't be doing, since this is as business critical as it gets for us.

**Comment by thedrow** [comment]
Hi sorry this took so long to get attention.
Can you please provide the test case again?

**Comment by manneorama** [comment]
I’d rather have someone take a look at #3916 since we’ve switched back to redis+rabbit and I’m no longer able to easily repro this.

**Comment by auvipy** [comment]
closing for now, will open if any future reports
