### ISSUE TITLE
Falls back to amqp.transport ocasionally

### ISSUE THREAD

**Issue by Simanas** [celery/celery#3252]
Recently we dropped rabbitmq and now using only redis as our messaging broker and results backend. Unfortunately (0 - 5 % of times) celery still tries to use amqp.transport for adding delayed tasks and then throws [Errno 111] Connection refused error as we do not have rabbitmq on our server. 

It seems like this is happening more often when our app is under heavier load. We tired redis instances on the same and separate servers. No difference. 

Python 2.7, Django 1.8.

Why is this happening? Does anybody have any ideas as I am out of my list after struggling with this for more than a week.. :(

**Comment by Simanas** [comment]
somebody?

**Comment by ask** [comment]
Are you using @shared_task?

If you use `@shared_task` then you must make sure your app is created before using the task.
In the Django example this is done by adding "from .celery import app as celery_app` to `proj/__init__` so that the app is always created as soon as the project is imported.

**Comment by Simanas** [comment]
Yes I was using it and figured that @shared_task decorator might be causing this. I was using it in exact same way as recommended. Checked and verified that many times. Then about 6 days ago I dropped @shared_task decorator all together and now importing celery app directly. No more errors for these last 6 days... Hope it stays like this. 

So basically I switched from this:

```
from celery import shared_task

@shared_task
def my_awesome_task():
    print "Hey man!"
```

To this:

```
from core.celery import app as celery_app

@celery_app.task(bind=True)
def my_awesome_task():
    print "Hey man!"
```

`core` is just my project core module where I keep django settings, urls, wsgi and celery config files.

Let's just keep this open for a while until I can verify this really worked.

**Comment by Simanas** [comment]
Verified. This was due to @shared_task decorator. Never experienced the same issue since the change to direct celery app import. There is something wrong with it, moreover I would say that it adds to much of "rocket science" to celery... So it is very prone to x-files types of errors. I would suggest dropping it all together as it seems to me like it's braking a lot of [PEP 20](https://www.python.org/dev/peps/pep-0020/) patterns.

Celery is awesome!
