### ISSUE TITLE
inspect.reserved fails:  TypeError("unsupported operand type(s) for -: \'set\' and \'WeakSet\'",)'}

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#3256]
I added some periodic tasks, then tried to inspect them:

```
In [1]: from celery.task.control import inspect

In [2]: i = inspect()

In [3]: tasks = i.reserved()
In [4]: tasks
Out[4]: {'celery@stu-OptiPlex-790': {'error': 'TypeError("unsupported operand type(s) for -: \'set\' and \'WeakSet\'",)'}}
```

**Comment by ask** [comment]
Oops!

`WeakSet() - WeakSet()` creates a new WeakSet, and so does `WeakSet() - set()`, but I didn't
realize `set() - WeakSet()` would create a set which would have created concrete references.

I changed it by having both reserved_requests, and active_requests being WeakSets, and keeping
the concrete references in the `requests` dictionary instead.
