### ISSUE TITLE
backend value is not being passed through to get_backend_cls on some systems

### ISSUE THREAD

**Issue by bigease** [celery/celery#3257]
I have been having a problem for a few days where the configured value for the results backend was not working on my production server, but was on my development machine.

I have even tried to build a new production environment using the same versions of software/tools as the development machine, but this hasn't help.

There is a strong possibility that this is not a bug in Celery at all, but my digging has lead to the get_backend_cls function in the backends.**init**.py file.

It appears that the line:

`backend = backend or 'disabled'`

is always returning disabled on my non-working system, as if I change the 'disabled' to 'amqp' the results backend works as expected.

I have tried configuring the backend in the settings file and also passing it directly in when starting the Celery app, but it does not make any difference.

Happy to be shot down in flames here.  I am using...

Celery == 3.1.23
python == 3.5.1
django == 1.9.6

Please let me know if you need any further information.

**Comment by ask** [comment]
Are you on Windows?  I can only guess the CELERY_RESULT_BACKEND is not configured correctly, have you tried using `celery -A proj report` to see what the value is?

**Comment by btx** [comment]
I am experiencing a similar issue with Celery 4:
```
$ celery report -A myproject

software -> celery:4.0.0rc3 (0today8) kombu:4.0.0rc3 py:3.5.1
            billiard:3.5.0.0rc2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

...

CELERY_RESULT_BACKEND: 'redis://localhost:6379/3
```

**Comment by bigease** [comment]
Apologies for not getting back to you here,

No.  I am running both my development and production systems on Ubuntu 16.04

If I run the report command I cannot find any reference to CELERY_RESULT_BACKEND, so I suspect you are right.  I am setting the the backend when I initiate the Celery App in celery.py of my Django project.

I have also tried setting it in settings.py, but neither have worked.  It must be something I am doing.  Any ideas?

Thanks for you help

**Comment by ask** [comment]
@btx do you have an example config/app setup where this happens? Not able to reproduce here

**Comment by andyneff** [comment]
I'm getting the same issue at @btx. It seems to go to `disable://` when I change

    app.config_from_object('django.conf:settings')

to

    app.config_from_object('django.conf:settings', namespace='CELERY')

Celery 4.0.0rc3
Tried CELERY_RESULT_BACKEND = 'redis://localhost:6379/3' and 'amqp://' and 'rpc://', all result in disabled

(Got namespace argument from [here](http://docs.celeryproject.org/en/master/whatsnew-4.0.html#lowercase-setting-names))

**Comment by auvipy** [comment]
Can anyone verify this using 4.1 or master? 4.2 is also going to be release in this month so if possible plz verify with new versions and report
