### ISSUE TITLE
Fix for incorrect Command syntax in docs

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#3258]
The syntax for commands is slightly different to that shown here:

http://docs.celeryproject.org/en/latest/userguide/extending.html#adding-new-celery-sub-commands

Instead of
```
setup(
    name='flower',
    entry_points={
        'celery.commands': [
           'flower = flower.command.FlowerCommand',
        ],
    }
)
```

It uses a colon, like this:
```

setup(
    name='flower',
    entry_points={
        'celery.commands': [
           'flower = flower.command:FlowerCommand',
        ],
    }
)
```

**Comment by ask** [comment]
Thanks! I would think it works both ways since it's using `celery.utils.imports.symbol_by_name`, but I do try to use the `:` syntax consistently in the docs, so we should definitely change it!

**Comment by stuaxo** [comment]
I was triggering an error about using split with ':' when I tried that syntax.   I should have posted it here as well, but am not using the entry point any more anyway.

**Comment by stuaxo** [comment]
[deleted my comment here, as it didn't make sense :) ]
