### ISSUE TITLE
Option to reject/NACK all task failures

### ISSUE THREAD

**Issue by midnightlynx** [celery/celery#3261]
I'm attempting to arrange a way to reject failed tasks, so that if they're acks_late, RabbitMQ can send them to a Dead Letter Exchange. This includes when a retry is attempted, but the max retry limit is exceeded.

I've tried connecting to signals.task_failure, and raising a Reject exception there. It worked, but it felt hacky and cluttered the logs up with warning messages about 'RuntimeWarning: Exception raised outside body'.

I can do it manually with try/except blocks in my tasks, but then it would only work for MY tasks.

What I'd like is an app-wide configuration option that allows for all permanent task failures to NACK the task message, not just failures from raising Reject.

**Comment by midnightlynx** [comment]
From what I've seen in the code, I think the best place to put this behavior would be in the Request class's on_failure method, after the 'if self.task.acks_late:' check. Just adding an additional if/else to choose between self.acknowledge() and self.reject().

**Comment by ask** [comment]
Yeah, I don't think task_failure is a good place for this.  I'm surprised if Reject is even handled in this case as the `try:` block handling the Reject exception is around the task function, not the error handlers.  It could maybe make sense for an error handler to raise Reject, so we could consider doing that also.

The best place to add this in user code is probably using a decorator around the task function, but you could also contribute a setting to the `Request` class.

**Comment by ask** [comment]
Please open pull request :)
