### ISSUE TITLE
Unable to use celery inspect memdump / memsample

### ISSUE THREAD

**Issue by MacDschie** [celery/celery#3262]
Hi there,

some of my celery workers are eating lots of memory, so I tried to debug this with the `memdump` / `memsample` options of `celery inspect`. But it just gives me an error:

```
-> adnymics@kallisto: ERROR
        AttributeError("'Process' object has no attribute 'get_memory_info'",)
```

I use celery 3.1.23 and have installed psutil v4.2.0 (before that, I got the error that psutil cannot get imported). What is wrong here?

**Comment by ask** [comment]
Sorry for that! Fixed in master and 3.1 branches.  Seems psutil changed their API without adding backwards compatibility so it's now `Process.memory_info()`.

memsample is simply recording the current RSS usage of the process, and memdump dumps the history of samples.
