### ISSUE TITLE
How to use celery inspect objgraph?

### ISSUE THREAD

**Issue by MacDschie** [celery/celery#3263]
Hi there,

I try to debug some memory issue with one of my tasks. So I executed `celery inspect objgraph` to get some insight. This gives me the following message on the console

```
-> adnymics@kallisto: OK
    {
        "filename": "/tmp/cobjg7eOphu.png"
    }
```

It also takes a while until the command exits and produces a PNG file in the /tmp directory which is empty (file size 0). What about this? How is this command supposed to work?

**Comment by ask** [comment]
The `objgraph` command is something I've used in debugging leaks in the worker, but it only works for the parent process, not the processes executing the tasks. That is unless you're using the eventlet/gevent/solo pools.

You can look at the source code of that command and do the same thing in your task after allocating memory, but when debugging memory leaks in tasks it's better to do it locally outside of the worker.

**Comment by ask** [comment]
Btw, the type argument is `Request` by default, which will graph the backrefs to the workers celery.worker.request:Request objects.  If the file is empty then maybe there are no requests at the point when you send the objgraph command?  You can also change the type to graph other object types.

**Comment by johnyoonh** [comment]
I believe there is a bug or it is implemented improperly. Even with a task running, it always return 0. (celery v4.3.1) Currently trying to understand how objgraph works and try different parameters.
