### ISSUE TITLE
High memory & network usage when providing unique node names

### ISSUE THREAD

**Issue by odedfos** [celery/celery#3266]
I have a production environment with three hosts, each running 4 celery processes bound to various queues. Using rabbitmq as broker and latest celery version (3.1.23)
Normal system load is about 150 messages/sec published and consumed.
rabbitmq network throughput is about 30 Mb/sec

I did not set a unique name for the celery nodes, and was receiving a warning:
`A node named celery@export_000 is already using this process mailbox!`

After providing a unique name for each celery process the warning was resolved but the system become unusable due to very high memory and network usage.

Memory usage of the celery processes peaked (4GB -> 30GB) to whatever was available on the machine even for processes that weren't performing any tasks.
Network peaked to 0.5 Gb/sec even though there was no abnormal queue utilization. If anything, celery consumers did not consume any messages.

Consumers seems busy mainly syncing with each other (according to logs) and occasionally performing a few tasks.

Reverting back to the non-unique node names immediately solved the issue.

Any ideas?

**Comment by ask** [comment]
Workers should only sync with each other at startup, what sort of latency do you have on this network?

You should enable these two settings:

http://docs.celeryproject.org/en/latest/configuration.html#celery-event-queue-ttl
http://docs.celeryproject.org/en/latest/configuration.html#celery-event-queue-expires

That will ensure the event queues are not getting too deep for the workers to keep up.

**Comment by odedfos** [comment]
I enabled these options and event queues seem to be empty most of the time.
The problem however still occurs from time to time.
With no apparent reason, the celery workers start shifting large amounts of data, leaking growing ram and cpu while no tasks are consumed at all.

I'm not even sure what caused the system to eventually settle - I think perhaps shutting all celery processes and starting them slowly one at a time,

What does this sync step involve? can I disable it in any way until the issue is identified?
Is it bad practice to have multiple worker processes on the same host?

**Comment by thedrow** [comment]
I had multiple worker processes on the same host and I saw no such issues. I was running Celery 3.1.17 as far as I can recall.
We did see workers stop consuming tasks for long periods but that was related to the (now undocumented) autoscaling feature.

**Comment by ask** [comment]
You can disable the sync step by setting `--without-mingle`.  The workers also consume events from each other and you can disable that with `--without-gossip`.   Both of these options can be very expensive with a large amount of workers.

**Comment by ask** [comment]
Note, mingle syncs revoked tasks and logical clock values at startup.  Gossip keeps the logical clocks somewhat in sync.  The logical clock is by default only used for ordering monitoring events, they fall back to regular unix timestamps so is safe to disable.

**Comment by odedfos** [comment]
Adding these two flags results in numerous connection errors in the log files such as the following:

WARNING:celery.worker.consumer:consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/project_env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/project_env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/project_env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/project_env/local/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/project_env/local/lib/python2.7/site-packages/kombu/async/hub.py", line 279, in create_loop
    item()
  File "/project_env/local/lib/python2.7/site-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/project_env/local/lib/python2.7/site-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/project_env/local/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/project_env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "/project_env/local/lib/python2.7/site-packages/amqp/connection.py", line 303, in drain_events
    chanmap, None, timeout=timeout,
  File "/project_env/local/lib/python2.7/site-packages/amqp/connection.py", line 366, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "/project_env/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/project_env/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
error: [Errno 104] Connection reset by peer

**Comment by ask** [comment]
Are you sure all the workers are running the 3.1.23 version?  What other options do you have enabled? (on the command-line, and in configuration)

**Comment by odedfos** [comment]
Linux web-prod-1 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux

packages
celery==3.1.23
kombu==3.0.35
billiard==3.3.0.23
amqp==1.4.9
six==1.10.0

celery options:
    CELERY_SEND_EVENTS=False,
    CELERY_EVENT_QUEUE_TTL=10,
    CELERY_EVENT_QUEUE_EXPIRES=10,
    BROKER_HEARTBEAT=20,
    BROKER_POOL_LIMIT=10,
    CELERYD_HIJACK_ROOT_LOGGER=False,

cmdline options:
    --concurrency=5
    --maxtasksperchild=1000
    --queues=<some_queues>
    --loglevel=info
    --hostname=django_celery@%%h
    -Ofair

**Comment by odedfos** [comment]
Putting aside the connection errors that don't seem to impact production performance, the two flags actually prevent the problem from occurring.

Should be fixed nevertheless, but it least it is not a blocker anymore...

**Comment by auvipy** [comment]
plz reopen if it still the issue after new release
