### ISSUE TITLE
Prefetch Count Reaching 65536 which stops worker.

### ISSUE THREAD

**Issue by siddhika-tm** [celery/celery#3267]
We are facing a problem in our celery configuration in which workers PREFETCH_COUNT is continuously increasing and once it reaches 65536 ,the worker stop processing with error 
**QoS: Disabled: prefetch_count exceeds 65535**
We need to restart celery after this error and prefetch_count decreases to 14 after restarting

The value of CELERY_PREFETCH_MULTIPLIER is set default i.e 4 and autoscale is set to 128,4
We are using Redis as RESULT_BACKEND.
Celery version : 3.1.23

I've attached the **celery config file** (entry.txt) , result of **celery -A entry inspect stats**  (celery_inspect_stats) and result of **celery -A entry inspect conf** (celery_inspect_conf)

[celery_inspect_conf.txt](https://github.com/celery/celery/files/327271/celery_inspect_conf.txt)
[entry.txt](https://github.com/celery/celery/files/327272/entry.txt)
[celery_inspect_stats.txt](https://github.com/celery/celery/files/327273/celery_inspect_stats.txt)

Please let us know if there is some issue with the configuration.

**Comment by ask** [comment]
We're aware of the issue, but we are not able to work on it due to lack of resources :(

**Comment by callnothing** [comment]
i have same problem, hope somebody can get a good solution.

**Comment by ask** [comment]
Solutions to work on:

- https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

- Using a Redis sorted set to schedule tasks

**Comment by barbarakr** [comment]
I had the same problem, but I didn't observe that celery doesn't start any tasks at that moment. Fixed that by increasing the visibility_timeout (http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#id1) to match the longest ETA.
