### ISSUE TITLE
Using the C4 development process?

### ISSUE THREAD

**Issue by ask** [celery/celery#3276]
I'm really interested in trying this:

https://hintjens.gitbooks.io/social-architecture/content/chapter4.html

We cannot change the license used, but the rest of it seems like it could actually work, or at least be better than any alternative I can think of.

Merge pull requests as fast as possible, but force contributors to do smaller patches and limit the scope
of each pull request.

**Comment by dejlek** [comment]
If the code is well-tested (full code coverage), this will work.

**Comment by ask** [comment]
@thedrow @malinoff ?

**Comment by ask** [comment]
@ionelmc

**Comment by malinoff** [comment]
I don't mind, as long we won't use gerrit for code review :)

**Comment by ask** [comment]
There is no chance I will use either gerrit nor phabricator for an open source project :)

**Comment by ask** [comment]
Btw, as long as I have you here.  I've triaged all the issues today and added tags + moved most of them to milestones.  Please do tell me if I'm not using the current tagging system correctly :)

What needs to be done (or closed) before 4.0 has been moved into the 4.0 milestone.  There are many documentation issues there, most are really simple to finish.

**Comment by malinoff** [comment]
You mean labels? I think literally any solution will work, but I'm in favor of having less labels, but many repositories.
I.e. all "project governance" issues may be moved into `celery/governance`, documentation and all its issues may be moved into `celery/celerydocs` (while keeping docs folder in celery repo as submodule/subtree) etc. I think it will make the whole picture a little bit clearer, where a user should submit his issue, and it would be easier to maintain them.

**Comment by thedrow** [comment]
We have a [**waffle.io board**](https://waffle.io/celery/celery) that I made (I added too many columns just because I wanted to see what the current state is).
We can split to more repositories and use it to see the bigger picture.

**Comment by thedrow** [comment]
I have to read more about the C4 process. Looks cool.

**Comment by thedrow** [comment]
I still don't know about not having branches. I'll keep reading.
Some of it is really good.

**Comment by ionelmc** [comment]
I haven't read all the C4 guide but I already like two things from it:

* no topic branches
* preference to breakage over lost/slow contributions (or "move fast and break things" as I like to say).

**Comment by ionelmc** [comment]
Correct me if I'm getting it wrong but the big idea of C4 is that you either merge quick or you just close the PR and don't let the potential contributor do more work on a PR that won't ever get merged.

From the perspective of a contributor this is very appealing. For context: I have done a big PR on a project and maintainers just dragged the PR around, and did not merge, gave little feedback, but sure asked for lots of additional work with no interest in merging.  Was the most frustrating experience I ever had in open-source work.

**Comment by malinoff** [comment]
@ionelmc 
> From the perspective of a contributor this is very appealing

I suppose you meant "not very appealing" ;)
Nowadays github allows to specify issue/pr templates, I think we will be ok if these templates will explicitly (and using big letters) say about small changes, quick merges etc.

**Comment by ionelmc** [comment]
On Wed, Jul 13, 2016 at 4:22 PM, Dmitry Malinovsky <notifications@github.com
> wrote:

> I suppose you meant "not very appealing" ;)


​No, I mean exactly what I said. As a contributor it's better to have your
pr merged quickly than having it dragged around for weeks. Longer time to
merge means more context switching, more overhead and frustration IMHO.
