### ISSUE TITLE
Celery map problem

### ISSUE THREAD

**Issue by ztsv** [celery/celery#3277]
I have a list on id's:

l = [1, 2, 3]

so i need to call celery task for all of them:

```
for x in l:
   my_task.delay(x)
```

I use 

```
~my_task.map(l).apply_async()
```

and got error:

TypeError: bad operand type for unary ~: 'AsyncResult'

**Comment by ask** [comment]
You have the `~` operator there, but that only works on signatures, not on results.

`~sig` is the same as `sig.apply_async().get()`, but probably shouldn't be used in actual production code. It's just nifty in the REPL to save typing some characters ;)


Note also that map(list_of_n_items) does not call n tasks, it calls one task applying the task functions to each item in the list.

If you want to start n tasks you should use group:

   `group(my_task.s(i) for i in l).delay()`
