### ISSUE TITLE
celery-pidbox queues

### ISSUE THREAD

**Issue by sobhaduvvuri** [celery/celery#3280]
Hi,

I am using a combination of celery-kombu-SQS and see that celery-pidbox-queues are being created(1 per node) in addition to my actual default queues. 

Could anyone please let me know if there is an option to disable the pidbox queues from being created or any suggestions for workarounds like configuring the name of the pidbox queues are welcome. I have read that their creation is disabled by default in SQS but it is not. 

Any help around these lines to highly appreciated. 

Thanks,
Sobha.

**Comment by ask** [comment]
I don't remember if I fixed this in master or not, so please try using the development version first.

**Comment by sobhaduvvuri** [comment]
Is there a particular dev version that you would suggest?

Regards,
Sobha.

**Comment by ask** [comment]
Bleeding edge master, with `pip install -r requirements/dev.txt` from the celery repo.

**Comment by sobhaduvvuri** [comment]
I am sorry but I could not find any code changes you are mentioning, could you please point me to a particular pull request? Thanks so much

**Comment by sobhaduvvuri** [comment]
I tried to install the packages mentioned in requirements/dev.txt and am getting an ImportError on starting celery. 
This is the error that I am seeing: 

Traceback (most recent call last):
  File "/Users/sduvvuri/pydev/bin/celery", line 7, in <module>
    from celery.__main__ import main
  File "/Users/sduvvuri/pydev/lib/python3.4/site-packages/celery/__init__.py", line 133, in <module>
    from celery import five  # noqa
  File "/Users/sduvvuri/pydev/lib/python3.4/site-packages/celery/five.py", line 153, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
ImportError: No module named 'kombu.utils.compat' 

Could you please help??

Thanks,
SD

**Comment by ask** [comment]
I think this means you have installed celery yet!

In the celery repo you also need to do; `python setup.py develop`

**Comment by ask** [comment]
There's no pull request, I have radically rewritten the SQS transport.  The code for that is in kombu/transport/SQS.py, and kombu/async/aws + kombu/async/http

**Comment by sobhaduvvuri** [comment]
Hey, 

Thanks for your response. Do you think you will merge these changes to master?
Also, although I read quite a bit about it online, I am still confused. 

Is it Kombu/pidbox.py which creates these pidbox queues? If yes, then it says that auto_delete is true in get_queue() ? Why in spite of that are the queues not being deleted?

Thanks so much for all your help,

Regards,
Sobha.

**Comment by ask** [comment]
It's already in github.com/celery/kombu master, which is where the transports live.

Auto_delete is not actually supported by SQS so that doesn't help, we also don't want to create them
in the first place there as SQS does not support broadcast messaging.

Pidbox is the broadcast messaging system used by celery to support remote control of workers.

If the SQS support is still creating these queues in master, we can have the celery/worker/pidbox.py bootstep  component refuse to start if `'fanout' not in connection.implements.exchange_types`

**Comment by sobhaduvvuri** [comment]
Hi,

I wrote a very simple fix which worked for me in my local testing but the
build failed for some reason.
Please look at PR #3284 if you have some time and please let me know if my
fix makes sense and any insight into why the build is failing might help me
too.

Thanks,
Sobha.


On Wed, Jun 29, 2016 at 5:16 PM, Ask Solem <notifications@github.com> wrote:

> It's already in github.com/celery/kombu master, which is where the
> transports live.
>
> Auto_delete is not actually supported by SQS so that doesn't help, we also
> don't want to create them
> in the first place there as SQS does not support broadcast messaging.
>
> Pidbox is the broadcast messaging system used by celery to support remote
> control of workers.
>
> If the SQS support is still creating these queues in master, we can have
> the celery/worker/pidbox.py bootstep component refuse to start if 'fanout'
> not in connection.implements.exchange_types
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/celery/celery/issues/3280#issuecomment-229491469>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AROJZrRWBZEohQRyrUsNY6ZKQDj-12Yvks5qQuC5gaJpZM4JAa8F>
> .
>



-- 
Regards,
- Sobha.

**Comment by ask** [comment]
This should already be fixed AFAICT.  The celery.worker.consumer.control:Control bootstep should already be disabled if the transport does not support the fanout exchange type.
