### ISSUE TITLE
Celery Exception Inheritance

### ISSUE THREAD

**Issue by tkuester** [celery/celery#3283]
While writing a Flask application with Celery, I realized I had the need to catch task errors from celery.exceptions, among other things. However, it appears that most of the celery errors inherit from the root Python exception.

Would it be possible to have celery.exceptions.CeleryError that everything inherits from? This would make it much easier to differentiate problems.

Before:
```
task = task_depending_on_bad_connection.apply_async(args=(...))
try:
    task.wait(timeout=10, interval=0.1)
    print [x for x in task.collect()]
except (TimeoutError, MaxRetriesExceededError, RuntimeError, ...) as e:
    # Handle here
except Exception:
    # Pokemon Exception Handling
    # Catches celery errors, and some things I'd rather have crash like ValueError
```

After
```
task = task_depending_on_bad_connection.apply_async(args=(...))
try:
    task.wait(timeout=10, interval=0.1)
    print [x for x in task.collect()]
except (CeleryError, RuntimeError) as e:
    # Handle here
```

**Comment by ask** [comment]
It does have a CeleryError in 4.0, but Kombu and the amqp client errors do not inherit from this one.

That's one of the downsides of splitting your project into reusable components (there are of course many positive sides to that as well:)

I'm not sure if catching a CeleryError would be beneficial either way, as this would also catch `SecurityError` and `NotConfigured` errors.

Kombu does not remap exceptions but instead uses the pattern of defining a tuple of exceptions
for different scenarios, that the transport overrides, thus you can do:

```py

connection_errors = app.connection().connection_errors
try:
    task = task_depending_on_bad_connection.apply_async()
except connection_errors as exc:
    #handle connection error

try:
    task.get(timeout=10, interval=0.1)
except (celery.exceptions.TimeoutError, celery.exceptions.IncompleteStream):
    # handle timeout error.
```

I fear the exceptions for result backends may not be as mapped out as for the transport though,
but using Celery for RPC like this is not as common a use case.

**Comment by ask** [comment]
A better solution may be to add callbacks for these:

```py
task_depending_on_bad_connection.apply_async(on_connection_error=handle_connection_error)
```

with the same for the result, which in 4.0 really needs that since we are now extending the result API with async I/O support.

**Comment by ask** [comment]
Now you can do:

```py
try:
    add.delay(2, 2)
except add.OperationalError:
    pass
```
