### ISSUE TITLE
ETA Tasks - All workers stall

### ISSUE THREAD

**Issue by koizo** [celery/celery#3290]
Using RabbitMQ 3.4.1 and Celery 3.1.10

If we have many scheduled tasks, all the workers hangs.
We run with 40 concurrency.

Worker Logs:
Received task: app.tasks.start[dbedecb2-e23f-4cbb-9be2-e87547273680] eta:[2016-05-10 21:52:46+01:00]
Received task: app.tasks.start[2acc22ba-91f8-4a3b-a76b-e4fb5e403663] eta:[2016-05-10 21:59:48+01:00]

The only workaround is to increase the number of workers or to delete the tasks from rabbitmq.
Any ideas?

Thanks

**Comment by ask** [comment]
Please see http://docs.celeryproject.org/en/latest/changelog.html#version-3-1-11 !
