### ISSUE TITLE
shared_task does not respect 'retry' argument

### ISSUE THREAD

**Issue by ba1dr** [celery/celery#3295]
Following the user guide http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying ,
I used the following task definition

```
@shared_task(bind=True, retry=False)
def blabla_mytask(self, arg1, arg2, arg3):
    x = do_something()
    if not x:
        raise self.retry(countdown=60, max_retries=1000000)
    pass

```

Unexpectedly I get an exception: `TypeError: 'bool' object is not callable` on the line with `self.retry()`

While debugging, I found that `self.retry === False`.

I had to replace the definition with (`retry=False` to `max_retries=0`):

    @shared_task(bind=True, max_retries=0)
    def blabla_mytask(self, arg1, arg2, arg3):
        ...

It started to retry, but I am not sure if it is the same.

Why `retry=False` works not as described in user guide?

**Comment by ask** [comment]
There's no retry= argument to the task?  There's an execution option though .apply_async(retry=False) that will force it to not retry if the broker connection is lost.

**Comment by ba1dr** [comment]
I do not want to make it retry-able by default. it should not retry in case of error. But in certain cases the task itself may want to retry with the same arguments.
I can rewrite it to call itself with the same kwargs, but I thought it would be better to call `retry()` to keep the same task_id (will it save in case of retry?).

It seems `retry` is a instance method by default and when I set `retry=False` in the decorator - I redefine the instance method. It is not obvious and not mentioned in the documentation.
I am ok with the other way if there is a workaround to achieve my needs.

**Comment by ask** [comment]
Any argument to the task decorator will overwrite the attribute of same name on the resulting task class,
except for some options the task decorator handles specially.

There's no retry by default, so there is no reason to disable it!

**Comment by ba1dr** [comment]
Wait a minute..
http://docs.celeryproject.org/en/latest/userguide/tasks.html#Task.max_retries

> The default value is 3. A value of None will disable the retry limit and the task will retry forever until it succeeds.

As I got it from there - there is a default behaviour with retries in 3 attempts in case of exception.
That's why I used to explicitly disable retries: `retry=False`.

Could you please explain what the settings should be used for these 2 cases:
* retry the task by default in case of any exception
* do not retry at all, but be able to retry if the task itself asks for that

In the second case it seems I can set `retry=False`, but throw `Retry` exception if needed, am I right?

**Comment by ask** [comment]
I clarified the docs a bit: 7ce913791a0331c299ea9951c981fe1535271629

To retry a task  for any exception

In 4.0 you can do:

    @app.task(autoretry_for=(Exception,))
    def x():
        ...

In 3.1 you have to use:

    @app.task(bind=True)
    def x(self):
        try:
            ...
        except Exception as exc:
            raise self.retry(exc=exc)

The second doesn't really make sense, since you have to explicitly retry for any exception raised in the task, or for any other condition you set.
