### ISSUE TITLE
module docs link gives 404

### ISSUE THREAD

**Issue by vipul-sharma20** [celery/celery#3300]
After importing celery, `help(celery)` shows module docs link as [http://docs.python.org/library/celery
](http://docs.python.org/library/celery) which leads to 404

**Comment by ask** [comment]
I don't see that here, neither in 3.1 or master?

**Comment by ask** [comment]
I get this when installing celery 2.5, but not in celery 3.1 and not in master.

This link is for standard Python libraries, not for third-party libraries so I'm assuming that this is a bug in pydoc.  In any case it doesn't seem to happen in newer versions.
