### ISSUE TITLE
pip install of celery==3.1.15 is now requiring Kombu 4.0 necessitating Python 2.7

### ISSUE THREAD

**Issue by progressive-business-media** [celery/celery#3308]
[root@ip-10-154-148-145 ~]# /opt/python/run/venv/bin/pip install --use-mirrors celery==3.1.15
Downloading/unpacking celery==3.1.15
  Running setup.py egg_info for package celery
    - Trying to upgrade 'task' in 'celery.app'
    - upgrade task: no old version found.
    no previously-included directories found matching '*.pyc'
    no previously-included directories found matching '*.sw*'
Downloading/unpacking pytz>dev (from celery==3.1.15)
  Running setup.py egg_info for package pytz
    warning: no files found matching '*.pot' under directory 'pytz'
    warning: no previously-included files found matching 'test_zdump.py'
Downloading/unpacking billiard>=3.3.0.8,<3.4 (from celery==3.1.15)
  Running setup.py egg_info for package billiard
    warning: no files found matching '*.py' under directory 'Lib'
Downloading/unpacking kombu>=3.0.6,<4.0 (from celery==3.1.15)
  Running setup.py egg_info for package kombu
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/opt/python/run/venv/build/kombu/setup.py", line 11, in <module>
        raise Exception('Kombu 4.0 requires Python 2.7 or higher.')
    Exception: Kombu 4.0 requires Python 2.7 or higher.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/opt/python/run/venv/build/kombu/setup.py", line 11, in <module>

    raise Exception('Kombu 4.0 requires Python 2.7 or higher.')

Exception: Kombu 4.0 requires Python 2.7 or higher.

**Comment by ask** [comment]
The current release of Kombu 4.x on PyPI is 4.0.0rc3, a development version, that you need
to tell pip to install by adding the `--pre` option or by using `pip install 'kombu>dev'`

Pip for me here does not install that version, and Celery 3.1.15 even has a hardcoded dependency on `kombu<4.0`:

```
$> pip install celery==3.1.15Collecting celery==3.1.15
  Downloading celery-3.1.15-py2.py3-none-any.whl (513kB)
    100% |████████████████████████████████| 522kB 2.6MB/s
Collecting billiard<3.4,>=3.3.0.18 (from celery==3.1.15)
  Using cached billiard-3.3.0.23-cp27-none-macosx_10_6_intel.whl
Collecting kombu<3.1,>=3.0.23 (from celery==3.1.15)
  Using cached kombu-3.0.35-py2.py3-none-any.whl
Collecting pytz>dev (from celery==3.1.15)
  Using cached pytz-2016.4-py2.py3-none-any.whl
Collecting amqp<2.0,>=1.4.9 (from kombu<3.1,>=3.0.23->celery==3.1.15)
  Using cached amqp-1.4.9-py2.py3-none-any.whl
Collecting anyjson>=0.3.3 (from kombu<3.1,>=3.0.23->celery==3.1.15)
Installing collected packages: billiard, amqp, anyjson, kombu, pytz, celery
Successfully installed amqp-1.4.9 anyjson-0.3.3 billiard-3.3.0.23 celery-3.1.15 kombu-3.0.35 pytz-2016.4
```

Maybe you have a broken version of pip somehow?

**Comment by ask** [comment]
And with `--no-cache` in a fresh virtualenv:

```
(test-issue-3308) asksol@grain:~$> pip install --no-cache celery==3.1.15
Collecting celery==3.1.15
  Downloading celery-3.1.15-py2.py3-none-any.whl (513kB)
    100% |████████████████████████████████| 522kB 17.7MB/s
Collecting billiard<3.4,>=3.3.0.18 (from celery==3.1.15)
  Downloading billiard-3.3.0.23-cp27-none-macosx_10_6_intel.whl (110kB)
    100% |████████████████████████████████| 112kB 18.7MB/s
Collecting kombu<3.1,>=3.0.23 (from celery==3.1.15)
  Downloading kombu-3.0.35-py2.py3-none-any.whl (240kB)
    100% |████████████████████████████████| 245kB 18.2MB/s
Collecting pytz>dev (from celery==3.1.15)
  Downloading pytz-2016.4-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 18.5MB/s
Collecting amqp<2.0,>=1.4.9 (from kombu<3.1,>=3.0.23->celery==3.1.15)
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 27.8MB/s
Collecting anyjson>=0.3.3 (from kombu<3.1,>=3.0.23->celery==3.1.15)
  Downloading anyjson-0.3.3.tar.gz
Installing collected packages: billiard, amqp, anyjson, kombu, pytz, celery
  Running setup.py install for anyjson ... done
Successfully installed amqp-1.4.9 anyjson-0.3.3 billiard-3.3.0.23 celery-3.1.15 kombu-3.0.35 pytz-2016.4
```

**Comment by firstcloudconsulting** [comment]
I don't think it's pip - it is happening on 6 separate servers on AWS. And I do indeed see the requirement, "Downloading/unpacking kombu>=3.0.6,<4.0 (from celery==3.1.15)" but then it still throws the exception. I did create a new virtualenv with the same result. My pip version (1.1) does not support the --no-cache option.

**Comment by firstcloudconsulting** [comment]
Okay, not sure why but upgrading pip to version 8.1.2 does solve the problem. Earlier version of pip (1.1) does not work.

**Comment by auvipy** [comment]
please post this type of issue in user mailing list first.

**Comment by picklepete** [comment]
If anyone else encounters this issue: *you'll need to upgrade to at least pip==1.4* (`pip install --upgrade pip==1.4`). In 1.3.1 and earlier, for some reason "kombu>=3.0.15,<4.0" doesn't get interpreted properly, it keeps trying to install kombu-4.0.0rc4.tar.gz and raising:

> Exception: Kombu 4.0 requires Python 2.7 or higher.

Sadly it's hard to tell [from the release notes](https://pip.pypa.io/en/stable/news/#release-notes) what changed in 1.4 that allowed the operators to be interpreted properly.
