### ISSUE TITLE
celery 3.1.12 breaks on plain pypi install

### ISSUE THREAD

**Issue by patroqueeet** [celery/celery#3309]
requires: https://github.com/celery/celery/blob/v3.1.23/requirements/default.txt `billiard<3.4,>=3.3.0.23` but billiard only has: 
<img width="307" alt="screenshot 2016-07-10 22 45 11" src="https://cloud.githubusercontent.com/assets/2073086/16716283/ff25f224-46ef-11e6-9388-576aa7e2b37e.png">

am I missing something obvious or is there a reason why this should break?

**Comment by ask** [comment]
The tag was simply missing from Github.  Shouldn't have any effect on pip though, as this was already working for me:

```shell

$ pip install billiard==3.3.0.23
Collecting billiard==3.3.0.23
  Using cached billiard-3.3.0.23-cp27-none-macosx_10_6_intel.whl
Installing collected packages: billiard
Successfully installed billiard-3.3.0.23
```
