### ISSUE TITLE
app.task decorator does not retain function attributes

### ISSUE THREAD

**Issue by mabouels** [celery/celery#3311]
It seems that the app.task decorator does not preserve it's function attributes. 

The following code for example does not work:

```
# A simple decorator that stores the arguments 
# of the decorator as a function attribute
def newdecorator(*args):
    def decorator(func):
        func.newattribute = args
    return decorator

@app.task
@newdecorator('something')
def foo(): 
    pass

# This will throw an exception as the newattribute is not retained
# by the app.task decorator
print(foo.newattribute)
```

**Comment by ask** [comment]
Decorators don't usually do this in Python.  The practice is to use `functools.wraps`, which only copies `__module__`, `__name__` and `__doc__`.

In Celery 4.0 (or if you use Python 3) you will also have access to __wrapped__ which is the original function, so in your code looking for this `newattribute` you could do:

```py
    def getattr_wrapped(fun, name, *default):
        while fun:
            try:
                return getattr(fun, name)
            except AttributeError:
                fun = getattr(fun, '__wrapped__', None)
        if default:
            return default[0]
        raise AttributeError(name)
```

Example use:

```py

>>> class O(object): pass
>>> x.__wrapped__ = O()
>>> x.__wrapped__.__wrapped__ = O()
>>> x.__wrapped__.__wrapped__.__wrapped__ = O()
>>> x.__wrapped__.__wrapped__.__wrapped__.newattribute = 42
>>> getattr_wrapped(x, 'newattribute')
42
```

Other than that you could also reverse the decorator so the task decorator is applied first.

**Comment by mabouels** [comment]
Thanks you very much! I appreciate your suggestion.

Any idea when do you expect Celery 4.0 to be officially released?

Cheers

On Tue, Jul 12, 2016 at 2:34 PM, Ask Solem <notifications@github.com> wrote:

> Decorators don't usually do this in Python. The practice is to use
> functools.wraps, which only copies __module__, __name__ and __doc__.
>
> In Celery 4.0 (or if you use Python 3) you will also have access to
> *wrapped* which is the original function, so in your code looking for
> this newattribute you could do:
>
>     def getattr_wrapped(fun, name, *default):
>         while fun:
>             try:
>                 return getattr(fun, name)
>             except AttributeError:
>                 fun = getattr(fun, '__wrapped__', None)
>         if default:
>             return default[0]
>         raise AttributeError(name)
>
> Example use:
>
> >>> class O(object): pass>>> x.__wrapped__ = O()>>> x.__wrapped__.__wrapped__ = O()>>> x.__wrapped__.__wrapped__.__wrapped__ = O()>>> x.__wrapped__.__wrapped__.__wrapped__.newattribute = 42>>> getattr_wrapped(x, 'newattribute')42
>
> Other than that you could also reverse the decorator so the task decorator
> is applied first.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/celery/celery/issues/3311#issuecomment-232138161>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/APLFkLTqQCCCLazxmWt_HKFpuIrvVF2Fks5qU94ogaJpZM4JJ08W>
> .
>



-- 
-Mohamed

**Comment by auvipy** [comment]
@mabouels it's on rc3 now and you could try it in development and report if anything not working properly.
