### ISSUE TITLE
Celeryd ignores BROKER_URL in /etc/defult/celeryd

### ISSUE THREAD

**Issue by tayganr** [celery/celery#3313]
**Summary**

- I am running Celery as a daemon via celeryd ([as per instructions](http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html))
- Specified redis as the broker in the configuration file /etc/default/celeryd BROKER_URL="redis://localhost:6379/0"
- Worker log file indicates that BROKER_URL is being ignored as it is still attempting to connect to the default broker.

> ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@localhost:5672//: Error opening socket: a socket error occurred.

**Question:** Do I need to modify the /etc/init.d/celeryd file beyond the basic template that was provided in the online instructions in order for BROKER_URL to be passed as an argument?

In addition (not sure if this helps), but other properties such as **CELERY_ACCEPT_CONTENT=["json"]** also appear to be getting ignored as the log file continues to warn about W_PICKLE_DEPRECATED

**Comment by auvipy** [comment]
which OS you are using? seems you are using amqp broker

**Comment by ask** [comment]
@tayganr The `/etc/default/celeryd` file is not a configuration file per se, it's a shell script that sets environment variables for the celeryd/celerybeat init scripts.

There's no environment variable called 'BROKER_URL', but there's one called `CELERY_BROKER_URL`.

If you want to configure celery though you should do so by specifying configuration like in
http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#configuration

The environment variable is mostly there as a quick way to set the broker from the command-line in testing.
