### ISSUE TITLE
celery events displays wrong time.

### ISSUE THREAD

**Issue by outshow** [celery/celery#3316]
celery events displays wrong time with UTC zero timezone, not local timezone.

337f0643-06a7-4d10-867e-baf704fcc63b celery@Kepler-186f    add    08:37:52 SUCCESS
4662a488-4d04-4752-8fa4-ab9e58e637a2 celery@Kepler-186f   add    08:37:42 SUCCESS 
5e618b92-b2aa-43bc-8019-49cca426c64e celery@Kepler-186f    add    08:37:33 SUCCESS 

celery flower displays the correct time.

add 337f0643-06a7-4d10-867e-baf704fcc63b    SUCCESS [16, 16]    {}  '32'    2016-07-14 16:37:52.698 2016-07-14 16:37:52.729 celery@Kepler-186f
add 4662a488-4d04-4752-8fa4-ab9e58e637a2    SUCCESS [16, 16]    {}  '32'    2016-07-14 16:37:42.643 2016-07-14 16:37:42.674 celery@Kepler-186f

My local timezone is Asia/Shanghai, and my configuration as below:

CELERY_TIMEZONE = 'Asia/Shanghai'

celery version is 3.1.23 (Cipater)
Sorry for my pool English, is there anything wrong with my config?

**Comment by ask** [comment]
Is it the wrong time, or do you mean it's not converted to the timezone defined in the `CELERY_TIMEZONE` setting?

If so I don't think it was ever written to do so, maybe  you could submit a patch?

**Comment by outshow** [comment]
Yes, celery events did not convert the time to the timezone defined in CELERY_TIMEZONE.

**Comment by thedrow** [comment]
@outshow Any intention to write a patch for this one?

**Comment by roman-ku** [comment]
Was this ever fixed for Celery 3.1.25 (the last working Windows version)?

My celery listens to `CELERYD_CONCURRENCY` but not `CELERY_TIMEZONE`
