### ISSUE TITLE
an empty task costs some 5seconds time

### ISSUE THREAD

**Issue by julyclyde** [celery/celery#3319]
I'm running sentry 7.7.4 with celery3.1.18, pypy5.3.1 on CentOS 6.
I analyzed the celery INFO log, around the "succeed" lines, and discover that sentry.tasks.index.index_event usually cost 0.x seconds, but some of them cost 5.x , 6.x , 10.x or 11.x seconds. That task include just one "pass" statement in its function.
What caused this? and What information should I provide in additional?

**Comment by ask** [comment]
Hard to say without knowing more details about your configuration.  What result backend is used? What broker is used, what execution pool (prefork is the default).  Do you actually see the latency happening?

There's several things that happen before the task is run, but I'd suspect that storing the result after the task returns is the culprit.  Do you store results in Redis?

**Comment by julyclyde** [comment]
CELERY_RESULT_BACKEND is set to None, Sentry doesn't use result.
Broker is redis, and I use gevent pool now, because prefork pool used to be hanged after running for several hours.
I see the latency from INFO log, like
[2016-07-20 02:51:42,090: INFO/MainProcess] Task sentry.tasks.index.index_event[44655318-ff2b-4ba9-ba4e-f935f4444be7] succeeded in 5.70634574536s: None
[2016-07-20 02:51:42,798: INFO/MainProcess] Task sentry.tasks.index.index_event[a62832fa-3b7f-43de-b74e-50046435b4ab] succeeded in 0.242995033972s: None

**Comment by julyclyde** [comment]
then I search the ID from log:

> [2016-07-20 02:51:36,378: INFO/MainProcess] Received task: sentry.tasks.index.index_event[44655318-ff2b-4ba9-ba4e-f935f4444be7]
> [2016-07-20 02:51:36,379: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x49677d0> (args:('sentry.tasks.index.index_event', '44655318-ff2b-4ba9-ba4e-f935f4444be7', (<Event at 0xcad09d0: id=255782900, project_id=6, group_id=17398186>,), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (<Event at 0xcad09d0: id=255782900, project_id=6, group_id=17398186>,), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'search', u'exchange': 'default'}, 'expires': None, u'hostname': 'celery@dx-ops-sentry01.XXXXXXX.com', 'task': 'sentry.tasks.index.index_event', 'callbacks': None, u'correlation_id': '44655318-ff2b-4ba9-ba4e-f935f4444be7', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': '722dda99-f232-3ff4-afdb-01b7f16a57cf', 'id': '44655318-ff2b-4ba9-ba4e-f935f4444be7', u'headers': {}}) kwargs:{})
> [2016-07-20 02:51:36,387: DEBUG/MainProcess] Task accepted: sentry.tasks.index.index_event[44655318-ff2b-4ba9-ba4e-f935f4444be7] pid:10609
> [2016-07-20 02:51:42,090: INFO/MainProcess] Task sentry.tasks.index.index_event[44655318-ff2b-4ba9-ba4e-f935f4444be7] succeeded in 5.70634574536s: None

This shows a latency between Task accepeted and Task succeeded.

**Comment by julyclyde** [comment]
I flushed the redis buffer, and the whole Sentry works as brand new. This issue is not fault of celery.
