### ISSUE TITLE
nested canvas not working on celery 4

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3322]
The following canvas worked fine using celery 3, but fails in celery 4 (except for EAGER = True). To keep things simple, I am using a dumb task that just returns its second argument (ignoring its first argument).

```python
from __future__ import absolute_import, division, print_function
from celery import Celery, chain, group
from celery.utils.log import get_task_logger

app = Celery('canvasnested')
app.config_from_object('celeryconfig_eager')
# app.config_from_object('celeryconfig_redis_json')  # kombu.exceptions.EncodeError: Circular reference detected
# app.config_from_object('celeryconfig_redis_pickle')  # returns correct value, but last task gets executed infinite times
# app.config_from_object('celeryconfig_rabbit_json')  # kombu.exceptions.EncodeError: Circular reference detected
# app.config_from_object('celeryconfig_rabbit_pickle')  # waits forever on "Task celery.chord_unlock[0dfe47bb-...] retry: None

logger = get_task_logger(__name__)

@app.task
def mytask(x, y):
    print(y)
    return y

if __name__ == '__main__':
    t = chain([
        mytask.s(0, 1),
        group([
            mytask.s(5),
            mytask.s(6),
        ]),
        mytask.s(9),
    ])
    result = t.apply_async()
    print(result.get())
```

When the serializer is set to 'json', I get "kombu.exceptions.EncodeError: Circular reference detected". So that might be a kombu bug.

But when serializer is set to 'pickle', I get more interesting bugs: redis returns the correct answer (9), but the worker process keeps on executing the last task infinite times; rabbit mq, on the other hand, won't execute the last task, as it keeps receiving a "celery.chord_unlock" task every two seconds.

I am using python 2.7.10, RabbitMQ 3.6.1, Redis 3.2.1. 

My source files, including the celeryconfigs:
[canvasnested.zip](https://github.com/celery/celery/files/371021/canvasnested.zip)

**Comment by bruno-rino** [comment]
I was looking into (explicit) chords, and ended up isolating these bugs into three separate reports: #3330, #3331, #3332.

**Comment by thedrow** [comment]
@bruno-rino Because you isolated this to 3 bugs I'm gonna close this one.
