### ISSUE TITLE
redis password include "#" | 使用redis时密码包含#异常

### ISSUE THREAD

**Issue by zhanghangorg** [celery/celery#3327]
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10:

o = urlparse('redis://:test#TEST@172.22.1.44:2000/1')
>>> print 0
0
>>> print o
ParseResult(scheme='redis', netloc=':test', path='', params='', query='', fragment='TEST@172.22.1.44:2000/1')

**Comment by zhanghangorg** [comment]
password = test#TEST

**Comment by ask** [comment]
你必须URL编码密码

```py
>>> urllib.quote('test#TEST')
test%23TEST

BROKER_URL = 'redis://:test%23TEST@172.22.1.44:2000/1'

```
