### ISSUE TITLE
Task.replace() does not return results when CELERY_ALWAYS_EAGER = True

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3329]
When CELERY_ALWAYS_EAGER = True, tasks are executed as expected, but the return value is missing. As a test, see this sample code adapted from #817:

``` python
from celery import Celery

app = Celery('hello')
app.conf.CELERY_ALWAYS_EAGER = True

@app.task(bind=True)
def hello(self):
    print('hello...')
    raise self.replace(goodbye.s())
    print('world')

@app.task
def goodbye():
    print('later...')
    return 'good bye!'

if __name__ == '__main__':
    mytasks = hello.s()
    result = mytasks.apply_async()
    print(result.get())
```

When run, 'hello...' and 'later...' are printed, but result.get() returns None

**Comment by ask** [comment]
I guess it could either reraise the `Ignore` exception, or forward the result in a new special semi-predicate exception somehow but that would complicate the main code a lot.

If this is for testing, then you should really use mocking instead as with `eager` you're only testing an emulation.

**Comment by bruno-rino** [comment]
I use CELERY_ALWAYS_EAGER to run smaller jobs locally. It is not testing. It is an important mode of operation.

I'll look into other options to have my results trickle down.

**Comment by auvipy** [comment]
hi @bruno-rino what's the status of the issue with new release of celery?

**Comment by bruno-rino** [comment]
Still occurs with celery 4.1.0

**Comment by auvipy** [comment]
that's sad. could you investigate to find out a fix? at least a testcase?
