### ISSUE TITLE
Celery Worker hangs, requires restart. redis/python27

### ISSUE THREAD

**Issue by gdxn96** [celery/celery#3335]
I'm running celery==3.1.23 with python27 and redis as a results backend and broker. After a short period of time celery workers just stop working through tasks requiring a restart to continue.

Command used to run celery
celery worker -A app.celery -l INFO

All config is default apart from CELERY_RESULT_BACKEND and CELERY_BROKER_URL pointing to dedicated redis cache db's.

Similar to:
https://github.com/celery/celery/issues/2296

**Comment by ask** [comment]
Is the worker executing tasks at that point? (`celery -A proj inspect active`)

Do you use the `-Ofair` argument to `celery worker` ?

**Comment by srajanpaliwal** [comment]
I am facing the same issue with Redis as  Broker. I am using celery with django to fetch article and remove boiler plate contents from them using [python-boilerpipe](https://github.com/misja/python-boilerpipe). But, the worker hangs after fetching and storing results for few articles(8-12 article).  I am also using celery-haystack with elastic-search, but these tasks don't result in this behavior. 

celery config
`
BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
`
Command used to start worker and beat(i have not used `-0fair` argument)
`celery -A server worker -l info 
    celery -A server beat -l info `

(`celery -A server inspect active`) results in
`-> celery@l: OK
    * {u'args': u"[[4780445, 4780446, 4780447, 4780448], 484, {u'average_body_length': 2859.0, u'body_null_count': 0, u'average_fulltext_length': 0.0, u'date_null_count': 0, u'article_count': 4, u'author_null_count': 0, u'average_image_count': 0.0}]", u'time_start': 3310304.149389917, u'name': u'fetch_boilerpipe_task', u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, u'hostname': u'celery@l', u'acknowledged': True, u'kwargs': u'{}', u'id': u'a8cc292b-9c8f-4557-947c-cea7f1d1f33a', u'worker_pid': 28183}
`
Log shows that worker stopped execution  in the middle. I have ran it a lot of time and it halts either when fetching article using urllib2 or passing fetched HTML to boiler.
I also made a test task with only boilerpipe and queued 20 tasks same inputs, this also halted the worker after completing 10 tasks.

**Comment by gdxn96** [comment]
Sorry for the late reply, it seems the issue has not been reproducible in the last few days. I will give it another week to check if the issue returns and if not I will close this issue. In the meantime I will attempt to find any config/environment changes in the last 11 days and post them back here if relevant.

**Comment by srajanpaliwal** [comment]
@gdxn96 i am still facing this issue. I would be very grateful, if you share configs/environment changes. Thanks.

**Comment by ask** [comment]
@srajanpaliwal Try adding `--time-limit` to the worker command-line.

It's better for your tasks to manually set timeouts for any network operation, as time limits will actually kill the process.

**Comment by gdxn96** [comment]
Unable to repro, no apparent config/environment changes
