### ISSUE TITLE
Get chain id from inside task class

### ISSUE THREAD

**Issue by OskarPersson** [celery/celery#3337]
I've setup a chain that executes some custom task classes. Is it possible to access the id of the chain from inside the task?

I need something like this

```
class MyCustomTask(Task):
    def __call__(self, *args, **kwargs):
        print self.chain.task_id
```

**Comment by ask** [comment]
Chains don't have an id, but in 4.0 you have: `self.request.parent_id` and `self.request.root_id`.

The root id is the first task in the workflow.

**Comment by Soham7777777** [comment]
Then How to get root task root_id? AsyncResult won't work correct?
