### ISSUE TITLE
Makes heartbeat check possible for sync loop when socket timeout

### ISSUE THREAD

**Issue by air-upc** [celery/celery#3338]
When I use `synloop` (in celery.worker.loops) to consume msg, I found that no heartbeat check is enabled when socket timeout occurs during drain events:

``` python
try:
    perform_pending_operations()
    connection.drain_events(timeout=2.0)
except socket.timeout:
    pass  # here no heartbeat checked, just pass
```

but in method `consume` of `ConsumerMixin` of `kombu.mixin`, we have

``` python
try:
    conn.drain_events(timeout=safety_interval)
except socket.timeout:
    conn.heartbeat_check()  # here checks the heartbeat when socket timeout
```

So heartbeat check disabled by default in `celery.worker.loops:synloop` compared with `kombu.mixin:ConsumerMixin`, but I think it's better to check the heartbeat when socket timeout occurs. Is there something hinders us to check the connection heartbeat?

Also in `celery.worker.consumer.consumer:Consumer`,  the code will set heartbeat 0 when event IO hub not used:

``` python
if self.hub:
    self.amqheartbeat = amqheartbeat
    if self.amqheartbeat is None:
        self.amqheartbeat = self.app.conf.broker_heartbeat
else:
    self.amqheartbeat = 0  # in connection's heartbeat_tick method of amqp, just return
```

and in method `heartbeat_tick` of `py-amqp.amqp.connection:Connection`, we have:

``` python
if not self.heartbeat:
    return
```

As amqheartbeat == 0, no real heartbeat check is executed. Shall we make heartbeat check possible in celery synloop when socket timeout occurs?

**Comment by air-upc** [comment]
@ask

**Comment by ask** [comment]
I'm guessing this is on Windows, since you're using synloop with amqp?

**Comment by air-upc** [comment]
For security and convenience, we disabled `event loop` and use `gevent` as our `taskpool` on platform `CentOS`. If concerns over this issue are much easier to deal with, can we add several lines of code to realise the heartbeat?

**Comment by ask** [comment]
Ah, yeah.  The gevent/eventlet pools don't enable heartbeats yet, but it should be a small change to enable.
