### ISSUE TITLE
Celery tasks are again not allowed to start subprocesses

### ISSUE THREAD

**Issue by lvh** [celery/celery#3340]
This is a regression of #1709. It looks like this causes issues like https://github.com/ansible/ansible/issues/14408 in addition to the ones mentioned in #1709.

That issue was closed in commit https://github.com/celery/billiard/commit/e6bb0f744e97bd9acc560788a1b6152bc9ba48c3 but then got reintroduced in commit https://github.com/celery/billiard/commit/c7eedbd0ee1498e76d4fa1affac5b1a275660ee7#diff-bf0b236b25b18d8affbc71f0052f9ebfR121. 

I am creating a new issue because I'm trying to fix it, #1709 was closed without being resolved, and I'm not a contributor so I can't reopen it.

**Comment by fxfitz** [comment]
+1

**Comment by lvh** [comment]
The linked PR reverts it back to the old behavior. Of course, as long as the parent (in this case, a celery worker process) doesn't start reaping these, you'll end up with a ton of zombies. My estimation from #1709 is that @ask feels that's better than just arbitrarily not allowing it. We can also introduce behavior for celery to take over that job.

**Comment by ask** [comment]
Thanks!  The billiard fix has been merged.

Indeed, the limitation is rather silly as it's just how Unix operates.  It does mean the tasks starting processes need to be careful at collecting these processes.  By using a shared pipe, by signal handler (does not work with signals that cannot be handled), or also AFAIR there's a new Linux-specific API to handle this.
