### ISSUE TITLE
Django + Autodiscovery + AppConfig modules + tutorial = ???

### ISSUE THREAD

**Issue by bobobo1618** [celery/celery#3341]
As of Django 1.9, [the tutorial uses `AppConfig` objects rather than module names in `INSTALLED_APPS`](https://docs.djangoproject.com/en/1.9/intro/tutorial02/#activating-models). 

A user on IRC following [the Celery Django tutorial](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) had some trouble with his tasks module being autodiscovered after setting up his `INSTALLED_APPS` in the new way, getting `KeyError` in his worker.

I'm not sure whether this was user error or an issue with autodiscovery not picking up `INSTALLED_APPS` with `AppConfig` objects but I thought I'd report it just in case.

**Comment by ask** [comment]
This is fixed in 4.0 where you do:

   ```app.autodiscover_tasks()```

instead.  No pointing to INSTALLED_APPS.

**Comment by dhepper** [comment]
Just for reference: if you using Django >=1.9 and are stuck with Celery < 4.0 you might be able read the app names from the app registry.

Import the registry:

    from django.apps import apps

Replace `settings.INSTALLED_APPS` with:

    [app_config.name for app_config in apps.get_app_configs()]
