### ISSUE TITLE
Celery command line error if django project has name "app"

### ISSUE THREAD

**Issue by jyek** [celery/celery#3342]
Is it possible to run the celery command line if your django project is named "app"? 

**Folder structure**
```
|- app
|  |- __init__.py
|  |- settings.py
|  |- celery.py
|- manage.py
```

`__init__.py` and `celery.py` are set up as per the docs: http://docs.celeryproject.org/en/master/django/first-steps-with-django.html

I get the following error `ImportError: No module named celery` when I run `celery --app=app.celery:app worker` and I think it is because the celery command line tool has an internal definition for the module app.

**Comment by ask** [comment]
Naming the project `app` works for me here, are you sure your `app/celery.py` module has `from __future__ import absolute_import` at the top of the module?

**Comment by auvipy** [comment]
@jyek please try to post this type of issues to user mailing list first https://groups.google.com/forum/#!forum/celery-users
