### ISSUE TITLE
Celery with Tornado coroutines 

### ISSUE THREAD

**Issue by anirbanroydas** [celery/celery#3343]
How to run `asynchrnous tornado coroutines` as `celery tasks`?

Is it possible? If not, then what is a work around to run tasks which are asynchronous? 

What I mean is, what if my task is a method which has to do **3rd party api calls**, and if there are many requests to 3rd party calls, then if my task is a **blocking one**, then the **workers** running those tasks are going to wait on the responses of those 3rd party api calls and soon there would be a **huge pile** waiting on the **queues**.

So, like in **_Tornado_**, if we use `coroutines`, then we can make our 3rd party api calls as non blocking by returning a future. So what if I want to add tasks which are going to do api calls in a non-blocking way?

What is the best solution, **`celery`** provides? Because as per as I could grasp from the code base, making the `tornado coroutine functions` as `celery tasks` is not possible.

Please let me know if there is a fix for this or if there is a better alternative to achieve the above **use case**.

**NOTE :** Currently my application is running on top of Tornado.

**Comment by ask** [comment]
You certainly could do that by starting a tornado event loop in the child process, but the best solution may be to use a tornado execution pool.

I imagine it could be possible to connect the gevent/eventlet pools to the tornado event loop,
and that is probably the best way to start a tornado worker.

Figure out how to connect gevent/eventlet to Tornado and you could use e.g. `-P gevent -c 1000`

**Comment by thedrow** [comment]
It's possible to connect gevent or eventlet to the Tornado event loop. It's also possible to do so with asyncio with a little bit of effort.

**Comment by auvipy** [comment]
@anirbanroydas https://groups.google.com/forum/#!forum/celery-users is better place to ask questions like this.
