### ISSUE TITLE
celery store wrong place

### ISSUE THREAD

**Issue by callnothing** [celery/celery#3345]
I use rabbitmq as backend and redis as  broker, buy why celery result will store in redis.

**Comment by ask** [comment]
Redis is not the default result backend, so if results are stored there it must mean you have configured it do so.

Do you have an example config where this is happening?

Using Redis as a message transport, but amqp as a result backend is a strange combination btw, usually it's the other way around.

**Comment by callnothing** [comment]
`BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'amqp://'`
this is my config, and when i use apply_async get get result, the key in _kombu.binding.celeryresults will be show
![image](https://cloud.githubusercontent.com/assets/5339910/17235426/8de14a72-5573-11e6-9900-9d305765442f.png)
![image](https://cloud.githubusercontent.com/assets/5339910/17235458/ce9645ae-5573-11e6-9d1a-2ad463334634.png)

**Comment by ask** [comment]
Aha!  The amqp result backend is actually using kombu to send messages, and it's using the BROKER_URL to do so.

Both the 'rpc' and 'amqp' result backends will use the BROKER_URL.

Usually people will want to use RabbitMQ as a message transport and Redis as a result backend,
I have a hard time seeing anyone needing to do the opposite...

**Comment by ask** [comment]
Use: CELERY_RESULT_BACKEND = 'redis://'

**Comment by callnothing** [comment]
i try to use redis as by backend, but when i use tornado-celery is very slow, more than 500ms, use rabbitmq as backend is fine.

**Comment by auvipy** [comment]
@callnothing this type of issue better fits here https://groups.google.com/forum/#!forum/celery-users
