### ISSUE TITLE
Retry does not raise given exception

### ISSUE THREAD

**Issue by auuron** [celery/celery#3348]
Let's take a look into example:

```
@app.task(bind=True)
def send_twitter_status(self, oauth, tweet):
    try:
        twitter = Twitter(oauth)
        twitter.update_status(tweet)
    except (Twitter.FailWhaleError, Twitter.LoginError) as exc:
        raise self.retry(exc=exc)
```

In similar case i would like to pass another exception than caught exc, but it's being rereaised by default. Going further, if i would change `raise self.retry(exc=exc)` to `raise self.retry(exc=1)` it would make no difference.. Is this behaviour desirable?

**Comment by ask** [comment]
@auuron The idea at first was that you'd pass an exception instance to `.retry`, and it would raise that exception.  The problem then turned out to be that you lose the original stack trace, so it was changed to simply reraise the current exception instead (as that's how it's used in 99% of cases).

**Comment by auuron** [comment]
@ask thanks for reply
