### ISSUE TITLE
Failed to install celery 4

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3351]
Today I tried to update celery to the latest master, but it failed.

The celery folder on my site-packages is missing all celery sub-packages except utils

Previously setup.py used `find_packages`. Reverting back to it solves the issue:
```
packages=find_packages(exclude=['ez_setup', 'tests', 'tests.*']),
```

**Comment by ask** [comment]
Thanks! I tried it locally and it seemed to work, but maybe I didn't test it properly.

Seems strange that `packages=['celery']` won't include sub packages, what else is a package for? ;)
