### ISSUE TITLE
Documentation: Error in 'extending' page?

### ISSUE THREAD

**Issue by someburner** [celery/celery#3353]
Howdy

In the [extending](http://docs.celeryproject.org/en/latest/userguide/extending.html) docs, under **Example worker bootstep**, 2nd code block, it has:

```
    def detect(self, worker):
        # update active requests
        for req in self.worker.active_requests:
            if req.time_start and time() - req.time_start > self.timeout:
                raise SystemExit()
```

Should this not be
```
for req in worker.active_requests:
```
? 

Also, might be nice to have the requires be more verbose, ie:

```
class DeadlockDetection(bootsteps.StartStopStep):
    requires = ('celery.worker.components:Timer',)
```

**Comment by berkerpeksag** [comment]
Both of your suggestions have been fixed in master in https://github.com/celery/celery/commit/b65c6991555e4b8c80364306a24b269b452be059. Perhaps it should be backported to 3.1?

**Comment by someburner** [comment]
Well, using 3.1.23 those both produce errors.. so not sure what you mean?

**Comment by ask** [comment]
Fixed in master, and we'll just focus on getting the 4.0 release out

**Comment by someburner** [comment]
Ah okay. Thanks.
