### ISSUE TITLE
Aerospike Support

### ISSUE THREAD

**Issue by hacknaked** [celery/celery#3354]
Would be great to have [Aerospike](http://www.aerospike.com/ ) support for Celery. Aerospike provides[ ACID consistency](https://www.aerospike.com/docs/architecture/assets/AerospikeACIDSupport.pdf) in the presence of node failures and [support lists](http://www.aerospike.com/docs/guide/cdt-list.html).

**Comment by thedrow** [comment]
I agree that providing a results backend for Aerospike is nice but I'd have to reject this feature request unless the vendor of Aerospike is willing to maintain this.
We have enough work as it is.
I'm gonna close this issue for now. If you can either get a promise from Aerospike to maintain this or willing to commit to maintain it yourself we can revisit.
