### ISSUE TITLE
Route task to multiple queues?

### ISSUE THREAD

**Issue by xidui** [celery/celery#3358]
Is there a mechanism in celery that can satisfy this? 
**two queues in the cluster:**
- queue1: old server listen on this queue which can process tasks
- queue2: new server listen on this queue which can also process tasks

Tasks can be processed either by server with queue1 or queue2, but queue2 is better.
If no server listen on queue2, then server listen on queue1 is also ok to process the tasks.

**Comment by kindule** [comment]
Hi, yes. Celery is already satisfy this.
I think you just need to bind one queue for both your server, but the new server can start more worker for consume the task.

**Comment by xidui** [comment]
@kindule 
I mean, I want the task to be consumed by either queue1 or queue2. If queue1 is consuming it, queue2 will not receive it. 

Machine1 listens queue1 and Machine2 listens queue2. After it get stable, I just want to remove machine1 or remove queue1. User will not know about that change.

**Comment by kindule** [comment]
@xidui these seems not celery currently can do :(

**Comment by ask** [comment]
We are pretty much bound to AMQP/0.9.1 as to what queues can do, so do check out RabbitMQ/AMQP routing examples.

AMQP does have the immediate flag, which means the broker must raise an error if the
queue cannot be routed directly to a consumer, but supporting this in Celery is complicated
by clients usually being run inside synchronous processes.  For this to work correctly you'd have
to asynchronously read updates from the connection, so your clients sending tasks would have to use one of 1) tornado/twisted/asyncio, 2) gevent/eventlet, 3) threads (not really recommended).

**Comment by txomon** [comment]
Guys, just in case this is already possible, and has always been, although you need to control who writes the result (like broadcast tasks).

Basically, you change the celery exchange type to `topic` and then you choose a routing key to which multiple queues are bound to. Hope this gives you a hint!

**Comment by auvipy** [comment]
closing as low prio
