### ISSUE TITLE
JSON serializer does not behave the same as Pickle with Chords containing Chains

### ISSUE THREAD

**Issue by dhm116** [celery/celery#3361]
This seems somewhat related to #3154, but given the example tasks:
```python
@shared_task()
def add_one(value):
    return value + 1

@shared_task()
def subtract_one(value):
    return value - 1

@shared_task()
def aggregate_results(values):
    return {
        'values': values
    }

@shared_task()
def sample_task():
    values = [x for x in xrange(1, 5)]

    return chord(
        chain(
            add_one.s(value),
            subtract_one.s()
        )
        for value in values
    )(aggregate_results.s())
```
and invoked:
```python
chord_task = sample_task.delay()
chord_result = AsyncResult(chord_task.id)
callback_task = chord_result.get()
print callback_task
```
If you invoke the `sample_task` with `pickle` as the result serializer, you will get:
```
f38b7727-51a6-4b9a-b990-8886405a8d53
```
which is the aggregate task that you can then use to properly get the aggregated results via `callback_task.get()` and returns the expected
```python
{'values': [1, 2, 3, 4]}
```

If you invoke `sample_task` with `json` as the result serializer, you will get:
```python
[[u'41219e4f-61cb-44d8-a9fe-6c783b01152e', [u'f9e2ed9f-fdf7-4b48-87a6-d3b2266f2435', [[[u'109ec9b3-08aa-4926-a7c5-517247aadb88', None], None], [[u'fce5757a-c35a-44e8-8514-c92d60a5905a', None], None], [[u'b094cbce-fa2a-48ca-8260-5ee7dfd869db', None], None], [[u'7c319f55-b020-4b0f-885d-962b67475c6f', None], None]]]], None]
```
and there does not appear to be any way to access the callback task to get the aggregate results. I have tested this with `simplejson` both installed and not installed with no change.

Given that Celery is no longer recommending `pickle` as a serialization format
 > Starting from version 3.2 Celery will refuse to accept pickle by default.

how are we supposed to access the chord results?

**Comment by dhm116** [comment]
It seems like the fix for this was to define `shared_task` as
```python
def sample_task():
    values = [x for x in xrange(1, 5)]

    return chord((
        chain(
            add_one.s(value),
            subtract_one.s()
        )
        for value in values
    ), aggregate_results.s()).delay()
```
and then
```python
chord_task = sample_task()
chord_result = AsyncResult(chord_task.id)
callback_task = chord_result.get()
print callback_task
```
will return the correct results.

I would still like to understand why wrapping the chord within a task was not working as expected with JSON serialization as opposed to Pickle.

**Comment by ask** [comment]
It seems you're simply seeing a tuple-serialized result, use:

   from celery.result import result_from_tuple
   callback_task = result_from_tuple(chord_result.get(), app=callback_task.app)

to convert it back into a result instance.

**Comment by ask** [comment]
The first version calls a task that calls a task, so return value is `AsyncResult -> AsyncResult`,
while in the second version you call a function that returns AsyncResult so no serialization is required.
