### ISSUE TITLE
how to comfigure celery with redis-server in heroku app

### ISSUE THREAD

**Issue by kartikdanidhariya** [celery/celery#3375]
hi,
in my local machine my pip freeze is 

Django==1.9.4
Pillow==2.9.0
ajaxuploader==0.3.8
amqp==1.4.9
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.23
boto==2.39.0
celery==3.1.23
crc16==0.1.1
dj-database-url==0.3.0
dj-static==0.0.6
django-allauth==0.25.2
django-appconf==1.0.1
django-bootstrap-pagination==1.6.1
django-celery==3.1.17
django-crontab==0.6.0
django-endless-pagination==2.0
django-geoposition==0.2.2
django-jfu==2.0.9
django-storages==1.4.1
django-thumbs==0.4
djangorestframework==3.1.3
importlib==1.0.3
kombu==3.0.35
oauthlib==1.0.3
python-openid==2.2.5
python-redis==0.0.7
pytz==2016.3
redis==2.10.5
reportlab==3.3.0
requests==2.9.1
requests-oauthlib==0.6.1
six==1.10.0
static3==0.6.1
stripe==1.32.0
wsgiref==0.1.2

Now i want to use celery for asynchronous task into django
so i use redis-server
configuration for celery in my setting.py is 
`BROKER_URL = 'redis://127.0.0.1:6379/0'
BROKER_TRANSPORT = 'redis'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

'''app.conf.update(
    CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend',
)

app.conf.update(
    CELERY_RESULT_BACKEND='djcelery.backends.cache:CacheBackend',
)'''

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Canada/Eastern'`

after i starter redis server and run following commnd

> python manage.py celeryd -v 2 -B -s celery -E -l INFO

so it run perfectly in my local machine

after that i want to deploy my project in heroku server 
so in that server i use heroku-redis addons for worker
after check log of heroku server it gies me error like 

[2016-08-03 06:09:25,608: ERROR/Beat] beat: Connection error: [Errno 111] Connection refused. Trying again in 20.0 seconds...
[2016-08-03 06:09:45,552: ERROR/MainProcess] consumer: Cannot connect to amqp://(redacted)@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds...

in this error os related to amqp so it related to rebbitmq but i am not use rebbitmq in any setting so why this show me error related to amqp

how can i solve this error

**Comment by auvipy** [comment]
please post this type of issue in support forum https://groups.google.com/forum/#!forum/celery-users
