### ISSUE TITLE
Stack trace for HardTimeLimitExceeded with gevent worker

### ISSUE THREAD

**Issue by binrush** [celery/celery#3378]
Hello.

We are using celery `3.1.23` with gevent workers do do some tasks (sending push messages). 

We are executing celery like this:

```
celery -A backend.tasks.async worker -l info -P gevent -c 50 -Q push -n async_worker
```

Sometimes worker stucks and stops processing messages so we need to restart it to make it work. In logs we have messages about HardTimeLimit for tasks:

```
2016-08-08 15:28:42,665:ERROR:celery.worker.job.on_timeout:Hard time limit (900s) exceeded for backend.tasks.async.send_push[43bb45fb-1463-4522-8c87-58fcf8407c08]
```

But I'm not sure if it is a reason for stucking.

Is it possible to get stack trace from HardTimeLimit error as well as greenlets stack traces for stucked celery process?

**Comment by binrush** [comment]
@ask thank you, I will try this. And is it possible to retry task in case of HardTimeLimit?

**Comment by auvipy** [comment]
report if it still an issue on master
