### ISSUE TITLE
django example template INSTALLED apps not compatible with default startapp

### ISSUE THREAD

**Issue by hamishwillee** [celery/celery#3380]
If you create a new app using manage.py in django the INSTALLED_APPS  is supposed to be a dotted path to the new app's config class, which created in apps. py. So your apps look like:
```
INSTALLED_APPS = [
   ...
    #'myapp.apps.MyAppConfig',
   ...
```
However if you do this then the build won't find tasks  using `autodiscover_tasks` will fail. YOu instead need to just specify the folder name 'uploader'

Probably this should be noted.

**Comment by ask** [comment]
This is fixed in master, wait for 4.0
