### ISSUE TITLE
Does send_error_emails exist in 4.0.0?

### ISSUE THREAD

**Issue by willseward** [celery/celery#3389]
After scanning the docs, it doesn't look like `Task.send_error_emails` (`CELERY_SEND_TASK_ERROR_EMAILS`) exists anymore. If not, I'd recommend adding it to the removed settings.

**Comment by berkerpeksag** [comment]
It was removed in https://github.com/celery/celery/commit/b5d8c1cebd50950e656998e909c9e0679d0a693e. http://docs.celeryproject.org/en/master/whatsnew-4.0.html#features-removed-for-simplicity contains the following note:

> Task no longer sends error emails.
> This also removes support for app.mail_admins, and any functionality related to sending emails.

Perhaps we can document all removed members of the API.

**Comment by willseward** [comment]
Ok. Thanks. Is there any prescribed way of sending out error notifications, or is it up to us?

**Comment by alanhamlett** [comment]
@willseward I used to wrap every task with a decorator to catch and email errors:
https://gist.github.com/alanhamlett/dc8cdd4721ea63053f14

These days instead of sending an email I would have the decorator create a Prometheus metric:
https://prometheus.io/

Sometimes bad deployments would send thousands of emails in a matter of seconds, and Gmail starts rejecting/throttling all incoming emails for a while. Prometheus or another logging aggregator or metrics platform can send one email alert about many Celery errors so your email won't get overloaded.

**Comment by luiscastillocr** [comment]
Why not using the celery signals?
http://docs.celeryproject.org/en/latest/userguide/signals.html#task-failure

**Comment by luiscastillocr** [comment]
`import socket
from celery.signals import task_failure
from django.conf import settings
from django.core.mail import send_mail

@task_failure.connect()
def celery_task_failure_email(task_id, exception, einfo, sender, *args, **kwargs):

    subject = "[Django][{queue_name}@{host}] Error: Task {task_name} ({task_id}): {exception}".format(
        queue_name=sender.queue,
        host=socket.gethostname(),
        task_name=sender.name,
        task_id=task_id,
        exception=exception
    )

    send_mail(subject, str(einfo), settings.DEFAULT_FROM_EMAIL, settings.ADMINS)
`

something like this maybe

**Comment by tisdall** [comment]
@luiscastillocr - thank you so much for this!  I got an exception on `sender.queue`, though, and had to replace `send_mail` with `mail_admins` to get it to work.  I also wanted to replicate more of the original email that used to be sent out.

Here's my version based on yours:
```
import socket
from celery.signals import task_failure
from django.core.mail import mail_admins


@task_failure.connect()
def celery_task_failure_email(**kwargs):
    """ celery 4.0 onward has no method to send emails on failed tasks
    so this event handler is intended to replace it
    """

    subject = u"[Django][{queue_name}@{host}] Error: Task {sender.name} ({task_id}): {exception}".format(
        queue_name=u'celery',  # `sender.queue` doesn't exist in 4.1?
        host=socket.gethostname(),
        **kwargs
    )

    message = u"""Task {sender.name} with id {task_id} raised exception:
{exception!r}


Task was called with args: {args} kwargs: {kwargs}.

The contents of the full traceback was:

{einfo}
    """.format(
        **kwargs
    )

    mail_admins(subject, message)
```

**Comment by mherrmann** [comment]
I published a similar solution as a `pip` package: https://github.com/mherrmann/celery-error-emails
