### ISSUE TITLE
 filedescriptor out of range in select(),why celery start so many pipe?

### ISSUE THREAD

**Issue by qinshuang** [celery/celery#3397]
When worker run the ansible's tasks, 
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py\", line 62, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 474, in _execute_module
    tmp = self._make_tmp_path(conn)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 1293, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py\", line 1174, in _low_level_exec_command
    in_data=in_data)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py\", line 362, in exec_command
    (returncode, stdout, stderr) = self._communicate(p, stdin, in_data, sudoable=sudoable, prompt=prompt)
  File \"/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py\", line 162, in _communicate
    rfd, wfd, efd = select.select(rpipes, [], rpipes, 1)
ValueError: filedescriptor out of range in select()

 ---------------------------------------------------------------

Version is celery (3.1.23)

Strace
--------------------------------------------------------------------------------

Start celery
celery]# python manage.py celery worker --loglevel=info -c 500   -Q queue 

I just check one subprocess
celery]# lsof -p 16138 | grep pip | wc -l
2501
celery]# lsof -p 16138 | grep -v pip | wc -l
93
celery]# ulimit -n
65536
celery]# lsof | wc -l
1176115

--------------------------------------------------------------------------------------
why celery start so many pipe?

**Comment by qinshuang** [comment]
Sorry, it's not celery issue

**Comment by ask** [comment]
You have 500 processes, that will create about 1000 pipes.

Using select is generally discouraged as it has a limit of 1024 or so file descriptors, and that is not only the file descriptors in the select set, it's the number of file descriptors used by the process in total.  For this reason `select.poll` is preferred over `select.select`
