### ISSUE TITLE
workers consuming from queues that weren't broadcasted to them

### ISSUE THREAD

**Issue by jclark360** [celery/celery#3399]
We're currently having an issue where when we call add_consumer, celery workers that don't match the destination argument somehow are trying to pick up the queues specified in the add_consumer call.    It seems to coincide with when we restart the docker container that celery is running.   Our workers start up with their own names i.e foo_worker@domain.com and bar_worker@domain.com, the destination is specified as foo_worker@domain.com.   Is there some loophole or edge case that we are missing?.    If we disable mingle does that ensure these other workers will never get the messages from add_consumer?

**Comment by auvipy** [comment]
which versions and stacks are you using?

**Comment by jclark360** [comment]
Celery 3.1.23, celery is just running standalone if you mean by stack is it running in flask or something else?

**Comment by auvipy** [comment]
celery with rabbitmq/or with what. and can you share your code?

**Comment by timofurrer** [comment]
@jclark360 He's talking about your celery configuration - mainly the broker. Other configuration and code will also help to analyze this issue.

**Comment by jclark360** [comment]
Worker startup cmd (worker that somehow received the message it shouldn't)

PYTHONPATH=. celery worker -Ofair -c 8 -A app.celery_app -l WARNING -f /var/log/celery/celery-worker.log -n assortment-worker@360pi.com

Worker startup cmd (worker that is supposed to get add_consumer messages)

PYTHONPATH=. celery worker -Ofair -c 8 -A app.celery_app -n crawler-worker@360pi.com -l WARNING -f /var/log/celery/celery-worker.log


Code to signal crawler workers to pickup new queue:

celery_app.control.add_consumer(
                queue_name,
                exchange='crawlers',
                destination=['crawler-worker@360pi.com']
            )

Config:

        'BROKER_URL': ['amqp://host1:5672', 'amqp://host2:5672'],
        'BROKER_TRANSPORT_OPTIONS': {'confirm_publish': True},
        'CELERY_ACCEPT_CONTENT': ['json'],
        'CELERY_TASK_SERIALIZER': 'json',
        'CELERY_RESULT_SERIALIZER': 'json',
        'CELERY_ENABLE_UTC': True,
        'SERVER_ENVIRONMENT': 'default',
        'CELERY_ACKS_LATE': True,
        'BROKER_HEARTBEAT': 10,
        'CELERY_ROUTES': (router()),
        'CELERY_EVENT_QUEUE_TTL': 60,
        'CELERYD_MAX_TASKS_PER_CHILD': 30000,
        'CELERY_ALWAYS_EAGER': False,
        'CELERY_REDIRECT_STDOUTS_LEVEL': 'DEBUG',
        'CELERY_DEFAULT_QUEUE': 'default'

**Comment by ask** [comment]
The worker consumes from all queues defined in `CELERY_QUEUES` by default, and if you add queues to consume from by remote management, that will not survive a worker restart.

I see you don't have any queues defined in the configuration you pasted, but I'm enumerating some possible causes:

1) When you restart the worker will reset what queues it consumes from, thus only consuming
from queues defined on the command-line (`-Q`), or queues configured in `CELERY_QUEUES`

2) You're defining multiple queues with the same exchange/routing_key

  If you have two queues bound to exchange/routing_key default/default, then the messages
  will be delivered to both queues.

Mingle doesn't have any effect on this, as it merely syncs logical clock values and revoked tasks.
