### ISSUE TITLE
Improve support for dill as serializer?

### ISSUE THREAD

**Issue by mathiasose** [celery/celery#3404]
CC @mmckerns

Previously mentioned in #2526.
Dill (https://github.com/uqfoundation/dill/) is able to serialize "all of python", which is very useful indeed.
For example, in preparation for my master's thesis I am trying to build a framework for running experiments with genetic algorithms.
For this I want to be able to queue various functions and their parameters to be composed and run asynchronously.

I have been looking into this today, and it seems that with some effort I have been able to get it working for my project (using Python 3.5 for the record).
It seems to me that `dill` can work as a drop-in replacement for `pickle`, with very little changes required to the `celery` codebase.
The main issue is that `celery` needs to be able to tell its dependencies `kombu` and `billiard` to use `dill`.

The two things I had to do was:
1. apply the 'monkeypatch' posted in https://github.com/uqfoundation/dill/issues/108 in my project
2. fork `billiard` and replace `pickle` imports with `dill` a couple of places (https://github.com/mathiasose/billiard/commit/15886a9e0b732d643710adb88657a3f5b014f472) and use the fork as `celery`s dependency.

**Comment by ask** [comment]
I think in 4.0 there won't be any need for adding explicit support for this in billiard, since the celery worker is no longer pickling complex objects back to the parent (other than the exception in case of failure, which could have complex attribute I guess but that sounds more specialized).

**Comment by mmckerns** [comment]
@ask: So in 4.0, celery will no longer ship complex objects, or do you have another method aside from serialization?  It's not well known, but `dill` also supports source code extraction from complex objects, which is what I was originally doing to support distributed computing in `pathos` (now in `ppft`).  I'd be interested in knowing if you have another alternative that works well for complex objects.

Note to @mathiasose: you may be interested to look at `mystic`, which is an nonlinear non convex optimizer that can leverage parallel/distributed computing.  It may or may not already do much of what you are looking to do.

**Comment by ask** [comment]
@mmckerns: There are several stages of serialization here:

- Sending the task message to the workers (kombu)
- Worker sending task messages to child processes (billiard/multiprocessing)
- Child processes sending results back to parent process (billiard/multiprocessing)

A Celery worker instance using the prefork execution pool consists of one parent process, and one ore more child processes actually executing the tasks.

In previous versions the parent process had to deserialize the task message to know the name of the task, this is no longer the case in the new task message protocol in Celery 4: The worker simply passes a long the message, it doesn't have to deserialize it.   In the child process, the message will be deserialized by Kombu.

In Celery 4 the worker also does not send results back to the parent process, instead it just sends
a simple string representation that can be logged.  If the task raises an exception it will send back the exception instance, but those should be easy to serialize without dill.

So in Celery 4 you should only need to create a custom Kombu dill serializer - you don't have to modify billiard/multiprocessing.

**Comment by mmckerns** [comment]
@ask: For anything that you will be passing across a process that is not something that can be handled by `pickle`, I'd suggest using `multiprocess` (instead of `multiprocessing`) -- it's a fork, much like `billiard` is, to replace `pickle` with `dill` in `multiprocessing`.  However, if you are only sending strings, then no need.  You can subclass the `dill.Pickler` pretty easily, so maybe this is a non-issue going into Celery 4…?

**Comment by mathiasose** [comment]
Can confirm this configuration is simpler now.
In Celery 4.0.2 this is the celery configuration for this case (tested with Python 3.5 and 3.6):

    from dill import dill
    from kombu.serialization import pickle_loads, pickle_protocol, registry
    from kombu.utils.encoding import str_to_bytes
    
    
    def register_dill():
        def encode(obj, dumper=dill.dumps):
            return dumper(obj, protocol=pickle_protocol)
    
        def decode(s):
            return pickle_loads(str_to_bytes(s), load=dill.load)
    
        registry.register(
            name='dill',
            encoder=encode,
            decoder=decode,
            content_type='application/x-python-serialize',
            content_encoding='binary'
        )
    
    
    register_dill()
    
    task_serializer = 'dill'
    event_serializer = 'dill'
    result_serializer = 'dill'
    accept_content = ['dill']

**Comment by thedrow** [comment]
Would anyone mind releasing this as a package and provide a link to it in the documentation?
It can be useful to someone.

**Comment by mathiasose** [comment]
@thedrow I actually started making a package but I got stuck trying to set up a sensible test environment and didn't publish anything yet.
I can put it up without tests for now, just give me a little while.

**Comment by mathiasose** [comment]
- https://github.com/mathiasose/celery_dill_serializer
- https://pypi.python.org/pypi/celery-dill-serializer
