### ISSUE TITLE
CELERY_TRACK_STARTED: states not always changing

### ISSUE THREAD

**Issue by robnagler** [celery/celery#3406]
Perhaps I'm not sure how CELERY_TRACK_STARTED is supposed to work. We are using Celery for jobs directly for users. These jobs take minutes or hours. Users want to know if their job is queued or running.

When CELERY_TRACK_STARTED=True, the tasks sometimes transition to STARTED and other times, they stay in PENDING. Worse, the jobs sometimes are never ready() even though the worker notes that the job has succeeded.

radiasoft/sirepo#276 has details. I didn't try to distill this. The complete configuration is:

``` python
celery = Celery('sirepo')

cfg = pkconfig.init(
    broker_url=('amqp://guest@localhost//', str, 'Celery: queue broker url'),
    celeryd_concurrency=(1, int, 'how many tasks to run in parallel'),
    celeryd_task_time_limit=(3600, int, 'max run time for a task in seconds'),
)

celery.conf.update(
    pkcollections.map_items(cfg, op=lambda k, v: (k.upper(), v)),
)

celery.conf.update(
    CELERYD_LOG_COLOR=False,
    CELERYD_MAX_TASKS_PER_CHILD=1,
    CELERYD_PREFETCH_MULTIPLIER=1,
    CELERYD_TASK_SOFT_TIME_LIMIT=celery.conf['CELERYD_TASK_TIME_LIMIT'] - 10,
    CELERY_ACKS_LATE=True,
    CELERY_REDIRECT_STDOUTS=not pkconfig.channel_in('dev'),
    CELERY_RESULT_BACKEND = 'rpc',
    CELERY_RESULT_PERSISTENT=True,
    CELERY_TASK_PUBLISH_RETRY=False,
    CELERY_TASK_RESULT_EXPIRES=None,
    CELERY_TRACK_STARTED=True,
)
```

Python 2.7.10, Celery 3.1.23, RabbitMQ 3.6.5.

**Comment by ask** [comment]
The RPC result backend uses one queue per process, so only the process that initiated the task can retrieve the result.  It sounds like you would need a persistent backend here (i.e. any result backend other than amqp/rpc).  Using RabbitMQ as a broker and redis as a result backend is a popular combination, or you can also use a SQL database for storing results.

**Comment by ask** [comment]
The RPC backend is also experimental in 3.1, and some serious issues are fixed in the upcoming 4.0 release.

**Comment by robnagler** [comment]
Thanks @ask. In this case, we're using Flask as a single process and multiple threads. The task's status comes back just fine unless CELERY_TRACK_STARTED=True. Perhaps I'm misunderstanding what you mean by "initiating process".

**Comment by ask** [comment]
One of the bugs fixed in 4.0 is a race condition where result messages received before a handler is registered for an id is dropped.  Try using the 4.0rc to see if it's fixed there.  Backporting this fix to 3.1 is rather tricky since it involves a refactor of the result backends to have an async API.

**Comment by ask** [comment]
Btw, you could also use the HTTP API of Flower to do this kind of thing if you don't need the return value in serialized form (in monitoring events the result is `repr()` and possibly truncated)

**Comment by robnagler** [comment]
I [simplified our implementation](https://github.com/robnagler/rncelery) so that I could demo what I think the problem is.  You can see a log for 
[3.1.23](https://github.com/robnagler/rncelery/blob/master/celery-3.1.23.log) and [4rc3](https://github.com/robnagler/rncelery/blob/master/celery-4rc3.log) with the output of several runs, which to me are inconsistent. I would expect to see each task in STARTED state after the Celery worker pulls the task off the queue. However, that doesn't seem to be the case. Maybe  I'm reading the output incorrectly.

Note that the client (curl) is polling the server, which in turn asks the AsyncResult what's the state of the task. Perhaps that's the wrong model, but we want the server to be stateless (it isn't now).

We don't want to run Flower, because it would be another component in the system, which seems unnecessary. 

What we really want to be able to ask questions about the tasks such as "what tasks are queued and running?" I don't think that's possible with Flower, which only counts events. We want to know information about the tasks: which user is running them, what is the allocated run time, and how long has the job been running.

[Our system](https://github.com/radiasoft/sirepo) is designed to run physics simulations so it's a bit more complex than the usual Celery application. Perhaps we are overextending Celery. Please let me know if you think that's the case, and what you think an alternative might be (besides SLURM, Torque, etc. which are problematic for other reasons).

**Comment by alonelaval** [comment]
ok,i knew.....  cause  i  Confused this question be one day!!!!!   English not good!!!

**Comment by ask** [comment]
I'm testing track_started with the RPC result backend in latest master, and it seems to be working fine here.

From your test case here, it looks as if you are checking the result of a task across processes?

Does it use threads at all?  I just changed the RPC unique queue id to not be specific to the current thread - this means that multiple threads in the same process can query the result of a task.

**Comment by automactic** [comment]
I am having a similar case here. [Our project](https://github.com/openzim/zimfarm) use flask+celery. I observed the same behavior when using rpc backend. (see [issue](https://github.com/openzim/zimfarm/issues/2) for detail)

**Comment by auvipy** [comment]
try master and report if it's still the issue

**Comment by xucian** [comment]
it's not clear to me how this should be fixed. I'm getting STARTED -> PENDING -> SUCCESS
even if I manually set it to STARTED, it reverts to pending. so who's changing it?


I have `CELERY_TASK_TRACK_STARTED` in my config is:
```
REDIS_DB_CACHE = 0
REDIS_DB_CELERY = 1
REDIS_DB_CELERY_BEAT = 2
REDIS_PASSWORD = env('REDIS_PASSWORD', throw=True) if APP_DOCKER else None
REDIS_BASE_URL = f'redis://:{REDIS_PASSWORD}@kwm_redis:6379' if APP_DOCKER else 'redis://localhost:6379'
# Celery cfg
CELERY_BROKER_URL = f'{REDIS_BASE_URL}/{REDIS_DB_CELERY}'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL  # Using Redis for results too
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Important to automatically mark a task as started once it's called or triggered. the default is to have it on PENDING
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = TIME_ZONE
# Gets rid of a warning "CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer.."
#  Ref: https://stackoverflow.com/a/78088996/27678579
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# For long-running tasks, 1 is a good default:https://docs.celeryq.dev/en/stable/userguide/optimizing.html#prefetch-limits
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Store beat schedule in Redis: https://github.com/search?q=repo%3Asibson%2Fredbeat%20REDBEAT_LOCK_TIMEOUT&type=code
CELERY_BEAT_SCHEDULER = 'redbeat.RedBeatScheduler'
CELERY_BEAT_SCHEDULE = {
    'vacuum-db': {
        'task': 'app.tasks.task_vacuum_db',
        'schedule': timedelta(minutes=5 if DEBUG else 1440),
        'options': {'expires': 60}
    },
    'retry-processing': {
        'task': 'app.tasks.task_retry_processing_docs',
        'schedule': timedelta(minutes=1),
        'options': {'expires': 10}
    },
    'cleanup-old-webhook-events': {
        'task': 'apppay.tasks.cleanup_old_webhook_events',
        'schedule': timedelta(days=1),
        'options': {'expires': 3600}
    }
}
# Prevent retroactive task execution
CELERY_BEAT_MAX_LOOP_INTERVAL = 60  # Maximum time between scheduler runs (in seconds)
REDBEAT_REDIS_URL = f'{REDIS_BASE_URL}/{REDIS_DB_CELERY_BEAT}'
REDBEAT_LOCK_TIMEOUT = CELERY_BEAT_MAX_LOOP_INTERVAL + 60
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_BASE_URL}/{REDIS_DB_CACHE}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient'
        }
    }
}
```
