### ISSUE TITLE
Sending results of one task to multiple subtasks with canvas

### ISSUE THREAD

**Issue by Chris7** [celery/celery#3407]
I have several tasks that I would like to execute in parallel that follow a pattern like so:

> ```
>            Task 1
>           /       \
>     Task 2      Task 3
>           \       /
>          Final Task
> ```

Currently, I accomplish this via:

```
chains = []
task1 = signature('task1')
chains.append(task1 | signature('task2'))
chains.append(task1 | signature('task3'))
result = chord(chains)(signature('final_task'))
```

The issue is task1 is repeated N times (N being the length of the chain) instead of the results being fed to task2/task3. I am unable to see how to implement this pattern using the existing canvas primitives. Is this design pattern possible with the existing canvas module?

**Comment by Chris7** [comment]
I realized this is possible to accomplish by using this approach:

http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time

To do it, I can wait until the results of the cache are not some preset value, and then pass along the results of the task to each chain. While task 1 would still be run N times, the memory intensive aspects of it would only be run once. I am still interested if there is another mechanism to accomplish this though.

**Comment by ask** [comment]
There  was a feature request that proposed we could add the possibility to reuse signatures, nobody is working on that though.

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/893 is this issue related?

**Comment by auvipy** [comment]
@alukach

**Comment by Chris7** [comment]
I believe it is the exact as #893. I wish github search was better :(. Closing this for you.

**Comment by Chris7** [comment]
Though maybe one issue should stay open to mark the feature request? I vote for #893 if that is the case.

**Comment by auvipy** [comment]
yes lets continue disucssion there
