### ISSUE TITLE
Calling celery tasks from ruby on rails

### ISSUE THREAD

**Issue by anirbanroydas** [celery/celery#3408]
What If my workers/tasks are written in python, and I want to call those tasks from a ruby on rails app? Is it possible?

Or should I just use sidekiq for my use case?

**Comment by malinoff** [comment]
Supporting more than rabbitmq would be tricky (you'll need to reimplement kombu), but in case of just rabbitmq it's pretty simple. All you need is to follow the protocol http://docs.celeryproject.org/en/latest/internals/protocol.html, construct amqp messages and publish them.

This is a general question, not an issue, thus I'm closing this.
