### ISSUE TITLE
Memory Leak in Application

### ISSUE THREAD

**Issue by kaarthikeyapreyan** [celery/celery#3411]
After trying extensively though various forums none of the solutions seems to get the problem solved.

**Current setup**
celery --vesion = 3.1.23 (Cipater)
Python 2.7.6
Django 1.8.5
**rabbitmqctl status**
[{pid,1313}, {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.2.4"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.2.4"},
      {webmachine,"webmachine","1.10.3-rmq3.2.4-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.2.4-git680dba8"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.2.4"},
      {rabbit,"RabbitMQ","3.2.4"},      {os_mon,"CPO  CXC 138 46","2.2.14"},      {inets,"INETS  CXC 138 49","5.9.7"},      {mnesia,"MNESIA  CXC 138 12","4.11"},      {amqp_client,"RabbitMQ AMQP Client","3.2.4"},      {xmerl,"XML parser","1.3.5"},      {sasl,"SASL  CXC 138 11","2.3.4"},
      {stdlib,"ERTS  CXC 138 10","1.19.4"},      {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:30] [kernel-poll:true]\n"},
 {memory,
     [{total,69475288},      {connection_procs,661184},      {queue_procs,1053848},
      {plugins,56592},      {other_proc,14051464},      {mnesia,76424},      {mgmt_db,905008},
      {msg_index,3227880},      {other_ets,2711664},      {binary,21907704},      {code,19586901},      {atom,703377},      {other_system,4533242}]},
 {vm_memory_high_watermark,0.4}, {vm_memory_limit,5040372121}, {disk_free_limit,50000000}, {disk_free,18427154432},
 {file_descriptors,     [{total_limit,924},{total_used,13},{sockets_limit,829},{sockets_used,9}]},
 {processes,[{limit,1048576},{used,289}]}, {run_queue,0},{uptime,600576}]
...done.

**Problems facing**
1. memory leak
2. zombie process 

I am running periodic task only and have djcelery as part of my INSTALLED_APPS
The detached process are predominantly happening in the functions where i invoke a sub-process call
and fills up the whole memory in a days time

```
data = subprocess.Popen(query, stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=True)
    result = gdata.stdout.read()
```

I start celeryd  and celerybeat as a service with `CELEDYD_OPS="--detach --time-limit=1500 --concurrency=8"` (many forums pointed out that this would be the issue)
Also tried setting 
`CELERYD_MAX_TAKS_PER_CHILD=100`

**Comment by ask** [comment]
zombie processes are probably created if you don't collect the subprocesses that you create here.  Do you close the processes after use?

See also warning about using popen.stdin/.stdout/.stderr here, in paragraph after this section:
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.kill

You need to call `wait` on the process to collect them, not doing this is the number one cause of zombie processes.  Popen.communicate calls wait between reading/writing from the std pipes.

**Comment by kaarthikeyapreyan** [comment]
I am using the communicate method as part of the function
```
def execute_sp(query='', result_type='json', pre_formatted=False):
    # POSIX
    if not pre_formatted:
        query = query.split()
    proc = subprocess.Popen(query, stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=True)
    stdout_v, stderr_v = proc.communicate()
    if result_type == 'json':
        return json.loads(stdout_v)
    return stdout_v
```

Task.py code

```
@periodic_task(run_every=crontab(minute="*/15"))
def refresh_dev():
    with pushd(os.path.join('scheduled', 'utils', 'refresh')):
        result = execute_sp('java DevRefresh', result_type=None).split('\n')
        return result

```
Please let me know if i am missing anything.

**Comment by ask** [comment]
You added that later, or you were using it from the beginning? Are you seeing zombie processes when using communicate?

**Comment by kaarthikeyapreyan** [comment]
The process detachment is solved when i added the communicate method (no longer able to see it on the process tree), i am not able to reproduce the zombie as it happens over sshd(paramiko calls) and subprocess calls (very less frequency)
The big problem is the memory getting utilized. A big chunk is also diverted to the cache (is it because of the fact that i am running a single instance without any workers ?)
```
6025:~$ free -m
             total       used       free     shared    buffers     cached
Mem:         12017      7593        424          0        761       4498
-/+ buffers/cache:       2333       5683
Swap:  
```

**Comment by kaarthikeyapreyan** [comment]
Any updates on the issue am still facing it, could it be because am running a single node?

**Comment by kaarthikeyapreyan** [comment]
Also happened to notice another strange behavior not sure if its intended

In the django setting.py when i set both

```
TIME_ZONE = "US/Pacific"
CELERY_TIMEZONE = "US/Pacific"
```
None of the periodic tasks run, but when i set this it works fine
```
TIME_ZONE = "UTC"
CELERY_TIMEZONE = "US/Pacific"
```

**Comment by auvipy** [comment]
try master and report if it's still the issue.

**Comment by planmin** [comment]
@kaarthikeyapreyan https://pythondev.space/questions/running-python-script-through-django-application
