### ISSUE TITLE
Trying to support windows

### ISSUE THREAD

**Issue by xBeAsTx** [celery/celery#3415]
I think it's really bad decision avoid of supporting Windows. Python is cross-platform and it's his power. Better not to support some version of python then not to support windows at all.

In our project we use celery framework on linux as well on windows. And it's great! Yes on windows we must use threads pool but it's better then nothing. Is there any serious reason to remove windows support?

**Comment by ask** [comment]
The test suite is passing on Windows, and we will keep it that way, but we are unlikely to provide support for Windows issues.  This just reflects reality, as many WIndows specific issues are left unresolved for years.  We could say we support it and then not help people, or we can be honest upfront.

The biggest problem with Windows is that it's hostile to open source software, even if someone wants to help fix an issue they would have to pay for a license of Windows.  I was kindly donated a license some years ago, and we have kept the test suite passing on that, but we don't have licenses for e.g. Windows 10.

I a company wishes to sponsor Windows support, or wants commercial support to fix a bug then we'd be happy to do so.
