### ISSUE TITLE
Django 1.10 Task Issue

### ISSUE THREAD

**Issue by bspotted** [celery/celery#3419]
The newest Django Version(10.10) seems to have problems with celery decorators.
To be specific the decorator for periodic tasks is replicating every task every 5 minutes.

Only if run_every is set to run_every=(crontab(minute=0, hour=0)) it is working correctly

@periodic_task(
    run_every=(crontab(minute=0, hour='2-23')),
    queue='reviews',
    name="fb_reviews",
    ignore_result=True
)

EDIT:
CELERY_ENABLE_UTC = False

Is the issue. Once set to True it works again like a charm (adjusting the times manually before sending it is necessary).
However this is still a Bug. 
According to the report this should already be fixed?

**Comment by ask** [comment]
CELERY_ENABLE_UTC isn't something that you'd want to disable unless you want to communicate with really old versions of Celery.

**Comment by bspotted** [comment]
I tried to to use my timezone not utc time and it did work for eta tasks, periodic ones broke instantly.
CELERY_TIMEZONE = 'Europe/Berlin' does nothing, it still receiving tasks with the utc timestamp.
So if i can't disable it how can i change the timezone?

**Comment by GFite** [comment]
I've had better luck with shared_task annotation on the task, then in celery.py enter an app.conf.beat_schedule using celery beat
