### ISSUE TITLE
send_task with unknown task name crashing celery worker

### ISSUE THREAD

**Issue by and3rson** [celery/celery#3420]
We're using Celery with a single Django app, but we plan to put multiple Celery workers & applications on a single MQ exchange, thus allowing the tasks to get routed to appropriate workers and be ignored by the rest.

# STR
1. Create an app with some task:

    @shared_task
    def foo(): return 'bar'

2. Run the different task via `send_task:

    send_task('tasks.spam_with_eggs')

# Expected result

The worker should ignore the task, probably printing some error message.

# Actual result

The worker fails with an exception:

    ...
      File "/foo/.env/lib/python2.7/site-packages/kombu/messaging.py", line 630, in _receive_callback
        return on_m(message) if on_m else self.receive(decoded, message)
      File "/foo/.env/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 550, in on_task_received
        return on_unknown_task(None, message, exc)
      File "/foo/.env/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 489, in on_unknown_task
        id_, name = body['id'], body['task']
    TypeError: 'NoneType' object has no attribute '__getitem__'

Am I doing it wrong? Or does the mechanism need some improvement? Seems like `on_unknown_task` doesn't behave as expected. I'm just asking in case this needs to be fixed. I'm looking forward to contribute.

Thanks!
Andrew

**Comment by ask** [comment]
What version are you using?

**Comment by and3rson** [comment]
@ask, It's 4.0.0rc3 from PIP. I tried Git version with the same result.
