### ISSUE TITLE
Coverage data is not captured for running celery processes when using prefork POOL_CLS

### ISSUE THREAD

**Issue by elyezer** [celery/celery#3422]
I have a functional/integration test suite which I run against a running Celery + Django project and I wanted to capture coverage data. I've followed all the information needed to capture coverage data from subprocess but since Celery uses a fork from multiprocessing the coverage data is not being captured.

The above is not true when using `solo` or `threads` as `POOL_CLS` (`-P` command line option). When running using a different pool class the coverage data is being captured without any problem.

To clarify, by capturing coverage data I mean coverage information for the body of the Celery tasks. With that said when running in `prefork` mode, all but Celery tasks coverage data is captured.

This can be easily reproduced by following these steps:

Create a directory and create a `myapp.py` Python module with the same contents as https://github.com/celery/celery/blob/3.1/examples/app/myapp.py.

Create a virtual environment and install celery and coverage (I am using virtualenv-wrapper):

``` console
mkvirtualenv -p python3 celery
pip install celery==3.1 coverage threadpool
```

Then configure create a `sitecustomize.py` with the following contents on the corresponding Python site-packages:

``` python
import coverage
coverage.process_startup()
```

In my case I did:

``` console
cat > ~/.virtualenvs/celery/lib/python3.4/site-packages/sitecustomize.py << EOF
import coverage
coverage.process_startup()
EOF
```

Next create a `.coveragerc` file:

``` console
cat > .coveragerc << EOF
[run]
include=myapp
source=.
concurrency=
    thread
    multiprocessing
EOF
```

And export the `COVERAGE_PROCESS_START` with the path of the `.coveragerc` file, in my case it was located on the same directory:

``` console
export COVERAGE_PROCESS_START=.coveragerc
```

With all the above steps we are now set to check the the behavior using the different `POOL_CLS` options. First let's start with the default `prefork`:

Run celery on one terminal window:

``` console
celery -A myapp worker -l info
```

Then on a second window, open a python shell session and execute the `add` task:

``` console
$ python
>>> from myapp import add
>>> add.delay(2, 3)
```

After that, go back to the first window and press Ctrl+c to finish the celery process. If everything were setup properly some `.coverage.*` files should have been created. Here is the contents I got for all the coverage data files:

```
!coverage.py: This is a private format, don't read it directly!{"lines": {"/home/elyezer/code/celery/examples/app/myapp.py": [35, 39, 24, 25, 27, 28, 29]}}
```

As you can see the line 37 is not listed there, this is the line for the add task function body. As we can see the coverage data was not captured even though the task was executed.

Next step is to check how coverage data capturing works with `solo` or `threads`, on my local tests they behaved the same. For this we will use just `solo` since it does not require any additional package to be installed.

Make sure to clean up the coverage data files before proceeding:

``` console
rm .coverage.*
```

Now we can run celery using `solo` as the `POOL_CLS`, on the first terminal window:

``` console
celery -A myapp worker -l info -P solo
```

Repeat the task call on the second terminal window and exit the celery process on the first window. Then check for the generated coverage data files, on my local test I got:

```
!coverage.py: This is a private format, don't read it directly!{"lines": {"/home/elyezer/code/celery/examples/app/myapp.py": [35, 37, 39, 24, 25, 27, 28, 29]}}
```

Now the line 37 is included as expected.

The documentation about how to capture coverage data from subprocess can be found at [1]. Also coverage.py allows us to specify a concurrency library, multiprocessing is one of the valid values and coverage.py apply some patches [2] to the multiprocessing library when it is specified as one of the concurrency libraries.

I saw that Billiard is setting some information on the Python built-in multiprocessing library but it seem that it is missing something.

I wish I could capture the coverage information on a running celery process no matter the `POOL_CLS` used. 

[1] http://coverage.readthedocs.io/en/coverage-4.2/subprocess.html

[2] https://bitbucket.org/ned/coveragepy/src/257e52793fb0f28853ddca679f67b158107262bf/coverage/multiproc.py

**Comment by ask** [comment]
Pasting log from IRC related to this issue:

```
bmbouter: fix for that must probably go in the coverage module since they're already special handling multiprocessing
1:03 pm bmbouter
asksol: I agree and we can do that but we're at a loss for the root cuase
1:03 pm
cause
1:03 pm
the coverage works with multiprocessing but not with billiard so that brings us back here
1:03 pm asksol
https://github.com/nedbat/coveragepy/blob/maste...
1:04 pm bmbouter
yes we've been reading that also
1:05 pm
is it just a matter of the library having a different name?
1:05 pm asksol
celery doesn't use multiprocessing, it uses billiard so that couldn't possibly work
1:05 pm bmbouter
right but is it just a module name difference or is the billiard for meaningfully different?
1:06 pm asksol
it would probably be better for coverage to use multiprocessing.util.register_after_fork for this stuff
1:06 pm
bmbouter nods
1:06 pm
the remaining problem being calling cov.stop() / cov.save() on exit, but multiprocessing.util.Finalize could help with that
1:06 pm bmbouter
agreed
1:07 pm
wouuulllddd you be willing to write this on the issue
1:07 pm
this is likely all that we need from you to get this to the next stop
1:07 pm asksol
the billiard name is about the only difference, except billiard has the API of the Python version in the billiard version number. billiard 3.3 = CPython 3,3
1:08 pm
sure I can write that
1:08 pm
the preparation_data stuff is rather tricky on Windows though
1:08 pm
(it adds the 'stowaway' field to the data pickled for the child process
1:09 pm bmbouter
yes I see that here too
1:09 pm asksol
but if that's just a filename or something, it could just set an environment variable
1:09 pm
it could do that in any case really
1:10 pm bmbouter
yes all of this please write it will greatly help us
1:10 pm asksol
if it really is a complex object it could just store the pickled data in an environment variable
1:10 pm bmbouter
then we can take this up with ned
1:10 pm asksol
multiprocessing.Process calls the functions registered in the after_forker_registry at startup
1:11 pm
both multiprocessing and billiard uses the same registry for register_after_fork
```

**Comment by ask** [comment]
I guess Textual.app never got the ability to copy and paste a sensible log

**Comment by omaciel** [comment]
Hi @ask I work with @elyezer (the person who originally filed this issue) and some other folks who write automation for the Pulp project. We've been trying to generate an accurate code coverage report for our automation and it is my understanding that the issue here reported is the remaining piece of the puzzle for us :) So, I'd like to make a proposal: I have offered a $100 bounty (https://www.bountysource.com/issues/37458046-coverage-data-is-not-captured-for-running-celery-processes-when-using-prefork-pool_cls) if you or anyone else can get this issue fixed for us :) Looking forward to working with you :)

**Comment by omaciel** [comment]
@ask ping on this?

**Comment by auvipy** [comment]
it still on master? ask is no longer working on celery

**Comment by monakhv** [comment]
Is there any possibility that the ussue will be resolved?

**Comment by elyezer** [comment]
There two ways to get this working AFAIK, one would be that Celery start using Python's built in subprocess module instead of Billiard. The other option is to write a coverage.py plugin that would also hook into Billiard and collect coverage data.

I've patched coverage.py to add support to Billiard [1]. It has been a while that I don't use it but that gives you a base for what would be needed on the coverage.py side.

[1] https://github.com/elyezer/coveragepy/commit/fa2a94dccb34b017035ccb819b037cab88ff492f

**Comment by auvipy** [comment]
We have a plan to replace billiard in next major version v5

**Comment by elyezer** [comment]
@auvipy that is good to know. Will it be replaced by another tool or will use Python's builtin modules?

**Comment by auvipy** [comment]
that's still need design decision but we will replace it for sure, leveraging goodies from python3.5+ and modern eco system. here is a open issue https://github.com/celery/ceps/issues/1 feel free to share your views.

**Comment by tyrelkostyk** [comment]
Any update on resolving this issue?

**Comment by elyezer** [comment]
Should I take the closed as won't fix?
