### ISSUE TITLE
Django 1.6  + celery 3.1.23 memory leak.

### ISSUE THREAD

**Issue by trungnq1510** [celery/celery#3427]
I have upgraded celery but celery task doesn't flush memory when task ended. Using memory of     each task still increase after executed. What wrong of my implementation.

``` py
#celery config
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

BROKER_URL = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERYD_LOG_FILE = BASE_DIR + "/celery.log"
CELERYD_MAX_TASKS_PER_CHILD = 10
```

``` py
#One of my tasks
@task(name="task_send_email_booking_success")
def task_send_email_booking_success(email_obj={}):
    """
        send email reset password task
    """
    try:
        action_result, action_msg = send_email_booking_success(
            email_obj=email_obj
        )
    except Exception, e:
        return str(e)
    return_msg = "%s - %s" %(email_obj.get("customer_email", ""), email_obj.get("order_number"))
    return return_msg
```

``` py
#using task
task_send_email_booking_success.apply_async((order.get_email_information(),))
```

```
celery==3.1.23
kombu==3.0.35
django==1.6.10
```

**Comment by ask** [comment]
Do you have `settings.DEBUG` enabled?

**Comment by trungnq1510** [comment]
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

TEMPLATE_DEBUG = False

No. I don't enable it in production. Do you have any way to check it out. I will debug base on it.

**Comment by daredevil82** [comment]
I am noticing the same issue.  With five workers on an AWS C4.Large instance running PDFMiner for processing PDFs, I have to restart the instance every five hours or so due to out of memory.  When first starting the Celery service, memory usage is < 15%.  After approximately 200 executions of the task, memory is at 100%.

**Comment by auvipy** [comment]
try master and report if it's still the issue
