### ISSUE TITLE
How to implement terminate_job for eventlet concurrency backend?

### ISSUE THREAD

**Issue by yrik** [celery/celery#3429]
As I see `terminate_job` method implemented only in prefork concurrency backend https://github.com/celery/celery/blob/master/celery/concurrency/prefork.py#L116.

I'm running eventlet based code in the celery task, and to have it properly patched I must use `-P eventlet` option while starting workers. With this option Celery uses eventlet based TaskPool and patches the code. However, I also need to be able to terminate the task. How could it be possible to write missing `terminate_job` code?

I have tried with the following code:

```

class TaskPool(base.BasePool):
    ...
    def on_terminate(self):
        from eventlet import greenthread
        if self._pool is not None:
             greenthread.kill(self.getcurrent())

    def terminate_job(self, pid, signal=None):
        self.terminate()

    def terminate(self):
        self._state = self.TERMINATE
        self.on_terminate()

```

But it actually does not stop the execution. Plase help with valid approach.

Other option for me is to run celery in prefork mode, which support terminate method, and apply eventlet patch in the task file, but in this case I have an issue with django

```
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140575345698560 and this is thread id 140575293188528.
```

So I need any method to run eventlet code in the Celery task with the ability to stop it.
Plase advice.

**Comment by hostgame** [comment]
Same issue. Is it planned to implement job terminating in pools except prefork?

**Comment by puzanov** [comment]
Anyone?

**Comment by auvipy** [comment]
may be this issue is a guide for fix https://github.com/celery/celery/issues/3520

**Comment by auvipy** [comment]
closing for lack of response.
