### ISSUE TITLE
Celery worker crashes when fetching a task with ETA year < 1900

### ISSUE THREAD

**Issue by sttwister** [celery/celery#3431]
For example, when passing a task with eta=`'1018-06-02T08:00:00+01:44'`, it crashes with the following exception:

`Unrecoverable error: ValueError('year out of range',)`

> Stacktrace (most recent call last):
> 
>   File "celery/worker/__init__.py", line 206, in start
>     self.blueprint.start(self)
>   File "celery/bootsteps.py", line 123, in start
>     step.start(parent)
>   File "celery/bootsteps.py", line 374, in start
>     return self.obj.start()
>   File "celery/worker/consumer.py", line 279, in start
>     blueprint.start(self)
>   File "celery/bootsteps.py", line 123, in start
>     step.start(parent)
>   File "celery/worker/consumer.py", line 838, in start
>     c.loop(*c.loop_args())
>   File "celery/worker/loops.py", line 76, in asynloop
>     next(loop)
>   File "kombu/async/hub.py", line 279, in create_loop
>     item()
>   File "amqp/utils.py", line 42, in __call__
>     self.set_error_state(exc)
>   File "amqp/utils.py", line 39, in __call__
>     **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
>   File "kombu/transport/base.py", line 146, in _read
>     drain_events(timeout=0)
>   File "amqp/connection.py", line 326, in drain_events
>     return amqp_method(channel, args, content)
>   File "amqp/channel.py", line 1909, in _basic_deliver
>     fun(msg)
>   File "kombu/messaging.py", line 598, in _receive_callback
>     return on_m(message) if on_m else self.receive(decoded, message)
>   File "kombu/messaging.py", line 564, in receive
>     [callback(body, message) for callback in callbacks]
>   File "celery/worker/consumer.py", line 459, in on_task_received
>     callbacks)
>   File "celery/worker/strategy.py", line 70, in task_message_handler
>     eta = to_timestamp(to_system_tz(req.eta))
>   File "celery/utils/timeutils.py", line 136, in to_system
>     return localize(dt, self.local)
>   File "celery/utils/timeutils.py", line 289, in localize
>     dt = dt.astimezone(tz)
>   File "celery/utils/timeutils.py", line 82, in utcoffset
>     return self.DSTOFFSET if self._isdst(dt) else self.STDOFFSET
>   File "celery/utils/timeutils.py", line 109, in _isdst
>     stamp = _time.mktime(tt)

While the ETA date can be considered invalid and is caused by errors in the user application, it should not crash the worker.

I had no option but to purge the entire queue and reschedule all the tasks with proper dates to recover from this.

**Comment by ask** [comment]
Related to #3078
