### ISSUE TITLE
Memory leak with redis broker

### ISSUE THREAD

**Issue by Wyzzcow** [celery/celery#3436]
celery leaks when redis becomes unavailable.
This is easily reproducible by stopping redis while celery is working.

```
from celery import Celery
from celery.task import periodic_task
from datetime import timedelta
app = Celery('tasks', broker='redis://:@localhost:6379/13')

@periodic_task(run_every=timedelta(seconds=.5))
def print_hello():
    print "hello"
```

celery -A tasks worker
celery -A tasks beat

The following screenshot shows the celery beat process when redis is stopped shortly after celery beat is started, and then restarted (memory is never freed).

![image](https://cloud.githubusercontent.com/assets/8915667/18351089/c12b4128-75a6-11e6-99a1-40452cb5d854.png)

```
amqp (1.4.9)
billiard (3.3.0.23)
celery (3.1.23)
kombu (3.0.35)
redis (2.10.5)
```

**Comment by mkuchen** [comment]
+1 on this - I have...
```
billiard (3.3.0.23)
celery (3.1.23)
kombu (3.0.35)
redis (2.10.3)
```

...and I am currently experiencing the same problem with my app; a linear growth in memory usage by both my web workers and my async workers (on Heroku).  I've made a workaround by cycling the dynos every 3 hours, but this is less than optimal obviously.

Here's some compelling evidence that it's a leak in Celery delay/apply_async:
```
>>> import objgraph
>>> from my_app.tasks import add
>>> 
>>> add(1,2)
3
>>> objgraph.show_growth()
>>> add(1,2)
3
>>> objgraph.show_growth()
>>> import gc; gc.collect()
0
>>> objgraph.show_growth()
>>> add.delay(2,3)
<AsyncResult: 36bd1893-8540-40e3-a1a1-2d1a93e44b14>
>>> import gc; gc.collect()
20
>>> objgraph.show_growth()
function             30012      +371
dict                 40348      +120
tuple                23707       +93
list                 38877       +55
weakref               6820       +51
type                  4605       +46
getset_descriptor     3065       +39
property              1549       +17
cached_property        129       +15
module                1649       +13
```

@ask - do you have any troubleshooting suggestions for this?  I'm contemplating setting `CELERY_MAX_CACHED_RESULTS`, but it says in the documentation that there's a default value of 100 for that, so it shouldn't be causing the problem.

**Comment by costasgambit** [comment]
There's a ref cycle in AsyncResult. This line, specifically:

`self.on_ready = promise(self._on_fulfilled)`

`_on_fulfilled` is a bound method that points to self, but self also points to a promise that points to `_on_fulfilled`.

**Comment by mkuchen** [comment]
Bingo!  Awesome find @costasgambit.

**Comment by costasgambit** [comment]
Whoops, my apologies. I did find a source of garbage, but it's actually in master, not 3.1.

**Comment by mkuchen** [comment]
@ask - while running a datamigration on my production instances I noticed some behavior that I think you'll find helpful in hunting down memory leaks in Celery.

The datamigration is structured like so:
```
@celery_app.task(queue='performance_queue')
def perform_datamigration_chunk(chunk):
    users = Users.objects.only('pk').filter(pk__in=chunk).distinct()
    for user in users.iterator():
        user.perform_data_operation() # sets a few fields to a specific value
    return True

@celery_app.task(queue='performance_queue')
def perform_datamigration(**filters):
    # sub-function, used only here
    def get_chunks(l, n):
        """ Yield successive n-sized chunks from l. """
        for i in xrange(0, len(l), n):
            yield l[i:i+n]

    users = Users.objects.filter(**filters)
    uids = users.values_list('pk', flat=True)
    chunks = get_chunks(list(uids), chunk_size)

    for chunk in chunks:
        perform_datamigration_chunk.delay(chunk=chunk)
```

The `perform_datamigration` task is then invoked, like so:
```
perform_datamigration.delay(**filters) # filters is some arbitrary list of filters to perform the action on
```

Here's the interesting part:
- when the task was first called there was a large spike in memory usage from evaluating the initial rather large queryset and shoving it into a `values_list` - this memory was then released back to the system, as is supposed to happen.
- after that there was a consistent memory climb wherein the memory was not released back to the system as thousands of `perform_datamigration_chunk` tasks were running.
- I performed a restart on the `performance_queue` queue via the Heroku CLI: `heroku restart -a my_app performance_queue`.
- **After this restart memory returned to pre-datamigration levels and remained stabile, even as thousands of `perform_datamigration_chunk` tasks continued to run.**
- This would support the theory that Celery is writing to the Redis queue in such a way that leaks memory continuously after the write happens - restarting the queue returns the memory to the system and *the tasks continuing to run do not leak memory*.

Here's a screen shot of the memory consumption behavior I described above:
![screencap](https://i.imgsafe.org/d016cef83f.png)

**Comment by dkingman** [comment]
@ask @mkuchen Having the same issue while running on Heroku with the exact same dependencies.

**Comment by toorsukhmeet** [comment]
I'm still seeing leaks with AsyncResult on Celery 4.0.2 using RPC results backend on Ubuntu 16.04. Was @costasgambit 's leak fixed? @ask @mkuchen 

Here's my config:
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc://admin:**@localhost/
```

**Comment by ggstuart** [comment]
My redis footprint is 900MB+ and redis is now blocking writes. Is there anything I can do?

```
# Memory
used_memory:1020972328
used_memory_human:973.68M
used_memory_rss:108736512
used_memory_peak:4101518880
used_memory_peak_human:3.82G
used_memory_lua:35840
mem_fragmentation_ratio:0.11
mem_allocator:jemalloc-3.6.0

```

**Comment by sunchuanleihit** [comment]
use this param  CELERYD_MAX_TASKS_PER_CHILD = 100, a worker will be killed after complete  100 tasks and a new worker will be created。

**Comment by thedrow** [comment]
If this is still the case with 4.0 please file a new issue.
