### ISSUE TITLE
Problem with queue with max-length defined.

### ISSUE THREAD

**Issue by madhur** [celery/celery#3440]
I am using celery 3.18 and using beat scheduler to put a task in queue every minute. I have a max length defined to 1 for the queue.

```
CELERYBEAT_SCHEDULE = {
    'user_engagement_task': {
        'task': 'tasks.engagement_beat_task',
        'schedule': crontab(minute='*/1')
    }
}

```

The queue is consumed by consumer in node.js.

```
 amqp.connect(config.get('amqp')).then(function (conn) {
        return conn.createChannel().then(function (ch) {
            ch.prefetch(1);

            var ok = ch.assertQueue(q, {durable: true, maxLength: 1});
```

I get the following in celery beat logs and no message is inserted in queue

> Message Error: Couldn't apply scheduled task user_engagement_task: queue.declare: server channel error 406, message: PRECONDITION_FAILED - inequivalent arg 'x-max-length' for queue 'tasks.engagement_beat_task' in vhost '/': received none but current is the value '1' of type 'byte'

This is working in docker environment on MAC OSX, but failing in Centos 6 environment. I am using rabbitmq 3.5.6

**Comment by ask** [comment]
You cannot define queue x to have a max-length of 1, then declare it again as having no limit.

Make sure celery beat is using the same arguments:

```py
from kombu import Exchange, Queue

app.conf.CELERY_QUEUES = [
    Queue('foo', Exchange('foo'),
                 routing_key='foo'
                 queue_arguments={'x-max-length': 1},
    ),
]

**Comment by ask** [comment]
I guess there's no longer any programmers working at GitHub now that it no longer uses a fixed-width font for code examples :(

**Comment by madhur** [comment]
👍
