### ISSUE TITLE
First Steps documentation refers to a task_result_backend setting

### ISSUE THREAD

**Issue by miikkas** [celery/celery#3442]
The Keeping Results section of the First Steps part in Celery docs refers to a setting named **task_result_backend**. A setting with that name isn't listed in the table at the Configuration and defaults documentation page, but a **result_backend** setting however seems to exist, which is probably what was meant at the First Steps page.

EDIT: Forgot to mention that I'm reading the 4.0.0rc4 docs.

**Comment by berkerpeksag** [comment]
Thanks for the report!
