### ISSUE TITLE
Worker hangs everytime a task is sent

### ISSUE THREAD

**Issue by ChillarAnand** [celery/celery#3447]
Consider this simple task

```py
@app.task
def get_frida_device(serial_number):
    print('getting device')
    import frida
    d = frida.get_device(serial_number)
    print('got {}'.format(d))
```

When running as function `get_frida_device('foo')` everything works fine. However when it is queued, it hangs at `frida.get_device` and never prints last line.

```sh
→ celery report

software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:3.5.2
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

Celery conf:

```py
CELERYD_LOG_COLOR = False
BROKER_URL = 'amqp://'
CELERYD_PREFETCH_MULTIPLIER = 1
CELERYD_CONCURRENCY = 1
CELERY_ACKS_LATE = True
```

**Comment by ChillarAnand** [comment]
After debugging a little, it seems frida is calling a C function [PyDeviceManager_enumerate_devices ](https://github.com/frida/frida-python/blob/4afd9debd489e3920b85cb6c542de10aabb0dcce/src/_frida.c#L783) which hangs worker.

**Comment by ask** [comment]
It's perfectly able to call C functions, sounds more like this library is not fork safe!

**Comment by ChillarAnand** [comment]
Thanks for the clarification @ask.

**Comment by gil01karougbe** [comment]
does this issue exists in current versions?
