### ISSUE TITLE
orchestrating task tree

### ISSUE THREAD

**Issue by khafan246** [celery/celery#3448]
I'm trying to create a workflow of dependent tasks and fire the execution of them. and finally notify when they are all done. but celery seem's to have shortcommings to implement this:
in some situations, the [Parallel Split](http://www.workflowpatterns.com/patterns/control/basic/wcp2.php) pattern is needed, e.g. task A result should be splitted into many B tasks. i know that i can create a third task to take task A results, apply them to many B tasks and group the results, but i don't want to group them as they would link further to other tasks independently.

**Comment by ask** [comment]
AFAICT parallel split just means there are independent workflows executing in parallel:

```py

A.s() | group(
    B1.s() | B2.s(),
    C1.s() | C2.s()
)

````

If the AND there means A returns two values and and each branch receives one of them,
then you could implement AND as:

```py
@app.task(bind=True)
def AND(self, retval, *signatures):
    return group(
        self.app.signature(sig).clone(value)
        for sig, value in zip(signatures)
    ).delay()
```

```py

A.s() | AND.s(B1.s() | B2.s(), C1.s() | C2.s())

```


The problem with this approach is that you can no longer simply call `result.get()` to retrieve the result, as some of them will be promises that you have to follow,
but you are generally discouraged from doing RPC with workflows anyway.

**Comment by khafan246** [comment]
@ask let me explain more what i mean from task tree with parallel split :
suppose the ```A``` task is in tree root, which returns a list of (prior) unknown length. in the 2nd level, there is ```B``` that should be spawned for each item in ```A``` result. in 3rd level, there is ```C``` that acts on each ```B``` returned item and so forth.

**Comment by bruno-rino** [comment]
If you want processes to be spawned, you should look at task.replace()

**Comment by mbande** [comment]
@bruno-rino as task.replace() is new in version 4.0, and this version is not production ready.
so this is not an option.

**Comment by auvipy** [comment]
try latest release and better post questions to mailing list, and if it seems something should be addressed in celery then report in github.
