### ISSUE TITLE
worker do not use all pool available

### ISSUE THREAD

**Issue by mbande** [celery/celery#3451]
i have started a multi worker setup with a worker with concurrency 64 listening on a certain queue
monitoring system processes, all workers are up and running, and while queue is full of messages, the active task count in any time is < 10, and the remaining tasks are just scheduled to run at worker
all the tasks going to the queue are a single function, with no retry/eta on them, but they expires if they wait some long time in queue.
what's going on? any help would be highly appreciated

**Comment by ask** [comment]
Do you pass the `-Ofair` command-line argument to the worker?  (This will be default behavior in 4.0)

**Comment by mbande** [comment]
I checked both with/without this option, with no effect on the issue

**Comment by mbande** [comment]
tasks are logging to a file, and the file size was grown to ~ 6 GB
deleting the file almost resolved this issue !!! now, the number of active tasks is ~40
what is happening here?

**Comment by mbande** [comment]
@ask using the latest 4.0.0rc5 version, the problem exists yet
any idea on this?

**Comment by auvipy** [comment]
whats the update on latest releases?
