### ISSUE TITLE
Chains with multiple workers

### ISSUE THREAD

**Issue by viperfx** [celery/celery#3454]
I recently came across the chain primitive and it was a perfect fit for a use case that I had in mind. I will try to go over the problem without going into too much detail, based on some events that come in a particular order, we create a chain (we actually append a list of events to redis - we serialise the signature). Then when an event arrives that usually arrives towards the end of a particular series of events, we use that as a trigger to execute the chain. These tasks, when run in the right order, will produce the right numbers in a report that we generate. We know what to expect when the tasks have been run in the correct order. It's quite obvious when something has been run out of sequence. One thing to note, is that our tasks do have a particular return, most of the tasks, simply just read/write data in redis and do number crunching. So we don't really care about the return results of the chain or the particular signatures/tasks in the chain, but we do care about the order that they are run!

Here are our findings:

When a worker is run with a `concurrency of 1`. Everything is fine. 

When a worker is run with a `concurrency of >` or multiple workers are run with `a concurrency of 1`, the numbers in the report start to go wrong and we know that the order that the tasks are being executed are slightly different.

```
@celery.task
def execute_chain(tracking_id):
    # CeleryTaskChain is a redis abstraction. 
    task_chain = CeleryTaskChain(tracking_id)
    # task_chain['chain'] is a list of signatures that we unserialise and use to form the chain.
    some_list = [signature(task) for task in task_chain['chain']]
    if len(some_list) > 0:
        # Note: This executes the chain. If we use .get(), the worker hangs. Even with concurrency of 1
        chain(*some_list)()
        print 'chain executed %s' % (len(task_chain['chain'])) 
        task_chain.delete()
```

How can we ensure the chains run in sequence with multiple workers and high concurrency?

**Comment by viperfx** [comment]
Bump. Can anyone answer this question?

**Comment by auvipy** [comment]
this type of questions are better fitted for mailing list or irc channel.
