### ISSUE TITLE
Stopping/Restarting workers works strange with BROKER_HEARTBEAT set

### ISSUE THREAD

**Issue by auuron** [celery/celery#3458]
Hi, some time ago i turned on and set BROKER_HEARTBEAT to 20
`BROKER_HEARTBEAT = 20`
After that change, i've observed strange behaviour:
1. Let's assume we have two workers consuming same queue (w1, w2).
2. Both are running.
3. w1 is running some task (A-123123).
4. I want to stop/restart w1 and im doing it via celery multi stop / restart      or just celeryd script.
5. w1 is being stopped (TERM was sent). w1 is still running because it's finishing it's tasks.
6. w2 runs A-123123 (is redelivered?), w1 still didn't finish it.
7. w1 finishes his tasks (including A-123123).
8. w2 finishes A-123123.
9. A-123123 was run twice.

So, basing on this example, whole restart/stop process is ruined.

**Comment by auvipy** [comment]
sorry  for late response. could you still verify this on latest master?

**Comment by auvipy** [comment]
and post questions to irc or mailing lists first
