### ISSUE TITLE
celery multi passing wrong cmd through to apps.multi.Node

### ISSUE THREAD

**Issue by jcushman** [celery/celery#3460]
Running the master branch (or 4.0.0rc4 release), I get this error when running `celery multi`:

```
$ celery multi start 2 --verbose
celery multi v4.0.0rc4 (0today8)
> Starting nodes...
       	> celery1@perma:   /home/vagrant/.virtualenvs/perma/bin/python2 celery -n celery1@perma --pidfile=celery1.pid --logfile=celery1%I.log --executable=/home/vagrant/.virtualenvs/perma/bin/python2
/home/vagrant/.virtualenvs/perma/bin/python2: can't open file 'celery': [Errno 2] No such file or directory
* Child terminated with exit code 2
FAILED
       	> celery2@perma:   /home/vagrant/.virtualenvs/perma/bin/python2 celery -n celery2@perma --pidfile=celery2.pid --logfile=celery2%I.log --executable=/home/vagrant/.virtualenvs/perma/bin/python2
/home/vagrant/.virtualenvs/perma/bin/python2: can't open file 'celery': [Errno 2] No such file or directory
* Child terminated with exit code 2
FAILED
```

(Note the invalid `python2 celery` in the generated commands for workers, which should be `python2 -m celery worker --detach`.)

The issue seems to be that the `multi` function in bin/celery.py passes `prog_name` in as the `cmd` argument to `multi.execute_from_commandline`, and that gets passed all the way through to become the `cmd` argument to `apps.multi.Node.__init__`, which would otherwise set a sensible default.

Adding an empty `--cmd` flag works around the problem, causing `Node.__init__` to receive an empty string and use the default as expected:

```
$ celery multi start 2 --verbose --cmd
celery multi v4.0.0rc4 (0today8)
> Starting nodes...
       	> celery1@perma:   /home/vagrant/.virtualenvs/perma/bin/python2 -m celery worker --detach -n celery1@perma --pidfile=celery1.pid --logfile=celery1%I.log --executable=/home/vagrant/.virtualenvs/perma/bin/python2
OK
       	> celery2@perma:   /home/vagrant/.virtualenvs/perma/bin/python2 -m celery worker --detach -n celery2@perma --pidfile=celery2.pid --logfile=celery2%I.log --executable=/home/vagrant/.virtualenvs/perma/bin/python2
OK
```

... but I'm not sure what the actual fix should be -- or if I'm just doing something wrong?

Thanks!

**Comment by ask** [comment]
Thanks!  I think using prog_name is a remnant from the olden days before it used `interpreter -m celery` that suddenly got activated after the refactor.
