### ISSUE TITLE
Different behaviour without --app between celery multi start and celery worker

### ISSUE THREAD

**Issue by chehsunliu** [celery/celery#3468]
My application is simple, a binary `blahadmin`, a module `blah.core.blahcore` and a configuration file `/etc/blah/celeryconfig.py`. The entire project is installed via `pip` so that the binary can recognise the module.

```python
# file /etc/blah/celeryconfig.py
BROKER_URL = [
    'amqp://username:password@192.168.11.111/bbbb,
]
```

```python
# file: blah/core/blahcore.py
import imp

from celery import Celery

celeryconfig = imp.load_souce('blah.celeryconfig', '/etc/blah/celeryconfig.py')
app = Celery('blahtasks')
app.config_from_object(celeryconfig)
```
```python
# file: bin/blahadmin
from blah.core.blahcore import app

if __name__ == '__main__':
    app.start()
```

In my scenario, I don't want to specify the `--app` argument and it works for this case.

```bash
$ blahadmin worker -c 2 -Q queue1,queue2 --loglevel=INFO
```

However, in the case `multi start`, I get connection refused errors since it is trying to connect to `amqp://guest:**@127.0.0.1:5672//`.

```bash
# Failed
$ blahadmin multi start w1 -c 2 -Q queue1,queue2 --loglevel=INFO
# Succeeded
$ blahadmin multi start w1 --app=blah.core.blahcore -c 2 -Q queue1,queue2 --loglevel=INFO
```

Why do I have to add the argument in `multi start`?

**Comment by ask** [comment]
The worker detaching mechanism uses `execv` to make sure the process is clean, so it needs
to be passed an explicit app.

It may be possible to derive that from the 'currently used' app, but I'm thinking it's easier
when you have an app argument in sys.argv to begin with (otherwise how to you get the canonical path from an app instance).
