### ISSUE TITLE
TypeError: <_weakrefset.WeakSet object at 0x7f83e192b2d0> is not JSON serializable

### ISSUE THREAD

**Issue by sourav82** [celery/celery#3469]
```
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:4.0.0rc4 (0today8) kombu:4.0.0rc4 py:2.7.12
            billiard:3.5.0.1 py-amqp:2.1.0
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

API - GET /api/task/info/ throws below error always -

Flower server log -

```
[E 160925 10:44:06 web:1496] Uncaught exception GET /api/task/info/893dc5e8-1efe-4fb2-b648-5c64c72d8055 (::1)
    HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/api/task/info/893dc5e8-1efe-4fb2-b648-5c64c72d8055', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:5555', 'Accept': '*/*', 'User-Agent': 'curl/7.47.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flower/api/tasks.py", line 602, in get
        self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <_weakrefset.WeakSet object at 0x7f83e192b2d0> is not JSON serializable
[E 160925 10:44:06 web:1908] 500 GET /api/task/info/893dc5e8-1efe-4fb2-b648-5c64c72d8055 (::1) 7.06ms
```

Curl client log -

```
*   Trying ::1...
* Connected to localhost (::1) port 5555 (#0)
> GET /api/task/info/893dc5e8-1efe-4fb2-b648-5c64c72d8055 HTTP/1.1
> Host: localhost:5555
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Sun, 25 Sep 2016 10:44:06 GMT
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Server: TornadoServer/4.2
<
* Connection #0 to host localhost left intact
```

Looks like celery task item çhildren'object is not JSON serializable. I have opened a bug with Flower as well (https://github.com/mher/flower/issues/617). Could you please suggest something here?

**Comment by alzeih** [comment]
I've updated #3490 

Fix works for for me, although I only experienced the symptoms with the cached properties `root` and `parent` (and I assumed encoding `children` was just something I hadn't encountered yet but with the same cause.)

@sourav82 does this patch work for you?

**Comment by ask** [comment]
Great work @alzeih :)

**Comment by sourav82** [comment]
@alzeih Sorry to inform you it did not work for me with the master branch code of celery. Below is the configuration -

```
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:4.0.0rc6 (0today8) kombu:4.0.0rc6 py:2.7.6
            billiard:3.5.0.1 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:redis://redis-server:6379/0

CELERY_ACKS_LATE: False
BROKER_CONNECTION_TIMEOUT: 60
timedelta: <type 'datetime.timedelta'>
CELERYBEAT_SCHEDULE: {
    'every-minutes': {   'schedule': datetime.timedelta(0, 300),
                         'task': 'rest.health_check'},
    'purge-task-log': {   'schedule': datetime.timedelta(7),
                          'task': 'rest.purger'}}
BROKER_TRANSPORT_OPTIONS: {
    'socket_timeout': 10}
BROKER_POOL_LIMIT: 20
CELERY_TIMEZONE: 'UTC'
BROKER_URL: u'redis://redis-server:6379/0'
os: <module 'os' from '/usr/lib/python2.7/os.pyc'>
CELERY_RESULT_BACKEND: u'redis://redis-server:6379/0'

0.9.1
4.0.0rc6 (0today8)
```

Below is the stack trace for Flower API - GET /api/task/info/task_id -

```
[E 161022 05:45:54 web:1496] Uncaught exception GET /api/task/info/75e5b157-6f42-4cee-89c8-3873e6658e0d (45.113.100.237)
    HTTPServerRequest(protocol='http', host='52.91.182.220:5555', method='GET', uri='/api/task/info/75e5b157-6f42-4cee-89c8-3873e6658e0d', version='HTTP/1.1', remote_ip='45.113.100.237', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Upgrade-Insecure-Requests': '1', 'Host': '52.91.182.220:5555', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flower/api/tasks.py", line 602, in get
        self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <_weakrefset.WeakSet object at 0x7f68203a36d0> is not JSON serializable
```

Could you please let me know if I am missing something here?

**Comment by alzeih** [comment]
@sourav82 Thanks for letting me know

I've tried some of the examples from http://docs.celeryproject.org/en/master/userguide/canvas.html  with 4.0.0rc6 and I haven't seen this error myself yet.

When I tried http://docs.celeryproject.org/en/master/userguide/canvas.html#chains , res.children returned a None for me from the shell, and I'm not sure why. 
However, in flower it shows "<_weakrefset.WeakSet object at 0x...>" for children, but does not crash. It shows this for all tasks for me (with a different memory address).

I tried python3.5.2 and python 2.7.12, with no difference.

Do you have a minimal example of the tasks and how they are called that causes this error?

**Comment by alzeih** [comment]
@sourav82 are you using flower's persistence option? Can you try without loading from persistence?

**Comment by bhargav95** [comment]
@alzeih I am still getting the same error when I use the API to get info of a task. I printed the json and the child is still not getting serialized. Can you guide me as to how to fix this?
The versions I have installed
tornado==5.1.1
amqp==2.4.1
celery==4.2.1
flower==0.9.2

`{'task-id': u'4c19e116-cb5c-44b7-b7fc-cbfb35720b8d', u'root_id': u'4c19e116-cb5c-44b7-b7fc-cbfb35720b8d', u'result': None, u'children': <_weakrefset.WeakSet object at 0x7f34caebf210>, u'clock': 152905, u'exchange': None, u'routing_key': None, u'failed': None, u'state': u'RECEIVED', u'client': None, u'parent_id': None, u'kwargs': u'{}', u'sent': None, u'args': u'[27, 425]', u'parent': None, u'retries': 0, u'started': None, u'timestamp': 1550084639.177732, u'expires': None, 'worker': u'celery@ip-172-xx-xx-xxx', u'rejected': None, u'revoked': None, u'received': 1550084639.177732, u'exception': None, u'name': u'Sensus.tasks.scheduled_broadcast_task', u'succeeded': None, u'traceback': None, u'eta': u'2019-02-15T13:40:01.065959-05:00', u'retried': None, u'runtime': None, u'root': <Task: Sensus.tasks.scheduled_broadcast_task(4c19e116-cb5c-44b7-b7fc-cbfb35720b8d) RECEIVED clock:152905>}`

`Uncaught exception GET /api/task/info/4c19e116-cb5c-44b7-b7fc-cbfb35720b8d (xxx.xxx.xx.xxx)
HTTPServerRequest(protocol='http', host='xx.xxx.xx.xx:5555', method='GET', uri='/api/task/info/4c19e116-cb5c-44b7-b7fc-cbfb35720b8d', version='HTTP/1.1', remote_ip=xxx.xx.xx.xxx')
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/web.py", line 3006, in wrapper
    return method(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flower/api/tasks.py", line 605, in get
    self.write(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/web.py", line 746, in write
    chunk = escape.json_encode(chunk)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/escape.py", line 81, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/home/ubuntu/miniconda3/envs/emotive/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/home/ubuntu/miniconda3/envs/emotive/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/miniconda3/envs/emotive/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/miniconda3/envs/emotive/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <_weakrefset.WeakSet object at 0x7f34caebf210> is not JSON serializable`
