### ISSUE TITLE
Persistence of list of instances across celery worker

### ISSUE THREAD

**Issue by axhue** [celery/celery#3470]
Hello!

I was wondering is it possible to have class based task that stores instances in a list and can modify the instances in other celery tasks. 
I wanted to clarify from the documentation saying that The Task class is instantiates once per process, so I would not be able to keep _instances variable consistent across other workers?

```py
class ConvoTracker(celeryapp.Task):
     _instances = []
     @classmethod
     def new_instance(id):
         _instances.append(Conversation(id))
     @classmethod
     def find_and_modify(id):
         instances = self.list_instances()
        for obj in instances:
            if id in obj:
                obj.state='CHANGED_STATE'
```

Thanks!

**Comment by ask** [comment]
The task may be instantiated once per process, but that depends on if fork is used on that platform.

If the process is forked, then the child process will inherit the instance from the parent.

Any changes to global variables (which includes the `_instances` class variable you have here), will only be visible during the process that makes the change.  The parent may initialize globals that are shared with the children (think precalculated caches, etc.)
