### ISSUE TITLE
Port replication when using gunicorn on docker

### ISSUE THREAD

**Issue by odedhar** [celery/celery#3471]
Using Django with celery 3.1.23 and django 1.82(issue also seen in other versions of Django and celery)
Broker = Redis (same issue also seen with RabbitMQ)
Running in Docker container.
It seems that all threads opened by gunicorn are using the same ports towards the broker:
From within the container, lsof -P | grep 6379 gives:
gunicorn   42         root   22u     IPv4              42597      0t0     TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42         root   23u     IPv4              42598      0t0     TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  50     root   22u     IPv4              42597      0t0     TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  50     root   23u     IPv4              42598      0t0     TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  51     root   22u     IPv4              42597      0t0     TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  51     root   23u     IPv4              42598      0t0     TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  52     root   22u     IPv4              42597      0t0     TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn   42  52     root   23u     IPv4              42598      0t0     TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)

As can be seen, ports 42587 and 42598 are used by all threads opened by worker PID 42. This causes messages not reaching the broker from time to time (without any celery exception).

**Comment by ask** [comment]
Connection pools are reset after fork, but that relies on gunicorn to be calling the multiprocessing after forker registry.

Shouldn't gunicorn be closing open file descriptors on fork?

**Comment by auvipy** [comment]
try master and report if it's still the issue
