### ISSUE TITLE
Use celery 3.1.x or later can't run ansible task, but use 3.0.x is ok

### ISSUE THREAD

**Issue by jackin853** [celery/celery#3472]
When I use celery integrting with ansible, I encountered a problem,  toss him a long time.
I use celery 3.1.x or later can't run ansible task, The problem is "AttributeError: 'NoneType' object has no attribute 'terminate'". And I use 3.0.x, It works well.
I think that this problem is or not related to "#1709 Tasks are not allowed to start subprocesses"?
Thanks.

**Comment by ask** [comment]
Can you please paste the full traceback?

**Comment by auvipy** [comment]
try master and report if it's still the issue
