### ISSUE TITLE
Cyclic Dependencies

### ISSUE THREAD

**Issue by richburdon** [celery/celery#3474]
Suppose I have two components: Frontend and Backend and the Celery Worker as the Backend.

[backend.py]
```
app = Celery(tasks="tasks")
```
[tasks.py]
```
import backend

@app.task()
def my_task():
    complex_logic_that_depends_on_secure_and_complicated_modules()
```
[frontend.py]
```
import tasks

app = Flask()

@app.route('/work')
def work():
    tasks.my_task.delay()

app.start()
```

It seems counter-intuitive to me that the "caller" (frontend.py) should need to depend on the implementation details (and dependent modules) of the task. I'd like to decouple them so that changes to the Backend logic don't require a redeploy of the Frontend.

Is there any way around this? I've tried having the tasks depend on current_app, but: a) this is discouraged in the docs; b) it leads to complex import dependencies (i.e., the frontend's app instance has to be defined before any tasks are imported -- otherwise current_app refers to a "default" instance). Also, using DI makes the issue more complex (since the Celery instance has to be injected).

**Comment by kindule** [comment]
@richburdon What about use send_task for decoupling.

http://docs.celeryproject.org/en/latest/reference/celery.html?highlight=send_task#celery.Celery.send_task

**Comment by richburdon** [comment]
AAAAAAAAAAAH!

@kindule Thank you. I was looking for that for days.

**Comment by kindule** [comment]
Can you close the issue as we already get the answer?
