### ISSUE TITLE
get_task_logger('celery') causes an infinite loop when logging

### ISSUE THREAD

**Issue by imbaczek** [celery/celery#3475]
That's because celery.parent becomes celery.task, but celery.task's parent is celery. This causes an infinite loop inside logging. Granted it's in the category of 'you shouldn't do that' but still lost a few hours where an exception from get_task_logger() would save me from this particular footgun.

celery 3.1.23

**Comment by ask** [comment]
Thanks! That sounds like a hellish debugging session...

**Comment by imbaczek** [comment]
yup, had to take out the big guns (gdb with python-dbg). thanks for the fix!
