### ISSUE TITLE
Celery redis backend not always returning result

### ISSUE THREAD

**Issue by Andarius** [celery/celery#3483]
I'm running a celery worker such that:

```
 -------------- celery@ v3.1.23 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.4.0-31-generic-x86_64-with-debian-stretch-sid
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7fe76cd42400
- ** ---------- .> transport:   amqp://
- ** ---------- .> results:     redis://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
[tasks]
  . tasks.mytask
```

**tasks.py**:

``` py
    @celery_app.task(bind=True, ignore_result=False)
    def mytask(task):
        r = redis.StrictRedis()
        r.rpush('/task_finished', task.request.id)
        return {'result': 42}
```

When I try to run the following code, and run 2 task one after the other it works when getting the first result but fails to return the second one.

``` py
    import celery.result
    import redis

    r = redis.StrictRedis()
    celery_app = Celery(name="my_long_task", backend="redis://")

    while True:
        _, resp = r.blpop('/task_finished')
        task_id = resp.decode('utf-8')
        task = celery.result.AsyncResult(task_id, app=celery_app)
        print(task)
        print(task.result)
```

Will return:

_First loop_:  

```
[1] 990e2d04-5664-4d7c-8a5c-e9cb4ef45e24  
[2] {'result': 42}
```

_Second loop_ (fails to return the result):  

```
[3] 8463cc46-0884-4bf7-b838-f0614f74b271  
[4] {}
```

However if I instantiate `celery_app = Celery(name="my_long_task", backend="redis://")` in the `while` loop it will work each time.  
When I get directly the result in redis `r.get('"celery-task-meta-{task_id}")` the result is there.
What is wrong with not reinstantiating `celery_app` ? What am I missing ?

**Edit**:
Waiting a bit for the result (in case of latency) won't work too

``` py
while True:
    _, resp = r.blpop('/task_finished')
    task_id = resp.decode('utf-8')
    for i in range(0, 20):
        # Won't work because I need to re instantiate celery_app
        task = celery.result.AsyncResult(task_id, app=celery_app)
        print(task.result)
        time.sleep(1)
```

**Comment by ask** [comment]
I guess the backend cache could be the cause if you need to reinstantiate the app.

Maybe setting:

```py
app.conf.CELERY_MAX_CACHED_RESULTS = -1
```

will help.

It could also simply be that reinstantating the app adds enough latency that it masks a
race condition in your code.

The redis result backend in Celery 4.0 is no longer polling for results, so using blpop like this is probably
not necessary anymore.

**Comment by auvipy** [comment]
try master and report if it's still the issue
