### ISSUE TITLE
task input parameter with default value receive its value from the same task previously executed

### ISSUE THREAD

**Issue by donguklim** [celery/celery#3485]
For example, let's say I have task like bellow

```python
def task_a(a, b, dict_input={}): 
    dict_input[a] = b
    return dict_input
```
The task has one input parameter that has  empty dictionary as a default value.

Then, I call above task twice with different input parameters

```python
task_a.delay('key3', '3', {'key1':1, 'key2':2})
task_a.delay('key', 'val')
```

dict_input parameter is explicitly assigned in the first call,
and it is implicitly assigned in the second call with default value.

I would expect the return value from the first task to be 
```python
{'key1':1, 'key2':2, 'key3':3}
```
and the second task to be

```python
{'key':'val'}
```

However, the actual return value of the second call is sometimes like bellow.
```python
{'key':'val', 'key1':1, 'key2':2, 'key3':3}
```
as if it has been executed with the same dict_input parameter value as the first call

It seems celery has a bug that if a task's default input parameter is set to an empty dictionary, 
and if there was the same task previously executed with the explicit value of the parameter,
the later task may receive its default value of the parameter from the previously executed task.

The solution to this bug is not using default parameter and call the task with explicit parameter values.
Ex
```python
task_a.delay('key3', '3', {'key1':1, 'key2':2})
task_a.delay('key', 'val', {})
```

To be more precisely, I actually encountered this bug when I called above form of task as a callback function for celery chord.
I used redis and rabbitmq.

**Comment by ask** [comment]
Hey!

This is a common mistake when defining default parameters in Python functions: the signature is not evaluated every time you call the function, the function is instead created with a list as default value.

Try this:

```py

>>> def f(x, defaults=[]):
...    defaults.append('foo')
...    return x + ''.join(defaults)
...
>>> f('hello')
'hellofoo'
>>> f('hello')
'hellofoofoo'
>>> f('hello')
'hellofoofoofoo'
>>> f('hello')
'hellofoofoofoofoo'
>>> f('hello')
'hellofoofoofoofoofoo'
```

What you really want is:

```
def task_a(a, b, dict_input=None):
   dict_input = dict_input if dict_input is not None else {}
    dict_input[a] = b
    return dict_input
```

Search Google for "python mutable default" and you'll see how common this mistake is.  It also hit
me when coming from a language where the signature is evaluated for every call.
