### ISSUE TITLE
3.1.24 upgrade?

### ISSUE THREAD

**Issue by listingmirror** [celery/celery#3489]
Is there anything special I should need to do to upgrade from 3.1.23 to 3.1.24?  Perhaps with the new message format?

I brought entire cluster down, brought it back up... but no tasks would register. Got something to the effect of

```
Traceback (most recent call last):
  File "/webapps/appname/lib/python3.5/site-packages/celery/worker/consumer.py", line 465, in on_task_rec
eived
    strategies[type_](message, body,
KeyError: 'appname.report_in'
ERROR 2016-10-03 00:04:00,030 [consumer] Received unregistered task of type 'appname.sometask'
.
The message has been ignored and discarded.
Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.
The full contents of the message body was:
{'eta': None, 'chord': None, 'errbacks': None, 'timelimit': [None, None], 'task': 'appname.sometask
_work', 'utc': True, 'kwargs': {}, 'id': '8a83c318-d856-499d-93f1-eb038ae9da80', 'taskset': None, 'callbacks': N
one, 'retries': 0, 'expires': None, 'args': []} (271b)
```

**Comment by ask** [comment]
There shouldn't be anything special :/

It only allows you to process messages sent using the new format, it shouldn't have any effect on anything else.

Does the worker show this task name as registered? (part of the startup banner when loglevel is INFO or higher).

**Comment by listingmirror** [comment]
@ask in fact none of my tasks showed up in the banner.  I am trying to look and see how task registry changed in this release.

Almost certainly I am doing task registry "wrong"... so perhaps the right answer is I just learn how to do task registry "right" and then perhaps I can do a PR to better document the process.

My basic problem is I have 100+ tasks. Putting in 1 giant file would be a nogo.  So I have a "tasks" directory where they all live. The way I did registry that works in 3.1.23 that did not work in 3.1.24 is this in my DJango Settings.py

```
CELERY_IMPORTS = ['appname.tasks.' + str(f).split('.')[0] for f in
                  os.listdir(os.path.join(BASE_DIR, 'appname', 'tasks'))
                  if f not in ['__init__.py', 'base_task.py']]


```

**Comment by thedrow** [comment]
This issue has gone stale.
If you still have a problem, please reopen or file a new issue.
