### ISSUE TITLE
No such entity with class_id = 0

### ISSUE THREAD

**Issue by aarondong2005** [celery/celery#3491]
When add new order and a configurable product from existing customer will get this error. 

Magento 2.111 was migrated from 1.9.0.1 about half month ago.

The product will removed after click update items and quantities button.
![untitled-1](https://cloud.githubusercontent.com/assets/15516555/19058546/0521d5f0-898d-11e6-8a54-f7a63df561e5.png)

**Comment by listingmirror** [comment]
@aarondong2005  wrong github perhaps?

**Comment by aarondong2005** [comment]
please delete it. sorry
