### ISSUE TITLE
How to dynamically add or remove tasks to celerybeat?

### ISSUE THREAD

**Issue by amitt001** [celery/celery#3493]
I know we can use djcelery but is there a way to independently(w/o django) do dynamic addition and deletion of tasks?

**Comment by ask** [comment]
Not currently, you have to restart beat.

One way for this to be possible would be if Beat had a process mailbox like the worker remote control commands.

Another way would be to change the  `celerybeat-schedule` shelve database, but I don't think beat currently reads changes from this at runtime, it only reads it at startup and saves it regularly.

**Comment by Windsooon** [comment]
So I still have to restart the beat when I use django-celery-beat to  dynamically add or remove tasks?

**Comment by mapleflow** [comment]
# my env

	ubuntu 14.04
    celery 4.0.2
    django-celery-beat 1.0.1
    django 1.10.6

# how to do

download `django_celery_beat` source code under your project not pip install

    ├── django_celery_beat
       ├── admin.py
       ├── apps.py
       ├── beat.py
       ├── __init__.py
       ├── managers.py
       ├── migrations
       ├── models.py
       ├── schedulers.py
       ├── templates
       └── utils.py

change settings.py

    # project/app/settings.py
    INSTALL_APPS = [
     'django_celery_beat'
    ]
   
rewrite celery.beat.Schduler

	# django_celery_beat/beat.py    
    from celery.beat import Scheduler, ScheduleEntry
   
    class Scheduler(Scheduler):
    	# copy celery.beat.Schduler content changed follow github link
        # https://github.com/celery/celery/pull/3791/files
   
now you can use it happily
	
    # not work
	from celery.beat import Scheduler
    
    # work well
	from django_celery_beat.beat import Scheduler
    
set your celerybeat.sh

	#!/bin/sh
    # use DatabaseSchduler
	celery -A project beat -l debug -S django_celery_beat.schedulers.DatabaseScheduler
    
now you can change/add/delete task dynamic without restart django_celery_beat.

 	good luck for you!

**Comment by alons45** [comment]
Not plans for add this feature in the near future?

**Comment by linjinze999** [comment]
Celery 4.1.0 has solved the problem.

**Comment by ramarivera** [comment]
@linjinze999 Could you please provide some link or more info on how does 4.1.0 solved it?
Thanks!

**Comment by ntcong** [comment]
I believe it was fixed in here https://github.com/celery/celery/pull/3958

With that patch, the beat heap will be populated every time the schedule changes

**Comment by thedrow** [comment]
Yes it was fixed.
