### ISSUE TITLE
Add a settings to not display the shell banner

### ISSUE THREAD

**Issue by ksamuel** [celery/celery#3496]
For tests purpose, I run celery in a thread next to my test code. Because there is no way to suppress the banner printing, my test results are getting difficult to read.

I can't manipulate stdout to suppress this manually because I use a lib that already does this for it's own purpose.

**Comment by ask** [comment]
There are multiple entrypoints to start a worker:
http://docs.celeryproject.org/en/master/internals/guide.html#worker-overview

To me it sounds like you'd want to use WorkController directly, but I also made the worker respect -q when printing the banner.

**Comment by ask** [comment]
Note -q can be passed in as `Worker(quiet=True)`

**Comment by ksamuel** [comment]
Wow, that was quick :)
