### ISSUE TITLE
Removing Redis MULTI/EXEC

### ISSUE THREAD

**Issue by ipapapa** [celery/celery#3500]
[Pipy](https://pypi.python.org/pypi/redis/), which is used for as a client for the Redis backend, has a flag `transaction=False` to disable Redis MULTI/EXEC when creating a pipeline. A [Redis pipeline](http://redis.io/topics/pipelining) is designed to send multiple commands to the server without waiting for the replies at all, and finally read the replies in a single step. 

MULTI/EXEC are [transactional](http://redis.io/topics/transactions) semantics that do not have to be integrated with the Redis pipelines (most Redis clients do not mix pipelines with transactions) and are generally used without pipelines. 

However, this pipelines with transactions mix is causing an issue to the [Dynomite](https://github.com/netflix/dynomite), a proxy layer that can be used to make Redis highly available, users that want to use Celery. I was wondering if transactions were set to be used as an artifact of using the default pipeline implementation from Pipy, and if there would be any issue if we set [transaction=False](https://github.com/ipapapa/celery/commit/162194380b38a5196506ae7059afec94324a2e50).

**Comment by ask** [comment]
It may be possible, but I fear that information may be fragmented across Redis servers if you use a cluster.

Redis result backend

- Store result: SETEX, PUBLISH
- Query chord: RPUSH, LLEN, GET, EXPIRE (pipeline operating on two keys)
- Join chord: LRANGE, DELETE, DELETE (two keys)

Redis transport

- Mutex: WATCH, GET, MULTI, DELETE, UNWATCH
- Ack emulation append: ZADD, HSET (on two keys)
- Ack emulation remove: ZREM, HDEL (on two keys)
- Ack emulation restore: Mutex + ZREVRANGEBYSCORE

I'm guessing the most of these are fine as long as the proxy uses consistent hashing on the keys.

The big problem is probably the mutex.

**Comment by ipapapa** [comment]
[Dynomite](https://github.com/netflix/dynomite) has the notion of coordinator node (similar to Cassandra) if the client is not token aware. The coordinator node performs a consistent hashing to make sure the same keys would always go to the correct nodes. So that would not be a problem.

Nonetheless, the single-threaded nature of Dynomite has limitations on supporting Redis [PUB/SUB](https://github.com/Netflix/dynomite/blob/dev/notes/redis.md). Unfortunately, Celery is using those two Redis APIs. Hence, Dynomite can move forward with the use of Celery once [multi-threaded project](https://github.com/Netflix/dynomite/projects) is completed.

**Comment by schleppy** [comment]
Sorry to resurrect this old ticket, but will a the Redis broker implementation support Dynomite now?  If the answer is already known that would help me avoid comparing the list of unsupported Redis commands with the broker code.

**Comment by ipapapa** [comment]
I am not sure how further ahead we can get. MULTI/EXEC and PUB/SUB are the only two major [non supported Redis APIs](https://github.com/Netflix/dynomite/blob/dev/notes/redis.md). I had put together a [small commit](https://github.com/ipapapa/celery/commit/162194380b38a5196506ae7059afec94324a2e50) to disable transactions but there is PUB/SUB used. Hence, it requires somebody motivated to do the work.

**Comment by auvipy** [comment]
If anyone interested to work on that please open a new issue describing the to-do's
