### ISSUE TITLE
Abrupt end of worker process with Redis as a broker loses scheduled tasks.

### ISSUE THREAD

**Issue by tipu** [celery/celery#3501]
I'd like to preface this by saying this behavior is potentially documented here with unsupported TTL on Redis (I say potentially because I am not 100% sure what the functionality of TTL actually is):
https://github.com/celery/kombu#transport-comparison

I'll be referencing two different worker definitions,

```
from celery import Celery
app = Celery(broker='redis://localhost:6379/0')

@app.task
def add(x, y): return x + y

if __name__ == '__main__':
    app.worker_main()
```

and

```
from celery import Celery
app = Celery(broker='amqp://guest:guest@localhost:5672//')

@app.task
def add(x, y): return x + y

if __name__ == '__main__':
    app.worker_main()
```

Both were tested using the steps described below in debug mode.

I enqueue this task:
`app.send_task('run.add', [2, 2], countdown=60)` and get an `AsyncResult` as expected. The workers in both situations output something similar to:

`[2016-10-07 13:25:58,080: INFO/MainProcess] Received task: run.add[fa0549ee-8a2e-4bd4-9d54-d58357de0092] eta:[2016-10-07 20:26:58.073791+00:00]`

After this, I force kill the worker with `pkill -9 celery`, abruptly ending the worker. This is where the behavior deviates.

The `amqp` worker, when started up again after the force kill, receives the scheduled task that was assigned to its predecessor. The `redis` worker, however, does not receive the scheduled task that its predecessor had received, resulting in a complete loss of the task. Is this a bug or expected behavior using Redis as a broker?

**Comment by Schweigi** [comment]
You may want to take a look at (if you use Celery v4): http://docs.celeryproject.org/en/master/userguide/configuration.html#task-reject-on-worker-lost

Nevertheless we still encounter some lost tasks with the Redis broker even when using the visibility timeout & setting the reject flag to true.

**Comment by tipu** [comment]
@Schweigi thanks for the link, we decided to roll with RabbitMQ instead.
