### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ensure'

### ISSUE THREAD

**Issue by mehdigmira** [celery/celery#3504]
Hey I already posted this on Kombu. But I don't know if it the problem is actually in Kombu or celery, so i'm posting it here as well:

We're currently running celery on 4 servers:
-2 with this config: celery==3.1.24 et kombu==3.0.37
-2 with this config: celery==3.1.17 et kombu==3.0.35
The code running is the same.

On the celery 3.1.24 servers we've being experiencing this error:

> AttributeError: 'NoneType' object has no attribute 'ensure'

The Traceback is:

> Traceback (most recent call last):
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/backends/redis.py", line 227, in _new_chord_return
> callback.delay([unpack(tup, decode) for tup in resl])
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/canvas.py", line 175, in delay
> return self.apply_async(partial_args, partial_kwargs)
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/canvas.py", line 251, in apply_async
> return _apply(args, kwargs, _options)
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
> *dict(self._get_exec_options(), *options)
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/our_library/settings/celery/utils.py", line 63, in send_task
> return super(CustomCelery, self).send_task(name, *args, *kwargs)
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
> reply_to=reply_to or self.oid, *options
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
> *kwargs
> File "/home/w/.virtualenvs/x/local/lib/python2.7/site-packages/kombu/messaging.py", line 169, in publish
> publish = self.connection.ensure(self, publish, *_retry_policy)
> AttributeError: 'NoneType' object has no attribute 'ensure'

'
Do you know what could be causing this ?

**Comment by mehdigmira** [comment]
Ok, I think this a bug in celery 3.1.24.
If I create a group contains two chords, It produces this error.

A test case:

```
# tasks.py

from celery import Celery

app = Celery('tasks', backend='redis://localhost', broker='amqp://guest@localhost//')

@app.task()
def add(x, y):
    return x + y

@app.task()
def tsum(numbers):
    return sum(numbers)
```

```
# run.py

from celery import chord
from celery import group

from tasks import add, tsum


c = chord(group(add.subtask((i, i)) for i in xrange(5)), (tsum.subtask()))
d = chord(group(add.subtask((i, i)) for i in xrange(3)), (tsum.subtask()))
e = group(c, d)
print e().get()  # raises error
```

**Comment by sintezcs** [comment]
@ask When will an updated pip package be released with this fix included?

**Comment by sintezcs** [comment]
@ask, could you please publish 3.1.25 release at least on github. We will really appreciate this.

**Comment by NotSqrt** [comment]
The package seems to have been published.

**Comment by auvipy** [comment]
seems to be fixed on master
