### ISSUE TITLE
Nested group-chain-group structure never succeeds

### ISSUE THREAD

**Issue by sintezcs** [celery/celery#3506]
Issue #2573 described by @traut is fully reproducible on 3.1.24. I used the original [test scripts](https://gist.github.com/traut/fcf5d76e07dd3ed6e54d) from #2573 and got exactly the same results - task 7 is never fired.
### Celery report

```
software -> celery:3.1.24 (Cipater) kombu:3.0.37 py:3.5.1
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:32776/1

CELERYD_LOG_FORMAT: '%(message)s'
BROKER_URL: 'amqp://guest:********@localhost:32780//'
CELERY_RESULT_BACKEND: 'redis://localhost:32776/1'
CELERY_TRACK_STARTED: True
```

**Comment by sintezcs** [comment]
3.1.24 introduced some updates to canvas, so I've tested it on 3.1.23 also. The issue is also fully reproducible.

**Comment by sintezcs** [comment]
This issue is a real blocker for us. Any updates on it? 
Thank you.

**Comment by ask** [comment]
We're not focusing on backporting these fixes to 3.1 at the moment.

The canvas in 4.0 have been refactored and so many bugs have been fixed, we're focusing all efforts
on getting this release out.

**Comment by sintezcs** [comment]
@ask Unfortunately, the issue is fully reproducible on 4.0.0.rc5
```
software -> celery:4.0.0rc5 (0today8) kombu:4.0.0rc5 py:3.5.1
            billiard:3.5.0.1 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:32774/1

CELERY_TRACK_STARTED: True
BROKER_URL: 'redis://localhost:32774/1'
CELERY_RESULT_BACKEND: 'redis://localhost:32774/1'
CELERYD_LOG_FORMAT: '%(message)s'
```

**Comment by thedrow** [comment]
@sintezcs Can you try again with master? I think I merged a fix for it.

**Comment by auvipy** [comment]
this should be fixed on master. report if still exist in latest releases.
