### ISSUE TITLE
group link does not executed

### ISSUE THREAD

**Issue by last-partizan** [celery/celery#3508]
Here is tasks:
```
@celery.task
def test_task():
    print "test_task running"
    group(test_subtask.s(p) for p in range(2)).apply_async(link=test_link.s())
    #test_subtask.apply_async(args=(5,), link=test_link.s())
    return "task-ok"

@celery.task
def test_subtask(v):
    print "test_subtask running", v
    return "subtask-ok"

@celery.task
def test_link(*args):
    print "test_link running", args
    return "link-ok"

test_task.apply_async() 
```

Expected result: test_link running after all test_subtask completed
Current result: test_links does not called.

![s1](https://cloud.githubusercontent.com/assets/301015/19268957/45b9b0c2-8fc0-11e6-84af-dd84c8bee0f3.png)

**Comment by last-partizan** [comment]
Celery version: v3.1.24
transport/result backends: redis

**Comment by ask** [comment]
You cannot link tasks to a group, as that means it needs synchronization.

You can use `chain`, which will automatically upgrade `group | callback` to a chord:

```py
 (group(test_subtask.s(p) for p in range(2)) | test_link.s()).delay()
```

The above is the same as:

```py
chord(group(test_subtask.s(p) for p in range(2)))(test_link.s()).delay()
```

**Comment by last-partizan** [comment]
Nice, thanks.

Btw, maybe celery must throw exception when using unsupported options like this?

**Comment by rca** [comment]
I believe the trailing `.delay()` in the `chord()` example above is a typo and should read:

```
chord(group(test_subtask.s(p) for p in range(2)))(test_link.s())
```

When trying this in my code, I get an error about AsyncResult not having a delay() method.

Aside from that, this works great, thanks.

**Comment by sainthk** [comment]
(group(test_subtask.s(p) for p in range(2)) | test_link.s()).delay()

It makes following errors;
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/builtins.py", line 76, in unlock_chord
    raise self.retry(countdown=interval, max_retries=max_retries)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 726, in retry
    raise ret
celery.exceptions.Retry: Retry in 1s


My goal is calling a callback function after a group of task is finished. 
But I don't want to wait for whole process is finished.
Is it possible to keep running a problem after calling that group line?
