### ISSUE TITLE
[master] Allow specifying an SQS queue to use

### ISSUE THREAD

**Issue by astronouth7303** [celery/celery#3510]
Due to a variety of configuration options required for using SQS queues in production (namely, permissions and redrive policies), it would be really nice if it was possible to specify the SQS queue that celery uses.

**Comment by ask** [comment]
That should be possible using the existing queue configuration options, as documented here:
http://docs.celeryproject.org/en/master/userguide/routing.html#changing-the-name-of-the-default-queue

**Comment by astronouth7303** [comment]
To make sure I'm reading that right, I would set the `task_default_queue` (`CELERY_TASK_DEFAULT_QUEUE` in Django) setting to the name of my SQS queue (not the URL or ARN)?

**Comment by astronouth7303** [comment]
Yup, just have to make sure you don't have a name prefix set.

**Comment by melvinkcx** [comment]
This deserves a section in the SQS documentation. It took me a while to found this issue.

**Comment by auvipy** [comment]
feel free to come with a PR
