### ISSUE TITLE
Schedule CELERY_TIMEZONE cannot work

### ISSUE THREAD

**Issue by XGiton** [celery/celery#3511]
Hi, all
I get a problem when using Celery CELERY_TIMEZONE configuration. For describing clearly, I push a test project on Github [https://github.com/XGiton/celery-test](https://github.com/XGiton/celery-test).

`celery_config.py` is configuration file and there are two CeleryConfig in it: DefaultCeleryConfig and SchedulerCeleryConfig.
SchedulerCeleryConfig configures sending two due tasks every minute. And when SchedulerCeleryConfig.CELERY_IMPORTS configures as follow, Scheduler works well and send due tasks every minute:

``` python
CELERY_IMPORTS = (
        # 'scheduler_and_default_task',  # if comment this line, schedule works well
        'scheduler_task'
    )
```

But if configures as this:

```
CELERY_IMPORTS = (
        'scheduler_and_default_task',  # if comment this line, schedule works well
        'scheduler_task'
    )
```

It will not send any due tasks longer.

Does anyone occur this problem?

_SchedulerCelery starting commands:_

``` shell
celery -A scheduler_celery beat
```

**Comment by ask** [comment]
Are there no errors when you do this?

What happens when you do `celery -A proj shell` with this bad IMPORTS line active?

**Comment by ask** [comment]
It sends the tasks for me no matter if I comment the line or not.   Did you start beat with `-l debug`? That will show you when the tasks are sent.  I'd also recommend removing the `celerybeat-schedule` file when things are not working.

**Comment by XGiton** [comment]
@ask 
Did it send tasks correctly in `Asia/Shanghai` timezone, 8 hours delta from `UTC` timezone?

**Comment by thedrow** [comment]
@XGiton I'm closing this issue assuming it's either solved or stale. Feel free to comment if that's not the case.
