### ISSUE TITLE
Group timeout on non-Default Queue Return Result

### ISSUE THREAD

**Issue by kevinguard** [celery/celery#3512]
My server was earlier setup to have only one (default) queue and a group waiting for a set of subtasks returning their results, and it was working like a charm. Recently I moved to multi-queue + multi-host environment and now I have problem with getting results from my subtasks. All subtasks begin, execute, and complete successfully but the group never receives the results and simply times out. I'm using REDIS as backend and like I said despite complicated system the server used to work very nice. I know it might be hard to guess what might be the root cause but I wonder if I need to consider something specific about groups when used in multi-host environment? Thanks!

**Comment by auvipy** [comment]
post this type of question to irc or mailing list.
