### ISSUE TITLE
Mongodb instances keep increasing and do not close on task complete

### ISSUE THREAD

**Issue by azhard4int** [celery/celery#3517]
Hi,

I am encountering a problem that is similar to https://github.com/celery/celery/issues/1494 which is done in Pymongo. The mongodb instance does not shut down when running through celery?

I am using Mongoengine for the database connection and data insertion, the program works fine for few hours after that the connection keeps spiking to above 1000 and does not close at all.

Any help would be appreciated.

Thanks

**Comment by DuncanBetts** [comment]
What versions are you running? E.g. if your components are celery, eventlet, pymongo, rabbitmq, mongodb, python.

Have you tried the solution given in that thread, if you are running an unpatched version?

**Comment by auvipy** [comment]
please report again with more detail if the bug still in master
