### ISSUE TITLE
ImportError: No module named 'kombu.transport.django

### ISSUE THREAD

**Issue by holinhot** [celery/celery#3518]
[root@apivc2 django]# python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd5aff7e1e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'kombu.transport' has no attribute 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(__exception)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/**init**.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'kombu.transport.django'

[root@apivc2 django-celery]# pip^C
[root@apivc2 django-celery]# python setup.py install
running install
running bdist_egg
running egg_info
writing dependency_links to django_celery.egg-info/dependency_links.txt
writing django_celery.egg-info/PKG-INFO
writing requirements to django_celery.egg-info/requires.txt
writing top-level names to django_celery.egg-info/top_level.txt
reading manifest file 'django_celery.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'TODO'
warning: no files found matching '_' under directory 'bin'
no previously-included directories found matching 'bin/_.pyc'
no previously-included directories found matching 'tests/_.pyc'
no previously-included directories found matching 'docs/_.pyc'
no previously-included directories found matching 'extra/_.pyc'
no previously-included directories found matching 'djcelery/_.pyc'
no previously-included directories found matching 'docs/.build'
no previously-included directories found matching 'examples/*.pyc'
writing manifest file 'django_celery.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/monproj
copying build/lib/djcelery/monproj/urls.py -> build/bdist.linux-x86_64/egg/djcelery/monproj
copying build/lib/djcelery/monproj/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/monproj
copying build/lib/djcelery/mon.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/views.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/db.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/models.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/urls.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/managers.py -> build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/management
copying build/lib/djcelery/management/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/management
copying build/lib/djcelery/management/base.py -> build/bdist.linux-x86_64/egg/djcelery/management
creating build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celeryd.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celerymon.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celery.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/djcelerymon.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celeryd_detach.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celerybeat.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celeryd_multi.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
copying build/lib/djcelery/management/commands/celerycam.py -> build/bdist.linux-x86_64/egg/djcelery/management/commands
creating build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_commands.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_discovery.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_loaders.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/utils.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/_compat.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/req.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_worker_job.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/__init__.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_snapshot.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_views.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_models.py -> build/bdist.linux-x86_64/egg/djcelery/tests
copying build/lib/djcelery/tests/test_schedulers.py -> build/bdist.linux-x86_64/egg/djcelery/tests
creating build/bdist.linux-x86_64/egg/djcelery/tests/test_backends
copying build/lib/djcelery/tests/test_backends/test_cache.py -> build/bdist.linux-x86_64/egg/djcelery/tests/test_backends
copying build/lib/djcelery/tests/test_backends/test_database.py -> build/bdist.linux-x86_64/egg/djcelery/tests/test_backends
copying build/lib/djcelery/tests/test_backends/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/tests/test_backends
creating build/bdist.linux-x86_64/egg/djcelery/transport
copying build/lib/djcelery/transport/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/transport
copying build/lib/djcelery/loaders.py -> build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/contrib
copying build/lib/djcelery/contrib/test_runner.py -> build/bdist.linux-x86_64/egg/djcelery/contrib
copying build/lib/djcelery/contrib/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/contrib
copying build/lib/djcelery/common.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/utils.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/picklefield.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/schedulers.py -> build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/static
creating build/bdist.linux-x86_64/egg/djcelery/static/djcelery
copying build/lib/djcelery/static/djcelery/style.css -> build/bdist.linux-x86_64/egg/djcelery/static/djcelery
copying build/lib/djcelery/snapshot.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/**init**.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/admin_utils.py -> build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/templates
creating build/bdist.linux-x86_64/egg/djcelery/templates/admin
creating build/bdist.linux-x86_64/egg/djcelery/templates/admin/djcelery
copying build/lib/djcelery/templates/admin/djcelery/change_list.html -> build/bdist.linux-x86_64/egg/djcelery/templates/admin/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/templates/djcelery
copying build/lib/djcelery/templates/djcelery/confirm_rate_limit.html -> build/bdist.linux-x86_64/egg/djcelery/templates/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/migrations
copying build/lib/djcelery/migrations/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/migrations
copying build/lib/djcelery/migrations/0001_initial.py -> build/bdist.linux-x86_64/egg/djcelery/migrations
copying build/lib/djcelery/compat.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/app.py -> build/bdist.linux-x86_64/egg/djcelery
creating build/bdist.linux-x86_64/egg/djcelery/backends
copying build/lib/djcelery/backends/database.py -> build/bdist.linux-x86_64/egg/djcelery/backends
copying build/lib/djcelery/backends/cache.py -> build/bdist.linux-x86_64/egg/djcelery/backends
copying build/lib/djcelery/backends/**init**.py -> build/bdist.linux-x86_64/egg/djcelery/backends
copying build/lib/djcelery/humanize.py -> build/bdist.linux-x86_64/egg/djcelery
copying build/lib/djcelery/admin.py -> build/bdist.linux-x86_64/egg/djcelery
byte-compiling build/bdist.linux-x86_64/egg/djcelery/monproj/urls.py to urls.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/monproj/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/mon.py to mon.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/views.py to views.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/db.py to db.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/models.py to models.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/urls.py to urls.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/managers.py to managers.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/base.py to base.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celeryd.py to celeryd.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celerymon.py to celerymon.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celery.py to celery.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/djcelerymon.py to djcelerymon.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celeryd_detach.py to celeryd_detach.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celerybeat.py to celerybeat.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celeryd_multi.py to celeryd_multi.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/management/commands/celerycam.py to celerycam.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_commands.py to test_commands.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_discovery.py to test_discovery.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_loaders.py to test_loaders.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/utils.py to utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/_compat.py to _compat.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/req.py to req.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_worker_job.py to test_worker_job.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/__init__.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_snapshot.py to test_snapshot.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_views.py to test_views.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_models.py to test_models.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_schedulers.py to test_schedulers.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_backends/test_cache.py to test_cache.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_backends/test_database.py to test_database.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/tests/test_backends/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/transport/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/loaders.py to loaders.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/contrib/test_runner.py to test_runner.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/contrib/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/common.py to common.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/utils.py to utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/picklefield.py to picklefield.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/schedulers.py to schedulers.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/snapshot.py to snapshot.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/admin_utils.py to admin_utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/migrations/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/migrations/0001_initial.py to 0001_initial.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/compat.py to compat.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/app.py to app.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/backends/database.py to database.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/backends/cache.py to cache.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/backends/**init**.py to **init**.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/humanize.py to humanize.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/djcelery/admin.py to admin.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_celery.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/django_celery-3.2.0a1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing django_celery-3.2.0a1-py3.5.egg
removing '/usr/local/lib/python3.5/site-packages/django_celery-3.2.0a1-py3.5.egg' (and everything under it)
creating /usr/local/lib/python3.5/site-packages/django_celery-3.2.0a1-py3.5.egg
Extracting django_celery-3.2.0a1-py3.5.egg to /usr/local/lib/python3.5/site-packages
django-celery 3.2.0a1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/site-packages/django_celery-3.2.0a1-py3.5.egg
Processing dependencies for django-celery==3.2.0a1
Searching for Django==1.10.2
Best match: Django 1.10.2
Adding Django 1.10.2 to easy-install.pth file
Installing django-admin script to /usr/local/bin

Using /usr/local/lib/python3.5/site-packages
Searching for celery==4.0.0rc5
Best match: celery 4.0.0rc5
Processing celery-4.0.0rc5-py3.5.egg
celery 4.0.0rc5 is already the active version in easy-install.pth
Installing celery script to /usr/local/bin

Using /usr/local/lib/python3.5/site-packages/celery-4.0.0rc5-py3.5.egg
Searching for kombu==4.0.0rc5
Best match: kombu 4.0.0rc5
Processing kombu-4.0.0rc5-py3.5.egg
kombu 4.0.0rc5 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/kombu-4.0.0rc5-py3.5.egg
Searching for billiard==3.5.0.1
Best match: billiard 3.5.0.1
Processing billiard-3.5.0.1-py3.5.egg
billiard 3.5.0.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/billiard-3.5.0.1-py3.5.egg
Searching for pytz==2016.7
Best match: pytz 2016.7
Processing pytz-2016.7-py3.5.egg
pytz 2016.7 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/pytz-2016.7-py3.5.egg
Searching for amqp==2.1.1
Best match: amqp 2.1.1
Processing amqp-2.1.1-py3.5.egg
amqp 2.1.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/amqp-2.1.1-py3.5.egg
Searching for vine==1.1.3
Best match: vine 1.1.3
Processing vine-1.1.3-py3.5.egg
vine 1.1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/vine-1.1.3-py3.5.egg
Finished processing dependencies for django-celery==3.2.0a1
[root@apivc2 django-celery]#

**Comment by holinhot** [comment]
same code it's working fine one mac os python3.5.2+jango-celery==3.2.0a1 but i try run it on centos6 can't working

**Comment by ask** [comment]
There is no Django ORM transport in Kombu 4.

What is your use case for using this transport?  It was never meant for production use, and it has some serious issues.

**Comment by peterdemin** [comment]
Ha! We were using it in production for rare long tasks.

**Comment by peterdemin** [comment]
Also, could you please update documentation in http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-celery-with-django
It says we can still use Django ORM as a broker.

**Comment by auvipy** [comment]
try new releases...
