### ISSUE TITLE
Is the documentation wrong?

### ISSUE THREAD

**Issue by ibigbug** [celery/celery#3523]
## Checklist
- [ ] I have included the output of `celery -A proj report` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
## Steps to reproduce

http://docs.celeryproject.org/en/latest/userguide/signals.html#basics
## Expected behavior

sender can handle string
## Actual behavior

http://docs.celeryproject.org/en/latest/_modules/celery/utils/dispatch/signal.html#Signal

After dive into source code I found that receivers are dispatched with `task` instance as sender , not `task.name`. So if connect using `connect(sender='task.name')`, the receiver would never be called.

The documentation about this is very confusing in my opinion.

**Comment by ask** [comment]
The sender is abstract, so it depends on the signal.

In the after_task_publish case the sender is the task name as a string:

"Sender is the name of the task being sent."

In the task_prerun case the sender is the task instance:

"Sender is the task object being executed."

For other signals, the sender is something else entirely, like in the case of the eventlet_pool_started
signal:

"Sender is the celery.concurrency.eventlet.TaskPool instance."


There may be lacking guidance on what the sender is, I guess it's implied that you already know how 
Django signals work, which is of course bad.

**Comment by ibigbug** [comment]
Thanks for feedback. I can understand the Signal pattern now.

So I think listing which type of sender are the builtin signals expecting could make a big help for fresh celery signal users :)

**Comment by cndaniel** [comment]
awesome
