### ISSUE TITLE
Bug or gotcha in Celery 3.x?

### ISSUE THREAD

**Issue by jonatron** [celery/celery#3524]
Not sure if this is a bug or gotcha, but even some explanation would be appreciated.

## Steps to reproduce

Celery 3.1.24

- Create bare django project using "First steps with Django" guide, set
`CELERY_DEFAULT_QUEUE = 'default'`
- Run `celery -A proj -Q celery,default worker -l info`
- Observe in rabbitmq management that 'celery' queue has routing key 'celery' binding.
'default' queue has routing key 'celery' binding.
- Run `./manage.py shell`
```
>>> from proj.celery import debug_task
>>> debug_task.delay()
```
- See that task has run twice.
- Stop worker, run task again, observe task is in both default and celery queue.

## Expected behavior

- Task runs once

## Actual behavior

- Task runs twice

On Celery master (4.0.0rc6), 'default' queue has 'default' routing key.

**Comment by ask** [comment]
In 3.x or earlier you have to change the actual queue definition:
http://docs.celeryproject.org/en/latest/userguide/routing.html#changing-the-name-of-the-default-queue

There are several settings that make up how the default queue is defined:

1. CELERY_DEFAULT_QUEUE (name of the queue)
2. CELERY_DEFAULT_EXCHANGE (name of exchange default queue is bound to)
3. CELERY_DEFAULT_ROUTING_KEY (routing key default queue is bound to).

CELERY_QUEUES is then populated based on these settings:

```py
CELERY_QUEUES = Queue(
    name=CELERY_DEFAULT_QUEUE,
    exchange=Exchange(CELERY_DEFAULT_EXCHANGE, CELERY_DEFAULT_EXCHANGE_TYPE),
    routing_key=CELERY_DEFAULT_ROUTING_KEY,
)

Since CELERY_DEFAULT_EXCHANGE is set to "celery" and CELERY_DEFAULT_ROUTING_KEY is set to celery, what you will end up by *just setting CELERY_DEFAULT_QUEUE* is: 

```py

CELERY_QUEUES = Queue('default', exchange=Exchange('celery'), routing_key='celery')

```

Since you already defined the "celery" queue earlier to be bound to celery/celery, you now have
two queues bound to the same exchange routing_key pair:

* celery (exchange=celery, routing_key=celery)
* default (exchange=celery, routing_key=celery)

And messages will be delivered to both of them.

In Celery 4.0 you only have to set the CELERY_DEFAULT_QUEUE, as both CELERY_DEFAULT_EXCHANGE and CELERY_DEFAULT_ROUTING_KEY takes the default value from that setting:

http://docs.celeryproject.org/en/master/userguide/routing.html#changing-the-name-of-the-default-queue

**Comment by jonatron** [comment]
Thanks @ask , very much appreciate the clarification.
