### ISSUE TITLE
`fixture 'celery_app' not found` when running py.test

### ISSUE THREAD

**Issue by sklarsa** [celery/celery#3530]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1. `py.test`

## Expected behavior
1. Tests should run

## Actual behavior
1. No tests are running and output is as follows: `1 failed, 120 skipped, 2108 error in 5.02 seconds`

Sample Error Output:
```
___________________________________________________________________ ERROR at setup of test_WorkController.test_Pool_create ___________________________________________________________________
file /Users/steven/source/github/celery/t/unit/worker/test_worker.py, line 1050
      def test_Pool_create(self):
file /Users/steven/source/github/celery/t/unit/conftest.py, line 71
  @pytest.fixture(autouse=True)
  def reset_cache_backend_state(celery_app):
E       fixture 'celery_app' not found
>       available fixtures: AAA_disable_multiprocessing, AAA_reset_CELERY_LOADER_env, app, cache, capfd, capsys, celery_config, doctest_namespace, monkeypatch, patching, pytestconfig, record_threads_at_startup, record_xml_property, recwarn, reset_cache_backend_state, sanity_logging_side_effects, sanity_no_shutdown_flags_set, sanity_stdouts, stdouts, task_join_will_not_block, test_cases_shortcuts, threads_not_lingering, tmpdir, tmpdir_factory, use_celery_app_trap
>       use 'pytest --fixtures [testpath]' for help on them.
```
I'd be happy to answer any more questions about my configuration, but I followed the instructions in CONTRIBUTING.rst and can't figure out what I'm doing wrong.  

`pip list` output:
```
amqp (2.1.1)
billiard (3.5.0.1)
case (1.5.2)
funcsigs (1.0.2)
kombu (4.0.0)
linecache2 (1.0.0)
mock (2.0.0)
nose (1.3.7)
pbr (1.10.0)
pip (8.1.2)
py (1.4.31)
pytest (3.0.3)
pytz (2016.7)
setuptools (28.7.1)
six (1.10.0)
traceback2 (1.4.0)
unittest2 (1.1.0)
vine (1.1.3)
wheel (0.30.0a0)
```

**Comment by ask** [comment]
Are you running the Celery test suite?

`celery` is a py.test plugin now, but I'm guessing you need to do `setup.py develop` for that to register.
