### ISSUE TITLE
tasks that follow a chord are run (prematurely) multiple times

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3536]
#3534 and #3535 might be just symptoms of the the this bug.

I have a not very complex canvas that has a final task, after a chord. This task seems to be executed once for each the tasks in the chord head, _before_ the chord body. It is executed again after the chord body, as it should (except if `rpc://` is used as result_backend; that might be another bug).

## Steps to reproduce

I wrote the canvas three times using different syntax (using chord; chain and group; group and | ), but the result is consistent.

```python
from __future__ import absolute_import, division, print_function
from celery import Celery, group, chain, chord
import time

app = Celery('simple_canvas')
app.config_from_object({
    # 'broker_url': 'redis://',
    # 'result_backend': 'redis',
    'broker_url': 'amqp://',
    'result_backend': 'redis://localhost',
    # 'result_backend': 'amqp',
    # 'result_backend': 'rpc://',
    'task_always_eager': False,
})


@app.task(bind=True)
def echo(self, name):
    print(name)
    return name


if __name__ == '__main__':

    mytasks_implicit = chain([
        echo.si('-> implicit chord'),
        group([
            echo.si('1'),
            echo.si('2'),
        ]),
        echo.si('_'),
        echo.si('.'),
    ])

    mytasks_explicit = chain([
        echo.si('-> explicit chord'),
        chord([
            echo.si('1'),
            echo.si('2'),
        ], body=echo.si('_')),
        echo.si('.'),
    ])

    mytasks_or_operator = chain([
        echo.si('-> or operator'),
        group([
            echo.si('1'),
            echo.si('2'),
        ]) | echo.si('_'),
        echo.si('.'),
    ])

    result = mytasks_implicit.apply_async()
    print(result.get())
    time.sleep(1.5)

    result = mytasks_explicit.apply_async()
    print(result.get())
    time.sleep(1.5)

    result = mytasks_or_operator.apply_async()
    print(result.get())
    time.sleep(1.5)
```
### celery report:
```
software -> celery:4.0.0rc7 (0today8) kombu:4.0.0 py:2.7.10
            billiard:3.5.0.1 py-amqp:2.1.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost/

task_always_eager: False
broker_url: u'amqp://guest:********@localhost:5672//'
result_backend: u'redis://localhost/'
```

## Expected behavior
`1` and `2` tasks are the chord head; `_` is the chord body; `.` is the final task, that should be run only once, at the end:

```
-> implicit chord
1
2
_
.
-> explicit chord
1
2
_
.
-> or operator
1
2
_
.
```

## Actual behavior
```
-> implicit chord
1
2
.
.
_
.
-> explicit chord
1
2
.
.
_
.
-> or operator
2
1
.
.
_
.
```

**Comment by ask** [comment]
Woha, that's interesting.

Really need to clean up the implementation of ``Signature.__or__``, it's just super crazy.  Maybe this should all be delayed until the workflow is actually sent, and it shouldn't try to optimize all this stuff up front.  Anyway, don't have enough time to rewrite that for 4.0.

The Operator version should actually be:

```py
  mytasks_or_operator = (
        echo.si('-> or operator') |
        group([
            echo.si('1'),
            echo.si('2'),
        ]) | echo.si('_') | echo.si('.')
    )
```

And this version does work:

```
-> or operator
1
2
_
.
```

So the bug seems to be that instead of adding the last task in the chain to the chord body, it actually adds it to every task in the group somehow.

**Comment by ask** [comment]
Seems this was all due to some isinstance checks that no longer works now that there are two chain classes (_chain and chain).

Should really rethink how this __or__ stuff works, but for now at least it fixed the issue :/
