### ISSUE TITLE
link_error not called on SIGKILL

### ISSUE THREAD

**Issue by DeoLeung** [celery/celery#3537]
## Checklist

- [x] version == 3.1.24
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
celery worker xxxx -c 2
run a long task with link_error=a_signature
kill the child process by 'kill -9'

## Expected behavior
some way the link_error signature is called

## Actual behavior
link_error is not called

The problem is I need the link/link_error to notify that I run the .get() method to get the result, or know that it fails, without continuously polling to check it finishes/fails.

Is there a way that I can use a async version of .get() (and it works with the SIGKILL and asyncio)?
or make link_error works when encounters SIGKILL?

many thanks

**Comment by georgepsarakis** [comment]
@DeoLeung not sure what you mean here, but Linux processes can handle the SIGTERM signal but never SIGKILL. When SIGKILL is received, the process is immediately shutdown by the OS.

**Comment by DeoLeung** [comment]
@georgepsarakis yes I agree we can't do anything if it's SIGKILL

the original thinking was:
1. I have an asyncio loop running, using `tornado`
2. I `apply_async` a celery task
3. I need to get the result back, but celery `AsyncRetult.get` is a blocking sync function
4. at the moment I use `after_run` to publish a message to redis to notify it's time to run `AsyncResult.get()`

if there is an `async_get` function I can use together with asyncio `await`, that will be greate, though seems irrelevant to this issue now

**Comment by georgepsarakis** [comment]
Have you looked at Canvas and more specifically on [Chains](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chains)?

I think it is close to what you want.

**Comment by deterb** [comment]
I've had to deal with this as well.  Celery 3.1.25 has the same issue, and I have worked around by scheduling a follow on task after the task is expected to have finished with the task id as a parameter.  You can check on the task status then or retry if needed.  For getting the result you can just call `result.result`

This no longer appears to be an issue in Celery 4.1.0, though there may be a difference in the error callback being used (there are two variants, one just taking the task id and the other taking 3 arguments; I know the three argument one works as an error callback; which one is called depends on the number of arguments in the callback).

**Comment by thedrow** [comment]
Can we close this issue then?
