### ISSUE TITLE
subtask argument order compared to typical partial function application

### ISSUE THREAD

**Issue by jonathanstrong** [celery/celery#3545]
For a task:

```python
@app.task
def double_identity(x, y):
    return x, y
```

Partially applying this with `double_identity.s(1)` is the equivalent of `curry(flip(double_identity))(1)` in functional pseudo-code. In other words, why is the second argument "prepended" when the function is called with both arguments? 

```python
>>> double_identity(1, 2)
(1, 2)
>>> double_identity.s(1)(2)
(2, 1)
```
This goes against every implementation of currying I've seen. Normally `f(x, y)` curried with one argument returns a function that takes `y` and applies `f` with `x` from the partial application and `y` from the new call. 

I found this to be a fairly annoying part of the API because it requires moving function arguments so that the variable argument is on the inside, where it won't be as useful in other applications. 

How I normally use currying/partial application, for example with `toolz.curry`

```python
from toolz import curry

@curry
def f(stable, variable):
    # whatever....
    return True 

results = map(f(1), range(10))
```

Clearly, at this point, you can't go changing this and breaking everyone's code. However, I did want to inquire about the feasibility of a possible solution. 

Would it be a) easy, b) hard, or c) impossible to allow the use of a special placeholder object to subtask that lets the user control the argument order? I'm not familiar with celery's internals at all - where would one start on something like that? 

Something like: 

```python
from celery.utils.functional import _ # make believe

f = double_identity.s(1, _)(2) # -> (1, 2)
```

Thanks for any insights you can provide. As a new user I was quite pleased to see the embrace of functional concepts throughout the code, so I figured this fairly esoteric concern might find some interest here.

**Comment by ask** [comment]
It's definitely confusing, I agree with that :)

I figured that it would be easier to reason about if the first argument of the task would always
be the return value of the previous task.  It was a conscious decision but I'm still not certain if it was the right call.

I'm not against changing it actually, maybe we could get a few real-world examples together that can demonstrate how it makes more sense to use the normal order.

**Comment by jonathanstrong** [comment]
The place where the current pattern becomes confusing is if you partially apply more than once. 

For example

```
from toolz import curry

@curry
def f(a, b, c):
    return a / b / c

f(1)(2)(3) == f(1, 2, 3)

f(1, 2)(3) == f(1, 2, 3)
```

The current celery rule means that 

```
f(1)(2)(3) == f(3, 2, 1)

f(1, 2)(3) == f(3, 1, 2)
```

(Although it's not possible to do more than one partial application that as far as I know with subtasks.)

This usage arises when you want to pass along a partially applied function along several times to get new arguments at each step. It would be particularly useful in the distributed environment of celery tasks, in my opinion.

**Comment by auvipy** [comment]
@jonathanstrong do you have any suggested solution for the issue? plz feel free to start a pr if anything on you mind which could be improved
