### ISSUE TITLE
Celery 3.1.25 not available on PyPI to follow docs instructions

### ISSUE THREAD

**Issue by jdotjdot** [celery/celery#3546]
The Celery 4.0.0 [docs](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#step-1-upgrade-to-celery-3-1-25) say that we should upgrade to 3.1.25 first, but 3.1.25 doesn't seem to be available on PyPI:

![image](https://cloud.githubusercontent.com/assets/1328961/20026675/9c1d8c7c-a2d5-11e6-86b9-1b5eaad3d835.png)

**Comment by ask** [comment]
Thanks!

Seems PyPI lost the files, as the .asc file made it, but the rest was missing :/

It should be working now!
