### ISSUE TITLE
class-based Task doesn't work at 4.0.0?

### ISSUE THREAD

**Issue by rightx2** [celery/celery#3548]
http://stackoverflow.com/questions/40436815/django-celery-class-based-task-doesnt-work.

I used `celery` in `Django(1.10)`.

However, class-based Task doesn't work at 4.0.0 but works at 3.1.25.

I spent almost 6 hours to find it out.

**Comment by andyregan** [comment]
This appears to be explained in the [release notes](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#the-task-base-class-no-longer-automatically-register-tasks).
