### ISSUE TITLE
Group results are not being sorted in 4.0

### ISSUE THREAD

**Issue by rsalmei** [celery/celery#3549]
Hello Ask,

Congrats on the 4!

I have migrated and now I'm having this problem, should be simple to fix I think.

Well, I have a workflow triggering some group tasks, and it seems that the sorting is broken, it is not deterministic anymore.
In this example I have some info and some account, both are integers, but account is either 1 or 2.
Sometimes I get:
[2016-11-05 15:20:36,550: WARNING/PoolWorker-8] [210, 2]
And other:
[2016-11-05 15:20:36,611: WARNING/PoolWorker-11] [1, 208]

This comes from a fairly advanced use of canvas workflow, don't know if it is related, but probably not, since it occurs in the inner most level.
Anyway, it is a task that runs several parallel workflows, with parallel subsections and a chain in a chord, and then it aggregates these workflows in another group with another chord.
Something like:
```
@app.task
def trigger_something(payload):
    def sub_workflow(data):
        workflow = chord(group(find_info.s(data),
                               find_account.s(data)),
                         chain(update_models_if_available.s(data),
                               create_models.s(data)))
        return workflow

    master_workflow = chord(group(sub_workflow(data) for data in payload),
                           notify_something_results.s())
    return master_workflow.delay()
```

The problem occurs in the task `update_models_if_available`, which is the first in a chain, inside the body of a chord, *which receives the group results*.

Thank you!

**Comment by rsalmei** [comment]
@ask Please, could you see this bug? I think that maybe I over explained, but it should not be hard to look into... It's just a group, that should always send its results sorted, and it is not doing that. Sometimes I get results in the expected order, the same of the workflow, and sometimes this fails, breaking subsequent tasks.

**Comment by auvipy** [comment]
This may be specific too backend. could you verify it on current master?

**Comment by auvipy** [comment]
plz report again if you face the same issue with newer releases.
