### ISSUE TITLE
where is `celery.contrib.methods.task_method` of 4.0 ????

### ISSUE THREAD

**Issue by RyanKung** [celery/celery#3558]
Or how to wrap a `class method` to `task` on version 4.0

**Comment by ask** [comment]
You mean to say you never noticed that it was horribly broken? :)

I wrote `celery.contrib.task_methods` as an experiment, but turns out there were some serious bugs
there, for example task retries wouldn't work at all, and since nobody were stepping up to fix it I removed it.

The new version does add some new fields to the message protocol though, notably `meth` where
the idea was you can have both a class and a method:

```
class Foo:

    def x(self):
        ...

    def y(self):
       ...
```

and both x and y could be tasks.

It's not used for anything yet, but you could probably make it work without much effort.

**Comment by murdav** [comment]
@ask when you wrote:
> the idea was you can have both a class and a method:
> and both x and y could be tasks.

Please could you point me in the correct direction?
What does it mean both x and y could be tasks if the buggy contrib.method has been removed.

I would need a Class based approach, basically I have 20ish class methods that depending on the parameters  passed in the `def __init__(self, param1, param2, param3=None, *) ` dynamically the Class can select which workflow-methods has to run.

Some code based on [here](https://blog.balthazar-rouberol.com/celery-best-practices) and [here](http://stackoverflow.com/questions/35128946/class-based-task-in-django-celery):

```
# proj.base.views.py
class BaseTask(Task):
    """
    """
    def on_success(self, retval, task_id, args, kwargs):
        """
        """
        self.backend.store_result(task_id, {'retval': retval,
                                            'hostname': self.request.hostname},
                                  states.SUCCESS,
                                  request=self.request)

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        """
        Parameters:
          exc     – The exception raised by the task.
          task_id – Unique id of the failed task.
          args    – Original arguments for the task that failed.
          kwargs  – Original keyword arguments for the task that failed.
          einfo   – ExceptionInfo instance, containing the traceback.
        """
        self.backend.store_result(task_id,
                                  exc,
                                  states.FAILURE,
                                  # for failed tasks, hostname is hidden in traceback...
                                  # since celery only accept Exception object as result
                                  traceback={'traceback': einfo.traceback, 'hostname': self.request.hostname},
                                  request=self.request)


#
from celery.decorators import task
from proj.base.views import BaseTask


@task(name="MyParserTask")
class MyParserTask(BaseTask):
    """
    """
    def __init__(self, id_user, id_molecular_type, update=False):
        """
        """
        self._id_user = id_user
        self._user = get_object_or_404(User, pk=self._id_user)
        self._id_ows_type = id_mol_type
        self._update = update

    def _load_ext_lib_obj():

    def _update_user_files():

    def _molecular_update():

    def _molecular_create():        

    def run(self):
        """
        """
        self._load_ext_lib_obj()

        if self._update:
            self._molecular_update()
            self._update_user_files()
        else:
            self._molecular_create()
	#

# in the Django REST viewset
    try:

        worker = MyParserTask(id_user=request.user.pk,
                               id_molecular_type=id_molecular_type,
                               update=False)

        job_id = worker.delay()

    except Exception as e:
        raise e  # raise Django or Django REST framework exceptions

    return Response({"job_url": reverse('api:default:jobs', args=[job_id])},
                    status=status.HTTP_202_ACCEPTED)


# Django REST framework view
class JobsApiView(APIView):
    """
    """

    def get(self, request, uuid=None):
        """
        """
        job = AsyncResult(uuid)

        if job is None:
            return Response(_('Not found.'), status=status.HTTP_404_NOT_FOUND)

        traceback = _('Only admin can check the traceback.')
        if request.user.is_superuser:
            traceback = job.traceback

        if isinstance(job.result, Exception):
            return Response({
                'status': job.status,
                'error': str(job.result),
                'traceback': traceback,
            }, status=status.HTTP_412_PRECONDITION_FAILED)

        # http://docs.celeryproject.org/en/latest/reference/celery.states.html
        if job.status == 'PROGRESS':
            if 'process_percent' in job.result:
                process_percent = job.result['process_percent']
            else:
                process_percent = 0

            return Response({'state': job.status,
                             'process_percent': process_percent},
                            status=status.HTTP_202_ACCEPTED)

        elif job.status == 'SUCCESS':
            return Response({
                'status': job.status,
                'msg': job.result,
            }, status=status.HTTP_200_OK)

        elif job.status == 'PENDING':
            return Response(_('Not found.'), status=status.HTTP_404_NOT_FOUND)

        elif job.status == 'REVOKED':
            return Response(_('Job revoked.'), status=status.HTTP_412_PRECONDITION_FAILED)

        else:
            return Response(job.result.args[0], status=status.HTTP_400_BAD_REQUEST)


```



but [here](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#the-task-base-class-no-longer-automatically-register-tasks) and [here (old)](https://github.com/celery/celery/issues/292) it seems the Class approach is not advisable.
Or aain the correct point could be to pass the parameters in the `run` like specified https://github.com/celery/celery/issues/3492.

Thanks in advance for any clarification.

D

**Comment by jdotjdot** [comment]
I also need this back&mdash;or some other way around it to fix it.

I read through the entire [changelog](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html) and didn't see this there, so I'm _really_ glad I saw this issue.

**Comment by jdotjdot** [comment]
Just kidding, found it deep in the changelog [here](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#unscheduled-removals).

**Comment by jdotjdot** [comment]
I ended up just copy-pasting the code into our app to reuse it, since it's always worked fine for us.  You can find the commit removing the code at 4f43276c236bbef7239a49b93815f478aec1d9f6 if you'd like do the same.

**Comment by scnerd** [comment]
Wouldn't a pretty simple work-around for the time being be:

```
class A:
    @task
    def method(self, *args, **kwargs):
        return "Hello, world!"

A.task.delay(my_a, *my_args, **my_kwargs)
```
? In particular, I have some methods in my Django models that I'd like to be able to fire-and-forget using Celery, and this seems like a way where the methods could both be defined within the model, and be usable as a Celery task.
