### ISSUE TITLE
Celery + SQLAlchemy with RabbitMQ broker hosted on compose.io resulting in (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by sahilkataria** [celery/celery#3561]
We are using celery to send some emails in the background. The celery task connects to the database to lookup some order related information and basically sends the email through mandrill. Our app stack is as follows:
```
- flask (0.10.1)
- SQLAlchemy (1.0.15)
- PostgreSQL 9.4.9
- Celery (3.1.23)
- RabbitMQ broker hosted on compose.io (3.6.5) - SSL enabled
```

Here are the celery config parameters we're using:
```python
CELERY_ACKS_LATE=True
BROKER_USE_SSL = True
CELERYD_MAX_TASKS_PER_CHILD=20
```

Here's how we create the SQL engine, session and the task:
```python 
db_engine = create_engine(
        'postgresql+psycopg2://{0}:{1}@{2}:{3}/{4}'
        .format(sql_username, sql_password, db_ip, db_port, db_name)
    )
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False))
db_session.bind = db_engine
Base.metadata.bind = db_engine

class DBTask(Task):
  _session = None

  def after_return(self, *args, **kwargs):
    if self._session is not None:
      db_session.remove()
      self._session = None

  def on_failure(self, *args, **kwargs):
    if self._session is not None:
      db_session.remove()
      self._session = None

  @property
  def session(self):
    if self._session is None:
      self._session = db_session

    return self._session

# the task sits in another file - only listed here as reference
@celery.task(base=DBTask, bind=True, default_retry_delay=15 * 60, max_retries=4, ignore_result=True)
def some_email_task(self, order_id, other_args):
   ...
```

And here's the output for ``celery -A proj report``
```
software -> celery:3.1.23 (Cipater) kombu:3.0.37 py:3.4.3
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
CELERY_ACKS_LATE: True
RMQ_PASSWORD: '********'
RMQ_PORT: '1234'
APP_ENV: 'DEV'
CELERYD_MAX_TASKS_PER_CHILD: 20
BROKER_URL: 'amqp://some_user:********@gcp-us-east1-cpu.0.dblayer.com:1234/some_app_name'
CELERY_ACCEPT_CONTENT: ['pickle', 'json']
RMQ_HOSTNAME: 'gcp-us-east1-cpu.0.dblayer.com'
RMQ_NAME: 'some_app_name'
BROKER_USE_SSL: True
RMQ_USERNAME: 'some_user' 
```

## The Issue
The celery workers start fine initially and seem to process tasks normally. But after they have been left to run for a few days, the workers seem to be going into an apparent stale connection state with the following error:

> (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

The error is non-recoverable and also results in the following subsequent error:

> exception: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back

The workers need to be restarted to return them to a normal state. I came across a similar issue on your github (#1564) and was wondering if that might be what's wrong here? Does anyone have an idea if a "register_after_fork" would help resolve this issue here? Any help is greatly appreciated.

**Comment by ask** [comment]
Thanks for the thorough description!

Could you try adding this to close the session after fork?

```py
from celery.signals import worker_process_init

@worker_process_init.connect
def on_fork_close_session(**kwargs):
    if db_session is not None:
        db_session._after_fork()
````

**Comment by sahilkataria** [comment]
Thanks for a prompt reply and for appreciating the writing effort :)

So "db_session" is an instance of "scoped_session" in this case. I couldn't find an "_after_fork()" method defined for it. Are you referring to "_after_fork()" method of "SessionManager" by any chance (https://github.com/celery/celery/blob/c122150887ae3633ff0164a5670d23bd093354e4/celery/backends/database/session.py#L30)? 

Should I be using "SessionManager" to create my session?

**Comment by ask** [comment]
I'm not entirely sure what the difference between Session and SessionManager is, so I couldn't tell you which to use.  Maybe there's a .close() method or similar that lets you clean up the state of the session?

**Comment by ask** [comment]
Oh, right, that's our SessionManager, sorry.  Disregard that then, but should try to find a .close method or similar on the session to call.

**Comment by sahilkataria** [comment]
So from my understanding of SQLAlchemy and also as suggested by this post (http://stackoverflow.com/questions/21738944/how-to-close-a-sqlalchemy-session), doing a ```session.close()``` will give the connection back to the connection pool while doing an ```engine.dispose()``` will close all the connections of the connection pool. So what would you recommend between the following two approaches:

1.
```
from celery.signals import worker_process_init

@worker_process_init.connect
def on_fork_close_session(**kwargs):
    if db_session is not None:
        db_session.close()
        db_engine.dispose()
```

2.
```
from multiprocessing.util import register_after_fork

register_after_fork(db_engine, db_engine.dispose)
```

I have a good feeling they both achieve the same thing. But just wanted to check if you might have a preference of one v/s the other? Also, do you recommend using connection pooling for SQLAlchemy or should I just use ```poolclass=NullPool```?

**Comment by sahilkataria** [comment]
@ask any final word on this?

**Comment by chrzrdx** [comment]
Hi Sahil, 

What solution did you finally go with?

I'm in a similar pickle as well. I'm using a db.session.execute() call (db is a SQLAlchemy instance) and I get the same error.

**Comment by auvipy** [comment]
could you guys verify if this still exist in master?

**Comment by sahilkataria** [comment]
@chrzrdx I used approach #2 above that seems to have solved it for us.
