### ISSUE TITLE
[Suggestion] Move Celery channel to Slack

### ISSUE THREAD

**Issue by cemremengu** [celery/celery#3562]
Many open-source projects and groups already use slack. Will be great to see Celery there. It's provides better functionality then IRC.

**Comment by dejlek** [comment]
I disagree - IRC is perfectly fine.

**Comment by cemremengu** [comment]
@dejlek I am not very familiar with IRC but AFAIK when I ask something I have to leave my details to be reached later on right ? There is no `@` funtionality which is a deal breaker at least for me.

**Comment by dejlek** [comment]
I see no problem (apart from perhaps splitting the community) in having both.

**Comment by Cediddi** [comment]
Slack supports irc and xmpp as a gateway, so you can see old messages, get mentions and notifications and still use it from IRC clients (though you can't see old messages in irc afaik).

**Comment by joshfriend** [comment]
> you can't see old messages in irc afaik

correct. slack IRC gateway is "experimental" and does not offer a bouncer.

**Comment by ask** [comment]
I'm not a huge fan of Slack, but I use it for work and have noticed that a lot of young developers use it, and it definitely makes sense to reach as many people as possible.

Is there any way to mirror between them?  I may need some help here, anyone has experience setting up Slack like this?

**Comment by jas32096** [comment]
https://sameroom.io

**Comment by thedrow** [comment]
We do have a Gitter channel which no one seems to use.
Gitter has IRC integration.
I'm not sure how to get people move there though.

**Comment by nukepuppy** [comment]
you should use slack asap :) sorry... move with the times is all i can say.

every open source tool is doing it for a reason.. its not just a fad.. slack is infinitely better than irc

**Comment by xirdneh** [comment]
There are also a lot of open source projects on Freenode.
If anything maybe people should use Gitter too.
IRC and Gitter are more open than Slack and IRC does not lock you into a specific client.

I do see the benefits of Slack to work within a group but not necessarily for an open source project.
There are also logs fo the #celery channel in IRC so you can leave your question there and see if anybody responded afterwards.
