### ISSUE TITLE
Windows - Access Denied Error - Django 1.10 and AWS SQS

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [celery/celery#3570]
Hello fellow developers,

Here you will find the report of my app : [report.txt](https://github.com/celery/celery/files/580739/report.txt)

I have a pretty nasty issue, I am 100% unable to make Celery works with SQS and Django on Windows.
I have tried to run it as Administrator and "normal user". It doesn't change anything.

##  Execution

When I launch the launch command : 
```
celery -A application worker -E -l info --concurrency=1
```

I have noticed a "localhost" in the url pointing to AWS, is it normal ??? I am not relying on a localhost but on AWS SQS.

![image](https://cloud.githubusercontent.com/assets/10923599/20139156/f97139f2-a684-11e6-971b-80e9a3ad0588.png)

## My Configuration

settings.py
```
BROKER_TRANSPORT = 'sqs'
BROKER_TRANSPORT_OPTIONS = {
	'region': 'eu-west-1',
	'visibility_timeout': 3600,# in seconds
	'polling_interval': 10,
	'queue_name_prefix':'celery-feedcrunch-prod-',
	'CELERY_SEND_TASK_ERROR_EMAILS': True
}

BROKER_USER = assign_env_value('AWS_USER')
BROKER_PASSWORD = assign_env_value('AWS_SECRET_KEY')

CELERY_DEFAULT_QUEUE = 'FeedCrunch'
CELERY_QUEUES = {
    CELERY_DEFAULT_QUEUE: {
        'exchange': CELERY_DEFAULT_QUEUE,
        'binding_key': CELERY_DEFAULT_QUEUE,
    }
}
```

I have verified that the User and Password values are correct with a print ;) No Problem about this.

I also have tried to change the BROKER_URL to : 
```
BROKER_URL = 'sqs://{0}:{1}@'.format(
	urllib2.quote(BROKER_USER, safe=''),
	urllib2.quote(BROKER_PASSWORD, safe='')
)
``` 

It doesn't change anything.

**Do not hesitate to tell me if I can help anyhow**

Thanks my friends

Jonathan

**Comment by malinoff** [comment]
Sorry, windows is not officially supported by celery v4. Please, try to run your worker on a linux box and open another issue if the problem persists!
