### ISSUE TITLE
chord fails when there's only one task

### ISSUE THREAD

**Issue by chripede** [celery/celery#3574]
Because of this commit https://github.com/celery/celery/commit/867a3aabef607d17af4a59a85e6ed2c40850cee5 a chord is changed if it's in the form of `chord([A], B)`
However the task_id is always set, even if it's None. That causes the code here https://github.com/celery/celery/blob/v4.0.0/celery/canvas.py#L268 to skip task id generation, and the task will ultimately fail with `ValueError: AsyncResult requires valid id, not <type 'NoneType'>`

**Comment by calvinwyoung** [comment]
FWIW, there's another discussion about this here: #3597

**Comment by alukach** [comment]
These all seem to be the same: #3317 #3709 #3597
