### ISSUE TITLE
Error in header isn't traceable by id

### ISSUE THREAD

**Issue by ersenkavak** [celery/celery#3581]
Hi,
In my workflow I create such code and check if it's finished or failed by looking at their statusses.
`chain(chord([a, b, c], d), e,  f)`
When I start this chain I traverse in the dependency chain to get id's and save to a list,
`[f-id, e-id, chord-id]`
and then I check their states with result.AsyncResult.

My algorithm is pretty simple. If first element in id list is succeed I proceed to do something, if it's failed I raise the exception and if it's pending, I check other ID's for any failed ones and if I can find one, I also raise the exception I found. If all are pending I take that as "queue is full and tasks are waiting" and try the id's few minutes later.

My problem is, If any of a, b or c tasks fail, I can never find it out just by having ids. There's no way to find out if a task in header failed just by chord's id (which is callback's id and it'll never be called because header is failed)

I'm using Celery 4.0 and redis as my broker and backend.

**Comment by ask** [comment]
The result of the chord callback will change to the FAILURE state if any of the tasks in the header fails.

I'm not sure what chord-id here is, maybe you could post example code?

**Comment by auvipy** [comment]
verify and report again if the issue still exist on master
