### ISSUE TITLE
Handling error emails going forward?

### ISSUE THREAD

**Issue by jdotjdot** [celery/celery#3588]
The changelog says that [all email-related functionality has been removed](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#features-removed-for-simplicity). We made heavy use of the error emails feature in Celery.  

Since this is removed, what is now the recommended way to handle errors in Celery tasks?

If we were to reimplement the error email sender internally, where would be the right place to hook that? 

Thanks!

**Comment by fuhrysteve** [comment]
@jdotjdot take a look at https://sentry.io

**Comment by jdotjdot** [comment]
I currently use Opbeat but I want to actually send them from Celery--also
without using an external service. Is there no hook to do this?

**Comment by fuhrysteve** [comment]
You can implement your own base task like this to handle errors however you would like:

http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-inheritance
http://docs.celeryproject.org/en/latest/userguide/tasks.html#on_failure

**Comment by jdotjdot** [comment]
Thanks.  And `on_failure` will properly handle tasks even if they're hard-killed with `SIGKILL`?  That was always my concern about `on_failure`.  For (bad) architectural reasons, we end up with tasks `SIGKILL`-ed a lot, and that's when I need to handle this the most.

**Comment by fuhrysteve** [comment]
No, when `SIGKILL` is delivered the kernel does not allow any activity by the process.

Try using `SIGTERM` instead of `SIGKILL` if you are able. This will enable a warm shutdown.

The process manager `supervisor`, for instance, uses `SIGTERM` as the default kill signal sent by `supervisorctl stop $JOB`. It then it waits for a configurable amount of time (specified by config value `stopwaitsecs`) before sending the process `SIGKILL`, if it is still alive.

I'd suggest mimicking that pattern if you are able.

- send `SIGTERM`
- wait _n_ seconds
- if process is still alive, send `SIGKILL` or `SIGQUIT`

http://celery.readthedocs.io/en/latest/userguide/workers.html#process-signals

**Comment by jdotjdot** [comment]
I am aware of that this--unfortunately I have no control over what signals are sent or when, our celery workers currently are on Heroku and Heroku follows [this shutdown process](https://devcenter.heroku.com/articles/dynos#shutdown) when dynos restart for any reason.

I was always shocked that when celery tasks were shut down by `SIGKILL` that I still got an error email since I would have imagined the `SIGKILL` would have prevented it, yet I did receive them.

Example:
![image](https://cloud.githubusercontent.com/assets/1328961/20247953/d0cb9ecc-a9a7-11e6-9e42-cf87942fae80.png)

Because there appears to be [no clean way in tasks to listen for `SIGTERM`](http://stackoverflow.com/questions/29872998/capture-heroku-sigterm-in-celery-workers-to-shutdown-worker-gracefully), we've come to rely on these error emails to deal with prematurely shut down tasks.

If `on_failure` will not do this, are you saying we have no options?

**Comment by jdotjdot** [comment]
The best I've got since I know RabbitMQ well is to make all task idempotent and use the new [`reject_on_worker_lost`](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.reject_on_worker_lost) (which, by the way, I'm really excited about), but it doesn't feel like the best solution to me, and also not all tasks can be idempotent--and some will require cleanup on kill anyway.

**Comment by fuhrysteve** [comment]
Interesting, I'm surprised you got the error email after `SIGKILL` was received.

That being the case, I'd suspect that `on_failure` is your best bet. If that doesn't work, you'll have to dig around and see where mail_admins was being called

**Comment by jdotjdot** [comment]
Is it possible that I'm actually wrong, and that what is happening is that the celery worker is receiving the `SIGTERM` and forcibly shutting down the child processes (resulting in the email being sent)--and this is all happening _before_ `SIGKILL`?

**Comment by ask** [comment]
All errors in Celery are logged, so make sure you set sentry or other monitoring tools to listen for all types of Celery error logs, not just in the on_failure signal.

It used to be necessary to configure special support for Celery in Sentry, this was done to register
the variables in the stack frame, but this should not be needed for Celery 4.

**Comment by jdotjdot** [comment]
Thanks.  We use Django, so I could simply configure the celery logger to use `mail_admins` and send to Sentry?  What is the logger named?
