### ISSUE TITLE
Problem with more than 65535 scheduled tasks

### ISSUE THREAD

**Issue by defcube** [celery/celery#359]
I am running celery 2.2.4 with kombu, amqplib, and rabbitmq. We 
schedule a lot of tasks to run in 24 hours, and the queue grows above 
65k sometimes. It seems celery implements this by incrementing the 
prefetch count, but py-amqplib gives a ValueError when we try to use a 
prefetch_count above 65535. 

If you look at http://code.google.com/p/py-amqplib/source/browse/amqplib/client_0_8/... 
you will see it is using write_short for the prefetch count, and the 
max size for a short is 65535. 

I made a post to celery-users about it here: http://groups.google.com/group/celery-users/browse_thread/thread/f10fa4c0858289f6

**Comment by nachopro** [comment]
Hi! What can I do to solve this? Thanks

**Comment by ask** [comment]
- Start more workers to divide the load between them
- Use a dedicated queue for ETA tasks and have dedicated worker instances consume from that queue. 
    set `--prefetch-multiplier=0` to disable the limit on those workers.
- Write an ETA scheduler using redis sorted sets.

**Comment by ask** [comment]
Those are all separate options btw :)
