### ISSUE TITLE
Chain within group does not get passed arg

### ISSUE THREAD

**Issue by The-Fonz** [celery/celery#3590]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.1+
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

accept_content: {'pickle'}
task_serializer: 'pickle'
broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://localhost:6379/0'
result_serializer: 'pickle'
```

## Steps to reproduce
Take any task, e.g.:

```
@app.task()
def printargs(*args, **kwargs):
    logger.info(args)
    logger.info(kwargs)
    return args
```

Then run a chain within a group:
`group((printargs.s(n='ca') | group(printargs.s(n='cga'),printargs.s(n='cgb'))),printargs.s(n='f')).delay('there')`

And observe that tasks 'ca', 'cga', and 'cgb' do not get passed the 'there' argument, only task 'f' does. This happens for amqp or redis, with json or pickle serialization.

## Expected behavior
The chain receives the argument given to the group just like any other task in the group.

## Actual behavior
The nested chain does not get passed the argument given to the group.

**Comment by p-col** [comment]
I confirm that I have this problem as well.

**Comment by The-Fonz** [comment]
I fixed it by wrapping the chain within the group in a task:

```
def chainfix(arg, ch):
    """
    Celery does not pass args to a chain within a group. This task creates a
    chain and passes the argument to it.
    """
    if not arg: raise Warning("No arg")
    if not ch: raise Warning("No chain")
    return ch.delay(arg, max_retries=1000, interval=10)
```

You would use it as a partial as such: `chainfix.s( chain_to_fix )`, the argument gets appended to the front of the list, which makes it the first argument and the chain the second.

Still, this is very basic behavior that should just work.

**Comment by p-col** [comment]
Thank you for the trick it does the job.
However I think that it's not advised to delay() inside a task.

I just want to add that this workflow worked in 3.1.23 and doesn't work anymore.

**Comment by tothegump** [comment]
This can not been reproduce on current master.
Maybe already fixed?

**Comment by auvipy** [comment]
then we should close this!
