### ISSUE TITLE
Can Celery 4.0.0 workers handle _both_ protocol versions simultaneously?

### ISSUE THREAD

**Issue by jdotjdot** [celery/celery#3593]
Hi,

We have a number of queued celery tasks that (advisably or not) have very long `countdown`s of multiple weeks.  We're trying to upgrade, but obviously the old tasks are protocol v1, and due to our setup, we must upgrade Celery at the same time on both the worker servers and the app server--we can't run 3.1.25 on just the workers.

If we run Celery 4.0.0 on the worker server, will the workers automatically be able to handle tasks both of protocol v1 and of protocol v2?  Or do we have to configure all of Celery to only use one version of the protocol?

**Comment by ask** [comment]
Yes!  A 4.0 worker can handle both protocol 1 and 2, and it can also send messages in both formats.

Since 3.1.24, the 3.1 version can also handle incoming messages in protocol 2 format.
