### ISSUE TITLE
Celery chain - detect on success of all tasks and on failure of individual tasks

### ISSUE THREAD

**Issue by dsafaric** [celery/celery#3612]
More of a question then an issue. Since I'm quite new to Celery, I've been wondering - can Celery execute an on success function while all chained tasks have been executed successfully? And in contrary, execute a function upon failure of an individual task? 

For example:

```
task = chain(
  makedirs.si(path=build_args['root_build_dir']),
  popen.si(args=build_args['git_clone']),
  popen.si(args=build_args['configure_xcodeproj']),
  popen.si(args=build_args['archive']),
  popen.si(args=build_args['generate_ipa']),
)

task.apply_async()

```
if all tasks in a chain would completed successfully, I would like to update record state in the database describing when the chain finished executing? In addition, this may also include sending status updates through web sockets and alike - just to illustrate the purpose. 

Thanks in advance.

**Comment by Rooon** [comment]
I'm also new to Celery, but would it be possible with a [chord](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chords)?
If any of the tasks raise an exception, the chord result shows a "ChordError" with details of the task that failed.
It would also make sense as a finalizer task if you send a status result.

**Comment by ask** [comment]
You should be able to use .on_error for any signature:

http://docs.celeryproject.org/en/latest/userguide/canvas.html#error-handling

An on_success callback, is simply adding another step to the chain :)

**Comment by dsafaric** [comment]
Well, interestedly enough I've tried by implementing the on_success callback initially but the problem was that the on_success task finished executing prior other tasks have returns which I found quite ought and unexpected. 

Hence the question at the first place

**Comment by ask** [comment]
You mean you did:

```py
task = chain(
  makedirs.si(path=build_args['root_build_dir']),
  popen.si(args=build_args['git_clone']),
  popen.si(args=build_args['configure_xcodeproj']),
  popen.si(args=build_args['archive']),
  popen.si(args=build_args['generate_ipa']),
  on_success_task.si()
)
```

and it executed out of order?
