### ISSUE TITLE
running 5000 celery workers in AWS EC2

### ISSUE THREAD

**Issue by pymonger** [celery/celery#3617]
Hello,

I'm running my celery workers in AWS spot market using an AutoScaling group. I'm trying to reach 5000 EC2 instances where each instance runs a single celery worker. All is well until we scale up to about 4300 instances. At that point, the new instances that come up fail to connect to RabbitMQ with the following error:
```
[2016-11-22 17:20:40,144: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@172.31.0.173:5672//: timed out.
Trying again in 32.00 seconds...
```

This may be more of a question on how to scale up RabbitMQ but if you have any insights or suggestions it would be great.

My settings are:
```
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.5
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://127.0.0.1/

CELERY_ACCEPT_CONTENT: ['msgpack']
BROKER_HEARTBEAT: 300
CELERY_TRACK_STARTED: True
CELERY_TIMEZONE: 'US/Pacific-New'
CELERY_SEND_TASK_SENT_EVENT: True
BROKER_URL: 'amqp://guest:********@172.31.0.173:5672//'
CELERY_ENABLE_UTC: True
CELERY_RESULT_BACKEND: 'redis://127.0.0.1/'
CELERY_TASK_SERIALIZER: 'msgpack'
USER_RULES_DATASET_INDEX: 'user_rules'
CELERY_SEND_TASK_ERROR_EMAILS: False
CELERY_ACKS_LATE: True
CELERY_QUEUE_MAX_PRIORITY: 10
CELERY_SEND_EVENTS: True
CELERY_TASK_RESULT_EXPIRES: 86400
CELERY_IMPORTS: ['proj.job_worker']
CELERY_EVENT_SERIALIZER: 'msgpack'
CELERYD_PREFETCH_MULTIPLIER: 1
CELERY_RESULT_SERIALIZER: 'msgpack'
BROKER_HEARTBEAT_CHECKRATE: 5
```

Each worker runs in supervisord with the following command:
```
celery worker --app=proj --concurrency=1 --loglevel=INFO -Q job_worker-small -n job_worker-small -O fair --without-mingle --without-gossip --heartbeat-interval=60
```

The RabbitMQ server (v3.6.2) has an increase ulimit:
```
ulimit -n 102400
```

And the configuration is:
```
[
  { rabbit,
    [
      { loopback_users, [] },
      { heartbeat, 300 },
      { vm_memory_high_watermark, 100 },
      { tcp_listen_options, [ binary,
                              { packet, raw },
                              { reuseaddr, true },
                              { backlog, 4096 },
                              { nodelay, true },
                              { exit_on_close, false },
                              { keepalive, true }
                           ]
      }
    ]
  }
].
```

Thanks,

Gerald

**Comment by alekibango** [comment]
hi, it would make sense to add more info about rabbitmq.
for example at least output of 
`rabbitmqctl status`
or even whole 
`rabbitmqctl report`.

Did you check rabbitmq logs? 

Your value for vm_memory_watermark is mostl likely wrong. 
Should that really say 100GB ? Is your rabbit server having at least 200GB RAM?
Having watermark over .50 (50%) is risky. 
Read  https://www.rabbitmq.com/memory.html

How much memory you have/use on rabbit?
How many network connections do you have there?  
```LC_ALL=C netstat   |grep ESTABLISHED |wc -l ```

**Comment by listingmirror** [comment]
What hardware is the broker?

Turning off broker heartbeat helped me a bunch for a similar problem. I can keep up with 300-400 single worker instances per CPU on my rabbitMQ box. So I would expect to be able to handle your load with 12 CPUs or so.

 It did seem like each of my auto scale instances made 2 connections to the broker (one for actual worker, one for parent process maybe???) If there was a way to reduce that to 1 it seems like it would help scaling... Not totally sure on the Celery architecture around this...

Curious what you find out, as I will need 5k to 10k connections eventually. Maybe at that scale it's easier to use SQS or similar...

**Comment by pymonger** [comment]
Hi @alekibango,

Status shows:
```
[{pid,4635},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.2"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.2"},
      {webmachine,"webmachine","1.10.3"},
      {mochiweb,"MochiMedia Web Server","2.13.1"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.2"},
      {rabbit,"RabbitMQ","3.6.2"},
      {os_mon,"CPO  CXC 138 46","2.2.14"},
      {ssl,"Erlang/OTP SSL application","5.3.3"},
      {public_key,"Public key infrastructure","0.21"},
      {crypto,"CRYPTO version 2","3.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.2"},
      {rabbit_common,[],"3.6.2"},
      {inets,"INETS  CXC 138 49","5.9.8"},
      {mnesia,"MNESIA  CXC 138 12","4.11"},
      {compiler,"ERTS  CXC 138 10","4.9.4"},
      {xmerl,"XML parser","1.3.6"},
      {syntax_tools,"Syntax tools","1.6.13"},
      {asn1,"The Erlang ASN1 compiler version 2.0.4","2.0.4"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
      {sasl,"SASL  CXC 138 11","2.3.4"},
      {stdlib,"ERTS  CXC 138 10","1.19.4"},
      {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:32:32] [async-threads:512] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{total,1182268776},
      {connection_readers,6627704},
      {connection_writers,1613312},
      {connection_channels,5493440},
      {connection_other,8366536},
      {queue_procs,11085992},
      {queue_slave_procs,0},
      {plugins,6960808},
      {other_proc,16457456},
      {mnesia,364720},
      {mgmt_db,613118912},
      {msg_index,6758040},
      {other_ets,40813760},
      {binary,412205024},
      {code,27045279},
      {atom,992409},
      {other_system,24365384}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,100},
 {vm_memory_limit,25150731059},
 {disk_free_limit,50000000},
 {disk_free,88590442496},
 {file_descriptors,
     [{total_limit,102300},
      {total_used,275},
      {sockets_limit,92068},
      {sockets_used,264}]},
 {processes,[{limit,1048576},{used,3942}]},
 {run_queue,0},
 {uptime,1977902},
 {kernel,{net_ticktime,60}}]
```

I'm not sure why the value of vm_memory_high_watermark is at 100 but at some point in the past a little trial and error using real workloads led to this value. I'll try lowering it back down to .5.

The instance running rabbitmq has 60GB of memory and the number of connections show 270 however I ran the command now without any of the 4300+ instances running. 

In the rabbitmq logs during the 4300+ instance run there are 30 log entries with:
```
=ERROR REPORT==== 8-Nov-2016::23:21:50 ===
closing AMQP connection <0.18429.83> (172.31.15.69:40240 -> 172.31.0.173:5672):
{inet_error,etimedout}
```

and 12158 log entries with:
```
=WARNING REPORT==== 8-Nov-2016::23:21:59 ===
closing AMQP connection <0.96.85> (172.31.1.190:51714 -> 172.31.0.173:5672):
client unexpectedly closed TCP connection
```

There were 250716 log entries with:
```
=INFO REPORT==== 9-Nov-2016::05:04:49 ===
closing AMQP connection <0.9150.109> (172.31.1.171:39312 -> 172.31.0.173:5672)
```

It sounds like at this scale, it may be better to setup rabbitmq in high availability using AWS AutoScaling and using AWS ELB to load balance the connections. I just wanted to see how far we can get without going that route.

Thanks.

**Comment by listingmirror** [comment]
@pymonger  how many CPUs are you running on the broker for 4300 connections?

Did you try turning off worker heartbeat?

**Comment by pymonger** [comment]
@listingmirror: That instance has 16 vCPUs and 30GB RAM. I did not try with worker heartbeats turned off though. I'll give that a try on our next test run.

**Comment by alekibango** [comment]
@pymonger 
this (part of) rabbitmq config helped me to survive high load in the past.
Try to figure out how to abuse those configuration options, do not just copy.
My problem was different though, i had too many queues.
```
  [
    {mnesia, [{dump_log_write_threshold, 35000},
              {dc_dump_limit, 30}
              
             ]},
    {rabbit, [ {tcp_listeners, [{"::", 5672}]},
               {vm_memory_high_watermark, 0.50},
               {vm_memory_high_watermark_paging_ratio, 0.40},
               {collect_statistics_interval, 30000},
               {heartbeat, 1200}
             ]}
  ].
```

**Comment by auvipy** [comment]
curious to know about the current resolution of the issue

**Comment by alekibango** [comment]
i processed 10e10+ tasks, still works, rabbitmq got a bit more reliable last 2 years.  
Holding my fingers crossed and writing my own custom brokers using python3.6 and asyncio.

What you can try in between is making use of multiple amqp servers, potentialy shoveling tasks from one to another if needed.
