### ISSUE TITLE
setuptools extras are not propagated to kombu

### ISSUE THREAD

**Issue by ticosax** [celery/celery#3619]
example: `pip install celery[sqs]` doesn't install `kombu[sqs]`
thus `pycurl` ends up to be missing.

What would be the best way to solve this ? knowing that we might be interested by several flavors at the same time like `celery[sqs,msgpack]`.

**Comment by ask** [comment]
There's no way to handle this in setuptools AFAIK, so this is the reason why we duplicate this in both celery and kombu.

It seems the requirement in celery, is out of date compared to the one in kombu, so I added the pycurl dependency to celery[sqs].
