### ISSUE TITLE
How to get task name in TaskResult / django-db result backend?

### ISSUE THREAD

**Issue by darklow** [celery/celery#3628]
Is there a way to get task name by TaskResult instance when using `django-db` as `CELERY_RESULT_BACKEND`? Or some way to extend result backend handling and save extra data like task name and queue along with TaskResult result and other info which already exists.

I understand that the point of result backend is to check status of task by ID, however if there is already task `result` and `traceback` for failed tasks, why there isn't such a core thing as task name? 

Thank you.

**Comment by ask** [comment]
I'm sure it's possible to add that information pretty easily, but it would have to be done by modifying the result backend.

**Comment by firlevapz** [comment]
hi, any update on this, I'd love to have this feature too...

**Comment by jobec** [comment]
We made a workaround like this (for Redis...)

``` Python
from datetime import datetime
from tzlocal import get_localzone

# Custom result backend that also stores the task name and date_done
app.loader.override_backends['extendedredis'] = 'my_package.celery:ExtendedRedisBackend'


class ExtendedRedisBackend(RedisBackend):
    def _store_result(self, task_id, result, state,
                      traceback=None, request=None, **kwargs):
        meta = {
            'status': state,
            'result': result,
            'traceback': traceback,
            'children': self.current_task_children(request),
            'task_id': bytes_to_str(task_id),
            'task': bytes_to_str(request.task),
            'date_done': bytes_to_str(datetime.now(get_localzone()).isoformat()),
        }
        self.set(self.get_key_for_task(task_id), self.encode(meta))
        return result

class ExtendedAsyncResult(app.AsyncResult):
    @property
    def task(self):
        return self._get_task_meta().get('task')


result = ExtendedAsyncResult(result_id)
print(result.task)
```

It's trivial actually to add this to the code of Celery itself, at least for the Redis backend. But having it there for all builtin backends is some more work.

**Comment by auvipy** [comment]
any kind of contribution is welcome... @jobec

**Comment by johnarnold** [comment]
Take a look at https://github.com/celery/celery/pull/4490 for my progress with adding additional attributes to other backends -- you could replicate this into the database backend fairly easily.

**Comment by sivang** [comment]
Any update on this, in particular , @johnarnold have the changes got merged and published in PyPi ?

**Comment by johnarnold** [comment]
@sivang I was out on honeymoon so not much progress. i'll rebase the PR and try to get it merged.

**Comment by sivang** [comment]
No worries :) Congrets btw. It's just that I'm using frame.inspect for that and though I madr sure to del the objs after I got the string name a bit scared to live it there as such

**Comment by duck2** [comment]
For anyone using @jobec's workaround, here are the required imports:

```python
from celery.backends.redis import RedisBackend
from datetime import datetime
from kombu.utils.encoding import bytes_to_str
from tzlocal import get_localzone
```

**Comment by auvipy** [comment]
@johnarnold should we close this?

**Comment by iegorval** [comment]
Does this workaround still work eg. for Redis in Celery 5? Is there some full code sample I could refer to?
