### ISSUE TITLE
Feature: Run arbitrary script on workers

### ISSUE THREAD

**Issue by arita37** [celery/celery#3632]
When launching the worker, we need to specify the module where the tasks are located:

 celery worker  -A task_module01  --loglevel=info
 
It means that task_module01 should contain the task in advance.

How about launching tasks remote worker which does not have access to  task_module01 ?
How about passing script code ?

Thanks

**Comment by ask** [comment]
This is definitely possible: you can create a task that evals anything that you send to it.

It's also almost certainly very unsafe unless you have some kind of sandboxing built-into it, but if you can trust the broker (e.g. in a firewall environment) then that can be an acceptable risk.

Evaling a simple script is easy, it's much more complicated if you also want to have dependencies like pip installable packages.

```py

@app.task
def eval(code):
    # type: (str) -> None
    _globals = {}
    _locals = {}
    exec(code, _globals, _locals)

SCRIPT1 = """\
def add(x, y):
    print(x + y)
add(4, 4)
"""
if __name__ = '__main__':
    eval.delay(SCRIPT1)
```

**Comment by ask** [comment]
Btw, this PyPI library contains code that helps you serialize actual Python functions on the wire:
https://pypi.python.org/pypi/cloud

You could extract that part out and integrate it with Celery.

**Comment by arita37** [comment]
Hi,

What if I passed the filepath of the script and script is available from the worker ?

Thanks



On 1 Dec 2016, at 08:36, Ask Solem <notifications@github.com> wrote:

Btw, this PyPI library contains code that helps you serialize actual Python functions on the wire:
https://pypi.python.org/pypi/cloud

You could extract that part out and integrate it with Celery.

―

**Comment by listingmirror** [comment]
If your worker already has the script.. it seems like you are back at the normal celery case.

I have 150 or so different tasks. All sit in a dir called tasks on each server. So any worker can do any task.  I divide my workers to do different tasks, but they all have all the code, so they all can do whatever task I want...

**Comment by auvipy** [comment]
closing for now
