### ISSUE TITLE
why celery work stuck ? 

### ISSUE THREAD

**Issue by lyroge** [celery/celery#3635]
## env

- [ ] celery3.0.11
- [ ] redis as broker

## Steps to reproduce
`for i in range(1000):
    tasks.add.apply_async((3,4), queue='abc')`

## Actual behavior
celery worker stuck , and many task dont finished

**Comment by ask** [comment]
You're using an old version of Celery... Please upgrade to either 4.0, or the latest version in the 3.1 series.
