### ISSUE TITLE
celery v3 docs link from http://docs.celeryproject.org/en/latest/

### ISSUE THREAD

**Issue by Sovetnikov** [celery/celery#3636]
Good day!

Many search results in google about celery leads to official docs http://docs.celeryproject.org/en/latest/.
When v4 is released there is now docs about v4, but i (and i think many other people) still using v3.

Please make a link to v3 docs on main page of http://docs.celeryproject.org/en/latest/ for easy accesibility.

**Comment by joshma** [comment]
Agreed - does anyone know if v3 docs are on the web at all?

**Comment by Sovetnikov** [comment]
Yes, it's accessible, but it's like quest challenge to find it :)
Bottom right corner of http://docs.celeryproject.org/en/latest/
Screenshot https://yadi.sk/i/q4sSrv-LzyNNW

**Comment by ask** [comment]
I guess we could put something in the 'This document describes the current stable version of Celery (4.0). For development docs, go here.' banner on top of every page.

**Comment by Sovetnikov** [comment]
"This document describes the current stable version of Celery (4.0). For development docs, go here." exist, but "go here" link leads to v4 docs....

**Comment by thedrow** [comment]
You can find the documentation for Celery 3.1 in http://docs.celeryproject.org/en/3.1/
