### ISSUE TITLE
ImportError: No module named timeutils

### ISSUE THREAD

**Issue by TBWISK** [celery/celery#3637]
## Checklist

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.10
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:djcelery.backends.database:DatabaseBackend

BROKER_TRANSPORT_OPTIONS: {
    'max_connections': 10000}
SECURE_SSL_REDIRECT: False
SECURE_HSTS_SECONDS: 0
CSRF_COOKIE_SECURE: False
CELERY_DEFAULT_QUEUE: 'wxmonitor'
LANGUAGE_CODE: 'zh-hans'
ROOT_URLCONF: 'weixin.urls'
LOGIN_URL: '/accounts/login/'
BROKER_URL: u'redis://127.0.0.1:6379/1'
BASE_DIR: '/Users/youyou/codingspace/django-work/wechat-article-monitor'
TEST_NON_SERIALIZED_APPS: []
DEFAULT_CHARSET: 'UTF-8'
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT: None
CELERYBEAT_SCHEDULER: 'djcelery.schedulers.DatabaseScheduler'
QINIU_BUCKET_NAME: 'wechat-article-monitor'
ALLOWED_HOSTS: ['*']
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX: '[Django] '
FILE_UPLOAD_PERMISSIONS: None
REDIS_PORT: 6379
STATICFILES_FINDERS:
    ('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
DATE_FORMAT: 'N j, Y'
SESSION_CACHE_ALIAS: 'default'
QINIU_BUCKET_DOMAIN: 'o9hnmhk6k.bkt.clouddn.com'
SESSION_COOKIE_NAME: 'sessionid'
TIME_INPUT_FORMATS:
    ('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
SECURE_REDIRECT_EXEMPT: []
DATABASES: {
    'default': {   'ENGINE': 'django.db.backends.mysql',
                   'HOST': '127.0.0.1',
                   'NAME': 'wechat',
                   'PASSWORD': u'********',
                   'PORT': '3306',
                   'USER': 'root'}}
EMAIL_SSL_KEYFILE: u'********'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
THOUSAND_SEPARATOR: ','
REIDS_DATABASE_KEY_POOL: u'********'
FILE_UPLOAD_HANDLERS:
    ('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE: 'text/html'
LOCALTION_TEXT: '/Users/youyou/codingspace/django-work/localtext/text/{0}.txt'
APPEND_SLASH: True
FIRST_DAY_OF_WEEK: 0
DATABASE_ROUTERS: u'********'
EMAIL_USE_SSL: False
YEAR_MONTH_FORMAT: 'F Y'
STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES: {
    'default': {   'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CELERY_BIN: '/opt/.virtualenvs/wxmonitor/bin/celery'
LOCALTION_COMMENT: '/Users/youyou/codingspace/django-work/localtext/comment/{0}.txt'
SERVER_EMAIL: 'root@localhost'
SESSION_COOKIE_PATH: '/'
EMAIL_HOST_PASSWORD: u'********'
SILENCED_SYSTEM_CHECKS: []
MIDDLEWARE_CLASSES:
    ('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')
USE_I18N: True
SECRET_KEY: u'********'
LANGUAGE_COOKIE_NAME: 'django_language'
IS_PROXY: True
DEFAULT_INDEX_TABLESPACE: ''
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
LOGGING_CONFIG: 'logging.config.dictConfig'
BROKER_POOL_LIMIT: 10000
TEMPLATE_LOADERS:
    ('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION: 'weixin.wsgi.application'
FORMAT_MODULE_PATH: None
X_FRAME_OPTIONS: 'SAMEORIGIN'
AUTHENTICATION_BACKENDS:
    ('django.contrib.auth.backends.ModelBackend',)
FORCE_SCRIPT_NAME: None
USE_X_FORWARDED_HOST: False
EMAIL_TIMEOUT: None
SECURE_SSL_HOST: None
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE: False
REDIS_HOST: '127.0.0.1'
SECURE_BROWSER_XSS_FILTER: False
CSRF_COOKIE_DOMAIN: None
FILE_CHARSET: 'utf-8'
DEBUG: True
LANGUAGE_COOKIE_DOMAIN: None
DEFAULT_FILE_STORAGE: 'qiniustorage.backends.QiniuStorage'
INSTALLED_APPS:
    ('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'djcelery',
 'kombu.transport.django',
 'qiniustorage',
 'item_weixin',
 'account',
 'logins',
 'celery_observe',
 'athena',
 'account_detail',
 'celery_monitor')
IS_SINA_PROXY: True
LANGUAGES:
    (('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
STATICFILES_DIRS:
    ('/Users/youyou/codingspace/django-work/wechat-article-monitor/webapp',)
is_overridden: <bound method Settings.is_overridden of <django.conf.Settings object at 0x110c2cd90>>
PREPEND_WWW: False
SECURE_PROXY_SSL_HEADER: None
REIDS_DATABASE_HISTORY: u'********'
LANGUAGE_COOKIE_AGE: None
SESSION_COOKIE_HTTPONLY: True
CELERY_REDIS_MAX_CONNECTIONS: 100
DEBUG_PROPAGATE_EXCEPTIONS: False
CSRF_COOKIE_AGE: 31449600
MEDIA_URL: ''
MONTH_DAY_FORMAT: 'F j'
MANAGERS:
    ()
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
REDIS_DATABASE_CELERY: u'********'
QINIU_ACCESS_KEY: u'********'
TIME_FORMAT: 'P'
CELERY_IGNORE_RESULT: True
EXTRA_APPS:
    ()
AUTH_USER_MODEL: 'logins.NewUser'
DATE_INPUT_FORMATS:
    ('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
CSRF_COOKIE_NAME: 'csrftoken'
USE_THOUSAND_SEPARATOR: False
PASSWORD_RESET_TIMEOUT_DAYS: u'********'
SESSION_FILE_PATH: None
CACHE_MIDDLEWARE_ALIAS: 'default'
SESSION_SAVE_EVERY_REQUEST: False
NUMBER_GROUPING: 0
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH: '/'
LOGIN_REDIRECT_URL: '/accounts/profile/'
CELERYD_POOL_RESTARTS: True
DECIMAL_SEPARATOR: '.'
REDIS_DATABASE: u'********'
IGNORABLE_404_URLS:
    ()
LOCALE_PATHS:
    ()
TEMPLATE_STRING_IF_INVALID: ''
DISALLOWED_USER_AGENTS:
    ()
REDIS_DATABASE_UIN: u'********'
ALLOWED_INCLUDE_ROOTS:
    ()
USE_L10N: True
EXECUTABLE_PATH: 'phantomjs'
FIXTURE_DIRS:
    ()
EMAIL_HOST: 'localhost'
REDIS_PASSWORD: u'********'
MEDIA_ROOT: ''
CELERYD_CONCURRENCY: '2'
ADMINS:
    ()
TEMPLATE_DEBUG: False
DEFAULT_FROM_EMAIL: 'webmaster@localhost'
SECURE_CONTENT_TYPE_NOSNIFF: False
DATETIME_FORMAT: 'N j, Y, P'
TEMPLATE_DIRS:
    ()
CELERY_ACCEPT_CONTENT: ['pickle', 'json', 'msgpack', 'yaml']
QINIU_SECRET_KEY: u'********'
LOGOUT_URL: '/accounts/logout/'
REDIS_DATABASE_PROXY_IP: u'********'
SOGOU_WAP_SID: 'CNXIpcEMEkBneFNPMDYxdi1vVzNwUXZiazF1T2pCSmVKRmJoc2lvZERsRmY5U3lWOGtXTzJra0xFQTh1ZmV1Q1FKNTQ2VjVSGAQgzhIokLOj9wgwsPX3vwU='
CELERY_TIMEZONE: 'Asia/Shanghai'
LOGGING: {
    }
SHORT_DATE_FORMAT: 'm/d/Y'
TEMPLATES: [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_KEY_PREFIX: u'********'
EMAIL_USE_TLS: False
TIME_ZONE: 'Asia/Shanghai'
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_TABLESPACE: ''
TEMPLATE_CONTEXT_PROCESSORS:
    ('django.contrib.auth.context_processors.auth',
 'django.template.context_processors.debug',
 'django.template.context_processors.i18n',
 'django.template.context_processors.media',
 'django.template.context_processors.static',
 'django.template.context_processors.tz',
 'django.contrib.messages.context_processors.messages')
CELERY_QUEUES:
    (<unbound Queue account_key -> <unbound Exchange account_key(direct)> -> account_key>,
 <unbound Queue wxmonitor -> <unbound Exchange wxmonitor(direct)> -> wxmonitor>,
 <unbound Queue history -> <unbound Exchange history(direct)> -> history>,
 <unbound Queue read -> <unbound Exchange read(direct)> -> read>)
MIGRATION_MODULES: {
    }
SESSION_COOKIE_AGE: 1209600
SETTINGS_MODULE: 'weixin.settings'
USE_ETAGS: False
SESSION_COOKIE_DOMAIN: None
LANGUAGES_BIDI:
    ('he', 'ar', 'fa', 'ur')
FILE_UPLOAD_TEMP_DIR: None
INTERNAL_IPS:
    ()
STATIC_URL: '/static/'
CELERYD_PREFETCH_MULTIPLIER: 0
EMAIL_PORT: 25
USE_TZ: True
SHORT_DATETIME_FORMAT: 'm/d/Y P'
CELERY_RESULT_BACKEND: 'djcelery.backends.database:DatabaseBackend'
PASSWORD_HASHERS: u'********'
ABSOLUTE_URL_OVERRIDES: {
    }
LANGUAGE_COOKIE_PATH: '/'
CACHE_MIDDLEWARE_SECONDS: 600
EMAIL_SSL_CERTFILE: None
CSRF_COOKIE_HTTPONLY: False
DATETIME_INPUT_FORMATS:
    ('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER: ''

- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
my new celery version is 4.0.0 and my old version is 3.1.20
when i use   
celery worker -A weixin  
it raise error 

## Actual behavior

and my errror is that  
[2016-12-01 16:09:33,140: CRITICAL/MainProcess] Unrecoverable error: ImportError('No module named timeutils',)
Traceback (most recent call last):
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/apps/worker.py", line 158, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/apps/worker.py", line 219, in startup_info
    results=self.app.backend.as_uri(),
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/app/base.py", line 1162, in backend
    return self._get_backend()
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/app/base.py", line 880, in _get_backend
    self.loader)
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/app/backends.py", line 65, in by_url
    return by_name(backend, loader), url
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/celery/app/backends.py", line 45, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/youyou/Envs/wechat-article-monitor/lib/python2.7/site-packages/djcelery/backends/database.py", line 5, in <module>
    from celery.utils.timeutils import maybe_timedelta
ImportError: No module named timeutils

**Comment by skrud** [comment]
You still have `djcelery` in your INSTALLED_APPS. As far as I know, djcelery doesn't work with Celery 4.0. (Also, it's no longer required to run Celery through Django -- Django is supported out of the box).

In order to store results in a Django DB Backend, you'll need the `django-celery-results` package. Note that this has a different model name than djcelery's TaskMeta – so you'll need to make some changes if you're relying on those models in your code.

See more info here: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by chenjian158978** [comment]
@skrud 
I am using RabbitMQ and Celery. 
Can you tell me **the newest versions** of both Celery, Djcelery and Django that those parts can **work fine together**? 
Thx.

**Comment by thedrow** [comment]
Why do you need djcelery? Celery 4.x integrated most of the functionality of djcelery already.

**Comment by TBWISK** [comment]
@chenjian158978 now , I know that the newest version in celery , it can use in django ,but it remove 'djcelery' this app ,and use django-celery-results and django-celery-beat to replace beat's work .You can look this [http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html)

**Comment by TBWISK** [comment]
@thedrow I know what happen in my wrong, and I know how to deal with it . Thanks for you ansower,but not celery 4.x intergrated most fo the functionality of djcelery . because It write other app to replase djcelery ^-^
