### ISSUE TITLE
"disabled prefetch" with "task_acks_late = True" and "worker_prefetch_multiplier = 1" is circumvented when using countdown on tasks

### ISSUE THREAD

**Issue by lukasheinrich** [celery/celery#3640]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

## Steps to reproduce

1) start redis broker
`
redis-server
`
2) submit two tasks without countdown

```
import debugcelery
debugcelery.hello.apply_async()
debugcelery.hello.apply_async()
```

3) start worker
```
celery worker -A debugcelery:app -l debug --concurrency 1 -E
```

as expected we see 1 task/messsage being received by the worker with the other task remaining in the queue

Now when using countdown = 1, we see unexpeced behaviour

repeat 1)
2) submit two tasks with countdown 

```
import debugcelery
debugcelery.hello.apply_async(countdown = 1)
debugcelery.hello.apply_async(countdown = 1)
```

3) start worker
```
celery worker -A debugcelery:app -l debug --concurrency 1 -E
```
## Actual behavior

Unexpectedly we see now that the worker Receives 2(!) messages/tasks, executed one and holds on to the second until the first task is finished

## Expected behavior

I would have expected the countdown to now be relevant in how the worker fetches messages and to for each worker to reserves the same number of tasks

celery report:

```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.10
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: u'redis://localhost:6379//'
worker_prefetch_multiplier
```
[debugcelery.py.txt](https://github.com/celery/celery/files/624510/debugcelery.py.txt)

**Comment by ask** [comment]
There's no way to get around this as for the worker to be able to accurately schedule the tasks
it needs to consume them.  The ETA of the second task could be shorter than the eta on the first task.

AMQP doesn't have the ability to schedule messages, so we are using the only cross-broker compatible solution available.

Redis could have a separate implementation, for example using sorted sets, but this is not implemented.
