### ISSUE TITLE
astimezone() argument 1 must be datetime.tzinfo, not function

### ISSUE THREAD

**Issue by contacitltd** [celery/celery#3650]
Hello,

I am trying to run a celery beat worker:
`sudo /home/ubuntu/myapp/bin/celery --app=myapp beat -s celerybeat-schedule -l info
`

And I get the following exception:
> [2016-12-04 19:06:01,839: WARNING/MainProcess] dt, timezone.utc if tz is None else timezone.tz_or_local(tz),
> [2016-12-04 19:06:01,839: WARNING/MainProcess] File "/home/ubuntu/myapp/local/lib/python2.7/site-packages/celery/utils/time.py", line 299, in localize
> [2016-12-04 19:06:01,839: WARNING/MainProcess] dt = dt.astimezone(tz)
> [2016-12-04 19:06:01,839: WARNING/MainProcess] TypeError
> [2016-12-04 19:06:01,839: WARNING/MainProcess] :
> [2016-12-04 19:06:01,839: WARNING/MainProcess] astimezone() argument 1 must be datetime.tzinfo, not function

This also happens when I try to run apply_async function with "countdown".
Has anyone seen it before?

Thanks!

**Comment by ask** [comment]
What's the value of the timezone setting?

```
celery -A myapp shell
>>> app.conf.timezone
>>> app.timezone
```

**Comment by contacitltd** [comment]
```
In [1]: app.conf.timezone
Out[1]: <function pytz.timezone>

In [2]: app.timezone
Out[2]: <function pytz.timezone>
```

**Comment by contacitltd** [comment]
So... I had this import in config.py:
`from pytz import timezone`
Which overriden the timezone value

**Comment by georgepsarakis** [comment]
@contacitltd can this issue be closed now perhaps?
