### ISSUE TITLE
The Task base class can't be registered in Celery 4.0

### ISSUE THREAD

**Issue by cydan33** [celery/celery#3659]
We can't register the class based tasks in the latest version of celery.
It is advised [here ](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#the-task-base-class-no-longer-automatically-register-tasks) to register these tasks manually by doing this:
`app.register_task(CustomTask())`

But the problem is that there's no "register_task" method. 
When we type:
`current_app.register_task(OurTask())`
It raises this:
```
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Celery' object has no attribute 'register_task'
```
Even when doing this:
`current_app.registry_cls().register(OurTask())`
It doesn't work and doesn't register anything.

**Comment by asafge** [comment]
You're right, register_task is part of the 4.0.1 release.
