### ISSUE TITLE
where is the register_task

### ISSUE THREAD

**Issue by Zuckonit** [celery/celery#3662]
from the celery4.0 doc:

```
class CustomTask(Task):
    def run(self):
        print('running')
app.register_task(CustomTask())
```

but there is no register_task method in whole celery4.0 source code

**Comment by ask** [comment]
It's coming in 4.0.1, it's not present in 4.0.0.

You're recommended to create tasks the normal way:

```
@app.task
def custom():
    print('running')
```

You can name it uppercase if you absolutely want to, and it won't be any different from the class you have above:

```
@app.task
def CustomTask():
    print('running')
```
