### ISSUE TITLE
How to show full log message in log file for a task

### ISSUE THREAD

**Issue by xiazhibin** [celery/celery#3663]
Here is example log:[2016-12-08 11:01:24,651: INFO/MainProcess] Task users.bin381.convert [535c8740-000a-4282-aa96-d1a9813da8ef] succeeded in 6.40846069995s: '{"rv": "ec1e90d2698b1845fd4998e9930727a3b4cacae4", "callback": "{\\"url\\":...

obviously,it does not show full log message.

so,How can I to show full log message in log file for a task?

**Comment by ask** [comment]
The result is always truncated at some size, but you can increase the size considerably:

```py
@app.task(resultrepr_maxsize=16384)
def convert(...):
    ....
```

**Comment by xiazhibin** [comment]
I try the keyword 'resultrepr_maxsize' but it does not work.

`@app.task(bind=True, max_retries=3, soft_tie_limit=600, default_retry_delay=600, routing_key='convert',
          resultrepr_maxsize=10240)`

Is there sth wrong?
