### ISSUE TITLE
Disable propagate for a portion of a canvas.

### ISSUE THREAD

**Issue by matthewatabet** [celery/celery#3673]
I have a `group` of tasks, some of which may fail unexpectedly. These tasks make use of shared resources which are allocated just before they run and need to be cleaned up afterwards.

I attempted to solve this like so:

```python
@task
def do_work():
    return generate_some_results()


@task
def cleanup(results):
    clean_stuff_up()
    return cull_exceptions_from_results(results)


canvas = group(do_work.s(propagate=False) for i in range(0, 10)) | cleanup.s()
```

But, if an exception is raised in one of the work tasks, the chord still fails without running `cleanup`. I found that running `canvas(propagate=False)` did work, but disables propagation for the entire canvas which is not what I want.

Essentially, I'd like to implement a canvas which achieves a try-except-finally semantic, where the finally clause is always run despite upstream errors. Any pointers? Thanks a bunch.

**Comment by matthewatabet** [comment]
At the moment, my workaround involves add a try/except to `do_work` which catches any exceptions and returns the corresponding exception object. It's up to `cleanup` at that point to filter and possibly re-raise these exceptions. That works fine, just wondering if Celery has support for try-except-finally and whether I might simply be using `propagate` incorrectly.

**Comment by ask** [comment]
The `propagate` argument is not used for `.apply_async`, it's used for `.apply` which is the eager execution implementation.

It's also an argument to `AsyncResult.get`:

```py
>>> div.delay(2, 0).get(propagate=False)
ZeroDivisionError('division by zero')

>>> div.delay(2, 0).get(propagate=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/celery/celery/celery/result.py", line 189, in get
    on_message=on_message,
  File "/opt/celery/celery/celery/backends/async.py", line 191, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
  File "/opt/celery/celery/celery/result.py", line 294, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/opt/celery/celery/celery/result.py", line 287, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/opt/celery/vine/vine/promises.py", line 213, in throw
    reraise(type(exc), exc, tb)
  File "/opt/celery/vine/vine/five.py", line 176, in reraise
    raise value
celery.backends.base.ZeroDivisionError: division by zero
```

So there's currently no way to tell a chain to ignore the exceptions in a task,
the task would have to handle the exceptions manually, or you could create a task that does it for you:

```py
@app.task(bind=True)
def ignore_errors(sig, errors=(Exception,)):
   try:
       self.app.signature(sig)()
   except errors:
       pass


canvas = group(
    ignore_errors.s(do_work.s()) for i in range(0, 10))
) | cleanup.s()
