### ISSUE TITLE
www.celeryproject.org needs updating

### ISSUE THREAD

**Issue by jakubczaplicki** [celery/celery#3677]
http://www.celeryproject.org/ might be a bit misleading. The latest news shouts that "Celery 3.1 Is Now Available!", yet the current stable version is 4.0.1. Perhaps it would be worth adding a news about 4.0 ?

**Comment by auvipy** [comment]
this should be on celeryprojec website repo

**Comment by jakubczaplicki** [comment]
Sorry about that. I've now re-created this ticket under the correct repo.
