### ISSUE TITLE
llen QUEUE_NAME can not get the expected length

### ISSUE THREAD

**Issue by huangkq1989** [celery/celery#3681]
## Checklist
 
software -> celery:4.0.1 (latentcall) kombu:4.0.1 py:2.7.10
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: u'redis://localhost:6379/1'

## Steps to reproduce

test.py
```
from celery import Celery
app = Celery('hello', broker='redis://localhost:6379/1')


@app.task(acks_late=True)
def add(x, y):
    import time
    time.sleep(10)   # sleep here, convenient for watching queue length. 
    return x + y
```

## Expected behavior

`llen celery` is NOT 0 when just run `test.add.delay(1,3)` without starting celery worker or task is not finished. 

## Actual behavior

When run `key *` in redis without starting celery worker, key `celery` doesn't exist, but `len celery\x06\x169` has the correct length.
And when start celery worker and  run  `for i in range(1000): test.add.delay(1,3)`, `celery` queue never show up in redis, but `len celery\x06\x169` is fine. And I do the same job in celery:3.1.23, expected behavior show up，which means `len celery` get the correct length. Anything is wrong? Thanks.

**Comment by ask** [comment]
This was fixed in kombu master, the default priority should be 0, but priority was reversed so it ended up being 9.

**Comment by huangkq1989** [comment]
Cool, thanks.
