### ISSUE TITLE
when I change the system date , celery beat will not work..

### ISSUE THREAD

**Issue by Rambo-rambo** [celery/celery#3685]
## Checklist

I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
①python manage.py celery worker -A prj
②python manage.py celery beat -A prj -loglevel=debug -s /var/run/celerybeat-schedule --pidfile=/var /run/celerybeat.pid
③ now，celery woker and beat in running，all right 0*0

BUT：：：：：：：
④ when i change the system date "date -s "2012-12-12 12:23:11"
⑤oh！！！！！！！ my celery beat is on strike。。。。。
⑥ now,only system reboot,is ok .

**Comment by Rambo-rambo** [comment]
env：
       centos -7 
       celery (3.1.24)
       django-celery (3.1.17)
       Python 2.7.5
config:
        BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}  # 1 hour.
       BROKER_URL = 'redis://localhost:8888'
       CELERY_RESULT_BACKEND = 'redis://localhost:8888'
       CELERY_ACCEPT_CONTENT = ['application/json']
       CELERY_TASK_SERIALIZER = 'json'
       CELERY_RESULT_SERIALIZER = 'json'
       CELERY_TIMEZONE = 'Asia/Shanghai'
       CELERY_ENABLE_UTC = True
       CELERYD_CONCURRENCY = 4
       CELERYBEAT_SCHEDULE = {
           'vgate_monitor-20-seconds': {
               'task': 'prj.tasks.monitor',
               'schedule': timedelta(seconds=20),
               # 'args': (16, 16)
           }}

①python manage.py celery worker -A prj 
②python manage.py celery beat -A prj -loglevel=debug -s /var/run/celerybeat-schedule  --pidfile=/var      /run/celerybeat.pid
③ now，celery woker and beat  in running，all right  0*0

BUT：：：：：：：
④ when i change the system date   "date -s "2012-12-12 12:23:11"
⑤oh！！！！！！！ my celery beat is on strike。。。。。
⑥ now,only system reboot,is ok .

HELP me 0~0

**Comment by ask** [comment]
One of the new optimizations in Celery 4 is that we use a heap to schedule periodic tasks.

This operation involves converting the datetime runtimes to a timestamp, so it definitely won't
work well if you change your system time.

I'm guessing we would need a way to figure out that the system time changed, but not sure how that is possible.

**Comment by ask** [comment]
This could maybe work on Linux: https://lkml.org/lkml/2010/9/16/405

**Comment by Rambo-rambo** [comment]
The beat schedule'starttime  can use the "linux uptime"

**Comment by Rambo-rambo** [comment]
# Setting a default time a bit before now to not miss a task that was
+        # just added.
+
+        if {'every', 'period'}.issubset(schedule.keys()):
+            now = self.nowfun()
+            # first time or system reboot
+            if not last_run_at or last_run_at > now:
+                last_run_at = now - timedelta(
+                    seconds=app.conf.CELERYBEAT_MAX_LOOP_INTERVAL)
+        elif not last_run_at:
+            last_run_at = app.now() - timedelta()




@classmethod
+    def nowfun(cls, utc=True):
+        with open('/proc/uptime', 'r') as f:
+            uptime = float(f.readline().split()[0])
+        if utc:
+            return datetime.utcfromtimestamp(uptime)
+        return datetime.fromtimestamp(uptime)

**Comment by auvipy** [comment]
I am closing the issue hoping to be fixed in master. report if not
