### ISSUE TITLE
Celery fails to convert tasks w/o kwargs from protocol v1 to v2

### ISSUE THREAD

**Issue by gabrielpjordao** [celery/celery#3687]
InvalidTaskError is being raised when there's no kwargs present in the message.

There's actually a test (https://github.com/celery/celery/blob/master/t/unit/worker/test_strategy.py#L33-L36) ensuring that an`InvalidTaskError` is raised in case there's no kwargs in the task.

This is not what used to happen in v1. Docs also say the following for kwargs:
```
Dictionary of keyword arguments. Will be an empty dictionary if not provided.
```
as you can see in
 http://docs.celeryproject.org/en/latest/internals/protocol.html#id8 

I can open a PR if you guys think this rule should really be removed.

Thanks!

**Comment by ask** [comment]
Thanks for reporting this, if it differs from the previous behavior then it's a mistake!

**Comment by rsichny** [comment]
I think it's misenterpretation of docs and tests.
'kwargs' must be in body, though if they were missing from task call they will be set to empty dictionary.

For example 3.1 always set them: https://github.com/celery/celery/blob/3.1/celery/app/amqp.py#L253
As well as both protocol versions in 4.0: https://github.com/celery/celery/blob/4.0/celery/app/amqp.py#L401 https://github.com/celery/celery/blob/4.0/celery/app/amqp.py#L314

**Comment by gabrielpjordao** [comment]
The problem is that some of my tasks aren't produced from celery @rsichny. 

They are produced from a non-python app, following the described protocol. The problem is in the consumption side, as there are "optional" fields in the protocol that are now actually required.

Does that make sense?

**Comment by rsichny** [comment]
probably it does

the fix is quite simple:

```diff
diff --git a/celery/worker/strategy.py b/celery/worker/strategy.py
index 6246b69..a508d3e 100644
--- a/celery/worker/strategy.py
+++ b/celery/worker/strategy.py
@@ -30,7 +30,7 @@ def proto1_to_proto2(message, body):
         Tuple: of ``(body, headers, already_decoded_status, utc)``
     """
     try:
-        args, kwargs = body['args'], body['kwargs']
+        args, kwargs = body['args'], body.get('kwargs', {})
         kwargs.items  # pylint: disable=pointless-statement
     except KeyError:
         raise InvalidTaskError('Message does not have args/kwargs')
diff --git a/t/unit/worker/test_strategy.py b/t/unit/worker/test_strategy.py
index 0876299..4e85c35 100644
--- a/t/unit/worker/test_strategy.py
+++ b/t/unit/worker/test_strategy.py
@@ -32,8 +32,8 @@ class test_proto1_to_proto2:

     def test_message_without_kwargs(self):
         self.body.pop('kwargs')
-        with pytest.raises(InvalidTaskError):
-            proto1_to_proto2(self.message, self.body)
+        body, _, _, _ = proto1_to_proto2(self.message, self.body)
+        assert body[:2] == ((1,), {})

     def test_message_kwargs_not_mapping(self):
         self.body['kwargs'] = (2,)
```

**Comment by gabrielpjordao** [comment]
Nice :) Do you want me to submit the PR? If you feel like it, go ahead

**Comment by gabrielpjordao** [comment]
Nice @rsichny. 

I just noticed that the same would probably also happen with `args`, which defaults to a list in v1 protocol. I didn't get it earlier because my messages did provide it.

It might be a good idea to include them in your PR as well.

**Comment by rsichny** [comment]
added.

i'm still worried that this is misintepretation of documentation, but we can leave this decision to maintainers.
