### ISSUE TITLE
Unable to consume message while using protocol 2.

### ISSUE THREAD

**Issue by eire1130** [celery/celery#3689]
## Checklist

- [X ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

Version 4.0.1

- [X ] I have verified that the issue exists against the `master` branch of Celery.

Also tried on version hash 199cf69

## Steps to reproduce

When using Django==1.8.15, amqp==2.1.4, billiard==3.5.0.2 and kombu==4.0.,  rabbitmq version {rabbit,"RabbitMQ","3.5.1"}, and Python 2.7.9 

while running on my local machine (mac 10.10.1)

I am unable to consume messages in protocol 2.

Example trace:

[2016-12-15 10:00:34,876: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: [[114], {}, {u'errbacks': None, u'callbacks': None, u'chord': None, u'chain': None}] (80b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{'consumer_tag': 'None11', 'redelivered': False, 'routing_key': 'ta-indexer', 'delivery_tag': 1L, 'exchange': ''} headers={'\xe5\xca.\xdb\x00\x00\x00\x00\x00': None, 'P&5\x07\x00': None, 'T\nKB\x00\x00\x00': '8f06dd0a-b6d5-484f-be90-96176c374ecc', 'N\xfd\x17=\x00\x00': 'gen8895@James-MacBook-Pro.local', '\xcfb\xddR': 'py', '9*\xa8': None, '\xb7/b\x84\x00\x00\x00': 0, '\xe0\x0b\xfa\x89\x00\x00\x00': None, '\xdfR\xc4x\x00\x00\x00\x00\x00': [None, None], 'T3\x1d ': 'talent_application_do_index_task', '\xae\xbf': '8f06dd0a-b6d5-484f-be90-96176c374ecc', '\x11s\x1f\xd8\x00\x00\x00\x00': '(114,)', 'UL\xa1\xfc\x00\x00\x00\x00\x00\x00': '{}'}}

However, setting:

CELERY_TASK_PROTOCOL = 1

results in:

[2016-12-15 10:09:47,511: INFO/MainProcess] Received task: talent_application_do_index_task[8917b028-4e3a-43b2-8e77-2c71dd178ba9]  
[2016-12-15 10:09:47,513: WARNING/PoolWorker-1] do_index_task(114, False)
[2016-12-15 10:09:48,224: INFO/PoolWorker-1] Task talent_application_do_index_task[8917b028-4e3a-43b2-8e77-2c71dd178ba9] succeeded in 0.712397804018s: None

This is my local instance, so both consumer and producer are using the same virtual env and the same setting files.

Obviously, I can continue to use Protocol 1, but I assume we should be moving to 2 soonish.

**Comment by bsusensjackson** [comment]
+1 for `CELERY_TASK_PROTOCOL = 1`

**Comment by ask** [comment]
You're using `librabbitmq` I think, and there's some bug there that stops it from working with Celery 4.

You should uninstall it:

`pip uninstall librabbitmq`

(repeat until it returns an error)

py-amqp is way ahead of librabbitmq at this point when it comes to features.

**Comment by eire1130** [comment]
That was the issue:

In our settings we have `CELERY_BROKER_TRANSPORT = 'amqp'`

and not librabbitmq though. Might be a documentation thing.

I appreciate the feedback here!
