### ISSUE TITLE
Does Celery Support SQS FIFO?

### ISSUE THREAD

**Issue by gregpinero** [celery/celery#3690]
It looks like it would require boto3 1.4.2. And it has new required arguments for the send_message call.

I created a new queue but my worker wouldn't connect. I'm wondering if you just don't support it yet.

https://aws.amazon.com/blogs/aws/new-for-amazon-simple-queue-service-fifo-queues-with-exactly-once-delivery-deduplication/

**Comment by ask** [comment]
I haven't looked into this feature yet, but if it's something that needs to be set in the client, some argument or something, then we probably don't support it yet.

Not sure how much work it would be to support it either, I'm guessing it won't be that difficult if boto has support for it.

**Comment by gregpinero** [comment]
Thanks.  I verified I could list, send a message, and receive using boto3 1.4.2.

I believe the new send message parameters are MessageGroupId and MessageDeduplicationId.

**Comment by jseutter** [comment]
@ask - is anyone working on this issue yet?  Are you open to PRs for this, at least in theory?

**Comment by sarthaksahni** [comment]
I have been using cheery 3.1.23 (Cipater) for some old deployments. I was just modifying an old deployment that works with SQS, found very odd (annoying) issue. My celery workers were doing just fine, but when I tried to push a packet in my queue, the name of the queue was modified. 

Let me explain in detail, if my queue name is ```some_queue.fifo``` (the extension ```.fifo``` is mandatory for an SQS FIFO queue) then the packets were being directed to ```some_queue-fifo```. I have already scratched my head to end up on my nerves to understand why would this even happen!

@ask any update that can help me here?

**Comment by jseutter** [comment]
@sarthaksahni - I recently worked on a PR for better SQS support (not yet merged).  On master I found code that replaces periods with hyphens:

https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L161 - specifically the CHARS_REPLACE_TABLE defined at the top of the file.

Going from (probably bad) memory, when I tested it I seem to remember weird behavior.  Something like I could consume from a pre-existing .fifo queue, but when I tried to publish to a .fifo queue a queue would be created with a name ending in -fifo.  It looks like the SQS support in Celery may predate fifo queues.

I made changes to Kombu to work with fifo queues - https://github.com/celery/kombu/pull/678 and Celery now works for my purposes.

**Comment by sarthaksahni** [comment]
@jseutter just added a 👍 for that PR request! Going to pull that code for my development environment. I don't understand that if ```.fifo``` is a __legal name__ by __AWS SQS__ then what does this ```"""Format AMQP queue name into a legal SQS queue name."""``` mean 😕? Thanks for the PR though!

**Comment by jseutter** [comment]
@sarthaksahni - If you go in the AWS console and try putting periods in the queue name, the console says that you have invalid characters.  So in this respect that comment is accurate.  It seems the code should prevent periods except for when the queue name ends in .fifo.

I think this code for queue names may predate AWS offering .fifo queues.  It looks like AWS has left the door open to offer other queue types as well, since tomorrow they could start offering .lifo, .random, or .blackhole queues.

**Comment by fletort** [comment]
Hello, is this issue always open ?
Celery does not yet support SQS Fifo queue ?

**Comment by dws-sarthak** [comment]
@fletort I think the PR did merge. BOTO3 worked well with SQS FIFO. Which version of celery and kombu are you using? 
For an update: [678](https://github.com/celery/kombu/pull/678) was merged by [this PR](https://github.com/celery/kombu/pull/693) at Kombu.
So if you are using celery 4+ and with all eligible and correct dependencies, you should not be facing issues!

**Comment by auvipy** [comment]
closing as fixed on master, try latest releases.

**Comment by marvelph** [comment]
Thankes  georgepsarakis.
I'll give it a try.
