### ISSUE TITLE
[question] How to do health check of a beat process?

### ISSUE THREAD

**Issue by robsonpeixoto** [celery/celery#3694]
I'm using the stack mesos + marathon + docker to run all celery workers and beat.
To health check the celery work process, I'm using the script:

```bash
#!/bin/bash

STATUS=$(celery -A <MY-MODULE> status -C | grep $(hostname) | awk '{print $2}')

if [[ "$STATUS" == "OK" ]]; then
  exit 0
else
  exit 1
fi
```

Do you have any idea how to check if the celery beat is running?

Thanks

**Comment by imanhodjaev** [comment]
@robsonpeixoto we do it by getting PID from `celerybeat.pid` and using `psutil`

**Comment by robsonpeixoto** [comment]
Thanks @imanhodjaev

**Comment by georgepsarakis** [comment]
@robsonpeixoto do you need other help with this or it is answered?

**Comment by hsiaoyi0504** [comment]
@georgepsarakis @robsonpeixoto @imanhodjaev  I would like to know if it is possible to check celery beat through python script. I am using celery 3.1.

**Comment by kjaworowski** [comment]
@hsiaoyi0504 
check [this](https://steemit.com/code/@qrul/celery-beat-and-workers-healthchecks)

**Comment by jose-lpa** [comment]
Nice one @kjaworowski thank you.

Also note that there is no need to read files from disk as the example shows. You can also obtain the schedule programatically by doing this:

```
from celery import current_app
from celery.beat import Service


schedule = Service(app).get_scheduler().get_schedule()

for task_name, task in schedule.items():
    # Your checks here :)
```

**Comment by lcannon** [comment]
For our beat set up, we didn't have any last_run_at dates to check. For people in the same position, you may be interested in the solution we used which is:

1. A minutely task that sets a key in redis to expire in 2 minutes' time.
2. A manage.py command that exits with sys.exit(1) if that key isn't set. Run every minute, starting two minutes from when beat starts running.
