### ISSUE TITLE
autodiscover_tasks(force=False) silently ignores import errors

### ISSUE THREAD

**Issue by paultiplady** [celery/celery#3697]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue:
I'm not able to share my app config, as it contains sensitive information. Can provide any relevant settings on request. Here's the celery-specific part:

```
software -> celery:4.0.1 (latentcall) kombu:4.0.2 py:3.4.5
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

- [x] I have verified that the issue exists against the `master` branch of Celery.
  Tested on 8c7ac5d84d245028f02b5d7f6a8684a1ce84dc9e

## Steps to reproduce

Introduce an import error in a task that's imported in Celery with `autodiscover_tasks(settings.INSTALLED_APPS)`.

## Expected behavior

Celery produces an error on startup, explaining why the imports failed.

## Actual behavior

Celery silently fails to load tasks, and starts up with no error. Task list is empty.

If the command `autodiscover_tasks(settings.INSTALLED_APPS, force=True) is run manually, then an exception is raised:

```
In [8]: app.autodiscover_tasks(settings.INSTALLED_APPS, force=True)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-d7c606beffc5> in <module>()
----> 1 app.autodiscover_tasks(settings.INSTALLED_APPS, force=True)

/usr/local/lib/python3.4/site-packages/celery/app/base.py in autodiscover_tasks(self, packages, related_name, force)
    661         """
    662         if force:
--> 663             return self._autodiscover_tasks(packages, related_name)
    664         signals.import_modules.connect(starpromise(
    665             self._autodiscover_tasks, packages, related_name,

/usr/local/lib/python3.4/site-packages/celery/app/base.py in _autodiscover_tasks(self, packages, related_name, **kwargs)
    668     def _autodiscover_tasks(self, packages, related_name, **kwargs):
    669         if packages:
--> 670             return self._autodiscover_tasks_from_names(packages, related_name)
    671         return self._autodiscover_tasks_from_fixups(related_name)
    672 

/usr/local/lib/python3.4/site-packages/celery/app/base.py in _autodiscover_tasks_from_names(self, packages, related_name)
    674         # packages argument can be lazy
    675         return self.loader.autodiscover_tasks(
--> 676             packages() if callable(packages) else packages, related_name,
    677         )
    678 

/usr/local/lib/python3.4/site-packages/celery/loaders/base.py in autodiscover_tasks(self, packages, related_name)
    221         self.task_modules.update(
    222             mod.__name__ for mod in autodiscover_tasks(packages or (),
--> 223                                                        related_name) if mod)
    224 
    225     @cached_property

/usr/local/lib/python3.4/site-packages/celery/loaders/base.py in autodiscover_tasks(packages, related_name)
    246     _RACE_PROTECTION = True
    247     try:
--> 248         return [find_related_module(pkg, related_name) for pkg in packages]
    249     finally:
    250         _RACE_PROTECTION = False

/usr/local/lib/python3.4/site-packages/celery/loaders/base.py in <listcomp>(.0)
    246     _RACE_PROTECTION = True
    247     try:
--> 248         return [find_related_module(pkg, related_name) for pkg in packages]
    249     finally:
    250         _RACE_PROTECTION = False

/usr/local/lib/python3.4/site-packages/celery/loaders/base.py in find_related_module(package, related_name)
    272         return
    273 
--> 274     return importlib.import_module('{0}.{1}'.format(package, related_name))

/usr/local/lib/python3.4/importlib/__init__.py in import_module(name, package)
    107                 break
    108             level += 1
--> 109     return _bootstrap._gcd_import(name[level:], package, level)
    110 
    111 

/usr/local/lib/python3.4/importlib/_bootstrap.py in _gcd_import(name, package, level)
...
<beginning of failed Python import>
```

**Comment by pramttl** [comment]
I am able to reproduce this on `Django 1.10.5` and `Celery 4.0.2`. If I add the `force=True` flag to autodiscover, it leads to a `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet` otherwise no error is shown and the tasks don't register.

**Comment by Bala-ksrn** [comment]
Is there a solution for this issue? I am on Django 1.10.5 and Celery 4.0.2. I get the error - django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

And only one App's tasks are having this problem. My other app tasks are getting registered without issues.

**Comment by GabLeRoux** [comment]
Experienced this too, we had a hard time finding out that we were missing a dependency for the task as it failed silently. I'm also seeking for a fix 👍

**Comment by kcdipesh** [comment]
I'm also getting this issue and not found any solution yet!

**Comment by Bala-ksrn** [comment]
I had to move all the tasks inside tasks.py and it started working. But what is weird is that this is not the case with other Apps in my project.

**Comment by GabLeRoux** [comment]
Try running tasks with breakpoints or manually from the command line by adding something like this at the end of your script:

```python
if __name__ == "__main__":
    name_of_your_task(hardcoded_parameters)
```

As I said above, one of my task had a missing dependency, but it could have been anything that prevented the script to run. You may also check your `__init__.py` files or make sure it's there for your none working app. Here's someone on [stackoverflow who had a similar issue](https://stackoverflow.com/questions/40553007/celery-doesnt-autodiscover-tasks-from-all-apps). Good luck.

**Comment by scottwilson312** [comment]
Why is this issue closed - what's the solution? Surely commenting out code until it works can't be the official solution !

**Comment by iddqd1** [comment]
It still does not work were django setings are module

**Comment by jmbowman** [comment]
We hit a problem that looked very similar, but ultimately turned out not to be an import error.  There were two different celery apps in the code, and based on variability in startup timing sometimes tasks ended up associated with the wrong one (they were using `celery.task`), so they were effectively missing from the app they were intended to belong to.  Just leaving that here in case it helps anyone else seeing similar symptoms and hunting for a root cause.
