### ISSUE TITLE
How to define bootstep for heartbeat?

### ISSUE THREAD

**Issue by imanhodjaev** [celery/celery#3703]
## Checklist

- [x] I have tried to add a bootstep for workers and and tried to do the same for beat
- [x] Bootstep worked with worker but didn't for heartbeat

## Motivation

I want to add a custom CLI argument and process it in bootstep.
According to documentation it is possible to add boostep for beat too http://docs.celeryproject.org/en/latest/userguide/extending.html#id14.

**Comment by auvipy** [comment]
ask questions to mailing list first
