### ISSUE TITLE
Question: RPC Cleanup?

### ISSUE THREAD

**Issue by listingmirror** [celery/celery#3704]
Is there a way to do old RPC cleanup?

I have a lot of workers join up for a while.. process some messages, then go away (autoscaling etc. etc.).  After a few days of this, my RabbitMQ broker has a few thousand empty queues with a GUID for a name. This seems to be from the rpc:// result backend.  Outside of manually deleting these, is there any way to configure Celery to clean these up?

I see an auto_delete property hidden down at http://docs.celeryproject.org/en/latest/internals/reference/celery.backends.rpc.html#celery.backends.rpc.RPCBackend.Exchange.auto_delete , but not sure if this is the correct route or how to apply it?  The docs seem to say the default is FALSE, but the source seems to say the default is FALSE for 3.1, but TRUE for 4.0?    If so, then I just need to figure out how to flip the setting in my 3.1 setup, and then make a PR to fix the docs for 4.0 to say the default is now true

**Comment by auvipy** [comment]
check master branch and verify
