### ISSUE TITLE
Worker option --max-memory-per-child does not work for me

### ISSUE THREAD

**Issue by tnatschl** [celery/celery#3706]
#### Steps to reproduce

I started a worker for my project like this:

`celery worker -A myproj -l INFO -c 2 -Q default --max-memory-per-child=150000`

#### Expected behavior

When the child exceeds 150MB of memory it should be restarted.

#### Actual behavior

When memory is below 150MB I get the *wrong* message:

`[2016-12-20 10:59:58,508: ERROR/PoolWorker-1] worker unable to determine worker memory usage`

When memory is above 150MB I get the *nearly correct* message:

`[2016-12-20 11:01:47,602: ERROR/PoolWorker-5] child process exiting after exceeding memory limit (155256KiB / 155256KiB)`

"nearly" refers to the KiB after the slash (which I assume should be the max amount).

#### Versions used

celery 4.0.2 which uses billiard 3.5.0.2

#### Problem

* In `billiard/pool.py` in `Worker.workloop` the else clause in lines 384-385 seems to be superfluous.
* The definition of `MAXMEM_USED_FMT` seems to be wrong.

#### Possible Fix

When I remove the two lines  384-385 and change the definition of `MAXMEM_USED_FMT` to

`MAXMEM_USED_FMT = "child process exiting after exceeding memory limit ({0}KiB / {1}KiB)"`

it seems to work.

**Comment by MrYoda** [comment]
I have the same issue. Celery 4.0.1 (latentcall), billiard 3.5.0.2, Python 3.5.2, Ubuntu 16.04.1 LTS

**Comment by QuilD** [comment]
I have the same issue. Celery 4.0.2, python 3.6.1

**Comment by cjcjcj** [comment]
Same. Python 3.5.2, Celery 4.0.2 (latentcall)

**Comment by Kalanamith** [comment]
Config which um using 

```python
worker.run(app="app.task_queue", loglevel="info", worker_max_tasks_per_child=4, max_memory_per_child=80000)
```



memory limit which Im seeing 
```
   74     9 root     S     205m   1%   1   0% ./tq.py tasks
   70     9 root     S     188m   1%   1   0% ./tq.py tasks

```

Its not spawning new processes and utilising more and more memory
