### ISSUE TITLE
Celery Task Execution time (runtime) increases with number of workers. Why?

### ISSUE THREAD

**Issue by josepainumkal** [celery/celery#3727]
I have executed 10 tasks with different number of worker instances. I noticed that the task execution time increases when the number of worker increases. The workers are configured to take exactly one job at a time ( prefetch=1).
Please see below. 
10 jobs and 1 worker - Avg Run time(each task): 4.2 seconds 
10 jobs and 2 worker - Avg Run time(each task): 8.7 seconds 
10 jobs and 3 worker - Avg Run time(each task): 13.03 seconds 
10 jobs and 4 worker - Avg Run time(each task): 18.51 seconds

I could see the jobs are starting and working parallely with different workers (by inspecting workers). Please tell me why the average execution time increases with more workers, even though jobs are being executed parallely?

Thanks,Jose

**Comment by brianwawok** [comment]
What OS? What's the command line you are starting workers with?

**Comment by josepainumkal** [comment]
my workers are actually separate docker containers. All my containers (workers) are on a single host.
the command for worker is:
celery -A worker.modelworker worker -Ofair --loglevel=info --autoreload --logfile=/celery.log

**Comment by brianwawok** [comment]
So you are running 4 docker containers each with 1 worker in it?  What is your system CPU usage, are you maxing it?

Try using a single docker for your workers, and add -c.. so -c 1, -c 2, -c 3, -c 4. Multiprocessing is going to be a lot more efficient than docker for more workers.  (And if multiprocessing doesn't help for you, then we can look into eventlet or such, but for 4 workers multiprocessing should be fine).
