### ISSUE TITLE
task_eager_propagates does not appear to help propagation, but causes on_failure handler to be skipped

### ISSUE THREAD

**Issue by lddubeau** [celery/celery#3728]
## Relevant Output of `celery -A tasks report`

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12+
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

BROKER_URL: u'amqp://guest:********@memory:5672//'
CELERY_ALWAYS_EAGER: True
CELERY_EAGER_PROPAGATES_EXCEPTIONS: False
```

Note that `CELERY_EAGER_PROPAGATES_EXCEPTIONS` is the setting which is the topic of this report and thus its value is changed in the code that follows.

I've actually reproduced the behavior as far back as Celery 3.1.0. So the following code is written to run with such old versions. That's why it does not use the setting names introduced in 4.0.

## Steps to reproduce

This is the code to use. Save it in `tasks.py`.

```
import sys

from celery import Celery, Task

propagate = len(sys.argv) > 1 and sys.argv[1] == "propagate"
print "PROPAGATE:", propagate

app = Celery('tasks', broker='memory')

app.conf.update(CELERY_ALWAYS_EAGER=True,
                CELERY_EAGER_PROPAGATES_EXCEPTIONS=propagate,
                )

class CustomEx(Exception):
    pass

@app.task
def add(x, y):
    return x + y

@app.task
def fail():
    raise CustomEx("we failed!")

class Custom(Task):

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print "on_failure", exc

@app.task(base=Custom)
def fail_custom():
    raise CustomEx("we custom failed!")

print add.delay(1, 2).get()

try:
    fail.delay().get()
except Exception as ex:
    print ex, ex.__class__ == CustomEx

try:
    fail_custom.delay().get()
except Exception as ex:
    print ex, ex.__class__ == CustomEx
```

## Actual behavior

Here's what happens when I run the above without exception propagation:

```
$ python tasks.py 
PROPAGATE: False
3
we failed! True
on_failure we custom failed!
we custom failed! True
```

**Even with propagation turned off**, it turns out that the exception were in fact propagated to the calling code. Not only do we get the error message set by the task but the class of the exception is exactly the one raised.

The `on_failure` handler was called as we expected it to.

With exception propagation turned on:

```
$ python tasks.py propagate
PROPAGATE: True
3
we failed! True
we custom failed! True
```

We get the same exception propagation as in the previous case. However, **the on_failure handler has not been executed.**

## Expected behavior

Twofold:

1. I'd expect `task_eager_propagates` (or its equivalent in previous versions) to make a difference in what is being propagated back to the calling code. Right now, it seems to make no difference whatsoever in this regard.

2. I'd expect `task_eager_propagates` to not affect whether or not the `on_failure` handler is executed.

**Comment by michaelhelmick** [comment]
After a bit of digging, I think I fixed the docs for this: https://github.com/celery/celery/pull/3846

The setting that should be used is `CELERY_TASK_EAGER_PROPAGATES`

**Comment by lddubeau** [comment]
@michaelhelmick No.

First, this bit of the [documentation](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings):

> **Celery will still be able to read old configuration files**, so there’s no rush in moving to the new settings format.

(Emphasis added.) I read this as saying that Celery 4.x is still able to read the old configuration files "as-is". The old setting name was `CELERY_EAGER_PROPAGATES_EXCEPTIONS`, not `CELERY_TASK_EAGER_PROPAGATES`.

Also, take the code in the initial report, and add the following line after the call to `app.conf.update`:

```
print app.conf["task_eager_propagates"]
```

With my initial code, you'll get a printed value which is equal to the value of `CELERY_EAGER_PROPAGATES_EXCEPTIONS`.

If I replace `CELERY_EAGER_PROPAGATES_EXCEPTIONS` with `CELERY_TASK_EAGER_PROPAGATES`, then **the value printed is always `False`**, irrespective of the value of `CELERY_TASK_EAGER_PROPAGATES`.

**Comment by michaelhelmick** [comment]
From my understanding, nothing should have changed either, but I opted to just change the setting instead of digging more.

It may be related to this bit of code: https://github.com/celery/celery/blob/7d7a6fe01c451b247274b7f7f30204784dae1723/celery/app/defaults.py#L216-L218

**Comment by auvipy** [comment]
closing as fixed. report if it's not.
