### ISSUE TITLE
celery 4.* does not support broadcast

### ISSUE THREAD

**Issue by yangbh** [celery/celery#3740]
i used the celery broadcast demo code as below [http://docs.celeryproject.org/en/latest/userguide/routing.html#broadcast](http://docs.celeryproject.org/en/latest/userguide/routing.html#broadcast)
```
from kombu.common import Broadcast

app.conf.task_queues = (Broadcast('broadcast_tasks'),)
app.conf.task_routes = {'tasks.reload_cache': {'queue': 'broadcast_tasks'}}
```
my broker: rabbitmq

in celery 4.* ,rabbitmq broker cannot receive broadcast message
in celery 3.1.24, the code works well
please help, ^.^!

**Comment by clokep** [comment]
I just put up a PR to fix this, could you maybe test it out and see if it fixes the issue for you? #3934

Additionally, I think the work around is to explicitly provide the exchange when calling your tasks:
```python
app.send_task('my.project.tasks.my_task', exchange='broadcast_tasks')
```

That seems to be working for me at least!
