### ISSUE TITLE
How to remove results of tasks in redis after read?

### ISSUE THREAD

**Issue by gzcf** [celery/celery#3741]
I integrate Celery to distribute tasks and use Redis as result backend. Now everything works. But after running some tasks, Redis is full of results which have been read. How can I remove these results after reading them.

I want something like this:

```
async_result.get_and_delete()
```

I have googled and looked up documentation for a whole day. Please help me.

**Comment by georgepsarakis** [comment]
If I am not mistaken you can do this:

```python
result = async_result.get()
async_result.backend.delete()
```

**Comment by gzcf** [comment]
Although it says "Forget about (and possibly remove the result of) this task." in [doc](http://docs.celeryproject.org/en/latest/reference/celery.result.html), this does remove results.

Thanks for remind.

**Comment by auvipy** [comment]
lets move this to discussion
