### ISSUE TITLE
time limit not working when using eventlet

### ISSUE THREAD

**Issue by max8899** [celery/celery#3747]
## Checklist

- [x]  ``celery report``
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
project : https://github.com/celery/celery/tree/master/examples/eventlet
start worker: celery worker -l info --concurrency=1 --pool=eventlet

Do some change in celeryconfig.py:
```
broker_url = 'amqp://guest:guest@localhost:5672//'
worker_disable_rate_limits = True
worker_prefetch_multiplier = 1
task_time_limit = 2
task_soft_time_limit = 1
worker_max_tasks_per_child = 100
result_backend = 'redis://localhost:6379/'
result_expires = 30 * 60
```

Try some url use more than 3 seconds to fetch, since in China, I use google
```
$ cd examples/eventlet
$ python
>>> from tasks import urlopen
>>> res = urlopen.delay('http://www.google.com/')
>>> res.state
u'PENDING'
```

the PENDING state takes more than 3 seconds to FAILURE and the worker doesn't reload

## Expected behavior

task fail quickly, and release the worker process

## Actual behavior

takes more time until the socket connection time out reached

**Comment by brechin** [comment]
I made a PR adding soft time limit support for gevent here: https://github.com/celery/celery/pull/3764

**Comment by auvipy** [comment]
will reopen if more consensus arise
