### ISSUE TITLE
Add Python 3.6 to CI

### ISSUE THREAD

**Issue by arcivanov** [celery/celery#3748]
Add Python 3.6 to CI

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/3749

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/3750

**Comment by arcivanov** [comment]
I was about to submit a PR :smile:

**Comment by arcivanov** [comment]
@auvipy shouldn't these be a single commit though?

**Comment by auvipy** [comment]
np problem. I send separate pr in drf and got merged :dagger:  and thanks for reporting! wasn't aware
