### ISSUE TITLE
priority of chord head and body can not be set

### ISSUE THREAD

**Issue by listen-lavender** [celery/celery#3755]
I have a question that priority of chord head and body can not be set, step A is much many than step B,  and both occur in a schedule work, so i hope the step B has a higher priority than step A

@app.task
def A(i, i):
    pass

@app.task
def B(b):
    pass

===run normally
chord((A.s(i, i) for i in xrange(10)), B.s())()

===crash

@app.task
def A():
    pass

@app.task
def B():
    pass

body = B
header = group(A.subtask((i, i)) for i in xrange(10))
header_result = header.apply_async(priority=2)
body.apply_async([header_result.get()], priority=3)

Any help?

**Comment by auvipy** [comment]
ask this type of question to mailing list.
