### ISSUE TITLE
Broadcast messages in Celery 4.0.1 + Django not worked for me

### ISSUE THREAD

**Issue by idreamussr** [celery/celery#3763]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I'm using django 1.8 + Celery 4.0.1 + Kombu 4.0.1 + Redis as broker

from kombu.common import Broadcast
CELERY_QUEUE_BROADCAST = 'broadcast'
CELERY_QUEUES = (Broadcast(queue=CELERY_QUEUE_BROADCAST), )

@task(ignore_result=True, queue=CELERY_QUEUE_BROADCAST)
def broadcast_task():
    print "task runned"

started two workers
celery -A proj worker -Q broadcast

broadcast_task.delay() 
## Expected behavior
tasks are performed by each worker at same time
## Actual behavior
tasks performed by one worker at same time

also i placed my question on SO
http://stackoverflow.com/questions/41639334/broadcast-messages-in-celery-4-x

**Comment by michael-k** [comment]
Duplicate celery/celery#3740?

**Comment by idreamussr** [comment]
Maybe. But it's bad. I hope my fault in incorrect settings.
