### ISSUE TITLE
Tasks intermittently get stuck as reserved even with -Ofair option enabled (Celery 3.1.23)

### ISSUE THREAD

**Issue by akira** [celery/celery#3765]
I am seeing an issue where tasks are becoming reserved even though the settings should prevent this (late ack, -Ofair, and prefetch of 1). This is only happening intermittently, about once a day. Not using any eta or countdown tasks. 

This is causing tasks to line up behind other long running tasks, thereby causing delays. Our system has very long running tasks, so this is problematic. We are also unable to split long running and short running tasks apart, as it is not known ahead of time which one will take long.  

Typing `celery inspect report` returns following (with application specific details removed):

```
 software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.10
                    billiard:3.3.0.23 redis:2.10.5
        platform -> system:Linux arch:64bit imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:redis results:redis://..../

        CELERY_ACKS_LATE: True
        CELERY_SEND_TASK_ERROR_EMAILS: True
        CELERY_DISABLE_RATE_LIMITS: True
        CELERY_ACCEPT_CONTENT: ['pickle', 'json']
        CELERY_IGNORE_RESULT: False
        CELERY_RESULT_DBURI: 'redis://....'
        CELERYD_CONCURRENCY: 8
        CELERY_ROUTES: None
        CELERYD_PREFETCH_MULTIPLIER: 1
        BROKER_URL: 'redis://.../'
        CELERY_RESULT_BACKEND: 'redis://.../'
```
-Ofair is also enabled on the command line.  

## Steps to reproduce

Unable to reproduce this consistently locally, this seems to happen on production. 

I tried upgrading to celery 3.1.25 but did not help. Also tried with --without-gossip --without-heartbeat which did not help either. I am unable to test with 4.0 since this is in prod. 

## Expected behavior

Given the settings above, I would expect to see no reserved tasks. 

## Actual behavior

Tasks are becoming reserved intermittently, causing them to be delayed.

**Comment by georgepsarakis** [comment]
Could you give the exact command that you use to start the workers?

**Comment by akira** [comment]
The command is:

```
/usr/local/bin/celery worker --app=appname.celery -l DEBUG -Q appname_production -c 8 -n appname.%n -Ofair
```

**Comment by georgepsarakis** [comment]
Can you try this please:

```
celery worker --app=appname.celery -l DEBUG -Q appname_production -c 8 -Ofair -n 'appname.%n'
```

**Comment by akira** [comment]
@georgepsarakis Sure, I will try that and report back

**Comment by akira** [comment]
@georgepsarakis using the command above still did not fix the issue. There are still reserved tasks appearing.

**Comment by georgepsarakis** [comment]
@akira since you are using Redis as a broker have you taken the [Caveats](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#caveats) into consideration?
Perhaps your long running tasks exceed the visibility timeout? Although this would result in tasks being processed twice.

Also, perhaps using this [setting](http://docs.celeryproject.org/en/latest/userguide/workers.html#max-tasks-per-child-setting) with a value of 1 may be a workaround, since it won't allow a single worker to run multiple tasks?

**Comment by akira** [comment]
> Perhaps your long running tasks exceed the visibility timeout? Although this would result in tasks being processed twice.

I have verified this occurring with tasks that have not yet executed, so I don't think it's caused by the visibility timeout being exceeded. I can try setting `max-tasks-per-child-setting` to 1 just to see if that help - do you think that would prevent extra tasks from getting reserved in this case? (Although it's not ideal since it may add extra time for spawning, but I can try it).

**Comment by georgepsarakis** [comment]
Not sure, you will have to inspect the logs to see if the tasks are reserved on the same worker which is already busy. If that is the case then yes, this may be a workaround.

See also #2464.

**Comment by akira** [comment]
For more context, I've attached a statsd graph over 24 hours of how we are seeing this problem manifest:
* The top graph is number of tasks executing (count of `celery inspect active`)
* Bottom graph is the reserved tasks (count of `celery inspect reserved`).  

<img width="1252" alt="screen shot 2017-01-18 at 11 05 45 am" src="https://cloud.githubusercontent.com/assets/43946/22078719/e0ee9472-dd6d-11e6-92c6-da3b57c0d0c7.png">

**Comment by AndreLobato** [comment]
Having the same problem (long running tasks, tasks with ETA, stuck in Reserved) but using RabbitMQ broker.
My current worker command is...

**Comment by auvipy** [comment]
what's it's status on latest master?

**Comment by akira** [comment]
This is on Celery 3.x branch, not 4.x.

**Comment by auvipy** [comment]
closing for now. verify after 4.2 release

**Comment by KevinYang21** [comment]
Hi @auvipy, is this verified and turned out to be not an issue anymore?

**Comment by auvipy** [comment]
I would request you to test yoursleves and report here
