### ISSUE TITLE
`autoreload` worker option is removed from celery worker options, but  presented in documentations

### ISSUE THREAD

**Issue by sgrigoriev** [celery/celery#3770]
Hello,
this issue about one distinguishing feature between celery code and docs, 4.0.x version. `autoreload` option now removed from worker options - https://github.com/celery/celery/commit/41873498eff4b5eac874fc22cef79e4043dd3671, but docs about worker blueprints contain info about [Worker blueprint attr named autoreloader ](http://docs.celeryproject.org/en/latest/userguide/extending.html#autoreloader), based on `autoreload` feature. Is documentation correct or not?

**Comment by sgrigoriev** [comment]
Can anybody answer me?

**Comment by sgrigoriev** [comment]
Up.

**Comment by auvipy** [comment]
didn't find any code on master. feel free to check latest code and send a pr to improve the doc if needed
