### ISSUE TITLE
Some Old Style Configuration Variable Names are Incorrect in Docs

### ISSUE THREAD

**Issue by pnovotnak** [celery/celery#3772]
## Checklist

- [✓] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [✓] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Follow the Django tutorial, then visit the configuration / defaults documentation page and attempt to use some of the old style configuration settings.

Using the old style setting `CELERY_DEFAULT_QUEUE` has no effect while `CELERY_TASK_DEFAULT_QUEUE` works as intended. I suppose this is probably the same for many or all of the `task_.*` variables, though I have not tested them.

```python
# proj/proj/celery.py
...
# Using a string here means the worker don't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings', namespace='CELERY')
...
```

## Expected behavior

One should be able to configure the app by referring to the documentation.

## Actual behavior

Configuration docs are broken.

**Comment by pnovotnak** [comment]
Forgot to actually include `celery -A proj report` ¯\_(ツ)_/¯ [celery-report.txt](https://github.com/celery/celery/files/717747/celery-report.txt)

**Comment by pnovotnak** [comment]
Also broken;

* CELERYD_PREFETCH_MULTIPLIER -> CELERY_WORKER_PREFETCH_MULTIPLIER

**Comment by thedrow** [comment]
@auvipy Is this fixed?

**Comment by marcomayer** [comment]
@thedrow @auvipy :This is still wrong on http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_default_queue and it just cost me half a day of work to figure it out. Is there any documentation or maybe a README or some other way to actually find out the correct configuration values that work?

**Comment by thedrow** [comment]
@marcomayer That document should be kept up to date.
If you find anything wrong, please issue a new pull request fixing the problem.

**Comment by ckm2k1** [comment]
@thedrow The prefixes for settings in the docs don't seem to correspond to what Celery 4.1.0 expects. 
Ex: 
Bad: `CELERY_TASK_ALWAYS_EAGER = True`
Good: `CELERY_ALWAYS_EAGER = True`

Like @marcomayer, this took some time to figure out and is quite frustrating to debug unless you step through Celery's own code and watch _very carefully_ over the config values.

Finally, I don't think that asking people to correct your docs is the solution here. It's not a typo or one wrong setting. All the prefixes like TASK or BROKER, for example, described in the docs are systematically wrong and require guessing the correct naming.

**Comment by auvipy** [comment]
open source projects rely on it's contributors. so feel free
