### ISSUE TITLE
Whereis 'broker_transport' documentation

### ISSUE THREAD

**Issue by luzfcb** [celery/celery#3775]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] Celery 4.x version

## Steps to reproduce

search `broker_transport` docs on settings list:

http://docs.celeryproject.org/en/latest/userguide/configuration.html#broker-settings

## Expected behavior
have `broker_transport` documentation explaining what the expected values and other related informations

## Actual behavior

There is no documentation explaining the purpose of `broker_transport` settings

**Comment by georgepsarakis** [comment]
Some options are deprecated, as you can also see [here](https://github.com/celery/celery/blob/master/docs/conf.py#L58) in the comment, and have been replace by `BROKER_URL`.
