### ISSUE TITLE
celery.events.state.State Pickling and Unpickling problem.

### ISSUE THREAD

**Issue by destinydesigner** [celery/celery#3776]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.6
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: u'amqp://guest:********@localhost:5672//'
include: [u'celery_app.helloworld']

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1, run `flower -A celery_app --broker=amqp://guest:guest@localhost:5672// --persistent=True`
2, create a task as `ping.apply_async((), link=say_hello.s())` which `ping` and `say_hello` are both tasks.
3, as the task is already sent to work, restart flower.

## Expected behavior
Restart flower successfully.
## Actual behavior
AttributeError: (**"'NoneType' object has no attribute 'tasks'"**, <function _depickle_task at 0x7fd6362e1050>, (<class 'celery.events.state.Task'>, {u'received': 1484914379.697065, u'result': u"'pong'", **u'children': [u'ac91b015-32f3-485d-b508-3340692c0d16']**, u'uuid': u'5569fb0a-d30a-4785-aaac-97e1b4b557fa', u'clock': 3944, u'exchange': None, u'routing_key': None, u'parent_id': None, u'state': u'SUCCESS', u'eta': None, u'kwargs': u'{}', u'sent': None, u'args': u'()', u'parent': None, u'root_id': u'5569fb0a-d30a-4785-aaac-97e1b4b557fa', u'started': 1484914380.438278, u'timestamp': 1484914380.458552, u'expires': None, u'worker': <Worker: celery@fang-virtual-machine (ONLINE clock:3947), u'rejected': None, u'name': u'celery_app.celery.ping', u'retries': 0, u'exception': None, u'failed': None, u'succeeded': 1484914380.458552, u'revoked': None, u'traceback': None, u'client': None, u'retried': None, u'runtime': 0.01600403303746134, u'root': u'5569fb0a-d30a-4785-aaac-97e1b4b557fa'}))

After checking the source, I found when flower using shelve to pickle and unpickle the `celery.events.state.Task` object, the **cluster_state** of the Task is not handled by __reduce__.
So, after pickling and unpickling from the file, the cluster_state is None.
```
        self.children = WeakSet(                                                                                              
            self.cluster_state.tasks.get(task_id)                                                                             
            for task_id in children or ()                                                                                     
            if task_id in self.cluster_state.tasks                                                                            
        )   
```
When it's trying to create a Task object with non-empty children, the exception will be raise.
If I add the `cluster_state` into _fields, the cluster_state will be not empty, but another exception will be raised in celery.events.state.State.rebuild_taskheap.

I don't understand why the `cluster_state` is not included in the _fields. Is that because of threading lock? And any suggestion to solve the problem?

**Comment by PaKZer0** [comment]
I have experienced the same problem with Flower, the same stacktrace, which renders persistence completely useless =P

**Comment by gidantribal** [comment]
Same issue here...

**Comment by gidantribal** [comment]
persistence is broken...

**Comment by kantorv** [comment]
bump

**Comment by kantorv** [comment]
seems like specifying `CELERY_RESULT_SERIALIZER="pickle"` is solving an issue (checked on amqp & redis backends)

**Comment by bohea** [comment]
Same issue , 
shelve.open(the db)
return an exception:
 'NoneType' object has no attribute 'tasks'

**Comment by auvipy** [comment]
please report again if this exists on top of master
