### ISSUE TITLE
Can not import Celery module error .....

### ISSUE THREAD

**Issue by manishhub9** [celery/celery#3786]
First i followed all the instructions provided in documents. I copy cleryd file and paste in init.d celeryd and write a /etc/default/celeryd file . I have a simple python project folder which include

test_celery 
                |
                celery.py
                tasks.py
                 __init.py__
Here is celery.py file:-
```
from __future__ import absolute_import
import os
from celery import Celery
from kombu import Queue, Exchange
from celery.schedules import crontab
import datetime

app = Celery('test_celery',
             broker='amqp://jimmy:jimmy123@localhost/jimmy_v_host',
             backend='rpc://',
             include=['test_celery.tasks'])
# Optional configuration, see the application user guide.
app.conf.update(
    result_expires=3600,
)

if __name__ == '__main__':
    app.start()
```
And here is tasks.py:-
```

from __future__ import absolute_import
from test_celery.celery import app
import time
from kombu import Queue, Exchange
from celery.schedules import crontab
import datetime


app.conf.beat_schedule = {
	'planner_1': {
		'task': 'test_celery.tasks.printTask',
		'schedule': crontab(minute='*/1'),
	},
}


@app.task
def longtime_add(x, y):
	print 'long time task begins'
	# sleep 5 seconds
	time.sleep(5)
	print 'long time task finished'
	return x + y

@app.task
def printTask():
	print 'Hello i am running'
	time=str(datetime.datetime.now())
	file=open('/home/hub9/mycelery/data.log','ab')
	file.write(time)
	file.close()
```
And last __init.py__:-
```
from __future__ import absolute_import, unicode_literals

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from test_celery.celery import app as celery_app

__all__ = ['celery_app']
```

Using command sudo service celeryd start , i am able to start worker but when i add my project to celeryd config file i am getting error that can not import name Celery.

I tried some other code but unable to start celeryd . Please give me a hint what i am doing wrong.
Thanks for your valuable time.

**Comment by georgepsarakis** [comment]
You have probably masked the installed package with the module `celery.py` in your `test_celery` project folder.

Check also this StackOverflow [post](http://stackoverflow.com/questions/19926750/django-importerror-cannot-import-name-celery-possible-circular-import).

Also, if I am not mistaken, since this is not a confirmed bug and you are only requesting help, you should prefer other contact options (see 2): http://docs.celeryproject.org/en/latest/contributing.html#other-bugs

**Comment by manishhub9** [comment]
I am again getting different error after change celery.py to celery_app.py.
ImportError: No module named test_celery.celery_app

**Comment by manishhub9** [comment]
My config celeryd for project is:

Project Location: /home/hub9/mycelery/test_celery

Project File: celery_app.py,tasks.py,__init__.py

My local config file is:
# Where to chdir at start. path to folder containing task
CELERYD_CHDIR="/home/hub9/mycelery/test_celery"
# App instance to use
# comment out this line if you don't use an app
CELERY_APP = "celery_app:app"
# or fully qualified:
#CELERY_APP="test_celery.tasks:app"

How can i run my project

**Comment by harshgangwar** [comment]
@manishhub9 Did you get the answer? and what was the solution?

**Comment by IhorMar** [comment]
Hello. I have that same problem. And what is the solution to this error?
