### ISSUE TITLE
Unable to revoke a 'STARTED' task under celery 3.1 / redis

### ISSUE THREAD

**Issue by rhyw** [celery/celery#3792]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

## Steps to reproduce
[root@worker-01 ~]# celery -A myapp report

software -> celery:3.1.11 (Cipater) kombu:3.0.24 py:2.7.5
            billiard:3.3.0.20 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:db+postgresql://dbuser:passwd@host/name

BROKER_TRANSPORT_OPTIONS: {
    'visibility_timeout': 86400}
BROKER_URL: 'redis://myserver:6379/0'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_ENABLE_UTC: True
CELERY_IMPORTS: 
    ('my.tasks',)
CELERY_TRACK_STARTED: True
CELERY_TIMEZONE: 'America/Chicago'
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: 'db+postgresql://dbuser/dbpassed@host/name'
CELERY_RESULT_SERIALIZER: 'json'

I've got a long running task in celery which for some reason hangs on "STARTED" for a few days and is no longer being proceeded. 

Now that I'd like to revoke that task since my others tasks in the queue is blocked by this.
While I tried below:

`from tasks.models import Task`
`from celery.task.control import revoke`
`task_meta_id = Task.objects.get(id=1103).meta_id`
`revoke(task_meta_id, terminate=True, signal='SIGKILL')`

After this, I see the task is still in "STARTED" and didn't seem to get revoked.

The worker is on while I tried to revoke the task.
What am I doing wrong? btw is there an alternative approach to revoke a long-hanging "STARTED" task?

**Comment by ask** [comment]
Are you using

**Comment by rhyw** [comment]
I'm not entirely sure what the 'prefork pool' in this context means, I'm following the 3.1 worker's guide and the [daemonizing tutorial].(http://docs.celeryproject.org/en/3.1/tutorials/daemonizing.html#usage-systemdguide) under a rhel-7 server.

I can provide the exact command we ran on our server if it's needed.

**Comment by rhyw** [comment]
Closing as it had been pending for months and I'm unable to reproduce..
