### ISSUE TITLE
autoretry_for doesn't log exceptions?

### ISSUE THREAD

**Issue by mindojo-victor** [celery/celery#3794]
https://github.com/celery/celery/blob/c5793740685fa1376b2d06f3678c872ca175ed6f/celery/app/base.py#L469

```
            if autoretry_for and not hasattr(task, '_orig_run'):

                @wraps(task.run)
                def run(*args, **kwargs):
                    try:
                        return task._orig_run(*args, **kwargs)
                    except autoretry_for as exc:
                        raise task.retry(exc=exc, **retry_kwargs)

                task._orig_run, task.run = task.run, run
```

Do I understand correctly that when an exception occurs it's not logged anywhere?
And than `MaxRetriesExceededError` occurs and we never find out what was the problem?

**Comment by mindojo-victor** [comment]
I see in the code 
```python
        if max_retries is not None and retries > max_retries:
            if exc:
                # On Py3: will augment any current exception with
                # the exc' argument provided (raise exc from orig)
                raise_with_context(exc)
            raise self.MaxRetriesExceededError(
                "Can't retry {0}[{1}] args:{2} kwargs:{3}".format(
                    self.name, request.id, S.args, S.kwargs))
```
So, looks like in case of failure `MaxRetriesExceededError` is not raised but the task exception is reraised. But the last try exception may differ from the previous attempts.

I've seen people recommending to use logging errors in `app.Task.on_retry` -- but that's additional work.

Is this an oversight? Or intentional?

**Comment by ask** [comment]
The worker logs that a task was retried:
https://github.com/celery/celery/blob/master/celery/app/trace.py#L54-L98

For a task that retries two times then fails with maxretries you'd except the states:

```
RETRY
RETRY
FAILED
```

all of which will be logged with exception information.

**Comment by mindojo-victor** [comment]
Thanks for the clarifications.
