### ISSUE TITLE
remove periodic task from schedule

### ISSUE THREAD

**Issue by freedomrezo** [celery/celery#3809]
Hello,

I've got a problem and i haven't found its solution in your documentation.

I'm dynamically adding periodic tasks from our program, like it is shown in your documentation example.
But i need to change the starting period of tasks or delete unused tasks.

How can i do it inside the python program?

```
from celery import Celery
from celery.schedules import crontab
app = Celery()
@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    # Calls test('hello') every 10 seconds.
    sender.add_periodic_task(10.0, test.s('hello'), name='add every 10')
    # Calls test('world') every 30 seconds
    sender.add_periodic_task(30.0, test.s('world'), expires=10)
    # Executes every Monday morning at 7:30 a.m.
    sender.add_periodic_task(
        crontab(hour=7, minute=30, day_of_week=1),
        test.s('Happy Mondays!'),
    )
@app.task
def test(arg):
    print(arg)
```

**Comment by auvipy** [comment]
this is possibly fixed in newer release. beside it's better to ask your questions in irc or mailing list
