### ISSUE TITLE
Celery 4.0.2 more than 4x slower than Celery 3.1.25

### ISSUE THREAD

**Issue by OskarPersson** [celery/celery#3814]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.13
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis:///

BROKER_URL: 'amqp://guest:********@localhost:5672//'
CELERY_RESULT_BACKEND: 'redis:///'
```

**and**

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.13
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis:///

broker_url: u'amqp://guest:********@localhost:5672//'
result_backend: u'redis:///'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Run the following script with Celery 3.1.25 and 4.0.2 (or master)

```
from celery import Celery, chain

app = Celery('tasks', broker='amqp://guest@localhost//', backend='redis://')

@app.task
def add(x, y):
    return x + y

if __name__ == '__main__':
    print chain(
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
        add.si(10, 20), add.si(10, 20), add.si(10, 20),
    )().get()
```

## Expected behavior
Running the script with Celery 4.0.2 should be at least as fast as running it with Celery 3.1.25.

## Actual behavior
Running the script with Celery 3.1.25 takes ~700-900ms while Celery 4.0.2 takes ~4-8s. The tasks themselves complete in about the same time on both versions, it just seems that starting each task is slower.

**Comment by pymonger** [comment]
Seeing the same thing as well.

**Comment by matteius** [comment]
Anyone found a workaround to the task slowness in Celery 4?  Is downgrading the only fix presently?

**Comment by pymonger** [comment]
Done: https://github.jpl.nasa.gov/aria-hysds/ariamh/commit/2de583b0cf34fd52b3c0a3608e89d976e9fe9a3d.
Testing in my dev cluster.

**Comment by thedrow** [comment]
Can you guys please check again with the latest versions of all our dependencies?

**Comment by OskarPersson** [comment]
This is now solved according to my tests, closing this

**Comment by matteius** [comment]
I also concur that the issue was resolved on the latest versions of the dependencies.
