### ISSUE TITLE
Celery 4 buffers tasks before execution 

### ISSUE THREAD

**Issue by sheny35** [celery/celery#3822]
I have a service using Celery 4.0.2 to dispatch tasks to workers. I observed that, periodically, Celery workers hang altogether for a while without doing any tasks, and then suddenly, they revive and resume execution again.  Looks like Celery 4.0.2 buffers those tasks and release to workers later.
Celery 3 (I tried 3.1.23 and 3.1.25) don't have those problems and tasks are processed smoothly & evenly.
I use Python Celery module. The command is something like "-A module_name --loglevel=info -n str(uuid4())[:8] -P solo --autoscale=16,2";
Some other configs are like: 
BROKER_CONNECTION_TIMEOUT=3600 * 24,
    BROKER_CONNECTION_MAX_RETRIES=None,
    CELERY_ACCEPT_CONTENT=['application/json'],
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERY_ACKS_LATE=False

Some screenshots are as follows;
Celery 4
<img width="950" alt="screen shot 2017-02-09 at 10 19 21 pm" src="https://cloud.githubusercontent.com/assets/11428198/22787304/c75dcffe-ef16-11e6-966c-1010c738ae2b.png">
Celery 3.0.25
<img width="961" alt="screen shot 2017-02-09 at 10 18 43 pm" src="https://cloud.githubusercontent.com/assets/11428198/22787353/f1fb3756-ef16-11e6-9342-1471424c4c78.png">

**Comment by OskarPersson** [comment]
This sound similar to what I'm seeing in #3814.

By the way, what is that lovely dashboard?

**Comment by sheny35** [comment]
@OskarPersson It's Grafana; :)

**Comment by matteius** [comment]
@sheny35  Are you attributing the bug of the task consumption slowdown in celery4 to a new task buffering technique/technology, or is that your way of describing the graph?  I ran a test earlier that showed celery3 and celery4 to perform the same at task enqueuing but that celery4 performs worse for task consumption.

celery 3 consuming 100 tasks from a single worker
![celery3-consume](https://cloud.githubusercontent.com/assets/479892/24021533/dc321508-0a77-11e7-96ab-0d32df4ccda6.PNG)

celery 4 consuming 100 tasks from a single worker
![celery4-consume](https://cloud.githubusercontent.com/assets/479892/24021534/dc36e542-0a77-11e7-8409-b46b948e857c.PNG)
 
I had even run the settings upgrade command to make sure that the application settings were still proper from 3 --> 4.

**Comment by sheny35** [comment]
@matteius Just my way of describing the graphs. They do look like some kind of "buffering", but you pointed out, more likely to be caused by Celery 4 consumption bugs. Hope someone could find a solution.

**Comment by thedrow** [comment]
This is fixed in https://github.com/celery/py-amqp/pull/144
