### ISSUE TITLE
Externally handled task

### ISSUE THREAD

**Issue by Korijn** [celery/celery#3823]
I'm wondering if it's possible to have a task in a chain, that has its output produced by an external system. For example:

```python
from celery.exceptions import Ignore

@app.task
def external_process():
    results = get_results()  # check if the external system sent us results yet
    
    if not results:
        # tell external system to get started
        requests.post("https://api.external.com/do_something")

        # don't continue
        raise Ignore()  # or should I let it fail?
    
    # if the external system sent us the results, pass them on to the next task
    return results
```

What I need to know is if I can put this task in the middle of a chain, and programmatically tell the chain to resume when the external system sends us the data. So:

* is my understanding correct that `raise Ignore()` will effectively put the chain in limbo, where it can sit around to resume later?
* can I use the `task_id` returned by `apply_async()` to resume (or retry?) this task programmatically?

**Comment by auvipy** [comment]
@georgepsarakis @thedrow any thoughts?

**Comment by georgepsarakis** [comment]
@Korijn I guess you could retry the specific task at regular intervals. See [here](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.retry) for details on how to execute this from within the task code.
