### ISSUE TITLE
"ImportError: No module named app" when trying to start celery worker

### ISSUE THREAD

**Issue by matchifang** [celery/celery#3824]
I am using flask server and follow [this example][1] trying to run celery and redis. 
First, I started the redis server, then I try to start the celery worker and got this error:

>     Traceback (most recent call last):
>       File "/Library/Frameworks/Python.framework/Versions/2.7/bin/celery", line 11, in <module>
>         sys.exit(main())
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
>         main()
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
>         cmd.execute_from_commandline(argv)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
>         super(CeleryCommand, self).execute_from_commandline(argv)))
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
>         argv = self.setup_app_from_commandline(argv)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
>         self.app = self.find_app(app)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
>         return find_app(app, symbol_by_name=self.symbol_by_name)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/app/utils.py", line 235, in find_app
>         sym = symbol_by_name(app, imp=imp)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/bin/base.py", line 492, in symbol_by_name
>         return symbol_by_name(name, imp=imp)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
>         module = imp(module_name, package=package, **kwargs)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
>         return imp(module, package=package)
>       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>         __import__(name)
>     ImportError: No module named app

This is my code in the flask server:

```
    app = Flask(__name__)
    app.config["CACHE_TYPE"] = "null"
    
    
    app.config['CELERY_BROKER_URL'] = 'redis://localhost:6379/0'
    app.config['CELERY_RESULT_BACKEND'] = 'redis://localhost:6379/0'
    
    celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    
    
    @celery.task(bind=True)
    def long_task(self):
        print("long_task")
        """Background task that runs a long function with progress reports."""
        verb = ['Starting up', 'Booting', 'Repairing', 'Loading', 'Checking']
        adjective = ['master', 'radiant', 'silent', 'harmonic', 'fast']
        noun = ['solar array', 'particle reshaper', 'cosmic ray', 'orbiter', 'bit']
        message = ''
        total = random.randint(10, 50)
        for i in range(total):
            if not message or random.random() < 0.25:
                message = '{0} {1} {2}...'.format(random.choice(verb),
                                                  random.choice(adjective),
                                                  random.choice(noun))
            self.update_state(state='PROGRESS',
                              meta={'current': i, 'total': total,
                                    'status': message})
            time.sleep(1)
        return {'current': 100, 'total': 100, 'status': 'Task completed!',
                'result': 42}
    
    @app.route('/longtask', methods=['POST'])
    def longtask():
        task = long_task.delay()
        return jsonify({}), 202, {'Location': url_for('taskstatus',
                                                      task_id=task.id)}
    
    @app.route('/status/<task_id>')
    def taskstatus(task_id):
        task = long_task.AsyncResult(task_id)
        if task.state == 'PENDING':
            # job did not start yet
            response = {
                'state': task.state,
                'current': 0,
                'total': 1,
                'status': 'Pending...'
            }
        elif task.state != 'FAILURE':
            response = {
                'state': task.state,
                'current': task.info.get('current', 0),
                'total': task.info.get('total', 1),
                'status': task.info.get('status', '')
            }
            if 'result' in task.info:
                response['result'] = task.info['result']
        else:
            # something went wrong in the background job
            response = {
                'state': task.state,
                'current': 1,
                'total': 1,
                'status': str(task.info),  # this is the exception raised
            }
        return jsonify(response)

```
Any comment or suggestion is greatly appreciated. Thank you.

  [1]: https://blog.miguelgrinberg.com/post/using-celery-with-flask

**Comment by georgepsarakis** [comment]
Have you perhaps looked at the official Flask documentation [example](http://flask.pocoo.org/docs/0.12/patterns/celery/)?

**Comment by ThomasCr** [comment]
any way to get this fixed?
