### ISSUE TITLE
How to change celerybeat.pid file path?

### ISSUE THREAD

**Issue by flyalex** [celery/celery#3828]
Hi!
I use Django+Redis+Celery.
My linux user which I run on production doesn't have write permissions and can't create new file in project' folder.

How can I change path of celerybeat.pid file? as --pidfile is deprecated?

CELERYBEAT_PID_FILE = "/var/run/celery/celerybeat.pid" - seems doesnot work as error in logs same:
celery.platforms.LockFailed: [Errno 13] Permission denied: '/webapps/path/to/project/celerybeat.pid'

Thanks.

**Comment by georgepsarakis** [comment]
`--pidfile` does not seem to be deprecated; if you run `celery beat --help` you will see it in the command options. Since you do not have write permissions, you should use `/tmp` as a base directory for the created files for: PID, logs and the local database file (named celerybeat-schedule by default).

**Comment by flyalex** [comment]
Yes, I tried it. Jut now made several more attempts.

command=/path/to/project/bin/celery beat -A celeryapp --loglevel=INFO --pidfile="/var/run/celery/celerybeat.pid"

Syntax is correct?

Cleared logs. Log says the same.

**Comment by georgepsarakis** [comment]
Try this (I am guessing that you are using supervisor):

```
command=/path/to/project/bin/celery beat -A celeryapp --loglevel=INFO --pidfile="/tmp/celerybeat.pid"
```

**Comment by flyalex** [comment]
Same result.
It's interesting that when I start beat on my local machine without --pidfile="/tmp/celerybeat.pid" I can see how file being created and then removed after turning of, but If I switch with that param I can't see that file appeared - folder tmp is empty, but beat working well anyway.

**Comment by georgepsarakis** [comment]
Are you sure it is passed correctly? Please check the output of `ps uxa` on your machine to see if `--pidfile` is included in the running command.

**Comment by flyalex** [comment]
It's not included. Can see the process, but there is no --pidfile

**Comment by georgepsarakis** [comment]
So it is an issue with supervisor then?

**Comment by flyalex** [comment]
It's on my local computer without supervisor.
What can be wrong with passing --pidfile to the command?

**Comment by georgepsarakis** [comment]
Can you try `ps -ef` too?

**Comment by flyalex** [comment]
This way I see it passed as it should be.

**Comment by georgepsarakis** [comment]
It should work then, the PID should be written to that file.

**Comment by flyalex** [comment]
Still same error on production.(

**Comment by georgepsarakis** [comment]
@flyalex I tested the command and its options, `--pidfile` is not used and a PID file is not created if you do not specify the boolean `--detach` as well. Since you are using supervisord you do not need to start celerybeat as a background process, so the command in your first comment should work.

Can you please describe exactly how you are starting the process and the OS/environment details that you are getting the error?

**Comment by flyalex** [comment]
Solved by changing linux user permissions.

**Comment by bkovacev** [comment]
@flyalex Could you tell me what permissions have you added and for what user?

**Comment by wooooodward** [comment]
@bkovacev 

First from the linux shell run `whoami` to find out your current username. In my case wooooodward

```
cd /var/run/
sudo mkdir celery
cd
chown -R wooooodward:wooooodward /var/run/celery/
```

Then you can use the following as your command

`command=/path/to/project/bin/celery beat -A celeryapp --loglevel=INFO --pidfile="/var/run/celery/celerybeat.pid"`

**Comment by aniltweak** [comment]
i uploded my django project in server.
everything running fine in local host
but after deploying in server i am not receiving message (not showing any error)
and iam having celery beat fatal error
and project name wsgi error

**Comment by umar13893** [comment]
Hi @georgepsarakis, 
I have tried one of your solution and added the --pidfile to command  in my supervisor config file and  permission error is gone for PID file but now I am getting permission error for celerybeat-schedule.dat file. How can I fix that?

Thanks!

**Comment by engineervix** [comment]
> Hi @georgepsarakis,
> I have tried one of your solution and added the --pidfile to command in my supervisor config file and permission error is gone for PID file but now I am getting permission error for celerybeat-schedule.dat file. How can I fix that?
> 
> Thanks!

I struggled with this for a while. The solution lies in **setting a custom location for the schedule database**.

I created a new user called **celery**, as explained in [this article](https://www.willandskill.se/en/celery-4-with-django-on-ubuntu-18-04/). From to the article, this was done as follows

```sh
sudo useradd celery -d /home/celery -b /bin/bash
```
However, I discovered that the command didn't create a Home directory for the **celery** user, so I did the following in addition:

```sh
sudo mkhomedir_helper celery
```
Then, I specified a custom location for the schedule database, as per [celery docs](https://docs.celeryproject.org/en/stable/reference/cli.html#cmdoption-celery-beat-s). Here's my `celerybeat.service` file:

```
[Unit]
Description=Celery Beat Service for Project X
After=network.target

[Service]
Type=simple
User=celery
Group=celery
EnvironmentFile=/etc/conf.d/celery
WorkingDirectory=/home/me/projects/project_x
ExecStart=/bin/sh -c '${CELERY_BIN} -A ${CELERY_APP} beat  \
    --pidfile=${CELERYBEAT_PID_FILE} \
    --logfile=${CELERYBEAT_LOG_FILE} \
    --loglevel=${CELERYD_LOG_LEVEL} \
    --schedule=/home/celery/celerybeat-schedule'

[Install]
WantedBy=multi-user.target
```
Hope this helps.
