### ISSUE TITLE
How to choose result queue for celery task?

### ISSUE THREAD

**Issue by InputError** [celery/celery#3837]
I am using version 3.1.24

Here is my celery config:
```python
BROKER_TRANSPORT='amqp',
CELERY_RESULT_BACKEND='rpc://',
```

I am sending task to execute this way:
```python
result = my_function.apply_async(('arguments here',), queue='queue_123')
```

Celery works as expected, I see this tasks in "queue_123".

Now I need to get all results of execution to queue "my_result_queue". How can I do it?

Celery now creates new queue with name like "19b7013a-a077-3d2a-b60a-d57c51d5d30c" and inserts results to it. I need to fix this behavior and insert results to queue with specified name.

I need something like this:
```python
result = my_function.apply_async(('arguments here',), queue='queue_123', results_queue='my_result_queue')
```

**Comment by OskarPersson** [comment]
I think `reply_to` is what you want

    result = my_function.apply_async(('arguments here',), queue='queue_123', reply_to='my_result_queue')

**Comment by InputError** [comment]
@OskarPersson , thanks a lot for your idea, I tested it now, but it don't works, celery show me same behavior as described in first post

**Comment by georgepsarakis** [comment]
[reply_to](https://github.com/celery/celery/blob/master/celery/worker/request.py#L157) is a message property. Did you try specifying it when defining the task:

```
@app.task(reply_to='result_queue_123)
```

**Comment by InputError** [comment]
@georgepsarakis thanks a lot, I did it, but got same result - celery still creates new queue and insert result to it

**Comment by InputError** [comment]
Also I noticed if type:
```python
result.backend.binding.routing_key
```
I can see this result:
`'3a661393-4713-33f0-b54e-0449e07ef792'
`

this is endpoint queue name, celery uses it. maybe this information helps to to get what's going on.

**Comment by InputError** [comment]
I prepared example to reproduce the error.

celery_app.py:
```python
from celery import Celery
from kombu import Exchange, Queue

app = Celery('worker')

app.conf.update(
    CELERY_ROUTES={
        'my_worker.test_func': {'queue': 'main_check'},
    },
    BROKER_TRANSPORT='amqp',
    CELERY_RESULT_BACKEND='rpc://',
    CELERY_RESULT_PERSISTENT=True,
    # CELERY_DEFAULT_DELIVERY_MODE='persistent',
    # CELERY_RESULT_EXCHANGE='export_task',
    CELERYD_CONCURRENCY=10,
    CELERYD_MAX_TASKS_PER_CHILD=3,
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERY_ACCEPT_CONTENT=['json'],

    CELERY_QUEUES=(
        Queue('main_check', Exchange('main_check', type='direct'), routing_key='main_check'),
    ),
)
```


my_worker.py:
```python
from celery_app import app


@app.task(reply_to='export_task')
def test_func():
    return "here is result of task"
```


starting celery:
`python -m celery -A my_worker worker --loglevel=info`

then in python debug console doing:
```python
from my_worker import *
result = test_func.delay()
result.result
```

and see result:
`'here is result of task'`

task finished, but result of execution I see not in queue "export_task", but in queue with name:
```
result.backend.binding.routing_key
Out[7]: 
'd5587446-0149-3133-a3ed-d9a297d52a96'
```

have you any ideas guys?

**Comment by InputError** [comment]
#3848

**Comment by cibinjohn** [comment]
@InputError 

The above steps worked for me when I created a Queue(say, "results_queue") manually using the RabbitMQ UI.   It can be done programatically too... I guess, the program checks if the specified queue exists first, save it in a different queue with a random name if it does not exist.
