### ISSUE TITLE
Celery chain with single step not sent to queue/workers and executed in main process

### ISSUE THREAD

**Issue by DanBuchan** [celery/celery#3841]
I'm building a moderately sophisticated django application which at runtime it constructs celery chains on the fly and executes them. These chains can have arbitrary number of subtasks which is determined at runtime. 

Essentially I do something like  this in the django application:
```python
tchain = construct_chain_string(steps, request_contents, s.UUID, job_priority)
exec(tchain)
```
`construct_chain_string()` is a method which takes some parameterisation and returns a string which is a valid celery chain and then the `exec()` call executes that string.

In the case where the chain has two or more steps the string returned will look something like
```python
chain(
    task_runner.subtask(
        ('ID', 0, 1, 1, 2,  'step1', [], {}, '', {}), immutable=True, queue='localhost'),
    task_runner.subtask(
        ('ID', 1, 2, 2, 2, 'step2', [], {}, '', {}), immutable=True, queue='localhost'),
      )()
```
Here my method is called `task_runner()` which takes a variety of parameters. As best as I can see this is a valid chain and when the `exec()` is called the tasks are pushed to the queue and consumed by the workers listening on the queue named "localhost".

However I have instances where there is only 1 subtask in the chain and so my chain string looks like
```python
chain(
    task_runner.subtask(
        ('ID', 0, 1, 1, 1, 'step1', [], {}, '', {}), immutable=True, queue='localhost'),
      )()
```
Once again this looks like a valid chain but when `exec()` is called the tasks are not sent to the queue and not consumed by the workers. Instead the `task_runner()` method just executes (succesfully) in the main thread of the Django process.

I note that if I change the string to 
```python
chain(
    task_runner.subtask(
        ('ID', 0, 1, 1, 1, 'step1', [], {}, '', {}), immutable=True, queue='localhost'),
      ).apply_async()
```
Then this does get sent to the workers and executes and completes as expect

Is this is a bug or am I misunderstanding the difference between `chain()()` and `chain().apply_async()`?

Celery report attached:
[celery_report.txt](https://github.com/celery/celery/files/777368/celery_report.txt)

**Comment by auvipy** [comment]
should be fixed on master
