### ISSUE TITLE
Loader still references djcelery

### ISSUE THREAD

**Issue by radiac** [celery/celery#3843]
This is causing problems under certain circumstances in the latest version of Celery 4. The offending code exists in the `master` branch of Celery.

The loader still references `djcelery`:

* https://github.com/celery/celery/blob/master/celery/loaders/__init__.py#L15

This has caused several obscure errors for me, but this seems to be a reliable way to recreate the problem when added to the relevant part of a django project's `celery.py`:

```
app.autodiscover_tasks()
from celery.task.control import inspect
inspect()```

**Comment by auvipy** [comment]
isn't it possible to override ?
