### ISSUE TITLE
need to register task for __call__

### ISSUE THREAD

**Issue by cp2587** [celery/celery#3844]
Hello,

For custom Task class that are not registered with app.register_task, it seems you cannot call the task with the __call__ method (like `task(*args, **kwargs)`). It fails with the following trace
```
File "./celery/app/task.py", line 967, in push_request
self.request_stack.push(Context(*args, **kwargs))
AttributeError: 'NoneType' object has no attribute 'push'
```
Is that normal ? Does this mean you always have to call app.register_task even if you don't plan to call your task with delay or apply_async ?

**Comment by georgepsarakis** [comment]
Yes, I think you must, see the [Changelog](https://github.com/celery/celery/blob/master/Changelog#L82).

**Comment by georgepsarakis** [comment]
You could however override the `__call__` method in your custom task class:

```
class MyCustomTask(Task):
    def run(*args, **kwargs):
        print args, kwargs
    
    def __call__(*args, **kwargs):
        if self._app is None:
            return self.run(*args, **kwargs)
        else:
            return super(MyCustomTask, self).__call__(*args, **kwargs)
```
