### ISSUE TITLE
Deleting the beat schedule db does not cause beat to forget its schedule

### ISSUE THREAD

**Issue by thecardcheat** [celery/celery#3854]
I have come to this issue after a thorough exploration [asked on SO](http://stackoverflow.com/questions/42322486/celery-beat-schedule-schedule-to-run-on-load-then-on-interval).

The issue I have been lead to is that deleting the beat schedule does not cause the schedule to be forgotten. If I schedule a task to run every hour for the first time and start beat, the task is en-queued. I subsequently can not force the schedule to "reset" a.k.a. delete the record of last runs to have that task run again and restart the interval when I choose.

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.6
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

beat_schedule: {
    'task-in-question': {   'schedule': 3600.0,
                                 'task': 'app.task_in_question'}}

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. Create a `beat_schedule` with a task and start the project worker/beat. The task will run.
2. Stop the celery worker/beat.
3. Delete the beat schedule database file (`celerybeat-schedule` by default).
4. Restart the worker/beat. The task will not run until the task schedule interval from the time beat was restarted.

## Expected behavior

From the documentation: "Beat needs to store the last run times of the tasks in a local database file (named celerybeat-schedule by default), so it needs access to write in the current directory, or alternatively you can specify a custom location for this file".

Therefore, I would expect the schedule of a task to not be remembered after I delete the beat schedule database file. Otherwise stated, I would expect the scheduled task to run within the time of a heartbeat tick when starting beat/worker after deleting the schedule file since last run times will be gone.

## Actual behavior

Deleting the beat schedule does not cause a scheduled task to run again when re-launching beat. I must wait for the time of the task interval for it to run again.

**Comment by auvipy** [comment]
possibly this has been fixed in master. wait for 4.2 release and report again
