### ISSUE TITLE
Signal "before_task_publish" received wrong dictionary of message properties

### ISSUE THREAD

**Issue by joker-ace** [celery/celery#3856]
## Checklist

- Celery version: 4.0.2
- I have verified that the issue exists against the `master` branch of Celery.

Declare signal like this

```
@signals.before_task_publish.connect
def _do_something_with_properties(properties=None, **kwds):
    properties['my_key'] = 'my_value'
```

and you will never get this this 'my_key' published in task properties.
Take a look:

Celery 3:

https://github.com/celery/celery/blob/3.1/celery/app/amqp.py#L296
https://github.com/celery/celery/blob/3.1/celery/app/amqp.py#L310

Celery 4:

https://github.com/celery/celery/blob/4.0/celery/app/amqp.py#L547
https://github.com/celery/celery/blob/4.0/celery/app/amqp.py#L558

As you can see, `properties` was updated before signal code invoked, signal code receives `kwargs` value as `properties` param, where I need to add some keys to `properties`, but  task is publishing with old `properties` dict from line 547.

**Comment by auvipy** [comment]
could you verify the issue on latest master?
