### ISSUE TITLE
plain celery.beat.Scheduler is not functional

### ISSUE THREAD

**Issue by fingon** [celery/celery#3862]
## Checklist
- [ ] I have included the output of ``celery -A proj report`` in the issue.
 4.0.2, also master
- [x] I have verified that the issue exists against the `master` branch of Celery.
 ^ based on code review, code hasn't changed

## Steps to reproduce

create a project that has scheduled tasks, do --scheduler celery.beat.Scheduler -B instead of -B when starting a worker

## Expected behavior

get running periodic tasks

## Actual behavior

periodic tasks are not run at all.

The reason for this is relatively obvious: https://github.com/celery/celery/blob/master/celery/beat.py#L458

The beat_schedule is merged in only in PersistentScheduler and not the superclass.

in my own workaround 'FixedScheduler', I simply call         self.merge_inplace(self.app.conf.beat_schedule) and then Scheduler's own setup_schedule.

**Comment by auvipy** [comment]
whats it's status on current master?

**Comment by craigds** [comment]
i realise this was a while ago, but I just ran into this and spent a good hour or so scratching my head.

Is this marked 'not a bug' for a reason?

**Comment by craigds** [comment]
As a workaround, I've switched to PersistentScheduler and just set the `--schedule` to a tmp file. Which is probably good enough, though a little confusing

**Comment by matteius** [comment]
@craigds and @auvipy I have reviewed this and it seemed like a logical change that @fingon suggested in the Issue report.   I opened a PR with the proposed change but also the existing celery beat mockScheduler tests are somewhat confusing as far as adding additional tests go.

**Comment by auvipy** [comment]
thanks good people!
