### ISSUE TITLE
UnicodeDecodeError: printing logging

### ISSUE THREAD

**Issue by goinnn** [celery/celery#3865]
## Checklist

- [ ] Celery version: 4.0.2 and Python 2.7.6
- [ ] Yes, the error is in master branch

With celery 3.1.19 works  and with celery 4.0.2 does not work. The problem is after this commit [016629f75e1464baf3dc053a814a91948111dbb8]. If I remove unicode_literals from  app/defaults.py it works again.

## Steps to reproduce

Add these lines in a task:

    from django.utils.safestring import SafeText
    logger.debug(SafeText(u"á").encode('utf-8'))

## Expected behavior

    DEBUG á                                                  // Django logging
    [2017-02-24 14:19:14,052: DEBUG/PoolWorker-2] á         // Celery logging

## Actual behavior

    DEBUG á               // Django logging works
    [2017-02-24 14:18:39,760: WARNING/PoolWorker-2] Traceback (most recent call last):
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] File "/usr/lib/python2.7/logging/__init__.py", line 854, in emit
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] msg = self.format(record)
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] File "/usr/lib/python2.7/logging/__init__.py", line 727, in format
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] return fmt.format(record)
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] File "VIRTUAL_ENV_PATH/local/lib/python2.7/site-packages/celery/utils/log.py", line 158, in format
    [2017-02-24 14:18:39,761: WARNING/PoolWorker-2] msg = logging.Formatter.format(self, record)
    [2017-02-24 14:18:39,762: WARNING/PoolWorker-2] File "/usr/lib/python2.7/logging/__init__.py", line 470, in format
    [2017-02-24 14:18:39,762: WARNING/PoolWorker-2] s = self._fmt % record.__dict__
    [2017-02-24 14:18:39,762: WARNING/PoolWorker-2] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
    [2017-02-24 14:18:39,762: WARNING/PoolWorker-2] Logged from file connector.py, line 81

**Comment by georgepsarakis** [comment]
Seems to work with current `master` branch. Do you have any more details, like logging configuration etc?

**Comment by goinnn** [comment]
@georgepsarakis Do you tested with Python 2.7?

I am using Django 1.8.6, and this is my logging config:

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple'
            },
        },
        'formatters': {
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            },
            'simple': {
                'format': '%(levelname)s %(message)s'
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'WARN',
                'propagate': True,
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'WARN',
                'propagate': True,
            },
            'api': {    // a Django application of my project
                'handlers': ['console'],
                'level': 'DEBUG',
                'propagate': True,
            },
        },
    }


My celerybeat schedule:

    CELERYBEAT_SCHEDULE = {
        'assign_services': {
            'task': 'api.tasks.assign_pending_services',
            'schedule': timedelta(seconds=10),
        }}


My task file:

    # -*- coding: utf-8 -*-
    import logging

    from django.utils.safestring import SafeText

    from joinupback.celery import app


    logger = logging.getLogger(__name__)


    @app.task
    def assign_pending_services(): 
        // It is a dummy task to get quickly the error
        logger.debug(SafeText(u"á").encode('utf-8'))
       // Next line you get the same error:
        logger.debug(u"á".encode('utf-8'))


And "from joinupback.celery import app":

    from __future__ import absolute_import

    import os

    from celery import Celery
    # set the default Django settings module for the 'celery' program.
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'joinupback.settings')

    from django.conf import settings  # noqa

    app = Celery('joinupback')

    # Using a string here means the worker will not have to
    # pickle the object when using Windows.
    app.config_from_object('django.conf:settings')
    app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

**Comment by georgepsarakis** [comment]
I have an idea of what might be wrong. You are using custom formatters, in your logging configuration (`LOGGING` dictionary).

Could you try adding:

```
from __future__ import unicode_literals
```

in the module that you defined the `LOGGING` dictionary?

**Comment by goinnn** [comment]
@georgepsarakis Same error.

If I add this line:

> from __future__ import absolute_import, unicode_literals

Now, I get the same error in both loggings system: Django and celery. :-(

I think the Django logging system is not the problem, but if you want I can test with another LOGGING configuration. Any idea?

**Comment by georgepsarakis** [comment]
I think I found the issue, you shouldn't be converting the log message to `str` using `encode('utf-8')`, so the following will work with Celery and Django logging as expected:

```
logger.debug(u"á")
```

The reason is that decoding the `str` to Unicode, with the default ASCII codec raises an error. This happens implicitly because the formatting template (e.g. `'%(levelname)s %(message)s'`) is `unicode`. 

Consider the following sample code using the built-in `logging` classes:

```
import logging
from logging import LogRecord, Formatter

record = LogRecord(
    level=logging.WARNING, 
    msg=u"á", 
    lineno=1, 
    name=None, 
    args=None, 
    pathname=None, 
    exc_info=None
)
formatter = Formatter(fmt=u'- %(message)s')
print formatter.format(record)  # - á

record = LogRecord(
    level=logging.WARNING, 
    msg=u"á".encode("utf-8"), 
    lineno=1, 
    name=None, 
    args=None, 
    pathname=None, 
    exc_info=None
)
print formatter.format(record)  # UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

**Comment by goinnn** [comment]
Yes, but in celery 3 message formatter is not an unicode object, so it worked :-(

Celery 3:

    from celery.app.defaults import DEFAULT_TASK_LOG_FMT
    DEFAULT_TASK_LOG_FMT
        '[%(asctime)s: %(levelname)s/%(processName)s] %(task_name)s[%(task_id)s]: %(message)s'
    print DEFAULT_TASK_LOG_FMT.__class__
        <type 'str'>


Celery 4:

    from celery.app.defaults import DEFAULT_TASK_LOG_FMT
    DEFAULT_TASK_LOG_FMT
        u'[%(asctime)s: %(levelname)s/%(processName)s] %(task_name)s[%(task_id)s]: %(message)s'
    print DEFAULT_TASK_LOG_FMT.__class__
        <type 'unicode'>


Following with your example, you can run the next both codes with celery 4.

Like in celery 3 formatter is a str object:

    import logging
    from logging import LogRecord, Formatter

    formatter = Formatter(fmt='- %(message)s')

    record = LogRecord(
        level=logging.WARNING, 
        msg=u"á".encode("utf-8"), 
        lineno=1, 
        name=None, 
        args=None, 
        pathname=None, 
        exc_info=None
    )
    print formatter.format(record)  # - á

Like in celery 4 formatter is an unicode object:

    import logging
    from logging import LogRecord, Formatter

    formatter = Formatter(fmt=u'- %(message)s')   # This line is changed

    record = LogRecord(
        level=logging.WARNING, 
        msg=u"á".encode("utf-8"), 
        lineno=1, 
        name=None, 
        args=None, 
        pathname=None, 
        exc_info=None
    )
    print formatter.format(record) # UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

So, It is a backward incompatibility. But I don't know if for you is it an important backward incompatibility, or do the celery users have to adapt their code?

Please tell me if you need some clarification, and thank you for your attention :-)

**Comment by georgepsarakis** [comment]
Since 3 and 4 are two different major versions, I think the backward incompatibilities are expected.

I think that using `unicode` directly should work both with Django and Celery 4:

```
from __future__ import unicode_literals
logger.debug("á")
```

Doesn't the above work correctly?

**Comment by goinnn** [comment]
Yes this works.

I understand it is very hard to continue a development without backward incompatibilities. For this reason I asked you, is it an important backward incompatibility, or do the celery users have to adapt their code?

If the answer is the second option, we have to change the code, feel free to close the issue.

Also, I have fixed my problem updating my settings with these lines:

    CELERYD_LOG_FORMAT = "[%(asctime)s: %(levelname)s/%(processName)s] %(message)s"
    CELERYD_TASK_LOG_FORMAT = """[%(asctime)s: %(levelname)s/%(processName)s]
    [%(task_name)s(%(task_id)s)] %(message)s"""

Thanks a lot!

**Comment by georgepsarakis** [comment]
So, you switched the format templates to `str`? I verified that by default the format template is indeed `unicode`.

**Comment by goinnn** [comment]
@georgepsarakis Yes, I did it in my settings... and now everything works for me. This was the only problem/error migrating from celery 3 to celery 4.

So, now for me it is not a problem :-) Feel free to close the issue, although solving the issues always more beautiful.

Thanks another time!

**Comment by georgepsarakis** [comment]
All modules use `unicode_literals`, so I am sure that the project intentionally uses `unicode` everywhere and not `str`. I beleve the change was introduced with this [commit](https://github.com/celery/celery/commit/016629f75e1464baf3dc053a814a91948111dbb8). 

You are welcome, closing for now since I think we have clarified the issue :smile: !
