### ISSUE TITLE
Can't use systemd to run celerybeat, status is always loaded, Inactive

### ISSUE THREAD

**Issue by ArsenePadthai** [celery/celery#3870]
Actually, 'celery beat -A sender' can get the expected result. But when I try to daemonize it, the systemd just can't get right, and always shows inactive dead.  

I carefully checked the userguide, and found that in daemonizing chapter, the systemd example of celery beat is missing. Is there any perticular reason for this? 

## Steps to reproduce
In my neocu-notification-beat.service:

[Unit]
Description=Celery beat scheduler
After=network.target

[Service]
Type=simple
User=neocu
Group=neocu
EnvironmentFile=/etc/neocu_notification_service/common.conf
EnvironmentFile=-/etc/neocu_notification_service/celery.conf
WorkingDirectory=/usr/share/neocu_notification_service
PermissionsStartOnly=true
ExecStartPre=/bin/bash -c 'mkdir -p /var/run/neocu_notification_service; chown neocu:neocu /var/run/neocu_notification_service'
ExecStart=/bin/bash -c '/usr/share/neocu_notification_service/venv/bin/celery beat -A sender --pidfile=${CELERYBEAT_PID_FILE}‘

[Install]
WantedBy=multi-user.target

## Actual behavior
● neocu-notification-beat.service - Celery beat scheduler
   Loaded: loaded (/usr/lib/systemd/system/neocu-notification-beat.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

2月 28 21:21:31 neocuqa-controller bash[40520]: celery beat v3.1.23 (Cipater) is starting.
2月 28 21:21:31 neocuqa-controller bash[40520]: __    -    ... __   -        _
2月 28 21:21:31 neocuqa-controller bash[40520]: Configuration ->
2月 28 21:21:31 neocuqa-controller bash[40520]: . broker -> amqp://neocu_notify:**@localhost:5672//
2月 28 21:21:31 neocuqa-controller bash[40520]: . loader -> celery.loaders.app.AppLoader
2月 28 21:21:31 neocuqa-controller bash[40520]: . scheduler -> celery.beat.PersistentScheduler
2月 28 21:21:31 neocuqa-controller bash[40520]: . db -> celerybeat-schedule
2月 28 21:21:31 neocuqa-controller bash[40520]: . logfile -> [stderr]@%INFO
2月 28 21:21:31 neocuqa-controller bash[40520]: . maxinterval -> now (0s)
2月 28 21:21:31 neocuqa-controller systemd[1]: Started Celery beat scheduler.

**Comment by ArsenePadthai** [comment]
Finally I solved the problem by set the user and group to root. I guess something goes wrong with the permission. Sorry for disturbing.

**Comment by EidrianGM** [comment]
In case that anyone reach this post, I faced the same problem and solved it, *NOT BY GIVING ROOT PERMISSIONS* which might lead to security issues, but I changed Type to "forking" and it is up and running correctly

**Comment by rishindoshi** [comment]
To continue on with the confusion, what fixed this for me was setting `Type=simple` in the Service section 😕
