### ISSUE TITLE
Class-based Task is not registered

### ISSUE THREAD

**Issue by primoz-k** [celery/celery#3874]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```python
from my_app.celery import app

class FetchProfilePhoto(Task):
    def run(self, profile_photo_id, **kwargs):
        # Do something
        pass
app.register_task(FetchProfilePhoto())

# Calling the task
FetchProfilePhoto().delay(profile_photo_id=123)
```

## Expected behavior
The task is executed with delay and no exception is raised

## Actual behavior
An exception is raised:
```python
celery.exceptions.NotRegistered
```

If I add the `name` attribute to my class-based Task, the task can be executed with `delay`:
```python
class FetchProfilePhoto(Task):
    name = "my_app.tasks.FetchProfilePhoto"
    def run(self, profile_photo_id, **kwargs):
        # Do something
        pass
app.register_task(FetchProfilePhoto())
```

Am I doing something wrong or is this behaviour expected?

**Comment by georgepsarakis** [comment]
The registration seems correct according to the [documentation](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html?highlight=register_task#the-task-base-class-no-longer-automatically-register-tasks).

If I understand correctly, the task name is derived incorrectly, see the implementation [here](https://github.com/celery/celery/blob/master/celery/app/base.py#L489).

Can you debug this specific section to check the value assigned to `task.name`  at this [line](https://github.com/celery/celery/blob/master/celery/app/base.py#L493)?

**Comment by primoz-k** [comment]
Hi, @georgepsarakis !

`task.name` at the specific line looks good. It is `my_app.tasks.FetchProfilePhoto`.

But it fails if I run call `FetchProfilePhoto().delay(profile_photo_id=123)` from my Django console.

Complete Traceback:

```python
Traceback (most recent call last):
  File "/home/primoz/.virtualenvs/project/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d09e482536df>", line 1, in <module>
    FetchProfilePhoto().delay(profile_photo_id=123)
  File "/home/primoz/.virtualenvs/project/lib/python3.5/site-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/home/primoz/.virtualenvs/project/lib/python3.5/site-packages/celery/app/task.py", line 522, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/primoz/.virtualenvs/project/lib/python3.5/site-packages/celery/app/task.py", line 721, in apply
    task = app._tasks[self.name]
  File "/home/primoz/.virtualenvs/project/lib/python3.5/site-packages/celery/app/registry.py", line 19, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered
```

**Comment by georgepsarakis** [comment]
Could you please also check the value of the Task `name` property [here](https://github.com/celery/celery/blob/master/celery/app/task.py#L722)?

**Comment by primoz-k** [comment]
`self.name`: `None`

`app._tasks`: `'my_app.tasks.FetchProfilePhoto': <@task: my_app.tasks.FetchProfilePhoto of project:0x7fbe4e0827f0>`

So the task looks like it is in `TaskRegistry` but has no name set.

I have `CELERY_TASK_ALWAYS_EAGER = True` if this info helps.

**Comment by georgepsarakis** [comment]
I think I found the solution, `register_task` returns the task instance, so the following will work:

```
FetchProfilePhoto = app.register_task(FetchProfilePhoto())

FetchProfilePhoto.delay(profile_photo_id=123) from
```

**Comment by primoz-k** [comment]
OK, so, should we fix the documentation or the `register_task` behavior to reflect the documentation?

**Comment by georgepsarakis** [comment]
Did you try what I suggested and it worked right? I guess expanding the documentation would be nice, so that nobody is confused again in the future. Will you open the related PR?

**Comment by primoz-k** [comment]
I will do it on Monday. I just wanted to know what the next step is if it works. And if it does, I will let you know and create the PR.

**Comment by primoz-k** [comment]
@georgepsarakis Your suggestion works! Thank you.

**Comment by primoz-k** [comment]
Fixed in https://github.com/celery/celery/commit/9342ed54f309914cd17adf038257a06c0f42605a

**Comment by sivang** [comment]
Also getting this, however, as I'm creating a class to hook up into on_failure, can the same resolution method apply to me to?

{code}
class ReplayableTask(celery.Task):

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print ("Exception caught: {}".format(exc))
        client = MongoClient()
        processing = client.processing
        failures = processing.failures
        failures.insert_one({"exc" : exc, "task_id" : task_id, "args" : args, "kwargs" : kwargs, "einfo" : einfo })
        del client
        del processing
        del failures


app.tasks.register(ReplayableTask())

{code}

**Comment by mathans1695** [comment]
> I think I found the solution, `register_task` returns the task instance, so the following will work:
> 
> ```
> FetchProfilePhoto = app.register_task(FetchProfilePhoto())
> 
> FetchProfilePhoto.delay(profile_photo_id=123) 
> ```

Here we are registering instance, not class. So, every celery will run on this same instance. I think this is the problem I am facing right now

**Comment by Hamma111** [comment]
> This is the problem I am facing right now

@mathans1695 did you figure out any solution for that?
