### ISSUE TITLE
Nested chord are failling with KeyError, if inner chord consists of one task

### ISSUE THREAD

**Issue by elysium31** [celery/celery#3885]
Tested on celery v4.0.2

I have the following set of tasks, nested chord of chords. One inner chord has only one task (i don't know exact number of tasks beforehand, they are compound in runtime). And it is falling with exception KeyError: 0

```
chord(
     [
         chord([taskA1.s(), taskA2.s()], taskC.si()),
         chord([taskB.s()], taskC.si())
     ], 
     taskD.si()
).delay()
```

```
Traceback (most recent call last):
  File "<console>", line 6, in <module>
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 182, in delay
    return self.apply_async(partial_args, partial_kwargs)
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 1245, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 1287, in run
    result=results)
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/backends/redis.py", line 245, in apply_chord
    return header(*partial_args, **options or {})
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 962, in __call__
    return self.apply_async(partial_args, **options)
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 987, in apply_async
    args=args, kwargs=kwargs, **options))
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 1063, in _apply_tasks
    **options)
  File "/home/maksym/projects/python_ve/lib/python3.4/site-packages/celery/canvas.py", line 1242, in apply_async
    return (self.tasks[0] | body).set(task_id=task_id).apply_async(
KeyError: 0
```
I assume self.task[0] should be replaced with self.task, am i right?

**Comment by robpogorzelski** [comment]
Confirmed, experienced the same. Replacing with self.task won't solve the problem, I'll provide a patch early next week.

**Comment by robpogorzelski** [comment]
So it seems that in the whole task execution pipeline only `apply_async` is affected. If you replaced `self.tasks[0]` with `self.tasks` the following case would fail:

```
    def test_apply_async_task_in_nested_chords(self):
        x = chord(
            [
                chord([self.add.si(5, 6)], body=self.mul.s(4), app=self.app),
            ],
            body=self.mul.s(4),
            app=self.app
        )
        x.apply_async()
```
with
`TypeError: unsupported operand type(s) for |: 'list' and 'Signature'`

**Comment by robpogorzelski** [comment]
Closed pull request for this ticket. It seems a completely different logic is applied to joining tasks when running in eager mode or not and I'm not likely to invest more time in investigating these issues. I switched to `group(tasks) | callback` which work perfectly fine.

**Comment by thedrow** [comment]
@robpogorzelski Do you mind describing your approach? I'll see if I can give it a go...

**Comment by robpogorzelski** [comment]
It's difficult to recover my last discoveries from memory, but I remember the final conclusion: the chord class is broken and the only way to regain control on what's going on would be to refactor both group and chord to use common interface and part of the implementation.

**Comment by bierdybard** [comment]
> One inner chord has only one task 

I think this may be the key. I dynamically generate my chords and they may have anywhere from 1-∞ members, and I noticed that when the chord has only one member, the result is not passed to the callback wrapped in a list.

Upon looking at the release notes, I discovered the following:
> A chord where the header group only consists of a single task is now turned into a simple chain.

I think this conversion is failing to wrap the result in a list as would happen if there were multiple tasks in the header. If your callback code is expecting to handle that list, you would run into errors. Complicating matters is the case (like mine) where the chord task result is itself a list.

Not sure if this specific finding has been reported elsewhere, I found this bug in that search.

**Comment by robpogorzelski** [comment]
As described above by @bierdybard, that's along my discoveries too.

**Comment by JioHooney** [comment]
I have same problem.
Has this problem been resolved?

**Comment by thedrow** [comment]
Yes in master. Release is coming soon. See #4387 for details.

**Comment by JioHooney** [comment]
@thedrow
Thanks for the answer
