### ISSUE TITLE
Rate limit ignored when ETA specified

### ISSUE THREAD

**Issue by browniebroke** [celery/celery#3888]
While I accept this is a limitation, it's not a very clear one from the documentation. It would be good to add it as a note/warning somewhere to clarify that ETA and rate limit are incompatible.

http://docs.celeryproject.org/en/latest/internals/worker.html#id1
http://docs.celeryproject.org/en/latest/userguide/tasks.html?highlight=delay#Task.rate_limit

## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

This is explained [here](http://stackoverflow.com/questions/30804857/celery-rate-limit-not-respected-when-scheduling-via-eta-option).

## Expected behavior

I was expecting that the task would be delayed as per the ETA, and then be executed sometimes after that, respecting the rate limit.

## Actual behavior

The rate limit is ignored entirely by Celery.

**Comment by thedrow** [comment]
I don't think the documentation changes fix this issue but it's a start until someone implements the support for both.
