### ISSUE TITLE
Time taken in tracking Groupresults

### ISSUE THREAD

**Issue by Rajlaxmi** [celery/celery#3894]
## Setup
Hi,
In my current setup I usually submit ~50k tasks and there are around 500 machines autoscaled to complete tasks. I am using celery to submit tasks with rabbitmq as broker and mysql as backend.

## Issue
I tried to submit 50k by dividing them into a bunch of 1k tasks and applying group on them. Finally, I track ~50 group ids to check its completion. I need to submit with by splitting it into multiple group due to this issue: [Issue-3387](https://github.com/celery/celery/issues/3387)
While tracking these group ids, it takes 20 mins to complete.

## Steps to reproduce
```
for i in {1..2000}; do echo "sleep 10; echo 1; sleep 10" >> ~/log; done
time submit.py -f ~/log > ~/ids
```

submit.py:
```
cmds = open(allfile).readlines()
sub_tasks = [exec_bash.subtask([x]) for x in cmds]
num = 1000
chunks = [sub_tasks[x:x+num] for x in xrange(0, len(sub_tasks), num)]
for chunk in chunks:
        tasks = group(chunk)
        res = tasks.apply_async(queue=queue_name, routing_key=queue_name, retry=True)
        res.save()
        print res.id
```
```
time for id in `cat ~/ids`; do getres.py -g $id > /dev/null; done
```

getres.py:
```
from proj.tasks import app
res = GroupResult.restore(args.group_id, app=app)
```

## Suggestion
Currently, GroupResult.restore is fetching entire result instead of state. Is it possible to provide state for tasks and grouped tasks and a custom method for fetching state.

**Comment by auvipy** [comment]
could you verify this on top of master?
