### ISSUE TITLE
Protocol example in documentation is not working.

### ISSUE THREAD

**Issue by sklif5** [celery/celery#3905]
## Checklist

- [ 4.0.2]  ( the Celery
       version ).
- [ X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Run the example from the documentation [page](http://docs.celeryproject.org/en/latest/internals/protocol.html)

## Expected behavior
The example should send a task
chain: add(add(add(2, 2), 4), 8) == 2 + 2 + 4 + 8
## Actual behavior
The code is not working
1. In Python 3.5.2 uuid module does not contain uuid()
2. The serialization message=json.dumps.... is not working, hence not allowing to see actual example of the message.

**Comment by georgepsarakis** [comment]
You are correct, there is an `import` statement missing:

```
from kombu.utils.uuid import uuid
```

Can you add this and test?

**Comment by georgepsarakis** [comment]
@sklif5 any updates on this issue? Did my suggestion work?

**Comment by auvipy** [comment]
closing due to lack of feedback.
