### ISSUE TITLE
Cell Support

### ISSUE THREAD

**Issue by dkhan11** [celery/celery#3906]
Hi,

I'm trying to use the Cell package but the current examples are no longer valid because Kombu updated their APIs. 'ipublish' is deprecated.
This is the error message:
ImportError: cannot import name 'ipublish'

Are you supporting cell?

Thanks in advance,
DD.

**Comment by dejlek** [comment]
Cell has a separate repo, with own project backlog... https://github.com/celery/cell

**Comment by dkhan11** [comment]
I did that first, but no one responded in the issue.
