### ISSUE TITLE
Task  raise unexpected SoftTimeLimitExceeded and ignore try/except and on_failure handler

### ISSUE THREAD

**Issue by SerhiyRomanov** [celery/celery#3914]
## Checklist
  I have included the output of ``celery -A proj report`` in the issue.

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.11+
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

SECURE_SSL_REDIRECT: False
SECURE_HSTS_SECONDS: 0
USE_X_FORWARDED_PORT: False
ACCOUNT_AUTHENTICATION_METHOD: 'username_email'
CSRF_COOKIE_SECURE: False
LANGUAGE_CODE: 'ru'
ROOT_URLCONF: 'seo_text_analyzer.urls'
LOGIN_URL: 'account_login'
BASE_DIR: '/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer'
TEST_NON_SERIALIZED_APPS: []
DEFAULT_CHARSET: u'utf-8'
SESSION_SERIALIZER: u'django.contrib.sessions.serializers.JSONSerializer'
ACCOUNT_EMAIL_REQUIRED: True
FIXTURE_DIRS: []
ALLOWED_HOSTS: ['127.0.0.1']
EMAIL_HOST: 'silicone-potato.ru'
MESSAGE_STORAGE: u'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX: u'[Django] '
FILE_UPLOAD_PERMISSIONS: None
CELERY_RESULT_SERIALIZER: 'json'
STATICFILES_FINDERS: [u'django.contrib.staticfiles.finders.FileSystemFinder',
 u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
SESSION_CACHE_ALIAS: u'default'
CELERY_IMPORTS: 
    ('seo_work',)
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_NAME: u'sessionid'
CELERY_BROKER_URL: u'redis://localhost:6379/0'
TIME_INPUT_FORMATS: [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
SECURE_REDIRECT_EXEMPT: []
DATABASES: {
    'default': {   'ENGINE': 'django.db.backends.mysql',
                   'HOST': '127.0.0.1',
                   'NAME': 'seo',
                   'PASSWORD': u'********',
                   'PORT': '3306',
                   'USER': 'root'}}
EMAIL_SSL_KEYFILE: u'********'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
THOUSAND_SEPARATOR: u','
FILE_UPLOAD_HANDLERS: 
    ('django.core.files.uploadhandler.TemporaryFileUploadHandler',)
DEFAULT_CONTENT_TYPE: u'text/html'
APPEND_SLASH: True
FIRST_DAY_OF_WEEK: 0
DATABASE_ROUTERS: u'********'
EMAIL_USE_SSL: False
YEAR_MONTH_FORMAT: u'F Y'
STATICFILES_STORAGE: u'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES: {
    u'default': {   u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
SERVER_EMAIL: 'info@silicone-potato.ru'
SESSION_COOKIE_PATH: u'/'
SILENCED_SYSTEM_CHECKS: []
MIDDLEWARE_CLASSES: ['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
USE_I18N: True
SECRET_KEY: u'********'
LANGUAGE_COOKIE_NAME: u'django_language'
DEFAULT_INDEX_TABLESPACE: u''
LOGGING_CONFIG: u'logging.config.dictConfig'
WSGI_APPLICATION: 'seo_text_analyzer.wsgi.application'
X_FRAME_OPTIONS: u'SAMEORIGIN'
AUTHENTICATION_BACKENDS: 
    ('django.contrib.auth.backends.ModelBackend',
 'allauth.account.auth_backends.AuthenticationBackend')
USE_THOUSAND_SEPARATOR: False
USE_X_FORWARDED_HOST: False
CSRF_HEADER_NAME: u'HTTP_X_CSRFTOKEN'
EMAIL_TIMEOUT: None
SECURE_SSL_HOST: None
SIGNING_BACKEND: u'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE: False
SECURE_BROWSER_XSS_FILTER: False
CSRF_COOKIE_DOMAIN: None
FILE_CHARSET: u'utf-8'
DEBUG: True
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
LANGUAGE_COOKIE_DOMAIN: None
DEFAULT_FILE_STORAGE: u'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS: ['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'solo',
 'widget_tweaks',
 'bootstrap3',
 'multiselectfield',
 'django_celery_beat',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.vk',
 'main',
 'text_analayzer',
 'copywriters',
 'words_count',
 'aquarelle',
 'clusterization',
 'positions']
LANGUAGES: [(u'af', u'Afrikaans'),
 (u'ar', u'Arabic'),
 (u'ast', u'Asturian'),
 (u'az', u'Azerbaijani'),
 (u'bg', u'Bulgarian'),
 (u'be', u'Belarusian'),
 (u'bn', u'Bengali'),
 (u'br', u'Breton'),
 (u'bs', u'Bosnian'),
 (u'ca', u'Catalan'),
 (u'cs', u'Czech'),
 (u'cy', u'Welsh'),
 (u'da', u'Danish'),
 (u'de', u'German'),
 (u'dsb', u'Lower Sorbian'),
 (u'el', u'Greek'),
 (u'en', u'English'),
 (u'en-au', u'Australian English'),
 (u'en-gb', u'British English'),
 (u'eo', u'Esperanto'),
 (u'es', u'Spanish'),
 (u'es-ar', u'Argentinian Spanish'),
 (u'es-co', u'Colombian Spanish'),
 (u'es-mx', u'Mexican Spanish'),
 (u'es-ni', u'Nicaraguan Spanish'),
 (u'es-ve', u'Venezuelan Spanish'),
 (u'et', u'Estonian'),
 (u'eu', u'Basque'),
 (u'fa', u'Persian'),
 (u'fi', u'Finnish'),
 (u'fr', u'French'),
 (u'fy', u'Frisian'),
 (u'ga', u'Irish'),
 (u'gd', u'Scottish Gaelic'),
 (u'gl', u'Galician'),
 (u'he', u'Hebrew'),
 (u'hi', u'Hindi'),
 (u'hr', u'Croatian'),
 (u'hsb', u'Upper Sorbian'),
 (u'hu', u'Hungarian'),
 (u'ia', u'Interlingua'),
 (u'id', u'Indonesian'),
 (u'io', u'Ido'),
 (u'is', u'Icelandic'),
 (u'it', u'Italian'),
 (u'ja', u'Japanese'),
 (u'ka', u'Georgian'),
 (u'kk', u'Kazakh'),
 (u'km', u'Khmer'),
 (u'kn', u'Kannada'),
 (u'ko', u'Korean'),
 (u'lb', u'Luxembourgish'),
 (u'lt', u'Lithuanian'),
 (u'lv', u'Latvian'),
 (u'mk', u'Macedonian'),
 (u'ml', u'Malayalam'),
 (u'mn', u'Mongolian'),
 (u'mr', u'Marathi'),
 (u'my', u'Burmese'),
 (u'nb', u'Norwegian Bokm\xe5l'),
 (u'ne', u'Nepali'),
 (u'nl', u'Dutch'),
 (u'nn', u'Norwegian Nynorsk'),
 (u'os', u'Ossetic'),
 (u'pa', u'Punjabi'),
 (u'pl', u'Polish'),
 (u'pt', u'Portuguese'),
 (u'pt-br', u'Brazilian Portuguese'),
 (u'ro', u'Romanian'),
 (u'ru', u'Russian'),
 (u'sk', u'Slovak'),
 (u'sl', u'Slovenian'),
 (u'sq', u'Albanian'),
 (u'sr', u'Serbian'),
 (u'sr-latn', u'Serbian Latin'),
 (u'sv', u'Swedish'),
 (u'sw', u'Swahili'),
 (u'ta', u'Tamil'),
 (u'te', u'Telugu'),
 (u'th', u'Thai'),
 (u'tr', u'Turkish'),
 (u'tt', u'Tatar'),
 (u'udm', u'Udmurt'),
 (u'uk', u'Ukrainian'),
 (u'ur', u'Urdu'),
 (u'vi', u'Vietnamese'),
 (u'zh-hans', u'Simplified Chinese'),
 (u'zh-hant', u'Traditional Chinese')]
STATIC_ROOT: '/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer/public/static'
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
MIDDLEWARE: None
is_overridden: <bound method Settings.is_overridden of <Settings "seo_text_analyzer.settings">>
PREPEND_WWW: False
SECURE_PROXY_SSL_HEADER: None
LANGUAGE_COOKIE_AGE: None
SESSION_COOKIE_HTTPONLY: True
DEBUG_PROPAGATE_EXCEPTIONS: False
CSRF_COOKIE_AGE: 31449600
MEDIA_URL: '/media/'
MONTH_DAY_FORMAT: u'F j'
MANAGERS: []
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
AUTH_PASSWORD_VALIDATORS: u'********'
TIME_FORMAT: u'P'
AUTH_USER_MODEL: u'auth.User'
DATE_INPUT_FORMATS: [u'%Y-%m-%d',
 u'%m/%d/%Y',
 u'%m/%d/%y',
 u'%b %d %Y',
 u'%b %d, %Y',
 u'%d %b %Y',
 u'%d %b, %Y',
 u'%B %d %Y',
 u'%B %d, %Y',
 u'%d %B %Y',
 u'%d %B, %Y']
CSRF_TRUSTED_ORIGINS: []
CSRF_COOKIE_NAME: u'csrftoken'
EMAIL_HOST_PASSWORD: u'********'
PASSWORD_RESET_TIMEOUT_DAYS: u'********'
SESSION_FILE_PATH: None
CACHE_MIDDLEWARE_ALIAS: u'default'
SESSION_SAVE_EVERY_REQUEST: False
NUMBER_GROUPING: 0
SESSION_ENGINE: u'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW: u'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH: u'/'
LOGIN_REDIRECT_URL: 'main:all_tasks'
CELERY_TASK_SERIALIZER: 'json'
DECIMAL_SEPARATOR: u'.'
IGNORABLE_404_URLS: []
LOCALE_PATHS: []
USE_L10N: True
CELERY_BROKER_TRANSPORT: 'redis'
ACCOUNT_USERNAME_BLACKLIST: ['admin']
FORCE_SCRIPT_NAME: None
DATE_FORMAT: u'N j, Y'
MEDIA_ROOT: '/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer/media'
DEFAULT_EXCEPTION_REPORTER_FILTER: u'django.views.debug.SafeExceptionReporterFilter'
ADMINS: []
FORMAT_MODULE_PATH: None
DEFAULT_FROM_EMAIL: 'info@silicone-potato.ru'
STATICFILES_DIRS: 
    ('/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer/static',)
SECURE_CONTENT_TYPE_NOSNIFF: False
DATETIME_FORMAT: u'N j, Y, P'
CELERY_ACCEPT_CONTENT: ['json']
SITE_ID: 1
DISALLOWED_USER_AGENTS: []
LOGGING: {
    }
SHORT_DATE_FORMAT: u'm/d/Y'
TEMPLATES: [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['templates'],
  'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages',
                                     'django.template.context_processors.debug',
                                     'django.template.context_processors.i18n',
                                     'django.template.context_processors.media',
                                     'django.template.context_processors.static',
                                     'django.template.context_processors.tz',
                                     'django.template.context_processors.request',
                                     'main.context_processors.admin_settings']}}]
LOGOUT_REDIRECT_URL: None
TEST_RUNNER: u'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_KEY_PREFIX: u'********'
EMAIL_USE_TLS: True
TIME_ZONE: 'Europe/Kiev'
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
EMAIL_BACKEND: u'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_TABLESPACE: u''
MIGRATION_MODULES: {
    }
DATA_UPLOAD_MAX_NUMBER_FIELDS: 1000
SESSION_COOKIE_AGE: 1209600
SETTINGS_MODULE: 'seo_text_analyzer.settings'
USE_ETAGS: False
LOCAL: True
LANGUAGES_BIDI: [u'he', u'ar', u'fa', u'ur']
FILE_UPLOAD_TEMP_DIR: None
INTERNAL_IPS: []
STATIC_URL: '/static/'
EMAIL_PORT: 25
USE_TZ: True
SHORT_DATETIME_FORMAT: u'm/d/Y P'
CELERY_RESULT_BACKEND: u'redis://localhost:6379/0'
PASSWORD_HASHERS: u'********'
ABSOLUTE_URL_OVERRIDES: {
    }
LANGUAGE_COOKIE_PATH: u'/'
CACHE_MIDDLEWARE_SECONDS: 600
EMAIL_SSL_CERTFILE: None
CSRF_COOKIE_HTTPONLY: False
DATETIME_INPUT_FORMATS: [u'%Y-%m-%d %H:%M:%S',
 u'%Y-%m-%d %H:%M:%S.%f',
 u'%Y-%m-%d %H:%M',
 u'%Y-%m-%d',
 u'%m/%d/%Y %H:%M:%S',
 u'%m/%d/%Y %H:%M:%S.%f',
 u'%m/%d/%Y %H:%M',
 u'%m/%d/%Y',
 u'%m/%d/%y %H:%M:%S',
 u'%m/%d/%y %H:%M:%S.%f',
 u'%m/%d/%y %H:%M',
 u'%m/%d/%y']
EMAIL_HOST_USER: 'info@silicone-potato.ru'
   
+ [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```
class BaseJobTask(celery_app.Task):
    abstract = True
    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print ("HOP STOP!")
        super(BaseJobTask, self).on_failure(exc, task_id, args, kwargs, einfo)


class BaseCeleryTask(celery_app.Task):
    abstract = True
    def on_failure(self, exc, task_id, args, kwargs, einfo):
        task = BaseTask.objects.get(pk=args[0])
        task.save_error("Ошибка выполнения задания")
        super(BaseCeleryTask, self).on_failure(exc, task_id, args, kwargs, einfo)


@celery_app.task(
    soft_time_limit=2,
    base=BaseJobTask,
    ignore_result=False
    )
def search_job(list_key_phrases, list_keywords, dict_key_stems, list_prep, list_keywords_and_prep,
               for_copy, need_aquarelle, stop_words, url):
    try:
      # many code there 
        else:
            log += url + " - ошибка получения содержимого страницы\n"

    except (SoftTimeLimitExceeded, MaybeEncodingError):
        log += url + " - превышение лимита времени обработки (" + traceback.format_exc() + ")\n"
    except WorkerError as e:
        log += e.message
    except Exception as e:
        log += url + " - ошибка обработки страницы (" + traceback.format_exc() + ")\n"

    return {
       ..., 
        'log': log
    }

@celery_app.task(
    queue="ta",
    soft_time_limit=600,
    base=BaseCeleryTask
    )
def do_single_task(task):
    

    try:
        # many code there

        search(task, list_urls, list_key_phrases, list_keywords, dict_key_stem, list_prep)
      

    except MaybeEncodingError as e:
        print "I am Here!!!"
        task.save_error(e)
        task.save_error(traceback.format_exc())
    except SoftTimeLimitExceeded as e:
        print "I am Here SOFT TIME!!!"
        task.save_error(e)
        task.save_error(traceback.format_exc())
    except WorkerError as e:
        task.save_error(e)
        task.save_error(traceback.format_exc())
    else:
        task.set_status("done")

    return None


def search(task, list_urls, list_key_phrases, list_keywords, dict_key_stems, list_prep):
    # some code here 
    group_work = group(search_job.s(...,  url ) for url in list_urls)()

    try:
        with allow_join_result():
            results = group_work.get()

    except MaybeEncodingError:
        print "III UNIC EROR!!!"
        return None
    except SoftTimeLimitExceeded:
        print "III SOFT TIME!!!"
        return None

    perform_and_save_results(task, results)
   
```

## Expected behavior
I expected that one of try/except or on_failure handler will catching a SoftTimeLimitExceeded, but there are error in terminal (see below)

## Actual behavior
[2017-03-15 21:56:42,243: WARNING/MainProcess] Soft time limit (2s) exceeded for seo_work.ta.search_job[d2049088-c32f-4221-9420-639634cc6058]
[2017-03-15 21:56:42,280: ERROR/PoolWorker-2] Task seo_work.ta.do_single_task[3a126eed-ee2f-4deb-89e6-b3653d31a33c] raised unexpected: SoftTimeLimitExceeded('SoftTimeLimitExceeded(True,)',)
Traceback (most recent call last):
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer/seo_work/ta.py", line 701, in do_single_task
    search(task, list_urls, list_key_phrases, list_keywords, dict_key_stem, list_prep)
  File "/home/serhiy/PycharmProjects/text_analyzer/seo_text_analyzer/seo_work/ta.py", line 634, in search
    results = group_work.get()
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/celery/result.py", line 630, in get
    on_message=on_message,
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/celery/result.py", line 744, in join_native
    raise value
Exception: SoftTimeLimitExceeded(True,)
[2017-03-15 21:56:42,298: WARNING/PoolWorker-1] TIME ANALASIS = 0.718394041061
[2017-03-15 21:56:42,303: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: SoftTimeLimitExceeded('SoftTimeLimitExceeded(True,)',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'celery.backends.base.SoftTimeLimitExceeded\'>: it\'s not found as celery.backends.base.SoftTimeLimitExceeded",)''.>
Traceback (most recent call last):
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/billiard/pool.py", line 363, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/serhiy/PycharmProjects/virtualenv/ta/local/lib/python2.7/site-packages/billiard/reduction.py", line 82, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 400, in save_reduce
    save(func)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: SoftTimeLimitExceeded('SoftTimeLimitExceeded(True,)',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'celery.backends.base.SoftTimeLimitExceeded\'>: it\'s not found as celery.backends.base.SoftTimeLimitExceeded",)''.
[2017-03-15 21:56:43,271: WARNING/PoolWorker-4] TIME ANALASIS = 1.00328588486

**Comment by aperezalbela** [comment]
Hello @SerhiyRomanov,

How did you managed to make it work?

**Comment by SerhiyRomanov** [comment]
Hi @aperezalbela !
I did not managed to work this as I expected. I use only try/except block to catch  any error in task.
