### ISSUE TITLE
Calls to Logger.log produce incorrect funcName, module, and filename on the LogRecord

### ISSUE THREAD

**Issue by DylanYoung** [celery/celery#3915]
## Steps to reproduce
Celery v3.2.25 with Django v1.8

No special steps necessary

## Expected behavior
This is obvious, but the funcName, module, and filename logged should be those of the calling function. 

## Actual behavior
Calls to Logger.log, log the wrong funcName, module, and filename.  

The module logged is celery.log (of course just the log part is logged) and the funcName is 'log' (from celery.log).

Logger.warning, error, etc. work as expected. 

Example call: 
`logging.getLogger('arbitrary_logger').log(logging.WARNING, 'Test')`

Example output with format `'%(levelname)s %(asctime)s %(module)s.%(funcName)s:%(lineno)d %(process)d %(thread)d %(message)s'`:
`WARNING 2017-03-15 18:15:43,082 log.log:282 23474 140735235596288 Test`

## Hypothesized Cause:

Celery is proxying the logging call through its own log function. When logging's findCaller then inspects the stack to find the calling function, looking for one that is in a different file from itself, it finds this proxied call and returns correct, but wrong, information.  

Short in short, you can't safely proxy these calls.

**Comment by DylanYoung** [comment]
Closed for what reason?

**Comment by auvipy** [comment]
as the issue is reletad to old version of celery. if you can reproduce it on master will re open it :)

**Comment by DylanYoung** [comment]
Was it fixed? Is there a commit reference? A closed issue should reference a reason for closing it ;) 

The fact that it appears in an old version is only more reason to investigate whether there is a many-years' old bug in the software. 

That said, when we get Celery upgraded, I'll see if I can reproduce.

**Comment by auvipy** [comment]
I will certainly reopen it then for sure :)
