### ISSUE TITLE
celery can not send channels.Group

### ISSUE THREAD

**Issue by Zidoing** [celery/celery#3918]
## Checklist
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
channels==1.0.1
celery==4.0.1
django-celery-beat==1.0.1
django-celery-results==1.0.1

hey man,does celery support channels ? when i send "channels.Group('platform_operation').send(
            {"text": json.dumps({"results": '2'})}) "  to    channels.reply_channel ,but it does worked  although i try many ways,if you have some ideas ,please tell me thank you.

## Steps to reproduce

```
import channels
import time, json
@app.task
def wsTestGateMonitor():
    n = 0
    while True:
        print n
        channels.Group('platform_operation').send(
            {"text": json.dumps({"results": '2'})})
        time.sleep(1)
        if n == 5:
            break
        n += 1
    return n
```
## Expected behavior
 channels.reply_channel  can received the message
## Actual behavior
can'not received

**Comment by thedrow** [comment]
I'm sorry. I don't understand what's the issue here. What seems to be the problem?

**Comment by georgepsarakis** [comment]
@thedrow I think they are using the following Django [package](https://pypi.python.org/pypi/channels).

I believe this question probably belongs to the [channels project](https://github.com/django/channels), not Celery.

**Comment by thedrow** [comment]
Yes, I don't see why there should be a problem with Celery here.
@Zidoing Please comment if you have more details and I'll reopen this issue.
