### ISSUE TITLE
Task over network bug

### ISSUE THREAD

**Issue by NomadDemon** [celery/celery#3923]
celery report -A apps.core

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

result_serializer: 'json'
timezone: 'Europe/Warsaw'
worker_redirect_stdouts_level: 'WARNING'
task_serializer: 'json'
broker_url: 'amqp://myuser:********@myip:5672/myvhost'
enable_utc: True
task_default_queue: 'dev@blog1_celery'
beat_scheduler: 'celery.beat.PersistentScheduler'
accept_content: ['json']
beat_schedule: {
 }
```
Whats the problem? When rabbitMQ and django app are in same machine [vps], everything is ok, but then i start local instance of my app [configured same, but changes ip adresses] there is serialise problem if i put DICT in arguments to task, i says 

`scheduled_task() takes 0 positional arguments but 1 was given`

This problem doesnt exist when running on same machine so i think there is some problem with serialisation? Wasted half day today to debug this, but no success :(

task:
```
@app.task(ignore_result=True, max_retries=3, name='tasks.scheduled_task')
def scheduled_task(params):
	print('called')
	prepare_task(params)
```

```
	eta = datetime.strptime(eta, '%d.%m.%Y %H:%M')
	print(eta)
	scheduled_task.apply_async(args=[params], eta=eta)

```

exactly same code works on vps and not working on my local pc [using vps rabbitmq]
tasks with arguments like:
`	scheduled_task.apply_async(args=[(1,2,3,4),], eta=eta)`
is still 
`scheduled_task() takes 0 positional arguments but 1 was given`

tasks with arguments like:
`	scheduled_task.apply_async(args=[4,], eta=eta)`
is still 
`scheduled_task() takes 0 positional arguments but 1 was given`

BUT
`scheduled_task.delay(params)`
works great on both machines

help please

**Comment by NomadDemon** [comment]
hmm it was "debug =True" problem.

when switched to "prod config" everything was ok, so i was searching which option was bad and thats what it is, is it a bug or it supposed to behave like that?

**Comment by thedrow** [comment]
Hi, I'm sorry it took so long for us to get back to you.
Do you still have the same problem?

**Comment by NomadDemon** [comment]
Hi

I just cancelled my celery stuff. Dont have time right now to develop this app :(

**Comment by auvipy** [comment]
closing for now
