### ISSUE TITLE
Celery workers on different machine from Django webserver

### ISSUE THREAD

**Issue by karesh** [celery/celery#3927]
we are trying to deploy a django project on three nginx web servers with aws ELB. We expect the traffic around 1 million request in 1 minute.

how to architect the system with celery workers on different machine.

1. From Django I need to call the asyn task
2. The different machine act as a broker (redis)
3. celery workers executes the tasks from broker on dedicated server (with the database operation should have db connection)

How can I achieve this. ?

Should I run celeryd worker on each web server?  running the workers inside same machine of web server require CPU from machine will it affect the request time ?
In development we run all on the same machine.

Last question:
From Django webserver we call the tasks then it goes to our separate message broker. then execute the task. (come back to same web server machine where the celery workers are running. ) my question is why we need to run the worker inside same machine again ?
we need to start workers inside django main config. celery --app=config.celery:app worker --loglevel=INFO but on different machine how ?
 
How can I do this in Django web. ?

**Comment by listingmirror** [comment]
You have no reason to run celeryd on the web servers.  Here is what I would do.

1) 1 Shared code base. It has both web Django code, + all the celery tasks.
2) The web nodes run DJango and Nginx. If you want to queue tasks, you run, you do task.delay.. and they get blasted off to the broker. Never run on the web nodes.
3) The backend nodes run celeryd. Add as many as you need. These do all the work.
4) 1 or more Broker nodes to deal with the brokering.
5) 1 node to run celery beat on it, for any scheduled tasks. This does very little work, so I often just combine it with the broker nodes.

**Comment by tyan4g** [comment]
@karesh I got your idea here,
but what if I just run the celery on the web nodes.
for example 
in each node i deploy both django web and celeryd

but all the celeryd connect to the same redis broker.
will this cause the same task excute on diffrent machine??
or it's will only excute once on one node ??

**Comment by rafael-h-ferreira** [comment]
Sorry to comment on a old thread.

@karesh , you said "1 Shared code base". What are you suggesting? A NFS share? Are there any issues with one server accessing pyc files that were compiled by other server?

Thanks

**Comment by shreyiitj** [comment]
> You have no reason to run celeryd on the web servers. Here is what I would do.
> 
> 1. 1 Shared code base. It has both web Django code, + all the celery tasks.
> 2. The web nodes run DJango and Nginx. If you want to queue tasks, you run, you do task.delay.. and they get blasted off to the broker. Never run on the web nodes.
> 3. The backend nodes run celeryd. Add as many as you need. These do all the work.
> 4. 1 or more Broker nodes to deal with the brokering.
> 5. 1 node to run celery beat on it, for any scheduled tasks. This does very little work, so I often just combine it with the broker nodes.

If i want to start celery workers along with the main service then i will have to put those commands in code. should we maintain 2 different config files for main service and celery machine because otherwise workers will get started on nginx machine also and hit the broker.
