### ISSUE TITLE
when dump postgresql's celery_taskmeta result data into file and the file size is huge up to 8GB

### ISSUE THREAD

**Issue by dllhlx** [celery/celery#3928]
hi, I use  postgresql as broker of celery, after a task is fail, then  find a fail task's meta  data  is very strange. So I dump the meta data of this fail task into outfile, the dump command as below:
```
#\o > '/tmp/d.dat'
# select result from celery_taskmeta;
#\q
```
then  i find the file ```d.dat``` 's size too huge, which is up to  7.9 GB, and the file's content is amost blank,  I don't know what happend?

**Comment by dllhlx** [comment]
my celery version is ``` 3.1.25 (Cipater) ```, my celery start command is ``` .venv/bin/celery worker -A applib.celery_app.celery --config applib.celery_config --loglevel=debug --beat ```

**Comment by auvipy** [comment]
plz use latest versions of celery and dont use any relational db as message broaker
