### ISSUE TITLE
"Ensuring a task is only executed one at a time" snippet keeps deleting the lock key

### ISSUE THREAD

**Issue by aatishnn** [celery/celery#3930]
I am referring to the following doc:
http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html

I was going to use this snippet and realized the lock wasn't working. `memcached -vv` displayed the following:

```
<36 add :1:mylockkey 2 600 1 
>36 STORED
<36 delete :1:mylockkey
>36 DELETED
```

As soon as the lock is created, it is being deleted. Maybe, this line is the culprit?

```
# memcache delete is very slow, but we have to use it to take
        # advantage of using add() for atomic locking
        if monotonic() < timeout_at:
```

**Comment by auvipy** [comment]
feel free to send updated code as fix

**Comment by auvipy** [comment]
closing due to lack of feedback.
