### ISSUE TITLE
Celery apply_async broke unicode somehow

### ISSUE THREAD

**Issue by Smosker** [celery/celery#3931]
Version django-celery==3.1.17

I have such an issue, i have a task which serialize data and send it throught request
Then i start task from shell i receive expected result like 
```
my_task("some_id")
{
 'message': u'\\u043f\\u043e\\u0441\\u0442\\u0430\\u0432\\u0438\\u0442\\u044c compression level \\u0442\\u0430\\u043a\\u043e\\u0439 \\u0436\\u0435 \\u043a\\u0430\\u043a \\u0432 \\u043f\\u0440\\u043e\\u0434\\u0430\\u043a\\u0448\\u0435\\u043d\\u0435' 
}
```

But if i send this task to celery i receive:
```
my_task.apply_async(
            args=["some_id"],
            queue='push'
        )
{
 'message': u'????????? compression level ??????? ??????????????' 
}
```

I search web and don't find any information why can this happened, can you help me?

**Comment by Smosker** [comment]
if i should provide any aditional info, please, let me know.

**Comment by georgepsarakis** [comment]
What serializer are you using? Can you share the code of the task function perhaps?

**Comment by Smosker** [comment]
I change my code a little but this didn't help. What i do now (my program is working with commits):
-get commit using https://www.mercurial-scm.org/wiki/MercurialApi
-get commit message  - `ctx.description()`
-get unicode from byte string using
```
def to_unicode(bytestring):
    try:
        return bytestring.decode('utf-8')
    except UnicodeDecodeError:
        try:
            return bytestring.decode('Windows-1251')
        except UnicodeDecodeError:
            result = chardet.detect(bytestring)
            return bytestring.decode(result['encoding'])
```
-store this value im mysql:
`Commit.object.create(message=to_unicode(ctx.description()))`

If i run this task from shell - works perfectly well, i can see proper unicode in my db
by if i run the same task with apply_async, i get broken result like 
u'?????? ???? ?????? pg > yt ? ??????????? ?????????'

**Comment by Smosker** [comment]
Any ideas?

**Comment by Smosker** [comment]
Solve this - just need to start with LANG=ru_RU.UTF-8 argument

**Comment by georgepsarakis** [comment]
Great, thanks for sharing the solution @Smosker .
