### ISSUE TITLE
Django + Redis + Celery - How to handle the connection error for async task when redis or celery worker is down

### ISSUE THREAD

**Issue by jpatel3** [celery/celery#3933]
I am using celery task for some async task like collecting some stats on specific events on the app. e.g. when the search happens, and if there is no result, I catch the data and report it via celery task. 

```
from .tasks import search_analytics
data = {'search': '12345'}
search_analytics.delay(data)

```

However, when redis is down, my celery worker keep throwing -
`ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/0`
which is as expected. 

But in my Django app when making `.delay(data)` call it fails with -
```
lib/python2.7/site-packages/kombu/transport/redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
ConnectionError
```

I can catch the exception and move on with the code, as it's not show stopper for the regular search flow. Is there any way I can handle it other way, as I don't know if it would be wise to add try catch on each task calls across the app and do the same.

**Comment by georgepsarakis** [comment]
Did you try with the [on_failure method](http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-inheritance)?

**Comment by jpatel3** [comment]
I have methods with app decorator like below -

```
@app.task(name='sum-of-two-numbers')
def add(x, y):
    return x + y
```
How it will work in that context? Can I add the base along with name? 

Also, on calling .delay() method it doesn't hit the task at all because celery is not running, `on_failure` seems to be handling if there is a failure inside the task.

**Comment by georgepsarakis** [comment]
You are right. I think your question is covered [here](http://docs.celeryproject.org/en/latest/userguide/calling.html#connection-error-handling).

**Comment by jpatel3** [comment]
Yes. I think in that case it's not much different than what I am doing. Thanks.

Closing it.
