### ISSUE TITLE
celery worker process

### ISSUE THREAD

**Issue by nijojames92** [celery/celery#3941]
Hi 

I'm running the celery tasks in supervisor using shell script. I've given  numprocs=1 in the supervisor config. But the number of celery workers in my EC2 instance is 3. Can you tell me how it spawing the celery worker processes automatically.

**celery.sh**
`PROJECT_ROOT=/home/ubuntu/

. $WORKON_HOME/env/bin/activate

cd $PROJECT_ROOT

celery worker -A tastyspots --loglevel=INFO
`

**supervisor config**

`[program:django-celery]

command=/home/ubuntu/celery.sh

user=ubuntu

numprocs=1

autostart=true

autorestart=true

stderr_logfile=/home/ubuntu/celery-worker.log

stdout_logfile=/home/ubuntu/celery-worker.log
`

If i change the numprocs too then also there is 3 processes. How can i increase or decrease the number of celery process in supervisor

**Comment by listingmirror** [comment]
Have you seen the worker concurrency flag?  

http://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=celeryd#std:setting-worker_concurrency

If you set concurrency to 5.. you should see a total of 6 processes that run. One coordinator process, and then 5 worker process that execute the actual tasks.

**Comment by nijojames92** [comment]
So Supervisor `numprocs`  will not affect the number of celery workers. The number of workers will not increase or decrease based on `numprocs` right?

**Comment by listingmirror** [comment]
@nijojames92  I think supervisor numprocs would multiply things.

I.e. set **worker_cocurrency** to 5
supervisor **numprocs** to 3

I think you have 15 workers?  Try it and see, I have not played with them both together..

**Comment by thedrow** [comment]
Numproc controls how many celery masters will be spawned. This is useful in case you are not using the preforking pool. Any other pool only uses one core so you need to spawn more processes somehow.
Worker concurrency controls how many workers Celery will spawn. By default the preforking pool is used which spawns processes.

**Comment by jerrychong25** [comment]
@nijojames92 @listingmirror @thedrow 

Hi all, 

I have one question to clarify on how to increase Celery concurrency using gevent.

My end faced issue that Celery concurrency always 1, regardless of how I increase cocurrency more than 1 in configuration via Python config file **(Not CLI method)**.

Do I missed out anythings?

Here is my Celery settings output (Output show that concurrency is 1):
```
 -------------- celery@project v4.4.2 (cliffs)
--- ***** -----
-- ******* ---- Linux-5.15.0-56-generic-x86_64-with-glibc2.29 2023-01-13 11:09:12
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         project:0x7fcd17b6caf0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
-------------- [queues]
```

Here is my configuration file:
```
from __future__ import absolute_import, unicode_literals

import os

from celery import Celery
from kombu import Queue
from celery.schedules import crontab

from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')

app = Celery('project', broker='redis://localhost:6379/0')

app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

app.conf.beat_schedule = {
    'task1': {
        'task': 'project.tasks.task1',
        'schedule': 1,
        # 'args': ()
    },
    'task2': {
        'task': 'project.tasks.task2',
        'schedule': 1,
        # 'args': ()
    }
}

app.conf.timezone = 'Asia/Singapore'
app.conf.task_default_queue = 'default'
app.conf.task_queues = (
    Queue('default', routing_key='task.#'),
    Queue('queue', routing_key='queue.#'),
)
app.conf.worker_pool = "gevent"
app.conf.update(
    worker_concurrency=50
)

app.config_from_object('django.conf:settings', namespace='CELERY')

app.autodiscover_tasks()
```

Thank you in advance!
