### ISSUE TITLE
celery.utils.functional.regen doesn't do what it should

### ISSUE THREAD

**Issue by tbazadaykin** [celery/celery#3942]
Description for [regen says](https://github.com/celery/celery/blob/master/celery/utils/functional.py#L173)

> Convert iterator to an object that can be consumed multiple times.

Let's test it:

```
>>> g = (i for i in range(10))
>>> type(g)
<type 'generator'>
>>> from celery.utils.functional import regen
>>> rg = regen(g)
>>> type(rg)
<class 'celery.utils.functional._regen'>
>>> for x in rg:
...     print x
...     
0
1
2
3
4
5
6
7
8
9
>>> for x in rg:
...     print x
...     
>>> print rg
[]
```

```
#:~$ celery report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.9
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

**Comment by auvipy** [comment]
@georgepsarakis was this issue resolved in master?

**Comment by georgepsarakis** [comment]
The given example works as expected with the current master, although no fix has been applied on `celery.utils.functional.regen`. I am not really sure I can reproduce it. @tbazadaykin I am closing this, but if you can give more exact details on how to reproduce this, please feel free to re-open.
