### ISSUE TITLE
What is the difference between rabbitmq consumer and celery worker? both are same?

### ISSUE THREAD

**Issue by amankumarjain** [celery/celery#3943]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

**Comment by georgepsarakis** [comment]
Closing this for now, as Github issues are used mainly for [bug/feature request tracking](http://docs.celeryproject.org/en/latest/getting-started/resources.html#bug-tracker).

Questions can also be asked through the following [channels](http://docs.celeryproject.org/en/latest/community.html).
