### ISSUE TITLE
celery sentinel for result backend

### ISSUE THREAD

**Issue by strawposter** [celery/celery#3945]
In version 4 the support of sentinel is declared.

The configuration example does not contain an explanation of how to transfer the name of sentinel

sentinel: //0.0.0.0: 26379; sentinel: //0.0.0.0: 26380/ ...

There must be something like

sentinel: //0.0.0.0: 26379/mymaster ....

How to correctly set the connection to sentinel?

**Comment by allanlei** [comment]
Try setting `BROKER_TRANSPORT_OPTIONS`.  Something like

```
celery_app.conf.BROKER_TRANSPORT_OPTIONS = {
    'master_name': 'mq',
}
```

It doesn't seem like there is sentinel support for the result backend yet.

**Comment by strawposter** [comment]
kombu.transport.redis.py:
......
Class SentinelChannel (Channel):
......
from_transport_options = Channel.from_transport_options + (
         'Master_name',
         'Min_other_sentinels',
         'Sentinel_kwargs')
......

Additional parameters for sentinel, such as the base number or
password is passed through the dictionary connection_kwargs

Https://github.com/celery/kombu/pull/739
