### ISSUE TITLE
Cannot route separate queues to separate tasks with SQS broker

### ISSUE THREAD

**Issue by zacharynevin** [celery/celery#3947]
### My Setup

- I have two SQS queues:
  - start_task
  - cancel_task

- I have two Celery tasks, each with the same name as the SQS queues:
  - start_task
  - cancel_task

I want to route the `start_task` SQS queue to the `start_task` celery task, and the `cancel_task` SQS queue to the `cancel_task` celery task.

I have a `que/celery.py` file like this:
```
app = Celery('tasks', backend=None)
app.config_from_object({
    broker_url = 'sqs://****:****@',
    broker_transport_options={
        'region': 'us-west-2',
        'visibility_timeout': 30,
        'polling_interval': 30
    }
})

@app.task(bind=True, serializer='json', name='cancel_task')
def cancel_task():
    print "Cancelling task!"

@app.task(bind=True, serializer='json', name='start_task')
def start_task():
    print "Starting task!"
```

These tasks are both part of the same Celery app. I am starting a single Celery worker:
```
celery worker -A que -l info -Q start_task,cancel_task
```

It seems that the SQS queue is not being routed to the task. When I push an example JSON message, I get this error:

```
[2017-03-31 03:44:21,574: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: u'{"hello":"world"}\n' (18b)
{content_type:None content_encoding:None
  delivery_info:{u'sqs_message': <boto.sqs.message.Message object at 0x11ab51bd0>, u'sqs_queue': Queue(https://us-west-2.queue.amazonaws.com/608181464701/grapheq_pending_tasks)} headers={}}
```

Based on this message, it seems that the message doesn't know which task to be directed to. I digged through the source code a bit in `consumer.py`, and found that this seems to happen when the `message.headers` dict is empty, which I presume means that the message being processed doesn't know which task to dispatch.

I also tried putting in custom `task_routes` and then both `task_queues`  and `task_routes`, but nothing seemed to work (no additional errors - just the same thing above).

Here is the result of my `celery -A app report`:
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.11
            billiard:3.5.0.2 sqs:N/A
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled

broker_transport_options: {
    'polling_interval': 30, 'region': 'us-west-2', 'visibility_timeout': 30}
broker_url: u'sqs://***:********@localhost//'
```

**Comment by zacharynevin** [comment]
I think I figured this out actually. I just misunderstood what how celery works. I was pushing raw JSON data to the SQS queue, when I should have been doing `app.apply_async(...)` so that the published message will contain the required information.

**Comment by himalreddy** [comment]
1. Will you send sample code, how you are sending messages.
2. is it possible to directly send message from aws sqs ui to its queue, so that celery will consume
3. how to includes headers part in aws sqs send message manually.
my requirement, i want to send a job to aws sqs queue and it should taken by python celery for execution.

**Comment by bornajelic** [comment]
I have a question. I have a similar situation. I posted it on SO

https://stackoverflow.com/questions/74068093/connect-celery-to-aws-sqs

Anyone had similar experience?
