### ISSUE TITLE
Redis command list

### ISSUE THREAD

**Issue by xavierhardy** [celery/celery#3953]
Could you please document the Redis commands each Celery service uses? This way people could partially secure their Redis instances by removing unused commands.

Thanks

**Comment by afranche** [comment]
@auvipy If this is still needed, I can make a PR to add it to the [Redis Backend](https://github.com/celery/celery/blob/4aefccf8a89bffe9dac9a72f2601db1fa8474f5d/celery/backends/redis.py#L151) class so it would appear [https://docs.celeryproject.org/en/latest/internals/reference/celery.backends.redis.html#module-celery.backends.redis](here). Let me know

**Comment by auvipy** [comment]
feel free
