### ISSUE TITLE
Celery's send_task/delay lost the first message after Broker goes offline

### ISSUE THREAD

**Issue by nachopro** [celery/celery#3957]
I'm using a simple app to verify the problem that I have.

My task `add` append some string to a text file.

When RabbitMQ is running, I achieve this appending from an ipython shell executing `send_task('add', ('my message',))`.

Then I manually stops RabbitMQ and execute `send_task('add', ('a new message',))` in the same ipython session. This execution occurs without trwhoing any exception.

The __'a new messasage'__ never been enqueued and not noticed about this.
In the subsequent send_task calls, an `OperationalError: [Errno 104] Connection reset by peer` is raised, that I properly handling with `try/except`.

How can I avoid this "first message" lost when Rabbit goes offline?

Thanks in advance.

Here a Video showing this issue in Action!
https://www.youtube.com/watch?v=WmAYBkVJk7Q

__tasks.py__

    from celery import Celery

    app = Celery('tasks', broker='amqp://dev:dev@127.0.0.1/')
    
    @app.task
    def add(algo):
        print('Writing "{}" to file'.format(algo))
        open('/tmp/pepe.txt', 'a').write('{}\n'.format(algo))

__ipython shell__ (just after stopping rabbitmq)

    In [1]: from celery import Celery
    
    In [2]: cel = Celery('tasks', broker='amqp://dev:dev@127.0.0.1/')
    
    In [3]: cel.send_task('tasks.add', ('my message 23',))
    Out[3]: <AsyncResult: a2167d23-3190-480b-bdb0-96dd1c98b08c>

  [1]: https://www.youtube.com/watch?v=WmAYBkVJk7Q

**Comment by auvipy** [comment]
sorry for taking soo long to respond! which celery version and settings are you using? did you used py-amqp? it's the recommended client for rabbitmq now

**Comment by auvipy** [comment]
did you tried retry feature?

**Comment by nachopro** [comment]
Hi @auvipy ! I'm using amqp==2.2.2 and celery==4.1.0

Thanks for your time!
