### ISSUE TITLE
Celery worker hung while trying to use LOG.exception

### ISSUE THREAD

**Issue by abhishej** [celery/celery#3959]
## Steps to reproduce
use LOG.exception() functionality from python logging within task code, to print stacktrace for exception caught
## Expected behavior
Stacktrace should be printed in the log file.
## Actual behavior
Celery worker gets stuck(hung) while attempting to write to log

Setup Excerpts:

>celery --app='app:worker_app' report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.6
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

task_queues: 
    (<unbound Queue JobTaskReceiver -> <unbound Exchange task_exchange(topic)> -> slavescheduler.na.na.na.na>,)
include: [u'worker.tasks']
broker_use_ssl: True
task_routes: {
    u'celery_daemons.tasks.execute_slave_task': {   u'exchange': u'task_exchange',
                                                    u'queue': u'JobTaskReceiver',
                                                    u'routing_key': u'********'}}
worker_hijack_root_logger: True
result_expires: 3600
broker_url: u'amqp://guest:********@172.16.2.168:5671//'
route_queues: 
    (<unbound Queue JobQueueReceiver -> <unbound Exchange netra_exchange(topic)> -> slavescheduler.na.na.na.na>,
 <unbound Queue JobTaskReceiver -> <unbound Exchange task_exchange(topic)> -> slavescheduler.na.na.na.na>)

>ps -ef | grep 28256
meridian 28256 27883  0 11:55 ?        00:00:00 /opt/meridian/dc/embedded/bin/python /opt/meridian/dc/embedded/bin/celery worker --autoscale=100,1 --max-tasks-per-child=10 --loglevel=INFO --app=meridian_workers.celeryd.worker.app:worker_app --logfile=/opt/meridian/dc/var/fsdc/logs/meridian-%n%I.log -n executor@%n --without-gossip --without-mingle --without-heartbeat -Ofair

>strace -p 28256 -s 10000
Process 28256 attached
write(2, "2017-04-05 11:55:46,342 - 28256 - snmp_connector - meridian_connectors.snmp_connector - connect - ERROR : 111 - Error connecting to 172.16.2.214 using SNMP\nTraceback (most recent call last):\n  File \"/opt/meridian/dc/embedded/lib/python2.7/site-packages/meridian_connectors/snmp_connector.py\", line 107, in connect\n    self.execute_connect(snmp_info)\n  File \"/opt/meridian/dc/embedded/lib/python2.7/site-packages/meridian_connectors/snmp_connector.py\", line 146, in execute_connect\n    raise e\nConnectionException: Error connecting to 172.16.2.214 using SNMP\n", 558

**Comment by abhishej** [comment]
Another observation, this happens only when celery worker is started using runit

**Comment by georgepsarakis** [comment]
This does not directly seem like an issue with Celery. Could you give more information about your task and logging configuration?

**Comment by thedrow** [comment]
According to the traceback it seems like your task is stuck on I/O which isn't related to celery.
@abhishej Are we correct?
