### ISSUE TITLE
Use callable in utils.functional.head_from_fun

### ISSUE THREAD

**Issue by georgepsarakis** [celery/celery#3964]
After the discussion in #3952, we should investigate whether an improvement can be applied using the builtin `callable` instead of `hasattr(fun, '__call__')`.

https://docs.python.org/2/library/functions.html#callable

**Comment by gabrielsoldani** [comment]
Hi. I'm a new contributor. May I tackle this issue?

**Comment by auvipy** [comment]
yes please, open a PR and ping me for review
