### ISSUE TITLE
parallel `self.replace` tasks cause deadlock

### ISSUE THREAD

**Issue by davidhyman** [celery/celery#3971]
## Checklist
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.6.0
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/1

BROKER_URL: 'redis://localhost:6379/0'
CELERYD_POOL_RESTARTS: True
CELERYD_TASK_SOFT_TIME_LIMIT: 300
CELERYD_TASK_TIME_LIMIT: 360
CELERY_ACCEPT_CONTENT: ['json']
CELERY_RESULT_BACKEND: 'redis://localhost:6379/1'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ROUTES: 
    ([('dyna_map', {'queue': 'dyna'}), ('*', {'queue': 'celery'})],)
CELERY_TASK_SERIALIZER: 'json'
CELERY_TRACK_STARTED: True
```
master@522ef610ea17ae79695e995ddd82d034e8e8bc7a

## Steps to reproduce
```
@apium.task(name='O2O')
def one_to_one(arg):
    result = 2 * arg
    logger.info('o2o %r -> %r', arg, result)
    return result

@apium.task(name='substitute', bind=True)
def substitute(self, arg):
    logger.info('substitute %r', arg)
    arg = ensure_list(arg)
    raise self.replace(group(one_to_one.s(a) for a in arg))

@apium.task(name='O2M')
def one_to_many(arg):
    result = list(range(1, arg + 1))
    logger.info('o2m %r -> %r', arg, result)
    return result

t = tasks.one_to_many.s(5) | tasks.substitute.s()
r = t.delay().get()
```
## Expected behavior
The `substitute` task is ended after submitting the group to the broker. The implication is that a single worker could process all of these tasks without issue.

## Actual behavior
The `substitute` task appears to run for the duration of the group tasks, with behaviour as if it were simply a nested chord waiting on `task.delay().get()`.
The implication is that you may only run as many `substitute` tasks as you have workers. Exceeding that limit results in deadlock (hence the Celery's existing protection from doing `.get()` when already in a task).

## Workaround
Currently I'm running two celery workers listening on different queues where there is at least one more consumer for child tasks than there is for `substitute` ones. Seems to work for now.

---
In my opinion, this behaviour is needed because it would allow us to write one-many-one tasks in complex workflows. It should be decoupled from the number of workers/consumers available. I really hope I'm doing it wrong, because to me, this is the primary functionality of `.replace()`!  In which case, suggestions welcome :)

**Comment by auvipy** [comment]
sorry for taking so long to reply, is this still and issue in new release of master?

**Comment by davidhyman** [comment]
No worries - I'll give it a go soon™️ and get back to you

**Comment by auvipy** [comment]
ok
