### ISSUE TITLE
Plans for next releases?

### ISSUE THREAD

**Issue by mtrofimm** [celery/celery#3974]
Are there any plans for next releases?

**Comment by jclark360** [comment]
wish there was, some serious bugs in 4.0.2, starting up with messages in the queue for one blows up the worker

**Comment by thedrow** [comment]
I'm trying to reach @ask to coordinate.

**Comment by auvipy** [comment]
@thedrow every package deserve a new release

**Comment by thedrow** [comment]
I managed to reach @ask. We need to prepare the release notes and he will publish a new release.

**Comment by dhuang** [comment]
I wrote up release notes in https://github.com/celery/celery/pull/3999.

**Comment by thedrow** [comment]
@celery/umbrella Do not merge anything new to master of this repo until we release please.

**Comment by cp2587** [comment]
any ETA on this ? Would love to see the fix https://github.com/celery/celery/pull/3752 be merged

**Comment by johnatron** [comment]
I second that motion.  An ETA at the very least, please.  Have been waiting patiently for #3620 and #3752 to make their way into a release.

**Comment by Sigurs** [comment]
I second this motion. Need the fix for #3620 .

**Comment by tspecht** [comment]
Any news on when this is happening?

**Comment by michael-k** [comment]
See https://github.com/celery/celery/pull/3752#issuecomment-296977492

**Comment by galuszkak** [comment]
I will greatly appreciate new release 👍 , it's something that we would definitely use.

**Comment by thedrow** [comment]
See #4109
