### ISSUE TITLE
Documentation of ignored results

### ISSUE THREAD

**Issue by mlissner** [celery/celery#3979]
First, on the [canvas page][c] there's currently a warning in the section about chords that indicates that they won't work if you ignore their results. 

There's no such warning about groups, but I believe the same is true for groups, since they need to join until all of the results are in. Can we add such a warning? 

Second, on the [tasks page][t] there's documentation about `ignore_result`, but it makes no mention of which features will fail if you provide that argument to your task. Can we at least outline that `group` and `chord` won't work? 

[c]: http://docs.celeryproject.org/en/3.1/userguide/canvas.html?highlight=CELERY_IGNORE_RESULT

**Comment by georgepsarakis** [comment]
@mlissner perhaps something like:

> **Important:** certain features will not work if task results are disabled. For more details check the Canvas documentation.

**Comment by georgepsarakis** [comment]
Please feel free to open a Pull Request with the documentation update.
