### ISSUE TITLE
Google Cloud Pub/Sub as a Broker - Hypothetically Possible?

### ISSUE THREAD

**Issue by mnadel** [celery/celery#3984]
Does anyone know offhand if using Google Cloud Pub/Sub as a backend broker would definitely not work?

**Comment by auvipy** [comment]
as amazon SQS is possible so gc pbsub should also be possible hypothetically.

**Comment by mnadel** [comment]
Thanks. I was more curious if anyone knew of specific SQS features that Celery is relying upon which might not exist in Pub/Sub.

**Comment by auvipy** [comment]
celery is an asynchronous task queue framework. it use kombu for message tranport. kombu has many broaker. so if you want gc pub/sub to use as celery message broker then you need gc client in kombu.

**Comment by auvipy** [comment]
https://github.com/celery/kombu

**Comment by mnadel** [comment]
Perfect, thanks!
