### ISSUE TITLE
celery (flask) running worker /incorrect name

### ISSUE THREAD

**Issue by ja-heller** [celery/celery#3989]
I've got problems running the celery worker process.
celery version: 4.0.2
python version: 2.7.9

my python code (test.py):

    from __future__ import absolute_import
    from flask import *
    from celery import *

    def main():
        #flask related code
        app = Flask(__name__)
        app.config['CELERY_BROKER_URL'] = 'redis://localhost:6379/0'
        app.config['CELERY_RESULT_BACKEND'] = 'redis://localhost:6379/0'

        celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
        celery.conf.update(app.config)

		@celery.task
		    def my_background_task(arg1, arg2):
		        f = open('file.txt','w')
		        f.write('answer:'+str(arg1))
		        f.close()
		        return 1
    
		@app.route('/createServer', methods=['POST'])
		     def createServer():
		         task = my_background_task.apply_async(args=["test0", "test1"], countdown=10)
		         return jsonify({"status": "done"})

		app.run(host='127.0.0.1', port=8080, debug=True)
     
    if __name__ == "__main__":
        main()

When I run the worker using

    celery worker -A test --broker=redis://127.0.0.1:6379  --loglevel=info

and a new command is inserted I get this error

	[2017-04-22 18:02:09,184: ERROR/MainProcess] Received unregistered task of type u'__init__.my_background_task'.
	The message has been ignored and discarded.

	Did you remember to import the module containing this task?
	Or maybe you're using relative imports?

	Please see
	http://docs.celeryq.org/en/latest/internals/protocol.html
	for more information.

	The full contents of the message body was:
	'[["test0", "test1"], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (93b)
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
	    strategy = strategies[type_]
	KeyError: u'__init__.my_background_task'

What's wrong? It seems like this is because of my main() handling? Any idea how to solve this? Including `absolute_import` as mentioned [http://docs.celeryproject.org/en/latest/userguide/tasks.html#automatic-naming-and-relative-imports](here) doesn't help.

**Comment by thedrow** [comment]
Why aren't you defining the task and the app outside of the `main()` function?
