### ISSUE TITLE
Celery trips over timezone/DST(?), auto-expires short-lived tasks 

### ISSUE THREAD

**Issue by AndreCimander** [celery/celery#4005]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

We are using the current master of celery, kombu, billiard and py-amqp with Python 2.7.

## Steps to reproduce
Setting the timezone to 'Europe/Berlin' leads to a time offset that expires short-lived tasks.

## Expected behavior
Tasks should be executed.

## Actual behavior
Tasks become expired and get revoked. Reverting the timezone to UTC fixes the problem.

Don't ask me about the amount of time, lost data and curses that went into this problem :-)

**Comment by georgepsarakis** [comment]
Could you please check if this is the same issue as the [one](https://github.com/celery/celery/issues/3753) addressed by this [Pull Request](https://github.com/celery/celery/pull/3867)?

**Comment by AndreCimander** [comment]
We are using the master branch @ commit 462d4e57f3825b2c9180f24660bc87115b658ed1, so the patch is already on our production. Switching to UTC doesn't hurt us, but a warning/troubleshoot FAQ would be neat for such cases.

**Comment by auvipy** [comment]
@AndreCimander could you please send a PR with your suggested measures?
