### ISSUE TITLE
Eager mode hides serialization side-effects

### ISSUE THREAD

**Issue by Korijn** [celery/celery#4008]
Running a task in eager mode doesn't pass the arguments through serialization, and therefore hides some of its side-effects. For example, calling a celery task in eager mode with UUID arguments, will leave them as UUIDs, whereas passing them through serialization (with eager mode switched off) converts them to strings. This hid a bunch of bugs in our application code.

Do you agree it would be more reasonable to pass the arguments through the serialization backends, even in eager mode, to have a more consistently behaving API?

**Comment by dperetti** [comment]
Sounds totally crazy but it's true. Passing a native date that I usually need to parse from a string, the date remains native in eager mode, breaking the functionality !

**Comment by charettes** [comment]
Just got it by that as well with a nested data structure containing a non JSON serializable object.

**Comment by alculquicondor** [comment]
Any update on this?

**Comment by charettes** [comment]
FWIW we worked around the issue by making `app.Task` a subclass that performs a round trip when `CELERY_ALWAYS_EAGER is True`.

```python
app = Celery('app')

class EagerSerializationTask(app.Task):
    abstract = True

    @classmethod
    def apply_async(cls, args=None, kwargs=None, *args_, **kwargs_):
        app = cls._get_app()
        if app.conf.CELERY_ALWAYS_EAGER and kwargs_.pop('serialize', True):
            # Perform a noop serialization backtrip to assert args and kwargs
            # will be serialized appropriately when an async call through kombu
            # is actually performed. This is done to make sure we catch the
            # serializations errors with our test suite which runs with the
            # CELERY_ALWAYS_EAGER setting set to True. See the following Celery
            # issue for details https://github.com/celery/celery/issues/4008.
            producer = kwargs.get('producer') if kwargs else None
            with app.producer_or_acquire(producer) as producer:
                serializer = kwargs_.get('serializer', producer.serializer)
                args_content_type, args_content_encoding, args_data = registry.encode(args, serializer)
                kwargs_content_type, kwargs_content_encoding, kwargs_data = registry.encode(kwargs, serializer)
                args = registry.decode(args_data, args_content_type, args_content_encoding)
                kwargs = registry.decode(kwargs_data, kwargs_content_type, kwargs_content_encoding)
        return super(EagerSerializationTask, cls).apply_async(args=args, kwargs=kwargs, *args_, **kwargs_)

app.Task = EagerSerializationTask
```

**Comment by italomaia** [comment]
Just had an issue with it today : / Big problem.

**Comment by jmichalicek** [comment]
I was just debugging this issue myself with passing a datetime.date object and am now wondering how many other places I have passing tests which don't test what is actually happening in real world use.

**Comment by jlward** [comment]
I ran into this issue as well (with celery 4.x). Working on a monkey patch for `apply_async` for tests until this can get handled.

**Comment by Korijn** [comment]
Does anyone of the commenters here have the knowledge, time and motivation to open a PR to remediate this issue?

**Comment by charettes** [comment]
@Korijn I'd happily submit a PR with the above solution if it's deemed appropriate by the maintainers of the project.

**Comment by AlexHill** [comment]
Hi Simon, I've only been a maintainer for about a week, but for what it's worth I support this 100% for calls to `delay` and `apply_async` with ALWAYS_EAGER enabled.

**Comment by jmichalicek** [comment]
I'll see if I can swing some time at work to take a crack at it next week.  Not a ton of free time outside of work this time of year, unfortunately.

**Comment by jmichalicek** [comment]
I was digging a bit myself to understand it all better and, not surprisingly, the conclusion I came to was that I pretty much just needed to drop @charettes' code into `apply_async()` before it calls `self.apply()`.  I do wonder if `apply()` should be doing it instead so that when called directly the data it passes to tasks will be consistent with `apply_async()`.

**Comment by charettes** [comment]
@jmichalicek I think the change should only be done for `delay()`/`apply_async()` because AFAIK `task.apply()` is an equivalent of `task()` and doesn't perform a serialization roundtrip for the sake of preserving provided `args`/`kwargs` identity.

**Comment by AlexHill** [comment]
I agree with leaving the existing behaviour of apply() alone. A patch
should only address the case of using delay() and apply_async() while
always_eager is enabled.

**Comment by jmichalicek** [comment]
@charettes @AlexHill Makes sense if `apply()` is intended to be conceptually different from `apply_async()` beyond just that one is async and the other is not.

I have always thought of them as "do the exact same thing, except one of these runs async in a separate process".  They are calling the same task with the same inputs so to me should pass the same data into the task.  But if I misunderstood the use case, then leaving `apply()` itself alone totally makes sense.  I pretty much never use `apply()`, anyway.  If I wanted it to run inline, I'd just call the function directly - I pretty much always just use the decorator on a function and that is usually just a light wrapper around calling a different function or method.

**Comment by Korijn** [comment]
Looks great to me @charettes! Thanks!

**Comment by alioguzhan** [comment]
Hello Everyone,

Any update on this? I just lost almost 4 hours because of this. Since all tests are passing, i thought it was my code is broken :/

**Comment by georgepsarakis** [comment]
@charettes solution seems to be on the right track. However, I believe it would be better to actually modify `Task.apply`, as it seems more consistent:

```python
from kombu.serialization import registry

def apply(self, args=None, kwargs=None,
               link=None, link_error=None,
               task_id=None, retries=None, throw=None,
               logfile=None, loglevel=None, headers=None, **options):
        """Execute this task locally, by blocking until the task returns.

        ....
        serializer_name = kwargs.get('serializer', app.conf.serializer)
        args = registry.loads(
            registry.dumps(args or (), serializer=serializer_name),
            serializer=serializer_name)
         
        kwargs = registry.loads(
            registry.dumps(kwargs or {}, serializer=serializer_name),
            serializer=serializer_name)
```

I also wonder if by changing `apply` we introduce a backwards incompatible change. Perhaps we can add the above patch in `apply_async` just before calling `apply`, if that makes more sense. @AlexHill what do you think?
