### ISSUE TITLE
Is Celery 5.x already planned?

### ISSUE THREAD

**Issue by giordano91** [celery/celery#4016]
Hi all,
I'm using Celery 3.1.17, and I'd like upgrade it at the latest version (meaning 4.0.2). 
In my application i'm using Python 3.6, and reading the Celery documentation, I have noticed that it's not supported at the moment, but it will be on the next release (5.x).

Is Celery 5.x already planned?

**Comment by auvipy** [comment]
use 4.x

**Comment by thedrow** [comment]
No not currently. We probably need help and funding to get it done.

**Comment by openalmeida** [comment]
> No not currently. We probably need help and funding to get it done.

any progress about that ? branch 5.0-devel seems stopped since year 2016.

p.s feel sorry about i am not able to help.

**Comment by thedrow** [comment]
We simply don't have the time to write the code for it as of yet.
Expect news on that front though.

**Comment by auvipy** [comment]
We are focusing on 4.3 release right now, but have long-standing plan to start work on v5. hopefully after 4.3 release,  this winter.
