### ISSUE TITLE
Is the datastructures.py code correct?

### ISSUE THREAD

**Issue by klahnakoski** [celery/celery#4017]
I am having some difficulty getting Redash to behave on Windows [1].  I believe the problem, on Windows, is caused by a broken call to `celery.conf.update()` [3].  The called code is here [5]:

    def update(self, *args, **kwargs):
         return self.changes.update(*args, **kwargs)

Unfortunately, I can not follow the logic;: The `ConfigurationView` has no instance variable by name of `changes` defined.  It does define a class variable, but even that is not used anywhere else.

Is this code correct?

Thank you!

[1] https://discuss.redash.io/t/celery-worker-fails-why/627

[3] https://github.com/getredash/redash/blob/e6fc73f4440a69351e56e6db4b9c1f07f3970c6e/redash/worker.py#L46
[4] blame for https://github.com/getredash/redash/commit/4caf1ac3d3cf691b3666e933a64df6f18b7d9ec6

[5] https://github.com/celery/celery/blob/214e142e915c2129188d86946da5195b80d7f221/celery/datastructures.py#L498

**Comment by georgepsarakis** [comment]
`changes` attributes is implicitly defined through `__dict__` in the constructor:

```
 self.__dict__.update(changes=changes, ...
```

**Comment by klahnakoski** [comment]
`self.__dict__.update(changes=changes, ...` happens in the constructor, and looks good.  I am referring to the `update()` method that oes not use that same strategy.

A stack trace will not help here, the `update()` code runs fine; it simply has no side effects. Because it has no side effects, the `changes` do not take effect; the configuration is not updated; and redash does the wrong thing.  That's all speculation.  What I am really asking is does the `update()` method do anything?

**Comment by georgepsarakis** [comment]
You can see an [example](http://docs.celeryproject.org/en/latest/userguide/application.html#configuration) in the documentation.

I would suggest that you try to reproduce the initialization steps taken in the project that you are using, but isolated, as in the example that I am referencing.

**Comment by klahnakoski** [comment]
Thank you for your time on this!

It turns out I never knew that Python class variables were accessible through `self`!
