### ISSUE TITLE
The celery document has a mistake about crontab

### ISSUE THREAD

**Issue by HaddyYang** [celery/celery#4020]
## about crontab
the document in this link about crontab simple.
http://docs.celeryproject.org/en/master/userguide/periodic-tasks.html

**crontab(0, 0, day_of_month='2-30/3')**
Execute on every even numbered day.

shuld be 
**crontab(0, 0, day_of_month='2-30/2')**

**Comment by auvipy** [comment]
plz send a fix

**Comment by rthille** [comment]
What's the update period on the posted docs?  I just cloned to issue a PR to fix the `/3` issue here: http://docs.celeryproject.org/en/latest/reference/celery.schedules.html#celery.schedules.crontab and saw that the code was fixed and the issue closed 5 days ago, but the docs are still out of date.

**Comment by rthille** [comment]
Ah, that makes sense.  Thanks @georgepsarakis.

**Comment by clokep** [comment]
I think they're updated each push, you can choose a version in the bottom right hand corner, e.g. for master:

http://docs.celeryproject.org/en/master/reference/celery.schedules.html
