### ISSUE TITLE
"TypeError: Can't convert 'bytes' object to str implicitly" on starting worker (dev branch)

### ISSUE THREAD

**Issue by Vslira** [celery/celery#4024]
Anyone else having this issue?

## Details
Version: Development version installed through pip
Python 3.5.2

## Steps to reproduce
* Uninstalled through pip celery, billiard, kombu, amqp, vine (in this order)
* Install dev version by running
    "pip install https://github.com/celery/*/zipball/master#egg=*" 
    For vine, amqp, kombu, billiard, celery (in order)
    Start a worker (celery worker -A proj)

## Expected behavior
Worker setup

## Actual behavior
I get this error:

> [2017-05-10 14:17:42,015: CRITICAL/MainProcess] Unrecoverable error: TypeError("Can't convert 'bytes' object to str implicitly",)
> Traceback (most recent call last):
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
>     self.blueprint.start(self)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/bootsteps.py", line 370, in start
>     return self.obj.start()
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 320, in start
>     blueprint.start(self)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/consumer/connection.py", line 21, in start
>     c.connection = c.connect()
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 407, in connect
>     conn = self.connection_for_read(heartbeat=self.amqheartbeat)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 414, in connection_for_read
>     self.app.connection_for_read(heartbeat=heartbeat))
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 438, in ensure_connected
>     callback=maybe_shutdown,
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/connection.py", line 405, in ensure_connection
>     callback)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
>     return fun(*args, **kwargs)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/connection.py", line 261, in connect
>     return self.connection
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
>     self._connection = self._establish_connection()
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
>     conn = self.transport.establish_connection()
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
>     conn.connect()
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/connection.py", line 302, in connect
>     self.drain_events(timeout=self.connect_timeout)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/connection.py", line 482, in drain_events
>     return self.blocking_read(timeout)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/connection.py", line 487, in blocking_read
>     return self.on_inbound_frame(frame)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/method_framing.py", line 68, in on_frame
>     callback(channel, method_sig, buf, None)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/connection.py", line 491, in on_inbound_method
>     method_sig, payload, content,
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
>     listener(*args)
>   File "/home/ubuntu/flowcelenv/lib/python3.5/site-packages/amqp/connection.py", line 347, in _on_start
>     self.mechanisms = mechanisms.split(b' ')
> TypeError: Can't convert 'bytes' object to str implicitly

**Comment by honux** [comment]
Bump.
This issue still exists on the development version.

**Comment by cliedeman** [comment]
This happened to me on 2.2.0,

Shouldn't this be logged in the [ampq](https://github.com/celery/py-amqp) repo?

Ciaran

**Comment by Fingel** [comment]
Same, pinning to ampq to 2.1.4 did the trick.

**Comment by diegoraf** [comment]
I had the exactly same problem. Looks like the amqp version 2.2.0 is broken.

**Comment by sp1ze** [comment]
Seems to exist as issue in amqp repo now https://github.com/celery/py-amqp/issues/155

**Comment by bimusiek** [comment]
`ampq==2.2.1` has a fix already, so I recommend using the latest one 👍
