### ISSUE TITLE
Add `add_context_manager()` to workers

### ISSUE THREAD

**Issue by klahnakoski** [celery/celery#4026]
Redash appears to do something that is neccesary, but confusing:

    class ContextTask(TaskBase):
        abstract = True
    
        def __call__(self, *args, **kwargs):
            with current_app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask

https://github.com/getredash/redash/blob/e6fc73f4440a69351e56e6db4b9c1f07f3970c6e/redash/worker.py#L63

This is confusing because the parameter passing is, at best unclear, and at worst hours to debug.  For example, which `self` is being used?  How to you pass bound objects through this call pattern?  Good luck passing `kwargs` with a `self` parameter!

Please let Celery accept a context manager (a class with `__enter__` and __exit__` methods) to all workers.  This will allow Redash, and maybe other Celery users, to 

    class ContextTask(object):
    
        def __int__(self):
            self.ctx=None
    
        def __enter__(self):
            self.ctx = current_app.app_context()
            self.ctx.__enter__()
    
        def __exit__(self, exc_type, exc_val, exc_tb):
            self.ctx.__exit()

    celery.Task.add_context_manager(ContextTask)

The clear interface may also help Redash be less dependent on Celery internal method call patterns.

My apologies if Celery has this already

**Comment by auvipy** [comment]
could you check docs if your suggested features exist? or simply similar

**Comment by auvipy** [comment]
redash is using celery 3.x. could you try latest version of celery and report again?
