### ISSUE TITLE
Too slow celery restart with many deferred tasks

### ISSUE THREAD

**Issue by ivanh03** [celery/celery#4031]
Celery version 3.1.17 (Cipater) and seems that all others behavior the same.

## Steps to reproduce
```
$ celery worker -Ofair --concurrency=32
```

## Expected behavior
Option which can disable this behavior.

## Actual behavior
I actively use deferred tasks, so have about 25000 task in RabbitMQ queue. When celery workers restart in debug log appears ~25000 entries:

```
INFO/MainProcess] Received task: celery.task_name
[4026841c-1d3a-4097-9e43-39b0b81b7b23] eta:[2016-08-11 10:54:16.179000+03:00]
```
Because of large count of registered tasks celery workers can't process new realtime tasks which stay delayed for about 10-15 minutes(approx. current celery restart time).

How can I accelerate restart process?

P. S.: Please, don't suggest me to purge queue before restare, configure limits for workers and so on, I need exactly what I asked. 
Thank you in advance.

**Comment by georgepsarakis** [comment]
I guess you could use different queues for deferred and realtime tasks and start multiple workers, each listening to the corresponding queues. You could also set the task priority.

You can read from the documentation [here](http://docs.celeryproject.org/en/latest/faq.html#does-celery-support-task-priorities) and [here](http://docs.celeryproject.org/en/latest/userguide/calling.html?highlight=priority#routing-options).

**Comment by ivanh03** [comment]
Thanks for your reply. It can help with realtime tasks, but will slow deferred tasks restart(because of limited workers number) which are already very slow. And I want to note that deferred tasks number grow fast in my application so can easily be hundreds of thousands, it's unacceptable if celery start time will stay couple of hours. BTW Rabbitmq in itself designed for millions deferred tasks on commodity hardware and I can't imagine that celery can be such tidy bottleneck for application.
I believe that there must be a way for disable task registering during celery start.

**Comment by hardikbansal** [comment]
I am facing the same issue. Whenever I restart celery, it takes took much time to register tasks. Is there any way to avoid it?

One solution that has worked for me is by giving HUP signal to the worker process and restarting it rather than restarting the main processes. But that will work for prefork only.

What should I do in case of eventlet? Also, what if for some reason I need to restart the machine completely or restart the Mainprocesses. How can i not register all tasks at once, so that tasks get their time to get executed even during startup time.

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/4031#issuecomment-301893554 after reading this, can you please provide more detaill?

**Comment by hardikbansal** [comment]
Yes I agree, that I can separate these two things, but what I am worried about most is that, if at some point of time, I have too many tasks to handle, it might take very very long to even register tasks. At the point of time, will it hinder the performance of even deferred tasks?
