### ISSUE TITLE
celery.task.backend_cleanup doesn't seem to honor the value of CELERY_TASK_RESULT_EXPIRES

### ISSUE THREAD

**Issue by hezbucho** [celery/celery#4050]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

```
> celery report

software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.12
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:db+postgresql://username:**@host/db_name

CELERY_TASK_RESULT_EXPIRES: 604800
```

## Steps to reproduce
I set `CELERY_TASK_RESULT_EXPIRES` to 1 week i.e. `604800` based on the [docs](http://docs.celeryproject.org/en/3.1/configuration.html#celery-task-result-expires) so that my task results are persisted for up to 1 week 

## Expected behavior
Celery beat executes everyday and clears task results older than 1 week

## Actual behavior
Celery beat executes everyday and clears task results older than 12 hours

**Comment by zhiyuli** [comment]
I am having this issue as well. I set CELERY_TASK_RESULT_EXPIRES (also tried 'result_expires') to 0 to persist all result records, but they still got deleted after about 24 hours (4.1.0 doc says default value is 1 day). I am not sure it is a celery issue? django result backend issue? or incorrect settings I did.

My development stack: celery 4.1.0 +django 1.9.13 + django-celery-beat 1.0.1 + django-celery-results 1.0.1

**Comment by cmoiccool** [comment]
Same problem here.
The workaround i have used for this problem is to force the result_expires configuration in my project celery.py file in my case after one hour (3600 seconds):

```
app.config_from_object(settings, namespace='CELERY')
app.conf.result_expires = 3600
```

**Comment by auvipy** [comment]
try to use the latest versions of the dependencies and verify on top of celery master branch. closing conditionally for now

**Comment by killua8p** [comment]
I had the same issue with Django + Celery setup. And I managed to work it out.
For future explorers: the document is wrong -- the setting name should be `CELERY_RESULT_EXPIRES` instead of `CELERY_TASK_RESULT_EXPIRES`

**Comment by georgepsarakis** [comment]
@killua8p that sounds correct. Would you perhaps like to contribute the change to the documentation?

**Comment by killua8p** [comment]
@georgepsarakis I'd love to, if only I know how to 😝

**Comment by alokgogate** [comment]
Hi @auvipy , can you please check the above code and guide?

**Comment by gainskills** [comment]
> @killua8p that sounds correct. Would you perhaps like to contribute the change to the documentation?

submit PR: https://github.com/celery/celery/pull/6429

**Comment by lambda-yu** [comment]
in celery you should like this:
CELERY_TASK_RESULT_EXPIRES = timedelta(seconds=1)

**Comment by JZoares** [comment]
> I use redis as the backend_Results. Tried to check the TTL of the key in redis and it shows 24hrs when i had set the parameter `CELERY_RESULT_EXPIRES=10` i.e. 10 seconds. Even tried with parameter `CELERY_TASK_RESULT_EXPIRES=10` and that too didnt work.
> 
> I am using it with a flask application. Following is the code: **app.py**
> 
> ```
> import os
> import random
> import time
> from flask import Flask, request, render_template, session, flash, redirect,url_for, jsonify
> from celery import Celery
> from celery.result import AsyncResult  
> import celery.states as states
> from datetime import datetime,date,timedelta
> 
> 
> 
> app = Flask(__name__)
> 
> app.config['SECRET_KEY'] = 'top-secret!'
> 
> # Celery configuration
> app.config['CELERY_BROKER_URL'] = 'redis://localhost:6379/0'
> app.config['CELERY_RESULT_BACKEND'] = 'redis://localhost:6379/1'
> app.config['CELERY_TASK_RESULT_EXPIRES'] = timedelta(seconds=10)
> app.config['CELERY_RESULT_EXPIRES'] = 10
> #app.config.CELERY_RESULT_EXPIRES = 5
> 
> 
> # initialization of celery
> 
> celery = Celery('task', broker=app.config['CELERY_BROKER_URL'])
> app.config_from_object(settings, namespace='CELERY')
> #celery.conf.result_expires = 60
> #celery = Celery('task', broker=app.config['CELERY_BROKER_URL'])
> celery.conf.update(app.config)
> celery.config_from_object(settings,na)
> @app.route('/longtask', methods=['POST'])
> def longtask():
>     features = request.get_json()
>     #task = add.apply_async(args=[features['a'],features['b']])
>     task = celery.send_task('mytasks.add',args=[features['a'],features['b']],task_id=features['task_id'])
>     print(task)
>     return jsonify('task id',task.id)
>     #return jsonify({}), 202, {'Location': url_for('taskstatus',task_id=task)}
> 
> @app.route('/check/<string:id>')
> def check_task(id):  
>     res = celery.AsyncResult(id)
>     print(res.state)
>     #return jsonify(res.state)
>     return res.state if res.state==states.PENDING else str(res.result) + str(res.state)
> 
> 
> 
> if __name__ == '__main__':
>     app.run(debug=True,port=5000,host='0.0.0.0')
> ```
> 
> **task.py**
> 
> ```
> from celery import Celery
> import time
> 
> celery = Celery('tasks', backend='redis://localhost:6379/1',
> broker='redis://localhost:6379/0')
> 
> def calc(x,y):
> 	return x+y
> 
> @celery.task(name='mytasks.add')
> def add(x, y):
> 	#time.sleep(10)
> 	abc = calc(x,y)
> 	return abc
> ```

Did you eventually get it to work? I've tried all the combinations possible and didn't notice any change on the time that the result is available.

**Comment by lindenb1** [comment]
???

```
@app.task(name="Delete outdated Task results", queue='platform')
def delete_old_task_results(days_to_keep=1):
    """
    A Celery task to delete task results older than a specified number of days.
    """
    threshold_date = datetime.now() - timedelta(days=days_to_keep)
    TaskResult.objects.filter(date_done__lt=threshold_date).delete()
```

All problems solved ...
