### ISSUE TITLE
celery mysql connect error

### ISSUE THREAD

**Issue by huakairuoxiangxi** [celery/celery#4056]
## Checklist

- [ ] I have included the output of ``celery -A xxx beat -l info -S django`` in the issue.
celery==4.0.2
today i update mysql to 5.7.18, but i use this command
 ``celery -A xxx beat -l info -S django`` 
error message
```
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```
when i use mysql 5.6 , it's all ok.

**Comment by georgepsarakis** [comment]
This issue does not seem related to Celery. Are you sure that your database configuration is correct?
