### ISSUE TITLE
celery.accumulate inconsistent behavior

### ISSUE THREAD

**Issue by mittagessen** [celery/celery#4060]
My code replaces a head task with a group containing a variable number of subtasks. This works fine but unfortunately ``celery.accumulate`` does not accumulate the output of a group containing a single task. Sample code:

```
from celery import Celery
from celery import signature, group, chain

app = Celery('tasks', broker='redis://', backend='redis://')

@app.task
def task_1():
    return [1, 2]

@app.task
def task_2():
    return [3, 4]

@app.task(bind=True)
def repl_1(self):
    raise self.replace(group([task_1.si()]))

@app.task(bind=True)
def repl_2(self):
    raise self.replace(group([task_1.si(), task_2.si()]))
```

Output:

```
>>> test.repl_1.apply_async().get()
[1, 2]
>>> res = test.repl_2.apply_async().get()
[[1, 2], [3, 4]]
```

This is somewhat annoying as 1. it is inconsistent and 2. I'm chaining the repl_* tasks requiring me to somehow find out the number of tasks run in a previous step of the chain to know what input to expect (some tasks return a nested list and there is no way to find out if it is the result of ```celery.accumulate``` or a legitimate task.

Expected output is:

```
>>> test.repl_1.apply_async().get()
[[1, 2]]
>>> res = test.repl_2.apply_async().get()
[[1, 2], [3, 4]]
```

**Comment by auvipy** [comment]
what version and setting of celery are you using

**Comment by auvipy** [comment]
closing as lack of feedback
