### ISSUE TITLE
Celery worker hang 15 minutes after a while

### ISSUE THREAD

**Issue by boyjemmy** [celery/celery#4062]
We use celery/redis to run some simple quick tasks, and we found after the worker idle for some time, it takes about 15 minutes to finish one task, I can see the worker received the task and see the task actually runs, but it take 15 minutes to get the task to complete and start the next task in the chain, this will also cause issue to enqueue the task, which takes about 15 minutes as well.

We use celery 4.0.2, kombu 4.0.2, redis 2.10.5, redis is used for broker and backend

Below are some sample logs

2017-05-31 10:01:30  Received task XXXX..............
2017-05-31 10:01:30  ****Internal task log that indicate the job actually complete
2017-05-31 10:16:53  task XXX succeeded in 926.89s

## Steps to reproduce
Create some small tasks and chain them
run celery worker with -Ofair option

## Expected behavior
Job finish quickly after receiving the task

## Actual behavior
The task runs, but it take 15 minutes to get the succeeded msg and start the next task in the chain

**Comment by imanhodjaev** [comment]
@boyjemmy I have the same situation here, when worker stucks on `wait` and suddenly wakes up after about an hour and works for the same amount of time then hangs again.
I tried to make connection pooling recycle workers after 10 tasks processed etc. but it didn't help also there are quite a few issues related to this topic.

**Comment by noamher** [comment]
I get the same behavior with celery 3.1.25 (rabbitmq broker, redis result backend).
After a few hours without new tasks, when a new task is created it takes ~15 minutes for the workers (which are not doing anything at the time) to consume the tasks from rabbitmq and change the tasks' state to un-acked (I use acks_late).

**Comment by thedrow** [comment]
Can you please try to upgrade to 4.1? We've resolved a lot of these issues.

**Comment by auvipy** [comment]
report if upgrading to 4.1+ don't resolve this type of issues.
