### ISSUE TITLE
Is there any way to get message_count from task-request in celery worker

### ISSUE THREAD

**Issue by chainly** [celery/celery#4064]
I want to know how many messages remains in `current queue` before I deal with new message in `celery worker`. The  `message_count` attribute in `message` help me easy to do that
```
[{u'exchange': u'',
  u'message_count': 8,
  u'payload': u'',
  u'payload_bytes': 0,
  u'payload_encoding': u'string',
  u'properties': {u'delivery_mode': 1, u'headers': {}, u'priority': 11111},
  u'redelivered': False,
  u'routing_key': u'test'}]
```
,but I can't get it from [task-request.delivery_info](
http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-request):
```
{u'priority': None,
 u'redelivered': False,
 u'routing_key': u'test',
 u'exchange': u''}
```
why can't get or remove `message_count`  from `task-request.delivery_info`?

**Comment by georgepsarakis** [comment]
Please check this [issue](https://github.com/celery/kombu/issues/422#issuecomment-300684422) and related comments.

**Comment by chainly** [comment]
@georgepsarakis  Thanks firstly! 
 I know there are lots of way to get `queue`'s info with `Broker's API`, but that not what I wanted.
I want to know why can't I get  `message_count` directly from `task-request.delivery_info` just like `exchange, redelivered etc.`
