### ISSUE TITLE
Too many connections in my redis?

### ISSUE THREAD

**Issue by JasonLZJ** [celery/celery#4068]
Hi I use celery version == 3.0.18, 
There are too many connections in my broker,
I find each  worker have 5 or even more connections for redis.
I use celery -c 1 , only 1 process exist.
What can I do to reduce connection numbers?
I use BROKER_POOL_LIMIT or CELERY_REDIS_MAX_CONNECTIONS it do not work for me.
thanks

**Comment by thedrow** [comment]
@auvipy Do you have an interest in resolving this? If not, please close as we'd rather not support 3.x anymore.

**Comment by auvipy** [comment]
sorry you could't provide support for celery 3.x branch... please consider and upgrade to 4.1 or upcoming 4.2 release. I will focus more on future v5 of celery
