### ISSUE TITLE
tasks being created with same task_id in queue

### ISSUE THREAD

**Issue by suygarg** [celery/celery#4070]
I am using Django-celery and Redis backend to push the tasks in celery queue. I am pushing tasks with same custom task_id in the queue. The documentation says that task_id is UUID which should be unique. But I am able to add more than one task with the same task_id in the queue. It is expected that it should raise an exception if a task with the same task_id is already there in the queue.

```
@task
def register_task(a, b):
    print a + b

@task
def deregister_task(a, b, c):
    print a + b + c

taskid=str(UUID(md5('test').hexdigest()))
register_task.apply_async(args=('hello', 'world'), task_id=taskid, countdown=60)
deregister_task.apply_async(args=('sample', 'hello', 'world'), task_id=taskid, countdown=60)
i = inspect()
i.scheduled()

{u'celery@Suyashs-MacBook-Pro.local': [{u'eta': u'2017-06-05T17:15:33.947002',
   u'priority': 6,
   u'request': {u'acknowledged': False,
    u'args': u"('sample', 'hello', 'world')",
    u'delivery_info': {u'exchange': u'celery',
     u'priority': 0,
     u'redelivered': None,
     u'routing_key': u'celery'},
    u'hostname': u'celery@Suyashs-MacBook-Pro.local',
    u'id': u'098f6bcd-4621-d373-cade-4e832627b4f6',
    u'kwargs': u'{}',
    u'name': u'flight.tasks.deregister_task',
    u'time_start': None,
    u'worker_pid': None}},
  {u'eta': u'2017-06-05T17:15:44.234537',
   u'priority': 6,
   u'request': {u'acknowledged': False,
    u'args': u"('hello', 'world')",
    u'delivery_info': {u'exchange': u'celery',
     u'priority': 0,
     u'redelivered': None,
     u'routing_key': u'celery'},
    u'hostname': u'celery@Suyashs-MacBook-Pro.local',
    u'id': u'098f6bcd-4621-d373-cade-4e832627b4f6',
    u'kwargs': u'{}',
    u'name': u'flight.tasks.register_task',
    u'time_start': None,
    u'worker_pid': None}}]}


```

**Comment by georgepsarakis** [comment]
Celery used the [uuid4](https://docs.python.org/2/library/uuid.html#uuid.uuid4) Python built-in to generate the random UUID, which has several guarantees of being unique. I cannot see how the check for duplicate task IDs could happen (and actually I cannot see the *why* too); Celery would have to load all messages to check if another one with the same ID exists. Remember that messages are being stored in a queue structure. 

If you are explicitly setting the task identifier and do not somehow efficiently randomize it among task instances, then it should be expected that you will end up with the same task ID multiple times.
