### ISSUE TITLE
Instructions for getting Celery 4.0 to run under Windows

### ISSUE THREAD

**Issue by SPKorhonen** [celery/celery#4082]
## In summary:

For anyone wanting to run Celery 4.x series on Windows, I can report that it is possible with following patches:

- celery/billiard#225
- celery/py-amqp#136
- #4078 

Hopefully we can get them integrated into their respective libraries so that vanilla pypi versions can be used instead of patched versions.

**Comment by auvipy** [comment]
http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#removed-features

**Comment by auvipy** [comment]
most likely we can continue the windows support

**Comment by SPKorhonen** [comment]
I thin k that it should be possible to find enough volunteers to maintain at least on unofficial support for Windows. My issue was mostly intended to guide people trying to run Celery 4.x on Windows to correct patches to allow continued use of Windows. It is much easier if one can find a recipe with minimal googling.

**Comment by auvipy** [comment]
I as a core team member will support the efforts for sure. by the time ask made the decision, there were serious lack of active contributors/maintainers.

**Comment by ambsw-technology** [comment]
In case others end up here (as a top Google search), the `eventlet` solution [suggested here](https://stackoverflow.com/a/47331438) fixed my issues running celery 4.1 on Windows.
