### ISSUE TITLE
Attributes are shared across multiple workers when using gevent pool

### ISSUE THREAD

**Issue by mehdigmira** [celery/celery#4089]
My version of celery is 4.0.2 (latentcall)

## Example that works fine (using a subprocess pool for the worker):

```python
# tasks/tasks.py

#from gevent import monkey
#monkey.patch_all()
from celery import Celery
from time import sleep
from celery import Task


app = Celery('tasks', broker='redis://localhost:6379/0')


class TestTask(Task):
    def run(self):
        self.x = []
        for t in range(10):
                self.x.append(t)
                sleep(1)
                print self.x

app.register_task(TestTask())
```
```python
# run.py

from celery import Celery
from tasks import TestTask
app = Celery('tasks', broker='redis://localhost:6379/0')
for x in range(5):
        app.send_task("tasks.tasks.TestTask")
```

Then running `celery -A tasks worker -c 4 -l DEBUG` outputs (as expected):

> [2017-06-15 09:48:14,552: WARNING/PoolWorker-2] [0]
> [2017-06-15 09:48:14,552: WARNING/PoolWorker-1] [0]
> [2017-06-15 09:48:14,558: WARNING/PoolWorker-4] [0]
> [2017-06-15 09:48:14,558: WARNING/PoolWorker-3] [0]
> [2017-06-15 09:48:15,554: WARNING/PoolWorker-2] [0, 1]
> [2017-06-15 09:48:15,554: WARNING/PoolWorker-1] [0, 1]
> [2017-06-15 09:48:15,559: WARNING/PoolWorker-3] [0, 1]
> [2017-06-15 09:48:15,559: WARNING/PoolWorker-4] [0, 1]
> [2017-06-15 09:48:16,556: WARNING/PoolWorker-1] [0, 1, 2]
> [2017-06-15 09:48:16,556: WARNING/PoolWorker-2] [0, 1, 2]
> [2017-06-15 09:48:16,560: WARNING/PoolWorker-4] [0, 1, 2]
> [2017-06-15 09:48:16,560: WARNING/PoolWorker-3] [0, 1, 2]
> [2017-06-15 09:48:17,558: WARNING/PoolWorker-1] [0, 1, 2, 3]
> [2017-06-15 09:48:17,558: WARNING/PoolWorker-2] [0, 1, 2, 3]
> [2017-06-15 09:48:17,561: WARNING/PoolWorker-4] [0, 1, 2, 3]
> [2017-06-15 09:48:17,562: WARNING/PoolWorker-3] [0, 1, 2, 3]
> [2017-06-15 09:48:18,559: WARNING/PoolWorker-1] [0, 1, 2, 3, 4]
> [2017-06-15 09:48:18,559: WARNING/PoolWorker-2] [0, 1, 2, 3, 4]
> [2017-06-15 09:48:18,563: WARNING/PoolWorker-4] [0, 1, 2, 3, 4]
> [2017-06-15 09:48:18,563: WARNING/PoolWorker-3] [0, 1, 2, 3, 4]
> [2017-06-15 09:48:19,561: WARNING/PoolWorker-1] [0, 1, 2, 3, 4, 5]
> [2017-06-15 09:48:19,561: WARNING/PoolWorker-2] [0, 1, 2, 3, 4, 5]
> [2017-06-15 09:48:19,565: WARNING/PoolWorker-3] [0, 1, 2, 3, 4, 5]
> [2017-06-15 09:48:19,565: WARNING/PoolWorker-4] [0, 1, 2, 3, 4, 5]
> [2017-06-15 09:48:20,562: WARNING/PoolWorker-1] [0, 1, 2, 3, 4, 5, 6]
> [2017-06-15 09:48:20,562: WARNING/PoolWorker-2] [0, 1, 2, 3, 4, 5, 6]
> [2017-06-15 09:48:20,566: WARNING/PoolWorker-4] [0, 1, 2, 3, 4, 5, 6]
> [2017-06-15 09:48:20,566: WARNING/PoolWorker-3] [0, 1, 2, 3, 4, 5, 6]
> [2017-06-15 09:48:21,564: WARNING/PoolWorker-2] [0, 1, 2, 3, 4, 5, 6, 7]
> [2017-06-15 09:48:21,564: WARNING/PoolWorker-1] [0, 1, 2, 3, 4, 5, 6, 7]
> [2017-06-15 09:48:21,567: WARNING/PoolWorker-3] [0, 1, 2, 3, 4, 5, 6, 7]
> [2017-06-15 09:48:21,567: WARNING/PoolWorker-4] [0, 1, 2, 3, 4, 5, 6, 7]
> [2017-06-15 09:48:22,566: WARNING/PoolWorker-2] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [2017-06-15 09:48:22,566: WARNING/PoolWorker-1] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [2017-06-15 09:48:22,569: WARNING/PoolWorker-3] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [2017-06-15 09:48:22,569: WARNING/PoolWorker-4] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [2017-06-15 09:48:23,567: WARNING/PoolWorker-2] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> [2017-06-15 09:48:23,568: WARNING/PoolWorker-1] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Example that doesn't work fine (using a gevent pool):

Just changing tasks.py to make it gevent friendly
```python
# tasks/tasks.py

from gevent import monkey
monkey.patch_all()
from celery import Celery
from time import sleep
from celery import Task


app = Celery('tasks', broker='redis://localhost:6379/0')


class TestTask(Task):
    def run(self):
        self.x = []
        for t in range(10):
                self.x.append(t)
                sleep(1)
                print self.x

app.register_task(TestTask())
```
and then running `celery -A tasks worker -c 4 -l DEBUG -P gevent` outputs:

> [2017-06-15 09:49:35,825: WARNING/MainProcess] [0]
> [2017-06-15 09:49:35,826: WARNING/MainProcess] [0, 1]
> [2017-06-15 09:49:35,826: WARNING/MainProcess] [0, 1, 1]
> [2017-06-15 09:49:35,830: WARNING/MainProcess] [0, 1, 1, 1]
> [2017-06-15 09:49:36,826: WARNING/MainProcess] [0, 1, 1, 1, 1]
> [2017-06-15 09:49:36,826: WARNING/MainProcess] [0, 1, 1, 1, 1, 2]
> [2017-06-15 09:49:36,827: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2]
> [2017-06-15 09:49:36,832: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2]
> [2017-06-15 09:49:37,830: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2]
> [2017-06-15 09:49:37,831: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3]
> [2017-06-15 09:49:37,831: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3]
> [2017-06-15 09:49:37,833: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3]
> [2017-06-15 09:49:38,834: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
> [2017-06-15 09:49:38,834: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4]
> [2017-06-15 09:49:38,835: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4]
> [2017-06-15 09:49:38,835: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4]
> [2017-06-15 09:49:39,840: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]
> [2017-06-15 09:49:39,840: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5]
> [2017-06-15 09:49:39,841: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5]
> [2017-06-15 09:49:39,841: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5]
> [2017-06-15 09:49:40,841: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]
> [2017-06-15 09:49:40,841: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6]
> [2017-06-15 09:49:40,842: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6]
> [2017-06-15 09:49:40,842: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6]
> [2017-06-15 09:49:41,843: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6]
> [2017-06-15 09:49:41,843: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7]
> [2017-06-15 09:49:41,844: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7]
> [2017-06-15 09:49:41,844: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7]
> [2017-06-15 09:49:42,849: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7]
> [2017-06-15 09:49:42,849: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8]
> [2017-06-15 09:49:42,850: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8]
> [2017-06-15 09:49:42,850: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8]
> [2017-06-15 09:49:43,854: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8]
> [2017-06-15 09:49:43,854: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9]
> [2017-06-15 09:49:43,855: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9]
> [2017-06-15 09:49:43,855: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9]
> [2017-06-15 09:49:44,859: WARNING/MainProcess] [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]

As you can see the self.x attribute gets shared across all the gevent workers running at the same time, which is absolutely not what i want !

**Comment by mehdigmira** [comment]
This is in my opinion a major bug, and It caused me a lot of trouble, because my tasks in production were silently not doing what they're supposed to.
If this a _design decision_ (which i think would be very weird), i think it should be stated **very clearly** in the celery docs.

**Comment by maratkomarov** [comment]
Prefork pool spawns separate processes, while gevent pool spawns greenlets, all within the same process. You'll experience the same "bug" with `threading` or `eventlet` concurrency modules. 

If you need to isolate task data you might consider `threading.local` / `gevent.local`.

**Comment by mehdigmira** [comment]
Yes I'm aware of the difference with Prefork. Still I think a task's behaviour shouldn't depend on wether it's running within a gevent, a threading or multiprocesses pool.
I think there should be one Task instance per running task whatever concurrency pool you're using.
I don't think using gevent.local whenever you want to share data is the right solution to this.

This is what I've been using since i've noticed this problem:

```python
@celery_app.task(name="test")
def test(x, y):
  test_logic = TestLogic()
  result = test_logic.run()
  # do some retry logic depending on result

class TestLogic(object):
  def __init__():
    pass
  def run():
    pass
```
