### ISSUE TITLE
Celery 3.1.25 concurrency does not work in CentOS 7.1.1503

### ISSUE THREAD

**Issue by mrabhiram** [celery/celery#4095]
Hi , I am working on a flask application which spawns background processes. They are supposed to run for longer times. 
It should more than 64 background tasks parallely.  

`celery -A cTasks worker --loglevel=info --concurrency=64`

This above is how I run celery. 
I can see 64 processes spawning when I inspect
` celery -A celeryTasks inspect stats`

But only two processes run. The other 62 are not running ever. 
I guess due to two cores, it is running two processes. Concurrency=64 does not seem to work.

Kindly, through some light on how to use concurrency with Celery 3.1.25 and CentOS 7.1.1503

**Comment by georgepsarakis** [comment]
Could you please explain more how you are viewing the two forked processes in the system? Using `ps uxa`  perhaps?

**Comment by mrabhiram** [comment]
ps -ef | grep celery is the command . I can see 64 child processes created.
celery -A celeryTasks inspect stats . This command also states that 64 workers are there.
ps auww | grep celery . This command shows only two workers.

I wanted to know if the default nature of celery is to run parallel when .delay() is called number of times?

Is this correct?

**Comment by georgepsarakis** [comment]
If you are observing only two active processes on a two-core server, when inspecting the process list, this would make sense. To answer your question, each worker process will consume a task instance queued using `.delay()` as you mention.

**Comment by mrabhiram** [comment]
Okay, If I need 64 tasks to be running parallely and independently, what would you suggest for that nature of celery execution?

**Comment by georgepsarakis** [comment]
It depends on the type of the task, is it CPU-bound or I/O-bound?

**Comment by mrabhiram** [comment]
It writes reads from server and writes data to redis server. Although, it is not huge data. We need it to keep running.

**Comment by georgepsarakis** [comment]
Sounds like I/O bound workload, have you perhaps also noticed the CPU load on the server at any given time? If CPU load is not an issue, you could increase the option `--prefetch-multiplier` to a larger value e.g. 32.

**Comment by mrabhiram** [comment]
CPU also seems pretty loaded. These are the tasks which run inevitably, to transfer data(64 different processes). Would this command be optimal ?

celery -A cTasks worker --loglevel=info --concurrency=64 --prefetch-multipliier=32

**Comment by georgepsarakis** [comment]
If CPU usage is high (80-90%), nothing can be done by modifying Celery worker settings, you will need more resources on the server.

**Comment by mrabhiram** [comment]
If CPU usage is maintained, then would above command be okay? Or could you suggest a command which runs tasks parallely.

**Comment by georgepsarakis** [comment]
@mrabhiram I believe the command I gave in my comment above is fine, but you should consider increasing CPU resources on the server if you want to gain on concurrency. I am closing this now, but feel free to re-open if you need further help.
