### ISSUE TITLE
RuntimeErrorkombu.connection in acquire ; Acquire on closed pool

### ISSUE THREAD

**Issue by rishabh18** [celery/celery#4098]
## Checklist
Using following versions of services
kombu==4.0.2
celery==3.1.18
django-celery==3.1.16
amqp==2.1.4

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Actual behavior
Connection is getting closed while serving the tasks , and throwing error as Acquire on closed pool

**Comment by auvipy** [comment]
could you verify this with new releases or on master?
