### ISSUE TITLE
link_error argument of apply_async doesn't work as documented

### ISSUE THREAD

**Issue by jobec** [celery/celery#4099]
## Checklist
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.3
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/
```

The documentation about linking tasks at http://docs.celeryproject.org/en/master/userguide/calling.html#linking-callbacks-errbacks doesn't work. It also doesn't match the documentation at http://docs.celeryproject.org/en/master/userguide/canvas.html#chains => "Here's an example errback..." which does work.

## Steps to reproduce
Follow the code example for linking tasks at http://docs.celeryproject.org/en/master/userguide/calling.html#linking-callbacks-errbacks

## Expected behavior
Prints the error and traceback

## Actual behavior
produces a `RuntimeError: Never call result.get() within a task!` exception.

**Comment by henribru** [comment]
Looks like the docs weren't fully updated after https://github.com/celery/celery/commit/ae3f36f7dadde455098963ecdada12b043fdfe41
