### ISSUE TITLE
Celery maintainers not documented

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#4100]
I am interested in knowing who are the current maintainers for the Celery projects. I thought that information would be on this page:  http://www.celeryproject.org/docs-and-support/

I also tried to look at the github repo, but github does not make that information public.

Can someone write out on this ticket who the current maintainers are for Celery? Then with that information, a documentation update can be prepared.

**Comment by jobec** [comment]
How about https://github.com/celery/celery/graphs/contributors ?

**Comment by bmbouter** [comment]
Thanks @jobec. That is a good list of all committers, but I'm looking for the project owners. Besides code contributions, who is leading the project currently? The motivation is that, as I understand it, @ask has stepped back (no judgement) and transitioned some others to be project owners perhaps temporarily or permanently. I'm just not sure who to ask questions to these days and who has the right to decide.

**Comment by georgepsarakis** [comment]
@bmbouter some of the Celery Github Organization members can be found here: https://github.com/orgs/celery/people

**Comment by bmbouter** [comment]
@georgepsarakis This is exactly what I was looking for! I asked in #github on freenode first, and I didn't get a reponse so I thought it wasn't possible in github. This answers my question very well.

I'd like opinions on the following two documentation improvements:

* A declaration of the current project lead. I've always thought of @ask as the BDFL and he probably still is.
* Adding a link to the Celery Github Organization members.
