### ISSUE TITLE
If a queue has no running worker, the producer hangs forever

### ISSUE THREAD

**Issue by samson-wang** [celery/celery#4111]
## Checklist
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 librabbitmq:1.6.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:rpc:///

broker_url: u'amqp://guest:********@192.168.1.11:5672//'
result_backend: u'rpc:///'
```

## Steps to reproduce
I use queues to separate same task of different configuration. If I send task to a queue without running worker, the producer will hangs forever even with a timeout specified.

## Expected behavior
producer fails or timeout.

## Actual behavior
producer hangs forever.

**Comment by georgepsarakis** [comment]
Are you waiting for the result perhaps?

**Comment by samson-wang** [comment]
`pyamqp` 's performance is instable. Consumer delays 1~2 seconds randomly. 
`librabbitmq` speeds up tremendously. However, I have to use `pyamqp` in producer, or there will be an `expire time mismatch error`.

I use `tw.apply_async(args=[arg1], soft_time_limit=10, queue='test').wait()` to call remote worker. When there is no worker running on `test` queue, the producer will never stop, although the `soft_time_limit=10` is set.

**Comment by georgepsarakis** [comment]
The `soft_time_limit` is enforced by the Worker only. You need to specify the timeout in the call to `wait` (`timeout` argument), see the documentation [here](http://docs.celeryproject.org/en/latest/reference/celery.result.html?highlight=wait#celery.result.AsyncResult.wait).

**Comment by samson-wang** [comment]
@georgepsarakis It works！
Could the submitted task expire after sometime if there is no worker on the queue?

**Comment by georgepsarakis** [comment]
Sure, see the `expires` parameter of [Task.apply_async](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html?highlight=task%20expires):

```
expires (float, datetime) – Datetime or seconds in the future for the task should expire. The task won’t be executed after the expiration time.
```
