### ISSUE TITLE
Django. Ignore task from autodiscover_tasks OR or load tasks manually

### ISSUE THREAD

**Issue by ArtemBernatskyy** [celery/celery#4112]
Hello how can i achieve ignoring tasks from `autodiscover_tasks` OR load them manually in `Django`.  

This should be particularly useful if we have a python package full of tasks and we need to somehow ignore some of them.

**Comment by aydin** [comment]
If you disable `autodiscover_tasks` you can register spesific task with `app.register_task(your_task)`

**Comment by ArtemBernatskyy** [comment]
@aydin , sound awesome. closing for now, thanks !
