### ISSUE TITLE
send_task() fails and closes connection to the broker

### ISSUE THREAD

**Issue by nskalis** [celery/celery#4117]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.4.5
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled

broker_url: 'amqp://netopsapp:********@172.31.141.241:5672/ixmac'
imports: ['macdb']
```
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

* **consumer**
```
app = celery.Celery("ip-spotlight.ixmac.macdb", broker='pyamqp://{}:{}@{}:{}/{}'.format(os.environ['USR_NETOPS'],os.environ['PASS_NETOPS'],RABBITMQ['ipaddr'],RABBITMQ['port'],RABBITMQ['vhost']))
    app.conf.update(
        imports=["macdb"],
    )
```
```
@app.task
def stats(data, netelement, snmp_comm, label, ignore_result=True):
    pass
```
* **producer**
```
app = celery.Celery("ip-spotlight.ixmac.macdb", broker='pyamqp://{}:{}@{}:{}/{}'.format(os.environ['USR_NETOPS'],os.environ['PASS_NETOPS'],rabbitmq['ipaddr'],rabbitmq['port'],rabbitmq['vhost']))
    app.conf.update(
        broker_transport_options={'confirm_publish': True},
    )
```
`app.send_task(name="macdb.stats", args=(data, k, v['snmp_comm'], arrow.now().format("YYYYMMDDHHmm")), exchange="ip-spotlight", routing_key='celery.{}'.format(k), queue='celery.{}'.format(k))`

## Expected behaviour
Celery task to be queued on `celery.<queue_name>`

## Actual behaviour
In RabbitMQ server logs, I see
`client unexpectedly closed TCP connection`

In RabbitMQ management plugin, I see the consumer labeled with
`Consumer tag=`**None4**

Could you please advise why celery tasks are not queued/processed, given that Celery task (producer) is closing the connection to the broker ?

**Comment by nskalis** [comment]
hi, would it be possible for a maintainer to look into this ?

**Comment by nskalis** [comment]
same symptoms with Python2  as well..

**Comment by aydin** [comment]
[Consumer Tag](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.consume.consumer-tag) is created by RabbitMQ as unique, so None4 is an expected tag. 
Could you please start your worker with `-l DEBUG` option and share output here(also after send_task command)?

**Comment by nskalis** [comment]
thanks @aydin for looking into it. Over [here](https://groups.google.com/forum/?nomobile=true#!topic/rabbitmq-users/6_9eaBr57gg) I have attached the logs while in debug mode. Unfortunately, nothing useful appears there.

The more I was reading about Celery's rabbitmq client, the more concerned I became and I switched to using Redis as a broker, and everything works now.

But I would like help and see what is going wrong. Could you please advise on the next steps ?

**Comment by aydin** [comment]
Hi @nskalis , i have sent you my testing Rabbitmq credentials by email. Could you please point this server as broker and run your workers? We can see if the problem is about Rabbitmq or not.

**Comment by auvipy** [comment]
if the issue still exist on master plz report or send a pr with suggested fix

**Comment by auvipy** [comment]
and use pyamqp
