### ISSUE TITLE
celery  ends immediately after starting with no error message 

### ISSUE THREAD

**Issue by ResolveWang** [celery/celery#4118]
I use celery4.0.2 in my application.It works well on my Mac.When I deploy it on my centos server, it ends with no error message:
I use this code to start my application
> celery -A tasks.workers worker -l debug -c 1

Here is the result
<pre>
 -------------- celery@weibo2 v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Linux-2.6.32-504.el6.x86_64-x86_64-with-centos-6.6-Final 2017-07-02 23:25:06
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         weibo_task:0x7f5226aea080
- ** ---------- .> transport:   redis://:**@202.115.44.154:6379/5
- ** ---------- .> results:     redis://:**@202.115.44.154:6379/6
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> ajax_home_crawler exchange=ajax_home_crawler(direct) key=ajax_home_info
                .> comment_crawler  exchange=comment_crawler(direct) key=comment_info
                .> comment_page_crawler exchange=comment_page_crawler(direct) key=comment_page_info
                .> fans_followers   exchange=fans_followers(direct) key=for_fans_followers
                .> home_crawler     exchange=home_crawler(direct) key=home_info
                .> login_queue      exchange=login_queue(direct) key=for_login
                .> repost_crawler   exchange=repost_crawler(direct) key=repost_info
                .> repost_page_crawler exchange=repost_page_crawler(direct) key=repost_page_info
                .> search_crawler   exchange=search_crawler(direct) key=for_search_info
                .> user_crawler     exchange=user_crawler(direct) key=for_user_info

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . tasks.comment.crawl_comment_by_page
  . tasks.comment.crawl_comment_page
  . tasks.comment.excute_comment_task
  . tasks.home.crawl_ajax_page
  . tasks.home.crawl_weibo_datas
  . tasks.home.excute_home_task
  . tasks.login.excute_login_task
  . tasks.login.login_task
  . tasks.repost.crawl_repost_by_page
  . tasks.repost.crawl_repost_page
  . tasks.repost.excute_repost_task
  . tasks.search.excute_search_task
  . tasks.search.search_keyword
  . tasks.user.crawl_follower_fans
  . tasks.user.crawl_person_infos
  . tasks.user.excute_user_task

[2017-07-02 23:25:06,683: INFO/MainProcess] Connected to redis://:**@202.115.44.154:6379/5
[2017-07-02 23:25:06,701: INFO/MainProcess] mingle: searching for neighbors
[2017-07-02 23:25:07,746: INFO/MainProcess] mingle: all alone
[2017-07-02 23:25:08,768: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
</pre>

Here is my OS info
<pre>
uname -a

Linux weibo2 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m
</pre>

My python version is
> Python 3.6.1 |Continuum Analytics

If I degrade celery to celery3, it will work well on the centos6 server.

What should I do to use celery4 on my server?

**Comment by ResolveWang** [comment]
BTW,if I specify the task queue in my code, such as 
> celery -A tasks.workers -Q login_queue worker -l debug -c 1

 the app seems to work well.

**Comment by aydin** [comment]
If you don't define queue [task_default_queue](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_default_queue) (which is 'celery') will be used as queue name. So your workers will listen to 'celery' queue.

**Comment by ResolveWang** [comment]
I tried again with  the code
> celery -A tasks.workers -Q login_queue worker -l debug -c 10

the problem still occurred

**Comment by teeberg** [comment]
I just had the same problem. I was still running redis 2.10.3 and it completely threw away the error and just exited silently (return code 1, but no other logs/output whatsoever). What helped me debug was this snippet that I found somewhere (don't remember where):

```python
from celery import signals
@signals.setup_logging.connect
def setup_celery_logging(**kwargs):
    pass
app.log.setup()
```
Add that to where you define your celery `app` and hopefully it will fail loud and clear :-)

**Comment by ResolveWang** [comment]
It's strange. If I add the snippet to my code, the app will work well instead of exiting.
<pre>
import os
from datetime import timedelta
from celery import Celery
from kombu import Exchange, Queue
from config.conf import get_broker_or_backend
from celery import platforms

platforms.C_FORCE_ROOT = True
worker_log_path = os.path.join(os.path.dirname(os.path.dirname(__file__))+'/logs', 'celery.log')
beat_log_path = os.path.join(os.path.dirname(os.path.dirname(__file__))+'/logs', 'beat.log')
tasks = ['tasks.login', 'tasks.user', 'tasks.search', 'tasks.home', 'tasks.comment', 'tasks.repost']
app = Celery('weibo_task', include=tasks, broker=get_broker_or_backend(1), backend=get_broker_or_backend(2))

from celery import signals
@signals.setup_logging.connect
def setup_celery_logging(**kwargs):
        pass
app.log.setup()

app.conf.update(
    CELERY_TIMEZONE='Asia/Shanghai',
    CELERY_ENABLE_UTC=True,
    CELERYD_LOG_FILE=worker_log_path,
    CELERYBEAT_LOG_FILE=beat_log_path,
    CELERY_ACCEPT_CONTENT=['json'],
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERYBEAT_SCHEDULE={
        'login_task': {
            'task': 'tasks.login.excute_login_task',
            'schedule': timedelta(hours=20),
            'options': {'queue': 'login_queue', 'routing_key': 'for_login'}
        },
        'user_task': {
            'task': 'tasks.user.excute_user_task',
            'schedule': timedelta(minutes=3),
            'options': {'queue': 'user_crawler', 'routing_key': 'for_user_info'}
        },
        'search_task': {
            'task': 'tasks.search.excute_search_task',
            'schedule': timedelta(hours=2),
            'options': {'queue': 'search_crawler', 'routing_key': 'for_search_info'}
        },
        'home_task': {
            'task': 'tasks.home.excute_home_task',
            'schedule': timedelta(hours=10),
            'options': {'queue': 'home_crawler', 'routing_key': 'home_info'}
        },
        'comment_task': {
            'task': 'tasks.comment.excute_comment_task',
            'schedule': timedelta(hours=10),
            'options': {'queue': 'comment_crawler', 'routing_key': 'comment_info'}
        },
        'repost_task': {
            'task': 'tasks.repost.excute_repost_task',
            'schedule': timedelta(hours=10),
            'options': {'queue': 'repost_crawler', 'routing_key': 'repost_info'}
        },
    },
        CELERY_QUEUES=(
                Queue('login_queue', exchange=Exchange('login_queue', type='direct'), routing_key='for_login'),

                Queue('user_crawler', exchange=Exchange('user_crawler', type='direct'), routing_key='for_user_info'),
                Queue('search_crawler', exchange=Exchange('search_crawler', type='direct'), routing_key='for_search_info'),
                Queue('fans_followers', exchange=Exchange('fans_followers', type='direct'), routing_key='for_fans_followers'),

                Queue('home_crawler', exchange=Exchange('home_crawler', type='direct'), routing_key='home_info'),
                Queue('ajax_home_crawler', exchange=Exchange('ajax_home_crawler', type='direct'), routing_key='ajax_home_info'),

                Queue('comment_crawler', exchange=Exchange('comment_crawler', type='direct'), routing_key='comment_info'),
                Queue('comment_page_crawler', exchange=Exchange('comment_page_crawler', type='direct'),
              routing_key='comment_page_info'),

                Queue('repost_crawler', exchange=Exchange('repost_crawler', type='direct'), routing_key='repost_info'),
                Queue('repost_page_crawler', exchange=Exchange('repost_page_crawler', type='direct'),
              routing_key='repost_page_info'),
               ),

)
</pre>

But if the snippet is placed at the bottom,the app will also exit  with  no logs or no output

**Comment by teeberg** [comment]
For what it's worth, in my case it logged to a logger called `celery.worker`, so your logging should be set up to record those logs somewhere

**Comment by wowkin2** [comment]
@teeberg thanks, following helps at least to see what is the error.
I have `celery` logger, but for some reason it doesn't work properly.
```python
LOGGING['loggers']['celery.worker'] = {
    'level': 'DEBUG',
    'handlers': ['console'],
    'propagate': False,
}
```
