### ISSUE TITLE
logger in Loader class does not show any message;

### ISSUE THREAD

**Issue by FavorMylikes** [celery/celery#4121]
from celery.utils.log import worker_logger as logger
    class ProxyLoader(BaseLoader):
        count=0
        def on_worker_init(self):
            logger.error("worker init with %s" % ProxyLoader.count)
            logger.warn("worker init with %s" % ProxyLoader.count)
            logger.info("worker init with %s" % ProxyLoader.count)
            ProxyLoader.count+=1

I wanna do some initialization when worker is started and show some configuration in log message. But there is not anything appear.  Is it a bug?

I try to view the logger variable, and I found that the root_logger property of logger dose not have `stderr` handler.  But it worked in another place.

How can I fix it?

**Comment by FavorMylikes** [comment]
I have figure it out. It because of logger configure function `celery.app.log.setup_logging_subsystem` would be invoked after `worker_init` function. And I think it's a defect about celery. Hope you guys could let it better. I've use `logging` build-in module with python.

That's all.

**Comment by auvipy** [comment]
please send a fix with testcase if you think it's a defect and could be improved.
