### ISSUE TITLE
Does WORKER_MAX_MEMORY_PER_CHILD work?

### ISSUE THREAD

**Issue by listingmirror** [celery/celery#4125]
## Steps to reproduce

`celery==4.0.2`
`python 3.6.1`
`WORKER_MAX_MEMORY_PER_CHILD=200000`

## Expected behavior

- Worker initial starts with about 90MB of used memory used, as measured by `mem_rss()`
- As time goes on, it slowly approaches 200MB of used memory
- After worker passes 200MB, worker is killed and replaced. 
- New worker starts at 90MB of used memory
- Repeat

## Actual behavior

- Worker initial starts with about 90MB of used memory used, as measured by `mem_rss()`
- As time goes on, it slowly approaches 200MB of used memory
- After worker passes 200MB, worker is killed and replaced
- New worker starts at 175-210MB of used memory, and is immediately killed most of the time
- Stuck in a cycle where each worker does 1 task, and gets killed

Is something in the fork for a worker retaining memory between replacements?

**Comment by georgepsarakis** [comment]
Can you describe your tasks? Perhaps you are using some type of caching that consumes too much memory or you have very large messages along with a large prefetch multiplier value, which accumulates too much memory above a specific queue size.

**Comment by listingmirror** [comment]
@georgepsarakis  sure!

95% of my tasks.. something like:

* Parameter to task: 1 or 2 ints
* It will use that int to load a model from the DB with the DJango ORM
* We will then query a 3rd party API with Python requests or an client given to me by the API
* We will maybe update 1 or 2 fields on the model, and save to the database.
* Total task time of maybe 2 seconds (most of it spent waiting for requests to come back with an answer)


There tasks that themselves use the most memory are something like:

* Web server reads in an excel spreadsheet, and turns into an [][]
* Split the [][] into groups of 100 rows, send each 100 rows as a task param for a task to process it (average size, maybe 10 KB of message data max)


I totally get why an individual worker can get fat over time. Any given worker can query about 20 different APIs. If he queries all 20, he has a lot of libraries loaded into memory. It is all code cache though, not data. The "big data" tasks are like I said, a few 10s of KB of data.  Which is fine, the worker gets fat and doesn't release memory because of python issues. But it SOUNDS like WORKER_MAX_MEMORY_PER_CHILD should kill that child and make a new lean worker again.  But I get the child killed and a new fat worker that is already bloated :(



Globally my prefetch multiplier is 10. I had 4 for the longest time. Trying 10, but notice no different from the 10. 

I DO use ETA tasks a lot (via countdown). At any given time I have between 10k and 50k tasks (of the 2 int parameter type) sitting with a future dated ETA. This is mostly due to API rate limits. A common case is something like:

* I need to update some local values based on what is at the API once per hour
* The api limits me to 1 call per second
* So I have a celery beat spawn an hourly "create work task"
* That create work creates 1000 small tasks to do the API call, the first with a delay of 0, the second with a delay of 1, etc. etc. up until the task with a max delay of about an hour

^^ I do not live this delay task pattern, and this may not be helping my memory usage. However I do not know of a better way to deal with an external API with a rate limit. Totally open to other designs to make this better.

Also more than happy to do any kind of memory dump of fat workers to troubleshoot why they are so bloated. I do not know enough about Python to do this off the top of my head, but if you can point me to a blog or a command I can dump and help poke at things to figure out where my message usage is.

**Comment by auvipy** [comment]
hey, could you verify this on top of master?

**Comment by mouradmourafiq** [comment]
I am noticing something similar when using rabbitmq as a broker. The leak does not show when using redis as broker.

Celery v0.4.3
Django v2.2.3
