### ISSUE TITLE
chord(group(chord1, chord2), func) not work? 

### ISSUE THREAD

**Issue by RZ16** [celery/celery#4126]
## My platform
`python: 3.5.2`
`celery: 4.0.2`
`system OS: Ubuntu 16.04`
`broker: redis`
`backend: redis`

## Task codes
```
from celery import Celery, group, chord

REDIS_URL = "redis://127.0.0.1:6379/0"
app = Celery("testing", broker=REDIS_URL, backend=REDIS_URL)

@app.task
def add(x,y):
    print("%d+%d--------------------------------------------------------" %(x,y))
    return x+y

@app.task
def xsum(x):
    print("xsum--------------------------------------------------------")
    print(x)
    print("------------------------------------------------------------")
    s = 0
    for i in x:
        s += i
    return s
```
## Expected behavior
```
chord1 = chord(group(add.si(i, i) for i in range(1, 4)), xsum.s())
chord2 = chord(group(add.si(i, i) for i in range(4, 7)), xsum.s())

chord3 = chord(group(chord1, chord2), xsum.s())
chord3.delay()
```
Expected return is (1 + 1) + ... + (6 + 6) -> 42, however, in chord1, after `group(add.si(i, i) for i in range(1, 4))`, the `xsum.s()` is not called, the same thing happens to chord2.

How can fix it?

**Comment by listingmirror** [comment]
I am not an expert in this, but here is my take:

No reason for a group inside a chord.. the tasks in the first part are already "grouped"

This is how I would write this in the most simple form:


```
    tasks_1 = [add.si(i, i) for i in range(1, 4)]
    tasks_2 = [add.si(i, i) for i in range(4, 7)]
    result = chord(tasks_1 + tasks_2)(xsum.s())
    print("Answer", result.get())
```

That correctly gets me 42. I just build up an array of tasks, and pass them all to the first arg of the chord., and then pass the result to collect.

To make the nested chords work though, I did like this:


```
    chord_1 = chord((add.si(i, i) for i in range(1, 4)), xsum.s())
    chord_2 = chord((add.si(i, i) for i in range(4, 7)), xsum.s())
    chord_3 = chord((chord_1, chord_2), xsum.s())
    print("Answer", chord_3().get())

```

Really looks like I did the same thing as you without the groups?

**Comment by RZ16** [comment]
Thank you, the reason for a group inside a chord is a project needed, but I got another answer. It's not celery' bug, but redis backend. After changing backend to rabittmq, it just works.
