### ISSUE TITLE
Suggested feature: task recorder

### ISSUE THREAD

**Issue by Shir0kamii** [celery/celery#4129]
Hi!

I recently implemented email notifications in a Flask application and for that, I used `Flask-Mail` and `celery`. Testing the code for mails was easy with their `record_messages` context manager, and I found that feature lacking for `celery`.

My idea is a `record_tasks` context manager yielding a list that will contain all tasks published during the context.

Having this feature would enable this sort of tests:

```python
def send_mail_delayed():
    send_mail.apply_async(eta=some_time)

def test_task_eta():
    with record_tasks() as tasks:
        send_mail_delayed()
        assert len(tasks) == 1
        assert tasks[0].headers["eta"] == some_time
```

I didn't looked but it could also probably be used to make existing tests easier to read.

I'm willing to implement it but would prefer approval of the concept before doing so. What do you think of it ?

**Comment by georgepsarakis** [comment]
Perhaps this [reference](https://github.com/celery/celery/blob/b6ca6b6579f118a9d7b3ebe46da7861df04f1c12/docs/userguide/calling.rst) would help?

**Comment by auvipy** [comment]
@georgepsarakis can we close this or consider it as a new feature request?
