### ISSUE TITLE
max execute time

### ISSUE THREAD

**Issue by HenryChenV** [celery/celery#4130]
Version 3.1.12.

How can I indicate the max execution time of a task when I call apply_async function. I want to use CELERYD_TASK_SOFT_TIME_LIMIT option to do something before kill the task, but it dosn't work. The option CELERYD_TASK_TIME_LIMIT is work well but I can't kill the task without cleanup. 

My code is like the example of doc.

**Comment by auvipy** [comment]
plz post this type of support question to https://groups.google.com/forum/#!forum/celery-users list or IRC chat channel
