### ISSUE TITLE
base class raises TypeError: metaclass conflict:

### ISSUE THREAD

**Issue by ptadas** [celery/celery#4133]
using: python 3.5
celery 4.0.2

The example code from celery website:

```
class CustomTask(Task):
    def run(self):
        print('running')
CustomTask = celery_app.register_task(CustomTask())

@celery_app.task(bind=True, base=CustomTask)
def custom(self):
    print('running')

```
Part of stacktrace:

```
celery_app.task(bind=True, base=CustomTask)
File "/home/xxx/Projects/nn/venv/lib/python3.5/site-packages/celery/app/base.py", line 416, in _create_task_cls
ret = self._task_from_fun(fun, **opts)
File "/home/xxx/Projects/nn/venv/lib/python3.5/site-packages/celery/app/base.py", line 454, in _task_from_fun
'wrapped': run}, **options))()
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Is there something I'm doing incorrectly?

**Comment by georgepsarakis** [comment]
@ptadas you do not need to register the `CustomTask`, the `base` argument value must be a class.

Omitting the registration line, should work:

```
class CustomTask(Task):
    def run(self):
        print('running')

@celery_app.task(bind=True, base=CustomTask)
def custom(self):
    print('running')
```

**Comment by sivang** [comment]
I'm bitten by this as well, and well, I'm using master branch, so now nor this way or the one with app.register_task work, and I have no way whatsoever to catch exceptions in a custom way and react to them :/

**Comment by odigity** [comment]
I'm running into the same problem using the simplest possible example based directly on the docs.

    import celery
    from celery import shared_task

    class Foo(celery.Task):
        pass

    @shared_task(name="test_noop", base="Foo")
    def test_noop():
        pass

Couldn't be simpler, right?  But I get:  `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

Python 3.7, Celery 5.2.6

**Comment by noninyo** [comment]
@auvipy, any update on when will it be solved?
Should I return to an earlier version?

**Comment by maxwoe** [comment]
I solved it in the following way in a flask app:

``` python
// celery_app.py
class ContextTask(Task):
    abstract = True
    schedulable = None
    current_app = None

    def __call__(self, *args, **kwargs):
        with self.current_app.app_context():
            return super(ContextTask, self).__call__(*args, **kwargs)
            
def init_celery(app):
    celery = Celery(task_cls=CustomTask)
    celery.app = app
    ContextTask.current_app = app

    return celery
 
// tasks.py
@shared_task(bind=True, base=ContextTask)
def custom(self):
    print('running')
```

You can extend the ContextTask to your liking on a per-task basis, e.g.
``` python
class RetryableContextTask(ContextTask):
    abstract = True
    autoretry_for = (Exception, )
     retry_backoff = True
    retry_kwargs = {'max_retries': 3}
    retry_jitter = True
    
@shared_task(bind=True, base=RetryableContextTask)
def custom_retryable(self):
    print('running')
 ```

**Comment by auvipy** [comment]
may be we can just add that code in documentation / example?
