### ISSUE TITLE
Please add UWSGI to Daemonizing docs

### ISSUE THREAD

**Issue by kwill** [celery/celery#4136]
## Checklist
- [x] I have verified that the issue exists against the `master` branch of Celery.
(Checked http://docs.celeryproject.org/en/master/userguide/daemonizing.html )

**User story:** I am a Django developer running UWSGI. I want to run Celery using UWSGI, so that I don't have to install another dependency (for example, supervisord).

The [Daemonizing](http://docs.celeryproject.org/en/master/userguide/daemonizing.html) documentation doesn't currently mention UWSGI as an option. However, Celery can be run from UWSGI, including from a virtualenv, and UWSGI is a popular choice for Django sites.

**Related notes from UWSGI docs:**

From https://uwsgi.readthedocs.io/en/latest/AttachingDaemons.html#examples :

> Managing celery:
>
> [uwsgi]
> master = true
> socket = :3031
> smart-attach-daemon = /tmp/celery.pid celery -A tasks worker --pidfile=/tmp/celery.pid

From https://uwsgi.readthedocs.io/en/latest/AttachingDaemons.html#legion-support :

> Managing celery beat:
>
> [uwsgi]
> master = true
> socket = :3031
> legion-mcast = mylegion 225.1.1.1:9191 90 bf-cbc:mysecret
> legion-smart-attach-daemon = mylegion /tmp/celery-beat.pid celery beat --pidfile=/tmp/celery-beat.pid

Please also mention if there are any drawbacks to using UWSGI (slower, less reliable, etc).

**Comment by georgepsarakis** [comment]
Isn't UWSGI suitable for applications that implement the WSGI protocol? I thought it was mainly for HTTP frameworks.

**Comment by auvipy** [comment]
the purpose of uwsgi is not running celery. couldn't you use systemd to daemonize celery with django and uwsgi?

**Comment by kwill** [comment]
@georgepsarakis @auvipy Thanks for the pointers. It sounds like systemd is a more appropriate solution that doesn't require additional dependencies.

**Comment by auvipy** [comment]
haha cool :dancer:

**Comment by bensteinberg** [comment]
I think the case for which uWSGI could be the answer is [as linked above](http://uwsgi-docs.readthedocs.io/en/latest/AttachingDaemons.html#legion-support): to use its Legion subsystem to run one and only one instance of celery beat in a cluster of servers. I'm experimenting with this now and looking for good documentation/examples.
