### ISSUE TITLE
Fund raising campaign for full time fellow maintainer position

### ISSUE THREAD

**Issue by auvipy** [celery/celery#4142]
http://www.celeryproject.org/news/fund-raising-celery-fellowship-program/

or direct https://igg.me/at/dFLL0FmznfI/x/16384863

**Comment by alukach** [comment]
Looks good! One ambiguity in the description of the fund-raising documentation is _how_ the project will select its maintainer. Is it assumed to be @auvipy because he created the Kickstarter?  If it is, then I think that fact should be clear and upfront.  If not, how will the maintainer be chosen? Will there be an application process?  What about after the 6-month trial?

Additionally, I think breaking the pricing up into milestones may be sensible. This could be either/both features or time.  Both the [DRF Kickstarter](https://www.kickstarter.com/projects/tomchristie/django-rest-framework-3) and the [Django Schema Migrations Kickstarter](https://www.kickstarter.com/projects/andrewgodwin/schema-migrations-for-django) broke goals up into features. I think this contributed to their high level of success. Saying that "this person will work on whatever they see fit for 6 months (or however much money is donated)" doesn't really express a specific need for a dollar amount.  Instead, I think we should come up with a reasonable rate in which someone would earn for being a full-time maintainer and then that person would work for as long as funding allows (or we could rotate maintainers after X months, if that's desired).  And then that person should be aiming for specific features during that time (as done by the aforementioned Kickstarters).  This would really help people get an idea of what they are getting in return to their contribution and make it easier for companies to justify the expense.

**Comment by auvipy** [comment]
Hi! actually this was inspired by django fellowship program https://www.djangoproject.com/fundraising/#fellowship-program though I believe there should be more improved writing in the description. As one of the most active maintainer for last one year or so I discussed with @ask about a fund raising for a full time position. Right now celery is not that organized like django software foundation so core board members have to step out for the house keeping tasks. Thanks for your feedback and suggestions.

**Comment by auvipy** [comment]
but yes we could include the break down of expected significant features during the first 6 months of the pilot program.

**Comment by alukach** [comment]
@auvipy So then the idea is that it will be you operating as the first fellow?  And what's the followup steps after the first 6 months?  I ask these questions not to scrutinize (I think you'd make a great Celery fellow!), I am simply saying that I think response would be warmer if the plan for the fellowship program and how the first batch of money would be used were more clearly documented.

**Comment by eire1130** [comment]
I saw this and thought: Great! Then I read it, and have the same concerns as @alukach . I don't mean for this to sound harsh, but I don't think this plan is very well planned out.

I'd be happy to pony up some of my own money, and I could possibly create budget so my company would support as well, but I can't do either until the plan is a bit more concrete with respect to a few things:

1. What do we get and when?
2. Who decides accountability, for example a board or a BDFL type system or both?
3. What happens at the end of this six months?
4. How is work reviewed and accepted?
5. Is there a process, and if so, what is it?

If you can give some color to the above and put that into indiegogo and update this PR as well, then i'll be happy to contribute and see what I can do about allocating some budget at my company as well.

And for the record, I also think you'd be a great fellow for this. I don't contribute code here obviously, but we use Celery at my company and on all my personal projects, so I try to keep up to date on what's going on. 

It would be great for me to stop seeing things like:

```sudo /etc/init.d/celeryd stop
celery init v10.1.
Using config script: /etc/default/celeryd
celery multi v3.1.25 (Cipater)
> Stopping nodes...
	> celery@ip-XX-0-0-XXX: TERM -> 27951
^C
Session terminated, terminating shell...> Waiting for 1 node -> 27951............................................................................................................................................................................................................................................................................................................................................... ...terminated.
```

for example, when trying to stop a worker.

**Comment by auvipy** [comment]
I think both of you bring some good points. I must have to admit while I tried but failed to illustrate things well. Surely I lack many.

**Comment by alukach** [comment]
@auvipy I'm curious if you plan on updating the IndieGoGo campaign or plan to keep it as is? I really think the idea is solid and Celery could really benefit from a full time dev. If needed, I'd be happy to help define the scope of the fellowship if you'd like (I think it would be best done as a group).

I think Celery would really benefit from a roadmap. I'd be interested to hear what the targets are for the project in the future. I think once this was established, building out goals for the fellowship would be easy.

**Comment by pelme** [comment]
Is the campaign still active?

I think this needs to be marketed more actively and prominently in release notes and on the website. I was actively looking for a way to contribute money to the celery project and still had a hard time finding this. I would love to setup a monthly contribution of about ~250 usd from our company but some kind of updates and follow ups on the questions raised would be nice.

Not following up on the questions raised here and no updates on the indiegogo makes it seem dead but I really hope it is not! A lot of people benefit so much from celery and I really think and hope that there are enough people and companies that could make this happen.

Huge thanks for your contributions and starting to get this rolling. I really really wish celery was sustainably funded! :)

**Comment by auvipy** [comment]
Hi guys, I must have to admit that the campaign was not well thought out one and a massive failure. I still have plans to set up better roadmap and atleast a part time position for working on the roadmap issues. we could have more consensus and suggestions for any next successful move. may be something like django-rest-framework like model could be followed :) looking forward for your inputs.

**Comment by auvipy** [comment]
I was able to raise 270 U$D from 5 backers :)

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/2655

**Comment by auvipy** [comment]
Meanwhile we got our first monthly backer on open collective, https://opencollective.com/celery# the fund will ensure some dedicated time for releasing to pypi and fixing critical issues. For those interested, right now two core team member is managing the opencollective page. all the donation and transaction will be transparent there. Let us know your concerns so that we can address them and make you all confident to contribute.

**Comment by xirdneh** [comment]
@auvipy Can we also take a look at: https://tidelift.com/lifter/search?q=celery
Seems like we can gather some more money from there.
It's still not enough to have a Celery fellow for one year but we can use that money to create a better community.
The last DjangoCon sprints taught us about the thing we're missing on documentation for people who would like to contribute and we're about to finish that PR (#5143). Apart from continuing improving documentation and environment setup I think we could also create some incentives for new contributors. For instance a patch or a pin. (The celery stickers and pins handed out at DjangoCon were also very successful 😄).
Thoughts?

**Comment by auvipy** [comment]
Creating a better community is a myth IMHO. these incentives are not sustainable for the long term. for a project like celery, we need paid workers to work major rewrites of celery. RIght now I managed roughly 20 hours paid work per month for celery and looking for more. I will start more intensive work for celery from November.

**Comment by clokep** [comment]
Not really related to this issue, but more to the point of building a community: are there curated short- / medium-term goals? A list of "easy" to tackle issues? Anything else that people who might *want* to contribute, but don't know where to start, could look at?

E.g. there's a ton of code in Celery that is marked as "deprecated", but it's still there, should someone start removing it? Are there other straight-forward tasks that people can help w/? Maybe start removing some of the cruft and making the rest of the code-base easier to understand? Something else? I don't know! 👍

**Comment by xirdneh** [comment]
I think it depends on the definition of a better community. What I mean it's just showing more support and feedback to the users, not so much trying to tell community members how to behave.
It's really more about the face of the project to the greater python community. Things like doing presentations about Celery on conferences, responding to github issues, mailing lists and IRC as well as updating documentation to make the code (and the project) friendlier to new user/contributors goes a long way. They take time but they go a long a way.
We don't have to do patches or any other incentive, although it'll be a cool thing to have some Celery swag, even if it's only to sell or maybe to give away in various python meetups.

I'm glad to hear you've managed to get some paid work for Celery! Congrats 😄 
@clokep raises a good point about the short/medium/long goals. Some of us would like to get even more involved in the project and that would definitely help.
Regarding making the code easier to navigate, I think that's mainly about documentation/spreading the word. I'm currently working on some articles about Celery's inner workings but that'll take some time to finish.

**Comment by xirdneh** [comment]
We could also create tasks about the rewrites needed and start tackling those even if we're not getting paid for it. I know it might move slower that if there were some paid devs but it's a start.

**Comment by othalla** [comment]
Will be glad to help when i'll have some time ;)
