### ISSUE TITLE
Task retry includes an extra `-00:28` offset

### ISSUE THREAD

**Issue by steve-gregory** [celery/celery#4145]
## Checklist
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1. Using celery master, call a task that will be 'retried'.
2. Observe the `eta` in `celery -A app inspect scheduled`
3. Set `CELERY_ENABLE_UTC` to `True` and `CELERY_TIMEZONE` to `America/Phoenix`

## Expected behavior
```
-> <My Node Name>: OK
    * {'priority': 6, 'eta': '2017-07-19T17:02:33.164276-07:00', 'request': {'args': ...

<Task retries @ ETA time>
```
## Actual behavior
```
-> <My Node Name>: OK
    * {'priority': 6, 'eta': '2017-07-19T17:02:33.164276-07:28', 'request': {'args': ...

<Task never retries. Retry count stays at one and the task hangs around indefinitely.>
```

**Comment by steve-gregory** [comment]
Notes:
- Tried other timezones (America/Los_Angeles) and got a similarly "weird" offset.
- This error does _NOT_ happen if timezone is set to `Etc/UTC`

**Comment by georgepsarakis** [comment]
Have you perhaps noticed if it is only a representation issue or the ETA is actually incorrect?

**Comment by steve-gregory** [comment]
@georgepsarakis (Just updated my description to reflect this) The ETA is actually incorrect and prevents the task from being executed.

**Comment by georgepsarakis** [comment]
There was a fix recently for ETA in https://github.com/celery/celery/issues/3753 , but perhaps this is unrelated.

**Comment by georgepsarakis** [comment]
Can you try with `CELERY_ENABLE_UTC=False`? In the issue that I mentioned, the correct way to respect the timezone setting was to also disable UTC.

**Comment by steve-gregory** [comment]
@georgepsarakis disabling UTC did not solve my problem. After looking into the fix you mentioned above, i dropped in an `rdb` line to see what was happening.. Here are my results:
```
> /opt/env/atmo_zz2/src/celery/celery/app/amqp.py(326)as_task_v2()
-> eta = maybe_make_aware(
(Pdb) n
> /opt/env/atmo_zz2/src/celery/celery/app/amqp.py(327)as_task_v2()
-> now + timedelta(seconds=countdown), tz=timezone,
(Pdb)
> /opt/env/atmo_zz2/src/celery/celery/app/amqp.py(329)as_task_v2()
-> if isinstance(expires, numbers.Real):
(Pdb) eta
datetime.datetime(2017, 7, 19, 19, 38, 31, 324450, tzinfo=<DstTzInfo 'America/Phoenix' LMT-1 day, 16:32:00 STD>)
(Pdb) timezone
<DstTzInfo 'America/Phoenix' LMT-1 day, 16:32:00 STD> # NOTE: This is wrong!
(Pdb) print timezone
America/Phoenix
(Pdb) type(timezone)
<class 'pytz.tzfile.America/Phoenix'>
```

**Comment by thedrow** [comment]
Can you please verify that this is fixed with master?

**Comment by steve-gregory** [comment]
Confirmed, fixed on master.

**Comment by jarshwah** [comment]
Is there a release planned any time soon with this fix? I'm looking at rolling back to 4.0 to avoid this problem.

Using UTC fixes the eta problems, but the beat schedule is way off in return.

**Comment by thedrow** [comment]
Yes, soon. But we want to merge a few things first.

**Comment by jarshwah** [comment]
No worries, thanks for the heads up.
