### ISSUE TITLE
Possible conflict with "kue"?

### ISSUE THREAD

**Issue by olalonde** [celery/celery#4158]
I'm using https://github.com/Automattic/kue in a project with a redis instance. I'd like to re-use that redis instance for Celery. I was wondering if there's anything that could conflict between those two? I know that kue let's me set a prefix for the keys it's using which I've done. Is there a similar option for Celery?

**Comment by georgepsarakis** [comment]
The prefix should be the queue name.

**Comment by davidt99** [comment]
Redis also have multiple databases support so you can assign different numbers to each project.
In celery, you can set the broker url like this: `redis://redis_address:redis_port/db_number`

**Comment by thedrow** [comment]
I hope you find the answer satisfactory. I'm gonna close this issue now.
