### ISSUE TITLE
Timezone calculations in app.now() are incorrect

### ISSUE THREAD

**Issue by rtpg** [celery/celery#4160]
From `celery/app/base.py`

```

    def now(self):
        """Return the current time and date as a datetime."""
        from datetime import datetime
        return datetime.utcnow().replace(tzinfo=self.timezone)
```

This is just semantically wrong. This takes the UTC timezone-aware time and replaces the timezone, _without actually ensuring it's the same point in time_.

So 9 AM UTC becomes 9 AM JTC, even though 9 AM UTC is 6 PM JTC

The "proper" way of doing this is `self.timezone.normalize(datetime.utcnow())`

This bug breaks things like `crontab` for celery beat, for example, since the schedules get shifted around. And it's the wrong time too

**Comment by georgepsarakis** [comment]
This may be caused by the changes in this [Pull Request](https://github.com/celery/celery/pull/3867/files).

**Comment by georgepsarakis** [comment]
Perhaps also related: https://github.com/celery/celery/issues/4145

**Comment by georgepsarakis** [comment]
@rtpg Based on your suggestion, I think this might be the correct implementation:
```
    def now(self):
        """Return the current time and date as a datetime."""
        from celery.utils.time import to_utc
        from datetime import datetime

        now_in_utc = to_utc(datetime.utcnow())
        return self.timezone.normalize(now_in_utc)

```
I need to test it some more though.

**Comment by rtpg** [comment]
one detail (I'm not sure how it applies here, but it feels relevant) is whether `self.timezone` differs from the system timezone. 

For example if self.timezone is UTC+1 but the system timezone is UTC+9

If those differs, then `datetime.utcnow()` will return the current timestamp (probably) by subtracting 9 hours from the `now`, but then `self.timezone.normalize(now_in_utc)` will shift it forward by only 1 hour? 

Though..... maybe the system timezone is "always right".

**Comment by georgepsarakis** [comment]
@rtpg I think it is actually the other way round, the system clock counts in UTC (Universal Coordinated Time) and when you set the system timezone, it changes the representation only. Thus UTC is an absolute measure of time, whereas timezones are relative offsets to UTC.
