### ISSUE TITLE
complex canvas getting stuck at the middle

### ISSUE THREAD

**Issue by itayB** [celery/celery#4164]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Celery 4.1.0, broker=RabbitMQ 3.6.5, backend=Redis 3.2.5

Consider the following canvas:
```celery worker -A worker.celeryapp:app -l info -Q default -c 2 -n defaultworker@%h -Ofair```

```
@app.task(name='task_1',
          bind=True,
          base=MyConnectionHolderTask)
def task_1(self, feed_id, flow_id, **kwargs):
    do_something()

task_1 = t_1.si(feed_id, flow_id)
  .
  .
task_13 = t_13.si(feed_id, flow_id)
```
```
           (task_1 |
            group((task_2 | group(task_3, task_4)),
                  task_5,
                  task_6,
                  task_7,
                  task_8) |
            task_9 |
            task_10 |
            task_11 |
            task_12 |
            task_13).apply_async(link_error=unlock)
```
means I have chain of tasks which one of its tasks is a group of several tasks, and one of them is chain of size 2 (with latter task as group of 2).

## Expected behavior
all task succeeded so expecting finish until task_13

## Actual behavior
task_4 is the last to run. task_9 and the rest (10..13) doesn't run.
if i cancel the group of task_3 & task_4 it does work (till 13):
```
           (task_1 |
            group((task_2 | task_3 | task_4),
                  task_5,
                  task_6,
                  task_7,
                  task_8) |
            task_9 |
            task_10 |
            task_11 |
            task_12 |
            task_13).apply_async(link_error=unlock)
```

**Comment by jheld** [comment]
Curious, have you lowered your logging level to DEBUG and does it show anything?

Have you listed the tasks through the events control inspect module?

**Comment by itayB** [comment]
No, I'll try to change the debug level and inspect, I'll update..

**Comment by auvipy** [comment]
please try the master branch and see if recent commits fix this issue. if not please ping to reopen
