### ISSUE TITLE
Question: Is it possible to remove a task from a workers revoked queue without worker restart?

### ISSUE THREAD

**Issue by niharathomas** [celery/celery#4168]
I want to restart a task that was previously revoked on the worker. I see it listed on the worker revoked list, but wasn't able to find a way to remove my task from the list using my task id. We do not persist revoked tasks to disk and so restarting the worker clears the list and we're able to restart the task fine. 
I want to be able to restart the task by id without having to restart the worker. Is it possible to accomplish this programmatically?
Is there a way to access the [revoked LimitedSet](https://github.com/celery/celery/blob/master/celery/worker/state.py#L60) directly in my code?

Celery version: 3.1.25
Redis broker: 2.6.17

**Comment by auvipy** [comment]
Ask this type of questions to the celery-users mailing list and use the latest releases.

**Comment by maxdebayser** [comment]
Sorry to comment on a closed issue, but I want to know the answer to this question too. @niharathomas , did you ask on the mailing list? The only similar question I could find is: https://groups.google.com/forum/#!searchin/celery-users/revoked|sort:date/celery-users/BmZWwr8BubA/La9kuQ7GAgAJ
