### ISSUE TITLE
Potential race condition when detaching workers

### ISSUE THREAD

**Issue by arhoyling** [celery/celery#4174]
## Checklist
- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Versions
Verified on `celery` `3.1.25` and above (including tip).

## Report
Not applicable.

## Description

In `celery.platforms`, `after_chdir_do()` in `detached()` makes sure the pidfile is not stale by calling `_create_pidlock()` and releasing the pidlock soon after.

Although the comment says "*Doesn't actually create the pidfile, but makes sure it's not stale.*", `_create_pidlock()` does indeed call `Pidfile.acquire()` which **does** create the pidfile.
The fact that the release is performed on the same line (`_create_pidlock(pidfile).release()`) **does not** make it atomic.

Any other process monitoring for the existence of a pidfile (for example to make sure workers actually started) will (one day) see that *temporary* file and wrongly assume workers already loaded their `Blueprint`.

Surely their must be another way to check that the pidfile is not stale without actually creating it.
Why not extract the *stale* logic from `_create_pidlock()` and reusing it there?

```python
def can_create_pidlock(pidlock):
    if pidlock.is_locked() and not pidlock.remove_if_stale():
        print(PIDLOCKED.format(pidfile, pidlock.read_pid()), file=sys.stderr)
        return False
    return True

def _create_pidlock(pidfile):
    pidlock = Pidfile(pidfile)
    if not can_create_pidlock(pidlock):
        raise SystemExit(EX_CANTCREAT)
    return pidlock.acquire()

...
    def after_chdir_do():
        logfile and open(logfile, 'a').close()
        if pidfile and not can_create_pidlock(Pidfile(pidfile)):
            raise SystemExit(EX_CANTCREAT)
```

**Comment by auvipy** [comment]
I am unsure it still exists on master? closing conditionally hoping to reopen if get report again on master

**Comment by arhoyling** [comment]
We removed our work-around after upgrading to 4.1 and saw the race condition happen again (an external system noticed the temporary pidfile and wrongly assumed the celery node had started).
This still exists on master - this part of the code was unchanged. 

I am happy to write a patch for this if needed.

**Comment by arhoyling** [comment]
Here are some simplified timelines to illustrate the problem:

![celery-expected](https://user-images.githubusercontent.com/7500364/39524527-29218d98-4e11-11e8-8e4f-520cff2b3a54.png)

![celery-actual](https://user-images.githubusercontent.com/7500364/39524424-d3f6a22c-4e10-11e8-978f-364c629de483.png)

![celery-failure](https://user-images.githubusercontent.com/7500364/39524459-f9cb5948-4e10-11e8-9f3a-5306f52a3a52.png)

As you can see, it is possible for a monitoring process to see the pidfile and assume the celery worker is detached even when the actual worker process fails to start.

I think it is a safe change to make. It would enforce the separation of responsibility between the parent and child processes - as explained in the current docstring:
> pidfile (str): Optional pid file.
 The pidfile won't be created, as this is the responsibility of the child.  But the process will exit if the pid lock exists and the pid written is still running.

**Comment by georgepsarakis** [comment]
@arhoyling thank you very much for providing detailed feedback :smile: ! 

Since this refers to daemonization only, I think it is indeed safe and correct to apply the suggested changes. Please feel free to open a PR, as you mentioned.

**Comment by auvipy** [comment]
https://github.com/celery/celery/compare/master...arhoyling:master

**Comment by thedrow** [comment]
> 
> 
> [master...arhoyling:master](https://github.com/celery/celery/compare/master...arhoyling:master)

@auvipy You can link a pull request. That way it will close when we merge the PR.
