### ISSUE TITLE
CeleryBeat Process consumes all OS memory

### ISSUE THREAD

**Issue by virenderdubey** [celery/celery#4175]
We are using

django-celery==3.1.10
celery==3.1.20
python 2.7.13

We have written a CustomDataBaseScheduler to schedule task, which schedules the task perfectly on time. We are running CeleryBeat Process as init script, but celeryBeat consumes Full memory of the system i.e. 24GB in a day.

The #task it schedules is ~100/minute. 

I tried to run pmap on celerybeat Process, but it shows [anon] has took the most memory.
Can someone please help to debug and fix this.

**Comment by niteeshm** [comment]
@virenderdubey Try running celery beat with Supervisor. We faced some similar issues wherein all system memory was getting used by celery workers and beat , ultimately resulting in worker crashes.
However, as a first rule , check for any memory leaks in your code.

**Comment by thedrow** [comment]
We unfortunately do not have the resources to support both 3.x and 4.x.
