### ISSUE TITLE
OperationalError: lost synchronization with server - Django 

### ISSUE THREAD

**Issue by bykof** [celery/celery#4179]
Hi dear celery team,

I use celery with django and sometimes this error happens. I checked a lot of things and everything should be fine. I use postgresql 9.5.6.

Error:

`OperationalError: lost synchronization with server: got message type "", length 50528282`

My settings:

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis:///
```

**Comment by auvipy** [comment]
use latest releases

**Comment by mic159** [comment]
We also had this issue when upgrading from celery 3.x to celery 4.x while using prefork.
Switching to gevent stopped the immediate issue.

What we saw some weirdness using `strace` on the workers where it was sending SQL to redis and redis commands to postgres on the first task sometimes.

We are testing a potential fix for that suspect maybe_close function in celery that we think is causing the issues.
