### ISSUE TITLE
may be closed

### ISSUE THREAD

**Issue by nymsa** [celery/celery#4180]

**Comment by nymsa** [comment]
@ask, I see you are the main developer of the rpc backend.
Do you have any ideas?

**Comment by nymsa** [comment]
I'm found in celery/backend/rpc.py function binding(self), which return Queue with parameter self.oid.
self.oid is self.app.oid, which defined in celery/app/base.py and have comment:
`# since 4.0: thread.get_ident() is not included when
# generating the process id.  This is due to how the RPC
# backend now dedicates a single thread to receive results,
# which would not work if each thread has a separate id.`

Does it mean, that rpc backend will be correct working with worker with concurrency = 1 only?

**Comment by auvipy** [comment]
post this type of question to the mailing list or irc
