### ISSUE TITLE
Gevent pool not removing completed messages

### ISSUE THREAD

**Issue by x00x70** [celery/celery#4182]
billiard==3.5.0.3
boto3==1.4.5
celery==4.1.0
kombu==4.1.0
gevent==1.2.2
greenlet==0.4.12

Broker: AWS SQS
OS: Centos

I'm having a weird issue that when using `--pool=gevent`, completed tasks are not removed from the message queue.  I don't have this issue using prefork/solo pools. When the message visibility from SQS is hit, the tasks get re-run indefinitely, even though they are stored as successful in the backend.

Anyone know why the gevent pool isnt able to update my SQS queue?

**Comment by thedrow** [comment]
Can you please provide us with a test case to reproduce the problem?

**Comment by dfirst** [comment]
Today i have almost same issue but with --pool=solo on two new instances.
My dependencies:
amqp (2.2.2)
billiard (3.5.0.3)
celery (4.1.0)
kombu (4.1.0)
Some details:
Im using rabbitmq and celery for importing Products.
Import started good and celery processed first 73k of products but then happened something strange, celery started to process same messages(around 3-4) over and over even after reload of workers and broker.
I have no any errors while tasks executing i checked my db there is products updating over and over without any errors.
The command for run celery was: 

> celery -A shop.settings.celery_app worker -Q celery --concurrency=4 --pool=solo -n shop-worker

Celery app file:

> import os
> os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'shop.settings')
> from celery import Celery

> app = Celery()
> app.config_from_object('django.conf:settings')
> app.autodiscover_tasks()

Celery settings:

> CELERY_ACCEPT_CONTENT = ['json', 'pickle']
> CELERY_TASK_SERIALIZER = 'pickle'
> CELERY_RESULT_PERSISTENT = False
> CELERY_SEND_TASK_ERROR_EMAILS = True
> CELERY_BROKER_URL = "amqp://shop:shop@localhost/shop"
> CELERY_RESULT_BACKEND = "amqp://shop:shop@localhost:5672/shop"

After removing --pool=solo everything become ok.
Also i have other projects where i never met this problem before they are running with:
amqp (1.4.9)
billiard (3.3.0.23)
celery (3.1.25)
django-celery (3.1.17)
kombu (3.0.37)

Running by command: 

> python manage.py celery worker --concurrency=4 --pool=solo -n shop-worker

With the same settings.
The main question for me why i this error happens with celery 4, what i did wrong and also why removing of --pool=solo helped me. 
Also the bug still exists on other server i`m trying to understand what was happened.
Thanks.

**Comment by auvipy** [comment]
try from master or wait till 4.2 release
