### ISSUE TITLE
Grant Releasse Access to all maintainers

### ISSUE THREAD

**Issue by thedrow** [celery/celery#4183]
We have some libraries that have not been updated such as django-celery-beat and django-celery-results.
I don't have time to release them at the moment and I haven't tracked their status as of yet.

In order to prevent a situation where one person is the bottleneck for a release again we should: 
- [x] Grant @auvipy release rights to all celery related projects
- [x] <s>Grant @georgepsarakis release rights to all celery related projects</s>
- [ ] Grant me release rights to celery-sphinx-theme so I can provide the release rights to other current maintainers. @ask Can you please grant me the permissions to release that library.

Note that in order to release you need to reuse the PGP key I provided in the previous package. Feel free to contact me for instructions.

Please provide your PyPi usernames as soon as possible.

**Comment by auvipy** [comment]
pypi: auvipy/auvipy@gmail.com

**Comment by thedrow** [comment]
@auvipy Done. Can you please evaluate the status of django-celery-beat and django-celery-results? If they are good to go, please release them.

**Comment by georgepsarakis** [comment]
@thedrow @auvipy a suggestion here: I believe this process should be automated with the help of [Travis CI](https://docs.travis-ci.com/user/deployment/pypi/#Deploying-tags). It is probably considered a better practice (security and operational issues) to have an automated system of performing releases. Looking forward to hearing your thoughts.

**Comment by thedrow** [comment]
I agree but I need you guys to be able to do so without my intervention. I'm going to be away for a couple of weeks and I want to ensure that even if I won't be able to perform a release, somebody will.

**Comment by auvipy** [comment]
no. both of them need some work before a new release. I will try to complete them by this month.

**Comment by thedrow** [comment]
@georgepsarakis What are your PyPi credentials?

**Comment by georgepsarakis** [comment]
@thedrow I have given it some thought and I would prefer not to be involved in the release process for the time being. Sorry and really hope that this is not a major issue for now.

**Comment by thedrow** [comment]
@georgepsarakis it is not a problem. I'd just rather you'd have them in order to assign them to someone else if needed.
