### ISSUE TITLE
Do not consider GID 0 root if the UID is different.

### ISSUE THREAD

**Issue by ThiefMaster** [celery/celery#4186]
For example, on OpenShift containers the non-root user is in a group with GID 0. However, the user does not have root privileges in the container (and [GID 0 does not come with special privileges](https://unix.stackexchange.com/questions/44077/what-does-it-mean-to-be-in-group-0/44086#44086)).

I think it would make sense to only check for UID 0 instead of GID 0 to determine whether Celery is running as root.

**Comment by georgepsarakis** [comment]
I believe you can bypass this check by setting `C_FORCE_ROOT=1`. You can also check this answer [here](https://superuser.com/a/626845), for superuser uid/gid. The superuser detection seems to err on the safe side here.

**Comment by ThiefMaster** [comment]
Even with `C_FORCE_ROOT`, Celery will refuse to work when using Pickle for serialization/deserialization (which makes sense). My point is, that being GID 0 does not mean you are root. If you are root, you are very likely to have GID 0 but in certain PaaS environments (OpenShift for example) you have a user with a non-zero UID (i.e. you aren't root) but still GID 0.

To deal with the usual case of someone trying to run Celery as root, checking the uid+euid is enough - checking the gid just breaks cases like the one I just mentioned.

**Comment by georgepsarakis** [comment]
If I am reading the code correctly, when enabling `C_FORCE_ROOT`, even with the pickle serialization only a warning will be printed. However, if you happen to know a reliable way of detecting that the code is running on OpenShift, perhaps an exception for this platform can be put in place.

**Comment by ThiefMaster** [comment]
What's wrong with just checking the UID in any case? UID 0 is what makes you root - the GID doesn't really matter, so removing the check for it shouldn't reduce security.

**Comment by ThiefMaster** [comment]
You're right, `C_FORCE_ROOT` works indeed. I thought the pickle check was somewhere else. However, this would remove the - much more useful - check that prevents Celery from actually running as root.

**Comment by georgepsarakis** [comment]
@ThiefMaster I am not sure that this is accurate. It seems to me that if a user can write to files owned by the root group, it would be quite easy to elevate its privileges to become superuser (e.g. writing to `/etc/sudoers`). Of course this depends to system configuration, for example these critical files are not usually group writable and modifications are performed via sudo. In any case I would suggest to narrow it down to Openshift only, if possible.

**Comment by ThiefMaster** [comment]
Maybe checking whether it's running inside a container would be the best option: https://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker

**Comment by georgepsarakis** [comment]
Correct, seems accurate for Docker. Would you like to open a pull request for this?

**Comment by Sispheor** [comment]
Hello guys.
On Openshift 3.9 with Celery 4.2 it seems that the `C_FORCE_ROOT` flag is ignored.
I tried with
```
C_FORCE_ROOT=true
C_FORCE_ROOT=True
C_FORCE_ROOT=yes
C_FORCE_ROOT=1
```

I always get the same output
```
/usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is absolutely not recommended!
Please specify a different user using the --uid option.

User information: uid=1001280000 euid=1001280000 gid=0 egid=0
```

Not really a big deal because the process started anyway. Just FYI.

**Comment by ckvtvm-arch** [comment]
> Hello guys.
> On Openshift 3.9 with Celery 4.2 it seems that the `C_FORCE_ROOT` flag is ignored.
> I tried with
> 
> ```
> C_FORCE_ROOT=true
> C_FORCE_ROOT=True
> C_FORCE_ROOT=yes
> C_FORCE_ROOT=1
> ```
> 
> I always get the same output
> 
> ```
> /usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is absolutely not recommended!
> Please specify a different user using the --uid option.
> 
> User information: uid=1001280000 euid=1001280000 gid=0 egid=0
> ```
> 
> Not really a big deal because the process started anyway. Just FYI.

Can you please let me know how you resolved this. i am in the same boat ?
