### ISSUE TITLE
Link tasks between many workers

### ISSUE THREAD

**Issue by friendka** [celery/celery#4193]
I have 4 docker containers:

1) Redis (broker for celery)
2) Django app running with built-in server
3) Celery worker for django app with same code base
4) Another Celery worker with plain python code base

I have 2 tasks. First task is on 3'th worker, second is on 4'th worker. Second task uses return result of first one.

In django app (2) i have two views, one of them i use to add task, second one is for getting task results by task_id.

Code from view function in django app (2):
```
def add_task(request):
    celery_3 = Celery('app', broker='redis://redis_host:6379/0', backend='redis://redis_host:6379/1')
    celery_4 = Celery('editor', broker='redis://redis_host:6379/3', backend='redis://redis_host:6379/4')
    app_task = signature('app.tasks.AddMediaTask', args=(), app=celery_3)
    task = celery_4.send_task('editor.tasks.ProcessMediaTask', (request.POST.get('data'),), link=app_task)
    return render(request, template, {'task_id': task.task_id})
```

but both tasks goes to 4th worker and docker container fails with error:

`editor           | [2017-08-10 12:09:26,318: ERROR/MainProcess] Received unregistered task of type 'app.tasks.AddMediaTask'.
`

This is correct, because this task exist only in 3'th worker. Arg 'app' in signature does not affect?

This is a bug, or misunderstanding? And any chance to get app_task.task_id in 
add_task function?

**Comment by georgepsarakis** [comment]
I don't think this is possible. May I ask why you are instantiating two different Celery instances?

**Comment by friendka** [comment]
Thank for answer.

Different code base and dependencies, different servers. First worker is for media encoding purposes and should work on dedicated powerful server.
