### ISSUE TITLE
Update SQS requirements file

### ISSUE THREAD

**Issue by georgepsarakis** [celery/celery#4195]
As mentioned [here](https://github.com/celery/celery/issues/3701#issuecomment-322001007), the requirements file for the SQS broker, must use `boto3` instead of `boto` as dependency.

**Comment by villasv** [comment]
This seems pretty simple for a contribution. I want to get rid of installing boto3 separately in my project (tagging https://github.com/villasv/turbine/issues/18), so what now?

Just replace `boto>=2.13.3` with `boto3>=1.4.6` and PR?

**Comment by georgepsarakis** [comment]
@villasv correct.
