### ISSUE TITLE
Celery doesn't fetch settings properly

### ISSUE THREAD

**Issue by lcd1232** [celery/celery#4198]
## Checklist

- Celery 4.1.0
- python 3.6
- I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Install project - https://github.com/lcd1232/celery_django_test
```
$ git clone https://github.com/lcd1232/celery_django_test.git
$ cd celery_django_test
$ virtualenv -p python3 .env
$ source .env/bin/activate
$ pip install -r requirements.txt
$ ./manage.py runserver
```

The problem is that celery doesn't get settings **CELERY_TASK_ROUTES** https://github.com/lcd1232/celery_django_test/blob/752d45f43ba0a141ca23a36bb3a3ef76e9886391/celery_test/settings.py#L123 but if uncomment [celery_test/celery.py:21-25](https://github.com/lcd1232/celery_django_test/blob/master/celery_test/celery.py#L21) all works as expected.

## Update
I localized the problem. https://github.com/celery/celery/blob/master/celery/app/utils.py#L217
For example if we have in settings.py `TASK_ROUTES`, `is_in_new` and `is_in_old` will be empty set because `'TASK_ROUTES' != 'task_routes'`.
If we have in settings.py 'task_routes', variable `source` will not contain `task_routes`

**Comment by pachewise** [comment]
The actual old value is `CELERY_ROUTES`, but it still isn't honored by Celery for some reason. Doing some debugging, it looks like the settings value isn't really parsed into `app.conf.task_routes` (for some reason, the settings conf is added to the defaults).

**Comment by lcd1232** [comment]
@pachewise do you know how to fix this issue?

**Comment by pachewise** [comment]
not yet @lcd1232 - still trying to understand how `detect_settings` works. Maybe digging into the commit history will give us a better idea of what happened.

**Comment by georgepsarakis** [comment]
@pachewise @lcd1232 I do not see the issue exactly. If I do the following:

```
# settings.py
MYCELERY_TASK_ROUTES = {
    'celery_test.celery.*': {
        'queue': 'site.tasks.supertest',
    }
}
```

```
# Celery module
app = Celery('7vpn')
app.config_from_object('settings', namespace='MYCELERY')
```

The configuration contains the `task_routes` dictionary as expected. Could you please elaborate on what should be happening?

**Comment by pachewise** [comment]
@georgepsarakis turns out there were some misconfigurations, though there is a weird quirk that `print(app.conf)` shows `'task_routes': None`, while `print(app.conf['task_routes'])` shows the defined setting (probably due to how the Settings object works).

@lcd1232 You forgot to update your `settings.py` to point to where your task is...

````python
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672' # change to match your AMQP
CELERY_TASK_ROUTES = {
    'main.tasks.*': {
        'queue': 'site.tasks.supertest',
    }
}
````
![image](https://user-images.githubusercontent.com/2257119/29490073-338d1ef4-84e6-11e7-8ae1-717d1d535474.png)

**Comment by georgepsarakis** [comment]
Perhaps we need to add the configuration example to the documentation?

**Comment by syllogismos** [comment]
I'm facing the same issue, what is the work around for this, I am not able to use  `CELERY_TASK_ROUTES` to define custom queues based on tasks. I also found that app.conf['task_routes'] has the config I added, but not the app.conf object.

**Comment by pachewise** [comment]
@syllogismos - there wasn't an issue for OP's particular case, they had misconfigured. what's your `CELERY_TASK_ROUTES` and celery app look like?

**Comment by syllogismos** [comment]
Mine is a django app, and I was trying to use different queues for different tasks. And SQS backed.. I tried both SQS and redis but in both cases, the messages are only going to the default queue.

So my `CELERY_TASK_ROUTES` in `settings.py` looked something like this.

```
CELERY_TASK_ROUTES = {'app.tasks.my_task': 'my_queue'}
```

I tried various config options like defining `CELERY_TASK_QUEUES` with exchanges, routing keys and etc. From the celery documentation. But nothing worked. I finally ended up just defining the queue at the task definition instead as stated in this stackoverflow answer/discussion.
https://stackoverflow.com/questions/46373866/celery-multiple-queues-not-working-properly-all-the-tasks-are-sent-to-default-q

**Comment by pachewise** [comment]
do you have an `app/tasks.py` module?

````python
CELERY_TASK_ROUTES = {
    'app.tasks.my_task': { 
        'queue': 'my_queue'
    }
}
````

this should be in your settings.py, and then you'll have to load the settings from your app; for example:

````python
app = Celery('7vpn') 
app.config_from_object('absolute.import.to.settings') # TODO replace with correct import path
# you should also be able to pass in the django.conf.settings object, but I haven't tried that
````

**Comment by syllogismos** [comment]
I did try that. It didn't work for me. But haven't tried the `app.config_from_object('absolute.import.to.django.settings')` I used the one from the documentation where they suggest to use `django.conf.settings`

Anyway I printed the app.conf object after loading the config, and I do see the routes settings when i print them using app.conf['task_routes'] but dont see them when I print the app.conf object. Also note that other celery settings are being applied, like celeyd_log_format and things like that. I only have problem with task_routes.

**Comment by arsenio** [comment]
I just went through the same thing (using Flask, not Django, for what it's worth). `CELERY_TASK_ROUTES` doesn't seem to work when using `celery.conf.update()`, but `CELERY_ROUTES` does.

**Comment by shitikanth** [comment]
Just wasted an hour on this. Guys, please fix the documentation. How hard can it be to rename some variables in the documentation?

**Comment by sparrowt** [comment]
If you come here confused about the difference between `CELERY_ROUTES` and `CELERY_TASK_ROUTES` (or `CELERY_QUEUES` & `CELERY_TASK_QUEUES`) then take a look at [this comment on a related issue](https://github.com/celery/celery/issues/5026#issuecomment-451143900).
