### ISSUE TITLE
Celery beat keeps running after supervisor stopped it

### ISSUE THREAD

**Issue by martialp** [celery/celery#4199]
## Steps to reproduce
Use the `extra/supervisord/celerybeat.conf` file to daemonize celery beat
 
## Expected behavior
Supervisor should be able to start and stop celery beat

## Actual behavior
Supervisor can start beat, but when the stop signal is sent, beat keeps running.

Adding `stopasgroup=true` to celerybeat.conf fix the problem. I also noticed that the celeryd.conf file already include `killasgroup=true`. It should probably be `stopasgroup=true` too, because the latter seems to allow not only the SIGKILL, but other more graceful signals (see [supervisor documentation](http://supervisord.org/configuration.html)).

Note that `stopasgroup` didn't exist when killasgroup [has been added](https://github.com/celery/celery/commit/637b4adf7a129fcf0c0a4cdac57946e63ccf9ec3) in the celeryd.conf file. Here is the supervisor [changelog](http://supervisord.org/changes.html#b1-2012-09-10).

**Comment by georgepsarakis** [comment]
Good catch! It sounds to me that perhaps both boolean options should be defined for both graceful and immediate shutdown. Would you like to open a pull request for this?

**Comment by martialp** [comment]
In fact, `stopasgroup` implies `killasgroup` is true ([http://supervisord.org/configuration.html](http://supervisord.org/configuration.html)). So, `stopasgroup` alone should be fine. I will open a pull request for this!
