### ISSUE TITLE
-u option does not exist

### ISSUE THREAD

**Issue by diemuzi** [celery/celery#4201]
## Steps to reproduce

Start -> celery -A application worker -l info

## Actual behavior

RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid

## Fixes

When displaying the help menu -> celery -A application worker -l info -h

There is currently no longer a -u option and the warning should be changed to use --uid / --gid options

**Comment by georgepsarakis** [comment]
Nice observation. Would you like to open a pull request for this?

**Comment by diemuzi** [comment]
Yes, sorry about that. Thought I had created it. It's there now =)
