### ISSUE TITLE
Error while run celery SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by Qingyangsun** [celery/celery#4202]
I have a task on my server, it run well when it started,but it appear the issue and shut down hours later.
`SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by georgepsarakis** [comment]
Can you please provide the complete stack trace?

**Comment by Qingyangsun** [comment]
`Traceback (most recent call last):
  File "/opt/hrbp_spider/hrbp_spider_env/lib/python3.5/site-packages/celery/__main__.py", line 4, in <module>
    from . import maybe_patch_concurrency
SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by auvipy** [comment]
please follow the docs and try again on top of master
