### ISSUE TITLE
task_reject_on_worker_lost throws WorkerLostException

### ISSUE THREAD

**Issue by tkram01** [celery/celery#4229]
It seems that the task_reject_on_worker_lost settings does not work when killed with a SIGTERM signal and returning results. After the worker is killed (kill -SIGTERM <pid>) any calls to AsyncResult.get() will throw a WorkerLostException. The task is rescheduled as expected but you can't access the results anymore since the AsyncResult is in an error state.

Checklist

- [x]  I have included the output of celery -A proj report in the issue.
- [x]  I have verified that the issue exists against the master branch of Celery.
- [x] => Tested with Celery 4.1.0

Steps to reproduce

1. Create a task with ack_late=True and reject_on_worker_lost=True
2. Run task
3. Kill Celery while the task is running (e.g. with kill -9 <pid> or pressing Ctrl+C twice)
4. See sample below.

Expected behavior

The task is executed once the Celery worker is started again without an exception being thrown and the results available through the original AsyncResult object.

Actual behavior

A WorkerLost exception is thrown and the results are not accessible.

Sample:

```
import time
from celery import Celery

app = Celery('tasks', broker=amqp://celery:celery@localhost:5672/celery')

@app.task(bind=True, acks_late=True, reject_on_worker_lost=True)
def example(self):
    print(self.acks_late)  # => make sure is True
    print(self.reject_on_worker_lost)  # => make sure is True

    print('Sleep')
    time.sleep(30)  # ==> Kill Celery while here
    print('Wakeup')

result_proxy = example.apply_async()
while 1:
    try:
        print(result_proxy.get())
        break
    except WorkerLostError as e:
        print(e)

```
celery report -A proj output of sample code:

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.2.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis

task_acks_late: True
worker_disable_rate_limits: True
result_serializer: 'pickle'
get_packages_containing: <function get_packages_containing at 0x10426d620>
task_reject_on_worker_lost: True
task_serializer: 'pickle'
worker_redirect_stdouts_level: 'Debug'
result_backend: 'redis'
worker_prefetch_multiplier: 1
worker_log_format: ('%(asctime)s: %(levelname)s/%(processName)s:  '
 '%(task_name)s : %(message)s')
worker_task_log_format: ('%(asctime)s: %(levelname)s/%(processName)s:  '
 '%(task_name)s : %(message)s')
imports: ['services.example.math_example']
broker_url: 'amqp://celery:********@localhost:5672/celery'
accept_content: ['pickle']
result_expires: 1200
worker_redirect_stdouts: True
```

**Comment by auvipy** [comment]
could you verify this again on top of master branch? and try upgrading all the dependencies
