### ISSUE TITLE
Failed test execution due to inconsistent boto3 version requirements

### ISSUE THREAD

**Issue by agladkov** [celery/celery#4242]
Double requirement given: boto3==1.4.3 (from -r /home/travis/build/celery/celery/requirements/extras/dynamodb.txt (line 1)) (already in boto3>=1.4.6 (from -r /home/travis/build/celery/celery/requirements/extras/sqs.txt (line 1)), name='boto3')

**Comment by thedrow** [comment]
This is fixed in #4243.
