### ISSUE TITLE
Unit Testing: self.request.chain is None when CELERY_TASK_ALWAYS_EAGER=True

### ISSUE THREAD

**Issue by chutes** [celery/celery#4247]
using celery v4.1.0

During unit testing I discovered that when CELERY_TASK_ALWAYS_EAGER=True, self.request.chain = None, while in production, self.request.chain has value.

This is problematic during unit testing since behavior between unit tests and production are dissimilar.

**Comment by auvipy** [comment]
what is your intended outcome should be?
