### ISSUE TITLE
SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by xtuyaowu** [celery/celery#4249]
hi can anyone help?
python3.5
celery:4.0.1
Traceback (most recent call last):
  File "/opt/lib/python3.5/site-packages/celery/__main__.py", line 4, in <module>
    from . import maybe_patch_concurrency
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by pachewise** [comment]
how are you running celery?

**Comment by xtuyaowu** [comment]
hi pachewise i run celery                                                                                                                             nohup python -m celery worker -l INFO -c 10 -A apps.celery_init.celery &

**Comment by pachewise** [comment]
does `celery worker -l INFO -c 10 &` work for you?

**Comment by auvipy** [comment]
try latest branch and docs and if still problem exist please report
