### ISSUE TITLE
Task com.seansu4you87.task2[fc09a3e5-e7ed-40ac-90b1-0a5da527cdc6] raised unexpected: WorkerLostError('Worker exited prematurely: exitcode 0.',)

### ISSUE THREAD

**Issue by seansu4you87** [celery/celery#4250]
This is for `celery==3.1.23`

Hi there, I'm getting the following error maybe once to twice a day, out of 100,000 tasks per day.  
This task is payments related, and it's important for each task to process at least once (the job is idempotent).

Error:
```
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1175, in mark_as_worker_lost human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.
```

I have configured the `acks_late=True`, `reject_on_worker_lost=True`, and `max_retries=3` options on the task.  However, when I check my logs, I don't see these `WorkerLostError` failures ever having been retried (I searched the task uuid in my logs).  I've configured a custom annotation for a retry-able job like so:

```
def bank_service_task(func):
    @task(bind=True, queue=Queue.PAYMENTS, acks_late=True, reject_on_worker_lost=True, max_retries=3)
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        try:
            func(*args, **kwargs)
        except Exception as e:
            worker = billiard.current_process()
            logger.info("Worker {}: {} retry for task {}, due to {}".format(worker.index, self.request.retries, self.request.id, e))
            self.retry(exc=e, countdown=2 ** self.request.retries)

    return wrapper
```

I'm expecting tasks configured with this annotation to execute up to 3 times with exponential decay, until which it would stop retry-ing (question about this at the end).  However, what I'm seeing is that very occasionally (1/100,000), the task hits an application exception, is never retried, and then the worker dies with `WorkerLostError: Worker exited prematurely: exitcode 0.`.  My understanding is that the `reject_on_worker_lost` setting would make sure that `WorkerLostErrors` keep the task in RabbitMQ, until it has been successfully processed, or exhausts all of its retries.

1. Can you please advise on how to fix or further debug this issue? 
2. After the last retry, what's the best way to catch that all retries have been exhausted, and run some custom code (i.e. sending a notification or page out to the team).

Thanks for your time!

**Comment by seansu4you87** [comment]
Bumping this issue, thanks

**Comment by deterb** [comment]
I'm also seeing worker lost errors with exit code 0, but with different circumstances.  I've seen it crop up in two main cases: one with a MAX_TASKS_PER_CHILD, where I was seeing an exit code 155 (which is Billiard's I'm replacing this worker exit code) fairly consistently and with exit code 0 when stopping a worker (both Ctrl-C with a `celery worker` running int the foreground and with a celery multi background worker).

I think I'm able to catch in Celery 4.1.0 with the many argument error handler (have at least 3 arguments for the on_error signature).  Traceback gives a oneline at billiard.pool:1223 at the raise in mark_as_worker_lost.  Note that the on_error catch probably won't work in 3.1.23 (or 3.1.25) as I haven't seen it getting called for segfaulting tasks.

**Comment by thedrow** [comment]
We don't support 3.x anymore. Sorry.
@deterb Please search the list of issues. I'm sure your issue exists for 4.1.
If it is not, please open a new one.
