### ISSUE TITLE
Issue with import name(conflict app name with python module name)

### ISSUE THREAD

**Issue by suhailars** [celery/celery#4256]
## Checklist

-  I have an app in django as social(app name)  also using 'social_django' module 
-  but 'social_django' django have dependency module python 'social' 
-  both having same name as 'social' due to this autodiscover_tasks giving wromg path for django app social
**_installed app for django_**
```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'social',
]
 ```

## Steps to reproduce
add _social_django_ in installed app also create django app with same name as _social_ 
now check path coming in fuction **_find_related_module_** at _**/lib/python3.5/site-packages/celery/loaders/base.py**_
```python
        def find_related_module(package, related_name):
            """Find module in package."""
            # Django 1.7 allows for speciying a class name in INSTALLED_APPS.
            # (Issue #2248).
            print("import ", package)
            try:
                importlib.import_module(package)
            except ImportError:
                print("error at import")
                package, _, _ = package.rpartition('.')
                if not package:
                    raise       

            try:
                pkg_path = importlib.import_module(package).__path__
            except AttributeError:
                return      

            try:
                _imp.find_module(related_name, pkg_path)
            except Exception as e:
                print ("error at import", e)
                return
```
the following line  is creating the bug 
```python
  pkg_path = importlib.import_module(package).__path__
```
## Expected behavior
expected path :: `/home/user/workspace/project/social`
## Actual behavior
actual path:: `/lib/python3.5/site-packages/social`

**Comment by auvipy** [comment]
I don't think it's a celery issue. check your packages and apps

**Comment by auvipy** [comment]
both should be from site package

**Comment by auvipy** [comment]
but if you have any suggested workaround feel free to send pr
