### ISSUE TITLE
Is celery 3 still supported?

### ISSUE THREAD

**Issue by bolkedebruin** [celery/celery#4258]
Hi there,

Im an Apache Airflow maintainer and we use celery as our main scaling out possibilities. We are doing a major release shortly and I would like to know if we should push our users to celery 4.X. We support celery 3 ourselves at the moment, but I don't know if you are still pushing patches to Celery 3.

Thanks!

**Comment by thedrow** [comment]
We're not pushing patches to Celery 3 as we lack the capacity to do so.
In any case, Celery 4.1 is much more stable and does not hang as often. We encourage people to upgrade as soon as possible.
