### ISSUE TITLE
Base 10 on Redis Password

### ISSUE THREAD

**Issue by adityosnrost** [celery/celery#4265]
## Problem

I have problem on using string contains Base 10 for Redis password on CELERY_BROKER_URL.
Error shown like this:

![image](https://user-images.githubusercontent.com/8223156/30415893-4ed720ce-9954-11e7-883c-2653c5c0fbcf.png)

## Reproduce

This is the code on init CELERY_BROKER_URL:
`app.config['CELERY_BROKER_URL'] = 'redis://'+str(dataConfig['redis']['password'])+'@'+str(dataConfig['redis']['url'])+':'+str(dataConfig['redis']['port'])+'/'+str(dataConfig['redis']['db'])`

Redis example password:
**redis://dsa86321hsd792194e8r1MiFyxz+9r/A=@redisserversomewhere:6380/14**

Celery worker run command:
celery worker -A sampleapp.views.celery --loglevel=info

## Question

How I can use Base 10 password on this case ? Our Redis server password always generate password with string that contain Base 10 char.

Thank You

**Comment by georgepsarakis** [comment]
Have you tried URL-encoding the password? The `\` it contains seems to be breaking the parsing.

**Comment by thedrow** [comment]
No response and no actionable item. I'm closing this.
