### ISSUE TITLE
How to check task status by task_id

### ISSUE THREAD

**Issue by WeipingGuo** [celery/celery#4271]
Hi,

Need your input on how to check the task status. I am running 4.0.2 with redis as backend. From a simple testing program, I am trying to create the task using delay() method. I got the AsyncResult with task_id. 

I know this task somehow is not picked by my worker, but just want to know where I can check its status, from redis?  What should I look?

Thanks
Weiping

**Comment by georgepsarakis** [comment]
Have you tried using [Flower](http://flower.readthedocs.io/en/latest/)?

**Comment by WeipingGuo** [comment]
Thanks a lot for quick response. Yes, I tried. Flower did not show it. Something is missing from my code, not sure where. If I can get a task_id back, does it mean the task is sent successfully?

**Comment by fptiangco** [comment]
A sample below:
```
>>> from tasks import long_task
>>> mytask = long_task.delay(1)
>>> mytask.state
u'PENDING'
```
The snippet above shows that the task is still `PENDING`, but this [doc](http://docs.celeryproject.org/en/latest/reference/celery.states.html#id9) should explain what other states you can also retrieve (e.g. a `SUCCESS` or a `FAILURE`). These would then represent receipt or completion of a task.

**Comment by nszceta** [comment]
@WeipingGuo 

Have you tried this?

worker_send_task_events
Default: Disabled by default.

Send task-related events so that tasks can be monitored using tools like flower. Sets the default value for the workers -E argument.
