### ISSUE TITLE
Celery slows down on concurrency 8 with single worker and it took very long to picj 

### ISSUE THREAD

**Issue by gauravt1** [celery/celery#4273]
I am using Celery-3.1.20 in my project I tried with 7 concurrent tasks on with Redis broker, It picks the very first tasks after 4-5 mins and it runs very slow taking around 1 minute to execute subtasks which would not take more than 20 secs to execute.

## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Expected behavior
It needs to respond in a usual time rather than taking so long.
## Actual behavior
It pick the first task after 5 mins and it also takes very long to process subtasks.

Am I doing something wrong? Please advise!

**Comment by listingmirror** [comment]
What OS are you running on?

How many CPUs does your celery box have?  

What is their load before and during running this task?

Celery has a pretty light overhead. If it takes 2 minutes to run X work without celery, it should take like 2.01 minutes to run the tasks under celery. The only time you would see celery overhead killing you is if you are doing many many tasks that last under 10ms or so, which does not seem to be your case?

**Comment by auvipy** [comment]
I would suggest to use the latest releases of celery and check again.
