### ISSUE TITLE
TypeError: get() got an unexpected keyword argument 'on_interval' when nested chain ends in group

### ISSUE THREAD

**Issue by craiga** [celery/celery#4274]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Given this task…

```python
from myapp.celery import app

@app.task
def say_something(msg):
    print(msg)
```

…this moderately complex workflow…

```python
import celery

from myapp.tasks import say_something

workflow = celery.chain(
    say_something.si('outer chain start'),
    celery.group(
        say_something.si('outer group'),
        celery.chain(
            say_something.si('inner chain start'),
            celery.group(
                say_something.si('inner group a'),
                say_something.si('inner group b'),
            ),
            # say_something.si('inner chain end'),
        ),
    ),
    say_something.si('outer chain end'),
)

workflow.delay()
```

…causes this error…

    ERROR:celery.app.builtins:Chord '70cb9fbe-4843-49ba-879e-6ffd76d63226' raised: TypeError("get() got an unexpected keyword argument 'on_interval'",)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/celery/app/builtins.py", line 80, in unlock_chord
        ret = j(timeout=3.0, propagate=True)
      File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 698, in join
        interval=interval, no_ack=no_ack, on_interval=on_interval,
    TypeError: get() got an unexpected keyword argument 'on_interval'
    INFO:celery.app.trace:Task celery.chord_unlock[cac53aaf-c193-442c-b060-73577be77d0f] succeeded in 0.04921864200150594s: None

…and the `outer chain end` task is never executed.

If I un-comment the `inner chain end` task, the whole workflow executes as expected.

Below is a sample of the output of `celery -A proj report`:

    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.1
                billiard:3.5.0.3 py-amqp:2.2.2
    platform -> system:Linux arch:64bit, ELF imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:amqp results:django-db
    
    BROKER_URL: 'amqp://admin:********@rabbitmq:5672//'
    
    CELERY_ACCEPT_CONTENT: ['json']
    CELERY_RESULT_BACKEND: 'django-db'
    CELERY_TASK_SERIALIZER: 'json'
    CELERY_WORKER_HIJACK_ROOT_LOGGER: False

## Expected behaviour

The `outer chain end` should be executed once all other tasks have completed.

## Actual behavior

    ERROR:celery.app.builtins:Chord '70cb9fbe-4843-49ba-879e-6ffd76d63226' raised: TypeError("get() got an unexpected keyword argument 'on_interval'",)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/celery/app/builtins.py", line 80, in unlock_chord
        ret = j(timeout=3.0, propagate=True)
      File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 698, in join
        interval=interval, no_ack=no_ack, on_interval=on_interval,
    TypeError: get() got an unexpected keyword argument 'on_interval'
    INFO:celery.app.trace:Task celery.chord_unlock[cac53aaf-c193-442c-b060-73577be77d0f] succeeded in 0.04921864200150594s: None

**Comment by craiga** [comment]
I believe there may be a similar issue when a `celery.group` is comprised solely of `celery.chain` tasks.

I can work around this issue by adding a `noop` task.

    @app.task
    def noop():
        """No-operation task, used to address https://github.com/celery/celery/issues/4274."""
        pass

**Comment by myw** [comment]
@craiga I took a crack at fixing this—mind letting me know if it does the trick in your case?

**Comment by myw** [comment]
Also worth noting that that this error only seems to occur when the result backend does not support native join.
