### ISSUE TITLE
Eager / Non eager mode argument differences

### ISSUE THREAD

**Issue by geoffreybauduin** [celery/celery#4275]
Hello,

after doing some digging, it seems that there's a behavior difference between eager/non eager modes.
Code examples are in the following gist: https://gist.github.com/geoffreybauduin/b3d5606ee5167b137097c9917880e21a, as well as output from those 2 program runs.

We would expect having the same behavior in eager and non eager, so basically, in that case, the datetime.datetime object should always be received, in the task, as a `unicode`. But it's not the case: in eager mode, it is received as `datetime.datetime`.

Is it a wanted behavior, or is it something that could be patched ?

**Comment by auvipy** [comment]
it's better to post this type of questions to https://groups.google.com/forum/#!forum/celery-users
