### ISSUE TITLE
Celery Flower dashboard task information source 

### ISSUE THREAD

**Issue by desuanil** [celery/celery#4277]
Currently, we have setup celery with rabbitmq as broker. The task information like Name, UUID, state etc is displayed in the front end. In this context, I have a question on the source of this task information in celery flower web UI dashboard, what is the source of this info. Is it fetching from rabbitmq or celery maintains its own persistent location. Please help

**Comment by johnarnold** [comment]
Flower stores event data in an in-mem cache.

**Comment by auvipy** [comment]
plz ask this type of questions to mailing list or irc.
