### ISSUE TITLE
What prevents celery events to support SQS?

### ISSUE THREAD

**Issue by mp3il** [celery/celery#4279]
Hi guys,

I'm using Celery @ Elasticbeanstalk, so my go-to queue is obviously SQS. but I just found out that 'celery events' doesn't support SQS. so monitoring isn't possible :(

Can someone elaborate on where is this issue stands? I would love to try and contribute if possible, but couldn't find any info about why its currently not supported.

Thanks.

**Comment by auvipy** [comment]
check the kombu and celery internal and docs about contribution

**Comment by auvipy** [comment]
http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html
