### ISSUE TITLE
Prioritizing queue among multiple queues?

### ISSUE THREAD

**Issue by arunk2** [celery/celery#4282]
We have 2 queues for processing different priority tasks. We have 2 cluster of nodes serving them separately. Things are working well as expected.

### Question:
We get mostly low priority tasks. For optimized resource utilization, I am wondering is there a way to configure workers(listening to high priority queue) to listen to both queues. But take jobs from the higher priority queue as long as some job is there? and fallback to low priority queue otherwise.

**Comment by georgepsarakis** [comment]
I think you can achieve this by defining multiple queues for the [worker](http://docs.celeryproject.org/en/latest/userguide/workers.html#queues), when starting it.

**Comment by arunk2** [comment]
Currently we have implemented it that way. We have 2 workers in the machines processing high priority tasks. But the problem is fallback kind of approach, where all resource should be used only for the high priority queue and process other queue when it is empty.
With multiple workers, it is taking low priority tasks even when something is there to process in high priority queue.

**Comment by arunk2** [comment]
Closing this issue as the workaround seems to work well for most of the situation and having higher % reservation for high priority tasks (like 75%) works well.
