### ISSUE TITLE
[Question] How to test if rabbitMQ is set?

### ISSUE THREAD

**Issue by hsiaoyi0504** [celery/celery#4283]
Hello, maybe it's a stupid question, but I can't find the answer through the document or previous issues, even google a while. I also checked the test cases for celery project, but I missed in so many files of the test cases.

I want to know how to program a test to check the rabbitMQ is set ?

Our project is based on Django combined with celery + rabbitMQ, and we want to write some test cases to check the whole environment of our project is set. I find there is a way to check if the celery is working or not. https://stackoverflow.com/questions/8506914/detect-whether-celery-is-available-running.

But I am curious about how to write test for testing the broker, i.e. RabbitMQ here is working or not ? I think the basic call of `Celery` will not test the broker automatically.

Thank you in advance.

**Comment by thedrow** [comment]
You can simply create a ping task and if it is completed and a result is returned then RabbitMQ works.

**Comment by hsiaoyi0504** [comment]
@thedrow Can you give my a real example of that? I prefer to write a program that in python script rather than using the celery command line utilities.

**Comment by thedrow** [comment]
This is a good example https://github.com/celery/celery/blob/master/celery/contrib/testing/tasks.py#L7
