### ISSUE TITLE
Wrong configuration name CELERY_TASK_ACKS_LATE  in celery 4.1 doc

### ISSUE THREAD

**Issue by chenfengyuan** [celery/celery#4286]
celery doc url is [v4.1.0](http://docs.celeryproject.org/en/v4.1.0/userguide/configuration.html)
I suppose the correct ack_late configuration name is `CELERY_ACKS_LATE`(old version) or `task_acks_late`(new version), not `CELERY_TASK_ACKS_LATE`.
current(latest, 4.1) doc is misleading

**Comment by thedrow** [comment]
PRs welcome :)

**Comment by sposs** [comment]
I stumbled on this and I think it's relevant to add that for a django config, the name is `CELERY_TASK_ACKS_LATE`, as it's the `CELERY_`-prefixed of the upper-cased version of the new setting: `task_acks_late`. Slightly confusing...
