### ISSUE TITLE
task succeeded but expected to be revoke via expires

### ISSUE THREAD

**Issue by jheld** [celery/celery#4287]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
software -> celery:4.0.2 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython (note we are running on ubuntu actually. this is just a local print out)
loader   -> celery.loaders.app.AppLoader

settings -> transport:redis 
results is also redis

BROKER_TRANSPORT_OPTIONS: {
    'fanout_patterns': True, 'fanout_prefix': True}
CELERY_TASK_COMPRESSION: 'gzip'
CELERY_TIMEZONE: 'UTC'
CELERY_ACCEPT_CONTENT: ['application/json']
CELERY_RESULT_EXPIRES: 60
CELERY_TASK_SERIALIZER: 'json'

- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Warning, this is not (from what I can tell) deterministic/easily reproducible.

In this case, the task is enqueued (`apply_async`) with a 4 second `expires`. Note, I did not use a `datetime` object. Please the `Actual behavior` section for the times reported by flower.

Then see the task run.

## Expected behavior

I expect that the task will get enqueued, and when it's about to run, the worker will see that it is past the expirey time, so it will revoke the task.

## Actual behavior
From flower's UI:
State | SUCCESS

Received | 2017-09-25 17:07:19.522151 UTC
Started | 2017-09-25 17:07:26.551319 UTC
Succeeded | 2017-09-25 17:07:27.365117 UTC
Expires | 2017-09-25T17:07:23.517932+00:00

**Comment by auvipy** [comment]
try the latest master branch and report for reopening
