### ISSUE TITLE
question: How to get information about periodic tasks like 'next in queue', ETA, etc?

### ISSUE THREAD

**Issue by skamsie** [celery/celery#4288]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: u'redis://localhost:6379/0'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

More a question than a bug. Is there any way of getting data about the upcoming periodic tasks? For example, file _tasks.py_

```
import random
from celery import Celery
from celery.schedules import crontab

app = Celery('tasks', broker='redis://localhost:6379/0')

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(100, test.s(30000), name='every 100')

    sender.add_periodic_task(10, test.s(100), name='every 10')

    # Executes every Monday morning at 7:30 a.m.
    sender.add_periodic_task(
        crontab(hour=7, minute=30, day_of_week=1),
        test.s(40),
    )

@app.task
def test(x):
    return random.choice(range(x))
```

This works correctly if I run with `celery -A tasks worker --loglevel=info --beat -E`. But how can inspect the upcoming tasks from a console? I see that inspect.scheduled() shows nothing for periodic tasks...

Considering the example above, let's say I started the server 3 seconds ago, is there any way to see that there is a pending task in ~7 seconds, another one in ~97 seconds and another one for next Monday at 7:30?

**Comment by auvipy** [comment]
this type of questions better fitted for celery-users mailing list or IRC
