### ISSUE TITLE
Celery doesn't discover tasks that are not imported globally

### ISSUE THREAD

**Issue by paulfab** [celery/celery#4289]
Hi
## Checklist
-celery:4.0.2 
-sorry didnt try with the master of celery

## Steps to reproduce
If you have an app named ``command`` and two files in it ``command/models.py`` and ``command/example.py`` 
if ``example.py`` is not globally imported in a file of the django project (let say  ``models.py``) then celery won't auto discover the tasks which are in ``example.py`` 

example.py:
```
from celery import shared_task

@shared_task()
def aa():
	pass
```
models.py
```
def test():
	from .ta import aa
	aa.delay()
```
then 
``celery -A proj worker -l info`` doesn't show ``example.aa``

but

if ``models.py`` is like that : 
```
from .ta import aa
def test():
	aa.delay()
```

Then celery auto discover the task ``example.aa``

## Expected behavior

I expect the task to be auto discover even if the import is local to a function

## Actual behavior
Doesn't auto discover when the import is local but found if the import is global

**Comment by marco-silva0000** [comment]
I was looking into a problem I'm having and found your issue. The autodiscover_tasks function has a default argument related_name='tasks', and I belive that the tasks will be imported only if the file has that name..

**Comment by auvipy** [comment]
you could use the latest release or master branch and ask for help in mailing list, if still it seems to be a bug pin me here to reopen.
