### ISSUE TITLE
Explanation surrounding __json__ / deserialization

### ISSUE THREAD

**Issue by tylerjharden** [celery/celery#4294]
This is not an actual issue with the functionality of Celery per-say, as much as it is a request for additional documentation or exaplantion.

The documentation for 4.0+ here: http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#json-is-now-the-default-serializer

Indicates that Celery uses the JSON serializer by default, and that by declaring a `__json__` method on your class, Celery's serializer can automatically serialize these instances for consumption via tasks. My question is, with only a serialization method, how is Celery deserializing these JSON-compliant objects back into the respective class types?

I ask because we tend to utilize type annotation / hinting on functions, including our Celery tasks, and it seems like everything works as long as we consume what was originally say `Person` class with a well-defined `__json__` as a `dict` and handle re-initializing a new class instance manually.

Is there support for deserialization out of the box that simply missed being documentation? Is this even possible? If not, can someone with a deeper grasp of Celery explain why / how this decision was made?

**Comment by auvipy** [comment]
you would get the answer of the question by digging into the code or on a thread in the mailing list.
