### ISSUE TITLE
Not Found: /id

### ISSUE THREAD

**Issue by quertenmont** [celery/celery#4306]
Hello,

Since I have included celery into my django project,
I am periodically getting some http request at "/id" of my side,
for which I do not have any corresponding URL.

Could you tell me how to suppress these spurious request, or how to properly use them

Thanks in advance,
Loic

**Comment by thedrow** [comment]
I don't believe this is Celery's doing. There's nothing in the code base that performs such HTTP requests.
Feel free to search the code and let us know if this is not the case.

In the meanwhile, I'm gonna close this issue and we'll revisit when and if there is an actionable problem to solve.
