### ISSUE TITLE
pseudo random jitter can cause dead lock

### ISSUE THREAD

**Issue by codingjoe** [celery/celery#4316]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

Versions affected: None (not yet released)
On master: Yes, added in 0d5b840af1890a9a499a339aa3256445b43837dc

## Steps to reproduce

https://github.com/celery/celery/blob/d59518f5fb68957b2d179aa572af6f58cd02de40/celery/utils/time.py#L390-L404

Image you have two workers that pull the same task from a queue at the same time and fail, do tue a lock for example. If you would retry and backoff, we have the `jitter` that should prevent those tasks to be executed at the same time and thus preventing a deadlock. But `random.seed` will default to the current system time, if there is no better function provided. This can mean that two if two workers would fail at the same milli-second, they would in fact end up in a dead lock, since the `jitter` will be the same, since the seed is the same.

## Expected behavior

In python 3.5 we have secrets, which would prevent this. In Python 2 we have to find an alternative. If we have a unique identifier for a worker, we can add this to the epoch as a new and unique seed.

## Actual behavior

Two or more tasks could be dead locked because of the pseudo random `jitter`.

**Comment by georgepsarakis** [comment]
As far as I understand from the Python [random module documentation](https://docs.python.org/2/library/random.html#random.seed), the majority of systems will support `os.urandom` which will be used internally in `random.seed`. The race condition you are describing sounds possible but to me seems highly improbable. If you have observed this behavior in an actual deployment of Celery, please describe the exact details (OS, Python version, task example).

**Comment by codingjoe** [comment]
I agree, this is a super duper edge case ;) I also didn't run into it yet, but if you have billions of tasks this might just happen.
Feel free to close it.

**Comment by auvipy** [comment]
will reopen if the issue has a real effect.
