### ISSUE TITLE
Strange coupling between sender and worker when having massive tasks, gevent and openurl.

### ISSUE THREAD

**Issue by julmarci** [celery/celery#4317]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

Environment: celery 4.1, rabbitmq and rpc backend.

I'm using apscheduler in order to schedule massive groups of tasks (hundred or thousands) and be able to dynamically change that scheduling. Both apscheduler and celery worker are using gevent so that huge number of corrutines (pseudo-threads) can be launch concurrently to access urls with async I/O.

Right now I'm just doing some tests, so I open ulrs like google.com or bing.com which reply very fast. The weird issue is that everything runs quick and smoothly right up until the very moment when the tasks in the worker finish. At this point the rest of results start to arrive exactly one per second while the previous ones were arriving in no time.

Some hints:
- This only happens when the tasks open an url (with urllib2 or requests, it doesn't matter)
- It happens indistinctly launching a few or a lot of tasks, when the worker finish (at second 1 or at second 20), the frequency of result arrivals slow downs.
- This happens when I do AsyncResult.get() but not when using AsyncResult.result (but in this case I don't know how to remove the tasks from the queue :-(  )
- This only happens when I launch all the tasks at once. If I do all the work in a for loop everything runs alright.

This is driving me crazy. Any idea of what can be happening?
In fact, for my work what would come best would be knowing how to delete tasks after doing the AsyncResult.result (by the way that gevent works)

## Update

I've been playing with the tests looking for a workaround and what I have found is:

- this issue happens with the rpc backend but not with amqp. However, you know, amqp is deprecated and not efficient.
- I tryed to gather the results with a pool of threads instead of greenlets and the consequence is a "socket.timeout" (again it does not happen when using amqp backend)
- and the weirdest thing is that if I call the AsyncResult.ready() function before the AsyncResult.get() this strange coupling goes away but the tasks messages are not acknowledge (the same thing that ocurred when reading just with the AsyncResult.result) This is the state of queue messages when the tasks are completed (as shown with Flower):

         Ready: 1
         Unacked: 499
         Total: 500

**Comment by julmarci** [comment]
Maybe some code helps:

# celery.py
```
from __future__ import absolute_import, unicode_literals
from celery import Celery

app = Celery('proj',
             broker='amqp://',
             backend='rpc://',
             include=['proj.tasks'])

app.conf.update(
    result_expires=3600,
)

if __name__ == '__main__':
    app.start()

```
# tasks.py
````
from __future__ import absolute_import, unicode_literals
from .celery import app
from datetime import datetime
import urllib2
import simplejson as json
import time
import requests

@app.task
def tick(n):
    date = datetime.now()
    a = 0
    for i in range(9999):
        a+=i
    print('Tick: '+str(n)+' The time is: %s' % date)
    return n

@app.task
def peticionweb(n):
    date = datetime.now()
    print('Petition: '+str(n)+' The time is: %s' % date)
    response = urllib2.urlopen('http://date.jsontest.com/')
    result = response.read()
    json_result = json.loads(result)
    date2 = json_result['time']
    response.close()
    date = datetime.now()
    print('Petition end: '+str(n)+' The time is: %s' % date+ ' Readed:'+date2)

    return n
````

# test_celery_gevent.py
```
from datetime import datetime
import time
import random
import threading
import sys
from apscheduler.schedulers.gevent import GeventScheduler
import logging

from gevent.queue import Queue
import gevent

from proj.tasks import tick
from proj.tasks import peticionweb


logging.basicConfig() 
    
    
def peticion(n):
    res = peticionweb.delay(n)
    message_queue.put(res)
    
def receiver(n):
    print('Receiver '+str(n)+' launched')
    while True:
        res = message_queue.get()
        print('I go to another greenlet')
        try:
            print('Receiver '+str(n)+'  Task '+str(res)+' launched: %s' % datetime.now())
            #while not res.ready():
            #    gevent.sleep(1)#  switch to another greenlet, otherwise all work will be done by the same co-routine
            print('Receiver '+str(n)+' The job worked :). Returned value: '+str(res.get()))                       
            print('Receiver '+str(n)+'  Task '+str(res)+' finished: %s' % datetime.now())
        except:
            e = sys.exc_info()[0]
            print('The job was launched but the work returned an error: '+str(e))

if __name__ == '__main__':
        
    scheduler = GeventScheduler(
        job_defaults={'misfire_grace_time': 25}
    )
    
    message_queue = Queue()
    
    jobs=[scheduler.add_job(peticion, 'cron', args=(i,), minute='*/1') for i in range(500)]    
    
    print('Press Ctrl+ C to exit')

    try:
        for i in range(10):
            gevent.spawn(receiver,i)
        g=scheduler.start()
        g.join()
    except (KeyboardInterrupt, SystemExit):
        pass
```

Thanks in advance.

**Comment by auvipy** [comment]
there are reports about rpc result backend
