### ISSUE TITLE
how to startup worker  using http remotely

### ISSUE THREAD

**Issue by zyjiang0571** [celery/celery#4318]
I integrate celery into flask and meet a question?
I post a message in the client browser:   http://myhostname.com/startwork, with json data.
In the flask server end, 
    workerInfo = request.json
    system('celery work -A proj.app --config=workerconfig -l info -P eventlet -n worker.%h') 

my question is how to transfer the workerInfo to worker by command-line mode?

**Comment by DomHudson** [comment]
Would something like this work for you?

```
import subprocess

config = {
    "concurrency": 3,
    "prefetch-multiplier": 1
}

subprocess.run(
    ["celery", "worker", "-A", "proj.app"] + ["--{}={}".format(k, v) for k, v in config.items()],
    check=True
)
```

**Comment by georgepsarakis** [comment]
[supervisord](http://supervisord.org/configuration.html#inet-http-server-section-settings) possibly offers the functionality that you are describing. Please use the mailing list or IRC to ask questions.
