### ISSUE TITLE
celery won't redirect stdout when using logbook

### ISSUE THREAD

**Issue by zjqzero** [celery/celery#4325]
When I use logbook streamhandler output to stdout, as following:

`handler = StreamHandler(sys.stdout, format_string=format_str, bubble=True)`

run command: 
    celery -A app.celery_cron.celery worker --concurrency=1 -l debug --logfile /tmp/log.log

All user log won't redirect to /tmp/log.log,  as worker_redirect_stdouts configured as default Enabled

**Comment by georgepsarakis** [comment]
Are you using the Celery task logger in your tasks (see also [this](https://stackoverflow.com/a/19018398/920374) StackOverflow answer)?

**Comment by zjqzero** [comment]
I don't know whether logbook' stdout will be redireted by celery.
but this is my solution:
 
```
@after_setup_task_logger.connect
def init_logger(sender=None, conf=None, logfile=None, **kwargs):
    if logfile:
        RotatingFileHandler(logfile, format_string=format_str, max_size=env.cfg.get('LOG_MAX_SIZE'),
                            backup_count=1, bubble=True).push_application()
    else:
        StreamHandler(sys.stdout, format_string=format_str, bubble=True).push_application()
```
