### ISSUE TITLE
Make `config_from_envvar` accept any config file like in Flask

### ISSUE THREAD

**Issue by lafrech** [celery/celery#4329]
Celery version 4.1.0.

Both Flask and Celery have `config_from_envvar` except those behave a bit differently.

The one in Flask accepts any file given an absolute path. The one in Celery needs a Python module that can be imported. In all the examples I found, the config file is in the application. To separate configuration from application code while using `config_from_envvar`, one needs to fiddle with `PYTHONPATH` to make the config file importable. I'm trying to do that from a systemd unit config file and it is not that simple (for instance, I don't know how to prepend or append to `PYTHONPATH` in there).

My point here is not to ask about my specific use case (I did this [on SO](https://stackoverflow.com/q/46710214/4653485)), but to say that I expected `config_from_envvar` to behave just like in Flask and it doesn't.

It is likely I'm totally missing the common/canonical/recommended way of configuring Celery. From what I saw on the Internet, it looks like for customization of only a few parameters (amq, DB), people just override those parameters one by one in their code from a dedicated env var or a Flask app config parameter. I didn't find any example of `config_from_envvar` used on a file external to the application code.

Anyway, from a "least astonishment" perspective, it would be nice if `config_from_envvar` behaved like in Flask. Is it something that could be feasible?

**Comment by lafrech** [comment]
> Both Flask and Celery have `config_from_envvar`

I was a bit wrong, here. In Flask, it is `config.from_envvar`.

Here's a related discussion about Flask: https://github.com/pallets/flask/issues/2368.

Not a trivial issue. Consider this issue more a question than an enhancement request.

**Comment by lafrech** [comment]
Someone on SO suggested I could let Flask read the config file then use

    celery_app.conf.update(flask_app.config)

which looks quite convenient. However, [Flask will only read uppercase values](http://flask.pocoo.org/docs/0.12/config/#configuring-from-files) from the config file, so this will only work as long as the old uppercase names are maintained.

Is there any plan to deprecate the old uppercase parameters? The comment on the "lowercase settings" commit provides an example of importing Django configuration using uppercase names.

**Comment by thedrow** [comment]
5.0 will not support the uppercase form of the setting names.
