### ISSUE TITLE
Fastest way to send large number of tasks?

### ISSUE THREAD

**Issue by johnarnold** [celery/celery#4331]
Using Celery 4.1, Redis broker+backend.

For some workloads, we may send 100k tasks that complete in 1-2 seconds and have a response/result around 1-100KB.

We have found that when sending all the tasks out, whether in a for loop or using task groups, the tasks take a really long time to get dispatched.  We've traced this down to the fact that the tasks are dispatched serially, and we're eating some WAN latency in some cases sending to a centralized REDIS broker (we have many locations).

We see similar problems trying to .get() the results -- serially.  Because it can take 1sec to dispatch, , and 1sec to get results, serially per task, it can take a really long time to process 100k tasks, even though they execute in parallel on the workers at (potentially) great scale.

Is there any best practice for dispatching many tasks in parallel?  Or retrieving results in parallel?

We are discussing whether it's worth making a multithreading wrapper to delay/async_apply/get  faster.

**Comment by jamesbeedy** [comment]
@johnarnold I used chunks to get around this, keywords *get around*

**Comment by johnarnold** [comment]
@jamesbeedy by chunks, i assume you mean submitting tasks with multiple "items of work" in them, to amoratize the cost of the messaging?

**Comment by jamesbeedy** [comment]
@johnarnold yea

**Comment by linar-jether** [comment]
Several options, all work rather well

1. Use a thread pool to send the tasks in parallel, e.g. 
```python
# Create 1000 tasks
signatures = [async(lambda x, y: x + y, np.random.rand(), np.random.rand()) for _ in range(10000)]

# Create a helper task that will submit the tasks closer to the broker to avoid latency
helper_task = async(lambda tasks: [t.delay() for t in tasks], signatures)

%%time
# Submit the tasks in parallel (thread pool)
from multiprocessing.dummy import Pool as tPool
pool = tPool(100)
async_results = pool.map(lambda x: x.delay(), signatures)
pool.close()
pool.join()
Wall time: 16.5 s

%%time
# Get all task results in a single request using ResultSet
res = celery.result.ResultSet(async_results)
res.get()
Wall time: 856 ms
Out[101]: 
[ 0.7009971539066354,
 1.6091714366064052,
....
 0.9526192535592929,
 1.2688287181345332]
```

2. Use a helper task to  submit the tasks from a node that is closer to the broker (same datacenter), assuming this is possible for you :
```python
# Create 1000 tasks
signatures = [async(lambda x, y: x + y, np.random.rand(), np.random.rand()) for _ in range(10000)]

# Create a helper task that will submit the tasks closer to the broker to avoid latency
helper_task = async(lambda tasks: [t.delay() for t in tasks], signatures)

%%time
# Send the helper task
helper_result = helper_task.delay()
Wall time: 275 ms

%%time
# Get all the AsyncResults objects from the helper task
res = celery.result.ResultSet(helper_result.get())
Wall time: 234 ms

%%time
# Get all task results in a single request using ResultSet
res.get()
Wall time: 864 ms
Out[101]: 
[0.9841198728286353,
 0.91065358147507,
...
 1.1349006758791926,
 0.9334506248484059]
```

**Comment by johnarnold** [comment]
Thanks @linar-jether @jamesbeedy !

**Comment by monstermac77** [comment]
@linar-jether, how might I implement your solution in python 2.7 (sending tasks in parallel)? Is it possible without the async keyword?

**Comment by linar-jether** [comment]
@monstermac77 the `async` in my example is used in python 2.7, it is just a wrapper of ours that creates a celery signature from an arbitrary callable.

**Comment by monstermac77** [comment]
@linar-jether got it, thanks! I ended up using Celery's built-in chunking solution which successfully cut down the time to add tasks to the queue, but I may return to this if I hit the scale where I need more speed-up. 

One downside of using Celery's built-in chunking solution is that tasks within a chunk will not execute in parallel, so you're reducing parallelism in exchange for less task overhead, which might not be acceptable in some applications.

**Comment by SKhakhulin** [comment]
Can you explain where is `async` wrapper now? for 3.6. I need to set about 10k tasks, every time in loop(in the outside script). But tasks are very small(2 http request and 4 multiple) in fact it's the same function with different args.  I use eventlet pool. Also, I don't use chunks solution because it will not execute task in parallel.

**Comment by SKhakhulin** [comment]
@[linar-jether](/linar-jether) up
