### ISSUE TITLE
chord does nothing when the header is an empty list

### ISSUE THREAD

**Issue by xavierhardy** [celery/celery#4333]
## Checklist

- [ x ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected). 
Affected version: 4.1.0

- [ x ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Initiate the Celery configuration, and run the following code.
```py
@celery.task()
def add(a, b):
    return sum(a) + b

print(chord([], add.s(3)).apply_async().get())
```

## Expected behavior

Does not wait, executes the callback task, prints 3.

## Actual behavior

Does nothing, the `get` call is stuck forever. I do not know if it's a bug, or a non-feature, but it should be at least documented. The use case behind this is we generate a list dynamically using Python's list comprehension `[my_task.s(i) for i in range(n)]`, the list is potentially empty.

Another thing is the fact that the response sent to the callback is a list only if there is more than one element in the list is also counter intuitive and should be at best overridable.

http://docs.celeryproject.org/en/latest/userguide/canvas.html#chords

Thanks a lot in advance

**Comment by AlexHill** [comment]
+1 here, I've run into this problem in the same scenario (group generated by a comprehension). There are a few rough edges around chords and fixing this would be a good start.

I agree that this behaviour is "wrong", in the sense that it would be more consistent for the chord to execute if the body is empty. There's precedent in Python in that `all([]) == True`. If someone from the Celery team can confirm that a patch to change this behaviour would be accepted in principle, I would be happy to look into it.

**Comment by xavierhardy** [comment]
You had the problem with group? Which version of Celery was it? With 4.1, group works as I expected, doing nothing with an empty list and consistently returning a list even with zero or one element. However, chain and chord are behaving as described previously.

**Comment by AlexHill** [comment]
Sorry, I mean specifically using a group as a chord header - it's equivalent to passing a list of tasks.
