### ISSUE TITLE
Improving the development process

### ISSUE THREAD

**Issue by vladcalin** [celery/celery#4334]
Hello celery community.

I have a proposition that I believe can improve the development process and allow new contributors to get involved easier in the development of celery:

I propose to have some easy to spin up development process using docker compose or vagrant that will build the development process in one shot without having to configure databases, brokers, the celery app instance, etc.

I am thinking about having a single script that will spin up a ready development with the required dependecies.

Some high-level example of what I am thinking:

```
$ setup_celery_dev python=3.6 os=ubuntu broker=redis backend=cassandra test_project=../weird-bug-example
```
And after running the command, the developer should have a VM with ubuntu, python3.6, celery and all dependencies installed with redis,cassandra extras, and a mounted volume with some source code that can reproduce some bug, and maybe some aliases for starting a worker, starting celerybeat, etc.

Also, a tag for "Easy picklings" (like django has) can allow new contributors to pick easier some issues to resolve as a way to learning to contribute to this project.

What do you think?

**Comment by georgepsarakis** [comment]
I think what you are describing can be achieved quite well by providing a [Docker Compose](https://docs.docker.com/compose/) file.

**Comment by georgepsarakis** [comment]
@vladcalin I added the tag `good first issue`, which is now [suggested](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/) from Github.

**Comment by auvipy** [comment]
there is also an issue to release official docker image and other modern deployment options like kubernete
