### ISSUE TITLE
chord_unlock isn't using the same queue as chord

### ISSUE THREAD

**Issue by k1p0d** [celery/celery#4337]
I've created a tasks_queue and priority_task_queue. in addition to that i've set the tasks_queue to be used as default queue. Now every time i would like a task to be perfrom right away i use priority_queue which is generally empty most of the time. now, the problem araise whenever i'm using chord. i noticed that chords are unable to complete their task because their chord_unlock counterpart always run on the default tasks queue(tasks_queue)

## Steps to reproduce

- Ubnutu 16 server
- celery==4.1.0
- kombu==4.1.0
- boto==2.48.0
- boto3==1.4.7
- botocore==1.7.31
- Using SQS for as broker.

## Expected behavior
I expected the chord_unlock to be performed in the same queue the chord was executed. This causes a major problem for me. Since SQS does not support priority tasks. I'm forced to use two queues to enable the effect of tasks priority. but since chord_unlock will always use the same default queue. priority_tasks using chords, will never be able to finish whenever the default queue is packed.

## Actual behavior
the chord was consumed from priority_task_queue and the chord_unlock got stuck in line on the regular tasks_queue

**Comment by k1p0d** [comment]
So after doing some tests I've realized that the problem resides within my code. I've forgotten to set the queue for one of my chords. and it was not running in priority.

My bad. Celery is awesome. Peace!

**Comment by k1p0d** [comment]
Okay, so apparently, it wasn't my coding error. a chord_unlock will always be running in the default queue instead of the queue its counterpart chord will run. If you are using celery with SQS as a broker, this is somewhat problematic since priority is a non-existent feature and you are forced to use different queue for priority tasks. but if your tasks canvas is using chord, its unlock could be stuck in a pile of tasks in the default queue.

the way I eventually overcome this problem is by using custom router to route chord_unlock to the queue where its group(chord) was sent.

using the following simple code - 
`def route_chord_unlock_to_chord_queue(name, args, kwargs, options, task=None, **kw):
    if name == 'celery.chord_unlock':
        callback_sig = args[1]
        callback_sig.get("options").get('queue')
        return {'queue': callback_sig.get("options").get('queue')}`  


it worked. but i still think the default situation is not what the author meant. I might be wrong. but I leave this up to you guys

**Comment by AlexHill** [comment]
Seems very sensible to me. I've just created a fix in the `unlock_chord_same_queue` branch. Are you able to test this and confirm it solves your problem?

**Comment by MelnykR** [comment]
https://github.com/celery/celery/pull/4448 does not solve the problem completely. 

It solves only the case when `queue` argument is manually passed to body (callback) task.
But it completely ignores automatic routing with `task_routes` parameter.

Steps to reproduce:
`celeryconfig.py`
```
broker_url = "amqp://guest@localhost//"
result_backend = 'db+postgresql://postgres:secretsecret@postgres:5432/postgres'

task_routes = ({
    "myapp.add_list": {"queue": "queue_add"},
    "*": {"queue": "queue_all"},
},)
```

`myapp.py`
```
from celery import Celery

app = Celery('myapp')
app.config_from_object("celeryconfig")


@app.task
def add_list(args):
    return sum(args)

if __name__ == '__main__':
    app.start()
```

`main.py`
```
from myapp import add_list, app
from celery.canvas import chord

app.config_from_object("celeryconfig")
promise = chord([add_list.s([2, 3]), add_list.s([4, 5])])(add_list.s())
print(promise.get())
```

1. Run first worker with `celery -A myapp worker -l debug -Q queue_all` in first terminal window
2. Run second worker with `celery -A myapp worker -l debug -Q queue_add` in second terminal window
3. Run `python3 -m main` in third terminal window

Expected behaviour:
All tasks are executed by the second worker

Actual behaviour:
`celery.chord_unlock` is executed by the first worker

**Comment by thedrow** [comment]
@MelnykR Can you please open a new issue since this one was resolved for the OP?

**Comment by MelnykR** [comment]
@thedrow I was just following contribution guide `3. Make sure your bug hasn’t already been reported.` =] 
And OP did not actually confirm that merged PR solves his issue.
But sure, I can open another issue.
