### ISSUE TITLE
The "retry_backoff" task argument is not working in 4.1.0 version

### ISSUE THREAD

**Issue by JoeZ99** [celery/celery#4341]
## Checklist

- [ x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```bash
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:cache+memcached://memcached:11211/
```
- [ ] I have verified that the issue exists against the `master` branch of Celery.
4.1
## Steps to reproduce
create a simple task
from requests.exceptions import RequestException

```python
@app.task(autoretry_for=(RequestException,), retry_backoff=True)
def x():
    if x.request.retries < 3:
        raise RequestException
    return "F#@! SUCCESS!!"
```

## Expected behavior

exponential delayed retries. 1s, 2s, 4s

```console
celery_1           | [2017-10-25 17:02:31,150: INFO/MainProcess] Received task: helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2]  ETA:[2017-10-25 17:05:31.069687+00:00] 
celery_1           | [2017-10-25 17:02:31,152: INFO/PoolWorker-4] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] retry: Retry in 1s: RequestException()
celery_1           | [2017-10-25 17:02:32,372: INFO/PoolWorker-5] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] retry: Retry in 2s: RequestException()
celery_1           | [2017-10-25 17:02:34,374: INFO/MainProcess] Received task: helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2]  ETA:[2017-10-25 17:08:31.346456+00:00] 
celery_1           | [2017-10-25 17:08:31,656: INFO/PoolWorker-6] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] succeeded in 0.00370980799198s: 'F SUCCESS'
```

## Actual behavior
retries every 180 seconds
```console
celery_1           | [2017-10-25 17:02:31,150: INFO/MainProcess] Received task: helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2]  ETA:[2017-10-25 17:05:31.069687+00:00] 
celery_1           | [2017-10-25 17:02:31,152: INFO/PoolWorker-4] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] retry: Retry in 180s: RequestException()
celery_1           | [2017-10-25 17:05:31,372: INFO/PoolWorker-5] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] retry: Retry in 180s: RequestException()
celery_1           | [2017-10-25 17:05:31,374: INFO/MainProcess] Received task: helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2]  ETA:[2017-10-25 17:08:31.346456+00:00] 
celery_1           | [2017-10-25 17:08:31,656: INFO/PoolWorker-6] Task helpck.custom_results.tasks.x[58036219-9bdd-4017-a36c-3c65fc1fa3b2] succeeded in 0.00370980799198s: 'FG SUCCESS'
```

**Comment by JoeZ99** [comment]
if you check

https://github.com/celery/celery/blob/v4.1.0/celery/app/base.py#L438

you will see there's no code related to the backoff alorithm. there is no `get_exponential_backoff`

but in 

http://docs.celeryproject.org/en/latest/_modules/celery/app/base.html

(which claims it's for 4.1)

there is a `get_exponential_backoff` function defined which takes into account all those arguments.

looks like the backoff_retry feature is from versions newer than 4.1.0???

**Comment by sanjioh** [comment]
Confirmed here with Celery 4.1

**Comment by Fingel** [comment]
I'm also confused by this. The documentation here says it's "new in 4.1": 
http://docs.celeryproject.org/en/latest/userguide/tasks.html#automatic-retry-for-known-exceptions

But I can't seem to get it to work. I thought I must have been making some mistake, then I found this issue.

**Comment by ChrisCalculus** [comment]
Running into this issue as well (running 4.1).

**Comment by mmcardle** [comment]
Also seeing this issue (4.1)

**Comment by shihanwan** [comment]
Confirmed on 4.1.0

**Comment by auvipy** [comment]
does it exist in master too?

**Comment by georgepsarakis** [comment]
@auvipy the [PR](https://github.com/celery/celery/pull/4101) with this feature was merged after 4.1.0 was released.

**Comment by thedrow** [comment]
Should we close then?

**Comment by thedrow** [comment]
Please follow #4387.
We just need the release notes and resolve another issue.

**Comment by WoLfulus** [comment]
I thought I was doing something wrong :(

**Comment by Ashlett** [comment]
This is not cool... people are wasting their time trying to figure out why this feature is not working, only to find out it is not actually implemented in the current version. Can you please remove it from the docs until it's released?

**Comment by georgepsarakis** [comment]
@Ashlett sorry for facing issues with this, the next version (4.2.0) will be released soon. See #4387 for details.
