### ISSUE TITLE
How to dynamicly distribute one task to specified worker

### ISSUE THREAD

**Issue by zyjiang0571** [celery/celery#4343]
I have a lot of tasks that need load some 3d models to process. The most time of task is spend on the model loading. And, some tasks often load the same 3d model. So, When one task(named A) is being consumed by worker, I hope the worker is the one have just consumed the task (named B) which need load the same  3d model. By this way, when consuming task A, we can avoid loading the same 3d model to save time.

So, my question is how to dynamicly distribute one task to specified worker(the right one)?

**Comment by auvipy** [comment]
it's better to post how to questions to mailing list to get better answers. we use issue traker for bug report/features request.
