### ISSUE TITLE
celery gets Australia/Melbourne timezone wrong

### ISSUE THREAD

**Issue by brianmay** [celery/celery#4346]
celery 4.1.0

I correctly configured the timezone:

```
In [6]: karaage.celery_app.conf.timezone
Out[6]: 'Australia/Melbourne'
```

and I get:

```
In [8]: karaage.celery_app.now()
Out[8]: datetime.datetime(2017, 10, 27, 3, 11, 56, 772565, tzinfo=<DstTzInfo 'Australia/Melbourne' LMT+9:40:00 STD>)
```

I was expecting something like:

```
$ date
Fri 27 Oct 14:12:21 AEDT 2017
$ date --utc
Fri 27 Oct 03:12:27 UTC 2017
```

i.e. the timezone difference from UTC is +11 hours here, not 9 hours 40 minutes. I don't know where celery is getting this stupid offset from.

I suspect this might be why hours matching in crontab schedules is not working.

**Comment by brianmay** [comment]
Actually I have no idea what this LMT is referencing. I was assuming this is a UTC reference.

**Comment by brianmay** [comment]
Actually my problem might be more complicated. If I set hour='*' it doesn't work. If I unset ``CELERY_TIMEZONE`` then it does work.

**Comment by georgepsarakis** [comment]
@brianmay did you try with the `master` branch? It contains some fixes for timezones.

**Comment by brianmay** [comment]
No, I didn't try this. At least I not that I remember now :-). Will try ASAP.

**Comment by georgepsarakis** [comment]
@brianmay there is an issue with non-UTC timezones in 4.1.0. It must be fixed in master, would you like to check that first?

**Comment by brianmay** [comment]
Yes, it does seem a lot better now.

**Comment by jm66** [comment]
@georgepsarakis are you releasing a new version with this fix soon?

**Comment by auvipy** [comment]
yes 4.2 release is due in january 2018
