### ISSUE TITLE
Celery with django (with SQS as broker) stops silently after starting

### ISSUE THREAD

**Issue by krdeepak** [celery/celery#4348]
## Checklist
celery - 4.1.0
kombu - 4.1.0
boto3 - 1.4.7
django - 1.10.5

## Steps to reproduce
Run worker using the following (with broker = 'sqs://')
celery -A <django_project> worker --loglevel=info

## Expected behavior
Worker starts

## Actual behavior
Worker dies silently

[config]
.> app:         bid:0x110320eb8
.> transport:   sqs://localhost//
.> results:     redis://localhost:6379/0
.> concurrency: 4 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery

-------

```
[2017-10-27 14:35:10,241: INFO/MainProcess] Found credentials in shared credentials file: ~/.aws/credentials
[2017-10-27 14:35:10,287: INFO/MainProcess] Starting new HTTPS connection (1): ap-southeast-1.queue.amazonaws.com
[2017-10-27 14:35:10,679: INFO/MainProcess] Connected to sqs://localhost//
[2017-10-27 14:35:10,709: INFO/MainProcess] Found credentials in shared credentials file: ~/.aws/credentials
[2017-10-27 14:35:10,747: INFO/MainProcess] Starting new HTTPS connection (1): ap-southeast-1.queue.amazonaws.com
```

**Comment by ElAutoestopista** [comment]
Hi,
I'm experiencing this issue as well. Similar configuration, same versions.

Regards

**Comment by ElAutoestopista** [comment]
Hi @krdeepak,

Further investigation drive me to see that I had incomplete dependencies for SQS. You will need to install OpenSSL Devel package for your distro, and also pycurl, crypto and boto modules.
This made my setup run like a charm!!

Regards.

**Comment by krdeepak** [comment]
Thanks a lot @ElAutoestopista , it worked. How did you figure it out? Is there a place where celery logs are saved?

**Comment by ElAutoestopista** [comment]
Not the logs. After hours or reading tutorials and articles about setting up Celery for SQS, I've found some of them installed dependencies not mentioned in the Celery docs. Trying all of them and testing lend me to the required depencencies.

Glad to see It helped you!

**Comment by gavihs** [comment]
@SergioFernandezCordero can you list all the dependencies

I have installed OpenSSL 1.1.0g, pycurl, boto & pycrypto, still does not work
