### ISSUE TITLE
Command not found `celery`

### ISSUE THREAD

**Issue by reachtoakhtar** [celery/celery#4351]
## Checklist

Upon running `python manage.py celery worker` gives me Command not found `celery`. I have installed celery 4.1 and using it with a Django project.

**Comment by vladcalin** [comment]
You are using the wrong command to start the celery worker: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#starting-the-worker-process

The worker process should be started as a regular celery worker ``celery -A proj worker -l info``

**Comment by georgepsarakis** [comment]
I think this is answered, so I am closing.

**Comment by wo1973727272** [comment]
I can not understand
