### ISSUE TITLE
Celery ignores BROKER_URL vhost

### ISSUE THREAD

**Issue by chrisspen** [celery/celery#4359]
## Steps to reproduce
1. Create an arbitrary Celery task.
2. Create a project with a BROKER_URL pointing to an RabbitMQ vhost, like 

    amqp://guest:**@127.0.0.1:5672/myapp

3. Start a Celery worker with this BROKER_URL like:

    celery worker -A myapp -l info

4. Launch the Celery task via:

    manage.py shell
    >>> from myapp.tasks import test_task; test_task.delay()

5. Task is never executed.
6. Kill Celery worker and change BROKER_URL to use the default "/" vhost, like:

    amqp://guest:**@127.0.0.1:5672//

7. Re-launch your Celery worker.
8. Notice that the previous task is immediately executed, implying the first call to `test_task.delay()` did not send it to the correct BROKER_URL, and instead sent it to one with the vhost removed.

## Expected behavior

Tasks should respect the vhost section in the BROKER_URL.

## Actual behavior

Tasks are seemingly hard-coded to always use the default vhost, causing them to be executed by the wrong workers in a multi-vhost environment.

This was tested in Celery 4.1.0 with Django 1.11.

**Comment by kedare** [comment]
I have the same Celery version but with Django 1.10 and the RabbitMQ vhost management is working fine for me.

**Comment by chrisspen** [comment]
I figured out the problem. For some reason, my `Celery()` instance was not being set to the `current_app` value stored in Celery's internal state. To every use of the `@task` decorator was using the default instance, which had blank settings. I don't know why this problem occurs, since I followed the steps as outlined in the [docs](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html), so these are either incomplete, or there's a bug in Celery.

To fix this, I had to manually call the internal method `_set_current_app()` and pass it my app. This is hacky, and likely to break in the future when this internal method is removed, but after digging around in Celery's code, this is the only solution I could find.

For reference, my functioning `celery.py` looks like:

    from __future__ import absolute_import
    import os
    import sys

    from celery import Celery
    from celery._state import _set_current_app
    import django

    app = Celery('myproject')
    app.config_from_object('django.conf:settings', namespace='CELERY')
    _set_current_app(app)

    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings.settings')
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../myproject')))
    django.setup()
    from django.conf import settings
    app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

**Comment by NogerbekNurzhan** [comment]
@chrisspen hello! I tried to use your code but it raise error when I want to runserver.

**Error:**
`AttributeError: 'Settings' object has no attribute 'ACCOUNT_PASSWORD_STRIP'`

In the same time celery task which inside custom app works.

If I remove `django.setup()` from code runserver command works but celery task don't. Do you have any ideas why it happens?

**Error:**
```
Received unregistered task of type 'custom_app.tasks.amount_counting'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"chain": null, "chord": null, "callbacks": null, "errbacks": null}]' (77b)
Traceback (most recent call last):
  File "/home/ubuntu/enjoy_jumping/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 557, in on_task_received
    strategy = strategies[type_]
KeyError: 'custom_app.tasks.amount_counting'
```
