### ISSUE TITLE
ModuleNotFoundError: No module named 'demjson'

### ISSUE THREAD

**Issue by willwinworld** [celery/celery#4360]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Actual behavior
I am using celery 3.1.25 on windows, type command celery worker -A tasks.workers -l info, but celery can't deal with demjson module,

**Comment by georgepsarakis** [comment]
Can you please provide a stack trace?

**Comment by auvipy** [comment]
We decided to no longer prodice support for 3.x branch
