### ISSUE TITLE
Documentation for celery with SQS as message broker should have pycurl and crypto mentioned as dependencies.

### ISSUE THREAD

**Issue by krdeepak** [celery/celery#4362]
If pycurl and crypto modules are not installed, worker dies just after starting without any debug information. This information should be included in the documentation.

**Comment by georgepsarakis** [comment]
Have you installed the extension requirements for SQS support?

```
$ pip install celery[sqs]
```

**Comment by ElAutoestopista** [comment]
@georgepsarakis that's ok, But the documentation doesn't says anything about this command:

http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html

As, for instance, does for Redis:

http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html

The docs mention installing boto, but it's not sufficient. In fact, boto, boto3, pycurl and crypto are required. I think the docs should be updated with the command you specified above,

**Comment by georgepsarakis** [comment]
@ElAutoestopista you are right, the `Installation` section must be updated. Would you perhaps like to open a Pull Request for that?

**Comment by ElAutoestopista** [comment]
Sure, I'll check it!

**Comment by ElAutoestopista** [comment]
@georgepsarakis https://github.com/celery/celery/pull/4382

**Comment by thedrow** [comment]
Since this issue is fixed in #4382 I'm going to close this issue.
