### ISSUE TITLE
Memory leak when retry

### ISSUE THREAD

**Issue by faith0811** [celery/celery#4371]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

I can reproduce the issue on linux(inside a docker container) or on my own mac.
The celery report goes like this:

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.6.0
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: 'amqp://guest:********@localhost:5672//'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Running a simple script with: 

```python
from celery import Celery

from some_config import CELERY_BROKER

app = Celery('test_celery', broker='amqp://{user}:{password}@{host}:{port}/{vhost}'.format(**CELERY_BROKER))


class FunkyException(Exception):
    def __init__(self, desc=None, extra=None):
        super().__init__(desc)
        self.extra = extra


@app.task(bind=True)
def eat_memory(self):
    try:
        raise FunkyException('test', extra=bytearray(512000000))
    except Exception as exc:
        raise self.retry(exc=exc, countdown=5)


if __name__ == '__main__':
    eat_memory.delay()
```

Start celery with gevent:

```bash
celery worker -A test_celery:app -P gevent
```

Then run the script:

```bash
python test_celery.py
```

## Expected behavior

I did't set the ``max_retries`` parameter, so the task should be executed after 15 seconds(3 times), and memory should be released after that.

## Actual behavior

The memory leaks, and did not release. It might be released after like 5-10 minutes, and sometimes never released.

## Actual behavior in my production

The celery worker process leaks slowly. I have to restart the worker every hour.

4.0.x and 4.1.0 are tested with this issue.

**Comment by faith0811** [comment]
And when memory leak happens, if I go inspect the worker, all seems fine.
```bash
$ celery inspect -A test_celery:app active
-> celery@xxxdeMacBook-Pro.local: OK
    - empty -
```

**Comment by Maples7** [comment]
It seems I got the same problem, the memory used by Celery worker goes upper and upper.

**Comment by georgepsarakis** [comment]
Memory is not being optimally released back to the OS for CPython processes, so memory consumption may be increasing, even if you don't have memory leaks in your code. The only solution is the prefork pool and the [--max-tasks-per-child](http://docs.celeryproject.org/en/latest/userguide/workers.html#max-tasks-per-child-setting) setting.

**Comment by Maples7** [comment]
@georgepsarakis Thanks for your answer, but if I choose Eventlet pool, are there any ways to release memory?

**Comment by Sobes76rus** [comment]
+1 ^^

**Comment by xbogdan** [comment]
Did anybody find a solution for this ? For the gevent pool ?
