### ISSUE TITLE
When LOGGING key exists in setting.py, celeryd can't restart

### ISSUE THREAD

**Issue by greenfrog82** [celery/celery#4372]
Hi, I'm user celery 3.x
I'm using celery as daemon mode with Django application.
I added LOGGING key into settings.py of Django. 
The owner of log file path which is LOGGING key is apache. 
And then I restart celeryd as below command.

```
$ /etc/init.d/celeryd restart
```
But I saw the below message.

![image](https://user-images.githubusercontent.com/22334078/32540683-c5125d12-c4b0-11e7-86ce-da600c42ba77.png)

The reason of the above image is because owner of log file path. The owner of log file path is apache and celery process can't access the log file.  First, I resolved this problem how I changed access permission of log file to 666 using chown. But this is not best practice which manage log file.

Does celery using LOGGING key from settings.py?
If celery use LOGGING key, how does celery use LOGGING key? and what is LOGGING key for and How to prevent to use LOGGING key in celery?

**Comment by greenfrog82** [comment]
Hi all ~
I've cloned celery source codes and tried to find suspected codes last week because I wonder the reason why above error.
As a result, I've found the methods which are celery.fixups.django.DjangoFixup.on_import_modules and celery.fixups.django.DjangoWorkerFixup.django_setup.
They are called when celeryd is restarted. 
Especially we have to attention to celery.fixups.django.DjangoWorkerFixup.django_setup method. It call the django.setup method. 
Please reference the below link aboout django.setup method.
[django.setup](https://docs.djangoproject.com/en/1.11/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage)
When django.setup method is called, Django load settings.py, load logging handler which are LOGGING in setting.p and access log file path finally.
This is the reason!!

**Comment by auvipy** [comment]
use new version and report again.
