### ISSUE TITLE
Tasks should be queued on worker getting lost

### ISSUE THREAD

**Issue by nans15jain** [celery/celery#4374]
## Checklist
I am using django-celery 3.2 and celery 3.1.25.
I have added below settings -
CELERY_TASK_ACKS_LATE = True                 
task_reject_on_worker_lost = True
The application results in below error and fails to load if I use celery 4.x with django-celery 3.2
ImportError: No module named vine.five
## Steps to reproduce
Trigger some tasks, and get their pids from logs.
I kill a worker(pid) at random using kill command.
## Expected behavior
The task should come back to the queue and picked up by same or other worker.
## Actual behavior
The task is getting lost.

**Comment by auvipy** [comment]
kindly use the lastest releases and follow the docs, and post on mailing list for help.
