### ISSUE TITLE
Closing down and restarting event monitoring is buggy

### ISSUE THREAD

**Issue by shazoom** [celery/celery#4376]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery 

I installed in a virtualenv using on PiPy (but put celery last to make sure it didn't automatically fulfill dependencies):

     $ pip install https://github.com/celery/billiard/zipball/master#egg=billiard
     $ pip install https://github.com/celery/py-amqp/zipball/master#egg=amqp
     $ pip install https://github.com/celery/kombu/zipball/master#egg=kombu
     $ pip install https://github.com/celery/vine/zipball/master#egg=vine
     $ pip install https://github.com/celery/celery/zipball/master#egg=celery

## Steps to reproduce
Run the attached file with interactive mode in the Python shell (-i) and run the function test(). 

### Further information
Stopping and starting events in this way almost works.  Run `othertest()`, from cel_events_test.py, 3 times and it works 2 out of 3 times. **The second run will hang (^c it and the third run will work) when the job is submitted to the queue** (this is the problem). I added some hacky sleeps to allow time for the jobs to execute but it should demonstrate the problem.

[cel_events_test.py.zip](https://github.com/celery/celery/files/1456371/cel_events_test.py.zip)

        from time import sleep
        from multiprocessing import Process, Manager
        from celery import Celery

        app = Celery(backend='rpc://', broker='amqp://')

        @app.task(name='primesOf')
        def primesOf(x):
            multiples = []
            results = []
            for i in range(2, x + 1):
                if i not in multiples:
                    results.append(i)
                    for j in range(i * i, x + 1, i):
                        multiples.append(j)
            return results

        class Monitor():

            def __init__(self, app, event_type):
                self.app = app
                self.event_type = event_type

            def __enter__(self):
                print('setting up monitor %s' % self.event_type)
                self.monitor, self.changes = self.new_monitor(self.app, self.event_type)
                print('done with %s' % self.event_type)

            def __exit__(self, *args):
                print('terminating monitor: %s' % self.event_type)
                self.monitor.terminate()

            @staticmethod
            def mkMon(app, shared_list, event_type):
                state = app.events.State()

                def announce(event):
                    state.event(event)
                    job = state.tasks.get(event['uuid'])
                    print('%s: %s[%s] %s' % (event_type, job.name, job.uuid, job.info(),))
                    shared_list.append(job.uuid)

                with app.connection() as conn:
                    recv_succeeded = app.events.Receiver(conn, handlers={
                        event_type: announce,
                        '*': state.event,
                    })
                    recv_succeeded.capture(limit=None, timeout=None, wakeup=True)

            @classmethod
            def new_monitor(cls, app, event_type):
                manager = Manager()
                shared_list = manager.list()
                mon_process = Process(target=cls.mkMon, args=(app, shared_list, event_type))
                mon_process.start()
                return mon_process, shared_list

        def test():
            'This one shows the broken behaviour'

            with Monitor(app, 'task-succeeded') as smon, Monitor(app, 'task-failed') as fmon, Monitor(app, 'task-started') as tmon, Monitor(app, 'task-received') as rmon:
                print('waiting for monitors to setup')
                sleep(3)
                print('submitting jobs')
                jobs = [primesOf.apply_async((x,)) for x in range(9)]
                sleep(3)

            print('\n\nnow test submitting a job')
            j = primesOf.delay(10)
            sleep(3)
            print(j.result)

            print('\n\nSetup event monitors again')
            with Monitor(app, 'task-succeeded') as smon, Monitor(app, 'task-failed') as fmon, Monitor(app, 'task-started') as tmon, Monitor(app, 'task-received') as rmon:
                print('submitting a job again (this call to delay won\'t return)')
                j = primesOf.delay(10)
                sleep(3)
                print(j.result)

        def otherTest():
            'Run this 3 times. The second run will hang; ^c it and the third run will work.'

            with Monitor(app, 'task-succeeded') as smon, Monitor(app, 'task-failed') as fmon, Monitor(app, 'task-started') as tmon, Monitor(app, 'task-received') as rmon:
                print('waiting for monitors to setup')
                sleep(3)
                print('submitting jobs')
                jobs = [primesOf.apply_async((x,)) for x in range(9)]
                sleep(3)

## Expected behavior
note: this refers to the `test()` function in the linked file: cel_events_test.py)
1. create event monitors running in separate `multiprocessing.Process` objects and wrapped in a context manager
2. submit several jobs to an event queue
3. the events will be printed to the shell
3. exit the `with` block and the context managers will `terminate()` the processes monitoring celery events
4. submit a job to the queue
5. print the result
5. create a new set of event monitors as before
6. submit another job to the queue
7. the events will be printed to the shell
7. print the result

## Actual behavior 
note: this refers to the `test()` function in the linked file: cel_events_test.py)
1. create event monitors running in separate `multiprocessing.Process` objects and wrapped in a context manager
2. submit several jobs to an event queue
3. the events will be printed to the shell
3. exit the `with` block and the context managers will `terminate()` the processes monitoring celery events
4. submit a job to the queue
5. print the result
5. create a new set of event monitors as before
6. submit another job to the queue
6. nothing (it hangs)

## Report Output
    $celery -A cel_events_test report

    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2 billiard:3.5.0.3 py-amqp:2.2.2
    platform -> system:Linux arch:64bit, ELF imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:amqp results:rpc:///

    result_backend: 'rpc:///'
    broker_url: 'amqp://guest:********@localhost:5672//'

**Comment by auvipy** [comment]
can you try the master again?

**Comment by shazoom** [comment]
Hi, I followed the same procedure as I outlined above (creating a new virtualenv and pip installing celery) but my test script is still hanging.

**Comment by shazoom** [comment]
I just retried with a new virtualenv and it seems the test now works as expected 😊 

```
(celery) shannon@shannon-virtual-machine:/tmp/celery$ python -i cel_event_test.py 
>>> test()
setting up monitor task-succeeded
done with task-succeeded
setting up monitor task-failed
done with task-failed
setting up monitor task-started
done with task-started
setting up monitor task-received
done with task-received
waiting for monitors to setup
submitting jobs
terminating monitor: task-received
terminating monitor: task-started
terminating monitor: task-failed
terminating monitor: task-succeeded


now test submitting a job
[2, 3, 5, 7]


Setup event monitors again
setting up monitor task-succeeded
done with task-succeeded
setting up monitor task-failed
done with task-failed
setting up monitor task-started
done with task-started
setting up monitor task-received
done with task-received
submitting a job again (this call to delay won't return)
[2, 3, 5, 7]
terminating monitor: task-received
terminating monitor: task-started
terminating monitor: task-failed
terminating monitor: task-succeeded
>>> 
```
