### ISSUE TITLE
TASK_PUBLISH_RETRY_POLICY  settings only works the first time

### ISSUE THREAD

**Issue by wilson-santos-pf** [celery/celery#4383]
## Checklist

- [x] Version affected: 4.1.0
- [x] Broker is RabbitMQ: "3.3.5"
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1) On `settings.py` of the Django project append this settings:

```python
CELERY_TASK_PUBLISH_RETRY = True
CELERY_TASK_PUBLISH_RETRY_POLICY = {
    "max_retries": 3,
    "interval_start": 0,
    "interval_step": 0.2,
    "interval_max": 0.2
}
```
2) Stop the RabbitMQ service

3) Call the `task.apply_sync`. This should raise an `OperationalError`.

4) Call `task.apply_sync` again. Now it hangs, without any exception raised.

## Expected behavior
`task.apply_sync` should time out according to the specified setting.

## Actual behavior
The second time `task.apply_sync` is called, it just hangs without timing out.

**Comment by fahyik** [comment]
Hi!

I am having the exact same problem.
Running with Django 1.10 and RabbitMQ 3.7.2 as Broker.

If I close the broker connection, nothing happens and the request to Django is stuck on an infinite loop without timing out.

@wilson-santos-pf did you manage to find a work around for this?
I am having difficulty handling the failure to publish to RabbitMQ.

**Comment by paultiplady** [comment]
I seem to be hitting this issue on Celery 4.0.0 and 4.0.1 as well. I've just retried with 4.1.0 and the code path is the same.

Step-debugging through the code, my stack looks like this:

```
retry_over_time
ensure_connection
default_channel
...
publish
send_task_message
send_task
```

At `publish`, I have `retry_policy={'interval_step': 0.2, 'interval_max': 0.2, 'interval_start': 0, 'max_retries': 3}`. When we drop into `ensure_connection` under `default_channel`, I have `max_retries=None`. `default_channel` is just calling `ensure_connection` with the default values, which results in `retry_over_time` being called with infinite retries, and hanging. 

In my case the error is that there is no broker, as I'm running UTs.

Patching `ensure_connection`'s default value for `max_retries` thusly has fixed this issue for me:

```
    def ensure_connection(self, errback=None, max_retries=3,
                          interval_start=2, interval_step=2, interval_max=30,
                          callback=None, reraise_as_library_errors=True):
```

This looks like it would block my API's request handling process, causing a total outage, if my AMQP broker went down - so on the face of it this looks like a critical bug.

**Comment by paultiplady** [comment]
This seems to be a bug in Kombu: https://github.com/celery/kombu/issues/735

**Comment by fahyik** [comment]
@paultiplady thanks for your reply, yea i read it on the other thread as well.
I am using kombu 4.0.2 with celery 4.1.0 as a temporary fix ;)

**Comment by paultiplady** [comment]
Ah, that's helpful, thanks -- I didn't spot that my Kombu version was stuck at 4.1.0, even though I was pinning Celery to 4.0.2.

**Comment by paultiplady** [comment]
Not sure what the project's bug announcement policy is, but it seems like it would be prudent to update the Celery requirements to blacklist the broken `4.1.0` kombu version? Any user on `celery>=4.0.0,<=5.0.0` is going to be affected by this bug, since Celery doesn't pin the Kombu dep tightly. This bug is obscure enough that most users won't notice it, until it causes an outage.

**Comment by auvipy** [comment]
fixed by https://github.com/celery/kombu/pull/769

**Comment by auvipy** [comment]
olz try master or wait for 4.2 release
