### ISSUE TITLE
beaats interval tasks only getting run once

### ISSUE THREAD

**Issue by brianmay** [celery/celery#4384]
## Checklist

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.2
            billiard:3.5.0.3 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

$ celery -A myrocc.base report | grep CELERY
CELERY_BROKER_URL: 'redis://localhost:6379/0'
CELERY_TIME_ZONE: 'Australia/Melbourne'
```

This is the latest master of celery.

## Steps to reproduce

Create interval task using django-celery-beat.

Now that when starting beat, it detects the task correctly and runs it:

```
[2017-11-14 09:07:29,374: DEBUG/MainProcess] Setting default socket timeout to 30
[2017-11-14 09:07:29,375: INFO/MainProcess] beat: Starting...
[2017-11-14 09:07:29,376: DEBUG/MainProcess] DatabaseScheduler: initial read
[2017-11-14 09:07:29,376: INFO/MainProcess] Writing entries...
[2017-11-14 09:07:29,381: DEBUG/MainProcess] DatabaseScheduler: Fetching database schedule
[2017-11-14 09:07:29,436: DEBUG/MainProcess] Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4 * * * (m/h/d/dM/MY)>>
<ModelEntry: Test myrocc.inventory.tasks.copy_from_cumulocity_task(*[], **{}) <freq: 2.00 minutes>>
[2017-11-14 09:07:29,873: DEBUG/MainProcess] beat: Ticking with max interval->5.00 seconds
[2017-11-14 09:07:29,885: INFO/MainProcess] Scheduler: Sending due task Test (myrocc.inventory.tasks.copy_from_cumulocity_task)
[2017-11-14 09:07:29,916: DEBUG/MainProcess] beat: Synchronizing schedule...
[2017-11-14 09:07:29,916: INFO/MainProcess] Writing entries...
[2017-11-14 09:07:29,921: DEBUG/MainProcess] myrocc.inventory.tasks.copy_from_cumulocity_task sent. id->23a91178-108a-4230-a679-58c0bb5960b0
```

## Expected behaviour

The test task should run every two minutes.

## Actual behaviour

The test task only runs once.

**Comment by asadlab** [comment]
I am having same issue. The beat is sending the task in correct interval. But the worker is receiving/servicing only the first time and then does not receive/service the task.

**Comment by brianmay** [comment]
@asadlab I am not seeing that; for me beat is not even sending the task.

**Comment by brianmay** [comment]
This ticket is a followup from #3958.

**Comment by asadlab** [comment]
@brianmay I am not using django-celery. Instead I am using just celery with rabbitmq.

**Comment by brianmay** [comment]
@asadlab I wasn't using django-celery either. I was using django-celery-beat however.

**Comment by asadlab** [comment]
@brianmay , here is a snippet of code that I am using, maybe it will help.

from celery import Celery
from celery.schedules import crontab

celeryTasks = Celery()
celeryTasks.conf.timezone = 'UTC'

@celeryTasks.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    # First Scheduled Event on ScheduledEvent entity
    # fire one every 2 minutes
    newSchedule = crontab(
        minute='*/2',
        hour='*',
        month_of_year='*',
        day_of_month='*',
        day_of_week='*',
    )
    sender.add_periodic_task(newSchedule, firstScheduledEvent.s(), name='firstScheduledEvent', kwargs={'moduleName': 'FirstScheduledEvent',


And then if you want to check if the cron schedule is recorded in celerybeat-schedule, you can try following piece of code to check actual shelve entry.
import shelve
s = shelve.open("<your path to celerybeat-schedule>")
print s

**Comment by thegasta** [comment]
I've nearly the same problem.
Tasks with crontab schedule are not sent, interval scheduled tasks are working instead.

**Comment by kyungSong** [comment]
I know this is a long shot, but try checking if your django server time zone and celery worker time zone matches up. I had the same problem (periodic task, task runs when I start it from the admin page, but doesn't run again), and syncing time zones is what solved it for me.

**Comment by brianmay** [comment]
@kyungSong Interesting theory. Unfortunately, just set both to Australia/Melbourne, and still appear to have the same problem. Then I tried UTC, and that seemed to work. Will retest.

**Comment by brianmay** [comment]
Yes, confirmed. UTC works, Australia/Melbourne doesn't.

**Comment by brianmay** [comment]
Appears to be timezone confusion occurring still. I expect is_due to return 2 minutes, but it returns 11 hours 2 minutes, where 11 hours happens to correspond with the timezone offset from UTC.

**Comment by brianmay** [comment]
Something looks wrong with the START time, it is in the future:

```
[2017-11-21 14:07:26,255: WARNING/MainProcess] rem: NOW:datetime.datetime(2017, 11, 21, 14, 7, 26, 255264, tzinfo=<DstTzInfo 'Australia/Melbourne' AEDT+11:00:00 DST>) START:datetime.datetime(2017, 11, 22, 1, 6, 21, 34513, tzinfo=<DstTzInfo 'Australia/Melbourne' AEDT+11:00:00 DST>) ENDS_IN:datetime.timedelta(0, 120) END_DATE:2017-11-22 01:08:21.034513+11:00 REM:11:00:54.779249
```

**Comment by brianmay** [comment]
Oh, looks like ``last_run_at`` is suppose to be UTC, but after the first run, it becomes local time instead...

**Comment by brianmay** [comment]
I suspect this is the problem:

```
    def _when(self, entry, next_time_to_run, mktime=time.mktime):               
        adjust = self.adjust                                                    
                                                                                
        return (mktime(entry.default_now().timetuple()) +                       
                (adjust(next_time_to_run) or 0))                                
```

I think the problem is that we get the timezone aware local time, drop the timezone, and then use it as a UTC time.

**Comment by brianmay** [comment]
(Deleted last comment, it appeared to be incorrect)

**Comment by brianmay** [comment]
Oh, never mind, just found https://github.com/celery/django-celery-beat/pull/68 which was merged into master on django-celery-beat. I was using master celery but not master on that project. I believe this was my problem. Closing.
