### ISSUE TITLE
redis connection issues on 4.x

### ISSUE THREAD

**Issue by jheld** [celery/celery#4386]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
   celery 4.0.2
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

This is not easy to reproduce. But, it does happen from time to time and it has blown up our usage of `beat` and the workers consuming tasks correctly.

## Expected behavior

We don't want to see the error continue to happen -- the workers and producers should be able to reconnect to the broker correctly.

Is there anything we can do to help? Anywhere to look?

## Actual behavior

They go into a retry loop and never come out. Other OS system issue may occur throughout this time.

https://github.com/celery/celery/issues/2442

**Comment by auvipy** [comment]
whats your celery setup? does using latest releases solve or change the trackback?

**Comment by auvipy** [comment]
try 4.1/4.2[upcoming release]
