### ISSUE TITLE
Celery worker and beat as daemon : not working ?

### ISSUE THREAD

**Issue by jy95** [celery/celery#4398]
## Version

- Celery 4.1.0
- django-celery-beat==1.1.0
- python 2.7
- rabbitmq 3.6.14
- Django 1.11.3

## Steps to reproduce
**settings.py** (only the part related to celery)
```py
from __future__ import absolute_import, unicode_literals
# ^^^ The above is required if you want to import from the celery
# library.  If you don't have this then `from celery.schedules import`
# becomes `proj.celery.schedules` in Python 2.x since it allows
# for relative imports by default.
# Celery settings
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
# http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings
CELERY_beat_scheduler = 'django_celery_beat.schedulers:DatabaseScheduler'  # use django_celery_beat instead
CELERY_broker_url = 'amqp://oscar:oscar@localhost:5672/oscarRabbit'
```

**celery.py** : 
```py
from __future__ import absolute_import, unicode_literals
import os
from celery import Celery

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'oscar.settings')

app = Celery('oscar')

# Using a string here means the worker doesn't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings', namespace='CELERY')

# Load task modules from all registered Django app configs.
app.autodiscover_tasks()
```

**__init__.py**:
```py
from __future__ import absolute_import, unicode_literals

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app

__all__ = ['celery_app']
```

**/etc/default/celeryd**
```
# Names of nodes to start
#   most people will only start one node:
CELERYD_NODES="worker1"
#   but you can also start multiple and configure settings
#   for each in CELERYD_OPTS
#CELERYD_NODES="worker1 worker2 worker3"
#   alternatively, you can specify the number of nodes to start:
#CELERYD_NODES=10

# Absolute or relative path to the 'celery' command:
CELERY_BIN="/home/jy95/Documents/oscareducation/ve/local/bin/celery"

# App instance to use
# comment out this line if you don't use an app
CELERY_APP="oscar"


# Where to chdir at start.
CELERYD_CHDIR="/home/jy95/Documents/oscareducation"

# Extra command-line arguments to the worker
# django_celery_beat for admin purpuse
# CELERYD_OPTS

# Set logging level to DEBUG
#CELERYD_LOG_LEVEL="DEBUG"

# %n will be replaced with the first part of the nodename.
CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
CELERYD_PID_FILE="/var/run/celery/%n.pid"

# Workers should run as an unprivileged user.
#   You need to create this user manually (or you can choose
#   a user/group combination that already exists (e.g., nobody).
CELERYD_USER="celery"
CELERYD_GROUP="celery"

# beat settings

CELERYBEAT_OPTS="--scheduler django_celery_beat.schedulers:DatabaseScheduler"

CELERYBEAT_LOG_FILE="/var/log/celery/celeryBeat.log"
CELERYBEAT_PID_FILE="/var/run/celery/celeryBeat.pid"

# If enabled pid and log directories will be created if missing,
# and owned by the userid/group configured.
CELERY_CREATE_DIRS=1
```

**some_app/tasks.py**:
```py
from __future__ import absolute_import, unicode_literals
from oscar import celery_app
from celery.schedules import crontab
from .models import HelpRequest
from datetime import datetime, timedelta
import logging

""" CONSTANTS FOR THE TIMER """
# Can be changed  (by default 1 week)
WEEKS_BEFORE_PENDING = 0
DAYS_BEFORE_PENDING = 0
HOURS_BEFORE_PENDING = 0
MINUTES_BEFORE_PENDING = 1


# http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html
# for schedule : http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules
# Why on_after_finalize ? https://stackoverflow.com/a/41119054/6149867
@celery_app.on_after_finalize.connect
def setup_periodic_tasks(sender, **kwargs):

    sender.add_periodic_task(
        crontab(minute=2),
        set_open_help_request_to_pending
    )


@celery_app.task(name="HR_OPEN_TO_PENDING")
def set_open_help_request_to_pending():
    """ For timedelay idea : https://stackoverflow.com/a/27869101/6149867  """
    logging.info("RUNNING CRON TASK FOR STUDENT COLLABORATION : set_open_help_request_to_pending")
    request_list = HelpRequest.objects.filter(
        state=HelpRequest.OPEN,
        timestamp__gte=datetime.now() - timedelta(hours=HOURS_BEFORE_PENDING,
                                                  minutes=MINUTES_BEFORE_PENDING,
                                                  days=DAYS_BEFORE_PENDING,
                                                  weeks=WEEKS_BEFORE_PENDING)
    )

    if request_list:
        logging.info("FOUND ", request_list.count(), "  Help request(s) => PENDING")
        for help_request in request_list.all():
            help_request.change_state(HelpRequest.PENDING)
```

My setup of rabbit : 
```bash
$ sudo rabbitmqctl add_user oscar oscar 
$ sudo rabbitmqctl add_vhost oscarRabbit 
$ sudo rabbitmqctl set_user_tags oscar administrator 
$ sudo rabbitmqctl set_permissions -p oscarRabbit oscar "." "." ".*"
```

The way I run this process : 
```bash
$ sudo rabbitmq-server -detached
$ sudo /etc/init.d/celeryd start 
$ sudo /etc/init.d/celerybeat start
$ source ve/bin/activate
$ python manage.py run server
```

## Expected behavior

Should working. 

## Actual behavior

The config_from_object doesn't seem to do its job.
Cannot figure out why it isn't working . Here is my log files : 

As you can see, it uses the default amqp url (and not the one I provided)
[celeryBeat.log](https://github.com/celery/celery/files/1486084/celeryBeat.log)
[worker1.log](https://github.com/celery/celery/files/1486085/worker1.log)

**Comment by thedrow** [comment]
If you are using the Django settings I think that this should be `CELERY_BROKER_URL` all caps.
Let me know if that works.

**Comment by jy95** [comment]
Correct me if I am not wrong but the [docs ](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings) says : 

> Version 4.0 introduced new lower case settings and setting organization.
> The major difference between previous versions, apart from the lower case names, are the renaming of some prefixes, like celerybeat_ to beat_, celeryd_ to worker_, and most of the top level celery_ settings > have been moved into a new task_ prefix.

> Celery will still be able to read old configuration files, so there’s no rush in moving to the new settings  format.

Setting name | Replace with
-- | -- 
BROKER_URL | broker_url

**Comment by thedrow** [comment]
Yes but you misunderstood the docs.
When you use the Django settings object everything is still prefixed with CELERY_ so only the uppercase form will work (and it makes sense since that's how Django defines the settings).
Let me know if you need something else.

**Comment by jy95** [comment]
Thanks : it was rewritten as lowercase with the celery command line tool ...  .
Finally, I dropped out celery for this project (seems the 4.0-4.1 releases are buggy if I believe the reviews I saw everywhere )

Hope the 4.2 release is up the next time I think about Celery XD

**Comment by trianglesis** [comment]
I can confirm BEAT deamonizing do not work, until I force options with:
CELERYD_OPTS="--beat --scheduler=django_celery_beat.schedulers:DatabaseScheduler"


Everything is configured and working fine, except of beat, it can only work with this conf below.
It works in "multi" module, but too bad, so I want to move it to deamon-type exec, but stil no luck, and not even live example can be found anywhere, just thousand tutorials with -B and --beat options.


**/etc/default/celeryd >**

> export DJANGO_SETTINGS_MODULE="octo.settings"
> CELERYD_NODES="beat"
> CELERY_BIN="/var/www/octopus/octo/bin/celery"
> CELERY_APP="octo.octo_celery:app"
> CELERYBEAT_CHDIR="/opt/celery/"
> CELERYD_OPTS="--beat --scheduler=django_celery_beat.schedulers:DatabaseScheduler"
> CELERYD_USER="user"
> CELERYD_GROUP="celery"
> CELERYD_PID_FILE="/opt/celery/beat.pid"
> CELERYBEAT_LOG_FILE="/var/log/celery/beat.log"
> CELERYBEAT_LOG_LEVEL="INFO"


**settings.py >**
No options, all moved to "octo_celery.py"


**__init__.py >**
> from .octo_celery import app as celery_app
> from octo.octologger import test_logger
> __all__ = ['celery_app']
> log = test_logger()

**octo_celery.py >**
> os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'octo.settings')
> django.setup()
> app = Celery('octo',
>              broker='amqp://USER:PASSWD@localhost:5672/HOSTNAME',
>              backend='django-db')
> app.config_from_object('django.conf:settings', namespace='CELERY')
> timezone            = 'UTC'
> enable_utc          = True
> app.conf.timezone   = 'Europe/London'
> app.conf.enable_utc = True
> app.autodiscover_tasks()
> default_exchange = Exchange('default',   type = 'direct')
> local_exchange   = Exchange('local',     type = 'direct')
> tests_exchange   = Exchange('tests_run', type = 'direct')
> task_default_exchange      = 'default'
> task_default_exchange_type = 'topic'
> task_default_routing_key   = 'default'
> celery_task_create_missing_queues = True
> app.conf.task_default_queue       = 'default'
> app.conf.update(
>     task_default_queue         = 'default',
>     task_default_exchange      = 'default',
>     task_default_routing_key   = 'default',
>     worker_pool_restarts       = True,
>     beat_scheduler             = 'django_celery_beat.schedulers:DatabaseScheduler',
>     worker_prefetch_multiplier = 0,
>     accept_content = ['json', 'pickle', 'application/x-python', 'application/json', 'application/x-python-serialize'],
>     task_serializer   = 'pickle',
>     result_serializer = 'json',
>     result_backend = 'django-db')

**Comment by Allan-Nava** [comment]
I create the file configuration (`/etc/default/celeryd`):, but when I try to start the service:
```
/etc/init.d/celeryd start 
-bash: /etc/init.d/celeryd: File o directory non esistente
```
