### ISSUE TITLE
Nested chords never complete

### ISSUE THREAD

**Issue by max4t** [celery/celery#4401]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

```
software -> celery:4.0.2 (latentcall) kombu:4.1.0 py:2.7.14
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://redis/0

broker_url: u'amqp://rabbit:5672//'
result_backend: u'redis://redis/0'
```

## Steps to reproduce
```python
from tasks import tsum
from celery import chord, group, chain

runner = group([
    group([
        tsum.s([1, 2]),
        tsum.s([4, 5])
      ]) | tsum.s(),
    group([
        tsum.s([6, 7]),
        tsum.s([8, 10])
      ]) | tsum.s()
  ]) | tsum.s()
```

## Expected behavior

`runner().get()` never finishes. Stops after the 4 most-nested groups finished and seems to wait idly.
Same when switching from group/chain to chord.
But works with EAGER on

## Actual behavior

expect to finish

**Comment by AlexHill** [comment]
Hi @max4t there have been some fixes around nested chords recently and your test scenario now passes for me on master. I'm going to close this - please try out the latest code and re-open this is the issue persists for you.
