### ISSUE TITLE
[Site] Link error "operate with other languages"

### ISSUE THREAD

**Issue by thenets** [celery/celery#4406]
Page not found at http://www.celeryproject.org/ :

![image](https://user-images.githubusercontent.com/2138276/33258196-d7485890-d33f-11e7-8610-bf6c61330203.png)

![image](https://user-images.githubusercontent.com/2138276/33258235-fa062f2e-d33f-11e7-9683-2dd44e856fb0.png)

**Comment by thedrow** [comment]
Thanks for the report. We'll get it fixed :)

**Comment by thedrow** [comment]
@auvipy Have we fixed this? Where is the related commit?

**Comment by auvipy** [comment]
I think this is a site issue so I moved the issue to celeryproject site repo, issue 18
