### ISSUE TITLE
Celery + Django: Task discover fails silently when wrong permissions in log file

### ISSUE THREAD

**Issue by sebastiaopf** [celery/celery#4408]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
- Create a Django Project and some celery task
- Configure a Django logging handler to use 'file'
- Allow write permissions on the django log file to the user who runs django, but not the user who runs the Celery worker
- EDIT: Change into the celery user (`su - celery` for example), to simulate how the service will execute
- Try to start celery worker with something like `/usr/local/bin/celery -A my_app worker -Q loan -l debug --logfile=/var/log/celery/celery.log --pidfile=/var/run/celery/celery.pid`

## Expected behavior
Celery worker should start and discover the tasks OR Celery worker should fail and inform it can't discover the tasks because (?) the current user can't write to the Django log file.

## Actual behavior
Celery worker starts, but fails to discover the tasks. But it doesn't show any error message, event with `-l debug`.

OK, I'm not sure if this is a bug in Celery or Django, or even if it's a bug at all. At least I'm leaving this here if someone else has the same problem. It took me some time to figure this out, so maybe I can save someone else's time.

At first I thought it was a problem with Systemd, but after sudo'ing into the Celery user and trying to run the command manually, i found that it fails to discover the tasks. The same command works when ran under root. The celery user has write permissions to all its folders, and has read permissions on the Django project folder. What it didn't have (and I never thought it would need) is write permissions on the Django log file/folder. After I gave the Celery user write permission to the file, it started discovering the tasks fine. The telling symptom for me was that when sudo'ing into the Celery user i couldn't run the Django manage.py command (should I need to?).

I think that even if this isn't a bug in Celery itself, it would benefit users if it could show a warning message telling that it couldn't write to the Django log file (or whatever reason is the root cause for this).

Attached report file is from when the Celery user didn't have the write permissions to the Django log file.

[report.txt](https://github.com/celery/celery/files/1510220/report.txt)

**Comment by sebastiaopf** [comment]
@auvipy thanks for your reply. I'd be happy to try and see what I can find.
Could you point me in the general direction I should be looking for this?
I'm not familiar with celery's source code structure.

**Comment by ianalexr** [comment]
Recently encountered this. After some poking around it looks like it's fixed in 4.2.0 by #4146. Figured I'd let you know since this is still open.
