### ISSUE TITLE
Chunks Performance Issue

### ISSUE THREAD

**Issue by exrich** [celery/celery#4409]
I have between 5000-10000 tasks to execute and to minimize the number of messages sent I'm putting them in chunks.  Whilst trying to get 5000 tasks to execute in under a second I noticed a delay in retrieving chunked results.  I'm running Redis results backend, AMPQ broker and Celery 4.1.0

No significant delay in sending the tasks:

%timeit tasks.add.chunks([(1,1)], 1)()
1000 loops, best of 3: 818 µs per loop
%timeit tasks.add.delay(1,1)
1000 loops, best of 3: 490 µs per loop

But retrieving is slow:

%timeit tasks.add.chunks([(1,1)], 1)().get()
1 loop, best of 3: 502 ms per loop
%timeit tasks.add.delay(1,1).get()
1000 loops, best of 3: 1.56 ms per loop

I thought it might be the db interval but the docs say it doesn't apply to Redis and adding interval=0.01 makes no difference:

%timeit tasks.add.chunks([(1,1)], 1)().get(interval=0.01)
1 loop, best of 3: 505 ms per loop

**Comment by auvipy** [comment]
were you able to apply any fix or workaround?

**Comment by auvipy** [comment]
use new release and report again.
