### ISSUE TITLE
Storing additional information about celery tasks in mongodb

### ISSUE THREAD

**Issue by yutkin** [celery/celery#4414]
I want to store in MongoDB additional information about a task. For example, an ID of a user that created the task. Example:
```
    {
      "_id" : "a77db490-d090-4c9d-a48c-b6f766bee902",
      "status" : "SUCCESS",
      "result" : "8",
      "date_done" : ISODate("2017-11-17T10:16:28.942Z"),
      "traceback" : "null",
      "children" : "[]",

      "task_creator": "username" // <---- How can I add such field?

    }
```
This is needed for simplification of querying (my app is statefull). How can I do it?

**Comment by johnarnold** [comment]
See:
https://github.com/celery/celery/issues/4309
