### ISSUE TITLE
Celerybeat not delivered to correct queue if specified in options

### ISSUE THREAD

**Issue by Woile** [celery/celery#4415]
## Checklist

- [x] I have included the version of celery in the issue.
```
>>> celery --version
4.0.2 (latentcall)
```
and master
```
>>> celery --version
4.1.0 (latentcall)
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. Create a debug task:
```
@app.task(bind=True)
def debug_task(self, word):
    logger.setLevel(logging.DEBUG)
    logger.info('Is this your word? %s', word)
    print('Request: {0!r}'.format(self.request))
```
2. Add a periodic task like this:
```
app.add_periodic_task(crontab(
        minute='*/1',  # run every minute
    ), debug_task.s('foo'),
        options={'queue': 'foo',
                       'routing_key': 'foo'})
```

3. Run 2 workers with different queues and a beat
```
celery worker -A proj worker -Q foo -n foo@%h --loglevel=DEBUG
celery worker -A proj worker -Q bar -n bar@%h --loglevel=DEBUG
celery -A main.celery_app beat --loglevel=DEBUG
```
4. Wait and observe.

## Expected behavior

The task is delivered to the right queue according to [the docs](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html), options will be passed to `apply_async`, so if I add `queue` it should go to the correct queue

>options
>
> Execution options (dict).
>
> This can be any argument supported by apply_async() – exchange, routing_key, expires, and so on.

## Actual behavior
The task is handled by any queue.

## Solution

I found that if I specify `queue` as an attribute of `add_periodic_task` it starts working correctly. But I couldn't find any related information in the documentations. Like this:
```
app.add_periodic_task(crontab(
        minute='*/1',  # run every minute
    ), debug_task.s('foo'),
        queue='foo',
        options={'queue': 'foo',
                       'routing_key': 'foo'})
```

Am I missing something here?

**Comment by auvipy** [comment]
could you try celery 4.2rc2 and report again?

**Comment by Woile** [comment]
Sorry for the delay.

This is the test I did:

```python
# tasks.py
from celery import Celery
from celery.schedules import crontab


app = Celery('tasks', broker='pyamqp://guest@localhost//')


@app.task(bind=True)
def debug_task(self, word):
    print(f'==============Is this your word? f{word}==============')
    print('Request: {0!r}'.format(self.request))


app.add_periodic_task(
    crontab(
        minute='*/1',  # run every minute
    ), 
    debug_task.s('foo'),
    options={
        'queue': 'foo',
        'routing_key': 'foo'})
```

And in three different terminals:
`celery -A tasks beat --loglevel=DEBUG`
`celery -A tasks worker -Q bar -n bar@%h --loglevel=DEBUG`
`celery -A tasks worker -Q foo -n foo@%h --loglevel=DEBUG`


**Conclusions**

 I'm not sure if it is working as intended or not working.

- Now instead of running in both queues, it runs in NO queue.
- The solution is still the same, adding `queue` parameter, like:

```python
app.add_periodic_task(
    crontab(
        minute='*/1',  # run every minute
    ), 
    debug_task.s('foo'),
    queue='foo',   # HERE!!
    options={
        'queue': 'foo',
        'routing_key': 'foo'})
```

I've read a while ago, that it is necessary to specify the queue in both places for beat, is this true? Or is this a bug? In case adding the `queue` parameter twice *is* expected, then the bug is **SOLVED**.

**Comment by noisyox** [comment]
put this in celery.py 

app.conf.task_routes = {
    'app.tasks.foo': {'queue': foo'}
}

All type of tasks will follow this setting and you won't have to explicitly mention it anywhere else.
