### ISSUE TITLE
How to unpack serialzied task arguments?

### ISSUE THREAD

**Issue by jenstroeger** [celery/celery#4420]
When iterate over all currently scheduled tasks
```python
for task in chain.from_iterable(my_app.control.inspect().scheduled().values()):
    print(task)
```
I get a dictionary `task['request']` which contains a serialization of the tasks’ arguments in `task['request']['args']` (and `'kwargs`). Both are strings:
```
'args': "('5', {'a': 'b'})",
'kwargs': '{}', 
```
It’s not [JSON](https://www.json.org/) nor [msgpack](https://msgpack.org/). How can I unpack that `args` string into a Python tuple again? Celery must have a helper function for that somewhere? (Anything to do with `argsrepr` and `kwargsrepr` and [`saferepr`](https://github.com/celery/celery/blob/master/celery/utils/saferepr.py)?)

**Comment by georgepsarakis** [comment]
This should be the string representation of the Python object. If you try the JSON [serializer](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_serializer), I think you will be closer to deserialize them consistently.

**Comment by jenstroeger** [comment]
My celery is configured with
```
    "task_serializer": "json",                                                                      
    "result_serializer": "json",                                                                    
    "accept_content": ["json"],                                                                     
```
already, has been from the beginning.

**Comment by georgepsarakis** [comment]
JSON is the default serializer in 4.x , but I thought of mentioning it just in case.

**Comment by jenstroeger** [comment]
Just FYI: this question has _not_ been answered. A task’s arguments are _not_ serialized using JSON.

**Comment by georgepsarakis** [comment]
@jenstroeger I think you are right, it does have to do with [saferepr](https://github.com/celery/celery/blob/120770929f4a37c5373a378b75b5c41a99702af9/celery/app/amqp.py#L337). Try passing `argsrepr=json.dumps(args)` and/or `kwargsrepr=json.dumps(kwargs)` when calling your task, by encoding the task arguments to JSON. That way you can deserialize them consistently and securely. Let me know if this works!

**Comment by RomainDLS** [comment]
Using `eval()` to unpack args and kwargs seems to work for me.

**Comment by ShaheedHaque** [comment]
Sorry to be late to this party, but `eval()` as noted by @RomainDLS introduces some risk of accidental code execution (albeit arguably small in this context). A more conservative approach is `ast.literal_eval()` which cannot execute code (and might be cheaper - just a guess?).

**Comment by jenstroeger** [comment]
Thanks @RomainDLS and @ShaheedHaque, both [`eval()`](https://docs.python.org/3/library/functions.html#eval) and [`literal_eval()`](https://docs.python.org/3/library/ast.html#ast.literal_eval) work for me. One more option would be the following:
```python
>>> args = …  # Whatever string task_request["args"] contains.
>>> json.loads(args.replace('(','[').replace(')',']').replace("'", '"'))
```
although that may not be a universal solution.

**Comment by auvipy** [comment]
the right places to ask questions are celery-users mailing list and #celery IRC channel on freenode.

**Comment by freewilll** [comment]
Looks like something changed in 4.4.0, released 2 days ago. evaI() is no longer needed as args is now an array. I've not overridden any serializers or anything like that. I suspect some out of the box default has changed, but I've not been able to find the smoking gun.
