### ISSUE TITLE
Document that tasks are now documented automatically by celery

### ISSUE THREAD

**Issue by thedrow** [celery/celery#4423]
See https://github.com/celery/celery/pull/4422

**Comment by johnarnold** [comment]
@thedrow @auvipy What is the doc bug that is blocking?  What's the task/todo?

If (as it appears to me) automodule just "works correctly now," I don't think that warrants a doc update at all...

**Comment by thedrow** [comment]
We need to add a page describing how to activate the Sphinx addon so that tasks will be documented correctly.
I haven't found the time to do so yet.

**Comment by clokep** [comment]
http://docs.celeryproject.org/en/master/reference/celery.contrib.sphinx.html seems to document this fairly well (although it's in the reference section, not in the userguide).

**Comment by thedrow** [comment]
This issue is about including it in the userguide.
