### ISSUE TITLE
Whether celery can start worker with specify region when using sqs?

### ISSUE THREAD

**Issue by UpTownCat** [celery/celery#4425]
I send message too amazon sqs with specify queue and region， but when I start a worker, I do not know how to specify queue with the same region，so the worker can’t receive messages from the queue. Is that celery support this？

**Comment by UpTownCat** [comment]
I solved this issue with the configuration of CELERY_BROKER_TRANSPORT_OPTIONS = {'region': 'xxx', 'queue': 'queue_xxx'}, besides start worker use option params -Q
celery -A project worker -l info --concurrency=1 -Q queue_xxx

**Comment by georgepsarakis** [comment]
@UpTownCat thanks for sharing the solution.
