### ISSUE TITLE
Celery 4.1.0 python 2.7 cause UnicodeDecodeError

### ISSUE THREAD

**Issue by YuraSerko** [celery/celery#4441]
celery==4.1.0
Python 2.7.6
Django==1.11
ubuntu 16.04
rabbitmq 3.7.0
Erlang 20.1
kombu==4.1.0

```
from django.db import models 
class Order(models.Model):
    myclient = models.ForeignKey('MyClient', verbose_name='asfd', default=None, null=True, on_delete=models.CASCADE, related_name='sdf')
    sdf = models.ForeignKey('sdfh', verbose_name='sadfh', default=None, null=True, on_delete=models.SET_DEFAULT, blank=False)
    ....
def  __unicode__ (self):
    return u'%s %s' % (self.id, self.description)   
```
mess.hint.order - object of Order class

without delay everything is ok. 
send_sms_celery - my custom function  
send_sms_celery.delay('message', '4234234324', toAuthor=True, order=mess.hint.order, fromPhone=title)

---------------------------------------------------------------------------
```
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-941323d5cc3d> in <module>()
----> 1 send_sms_celery.delay('message', '4234234324', toAuthor=True, order=mess.hint.order, fromPhone=title)

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/task.pyc in delay(self, *args, **kwargs)
    411             celery.result.AsyncResult: Future promise.
    412         """
--> 413         return self.apply_async(args, kwargs)
    414 
    415     def apply_async(self, args=None, kwargs=None, task_id=None, producer=None,

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/task.pyc in apply_async(self, args, kwargs, task_id, producer, link, link_error, shadow, **options)
    534             link=link, link_error=link_error, result_cls=self.AsyncResult,
    535             shadow=shadow, task_type=self,
--> 536             **options
    537         )
    538 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/base.pyc in send_task(self, name, args, kwargs, countdown, eta, task_id, producer, connection, router, result_cls, expires, publisher, link, link_error, add_to_parent, group_id, retries, chord, reply_to, time_limit, soft_time_limit, root_id, parent_id, route_name, shadow, chain, task_type, **options)
    727             reply_to or self.oid, time_limit, soft_time_limit,
    728             self.conf.task_send_sent_event,
--> 729             root_id, parent_id, shadow, chain,
    730         )
    731 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/amqp.pyc in as_task_v2(self, task_id, name, args, kwargs, countdown, eta, group_id, expires, retries, chord, callbacks, errbacks, reply_to, time_limit, soft_time_limit, create_sent_event, root_id, parent_id, shadow, chain, now, timezone, origin, argsrepr, kwargsrepr)
    339             argsrepr = saferepr(args, self.argsrepr_maxsize)
    340         if kwargsrepr is None:
--> 341             kwargsrepr = saferepr(kwargs, self.kwargsrepr_maxsize)
    342 
    343         if JSON_NEEDS_UNICODE_KEYS:  # pragma: no cover

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/utils/saferepr.pyc in saferepr(o, maxlen, maxlevels, seen)
     92     """
     93     return ''.join(_saferepr(
---> 94         o, maxlen=maxlen, maxlevels=maxlevels, seen=seen
     95     ))
     96 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/utils/saferepr.pyc in _saferepr(o, maxlen, maxlevels, seen)
    199             val = _format_chars(token.value, maxlen)
    200         else:
--> 201             val = _safetext(truncate(token, maxlen))
    202         yield val
    203         if maxlen is not None:

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/utils/text.pyc in truncate(s, maxlen, suffix)
     98     """Truncate text to a maximum number of characters."""
     99     if maxlen and len(s) >= maxlen:
--> 100         return s[:maxlen].rsplit(' ', 1)[0] + suffix
    101     return s
    102 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)
```
---------------------------------------------------------------------------------------------------------------------------------------
the problem is in mess.hint.order - my param. If i change method def __unicode__(self) of class of object order and make it not return characters and return for example number '111'. everything will be ok
But it is not good for me make changes in all the project in __unicode__  methods

**Comment by AlexHill** [comment]
What is the value of `mess.hint.order`? What is its type? As long as it's unicode rather than bytes, you should be fine.

I believe there's a bug in the `celery.utils.saferepr._saferepr` function on line 201 - it should perhaps be `truncate(_safetext(token, maxlen))` rather than  `_safetext(truncate(token, maxlen))`. The `truncate` function doesn't deal with non-ASCII bytes, but before `_safetext` is called, the value could still not be unicode.

**Comment by YuraSerko** [comment]
mess.hint.order
order is object of class Order(models.Model) // from django.db import models    
def __unicode__(self):
        return u'%s %s' % (self.id, self.description)

**Comment by YuraSerko** [comment]
AlexHill, it did not help. Another error occured


`TypeError                                 Traceback (most recent call last)
<ipython-input-5-941323d5cc3d> in <module>()
----> 1send_sms_celery.delay('message', '323432', toAuthor=True, order=mess.hint.order, fromPhone=title)

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/task.pyc in delay(self, *args, **kwargs)
    411             celery.result.AsyncResult: Future promise.
    412         """
--> 413         return self.apply_async(args, kwargs)
    414 
    415     def apply_async(self, args=None, kwargs=None, task_id=None, producer=None,

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/task.pyc in apply_async(self, args, kwargs, task_id, producer, link, link_error, shadow, **options)
    534             link=link, link_error=link_error, result_cls=self.AsyncResult,
    535             shadow=shadow, task_type=self,
--> 536             **options
    537         )
    538 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/base.pyc in send_task(self, name, args, kwargs, countdown, eta, task_id, producer, connection, router, result_cls, expires, publisher, link, link_error, add_to_parent, group_id, retries, chord, reply_to, time_limit, soft_time_limit, root_id, parent_id, route_name, shadow, chain, task_type, **options)
    727             reply_to or self.oid, time_limit, soft_time_limit,
    728             self.conf.task_send_sent_event,
--> 729             root_id, parent_id, shadow, chain,
    730         )
    731 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/app/amqp.pyc in as_task_v2(self, task_id, name, args, kwargs, countdown, eta, group_id, expires, retries, chord, callbacks, errbacks, reply_to, time_limit, soft_time_limit, create_sent_event, root_id, parent_id, shadow, chain, now, timezone, origin, argsrepr, kwargsrepr)
    339             argsrepr = saferepr(args, self.argsrepr_maxsize)
    340         if kwargsrepr is None:
--> 341             kwargsrepr = saferepr(kwargs, self.kwargsrepr_maxsize)
    342 
    343         if JSON_NEEDS_UNICODE_KEYS:  # pragma: no cover

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/utils/saferepr.py in saferepr(o, maxlen, maxlevels, seen)
     92     """
     93     return ''.join(_saferepr(
---> 94         o, maxlen=maxlen, maxlevels=maxlevels, seen=seen
     95     ))
     96 

/home/zaochnik/venv3/local/lib/python2.7/site-packages/celery/utils/saferepr.py in _saferepr(o, maxlen, maxlevels, seen)
    200         else:
    201             #val = _safetext(truncate(token, maxlen))
--> 202             val = truncate(_safetext(token, maxlen))
    203         yield val
    204         if maxlen is not None:

TypeError: _safetext() takes exactly 1 argument (2 given)

`

**Comment by auvipy** [comment]
could you check this link? https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by AlexHill** [comment]
Sorry, that was a typo - should be `val = truncate(_safetext(token), maxlen)`.

**Comment by AlexHill** [comment]
@YuraSerko have dug into this a bit more. Does your `Order` class have a custom `__repr__` that ends up calling your `__unicode__` method? When you pass arbitrary objects as arguments, they're ultimately [converted with repr](https://github.com/alexhill/celery/blob/e6a6cced7f8bd7d6cba21374653aebad4f8fc65e/celery/utils/saferepr.py#L273).

There may well be a bug here, but even if there wasn't this would fail because the argument you're passing simply isn't JSON serialisable, and that's a Celery requirement. Your `Order` object isn't going to make it through the serialisation/deserialisation process intact.

Your task needs to take a serialisable argument (like a plain Python dictionary or an ID) rather than an `Order` object) and then reconstruct the `Order` from that on the other end.

**Comment by auvipy** [comment]
I am closing this as not a celery bug
