### ISSUE TITLE
Celery (4.1.0) worker stops to consume new message when actives is empty  

### ISSUE THREAD

**Issue by yanliguo** [celery/celery#4451]
Hi there,
   I was using celery to dispatch some long running task recently, and finding a way to disable prefetch. Now the config is:

acks_late = True
concurrency = 1
prefetch_multiplier = 1
-Ofair

Actually, workers are still prefetching tasks. And I also have a monitor job to revoke tasks when a task is stuck in reserved state for a long time (let's say 5 minutes) or the task is outputing valid result.  

One thing wired is that, some workers stopped consuming new tasks when the actives is empty and the reseved task is revoked.  Has anybody ever met with this issue ? any help will be appreciated.

**Comment by auvipy** [comment]
could you please elaborate more about your usecase and settings? celery versions etc?

**Comment by dralley** [comment]
This does sound similar to something we've been experiencing. https://pulp.plan.io/issues/2835#note-15

**Comment by auvipy** [comment]
whats its status with celery 4.2.1?
