### ISSUE TITLE
New configuration lowercase settings don't appear to work in 4.1.0.

### ISSUE THREAD

**Issue by glynjackson** [celery/celery#4452]
I have just updated from Celery 3.x to 4.1.0. I changed the broker URL settings from **uppercase** to **lowercase** as described here: http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings

> Version 4.0 introduced new lower case settings and setting organization.

However, it appears that only the uppercase version of `BROKER_URL` works in 4.1.0. Using the new lowercase settings as described above don't appear to work for me? Why?

## Steps to reproduce
Updated celery to 4.1
```
> pip install celery==4.1
> pip show celery
```
Output.
```
Name: celery
Version: 4.1.0
Summary: Distributed Task Queue.
Home-page: http://celeryproject.org
Author: Ask Solem
Author-email: ask@celeryproject.org
License: BSD
Location: /Users/glyn/Documents/workspace/shortbite/env/lib/python3.6/site-packages
Requires: billiard, pytz, kombu
```

Changed celery setting as per instructions 👍 

FROM: `BROKER_URL = amqp://x:x@broker-staging.x.eu:5672//'`
TO: `broker_url = amqp://x:x@broker-staging.x.eu:5672//'`

## Expected behaviour

```
app = Celery('tasks')

app.config_from_object('django.conf:settings')
# Load task modules from all registered Django app configs.
app.autodiscover_tasks()
print(app.conf.broker_url)
```
> OUTPUT: amqp://x:x@broker-staging.x.eu:5672//

## Actual behaviour

```
app.config_from_object('django.conf:settings')
# Load task modules from all registered Django app configs.
app.autodiscover_tasks()
print(app.conf.broker_url)
```
> OUTPUT: None

Using: 
* Python 3.6
* Django 1.9.9
* Celery 4.1.0

**Comment by glynjackson** [comment]
> Celery will still be able to read old configuration files, so there’s no rush in moving to the new settings format.

After some investigation it appears that Django settings can only be an uppercase.  So, if you’re loading Django settings in to Celery using this method you cannot use the new lowercase versions as documented. 

The new 4.1 Celery documentation is somewhat misleading.

**Comment by pachewise** [comment]
@auvipy @glynjackson - this is mentioned in the Django section, and in the what's new in 4.0 section... I'm guessing we just want to reword a bit and add a note in the userguide/configuration? similar issue with documentation seen in #4198

**Comment by C0DK** [comment]
I realize that this is closed in 2017, however the documentation is still lacking, in my honest opinion.

And the example doesn't really portray it that well. https://github.com/celery/celery/blob/v5.0.5/examples/django/proj/celery.py#L14

I've atleast used multiple hours trying to debug (however i might just be stupid).
