### ISSUE TITLE
Celery worker hangs when Redis node is rebooted

### ISSUE THREAD

**Issue by joshma** [celery/celery#4453]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
-> bigworker@rochetest-celery-0: OK
    - empty -
-> bigworker@rochetest-celery-1: OK
    - empty -
```
- [ ] I have verified that the issue exists against the `master` branch of Celery.
I have not had time to do this, but I hope this issue is relevant anyways - I'm on `celery==3.1.25` and `kombu==3.0.37`.

## Steps to reproduce
We use ElastiCache Redis on AWS with celery - I've been trying to diagnose why we frequently (a few times a week) see some of our workers suddenly stop processing tasks. (This is usually in the middle of the night, even on test deployments with no real traffic.)

I've come to suspect something with Redis rebooting and the workers not reconnecting. To reproduce, I went to the AWS console and selected "Reboot node" on the primary node:
![image](https://user-images.githubusercontent.com/64739/34010658-674f1be2-e0c2-11e7-927b-852c5e4cce1c.png)

This then causes the workers we have to stop processing tasks until I restart them (the flat region starts when I reboot Redis and only ends when I restart celery):
![image](https://user-images.githubusercontent.com/64739/34010560-0dd5e3b6-e0c2-11e7-8439-db51cd52e669.png)

## Expected behavior
Expected behavior is that the workers figure out their connection is bad and reconnect. For example, if I do a "failover" in AWS, so that our replica is promoted to a primary, the celery workers successfully reconnect to the new replica.

## Actual behavior
The celery workers stop processing tasks indefinitely, until they're manually restarted.

**Comment by joshma** [comment]
(To clarify, the 11:28 mark is when I manually restarted the node. I verified that the node was done rebooting at 11:27.)

**Comment by auvipy** [comment]
sorry you dont support celery 3 anymore. upgrading to celery 4.1+ should resolve many of your issue. celery 4.2 is coming in next january.

**Comment by joshma** [comment]
For others watching, our team investigated further and we believe this is the same as https://github.com/celery/celery/issues/1221
