### ISSUE TITLE
bug in documentation for tasks regarding spam_filter()?

### ISSUE THREAD

**Issue by ckot** [celery/celery#4455]
It might just be that it's 5:30 am and I'm simply not noticing something which is right in front of me, but at the very bottom of:

http://docs.celeryproject.org/en/latest/userguide/tasks.html

in `tasks.py`, there is a reference to `settings.AKISMET_KEY`.  I don't see `settings` defined anywhere in that module.  is there supposed to be a `from django.conf import settings` in that file, or am I missing something?

**Comment by auvipy** [comment]
if the key is explicitely defined in django settings then your suggested way is right

**Comment by ckot** [comment]
That's a good point. I hadn't thought about settings potentially being defined elsewhere. I merely noticed that it wasn't defined.
