### ISSUE TITLE
Examples for RPC celery

### ISSUE THREAD

**Issue by folt** [celery/celery#4460]
Examples for RPC celery
I found a good [example for kombu implementation of RPC](https://github.com/celery/kombu/blob/master/examples/rpc-tut6/)

But I did not find how to do PRC for celery
on this I have a question:
Is it necessary to do RPC with celery or is it better to use workers without celery?
I would like to see my workers run command `celery -A proj worker`

**Comment by auvipy** [comment]
prc or rpc?

**Comment by folt** [comment]
@auvipy Sorry - RPC

**Comment by auvipy** [comment]
check celery broker/result back end docs
