### ISSUE TITLE
django 1.11 with celery can't discover tasks?

### ISSUE THREAD

**Issue by tyan4g** [celery/celery#4461]
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#django-first-steps

follow all the step in the about url , and celery can't found any tasks in my app module.

when using blog.apps.BlogConfig installed apps,

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'blog.apps.BlogConfig',
]

does not work..

but if I change it to blog then the task can be found..

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'blog',
]

what's the problem here???

**Comment by auvipy** [comment]
post this to irc or mailing list
