### ISSUE TITLE
INFO log messages land to stderr

### ISSUE THREAD

**Issue by lexabug** [celery/celery#4462]
I've set up a basic application with Django 2.0 and Celery 4.1.0 with debug task (as it described [here](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-celery-with-django)) and one custom task in application tasks module.
My module code look like this:
```
# Create your tasks here
from __future__ import absolute_import, unicode_literals
from celery import shared_task
from django.conf import settings
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

@shared_task(name='validate_user_email', ignore_result=True, bind=True)
def validate_user_email(self, user_id):
    logger.info('%s email verified', user_id)
```

When I redirect streams (stdout and stderr) to different logs  (info.log and error.log) info.log is silent while error.log contains log entries with levels WARNING and INFO.

Command I execute celery with is: `celery -A email_validation worker -Q validate --concurrency 5 --maxtasksperchild 100 -l info > info.log 2> error.log`

Celery config:
```
CELERY_BROKER_URL = '******************'
CELERY_BROKER_HEARTBEAT = 900
CELERY_BROKER_HEARTBEAT_CHECKRATE = 15
CELERY_RESULT_BACKEND = 'amqp'
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
CELERY_TASK_ACKS_LATE = True
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'US/Eastern'
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_EVENT_QUEUE_TTL = 1
CELERY_EVENT_QUEUE_EXPIRES = 60
CELERY_RESULT_EXPIRES = 3600
CELERY_TASK_IGNORE_RESULT = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = True
```

How can make celery to post INFO log messages to stdout?

**Comment by MattBlack85** [comment]
You have to start workers with `-f /path/to/logfile.log`
If not passed LOGFILE option, is set by default to stderr. Had the same problem not so long ago

**Comment by lexabug** [comment]
@MattBlack85 ii thought that celery allows to configure logging in very flexible manner, so i can separate log messages by their loglevel into different streams. For example, i want to keep INFO and more severe messages in info.log, and everything from WARNING and above into error.log. Another one thing that i want to run celery app with circus process manager that allows to capture standard streams with the following configuration:
```
[watcher:email-validation-validate]
cmd = /var/www/email-validation/venv/bin/celery -A email_validation worker -Q validate --concurrency 5 --maxtasksperchild 100 -l info
working_dir = /var/www/email-validation/current
uid = vagrant
gid = vagrant
numprocesses = 1
stderr_stream.class = FileStream
stderr_stream.filename = /var/log/email-validation/validate_error.log
stderr_stream.max_bytes = 10000000
stderr_stream.backup_count = 3
stdout_stream.class = FileStream
stdout_stream.filename = /var/log/email-validation/validate_info.log
stdout_stream.max_bytes = 10000000
stdout_stream.backup_count = 3
```

**Comment by MattBlack85** [comment]
I don't think Celery support what you want out of the box, it sounds a bit like an edge case, you should override the celery logger to achieve your goal. With - f your startup configuration should work fine (I use supervisisord with a very similar configuration and it works)

**Comment by lexabug** [comment]
@MattBlack85 Supervisord pretty much the same as the circus.
If I use `-f` that would put all log entries to a file leaving standard streams empty, thus I wouldn't need those directives setting up log files and I think I would lose advantage of rotating log files by the circus.

**Comment by MattBlack85** [comment]
Dunno circus specific but apparently for me using - f and configuring supervisor to do logrotation works pretty well. Also error logs go to a second file specified in the supervisor configuration while only the other ones go to LOGFILE

**Comment by MattBlack85** [comment]
This is my config
```
[program:celery]
command=celery worker -A config %(ENV_QUEUE)s -l info -f /mnt/app_logs/celery.log -E
stdout_logfile=/mnt/app_logs/celery.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/mnt/app_logs/celery_errors.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
autostart=true
```

**Comment by lexabug** [comment]
Thank you I'll try something like that w/ circus.

**Comment by lexabug** [comment]
@MattBlack85 I've tried that approach and I noticed there a security concern.  Your config (so does mine) tells supervisord to rotate logs larger than 1MB and keep up to 10 backups. I assume that supervisord process is executed by root user thus log files are owned by it. In order to let celery process to write the same log files it should be executed by root too, which is not secure since in such case the application can access system resources with root privileges.

**Comment by MattBlack85** [comment]
Right that's true but my workers are dockerized so that is not a big issue for us cause only celery is running within that container

**Comment by MattBlack85** [comment]
btw I think you can drop privileges when starting processes and you should still be fine, afair master process intercepts children log emissions and write them to file

**Comment by auvipy** [comment]
so this isn't a bug? Is there any thought to improve the edge case? or this can left close

**Comment by lexabug** [comment]
I'm not sure, perhaps it's an intended behavior. I wonder if there a way of configuring celery's logger just to use stream handlers and separate log entries like i want: info and all that above to stdout, all that above info - to stderr.

**Comment by ClintOxx** [comment]
@MattBlack85 two days worth of trying to figure out why celery wouldnt print my errors to my log but would show them in the console and you fixed it for me, THANKS. 

I didnt know about the -f flag I didnt see a mention of it anywhere ugh. 

Im still not exactly sure why I have to point it to the .log file when launching celery since i already do it inside my code

**Comment by auvipy** [comment]
closing it as not bug. if anyone has any suggested improvement, we will reconsider that.
