### ISSUE TITLE
Celery schedule doesn't work after change local datetime for testing

### ISSUE THREAD

**Issue by b3g00d** [celery/celery#4466]
When I turn `ntp` on. My schedule with crontab working fine. But after I change the datetime back to the pass and turn `ntp` off. The schedule with crontab not working anymore. How can I test with specific time ?

**Comment by haishenming** [comment]
Me too. I think this is a bug only for 4.1, when i back to 4.0, it works.

**Comment by auvipy** [comment]
I think this issue is fixed on master, do check after 4.2 release

**Comment by haishenming** [comment]
i'l try, thanks
