### ISSUE TITLE
Call to ResultSet.get() hangs indefinitely even though all tasks in set have completed

### ISSUE THREAD

**Issue by keaneokelley** [celery/celery#4470]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.   

> software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.4
>             billiard:3.5.0.3 redis:2.10.6
> platform -> system:Linux arch:64bit, ELF imp:CPython
> loader   -> celery.loaders.app.AppLoader
> settings -> transport:redis results:redis:///
> 
> broker_url: 'redis://localhost:6379//'
> result_backend: 'redis:///'
> 

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Looks very similar to https://github.com/celery/celery/issues/2672

Consider the following code, an oversimplification of what I am trying to do in a real application:
```python
from celery import Celery
from celery.result import ResultSet

celery = Celery('celtest', backend='redis://', broker='redis://')


@celery.task(bind=True)
def test_task(self, a: int, b: int):
    self.update_state(state='RESULTS', meta={'test': a + b})
    return a + b


def callback(data):
    print(data)


def launch_many_tasks():
    r = ResultSet([])
    for i in range(10):
        r.add(test_task.delay(i, i + 1))
    r.get(on_message=callback)
    print("Done!")


if __name__ == '__main__':
    launch_many_tasks()
```

## Expected behavior
The application will print out the results of each task (in the callback function), print "Done!", and exit.
## Actual behavior
The results of each task are printed out in the callback function. The execution hangs at `r.get()`, with or without the `on_message` argument. The Celery console shows that 10 tasks were started and completed successfully. Using Flower, it shows that all tasks are completed, nothing is waiting or in a queue somewhere.

This traceback was obtained after a SIGINT, perhaps indicating where things are hung:
```
Traceback (most recent call last):
  File "celtest.py", line 27, in <module>
    launch_many_tasks()
  File "celtest.py", line 22, in launch_many_tasks
    r.get(on_message=callback)
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/result.py", line 644, in get
    on_interval=on_interval,
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/result.py", line 762, in join_native
    on_message, on_interval):
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/backends/async.py", line 142, in iter_native
    for _ in self._wait_for_pending(result, no_ack=no_ack, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/backends/async.py", line 255, in _wait_for_pending
    on_interval=on_interval):
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/backends/async.py", line 56, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/backends/async.py", line 65, in wait_for
    wait(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/celery-4.1.0-py3.6.egg/celery/backends/redis.py", line 77, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2513, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2428, in parse_response
    if not block and not connection.can_read(timeout=timeout):
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 619, in can_read
    bool(select([sock], [], [], timeout)[0])
KeyboardInterrupt
```

**Comment by auvipy** [comment]
closing in favor of https://github.com/celery/celery/issues/2672 lets continue there

**Comment by keaneokelley** [comment]
In #2672, it sounds like the issue was sporadic; it happens for me every single time.

**Comment by auvipy** [comment]
so you are facing quite different problem?

**Comment by keaneokelley** [comment]
Yes and no; I am using `get()` with the underlying call to `join_native()`, while the other issue uses `join()`, if that makes a difference. Both issues lead to the code blocking, but my issue happens every time instead of every 1/10 times

**Comment by arossert** [comment]
I'm facing the same issue with `get()` hangs forever after all jobs have finished.
Is there any workaround other than giving a timeout and catch the exception?

**Comment by georgepsarakis** [comment]
@arossert @keaneokelley may I ask why are you not using [Groups](http://docs.celeryproject.org/en/latest/userguide/canvas.html#groups) or a Chord to achieve the same workflow?

Also, why are you manually updating the state of the task using `Task.update_state`? I am not sure if this the intended use.

**Comment by keaneokelley** [comment]
@georgepsarakis I ended up going with Groups a while ago, as it matches my use case. But I didn't understand why the documentation existed for my original attempt, yet it was broken.

Using `update_state` like that is straight out of the docs.

**Comment by georgepsarakis** [comment]
I found two references of `update_state` in the `docs`:
1. http://docs.celeryproject.org/en/latest/userguide/calling.html#on-message
2. http://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-states
It turns out that you can define a custom state, I don't think that the issue was there, but instead I am not sure you can use `ResultSet` to replicate Group behavior (which by the way works as expected, as you correctly pointed out). I think we can close this now, if your issue is resolved.

**Comment by arossert** [comment]
@geoffreybauduin actually my use case is a bit different, I want to send multiple tasks and get notified every time a task is ended or sends an "update_state" message so I'm using the `get(on_message)` property.

**Comment by geoffreybauduin** [comment]
@arossert you meant to mention @georgepsarakis

**Comment by arossert** [comment]
@georgepsarakis thanks, I will try

**Comment by georgepsarakis** [comment]
Closing for now but feel free to re-open, if you have further feedback.
