### ISSUE TITLE
duplicate task in each work.

### ISSUE THREAD

**Issue by MYMhaly** [celery/celery#4487]
## Checklist
celery 4.1.0 (latentcall)

i found celery workers get duplicate tasks . the workers will get the same task.

## Steps to reproduce
the details can be found at (#3270 ), totally the same.
and i found that the same problem issued in 2012, lasts for 5 years?

and config below does not work.
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}

**Comment by auvipy** [comment]
i have reopened that issue. lets discuss there for fix

**Comment by einverne** [comment]
I am using https://github.com/cameronmaske/celery-once to prevent task run multiple times
