### ISSUE TITLE
launching worker from python: error with configuration from object.

### ISSUE THREAD

**Issue by Kurara** [celery/celery#4488]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Version celery: 4.1.0 (latentcall)

I'm trying to launch a worker from python code. When I use the class CeleryCommand with 'worker' option, it works. But if I add the option '--detach' or 'multi' the broker configuration is wrong. The code is:

```
app.config_from_object(config_module)
celerycmd = CeleryCommand(app)
celerycmd.execute_from_commandline(argv=[prog_name, 'worker', 'app_name', pidfile, logfile, loglevel])
```
or (which is not working)

`celerycmd.execute_from_commandline(argv=[prog_name, 'multi', 'start', 'app_name', pidfile, logfile, loglevel])`

# Expected behavior
Get the same broker as in the configuration, not the default one

## Actual behavior

log_file:

```
[2018-01-15 15:08:58,471: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-15 15:08:58,506: INFO/MainProcess] mingle: searching for neighbors
[2018-01-15 15:08:59,647: INFO/MainProcess] mingle: all alone
[2018-01-15 15:08:59,672: INFO/MainProcess] app_name@hostname ready.
```

FYI: I'm using lower case configuration. 

I could provide you what the object has in debug mode. Just ask me and I post it. When I debugged, I think the 'app' had the configuration of the file when it was inside the function _execute_from_commandline_, I can't understand when it loses it.

I tought that maybe the problem is that I don't provide the configuration at the begining of the file, where app is declared, but in a function. So I tested to add the broker directly when I create the app: 
`app = Celery('app_name', broker_url='broker@...')`
but it didn't work either.

**Comment by auvipy** [comment]
could you verify this is an issue of celery itself sing the newer version?
