### ISSUE TITLE
[BUG] ready() always returns False for groups

### ISSUE THREAD

**Issue by xunto** [celery/celery#4491]
## Steps to reproduce

```python
sent = group(
    celery_app.signature('task1', args=arg),
    celery_app.signature('task2', args=arg),
    celery_app.signature('task3', args=arg)
).apply_async()

while not sent.ready():
    pass

print("test")
```

## Expected behavior
I expect ```ready()``` to return ```True``` when all tasks are finished.

## Actual behavior
Looks like this code will never finish execution as ```ready()``` always return ```False``` even if all tasks are finished. Tested on celery master branch.

**Comment by auvipy** [comment]
version of celery and broker?

**Comment by xunto** [comment]
@auvipy as I said ```Tested on celery master branch.``` and ```RabbitMq 3.7.2 Erlang 20.1.7```

**Comment by auvipy** [comment]
master from github or pip install?

**Comment by auvipy** [comment]
do you find any open or closed issue similar https://github.com/celery/celery/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Canvas%22

**Comment by xunto** [comment]
@auvipy not sure but doesn't seem so. From my pont of view - no.
