### ISSUE TITLE
celery quit immediately after starting

### ISSUE THREAD

**Issue by me115** [celery/celery#4495]
I use celery in django.  when I start the debug consumer process,  it quit immediately after starting.

my input command:
`celery -A common worker --loglevel=DEBUG`
ps: common is my module name

output shows:

> celery -A common worker --loglevel=DEBUG
>  
>  -------------- celery@n6-026-137 v4.0.2 (latentcall)
> ---- **** ----- 
> --- * ***  * -- Linux-4.4.0-33.bm.1-amd64-x86_64-with-debian-8.8 2018-01-22 22:47:51
> -- * - **** --- 
> - ** ---------- [config]
> - ** ---------- .> app:         common:0x7f1029bc6590
> - ** ---------- .> transport:   redis://10.14.23.45:3907/0
> - ** ---------- .> results:     disabled://
> - *** --- * --- .> concurrency: 32 (prefork)
> -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
> --- ***** ----- 
>  -------------- [queues]
>                 .> default_queue    exchange=cap_exchange(topic) key=default
>                 .> workflow_queue   exchange=cap_exchange(topic) key=workflow
> 
> [tasks]
>   . celery.accumulate
>   . celery.backend_cleanup
>   . celery.chain
>   . celery.chord
>   . celery.chord_unlock
>   . celery.chunks
>   . celery.group
>   . celery.map
>   . celery.starmap
>   . common.celery.debug_task
>   . workflow_task
> 
> [2018-01-22 22:47:52,873: INFO/MainProcess] Connected to redis://10.14.23.45:3907/0
> [2018-01-22 22:47:52,878: INFO/MainProcess] mingle: searching for neighbors
> [2018-01-22 22:47:53,890: INFO/MainProcess] mingle: all alone
> **[2018-01-22 22:47:53,905: DEBUG/MainProcess] Canceling task consumer...**
> [2018-01-22 22:47:54,946: DEBUG/MainProcess] Canceling task consumer...
> [2018-01-22 22:47:54,946: DEBUG/MainProcess] Closing consumer channel...
> [2018-01-22 22:47:54,947: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
> 

here you see,  after connected to redis broken. it quit immediaterly without any log.

my  project dir:
workdir/
.............../manage.py  (django manage.py file)
............../common/celery.py
............../common/settings.py (include celery.py)

celery.py 's content:
```
from __future__ import unicode_literals, print_function, absolute_import
import sys
import os
from celery import Celery
import logging

reload(sys)
sys.setdefaultencoding('utf-8')

logger = logging.getLogger('celery')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'common.settings')
app = Celery('common')
app.config_from_object('django.conf:settings')
app.autodiscover_tasks()


@app.task(bind=True)
def debug_task(self):
    logger.error("!!!Debug Task!!!")
    logger.debug('Requests:{0!r}'.format(self.request))
```

## Checklist
software -> celery:4.0.2 (latentcall) kombu:4.1.0 py:2.7.9
              billiard:3.5.0.3 redis:2.10.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

**Comment by me115** [comment]
resolved: 
It's because I used an old redis lib. kombu call redis use function 
 def can_read(self, timeout=0):                                                     
but the older version only has can_read() without any params.

**Comment by theakshashetty** [comment]
Hi,
Can you please tell which version of redis you have used?

**Comment by Egregors** [comment]
The same problem.
python 3.6.6
celery==4.2.1
redis==2.10.6

**Comment by maomorales** [comment]
Our team recently faced a similar problem and it was because the new redis version (3.0) is not backwards compatible; just in case this helps someone facing a similar issue. Make sure you use redis==2.10.6

**Comment by nadavperetz** [comment]
I solved the problem rolling back to redis==2.10.6! 

Python 3.4
Celery==4.2.1
redis==2.10.6

(@maomorales really thanks, I was going crazy!)

**Comment by MrLokans** [comment]
The same problem is with Celery 4.2.1. Celery worker just stops working with redis==3.2

**Comment by hassanselim0** [comment]
I've had the same problem, I already had `redis==2.10.6`, but my problem turned out to be with `kombu`!
Version `2.3.0` worked, but anything higher failed.

**Comment by matthewhegarty** [comment]
I had this issue when using SQS.  For me the fix was to ensure that [pycurl](http://pycurl.io/) was installed as a dependency (in my pipenv file).

**Comment by alex-verve** [comment]
I've had similar problem with pycurl installed.
However when I tried to import it there was a problem as blow

```
Python 3.7.9 (default, Aug 18 2020, 11:14:44) 
[GCC 7.5.0] on linux
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: python/lib/python3.7/site-packages/pycurl.cpython-37m-x86_64-linux-gnu.so: undefined symbol: GSS_C_NT_HOSTBASED_SERVICE
``` 

After upgrading python version to 3.7.10 ImportError gone.
