### ISSUE TITLE
Celery hangs with .s() in @on_after_configure/@on_after_finalize

### ISSUE THREAD

**Issue by rob-deutsch** [celery/celery#4497]
## Environment

```
$ celery -A proj report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.4
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:db+sqlite:///results.sqlite
```
```
$ pip show django
Name: Django
Version: 2.0
```

## Steps to reproduce
Note: This is a simplified example. In reality I'm trying to create some periodic tasks, and that's not working. I believe its not working because `add.s()` hangs indefinitely, and this is the simplest replicating example that I can come up with.

1. Copy the [Celery django example](https://github.com/celery/celery/tree/master/examples/django) and **confirm that it works as expexted**.
2. In proj/celery.py add the following lines and note that the same thing happens with `@app.on_after_configure.connect`. See rob-deutsch/celery-example-django@b1dc80b67b207d71d0f1c15f76da99ef02a41ba6 .
```
@app.on_after_finalize.connect
def setup_periodic_tasks(sender, **kwargs):
    print("Attempting to print add.s()")
    print(add.s(2,2))
    print("Printed add.s()")
```
3. Fire up a shell and try to run `add.delay(2,2)`. This was the explicit command used:
```
$ python manage.py shell -c "from demoapp.tasks import add;a = add.delay(2,2)"
```

## Expected behavior
Program should terminate normally. `a` will contain the relevant object.

## Actual behavior
Program prints `Attempted to print add.s()` and hangs for at least 10 minutes. On Ctrl-C it prints numerous amounts of error text which can be seen in output.txt of rob-deutsch/celery-example-django@b1dc80b67b207d71d0f1c15f76da99ef02a41ba6 .

**Comment by auvipy** [comment]
try the latest release and report again.
