### ISSUE TITLE
How to execute task registered on the other host

### ISSUE THREAD

**Issue by Joukosucl** [celery/celery#4502]
env:  python2.5 + celery4.1 + rabbitmq 3.7.2 + redis 3.2.8

I test the function send_task and found it can't execute the task on the other host
e.g.
 host A:   task plus -> bind queue normal_queue -> bind exchange normal_exchange
 host B:   task minus -> bind queue abnormal_queue -> bind exchange abnormal_exchage

execute `send_task('plus', args=(12,3))` on host B,  but message was sent to default queue, and `send_task('minus', args(12,3))` worked on host B. 

 checked the message in rabbitmq below,  some parameter isn't right . should i must define task `plus` or related things on host B??

![image](https://user-images.githubusercontent.com/20793539/35373682-91043326-01da-11e8-96bd-c89ec541f8c9.png)

`test code attached`
[code.zip](https://github.com/celery/celery/files/1662737/code.zip)

**Comment by Joukosucl** [comment]
i tried with python3.6 and also like this

**Comment by bpereto** [comment]
You have to define the queue, in which your task should go. If you don't specify, it goes as its defined in your routing settings or the default queue.

`send_task('plus', args=(12,3), queue='normal_queue)`

Here is more information:
http://docs.celeryproject.org/en/latest/userguide/routing.html
