### ISSUE TITLE
rdb breakpoint not logged

### ISSUE THREAD

**Issue by adelavega** [celery/celery#4506]
## Checklist

- [ X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.0
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/0

broker_url: 'redis://redis:6379/0'
result_backend: 'redis://redis:6379/0'
include: ['tasks']

```

- [ X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I'm trying to interactively debug using `rdb.set_trace()` in my task. I set the trace point, trigger the task, and check the logs. Note that I am running in Docker as root (this may be a problem?).

## Expected behavior
Logging of which port to telnet into.
## Actual behavior
The logging pauses at the breakpoint, but no information about which port to telnet into is given. Thus, I am unable to jump into rdb, even though the breakpoint is effectively being triggered.

**Comment by tofay** [comment]
@adelavega I hit the same problem using celery in a docker and resolved it by setting the [PYTHONUNBUFFERED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED) environment variable to a non-empty string in the container running celery. There's an explanation https://stackoverflow.com/questions/23524976/capturing-output-of-python-script-run-inside-a-docker-container
