### ISSUE TITLE
Please make a new release to pypi!

### ISSUE THREAD

**Issue by wonderbeyond** [celery/celery#4507]
Half a year has passed since [pr#4173](https://github.com/celery/celery/pull/4173) been merged, which fixed a critical bug about timezone.

I have always been installing celery via:

```shell
$ pip install -e git+https://github.com/celery/celery.git@bd347f7565f3a72c8cfb686ea0bfe38cfa76e09b#egg=celery
```

However, since I switched to *Pipenv*, a new problems arise: After I execute:

```
$ pipenv install git+https://github.com/celery/celery.git@bd347f7565f3a72c8cfb686ea0bfe38cfa76e09b#egg=celery
```

I did get an entry in Pipfile like below:

```
celery = {ref = "bd347f7565f3a72c8cfb686ea0bfe38cfa76e09b", git = "https://github.com/celery/celery.git"}
```

But got below in Pipfile.lock (without the github link):

```
        "celery": {
            "hashes": [
                "sha256:81a67f0d53a688ec2bc8557bd5d6d7218f925a6f2e6df80e01560de9e28997ec",
                "sha256:77ff3730198d6a17b3c1f05579ebe570b579efb35f6d7e13dba3b1368d068b35"
            ],
            "version": "==4.1.0"
        },
```

---

**Please make a new release to pypi!**

> @nooperpudd
> hopefully release this pull request as soon as possible.

> @ldsink
> This PR solve our problems. Please release a fix version for 4.1.x series as soon as possible.

> @pieterdd
> Any chance of a 4.1.1 hotfix release happening? We recently upgraded from v4.0.2 to v4.1, thinking a minor version release from two months ago would have been a safe upgrade. But due to our reliance on crontab for some of our periodic tasks, this is impacting us.

> @jobec
> We downgraded to v4.0.2 because of this issue...

> @jobec
> Any chance of releasing a new version for this any time soon?

> @auvipy
> yes version 4.2 is due in January 2018

Why???

**Comment by sfdye** [comment]
+1 for new release

**Comment by thedrow** [comment]
Please avoid creating such issues. Follow #4387 for updates.
