### ISSUE TITLE
It is possible to use celery for infinity loop tasks ?

### ISSUE THREAD

**Issue by Maximilan4** [celery/celery#4512]
Just a question, because i cant find at stackoverflow and etc.
I  have a system, that must manage some bots (simple start|stop). I created one task, what should run an infinity process. For single instance it works fine, task starts and stops in web interface. But when i am trying to create new bot instance (same infinity task with another params), celery has one of next behaviors:
- new task cant run (I think because celery hasn`t single workers)
- new task runs, but previous stops

So, can i realize this case using celery, and if i can - in which way?
I am using celery 3.1.25, rabbitmq for broker, but without any queues (not needed now).
Run it by command :
> celery -A src  worker -l info

Thanks for any help.

**Comment by georgepsarakis** [comment]
Your use case does not seem like a task queue, but more of a remote orchestration. You should configure your application to run as daemon (depending on your OS) and I would suggest [Fabric](http://www.fabfile.org/) as a solution to remote management.

**Comment by Maximilan4** [comment]
@georgepsarakis , thanks for your asnwer. My problem was in concurrency param, on localhost i have default 4 child processes, but on prod version i have only one. I think you are right, and i needs to create system daemons. I also can run daemons in celery, but only a n-count, because one worker = one daemon process. The scalability problem.

**Comment by Sleeeepy7** [comment]
How to make infinite task if I need that ?
