### ISSUE TITLE
Emit some SIGNAL for the tasks that are present in the chain after a failed task. 

### ISSUE THREAD

**Issue by rachit1010** [celery/celery#4515]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

celery -A celeryapp.tasks report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:db+postgresql://celery:**@localhost/celery

CELERY_TASK_DEFAULT_EXCHANGE: 'celery_dev'
sys: <module 'sys' (built-in)>
CELERYD_CONCURRENCY: '1'
CELERY_ROUTES: {
    'celeryapp.tasks.*': {   'queue': 'celery_dev'}}
CELERYD_LOG_FILE: '/log-dir/logs'
BROKER_URL: u'amqp://guest:********@localhost:5672//'
os: <module 'os' from '/Users/dummy_user/anaconda2/lib/python2.7/os.pyc'>
CELERY_RESULT_BACKEND: u'db+postgresql://celery:********@localhost/celery'

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1. Create a chain of 6 tasks. 
Let's say: chain(sum.si(4,4),sum.si(2,2),error_raising_task.si(a,b),sum.si(4,4),sum.si(5,5),sum.si(6,6))
2. For 3rd task if failure has happened then we will receive signals only for 1st, 2nd and 3rd tasks but no signal for 4th, 5th, 6th tasks indicating they they will not be run.

## Expected behavior
Since the task IDs get generated for all the tasks that are mentioned in the chain when we submit a chain so emit some kind of signal that can be listened like other signals mentioned here --> http://docs.celeryproject.org/en/master/userguide/signals.html 

## Actual behavior
No signals are emitted for tasks that are present after a failed task in the chain.

**Comment by rachit1010** [comment]
Can someone check on this one?

**Comment by auvipy** [comment]
whats the current status on celery 4.3 or master?
