### ISSUE TITLE
AsyncResult loses .parent when being retrieved via AsyncResult(<id>)

### ISSUE THREAD

**Issue by SaintSimmo** [celery/celery#4516]
So my ultimate goal here is to kick off a `Chord` (start with many parallel tasks, once they complete callback to another task with their results). This is easy, but my issue relates to getting the status of the tasks in the `Group`.

The issue is my `AsyncTask` returned from the `Chord` loses it's .parent attribute when recalled via `celery.results.AsyncTask()` (when I want to check the Chord's status)

## Celery info

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/
```

## Steps to reproduce

```python
from celery import group, chord

callback = tsum.s()
group_tasks = group([
    add.s(5,5),
    subtract.s(20,10),
    multiply.s(2,5)
])
task = chord(group_tasks)(callback)
task.id
task.parent
task.parent.children
```

```
>>> 2303c00d-50b3-4c01-bf44-3d2aea741f19
>>> <GroupResult: f7991cea-03ce-4467-9a65-4b3331c6f66a [5790dcc1-df60-4ce2-ab2f-8b649d99d9d3, 93d1cef3-1123-4272-8f3b-fc6e4397ad03, 7386ad7b-4e02-409c-a241-6ca6de1edf15]>
>>> [<AsyncResult: 5790dcc1-df60-4ce2-ab2f-8b649d99d9d3>, <AsyncResult: 93d1cef3-1123-4272-8f3b-fc6e4397ad03>, <AsyncResult: 7386ad7b-4e02-409c-a241-6ca6de1edf15>]
```

## Expected behavior

```python
from celery.result import AsyncResult

task = AsyncResult('2303c00d-50b3-4c01-bf44-3d2aea741f19')
task.parent
```

```
>>> <GroupResult: f7991cea-03ce-4467-9a65-4b3331c6f66a [5790dcc1-df60-4ce2-ab2f-8b649d99d9d3, 93d1cef3-1123-4272-8f3b-fc6e4397ad03, 7386ad7b-4e02-409c-a241-6ca6de1edf15]>
```

## Actual behavior

```python
from celery.result import AsyncResult

task = AsyncResult('2303c00d-50b3-4c01-bf44-3d2aea741f19')
task.parent
```
```
>>> None
```

So as you see I need the `GroupResult` that's expected from `task.parent` so I can iterate over them and get their statuses, but it's `None` when I try to get it again by its ID. I see that I have the option to pass in a `parent` as a keyword argument to `AsyncResult()` but I tried that as well with the correct GroupResult id but that didn't work for me... the documentation there isn't super clear.

I may be overcomplicating this. Ultimately, I want to kick off a `Chord` and then call something (my own function) that will give me insight into the `Chord` and the status of all of its subtasks in the `Group`. If there's a better way to do that I'm all ears!

I'm also aware of serializing the result with `as_tuple` and `result_from_tuple`, but this is a web application and I want to recall the Chord with a single ID, if possible.

**Comment by SaintSimmo** [comment]
Well in classic fashion I spent all day failing, decided to ask people smarter than me, then figured out the answer just a few minutes later. Couple things I was doing wrong, for anyone in the future with the same problem. Here's what the good code should look like:

```python
from celery import group, chord

callback = tsum.s()
group_tasks = group([
    add.s(5,5),
    subtract.s(20,10),
    multiply.s(2,5)
])
task = chord(group_tasks)(callback)
task.parent.save()
task.id
task.parent
task.parent.children
```

```
>>> 2303c00d-50b3-4c01-bf44-3d2aea741f19
>>> <GroupResult: f7991cea-03ce-4467-9a65-4b3331c6f66a [5790dcc1-df60-4ce2-ab2f-8b649d99d9d3, 93d1cef3-1123-4272-8f3b-fc6e4397ad03, 7386ad7b-4e02-409c-a241-6ca6de1edf15]>
>>> [<AsyncResult: 5790dcc1-df60-4ce2-ab2f-8b649d99d9d3>, <AsyncResult: 93d1cef3-1123-4272-8f3b-fc6e4397ad03>, <AsyncResult: 7386ad7b-4e02-409c-a241-6ca6de1edf15>]
```

```python
from app import celery_app # my celery instance in my app

parent = celery_app.GroupResult.restore('f7991cea-03ce-4467-9a65-4b3331c6f66a')
task = celery_app.AsyncResult('2303c00d-50b3-4c01-bf44-3d2aea741f19', parent=parent)
task.parent
```

```
>>> <GroupResult: f7991cea-03ce-4467-9a65-4b3331c6f66a [5790dcc1-df60-4ce2-ab2f-8b649d99d9d3, 93d1cef3-1123-4272-8f3b-fc6e4397ad03, 7386ad7b-4e02-409c-a241-6ca6de1edf15]>
```

So first thing is I had to use the `save()` and `restore()` function of the `GroupResult`, the parent of the `AsyncResult` returned from the Chord (which is actually just the result of the callback task).

Other thing was I had to use the `AsyncResult()` and `GroupResult()` from my instance with the backend already loaded.

**Comment by radusuciu** [comment]
Thank you for this. I had a similar problem but with chained tasks instead. There, the best solution for re-populating the parent tree of an `AsyncResult` seems to require something like this:

```python
from celery import chain
import json

result = chain(
    add.s(1,2), multiple(4, 7)
).apply_async()

# the resulting tuple can be further serialized and stored if necessary
res = result.as_tuple()

# serialization with json module
serialized = json.dumps(res)
```

then, at a later point you may de-serialize like so:

```python
from celery.result import result_from_tuple
import json

serialized = get_from_somewhere_else_like_maybe_your_database()

# rehydrated_res will have parents hopefully
rehydrated_res = result_from_tuple(json.loads(serialized)
```

**Comment by itayB** [comment]
I guys,
I'm having the same problem.
There must be another way to achieve that.
Let's say I want to build some monitor tool like flower.
I cannot add the `save` (or dump to db) because I don't have access to the canvas flow.
flower (for example) shows the parent id and the root id of each task.
How does it happen?

**Comment by jtallieu** [comment]
> I guys,
> I'm having the same problem.
> There must be another way to achieve that.
> Let's say I want to build some monitor tool like flower.
> I cannot add the `save` (or dump to db) because I don't have access to the canvas flow.
> flower (for example) shows the parent id and the root id of each task.
> How does it happen?

I believe Flower is able to maintain the flow by observing events.  If Flower were down when the flow was created and executing, I bet it would be just as incomplete.

**Comment by coltonbh** [comment]
[This answer on SO](https://stackoverflow.com/a/71713239/5728276) provides a basic implementation of what @radusuciu mentioned above for saving results to the DB and rehydrating them later.
