### ISSUE TITLE
Time Zone detection issue

### ISSUE THREAD

**Issue by last-partizan** [celery/celery#4517]
https://github.com/celery/celery/blob/35fd2d0096cf10d106836ba03819d2e50173b3b4/celery/app/base.py#L1253

```
        tz = conf.timezone or 'UTC'
        if not tz:
            if conf.enable_utc:
                return timezone.get_timezone('UTC')
            else:
                if not conf.timezone:
                    return timezone.local
        return timezone.get_timezone(tz)
```

Here is timezone detection code, and looks like most of it never actually used.
`tz` will be actual time zone or 'UTC' if conf.timezone is None, so `if not tz` never happens.

**Comment by auvipy** [comment]
could you send a pr?

**Comment by auvipy** [comment]
could you send a pr?

**Comment by last-partizan** [comment]
Yes, i'll fix it.

**Comment by last-partizan** [comment]
I'm looking at tests for this part of code; and it looks like tests ignoring enable_utc completely;

https://github.com/celery/celery/blob/eac96241d2f4d4d2dfe21c071537431518e01718/t/unit/app/test_app.py#L827

Am I right, if enable_utc is False celery must use timezone.local? and utc only if enable_utc is True?

**Comment by auvipy** [comment]
@georgepsarakis
