### ISSUE TITLE
Feature request: configurable max_retries and back-off strategy for database backend

### ISSUE THREAD

**Issue by MShekow** [celery/celery#4518]
Suppose you configure your workers to store results in a database backend, e.g. a MySQL database. Suppose this database is down for a few minutes for maintenance. Currently, this results in completely loss of the work done in these tasks, which is highly annoying (suppose that one task takes 3 hours to compute, i.e. the result is very valuable, and I would like to be able to retry putting the result into the DB for 3-4 minutes, retrying 4 times, once per minute).

My code analysis shows that in `celery.backends.database.__init__.py` the `_store_result()` method uses the vanilla `@retry` decorator (without any arguments). Consequently, the default value of maximum retries is 3 (see `max_retries = kwargs.pop('max_retries', 3)`). What's worse, these 3 attempts are done in very quick succession, making the retry operation almost useless in situations where the DB is not reachable for more than a few seconds.

It would be nice to have a configuration option for database backends that allows to configure this.

**Comment by georgepsarakis** [comment]
@MShekow this will be resolved by the exponential backoff feature that is already included in the `master` branch and will be available with the release of 4.2.0 . For details see [here](https://github.com/celery/celery/pull/4101).
