### ISSUE TITLE
daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by FurqanKhan1** [celery/celery#4525]
I have seen this issue reported before as well ,and apparently it was fixed with 3.11 release of celery .But in the later realizes the issue again persisted.I have a current set-up of pyuthon3.6 ,Django 1.11,rabbit-mq ,Cent-os ,and i have a requirement to make the task allow / run pythons conventional multiprocessing.

I just want to seek clarification on weather is the issue fixed ,as i have celery 4.1.0 (latentcall) ,but the issue still seems to persist.

If its not fixed / or is likely not to have a workaround (because of running in the chance of having orphaned processes ) ,kindly let me know over it as well!!!

Thanks

**Comment by georgepsarakis** [comment]
Could you please show an outline of what you are trying to achieve in your task? Some sample code would be nice.

**Comment by trianglesis** [comment]
Had the same with multiproc.
Unfortunately I can't found any solution for this and just make "threading" as multiplying tasks for each "thread" I wanted.
I have now just single worker with concurrency 5 - which run 1000+ task more like in "parallel".
And other 5 workers for each single environment with concurrency 1, and I just fed each worker with set of tasks (tests) which also run in like "parallel".

So, you can try to change code design to achieve this "hack" =)

**Comment by FurqanKhan1** [comment]
I actually ended up using billiard library of python which does allow demonic processes to have child processes and its just working good
U might want to give a look at billiard ,doesn't require much code change as well. 
https://pypi.python.org/pypi/billiard

Appreciate your input tough !!

**Comment by yyyyuan** [comment]
I agree with @FurqanKhan1 , using billiard instead of multiprocess can solve this problem perfectly. Billiard is a module of the multiprocess and it also has Process module instead, so you can use billiard instead of multiprocess in the script.

**Comment by flamby** [comment]
Celery 4.4.0 with threads (`celery worker -P threads`) solved the issue for me.

**Comment by auvipy** [comment]
thanks

**Comment by hoseiniehsan** [comment]
> Hi @georgepsarakis ,
> So what i am trying to achieve is something like as under
> 
> @shared_task
> def process_me():
> 
> ```
>         ``` 
>          cpu_cores=multiprocessing.cpu_count()   
> 
>          process_list=[]          
> 
>          for i in range(0,cpu_cores):
>                p=multiprocessing.Process(target=my_task,args=(x,y,z))
>                process_list.append(p)
>         for pr in process_list:
>                pr.start()
>                pr.join()
>         ```
> ```
> 
> def my_task(arg1,agr2,arg3):
> 
> ```
>     `Process_heavy_task()`
> ```
> 
> Now i know the same can be achieved by taking the initial task request on queue : Q1 ,and from the method process_me ,i can put the task on other queue :Q2 polled by 'n' workers ,as my cpu cores and they can all process in parallel.
> 
> I did not want to change the structure of the code ,so came across a library billiard ,this one apparently allows the task to create sub processes ,but i am not sure if there is anything that i am missing here .
> 
> What would be your take on this
> 
> Thanks
> Furqan
You can use it easily as below (add daemon flag):
p=multiprocessing.Process(target=my_task,args=(x,y,z), daemon=False)
It will let you use 'Nested' multiprocessing

**Comment by kaustubhd93** [comment]
> I actually ended up using billiard library of python which does allow demonic processes to have child processes and its just working good
> U might want to give a look at billiard ,doesn't require much code change as well.
> https://pypi.python.org/pypi/billiard
> 
> Appreciate your input tough !!

@FurqanKhan1 and @yyyyuan I also used billiard instead of multiprocessing and it worked for me. Thanks for posting this issue and your findings.

**Comment by veerendrapolepalli** [comment]
> Celery 4.4.0 with threads (`celery worker -P threads`) solved the issue for me.

But we are not able to abort the celery task if we enable -P threads

**Comment by kayuzee** [comment]
> Celery 4.4.0 with threads (`celery worker -P threads`) solved the issue for me.

Omg genius! Worked for me after pulling my hair out!

**Comment by JonnyWaffles** [comment]
Hi team, apologies for bringing this back from the dead, just want to check my understanding. Is multiprocessing not supported within Celery Tasks? I have an Airflow cluster using Celery 5.2.7 where a third party dependency is creating a `multiprocessing.Manager()`, thus crashing with the 
> AssertionError: daemonic processes are not allowed to have children
A simple test throws the same
```python
from celery import Celery
import multiprocessing

app = Celery('demo', backend='rpc://', broker='redis://redis:6379/2')


@app.task
def mtest():
    multiprocessing.Manager()
```
Is this the expected behavior? Is it possible for me to run my Celery workers as non-daemonic processes? I'd rather not monkey patch my third party dependency to use Billiard if I can avoid it. Thank you for your assistance.

**Comment by JonnyWaffles** [comment]
Additionally, I'm confused regarding `billiard`. If Celery uses `billiard`, would it not be expected that `billiard` has already monkey patched `multiprocessing`? It's confusing because in the billiard documentation they refer to the `multiprocessing` namespace, not their own. When the Celery Task Worker process executes the task, should I expect multiprocessing to be monkey patched by billiard and then my third party's usage of multiprocessing to just work?

**Comment by sminnee** [comment]
> Hi team, apologies for bringing this back from the dead, just want to check my understanding. Is multiprocessing not supported within Celery Tasks?

The default pool option of Celery is "prefork", which doesn't support multiprocessing. In particular, it already uses multiprocessing itself to create daemon processes, and you can't do that a second time.

However, other pool options for Celery such as "threads" *do* support multiprocessing.
