### ISSUE TITLE
How to route a Message to multiple Tasks with RabbitMQ Exchanges in Celery?

### ISSUE THREAD

**Issue by capital-G** [celery/celery#4530]
I use celery with django right now, but as my project gets bigger I really have a problem with routing messages the way I want to.

As I was reading the RabbitMQ documentation I found the concept of Exchanges really intresting as seen [here](https://www.rabbitmq.com/tutorials/tutorial-three-python.html).

Celery also mentions the distribution-capabilites of Exchanges in the documentation http://docs.celeryproject.org/en/latest/userguide/routing.html#exchanges-queues-and-routing-keys but and gives an example in celery amqp, but it never describes how I can send a message to multiple tasks (aka how to create an Exchange, bind multiple Queues to this Exchange and let Consumers consume the queues).

After I couldn't find how to do this with Celery I decided to go "deeper" with kombu, so I wrote

    def test_message(message):
        exchange = kombu.Exchange('test_exchange', channel=app.connection())
        exchange.declare()
        producer = kombu.Producer(channel=app.connection(), exchange=exchange, routing_key='test.message')
        producer.publish(body=message, serializer='json')

into `my_proj/my_proj/celery.py` where `app` is the Celery object. I bound the queue `test_queue` to consume from `test_exchange` via `queue = kombu.Queue('test_queue', channel=app.connection(), exchange='test_exchange')` and bound an task to this queue with

    @app.task(queue='test_queue', key='test.message', bind=True)
    def receive_message(self, msg):
        print(msg)
        return msg

Now I can send a message to a Queue which is bound to a task in Celery, but the worker (which is now also set to listen to the Queue `test_queue`) fails to recognize what to do with this task

    [2018-02-07 15:03:54,504: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?
    
    The full contents of the message body was: body: '{"content:"hello_world"}' (29b)
    {content_type:'application/json' content_encoding:'utf-8'
    delivery_info:{'consumer_tag': 'None4', 'delivery_tag': 7, 'redelivered': False, 'exchange': 'text_exchange', 'routing_key': 'test.message'} headers={}}

I took a look at the payload of a Celery-Message in RabbitMQ and saw that always a "task" is set which is a real bummer because this means that I can't use Exchanges. Or did I went somewhere wrong?

**Comment by thulasi-ram** [comment]
@capital-G ,

Let me know if I'm being helpful here. I didn't exactly get the Publishing part.

For the consumer part:
you can look into this: http://docs.celeryproject.org/en/latest/userguide/extending.html#custom-message-consumers

our scenario: A 3rd party team used to broadcast messages. We needed this message to be broadcasted again. So we set up a shovel from one 3rd party rmq system to our rmq system and routed this message on to a topic exchange and had multiple queues connecting to them. Different business logic needs to happen for different queues but celery identifies a task to be executed based on either `task` argument on headers / payload of a message. Initially we wrote our own consumer implementation of Kombu ConsumerMixin later found this: http://docs.celeryproject.org/en/latest/userguide/extending.html#custom-message-consumers

```
from celery import Celery, bootsteps
from kombu import Consumer, Queue

app = Celery('<our application>')

class MyConsumerStep(bootsteps.ConsumerStep):

    def get_consumers(self, channel):
        return [Consumer(channel,
                         queues=[Queue('test_a')],
                         callbacks=[self.handle_message],
                         accept=['json'])]

    def handle_message(self, body, message):
        print('Received message: {0!r}'.format(body))
        message.ack()

app.steps['consumer'].add(MyConsumerStep)
```
