### ISSUE TITLE
Worker prefetching tasks even after setting acks_late=True, worker_prefetch_multiplier=1 and -Ofair

### ISSUE THREAD

**Issue by chraj007** [celery/celery#4537]
## Checklist
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.4
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://localhost:6379/0'
include: ['dh_celery.task_setup']
CELERY_TASK_ACKS_LATE: True
worker_prefetch_multiplier: 1

## Steps to reproduce
1. Push 20 tasks into Redis queue
2. Start the worker with concurrency=2
3. Worker always emptying the queue
4. Stop worker without process completion of any task
5. Its only requeuing 1 task (that to into celery default queue)

**Comment by vlcinsky** [comment]
I have similar needs (cca 30-seconds tasks, multiple servers, need to distribute tasks evenly) and I succeeded.

my `celeryconfig.py` file contains:
```
broker_url = 'redis://localhost/1'
imports = ("tasks", )
worker_prefetch_multiplier = 1
task_acks_late = True
worker_redirect_stdouts_level = "INFO"
worker_send_task_events = True
```

and my code is using something like:
```
import celery
app = celery.Celery()
app.config_from_object("celeryconfig")
```

From your descriptions it seems that you are using obsolete configuration value name `CELERY_TASK_ACK_LATE` and it shall read `task_acks_late`.

My setup was tested with 3 workers, each with concurency 4 (default derived from number of cores).

starting the first one ```$ celery worker -n alfa -l INFO``` shows, 4 tasks are started, starting second one ```$ celery worker -n beta -l INFO``` consumes next 4 tasks and third one ```$ celery worker -n beta -l INFO``` gets another 4. Then the tasks are completed and next ones started, never prefetching more tasks, then can be actually run.

I did not play with `-Ofair`.

**Comment by auvipy** [comment]
whats the status of the issue with celery 4.2.1?

**Comment by x007007007** [comment]
I have same issue

**Comment by auvipy** [comment]
can you try 4.3rc1?

**Comment by thedrow** [comment]
Can anyone provide a test case for us to reproduce?
Does this behaviour happen with any task?

**Comment by pawel-furmaniak** [comment]
I am running version 4.3 and I am getting this issue. The workaround is to:

1. Configure late acknowledging directly in `Task` definition (either by defining class attribute `acks_late=True` or by passing `acks_late=True` to a decorator)
2. Configure prefetch multiplier directly in the invocation of the worker by passing `--prefetch-multiplier 1`

It seems that defining those parameters in a configuration file is ineffective.

**Comment by auvipy** [comment]
Can you open a PR with your suggested workaround? even in doc

**Comment by jsynowiec** [comment]
(2) Setting `--prefetch-multiplier 1` on worker process doesn't help. 

We're using celery mostly for long running tasks and there's no point in prefetching. In the past it seemed to work, but somewhere with recent updates workers are now fetching 1 additional task. Another `Received task:` log message can be seen some time after the first task starts, but it's not yet finished.

`celery[redis]==4.4.2` is configured with following settings:
```
CELERY_ACKS_LATE = False
CELERYD_MAX_TASKS_PER_CHILD = 1
CELERYD_PREFETCH_MULTIPLIER = 1
```

And workers are started with `--events -O fair --without-heartbeat --concurrency=1 --prefetch-multiplier=1` arguments.

I managed to verify that `Worker` and `Consumer` get `1` as multiplier value and set `1` as a value for `prefetch_count` parameter.

**Comment by zerog2k** [comment]
running into this also with long running tasks w/ acks_late=True, `-O fair` on celery worker invokation, and celery 4.3.0 / rabbitmq 3.7.23

is #5480 related?

**Comment by auvipy** [comment]
> running into this also with long running tasks w/ acks_late=True, `-O fair` on celery worker invokation, and celery 4.3.0 / rabbitmq 3.7.23
> 
> is #5480 related?

can you try with celery==4.4.x?

**Comment by zerog2k** [comment]
Ok, an update for our issue, seems to be a problem of our own creation.
We were adding an `eta` arg to `send_task`, and missed this key part of docs @ https://docs.celeryproject.org/en/latest/userguide/configuration.html#worker-prefetch-multiplier
>*Tasks with ETA/countdown aren’t affected by prefetch limits.*

**Comment by auvipy** [comment]
thanks!

**Comment by scythargon** [comment]
Hello folks!
Can someone please elaborate on what is the reason behind
>Tasks with ETA/countdown aren’t affected by prefetch limits.

And if I have tens of thousands of tasks with ETA - how do I avoid a long running prefetching every time my workers are restarted?

And what are even other task types except ETA/countdown? 

Thanks!

**Comment by fjsj** [comment]
@scythargon tasks with ETA and retries (which are ETA tasks, AFAIK) are kept in worker memory for execution when due. That's how it's implemented now: they are not kept on broker, that's why they can't be affected by prefetch limits. 

See the warning in [current docs](https://docs.celeryq.dev/en/stable/userguide/calling.html#eta-and-countdown):
> Tasks with eta or countdown are immediately fetched by the worker and until the scheduled time passes, they reside in the worker’s memory. When using those options to schedule lots of tasks for a distant future, those tasks may accumulate in the worker and make a significant impact on the RAM usage.

Related issues:
- https://github.com/celery/celery/issues/2541
- https://github.com/celery/celery/issues/8394
