### ISSUE TITLE
Celery Fails when trying to connect to a non-durable queue

### ISSUE THREAD

**Issue by infintesimal** [celery/celery#4538]
Project Report
```
(pg3) steve@julian-seahawks:~/pg3$ celery -A pg3 report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: 'amqp://guest:********@localhost:5672//'
task_default_queue: 'getting_started'
task_default_routing_key: '********'
task_always_eager: False
task_default_exchange_type: 'direct'
accept_content: ['json', 'application/json']

```
Hi all,
I have found a problem in addressing existing, non-durable queue. I am using RabbitMQ 3.7.3
Here's the scenario: I use either pika or RabbitMQ Admin to create a non-durable queue, in this case it is named 'getting started.' (Note in steps to reproduced, I have pasted in [my note to the celery users group ](https://groups.google.com/forum/#!topic/celery-users/IhKsCzRf6tY)on google forums). 
## Steps to reproduce
Hi,
I just started to play with both RabbitMQ and Celery, and I ran into a problem that seemed strange to me.
My setup is
Ubuntu 16.04
Python 3.6.4
Celery 4.1
RabbitMQ 3.7.3
 
I created a direct queue using pika (following pika docs):
```
import sys
import pika
connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()


channel.queue_declare(queue='getting_started')


channel.basic_publish(exchange='',
                      routing_key='steve_testing',
                      body=" ".join(sys.argv[1:]))
print(" [x] Sent ", " ".join(sys.argv[1:]))
```

I published messages to this queue (and simple receiver program echoed the message). The rabbitmq admin shows me that this queue is not durable (pika uses durable=False as default)

Now, when I tried to define my Celery app, I received the following (code first, then will show the error I received:
celery.py
```
from __future__ import absolute_import, unicode_literals
import os
import time
from kombu import Queue
from celery import Celery
from celery import shared_task
from celery.utils.log import get_task_logger

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pg3.settings')

app = Celery('pg3')

app.conf.broker_url = 'amqp://localhost:5672'
app.conf.task_default_queue = 'getting_started'
app.conf.task_default_routing_key = 'getting_started'
app.conf.task_always_eager = False
app.conf.task_default_exchange_type = 'direct'
app.conf.accept_content = ['json', 'application/json']

# Load task modules from all registered Django app configs.
app.autodiscover_tasks()

logger = get_task_logger(__name__)

@app.task(bind=False)
def do_something_dumb():
    time.sleep(5)
    logger.info("Something dumb being done")
    return 1
```

Launching celery with the above code with
```
celery -E -A pg3 worker --loglevel=info

yields the following stack trace (last few lines only shown):
  File "/home/steve/.virtualenvs/pg3/lib/python3.6/site-packages/amqp/connection.py", line 481, in on_inbound_method
    method_sig, payload, content,
  File "/home/steve/.virtualenvs/pg3/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/home/steve/.virtualenvs/pg3/lib/python3.6/site-packages/amqp/channel.py", line 279, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'getting_started' in vhost '/': received 'true' but current is 'false'

```
Does this mean that Celery has a bug since it is breaking the rule of "server Must ignore the durable field if the queue already exists" or does this mean there is a bug in RabbitMQ (as it is the server that perhaps is not ignoring the rule?

Thanks for taking the time. I have worked around the problem by having Celery create the queues I want to create first, and then I allow pika to connect to them with it's defaults without breaking the behavior. The fact that it only breaks when first creating a durable queue with Celery and then successfully connecting to said queue with pika using pika's defaults leads me to believe it's a bug on Celery's end but I am not sure if I am right in this.

## Expected behavior
My current best understanding of the expected behavior is that Celery would simply attach to this already existing non-durable queue.

## Actual behavior
So, after much gnashing of teeth, I figured out that pika creates the queue as non-durable by default, yet Celery wants to do the opposite. See [kombu/entity.py](https://github.com/celery/kombu/blob/master/kombu/entity.py#L137-L139)

It seems to me that Celery isn't honoring what (little) I currently understand about AMQP, Rabbit, pika and Celery. The docs I had read said if a queue is inadvertantly redeclared, that should be a no-op. But it also appears that Celery is trying to declare the queue, in this case 
getting_started
with a parameter of durable = "True" and then RabbitMQ rightfully complains that a queue cannot be both durable and non durable.

So, my questions are:
1) Should Celery honor pre-existing queues that are not default, but direct? (In otherwords, should it test for a queue's existence before trying to create it with its own set of default parameters
2) Is it shown somewhere in the Celery docs where I could let Celery no that this already existing queue is not durable; and if so, how would I do that?
3) Are the AMQP docs in error to show that durable gets initialized to false?
4) Following the link in the AMQP docs to the source code of queue_declare states quite clearly:

**Comment by thedrow** [comment]
When you define a queue, mark it as non-durable. Refer to the [docs](http://docs.celeryproject.org/en/latest/userguide/routing.html#defining-queues) to understand how to define queues.
The constructor of Queue accepts a durable argument which in your case should be set to False e.g. `Queue('myqueue`, durable=False)`.

**Comment by oleks-popovych** [comment]
I'm creating queues at runtime. So far everything works.

Currently I'm trying to optimize my solution and delete queues that not in use already. I'm relying on auto-delete feature of rabbitmq, which deletes queue if there are no consumers. On the other hand I don't want it to be durable.

When I use celery.send_task I get an error that celery expect queue to be durable, is there a way to inform celery that it is not. I assume I should pass something into celery.send_task, but so far I did not found anything

**Comment by oleks-popovych** [comment]
@auvipy I've posted my message here, under related issue.

**Comment by oleks-popovych** [comment]
I found a solution to my question.

So after experimenting for several hours, I've found this peace of code:

```
celery_instance = get_celery()
queue_instance = Queue(name="person", durable=False, auto_delete=True)
celery_instance.send_task(
    "person",
    kwargs={
        "message": "hello"*1000
    },
    queue=queue_instance,
)
```
