### ISSUE TITLE
Celery beat throws "psycopg2.InterfaceError: connection already closed" exception at random points

### ISSUE THREAD

**Issue by ShaheedHaque** [celery/celery#4542]
## Checklist

- [Y] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [N] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Just run celery beat. At apparently random intervals, the exception is thrown.

## Expected behavior

Reliable operation with no exceptions being thrown.

## Actual behavior

At seemingly random times, the Beat log shows an exception which seems database connection-related. In this example at least, the exception seems to shortly follow a schedule update, but I think I have seen it at other times too:

> [2018-02-15 22:03:24,764: INFO/MainProcess] Writing entries...
> [2018-02-15 22:03:24,777: INFO/MainProcess] DatabaseScheduler: Schedule changed.
> [2018-02-15 22:03:24,777: INFO/MainProcess] Writing entries...
> [2018-02-15 22:03:24,779: INFO/MainProcess] Writing entries...
> [2018-02-15 22:03:24,790: CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.InterfaceError'>: InterfaceError('connection already closed',)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
>     return self._prepare_cursor(self.create_cursor(name))
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 212, in create_cursor
>     cursor = self.connection.cursor()
> psycopg2.InterfaceError: connection already closed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/celery/apps/beat.py", line 107, in start_scheduler
>     service.start()
>   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 564, in start
>     self.scheduler._do_sync()
>   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 343, in _do_sync
>     self.sync()
>   File "/home/srhaque/Innovatieltd/testdjango/django_celery_beat/schedulers.py", line 243, in sync
>     self.schedule[name].save()
>   File "/home/srhaque/Innovatieltd/testdjango/django_celery_beat/schedulers.py", line 290, in schedule
>     self._schedule = self.all_as_schedule()
>   File "/home/srhaque/Innovatieltd/testdjango/django_celery_beat/schedulers.py", line 197, in all_as_schedule
>     for model in self.Model.objects.enabled():
>   File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 272, in __iter__
>     self._fetch_all()
>   File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1179, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 54, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
>   File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
>     cursor = self.connection.cursor()
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 255, in cursor
>     return self._cursor()
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
>     return self._prepare_cursor(self.create_cursor(name))
>   File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
>     return self._prepare_cursor(self.create_cursor(name))
>   File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 212, in create_cursor
>     cursor = self.connection.cursor()
> django.db.utils.InterfaceError: connection already closed

Sometimes, after this, schedules are picked up after a delay and seem to run normally. But in this case, the routine messages stopped after this:

> [2018-02-15 22:03:24,923: WARNING/MainProcess] django.db.utils
> [2018-02-15 22:03:24,923: WARNING/MainProcess] .
> [2018-02-15 22:03:24,923: WARNING/MainProcess] InterfaceError
> [2018-02-15 22:03:24,923: WARNING/MainProcess] :
> [2018-02-15 22:03:24,924: WARNING/MainProcess] connection already closed
> [2018-02-15 22:03:24,924: INFO/MainProcess] Writing entries...
> [2018-02-15 22:03:24,935: INFO/MainProcess] Writing entries...
> [2018-02-15 22:35:32,660: INFO/MainProcess] beat: Starting...
> [2018-02-15 22:35:32,662: INFO/MainProcess] Writing entries...
> [2018-02-15 22:35:32,794: INFO/MainProcess] Scheduler: Sending due task Porsche:w1 (paiyroll.tasks.pay_run)
> [2018-02-15 22:35:32,815: INFO/MainProcess] Writing entries...

As shown in the log, a restart of beat was required before normal operation resumed.

Output from "celery report":

> software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
>             billiard:3.5.0.3 py-amqp:2.2.2
> platform -> system:Linux arch:64bit, ELF imp:CPython
> loader   -> celery.loaders.app.AppLoader
> settings -> transport:amqp results:django-db
> 
> ABSOLUTE_URL_OVERRIDES: {
>  }
> ADMINS: []
> ALLOWED_HOSTS: ['*']
> APPEND_SLASH: True
> AUTHENTICATION_BACKENDS: ['django.contrib.auth.backends.ModelBackend']
> AUTH_PASSWORD_VALIDATORS: '********'
> AUTH_USER_MODEL: 'myapp.User'
> BASE_DIR: '/home/srhaque/Innovatieltd/testdjango'
> CACHES: {
>  'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
> CACHE_MIDDLEWARE_ALIAS: 'default'
> CACHE_MIDDLEWARE_KEY_PREFIX: '********'
> CACHE_MIDDLEWARE_SECONDS: 600
> CELERY_BEAT_SCHEDULER: 'django_celery_beat.schedulers:DatabaseScheduler'
> CELERY_BEAT_SCHEDULE_FILENAME: 'django'
> CELERY_BROKER_URL: 'amqp://guest:********@localhost:5672//'
> CELERY_RESULT_BACKEND: 'django-db'
> CSRF_COOKIE_AGE: 31449600
> CSRF_COOKIE_DOMAIN: None
> CSRF_COOKIE_HTTPONLY: False
> CSRF_COOKIE_NAME: 'csrftoken'
> CSRF_COOKIE_PATH: '/'
> CSRF_COOKIE_SECURE: False
> CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
> CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
> CSRF_TRUSTED_ORIGINS: []
> CSRF_USE_SESSIONS: False
> DATABASES: {
>     'default': {   'ENGINE': 'django.db.backends.postgresql',
>                    'HOST': '127.0.0.1',
>                    'NAME': 'foo',
>                    'PASSWORD': '********',
>                    'PORT': '5432',
>                    'USER': 'dbcoreuser'}}
> DATABASE_ROUTERS: '********'
> DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
> DATA_UPLOAD_MAX_NUMBER_FIELDS: 1000
> DATETIME_FORMAT: 'N j, Y, P'
> DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
>  '%Y-%m-%d %H:%M:%S.%f',
>  '%Y-%m-%d %H:%M',
>  '%Y-%m-%d',
>  '%m/%d/%Y %H:%M:%S',
>  '%m/%d/%Y %H:%M:%S.%f',
>  '%m/%d/%Y %H:%M',
>  '%m/%d/%Y',
>  '%m/%d/%y %H:%M:%S',
>  '%m/%d/%y %H:%M:%S.%f',
>  '%m/%d/%y %H:%M',
>  '%m/%d/%y']
> DATE_FORMAT: 'N j, Y'
> DATE_INPUT_FORMATS: ['%Y-%m-%d',
>  '%m/%d/%Y',
>  '%m/%d/%y',
>  '%b %d %Y',
>  '%b %d, %Y',
>  '%d %b %Y',
>  '%d %b, %Y',
>  '%B %d %Y',
>  '%B %d, %Y',
>  '%d %B %Y',
>  '%d %B, %Y']
> DEBUG: True
> DEBUG_PROPAGATE_EXCEPTIONS: False
> DECIMAL_SEPARATOR: '.'
> DEFAULT_CHARSET: 'utf-8'
> DEFAULT_CONTENT_TYPE: 'text/html'
> DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
> DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
> DEFAULT_FROM_EMAIL: 'webmaster@localhost'
> DEFAULT_INDEX_TABLESPACE: ''
> DEFAULT_TABLESPACE: ''
> DISALLOWED_USER_AGENTS: []
> EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
> EMAIL_HOST: 'localhost'
> EMAIL_HOST_PASSWORD: '********'
> EMAIL_HOST_USER: ''
> EMAIL_PORT: 25
> EMAIL_SSL_CERTFILE: None
> EMAIL_SSL_KEYFILE: '********'
> EMAIL_SUBJECT_PREFIX: '[Django] '
> EMAIL_TIMEOUT: None
> EMAIL_USE_LOCALTIME: False
> EMAIL_USE_SSL: False
> EMAIL_USE_TLS: False
> FILE_CHARSET: 'utf-8'
> FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
> FILE_UPLOAD_HANDLERS: 
>     ('django_excel.ExcelMemoryFileUploadHandler',
>  'django_excel.TemporaryExcelFileUploadHandler')
> FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
> FILE_UPLOAD_PERMISSIONS: None
> FILE_UPLOAD_TEMP_DIR: None
> FIRST_DAY_OF_WEEK: 0
> FIXTURE_DIRS: []
> FORCE_SCRIPT_NAME: None
> FORMAT_MODULE_PATH: None
> FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
> IGNORABLE_404_URLS: []
> INSTALLED_APPS: ['myapp.apps.myappConfig',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.postgres',
>  'django_jinja',
>  'bootstrapform_jinja',
>  'django_celery_beat',
>  'django_celery_monitor',
>  'django_celery_results']
> INTERNAL_IPS: []
> LANGUAGES: [('af', 'Afrikaans'),
>  ('ar', 'Arabic'),
>  ('ast', 'Asturian'),
>  ('az', 'Azerbaijani'),
>  ('bg', 'Bulgarian'),
>  ('be', 'Belarusian'),
>  ('bn', 'Bengali'),
>  ('br', 'Breton'),
>  ('bs', 'Bosnian'),
>  ('ca', 'Catalan'),
>  ('cs', 'Czech'),
>  ('cy', 'Welsh'),
>  ('da', 'Danish'),
>  ('de', 'German'),
>  ('dsb', 'Lower Sorbian'),
>  ('el', 'Greek'),
>  ('en', 'English'),
>  ('en-au', 'Australian English'),
>  ('en-gb', 'British English'),
>  ('eo', 'Esperanto'),
>  ('es', 'Spanish'),
>  ('es-ar', 'Argentinian Spanish'),
>  ('es-co', 'Colombian Spanish'),
>  ('es-mx', 'Mexican Spanish'),
>  ('es-ni', 'Nicaraguan Spanish'),
>  ('es-ve', 'Venezuelan Spanish'),
>  ('et', 'Estonian'),
>  ('eu', 'Basque'),
>  ('fa', 'Persian'),
>  ('fi', 'Finnish'),
>  ('fr', 'French'),
>  ('fy', 'Frisian'),
>  ('ga', 'Irish'),
>  ('gd', 'Scottish Gaelic'),
>  ('gl', 'Galician'),
>  ('he', 'Hebrew'),
>  ('hi', 'Hindi'),
>  ('hr', 'Croatian'),
>  ('hsb', 'Upper Sorbian'),
>  ('hu', 'Hungarian'),
>  ('ia', 'Interlingua'),
>  ('id', 'Indonesian'),
>  ('io', 'Ido'),
>  ('is', 'Icelandic'),
>  ('it', 'Italian'),
>  ('ja', 'Japanese'),
>  ('ka', 'Georgian'),
>  ('kab', 'Kabyle'),
>  ('kk', 'Kazakh'),
>  ('km', 'Khmer'),
>  ('kn', 'Kannada'),
>  ('ko', 'Korean'),
>  ('lb', 'Luxembourgish'),
>  ('lt', 'Lithuanian'),
>  ('lv', 'Latvian'),
>  ('mk', 'Macedonian'),
>  ('ml', 'Malayalam'),
>  ('mn', 'Mongolian'),
>  ('mr', 'Marathi'),
>  ('my', 'Burmese'),
>  ('nb', 'Norwegian Bokmål'),
>  ('ne', 'Nepali'),
>  ('nl', 'Dutch'),
>  ('nn', 'Norwegian Nynorsk'),
>  ('os', 'Ossetic'),
>  ('pa', 'Punjabi'),
>  ('pl', 'Polish'),
>  ('pt', 'Portuguese'),
>  ('pt-br', 'Brazilian Portuguese'),
>  ('ro', 'Romanian'),
>  ('ru', 'Russian'),
>  ('sk', 'Slovak'),
>  ('sl', 'Slovenian'),
>  ('sq', 'Albanian'),
>  ('sr', 'Serbian'),
>  ('sr-latn', 'Serbian Latin'),
>  ('sv', 'Swedish'),
>  ('sw', 'Swahili'),
>  ('ta', 'Tamil'),
>  ('te', 'Telugu'),
>  ('th', 'Thai'),
>  ('tr', 'Turkish'),
>  ('tt', 'Tatar'),
>  ('udm', 'Udmurt'),
>  ('uk', 'Ukrainian'),
>  ('ur', 'Urdu'),
>  ('vi', 'Vietnamese'),
>  ('zh-hans', 'Simplified Chinese'),
>  ('zh-hant', 'Traditional Chinese')]
> LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
> LANGUAGE_CODE: 'en-us'
> LANGUAGE_COOKIE_AGE: None
> LANGUAGE_COOKIE_DOMAIN: None
> LANGUAGE_COOKIE_NAME: 'django_language'
> LANGUAGE_COOKIE_PATH: '/'
> LOCALE_PATHS: []
> LOGGING: {
>     'disable_existing_loggers': False,
>     'formatters': {   'standard': {   'format': '%(asctime)s [%(levelname)s] '
>                                                 '%(name)s: %(message)s'}},
>     'handlers': {   'file': {   'backupCount': 10,
>                                 'class': 'logging.handlers.RotatingFileHandler',
>                                 'filename': '/home/srhaque/.local/share/myapp/django.log',
>                                 'formatter': 'standard',
>                                 'level': 'DEBUG',
>                                 'maxBytes': 15728640}},
>     'loggers': {'': {'handlers': ['file'], 'level': 'INFO', 'propagate': True}},
>     'version': 1}
> LOGGING_CONFIG: 'logging.config.dictConfig'
> LOGGING_DIR: '/home/srhaque/.local/share/myapp'
> LOGIN_REDIRECT_URL: '/accounts/profile/'
> LOGIN_URL: '/accounts/login/'
> LOGOUT_REDIRECT_URL: None
> MANAGERS: []
> MEDIA_ROOT: ''
> MEDIA_URL: ''
> MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
> MIDDLEWARE: ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> MIGRATION_MODULES: {
>  }
> MONTH_DAY_FORMAT: 'F j'
> NUMBER_GROUPING: 0
> PASSWORD_HASHERS: '********'
> PASSWORD_RESET_TIMEOUT_DAYS: '********'
> PREPEND_WWW: False
> ROOT_URLCONF: 'testdjango.urls'
> SECRET_KEY: '********'
> SECURE_BROWSER_XSS_FILTER: False
> SECURE_CONTENT_TYPE_NOSNIFF: False
> SECURE_HSTS_INCLUDE_SUBDOMAINS: False
> SECURE_HSTS_PRELOAD: False
> SECURE_HSTS_SECONDS: 0
> SECURE_PROXY_SSL_HEADER: None
> SECURE_REDIRECT_EXEMPT: []
> SECURE_SSL_HOST: None
> SECURE_SSL_REDIRECT: False
> SERVER_EMAIL: 'root@localhost'
> SESSION_CACHE_ALIAS: 'default'
> SESSION_COOKIE_AGE: 1209600
> SESSION_COOKIE_DOMAIN: None
> SESSION_COOKIE_HTTPONLY: True
> SESSION_COOKIE_NAME: 'sessionid'
> SESSION_COOKIE_PATH: '/'
> SESSION_COOKIE_SECURE: False
> SESSION_ENGINE: 'django.contrib.sessions.backends.db'
> SESSION_EXPIRE_AT_BROWSER_CLOSE: False
> SESSION_FILE_PATH: None
> SESSION_SAVE_EVERY_REQUEST: False
> SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
> SETTINGS_MODULE: 'testdjango.settings'
> SHORT_DATETIME_FORMAT: 'm/d/Y P'
> SHORT_DATE_FORMAT: 'm/d/Y'
> SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
> SILENCED_SYSTEM_CHECKS: []
> STATICFILES_DIRS: []
> STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
>  'django.contrib.staticfiles.finders.AppDirectoriesFinder']
> STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
> STATIC_ROOT: '../staticroot'
> STATIC_URL: '/static/'
> TEMPLATES: [{'APP_DIRS': True,
>   'BACKEND': 'django_jinja.backend.Jinja2',
>   'DIRS': ['/home/srhaque/Innovatieltd/testdjango/templates'],
>   'OPTIONS': {'app_dirname': 'templates',
>               'auto_reload': True,
>               'autoescape': True,
>               'bytecode_cache': {'backend': 'django_jinja.cache.BytecodeCache',
>                                  'enabled': False,
>                                  'name': 'default'},
>               'constants': {},
>               'extensions': ['jinja2.ext.do',
>                              'jinja2.ext.loopcontrols',
>                              'jinja2.ext.with_',
>                              'jinja2.ext.i18n',
>                              'jinja2.ext.autoescape',
>                              'django_jinja.builtins.extensions.CsrfExtension',
>                              'django_jinja.builtins.extensions.CacheExtension',
>                              'django_jinja.builtins.extensions.TimezoneExtension',
>                              'django_jinja.builtins.extensions.UrlsExtension',
>                              'django_jinja.builtins.extensions.StaticFilesExtension',
>                              'django_jinja.builtins.extensions.DjangoFiltersExtension',
>                              'jinja_extensions.DebugExtension'],
>               'filters': {},
>               'globals': {},
>               'match_extension': ('.html',
>                                   '.jinja'),
>               'match_regex': '^(?!admin/).*',
>               'newstyle_gettext': True,
>               'tests': {},
>               'translation_engine': 'django.utils.translation',
>               'undefined': None}},
>  {'APP_DIRS': True,
>   'BACKEND': 'django.template.backends.django.DjangoTemplates',
>   'DIRS': ['/home/srhaque/Innovatieltd/testdjango/templates'],
>   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
>                                      'django.template.context_processors.request',
>                                      'django.contrib.auth.context_processors.auth',
>                                      'django.contrib.messages.context_processors.messages']}}]
> TEST_NON_SERIALIZED_APPS: []
> TEST_RUNNER: 'django.test.runner.DiscoverRunner'
> THOUSAND_SEPARATOR: ','
> TIME_FORMAT: 'P'
> TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
> TIME_ZONE: 'UTC'
> USE_ETAGS: False
> USE_I18N: True
> USE_L10N: True
> USE_THOUSAND_SEPARATOR: False
> USE_TZ: True
> USE_X_FORWARDED_HOST: False
> USE_X_FORWARDED_PORT: False
> WSGI_APPLICATION: 'testdjango.wsgi.application'
> X_FRAME_OPTIONS: 'SAMEORIGIN'
> YEAR_MONTH_FORMAT: 'F Y'
> is_overridden: <bound method Settings.is_overridden of <Settings "testdjango.settings">>

**Comment by ShaheedHaque** [comment]
Actually, even worse, I think that the Beat process dies after the exception because it happened again this morning, and now there is no Beat process on my system after:

> [2018-02-16 10:07:03,390: WARNING/MainProcess] cursor = self.connection.cursor()
> [2018-02-16 10:07:03,390: WARNING/MainProcess] django.db.utils
> [2018-02-16 10:07:03,390: WARNING/MainProcess] .
> [2018-02-16 10:07:03,390: WARNING/MainProcess] InterfaceError
> [2018-02-16 10:07:03,390: WARNING/MainProcess] :
> [2018-02-16 10:07:03,390: WARNING/MainProcess] connection already closed
> [2018-02-16 10:07:03,391: INFO/MainProcess] Writing entries...
> [2018-02-16 10:07:03,402: INFO/MainProcess] Writing entries...

(I did not notice this in my original report, but I now suspect the same happened there). Also, it seems the pidfile was deleted: is that perhaps a clue? Here is how I run it normally according to `ps` (paths slightly redacted for clarity):

`
/usr/bin/python3 /usr/local/bin/celery beat -A paiyroll -l info --detach --logfile celery-beat.log --pidfile celery-beat.pid
`

**Comment by ShaheedHaque** [comment]
And again. Started Beat after previous crash:

> [2018-02-16 12:33:23,147: INFO/MainProcess] beat: Starting...
> [2018-02-16 12:33:23,148: INFO/MainProcess] Writing entries...

and then:

> ...
> [2018-02-16 12:51:33,550: INFO/MainProcess] Writing entries...
> [2018-02-16 12:54:31,326: INFO/MainProcess] Scheduler: Sending due task Porsche:w1 (xx.yy.zz)
> [2018-02-16 12:54:36,332: INFO/MainProcess] Writing entries...
> [2018-02-16 12:54:36,348: INFO/MainProcess] DatabaseScheduler: Schedule changed.
> [2018-02-16 12:54:36,348: INFO/MainProcess] Writing entries...
> [2018-02-16 12:54:36,350: INFO/MainProcess] Writing entries...
> [2018-02-16 12:54:36,362: CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.InterfaceError'>: InterfaceError('connection already closed',)
> Traceback (most recent call last):
> ...
> [2018-02-16 12:54:36,402: WARNING/MainProcess] .
> [2018-02-16 12:54:36,402: WARNING/MainProcess] InterfaceError
> [2018-02-16 12:54:36,402: WARNING/MainProcess] :
> [2018-02-16 12:54:36,402: WARNING/MainProcess] connection already closed
> [2018-02-16 12:54:36,403: INFO/MainProcess] Writing entries...
> [2018-02-16 12:54:36,415: INFO/MainProcess] Writing entries...

No process, no pid file, no trace. I looked around other system log files (including Postgres), and only found this in Rabbitmq's log:

> =WARNING REPORT==== 16-Feb-2018::12:54:36 ===
> closing AMQP connection <0.4467.0> (127.0.0.1:40376 -> 127.0.0.1:5672, vhost: '/', user: 'guest'):
> client unexpectedly closed TCP connection

FWIW, the versions involved are:

```
ii  postgresql                          9.6+184ubuntu1.1       all                    object-relational SQL database (supported version)
ii  rabbitmq-server                     3.6.10-1               all                    AMQP server written in Erlang
```

Any ideas on how to investigate further would be welcome.

**Comment by PoloPing** [comment]
I have same problem too, but the point of time I got the error message is when I updated too many PeriodicTask and CrontabSchedule in the short time

**Comment by PoloPing** [comment]
@ShaheedHaque Hi, Did u find out what happen about this error now?

**Comment by ShaheedHaque** [comment]
No, I'm afraid not.

**Comment by PoloPing** [comment]
@ShaheedHaque Hi, sorry for disturbing you again, 
do u use docker swarm to deploy your celery-beat?

**Comment by ShaheedHaque** [comment]
No. We are still in development. Actually, for production, we will not be using Beat (this is just one reason).

**Comment by auvipy** [comment]
probably this should be filed on django-celery-beats

**Comment by ukrutt** [comment]
Is this the same error as https://github.com/celery/django-celery-beat/issues/158 ?
(It also seems that https://github.com/celery/celery/issues/4771 is related.)

**Comment by auvipy** [comment]
could you try to install django-celery-beat from the master?

**Comment by xxholyChalicexx** [comment]
Has this issue been solved in the new version of django-celery-beat ?

**Comment by auvipy** [comment]
> Has this issue been solved in the new version of django-celery-beat ?

can you please try latest version of django-celery-beat? as its an old issue so need someone to check

**Comment by auvipy** [comment]
seems https://github.com/celery/django-celery-beat/pull/182 should have fix it in MySQL DB

**Comment by xxholyChalicexx** [comment]
been facing this issue at random time and so far no such error!
