### ISSUE TITLE
Contradiction between validation and calling structure for kwargs parameter on signals

### ISSUE THREAD

**Issue by hheimbuerger** [celery/celery#4543]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [X] I checked the `master` branch and spotted the same code in the latest [signal.py](https://github.com/celery/celery/blob/master/celery/utils/dispatch/signal.py).

## Steps to reproduce

Celery 4.1.0.

Define a custom signal (I've looked at `task_prerun` and `task_postrun`), using the decorator:

    @task_prerun.connect
    def task_prerun(signal=None, sender=None, task_id=None, task=None, *args, **kwargs):
        pass

Note that the decorator calls `fun_accepts_kwargs()` on the function, so I must use the keyword argument unpacking syntax. (The documentation just says "The tasks keyword arguments." It doesn't mention what type this argument has to be in. Also note the grammar mistake: tasks => task's.)

## Expected behavior

Given the assertion on the parameter list, I expected the kwargs to be passed straight in, meaning `args` would receive the task's positional arguments and `kwargs` would receive the task's keyword arguments.

Additionally, I would expect the documentation to mention what type (calling style) the parameter will receive.

Also, I would expect the documentation to contain an example for the expected signature of a function implementing this signal.

## Actual behavior

Here's how the signal receiver is actually called:

    response = receiver(signal=self, sender=sender, **named)

with `named` being a dictionary containing among others the keys `args` and `kwargs`.

So I end up with

    args == ()
    kwargs == {'args': (...), 'kwargs': {...}}

Which is of course pretty absurd and not what's expected.

## Workaround

Here's a way to satisfy both the validation as well as the caller:

    @task_prerun.connect
    def task_prerun(signal=None, sender=None, task_id=None, task=None, args=None, kwargs=None, **_):
        pass

The `**_` is just there to lie to the validation code and should never receive anything.  
The `args` and `kwargs` are for the caller and actually filled with the expected data.

**Comment by hheimbuerger** [comment]
Looking at this some more, and seeing the examples for the other signals, I'm wondering whether the intended signature is this:

    @task_prerun.connect
    def task_prerun(signal=None, sender=None, task_id=None, task=None, args=None, **kwargs):
        pass

However, I tried that, and I'm still receiving my keyword arguments as a dict to the key `kwargs` *inside* the `kwargs` parameter, so

    kwargs == {'kwargs': {'foo': 3, 'bar': 4}}

which just doesn't seem to be as intended.

**Comment by auvipy** [comment]
I am realy sorry this didnt get proper traction before. may I know the current resolution of this?

**Comment by hheimbuerger** [comment]
My requirements/approach has changed, so I no longer need to create any Celery signal receivers.

So I'm not aware whether this has been fixed in 4.3.
