### ISSUE TITLE
Warm v/s Cold Shutdown 

### ISSUE THREAD

**Issue by vmandke** [celery/celery#4550]
How does the warm / cold shutdown of celery work ? I was going through the celery source code and found that the handlers for the signals are mapped here: celery/apps/worker::_shutdown_handler. However, how does it get called? I basically want to override the warm shutdown and always do a cold shutdown with only a single TERM signal.
How is the handling different on sending the second TERM ? As far I could follow the code, both TERM handlers are the same and do same work.

**Comment by vin18** [comment]
Found a hack!

    @celery.signals.celeryd_after_setup.connect
    def worker_ready(*args, **kwargs):
        try:
            celery.apps.worker.install_worker_term_handler = partial(
                celery.apps.worker._shutdown_handler,
                sig='SIGTERM',
                how='Cold',
                exc=WorkerTerminate,
                exitcode=EX_FAILURE
            )
        except Exception as e:
            print(e)

is there a better way to do this ?

**Comment by auvipy** [comment]
can you send a pr with test and proposed fix?
