### ISSUE TITLE
Multiprocessing in Celery with Billiard? 

### ISSUE THREAD

**Issue by rikkuporta** [celery/celery#4551]
Hi!
I'm not sure if this is a bug or intended - so it is either a bug report or a question.

Im using Celery for a server framework running neural entworks. There is a framework called sklearn which is used for optimization of neural networks and some of the methods allow the running of parallel jobs, to reach a desired resolution faster.
This does not work, since I can not spawn new processes from inside the workers.
The errror is: Multiprocessing-backed parallel loops cannot be nested

I tried to implement my own version with multiprocessing module, by creating multiple Process objects and then start()/join() but this also did not work.
I got an error as soon as i wanted to start() the process: AssertionError: daemonic processes are not allowed to have children

I then found out that Celery has their own multiprocessing fork called billiard and I tried to take the same code but replace the import with billiard.process
But I get following error: TypeError: _Popen() takes 1 positional argument but 2 were given

Looking inside it seems that _Popen() expectes no arguement (except self). But the call which raises the error is: self._popen = self._Popen(self)
Am I missing something? 

Is there any way to allow spawning of Processes and Multiprocessing inside of Workers? Is this a bug or intended function?

For reference, her is my more-or-less test code which I have used. It gets called within a task:

for a in range(3):
    def target(j):
        Logger.warning('test')

    pr = [mp.Process(target=target, args=(i,)) for i in range(3)]
    [p.start() for p in pr]
    [p.join() for p in pr]

Here is my Output for celery report:

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.2
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc:///

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'rpc:///'
worker_concurrency: 1
task_queues: 
    (<unbound Queue bcast.df1e639c-bfcd-4b6c-8453-c2332820931f -> <unbound Exchange broadcast_exchange(fanout)> -> >,)
task_routes: {
    'mtag.server.fworker.intent_recognition': {   'exchange': 'broadcast_exchange',
                                                       'queue': 'bcast'},
    'mtag.server.fworker.load_network': {   'exchange': 'broadcast_exchange',
                                                 'queue': 'bcast'},
    'mtag.server.fworker.reset_network': {   'exchange': 'broadcast_exchange',
                                                  'queue': 'bcast'},
    'mtag.server.fworker.save_network': {   'exchange': 'broadcast_exchange',
                                                 'queue': 'bcast'},
    'mtag.server.fworker.train_network': {   'exchange': 'broadcast_exchange',
                                                  'queue': 'bcast'}}

**Comment by thedrow** [comment]
We do not support multiprocessing inside Celery tasks for now.
I recommend to use [Dask](http://dask.pydata.org/en/latest/index.html) and [DaskML](http://dask-ml.readthedocs.io/en/latest/) for your use case.
You can trigger the training/test of your neural network using Celery but leave the calculation to Dask.

**Comment by linar-jether** [comment]
@thedrow Should note that the current sklearn version uses joblib which by default now uses `Loky` instead of `multiprocessing` which works fine with celery, and much more robust to deadlocks/worker crashes (might also be a good alternative to billiard, as it is both supported on windows/linux and python2/3)

**Comment by thedrow** [comment]
Celery 5 would require an async multiprocessing library but thanks for the pointer. I'll take a look at their design.

**Comment by auvipy** [comment]
we have a open issue in cep which aims to choose an alternative  for billiard.

**Comment by hotea** [comment]
You should do `from billiard.context import Process` rather than `from billiard.process import Process`

**Comment by Tommos0** [comment]
@linar-jether you mention that sklearn uses loky which should work. So I updated my sklearn, but now I'm getting:
`Loky-backed parallel loops cannot be called in a multiprocessing`, from this line:
```python
        elif mp.current_process().daemon:
            # Daemonic processes cannot have children
            if n_jobs != 1:
                warnings.warn(
                    'Loky-backed parallel loops cannot be called in a'
                    ' multiprocessing, setting n_jobs=1',
                    stacklevel=3)
            return 1
```
(celery 4.2.1, sklearn 0.20.0)

**Comment by 363568233** [comment]
subprocess Popen(args, start_new_session=True)  , child process can use multiprocessing or loky with sklearn

**Comment by Tommos0** [comment]
Yes, I'm just using a subprocess now too, note that this means I have to take care of propagating stdio and errors (which is something celery would normally do 'automatically').

**Comment by roelzkie15** [comment]
> You should do `from billiard.context import Process` rather than `from billiard.process import Process`

It is possible to use Pool? because using `from billiard import Pool` is not working and I don't know what is the equivalent of your suggested code using the `billiard.context` for pooling processes.

**Comment by afparsons** [comment]
I am trying to launch a celery task which calls sklearn with `n_jobs > 1`. Everything I read from late 2018 onward claims that the following is fixed:

>  UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1

I don't have anything to offer other than "it doesn't work for me" for posterity's sake.

```
celery==5.0.5
joblib==0.14.0  (upgrading to 1.0.1 doesn't change anything)
scikit-learn==0.23.1
billiard==3.6.4.0

Python 3.8.5, Ubuntu 18.04
```
---

Pseudocode:
```
def my_cool_ml_function(...):
    random_forest_classifier = RandomForestClassifier(..., n_jobs=-1)
    stuff = random_forest_classifier.fit(...)
    result = do_something_with_stuff(stuff)
    return result

def intermediate_step(...):
    return my_cool_ml_function(...)

@shared_task
def my_cool_task(...):
    result = intermediate_step(...)
    log_result_somewhere(result)
    
```

```
def foo_bar(...):
      my_cool_task.delay(...)  
```
```
$ celery -A <app_name> worker --loglevel=INFO
(--concurrency=4 or 8 or 16 or whatever doesn't change anything, despite the claim of a random StackOverflow comment)
```

Resulting in infinite warnings of:
```
UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
```
`Ctrl-C` does nothing; I have to `kill` the process.

---

If so many are writing that this is fixed, then it is more than likely I am doing something wrong! However, implementing this the right way is not obvious.

**Comment by Kipre** [comment]
For me, on both Ubuntu and Windows and Celery 5, neither `billiard.Pool` or `billiard.context._default_context.Pool` work 😢

**Comment by hadim** [comment]
Same here I am trying to use `multiprocessing` or `joblib` within a celery task for data analysis task but it does not work. I have tried all the mentioned solutions without success.

**Comment by linar-jether** [comment]
@hadim If you want a simple processing pool, use [loky ](https://github.com/joblib/loky)directly, this sample task works fine with celery.

```python
def multiprocessing_test_task(items):
    import loky
    pool = loky.get_reusable_executor()
    return list(pool.map(lambda x: x+1, items))
```

**Comment by hadim** [comment]
Thanks @linar-jether.

Any idea what `loky.get_reusable_executor()` is doing to make it work?

Also my code is extensively using `Parallel` and `delayed` (not `pool.map` from `loky`):

```python
from math import sqrt
from joblib import Parallel, delayed
def producer():
    for i in range(6):
        print('Produced %s' % i)
        yield i
out = Parallel(n_jobs=2, verbose=100, pre_dispatch='1.5*n_jobs')(
               delayed(sqrt)(i) for i in producer()
```

I am not sure what would the best way to inject `loky.get_reusable_executor()` in it?

**Comment by linar-jether** [comment]
Loky itself doesn't do anything specific to allow it, just the Joblib specifically [_disallows_ ](https://github.com/joblib/joblib/blob/754433f617793bc950be40cfaa265a32aed11d7d/joblib/_parallel_backends.py#L512) it. 

This is a simple workaround that monkey-patches joblib to allow for nested concurrency (inside Celery or any other pool).

```python
def _patch_joblib_loky_backend():
    import joblib._parallel_backends
    from joblib._parallel_backends import mp, cpu_count
    
    def effective_n_jobs(self, n_jobs):
        """Determine the number of jobs which are going to run in parallel"""
        if n_jobs == 0:
            raise ValueError('n_jobs == 0 in Parallel has no meaning')
        elif mp is None or n_jobs is None:
            # multiprocessing is not available or disabled, fallback
            # to sequential mode
            return 1
        elif n_jobs < 0:
            n_jobs = max(cpu_count() + 1 + n_jobs, 1)
        return n_jobs
    
    # Monkey-patch to allow daemonic thread to spawn processes
    joblib._parallel_backends.LokyBackend.effective_n_jobs = effective_n_jobs

# This works as a celery task, properly using nested concurrency
def multiprocessing_joblib_test_task(items):
    _patch_joblib_loky_backend()
    from joblib import Parallel, delayed, parallel_backend
    with parallel_backend("loky"):
        with Parallel(n_jobs=2) as pool:
            return pool(delayed(lambda x: x + 1)(x) for x in items)
```

**Comment by hadim** [comment]
As anyone else encounter the following issue using the @linar-jether monkey-patch snippet:

```
    p.start()
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```

**Comment by muety** [comment]
I was evaluating a Tensorflow model (CPU) inside a Celery task and realized that only one core was utilized, which drastically slowed down the process. Adding `--pool=threads` to the `celery worker` command solved the issue for me and since one such task is fully utilizing the CPU anyway, there is no point in having parallel tasks, so I combined this with `-c 1`.
