### ISSUE TITLE
No module named sqs.

### ISSUE THREAD

**Issue by logandhead** [celery/celery#4552]
I am unable to configure celery to use sqs. I followed the instructions on http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html

Here is the stack trace.
`[2018-02-21 12:27:25,073: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'sqs'",)
12:27:25 worker.1 | Traceback (most recent call last):
12:27:25 worker.1 |   File "/Users/logan/.virtualenvs/dolittle/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
12:27:25 worker.1 |     return obj.__dict__[self.__name__]
12:27:25 worker.1 | KeyError: 'backend'
`

I'm using python 3.6.

Requirements
boto==2.46.1
celery==4.0.2

Am I missing something?

**Comment by georgepsarakis** [comment]
Can you please share your configuration (omitting sensitive information of course, such as AWS API keys etc)?
