### ISSUE TITLE
Unstable max-concurrency in celery.inspect()

### ISSUE THREAD

**Issue by arthurlogilab** [celery/celery#4555]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
$ celery report
CELERYD_MAX_TASKS_PER_CHILD: 1
CELERY_ACKS_LATE: 0
CELERY_IMPORTS: [u'cw_celerytask_helpers.helpers']
CELERYD_MAX_TASK_PER_CHILD: 1
CELERYD_CONCURRENCY: 4
CELERYD_PREFETCH_MULTIPLIER: 1

software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.9
            billiard:3.3.0.23 redis:2.10.6
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis-sentinel results:redis-sentinel://redis-sentinel:26379/0

CELERY_QUEUES: 
    [snip]
SENTRY_DSN: [snip]
BROKER_TRANSPORT_OPTIONS: {
    'sentinels': [  [snip]
     ],
    'service_name': 'mymaster',
    'socket_timeout': 3,
    'visibility_timeout': 604800}
BROKER_URL: 'redis-sentinel://redis-sentinel:26379/0'
CELERY_ACCEPT_CONTENT: ['json', 'msgpack', 'yaml']
CELERYD_MAX_TASK_PER_CHILD: 1
CELERYD_MAX_TASKS_PER_CHILD: 1
CELERY_IMPORTS: [u'cw_celerytask_helpers.helpers']
CELERY_ACKS_LATE: 0
CELERY_ROUTES: {
[snip]
}
CELERY_RESULT_SERIALIZER: 'json'
CELERYD_PREFETCH_MULTIPLIER: 1
CELERY_TASK_SERIALIZER: 'json'
CUBICWEB_CELERYTASK_LOG_ALL: True
CELERY_RESULT_BACKEND: 'redis-sentinel://redis-sentinel:26379/0'
CUBICWEB_CELERYTASK_REDIS_URL: 'redis-sentinel://redis-sentinel:26379/0'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

For evaluating the availability of our celery workers on a cluster we take a look at the difference between the max-concurrency that we extract from celery.inspect().stats() and the active tasks from celery.inspect(). 

For a while max-concurrency was very stable, but then we introduced the `CELERY_ACKS_LATE: 0` http://docs.celeryproject.org/en/3.1/configuration.html?highlight=CELERY_ACKS_LATE#celery-acks-late the max-concurrency varies according to the load of the workers. Are we guessing correctly that when it is acknowledging that a task is done, it reduces the max-concurrency by one ? 

## Expected behavior

max-concurrency does not vary over time and is the setting in the configuration

## Actual behavior

max-concurrency varies over time and according to what the worker is doing.

**Comment by auvipy** [comment]
is this issue also effect new celery release or master?
