### ISSUE TITLE
Celery hangs indefinitely (instead of failing) if redis is not started

### ISSUE THREAD

**Issue by nemesisdesign** [celery/celery#4556]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: u'redis://localhost:6379/0'
```

## Steps to reproduce

Stop `redis-server.`
Initialize a celery instance configured with redis.

## Expected behavior

I expected an `OperationalError` or another exception communicating that celery cannot connect to the broker server.

## Actual behavior

It hangs indefinitely.

## Why this is important

In the current situation is not possible to write automated functional and integration tests that check whether the software handles failures when brokers are not reachable.

**Comment by clokep** [comment]
Sounds similar to #4328 to me, we've been running into a similar issue, although with RabbitMQ.

**Comment by keaneokelley** [comment]
I have seen this issue with Redis stopped and when Celery tries to connect to the broker over IPv6 but the firewall is configured to silently drop the connection attempts. It would eventually fall back to IPv4 and get an instant connection refused. Could this be your issue?

**Comment by keaneokelley** [comment]
@nemesisdesign what about `ip6tables`?

**Comment by cal97g** [comment]
@auvipy this is still an issue in v4.3

**Comment by auvipy** [comment]
if you can install celery and kombu from master and try to find the root cause of this hang?

**Comment by gertjanol** [comment]
I ran into the same issue, both with Redis and RabbitMQ. I think this is a serious problem, since it could easily lead to a denial-of-service of a webservice.

**Comment by auvipy** [comment]
Did anyone identify the root cause?

**Comment by Skidushe** [comment]
Still an issue... Plus fix could easily lead to DOS

**Comment by thedrow** [comment]
You should probably try to set [`broker_connection_max_retries`](https://docs.celeryproject.org/en/latest/userguide/configuration.html#broker-connection-max-retries) to a much lower value.

**Comment by Distill-pixel** [comment]
+1 @thedrow that might be the reason.

**Comment by marfgold1** [comment]
I've seen that it's not indefinitely, actually. As @thedrow mentioned, `broker_connection_max_retries` have been set to 100 by default. It means that eventually it will fail in 2+4+6+..+200 secs = 10100 secs (2 hours 48 mins 20 secs, to be exact. Yeah, a long time indeed). When I modify the configuration and either:
1. Set `broker_connection_max_retries` to 1, celery will retry the connection once in 2 secs, if it's still not available then it will throw ConnectionError.
2. Set `broker_connection_retry` to 0, celery will not even try to retry the connection and will throw ConnectionError anyway.

So you might either don't try celery to retry the connection, or maybe set the max retries to maybe 3 tries, depends on your case.
Or maybe I missed something? I don't really sure what do you mean by "hangs". Is it really hangs, like the process is not responding, or it will retry the connection again and again and again?

**Comment by auvipy** [comment]
@georgepsarakis

**Comment by marfgold1** [comment]
I think `broker_connection_max_retry` should be set to lower value by default, maybe 3 retries, for example. 100 is kinda ridiculous especially with increased retry time.
Also the broker keep retrying without saying anything like retry attempt (Attempt 1 of 100..Attempt 2 of 100..etc) or how many attempt for broker to reconnect (Reconnecting to broker in 100 tries..). That made user confused on how long celery worker will reconnect to the broker and assumed that it will retry indefinitely, especially those who does not notice this configuration variable.
That's just my suggestion, feel free to improve or maybe another good suggestion :smile:

**Comment by nemesisdesign** [comment]
Thank you for your analysis @marfgold1, what do you guys think?
@auvipy @georgepsarakis

**Comment by nemesisdesign** [comment]
Thanks @marfgold1 @auvipy :+1: :tada:

**Comment by dvf** [comment]
Hey folks, I've set the following:

```
CELERY_BROKER_CONNECTION_TIMEOUT = 2
CELERY_BROKER_CONNECTION_MAX_RETRY = 1
CELERY_BROKER_CONNECTION_RETRY = True
```

But Django still times out when calling `.apply_async(...)` on a function.

Am I missing something?
