### ISSUE TITLE
Having troubles with logging.

### ISSUE THREAD

**Issue by Subaku** [celery/celery#4557]
Hello,

I have a general question about logging with Celery as this may or may not be expected behavior. When logging inside a task it appears as though the logger is not flushing right away. Only when either a lot of output occurs in a single task or if I, inside a python shell, spam the same task repeatedly does the logs finally show up.

Here is the output from a ``celery report``.

software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.9
                    billiard:3.3.0.20 librabbitmq:1.5.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:librabbitmq results:disabled

We are using Celery inside a Django project using django-celery version 3.1.16 and we are using the logger returned from get_task_logger(__name__) from celery.utils.log. I should also mention that we've not implemented any log configurations for celery in our settings for Django.

Thanks!

**Comment by thedrow** [comment]
This has nothing to do with Celery probably. I suspect you should be using [unbuffered output](https://docs.python.org/2/using/cmdline.html#cmdoption-u) if that's the behavior you want.
