### ISSUE TITLE
.get() hangs indefinitely after running smoothly for ~70 hours (Redis broker)

### ISSUE THREAD

**Issue by monstermac77** [celery/celery#4561]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Report
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.3
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:rpc://[masterIP]/

task_queues: 
    (<unbound Queue unthrottledQueue -> <unbound Exchange u''(direct)> -> unthrottledQueue>,
 <unbound Queue throttledQueue -> <unbound Exchange u''(direct)> -> throttledQueue>,
 <unbound Queue queue15Min -> <unbound Exchange u''(direct)> -> queue15Min>,
 <unbound Queue queueEveryRequest -> <unbound Exchange u''(direct)> -> queueEveryRequest>)
broker_url: u'redis://[masterIP]:6379//'
result_backend: u'rpc://[masterIP]/'
```

## The Issue
After everything running smoothly for thousands of cycles (a cycle being: adding tasks to the queue, waiting for .get() to return (~50 seconds), sleeping 2 minutes, then starting all over), I get an indefinite hang on .get(). The time it takes for the indefinite hang to occur varies, but it's between 24 and 72 hours of running. 

I suspect that it has something to do with using the Redis broker. The output of `CLIENT LIST` shows a large number of connections with a very high idle number (see below). But I don't know why this would cause .get() to hang indefinitely. 

I can provide more details on my setup, but basically I have 6 worker servers and 1 master server. The master server is adding tasks to the 4 queues, and the worker servers each have workers that process each of the queues. unthrottledQueue handles the highest number of tasks (about 10k at a time) and the workers are able to finish them in about 50 seconds. This is the queue that eventually hangs on .get(). Sometimes a couple hours after unthrottledQueue hangs, the other queues (e.g. throttledQueue) start to hang on .get() too. 

### celery -A proj inspect active 
Running inspect active shows that there are no active tasks in the queue that .get() is hanging on, so it's not that there's just some really long running task that's causing the hang. 

### celery -A proj inspect reserved
Running inspect reserved returns empty across all workers. 

### redis-cli && CLIENT LIST
I ran `CLIENT LIST` on the master server soon after I was notified that .get() had hung. I ran it while the other queues that had not hung were not active in order to reduce noise. I've attached the output as a file. It looks like there are many with a high idle time. Also, it looks like it's listing connections from IPs that I either don't recognize or I may have used in the past, like weeks ago (IPs I'm actively using have been replaced with `[workerIPx]`).

[clientListWhileNothingActive.txt](https://github.com/celery/celery/files/1761491/clientListWhileNothingActive.txt)

### strace -p [worker PID] -s 10000
I ran `strace` on one of the 6 workers that was handling the queue that .get() had hung on. I've attached the output as a file.

[straceOfWorker.txt](https://github.com/celery/celery/files/1761489/straceOfWorker.txt)

### lsof -p [worker PID]
I ran `lsof` on one of the 6 workers that was handling the queue that .get() had hung on. I've attached the output as a file.

[lsofOfWorker.txt](https://github.com/celery/celery/files/1761492/lsofOfWorker.txt)

### ps aux | grep celery
I ran `ps aux` on one of the 6 worker servers, and the worker handling the queue that .get() had hung on came back with: 
```
root     13634 29.8  5.6 121324 58312 ?        S<   Feb24 1242:04 /usr/bin/python /usr/local/bin/celery -A checkerApp worker --pool eventlet --concurrency 100 --queue unthrottledQueue --hostname unthrottled@%h
```
Indicating I believe a 30% CPU utilization even though running `top` on the machine didn't seem to show 30% CPU utilization. I thought this could be relevant.

### flower
Perhaps this could be related: I'm getting a "clocks are out of sync" warning when launching flower. Here's the output: 
```celery flower --broker=redis://[masterIP]
[I 180227 04:01:02 command:139] Visit me at http://localhost:5555
[I 180227 04:01:02 command:144] Broker: redis://[masterIP]:6379//
[I 180227 04:01:02 command:147] Registered tasks: 
    [u'celery.accumulate',
     u'celery.backend_cleanup',
     u'celery.chain',
     u'celery.chord',
     u'celery.chord_unlock',
     u'celery.chunks',
     u'celery.group',
     u'celery.map',
     u'celery.starmap']
[I 180227 04:01:03 mixins:224] Connected to redis://[masterIP]:6379//
[W 180227 04:01:03 state:112] Substantial drift from unthrottled@workerServer6 may mean clocks are out of sync.  Current drift is
    21 seconds.  [orig: 2018-02-27 04:01:03.076278 recv: 2018-02-27 04:01:24.357406]
    
[W 180227 04:01:03 state:112] Substantial drift from unthrottled@workerServer4 may mean clocks are out of sync.  Current drift is
    17 seconds.  [orig: 2018-02-27 04:01:03.077826 recv: 2018-02-27 04:01:20.750901]
    
[W 180227 04:01:03 state:112] Substantial drift from unthrottled@workerServer3 may mean clocks are out of sync.  Current drift is
    21 seconds.  [orig: 2018-02-27 04:01:03.087373 recv: 2018-02-27 04:01:24.995805]
    
[W 180227 04:01:03 state:112] Substantial drift from throttled@workerServer4 may mean clocks are out of sync.  Current drift is
    17 seconds.  [orig: 2018-02-27 04:01:03.114218 recv: 2018-02-27 04:01:20.786468]
    
[W 180227 04:01:03 state:112] Substantial drift from throttled@workerServer3 may mean clocks are out of sync.  Current drift is
    22 seconds.  [orig: 2018-02-27 04:01:03.153177 recv: 2018-02-27 04:01:25.068150]
```

**Comment by wghilliard** [comment]
I'm not an expert with celery or redis but I can try to help debug. 

1. Are your servers virtualized?
2. Are you using NTP?
3. Do you have access to the redis broker logs? If so are there any warnings about message / client limits?
4. Does this problem occur faster / slower when changing the concurrency setting?
5. Is the redis broker also idle (sleep state) when the queues hang?

**Comment by monstermac77** [comment]
Thanks so much. So we ended up not being able to figure this out and have been using RabbitMQ ever since (but only after we managed to get RabbitMQ to compete with the performance we were seeing from Redis). 

However, it does bother me that we never figured this out. Someone who does appear to have a lot of experience running Redis with Celery essentially said that these kind of errors are pretty unavoidable and the only option might be to just abandon Celery+Redis altogether: https://stackoverflow.com/a/49036565/2611730. They even say that they've had to restart workers regularly via a cronjob to get things running long term (which is obviously a terrible hack). 

To answer your questions: 

> 1. Are your servers virtualized? 

Yes, they are VPS'.

> 2. Are you using NTP?

No, I'm pretty confident NTP is not even installed on these VPS'. 

> 3. Do you have access to the redis broker logs? If so are there any warnings about message / client limits?

If we were to reproduce this again, we could check the redis broker logs. I don't see anything in my notes about having done so, but if I recall correctly, the redis broker log may have just had something about not being able to save to disk, which was logged every second or so, but that was happening all the time (not just when things were hung). Again, I could be confusing this with another log. 

> 4. Does this problem occur faster / slower when changing the concurrency setting?

Normally after our tasks are completed, we wait a couple minutes before adding all the new tasks to the queue, and we tried taking out this delay and letting it run for an hour or so and that did not cause us to hit the hanging  within that hour. But no, I'm pretty sure we didn't play around with the concurrency settings overall. That said, the hanging did occur on both the unthrottledQueue and throttledQueue, and unthrottledQueue was being consumed by 6 workers each with concurrency 100, and throttledQueue had 6 workers each with concurrency 5. Usually unthrottledQueue would hang first, then maybe an hour later throttledQueue would also hang. I think maybe you could draw a connection between which queues hung first and how many tasks they were charged with handling, but after leaving it a while it seemed like all the queues were destined to hang eventually. 

> 5. Is the redis broker also idle (sleep state) when the queues hang?

How would I determine this exactly? I'm pretty sure the answer is "no", though, because only some of the queues hang, and others continue on normally, at least for a while (and the queues that are still running are using the redis broker).

**Comment by auvipy** [comment]
does this happen with celery 4.2.1 too?

**Comment by monstermac77** [comment]
I'm not sure. We switched to using RabbitMQ after weeks of trying to figure out this bug. 

Was there a change made in 4.2 that you think could have resolved this issue (specifically, any fixes related to Redis that could have been causing .get() to hang indefinitely)?

**Comment by auvipy** [comment]
probably not, but have to check.
