### ISSUE TITLE
Worker should get() a GroupResult or AsyncResult returned by a task

### ISSUE THREAD

**Issue by quantoid** [celery/celery#4563]
## Checklist

    $ celery -A tasks report
    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 librabbitmq:1.6.1
    platform -> system:Darwin arch:64bit imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:librabbitmq results:rpc:///

    accept_content: ['pickle', 'json']
    task_serializer: 'pickle'
    result_serializer: 'pickle'
    result_backend: u'rpc:///'

## Steps to reproduce

I have a workflow something like this:

    wf = collect_items.s() | add_details.s() | publish_items.s()

It collects some items, adds extra details to each one in parallel, then publishes the decorated information somewhere.

What I want is for `add_details` to behave as a group of tasks, one per item, that fetch the details for each item in parallel. Obviously the group has to be generated from the data output by `collect_items`. I don't want to use Celery's `map` because that would get details sequentially.

Here's what I tried, using the default rabbitmq broker:

    app = Celery(backend="rpc://")

    @app.task
    def collect_items(n):
        return range(n)

    @app.task
    def add_details(items):
        return group(get_details.s(i) for i in items).delay()

    @app.task
    def get_details(item):
        return (item, item * item)

    @app.task
    def publish_items(items):
        print("items = %r" % items)

## Expected behavior

I'm expecting the output to be a list of numbers 0-9 paired with their squares, all calculated concurrently:

    >>> wf.delay(10).get()
    items = [(0, 0), (1, 1), (2, 4), ... (8, 64), (9, 81)]

I'm expecting the `GroupResult` returned by `add_details` to be evaluated by Celery with `get()` before being passed on to `publish_items`. Alternatively, if I remove the `delay()` from the group, I'm expecting Celery to use `delay().get()` on a signature returned by a task.

## Actual behavior

This does invoke the expected tasks (I added prints in the tasks and watched the worker output), but unfortunately passes the result from `add_details` on to `publish_items` as a `GroupResult` containing `AsyncResults` with PENDING status, even though all the tasks appear to have completed.

**Comment by quantoid** [comment]
I guess if `Task.map(items)` executed the task for each item in parallel (like `multiprocessing.Pool.map` does) then that would solve this problem.

**Comment by quantoid** [comment]
Perhaps it doesn't work because I need to use a `chord` to wait for the results from the group, and that requires a different backend such as Redis.

**Comment by auvipy** [comment]
sorry for not noticing it earlier. whats the current status? wit pip install celery==4.4rc2+
