### ISSUE TITLE
Celery cron tab cheduled periodic task executes in delay or till you "inspect" workers.

### ISSUE THREAD

**Issue by trianglesis** [celery/celery#4574]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
- Register task in CRON
- Set time (17:00)
- Go away and do not touch server or any web application
- See no task were executed on 17:00
- Refresh page on Flower 
- Task had run just after page was refreshed!

> Received	2018-03-06 18:25:35.273168 UTC
> Started	2018-03-06 18:25:35.626143 UTC
> 

## Expected behavior
Task should run at 17:00

## Actual behavior
Task run only when user make any "refresh" action on workers, get any worker status, list of tasks etc.

## The problem
This issue cannot be reproduced under control, it just happened from time to time. Task can be "registered" in beat log and then nothing just happens, until you make any action on worker. Not restart or reload services, just getting something from app.control.inspect([worker_name]) and VOILA - task start its execution right after this action.

Sometimes it happen even on user behalf - I use the same task execution mechanism on webpage, and user run test button, and task just hangs in nowhere, flower have no task to show, and getting task statuses programmatically also did not help. It run only after workers restart.

Also got email: Scheduled start of nightly test run was initiated! At 2018-03-06 18:25:35 =)

Celery config:
[octo_celery_ISSUE_py.log](https://github.com/celery/celery/files/1786306/octo_celery_ISSUE_py.log)

Log and reports:
[celery_report.log](https://github.com/celery/celery/files/1786273/celery_report.log)

How it run on system:
[celeryd_conf_ISSUE.log](https://github.com/celery/celery/files/1786321/celeryd_conf_ISSUE.log)
[celery_service_conf_ISSUE.log](https://github.com/celery/celery/files/1786322/celery_service_conf_ISSUE.log)

Service:
[celery - ISSUE.service.log](https://github.com/celery/celery/files/1786329/celery.-.ISSUE.service.log)
[celerybeat - ISSUE.log](https://github.com/celery/celery/files/1786331/celerybeat.-.ISSUE.log)

**Comment by trianglesis** [comment]
And again!
Task is set on 17:00
Beat sent it at 17:00

> [2018-03-14 17:00:00,125: INFO/MainProcess] Scheduler: Sending due task tkn_ship_routine_manual_expires (cases.tasks_shelf.routine_tasks.tasks.night_test_executor)

But then - all workers just sleep till I refresh the gjango web site.

2018-03-14 17:23:22,242 DEBUG   tasks.py               night_test_executor       L:100   <=TasksRoutine=>Just executing Night test for branch: kwargs: {'send_mail': True, 'user_name': 'cron_user', 'sync_tku': True}
2018-03-14 17:23:22,243 DEBUG   tasks_helpers.py       night_routine_mail_status L:33    <=CASE MAIL=> Mail mode start

How can it be possible?
How to avoid this?

**Comment by trianglesis** [comment]
And actually flower show task received:
```
Received | 2018-03-14 17:23:22.239446 UTC
-- | --
```
Where this task was for 23 minutes?

**Comment by trianglesis** [comment]
Any updates? anybody?
It happens again and again and cannot be reproduced under control, I just can't be sure any of my scheduled tests will execute.
It just do nothing, no errors or warnings!

**Comment by georgepsarakis** [comment]
@trianglesis the issue persists with current master and you are using the UTC timezone?

**Comment by trianglesis** [comment]
It was set:
`    timezone            = 'UTC'
    enable_utc          = True
    app.conf.timezone   = 'Europe/London'
    app.conf.enable_utc = True`

I found an older issue from Dec 2017 and changed settings to:

`    app.conf.update(
        # https://github.com/celery/celery/issues/4184
        timezone            = 'UTC',
        enable_utc          = True,`

Will see later how it work after changes. I also change cron chedule tasks from 00 min to 01 min.

And regarding master branch - I just install latest "prod" version from pip. 

Should I copy "raw" code from current master branch? I thought there is just an early dev version. Do not want to face new hidden issues instead of one and known.

**Comment by trianglesis** [comment]
After upgrade from master branch I having now: ConnectionResetError at /

**Comment by trianglesis** [comment]
Now facing:
ConnectionResetError at /
[Errno 104] Connection reset by peer

Right after update to latest versions from master branches.

**Comment by trianglesis** [comment]
Ok, 
Cron issue is still here:

Beat sent task:
```
[2018-03-19 17:01:00,133: INFO/MainProcess] Scheduler: Sending due task tkn_main_workday_routine (cases.tasks_shelf.routine_tasks.tasks.night_test_executor)
[2018-03-19 17:01:30,176: INFO/MainProcess] Writing entries...
```

No workers were affected, all queues = 0.
Waiting for two minutes and then.. just refresh MAIN page of my site, where attributes from inspect.active is shown.

All workers start jobs immediately after I refresh the main page!

`2018-03-19 17:02:33,576 DEBUG   tasks.py               night_test_executor       L:100   <=TasksRoutine=>Just executing Night test for branch: tkn_main kwargs: {'send_mail': True, 'user_name': 'cron_user', 'sync_tku': True}`

Scheduled start of nightly test run was initiated! At 2018-03-19 17:02:33

Also in ver 4.2.0 worker_prefetch_multiplier = 0 - isn't working as expected. Or working in other way.
In prev. version all tasks were placed in worker queue at once! Now it adding them one by one. So when I have hundreds of them - I need to wait they all add in queue after few minutes.


Current settings:
```
    app.conf.update(
        accept_content    = ['json', 'pickle', 'application/x-python', 'application/json',
                             'application/x-python-serialize'],
        task_serializer   = 'pickle',
        result_serializer = 'json',
        # Do not set! Or logic will not wait of task OK: # task_ignore_result=True,
        # result_backend = 'db+mysql://octo_user:yAsqigFAZQ@localhost/octopus_dev_copy'
        result_backend = 'django-db',  # Disable if 'django_celery_results'

        # INFO: This added as arg to celery service in Centos init.d | BUT should be used here?
        beat_scheduler             = 'django_celery_beat.schedulers:DatabaseScheduler',
        task_default_queue         = 'default',
        task_default_exchange      = 'default',
        task_default_routing_key   = 'default',
        task_default_exchange_type = 'direct',
        task_create_missing_queues = True,

        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_send_task_events
        worker_send_task_events = True,
        task_send_sent_event    = True,
        worker_pool_restarts    = True,
        # http://docs.celeryproject.org/en/master/userguide/configuration.html#std:setting-worker_prefetch_multiplier
        worker_prefetch_multiplier = 0,
        # worker_prefetch_multiplier = 2000, - will check it next time
        # Maybe this should be disabled to allow workers to get ALL tasks in queue.
        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_acks_late
        # http://docs.celeryproject.org/en/master/faq.html#faq-acks-late-vs-retry
        # task_acks_late = True,

        # Experimental:
        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-result_persistent
        result_persistent = True,
        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_track_started
        # task_track_started = True,

        # Can produce web errors: [Errno 104] Connection reset by peer???
        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_pool_limit
        # https://stackoverflow.com/questions/45803728/celery-upgrade-3-1-4-1-connection-reset-by-peer
        broker_pool_limit = None,  # Keep connection always up!
        # http://docs.celeryproject.org/en/latest/userguide/configuration.html#broker-connection-timeout
        broker_connection_timeout     = 2,
        broker_connection_retry       = True,
        broker_connection_max_retries = 0,
    )

```

**Comment by trianglesis** [comment]
Next issue:
workers came down time to time, this breaks the task, which should wait a loooong time to verify when all workers are empty and then send email:


```
Traceback (most recent call last):
  File "/var/www/octopus/octo/lib/python3.4/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/octopus/octo/lib/python3.4/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/octopus/cases/tasks_shelf/routine_tasks/tasks.py", line 106, in night_test_executor
    user_name = kwargs['user_name'],)
  File "/var/www/octopus/cases/cases_routine.py", line 176, in nightly_test_routine_case
    if TasksOperations().wait_active_tasks_all_workers(w_list):
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 164, in wait_active_tasks_all_workers
    if self.task_active_list_wait(worker_name=worker):
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 69, in task_active_list_wait
    while not self.get_active_tasks_list_len(worker_name) == 0:
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 86, in get_active_tasks_list_len
    return len(inspect.active()[worker_name])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by trianglesis** [comment]
UPD:
TZ changing to TIME_ZONE = 'Europe/London' did not allow Celery to execute task right in server's time.

Case:
True time is 'Europe/London' = 17:00 (also as server time)
Celery UTC "Hardcoded" time = 16:00

If I change Django TZ to London time, to allow my apllication to work in real True time - Celery did not run task at 17:00

If I change task time to 16 - it run.

**Comment by trianglesis** [comment]
Again:
```
[2018-04-03 16:01:00,129: INFO/MainProcess] Scheduler: Sending due task tkn_main_workday_routine (cases.tasks_shelf.routine_tasks.tasks.night_test_executor)
2018-04-03 16:01:00,143 DEBUG   tasks.py               night_test_executor       L:99    <=TasksRoutine=>Just executing Night test for branch: tkn_main kwargs: {'send_mail': True, 'sync_tku': True, 'user_name': 'cron_user'}
2018-04-04 05:01:00,007 DEBUG   tasks.py               addm_daily_cleanup_routineL:159   <=TasksRoutine=> Execute: daily_cleanup_routine
```

Didn't get why usual routine did not start but was announced?
Others are fine, for example cleanup routine starts and run fine.

**Comment by trianglesis** [comment]
Still no fix available here.
Celery TZ has no effect.

**Comment by auvipy** [comment]
tried celery 4.2?

**Comment by trianglesis** [comment]
now trying latest version on dev env. There are lot of other issues, this one have no change to reoccurs,
I'll update this issue right after I move to cron and planned task tests in next week or two.

**Comment by codeadict** [comment]
I'm experiencing this same issue.
