### ISSUE TITLE
Eager Application Synchronous Subtask Guard Blocks Canvas

### ISSUE THREAD

**Issue by npilon** [celery/celery#4576]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

```
celery -A minimal_eager_chain report

software -> celery:4.2.0 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

```

Minimal script to reproduce: https://gist.github.com/npilon/9f3c8469a615081fc8454359945eebd7

## Expected behavior

- No error occurs

## Actual behavior

- We trip the synchronous subtask alarm:

```
>>> test.delay().get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/npilon/Documents/celery/celery/result.py", line 949, in get
    raise self.result
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

**Comment by jcushman** [comment]
The patch fixed this issue for `chain()` but not for `chord()`. Here is a modified script to reproduce the issue with `chord`:

https://gist.github.com/jcushman/ea8adcb37dffdf5c3fdf756d02366ab2

As in the original report, calling `chord().apply_async()` triggers the synchronous subtask guard when `CELERY_TASK_ALWAYS_EAGER=True`.

I'm guessing a full fix requires additional application of `with allow_join_result():` elsewhere in `celery/canvas.py`.

**Comment by jcushman** [comment]
This also makes me wonder if there's a general way to avoid triggering the guard because of `CELERY_TASK_ALWAYS_EAGER` in general, rather than just flagging all the spots where it misfires. I don't get the interaction enough to know if that's possible, though.

**Comment by thedrow** [comment]
@jcushman We prefer to create new issues for newly discovered problems.
If needed, we'll create a top issue for all those issues and close it once all problems are solved.
