### ISSUE TITLE
having uninstalled libraries can avoid tasks from being detected

### ISSUE THREAD

**Issue by amirRamirfatahi** [celery/celery#4589]
This Took me 3hours to figure out after having tried every page related to it
None had mentioned that this could be the cause

**Comment by WoaDmulL** [comment]
Also, bad written tasks.py ( syntax ) and even missing imports results in the tasks not being detected. 
Somehow, celery doesn't raise the exceptions...

**Comment by auvipy** [comment]
can you both please elaborate the problem?

**Comment by WoaDmulL** [comment]
It got fixed in the latest release. You can close it.

**Comment by auvipy** [comment]
thanks alex!
