### ISSUE TITLE
Can we please get a new release for the v4.1.0 series to fix time zone issues?

### ISSUE THREAD

**Issue by 2ps** [celery/celery#4590]
The 4.1.0 (latest release in pypi) is plagued by an issue where `Celery.now` does not return a proper timezoned date for non-UTC timezones.  This issue looks to be resolved in master, but unless a v4.1.1 or bug fix release is pushed out it will continue to haunt any poor soul that uses v4.1.0.  There are at least four open issues in `django-celery-beat` that can be traced to this bug, so a release would be most appreciated.

Steps to reproduce:

1.  Set `CELERY_TIMEZONE` to any value other than UTC, for example, `PST8PDT`.
2.  Call `app.now()`
3.  `app.now()` will return a time in the future rather than the current time in `PST8PDT`

Fix:

change `Celery.now` to use the following code:

```python
    def now(self):
        """Return the current time and date as a datetime."""
        return datetime.now(self.timezone)
```

**Comment by NullYing** [comment]
+1

**Comment by amitripshtos** [comment]
+1

**Comment by georgepsarakis** [comment]
Please see #4387 for tracking progress in the release process.
