### ISSUE TITLE
CELERY_BEAT_SCHEDULER instead CELERYBEAT_SCHEDULER | Docs

### ISSUE THREAD

**Issue by MIKNOTAURO** [celery/celery#4591]
I think, there is a little mistake in docs
https://github.com/celery/celery/blob/master/docs/userguide/configuration.rst

Try this in Django and did not work
CELERYBEAT_SCHEDULER

Should be like
CELERY_BEAT_SCHEDULER

That works ;)

**Comment by MIKNOTAURO** [comment]
I guess is the same for the other CELERYBEAT settings

**Comment by pachewise** [comment]
The docs you linked to are pointing out the _old_ setting name; Maybe we still need to clarify these values a bit more?

**Comment by auvipy** [comment]
https://github.com/celery/celery/commit/f9638fa24110f0589c4f1372bf86e43d6ae1781f
