### ISSUE TITLE
Django celery for download large file

### ISSUE THREAD

**Issue by chaudhary238** [celery/celery#4596]
I am developing a django app and my app need to user to upload the urls in excel files. On server side i am reading the excel file by each cells, extracting the news article of the urls and generating the summary of article. This process can take up to 5-10 minutes for the long list of urls. I am using celery for managing the long running task but somehow server is giving me error 500 - Internal server error after 2 min without completing the task
celery version : 3.1.25
django:1.10.7

__init__.py
    from .celery import app as celery_app
    __all__ = ['celery_app']

Setting.py

  BROKER_URL = 'django://'
  CELERY_ACCEPT_CONTENT = ['json']
  CELERY_TASK_SERIALIZER = 'json'
  CELERY_RESULT_SERIALIZER = 'json'

celery_app.py

   from __future__ import absolute_import

   import os
   import djang
   from celery import Celery
   from django.conf import settings
   os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'news.settings')
   django.setup()

   app = Celery('news')

   app.config_from_object('django.conf:settings')
   app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

summary.py

   from celery import shared_task
   @shared_task

   def WritesummaryfromArticleToExcel(input_file,noofline,lang):
       try:
           data=False
           wb = xlrd.open_workbook(file_contents=input_file.read())
           wb_sheet=wb.sheet_by_index(0)
           df=pd.DataFrame(columns=['Full Article','Summary'])
           for rownum in range(0, wb_sheet.nrows):
        # for colnum in range(0,1):
           try:
               rw=wb_sheet.cell_value(rownum,0)
               if type(rw)==float or type(rw)==int:
                   rw= str(rw)
        # if len(rw)>15000:
               data=True
               articletext=rw
        # nooflines=request.data["numberofline"]
               lantext=""
               lantexttemp= articletext.split('\n')[0:2]
               for l in lantexttemp:
                   lantext=lantext +"\n" +l
               lan=detect(lantext)   
view.py
    def translatedoc(request):
    data=""
    convrowstr=""
    if request.method=='POST':
       try:
            form=fileUpload(request.POST,request.FILES)
            if form.is_valid():
               input_file=request.FILES.get('file')
               noofline=request.POST.get('noofline')
               lang=request.POST.get('lang')
                sv=WritesummaryfromArticleToExcel(input_file,noofline,lang)
                response = StreamingHttpResponse (sv,content_type='application/vnd.ms-excel')
                response['Content-Disposition'] = 'attachment; filename=Output.xls'
                response['Content-Transfer-Encoding']='binary'
                return response

**Comment by raghuraju** [comment]
Looks like Stackoverflow would be a better place for this query.
