### ISSUE TITLE
Empty exchange value in task message

### ISSUE THREAD

**Issue by Ashish-Bansal** [celery/celery#4598]
Hi everyone,

I just upgraded one of my project to celery 4.1 from celery 3.1. Whenever I call send_task, exchange is empty in the delivery_info which contradicts with what has been specified here: http://docs.celeryproject.org/en/latest/userguide/routing.html#how-the-queues-are-defined

Is this the intended change in the celery 4.1 or is it a bug in celery or I'm doing something wrong ?

In celery 4.1:
```
{
  ...
  "properties": {
    "priority": 0, 
    "delivery_info": {
      "routing_key": "email", 
      "exchange": ""
    }, 
    ...
}
```

In celery 3.1:
```
{
  ...
  "properties": {
    "delivery_info": {
      "priority": 0, 
      "routing_key": "email", 
      "exchange": "email"
    }, 
}
```

```
(venv-py3-backend) (develop)⚡ % celery -A judger report                                              
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0
```

You can find full task message from the redis queue here: https://pastebin.com/fe4AsgKY

Regards,
Ashish Bansal

**Comment by auvipy** [comment]
use celery 4.2.1 and check docs properly. report again if still seems a real issue.
