### ISSUE TITLE
celery beat trigger celery.backend_cleanup exception as use redis cluster broker but None backend!

### ISSUE THREAD

**Issue by aohan237** [celery/celery#4605]
i read the celery.backend_cleanup code。
the celery beat will add a celery.backend_cleanup task.
as designed, cleanup should be bind with the backend.  but i didnt use any backend.

and  exception raised, this is werid

this "kombu/entity.py", line 649, in queue_declare
    nowait=nowait,
  File "python3.6/site-packages/kombu/transport/virtual/base.py", line 532, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
  File "python3.6/site-packages/kombu/transport/redis.py", line 750, in _size
    sizes = pipe.execute()
  File "python3.6/site-packages/redis/client.py", line 2626, in execute

Couldn't apply scheduled task celery.backend_cleanup: Command # 2 (LLEN celery3) of pipeline caused error: llen command keys must in same slot

**Comment by aohan237** [comment]
how to solver this?   many thanks

**Comment by japneet121** [comment]
@aohan237  how are you using redis cluster as backend ?

**Comment by aohan237** [comment]
@japneet121   i dont user redis cluster as backend  ， but  i encounter this problem that  maybe celery beat be the cause.
if i forbid celery beat,this will gone.

thanks for your help~~

**Comment by aohan237** [comment]
i read the celery.backend_cleanup code。
the celery beat will add a celery.backend_cleanup task.
as designed, cleanup should be bind with the backend.  but i didnt use any backend.

and  exception raised, this is werid

this "kombu/entity.py", line 649, in queue_declare
    nowait=nowait,
  File "python3.6/site-packages/kombu/transport/virtual/base.py", line 532, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
  File "python3.6/site-packages/kombu/transport/redis.py", line 750, in _size
    sizes = pipe.execute()
  File "python3.6/site-packages/redis/client.py", line 2626, in execute

**Comment by auvipy** [comment]
Will reopen the issue after feedback on celery 4.3++
