### ISSUE TITLE
What is the right way to share db connctions in every worker, rather than tasks where fork safe is concerned

### ISSUE THREAD

**Issue by tarjintor** [celery/celery#4607]
I try to do some db ops during a task, maybe write log to mongodb or insert some rows to mysql, or even use a redlock since celery works distributed, but I found it is hard to use the connections of all kinds of db properly.
For example, I found pymongo is not fork safe, so if I import pymongo, and use a custom Task class like the official example:
```
class DatabaseTask(Task):
    _db = None

    @property
    def db(self):
        if self._db is None:
            self._db = MongoClient(**mongo_kwargs)
        return self._db
```
This will work fine, but each task need a client, I feel a kind of waste
I wish that every worker share the mongo client rather than every task.
but if I import client as a singleton, then after fork, all worker shared the same client,since pymongo is not fork safe, this could case unpredicated dead lock,
So I want do some work after the fork, I guess my only shoot is use the Worker Signals,but I don't know how to do it,there is no example.
What should I do?

**Comment by auvipy** [comment]
you might check celery result backends. beside to get answer of your questions, better to ask either in stackoverflow, mailing-list or irc. github is for reporting issues on celery.
