### ISSUE TITLE
Celery 4.2.0 workers lost connection with AMQP constantly!

### ISSUE THREAD

**Issue by trianglesis** [celery/celery#4608]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Install fresh 4.2.0 main branch.
Execute large amount of tasks - hundreds of them.
Make a function which shows a worker queue length for selected workers on your django website.
Catch: 

> 'NoneType' object is not subscriptable
or 
> ConnectionResetError at / [Errno 104] Connection reset by peer

## Expected behavior
Worker should be 100 up and connection to AMQP should not be dropped.

## Actual behavior
Workers lost connections and it affects website UI and routines.

=ERROR REPORT==== 20-Mar-2018::07:31:27 ===
closing AMQP connection <0.18430.4> (127.0.0.1:42336 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}

Now I even can't track any progress of tasks execution on my website.
Also I use design where one task on worker "routines" is waiting for all other 5 workers until they finish theirs work to send email of completion confirmation.

Now none of those designs cannot work:

> cases.tasks_shelf.routine_tasks.tasks.night_test_executor 
> Worker | w_routines@HOST
> Exception | TypeError("'NoneType' object is not subscriptable",)

```
  File "/var/www/octopus/cases/cases_routine.py", line 176, in nightly_test_routine_case
    if TasksOperations().wait_active_tasks_all_workers(w_list):
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 164, in wait_active_tasks_all_workers
    if self.task_active_list_wait(worker_name=worker):
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 69, in task_active_list_wait
    while not self.get_active_tasks_list_len(worker_name) == 0:
  File "/var/www/octopus/cases/tasks_shelf/tasks_oper.py", line 86, in get_active_tasks_list_len
    return len(inspect.active()[worker_name])
TypeError: 'NoneType' object is not subscriptable
```

Config:
```
accept_content | ['json', 'pickle', 'application/x-python', 'application/json', 'application/x-python-serialize']
-- | --
beat_schedule | {}
beat_scheduler | django_celery_beat.schedulers:DatabaseScheduler
broker_connection_max_retries | 0
broker_connection_retry | True
broker_connection_timeout | 2
broker_url | amqp://octo_user:********@localhost:5672/HOST
enable_utc | True
include | ['cases.tasks_shelf.routine_tasks.tasks', 'celery.app.builtins', 'cases.tasks_shelf.service_tasks.tasks', 'cases.tasks_shelf.test_tasks.tasks']
result_backend | django-db
result_persistent | True
result_serializer | json
task_create_missing_queues | True
task_default_exchange | default
task_default_exchange_type | direct
task_default_queue | default
task_default_routing_key | ********
task_send_sent_event | True
task_serializer | pickle
timezone | UTC
worker_pool_restarts | True
worker_prefetch_multiplier | 0
worker_send_task_events | True
```

**Comment by trianglesis** [comment]
And I'm not even saying - page loading becomes too slow now.
All view with any inspect functions in it - loads longer then pages with thousands of queries to DB.

**Comment by auvipy** [comment]
is it happening with 4.2.1 and latest django-celery-beats?

**Comment by trianglesis** [comment]
This issue is not reproduce-able with new design of tasks execution.
I'm now avoiding this by pinging workers before use them for any action on user behalf,
