### ISSUE TITLE
Loggers are not set up when (some?) signal handlers are called, causing exceptions to be silently ignored

### ISSUE THREAD

**Issue by anlutro** [celery/celery#4609]
Given this code:

```
from celery import Celery

app = Celery(broker='memory://')

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    raise RuntimeError('this never shows up anywhere')
    print('this code is never reached')

if __name__ == '__main__':
    app.start()
```

You'd expect for `celery beat` or `celery worker -B` to fail, or at least log the exception being thrown, but neither happens.

Personally I'd like the above code to cause an early `sys.exit(1)`, but that's up for debate, I guess. However, the fact that the `RuntimeException` never shows up anywhere is less excusable - it's not logged anywhere.

I was only able to debug this by putting a try/except inside my handler function, and I put in a `print` statement into `Signal.send` just to be sure my theory was correct:

```
diff --git a/celery/utils/dispatch/signal.py b/celery/utils/dispatch/signal.py
index d69506819..fa648113b 100644
--- a/celery/utils/dispatch/signal.py
+++ b/celery/utils/dispatch/signal.py
@@ -276,6 +276,7 @@ class Signal(object):  # pragma: no cover
             except Exception as exc:  # pylint: disable=broad-except
                 if not hasattr(exc, '__traceback__'):
                     exc.__traceback__ = sys.exc_info()[2]
+                print(exc)
                 logger.exception(
                     'Signal handler %r raised: %r', receiver, exc)
                 responses.append((receiver, exc))
```

This `print` shows the actual exception, but the `logger.exception` is nowhere to be seen. The `print` happens before any log output is showing up in my terminal, so I have to assume logging is entirely disabled before this point or something?

This may be an issue with all signals or only some specific ones, I'm not sure.

```
$ celery -A sar report

software -> celery:4.2.0 (latentcall) kombu:4.1.0 py:3.5.3
            billiard:3.5.0.3 memory:N/A
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:memory results:disabled

broker_url: 'memory://localhost//'
```

**Comment by domenkozar** [comment]
Logging is not setup at that point.
