### ISSUE TITLE
Documentation of "accept_content" configuration directive seems incorrect

### ISSUE THREAD

**Issue by felipegeru** [celery/celery#4616]
This inconsistency is found at v4.0.2, at least.

The documentation states:
```
accept_content
Default: {'json'} (set, list, or tuple).

A white-list of content-types/serializers to allow.

If a message is received that’s not in this list then the message will be discarded with an error.

By default any content type is enabled, including pickle and yaml, so make sure untrusted parties don’t have access to your broker. See Security for more.
```
If the default value is `{'json'}` then by default only `json` is enabled. I confirmed that because I had a problem in my application when I added `CELERY_TASK_SERIALIZER = 'pickle'` to the Celery configuration, I later realized that I had to add `CELERY_ACCEPT_CONTENT = ['pickle']` to the configuration also for the tasks to work.

**Comment by rusty-udemy** [comment]
We just ran into this ourselves; it should definitely be changed.

**Comment by auvipy** [comment]
PR welcome

**Comment by felipegeru** [comment]
@auvipy you mean a PR to change the documentation, right? If so I can do it. :-)

**Comment by auvipy** [comment]
yes

**Comment by felipegeru** [comment]
Just created the above PR (https://github.com/celery/celery/pull/4658).
