### ISSUE TITLE
Release 3.1.27 instead of post release to 3.1.26

### ISSUE THREAD

**Issue by peterdemin** [celery/celery#4621]
Hello, I didn't find much detail but it seems that 3.1.26 was purged from PyPI and 3.1.26.post1 and 3.1.26.post2 uploaded to replace it.
Post releases are prohibited in my project, could you please make a proper 3.1.27 release?

**Comment by thedrow** [comment]
Why are they prohibited?

**Comment by peterdemin** [comment]
I think it's rather specific to my workplace. People sometimes upload post releases unintentionally when they forget to bump version.

**Comment by thedrow** [comment]
I'm sorry. I'm not going to be able to keep up with everyone's special requirements. Especially not for free.

You only need this version if you intend to migrate between Celery 3 and Celery 4.
