### ISSUE TITLE
Tests fail with pytest >= 3.3

### ISSUE THREAD

**Issue by fladi** [celery/celery#4626]
pytest 3.3 introduced automatic log capturing [0], which changes the log handlers during tests. This makes several tests in `t/unit/app/test_log.py` fail with RuntimeError exceptions raised. The cause for this is in the `sanity_logging_side_effects` autouse-fixture.

The whole exceptions can be seen in the Debian CI build report [1].

A temporary fix for this is to add `addopts=-p no:logging` to the `[tool:pytest]` section in `setup.cfg`. A more future-proof fix would be to ignore any pytest related log handlers when comparing them in the fixture.

[0] https://docs.pytest.org/en/latest/logging.html
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892640

**Comment by auvipy** [comment]
pr welcome

**Comment by thedrow** [comment]
We're aware of that and in fact in CI we have limited our pytest version to `<3.3`.

**Comment by auvipy** [comment]
started work to fix the issue. @fladi could you check the latest pr? and suggest clean ups?

**Comment by auvipy** [comment]
its fixed
