### ISSUE TITLE
Access Custom Configuration

### ISSUE THREAD

**Issue by mikegrima** [celery/celery#4633]
Hello!

What is the proper way for getting custom configuration variables in Celery Beat? (I'm on Celery 4.1.0)

By that I mean in my `celeryconfig.py`, say I have the following:
```
my_variable = 'foo'
```

When Celery Beat loads this, for me to grab this out, I need to use something along the lines of:
```
app.conf.get_by_parts("my_variable")
```

This works fine -- except when I'm in a `app.on_after_configure.connect` function. The problem here is when I call `app.conf.get_by_parts("my_variable")` from within my task scheduling function, it re-calls the `app.on_after_configure.connect` function!  I need that variable to know which tasks I need to (or don't need to) schedule.

Thus, it would appear that I am not using this properly.  I could always just try to find the raw value and extract it, but would much rather not do that.

Is this a bug, or am I doing it wrong?

**Comment by auvipy** [comment]
were you able to overcome the issue? or its a celery bug?

**Comment by mikegrima** [comment]
I completely forgot about this.

I would say that it's still an issue, but I found a workaround for this by simply loading the celery configuration file as a Python module: 
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/task_scheduler/util.py#L23-L24 and https://github.com/Netflix/security_monkey/blob/develop/security_monkey/task_scheduler/beat.py#L35

If this is the recommended way of doing this, then you can close out this issue. For now, I am able to achieve what I need.
