### ISSUE TITLE
celery beat: OSError: [WinError 87]

### ISSUE THREAD

**Issue by EmmanuelObo** [celery/celery#4636]
Suddenly I started getting this error when I run celery beat

```
celery beat -A proj 
```

Funny thing is that celery worker still runs but beat doesn't.
I'm running version 3.1.17 btw.

```
celery beat v3.1.17 (Cipater) is starting.
OSError: [WinError 87] The parameter is incorrect
...
SystemError: <class 'OSError'> returned a result with an error set
```

**Comment by auvipy** [comment]
use newer versions

**Comment by EmmanuelObo** [comment]
Upgraded to 4.1.0 (latentcall) still getting the same error
