### ISSUE TITLE
link_error not working with class based tasks

### ISSUE THREAD

**Issue by WoaDmulL** [celery/celery#4637]
Tested with the `4.2.0rc2` version.

## Steps to reproduce
Set the `link_error` of any task with a class based task and make sure the executed task will fail so the callback would be called.

## Expected behavior
Work?

## Actual behavior
The callback is not executed and an exception is raised ( AttributeError ).
`object has no attribute '__header__'`

Related to/duplicate of #4377

**Comment by auvipy** [comment]
I reopened the older #4377 lets continue there
