### ISSUE TITLE
Cant Use Any Functionality When Workers Busy 

### ISSUE THREAD

**Issue by hakanEdico** [celery/celery#4641]
Celery Version 4.1.0
Broker: RabbitMQ through CloudAMQP service 

I have a few nodes that are running Celery workers like so: 
`celery -A tasks worker -Q tasks,other -c 1 --without-heartbeat --loglevel=warning --logfile=/var/log/celery/celery.log`

I added the --without-heartbeat as to limit the number of messages sent, as I am using a free shared server through CloudAMQP currently. The -c 1 is to limit each server to only running one job (hardware limitations). 

All Config Options:
```
task_default_queue = 'tasks'
task_acks_late = False
worker_prefetch_multiplier = 1
broker_pool_limit = 1 
broker_heartbeat = None
broker_connection_timeout = 30 
event_queue_expires = 60
worker_send_task_events = True
```

When I am running 2-3 nodes like this, then I try to run any other Celery command
e.g. `celery -A tasks inspect active` 
The process hangs, and I am unable to even ctrl-c it. 

Same goes for running Flower. When I run the command, I get some stdout saying its connected, and that its available at localhost:5555, but I cannot actually connect to the website. Also the process hangs just like any other. 

Now I am not sure if the same behavior exists when the workers are free, because they are running important processes that I can not kill. I'm guessing these problems are due to either the concurrency option or the heartbeat. Haven't seen any other issues with people having similar problems, so any help is appreciated!

**Comment by russoz** [comment]
@hakanEdico as far as I recall (not using celery for that long either), inspecting requires sending AMQP messages. If that is true, then my guess would be that your problem might be in the
`broker_pool_limit = 1`

...
it made more sense when I though about it than now that I wrote it. Anyways, I would give it a try.

Make sure to read:
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_pool_limit
