### ISSUE TITLE
isort is not deterministic

### ISSUE THREAD

**Issue by thedrow** [celery/celery#4649]
@auvipy encountered a situation where isort did not sort imports in a way that we expect and thus #4647 failed.
We need to investigate and ensure isort is deterministic.

**Comment by auvipy** [comment]
yes important

**Comment by jackdbernier** [comment]
If it's worth it, I've noticed in the past some behaviors where specifying known_standard_library, known_third_party, or known_first_party would solve some weird isort behaviors. I do not know the exact cause. See https://github.com/timothycrosley/isort/wiki/isort-Settings.
