### ISSUE TITLE
how to set result expire time??

### ISSUE THREAD

**Issue by wsqy** [celery/celery#4656]
celery：4.1
RESULT_BACKEND: redis
django-celery-results:1.0.1

**Comment by jackdbernier** [comment]
Are you using redis or django as a result backend? "RESULT_BACKEND: redis" is conflicting with "django-celery-results:1.0.1" or do you mean redis is your broker?

You should be able to pass this setting http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-result_expires or the django settings equivalent CELERY_TASK_RESULT_EXPIRES (http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings)
