### ISSUE TITLE
Bind Tasks to Queues on consumer

### ISSUE THREAD

**Issue by shanzo** [celery/celery#4657]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

   celery==4.1.0

- [x] I have verified that the issue exists against the `master` branch of Celery.

   Seems like a configuration issue probably??

## Steps to reproduce

celery version
celery==4.1.0

Is is possible to restrict queue to specific tasks like with decorators?

Assuming i have predefined 

Exchange   | Queue | RoutingKey
exchangeX | queueX | routingKeyX
exchangeY | queueY | routingKeyY

exchanges are declared as passive=True and queues as no_declare=True to not declare them in the celrey app config. 

assuming i have 2 tasks registered in workerA

task1() => queueX
task2() => queueY 

and its consuming queueX and queueY.

workerB is restricted to use queueX for sending tasks using app.send_task('task1', queue='queueX', exchange='exchangeX', routing_key='routingKeyX', .... ) 

workerB sends task (task1) to queueX and workerB receives it and it is processed. 
workerB sends task (task2) to queueX.

## Expected behavior
workerB discards it.

## Actual behavior
workerB processes it.

I saw manual routing option but assuming if i am not using manual routing, is there any way that i bind task to specific queue or queues only using decorators etc.

just to confirm conceptually the routes that are defined are using by sender of task right? in my case workerB ???

Thanks for all the help. Its my first time here so my apologise if i didn't format the information correctly.

**Comment by auvipy** [comment]
try 4.2rc2 and see what happen

**Comment by shanzo** [comment]
We need to use 4.1.0. We can use any other version than this one.
