### ISSUE TITLE
Task.retry() always raises RuntimeError if task_always_eager and task_eager_propagates are set

### ISSUE THREAD

**Issue by lpsinger** [celery/celery#4661]
`Task.retry()` always raises a `RuntimeError` if `task_always_eager` and `task_eager_propagates` are set to `True`. This is counterintuitive. I would expect this example to work:

```python
from celery import Celery

app = Celery(__name__,
             config_source=dict(task_always_eager=True,
                                task_eager_propagates=True))

@app.task(bind=True, default_retry_delay=1, max_retries=None, shared=False)
def foo(self, i):
    if i <= 0:
        return 'Task succeeded!'
    else:
        self.retry((i - 1,))


foo.delay(3)
```

But instead it raises this error:

```
Traceback (most recent call last):
    ...
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

This can be reproduced on master and with 4.2.0rc2.

**Comment by javiermatos** [comment]
I upgraded celery from version 4.1.1 to 4.2.0 and I have that error when `task_always_eager` and `task_eager_propagates` are `True`. I am not using retry.

I created a decorator to make synchronous calls:

```python
def sync_task(func):
    def func_wrapper(*args, **kwargs):
        promise = func.apply_async(args, kwargs, serializer='dill')  # with dill serializer we allow olt_manager models
        return promise.get(timeout=settings.CELERY_GET_TIMEOUT)
    return func_wrapper
```
and after that I use it the following way:

```python
@sync_task
@shared_task
def myfunction(...):
    ...
```

I need to make tasks synchronous as they deal with an external hardware and I am using Celery as a queue with just one processor to ensure requests are processed in order and one at a time.

**Comment by auvipy** [comment]
so this is a regression

**Comment by joekohlsdorf** [comment]
Also happens on 4.2.1.

**Comment by untitaker** [comment]
since this is marked with the 4.3 milestone, I want to note that this still happens with 4.3. Please let me know if you require additional information or a clean repro case.

**Comment by auvipy** [comment]
re-milestoning for 4.5

**Comment by jarussi** [comment]
I had the same issue, but I only use always_eager for tests. I made a workaround with mock that allows you to run your tests on version `4.3.x`

```python
from unittest import mock

with mock.patch(
    'celery.app.task.denied_join_result'
) as mocked_task_join_will_block:
    mocked_task_join_will_block.__enter__.return_value = None

    # run your task as you wish...
```

Hope this helps someone.

**Comment by georgepsarakis** [comment]
https://github.com/celery/celery/blob/5385298f5c2f498841a6670115151a5111389337/celery/app/task.py#L720-L723

If I am not mistaken since `.apply` is eager, `.get` is not required. Could someone test this patch?

**Comment by hedleyroos** [comment]
Inspired by @jarussi you can simplify the workaround to:

```
@patch("celery.app.task.denied_join_result")
class MyTest(TestCase):
    def test_foo(self, mocked_join_result):
        ...
```
Now you can apply it to the entire test case in one shot. The `__enter__` lookup is lazily created by mock, so no need to explicitly set it to return None since that is the default behaviour.

**Comment by fazlerabby7** [comment]
This PR https://github.com/celery/celery/pull/6109 resolves this issue as well.
