### ISSUE TITLE
calling taks hangs for ever when the broker is down

### ISSUE THREAD

**Issue by ravimaharjan** [celery/celery#4663]
I am calling the celery tasks by task.delay, task.appy_asyn or send_task but each of these methods hang for ever when the broker is not started. I am using celery version 4.1.0. 
I thought the action would expire and throw exception after default timeout. Is there any way to stop the application waiting for ever. 
I also specified the retry_policy parameters while calling tasks but they do not make any difference.

**Comment by russoz** [comment]
@ravimaharjan 

As far as I can tell:
https://github.com/celery/celery/blob/3fe5a20ca655aa3aeed60205b39ede2a21845df0/celery/app/base.py#L728

the parameter **expires** is passed through directly to the AMQP broker. The broker is responsible for expiring the message, this expiration does not happen on the application side. I am not in the celery development team, but from where I stand it makes little sense to re-implement this functionality in the application side. Celery was designed to work **with** a broker.

You might want to try and search for an AMQP client-side queueing solution, but it strikes me as an odd solution: to implement a queue, to queue the messages that your queue server cannot take.

**Comment by drmclean** [comment]
Putting this:

```
BROKER_TRANSPORT_OPTIONS = {"max_retries": 3, "interval_start": 0, "interval_step": 0.2, "interval_max": 0.5}
```

In your celery config ought to fix this issue. (#4627 for details)

**Comment by auvipy** [comment]
closing as dup of #4627
