### ISSUE TITLE
Celery beat picks up tasks when CELERY_ALWAYS_EAGER=True

### ISSUE THREAD

**Issue by plantfansam** [celery/celery#4664]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Summary

I'm new to `celery` and `celery beat`, and this doesn't seem like _un_-expected behavior, but I think the docs for `celery beat` ought to note that the `celery beat` process will pick up work if `CELERY_ALWAYS_EAGER=True`. I had a hard time figuring out why `beat` was executing scheduled tasks when [starting the scheduler](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#starting-the-scheduler) suggests that the only way to combine `beat` and `worker` was with `celery -A proj worker -B`. I'd also consider throwing something in during the `beat` service's startup log — this was a hard one to track down 😜. For anyone out there trying to figure this one out, just set `CELERY_ALWAYS_EAGER=False`.

## celery report
```
$ celery -A repro report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

BROKER_URL: 'redis://localhost:6379//'
CELERY_ALWAYS_EAGER: True
```

## Steps to reproduce

Define `repro.py` as follows:

```python
from celery import Celery
from celery.schedules import crontab

app = Celery('tasks', broker='redis://localhost//')
app.conf.CELERY_ALWAYS_EAGER=True
@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    # Calls test('hello') every 10 seconds.
    sender.add_periodic_task(10.0, test.s('hello'), name='add every 10')

@app.task
def test(x):
    print(x)
```

Then, run `celery -A repro -l debug beat`

## Expected behavior
Celery beat puts work in broker queue to be executed by worker.

## Actual behavior
Celery beat executes tasks synchronously.

**Comment by russoz** [comment]
From:
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_always_eager

> task_always_eager
> Default: Disabled.
> 
> If this is True, all tasks will be executed locally by blocking until the task returns. apply_async() and Task.delay() will return an EagerResult instance, that emulates the API and behavior of AsyncResult, except the result is already evaluated.
> 
> That is, tasks will be executed locally instead of being sent to the queue.

Unless I missed anything, it looks like this is celery working as designed.

**Comment by handlers** [comment]
Yeah, I think it is definitely celery working as designed, but it felt weird to have celery beat picking up work synchronously, since celery beat's role (as I understand it) is just to put work into the queue on a schedule. I basically never expected celery beat to pick up work.

**Comment by ljhwdev** [comment]
I came across this today. There are 2 issues:
1) Celery beat can pick up historic scheduling from the celerybeat-schedule file (configured via the -s command line argument) if the tasks/scheduling haven't changed. Delete this file (or delete database entries if using a database) and beat will not run spurious tasks at startup.
2) !DO NOT! use Celery EAGER settings to address this issue. These are designed for testing where you might not have active Celery workers running during unit tests.

**Comment by agalazis** [comment]
@ljhwdev  existing celerybeat-schedule file was indeed what caused the confusion in my case
@auvipy  There is no apparent mention in :
https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html
