### ISSUE TITLE
revoke is not working in nested chord task

### ISSUE THREAD

**Issue by JioHooney** [celery/celery#4667]
header =  // nested chain and group
chord_task = chord(header)(callback)
result = chord_task.get()

I want to quit running TASK.

What i tried...
```
from <my app>.celery import app

app.control.revoke(task_id = chord_task_id )   # ---> not working
app.control.revoke(task_id = chord_task_id, terminate=True )   # ---> not working
app.control.revoke(task_id = chord_task_id, terminate=True, signal='SIGTERM' )   # ---> not working
app.control.revoke(task_id = chord_task_id, terminate=True, signal='SIGKILL' )   # ---> not working

```

How can i cancel for executed chord task ?

**Comment by youguanxinqing** [comment]
so, any solutions ?

**Comment by mufaddal12** [comment]
you need to terminate all running tasks in the chord manually. I wanted to stop using chord id itself but it doesn't work that way.

**Comment by p1003** [comment]
> you need to terminate all running tasks in the chord manually. I wanted to stop using chord id itself but it doesn't work that way.

How do I get ids of those tasks?
