### ISSUE TITLE
MongoDB backend does not support mongodb+srv:// URL's

### ISSUE THREAD

**Issue by bertjwregeer** [celery/celery#4668]
## Checklist

https://github.com/celery/celery/blob/master/celery/backends/mongodb.py#L143-L146

## Steps to reproduce

Set the MongoDB URL to one like:

```mongodb+srv://mongo.private.corp.example.com/celery?ssl=false```

## Expected behavior

This works.

## Actual behavior

This fails because the URL parsing does not match on `mongodb+srv://` instead trying to match `mongodb://` only.

**Comment by georgepsarakis** [comment]
Could you please elaborate on the proposed URL format? Some references would be nice as well.

**Comment by bertjwregeer** [comment]
@georgepsarakis it's documented here: https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format

**Comment by bertjwregeer** [comment]
Has there been any movement on this at all?

**Comment by thedrow** [comment]
It's going to be part of 4.3.
