### ISSUE TITLE
Open celery tasks in diffrent virtualenv?

### ISSUE THREAD

**Issue by arossert** [celery/celery#4683]
I want to use celery in my project and I need that the celery tasks (subprocesses) will run in a diffrent python virtualenv.
I noticed that there is an `--executable` flag but it will change the executable for all celery processes (main and tasks).
If this feature is not exeists I'm willing to put some work to add this but need some guidance on where to begin with.

**Comment by arossert** [comment]
I have played with the celery source code and documentation and found some stuff that can do what I want but I can't get it to work.

The default celery behavior when opening a worker is to `fork` a clone process, from the documentation [here](http://docs.celeryproject.org/en/latest/userguide/security.html#worker), it stated that this can be changed to `fork + execve` but I can't see how.

Going over the source code of celery and billiard (celery multiprocess library) there are a couple of modules to open a child process:
- popen_fork
- popen_forkserver
- popen_spawn_posix
- popen_spawn_win32

The one that celery is using is `popen_fork`, I have tried to change it to `popen_spawn_posix` by changing celery source code (I can't find any option or configuration for that) but this does not work.

Can anyone give me some direction on how I can achieve this? I want to be able to do `fork + execve` and give the `ececve` argument to lunch the same python file but under different python virtualenv.

**Comment by mjmonroe** [comment]
Running different processes of the same program, Celery, in different Python environments does not seem like a good idea. Signal handlers and cross process communications will not necessarily work as expected. One Celery process could be running Python 2.5 while another is running in Python 3.6.

You might want to re-think your requirement to have different Python processes from the same application run in different environments. One thing you can do is pass an env argument to a `subprocess.Popen`, and launch another application from a Celery Task in its own process and environment. Then the different environments are explicitly separated.

**Comment by thedrow** [comment]
I suggest that you either avoid doing so, or create specific workers and queues for each virtualenv you have.

**Comment by arossert** [comment]
@thedrow, one more question. 
Fro the celery security section here http://docs.celeryproject.org/en/latest/userguide/security.html it stated that it is more secure it open each worker in subprocess using ‘fork’ + ‘execve’. 

How can this be configured?

**Comment by thedrow** [comment]
I'm not sure actually.

**Comment by aiqc** [comment]
this is attractive because tensorflow cannot be imported on multiple processes in the same env
