### ISSUE TITLE
Librabbitmq 2.0.0 with Python 3 gives TypeError: can't pickle memoryview objects

### ISSUE THREAD

**Issue by somghosh** [celery/celery#4693]
I am using the latest master branch of the git repo https://github.com/celery/librabbitmq and installing `librabbitmq==2.0.0` for Python 3.6 by following the instructions in the readme

## Using the development version

You can clone the repository by doing the following:

	$ git clone git://github.com/celery/librabbitmq.git

Then install it by doing the following:

	$ cd librabbitmq
	$ make install        # or make develop

This works fine (after installing certain binaries for c compliation in the OS), but when I then make a small `a+b` add task and call it with `add.delay(2,2)` it fails with the following error. I looked up and saw that Celery 4 uses json as serializer, so clearly it is not because if pickle serialization

1. Changing from librabbitmq to pyamqp broker works normally
2. Same exact situation in both MacOS and Ubuntu 16

> 	[2018-04-30 23:40:02,956: CRITICAL/MainProcess] Unrecoverable error:
> SystemError('<built-in method _basic_recv of Connection object at
> 0x1099ec5e8> returned a result with an error set',) 	Traceback (most
> recent call last): 	  File
> "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/kombu/messaging.py",
> line 624, in _receive_callback
> 	    return on_m(message) if on_m else self.receive(decoded, message) 	  File
> "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/consumer/consumer.py",
> line 570, in on_task_received
> 	    callbacks, 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/strategy.py",
> line 145, in task_message_handler
> 	    handle(req) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/worker.py",
> line 221, in _process_task_sem
> 	    return self._quick_acquire(self._process_task, req) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/kombu/async/semaphore.py",
> line 62, in acquire
> 	    callback(*partial_args, **partial_kwargs) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/worker.py",
> line 226, in _process_task
> 	    req.execute_using_pool(self.pool) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/request.py",
> line 531, in execute_using_pool
> 	    correlation_id=task_id, 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/concurrency/base.py",
> line 155, in apply_async
> 	    **options) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/billiard/pool.py",
> line 1486, in apply_async
> 	    self._quick_put((TASK, (result._job, None, func, args, kwds))) 	  File
> "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/concurrency/asynpool.py",
> line 813, in send_job
> 	    body = dumps(tup, protocol=protocol) 	TypeError: can't pickle memoryview objects
> 
> 	The above exception was the direct cause of the following exception:
> 
> 	Traceback (most recent call last): 	  File
> "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/worker.py",
> line 203, in start
> 	    self.blueprint.start(self) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/bootsteps.py",
> line 119, in start
> 	    step.start(parent) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/bootsteps.py",
> line 370, in start
> 	    return self.obj.start() 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/consumer/consumer.py",
> line 320, in start
> 	    blueprint.start(self) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/bootsteps.py",
> line 119, in start
> 	    step.start(parent) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/consumer/consumer.py",
> line 596, in start
> 	    c.loop(*c.loop_args()) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/celery/worker/loops.py",
> line 88, in asynloop
> 	    next(loop) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/kombu/async/hub.py",
> line 354, in create_loop
> 	    cb(*cbargs) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/kombu/transport/base.py",
> line 236, in on_readable
> 	    reader(loop) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/kombu/transport/base.py",
> line 218, in _read
> 	    drain_events(timeout=0) 	  File "/Users/somghosh/.virtualenvs/ctdb/lib/python3.6/site-packages/librabbitmq-2.0.0-py3.6-macosx-10.6-intel.egg/librabbitmq/__init__.py",
> line 227, in drain_events
> 	    self._basic_recv(timeout) 	SystemError: <built-in method _basic_recv of Connection object at 0x1099ec5e8> returned a result with an error set

**Comment by auvipy** [comment]
in the mean time use py-amqp, it's the recommended package for now

**Comment by somghosh** [comment]
Thanks that's what I'm doing but is it true that issuing librabbitmq gives performance gain? Celery optimisation tricks page say this but maybe this is not true any more?

**Comment by auvipy** [comment]
yeah thats not true anymore

**Comment by guilhermemauro** [comment]
Works for me on Dokku Container

**Comment by cyzanfar** [comment]
same problem here using librabbitmq 2.0.0

```
Traceback (most recent call last):
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 145, in fire_timers
    entry()
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 478, in apply_eta_task
    self.on_task_request(task)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/worker/request.py", line 551, in execute_using_pool
    correlation_id=task_id,
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/concurrency/base.py", line 155, in apply_async
    **options)
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/billiard/pool.py", line 1530, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
  File "/Users/cyrusghazanfar/Desktop/startup-studio/pilota_project/FDMS/venv/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 819, in send_job
    body = dumps(tup, protocol=protocol)
TypeError: can't pickle memoryview objects
```

**Comment by ChrisBurch** [comment]
For anyone stumbling across this issue, changing my broker url from `amqp://`  to `pyamqp://` solved the issue for me. I guess that forced usage of py-amqp over librabbitmq?

**Comment by ritiko** [comment]
Depending on your error, this may fix it
https://github.com/celery/librabbitmq/issues/118#issuecomment-471002901

> To compile the C library you need cmake, libtool and autoconf. I think that is all the packages. If you can clone https://github.com/alanxz/rabbitmq-c and build it then this will compile correctly.

**Comment by SeyyedKomeil** [comment]
> For anyone stumbling across this issue, changing my broker url from `amqp://` to `pyamqp://` solved the issue for me. I guess that forced usage of py-amqp over librabbitmq?

thanks. it works for me too

**Comment by dmick** [comment]
So....is using librabbitmq deprecated now?  I can't tell what the resolution of this issue is

**Comment by dmick** [comment]
...in fact, why is this closed, when it apparently wasn't resolved?

**Comment by auvipy** [comment]
please use py-amqp project with cython instead of this.

**Comment by dmick** [comment]
Are there plans to remove the recommendation to use librabbitmq from the Celery docs?  As far as I can tell, even on the master docs branch, librabbitmq is the preferred approach, which seems to be in conflict with things @auvipy and @thedrow have said in several issue threads, but not yet in the official documentation

**Comment by auvipy** [comment]
you might not see https://github.com/celery/celery/pull/6933/files and more doc clean ups
