### ISSUE TITLE
Question: `raise self.retry(....)` OR `self.retry(...)`? 

### ISSUE THREAD

**Issue by wjehenddher** [celery/celery#4705]
Hello:

**Silly question**

Documentation states:
http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying

```python
except Exception as exc:
    raise self.retry(exc=exc)
```

Many tutorials and bloggers state (google celery retry example):

```python
except Exception as exc:
    self.retry(exc=exc)
```
https://stackoverflow.com/questions/9731435/retry-celery-tasks-with-exponential-back-off
https://medium.com/@dwernychukjosh/retrying-asynchronous-tasks-with-celery-221acd385d34
https://blog.balthazar-rouberol.com/celery-best-practices

### Is the `raise` required or not? 
Or

**Comment by erdnaxeli** [comment]
> is the raise required or not?

Not.  As the doc says: 

> Although the task will never return above as `retry` raises an exception to notify the worker, we use `raise` in front of the retry to convey that the rest of the block won't be executed.

> Does it matter?

It's part of your coding style. I agree with the doc, putting a `raise` before `self.retry()` is more explicit.

**Comment by RamonGiovane** [comment]
If I use raise `self.retry(exc=exc) ` with `exc` being a custom exception, it throws: `TypeError: exceptions must derive from BaseException`. So I'm not using `raise` for this.
