### ISSUE TITLE
How to dynamically add periodic tasks

### ISSUE THREAD

**Issue by storyicon** [celery/celery#4711]
Celery is an excellent project, but there are some confusions when I use it:
How to dynamically add periodic tasks

./period.py
```python
app = Celery(
    'test',
    Broker='redis://localhost:6379/0',
)
@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
        print("add task")
        sender.add_periodic_task(schedule=10.0, sig=func.s(arguments), name="test")
```

If I'm not mistaken, adding schedule tasks dynamically requires this, and I need to execute the following command at the command line:
```bash
celery -A period worker --loglevel=info
celery -A period beat -l info
```
However, when these two commands are executed, "add tast" is output respectively.

This means that the command "celery -A period worker --loglevel=info" will execute setup_periodic_tasks, and the command "celery -A period beat -l info" will also execute setup_periodic_tasks again.

I now have a table of schedulers. At present, there are more than 2000 records. When the program is running, I hope to add it dynamically to the periodic task of Celery, but execute "celery -A period worker --loglevel=info" and execute " "celery -A period beat -l info" will scan the table again and I think this is not normal

May I ask how to amend or have a better way to solve it?

**Comment by bluewhale8202** [comment]
I'm not sure if I have understood your needs correctly but how about adding a periodic task that check if there is a new periodic task to add and add it if there is?

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
        sender.add_periodic_task(schedule=3600, sig=check_and_add_periodic_tasks.s(), name="test")

@app.task(bind=True)
def check_and_add_periodic_tasks(self):
        # Get new periodic tasks somehow
        new_tasks = get_new()
        for schedule, sig, name in new_tasks:
             self.add_periodic_task(schedule=schedule, sig=sig, name=name)

I'm only a beginner user of celery, so don't take my words too seriously

**Comment by storyicon** [comment]
Thank you very much for your answer, but after testing it did not solve my problem
A few days ago, I used golang to refactor the code and used "github.com/robfig/cron" to solve my problem. It improved the performance of my project by a factor of 100.

**Comment by storyicon** [comment]
@bluewhale8202

**Comment by rzlmma** [comment]
Hi，I have the same problem. Can you explain your solution in detail?

**Comment by JoshAudibert** [comment]
I also would like to call add_periodic_task from within another task. Is this possible?

**Comment by dlernstrom** [comment]
@JoshAudibert - this is how we do it...
```python
from celery import current_app
current_app.send_task('appname.tasks.this_is_my_task', (args1, args2, etc,))
```

**Comment by thedrow** [comment]
> 
> 
> I also would like to call add_periodic_task from within another task. Is this possible?

I'm not sure anyone has ever tried. Try it and let me know :)
