### ISSUE TITLE
Celery Error: Received unregistered task of type 'task'

### ISSUE THREAD

**Issue by 96street** [celery/celery#4716]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery. - I am not running celery through the main module (`draft1`), but through my `post` module. (not sure if this is what this checklist is asking for)

I'm getting the following error in my celery log:

    [2018-05-04 23:33:42,186: ERROR/MainProcess] Received unregistered task of type 'test_post'.
    The message has been ignored and discarded.
    
    Did you remember to import the module containing this task?
    Or maybe you're using relative imports?
    
    Please see
    http://docs.celeryq.org/en/latest/internals/protocol.html
    for more information.
    
    The full contents of the message body was:
    '[[], {}, {"callbacks": null, "errbacks": null, "chord": null, "chain": null}]' (77b)
    Traceback (most recent call last):
      File "/home/james/postr/env/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", li$
        strategy = strategies[type_]
    KeyError: 'test_post'

`post_jobs` is my only celery task, and it's in another module (not my main app module), which may be why I'm encountering this problem. I was forced to do this as my model could not be imported from the main app. My celery conf looks like this (`post` is not the main module):

    [program:postr-celery]
    command=/home/james/postr/env/bin/celery -A post worker --loglevel=INFO
    directory=/home/james/postr
    user=james
    numprocs=1
    stdout_logfile=/var/log/supervisor/celery.log
    stderr_logfile=/var/log/supervisor/celery.log
    autostart=true
    autorestart=true
    startsecs=10
    
    ; Need to wait for currently executing tasks to finish at shutdown.
    ; Increase this if you have very long running tasks.
    stopwaitsecs = 600
    
    stopasgroup=true

I can successfully receive the task:

https://i.stack.imgur.com/gIawm.png

however when I start my celery beat via `celery -A draft1 beat`:

https://i.stack.imgur.com/ey1F1.png

my celery log returns the error (`Received unregistered task of type 'test_post'`):

I've tried starting celery beat via `celery -A post beat` instead however it doesn't change anything. 

My settings looks like this:

    CELERY_BROKER_URL = 'amqp://{}:{}@174.138.62.249/vhost'.format(config('RABBIT_USER'), config('RABBIT_PW'))
    CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"
    CELERYBEAT_SCHEDULE = {
        'test_post': {
            'task': 'post.tasks.test_post',
            'schedule': crontab(minute=40),
        }
    }

post/tasks.py

    @app.task
    def test_post():
        from .models import Post
        for i in Post.objects.all():
            if i.entered_category == "test":
                i.entered_category = "not_test"
                i.save()
        return HttpResponseRedirect('/')

post/celery.py

    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'draft1.settings')
    app = Celery(broker=CELERY_BROKER_URL)
    app.config_from_object('django.conf:settings', namespace='CELERY')
    app.autodiscover_tasks()

draft1/celery.py

    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'draft1.settings')
    app = Celery("draft1", broker=CELERY_BROKER_URL)
    app.config_from_object('django.conf:settings', namespace='CELERY')
    app.autodiscover_tasks()

Any idea why I'm getting the error and how I can fix it?

**Comment by tyan4g** [comment]
is there pycache here..
use py3clean or pyclean command in your work directory to clear all cache.

then, is there's a dependences not install using pip?
will get the error too.

**Comment by NogerbekNurzhan** [comment]
@96street hello! Do you solve this problem? I have the same problem and don't know how to fix it.

**Comment by auvipy** [comment]
versions using?

**Comment by NogerbekNurzhan** [comment]
@96street I solve my problem few  days ago. Thank you anyway. [Here ](https://github.com/celery/celery/issues/4794)is the full explanation of the problem.

**Comment by auvipy** [comment]
can we close this?

**Comment by wzxJayce** [comment]
thank you bro~

**Comment by sebbekarlsson** [comment]
what was the solution?

**Comment by JediKnightChan** [comment]
`py3clean .` worked great!

**Comment by lexuancuong** [comment]
I solved this issue by add `include`, like:
`celery_app = Celery(
    'worker',
    broker='....',
    include=['app.xxx.yyy', 'app.aaa.bbb']
)`
