### ISSUE TITLE
Document changes in task execution options introduced in #4709

### ISSUE THREAD

**Issue by georgepsarakis** [celery/celery#4721]
## Description

Pull Request #4709 introduced changes to `AsyncResult` public interface and `apply_async` task execution options. Also `AsyncResult.get()` behavior is changed for tasks with ignored result and is no longer blocking. In addition see this [comment](https://github.com/celery/celery/issues/4707#issuecomment-387283082).

**Comment by thedrow** [comment]
We should do this before GA.

**Comment by georgepsarakis** [comment]
@thedrow I will open a PR with the Changelog entries and the documentation additions shortly.
