### ISSUE TITLE
Testing subclasses of Task with redefined __call__ fails

### ISSUE THREAD

**Issue by imomaliev** [celery/celery#4732]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. Create subclass of Task with redefined ` __call__` which calls `super()`
2. Create bound task with this class
3. write tests with `celery_worker` fixture
4. `_task_stack` is empty

## Expected behavior
`_install_stack_protection` should be called in `TestWorkController.on_before_init` as well as in `WorkerController`
```python
from celery.app.trace import _install_stack_protection
from celery.contrib.testing.worker import TestWorkController

class ProtectedTestWorkController(TestWorkController):
    def on_before_init(self, quiet=False, **kwargs):
        # https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L606
        _install_stack_protection()
```

## Actual behavior
Sometimes it fails with random errors which are not saying anything about actual problem

**Comment by danield137** [comment]
A workaround for now would be to not call `super().__call__(*args, **kwargs)` and instead call 
`self.run(*args, **kwargs)`

**Comment by imomaliev** [comment]
@danield137 and what about stack handling? 
```
    def __call__(self, *args, **kwargs):
        _task_stack.push(self)
        self.push_request(args=args, kwargs=kwargs)
        try:
            return self.run(*args, **kwargs)
        finally:
            self.pop_request()
            _task_stack.pop()
```
