### ISSUE TITLE
AsyncResult.get() sleeping for 1 second when worker concurrency is high

### ISSUE THREAD

**Issue by taibende** [celery/celery#4733]
We've recently started using Celery for distributed computations. Each task lasts a few seconds, with the result being fetched by the task issuer from the backend as soon as it is available.

Our tests so far have taken place on a single Linux machine with one Celery worker, using RabbitMQ as the broker and Redis as the backend (all components are on the same machine).

After submitting 53 tasks through RabbitMQ using apply_async(), we are calling get() in a _for_ loop on a list of AsyncResult objects to fetch the results.

The Celery worker is started from within Python with something like the following code:

        p = multiprocessing.Process(
            target=app.worker_main,
            kwargs={
                'argv': ['worker', '-n', app_name.replace('-', '_') + '@%h',
                           '-E',
                           '-c', '[50 (or some other number here)]']
            }
        )
        p.daemon = True
        p.start()

Our problem is that as we increase the -c (--concurrency) option on the worker, the computations finish quicker, but the get() function becomes slower and slower at fetching results from the Redis backend.

By listening for 'task-succeeded' messages coming through the broker using a separate monitoring process, we've confirmed that increasing -c does improve the processing time. For example, when we set -c to 6, 12 and 50, the total time needed to receive all 53 task-succeeded messages (with results) is 14.5 seconds, 12.3 seconds and 6.9 seconds respectively.

However, if we run get() in a _for_ loop to fetch all the results, the total running time is 19.1 seconds for 6 child processes, 19.4 seconds for 12 child processes, and **51.7**(!) seconds for 50 child processes. We dug deeper into the exact times when each get() succeeds. For 6 worker child processes, below is a list of timestamps when get() succeeds. The first ten and last ten times are included:

1526361605.2336624
1526361605.442445
1526361605.9021978
1526361606.433369
1526361606.5423493
1526361606.8964653
1526361607.0636003
1526361607.7047405
1526361607.9823422
1526361608.0684745
...
1526361618.2120564
1526361618.280207
1526361618.8815565
1526361618.9758325
1526361619.3499904
**1526361620.3514884
1526361621.3524063
1526361622.35393
1526361623.3554215
1526361624.356973**

Initially, it takes well less than a second between successful get() calls, but for the final five results, the time interval becomes almost **exactly** 1 second. As we change the number of child processes (call this number _n_), in general the final _n_ get() calls will have a one-second time interval between them. When n=50, the amount of time waiting for all the get() calls to finish already dwarfs the amount of time spent doing calculations.

We are currently doing more extensive experiments with a multi-machine setup, and plan to update this post with some example code to reproduce the issue soon, but it seems like we might be missing something obvious with our configuration. Are any experienced Celery users able to give some hints as to which settings to change or further tests we should do?

At the moment, Celery 4.1.0 is running on an Ubuntu 14.04 machine with

- Python 3.6.3
- Redis 2.8.4
- RabbitMQ 3.2.4

Some selected Python module versions that may be relevant:

- amqp==2.2.2
- billiard==3.5.0.3
- celery==4.1.0
- kombu==4.1.0
- redis==2.10.6

**Comment by taibende** [comment]
Hey George,

Thanks for the response. My test server has 6 cores (12 threads), which do saturate if the number of worker child processes is too high.

However, we have confirmed that the problem is with Redis (or Celery's interface to Redis), as we have tried switching the backend to memcached and are not seeing this problem with slow AsyncResult.get() calls towards the end.

We have tested the latest version of Redis (4.0.9), but that also has this problem. We are investigating the possibility that the Python redis library is causing this issue. If anyone has recommendations on how to configure Redis or the Python redis library (v. 2.10.6), any pointers would be appreciated.

**Comment by georgepsarakis** [comment]
- Have you also [hiredis](https://github.com/andymccurdy/redis-py#parsers) installed? It improves efficiency by speeding up response message parsing.
- Although not very likely to help in your case, the latest `master` includes several fixes on the Redis backend, mostly concerning the use of channels.

Let me know if any of these help.

**Comment by taibende** [comment]
I've just checked the latest version of Celery master (4.2.0rc3) against Redis.

It appears that something was changed between 4.1.0 and the current version, and this issue no longer exists!

Here is some code to reproduce the issue if anyone is interested (simply run the code and change the `use_get_without_state_check` variable from `True` to `False` to see it slow down.

```
import multiprocessing
from celery import Celery
import time

# How many tasks to try
num_attempts = 200
# concurrent worker child processes
cwcp = 24
# Collect AsyncResult objects in a list
tasks_list = []
# Use get() directly without checking for task state first
use_get_without_state_check = True

# Function to be executed by Celery worker
def sum_function(*args):
    time.sleep(1)
    return sum(args)

# Start Celery worker process and add task
def start_celery():
    # Assume server has RabbitMQ and Redis already installed and listening
    # Create a Celery worker
    app = Celery("my_app_name", broker="amqp://",
                                #backend="cache+memcached://")
                                backend="redis://")
    # Add and register task
    task = app.task(name="tasks." + sum_function.__name__)(sum_function)
    app.tasks.register(task)
    # Start process
    p = multiprocessing.Process(
        target=app.worker_main,
        kwargs={
            'argv': ['worker', '-E', '-c', str(cwcp)]
        }
    )
    p.daemon = True
    p.start()
    return app

if __name__ == "__main__":
    app = start_celery()
    for i in range(num_attempts):
        tasks_list.append(
            app.send_task('tasks.' + sum_function.__name__,
                          args=[1, 2],
                          kwargs={}
            )
        )
    print("%s tasks submitted" % len(tasks_list))
    get_finished_timestamps = {}
    result_fetch_start_time = time.time()
    results_count = [0]*num_attempts
    while sum(results_count) < num_attempts:
        for i in range(len(tasks_list)):
            if use_get_without_state_check:
                results_count[i] = 1
                res = tasks_list[i].get()
                assert(res == 3)
                get_finished_timestamps[i] = time.time()
            else:
                if tasks_list[i].state == "SUCCESS":
                    results_count[i] = 1
                    res = tasks_list[i].get()
                    assert(res == 3)
                    get_finished_timestamps[i] = time.time()
        # sleep to stop CPU spinning all the time
        time.sleep(0.1)

    # print out timestamps when get() calls were finished
    for k in sorted(get_finished_timestamps, key=get_finished_timestamps.get):
        print(k, get_finished_timestamps[k])

    # Display total get() time
    result_fetch_end_time = time.time()
    print("%s secs to fetch" %
              (result_fetch_end_time - result_fetch_start_time))
```

On my 6-core (Ryzen 5 1600) machine with 16 GB RAM running Ubuntu 16.04 and Python 3.5.2, I am getting the following results:

**Celery 4.1.0 + Redis 3.0.6 (client redis 2.10.6, hiredis 0.2.0):**
use_get_without_state_check == True: 29.63 seconds
use_get_without_state_check == False: 18.74 seconds

**Celery 4.2.0rc3 + Redis stack above**
use_get_without_state_check == True: 18.62 seconds
use_get_without_state_check == False: 17.77 seconds

The timings for memcached, for comparison:

**Celery 4.1.0 + memcached 1.4.25 (client pylibmc 1.5.2)**
use_get_without_state_check == True: 10.66 seconds
use_get_without_state_check == False: 10.72 seconds

**Celery 4.2.0rc3 + memcached stack above**
use_get_without_state_check == True: 10.66 seconds
use_get_without_state_check == False: 10.65 seconds

Since our requirements are fairly basic and we have no need for Redis's more advanced features, I'm inclined to stick with memcached for now.

**Comment by SamFerwerda** [comment]
I am having the exact same problem now with celery version 4.4, broker AMQP and result_backend RPC..

Is there anyway to fix this issue?

**Comment by thedrow** [comment]
Since the OP cannot reproduce the issue anymore you're likely to have another issue.
Please open a new ticket or search for an existing open one that fits your problem.
