### ISSUE TITLE
Celery map handled by default queue

### ISSUE THREAD

**Issue by gasbasd** [celery/celery#4738]
When i use celery map, a task named celery.map is handled by default queue, i want to be handled by the queue who handle my task

example:
`celery_worker.conf.task_routes = {'ellipse.bankpipe.*': {'queue': 'bankpipe'}} `

when i schedule a task `simple_task`, defined inside `ellipse.bankpipe.*`, is correctly handled by bankpipe queue.
If i use `map()` on `simple_task` (`simple_task.map([1, 2, 3])`) the behaviour was different, a `celery.map` task is handled by default queue, `simple_task` correctly handled by `bankpipe` queue
<img width="1408" alt="untitled" src="https://user-images.githubusercontent.com/6060733/40121856-d0585404-5922-11e8-9710-4eda648936f8.png">

**Comment by auvipy** [comment]
ask your support questions to mailing lists or in irc.
