### ISSUE TITLE
celery 4.1 is broken after kombu 4.2 release

### ISSUE THREAD

**Issue by petrjasek** [celery/celery#4748]
it's duplicate of https://github.com/celery/kombu/issues/870, but in order to fix 4.1 I suggest creating a 4.1.1 release with kombu dependency set to `>=4,1,<4.2`

**Comment by thedrow** [comment]
I'm already working on it. See https://github.com/celery/celery/issues/4387#issuecomment-390564037
Thanks for the heads up :)

**Comment by petrjasek** [comment]
thank you!

**Comment by thedrow** [comment]
Released.
