### ISSUE TITLE
ImportError: No module named 'kombu.async'

### ISSUE THREAD

**Issue by alej0varas** [celery/celery#4749]
After a server deployment with no changes in the requirements cerely fails to run.

Celery version 4.1.0

## Steps to reproduce
$ celery worker --app core

## Expected behavior
celery to run without issue

## Actual behavior
ImportError: No module named 'kombu.async'

What I've found is that in `setup.cfg` kombu is required with "kombu >= 4.0.2". The release 4.2.0 of kombu renamed `kombu.async` to `kombu.asynchronous`.

In effect installing kombu==4.1.0 solves the issue

**Comment by auvipy** [comment]
yes there is and open pr to resolve this issue. wait for rc4
