### ISSUE TITLE
add_periodic_task Parameter is invalid

### ISSUE THREAD

**Issue by shencan** [celery/celery#4755]
## Checklist

##celery version
```
shencan@MacBook:~/TestCelery$ celery --version
4.1.1 (latentcall)
```

## Steps to reproduce
1.code directory structure
```
shencan@MacBook:~/TestCelery$ tree newceleryserver
newceleryserver
├── __init__.py
├── celeryconfig.py
└── tasks.py

```
2. ```__init__.py```  file
```
from __future__ import absolute_import
from celery import Celery
app = Celery('demo1')
app.config_from_object('newceleryserver.celeryconfig')
```

3. ```celeryconfig.py```  file
```
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/5'
BROKER_URL = 'redis://127.0.0.1:6379/6'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_IMPORTS = (
    'newceleryserver.tasks'
)
```

4. ```tasks.py```  file
```
from newceleryserver import app
@app.task
def test(a,b):
    print(a+b)
    return a+b
```

5.``` Start beat```
```
sudo celery -A newceleryserver beat -l debug

``` 
![image](https://user-images.githubusercontent.com/11796215/40355247-7ffe65dc-5de8-11e8-9968-caa9ce8ef194.png)

6.``` Start worker```
```
sudo celery -A newceleryserver worker -l debug
``` 
![image](https://user-images.githubusercontent.com/11796215/40355275-8f67ca86-5de8-11e8-9734-c8b9f8669b68.png)

7. ```client.py``` file  use ```add_periodic_task``` Parameter add task
```
from newceleryserver import app
from newceleryserver.tasks import test

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(10.0, test.s(2,3), name='periodic')

setup_periodic_tasks(app)

```

6. ```python client.py``` running normal
```
shencan@MacBook:~/TestCelery$ python client.py
shencan@MacBook:~/TestCelery$
```

**Comment by juannyG** [comment]
I believe that if you're trying to add a periodic task to the schedule **outside** of when `beat` is initialized **AND** while it's already running, you would need to update the data store where the tasks are being held. By default, they are persisted using python's `shelve` module - but if beat is running, you can't actually access the file - as the `beat` process effectively keeps a lock on it.
### With beat running
```
In [12]: with shelve.open('celerybeat-schedule') as db:
    ...:     print(list(db.keys()))
    ...:     print(list(db.values()))
    ...:     
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-12-7ef3ef79abe9> in <module>()
----> 1 with shelve.open('celerybeat-schedule') as db:
      2     print(list(db.keys()))
      3     print(list(db.values()))

~/.pyenv/versions/3.6.4/lib/python3.6/shelve.py in open(filename, flag, protocol, writeback)
    241     """
    242 
--> 243     return DbfilenameShelf(filename, flag, protocol, writeback)

~/.pyenv/versions/3.6.4/lib/python3.6/shelve.py in __init__(self, filename, flag, protocol, writeback)
    225     def __init__(self, filename, flag='c', protocol=None, writeback=False):
    226         import dbm
--> 227         Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
    228 
    229 

~/.pyenv/versions/3.6.4/lib/python3.6/dbm/__init__.py in open(file, flag, mode)
     92     else:
     93         mod = _modules[result]
---> 94     return mod.open(file, flag, mode)
     95 
     96 

error: [Errno 11] Resource temporarily unavailable
```

### Without beat running
```
In [23]: with shelve.open('celerybeat-schedule') as db:
    ...:     print(list(db.keys()))
    ...:     print(list(db.values()))
    ...:     
['__version__', 'utc_enabled', 'entries', 'tz']
['4.1.1', True, {}, None]
```
Even if you could, [based on the docs](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#using-custom-scheduler-classes), the default `PersistentScheduler` keeps a minimal amount of data: "*The default scheduler is the celery.beat.PersistentScheduler, that simply keeps track of the last run times in a local shelve database file.*" This would also imply that you have one shot to load the periodic schedule, and that's in memory when `celery -A app beat` is evaluating and configuring the app.

If you use [`django-celery-beat`](https://github.com/celery/django-celery-beat) - you should be able to achieve the functionality you're looking for: `This extension enables you to store the periodic task schedule in the database.`
