### ISSUE TITLE
Celery 4.0.2 broken by new kombu 4.2.0

### ISSUE THREAD

**Issue by thomas-riccardi** [celery/celery#4757]
Related to celery hotfix 4.1.1: the same incompatibility issue exists with celery 4.0.2 (and all 4.0).

Related links:
- https://github.com/celery/celery/issues/4387#issuecomment-390564037
- http://www.celeryproject.org/news/celery-411-hot-fix-releaesd/

Maybe issue a celery 4.0 hotfix with `kombu <4.2.0` ?

Also, why break things in a minor upgrade in kombu? why not bump its version to 5.0.0? This would have avoided all these hotfixes.

**Comment by auvipy** [comment]
either use 4.1 or 4.2. every version is a major release actually.

**Comment by thomas-riccardi** [comment]
> every version is a major release actually.

Are you talking about celery or kombu? If kombu, then the requirements.txt version constraint in celery should reflect that, shouldn't it?

**Comment by auvipy** [comment]
celery.

**Comment by auvipy** [comment]
if you have anything to offer please send a pr and lets discuss there.
