### ISSUE TITLE
Requesting access to update IRC #celery topic

### ISSUE THREAD

**Issue by xirdneh** [celery/celery#4759]
I've been helping around on IRC #celery. I would like to request permissions to update the channel's information since there's been a few questions about future releases.
Most of them have been answered.
My IRC handle is `josuebc`, thanks.
@thedrow @ask

**Comment by auvipy** [comment]
i think more core team member should get access

**Comment by thedrow** [comment]
I think only @ask has permission.

**Comment by thedrow** [comment]
I need to find the time to call him.

**Comment by xirdneh** [comment]
Any updates on this?
I know we're all busy only bumping as reminder.
Thanks.

**Comment by xirdneh** [comment]
Topic on the IRC channel has been updated.
Closing this...
