### ISSUE TITLE
Channels are not cleaned up when chord is used inside a task.

### ISSUE THREAD

**Issue by LasseGravesen** [celery/celery#4761]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      software -> celery:4.2.0rc4 (windowlicker) kombu:4.2.0 py:3.6.5
            billiard:3.5.0.3 redis:2.10.6
      platform -> system:Linux arch:64bit, ELF imp:CPython
      loader   -> celery.loaders.app.AppLoader
      settings -> transport:redis results:redis://localhost:6379/2

      broker_url: 'redis://localhost:6379/1'
      imports:
          ('utils.library',)
      result_backend: 'redis://localhost:6379/2'
      task_default_queue: 'default'
      task_queues:
          (<unbound Queue default -> <unbound Exchange ''(direct)> -> parent.#>,
       <unbound Queue children -> <unbound Exchange ''(direct)> -> child.#>)
      worker_max_tasks_per_child: 15
      worker_prefetch_multiplier: 2
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
See here: https://github.com/FalconSocial/Celery-Testing-LasseVG

## Expected behavior
The expected behaviour is that the channels are cleaned up, i.e. drop to 0 after the result has been retrieved. 

## Actual behavior
The actual behaviour is that the channels keep accumulating, as the main.py program is run. See this output:

    # with @app.task(bind=True) decorator for def enrich(self)
    (chord) $ python main.py
    Redis channels count before chord execution 0
    Redis channels count after chord execution 9
    Redis channels count after result retrieval 120
    (chord) $ python main.py
    Redis channels count before chord execution 8
    Redis channels count after chord execution 26
    Redis channels count after result retrieval 120
    (chord) $ python main.py
    Redis channels count before chord execution 25
    Redis channels count after chord execution 53
    Redis channels count after result retrieval 120
    (chord) $ python main.py
    Redis channels count before chord execution 52
    Redis channels count after chord execution 11
    Redis channels count after result retrieval 121
     
Further the problem can be gotten rid of if the task decorator is removed from the enrich function. However, what we want to do is use the task decorator, with the chord, but for some reason there's some cleanup that's not working when a chord is used within a task. For an example of this behaviour see this output:

    # Without decorator for def enrich()
    (chord) $ python main.py
    Redis channels count before chord execution 0
    Redis channels count after chord execution 8
    Redis channels count after result retrieval 0
    (chord) $ python main.py
    Redis channels count before chord execution 0
    Redis channels count after chord execution 8
    Redis channels count after result retrieval 0

Note that this issue is very similar to the #3812 and #3815, but even celery:4.2.0rc4 does not resolve this problem.

**Comment by awbacker** [comment]
I'm having a similar issue when firing off a chord from a django view.  The channels are not released until the django app is restarted.  In my case I don't care about the results of the tasks. 

* Celery 4.1.1 or 4.2.0rc4
* Redis 3.0.9
* Python 2.7 or 3.6.5

I've made a sample project on github which demonstrates this (and an SO question relating to it).  If this isn't the same issue, then make a new one.

* https://github.com/awbacker/celerychord-issue  (readme.md has full details)
* https://stackoverflow.com/questions/50617142/

**Comment by georgepsarakis** [comment]
@LasseGravesen the task `enrich` is returning an `AsyncResult` object, since you are not calling `.get` inside the task. Your task is also returning an `AsyncResult` instance for the chord. 

So [here](https://github.com/FalconSocial/Celery-Testing-LasseVG/blob/master/utils/library.py#L65), you actually need to call `result.result.get()` in order to get the chord execution result and cleanup the channels.

**Comment by georgepsarakis** [comment]
@awbacker [here](https://github.com/awbacker/celerychord-issue/blob/dc870a98a7185a7af2c5fca0ed0daa4b9d335f6b/cbug/apps/api/views.py#L30) you can call `apply_async` with the `ignore_result` execution option.

```python
all_tasks.apply_async(ignore_result=True)
```

**Comment by awbacker** [comment]
@georgepsarakis I've launched the start command and the monitor in an loop (using `watch`) and this is what I see (tl;dr: it cleans up, eventually)

* Channels stick around for a little while
* They get cleaned up somehow (not sure how/where/when)
* Cleanup happens with *or* without `ignore_result=True` in the `apply_async()` call

Basically, if I run one task then they stay.  If I run 50 tasks, then at various points it has between 5 (minimum) and 20 channels active.  Doesn't seem too bad, since it does get cleaned up eventually if more tasks are run, so it doesn't *look* like i'll have millions of 'em (like some have seen).

Not sure whats going on, but thats what I see when running in a loop for several minutes:

```
$> watch -n5 "http :8000/api/start"
$> watch -n0 "redis-cli pubsub channels"
```

**Comment by LasseGravesen** [comment]
Thanks for clarifying the intended use @georgepsarakis !

**Comment by georgepsarakis** [comment]
@awbacker the task caller subscribes to (at least) one Redis channel, when results are not ignored. In the case of a Canvas workflow such as chord, results are required by the worker (which also becomes a *result consumer* at that point). If you happen to notice a different behavior, please let us know.

If there are no other questions, I believe we can close this now.
