### ISSUE TITLE
Chains do not retain on_error callbacks

### ISSUE THREAD

**Issue by cdosborn** [celery/celery#4763]
## Checklist

- [x] 4.0.2
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```
@task(name="success")
def success():
    pass

@task(name="error")
def error():
    raise Exception()

@task(name="hello")
def hello():
    return "hello"

((error.si() | success.si()).on_error(hello.si()) | success.si()).delay()
```

## Expected behavior
The error callback `hello` should be called.

## Actual behavior
The error callback is not called.

I stepped through the code a bit and found more or less "why" it's not behaving like I expect. There is a stage where a chain is reduced to a list of tasks, during this reduction its error callbacks are not preserved:
https://github.com/celery/celery/blob/3aaa7538a519522fca0454cf4ee5f9dd106d4190/celery/canvas.py#L642-L645

I was thinking you could just add the callbacks to each of the chain's `.tasks` (in the snipped above) and the next iteration the process would continue, until all nested chains have passed their error callbacks onto the base tasks.

**Comment by cdosborn** [comment]
When a chain is `or'd` with a task, the chain's options are also discarded.
https://github.com/celery/celery/blob/3aaa7538a519522fca0454cf4ee5f9dd106d4190/celery/canvas.py#L420-L421

**Comment by auvipy** [comment]
what you got with celery 4.2rc4? could you try that and let us know?

**Comment by cdosborn** [comment]
It works in that version! Thank you.
