### ISSUE TITLE
docs regarding how to use eta/countdown should mention visibility_timeout setting for Redis and SQS brokers

### ISSUE THREAD

**Issue by ckot** [celery/celery#4766]
Currently, the Redis and SQS transports provide a `visibility_timeout` option in the config.  This has an effect on how apply_async() works with either eta or countdown kwargs.  The caveats regarding this are buried in: 

http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#redis-caveats

http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html

Using etas or countdowns greater than the visibility_timeout value will result in tasks being duplicated. There should be some mention of this and/or links to these in:

http://docs.celeryproject.org/en/latest/userguide/calling.html#eta-and-countdown

**Comment by auvipy** [comment]
could you please send a pr?

**Comment by pcastro93** [comment]
I think this issue might be closed since the PR was already merged. https://github.com/celery/celery/pull/8075

**Comment by auvipy** [comment]
thanks for cross checking
