### ISSUE TITLE
ModuleNotFoundError: No module named 'kombu.asynchronous.timer'

### ISSUE THREAD

**Issue by AlphaFase** [celery/celery#4772]
```python
from kombu.asynchronous.timer import Entry
```
```python
  File "C:\Users\Administrator\.IntelliJIdea2018.1\config\plugins\python\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Administrator\.IntelliJIdea2018.1\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Administrator/IdeaProjects/easybook/app.py", line 5, in <module>
    from kombu.asynchronous.timer import Entry
ModuleNotFoundError: No module named 'kombu.asynchronous.timer'
```

**Comment by thedrow** [comment]
@AlphaFase Have you upgraded to 4.2.1?

@auvipy Seems like a lot of people are hitting this.

**Comment by auvipy** [comment]
it works fine on my local machine.

**Comment by AlphaFase** [comment]
Python 3.6.5 uses all versions of celery, none of which is BUG free.

**Comment by thedrow** [comment]
@AlphaFase I'm not sure what you mean.
Can you please provide the output of `celery report`?

**Comment by AlphaFase** [comment]
main.py
```
from kombu.asynchronous.timer import Entry
```

**Comment by kyrelos** [comment]
Seen the issue in celery==4.2.0rc3, upgrading to celery==4.2.0rc4 fixes the issue. Also celery==4.1.1 doesn't have the import issue.

**Comment by thedrow** [comment]
@kyrelos Do you have any idea why this happens? We can't reproduce it.

**Comment by sywesk** [comment]
After looking on my own machine having the bug, we have the new `asynchronous` directory side by side with the old `async`, but the first lacks the files in the latter. This is a fresh install, in a new venv. This is strange because after inspection of the files in pypi, the `asynchronous` directory exists and is full, and there's no `async`. That's really strange

**Comment by thedrow** [comment]
Released.

**Comment by zulrang** [comment]
I'm having this issue with the latest stable releases:

kombu==4.2.1
celery==4.1.1

**Comment by thedrow** [comment]
I'm gonna re-open this.
I'll inspect the 4.2.1 tarball and see if it's not there.

**Comment by thedrow** [comment]
@zulrang Can you please try removing your virtual environment and reinstalling everything?
