### ISSUE TITLE
Testing on_failure

### ISSUE THREAD

**Issue by ericman93** [celery/celery#4778]
Couldn't find a way to test the `on_failure` behavior anywhere so I would like to suggest it as a feature request.

A celery task has a base class were an `on_failure` method is implemented.
In my test, I patched one of the methods that the task is calling to, to raise an exception but `on_faliure` is never called.
It seems that the worker it self is calling to `on_failure` when an exception is rasied and not the `@task` attribute, and I in my test I don't have any worker running.

Base class
```
class BaseTask(celery.Task):
    abstract = True 

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print("error")
```
Task
```
@celery.task(bind=True, base=BaseTask)
def multiple(self, a, b):
    logic.method(a, b)
```

Test
```
@patch('tasks.logic.method')
def test_something(self, mock):
    # arrange
    mock.side_effect = NotImplementedError

    # act
    with self.assertRaises(NotImplementedError):
        multiple(1, 2)
```

**Comment by xirdneh** [comment]
By definition the [`on_failure`](http://docs.celeryproject.org/en/latest/userguide/tasks.html#on_failure) method will be called by the worker.
I would suggest to write a test to test whatever your `on_failure` does instead of testing if they was called.
Those tests are already done on the Celery level (verifying if `on_failure` is called).

**Comment by ericman93** [comment]
I wanted to write an `e2e` test and check the value after an exception has raised.
Can something like that, can be tested?

**Comment by xirdneh** [comment]
If you want to test that your custom `on_failure` method, you could do a unit test to see that everything is working correctly inside that method.
If you want to check that `on_failure` is called when a task fails then you're going to have to fire a test worker. If you're using `py.test` you can [use a fixture](http://docs.celeryproject.org/en/latest/userguide/testing.html#celery-worker-embed-live-worker) to start a worker for integration tests.
Take note that this would make sense if this integration test's aim is to check if everything is going OK with the broker.
Testing the worker in fact fires `on_failure` when a task fails is already tested on [Celery's worker tests](https://github.com/celery/celery/blob/master/t/unit/worker/test_request.py#L850)
