### ISSUE TITLE
KeyError on mocked task in 4.1.x

### ISSUE THREAD

**Issue by brendenwest** [celery/celery#4781]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I have an existing job that groups several tasks. My tests use 'mock.patch' to verify each task is called. The tests work fine in Celery 3.1.25, but fail in 4.1.x with a 'KeyError'. Code & traceback are at:

https://stackoverflow.com/questions/50495274/celery-4-keyerror-on-mock-task

## Expected behavior
Mock tasks behave the same as normal tasks, with subtask_type=None

## Actual behavior
Mock tasks have a subtask_type like so:

  `<MagicMock name='do_extract.s().get()' id='139863536143048'>`

**Comment by auvipy** [comment]
try latest releases.
