### ISSUE TITLE
Release of kombu==4.2.0 is breaking celery==4.0.2

### ISSUE THREAD

**Issue by anandtripathi5** [celery/celery#4784]
While installing celey==4.0.2 its giving error `KeyError: 'async'`. Upgraded dependencies should install only when  the version is upgraded not in this case

**Comment by auvipy** [comment]
with kombu 4.2 you need to use atleast celery 4.1.1 or celery 4.2rc4, if you are forced to use celery 4.0.2 then use kombu 4.1x series

**Comment by anandtripathi5** [comment]
@auvipy I know that it is duplicate but my concern was not that. The concern is that on a one fine day I'm installing celery==4.0.2 and suddenly it is giving error cause kombu has a release that is my concern, the versioning doesn't work that way. To solve this I have to upgrade the celery to celery==4.1.1 in every project I'm having

**Comment by clokep** [comment]
@anandtripathi5 You also could pin kombu to 4.1.0.
