### ISSUE TITLE
--workdir + --detach sliently fails in 4.1.1

### ISSUE THREAD

**Issue by nikokio** [celery/celery#4785]
Hello,

After upgrading to celery 4.1.1 + kombu 4.2, when launching celery multi with --workdir (which launches celery worker with --detach and --workdir), the workers start and then immediately stop with no log (even in debug mode) and only the log of the master process is generated.

If omitting --workdir, all runs perfectly. Keeping --workdir but omitting --detach also works

This issue appeared in 4.1.1, 4.1.0 is not affected

Thanks

**Comment by juannyG** [comment]
Would it be possible to provide more information? With the information you have provided I've tried to replicate the behavior you've reported but `celery mutli start w1 -A celeryapp.app --workdir=/path/to/celeryapp` with or without `--detach` appear to be working as expected on my Linux machine.

**Comment by nikokio** [comment]
Hello,

Yes for sure. The multi command launched is :

celery multi start worker1 worker2 worker3 worker4 worker5 --workdir=/path/to/workdir --pidfile=/var/run/appname_%n.pid --logfile=/var/log/appname_%n_%i.log --hostname=hostname.example.com --loglevel=INFO --loglevel:1=INFO --loglevel:2=INFO --loglevel:3=INFO --loglevel:4=INFO --loglevel:5=INFO --queues:1=celery,queue_a,queue_b,queue_c --queues:2=celery,queue_a,queue_b,queue_c --queues:3=queue_d --queues:4=queue_e --queues:5=queue_f --concurrency:1=5 --concurrency:2=5 --concurrency:3=5 --concurrency:4=5 --concurrency:5=5 --app=appName --verbose

The --verbose option let us see what is the worker command called :

/path/to/bin/python3.5 -m celery worker --detach --logfile=/var/log/appname_worker1_%i.log --pidfile=/var/run/appname_worker1.pid --workdir=/path/to/workdir --loglevel=INFO --app=appName --queues=celery,queue_a,queue_b,queue_c --concurrency=5 -n worker1@hostname.example.com --executable=/path/to/bin/python3.5


The above commands work when modules versions are :

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.1
            billiard:3.5.0.3 py-amqp:2.3.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled


But when I upgrade to celery:4.1.1 / kombu:4.2.0, it doesn't unless I remove --workdir :

Thanks

**Comment by juannyG** [comment]
I still can't seem to replicate the behavior given an identical match to the versions you described:
```
(celery-issues-env) j@zebra:~/celery-issues-env/celery-issues/4785$ celery report

software -> celery:4.1.1 (latentcall) kombu:4.2.0 py:3.5.1
            billiard:3.5.0.3 py-amqp:2.3.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```
I did noticed that our `loader` definition differed, but I was able to match it to yours (`loader -> celery.loaders.app.AppLoader`) by running `celery report --app=my.app.module`:
```
(celery-issues-env) j@zebra:~/celery-issues-env/celery-issues/4785$ celery report --app=celeryapp.app

software -> celery:4.1.1 (latentcall) kombu:4.2.0 py:3.5.1
            billiard:3.5.0.3 py-amqp:2.3.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

CELERY_IMPORTS: 'celeryapp.tasks'
BROKER_URL: 'amqp://guest:********@127.0.0.1:5672//'
```

There's a minor tweak to the paths - but I ran the identical `multi` command you provided - please review in case I missed something:
```
/home/j/celery-issues-env/bin/celery multi start worker1 worker2 worker3 worker4 worker5 --workdir=/home/j/celery-issues-env/celery-issues/4785 --pidfile=/var/run/celery-issues/appname_%n.pid --logfile=/var/log/celery-issues/appname_%n_%i.log --hostname=hostname.example.com --loglevel=INFO --loglevel:1=INFO --loglevel:2=INFO --loglevel:3=INFO --loglevel:4=INFO --loglevel:5=INFO --queues:1=celery,queue_a,queue_b,queue_c --queues:2=celery,queue_a,queue_b,queue_c --queues:3=queue_d --queues:4=queue_e --queues:5=queue_f --concurrency:1=5 --concurrency:2=5 --concurrency:3=5 --concurrency:4=5 --concurrency:5=5 --app=celeryapp.app --verbose
```
which executed:
```
celery multi v4.1.1 (latentcall)
> Starting nodes...
	> worker1@hostname.example.com:   /home/j/celery-issues-env/bin/python -m celery worker --detach --workdir=/home/j/celery-issues-env/celery-issues/4785 --app=celeryapp.app --logfile=/var/log/celery-issues/appname_worker1_%i.log --loglevel=INFO --pidfile=/var/run/celery-issues/appname_worker1.pid --queues=celery,queue_a,queue_b,queue_c --concurrency=5 -n worker1@hostname.example.com --executable=/home/j/celery-issues-env/bin/python
...
```
The worker nodes we running and I was able to send tasks repeatedly with no issue. The only thing that comes to my mind, that I've seen historically: I've typically let the service scripts (`/etc/init.d/celeryd`) manage the `celery multi` execution. When I saw the start script tell me nodes were up, but did a `ps aux | grep celery` and found no workers running, I would use the `--verbose` parameter, as you are, to see the worker command generated and then try to manually execute it without `--detach` - this usually revealed some import/syntax failure present in my code.

That said, given that when you change versions things work fine, leads me to believe that this isn't very likely in this case...but may be worth a try, if you haven't tried running `celery worker ...` manually, just to see what it does.

Without more information, I'm not sure that I can be of much more assistance :disappointed: If there's any more information you can share/find/think of - I'd be more than happy to try to continue assisting.

**Comment by nikokio** [comment]
All my tests are done outside an init.d script, i.e. directly from console to be sure I understand what I do.

The problem is, as said in my first post, as soon as I remove the --detach option, it works.
This is when running the worker with both --detach and --workdir that I get this behavior : the worker starts, create the mainProcess log file empty and suddenly stops without any line in the log, even in debug mode....

The only solution I have is to try to run the worker with strace, but with --detach not sure I'll get what I need. I'll try to find time to perform this test...

**Comment by thedrow** [comment]
We haven't changed anything except bumping the version and making the linters pass.
The same changes were applied to Celery 4.2.
Can you please check the latest 4.2 RC and see if you can reproduce the same behavior?

**Comment by nikokio** [comment]
That was definitely a bug : I tried again but with the very new 4.2.1 kombu release : I can't reproduce anymore.
So the issue seems to be a combination between our code, celery 4.1.1 and kombu 4.2.0.
I'll then be able to upgrade to celery 4.1.1 and kombu 4.2.1.

Thanks
