### ISSUE TITLE
Celery work on federated RabbitMQ

### ISSUE THREAD

**Issue by craynic** [celery/celery#4786]
I'm trying to let Celery work on federated RabbitMQ, with the result backend set to the same RabbitMQ.
I have two network environment, and each environment has one RabbitMQ. Tasks are always submited on No.1 RabbitMQ, and I will always get task results on No.1 RabbitMQ. Tasks will be executed on No.1 RabbitMQ or No.2 RabbitMQ, by setting different listening queues for celery workers.
Now I federate such exchanges to try to let them work:

    reply.celery.pidbox  Exchange  No.2(upstream) -> No.1
    celeryresults  Exchange  No.2(upstream) -> No.1
    celery.pidbox  Exchange  No.1(upstream) -> No.2
    my.task.queue  Queue  No.1(upstream) -> No.2

With theses federations, tasks could be perfectly executed, and Celery control tasks also work, but the results could not be retrieved. The bindings on exchange `celeryresults` seem to be created when tasks get done, and the federation plugin syncs messages but not bindings, so the message copied to the exchange on No.1 RabbitMQ will be lost. The task id is automatically generated (in my case), so I either cannot federate the result queue. 
Is there any solution for this case?

======================
In the end I use these federation settings:

    reply.celery.pidbox  Exchange  No.2(upstream) -> No.1
    celery.pidbox  Exchange  No.1(upstream) -> No.2    # to let celery control commands work
    my.task.queue  Queue  No.1(upstream) -> No.2    # to let task messages be routed
    celeryev Exchange No.2(upstream) -> No.1    # to let events go

(No.1 could be treated as a manager, while No.2 could be treated as a worker.)

**Comment by xirdneh** [comment]
How are you retreiving the result?
How are you configuring ypurresult backed?
I believe if the backed is configured as RPC that would mean that only the process that started the task is able to retrieve the result.
So, if you're trying to retreiving the result from another process this might be the issue.

**Comment by craynic** [comment]
I'm using the same URI for both broker backend and result backend.
In my case, task publishing and result reading will always be in one process, so the oid will work fine. There is no problem with the queue name. My problem is that the result queues are created dynamically, so they cannot get federated.
Now I'm trying to write a worker to retrieve messages from No.2 RabbitMQ and publish to No.1 RabbitMQ. It may look ugly but should work.
(Also I wonder why the result queue name is oid but not task id.)

**Comment by xirdneh** [comment]
Ah, ok. I wanted to make sure that was clear.
I have never tried updated the `reply_to` value but it is a property defined in [Celery's message protocol](http://docs.celeryproject.org/en/latest/internals/protocol.html).
This means that one should be able to set the `reply_to` value when creating the message.
When you queue a task Celery will call [`celery.app.base::Celery.send_task`](https://github.com/celery/celery/blob/master/celery/app/base.py#L688). Everything from [`apply_async`](https://github.com/celery/celery/blob/master/celery/app/task.py#L531) is passed to `send_task`.
We can see that in `send_task` is where the [`oid` is set](https://github.com/celery/celery/blob/master/celery/app/base.py#L731) as the `reply_to` value.
I believe you should be able to specify the `reply_to` value by doing something like this:
```python
>>> my_task.apply_async(reply_to='federated.responses')
```

**Comment by craynic** [comment]
@xirdneh Thank you for your explaination. But in my case, there may be many tasks executing at the same time. If workers return results to one queue, we may retrieve the results prepared for other tasks. If the results are returned to different queues, the federation is still a problem.

**Comment by xirdneh** [comment]
I think that depends more on your architecture and what you're trying to do.
The example given it's only an example.
You can use it to send the results to a federated exchange that then sends the message to a queue using the `task_id` or something like that.
Not sure if it'll work for your use case.

You mentioned you were building a worker to retrieve results from one queue and send it to another. Not sure what that would solve but the same issues might arise about sending all results to one queue.

Also, this shows why it's `oid` and not `task_id`. Because the idea is to only allow the publisher to retrieve the result. The uniqueness there is the app's `oid`.

If this is a central issue I would also suggest not to use RPC as a result backend. But it's only a suggestion since I'm not acquainted with the rest of your application.

Hopefully this helps your in your implementation.

**Comment by craynic** [comment]
Thank you for your suggestions.
I have been thinking using a federated exchange to copy messages from the upstream to the downstream. It seems that bindings will not be synced to the downstream exchange, so the messages copied to the downstream exchange are silently dropped.
Now I've finished the worker. It listens binding events on exchange `celeryresults`, and try to consume messages from the upstream and then publish to the downstream.
I'm surely aware of that rpc is not a good result backend, or event not an ordinary result backend. But the project I'm working on has been using this for a long time, and using another service to provide a result backend will be a little difficult to deploy. It may be the only result backend that I could choose.

**Comment by xirdneh** [comment]
I see.
Is your custom worker solving the issue?
I'm trying to think about a simpler way to work around this.
Could you offer a raw idea of how the worker is implemented. A bit more in detailed that your past message if possible.
Thanks.

**Comment by xirdneh** [comment]
@craynic is the custom worker working correctly?
Can you give a suggestion how we can make it easier for people to use federated rabbitMQ as backend?
Thanks.

**Comment by craynic** [comment]
1. Enable plugin rabbitmq_event_exchange on the upstream node. Create a queue and a binding with routing key `binding.created` on exchange `amq.rabbitmq.event`.
2. A worker consumes events from the queue just created. Select bindings created on exchange `celeryresults`. We need the queue names of the bindings.
3. Consume a message from the queue on the upstream node. Create a queue with the same name on the downstream node and publish the message to this queue.

Sorry, I didn't visit Github these days. Also, I found an easier way to do this work. 
There is a topic exchange named `celeryev` which sends celery events. I federate this exchange from the upstream to the downstream. The event receivers listening on the downstream will also get events from the upstream. It seems better because it does not rely on the result backend.

**Comment by xirdneh** [comment]
@craynic That is a great workaround.
Thanks for the info. Is it ok to close this issue?

**Comment by craynic** [comment]
ok.
I also update the first post for the complete federation settings.
