### ISSUE TITLE
Task doesn't fail if on failure, an errback throws an exception

### ISSUE THREAD

**Issue by cdosborn** [celery/celery#4787]
## Checklist

- [x] Reproduced in master, 4.2rc4
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
When a task fails and an exception is thrown in one of its error callbacks, the task will not transition to failed.
```
@task(name="error")
def error():
    raise Exception()

@task(name="bad_errback")
def bad_errback(err, exc, tb):
    raise Exception()

error.si().on_error(bad_errback.s()).delay()
```

## Expected behavior
The `error` task would fail.

## Actual behavior
The `error` task remains in started.

I did some digging and have an explanation for the behavior.

When an exception occurs during a task. `on_failure` is called:
https://github.com/celery/celery/blob/fd6e4758260612cbd03dc007010be5699208ca2f/celery/worker/request.py#L343-L390

Line 365, is where the errbacks are called for a task. If any of the errbacks throw an exception, it won't be caught.

Line 381, is where the task is marked as failed, which won't happen if an errback throws an exception.

This issue is only reproduced when errbacks have have more than 1 argument in their signature, if they do the errbacks are called immediately. This way the traceback/exception can be preserved see https://github.com/celery/celery/pull/2538#issuecomment-227865509. 
https://github.com/celery/celery/blob/fc987ed0636a50dff7e0a738a10d8e89f34d3158/celery/backends/base.py#L172

I also noticed that if the the errback is a chain, everything works as expected as in:
```
error.si().on_error(bad_errback.s() | bad_errback.si("","","")).delay()
```

**Comment by xirdneh** [comment]
I believe if the errback is a chain everything will work as expected because a chain will queue the tasks inside of it. So if there's an error the chain is probably not going to raise that exception.

How are you checking if the task is set as Failed?

I tried running the sample code but I do see when both exceptions are raised and when I look at the task's state it returns `FAILURE`.
```python
# With tasks like this
@app.task
def task_error():
    """task error"""
    print('task_error')
    raise Exception()

@app.task
def handler(err, exc, tb):
    """handler"""
    print(f'handler')
    raise Exception()
```

And testing like this:
```python
>>> from app import task_error, handler
>>> res = task_error.si().on_error(handler.s()).delay()
>>> res.ready()
True
>>> res.successful()
False
>>> res.state
'FAILURE'
```

And I see this on my worker's output:
```
[2018-06-04 19:12:02,329: INFO/MainProcess] Received task: app.main.task_error[47484397-0bfe-45b6-b1e3-c78936223da1]  
[2018-06-04 19:12:02,337: WARNING/ForkPoolWorker-2] task_error
[2018-06-04 19:12:02,370: WARNING/ForkPoolWorker-2] handler
[2018-06-04 19:12:02,410: WARNING/ForkPoolWorker-2] /src/celery/app/trace.py:561: RuntimeWarning: Exception raised outside body: Exception():
Traceback (most recent call last):
  File "/src/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/src/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/www/project/app/main.py", line 105, in task_error
    raise Exception()     ****************** FIRST EXCEPTION ***********************
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/celery/app/trace.py", line 396, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/src/celery/app/trace.py", line 338, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/src/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/src/celery/app/trace.py", line 217, in handle_failure
    call_errbacks=call_errbacks,
  File "/src/celery/backends/base.py", line 160, in mark_as_failure
    self._call_task_errbacks(request, exc, traceback)
  File "/src/celery/backends/base.py", line 172, in _call_task_errbacks
    errback(request, exc, traceback)
  File "/src/celery/canvas.py", line 175, in __call__
    return self.type(*args, **kwargs)
  File "/src/celery/app/trace.py", line 642, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/src/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "/srv/www/project/app/main.py", line 111, in handler
    raise Exception() ****************** EXCEPTION ON HANDLER ***********************
Exception
```

**Comment by cdosborn** [comment]
Okay, I noticed that in celery flower the status of the task wasn't updating (which wasn't conclusive regarding the actual task state). So I think you're right that the task is being updated. But I think that celery is still aborting too early for the signal to be sent. 

Also, the method reporting the error is `report_internal_error`, which made me believe it might be exiting too early.

**Comment by xirdneh** [comment]
Can you show the code and stacktrace where you see this?
If you could suggest how to write a test for this, it would be great.
