### ISSUE TITLE
Feature: Expose task runtime in AsyncResult

### ISSUE THREAD

**Issue by mattlong** [celery/celery#479]
A common pattern I'm using is to measure the runtime of a task and return it as part of the result. It would be great if  the built in runtime that shows up in the celeryd log ("Task my.TaskClass succeeded in 0.411760091782s:...") could be available as part of AsyncResult as well as for each AsyncResult that is a part of a TaskSetResult.

**Comment by feifangit** [comment]
I retrieve the runtime of a task by `task_prerun` and `task_postrun` combination.
```
from celery.signals import task_postrun, task_prerun

@task_prerun.connect
def pre_run(sender, task_id, task, *args, **kwargs):
    task.__hack_starttime = time.time()

@task_postrun.connect
def post_run(sender, task_id, task, retval, state,  *args, **kwargs):
    st = getattr(task, "__hack_starttime", None)
    if st:
       print "time span", time.time()-st
```

**Comment by bohea** [comment]
from celery.signals import task_postrun, task_prerun

@celery.signals.task_prerun.connect
def statsd_task_prerun(**kwargs):
    current_task.start_time = time.time()


@celery.signals.task_postrun.connect
def statsd_task_postrun(**kwargs):
    runtime = time.time() - current_task.start_time

**Comment by jcaffrey** [comment]
looking more closely it seems that calculating the `runtime` in the `task_success` and `task_failure` signals matches the [`runtime`](http://docs.celeryproject.org/en/latest/userguide/monitoring.html#task-succeeded) variable that is logged by celery

**Comment by mr-bjerre** [comment]
Isn't there a way to retrieve [`runtime`](https://docs.celeryproject.org/en/latest/userguide/monitoring.html#task-succeeded) from [`AsyncResult`](https://docs.celeryproject.org/en/stable/reference/celery.result.html)?

Preferably it wouldn't require the workers to set up some configurations (that is the suggestion from @bohea, right?)

**Comment by tochimclaren** [comment]
why is celery task runtime difficult to access! There is an Event that returns tasks runtime it's called "task-succeeded" when I apply to my django code it freeze the server.

**Comment by tochimclaren** [comment]
> I retrieve the runtime of a task by `task_prerun` and `task_postrun` combination.
> 
> ```
> from celery.signals import task_postrun, task_prerun
> 
> @task_prerun.connect
> def pre_run(sender, task_id, task, *args, **kwargs):
>     task.__hack_starttime = time.time()
> 
> @task_postrun.connect
> def post_run(sender, task_id, task, retval, state,  *args, **kwargs):
>     st = getattr(task, "__hack_starttime", None)
>     if st:
>        print "time span", time.time()-st
> ```

This was helpful. Thanks.
