### ISSUE TITLE
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

### ISSUE THREAD

**Issue by liangxianyu** [celery/celery#4796]
the output of ``celery -A proj report`` in the issue.
   
software -> celery:4.2.0rc4 (windowlicker) kombu:4.2.1 py:3.5.2
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:django-cache

CELERY_TASK_SERIALIZER: 'json'
FIXTURE_DIRS: []
MIGRATION_MODULES: {
 }
CSRF_COOKIE_SECURE: False
TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
CSRF_COOKIE_PATH: '/'
SESSION_CACHE_ALIAS: 'default'
SECURE_SSL_REDIRECT: False
DATETIME_FORMAT: 'Y-m-d H:i:s'
DEFAULT_TABLESPACE: ''
TIME_ZONE: 'Asia/Shanghai'
FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
AUTHENTICATION_BACKENDS: ['django.contrib.auth.backends.ModelBackend']
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
PASSWORD_HASHERS: '********'
EMAIL_HOST_USER: ''
DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']
DATABASES: {
    'default': {   'ENGINE': 'django.db.backends.mysql',
                   'HOST': '127.0.0.1',
                   'NAME': 'shenzhu',
                   'PASSWORD': '********',
                   'PORT': '3306',
                   'USER': 'root'}}
CELERY_BROKER_URL: 'redis://127.0.0.1:6379/3'
SECURE_REDIRECT_EXEMPT: []
CELERY_ACCEPT_CONTENT: ['json']
USE_I18N: True
DATA_UPLOAD_MAX_NUMBER_FIELDS: 10000
SHORT_DATE_FORMAT: 'm/d/Y'
DATE_INPUT_FORMATS: ['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
INSTALLED_APPS: ['suit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_crontab',
 'yoher',
 'django_celery_results',
 'django_celery_beat',
 'django_extensions']
LOGOUT_REDIRECT_URL: None
SUIT_CONFIG: {
    'ADMIN_NAME': '吆喝后台管理界面',
    'LIST_PER_PAGE': 20,
    'MENU': (   {   'app': 'auth',
                    'icon': 'icon-lock',
                    'label': '用户管理',
                    'models': ('author.User', 'auth.Group')},
                {'app': 'yoher', 'label': '监控管理', 'models': 'yoher.goods'})}
LANGUAGE_CODE: 'zh-hans'
LANGUAGE_COOKIE_NAME: 'django_language'
FORCE_SCRIPT_NAME: None
CACHE_MIDDLEWARE_KEY_PREFIX: '********'
DEFAULT_CHARSET: 'utf-8'
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
CSRF_COOKIE_HTTPONLY: False
LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
EMAIL_USE_TLS: False
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
LOGGING: {
 }
CACHES: {
 'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
DEFAULT_FROM_EMAIL: 'webmaster@localhost'
USE_X_FORWARDED_HOST: False
AUTH_USER_MODEL: 'auth.User'
BASE_DIR: '/home/ubuntu/web/shenzhu'
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
LANGUAGE_COOKIE_DOMAIN: None
SHORT_DATETIME_FORMAT: 'm/d/Y P'
LANGUAGES: [('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
IGNORABLE_404_URLS: []
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
USE_L10N: True
MANAGERS: []
EMAIL_PORT: 25
X_FRAME_OPTIONS: 'SAMEORIGIN'
CSRF_COOKIE_AGE: 31449600
ALLOWED_HOSTS: ['111.231.144.99']
CSRF_COOKIE_NAME: 'csrftoken'
FILE_UPLOAD_TEMP_DIR: None
SECURE_PROXY_SSL_HEADER: None
FILE_CHARSET: 'utf-8'
FIRST_DAY_OF_WEEK: 0
SESSION_SAVE_EVERY_REQUEST: False
TEMPLATES: [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
CELERYD_MAX_TASKS_PER_CHILD: 5
MEDIA_URL: '/media/'
DEFAULT_INDEX_TABLESPACE: ''
SECURE_HSTS_PRELOAD: False
SESSION_COOKIE_SECURE: False
CSRF_COOKIE_DOMAIN: None
SESSION_COOKIE_AGE: 1209600
EMAIL_TIMEOUT: None
WSGI_APPLICATION: 'shenzhu.wsgi.application'
EMAIL_USE_SSL: False
SECURE_SSL_HOST: None
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
TIME_FORMAT: 'P'
TEST_NON_SERIALIZED_APPS: []
SILENCED_SYSTEM_CHECKS: []
AUTH_PASSWORD_VALIDATORS: '********'
FILE_UPLOAD_PERMISSIONS: None
PREPEND_WWW: False
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
SETTINGS_MODULE: 'shenzhu.settings'
FILE_UPLOAD_HANDLERS: ['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
SECRET_KEY: '********'
DATE_FORMAT: 'Y-m-d'
PASSWORD_RESET_TIMEOUT_DAYS: '********'
DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
CACHE_MIDDLEWARE_SECONDS: 600
EMAIL_SUBJECT_PREFIX: '[Django] '
DEBUG_PROPAGATE_EXCEPTIONS: False
ABSOLUTE_URL_OVERRIDES: {
 }
CELERY_RESULT_BACKEND: 'django-cache'
ADMINS: []
EMAIL_SSL_CERTFILE: None
DATABASE_ROUTERS: '********'
SESSION_COOKIE_PATH: '/'
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
FORMAT_MODULE_PATH: None
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
SESSION_COOKIE_NAME: 'sessionid'
NUMBER_GROUPING: 0
DEFAULT_CONTENT_TYPE: 'text/html'
SECURE_CONTENT_TYPE_NOSNIFF: False
CACHE_MIDDLEWARE_ALIAS: 'default'
DEBUG: True
STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
LOCALE_PATHS: []
USE_X_FORWARDED_PORT: False
USE_THOUSAND_SEPARATOR: False
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
STATICFILES_DIRS: []
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
is_overridden: <bound method Settings.is_overridden of <Settings "shenzhu.settings">>
DISALLOWED_USER_AGENTS: []
CSRF_USE_SESSIONS: False
USE_ETAGS: False
EMAIL_HOST_PASSWORD: '********'
CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
CRONJOBS: [('57 20 * * *',
  'yoher.cron.my_cron',
  '>>/home/ubuntu/test.log')]
LOGIN_REDIRECT_URL: '/accounts/profile/'
INTERNAL_IPS: []
LANGUAGE_COOKIE_PATH: '/'
MEDIA_ROOT: '/home/ubuntu/web/shenzhu/media'
EMAIL_HOST: 'localhost'
USE_TZ: False
CELERY_ENABLE_UTC: False
EMAIL_SSL_KEYFILE: '********'
SERVER_EMAIL: 'root@localhost'
LANGUAGE_COOKIE_AGE: None
THOUSAND_SEPARATOR: ','
STATIC_ROOT: None
YEAR_MONTH_FORMAT: 'F Y'
CSRF_TRUSTED_ORIGINS: []
ROOT_URLCONF: 'shenzhu.urls'
SECURE_HSTS_SECONDS: 0
SESSION_COOKIE_DOMAIN: None
SECURE_BROWSER_XSS_FILTER: False
MIDDLEWARE: ['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
APPEND_SLASH: True
DECIMAL_SEPARATOR: '.'
LOGIN_URL: '/accounts/login/'
beat_schedule: {
    'add-x-y': {   'args': (3, 2),
                   'schedule': <crontab: 52 15 * * * (m/h/d/dM/MY)>,
                   'task': 'yoher.tasks.add'}}
LOGGING_CONFIG: 'logging.config.dictConfig'
MONTH_DAY_FORMAT: 'F j'
SESSION_COOKIE_HTTPONLY: True
EMAIL_USE_LOCALTIME: False
STATIC_URL: '/static/'
SESSION_FILE_PATH: None

when i use 'celery -A shenzhu beat -l info --scheduler django_celery_beat.Schdulers:DatabaseScheduler’ in command line ,the valueError occur。i find this problem in celery 2.x in celery post problem list ,but i find this problem in celery 4.2.0rc4,i'm confused.

command line output like this ;
[2018-06-06 15:43:58,258: ERROR/MainProcess] Message Error: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
['  File "/home/ubuntu/.local/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/__main__.py", line 16, in main\n    _main()\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/celery.py", line 322, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/base.py", line 275, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/celery.py", line 476, in handle_argv\n    return self.execute(command, argv)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/celery.py", line 408, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/base.py", line 279, in run_from_argv\n    sys.argv if argv is None else argv, command)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/base.py", line 363, in handle_argv\n    return self(*args, **options)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/base.py", line 238, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/bin/beat.py", line 109, in run\n    return beat().run()\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/apps/beat.py", line 81, in run\n    self.start_scheduler()\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/apps/beat.py", line 109, in start_scheduler\n    service.start()\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 588, in start\n    interval = self.scheduler.tick()\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 307, in tick\n    self.apply_entry(entry, producer=self.producer)\n', '  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 244, in apply_entry\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 241, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 362, in apply_async
    self._do_sync()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/celery/beat.py", line 373, in _do_sync
    self.sync()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 243, in sync
    self.schedule[name].save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 121, in save
    obj.save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_celery_beat/models.py", line 316, in save
    super(PeriodicTask, self).save(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1053, in execute_sql
    sql, params = self.as_sql()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1343, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 767, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1432, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/backends/mysql/operations.py", line 180, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

**Comment by auvipy** [comment]
what about USE_TZ is True?

**Comment by liangxianyu** [comment]
when i use USE_TZ=True,then django.utils.timezone.now() is not the time of my living place,is UTC time

**Comment by zuoakang** [comment]
### **I have this ploblem too**
[https://github.com/celery/django-celery-beat/issues/80#issuecomment-432122711](url)

**Comment by Kinganmi** [comment]
I have this ploblem too

**Comment by auvipy** [comment]
with celery 4.3 or master?

**Comment by BlueClouDragon** [comment]
please make USE_TZ = True on settings.py of Django project.
The default value is False

**Comment by vladjkeee13** [comment]
You need to add this line to your settings.

DJANGO_CELERY_BEAT_TZ_AWARE = False

**Comment by akipham15** [comment]
> 
> 
> You need to add this line to your settings.
> 
> DJANGO_CELERY_BEAT_TZ_AWARE = False

It works for me, thanks !
