### ISSUE TITLE
'

### ISSUE THREAD

**Issue by jamespedid** [celery/celery#4801]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

**Comment by auvipy** [comment]
what are you willing to report?

**Comment by jamespedid** [comment]
Sorry, I didn't realize I created the request.
The issue I had was with a dependency issue between celery and kumbo, and it was not finding a dependency combination for `celery[redis]`.
