### ISSUE TITLE
Tensorflow workers keep restarting when the worker fails in `worker_process_init`

### ISSUE THREAD

**Issue by Phylliade** [celery/celery#4814]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.

Output of `celery report`:
```
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.5
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

## Steps to reproduce
When using Tensorflow in the initialization of the celery worker process (in `worker_process_init`), exiting the worker process during initialization makes the main worker restarting the worker process. 
The standard behavior being normally to raise an error in the main worker, this appends only after Tensorflow threads are created.

```python
from celery import Celery
from celery.signals import worker_process_init
import tensorflow as tf
import sys
app = Celery()

@app.task()
def add(x, y):
    return x + y

@worker_process_init.connect()
def fail(**kwargs):
    #raise Exception
    try:
        # Raise an exception here, and everything works (the main worker exits with WorkerLostError)
        # Here, Tensorflow threads get created
        tf_session = tf.Session()
        K.set_session(tf_session)
        raise Exception
    except Exception as e:
        print("EXITING: {} / {}".format(type(e), e))
        sys.exit(1)
```
## Expected behavior
When raising the exception (=exiting) before creating the tensorflow threads, the worker process fails and the main worker fails with an error:

```
[2018-06-14 10:14:48,284: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:72488 exited with 'exitcode 1'
[2018-06-14 10:14:48,295: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:72487 exited with 'exitcode 1'
[2018-06-14 10:14:48,336: CRITICAL/MainProcess] Unrecoverable error: WorkerLostError('Could not start worker processes',)
```
## Actual behavior
When raising the exception (=exiting) after creating the tensorflow thread, the worker process fails, but keep being restarted by the main worker: 
```
[2018-06-14 10:16:10,094: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:73458 exited with 'exitcode 1'
...
[2018-06-14 10:18:12,342: ERROR/MainProcess] Process 'ForkPoolWorker-22' pid:77693 exited with 'exitcode 1'
[2018-06-14 10:18:12,353: ERROR/MainProcess] Process 'ForkPoolWorker-21' pid:77624 exited with 'exitcode 1'
```

**Comment by auvipy** [comment]
don't know much about the internals of tensorflow. could you share latest resolution of the issue?

**Comment by Phylliade** [comment]
No update since!

**Comment by auvipy** [comment]
may be this is out of the scope of celey?
