### ISSUE TITLE
Service(current_app).get_scheduler() always returns celery.beat.PersistentScheduler

### ISSUE THREAD

**Issue by chrisgrande** [celery/celery#4828]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
     Celery 4.2.0
     Beats 1.0.1
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

With:
`CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'`
configured, running `celery -A app beat -l info` correctly starts and returns `scheduler -> django_celery_beat.schedulers.DatabaseScheduler`

Celery beat correctly notices when the Periodic Task table changes however none of the tasks ever run. I noticed that even with the DB scheduler set I was getting a celerybeat-schedule.db file which made me wonder if Celery.beat was reading the right database.

Dropping to the console:
`from celery.beat import Service`
`test = Service(current_app).get_scheduler()`
`print(test)`
`<celery.beat.PersistentScheduler object at 0x10abec090>`
`test.get_schedule()`
`{u'celery.backend_cleanup': <ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>}`

Seems it's calling the celerybeat-schedule.db file with the automatically setup _backend_cleanup_ task.

## Expected behavior

It should run the tasks stored in the Django DB.

## Actual behavior

Monitors the Periodic Task table but never actually sends to a worker, only items from the persistent store are run.

**Comment by auvipy** [comment]
could you try latest releases and report again?

**Comment by auvipy** [comment]
could you try more latest version of django-celery-beats?

**Comment by chrisgrande** [comment]
I'll get back into the project I was working on and will test it within the next couple days.
