### ISSUE TITLE
Task destination configuration order in doc is not accurate

### ISSUE THREAD

**Issue by chenfengyuan** [celery/celery#4831]
The configuration in [Specifying task destination](http://docs.celeryproject.org/en/latest/userguide/routing.html#id23) is not accurate
I suppose:
1. The routing arguments to :func:`Task.apply_async` has highest priority
2. task attributes has medium priority.
3. `task_routes` has lowest priority.

Pull Request: #4783

**Comment by chenfengyuan** [comment]
#4783

**Comment by auvipy** [comment]
thanks
