### ISSUE TITLE
3.0.19 version documentation not found

### ISSUE THREAD

**Issue by anipapyan** [celery/celery#4833]
## Checklist

I was looking for 3.0 version documentation (3.0.19) but it open 4.0.0 version doc.

## Steps to reproduce
open [this link](https://media.readthedocs.org/pdf/celery/3.0/celery.pdf) or go [here](https://readthedocs.org/projects/celery/downloads/) and click on "3.0 PDF".
## Expected behavior
3.0.* version documentation should be opened.
## Actual behavior
4.0.0 version's documentation is opened.
![1212](https://user-images.githubusercontent.com/3540228/41719087-078d34f8-7570-11e8-8c68-f1c22c5be419.png)

**Comment by auvipy** [comment]
this is an un supported version

**Comment by IvanAnishchuk** [comment]
I can't find pdf for (supported) 5.0 as well. Was it intentionally disabled to save trees or something? (I know I should ask in a separate issue, sorry, will try to do that later today.) I can't seem to be able to build it myself either :(
