### ISSUE TITLE
Setting task_compression value doesn't actually do anything

### ISSUE THREAD

**Issue by asgoel** [celery/celery#4838]
## Checklist
* [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
       Celery==4.2.0
* [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```python3
app = Celery()
app.conf.update(task_compression="gzip")
```

## Expected behavior
I would expect that if I set a global `task_compression` config, my tasks are indeed gzipped. I shouldn't have to manually define compression=gzip on each task I want.

## Actual behavior
I don't think this setting is respected. This could be the wrong place to look, but it seems like `amqp` is using the wrong compression setting when sending a message: https://github.com/celery/celery/blob/7d9300b3b94399eafb5e40a08a0cdc8b05f896aa/celery/app/amqp.py#L548. `default_compressor` is being set here: https://github.com/celery/celery/blob/7d9300b3b94399eafb5e40a08a0cdc8b05f896aa/celery/app/amqp.py#L483 - should this read `default_compressor = self.app.conf.task_compression` ? Or am I missing something?

**Comment by auvipy** [comment]
sorry for the late. current status?

**Comment by jasisz** [comment]
I can confirm that - working the same in my case.

Exactly as @asgoel points out - it is an obvious bug in the code and setting the `task_compression` does nothing, `result_compression` is used instead.

What is even more interesting `result_compression` compresses... just the tasks headers and results are still not compressed, because of the producer call in `AMQPBackend.store_result` looking like:

```
        with self.app.amqp.producer_pool.acquire(block=True) as producer:
            producer.publish(
                payload,
                exchange=self.exchange,
                routing_key=routing_key,
                correlation_id=correlation_id,
                serializer=self.serializer,
                retry=True, retry_policy=self.retry_policy,
                declare=self.on_reply_declare(task_id),
                delivery_mode=self.delivery_mode,
            )
```

So it is missing the compression kwarg.

**Comment by jasisz** [comment]
It also seems that the `result_compression` does not work for Redis or any other backend too.

**Comment by auvipy** [comment]
which version of celery are you using? 4.4.0?

**Comment by jasisz** [comment]
@auvipy 4.4.0 right now. It compresses task messages, but results are not compressed. Checked that directly in redis too.

**Comment by kwadra** [comment]
Same problem with Celery 4.4.7. No observable change in the messages looking in REDIS when my celeryconfig.py:task_compression="gzip"

When I submit the task with apply_async(compress="gzip") it does work

**Comment by kwadra** [comment]
https://github.com/celery/celery/blob/5b86b35c81ea5a1fbfd439861f4fee6813148d16/celery/app/task.py#L303
I would think the "task_compression" would be referenced here in the code  but it is not.
   from_config = (
        ('serializer', 'task_serializer'),
        ('rate_limit', 'task_default_rate_limit'),
        ('priority', 'task_default_priority'),
        ('track_started', 'task_track_started'),
        ('acks_late', 'task_acks_late'),
        ('acks_on_failure_or_timeout', 'task_acks_on_failure_or_timeout'),
        ('reject_on_worker_lost', 'task_reject_on_worker_lost'),
        ('ignore_result', 'task_ignore_result'),
        ('store_errors_even_if_ignored', 'task_store_errors_even_if_ignored'),
    )

**Comment by Sobes76rus** [comment]
i solved this issue with custom serialization function. like this
```python
def pickle_bz2_encoder(data):
    return bz2.compress(pickle.dumps(data))

def pickle_bz2_decoder(data):
    return pickle.loads(bz2.decompress(data))

serialization.register('pickle-bzip2', pickle_bz2_encoder, pickle_bz2_decoder, 'application/x-pickle-bz2', 'binary')
```

and config
```python
result_serializer = 'pickle-bzip2'
accept_content = ['pickle', 'pickle-bzip2']
```

**Comment by vlad-outscraper** [comment]
allowing using compression will be extremely helpful

**Comment by Tomasz-Kluczkowski** [comment]
Hello, 
is the `result_compression` option actually doing anything as well for the task results?

I have done a global search for it in `celery` (5.2.3) and this is the only place it is used:

```python
    def _create_task_sender(self):
        default_retry = self.app.conf.task_publish_retry
        default_policy = self.app.conf.task_publish_retry_policy
        default_delivery_mode = self.app.conf.task_default_delivery_mode
        default_queue = self.default_queue
        queues = self.queues
        send_before_publish = signals.before_task_publish.send
        before_receivers = signals.before_task_publish.receivers
        send_after_publish = signals.after_task_publish.send
        after_receivers = signals.after_task_publish.receivers

        send_task_sent = signals.task_sent.send   # XXX compat
        sent_receivers = signals.task_sent.receivers

        default_evd = self._event_dispatcher
        default_exchange = self.default_exchange

        default_rkey = self.app.conf.task_default_routing_key
        default_serializer = self.app.conf.task_serializer
        default_compressor = self.app.conf.result_compression
```

which tells me it is used for task compression , not results?

Was this ever working at all?

**Comment by thedrow** [comment]
You're all absolutely right, it should be `self.app.conf.task_compression` in this instance.

**Comment by thedrow** [comment]
Welp. It seems like compressing results isn't supported and only the setting exists. Is anyone up for a quick PR to fix that?

**Comment by Tomasz-Kluczkowski** [comment]
:) By quick PR we mean implement it? Or remove the setting?

On 18 Apr 2022, at 15:25, Omer Katz ***@***.***> wrote:

﻿

Welp. It seems like compressing results isn't supported and only the setting exists. Is anyone up for a quick PR to fix that?

**Comment by auvipy** [comment]
will be on v5.3a1

**Comment by yaronsh-suridata** [comment]
Thanks!
Do you know in what date is it exactly?

**Comment by auvipy** [comment]
this month for sure
