### ISSUE TITLE
limit cpu time instead of run time?

### ISSUE THREAD

**Issue by sivang** [celery/celery#4845]
Hello there. First thank you so very much for celery. It's an amazing project and I'm dazzled how easy it is to use it to create complex and robust out of band processing architectures.

I would like to know if there's an option to limit task worker cpu usage time? Instead of limiting the run time?

Rational would be that if a process consumed just 0.01% of cpu time every time it 'awakens' that perhaps it could be left to run as long as needed.

Hope this makes sense.

**Comment by georgepsarakis** [comment]
@sivang not sure I understood. Do you want to set a threshold on the tasks' CPU usage?

**Comment by sivang** [comment]
@georgepsarakis ,  precisely!

**Comment by georgepsarakis** [comment]
This can be achieved by starting the worker with a specified priority, using [nice](https://en.wikipedia.org/wiki/Nice_%28Unix%29), which I believe is the optimal in terms of CPU allocation if the worker processes also co-exist with other processes in the same server instance.

**Comment by sivang** [comment]
that's exactly my use case, so to achieve that do it through obtaining the PID and then renice it through a shell command perhaps in the celery 'spawn' code?

**Comment by georgepsarakis** [comment]
Depending on your deployment method of choice, you can just start the worker process with `nice`:

```bash
$ nice -10 celery worker ...
```
