### ISSUE TITLE
Python 3.7 syntax error: async is a reserved keyword

### ISSUE THREAD

**Issue by hroncok** [celery/celery#4849]
## Checklist

Happens on master and previously released versions as well.

## Steps to reproduce

See https://github.com/celery/celery/blob/b2668607c909c61becd151905b4525190c19ff4a/celery/backends/redis.py#L22 and https://github.com/celery/celery/blob/b2668607c909c61becd151905b4525190c19ff4a/celery/backends/rpc.py#L20 and https://github.com/celery/celery/blob/master/celery/backends/async.py

## Expected behavior

Module should not be named async.

## Actual behavior

Module is named async.

## More info

I fail to run 3.7 test easily, but this leads to:

```
  File "celery/backends/redis.py", line 22
    from . import async, base
                      ^
SyntaxError: invalid syntax
```

**Comment by georgepsarakis** [comment]
Nice catch. This is already handled in #4500. The module will be renamed to `asynchronous` soon. @auvipy should we close as duplicate?

**Comment by hroncok** [comment]
Sure. Sorry I haven't noticed that one.

**Comment by auvipy** [comment]
i will take care of this today

**Comment by hroncok** [comment]
Since #4500 is closed, I'm reopening this one.

**Comment by auvipy** [comment]
yeah ok I have already started working

**Comment by nitinnain** [comment]
bump: I just got affected by this after updating to Python 3.7 . 
I've added a Pull Request for the bugfix.

**Comment by auvipy** [comment]
work in progress https://github.com/celery/celery/pull/4852

**Comment by auvipy** [comment]
work is merged in master

**Comment by hroncok** [comment]
Can we anticipate a quick release or not? Just want to make sure whether we need to patch the Fedora package or wait.

**Comment by auvipy** [comment]
we have a plan to release a minor on before the end of this month

**Comment by hroncok** [comment]
Thanks.

**Comment by Avamander** [comment]
If anyone needs the changes right now then you can do `pip install --upgrade https://github.com/celery/celery/tarball/master` to get the fixes temporarily directly from development branch. Maybe it saves people finding this issue from Google some effort.

**Comment by sklarsa** [comment]
I'm still getting this error when trying to run celery 4.2.1, will this fix be available in an upcoming release?

**Comment by auvipy** [comment]
yes, try master branch if you are in hurry for python 3.7

**Comment by metakermit** [comment]
Yup, would be nice to have this fixed soon, since Python 3.7 is the default you get on python.org / homebrew etc.

**Comment by metakermit** [comment]
OK, correction – the above doesn't work in pipenv (at least not as part of a Docker build with a step `RUN pipenv install --system --dev`). I'm getting ImportErrors for celery not being there (I think it's because it gets placed in some local src folder for some reason).

I've also tried the following:

```shell
pipenv install https://github.com/celery/celery/tarball/master
```

in which case celery does get installed and can get imported, but it seems that this command doesn't install the dependencies…

```
web_1     |   File "/usr/local/lib/python3.7/site-packages/celery/five.py", line 7, in <module>
web_1     |     import vine.five
web_1     | ModuleNotFoundError: No module named 'vine'
```

So, Celery is now broken if you want to use latest stable Python, Pipenv + Docker 😢.

**Comment by metakermit** [comment]
Regarding [installation of Celery from GitHub as editable](https://github.com/celery/celery/issues/4849#issuecomment-418798006) which seems to be a Pipenv issue, I've opened a [bug there](https://github.com/pypa/pipenv/issues/2872).
