### ISSUE TITLE
 Declaring event listener (in separate thread) cause task executing hangs on delay()

### ISSUE THREAD

**Issue by Bartoneczek** [celery/celery#4861]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Report output:

> software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.4
>             billiard:3.5.0.3 py-amqp:2.3.2
> platform -> system:Darwin arch:64bit imp:CPython
> loader   -> celery.loaders.app.AppLoader
> settings -> transport:amqp results:amqp:///
> 
> broker_url: 'amqp://guest:********@rabbitmq:5672//'
> result_backend: 'amqp:///'
> include: ['impa.server']
> broker_heartbeat: 0
> task_track_started: True
> worker_send_task_events: True

I've got an app with Flask and Celery and there are two modules. In first module, there is a Flask app object and defined endpoint which calls celery task (also defined in this module).

In second module, there is a Celery object defined and class which run event listener for Celery:

`class MonitorThread(object):
        def __init__(self, celery_app):
            self.celery_app = celery_app

            self.state = self.celery_app.events.State()

            self.thread = threading.Thread(target=self.run, args=())
            self.thread.daemon = True
            self.thread.start()

        def catchall(self, event):
            print(event['type'])

        def run(self):
            try:
                with self.celery_app.connection() as connection:
                     recv = self.celery_app.events.Receiver(connection, handlers={
                        '*': self.catchall,
                    })
                    recv.capture(limit=None, timeout=None, wakeup=True)
            except Exception as ex:
                print(ex)`

When I create `MonitorThread` object in celery module and run it like `celery worker -A proj` and call some Flask endpoint which call Celery task, it hangs on delay() function. If I remove `MonitorThread`, everything works well. 

So: running event listener (even on separate thread) cause task call hangs. I debugged connection and there is no RabbitMQ disconnections.

## Expected behavior
Task is executed and event listener doesn't impact it.

## Actual behavior
Declaring event listener cause task executing hangs.

**Comment by auvipy** [comment]
whats the current status of the issue?
