### ISSUE TITLE
Make retries as "error" messages?

### ISSUE THREAD

**Issue by rprots** [celery/celery#4872]
## Expected behavior
It makes sense to change to "error" so these events are tracked since these seem to be more priority than other "info" messages.

## Actual behavior

These are logged as "information" messages:

```
info(LOG_RETRY, {
--
'id': req.id,
'name': get_task_name(req, task.name),
'exc': text_t(reason),
})



```

**Comment by amirouche** [comment]
It's an expected behavior so it can not be an error. The maxium level I would agree with is `warning` but even that is dubious.
