### ISSUE TITLE
Synchronous subtask guard blocks chord() when CELERY_TASK_ALWAYS_EAGER=True

### ISSUE THREAD

**Issue by jcushman** [celery/celery#4873]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

```
$ celery -A minimal_eager_chord report
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.5.3
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

Script to reproduce: 
https://gist.github.com/jcushman/ea8adcb37dffdf5c3fdf756d02366ab2

## Expected behavior

No error occurs

## Actual behavior

```
In [1]: test.delay().get()

...

~/minimal_eager_chord.py in test()
     27 def test():
     28     chord(
---> 29         a.s(), b.s()
     30     ).apply_async()
     31

...

~/.pyenv/versions/3.5.3/envs/capstone/src/celery/celery/result.py in assert_will_not_block()
     39 def assert_will_not_block():
     40     if task_join_will_block():
---> 41         raise RuntimeError(E_WOULDBLOCK)
```

## Comments

This is a similar issue to #4576: `assert_will_not_block()` is triggered when using canvas functions with `CELERY_TASK_ALWAYS_EAGER=True`, even when they are used with apply_async(). 

The patch for that issue fixed `chain()` but not `chord()`, and the problem may exist for other canvas functions as well. I'm not sure whether it makes sense to add more calls to `with allow_join_result():` in `celery/canvas.py` (as in the patch for #4576), or if `assert_will_not_block()` could be modified to avoid false positives from `CELERY_TASK_ALWAYS_EAGER=True` in general.

The tricky bit of a general solution would be that the guard should still detect actual unsafe subtasks even if `CELERY_TASK_ALWAYS_EAGER=True`, since that's a natural way to run tests.

**Comment by noirbizarre** [comment]
Same issue here: our tests are using `CELERY_TASK_ALWAYS_EAGER=True` and tests using `chords()` fail with the same stacktrace

**Comment by noirbizarre** [comment]
Done in #4979
