### ISSUE TITLE
Custom headers not propagated as documented ?

### ISSUE THREAD

**Issue by frivoire** [celery/celery#4875]
## Intro
I cannot get to work properly with custom (additional) headers : they dont seem to be readable by the consumer, or at least not the way it's documented.

With this setup :
```
$ celery report

software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.14
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

## Steps to reproduce

**1.** Prepare minimal venv :
```
virtualenv venv
source ./venv/bin/activate
pip install celery==4.2.0
```
**2.** Start a rabbitmq with default configuration, exactly it's the Docker image `rabbitmq:3-management`, so RabbitMQ 3.7.3 (Erlang 20.2.2)
**3.** Create a task with 2 additionnal headers, like this : `./venv/bin/python create_task.py`
```
from celery import Celery

app = Celery('proj', broker='amqp://guest@127.0.0.1:5672')

mydict = {'customheader1':'foo', 'customheader2':'bar'}
app.send_task('proj.add', [23, 45], headers=mydict)
```
**4.** Check that the task created in RabbitMQ contains the 2 headers ==> yes, it seems OK 
**5.** Launch the worker : `./venv/bin/python worker.py worker -l INFO`
```
from celery import Celery
from celery.utils.log import get_task_logger

app = Celery('proj', broker='amqp://guest@127.0.0.1:5672')
logger = get_task_logger(__name__)

@app.task(bind=True)
def add(self, x, y):
    logger.info("self.request.headers: %s", self.request.headers)
    logger.info("self.request.customheader1: %s", self.request.customheader1)
    logger.info("self.request.customheader2: %s", self.request.customheader2)
    return x + y

if __name__ == '__main__':
    app.start()
```
**6.** Observe that headers are not where it's documented :
    - http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-request says that `app.Task.request` should contains an attribute `headers` with this description `Mapping of message headers sent with this task message (may be None)`
    - but this `headers` attribute seems also empty, cf below :

## Actual behavior
```
$ ./venv/bin/python worker.py worker -l INFO

celery@mbp-fri.local v4.2.0 (windowlicker)
Darwin-17.6.0-x86_64-i386-64bit 2018-07-03 10:30:38

[config]
.> app:         proj:0x10b016810
.> transport:   amqp://guest:**@127.0.0.1:5672//
.> results:     disabled://
.> concurrency: 8 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery

[tasks]
  . proj.add

[2018-07-03 10:30:38,684: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-07-03 10:30:38,698: INFO/MainProcess] mingle: searching for neighbors
[2018-07-03 10:30:39,731: INFO/MainProcess] mingle: all alone
[2018-07-03 10:30:39,750: INFO/MainProcess] celery@mbp-fri.local ready.
[2018-07-03 10:30:41,598: INFO/MainProcess] Received task: proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]
[2018-07-03 10:30:41,601: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.headers: None               <=====
[2018-07-03 10:30:41,602: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.customheader1: foo
[2018-07-03 10:30:41,602: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.customheader2: bar
[2018-07-03 10:30:41,603: INFO/ForkPoolWorker-2] Task proj.add[0d6163f3-5457-4267-820f-645de40ad2ed] succeeded in 0.00254076899728s: 68
```

## Expected behavior

```
[same startup]
[2018-07-03 10:30:41,598: INFO/MainProcess] Received task: proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]
[2018-07-03 10:30:41,602: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.headers: {'customheader2': 'bar', 'customheader1': 'foo'}              <=====
[2018-07-03 10:30:41,602: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.customheader1: None
[2018-07-03 10:30:41,602: INFO/ForkPoolWorker-2] proj.add[0d6163f3-5457-4267-820f-645de40ad2ed]: self.request.customheader2: None
[2018-07-03 10:30:41,603: INFO/ForkPoolWorker-2] Task proj.add[0d6163f3-5457-4267-820f-645de40ad2ed] succeeded in 0.00254076899728s: 68
```

## Conclusion

So, I think there is something wrong about handling of custom headers.
Another aspect that is not described above : how to iterate on custom headers ? It seems impossible, since they are mixed with "system headers" (argsrepr, eta, expires, group, id, etc.)

Of course, if I've missed something in the doc, in my code, or somewhere else, I appreciate any advices/critics :)

**Comment by frivoire** [comment]
And here is a screenshot of the RabbitMQ message (cf step 4) :

![Rabbitmq management interface](https://image.ibb.co/ksztmd/task_as_seen_in_Rabbit_MQ_mgt_interface.png)

**Comment by auvipy** [comment]
whats the latest resolution of the issue? and my apologies for the late response.

**Comment by frivoire** [comment]
No resolution (AFAIK) yet, so nothing new.
Do you think that more infos are needed to describe my question/issue ?

**Comment by nh2d** [comment]
+1 I believe I am facing the same issue upgrading from 4.0.3 to 4.2.1 @auvipy

**Comment by bbain** [comment]
We are also having problems with this issue. 

The description of this issue is 100% accurate for our problems as well. Additionally, I wanted to say that if you run the task synchronously with `task.apply(headers=headers)` or have `task_always_eager = True` configured then the `headers` are copied to `task.request.headers` as expected.

Looking through the code it seems that https://github.com/celery/celery/blame/681a92222038ca89e28dc5fb06200145f77224f5/celery/app/amqp.py#L495 is the problem. Its merging the user provided `headers` rather than creating a new `headers` field. For example the following change will make the `headers` appear on `task.request.headers`.

```python
if headers:
  headers2['headers'] = headers
```

I have absolutely no idea what this would break or if its even correct.

**Comment by rogerio-geru** [comment]
Also, unfortunately, none of the ways are getting set in a Signal...
```
@task_prerun.connect
def task_log_prerun(task=None, **kwargs):
    print task.request.headers
    print task.request.customheader1
```
This would be very important to work.
Thanks.

**Comment by clokep** [comment]
This smells like it might be related to protocol v2 vs. v1? Does this issue disappear if you use protocol v1?

**Comment by rogerio-geru** [comment]
Thanks @clokep, but unfortunately it doesn't.

In protocol v1 (task.request):
```
<Context: {u'chord': {u'chord_size': 863, u'task': u'next_task_name', u'args': (), u'immutable': False, u'subtask_type': None, u'kwargs': {}, u'options': {u'reply_to': '565d0aaf-92a6-3cff-b527-b2688ccb3f78', u'task_id': '52cace6b-f1fa-4dc2-920f-934e0128ebd9'}}, u'chain': None, u'utc': True, u'args': (u'b0a6390b22b748b582ce8b006d72ee37',), u'callbacks': None, u'correlation_id': '9da4df39-84e0-47ad-ba14-9176ab15a4a2', u'errbacks': None, u'reply_to': '565d0aaf-92a6-3cff-b527-b2688ccb3f78', u'taskset': '7f285066-206e-4728-8ef3-6f6282a016f1', u'id': '9da4df39-84e0-47ad-ba14-9176ab15a4a2', 'kwargsrepr': u'{}', 'called_directly': False, u'retries': 0, u'task': 'task_name', u'group': '7f285066-206e-4728-8ef3-6f6282a016f1', u'is_eager': False, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'queue', u'exchange': ''}, u'hostname': u'celery@68797283515d', u'expires': None, 'headers': {}, 'argsrepr': u"('b0a6390b22b748b582ce8b006d72ee37',)", u'timelimit': (None, None), u'kwargs': {}, u'eta': None}>
 ```
Note that ** 'headers': {}** is here, but empty.

In protocol v2:
```
<Context: {'origin': 'gen6312@68797283515d', u'args': (u'b1d81b6dc0344d27a626924c941989f5',), u'chain': None, 'root_id': '511ae270-5345-4535-8653-4c6e0246b983', 'expires': None, u'is_eager': False, u'correlation_id': '149de94b-6eae-46fb-801e-2db3b7714cd7', u'chord': {u'chord_size': 863, u'task': u'next_task_name', u'args': (), u'options': {u'reply_to': 'c15d06f3-23cf-344f-ad7c-6dd555af2ad6', u'task_id': '0867f376-81c7-4d5d-988b-6cf88e9dc101'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}, u'reply_to': 'c15d06f3-23cf-344f-ad7c-6dd555af2ad6', 'id': '149de94b-6eae-46fb-801e-2db3b7714cd7', 'kwargsrepr': '{}', 'lang': 'py', 'retries': 0, 'task': 'task_name', 'group': 'a5daff9d-201a-48f7-9b69-d0fd32db40ec', 'timelimit': [None, None], u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'queue', u'exchange': ''}, u'hostname': u'celery@68797283515d', 'called_directly': False, 'parent_id': '511ae270-5345-4535-8653-4c6e0246b983', 'argsrepr': "('b1d81b6dc0344d27a626924c941989f5',)", u'errbacks': None, u'callbacks': None, u'kwargs': {}, 'eta': None}>
```
`headers` does not even appear here.

**Comment by rogerio-geru** [comment]
I'm sorry @clokep, it does work! It was a mistake in another point of my code (I did delete the messages to not confuse anyone).
And actually FWIW, it is related to protocol as you thought. In v1 it fails in both task and Signal, in v2 it works in both.

Now I'm waiting for `headers` field to work, as in this ticket.
Thanks again!

**Comment by Chikashi-Kato** [comment]
This is just a hack, but we can make this work by putting the custom headers to under `headers` property of headers parameter (Just use the solution of @bbain).

Here is the example:
```
mydict = {'customheader1':'foo', 'customheader2':'bar'}
headers_hack = {'headers': mydict}
app.send_task('proj.add', [23, 45], headers=headers_hack)
```

Once this issue is fixed in the next release, this hack obviously stops working.
But, this might be useful, if you really want to use the custom headers now.

**Comment by thedrow** [comment]
I'm going to check this out soon...

**Comment by avodaqstephan** [comment]
Are there any news to this issue? I try to pass headers through for monitoring/tracing reasons and this kind of a show stopper.

**Comment by flocreate** [comment]
custom header still not working ? cant make it work...

**Comment by andyneff** [comment]
It still _behaves_ the same way in 4.4.2, custom headers show up in `self.request`, not `self.request.headers`.

Personally, I'm okay with this behavior, if the docs just made that clear.

**Comment by jheld** [comment]
We shouldn't be okay with this behavior. It's a violation.

Given that it _technically_ is an incompatible change (fixing it), we likely can only do it on a minor release (not patch release).

Do we think the solution @bbain illustrated is good to make a PR for? And yes, writing/fixing tests as best as possible.

**Comment by auvipy** [comment]
I think PR is OK to improve it

**Comment by frivoire** [comment]
I have to admit that I won't really be able to help on this issue (or spent time on celery) anymore.
Sorry about that. And thanks to everyone :)

**Comment by aniforprez** [comment]
This is sorted in v5.0.1 right? Can this issue be closed?

**Comment by aniforprez** [comment]
I can verify that this is indeed working as of celery v5.0.2. Thanks for the fix @beezz !

**Comment by aniforprez** [comment]
Unfortunately it seems like the issue has cropped up again when retrying. Consider the following task:

```python
@shared_task(autoretry_for=(CustomException,),
    retry_kwargs={"max_retries": 3},
    retry_backoff=5,)
def do_thing():
    raise CustomException
    return "thing"
```

and a custom task class
```python
class CustomTask(Task):
    def apply_async(self, args=None, kwargs=None, **options):
        headers = {"sample_header": "thing"}
        return super().apply_async(args=args, kwargs=kwargs, headers=headers, **options)

    def on_retry(self, exc, task_id, args, kwargs, einfo):
        sample = self.request.get("sample_header")
        print(f"ON RETRY: {sample}")

        return super().on_retry(exc, task_id, args, kwargs, einfo)

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        sample = self.request.get("sample_header")
        print(f"ON FAILURE: {sample}")

        return super().on_failure(exc, task_id, args, kwargs, einfo)
```

On unhandled failures for exceptions other than `CustomException` I get the failure message properly as `ON FAILURE: thing` but when the task retries the output is
```
...
ON RETRY: None
...
ON FAILURE: None
```

**Comment by aniforprez** [comment]
Can we reopen this issue or should I create a separate issue about this problem?

**Comment by aniforprez** [comment]
Can this issue be reopened or should I create a new issue for this problem? Seems related

**Comment by thedrow** [comment]
Please open a new issue so we can track this. This could be a case we haven't covered yet.

**Comment by brmzkw** [comment]
@aniforprez did you create an issue? If so, I couldn't find it. Can you put a link here?

**Comment by aniforprez** [comment]
@brmzkw sorry I haven't created an issue. Life got in the way

**Comment by ferndot** [comment]
This seems to still be an issue in Celery 5.3.6. When running eagerly, the custom headers I set are located on `task.request.headers`. However, they are set on `task.request` when running in a production environment.

**Comment by sk-** [comment]
We were implementing some monitoring and faced the same issue. For some reason it worked locally but not in prod. The solution was to set the headers just like many other tracing tools (sentry, dd-tracing) have done, which is the same hack presented in comment https://github.com/celery/celery/issues/4875#issuecomment-473507513

**Comment by julienc91** [comment]
> they are set on `task.request` when running in a production environment.

I observed the same behaviour (eager mode or not), and was able to link it to the integration of sentry-sdk: as soon as the integration was disabled, `task.request.headers` contained the expected values. As a workaround, I'm reading the headers in `task.request` directly instead.
