### ISSUE TITLE
IndexError: list index out of range in celery 

### ISSUE THREAD

**Issue by ravigoti** [celery/celery#4894]
I am using Celery 4.2.0 and Django 2.0.6 for queueing tasks. A lot of my tasks are failing with the error
IndexError: list index out of range
This also does not always happen. Only sometimes abruptly.
Is this a known issue ?

**Comment by clokep** [comment]
Can you give more information? What's your configuration? Is there a longer stack trace you can provide?

**Comment by ravigoti** [comment]
Sorry for the false alarm. Please ignore this error. Turns out it was an issue on our end.
