### ISSUE TITLE
CELERY_QUEUE_HA_POLICY has no effect on RabbitMQ 3 due to change of x-ha-policy to ha-mode

### ISSUE THREAD

**Issue by joekohlsdorf** [celery/celery#4896]
Celery leaves you with the impression that RabbitMQ queues are getting mirrored if you set `CELERY_QUEUE_HA_POLICY = 'all'`.
This does not make queues mirrored in RabbitMQ 3 (released 2012).
The required policy string was changed from `x-ha-policy: all` to `ha-mode: all`:
http://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/

Problematic code in current `master`:
https://github.com/celery/celery/blob/e7002769211f7340f38df80b3112706a8e07cafb/celery/app/amqp.py#L142

**Comment by auvipy** [comment]
what is the suggested fix?

**Comment by joekohlsdorf** [comment]
change the linked code from this:
```python
    def _set_ha_policy(self, args):
        policy = self.ha_policy
        if isinstance(policy, (list, tuple)):
            return args.update({'x-ha-policy': 'nodes',
                                'x-ha-policy-params': list(policy)})
        args['x-ha-policy'] = policy
```

to this:
```python
    def _set_ha_policy(self, args):
        policy = self.ha_policy
        if isinstance(policy, (list, tuple)):
            return args.update({'ha-mode': 'nodes',
                                'ha-params': list(policy)})
        args['ha-mode'] = policy
```

**Comment by auvipy** [comment]
thanks, will do so. hope you will have time to review the pr.
