### ISSUE TITLE
One queue and many workers that execute tasks based on age and priority 

### ISSUE THREAD

**Issue by amirouche** [celery/celery#4901]
It will be nice to be possible to specify a single queue with many workers. Workers would run tasks based on priority **and age**. That way, it's easier to scale because there is a single pool of worker.

That leads to a more monolithic code base because all workers must be able to execute any tasks.

My understanding is that AMQP or rabbitmq doesn't offer that feature, any idea how this could be implemented using REDIS?

**Comment by joekohlsdorf** [comment]
This is exactly how RabbitMQ and the default setup of Celery works.

It creates one queue `celery` and you start as many workers as you like which will start to process tasks from that queue based on enqueuing order and priority.

**Comment by amirouche** [comment]
What is the algorithm used to compute the next task?

**Comment by xirdneh** [comment]
Depending on the prefetch configuration, yes.
Also, rabbit mq and Redis offers priorities. But those priorities are based on a fixed weight.
I'm more curious about what you mean by "based on priority and age".
The messages should get handled by workers based on First-In-First-Out (FIFO) as well as priorities (if your broker and your configuration can work with it)

**Comment by amirouche** [comment]
Well, because devops is difficult. I want to scale a single pool of worker (and single codebase).

In the end, I'd like only to only specify priority using an enum for instance:

```Python
from enum import Enum

class Priority(Enum):
    realtime = 'realtime'
    high = 'high'
    default = 'default'
    low = 'low'
```

Then, I will dispatch task using those priorities for instance:

```python
@app.task
def add(a, b):
    return a + b

add.delay(20, 22, priority='high')
```

Then in some interface I can monitor how many times tasks of each priority stay in the queue. For instance, I can't afford `realtime` task to stay more than a few `ms` in the queue. Then for `high` let's say it's a few seconds like 3 seconds and finally for `low`, it's only best effort so I can afford those task to stay 24h in the queue. That information : «how much time a tasks stays in a queue depending on its priority » can be queried from the devops team to be monitored, graphed and acted upon.

In my mind, this can be implemented using a single task queue and a function that scores tasks taking into account the `priority` and `age` aka. the time since the task was added to the queue. Something like the scoring algorithm for stories on website like reddit or hackernews but with different tweaking is what I have in mind.

@xirdneh Indeed it might already exist.

**Comment by joekohlsdorf** [comment]
Did you look at the Celery documentation?

You specify priority in your task: 
```
@app.task(queue = 'demo_task', priority = 5)
```

RabbitMQ then gives you messages with higher priority first, always with FIFO ordering.

> That information : «how much time a tasks stays in a queue depending on its priority » can be queried from the devops team to be monitored, graphed and acted upon.

To achieve this you'll have to record the data on your own, neither Celery nor RabbitMQ give you that information. You also have no way of knowing what type of tasks are queued up unless you record that data on your own. And for that reason it is in my experience better to have per-task queues.

**Comment by amirouche** [comment]
> To achieve this you'll have to record the data on your own, neither Celery nor RabbitMQ give you that 
> information. You also have no way of knowing what type of tasks are queued up unless you record 
> that data on your own. And for that reason it is in my experience better to have per-task queues.

That also my understanding, hence that issue.

**Comment by amirouche** [comment]
You specify priority in your task:

```python
@app.task(queue = 'demo_task', priority = 5)
```

I need to be able to override priority in call site.

**Comment by amirouche** [comment]
I want to configure priorities in terms of how much time it takes to run the task.

**Comment by joekohlsdorf** [comment]
How is a message broker or a task executor supposed to achieve that? It all depends on the amount of workers you throw at it. If you measure the time it takes from a task being enqueued to it getting processed by a worker you can scale your workers based on your requirements. I guess the same could be achieved by monitoring the amount of tasks enqueued if you know how much time they take to execute.

**Comment by amirouche** [comment]
> I guess the same could be achieved by monitoring the amount of tasks enqueued if you know how much time they take to execute.

I agree.

**Comment by xirdneh** [comment]
Let me see if I got this clear. Say we have these three different tasks: _add_, _mul_ and _sum_.
And they take **x**, **y** and **z** time units to run respectively:
1. Run _n_ workers consuming on **one** queue.
2. Queue multiple different tasks with different priorities. 
3. Calculate the next task to run (for _task_ in _tasks_):
    3.1. If _task_ has a higher priority than any other task
        3.1.1 Run _task_
    3.2 if more than one _task_ have the same priority
        3.2.1 If _task_ has an **queued datetime** older than any task in _tasks_ (e.g. got queued before any other task)
            3.2.1.1 Run _task_
        3.2.2 Else
            3.2.2.1 get every task with the same priority and **queued time** in _tasks_to_run_
            3.2.2.2 Sort _tasks_to_run_ based on the time each task takes to run (**x**, **y** or **z**)
            3.2.2.3 Run _task_

Is this something like what you have in mind?
Keep in mind this is very raw :)

**Comment by amirouche** [comment]
> Also in this context a queue will no longer be a queue since it wouldn't be FIFO.

Is it a leaderboard?

**Comment by xirdneh** [comment]
It would be more of a weighted heap. So yes, something like a modified leaderboard.
That becomes problematic because this is implemented on the broker level.
We're talking about creating a new broker protocol.

**Comment by auvipy** [comment]
closing it as the design doesn't seem to be much concrete.
