### ISSUE TITLE
Retries are not being set in Events

### ISSUE THREAD

**Issue by rsalmei** [celery/celery#4904]
Hello,

I'm the developer of [Clearly](https://github.com/rsalmei/clearly), a real-time monitor for celery.

After a few hours debugging why the Task objects weren't getting set the `retries` field, despite it was correct in the `task-received` event, I've found the bug, it's a simple missing comma in:
https://github.com/celery/celery/blob/master/celery/events/state.py#L283

This is what I get in any celery >= 4:
![image](https://user-images.githubusercontent.com/6652853/42661258-0628b4bc-8604-11e8-9cba-a8f10553c7c0.png)

And this was what I expected (celery >3.1,<4):
![image](https://user-images.githubusercontent.com/6652853/42661338-4ba60aee-8604-11e8-8221-fdd63cf4efc1.png)

Thank you, and congrats on the nice project!

**Comment by russoz** [comment]
may I suggest you leave a pull request for it?

**Comment by auvipy** [comment]
please send a pull request.
