### ISSUE TITLE
rotate log file in celery

### ISSUE THREAD

**Issue by better629** [celery/celery#4905]
## Target
I want to flush all log to local files in different task(maybe a task a file) without -f flag when celery app starts, and want to rotate these files with TimedRotatingFileHandler in logging.
the app config worker_hijack_root_logger is set to false.

## Questions
1、If worker_hijack_root_logger is enabled without -f flag，the app will print default log to stderr with worker_log_format。If you want to print logs under task_function，you need to configure logging.basicConfig with the worker_log_forma. Otherwise, the default log will look like
`[2018-07-13 17:05:11,957: INFO/MainProcess] Connected to %s `
`[2018-07-13 17:05:12,034: INFO/MainProcess] mingle: searching for neighbors`

2、If you want to custom your own log, you can use celery.signals.after_setup_logger

`from celery.signals import after_setup_logger`
`@after_setup_logger.connect`
`def reset_log_config(logger, **kwargs):`
`    # define you log handler`
`    pass`

But it seems that TimedRotatingFileHandler is not thread safe, when I custom my handler in reset_log_config function with TimedRotatingFileHandler. It will rotate serveral log under different task_id.

Anyone knows how to rotate log files in celery ???
Thx~

**Comment by xirdneh** [comment]
It seems like python's rotate file is indeed thread safe: https://bugs.python.org/issue24262
Maybe the issue is in your setup.

Is the issue that there's multiple task ids?
Because every task has it's own id.
