### ISSUE TITLE
Aync fix included in 4.2.1 not actually included in 4.2.1

### ISSUE THREAD

**Issue by Tiedye** [celery/celery#4916]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

I've updated to https://github.com/celery/celery/releases/tag/v4.2.1 to get the fix in this commit https://github.com/celery/celery/commit/e7002769211f7340f38df80b3112706a8e07cafb which is listed to be included in 4.2.1, but when viewing the affected file after installation `celery/backends/redis.py` the fix is not present.  I've checked `__init__.pt` and the version is listed as 4.2.1.

**Comment by auvipy** [comment]
@thedrow

**Comment by thedrow** [comment]
I'll release a new version today.

**Comment by thedrow** [comment]
We don't officially support Python 3.7 yet.
That will happen in Celery 4.3.
Kombu does support 3.7 since we already did the prep work there.
Where do you see the commit listed? It's not on the change log.

**Comment by Tiedye** [comment]
https://github.com/celery/celery/compare/v4.2.1...master

**Comment by thedrow** [comment]
Master is 4.3.
The release branch for 4.2.1 is 4.2.
I cherry picked all the commits to there.

**Comment by Tiedye** [comment]
Ah my bad I read 
![image](https://user-images.githubusercontent.com/6187173/43016435-d4115ce0-8c20-11e8-867c-eca31c07f203.png)
as `26 commits included in this tag` = since last release.  Closing the issue

**Comment by kylebebak** [comment]
Any timeline on the 4.3 release?

**Comment by thedrow** [comment]
Not yet unfortunately.
I'm pretty tired from 4.2, but we're still merging PRs.
