### ISSUE TITLE
Worker doesn't execute task after 5 minutes idle

### ISSUE THREAD

**Issue by tdna** [celery/celery#4921]
## Steps to reproduce
run rabbitmq 3.7.7, celery 4.2.0

Run celery worker: `celery -A tasks worker --loglevel=debug`
Run client.py: `python client.py`

wait 5 minutes and run client.py again

tasks.py
```python
from celery import Celery


# app = Celery('tasks', broker='redis://localhost:6379/0', backend='redis://localhost')
app = Celery('tasks',
             broker='amqp://localhost:5672',
             broker_heartbeat=15,
             backend='rpc://')


@app.task
def add(x, y):
    return x + y


@app.task
def mul(x, y):
    return x * y
```

client.py
```python
from celery import group
from tasks import add, mul


r = (add.s(3, 4) | add.s(6))
r2 = mul.s(3, 5)

g = group([r, r2]).apply_async()

print(g)
print(g.get())
```

## Expected behavior
prints: `[13, 15]`

## Actual behavior
Hanging in the middle of the chain and doesn't get the result.
Worker doesn't get any tasks.

**Comment by ayderGH** [comment]
I have the same problem. Do somebody know why?

**Comment by auvipy** [comment]
could you change the backend from rpc to something else?

**Comment by ayderGH** [comment]
`broker_pool_limit = None` helped me

**Comment by tdna** [comment]
Unfortunately setting `broker_pool_limit=None` didn't solve the problem.

**Comment by auvipy** [comment]
could you try py-amqp as the broker?

**Comment by auvipy** [comment]
hope celery 4.4rc2 fix this?
