### ISSUE TITLE
Runtime Configuration Strategy for Workers

### ISSUE THREAD

**Issue by dmlb2000** [celery/celery#4926]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

I want to program a worker to handle `argparse` for custom command line options for my tasks.

## Expected behavior

Some documentation on how to use `argparse` with custom configuration options for worker tasks

## Actual behavior

Searching doesn't get what I'm looking for... some help would be good.

**Comment by auvipy** [comment]
better ask this question on irc or mailing list.
