### ISSUE TITLE
custom task class with on_failures fails to catch certain Exceptions.

### ISSUE THREAD

**Issue by sivang** [celery/celery#4932]
How to reproduce:
```
class ReplayableTask(celery.Task):
    def on_failure(self, exc, task_id, args, kwargs, einfo):
        print ("Exception caught: {}".format(exc))
        client = MongoClient()
        processing = client.processing
        failures = processing.failures
        failures.insert_one({"exc" : str(exc), 
                                "task_id" : str(task_id), 
                                "args" : str(args), 
                                "kwargs" : str(kwargs), 
                                "einfo" : str(einfo) })
        del client
        del processing
        del failures

@app.task(base=ReplayableTask, bind=True)
def download(self, **kwrags):
       import time
       time.sleep(1200)
```

...
...

In celeryconfig.py:

task_time_limit = 30 (or any smaller figure to help testing).

Run the task and wait for the timeout, in my setting only the non TimeLimitExceeded exceptions are logged into mongodb. Desire behavior, all tasks failed as appearing in the result collection should be caught.

**Comment by sivang** [comment]
tested with 4.1.0 (latentcall), checked out from master. e.g:
e7002769211f7340f38df80b3112706a8e07cafb

**Comment by sivang** [comment]
Was it unreproducible ?

**Comment by auvipy** [comment]
> Was it unreproducible ?

sorry, I closed it mistakenly and later didn't notice your comment!
