### ISSUE TITLE
[feature request] don't ask about result backend if chord callback has immutable signature

### ISSUE THREAD

**Issue by vanyakosmos** [celery/celery#4934]
## Checklist
- [x] I haven't included the output of ``celery -A proj report`` in the issue. But here is version of celery: `4.2.0`.

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```python
from celery import chord
chord(jobs, callback.si())
```

## Wanted behaviour
everything is fine

## Actual behaviour
`NotImplementedError: Starting chords requires a result backend to be configured.`

**Comment by vaniakosmos** [comment]
it is feature request, nothing is wrong with celery (except for lack of this feature)

**Comment by clokep** [comment]
I suspect the configuration would be useful here? (`celery -A proj repo`) Does a `chord` require a backend in order to push results along or something?

**Comment by auvipy** [comment]
I wanted to know If you are able to implement this feature? what changes are needed to implement it?

**Comment by auvipy** [comment]
NotImplementedError: Starting chords requires a result backend to be configured. -- based on this should we close the issue for now?

**Comment by thedrow** [comment]
Yes, I don't think we have a way to implement this.
