### ISSUE TITLE
[documentation] broker_transport setting needs documentation

### ISSUE THREAD

**Issue by jakubczaplicki** [celery/celery#4937]
## Steps to reproduce/Expected behavior/Actual behavior

I have switched my project from the old configuration (uppercase) to use the new (lowercase) Celery configuration. I followed the documentation http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings 

After replacing `CELERY_BROKER_URL="sqs://"` with `broker_url="sqs://"`, Celery didn't recognise this particular setting and defaulted to `transport:   amqp://guest:**@localhost:5672//`

Only after trying few combinations of the names I found out that I need to use `broker_transport = 'sqs'` instead. 

It would be worth adding an explanation in what circumstances `broker_url` and `broker_transport` should be used.

**Comment by asterion2nd** [comment]
@jakubczaplicki are you using Django?

**Comment by jakubczaplicki** [comment]
@asterion2nd :  no.

**Comment by odigity** [comment]
I was also wondering about the setting "BROKER_TRANSPORT", and then learned from this issue that it is deprecated - replaced by "BROKER_URL".

https://github.com/celery/celery/issues/3775

The docs should probably be updated to reflect that:

https://docs.celeryproject.org/en/stable/userguide/configuration.html#new-lowercase-settings

**Comment by auvipy** [comment]
https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-broker_url
