### ISSUE TITLE
Routing to a specific process inside a Celery worker

### ISSUE THREAD

**Issue by xavierhardy** [celery/celery#4947]
The documentation clearly states how to route to specific Celery worker using the `worker_direct` option.
https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_direct

However, in my case, I would like to go further and to select not only a particular worker but a particular process inside that worker because I need access a resource that this process is holding, and there is an overhead when accessing this resource for the first time.

Of course, one solution would be to set concurrency to 1, but is there to define queues (routing keys) for each process, rather than for each worker, please?

If there are 5 Celery workers with 6 processes each (`worker_concurrency = 6`), I would need 30 queues, one for each process, rather than only 5.

**Comment by xavierhardy** [comment]
I think this issue is more of a feature request than a question actually, but I might be wrong. Could you please provide a reason why this issue has been closed please?

Is it fixed? If yes, then, how is it done?
Is it a "won't fix"? If yes, why?

Thanks in advance

**Comment by xavierhardy** [comment]
Note that I am ready to contribute if necessary.

**Comment by hp685** [comment]
What type of resource is the process holding? If it is something instantiated within a process, it is probably the state that you care about.

**Comment by xavierhardy** [comment]
It's an SSH or HTTPS session to an external device. We would like to reuse the connection. If there's only one process per worker, it's "easy" (though you need to have to monitor the connections in some way), use the `worker_direct` option and always use the same worker using an hashing mechanism based on the destination host name.

**Comment by hp685** [comment]
How about using two workers -  A gevent worker (with concurrency set) to maintain network connections to external hosts and a prefork worker(w/processes) that routes I/O tasks to the gevent worker?  This decouples stateful aspects, from rest of the application logic that can be processed by *any* prefork process. 
Of course the feature ask if implemented will also solve the problem.

**Comment by xavierhardy** [comment]
I see only two problems with that:
- eventlet won't work with C extensions (think pycurl or ssh2-python)
- the eventlet worker will be able to use only one processor (which is not problem for us)

**Comment by xavierhardy** [comment]
Apparently as those two libraries provide non-blocking modes, it might be possible to work around this problem.

**Comment by hp685** [comment]
parallel-ssh provides non-blocking mode with gevent sockets as well. Regarding the second problem, ideally you want to reserve the gevent/eventlet worker for I/O requests only, so a single processor won't be a concern.
