### ISSUE TITLE
The  celery result  column, date_done is utc, even though you set the timezone

### ISSUE THREAD

**Issue by zhangchenchen** [celery/celery#4948]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

run celery, set the timezone, 'Asia/Shanghai'.
run task.

## Expected behavior
the task result culumn, date_done is  the local time, as setted up, Asia/Shanghai.

## Actual behavior
date_done is utc.

**Comment by johnarnold** [comment]
date_done in the backend?  What backend are you using?

**Comment by zhangchenchen** [comment]
I use mysql as the backend. I check the source code,  it seems that it use datetime.utcnow as the default and onupdate time. 
 https://github.com/celery/celery/blob/b472fbccd082c4f2137d4ac40d9e7061ffaf41f7/celery/backends/database/models.py#L30

**Comment by auvipy** [comment]
can you paste your pip freeze list?

**Comment by zhangchenchen** [comment]
sure.
```yaml
amqp==2.3.2
Babel==2.6.0
billiard==3.5.0.3
blinker==1.4
celery==4.2.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
dominate==2.3.1
eventlet==0.23.0
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
Flask-HTTPAuth==3.2.4
Flask-Mail==0.9.1
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
flower==0.9.2
gevent==1.3.4
greenlet==0.4.13
idna==2.7
itsdangerous==0.24
Jinja2==2.10
jsonschema==2.6.0
kombu==4.2.1
librabbitmq==2.0.0
MarkupSafe==1.0
msgpack-python==0.5.6
mysqlclient==1.3.12
pytz==2018.4
requests==2.19.1
six==1.11.0
SQLAlchemy==1.2.8
tornado==5.0.2
urllib3==1.23
vine==1.1.4
visitor==0.1.3
Werkzeug==0.14.1
```

**Comment by zaipingy** [comment]
I use Redis as backend, and meet this problem too. The version of celery is 4.3.0.
