### ISSUE TITLE
async is a reserved keyworkd in python 3.7 causes celery to failt to start with redis backend

### ISSUE THREAD

**Issue by cdknorow** [celery/celery#4958]
## Checklist

In celery.backends.redis there is an import for async

from . import async, base

In python 3.7, async is a reserved keyword. 

Suggest renaming async.py to something else. async_backend.py or rasync.py

## Steps to reproduce

Attempt to start celery with a redis backend using python 3.7

## Expected behavior

Should start without error

## Actual behavior

Errors out because async is a reserved keyword in python 3.7

**Comment by coldnight** [comment]
PR #4852 has fixed this issue, but not released currently!

**Comment by auvipy** [comment]
try to install from Github master if you need python 3.7 support.
