### ISSUE TITLE
Allow setting max size of revoked task list

### ISSUE THREAD

**Issue by Ashish-Bansal** [celery/celery#4959]
**Celery version: 4.2.1 (happens on master)**

## Steps to reproduce

If payload size is large and you have 50k revoked task list, then it would take lot of time to sync the revoked list.

https://github.com/celery/celery/blob/b472fbccd082c4f2137d4ac40d9e7061ffaf41f7/celery/worker/state.py#L38

## Expected behavior

There should be some option to configure this up.

Right now we are using quite dirty way to fix it: 

```
from celery.utils.collections import LimitedSet
from celery.worker import state

state.revoked = LimitedSet(maxlen=500, expires=10800)
```

If there's cleaner workaround for this before this is implemented, that would be quite helpful.

Though I didn't get the use case of syncing revoked task list with other workers. Any reason behind it ?

## Actual behavior

It slows up celery a lot, increases memory usage etc.

**Comment by auvipy** [comment]
do you have any proposed improvement in mind? feel free to start a pr

**Comment by bepetersn** [comment]
FYI, Fixed in: https://github.com/celery/celery/commit/d29610bac81a1689b53440e6347b9c5ced038751
