### ISSUE TITLE
Can not run periodic task: E0807 17:05:33.560152519      71 backup_poller.cc:124]       Run client channel backup poller: {"created":"@1533639933.560082290","description":"pollset_work","file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":231,"referenced_errors":[{"created":"@1533639933.560076603","description":"OS Error","errno":9,"file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":656,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}

### ISSUE THREAD

**Issue by MuslimBeibytuly** [celery/celery#4960]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

**Comment by arvindnrbt** [comment]
Were you able to fix this issue? this is flooding our logs and occurs only in Celery beat worker.

**Comment by vikramray-fc** [comment]
Any fix for this?
