### ISSUE TITLE
Can not run periodic task

### ISSUE THREAD

**Issue by MuslimBeibytuly** [celery/celery#4961]
## Checklist

Celery==4.1.0
Redis==2.10.6

E0807 17:05:33.560152519      71 backup_poller.cc:124]       
Run client channel backup poller: {"created":"@1533639933.560082290","description":"pollset_work","file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":231,"referenced_errors":[{"created":"@1533639933.560076603","description":"OS Error","errno":9,"file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":656,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}

I have verified that the issue exists against the `master` branch of Celery.

celery -A core worker --beat with latest image of Redis on Docker Hub

print('working')

E0807 17:07:48.560145702      82 backup_poller.cc:124]       Run client channel backup poller: {"created":"@1533640068.560070217","description":"pollset_work","file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":231,"referenced_errors":[{"created":"@1533640068.560064091","description":"OS Error","errno":9,"file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":656,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}

**Comment by MuslimBeibytuly** [comment]
@periodic_task(
    name='Log terminal status',
    run_every=crontab(minute=1, hour=0)
)
def log_terminal_status():
    log_status()

**Comment by auvipy** [comment]
use the latest version of celery and follow docs properly. If you can't figure out post your question on IRC chat.

**Comment by arvindnrbt** [comment]
I still have this issue and this is flooding the logs at a rapid pace. Were you able to solve this issue?

**Comment by MuslimBeibytuly** [comment]
I've written tiny entrypoint for my docker container:
#!/bin/bash
while ! nc -vz redis 6379;
    do
      echo "waiting for redis"
      sleep 1;
    done;
celery -A core worker --beat --loglevel=INFO

**Comment by arvindnrbt** [comment]
I use RabbitMQ though. Is this because of the connectivity issue? My other worker processes are not affected at all. Does anyone know why this is happening?

**Comment by weaming** [comment]
I have same issue .

**Comment by auvipy** [comment]
could you try celery==4.4.0rc4 and ask for help in the celery-users mailing list first? after confirming this as a celery bug please report back again here.
