### ISSUE TITLE
pytest celery

### ISSUE THREAD

**Issue by amirajina** [celery/celery#4962]
I’m trying to use pytest to test my celery task.
For this I’m using (celery_app and celery_worker) , or  (celery_session_app, celery_session_worker.

class TestCase(object):
@pytest.mark.celery(result_backend='rpc')
    def test_mul(self, celery_session_app, celery_session_worker):
        print("celery_session_worker mul = ", celery_session_worker)
        print(" celery_session_app mul = ", celery_session_app)
        task = mult.delay(4, 4)
        result = task.get(timeout=10)
        status = task.status
        print("Task mult result = ", result)
        print("Task mult status = ", status)
        assert result == 16
        assert status == 'SUCCESS'

I well create the two object for celey:
celery_session_worker mul =  gen14038@workshop.localdomain
celery_session_app mul =  <Celery celery.tests at 0x7f3b10ca77f0>

But I think the worker never launched, I have always a timeout issue:
celery.exceptions.TimeoutError: The operation timed out.

**Comment by auvipy** [comment]
this might be a duplicate issue, please check issues tagged with test and let us know
