### ISSUE TITLE
librabbitmq plugin raise TypeError: Required argument 'object' (pos 1) not found

### ISSUE THREAD

**Issue by MIKNOTAURO** [celery/celery#4964]
## Checklist
- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

`software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:2.7.12
            billiard:3.5.0.4 librabbitmq:2.0.0`
`platform -> system:Linux arch:64bit, ELF imp:CPython`
`loader   -> celery.loaders.app.AppLoader`
`settings -> transport:librabbitmq results:redis://127.0.0.1:6379/0`

CELERY_BROKER_URL = 'amqp://localhost'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TIMEZONE = 'America/Mexico_City'
CELERY_ALWAYS_EAGER = True

## Steps to reproduce
I'm trying to use librabbitmq plugin, with the above config./arch but I got this

`[2018-08-07 16:31:30,476: ERROR/ForkPoolWorker-1] Pool process` `<celery.concurrency.asynpool.Worker object at 0x7fb8960b19d0> error: TypeError("Required argument 'object' (pos 1) not found",)`

Here is my traceback

![image](https://user-images.githubusercontent.com/2102746/43804134-9439ecd8-9a60-11e8-9560-67602f549fa8.png)

Any Ideas?

**Comment by xirdneh** [comment]
Are you queueing any tasks or is this while starting a worker?

**Comment by p2k** [comment]
I have the same problem; it happens right after queueing a task, not while the worker sits there waiting.

**Comment by p2k** [comment]
After some more investigation, it tries to unpickle a memoryview object for which the first parameter is somehow missing. If you do `memoryview()` in a python REPL, you'll see the same error.

As a workaround - you might have guessed it - one can use pyamqp instead of librabbitmq (`pyamqp://...` instead of `amqp://...`).

**Comment by MIKNOTAURO** [comment]
@xirdneh @p2k Yep, for me, it happens right after queueing a task also, not while starting a worker...
Now it works fine with amqp:// though

**Comment by auvipy** [comment]
I think we should depricate librabitmq and cythonize pyamqp where possible. librabbitmq dont add any performence boost, and not feature rich either. and its buggy too
