### ISSUE TITLE
ack_late will not work when using gevent 

### ISSUE THREAD

**Issue by galCohen88** [celery/celery#4968]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

**Using 4.2.1**

[2018-08-12 08:39:27,855: INFO/MainProcess] Connected to redis://***:6379
[2018-08-12 08:39:27,865: INFO/MainProcess] mingle: searching for neighbors
[2018-08-12 08:39:28,934: INFO/MainProcess] mingle: all alone
[2018-08-12 08:39:28,997: INFO/MainProcess] celery@e547ccc58559 ready.

==> app-celery-stdout---supervisor-er5uXH.log <==
## Steps to reproduce
1. Create new job with acks_late flag as True
2. use gevent and patch it using monkey.patch_all()
3. Set visibility_timeout to 30 seconds
4. Execute the task (when execution will take more than 30 secs)
5. Task is not re-executed  

## Expected behavior
The task should be re-executed when unacked_index zset entry reaches timeout 

## Actual behavior
Task is not re-executed what so ever, when removing monkey.patch_all() task is re-executed

**Comment by galCohen88** [comment]
Narrowing this issue down, kombu loop that queries unacked_index is not running because gevent patch (this behaviour is ok)

The problem originates when the worker restarted and visibility timeout **not** exceeded. the task will no be re-executed, as  unacked_index is queried only once when the worker is started 

Suggested solution:

Add the task to the queue with countdown equivalent to the zset entry expiry (i.e execute the task in the time that it would have been executed if the loop was running)

**Comment by auvipy** [comment]
does the suggested solution qualify as a pr?

**Comment by galCohen88** [comment]
i'm not sure what you mean by qualify as a pr, anyway its a change in kombu repo
