### ISSUE TITLE
How to get signature of a task by name in canvas?

### ISSUE THREAD

**Issue by misssprite** [celery/celery#4969]
Suppose that we have a caller `A` and a callee `B`. `B` implements some function and has heavy dependencies.

Typically, I don't want to import these dependencies in `A` to keep the caller lightweight.

Previously, I can happily use `send_task` to call `B` by name. 

Now I have more complex logic and wanna orchestrate tasks with canvas. Following the user guide [here](http://docs.celeryproject.org/en/latest/userguide/canvas.html)
```
signature('tasks.add', args=(2, 2), countdown=10)
```

I got a task `NotRegistered` error.

How to register task by name?

Thanks a lot.

P.S., I posted a question on SO [here](https://stackoverflow.com/questions/51783013/how-to-use-canvas-without-import-task-module-in-celery-client) but sadly no help yet.

### **UPDATE:**

I notice this comment in the user guide:
```
Calling the signature will execute the task inline in the current process:
add.s(2, 2)()
```
I succeeded  invoking remote task with the following change:
1.  calling with `apply_async`
```
step1 = app.signature('step1.s1', args=(2,))  # without import step1.s1 and step2.s2
step2 = app.signature('step2.s2', args=(2,))
c = (step1 | step2)
res = c.apply_async()
print(res.get(10))
```

2. manually set queue for each task, otherwise task in `chain` try to find task in  registry and throw the following error:
```
File "/home/dwf/dev/py/celery_demo/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: 'step1.s1'
```

Is Point 2 intended behavior?

**Comment by auvipy** [comment]
better post your questions on IRC

**Comment by auvipy** [comment]
always post these type of question to stackoverflow/irc/mailing list to get a better answer.

**Comment by LeRett0** [comment]
I have the same problem

**Comment by LeRett0** [comment]
@misssprite 
No, that doesn't work.
My case:
```python
worfklow = group(signature('pipe.download').set(queue='download') for url in urls) | signature('pipe.processing').set(queue='processing')
```
In my case, all files are loaded, after that processing should start, but it is not performed
KeyError: 'pipe.processing'

**Comment by misssprite** [comment]
@LeRett0 
Sorry for delayed reply.
Here is a working demo. I didn't test for `group` operator but I believe it should make no difference than `chain`.

https://github.com/misssprite/celery_canvas_demo
