### ISSUE TITLE
celery Pytest

### ISSUE THREAD

**Issue by amirajina** [celery/celery#4973]
-I'm using celery Version: 4.1.1

In the celery Task I'm using group, chain and chord from celery
To excute the task I need to set the --concurrency=4
everything works fine

When I call pytest, using the worker for test (celery_session_worker) to test this task,  a timeout excpetion occured.

Can you please advise how I can use the **celery_session_worke**r with **--concurrency=4.**

Thanks in advance.

**Comment by amirajina** [comment]
to ovoid any confuse, I need  celery worker and 4 worker threads for testing like this:
celery -A proj worker -l info --concurrency=4 -n wkr1@hostn

**Comment by auvipy** [comment]
closing as duplicate.

**Comment by amirajina** [comment]
Could you please specify the id of the duplicated bug.
