### ISSUE TITLE
mock pytest with prefork

### ISSUE THREAD

**Issue by amirajina** [celery/celery#4977]
I'm using celery Version: 4.1.1
I'm trying to mcok function called by the celery task.
In my celery task I"m using allow_join_result.
**The mock works correctly  with 'solo' but not with 'prfork'**
But to excute correctly ma celery task and nedd the prfeor configuration.

Could you please advise, to mock this function called in celery task, using prefork?

Code:

**celerytasks.py:**

app = Celery()

def method1(a, b):
print("add {} and {}".format(a,b))

def method2(a, b):
return a*b

@app.task
def fun(a, b):
method1(a,, b)
methode2(a, b)

**test_celery_task.py:**

from unitest.mock import patch

class MockedFuntion:
def mock_method1(a, b):
print("mult {} and {}".format(a,b))

class TestClass:

@patch("celerytasks.method1", new=MockedFunction.mock_method1)
def test_task(celery_app, celery_worker):
task = fun.delay(5, 4)
res=task.get()
assert res.result == 20

**Conftest.py:**
@pytest.fixture(scope='session')
def celery_worker_pool():
    """You can override this fixture to set the worker pool.

    The "solo" pool is used by default, but you can set this to
    return e.g. "prefork".
    """
    return 'prefork'

@pytest.fixture(scope='session')
def celery_worker_parameters():
    # type: () -> Mapping[str, Any]
    """Redefine this fixture to change the init parameters of Celery workers.
    This can be used e. g. to define queues the worker will consume tasks from.
    The dict returned by your fixture will then be used
    as parameters when instantiating :class:`~celery.worker.WorkController`.
    """
    return {
        'concurrency': 4,
        'loglevel': 10,
        'logfile': "pytest_celery.log"
}

**Comment by auvipy** [comment]
please use latest release of celery, 4.2.1 and ask your question to celery-users mailing list or #celery irc channel first.

**Comment by amirajina** [comment]
Thanks for your response.
Same issue with celery, 4.2.1.

**Comment by amirajina** [comment]
I don't have any response from celery-users.
Could you please advise
