### ISSUE TITLE
Redis backend  unacked task residual

### ISSUE THREAD

**Issue by liukaigit** [celery/celery#4984]
- I'm still working on a risk assessment,in a test scenario,I met  a unable to bypass problem:
```  
task_reject_on_worker_lost=True
task_acks_late = True
```
when the task is running,I can see the unacked(hash type) in the redis has a key,the key will be deleted util task over,now power off or kill celery and worker process,when celery starts again,it will not to deal with the task in redis's unacked hash list,the task will contain pre-status,but I want the task to be processed again,so what should I do.

**Comment by auvipy** [comment]
any suggested fix?

**Comment by yanwencheng** [comment]
> 任何建议的修复？



> any suggested fix?

CELERY_TASK_REJECT_ON_WORKER_LOST= True 
CELERY_TASK_ACKS_LATE = True 

The task did not continue to execute after cellery suddenly interrupted recovery. I have also encountered this problem. Have you solved it

**Comment by gauravaror** [comment]
I was trying to figure out the same issue. Seems like the default visibility timeout for Redis is 1 hour(3600). So, your task would recover, but after 1 hour. https://docs.celeryproject.org/en/stable/getting-started/brokers/redis.html#visibility-timeout

If you change your visibility timeout in celeryconfig to a lower value, you should see the task getting recovered soon after:

```
app.conf.broker_transport_options = {'visibility_timeout': 10}  # 1 hour.

```

**Comment by auvipy** [comment]
> I was trying to figure out the same issue. Seems like the default visibility timeout for Redis is 1 hour(3600). So, your task would recover, but after 1 hour. https://docs.celeryproject.org/en/stable/getting-started/brokers/redis.html#visibility-timeout
> 
> If you change your visibility timeout in celeryconfig to a lower value, you should see the task getting recovered soon after:
> 
> ```
> app.conf.broker_transport_options = {'visibility_timeout': 10}  # 1 hour.
> ```

closing as per this

**Comment by JoeGaffney** [comment]
This is not really a great solution what if your job does sometimes run for a longer time. 

This will keep trying task over and over again. Sure you can make it idempotent, but really if the the worker crashes or is stopped it should really mark it as so can more naturally be retired.

Guess i will have to switch to rabbit

**Comment by auvipy** [comment]
do you have any better proposal in mind?
