### ISSUE TITLE
Celery dies when declaring result_backend

### ISSUE THREAD

**Issue by raylenmargono** [celery/celery#4992]
## Checklist

I am using celery celery-4.2.1 and kombu-4.2.1

## Steps to reproduce

celery -A (project) worker -l info

## Expected behavior

celery worker should start

## Actual behavior

celery worker does not start and does not leave any error logs. This only occurs when result_backend is declared in the app settings. Any value causes it to crash.

![screen shot 2018-08-20 at 10 49 10 am](https://user-images.githubusercontent.com/5940684/44347783-c0056a80-a466-11e8-853c-b489daad59de.png)

Here are my settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'socrates.settings')

celery_settings = {
    'broker_url': app_config.REDIS_URL,
    'result_backend': 'redis',
    'task_serializer': 'json',
    'accept_content': ['json'],
    'result_serializer': 'json',
    'timezone': 'US/Eastern',
    'broker_transport_options': {
        'fanout_patterns': True,
        'fanout_prefix': True
    },
    'worker_max_tasks_per_child': 10  # replace worker process every 10 tasks
}

app = Celery((project name), config_source=celery_settings)

app.autodiscover_tasks()

**Comment by thedrow** [comment]
There's no error? No output? Nothing?
What does strace say?
Is the process still running but stuck?

**Comment by raylenmargono** [comment]
@thedrow - no error and no strace. Process is immediately killed. ps aux | grep celery reveals no processes that are being run under that namespace. Let me know how else I can be of help.

**Comment by thedrow** [comment]
I meant try to run the process with strace and see what it's trying to do.

**Comment by raylenmargono** [comment]
Also I realized there is only support for python 3.6>= . I am using python 3.7 @thedrow

**Comment by thedrow** [comment]
Python 3.7 is not supported yet.
There is something else going on but I think it's related to your environment:

```
open("/Users/raylenmargono/.local/share/virtualenvs/socrates-3Fc0fH5T/lib/python3.7/site-packages/celery/backends/__pycache__/redis.cpython-37.pyc\0", 0x1000000, 0x1B6)         = -1 Err#2
```
Error 2 usually means no such file or directory. I'm not sure why python doesn't complain that the module doesn't exist.
