### ISSUE TITLE
[Question] What is the correct way to override Task.__call__()?

### ISSUE THREAD

**Issue by ArtemGordinsky** [celery/celery#4993]
If I'm overriding `app.Task` with my own class to extend the behaviour of `__call__` , should I call `self.run()` or `super().__call__()` to perform the task?

Looking at [the code](https://github.com/celery/celery/blob/master/celery/app/task.py#L382), it seems like `super().__call__()` would be more correct since it's performing some context-management which would be skipped otherwise. However, some people in the Flask community have had doubts about which way is right ([1](https://github.com/pallets/flask/pull/2055), [2](https://github.com/pallets/flask/pull/2889)).

Could one of the core maintainers or somebody who knows the codebase well weigh in on the issue to bring some clarity into the discussion?

### Examples
**Option 1, using `self.run`** (from the Flask [documentation](http://flask.pocoo.org/docs/1.0/patterns/celery/)):
```python
celery = Celery()

class ContextTask(celery.Task):
    def __call__(self, *args, **kwargs):
        with celery.app_context():
            return self.run(*args, **kwargs)

celery.Task = ContextTask
```

**Option 2, using `super().call()`** (the one that seems more correct to me)
```python
celery = Celery()

class ContextTask(celery.Task):
    def __call__(self, *args, **kwargs):
        with celery.app_context():
            return super().__call__(*args, **kwargs)

celery.Task = ContextTask
```

**Comment by thedrow** [comment]
My first instinct says you are correct.
After reading the thread, I'm not sure sure.

**Comment by auvipy** [comment]
current status? @ArtemGordinsky

**Comment by ArtemGordinsky** [comment]
@auvipy Sorry, forgot I asked this question.
I've been using the second option for over a year now, so that definitely works.

**Comment by emiliyan-rashev** [comment]
You can use task_cls, here is an example:
```
class CeleryTask(DjangoTask):
    """
    Override Celery Task class to add custom delay method in order to run tasks synchronously in
    tests.
    """

    def delay(self, *args, **kwargs):
        if settings.TESTING:
            return self(*args, **kwargs)
        return self.apply_async(*args, **kwargs)


app = Celery('project', task_cls=CeleryTask)
```
