### ISSUE TITLE
Celery does not honor max_connections_redis or max_connections

### ISSUE THREAD

**Issue by SHxKM** [celery/celery#4994]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Django 1.11, Celery v4.20, redis==2.10.6

With the following settings, with either/both/none of `CELERY_BROKER_POOL_LIMIT` and `CELERY_BROKER_TRANSPORT_OPTIONS` set-up, and `max_connections` set to any number between `1-9`, celery will not honor the settings. 

Each worker spawned like this:

`celery -A proj worker -Q important -l info`

Note: applies when worker in launched with `-c=1` to limit concurrency.

Will create **a minimum of 8** connections that are always present when idle, and the number going up by 2 when the worker is actually performing a job. 

reporoduce: with the settings above, and by running `redis-cli` in the terminal, and then `info Clients` when the worker is running, not running, and running and doing a job.

```
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Jerusalem'
CELERY_BROKER_POOL_LIMIT = 0
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'max_connections': 1,
}
CELERY_TASK_CREATE_MISSING_QUEUES = 1
CELERYD_WORKER_MAX_TASKS_PER_CHILD = 5
CELERY_PREFETCH_MULTIPLIER = 1
```

## Expected behavior

Celery will kill connections when not active? celery will honor/limit the number of connections to redis?

## Actual behavior

Celery ignores limits

## celery report
ABSOLUTE_URL_OVERRIDES: {
 }
ACCOUNT_ACTIVATION_DAYS: 30
ADMINS: [('XXXX', 'XXXXX@gmail.com')]
ALLOWED_HOSTS: ['192.168.14.37',
 'localhost',
 'www.XXXXXX.io',
 'XXXXXXX.herokuapp.com',
 '127.0.0.1']
APPEND_SLASH: True
AUTHENTICATION_BACKENDS: 
    ('accounts.auth_backend.CustomBackend',
 'django.contrib.auth.backends.ModelBackend')
AUTH_PASSWORD_VALIDATORS: '********'
AUTH_USER_MODEL: 'auth.User'
BASE_DIR: '/Users/XXXXXX/PycharmProjects/proj'
CACHES: {
 'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS: 'default'
CACHE_MIDDLEWARE_KEY_PREFIX: '********'
CACHE_MIDDLEWARE_SECONDS: 600
CELERYD_WORKER_MAX_TASKS_PER_CHILD: 5
CELERY_ACCEPT_CONTENT: ['application/json']
CELERY_BEAT_SCHEDULE: {
    'purge_django_session': {   'options': {'queue': 'regular'},
                                'schedule': <crontab: 42 12 * * * (m/h/d/dM/MY)>,
                                'task': 'clear_django_sessions'},
    'refresh-db-task': {   'options': {'queue': 'regular'},
                           'schedule': <crontab: 30 */2 * * * (m/h/d/dM/MY)>,
                           'task': 'refresh_db_task'},
    'scan_rgs_db_task': {   'options': {'queue': 'regular'},
                            'schedule': <crontab: 29 */9 * * * (m/h/d/dM/MY)>,
                            'task': 'scan_rgs_db_task'}}
CELERY_BROKER_POOL_LIMIT: 0
CELERY_BROKER_TRANSPORT_OPTIONS: {
 'max_connections': 1}
CELERY_BROKER_URL: 'redis://localhost:6379//'
CELERY_PREFETCH_MULTIPLIER: 1
CELERY_RESULT_BACKEND: 'redis://localhost:6379/'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_TASK_CREATE_MISSING_QUEUES: 1
CELERY_TASK_SERIALIZER: 'json'
CELERY_TIMEZONE: 'Asia/Jerusalem'
CHANNEL_LAYERS: {
    'default': {   'BACKEND': 'asgi_redis.RedisChannelLayer',
                   'CONFIG': {'hosts': ['redis://localhost:6379']},
                   'ROUTING': 'proj.routing.channel_routing'}}
COMPRESS_CACHEABLE_PRECOMPILERS: 
    ()
COMPRESS_CACHE_BACKEND: 'default'
COMPRESS_CACHE_KEY_FUNCTION: '********'
COMPRESS_CLEAN_CSS_ARGUMENTS: ''
COMPRESS_CLEAN_CSS_BINARY: 'cleancss'
COMPRESS_CLOSURE_COMPILER_ARGUMENTS: ''
COMPRESS_CLOSURE_COMPILER_BINARY: 'java -jar compiler.jar'
COMPRESS_CSS_COMPRESSOR: 'compressor.css.CssCompressor'
COMPRESS_CSS_FILTERS: ['compressor.filters.css_default.CssAbsoluteFilter']
COMPRESS_CSS_HASHING_METHOD: 'mtime'
COMPRESS_DATA_URI_MAX_SIZE: 1024
COMPRESS_DEBUG_TOGGLE: None
COMPRESS_ENABLED: False
COMPRESS_FILTERS: {
    'css': ['compressor.filters.css_default.CssAbsoluteFilter'],
    'js': ['compressor.filters.jsmin.JSMinFilter']}
COMPRESS_JINJA2_GET_ENVIRONMENT: <function CompressorConf.JINJA2_GET_ENVIRONMENT at 0x110fdb7b8>
COMPRESS_JS_COMPRESSOR: 'compressor.js.JsCompressor'
COMPRESS_JS_FILTERS: ['compressor.filters.jsmin.JSMinFilter']
COMPRESS_MINT_DELAY: 30
COMPRESS_MTIME_DELAY: 10
COMPRESS_OFFLINE: False
COMPRESS_OFFLINE_CONTEXT: {
 'STATIC_URL': '/static/'}
COMPRESS_OFFLINE_MANIFEST: 'manifest.json'
COMPRESS_OFFLINE_TIMEOUT: 31536000
COMPRESS_OUTPUT_DIR: 'CACHE'
COMPRESS_PARSER: 'compressor.parser.AutoSelectParser'
COMPRESS_PRECOMPILERS: 
    (('text/x-sass', 'django_libsass.SassCompiler'),
 ('text/x-scss', 'django_libsass.SassCompiler'))
COMPRESS_REBUILD_TIMEOUT: 2592000
COMPRESS_ROOT: '/Users/XXXXX/PycharmProjects/proj/staticfiles'
COMPRESS_STORAGE: 'compressor.storage.CompressorFileStorage'
COMPRESS_TEMPLATE_FILTER_CONTEXT: {
 'STATIC_URL': '/static/'}
COMPRESS_URL: '/static/'
COMPRESS_VERBOSE: False
COMPRESS_YUGLIFY_BINARY: 'yuglify'
COMPRESS_YUGLIFY_CSS_ARGUMENTS: '--terminal'
COMPRESS_YUGLIFY_JS_ARGUMENTS: '--terminal'
COMPRESS_YUI_BINARY: 'java -jar yuicompressor.jar'
COMPRESS_YUI_CSS_ARGUMENTS: ''
COMPRESS_YUI_JS_ARGUMENTS: ''
CRISPY_FAIL_SILENTLY: False
CRISPY_TEMPLATE_PACK: 'bootstrap3'
CSRF_COOKIE_AGE: 31449600
CSRF_COOKIE_DOMAIN: None
CSRF_COOKIE_HTTPONLY: False
CSRF_COOKIE_NAME: 'csrftoken'
CSRF_COOKIE_PATH: '/'
CSRF_COOKIE_SECURE: False
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS: []
CSRF_USE_SESSIONS: False
DATABASES: {
    'default': {   'ATOMIC_REQUESTS': False,
                   'AUTOCOMMIT': True,
                   'CONN_MAX_AGE': 0,
                   'ENGINE': 'django.db.backends.postgresql_psycopg2',
                   'HOST': 'localhost',
                   'NAME': 'mbutler',
                   'OPTIONS': {},
                   'PASSWORD': '********',
                   'PORT': '',
                   'TEST': {   'CHARSET': None,
                               'COLLATION': None,
                               'MIRROR': None,
                               'NAME': None},
                   'TIME_ZONE': None,
                   'USER': 'XXXXXX'}}
DATABASE_ROUTERS: '********'
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS: 2000
DATETIME_FORMAT: 'N j, Y, P'
DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']
DATE_FORMAT: 'N j, Y'
DATE_INPUT_FORMATS: ['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG: True
DEBUG_PROPAGATE_EXCEPTIONS: False
DECIMAL_SEPARATOR: '.'
DEFAULT_CHARSET: 'utf-8'
DEFAULT_CONTENT_TYPE: 'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL: 'XXXXXX'
DEFAULT_INDEX_TABLESPACE: ''
DEFAULT_LOGGING: {
    'disable_existing_loggers': False,
    'filters': {   'require_debug_false': {   '()': 'django.utils.log.RequireDebugFalse'},
                   'require_debug_true': {   '()': 'django.utils.log.RequireDebugTrue'}},
    'formatters': {   'django.server': {   '()': 'django.utils.log.ServerFormatter',
                                           'format': '[%(server_time)s] '
                                                     '%(message)s'}},
    'handlers': {   'console': {   'class': 'logging.StreamHandler',
                                   'filters': ['require_debug_true'],
                                   'level': 'INFO'},
                    'django.server': {   'class': 'logging.StreamHandler',
                                         'formatter': 'django.server',
                                         'level': 'INFO'},
                    'mail_admins': {   'class': 'django.utils.log.AdminEmailHandler',
                                       'filters': ['require_debug_false'],
                                       'level': 'ERROR'}},
    'loggers': {   'django': {   'handlers': ['console', 'mail_admins'],
                                 'level': 'INFO'},
                   'django.server': {   'handlers': ['django.server'],
                                        'level': 'INFO',
                                        'propagate': False}},
    'version': 1}
DEFAULT_TABLESPACE: ''
DISALLOWED_USER_AGENTS: []
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST: 'smtp.mailgun.org'
EMAIL_HOST_PASSWORD: '********'
EMAIL_HOST_USER: 'XXXXXXXXX'
EMAIL_PORT: 587
EMAIL_SSL_CERTFILE: None
EMAIL_SSL_KEYFILE: '********'
EMAIL_SUBJECT_PREFIX: '[Django] '
EMAIL_TIMEOUT: None
EMAIL_USE_LOCALTIME: False
EMAIL_USE_SSL: False
EMAIL_USE_TLS: True
FILE_CHARSET: 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
FILE_UPLOAD_HANDLERS: ['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
FILE_UPLOAD_PERMISSIONS: None
FILE_UPLOAD_TEMP_DIR: None
FIRST_DAY_OF_WEEK: 0
FIXTURE_DIRS: []
FORCE_SCRIPT_NAME: None
FORMAT_MODULE_PATH: None
FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS: []
INSTALLED_APPS: ['core',
 'accounts',
 'notifications',
 'sendmail',
 'faq',
 'stayintouch',
 'tinymce',
 'dal',
 'dal_select2',
 'registration',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'debug_toolbar',
 'django_extensions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'compressor',
 'django_inlinecss',
 'widget_tweaks',
 'crispy_forms',
 'channels',
 'whitenoise.runserver_nostatic',
 'raven.contrib.django.raven_compat']
INTERNAL_IPS: 
    ('127.0.0.1',)
LANGUAGES: [('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE: 'en-us'
LANGUAGE_COOKIE_AGE: None
LANGUAGE_COOKIE_DOMAIN: None
LANGUAGE_COOKIE_NAME: 'django_language'
LANGUAGE_COOKIE_PATH: '/'
LOCALE_PATHS: []
LOGGING: {
 }
LOGGING_CONFIG: 'logging.config.dictConfig'
LOGIN_REDIRECT_URL: '/'
LOGIN_URL: '/accounts/login/'
LOGLEVEL: 'INFO'
LOGOUT_REDIRECT_URL: None
MANAGERS: []
MEDIA_ROOT: ''
MEDIA_URL: ''
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE: ['raven.contrib.django.middleware.DjangoRestFrameworkCompatMiddleware',
 'raven.contrib.django.middleware.SentryMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'proj.middleware.SessionForAnonymousMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'proj.middleware.CanonicalDomainMiddleware']
MIDDLEWARE_CLASSES: ['django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware']
MIGRATION_MODULES: {
 }
MONTH_DAY_FORMAT: 'F j'
MYSITE_URL: 'http://localhost:8000/'
NUMBER_GROUPING: 0
PASSWORD_HASHERS: '********'
PASSWORD_RESET_TIMEOUT_DAYS: '********'
PREPEND_WWW: False
ROOT_URLCONF: 'proj.urls'
SECRET_KEY: '********'
SECURE_BROWSER_XSS_FILTER: False
SECURE_CONTENT_TYPE_NOSNIFF: False
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
SECURE_HSTS_PRELOAD: False
SECURE_HSTS_SECONDS: 0
SECURE_PROXY_SSL_HEADER: None
SECURE_REDIRECT_EXEMPT: []
SECURE_SSL_HOST: None
SECURE_SSL_REDIRECT: False
SERVER_EMAIL: 'root@localhost'
SESSION_CACHE_ALIAS: 'default'
SESSION_COOKIE_AGE: 1209600
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_NAME: 'sessionid'
SESSION_COOKIE_PATH: '/'
SESSION_COOKIE_SECURE: False
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
SESSION_FILE_PATH: None
SESSION_SAVE_EVERY_REQUEST: False
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE: 'proj.settings.dev'
SHORT_DATETIME_FORMAT: 'm/d/Y P'
SHORT_DATE_FORMAT: 'm/d/Y'
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS: []
SITE_ID: 1
SPOTIFY_CLIENT_ID: 'XXXXXXXXXX'
SPOTIFY_SECRET_ID: '********'
STATICFILES_DIRS: 
    ('/Users/XXXXXXXX/PycharmProjects/proj/static',
 '/Users/XXXXXXXX/PycharmProjects/proj/static/proj/sass/')
STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder',
 'compressor.finders.CompressorFinder']
STATICFILES_STORAGE: 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT: '/Users/XXXXXXXX/PycharmProjects/proj/staticfiles'
STATIC_URL: '/static/'
TEMPLATES: [{'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/Users/XXXXXXX/PycharmProjects/proj/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages',
                                     'proj.processors.get_website_name',
                                     'proj.processors.get_add_artist_form'],
              'loaders': ['django.template.loaders.filesystem.Loader',
                          'django.template.loaders.app_directories.Loader']}}]
TEST_NON_SERIALIZED_APPS: []
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR: ','
TIME_FORMAT: 'P'
TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE: 'Asia/Jerusalem'
USE_ETAGS: False
USE_I18N: True
USE_L10N: True
USE_THOUSAND_SEPARATOR: False
USE_TZ: True
USE_X_FORWARDED_HOST: False
USE_X_FORWARDED_PORT: False
WSGI_APPLICATION: 'proj.wsgi.application'
X_FRAME_OPTIONS: 'SAMEORIGIN'
YEAR_MONTH_FORMAT: 'F Y'
is_overridden: <bound method Settings.is_overridden of <Settings "proj.settings.dev">>

**Comment by typistX** [comment]
Is this a known issue? Have I missed something?

**Comment by auvipy** [comment]
It is still happening with the new version?

**Comment by SHxKM** [comment]
I gave up on using this feature when it didn't work. I have no idea. Feel free to close this.
