### ISSUE TITLE
redis as broker caused Received and deleted unknown message. Wrong destination?!?

### ISSUE THREAD

**Issue by 1uanWu** [celery/celery#4998]
when I use redis as broker appeared Received and deleted unknown message. Wrong destination?!?

![image](https://user-images.githubusercontent.com/23513206/44398905-3b0a7600-a578-11e8-9bcc-924dee9287a0.png)

https://github.com/celery/celery/issues/3675
this issue about this error is for rabbitmq, the redis I use.

**Comment by auvipy** [comment]
can you provide a sample test case and run that with the current release?

**Comment by Arusey** [comment]
Hey did anyone a fix for when using redis?

**Comment by Arusey** [comment]
> Hey did anyone a fix for when using red

> when I use redis as broker appeared Received and deleted unknown message. Wrong destination?!?
> 
> ![image](https://user-images.githubusercontent.com/23513206/44398905-3b0a7600-a578-11e8-9bcc-924dee9287a0.png)
> 
> #3675
> this issue about this error is for rabbitmq, the redis I use.

@1uanWu did you get a fix for this issue?

**Comment by nitrocode** [comment]
I can confirm that we're seeing this with Redis / Elasticache and celery 4.2.1

**Comment by auvipy** [comment]
celery 4.4.4 is the latest release

**Comment by nitrocode** [comment]
Yes, I'm aware we're on an older version. Would you be able to confirm that this issue is resolved in the latest release ?

**Comment by auvipy** [comment]
sorry you have to reproduce it by yourself on master
