### ISSUE TITLE
AsyncResult.get()  stuck in high cpu usage

### ISSUE THREAD

**Issue by monsterxx03** [celery/celery#4999]
celery  4.2.1
gevent  1.3.5 
redis-py 2.10.6

With gevent.monkey.patch_all(), when try to get result of a delay executed task(shutdown worker or make task in long pending task queue), result.get() will cause very high cpu usage on the producer side.

Tested on python2.7 and python3.6, both have this issue.

Test script:

```
import gevent
import gevent.monkey
gevent.monkey.patch_all()

import time
from celery import Celery

app = Celery()
app.conf.update(BROKER_URL='redis://localhost:6379/1',
        CELERY_RESULT_BACKEND='redis://localhost:6379/2')

@app.task()
def dummy():
    return '1'

ret = dummy.delay()
ret.get()
```
strace -p {pid}, get:

```
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
epoll_wait(3, [], 64, 1)                = 0
getpid()                                = 10484
```
It's flushing very quickly, seems gevent is checking something actively, after debuging, I find `ret.get()`  stucked in  `https://github.com/celery/celery/blob/master/celery/backends/asynchronous.py#L99`

If  change it to `sleep(0.1)`,  high cpu usage go way. Not sure what sleep(0) does here.

**Comment by thedrow** [comment]
`sleep(0)` tells gevent that it is allowed to yield to other greenlets at this point.
What do you think the fix should be?

**Comment by SharpEdgeMarshall** [comment]
Why `greenletDrainer` is bypassing the `wait_for` method of the consumer?
Why we don't just use the the pub/sub of redis instead of looping with sleep(0) and destroying CPU?

**Comment by thedrow** [comment]
I see that the timeout is not enforced as well.
That could be a problem as well.
I'll try to mitigate it.

Oh, it also doesn't use the gevent/eventlet sleep method which may be a problem.
I'm going to fix it soon.

How does the `greenletDrainer` bypasses `wait_for`?

**Comment by thedrow** [comment]
Wait, maybe sleep is monkeypatched?
Yes I just checked. It is. That's not the problem.
Should we increase the sleep time?

**Comment by thedrow** [comment]
I've analysed why we don't use the wait method.

The `run()` method calls `self.result_consumer.drain_events()` in a different greenlet until the drainer is stopped to allow concurrency.
That's why we also ignore the timeout.

Who repeatedly calls `wait_for()`?

**Comment by SharpEdgeMarshall** [comment]
ATM in our fork we increased `sleep(0)` to `sleep(0.001)` and the CPU usage dropped, this should be configurable from `interval` and I was going to do a PR, tell me if you don't have time I can do it.

Yes, I didn't see the `run()` method, but now the question is: Why we don't execute the `run()` logic in the main greenlet and remove the loop? Gevent should take care of releasing control during I/O, I'm missing something?

**Comment by thedrow** [comment]
I think that the expectation was that Celery won't repeatedly call `wait_for`.
Do you know who is doing so?

**Comment by tildedave** [comment]
We ran into this during a recent attempt to upgrade our servers to Celery 4.  This caused high CPU for all processes running in gevent where it waits on a result that isn't ready yet.

It looks like what's happening is that in the base `Drainer` class, it runs wait_for in a loop:
https://github.com/celery/celery/blob/c52105eb781338b24df040371920e7e26f6bc97b/celery/backends/asynchronous.py#L51-L62

Both gevent and eventlet have the following implementation where wait_for starts the drainer (only executed the first time then sleep(0)s).

I think what should be happening instead is a call to the wait() function which has a passed in timeout so on_interval() still gets executed, something like:
```
class geventDrainer(greenletDrainer):

    def wait_for(self, p, wait, timeout=None):
        from gevent import wait
        self.start()
        if not p.ready:
            wait([self._g], timeout=timeout)
```

**Comment by tildedave** [comment]
Actually, maybe we be using the passed in `wait` function in wait_for.  It doesn't look like we're currently using it at all now.
