### ISSUE TITLE
Custom task classes not working

### ISSUE THREAD

**Issue by arossert** [celery/celery#5002]
I'm trying to include some headers metadata to the task that will be included in the result.
I have tried to create a custom task classes that will override the `on_success`/`on_failure` methods and will append the data to the result but I can't get it to work.

I have copied the example from the documentation from [here](http://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-task-classes) but it does not work.
The `on_timeout` \ `on_failure` \ `on_success` methods are not being called when calling ```some_longrunning_task.apply_async()```.

## Checklist

- [x] Celery 4.2.1
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Copie the example and execute

## Expected behavior
The `on_timeout` \ `on_failure` \ `on_success` from `MyRequest` class should be executed.

## Actual behavior
The result is returning as normal like there is no `base` class to the task

**Comment by Jiydam** [comment]
Upgrading to 4.2.0 fixed the issue for me.
