### ISSUE TITLE
celery  delay got an unexpected keyword argument 'countdown' !

### ISSUE THREAD

**Issue by jekoie** [celery/celery#5003]
i follow the tutorial http://docs.celeryproject.org   but when i use task signature , it raise error.
i use celery 4.2
tasks.py
```
@app.task(bind=True)
def add(self, x, y):
	sleep(1)
	return x+y
```

errors below
> In [84]: s = add.s(2, 2)
> 
> IIn [85]: s.apply_async(countdown=1)
> Out[85]: <AsyncResult: f77090b2-15c6-45fc-a429-bb3b00ec5cec>
> 
> In [86]: s.delay(countdown=1)
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-86-486e78725d25> in <module>()
> ----> 1 s.delay(countdown=1)
> 
> c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\celery\canvas.py in delay(self, *partial_args,
> **partial_kwargs)
>     177     def delay(self, *partial_args, **partial_kwargs):
>     178         """Shortcut to :meth:`apply_async` using star arguments."""
> --> 179         return self.apply_async(partial_args, partial_kwargs)
>     180
>     181     def apply(self, args=(), kwargs={}, **options):
> 
> c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\celery\canvas.py in apply_async(self, args, kwa
> rgs, route_name, **options)
>     216         # pylint: disable=too-many-function-args
>     217         #   Borks on this, as it's a property
> --> 218         return _apply(args, kwargs, **options)
>     219
>     220     def _merge(self, args=(), kwargs={}, options={}, force=False):
> 
> c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\celery\app\task.py in apply_async(self, args, k
> wargs, task_id, producer, link, link_error, shadow, **options)
>     511                 pass
>     512             else:
> --> 513                 check_arguments(*(args or ()), **(kwargs or {}))
>     514
>     515         app = self._get_app()
> 
> TypeError: add() got an unexpected keyword argument 'countdown'
> 
> In [87]:

**Comment by art-vasilyev** [comment]
@jekoie `delay` is a shortcut to the `apply_async` without extra options: http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.delay
