### ISSUE TITLE
Is there any way to set multiprocess start method

### ISSUE THREAD

**Issue by DonYum** [celery/celery#5005]
In multiprocessing, there are 3 start_method: `spawn/fork/forkserver`. Each one have its own feature.

Such as, **I want every worker have seperated file descriptors and handles. So I can only use `spawn or forkserver` method, rather than `fork`.**

Ref: <https://docs.python.org/3.4/library/multiprocessing.html?highlight=process#contexts-and-start-methods>

However, celery only have `fork` method.

And I have try to use mp.set_start_method() to set it manually. 
Unfortunately, it failed too.

Then I found celery use billiard rather than mp. So I tried billiard again, also fail.

Thx for your attention!

**Comment by auvipy** [comment]
please post your questions to mailing list or irc. issue tracker is for reporting bugs mainly.

**Comment by DonYum** [comment]
@auvipy  Thx for your reply. 

But I'm sorry. I can not reach Celery mailing list from China Internet because it's blocked.

In <https://github.com/celery/celery/issues/5021>, I described in detail. If there are more info u need, just reply.

Thanks!
