### ISSUE TITLE
Update docs for extended results

### ISSUE THREAD

**Issue by johnarnold** [celery/celery#5007]
From https://github.com/celery/celery/pull/4490

Update http://docs.celeryproject.org/en/latest/userguide/calling.html#results-options with a description of the use case for it.

**Comment by huangsam** [comment]
Looking at this [test case](https://github.com/celery/celery/blob/v4.3.0rc2/t/unit/tasks/test_result.py#L71), it seems like `result_extended` is meant to be used for app configuration. It doesn't seem like a parameter you would pass into a call to `apply_async`. Does that mean the output from `apply_async` changes depending on whether that configuration is set or not? If so, how does the output change?

**Comment by thedrow** [comment]
We should test if `result_extended` works on tasks. I think it should.
Also, we added #5017 which could be used by users.

**Comment by thedrow** [comment]
I was wrong about what #5017 was all about.
