### ISSUE TITLE
Suggestion: Pass default parameters of task into a broker message

### ISSUE THREAD

**Issue by olii** [celery/celery#5012]
I suggest to pass the default arguments to the message that gets into the broker.

Having a simple task:
```python3
@app.task()
def hello(arg1, arg2=1, arg=2):
    pass

hello.delay('test')
```
And using RabbitMQ as a message broker I see the queued message:
```json
[["test"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]
```
Clearly, the default values for `arg2` and `arg3` are missing in the message.
This causes us trouble, because we interface celery from C++. Missing default values can be restored in the C++ part (python does this natively), but it causes a code duplication. When default value changes, this must be reflected at all places accordingly.

I think that for the portability and robustness of the celery framework, there should be some way of specifying that the default parameters should be included in the message that gets to the message broker.

The produced message should look like this:
```
[["test", 1, 2], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]
````
eventually, it can be passed in the kwargs dictionary.

**Comment by clokep** [comment]
Are you using C++ on the worker/consumer side or the producer side?

**Comment by olii** [comment]
I am sorry to mention that. In our setup, the c++ worker consumes tasks but also produces other tasks consumed by the python workers.

**Comment by clokep** [comment]
Interesting! I guess my confusion stems from -- why would you have the task defined in both C++ and in Python? You might be able to define it just in C++ and not have to duplicate anything.

**Comment by olii** [comment]
We define the task in the python part:
```python
@app.task()
def foo(arg1, arg2=True):
    """Docstring here."""
    logging.error('This should never be executed from the python part')
```
So we can call it from the python code easily:
```
foo.delay('bar')
```
Task is routed into the dedicated queue named `foo` using a celery router.
When celery worker is started, we exclude the `foo` queue from the list of served queues. This way, tasks that are directed to the queue `foo` are not executed in the python worker.
In the C++ worker, we consume messages from the  `foo`  queue. Only a small subset of tasks is processed in the C++ worker for performance reasons. And here comes the trouble of missing arguments, since the task declaration with parameter default values is defined only in python part.

Do you have an idea how to handle this in a better way?

**Comment by clokep** [comment]
That seems pretty reasonable, if you want to use the `foo.delay()` API, when I have tasks that I don't have access to the source code (which is somewhat similar to what you're doing here), I usually use `app.send_task()` instead.

E.g. you would do:

```python
app.send_task('foo', args=('bar', ))
```

You wouldn't need `foo` to be defined in Python code at all then, just your C++ code. (Note that by default the name of the task is the full Python path, e.g. `my_module.submodule.foo`.)
