### ISSUE TITLE
How to check if celery beat works?!?

### ISSUE THREAD

**Issue by jedie** [celery/celery#5014]
The celery worker can be easy checked with `celery inspect ping`

But there is nothing corresponding to celery beat, isn't it?

I have found one approach here: https://steemit.com/code/@qrul/celery-beat-and-workers-healthchecks by manually read the database with `shelve.open('celerybeat-schedule')` and check the last run times...

Have i missed something?!?

**Comment by thedrow** [comment]
There is no healthcheck for beat as of now.

Your link looks like a good solution.
We're open to a PR that adds this script to our contrib folder.
