### ISSUE TITLE
KeyError..unregistered task out of the blue. Ran sucessfully thousands of times int he 

### ISSUE THREAD

**Issue by AvkashKana** [celery/celery#5016]
Hi there,

I need your help. Four days ago I started getting KeyError:None on a task that has run successfully thousands of times in the past.  

The error is stating that Celery received an unregistered task type none for 'get_new_geojson' which is unusual as that is not the task name or the args name the job is under. 

'get_new_geojson' is a def in the code but not the registered task. The actual task name 'CollectGeoJson' does appear to be registered on each of our worker machines and other tasks set up the exact same way execute correctly. 

So why does this one not work? 

Task name is '_CollectGeoJson_'

Celery beat scheduler: 
_beat_schedule = {
      'trigger-getgeojson': {
        'task': 'trigger_collection',
        'schedule': crontab(minute='10', hour='0'),
        'args': ('CollectGeoJson', 'A',),
        },_

Running celery[redis,gevent]==4.0.2

KeyError 
------------
**ERROR:**

KeyError: 'get_new_geojson'
  File "celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]

Received unregistered task of type 'get_new_geojson'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?
-----------

What happens

1. The celery beat scheduler or I trigger a task-based.
2. Our code creates a unique ID for this task which is stored in our database.
3. The tasks show up in our tracker monitor like normal
4. The job count does not increase or change and the error appears

Attempts to fix:

1. I checked to make sure the CollectGeoJson which is the task and any subtask are registered on the celery machines. 
2. Restarted all machines ;)
3. Attempted to move the registration file.
4. Updated celery to 4.0.2

**Comment by auvipy** [comment]
try use latest version of celery 4.2.1 and report again.
