### ISSUE TITLE
Celery Result backend on Windows OS

### ISSUE THREAD

**Issue by razasaad** [celery/celery#5030]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
While testing celery on Windows 10 with python 3.6.3 and celery 4.1.1, I was unable to use the filesystem based result_backend. After hours of search I came across the code and it checks for `file:///` in the URL due to which the Windows based path scheming is failing. Any plan to fix this and support filesystem based backend in Windows?

**Comment by bstiel** [comment]
Even though Celery 4 is not officially supported on Windows, it should work with this:

`result_backend='file:///broker/results'

ie you need to use the UNC path. Had a similar discussion on stackoverflow:
https://stackoverflow.com/questions/52163492/celery-result-backend-on-windows/52164805

**Comment by pcp1976** [comment]
From backends/filesystem.py:

```
    def _find_path(self, url):
        if not url:
            raise ImproperlyConfigured(
                'You need to configure a path for the File-system backend')
        if url is not None and url.startswith('file:///'):
            return url[7:]
```
url[7:] returns `/<path>`, which results in (for example) `/C:/foo/bar/baz`. Which cannot be resolved on a windows box.

Swapping the 7 for an 8 makes this work on windows.
