### ISSUE TITLE
AttributeError celery.beat in populate_heap

### ISSUE THREAD

**Issue by oortega** [celery/celery#5032]
## Checklist

- [ x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
On some occasions when I update or add a periodictask of django admin,
I get this error via sentry

## Expected behavior
Update the scheduler without this error.

## Actual behavior
beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'append'",)

AttributeError: 'NoneType' object has no attribute 'append'
  File "celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "celery/beat.py", line 588, in start
    interval = self.scheduler.tick()
  File "celery/beat.py", line 293, in tick
    self.populate_heap()
  File "celery/beat.py", line 268, in populate_heap
    self._heap.append(event_t(

## Setup
amqp==2.3.2
billiard==3.5.0.4
celery==4.2.1
Django==1.10.4
django-celery-beat==1.1.1
django-celery-results==1.0.1
kombu==4.2.1
vine==1.1.4
redis==2.10.5

## Possible Solution?

I edit https://github.com/celery/celery/blob/master/celery/beat.py#L262 up to now it works correctly, but I do not know if it's the best way.

```
    def populate_heap(self, event_t=event_t, heapify=heapq.heapify):
        """Populate the heap with the data contained in the schedule."""
        priority = 5
        self._heap = []
        for entry in values(self.schedule):
            is_due, next_call_delay = entry.is_due()

            if self._heap != None:#Fix temporary AttributeError("'NoneType' object has no attribute 'append'",)..
                self._heap.append(event_t(
                    self._when(
                        entry,
                        0 if is_due else next_call_delay
                    ) or 0,
                    priority, entry
                ))
        if self._heap: #TypeError heap argument must be a list
            heapify(self._heap)
```

Thank you very much, I remain for your comments.

**Comment by LyleScott** [comment]
I'm experiencing the same issue. 

```
AttributeError: 'NoneType' object has no attribute 'append'
(11 additional frame(s) were not displayed)
...
  File "celery/apps/beat.py", line 81, in run
    self.start_scheduler()
  File "celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "celery/beat.py", line 588, in start
    interval = self.scheduler.tick()
  File "celery/beat.py", line 293, in tick
    self.populate_heap()
  File "celery/beat.py", line 268, in populate_heap
    self._heap.append(event_t(

AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by LyleScott** [comment]
Looks like `self._heap` is `[]` outside the loop using `.values()` but if you print `self._heap` when you are in the loop (after is_due), it's `None`. Debugging more later today.

**Comment by oortega** [comment]
I fix with this:

```
    def populate_heap(self, event_t=event_t, heapify=heapq.heapify):
        """Populate the heap with the data contained in the schedule."""
        priority = 5
        self._heap = []
        for entry in values(self.schedule):
            is_due, next_call_delay = entry.is_due()

            if self._heap != None:#Fix temporary AttributeError("'NoneType' object has no attribute 'append'",)..
                self._heap.append(event_t(
                    self._when(
                        entry,
                        0 if is_due else next_call_delay
                    ) or 0,
                    priority, entry
                ))
        if self._heap: #TypeError heap argument must be a list
            heapify(self._heap)
```

**Comment by LyleScott** [comment]
yeah, but that's a hack. we'll be testing it soon, and thanks for the tip!, but it seems like it would not run some schedules.  my and some team members are trying to fix the actual problem so i can sleep at night. we have large production loads facing this issue and we can't just skip tasks.

**Comment by LyleScott** [comment]
there must be a sideeffect somewhere or some thread weirdness. We're debugging more for the next hour or two and will report any findings!

**Comment by LyleScott** [comment]
We have proven this hack is not reliable. To prove it, we scheduled a beat task every minute for an hour (x4). We still lose a few tasks because beat still crashes when we create cron schedules. The side-effect needs to be addressed directly and we are pivoting resources to it. Next step, step through the code and hope we can find out where `self._heap` is going `[]` to `None`.

**Comment by LyleScott** [comment]
> Dou you also have this error #5048 ?

I have not seen this one. thanks for checking. We've been unsuccessful in hacks and fixes and are  out of time... so we just reverted for now. The hunt will continue after we get through some more customer facing work but hopefully it'll just go away with some new releases :) 

Our next step is to `git bisect` with versions of celery and django-celery-beat to see where it occurs. We don't really have another direction on the radar.
