### ISSUE TITLE
Is there a policy around releasing new versions?

### ISSUE THREAD

**Issue by mariokostelac** [celery/celery#5043]
I am wondering if this project has any policy around releasing new versions and its cadence or it's ad-hoc. 

To be more specific, that would help me to understand when can I expect new features like https://github.com/celery/celery/commit/90da2b3bb08d1b88063e312f6f965cff69a56a21 being available.

**Comment by auvipy** [comment]
right now NO. you have to install from master :) in near future, we have plan for that if we get enough funding.

**Comment by mariokostelac** [comment]
Thanks.
