### ISSUE TITLE
Celery Beat and its documentation don’t work.

### ISSUE THREAD

**Issue by jenstroeger** [celery/celery#5045]
Latest drop of Celery [4.2.1](https://github.com/celery/celery/releases/tag/v4.2.1), and following [these steps](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries) in the documentation, nothing happens. In fact, the [`on_after_configure` signal](http://docs.celeryproject.org/en/latest/reference/celery.html#celery.Celery.on_after_configure) doesn’t seem to be sent/received _at all_; various sources suggest to use the [`on_after_finalize` signal](http://docs.celeryproject.org/en/latest/reference/celery.html#celery.Celery.on_after_finalize) which is being called before anything else happens:
```
> ./bin/celery worker --beat --loglevel debug --schedule celery-beat-localhost.state
-----> on_after_finalize
[2018-09-11 11:15:53,491: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2018-09-11 11:15:53,493: DEBUG/MainProcess] | Worker: Building graph...
[2018-09-11 11:15:53,493: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
…
[2018-09-11 11:15:53,557: DEBUG/MainProcess] | Worker: Starting Beat
[2018-09-11 11:15:53,561: DEBUG/MainProcess] ^-- substep ok
[2018-09-11 11:15:53,562: DEBUG/MainProcess] | Worker: Starting Hub
[2018-09-11 11:15:53,562: DEBUG/MainProcess] ^-- substep ok
[2018-09-11 11:15:53,562: DEBUG/MainProcess] | Worker: Starting Pool
[2018-09-11 11:15:53,570: INFO/Beat] beat: Starting...
[2018-09-11 11:15:53,572: DEBUG/Beat] Current schedule:

[2018-09-11 11:15:53,573: DEBUG/Beat] beat: Ticking with max interval->5.00 minutes
[2018-09-11 11:15:53,573: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2018-09-11 11:15:53,638: DEBUG/MainProcess] ^-- substep ok
…
```
Please fix either the documentation or Celery so that following the manual actually works.

**Comment by auvipy** [comment]
were you able to make this work? any suggested improvement?

**Comment by max-l** [comment]
I'm running into the problem, *on_after_configure* never gets called  

@jenstroeger did you manage to get it to work ?

**Comment by jenstroeger** [comment]
@max-l, nope, and I’ve ditched Celery. It’s too broken.

**Comment by max-l** [comment]
@jenstroeger may I ask what you have replaced it with ? 

I'm evaluating options

**Comment by jenstroeger** [comment]
@max-l, so far I’m impressed with [Dramatiq](https://dramatiq.io/) but see also [this conversation on SO](https://stackoverflow.com/questions/46517613/python-task-queue-alternatives-and-frameworks).

**Comment by maybe-sybr** [comment]
Tested this on current master and I can see the event firing as expected and triggering periodic tasks in a `celery -A app worker -B` as well as a pair of `celery -A app beat` and `celery -A app worker` instances.

Whatever was broken previously seems to have been fixed for the following code using both a rabbitmq and redis backend:
```python
from celery import Celery
from celery.schedules import crontab

app = Celery()

print("About to use decorator")

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    # Calls test('hello') every 10 seconds.
    sender.add_periodic_task(10.0, test.s('hello'), name='add every 10')

    # Calls test('world') every 30 seconds
    sender.add_periodic_task(30.0, test.s('world'), expires=10)

    # Executes every Monday morning at 7:30 a.m.
    sender.add_periodic_task(
        crontab(hour=7, minute=30, day_of_week=1),
        test.s('Happy Mondays!'),
    )

@app.task
def test(arg):
    print(arg)

@app.task
def add(x, y):
    z = x + y
    print(z)
```

I don't think there's much for us to do here if it appears to be working now. The conversation is unlocked so if @jenstroeger or @max-l care to chime in with some new information, they're able to.

@auvipy @thedrow - shall we close this?
