### ISSUE TITLE
Docs: Worker documentation has formatting issues

### ISSUE THREAD

**Issue by blairg23** [celery/celery#5050]
Found at: http://docs.celeryproject.org/en/stable/reference/celery.bin.worker.html

![image](https://user-images.githubusercontent.com/6225764/45531381-c8726c00-b7ac-11e8-8c7d-b6734580cc13.png)

![image](https://user-images.githubusercontent.com/6225764/45531417-ee980c00-b7ac-11e8-9939-9ff8c66b6529.png)

**Comment by auvipy** [comment]
care to send an improvement request?

**Comment by blairg23** [comment]
Sure, what file would I find this template in?

**Comment by blairg23** [comment]
I may have misunderstood how these docs are set up. It seems like this "docs" section might actually be valid for `celery.bin.*.py` files, based on what I see in the source. Can you confirm? This issue can be resolved if this is the case.

**Comment by auvipy** [comment]
yes
