### ISSUE TITLE
Celery loglevel

### ISSUE THREAD

**Issue by yanjiangdi** [celery/celery#5051]
when I run celery with :

celery multi start w_online -A service.tasks -c 8 --loglevel=FATAL --logfile=${LOG_PATH}/celery.log

when a task comes in i get :
[2018-09-14 15:51:19,745: TRACE/ForkPoolWorker-1] End Calc [house_code:101103229329] [house_type:SELL] [Cost Time: 91 ms]

Why is this happening ? It shouldn't because I started it with loglevel TRACE. the problem is that for every task that comes to the task pool all the args are dumped, some times in the args are sensitive information.

**Comment by auvipy** [comment]
please post your support questions to celery-users mailing list or IRC first until its obviously a bug.
