### ISSUE TITLE
Chain celery.chord_unlock to retry indefinitely

### ISSUE THREAD

**Issue by amirajina** [celery/celery#5058]
## Checklist

- I have included the output of ``celery -A proj report`` in the issue.
- I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
from tests.tasks_tests import test1, test2, test3, test4
from celery import group, chain, chord

def get_status():
    mychain = chain(test2.s(), test3().s(), test4.s())
    group1 = group(mychain, test1.s())
    workflow = chain(group1, test3.s())

    tasks = workflow.delay()

    try:
        ret = tasks.get()
        state = tasks.status
        print("state = ", state)
        print("ret = ", ret)

    except:
        print("state after exception = " , tasks.status)
        return

get_status()

## Expected behavior
If an exception occured in on one of tasks in mychain :  chain(test2.s(), test3().s(), test4.s()), the status of chain will be FAILURE and then, the worken can excute test3.

## Actual behavior

When an exception occured on one of tasks in  mychain :  chain(test2.s(), test3().s(), test4.s()), the status of this chain still PENDING, so the worker cannot excute the test3, and an infinitie loop occured waiting for status (FAILURE or SUCCES) of this chain.

**Could please advise, how i can fail the status of chain if one of her parents has the FAILURE status**

**Comment by auvipy** [comment]
can you reproduce this in celery 4.3?
