### ISSUE TITLE
REST endpoint for other languages/systems to add work

### ISSUE THREAD

**Issue by twiggy** [celery/celery#5073]
This is a feature request.

We use celery and consider it to be our "worker" for doing tasks in the background. It works pretty well for that when celery beat is the initiator or one of our python apps.

It being very bound to python is becoming a problem for us. I know there are a few other projects that allow other languages to add work, but they feel less than official. https://github.com/mher/node-celery write directly to the backend and so don't support SQS and maybe might not work after a celery upgrade. It is also just for node, so would have to replicate for ruby, java, etc etc.

Is it possible to maybe have a celery REST endpoint that we could hit to add work to a celery queue. I realize I could probably just write a quick little Flask app that would effectively do this, but thought maybe it should be more official and tied into the main worker, but maybe a separate project is a better idea.

Another basic use case we want is to use a framework like Google's Cloud Pub/Sub service. When a message is received it would then insert a task for celery to complete. AWS has SNS which can then be tied to SQS which could then be consumed by a hand rolled tool like celery, but it seems like celery takes care of having multiple workers etc that I'd rather not replicate as I wouldn't do it nearly as well. 

Celery might need some sort of listener sub-system  which is hard to clusterize, but could tie to these very pub/sub type systems to initiate tasks. The REST endpoint doesn't really solve a pub/sub type world. Starting to think we need a side project that can be configured to listen to various pub/sub systems, has a REST endpoint etc to add work sort of how Beat is CRON for Celery.

Thanks for the communities consideration!

**Comment by jayendra13** [comment]
Something like this I am trying to achieve here https://stackoverflow.com/questions/53483007/multiligual-workers-with-celery-and-jupyter

**Comment by thedrow** [comment]
Celery used to have a webhooks mechanism which nobody used.
We removed it.
Celery 5 may introduce a redesigned version of this feature. I'm still thinking over it.

**Comment by johnarnold** [comment]
I use Flower's rest API for this. I soft-forked flower to merge all the bugfixes I need. Works good.
