### ISSUE TITLE
Django with celery class based tasks throw frame errors after a while

### ISSUE THREAD

**Issue by kpahawa** [celery/celery#5081]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Quick summary: 
A quick summary of the issue: When i run concurrent requests on Celery it works for one or two batches of concurrent requests. But then it suddenly stops working and I can't see why it would fail. Is there a mismatch between the tasks Id's sent to celery and the threads waiting for a response? I get the error as `received 0xb9 while expecting 0xce`. 

**Packages being used:**

- celery: 4.2.1 ( I have also switched to 4.1.1 but to no avail) 
- kombu: 4.2.1
- Rabbitmq: 3.3.5
- Django: 2.1.1
- amqp: 2.3.2
- psycopg2-binary: 2.7.5  <-- including this because I read on another github issue that postgres may be messing with celery or amqp? 

## Steps to reproduce
I have a custom Task class like this:

    from __future__ import absolute_import, unicode_literals
    from .services.celery import app
    from .services.command_service import CommandService
    from exceptions.exceptions import *
    from .models import Command

    class CustomTask(app.Task):

    def run(self, json_string, method_name, cmd_id: int):
        command_obj = Command.objects.get(id=cmd_id)  # type: Command
        try:
            val = eval('CommandService.{}(json_string={})'.format(method_name, json_string))
            status, error = 200, None
        except Exception as e:
            auto_retry = command_obj.auto_retry
            if auto_retry and isinstance(e, CustomError):
                command_obj.retry_count += 1
                command_obj.save()
                return self.retry(countdown=CustomTask._backoff(command_obj.retry_count), exc=e)
            elif auto_retry and isinstance(e, AnotherCustomError) and command_obj.retry_count == 0:
                command_obj.retry_count += 1
                command_obj.save()
                return self.retry(countdown=command_obj.retry_count*2, exc=e)
            val = None
            status, error = self._find_status_code(e)

        return_dict = {"error": error, "status_code": status, "result": val}
        return return_dict

    @staticmethod
    def _backoff(attempts):
        return 2 ** attempts

    @staticmethod
    def _find_status_code(exception):
        if isinstance(exception, APIException):
            detail = exception.default_detail if exception.detail is None else exception.detail
            return exception.status_code, detail

        return 500, CustomTask._get_generic_exc_msg(exception)

    @staticmethod
    def _get_generic_exc_msg(exc: Exception):
        s = ""
        try:
            for msg in exc.args:
                s += msg + ". "
        except Exception:
            s = str(exc)
        return s

    CustomTask = app.register_task(CustomTask())
`
The Celery App definition:

    from __future__ import absolute_import, unicode_literals
    import os
    from celery import Celery, Task
    from django.conf import settings

	# set the default Django settings module for the 'celery' program.
	os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myapp.settings')

	_celery_broker = settings.CELERY_BROKER  <-- my broker is pyamqp://username:password@localhost:5672/myhost. I have also tried with "librabbitmq://" and "amqp://". Nothing worked really

	app = Celery('myapp', broker=_celery_broker, backend='rpc://', include=['myapp.tasks', 'myapp.controllers'])
	app.config_from_object('django.conf:settings', namespace='CELERY')

	app.autodiscover_tasks(['myapp'])
        app.conf.task_protocol = 1
	app.conf.update(
	    result_expires=4800,
	    task_acks_late=True,
            task_protocol=1
	)

my init.py the tutorial recommended:

    from .celery import app as celery_app

    __all__ = ['celery_app']

The controller that is running the task:

	from __future__ import absolute_import, unicode_literals
	from .services.log_service import LogRunner
	from myapp.services.command_service import CommandService
	from exceptions.exceptions import *
	from myapp.services.celery import app
	from myapp.services.tasks import MyTask
	from .models import Command

	class MyController:
	    def my_method(self, json_string):
	        <non-async set up stuff here>

	        cmd_obj = Command.objects.create(<stuff>)  # type: Command
	        task_exec = MyTask.delay(json_string, MyController._method_name, cmd_obj.id)  <-- does an external task call but that doesn't matter
	        cmd_obj.task_id = task_exec
	        try:
	            return_dict = task_exec.get()
	        except Exception as e:
	            self._logger.error("ERROR: IP: {} and transaction: {}. Error Type: {}, "
	                            "Celery Error: {}".format(ip_addr, transaction_id, type(e), e))
	            status_code, error = self._find_status_code(e)
	            return_dict = {"error": error, "status_code": status_code, "result": None}
	        return return_dict

To reproduce, I hit the same URL from postman from three different tabs in succession (really fast). It works once or twice but then stops working and then all `.get()` calls stop working. Even the `.delay()` stops working. 

**Celery report:** I had to obfuscate some of the name but I assure you that the package names are correct and the tasks are for sure being picked up and processed properly. 

    software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.6
                    billiard:3.5.0.4 py-amqp:2.3.2
        platform -> system:Linux arch:64bit, ELF imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:pyamqp results:rpc:///

    ABSOLUTE_URL_OVERRIDES: {
     }
    ADMINS: []
    ALLOWED_HOSTS: ['*']
    ANGULAR_APP_DIR: '/my/proj/path/frontend/dist'
    APPEND_SLASH: True
    AUTHENTICATION_BACKENDS: ['django_auth_ldap.backend.LDAPBackend',
     'django.contrib.auth.backends.ModelBackend']
    AUTH_PASSWORD_VALIDATORS: '********'
    AUTH_USER_MODEL: 'auth.User'
    BASE_DIR: '/my/proj/path'
    CACHES: {
     'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
    CACHE_MIDDLEWARE_ALIAS: 'default'
    CACHE_MIDDLEWARE_KEY_PREFIX: '********'
    CACHE_MIDDLEWARE_SECONDS: 600
    CELERY_BROKER: 'pyamqp://username:password@localhost:5672/myhost'
    CORS_ALLOW_CREDENTIALS: True
    CORS_ORIGIN_ALLOW_ALL: True
    CSRF_COOKIE_AGE: 31449600
    CSRF_COOKIE_DOMAIN: None
    CSRF_COOKIE_HTTPONLY: False
    CSRF_COOKIE_NAME: 'csrftoken'
    CSRF_COOKIE_PATH: '/'
    CSRF_COOKIE_SAMESITE: 'Lax'
    CSRF_COOKIE_SECURE: False
    CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
    CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
    CSRF_TRUSTED_ORIGINS: []
    CSRF_USE_SESSIONS: False
    CURR_DIR: '/my/proj/path/MyProj'
    DATABASES: {
        'default': {   'ATOMIC_REQUESTS': False,
                       'AUTOCOMMIT': True,
                       'CONN_MAX_AGE': 0,
                       'ENGINE': 'django.db.backends.postgresql',
                       'HOST': 'localhost',
                       'NAME': 'username',
                       'OPTIONS': {},
                       'PASSWORD': '********',
                       'PORT': '5432',
                       'TEST': {   'CHARSET': None,
                                   'COLLATION': None,
                                   'MIRROR': None,
                                   'NAME': None},
                       'TIME_ZONE': None,
                       'USER': 'postgres'}}
    DATABASE_ROUTERS: '********'
    DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
    DATA_UPLOAD_MAX_NUMBER_FIELDS: 1000
    DATETIME_FORMAT: 'N j, Y, P'
    DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
     '%Y-%m-%d %H:%M:%S.%f',
     '%Y-%m-%d %H:%M',
     '%Y-%m-%d',
     '%m/%d/%Y %H:%M:%S',
     '%m/%d/%Y %H:%M:%S.%f',
     '%m/%d/%Y %H:%M',
     '%m/%d/%Y',
     '%m/%d/%y %H:%M:%S',
     '%m/%d/%y %H:%M:%S.%f',
     '%m/%d/%y %H:%M',
     '%m/%d/%y']
    DATE_FORMAT: 'N j, Y'
    DATE_INPUT_FORMATS: ['%Y-%m-%d',
     '%m/%d/%Y',
     '%m/%d/%y',
     '%b %d %Y',
     '%b %d, %Y',
     '%d %b %Y',
     '%d %b, %Y',
     '%B %d %Y',
     '%B %d, %Y',
     '%d %B %Y',
     '%d %B, %Y']
    DEBUG: True
    DEBUG_PROPAGATE_EXCEPTIONS: False
    DECIMAL_SEPARATOR: '.'
    DEFAULT_CHARSET: 'utf-8'
    DEFAULT_CONTENT_TYPE: 'text/html'
    DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
    DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
    DEFAULT_FROM_EMAIL: 'webmaster@localhost'
    DEFAULT_INDEX_TABLESPACE: ''
    DEFAULT_TABLESPACE: ''
    DISALLOWED_USER_AGENTS: []
    EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST: 'localhost'
    EMAIL_HOST_PASSWORD: '********'
    EMAIL_HOST_USER: ''
    EMAIL_PORT: 25
    EMAIL_SSL_CERTFILE: None
    EMAIL_SSL_KEYFILE: '********'
    EMAIL_SUBJECT_PREFIX: '[Django] '
    EMAIL_TIMEOUT: None
    EMAIL_USE_LOCALTIME: False
    EMAIL_USE_SSL: False
    EMAIL_USE_TLS: False
    ENVIRONMENT: 'DEV'
    FILE_CHARSET: 'utf-8'
    FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
    FILE_UPLOAD_HANDLERS: ['django.core.files.uploadhandler.MemoryFileUploadHandler',
     'django.core.files.uploadhandler.TemporaryFileUploadHandler']
    FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
    FILE_UPLOAD_PERMISSIONS: None
    FILE_UPLOAD_TEMP_DIR: None
    FIRST_DAY_OF_WEEK: 0
    FIXTURE_DIRS: []
    FORCE_SCRIPT_NAME: None
    FORMAT_MODULE_PATH: None
    FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
    IGNORABLE_404_URLS: []
    INSTALLED_APPS: ['django_filters',
     'django_apscheduler',
     'rest_framework',
     'corsheaders',
     'authentication.apps.AuthenticationConfig',
     'locking_service.apps.LockingServiceConfig',
     'command_runner.apps.CommandRunnerConfig',
     'django.contrib.admin',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'django.contrib.staticfiles',
     'rest_auth',
     'django.contrib.sites',
     'allauth',
     'allauth.account',
     'rest_auth.registration']
    INTERNAL_IPS: []
    LANGUAGES: [('af', 'Afrikaans'),
     ('ar', 'Arabic'),
     ('ast', 'Asturian'),
     ('az', 'Azerbaijani'),
     ('bg', 'Bulgarian'),
     ('be', 'Belarusian'),
     ('bn', 'Bengali'),
     ('br', 'Breton'),
     ('bs', 'Bosnian'),
     ('ca', 'Catalan'),
     ('cs', 'Czech'),
     ('cy', 'Welsh'),
     ('da', 'Danish'),
     ('de', 'German'),
     ('dsb', 'Lower Sorbian'),
     ('el', 'Greek'),
     ('en', 'English'),
     ('en-au', 'Australian English'),
     ('en-gb', 'British English'),
     ('eo', 'Esperanto'),
     ('es', 'Spanish'),
     ('es-ar', 'Argentinian Spanish'),
     ('es-co', 'Colombian Spanish'),
     ('es-mx', 'Mexican Spanish'),
     ('es-ni', 'Nicaraguan Spanish'),
     ('es-ve', 'Venezuelan Spanish'),
     ('et', 'Estonian'),
     ('eu', 'Basque'),
     ('fa', 'Persian'),
     ('fi', 'Finnish'),
     ('fr', 'French'),
     ('fy', 'Frisian'),
     ('ga', 'Irish'),
     ('gd', 'Scottish Gaelic'),
     ('gl', 'Galician'),
     ('he', 'Hebrew'),
     ('hi', 'Hindi'),
     ('hr', 'Croatian'),
     ('hsb', 'Upper Sorbian'),
     ('hu', 'Hungarian'),
     ('ia', 'Interlingua'),
     ('id', 'Indonesian'),
     ('io', 'Ido'),
     ('is', 'Icelandic'),
     ('it', 'Italian'),
     ('ja', 'Japanese'),
     ('ka', 'Georgian'),
     ('kab', 'Kabyle'),
     ('kk', 'Kazakh'),
     ('km', 'Khmer'),
     ('kn', 'Kannada'),
     ('ko', 'Korean'),
     ('lb', 'Luxembourgish'),
     ('lt', 'Lithuanian'),
     ('lv', 'Latvian'),
     ('mk', 'Macedonian'),
     ('ml', 'Malayalam'),
     ('mn', 'Mongolian'),
     ('mr', 'Marathi'),
     ('my', 'Burmese'),
     ('nb', 'Norwegian Bokmål'),
     ('ne', 'Nepali'),
     ('nl', 'Dutch'),
     ('nn', 'Norwegian Nynorsk'),
     ('os', 'Ossetic'),
     ('pa', 'Punjabi'),
     ('pl', 'Polish'),
     ('pt', 'Portuguese'),
     ('pt-br', 'Brazilian Portuguese'),
     ('ro', 'Romanian'),
     ('ru', 'Russian'),
     ('sk', 'Slovak'),
     ('sl', 'Slovenian'),
     ('sq', 'Albanian'),
     ('sr', 'Serbian'),
     ('sr-latn', 'Serbian Latin'),
     ('sv', 'Swedish'),
     ('sw', 'Swahili'),
     ('ta', 'Tamil'),
     ('te', 'Telugu'),
     ('th', 'Thai'),
     ('tr', 'Turkish'),
     ('tt', 'Tatar'),
     ('udm', 'Udmurt'),
     ('uk', 'Ukrainian'),
     ('ur', 'Urdu'),
     ('vi', 'Vietnamese'),
     ('zh-hans', 'Simplified Chinese'),
     ('zh-hant', 'Traditional Chinese')]
    LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
    LANGUAGE_CODE: 'en-us'
    LANGUAGE_COOKIE_AGE: None
    LANGUAGE_COOKIE_DOMAIN: None
    LANGUAGE_COOKIE_NAME: 'django_language'
    LANGUAGE_COOKIE_PATH: '/'
    LOCALE_PATHS: []
    LOGGING: {
     }
    LOGGING_CONFIG: 'logging.config.dictConfig'
    LOGIN_REDIRECT_URL: '/accounts/profile/'
    LOGIN_URL: '/accounts/login/'
    LOGOUT_REDIRECT_URL: None
    MANAGERS: []
    MEDIA_ROOT: ''
    MEDIA_URL: ''
    MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
    MIDDLEWARE: ['corsheaders.middleware.CorsMiddleware',
     'django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
     'spa.middleware.SPAMiddleware']
    MIGRATION_MODULES: {
     }
    MONTH_DAY_FORMAT: 'F j'
    CUSTIM_URL: None
    ANOTHER_URL: 'http://127.0.0.1:8000/'
    NUMBER_GROUPING: 0
    PASSWORD_HASHERS: '********'
    PASSWORD_RESET_TIMEOUT_DAYS: '********'
    PREPEND_WWW: False
    REST_FRAMEWORK: {
        'DATETIME_FORMAT': '%m/%d/%Y %H:%M:%S',
        'DEFAULT_AUTHENTICATION_CLASSES': (   'rest_framework.authentication.BasicAuthentication',
                                              'common.csrf_exempt_session_authentication.CsrfExemptSessionAuthentication'),
        'DEFAULT_FILTER_BACKENDS': (   'rest_framework.filters.SearchFilter',
                                       'django_filters.rest_framework.DjangoFilterBackend'),
        'EXCEPTION_HANDLER': 'exceptions.custom_exception_handler.custom_exception_handler'}
    ROOT_URLCONF: 'my_proj.urls'
    SECRET_KEY: '********'
    SECURE_BROWSER_XSS_FILTER: False
    SECURE_CONTENT_TYPE_NOSNIFF: False
    SECURE_HSTS_INCLUDE_SUBDOMAINS: False
    SECURE_HSTS_PRELOAD: False
    SECURE_HSTS_SECONDS: 0
    SECURE_PROXY_SSL_HEADER: None
    SECURE_REDIRECT_EXEMPT: []
    SECURE_SSL_HOST: None
    SECURE_SSL_REDIRECT: False
    SERVER_EMAIL: 'root@localhost'
    SESSION_CACHE_ALIAS: 'default'
    SESSION_COOKIE_AGE: 1209600
    SESSION_COOKIE_DOMAIN: None
    SESSION_COOKIE_HTTPONLY: True
    SESSION_COOKIE_NAME: 'sessionid'
    SESSION_COOKIE_PATH: '/'
    SESSION_COOKIE_SAMESITE: 'Lax'
    SESSION_COOKIE_SECURE: False
    SESSION_ENGINE: 'django.contrib.sessions.backends.db'
    SESSION_EXPIRE_AT_BROWSER_CLOSE: False
    SESSION_FILE_PATH: None
    SESSION_SAVE_EVERY_REQUEST: True
    SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
    SETTINGS_MODULE: 'my_proj.settings'
    SHORT_DATETIME_FORMAT: 'm/d/Y P'
    SHORT_DATE_FORMAT: 'm/d/Y'
    SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
    SILENCED_SYSTEM_CHECKS: []
    SITE_ID: 1
    STATICFILES_DIRS: ['/my/proj/path/frontend/dist']
    STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
     'django.contrib.staticfiles.finders.AppDirectoriesFinder']
    STATICFILES_STORAGE: 'spa.storage.SPAStaticFilesStorage'
    STATIC_ROOT: '/my/proj/path/staticfiles'
    STATIC_URL: '/static/'
    TEMPLATES: [{'APP_DIRS': True,
      'BACKEND': 'django.template.backends.django.DjangoTemplates',
      'DIRS': ['/my/proj/path/templates'],
      'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                         'django.template.context_processors.request',
                                         'django.contrib.auth.context_processors.auth',
                                         'django.contrib.messages.context_processors.messages']}}]
    TEST_NON_SERIALIZED_APPS: []
    TEST_RUNNER: 'django.test.runner.DiscoverRunner'
    THOUSAND_SEPARATOR: ','
    TIME_FORMAT: 'P'
    TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
    TIME_ZONE: 'UTC'
    USE_I18N: True
    USE_L10N: True
    USE_THOUSAND_SEPARATOR: False
    USE_TZ: True
    USE_X_FORWARDED_HOST: False
    USE_X_FORWARDED_PORT: False
    WSGI_APPLICATION: 'my_proj.wsgi.application'
    X_FRAME_OPTIONS: 'allow-from http://127:0.0.1:8203'
    YEAR_MONTH_FORMAT: 'F Y'
    is_overridden: <bound method Settings.is_overridden of <Settings "my_proj.settings">>
    broker_url: 'amqp://username:********@localhost:5672/myhost'
    result_backend: 'rpc:///'
    include: ['MyApp.tasks',
     'MyApp.controllers']
    task_protocol: 1
    result_expires: 4800
    task_acks_late: True

    Process finished with exit code 0

## Expected behavior
When I concurrent requests that hit this controller, celery will receive the task, process it, and then the `.get()` call in the controller will wait for it to finish. This will continue to work no matter what. 

## Actual behavior
**So here is the issue:**
When I run this Django controller by hitting the view with one request, one after the other, it works perfectly fine once or twice. But then two things happen:

1.  the `.get()` method just hangs there and then times out (connection reset by peer) **even though the celery worker has finished processing the task and the proper response ready**

2. I get these strange errors: "received 0xb9 while expecting 0xce", "received frame 3 while expecting type: 2"

What error is that? from my understanding, ampq throws that?

**Comment by auvipy** [comment]
whats the current status?

**Comment by auvipy** [comment]
IMHO this issue can be closed for now. if we get more report on latesr django and celery 5.2 releases we will reopen this again.
