### ISSUE TITLE
multiprocessing.pool worker in taks report  "ERROR/PoolWorker Exception in callback None "

### ISSUE THREAD

**Issue by zhaoliguangLFL** [celery/celery#5087]
Hello,everyone:
          I have a question about celery. 
          In my tasks file, I use the multiprocessing.pool module to work. Report the following error: ERROR/PoolWorker-106:1] Exception in callback None , ask for help, help me solve this problem. Here is my code -----------------
         tasks.py
         =========================================================
         import multiprocessing  
         from baseinfo.models import dbbackup,extend_dbbackup,Game_info,machine_info 
        @task
         def run_backup(db_id): 
                ...........................................................  Omitted here
               curr_proc = multiprocessing.current_process()
               curr_proc.daemon = False 
                __Pool = multiprocessing.Pool(__dbbackup.mcpool) #__dbbackup.mcpool = 5
               curr_proc.daemon = True
               __Pool.apply_async(run_ssh,args=(__pool[key],),callback=callback_log)   #run_ssh is For loop function for database backup
              __Pool.close()
             __Pool.join()
                     
thanks all

**Comment by auvipy** [comment]
don't use multiprocessing, as celery use a vendor version of that as billiard
