### ISSUE TITLE
Support `async` keyword in python 3.7

### ISSUE THREAD

**Issue by lig** [celery/celery#5101]
This issue is closed at the moment https://github.com/celery/celery/issues/4500

However, there is no release of Celery supporting Python 3.7.

It seems like a good idea to keep track somewhere the Python 3.7 compatibility for users to be able to subscribe and be notified when it is ok to upgrade their interpreters.

**Comment by MS-AvivG** [comment]
I agree, however, the master branch supports it (to the extent that it doesn't crash)

**Comment by auvipy** [comment]
you can use from master, we need to fix one test in celery and one in py-amqp . mainly deprecation warning though

**Comment by lig** [comment]
@auvipy obviously, "use master" nowhere near "fixed released". It is great that some code works on Python 3.7 but it is not the same as Python 3.7 is supported by the latest release. I have no doubts that there are a lot of celery users who prefer to use Python 3.6 meanwhile and wait for Python 3.7 is being supported by a stable release.
My point is that it is a good idea to keep some tracking branch updated with the Celery Python 3.7 compatibility status to let Celery users subscribe to such a tracking issue and be up to date without further bothering Celery developers.

**Comment by xirdneh** [comment]
Python 3.7 compatibility work is being done on master which is the development branch.
Having an extra branch to do compatibility work will open the doors to merge hell.
The alternative is to keep track of issues that point to 3.7 compatibility. There are many tasks we have to do to fully support 3.7 which will make creating one single issue for everything not ideal either.
We are aware this is something the community want and we are doing our best to get there and any help is appreciated.
Thank you.
