### ISSUE TITLE
Set workers availability status dynamically

### ISSUE THREAD

**Issue by himanshu1691** [celery/celery#5102]
We have a scenario where the workers have to use resources from a limited pool of resources that is specific to that machine.
Is it possible to set up workers in a way that they only start fetching tasks when the resources are free on the system and then go back to waiting for state till the time resources are free again?

Just to clarify, resources don't mean system's hardware resources but it is some other info which is stored in a DB locally and cannot be remotely fetched.

Is it a good idea to try and implement this using rate limiting which can be adjusted on the runtime.
1) When resources are exhausted, set rate limiting to 0
2) When resources are available, increase rate limit.
3) After each completed task check resources and adjust rate limit.

Are there any other recommended implementation methods for this?
Is celery not a good candidate for this kind of project.

**Comment by auvipy** [comment]
Please cross post your questions to the celery-users mailing list. https://groups.google.com/forum/#!forum/celery-users, will re-open if this issue turned into a feature request.
