### ISSUE TITLE
Celery beat AttributeError 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by maximekl** [celery/celery#5104]
## Steps to reproduce
Launch beat :  `celery -A conf beat -S django --detach`

## Expected behavior
Celery beat is up and running.

## Actual behavior
Error `AttributeError 'NoneType' object has no attribute 'keys'`
File : celery/beat.py in schedules_equal at line 317

```python
    def schedules_equal(self, old_schedules, new_schedules):
        if set(old_schedules.keys()) != set(new_schedules.keys()):
            return False
        for name, old_entry in old_schedules.items():
            new_entry = new_schedules.get(name)
            if not new_entry:
                return False
        return True
```

## Step to correct
Add a condition if old_schedules is None
```python
    def schedules_equal(self, old_schedules, new_schedules):
        if old_schedules is None:
            return False
        if set(old_schedules.keys()) != set(new_schedules.keys()):
            return False
        for name, old_entry in old_schedules.items():
            new_entry = new_schedules.get(name)
            if not new_entry:
                return False
        return True
```

**Comment by HugoArts** [comment]
I've had the same exception suddenly pop up since yesterday. Since celery hasn't had any recent releases the timing seemed odd, so I investigated further. This revealed that the bug was caused by a recent upgrade of django-celery-beat from 1.1.0 to 1.2.0. Downgrading solved the issue.

I've filed an [issue](https://github.com/celery/django-celery-beat/issues/175) with the django-celery-beat folks.

**Comment by auvipy** [comment]
please try the django-celery-beats from master branch

**Comment by maximekl** [comment]
Hi it's quite unrevelant to close this issue and ask to try django-celery-beats.
I only use celery and the error is resolved if i modify the celery package file.

**Comment by auvipy** [comment]
I got confused with the last comment pointing to Django-celery-beat actually

**Comment by maximekl** [comment]
@auvipy No problem, but the error is still in the celery package, and i provided a solution to fix this.

**Comment by auvipy** [comment]
would you mind sending the solution as a PR? possibly with a test?

**Comment by hellerbarde** [comment]
@maximekl 
> I cloned the repo and create a branch from master.

For Github pull requests, you'll have to fork the repository, push the branch to copy of the repo and then there will be a button for creating a pull request. You won't be able to push on a repository that is not yours. (Unless given permission)

**Comment by maximekl** [comment]
My bad, just made a copy..... what a joke :(
