### ISSUE TITLE
be able to set connecting timeout for kombu from within celeryconfig / djangosettings

### ISSUE THREAD

**Issue by sivang** [celery/celery#5109]
celery 3.1.25.

I'm seeing a connecting linger when using celery to send messages through a rabbitmq server frontended with an AWS elb.

Connection never close, and I'd like to make sure this is not something wrong with how kombu is connecting to RMQ to send messages, e.g. by not providing a defined timeout for the client connection which leaves the rabbitmq/ celery at the receiving end confused and never closing the connections even though it was for one message each. 

What would be the way to setup a timeout for kombu from Celery? I could not find anywhere in the docs.

**Comment by xirdneh** [comment]
I believe this configuration exists but you will have to update to 4.0
http://docs.celeryproject.org/en/latest/userguide/configuration.html#broker-connection-timeout

**Comment by sivang** [comment]
But when about setting the timeout in the producer? is this it? -
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_transport_options
