### ISSUE TITLE
Why beat.Schedle _when return this???

### ISSUE THREAD

**Issue by yywing** [celery/celery#5113]
## Steps to reproduce
**https://github.com/celery/celery/blob/master/celery/beat.py#L261**
```python
        return (mktime(as_now.timetuple()) +
                     as_now.microsecond / 1e6 +
                     (adjust(next_time_to_run) or 0))
```
What about the as_now timezone???
## Expected behavior
like this?
```python
return (as_now.timestamp() + (adjust(next_time_to_run) or 0))
```
But timestamp not support for python2.7?
```python
        return (mktime(as_now.utctimetuple()) +
                     as_now.microsecond / 1e6 +
                     (adjust(next_time_to_run) or 0))
```
Or, tell me why wirte like this.

This problem is found because of django-celery-beat.TzAwareCrontab not work as well.
Beacause this schedule.now() return a time with timezone.

**Comment by yywing** [comment]
python2.7 dont have `timestamp()`

**Comment by yywing** [comment]
This question come back.

**Comment by auvipy** [comment]
what?
