### ISSUE TITLE
`date_done` object in metadata is not serializable.

### ISSUE THREAD

**Issue by xirdneh** [celery/celery#5118]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://redis:6379/0
```

- [x] I have verified that the issue exists against the `master` branch of Celery.
## Steps to reproduce

This is using: 

    - latest master
    - Django 2.1.2
    - rabbitmq as broker
    - redis as backend

Queue debug task:
```
@app.task(bind=True)
def debug_task(self):
    """Debug Task"""
    print('Request: {0!r}'.format(self.request))
    return "debug task"
```

## Expected behavior

Task gets queued and runs in the worker without any hiccups.

## Actual behavior
Task is not run and following error is displayed:
```
Traceback (most recent call last):
  File "/src/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/src/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/src/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/cyanide/data.py", line 18, in default
    return super(JSONEncoder, self).default(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
```

Also, running `make test` yields some of the result tests failed with the previous error.

## Solution

I believe this was introduced by https://github.com/celery/celery/pull/4490.
The `date_done` object in the metadata is added as a `datetime` object instead of its iso string representation.
**PR is on the way.**

One thing that concerns me is how come tests in travis-CI are running correctly and not catching this?
if I run the test suite locally it does show this error.

**Comment by georgepsarakis** [comment]
@xirdneh I am not sure why this happens locally. Kombu JSON serialization does support `datetime` objects:

```
In [1]: from kombu.utils import json
In [2]: import datetime 
In [3]: json.dumps({'a': datetime.datetime.utcnow()})
Out[3]: '{"a": "2018-10-17T04:33:43.312791"}'
```

**Comment by xirdneh** [comment]
@georgepsarakis Do you get an error if you run `make test` locally?

**Comment by xirdneh** [comment]
Update: This does not happen when running `tox`. Will continue to investigate.

**Comment by xirdneh** [comment]
This issue has to do with how the `Dockerfile` sets up the dev environment. Closing it in favor of: https://github.com/celery/celery/issues/5096

**Comment by georgepsarakis** [comment]
Thanks for clarifying @xirdneh .

**Comment by georgepsarakis** [comment]
Thanks for clarifying @xirdneh .
