### ISSUE TITLE
Sequentially processing queues by priority

### ISSUE THREAD

**Issue by Skeen** [celery/celery#5127]
I have an use-case similar to the one from #4282

In our use-case there are roughly three-types of tasks:
* idle-time background tasks of low priority (`lowprio`)
* ordinary tasks of medium priority (`midprio`)
* time-critical tasks of very high priority (`highprio`)

The goal is to execute all time-critical tasks (`highprio`) before moving on to the ordinary tasks (`midprio`), executing all of these before finally starting on the idle-time tasks (`lowprio`). If new tasks of a higher priority comes in, the goal would be to pick these up as soon as possible (i.e. once a given worker finished it's current task).

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

We are currently running:
```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:2.7.13
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:django-db
```
But I have also verified the issue against master:
```
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.13
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:django-db
```
Installed via:
```
pip install --upgrade https://github.com/celery/celery/archive/master.z
```

## Steps to reproduce

I attempted implementing a priority scheme according to the documentation, by creating three separate queues with `rabbitmq` as broker:
```
CELERY_TASK_QUEUES = (
    Queue(
        'lowprio',
        Exchange('lowprio'),
        routing_key='lowprio',
        queue_arguments = {'x-max-priority': 255}
    ),
    Queue(
        'midprio',
        Exchange('midprio'),
        routing_key='midprio',
        queue_arguments = {'x-max-priority': 127}
    ),
    Queue(
        'highprio',
        Exchange('highprio'),
        routing_key='highprio',
        queue_arguments = {'x-max-priority': 0}
    ),
)
```
Along side the settings:
```
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
```
Queueing the tasks with:
```
from tasks import sleep_task
queues = {
    'lowprio': 0,
    'midprio': 5, 
    'highprio': 9,
}
for _ in range(1000):
    for queue in queues:
        sleep_task.apply_async(args=[0.1], queue=queue, routing_key=queue, priority=queues[queue])
```
Where the `sleep_task` is defined as:
```
from celery import shared_task

@shared_task
def sleep_task(seconds):
    import time
    time.sleep(seconds)
```
Starting celery after all tasks have been committed, and running until one queue is empty, I would expect the following result:

## Expected behavior
```
lowprio 1000
midprio 1000
highprio 0
```
I would consider it acceptable, if a small number of `midprio` jobs was executed due to scheduling or similar, but sadly the following is the result:

## Actual behavior
```
lowprio 628
midprio 364
highprio 0
```
Showing that priorities do indeed work, and that `highprio` is prioritized over `midprio`, which is again prioritized over `lowprio`. Unfortunately the prioritization is prominent enough, and I found no way to make it more prominent.

I've tried utilizing specific workers for each queue, but I still see I still see `highprio` tasks entering the queue and waiting, while `lowprio` tasks are getting picked up (albeit at a slower processing rate).
The only work-around seems to be utilize an excessive number of `highprio` workers, however this leaves me with a huge-backlog of `midprio` and `lowprio` jobs. I've tried playing around with Linux priorities for the workers, using `nice` / `renice`, but to no avail. 

From what I've gathered prioritizes are handled by the broker itself, and not by celery; but is there an option to somehow separate the queues or to utilize multiple brokers in a prioritized fashion, rather than in a round-robin fashion?

**Comment by MattBlack85** [comment]
how many workers are you starting?

**Comment by Skeen** [comment]
@MattBlack85 For the tests above I'm running just 1 worker, started by running:
```
celery worker -A project
```
Which yields a concurrency of 4 (prefork).

**Comment by Skeen** [comment]
@MattBlack85 yes, I've tried that, I end up consuming from `highprio` significantly faster than from the two others, this is of course expected, but when there is no load on `highprio`, I'd like to see full CPU utilization on `lowprio` / `midprio` tasks, otherwise I will never get through the workload.

In order to achieve full CPU utilization on these non `highprio` tasks, I need several parallelization; which means I will need even more workers for `highprio` (assuming fair round-robin scheduling), or intelligent scheduling between the threads.
- I attempted to achieve this using Linux thread priorities to no avail.

Thus the problem with this setup, is that the 3 workers for `highprio` don't help out in `lowprio` / `midprio`. I was looking into utilizing the `autoscale` feature to mimick the `intelligent scheduling` I am looking for, but quite frankly I couldn't get that to work at all.

**Comment by MattBlack85** [comment]
Gotcha, the way we got around this is having separate clusters per queue, then we monitor the rabbit queues with a basic threshold. If it goes over for some queues we start more workers and then kill them if backlog is done. Complicated but couldn't come up at that time with a better solution

**Comment by Skeen** [comment]
@MattBlack85 I did consider doing something along the same lines, but I'd rather uncover whether it was possible to do with celery, before I went on with something like that.
- No offense, but I do not find it to be a very attractive solution compared to a concept of queue priorities, and just consuming from queues in a prioritized order.

**Comment by Skeen** [comment]
I've made an ugly hack which achieves what I need:
```
# Collection of queues we have ever seen
queues_seen = set()

def _one_queue_consume(consumer):
    """Consume one queue at a time."""
    # List of queues currently being consumed
    active_queues = []
    for queue in consumer.queues:
        result = queue.queue_declare(passive=True)
        active_queues.append({
            'count': result.message_count,
            'priority': queue.queue_arguments['x-max-priority'],
        })
        # We've seen this queue now
        queues_seen.add(queue)

    # Queues that are being consumed and have messages
    live_queues = [queue for queue in active_queues if queue['count'] > 0]

    if live_queues:
        current = min(live_queues, key=lambda el: el['priority'])
        # Enable all queues above us, and disable all queues below us
        for queue in queues_seen:
            if queue.queue_arguments['x-max-priority'] <= current['priority']:
                consumer.add_queue(queue)
            else:
                consumer.cancel_by_queue(queue)
    else:
        # No live queues - Make sure we are consuming everything
        for queue in queues_seen:
            consumer.add_queue(queue)
    consumer.consume()
```
Inserted right into the `asynloop` / `synloop` of `celery/worker/loops.py`.

Using this I get:
```
lowprio 1000
midprio 998
highprio 0
```

**Comment by xirdneh** [comment]
Is the proposed solution consuming from the queues that have set a bigger `max_priority` first?
And every time a worker gets any messages (prefork or not) to first get them from the queues that have a bigger `max_priority` and then loop through the other queues?

Meaning, using `max_priority` as a queue priority value?

**Comment by Skeen** [comment]
Hi @xirdneh

I don't believe I have proposed a solution, but rather argued a shortcoming of the prominentness of prioritization of queued jobs with the RabbitMQ broker.

But otherwise; yes, the behavior I was expecting was for consumption to happen from queues with higher priority before queues with lower priority, and while it did happen, the prioritization was not as prominent as I would have liked.

I'm not arguing that it should necessarily be a complete binary split like I've hacked together, rather I'd like to think an optimal solution would allow for prioritization prominentness of none all the way to what I've hacked together.

**Comment by xirdneh** [comment]
I believe these are different issues or shortcomings.
The first one is task priority which is implemented by the broker (as pointed out earlier).
Celery will ask the broker which is the next task and the broker will reorder the tasks in the queue based on its implementation of priority. There's not that much we can do about it other that understand how the broker handles priority.

Now, the second part, I think is the main point here, is about priorities in queues.
Celery will round robin worker processes which will then consume messages from the queues assigned in, I believe,  round robin. This means that the queues themselves don't have priorities and the priority assign to a queue is not taken into consideration by Celery workers.

Your workaround @Skeen should be a good solution for your specific needs. I think a good way to offer a partial solution to this problem is to figure out a way to specify a custom strategy to handle queues. It could get complicated but the way that Celery works right now doesn't really implements the concept of different priorities at the queue level.

**Comment by johnyoonh** [comment]
Even though assigning specific priority values for each queue is not possilbe, it it now possible to order of the queue should be processed and acheieve the outcome that @skeen expected.  http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.transport.redis.html#kombu.transport.redis.Channel.queue_order_strategy

**Comment by bityob** [comment]
Hey,

Can this be achieved with RabbitMQ broker?

@auvipy @Skeen

**Comment by manisha0629** [comment]
Priority is not working as it executes the tasks sequentially. Please confirm whether RabbitMQ supports priority.

**Comment by bityob** [comment]
@manisha0629 
RabbitMQ supports priority in the queue itself, so higher priority messages will be fetched before lower ones.
But in this case, we want to have 2 different queues, one for high priority and the second for low priority.
Still, we want Celery to be able to read messages from the 1st queue and only read from the 2nd queue if the 1st one is empty.

**Comment by vocuzi** [comment]
Is there a way to achieve this with RabbitMQ as broker ?

**Comment by thedrow** [comment]
RabbitMQ cannot proritize messages over queues. What potentially can be done is to create multiple channels with a different prefetch count for each channel so more tasks from queue A bound to channel A would be fetched than tasks from queue B bound to channel B.
This is currently unsupported by Celery.
