### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by RoraxHan** [celery/celery#5132]
I'm using celery 4.1 in flask. (python 2.7)
```
print('--test unicode', u'glätteisen')
```
this code is working in flask. but when I try this code inside celery, that doesn't print anything for unicode string.
I can only see '---test unicode' in my console.
What is the problem?

**Comment by RoraxHan** [comment]
Hello, Thanks for replying.
I made test project for you.
Please check it and let me know.
https://bitbucket.org/amcquistan/celery-demo/src/master/

**Comment by RoraxHan** [comment]
@xirdneh  Hello! I uploaded the source that you asked. I hope you check it soon and let me know about it.

**Comment by RoraxHan** [comment]
Did you get the code?
Please update me after you reviewing the code.

**Comment by RoraxHan** [comment]
@xirdneh Can you please reply for this issue?
I made the simple project and shared here. Please check and let me know for me.

**Comment by xirdneh** [comment]
@RoraxHan Sorry, will take a look next week.

**Comment by RoraxHan** [comment]
@xirdneh Hi! Didn't you check this yet?
If you are busy, when can I expect the the time for this issue?

**Comment by RoraxHan** [comment]
Any update on this problem?
This is really important for my project.

**Comment by auvipy** [comment]
it would be better to move to python 3
