### ISSUE TITLE
Eager tasks ignore CELERY_*_SERIALIZER settings

### ISSUE THREAD

**Issue by muzhig** [celery/celery#5133]
It just uses `json`.
The bug is on master, but not on last production version, probably easy to fix it now than later.
Relevant line is this: https://github.com/celery/celery/blob/master/celery/app/task.py#L529

**Comment by auvipy** [comment]
what is the proposed fix?

**Comment by clokep** [comment]
@muzhig Any steps to reproduce this issue? At first glance that code looks OK.

**Comment by bjackson** [comment]
I have this issue as well. 

The producer returned from `app.producer_or_acquire(producer)` has its `serializer` attribute set to `None`. When `serializer.dumps` is called with `serializer=None` it will use the default encoder, which is `json`.

**Comment by bjackson** [comment]
If you are using the pickle serializer, and you call the task with `serializer='pickle'` an `ContentDisallowed` exception will be raised.

**Comment by bjackson** [comment]
I've submitted a PR to fix this issue: https://github.com/celery/celery/pull/5342
