### ISSUE TITLE
pidbox received method enable_events() [reply_to:None ticket:None]

### ISSUE THREAD

**Issue by somtirtha** [celery/celery#5136]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      Using Celery 4.2.0
     amqp 2.3.2
     Running: celery -A proj worker -l DEBUG -E -Ofair 

- [x] I have verified that the issue exists against the `master` branch of Celery.
   Yes

## Steps to reproduce
   Running rabbitmq in a docker container and celery on a separate container having exposed rabbitmq port to it.

## Expected behavior
Connection from celery to rabbitmq stays

## Actual behavior
Rabbitmq connects fine but as soon as Celery workers start I get this error:
pidbox received method enable_events() [reply_to:None ticket:None]

On the rabbitmq logs I get:
closing AMQP connection <0.3086.0> (172.31.0.9:41548 -> 172.31.0.4:5672, vhost: '<hostname>', user: 'user_name')

Please share if you have experienced this.

**Comment by jheld** [comment]
Flower and other clients may be calling that (by default calling it periodically). I'm unsure if rabbitmq itself does so.

**Comment by auvipy** [comment]
post your support questions to mailing list
