### ISSUE TITLE
Celery inspect queries hang forever.

### ISSUE THREAD

**Issue by rajeshyogeshwar** [celery/celery#5139]
Hi, I am using Celery inside a Docker container with Redis as the broker for one of my Django projects. I am unable to use any celery inspect queries as the command simply doesn't respond forever and I have to hit CTRL+C every time. My Redis is again in one of the docker containers and it is password protected as well. 

**Project Report**

```
software -> celery:4.0.2 (latentcall) kombu:4.1.0 py:3.5.4
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```

**Steps to reproduce**

I am not sure how one can reproduce it. Because I have my development environment where it is running fine but in my production environment it doesn't. Both my environments have absolutely same setup.

**Expected Behavior**

The expected behavior is that I should be able to use celery inspect queries without an issue.

**Actual Behavior**

Celery inspect queries hang forever. Probably due to same I am also unable to use flower for checking on celery.

Although I have tried to create this issue with the provided template, do point if I have erred somewhere.

**Comment by ccate** [comment]
Experiencing same behavior in a dockerized environment.

**Comment by jozo** [comment]
Hi. I have the same (or similar) problem. When rabbitmq (my brocker) is not running, celery can't connect to it. But instead of throwing exception after some timeout it waits forever until I hit Ctrl+C. Code example will be probably best:
```
>>> app = Celery(settings.CLEAN_CACHE_CELERY_APP)
>>> app.config_from_object('django.conf:settings', namespace='CELERY')
>>> inspect = app.control.inspect()
>>> inspect.scheduled()

^CTraceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/web/env/lib/python2.7/site-packages/celery/app/control.py", line 97, in scheduled
    return self._request('scheduled')
  File "/home/web/env/lib/python2.7/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/home/web/env/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/home/web/env/lib/python2.7/site-packages/kombu/pidbox.py", line 304, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/web/env/lib/python2.7/site-packages/kombu/connection.py", line 819, in default_channel
    self.ensure_connection()
  File "/home/web/env/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/home/web/env/lib/python2.7/site-packages/kombu/utils/functional.py", line 345, in retry_over_time
    sleep(1.0)
KeyboardInterrupt
>>>
```

Library "kombu" tries to connect every second to rabbitmq and it tries forever. I think it should limited somehow (maybe by "timeout" argument in Inspect class?)


If it's needed I can create sample docker app with this problem.

**Comment by ryo12882** [comment]
I faced the same issue. And it is also dockerized environment. Anyone knows a solution?

**Comment by auvipy** [comment]
with celery 4.3 as well?

**Comment by MattBlack85** [comment]
We had this problem as well, AFAIR inspect commands accept a timeout arg `-t X` where X is the number of seconds the command will wait at max. It should solve the hanging problem

**Comment by feigenblatt** [comment]
Same issue here.
The -t/--timeout seems to affect only how long we'll wait for workers, but not for rabbitmq itself.
If the broker is down the inspect commands will hang forever.

**Comment by auvipy** [comment]
any solution?

**Comment by pkariz** [comment]
the issue in my case was that when I ran `docker-compose exec celeryworker python manage.py shell`
the `CELERY_BROKER_URL` was not set properly (to the redis container). That was because `CELERY_BROKER_URL` was exported inside the `entrypoint.sh`, which is not ran when you `exec` to an existing container. So instead of `exec` i use `run`, eg:
```bash
docker-compose run --rm celeryworker bash
celery -A proj inspect stats
```
So, at least in my case, that doesn't seem like a celery issue but a mistake from the user.

**Comment by Rawgeek** [comment]
In Django setting `BROKER_POOL_LIMIT = 1` hangs `app.control.inspect().active()` when using with AMQP

**Comment by auvipy** [comment]
with celery==4.4.0rc3?

**Comment by Rawgeek** [comment]
celery==4.3.0, although I'll try ==4.4.0rc3 and report back soon

**Comment by Rawgeek** [comment]
Ok. I can confirm this is still an issue with `BROKER_POOL_LIMIT = 1`
Here is full config:
```
BROKER_CONNECTION_MAX_RETRIES = None
BROKER_CONNECTION_TIMEOUT     = 30
BROKER_HEARTBEAT  = None
BROKER_POOL       = LIMIT 1
BROKER_URL        = amqp://guest@localhost//

CELERYD_PREFETCH_MULTIPLIER = 4
CELERYD_TASK_TIME_LIMIT     = 21600
CELERY_ACCEPT_CONTENT       = ('json', 'pickle')
CELERY_ACKS_LATE            = True
CELERY_ALWAYS_EAGER         = False
CELERY_BROKER_URL           = amqp://guest@localhost//
CELERY_IGNORE_RESULT        = True
CELERY_PREFETCH_MULTIPLIER  = 4
CELERY_RESULT_BACKEND       = redis://localhost:6379/0
CELERY_RESULT_SERIALIZER    = pickle
CELERY_SEND_EVENTS          = True
CELERY_SEND_TASK_SENT_EVENT = True
CELERY_TASK_SERIALIZER      = pickle
CELERY_TIMEZONE             = UTC
```

**Comment by preeth1** [comment]
Why is this closed? I dont see a solution

**Comment by Rawgeek** [comment]
In my case increasing BROKER_POOL_LIMIT to over 1 helped

**Comment by auvipy** [comment]
if there is any possible document improvement please send a PR.

**Comment by thedrow** [comment]
> 
> 
> the issue in my case was that when I ran `docker-compose exec celeryworker python manage.py shell`
> the `CELERY_BROKER_URL` was not set properly (to the redis container). That was because `CELERY_BROKER_URL` was exported inside the `entrypoint.sh`, which is not ran when you `exec` to an existing container. So instead of `exec` i use `run`, eg:
> 
> ```shell
> docker-compose run --rm celeryworker bash
> celery -A proj inspect stats
> ```
> 
> So, at least in my case, that doesn't seem like a celery issue but a mistake from the user.

@preeth1 It seems like it wasn't a bug for the OP's case.

**Comment by Rafatlne** [comment]
For Django `celery -A {celery_app_name} inspect registered` does the trick.
