### ISSUE TITLE
Migrate from AppVeyor to Travis-CI

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5147]
Travis-CI has added preview support for Windows.
We should migrate from AppVeyor to Travis-Ci.
Having one CI platform mean we can manage everything more easily.

**Comment by auvipy** [comment]
that would be great!

**Comment by xirdneh** [comment]
How much support are we officially offering for Windows?

**Comment by auvipy** [comment]
basic

**Comment by auvipy** [comment]
https://github.com/cclauss/itinerant-tester-windows/blob/master/.travis.yml

**Comment by auvipy** [comment]
closing this as we are no longer going to use travis
