### ISSUE TITLE
Setting beat_schedule to empty dictionary causes cascading DB read errors

### ISSUE THREAD

**Issue by chrisconlan** [celery/celery#5151]
## Version and Environment
This affects Celery version 4.2.1 (windowlicker) on Django 2.1.

## Steps to reproduce
Set `CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'` in your `settings.py`.

Set `app.conf.beat_schedule = {}` in your `celery.py` file. Run a `--beat` worker.

## Expected behavior
Should act as though no scheduler is set up, and therefore should not attempt to run the database scheduler periodically.

## Actual behavior
Scheduler attempts to run every few minutes, and for some reason dumps the following to the main worker's log...

```
[2018-10-28 16:23:27,410: ERROR/Beat] Database error while sync: ProgrammingError('Cannot operate on a closed database.',)
...
sqlite3.ProgrammingError: Cannot operate on a closed database.
...
The above exception was the direct cause of the following exception:
...
django.db.utils.ProgrammingError: Cannot operate on a closed database.
```

## Hotfix

Commenting out `app.conf.beat_schedule = {}` or setting up tasks in it avoids this error.

## Possibly Related Issue

This issue relates to the same block of code, so this issue may have been tangentially fixed a few weeks ago ... https://github.com/celery/celery/pull/5116

**Comment by auvipy** [comment]
hopefully fixed in master. please wait for 4.3rc release
