### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' is deprecated

### ISSUE THREAD

**Issue by yuvadm** [celery/celery#5161]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Run anything that uses `celery` under Python 3.7, verified against `celery==4.2.1`

## Expected behavior
No `DeprecationWarning` should be seen

## Actual behavior
```
.../lib/python3.7/site-packages/celery/canvas.py:12
.../lib/python3.7/site-packages/celery/canvas.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableSequence, deque
```

**Comment by thedrow** [comment]
Note that the `collections.abc` module does not exist on Python 2.7.
