### ISSUE TITLE
Run single link_error task when multiple tasks in group fails

### ISSUE THREAD

**Issue by OskarPersson** [celery/celery#5166]
```python
@app.task
def failing():
    raise ValueError('oh no!')

group(failing.s(), failing.s(), link_error=on_error.s())
```

Running the group above results in the `on_error` task being called twice. How can I make it so that the task set on link_error is only called once when multiple tasks fails in a group?

**Comment by georgepsarakis** [comment]
I think you can solve this by adding a chord and attaching an error callback to that chord callback. For details see [here](http://docs.celeryproject.org/en/latest/userguide/canvas.html#error-handling).

**Comment by OskarPersson** [comment]
But then I also need a callback task, or is there a way to create a chord without it?

**Comment by georgepsarakis** [comment]
I guess you would have to create a noop task, just for this case. How does that sound?

**Comment by OskarPersson** [comment]
Sure, that works. Thanks 👍
