### ISSUE TITLE
When trying to revoke terminate real quickly to the queued tasks including running one, worker takes CPU Usage to 100% and freezes

### ISSUE THREAD

**Issue by ksodari** [celery/celery#5169]
## Checklist
- [x] The Issue exists with Latest version of celery (4.x) since I am using that as of now
- [x] There are other issues similar to this here but none of them describe what is causing it and how it is caused. 

## Steps to reproduce
Try to cancel the task by task id as 
`app.control.revoke(task_id=task_id, terminate=True, signal='SIGUSR1')`
This step needs to be done in a row with multiple tasks in the queue while a task is running.
I tried to cancel a running task and then cancel another and another and so on...
In this process, there will come a condition when the worker will go wild and freeze taking cpu usage as 100% and not taking any task further.

## Expected behavior
Task with the provided task_id should terminate and another process should run smoothly even if we terminate multiple in a row

## Actual behavior
Worker freezes and CPU Usage becomes 100% for that worker while other remaining workers just sit idle.

## Thought and Scenario
I think there is some sort of lag with the termination and prefetching of the queued task which runs right after one is terminated. I don't know the actual reason behind this and how this is happening. I am new to Celery. So, I would like to get some answers regarding this.
There are 3 workers running in my server worker instance. When the tasks are queued, one worker is active and it processes the task smoothly as intended. Only the problem arises when multiple tasks are revoked for termination in a row starting with the running one. The worker1 freezes when that happens and worker2 and worker3 just sit idle. When I manually killed the worker1 with pid the other worker processes the queued task normally and worker1 starts with new pid. This is happening frequently. I just want to know why is this happening and how to resolve this issue. 
Thanks in advance.

**Comment by auvipy** [comment]
could you share some more detail? broker, result backend, celery version? also is it possible you try all the package from github master?

**Comment by ksodari** [comment]
> could you share some more detail? broker, result backend, celery version? also is it possible you try all the package from github master?

@auvipy Did you go through the detail description I wrote above?
**Celery Version:** 4.2.1 (Latest)
**Broker:** Redis 
#redis-server
REDIS_URL = 'redis://127.0.0.1:6379'

**Cekery Config I used:**
BROKER_URL = config('REDIS_URL') + '/1'
CELERY_RESULT_BACKEND = config('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = config('TIME_ZONE')

**Comment by asheeshcric** [comment]
The same problem persists when I try to revoke multiple tasks in the queue simultaneously. The one thing that I've noticed so far is that terminating tasks that are not running and are still in the queue, cause such problem.
@ksodari @amitness Did you guys experience the same problem, or it is only me going through it?

**Comment by amitness** [comment]
![image](https://user-images.githubusercontent.com/8587189/48885435-6c812f00-ee50-11e8-8be1-9669d34fc674.png)

**Comment by ksodari** [comment]
@asheeshcric exactly the same thing is going on here with me. I hope somebody have nice explanation about this. Why is this problem happening and how can it be resolved. 

When I was searching for the solution and gave some hit and trial with solutions.
Temporary solution was to reboot the worker or kill the worker which was freezing and taking 100% CPU usage. meaning Suppose there are 3 worker as 
worker A
worker B and 
worker C
When I revoke the termination with this code here 
`app.control.revoke(task_id=task_id, terminate=True, signal='SIGUSR1')`
the worker (suppose worker A here) which was processing the task being canceled freezes with 100% CPU usage and no other queued task are processed. No new task are taken in the queue.
Now when I kill that worker A programmatically with pid which was freezing, immediately other worker B or worker C will respond to queued task and start processing. Worker A will restart again with some new pid.
This is what happening

**Comment by auvipy** [comment]
hope this is fix in 4.3 or 4.4rc2?
