### ISSUE TITLE
Support v3 of redis package

### ISSUE THREAD

**Issue by simonschmidt** [celery/celery#5178]
The python redis package has released version 3, which contains a few [backwards incompatible changes](https://github.com/andymccurdy/redis-py/blob/master/CHANGES)

I created two PRs (#5176 #5177) to restrict the version of the dependency, but I guess the long-term fix would be to adapt to the changes, hence this issue

**Comment by MeTaNoV** [comment]
just found out this incompatibility too...

**Comment by isknight** [comment]
just found out about this incompatibility too after hours of debugging.... 

For now the hotfix is not doing pip install celery[redis], but version locking redis to the previous compatible version (2.10.6 for us) until a fix is made.

**Comment by TheBlusky** [comment]
So until estimated 2019/03, redis python package cannot be updated to last version ? (this is purely an information request, and not a rhetoric criticism)

**Comment by auvipy** [comment]
it's now supported in kombu master
