### ISSUE TITLE
task.update_state(state='FAILURE') does not fails the task

### ISSUE THREAD

**Issue by ivan-usenka** [celery/celery#5179]
In the actual task I'm running spark job using spark-submit tool. The only way I have to check the failed job execution cause is by surrounding with try except and checking the subprocess output in terms of CalledProcessError and set the task state to 'FAILURE'. Seems to be that this doesn't work. 
Here is my code - in this case except block is working (I do print() there) but task still finishes with status 'SUCCESS'
```
@celery.task(name='_put_new_job_to_queue_task', bind=True)
def _put_new_job_to_queue_task(self_in, job_config, mode):
    try:
        subprocess.check_output('spark-submit test_job.py', stderr=subprocess.STDOUT, shell=True)
    except subprocess.CalledProcessError:
        self_in.update_state(state='FAILURE')
```

If I do after update_state
```
raise Ignore()
```
console says that task is ignored but at the fowler/AsyncResult(id) the actual state is 'STARTED' (sic!)

and BTW if I'm passing the error object to update_state as follows:
```
except subprocess.CalledProcessError as er:
        self.update_state(state='FAILURE', meta={'exc': er.output})
```
the task is finally failing but because of worker error
```
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: CalledProcessError() is not JSON serializable
```

Any Idea how to correctly immediately fail the task from within?

UPD: Sure I can track the output and raise a custom error, but still it looks like a workaround

**Comment by auvipy** [comment]
whats the update on the master branch?

**Comment by sibiryoff** [comment]
Just got exactly the same on 4.4.7 version, is this issue resolved?

**Comment by auvipy** [comment]
can you just try celery 5.2.0rc1 and report back plz?
