### ISSUE TITLE
Why celery cannot reload my latest codes, it used codes celery was first started.

### ISSUE THREAD

**Issue by yvonneFtMore** [celery/celery#5181]
I have used init-script to make celery daemonized. When I git pull my latest code for my project, I restart celery to reload my latest codes. It seems that sometimes is ok while sometimes is not ok. It puzzled me for days.

My celery version is 4.2.1.

**Comment by MattBlack85** [comment]
Did you check the main process is killed and then restarted? Maybe some orphaned workers? How do you restart celery? Do you have long running tasks that can go beyond the soft kill time limit?

**Comment by yvonneFtMore** [comment]
> Did you check the main process is killed and then restarted? Maybe some orphaned workers? How do you restart celery? Do you have long running tasks that can go beyond the soft kill time limit?

I just use init-script: `/etc/init.d/celeryd restart` to restart celery.

Yeah, there are two soft-time-limit tasks, but I am testing other tasks witch is not soft-time-limit.

Do you know the best way to restart celery? 

This problem made me changed the daemonize tool from supervisor into init-script. Finally,  I found it didn't fix my problem.

**Comment by MattBlack85** [comment]
Personally I use supervisord but all my task finish between 20-1000ms.
I had this problem before and the way we were workinh around this was using `kill` command and then restart when normal restart wasn't working

**Comment by yvonneFtMore** [comment]
That's crazy! At first, I thought it was cause by supervisor, so I changed it. Maybe I need to check the main process is closed. I used celery for a long time, but this problem never occurred! That's weird...
