### ISSUE TITLE
In-memory broker

### ISSUE THREAD

**Issue by vikonnikov** [celery/celery#5182]
Current version **Kombu** doesn't support transport **in-memory** and **Celery** has no broker with same name, but this transport mentioned in the many places of the latest documentation.

**Celery** and **Kombu** docs contain poor lists of available brokers and transports:

- http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html
- http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html#transport-comparison (**in-memory** transport was renamed to **cache**)

**Comment by thedrow** [comment]
The in memory backend is used only for testing.
I'm not sure what do you mean by not supported.
We're using it on our integration suite.

**Comment by thedrow** [comment]
If there's no further comment here, we're going to close this issue.
