### ISSUE TITLE
Sending unregistered task to SQS causes an infinite retry loop

### ISSUE THREAD

**Issue by pawelad** [celery/celery#5188]
## Checklist
- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

accept_content: ['json']
broker_transport_options: {
 'region': 'eu-west-1'}
broker_url: 'amqp://guest:********@localhost:5672//'
config: <decouple.AutoConfig object at 0x10dc81208>
settings: *
task_always_eager: False
task_default_queue: *
task_ignore_result: True
task_serializer: 'json'
timezone: 'UTC'
include: *
```

## Steps to reproduce
Send a unregistered task to Celery configured with SQS broker.

## Expected behavior
The task should fail _once_ with `KeyError`.

## Actual behavior
The task failed with `KeyError` but was was still in SQS with `in flight` status and was constantly being picked up by the worker, stuck in an infinite loop.

This generated over 1k events in Sentry, even though the incorrect task was sent only once, all with the same error message:

```
Received unregistered task of type KeyError('Foobar',).
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
*
```

To fix this, I had to clear the SQS queue, which worked as expected.

AWS docs in regards to 'in flight' messages (`A message is considered to be in flight after it's received from a queue by a consumer, but not yet deleted from the queue.`) helped me understand the problem (the task wasn't acknowledged back to SQS), but I'm still not sure wether this is an SQS limitation or a Celery bug.

I am aware of:
- https://github.com/celery/celery/issues/4002
- https://stackoverflow.com/questions/41300209/celery-sqs-duplication-of-tasks-sqs-visibility-timeout
- http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html?highlight=sqs#caveat

_but_, I don't use ETA/countdown/retry anywhere so I'm not sure if this is the problem / limitation.

I tried debugging this myself but I figured I might as well ask here to be sure I understand what happened and so people can search for this in the future.

**Comment by pawelad** [comment]
For obvious reasons I won't be able to do that in production / staging, but I'll try to reproduce the issue locally with Celery installed from `master`.

**Comment by auvipy** [comment]
will reopen after feedback

**Comment by drahosh** [comment]
happened to me too, found this by googling, we were using celery 4.4.1
