### ISSUE TITLE
Memory leak with time limits

### ISSUE THREAD

**Issue by glazari** [celery/celery#5200]
## Checklist

It seams I am having this issue in 2018 with celery==4.2.1.

I have tried many different things to solve my memory leak, including what was suggested by #4839

But what finally seems to have solved my problem was to remove the --time-limit from the cli command. 

There a previous isso about this in 2012 #1129 for a previous version of celery. But seeing as this solved my problem, I think the problem has returned. 

Note, my application went from predictably unreliable to predictably reliable.

## Steps to reproduce

I don't have a minimal example yet, but this seems to be related with a high volumn of tasks

Using `objgraph` library I was able to identify the following objects as part of the problem

`scheduled`
`Enter` 

Both of which where with 100k+ instances that would not be collected by the garbage collector.

The following image is of the back-reference-chain from this scheduled object. which leads back to `kombu.asynchronous.hub` module.

![chain](https://user-images.githubusercontent.com/19623477/49084169-dd03c380-f235-11e8-8256-cdb05b004f50.png)

**Comment by FelipeEmerim** [comment]
I am having the same problem, oom is killing my workers and causing me a lot of trouble. Hopefully your workaround works for me.

**Comment by auvipy** [comment]
can you try celery 4.3rc1? and possibly come up with a minimal fix?
