### ISSUE TITLE
clean up resources created by Task initialization

### ISSUE THREAD

**Issue by jayendra13** [celery/celery#5202]
To achieve things mentioned here https://github.com/celery/celery/issues/3919, I tried a different approach.
As I need a jupyter kernel per worker I am adding the code to start it at the Task initialization. So my BaseTask looks like this

    class WorkerTask(Task):
        abstract = True
        reply_futures = {}
        _kernel_manager = None
        _kernel_client = None
    
        def __del__(self):
            print('A distructor has been called')
            self.kernel_manager.shutdown_all()
    
        @property
        def kernel_manager(self):
            if self._kernel_manager is None:
                self._kernel_manager = MultiKernelManager()
            return self._kernel_manager
    
        @property
        def kernel_client(self):
            if self._kernel_client is None:
                self._kernel_client = self.start_kernel('octave')
            return self._kernel_client
    
        def start_kernel(self, language):
            # Logic to start the kernel which creates a new process when 
            # worker get started
            return kernel_client
    
        async def execute(self, code):
            msg_id = self.kernel_client.execute(code)
            # There does exist a method which fill sthe result of this future object
            # but I have omitted the irrelevant code for the sake of simplicity
            f = Future()
            self.reply_futures.update({msg_id : f})
            await f

Here is the my celery task 

    @app.task(base=WorkerTask)
    def worker_task(code):
        loop = asyncio.get_event_loop()
        loop.run_until_complete(worker_task.execute(code))

The problem with this appraoch is that when kernel exits, the jupyter kernel process created at the Task initialization doesn't get killed. Is there any hook which I can write in my `WorkerTask` to get executed when celery worker get shutdown ?

Moreover which is more preferable way to do this ?
Approach-1 : Mentioned here https://github.com/celery/celery/issues/3919
Approach-2:  Mentioned in the current thread

**Comment by auvipy** [comment]
It would be great if you could start a PR with the approach described in this issue with appropriate unit tests
