### ISSUE TITLE
"task_revoked" signal not handled

### ISSUE THREAD

**Issue by vakorol** [celery/celery#5207]
I have a long-running task:
```
from celery import Celery
celery_app = Celery( 'myapp' )
# ...
@celery_app.task()
def myTask( *args, **kwargs ) :
    # the task body
```
with a `task_revoked` handler attached:
```
from celery.signals import task_revoked

@task_revoked.connect ( sender=myTask, dispatch_uid="myTask" )
def revokeHandler( *args, request=None, **kwargs ) :
   # the handler body
```
The handler works fine, if i start a task and then revoke it normally:
```
job_uuid = myTask.delay( *args, **kwargs )
 # ...
res = AsyncResult( job_uuid )
res.revoke( terminate=True, signal='SIGKILL' )
res.forget()
```
But the handler **is not called** if i first start the task, then restart the celery worker (with the task surviving the restart), and then revoke. There is nothing in the log file (at DEBUG level) either.

I can steadily reproduce the issue with both Celery 4.1.1 and 4.2.1, using RabbitMQ server 3.2.4 as transport and Redis 2.10.5 as results backend. Python version: 3.4.3.

The version from `master` (commit  6bd31f19e0b68a5b595d8a254dac9e4cc570cccc) seems to do even worse - the signal handler doesn't work even without restarting the worker!

The worker is started with the following arguments:
```
WORKER1_ARGS="worker -A $PROJ_NAME -Q $WORKER1_NAME -Ofair --concurrency=16 --logfile=/var/log/celery/worker.log --loglevel=DEBUG"
```

<details>
<summary>
The output of 'celery -A proj report'
</summary>

software -> celery:4.1.1 (latentcall) kombu:4.2.1 py:3.4.3
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

imports: 
    ('tasks.models',
 'djcelery_email.tasks',
 'tasks.system.abortextresjobs',
 'tasks.system.addpotentialstoproject',
.... long list of tasks ....
 'tasks.subtask.mdanalysisinteraction',
 'tasks.subtask.mdanalysisrmsd')
task_default_queue: 'master'
result_backend: 'redis://localhost:6379/0'
broker_connection_max_retries: 200
task_serializer: 'pickle'
accept_content: {'pickle'}
broker_transport_options: {
 'confirm_publish': True}
broker_connection_timeout: 10
broker_url: 'amqp://viking:********@localhost:5672/master'
result_expires: None
broker_connection_retry: True
broker_pool_limit: 0
worker_send_task_events: True
task_queues: 
    (<unbound Queue master -> <unbound Exchange master(direct)> -> master>,)
task_eager_propagates: True
task_track_started: True
result_serializer: 'pickle'
</details>

**Comment by auvipy** [comment]
did you found any solution?

**Comment by vakorol** [comment]
Not really. In my case particularly, a poor man's solution can be used as a workaround:
The long-running tasks are revoked manually by the user. I could poll and wait (synchronously) until the Celery task stops, and then immediately start another Celery task that would do the stuff that the 'revoke' handler is supposed to do. But this is really something i'd like to avoid..

**Comment by auvipy** [comment]
with current master?
