### ISSUE TITLE
Stabilize the build

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5212]
The build has been failing for quite a while now.
Before releasing 4.3 we need to make sure all the tests pass.

**Comment by georgepsarakis** [comment]
@thedrow is this related to failures with Redis test cases?

**Comment by auvipy** [comment]
can we release py-amqp and vine and cyanide etc initially?

**Comment by thedrow** [comment]
> @thedrow is this related to failures with Redis test cases?

@georgepsarakis Yes. It does.

**Comment by georgepsarakis** [comment]
Thanks @thedrow, I'll try and have a look.

**Comment by auvipy** [comment]
or even a new kombu release would be great too

**Comment by xiantotikui** [comment]
https://github.com/celery/kombu/issues/962

I changed this in kombu and Celery is working.

**Comment by kcolton** [comment]
Sorry if dumb questions, am a bit new here (using for a long time, but mostly lurked on github) and trying to get up to speed quickly.

> The build has been failing for quite a while now.
Like, automated builds across everything? 4.2.1, master, and 4.3 branch or just a specific PR/branch for 4.3? (didn't see one, wasn't sure if 4.2 branch is 4.3 in disguise or there is some PR that encapsulates already)

**Comment by thedrow** [comment]
The build for master.
We need it for releasing 4.3.

**Comment by thedrow** [comment]
@georgepsarakis I just released that fix as kombu 4.2.2.
I don't have time to cherry pick all the other bugs as well.

**Comment by thedrow** [comment]
Master is passing.

**Comment by georgepsarakis** [comment]
@thedrow excellent!
