### ISSUE TITLE
Adding chains to the queue in chunks

### ISSUE THREAD

**Issue by monstermac77** [celery/celery#5214]
I need to add many tasks to the queue quickly (adding tasks to the queue is currently a bottleneck). These tasks must be organized into `chains`, which means to cut down the time to add the tasks to the queue, I need to figure out how to submit `chains` as `chunks`. Is this possible?

**Comment by ducquangkstn** [comment]
Why you closed the issue without any comments?

At least, pls say that is not possible.
`chains` is not a really task and chunks only work with a really task.

I knew both Apache spark and celery and IIRC, apache spark can resolve this in a better way b/c it is designed for parallel processing.

**Comment by auvipy** [comment]
because the issue didn't follow the formal template. I can convert this to a discussion for more feedback, or you can share more detail here so that I can reconsider opening this

**Comment by ducquangkstn** [comment]
https://github.com/celery/celery/issues/8200

**Comment by monstermac77** [comment]
@ducquangkstn thanks very much for putting it in the right format in that issue. I took a look at what you put and I _think_ that mirrors what I was asking for here, but it's been a while since I got into the weeds of our Celery application.
