### ISSUE TITLE
Can only execute a constant number of tasks. All other tasks wait. Issue: connection pool limit reset to 10 (default), intermittently at runtime

### ISSUE THREAD

**Issue by hp685** [celery/celery#5215]
Using a broker pool limit of 0 (disabling connection pooling), my application, after running for several days or a few hours, will land into a state where connection pooling gets enabled during runtime. 
Subsequently, it can only process 10 tasks at a time while all other tasks wait until these tasks finish even though I have 40+ workers running. It is potentially an issue with the resize of `Resource` (ProducerPool) instance of kombu Resource class. 

Note this doesn't always happen and is intermittently reproducible but once it lands into that state, it stays in that state until a restart is done.

## Checklist [EDIT: I initially had the config from a wrong client. This is the config of the actual issue]
software -> celery:4.1.0 (latentcall) kombu:4.0.2 py:2.7.13
            billiard:3.5.0.3 librabbitmq:1.5.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:librabbitmq results:disabled

Workers are started with autoscaling enabled and maxtasksperchild set to 1.

## Steps to reproduce
~~Intermittently send more number of tasks than the set concurrency of workers. This triggers use of autoscale feature for prefork pool.~~

## Expected behavior
Connection pool should always be at to the value specified by config
broker_pool_limit = 0  (I expect rabbitmq admin dashboard to show no pooled connections)
## Actual behavior
RabbitMQ dashboard shows 10 pooled connections even though pooling has been disabled by setting broker_pool_limit to 0

**Comment by AlexHill** [comment]
If this is just happening in prod, I think your best bet would be to log a traceback in `Resource.__init__()` and `Resource.resize()` to see where it's being called from with the wrong value.

Something like `logger.debug(''.join(traceback.format_list(traceback.extract_stack()))`

**Comment by hp685** [comment]
@AlexHill The issue is addressed partially in kombu 4.2.1 and I've created a PR for the remainder:
https://github.com/celery/kombu/pull/961

Can you please review?

**Comment by hp685** [comment]
Deciding to go with broker pool limit of 0. Letting limit values between 0 and 10 default to 10 if pool is in use.

**Comment by mbaragiola** [comment]
Hello @hp685 , did you upgrade `kombu`? I tried setting `broker_pool_limit` to 0 but no luck, still stuck with my tasks not being executed

**Comment by hp685** [comment]
@mbaragiola I ended up patching kombu 4.0.2 with changes similar to AlexHill's commit to 4.2.1. 
Are all your tasks stuck? In my case, it was only executing 10 at a time while other tasks were waiting to be picked up.

**Comment by bhuiyanmobasshir94** [comment]
@mbaragiola I got the fix with this command by adding` --pool=solo`

`celery -A prodapi worker -l info --without-gossip --without-mingle --without-heartbeat -Ofair -- pool=solo
`

**Comment by blueyed** [comment]
Same for me back then: https://github.com/celery/celery/issues/3759#issuecomment-311763355
