### ISSUE TITLE
Application Error when running celery

### ISSUE THREAD

**Issue by cjarv** [celery/celery#5233]
celery 3.1.25
reason we are using this is because we are on windows

Any attempt to run celery (even celery -V to show the version) causes issue
python.exe - Application Error
The instruction at 0x########## referenced memory at
0x#############. The required data was not placed into memory
because of an I/O error status of 0xc00000c4.

I am not actually sure how to debug this since I can't get it to do anything.

**Comment by othalla** [comment]
Can you provide the python version you're using? and your windows environment?

**Comment by cjarv** [comment]
Windows server 2012 r2 and Python 2.7.11

**Comment by cjarv** [comment]
Was there any information regarding this ticket?

**Comment by othalla** [comment]
And your python interpreter is working if you invoke it alone without any parameter?

**Comment by cjarv** [comment]
When this issue comes up anything using celery is locked until I close all python scripts and clear the heap.

**Comment by cjarv** [comment]
It hasn't happened  since I classed out my workers and added more robust exception handling along with setting the max retries on everything. however without the ability to set soft and hard timeouts on windows i can't guarantee that its not a stray process, or a server connection keeping the process open. Still investigating this.

**Comment by cjarv** [comment]
...and yes even calling trying to import celery causes this error.
