### ISSUE TITLE
Cannot get arguments of a parent task through AsyncResult

### ISSUE THREAD

**Issue by Alkalit** [celery/celery#5238]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

https://pastebin.com/bJZZcc1K

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```
    chains = (
        chain(
            login.s(),
            scrap_edit_page.signature(args=(reservation.id,)),
            american_reservate_campaign.signature(args=(reservation.id, target_time), link_error=reservate_campaign.s()),
        ) for reservation in reservations
    )

    group(chains)()

@app.task(bind=True, ignore_result=False, autoretry_for=(Exception,), retry_kwargs={'max_retries': 100}, default_retry_delay=None)
def reservate_campaign(self, uuid):

    result = AsyncResult(uuid)

    args, id, target_time = result.args
```
## Expected behavior
I expect that `result.args` will contain arguments of the parent task. But it is None instead

**Comment by Alkalit** [comment]
Here is a simpler example. 

In my project.celery.py
```
@app.task()
def returning_task(x, y):
    return x + y
```

then in django shell

```
In [1]: from project.celery import returning_task

In [2]: returning_task.delay(2,3)
Out[2]: <AsyncResult: 5ac70262-b509-4ae4-a96c-583f0fc25bc7>

In [3]: from celery.result import AsyncResult

In [4]: result = AsyncResult('5ac70262-b509-4ae4-a96c-583f0fc25bc7')

In [5]: result.args

In [6]: result.kwargs

In [7]: result.get()
Out[7]: 5

In [8]: result.args

In [9]: result.kwargs
```

Is there is any way to get arguments of a task? I mean when there is no access to the original task object.

**Comment by thedrow** [comment]
The `result_extended` setting will be added in Celery 4.3 which stores more information about the task.
