### ISSUE TITLE
AsyncResult.get() block when timeout is set to 0

### ISSUE THREAD

**Issue by wsyzxcn** [celery/celery#5240]
If get is called with timeout=0 eg. ``async_result.get(timeout=0)``, it will block until the async task is finished, and then result is returned. However, if I set ``timeout=0``, I just mean check if the result is ready for only once, if not raise Exception. Dose't it more convenient this way?

**Comment by thedrow** [comment]
The API for that usecase is `async_result.result`.
Timeout 0 is ambiguous.

**Comment by wsyzxcn** [comment]
> The API for that usecase is `async_result.result`.
> Timeout 0 is ambiguous.
But ``async_result.result``  is problematic when use redis as backend. because it just get the result key in redis without consuming the pubsub channel previously subscribed to. So after a while your redis backend will subscribe to tons of channels， causing problem to the redis server

**Comment by thedrow** [comment]
You need to forget() after you get the result then.

**Comment by wsyzxcn** [comment]
> You need to forget() after you get the result then.

I don't think forget() is gonna work, as it show in the code, forget() call just call a ``unsubscribe`` to redis server. But if the task is done, it's result has already published to  the channel, which ,if the client not consume it, will stuck in redis server's client-output-buffer, and then exceed output-buffer-limit.
Did i miss something? However this actually cause problem in my project.

**Comment by thedrow** [comment]
@georgepsarakis Maybe you can weight in here. You know the Redis broker better than I do.
