### ISSUE TITLE
head_from_fun failing if task decorated by callable class

### ISSUE THREAD

**Issue by Sovetnikov** [celery/celery#5241]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [*] I have verified that the issue exists against the `master` branch of Celery.

celery 4.2.1
python 3.7
## Steps to reproduce
Decorate task with "smart" decorator that can work on method and function as in this solution https://stackoverflow.com/a/19319626/590233.
Solution implies to return a class instance as wrapper and wait for ____get__ or ____call__ (what will be called first).

## Expected behavior
apply_async() call will work normally.

## Actual behavior
apply_async() failing because head_from_fun generates ____header__ as
definition =`
def MethodDecoratorAdapter(self, *args, **kwargs):
   return 1
`
"self" argument is redundant here.

This is a rare case but possible.
Workaround is to remove "self" from MethodDecoratorAdapter.____call__ and process it as args[0].

Failing message:
> beat_1   | Traceback (most recent call last):
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 350, in apply_async
beat_1   |     **entry.options)
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 513, in apply_async
beat_1   |     check_arguments(*(args or ()), **(kwargs or {}))
beat_1   | TypeError: MethodDecoratorAdapter() missing 1 required positional argument: 'self'
beat_1   | 
beat_1   | During handling of the above exception, another exception occurred:
beat_1   | 
beat_1   | Traceback (most recent call last):
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 241, in apply_entry
beat_1   |     result = self.apply_async(entry, producer=producer, advance=False)
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 358, in apply_async
beat_1   |     entry, exc=exc)), sys.exc_info()[2])
beat_1   |   File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 178, in reraise
beat_1   |     raise value.with_traceback(tb)
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 350, in apply_async
beat_1   |     **entry.options)
beat_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 513, in apply_async
beat_1   |     check_arguments(*(args or ()), **(kwargs or {}))
beat_1   | celery.beat.SchedulingError: Couldn't apply scheduled task РЁРµРґСѓР»РёРЅРі Р·Р°РґР°С‡: MethodDecoratorAdapter() missing 1 required positional argument: 'self'

**Comment by 3ddi** [comment]
@Sonictherocketman they don't support python 3.7 yet, so it makes sense. You should wait for celery 4.3

**Comment by auvipy** [comment]
wi reopen this after bug report with celery 4.3 or master
