### ISSUE TITLE
celery hangs 

### ISSUE THREAD

**Issue by zhouchengcom** [celery/celery#5243]
## Checklist
Celery version 4.2
When the celery node size exceeded 500, and more than 100 nodes were frequently shut down and restarted (about 20 minutes once) each time, some nodes turned into suspended state, can't consume any task. By configuring all nodes with the three parameters --without-gossip - -without-mingle --without-heartbeat , it didn't happen again.

**Comment by hp685** [comment]
Did that happen due to heartbeat timeouts?
Can you provide more information or share logs? It's hard to tell otherwise
