### ISSUE TITLE
memery leak when task has exception

### ISSUE THREAD

**Issue by Bogunzhao** [celery/celery#5249]
## Steps to reproduce
The memery can't release when the task raise exception. Here is the code:
```from celery import Celery
import time
app = Celery('tasks', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')

@app.task
def add(x, y):
    a = ' ' * 1024 *1024*100
    time.sleep(10)
    raise Exception
```
 
celery versions: 4.2.1
Start code:
`celery -A test worker -l debug -c 1`
Although I added the ` --max-tasks-per-child=3` opttion, the worker restarted, but memery still can't release completely.

**Comment by den4uk** [comment]
Yes, I observed the leak as well.
Here was my dirty fix to solve the leak:

```
import gc
import time
from celery import Celery

gc.enable()
app = Celery('tasks', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')

@app.task
def add(x, y):
    try:
        a = ' ' * 1024 *1024*100
        time.sleep(10)
        raise Exception
    except Exception:
        pass
    finally:
        gc.collect()
````

It doesn't solve the core issue, but at least it would let you carry on until a proper solution is implemented.

**Comment by auvipy** [comment]
could any of you verify this with the latest master?

**Comment by auvipy** [comment]
closing for the lack of feedback. you can try a newer version and https://stackoverflow.com/questions/141351/how-do-i-find-what-is-using-memory-in-a-python-process-in-a-production-system/61260839#61260839
