### ISSUE TITLE
Celery-v4.2.1, branch master: wrong doc info for tasks_ack_late default value

### ISSUE THREAD

**Issue by meysam81** [celery/celery#5259]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I have checked my app, the task_acks_late setting is set to False by default, but you are saying in your docs that it's set to True by default.

## Expected behavior
I think you should edit the doc for this part

## Actual behavior
The actual behavior is that the default global task_acks_late setting is set to False by default

**Comment by 007** [comment]
https://github.com/celery/celery/blob/9b39fc41998c708c6612f0c7bf4393bf48f72e9b/celery/app/defaults.py#L246 says it's `False` by default, and everywhere else it's initialized explicitly says `None` so this should override.

**Comment by huangsam** [comment]
Seems like the current docs [in master branch](https://github.com/celery/celery/blob/master/docs/userguide/configuration.rst) says that this is disabled by default:

<img width="934" alt="Screen Shot 2019-03-13 at 8 29 40 AM" src="https://user-images.githubusercontent.com/515617/54291694-333d0e00-456a-11e9-928b-88a9b0cb40b2.png">

@thedrow is there still a bug here?

**Comment by huangsam** [comment]
> [celery/celery/app/defaults.py](https://github.com/celery/celery/blob/9b39fc41998c708c6612f0c7bf4393bf48f72e9b/celery/app/defaults.py#L246)
> 
> Line 246 in [9b39fc4](/celery/celery/commit/9b39fc41998c708c6612f0c7bf4393bf48f72e9b)
> 
>  acks_late=Option(False, type='bool'), 
> says it's `False` by default, and everywhere else it's initialized explicitly says `None` so this should override.

@007 that is an interesting observation you make. I'm wondering why some values were configured as `None` instead of the same values as the global defaults in `celery/celery/app/defaults.py`. @thedrow should the other files initialize the `acks_late` value as `False` instead of `None`?

**Comment by thedrow** [comment]
They are set to None since if they are None we take the values from the configuration.

**Comment by huangsam** [comment]
Just checking back here again, but is this issue still valid or can it be closed?

**Comment by thedrow** [comment]
Master branch looks like it's already updated.
