### ISSUE TITLE
[request] autodiscover_task: print out exception if task failed to import

### ISSUE THREAD

**Issue by vanyakosmos** [celery/celery#5262]
Sometimes error might occur inside task (tasks.py in some django app) when celery tries to import it. But celery doesn't do anything about it, it just silently start up w/o any warning. 

Good candidates to place logger (probably):
- https://github.com/celery/celery/blob/master/celery/loaders/base.py#L254-L270
- https://github.com/celery/celery/blob/master/celery/loaders/base.py#L248-L251

---

After further investigation I have found [this comment](https://github.com/celery/celery/blob/master/celery/loaders/base.py#L103-L105):

> Prior to this point loggers are not yet set up properly, need to
> check responses manually and reraised exceptions if any, otherwise
> they'll be silenced, making it incredibly difficult to debug.

Maybe we can at least just print out exceptions?
```python
if debug:
  print(f"Something bad happened: {e}", file=sys.stderr)
````

**Comment by PeterBeklemishev** [comment]
>celery doesn't do anything about it, it just silently start up w/o any warning

Source of this - incorrect ImportError handling when celery tries to import tasks.
see https://github.com/celery/celery/pull/5211
