### ISSUE TITLE
ImportError: cannot import name 'App'

### ISSUE THREAD

**Issue by Ankita-Das** [celery/celery#5273]
>> File "/home/myuser/.local/lib/python3.5/site-packages/flask_celery.py", line 16, in \<module\>  

>>from celery.app import App, AppPickler, current_app as current_celery 
>>The above line gives error:  
>> ImportError: cannot import name 'App'

**Comment by alwaysused** [comment]
Hi.I think maybe you got a circular references about celery.Examining your import chain in your file would help.
