### ISSUE TITLE
Tasks are sent (created) but not executed during 24 hours

### ISSUE THREAD

**Issue by rafikmak** [celery/celery#5278]
Hello Celery team, 

Periodically and during 24 hours interval, all celery beat tasks are just sent but not received and executed. At the end of this period of inactivity (same minute 24 hours later), we get an exception. After this exception, Celey tasks work again during 24 hours exactly. Logs are given below. Have you any idea on the reason of this issue ? We are experiencing this on all our servers, but at different hours. 

You can see on the following logs that created asynchronous tasks are blocked on pending status from 2019-01-07 15:08 GMT until 2019-01-08 15:08 GMT. We get an exception on 2019-01-08 15:08 GMT, and after this tasks are executed correctly. 

Thanks for your help!

Used packages versions : 
Redis IBM bluemix service (4.0.10)
celery 4.2.1 
kombu 4.2.2
django 1.11.13

January 8th 2019, 16:08:20.423[2019-01-08 15:08:20,420: INFO/MainProcess] Received task: scout.tasks.downlink_engine[53c09e9e-facc-4c13-9dd0-83518c9998d3]   expires:[2019-01-07 15:10:00.053976+00:00]
January 8th 2019, 16:08:20.423[2019-01-08 15:08:20,423: INFO/MainProcess] Discarding revoked task: scout.tasks.downlink_engine[53c09e9e-facc-4c13-9dd0-83518c9998d3]
January 8th 2019, 16:08:20.131[2019-01-08 15:08:20,130: INFO/MainProcess] mingle: all alone
January 8th 2019, 16:08:18.971[2019-01-08 15:08:18,970: INFO/MainProcess] mingle: searching for neighbors
January 8th 2019, 16:08:18.903[2019-01-08 15:08:18,903: WARNING/MainProcess] Secure redis scheme specified (rediss) with no ssl options, defaulting to insecure SSL behaviour.
January 8th 2019, 16:08:18.900[2019-01-08 15:08:18,898: INFO/MainProcess] Connected to rediss://admin:**@sl-eu-gb-p01.dblayer.com:15946//
January 8th 2019, 16:08:18.818[2019-01-08 15:08:18,817: WARNING/MainProcess] Secure redis scheme specified (rediss) with no ssl options, defaulting to insecure SSL behaviour.
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
January 8th 2019, 16:08:18.727step.start(parent)
January 8th 2019, 16:08:18.727next(loop)
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
January 8th 2019, 16:08:18.727response = self._parser.read_response()
January 8th 2019, 16:08:18.727self._read_from_socket()
January 8th 2019, 16:08:18.727response = self._buffer.readline()
January 8th 2019, 16:08:18.727cb(*cbargs)
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/kombu/transport/redis.py", line 1065, in on_readable
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/client.py", line 2430, in parse_response
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
January 8th 2019, 16:08:18.727response = self._buffer.readline()
January 8th 2019, 16:08:18.727(e.args,))
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
January 8th 2019, 16:08:18.727c.loop(*c.loop_args())
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/kombu/transport/redis.py", line 348, in on_readable
January 8th 2019, 16:08:18.727return command(*args)
January 8th 2019, 16:08:18.727redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
January 8th 2019, 16:08:18.727response = self._parser.read_response()
January 8th 2019, 16:08:18.727OSError: Connection closed by server.
January 8th 2019, 16:08:18.727Traceback (most recent call last):
January 8th 2019, 16:08:18.727blueprint.start(self)
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/kombu/transport/redis.py", line 678, in _receive
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
January 8th 2019, 16:08:18.727(e.args,))
January 8th 2019, 16:08:18.727Traceback (most recent call last):
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
January 8th 2019, 16:08:18.727self._read_from_socket()
January 8th 2019, 16:08:18.727raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
January 8th 2019, 16:08:18.727During handling of the above exception, another exception occurred:
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/client.py", line 2419, in _execute
January 8th 2019, 16:08:18.727redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
January 8th 2019, 16:08:18.727During handling of the above exception, another exception occurred:
January 8th 2019, 16:08:18.727self.cycle.on_readable(fileno)
January 8th 2019, 16:08:18.727chan.handlers[type]()
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/kombu/transport/redis.py", line 689, in _receive_one
January 8th 2019, 16:08:18.727response = c.parse_response()
January 8th 2019, 16:08:18.727return self._execute(connection, connection.read_response)
January 8th 2019, 16:08:18.727File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 177, in _read_from_socket
January 8th 2019, 16:08:18.727ret.append(self._receive_one(c))
January 8th 2019, 16:08:18.726raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
January 8th 2019, 16:08:18.726[2019-01-08 15:08:18,721: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
January 8th 2019, 16:08:18.726Traceback (most recent call last):
January 8th 2019, 16:08:18.726File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 177, in _read_from_socket
January 8th 2019, 16:08:18.726return command(*args)
January 8th 2019, 16:08:18.726File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
January 8th 2019, 16:08:18.726Traceback (most recent call last):
January 8th 2019, 16:08:18.726OSError: Connection closed by server.
January 8th 2019, 16:08:18.726During handling of the above exception, another exception occurred:
January 8th 2019, 16:08:18.726File "/home/vcap/deps/0/python/lib/python3.6/site-packages/redis/client.py", line 2408, in _execute

January 8th 2019, 16:08:00.053[2019-01-08 15:08:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:07:00.052[2019-01-08 15:07:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:06:00.053[2019-01-08 15:06:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:05:00.057[2019-01-08 15:05:00,051: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:04:00.054[2019-01-08 15:04:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:03:00.060[2019-01-08 15:03:00,059: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:02:00.057[2019-01-08 15:02:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:01:00.056[2019-01-08 15:01:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:00:00.076[2019-01-08 15:00:00,076: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 8th 2019, 16:00:00.068[2019-01-08 15:00:00,067: INFO/Beat] Scheduler: Sending due task run-assets-extract-tasks (extractor.tasks.set_tenant_assets_extracting_tasks)
January 8th 2019, 16:00:00.053[2019-01-08 15:00:00,052: INFO/Beat] Scheduler: Sending due task check-missing-data-tasks (alerts.tasks.check_missing.check_missing_data)
January 8th 2019, 15:59:00.054[2019-01-08 14:59:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)

...

January 7th 2019, 16:16:00.055[2019-01-07 15:16:00,053: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:15:00.053[2019-01-07 15:15:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:14:00.053[2019-01-07 15:14:00,052: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:13:00.055[2019-01-07 15:13:00,053: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:12:00.053[2019-01-07 15:12:00,051: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:11:00.060[2019-01-07 15:11:00,059: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:10:00.069[2019-01-07 15:10:00,069: INFO/Beat] Scheduler: Sending due task compute-kpis (kpi.tasks.set_kpi_computing_tasks)
January 7th 2019, 16:10:00.058[2019-01-07 15:10:00,057: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:09:00.053[2019-01-07 15:09:00,051: INFO/Beat] Scheduler: Sending due task downlink-manager-tasks (scout.tasks.downlink_engine)
January 7th 2019, 16:08:00.504[2019-01-07 15:08:00,503: INFO/ForkPoolWorker-20] Task scout.tasks.downlink_engine[6010ec45-010a-4a74-9650-88f20f1a953b] succeeded in 0.4096169089898467s: None
January 7th 2019, 16:08:00.500[2019-01-07 15:08:00,499: ERROR/ForkPoolWorker-20] Command with ID `1208` has not been sent

# Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
[celery_kyu_report.txt](https://github.com/celery/celery/files/2744576/celery_kyu_report.txt)
- [x] I have included the contents of ``pip freeze`` in the issue. 
[pip_freeze.txt](https://github.com/celery/celery/files/2744587/pip_freeze.txt)

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have tried reproducing the issue on more than one message broker and/or result backend.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings

celery 4.2.1 
kombu 4.2.2
Redis IBM bluemix service (4.0.10)
django 1.11.13
Ubuntu 16.04 and 14.04
Python 3.6.5
(pip freeze attached for local copy)

# Steps to Reproduce
Reproduced periodically without a specific steps 
Example of periodical task on celery config file : 
beat_schedule = {
    'downlink-manager-tasks': {
        'task': 'scout.tasks.downlink_engine',
        'schedule': crontab(minute='*'),
        'options': dict(expires=60)
    },

**Comment by maximekl** [comment]
hi, same here some of my scheduled tasks are not executed since a range from 2 weeks.

**Comment by RomainDLS** [comment]
When experimenting this problem, the first line of log after the "not executing tasks" period is : 
`[2019-01-12 16:22:49,897: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...`

**Comment by auvipy** [comment]
whats the update on this on current master?

**Comment by RomainDLS** [comment]
It seems that it came from Redis configuration. Since we updated it, we don't have this problem anymore.

**Comment by auvipy** [comment]
hanks for the feedback
