### ISSUE TITLE
SQS MessageDeduplicationId

### ISSUE THREAD

**Issue by ikonst** [celery/celery#5281]
Is there a way to propagate a value as the SQS `MessageDeduplicationId`? Kombu supports it as a message property, but I cannot see a way to propagate it from a Celery task's enqueueing.

Also, it could potentially be propagated from a Task Id, although I'm not sure whether Task Ids being de-duped on will break the existing contract.

**Comment by ikonst** [comment]
@auvipy
```py
@app.route('/generate-report')
def generate_report():
    params = request.args
    my_celery_task.delay(params.foo, params.bar)
```
Let's assume that this "/generate-report" endpoint is called when the "Generate" button. I was trying to think up a way for a single task to be enqueued even if the user pressed the button twice (or perhaps a network retry is performed in some middleware or proxy).

Reading it again, I think I misunderstood the [SQS documentation on the matter](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html). SQS FIFO queues already perform deduping based on the content, i.e. if the content is exactly the same, the queue will dedup (within a 5-minute window) without having to provide any kind of `MessageDeduplicationId` out of band.

(Of course, if Celery's SQS backend puts e.g. the current time into the SQS message, then each message will be considered unique if we don't pass an explicit `MessageDeduplicationId`, but I didn't look into Celery's internals.)

**Comment by ant-** [comment]
@ikonst I'm looking into the same issue now. In my case, I have 2 different servers with celery workers and I'm not quite sure that FIFO queue will work for a distributed system. Could you please share your celery setup? I mean did you have a distributed system or a single server for workers?

**Comment by ikonst** [comment]
@ant- I'm no longer involved with the project that needed that set up, but we did have multiple workers. Eventually we added a separate deduplication layer based on DynamoDB.

**Comment by ant-** [comment]
> @ant- I'm no longer involved with the project that needed that set up, but we did have multiple workers. Eventually we added a separate deduplication layer based on DynamoDB.

OK, I see. Thanks.

I keep trying to find a way to pass deduplication_id to kombu...

**Comment by eugeneyalansky** [comment]
I'm also interested

**Comment by tcigrand** [comment]
I'm wondering about this and `MessageGroupId` too

**Comment by n0061q** [comment]
There is a way to pass `MessageGroupId` and `MessageDeduplicationId` to kombu as message properties.

This is how kombu handles it: 
https://github.com/celery/kombu/blob/v5.2.2/kombu/transport/SQS.py#L372-L382

By the way you can see default values for `MessageGroupId` and `MessageDeduplicationId` ('default' and generated UUID respectively).

With [`apply_async`](https://docs.celeryproject.org/en/v5.2.1/reference/celery.app.task.html#celery.app.task.Task.apply_async) one can pass any 
keyword arguments supported by `kombu.Producer.publish()`.

Then [`kombu.Producer.publish`](https://docs.celeryproject.org/projects/kombu/en/v5.2.2/userguide/producers.html#kombu.Producer.publish) uses `**properties` to pass any additional message properties (which is what we need).

Example:
```python
custom_properties = {
    'MessageGroupId': 'YourMessageGroupId',
    'MessageDeduplicationId': 'YourMessageDeduplicationId'
}
your_task.apply_async(**custom_properties)
```

Other option would be to override `_get_exec_options` in `Task` class which is used to get default options [here](https://github.com/celery/celery/blob/v5.2.1/celery/app/task.py#L547) or something along those lines.

Perhaps this is a good candidate for caveats section [in the docs](https://docs.celeryproject.org/en/stable/getting-started/backends-and-brokers/sqs.html#caveats).

**Comment by auvipy** [comment]
> Perhaps this is a good candidate for caveats section [in the docs](https://docs.celeryproject.org/en/stable/getting-started/backends-and-brokers/sqs.html#caveats).

Would you mind sending a PR to add this to the docs?

**Comment by n0061q** [comment]
@auvipy sure, I got the PR ready. Let me know if it needs more work.
