### ISSUE TITLE
wait minutes later and send task again

### ISSUE THREAD

**Issue by SilenCELIkemes** [celery/celery#5298]
when  I  receive a False through the task，I want to  wait minutes and send this task again，please add this feature in next release，thank you

**Comment by SilenCELIkemes** [comment]
if  this feature already in current release，please tell how to use it and send it's api document to me。thank you so much。

**Comment by clokep** [comment]
Can you describe your use-case a bit more? It sounds very specific (and probably capable with the current API).

**Comment by clokep** [comment]
Instead of returning `False`, you can automatically retry as part of the task: http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying

If you look down a little bit there's a `default_retry_delay` that can be customized.
