### ISSUE TITLE
docs: undocumented use of CELERY_CACHE_BACKEND in django-celery-results

### ISSUE THREAD

**Issue by salty-horse** [celery/celery#5301]
# Description

When using `django-celery-results` with the `CELERY_RESULT_BACKEND = 'django-cache'` setting, it is possible to use the `CELERY_CACHE_BACKEND` to specify a Django cache other than `default`.

This is undocumented. Furthermore, the Configuration page of the user guide [describes](http://docs.celeryproject.org/en/v4.2.0/userguide/configuration.html#std:setting-cache_backend) this setting as "no longer used", which appears to be false.

# Suggestions
Describe the use of `CELERY_CACHE_BACKEND` by `django-celery-results`.

**Comment by auvipy** [comment]
could you send pr for the changes?

**Comment by clokep** [comment]
Should this be documented in `django-celery-results`, not in Celery itself?

**Comment by salty-horse** [comment]
Ideally both, but `django-celery-results` documentation is unfortunately empty, and all the guides on how to install it are in Celery's docs, so it might as well stay in Celery.

That, and Celery's docs mention `CELERY_CACHE_BACKEND` already, which needs to be updated.

**Comment by clokep** [comment]
Oops, I didn't realize that! Sorry for the noise then! 🤐
