### ISSUE TITLE
Why there's not a classic thread pool

### ISSUE THREAD

**Issue by tinylambda** [celery/celery#5307]
We have prefork, eventlet/gevent pools, and can run worker in solo mode.

it looks like that solo-mode worker is a single thread worker, but it's not really a pool. it does not support warm shutdown correctly(all tasks in solo-mode worker will shutdown immediately but not to wait them to finish when stopping the worker, event after setting CELERY_ACKS_LATE=True)

If we can have a classic thread pool, we can use  a thread as main thread to control the pool, other threads will take the workloads.

**Comment by clokep** [comment]
I think there's a PR to add this, see #5099.

**Comment by tinylambda** [comment]
> I think there's a PR to add this, see #5099.

Cool~
