### ISSUE TITLE
does a celery task remain in the same worker when retried ?

### ISSUE THREAD

**Issue by liormaynhypr** [celery/celery#5311]
# Description
could you please try and help me understand if a task returns to the queue when retried or remains in the worker's memory?
can't say for sure that something is missing in the documentation, but i couldn't find an explanation for this or something that tells me for sure what happens in this case?
https://stackoverflow.com/questions/54387941/celery-retried-messages-remain-in-same-worker

Thanks in advance!

**Comment by clokep** [comment]
I'm fairly certain that Celery just puts the task back in the broker's queue during a retry (meaning...that no, there's no guarantee it will end up at the same worker). This also seems to match the answer given on StackOverflow.

**Comment by liormaynhypr** [comment]
@clokep 
that's what i think should happen too , but as i explained in the question - i tried and saw a different result.. (with perfect multiplier and concurrency set to 1)

**Comment by liormaynhypr** [comment]
Hey @auvipy - where is the right place for types question? i'm still searching for it's answer :)

**Comment by auvipy** [comment]
https://groups.google.com/forum/#!forum/celery-users or IRC

**Comment by liormaynhypr** [comment]
hey @auvipy  :) i know this is closed, but i found an issue explaining this , linking in here in case anyone needs.
https://github.com/celery/celery/issues/2541
