### ISSUE TITLE
Update our documentation for the new compression methods introduced in Kombu 4.3

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5328]
# Description

The new release of Kombu 4.3 introduced a few new optional compression methods.
They are currently not documented in Celery.

# Suggestions

We should document those new compression methods and instruct how to enable them.

**Comment by huangsam** [comment]
It seems like [kombu.compression](https://github.com/celery/kombu/blob/v4.3.0/kombu/compression.py) reveals the compression options available in Kombu at the moment. Where would these settings be documented? It seems like it was referenced in the [Celery release notes](https://github.com/celery/celery/blob/v4.3.0rc1/docs/whatsnew-4.3.rst) at the moment.

**Comment by huangsam** [comment]
It seems like it would need to be documented [in the README.rst](https://github.com/celery/celery/blob/v4.3.0rc1/README.rst) and [introduction.rst](https://github.com/celery/celery/blob/v4.3.0rc1/docs/getting-started/introduction.rst).

**Comment by thedrow** [comment]
https://github.com/celery/celery/blob/master/docs/userguide/calling.rst#compression - this is the right place.

**Comment by huangsam** [comment]
@thedrow I went ahead and created a PR to add compression scheme documentation at the location you pointed out.
