### ISSUE TITLE
I am working with celery 4.1.2 and also oracle as result_backend and redis as broker. 

### ISSUE THREAD

**Issue by manojmspython** [celery/celery#5339]
# Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings
**Celery version**: 

**Report**:
<details>
```
```
</details>

# Steps to Reproduce
from celery import Celery, group
from celery.utils.log import get_task_logger

app = Celery('tasks', broker='redis://localhost',
             backend="db+oracle:xxxx")

@app.task(bind=True)
def add(self,x, y):
    return x + y

@app.task(bind=True)
def multiple(self,z):
    return z * z

@app.task(bind=True)
def start(self):
    streams=[]
    for i in range(1,100):
        task = add.s(1,i)|multiple.s()
        streams.append(task)
    self.replace(group(streams))

@app.task
def check():
    result = group([start.s()]).apply_async()
    logger = get_task_logger(__name__)
    logger.info(f"id is {result.id}")

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: : N/A or Unknown

### Python Packages

<details>
```
```
</details>

### Other Dependencies

<details>
N/A
</details>

## Minimally Reproducible Test Case

<details>
```

```
</details>

# Expected Behavior
The join at the end should not timeout 

# Actual Behavior

**Comment by auvipy** [comment]
Sorry for not responding earlier. could you please check this with celery 4.3 or master?
