### ISSUE TITLE
Django fixup appends to PYTHONPATH instead of prepending

### ISSUE THREAD

**Issue by Phyks** [celery/celery#5347]
Hi,

## Environment & Settings
**Celery version**: 4.2.1  (windowlicker)

# Steps to Reproduce

We are using Celery + Django in [dissemin](https://github.com/dissemin/dissemin/). We have a Django app named "statistics" which is actually a name conflicting with a Python 3 package from standard library. This should be fine in principle as long as the `PYTHONPATH` is set so that the local modules have precedence over the system ones.

When running Celery CLI, the system wide module has precedence over the local ones apparently.

I traced this issue back to [this `sys.path` tweak](https://github.com/celery/celery/blob/072dab85261599234341cc714b0d6f0caca20f00/celery/fixups/django.py#L60-L61), which is actually **appending** local path instead of prepending it.

I may have missed something, but is it important for some reason to append it and not prepend it in this context?

# Expected Behavior

Celery should load the local module as expected.

# Actual Behavior

```
# When going through celery CLI
sys.path == ['/Users/lverney/.local/share/virtualenvs/dissemin3/bin', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python36.zip', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6/site-packages', '/Users/lverney/.local/share/virtualenvs/dissemin3/src/django-allauth', '/Users/lverney/tmp/dissemin']

# Without celery
sys.path == ['', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python36.zip', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Users/lverney/.local/share/virtualenvs/dissemin3/lib/python3.6/site-packages', '/Users/lverney/.local/share/virtualenvs/dissemin3/src/django-allauth']
```

We can see that current path is actually appended, not prepended. Therefore, "system" modules have precedence on the ones from the local project.

# Workaround

For people experiencing this issue, `PYTHONPATH=$(pwd) celery …` is a workaround.

Best,

/cc @wetneb who first noticed this issue.

**Comment by auvipy** [comment]
could you come with a possible fix?

**Comment by wetneb** [comment]
@auvipy fixing is easy - use `prepend` instead of `append`. I am more worried about the sort of testing you would expect for that kind of bug? It looks a bit hard to test to me. Happy to provide a PR otherwise.

**Comment by richkirsch** [comment]
@auvipy @wetneb 

This is throwing an error. Lists don't have 'prepend' methods.

Instead, please change `sys.path.prepend(os.getcwd())` to `sys.path.insert(0, os.getcwd())`

**Comment by wetneb** [comment]
@richkirsch yes this was my fault! This was fixed, just `git pull` again.

**Comment by clokep** [comment]
#5356 has the fix, for record keeping.

**Comment by richkirsch** [comment]
Thanks!
