### ISSUE TITLE
subprocess spawned from Celery task never terminates and proc.poll() == None status stays all the time

### ISSUE THREAD

**Issue by tianpunchh** [celery/celery#5352]
Hello, I met this issue and I have detailed description about the problem in stackoverflow, the link is below.

Basically what I find is that, I register a task under Celery, and inside the task there is a python subprocess. However, once subprocess is done and this task is done, subprocess does not terminate gracefully and leaves the process running forever 

https://stackoverflow.com/questions/54773861/subprocess-spawned-from-celery-task-never-terminates-and-proc-poll-none-sta

I appreciate your attention and help !

**Comment by thedrow** [comment]
Currently using subprocesses from tasks are not properly supported.
The patch to make it supported is non-trivial.

**Comment by tianpunchh** [comment]
@thedrow thank you
Can you suggest what should I use if I want to have this kind of subprocess call inside the celery task (for example, I want to execute some script from the celery task) ? Any alternative solutions ?

**Comment by thedrow** [comment]
You could run a Docker container.

**Comment by tianpunchh** [comment]
@thedrow Do you mean I wrap up the celery service in a docker container? I already did this. But how would this solve the problem? I mean a zombie process is still a zombie.  Sorry I am not the expert about these engineering issues, please bear with me if my question is trivial.

**Comment by thedrow** [comment]
No, I mean that you can mount the docker socket to your container and use docker-py to start another container which will execute the task and print the results back in stdout.
Other alternatives are using systemd to spawn a process and reading the results from journald.
