### ISSUE TITLE
Canvas with group-task-task-group does not work

### ISSUE THREAD

**Issue by AbdealiJK** [celery/celery#5354]
# Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included all related issues and possible duplicate issues in this issue.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have tried reproducing the issue on more than one message broker and/or result backend.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.2.1 (windowlicker)

<details>
<summary><b><code>celery report</code> Output:</b></summary>

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.4
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
settings -> transport:redis results:redis://localhost/

BROKER_URL: 'redis://localhost:6379//'
CELERY_RESULT_BACKEND: 'redis://localhost/'
BROKER_TRANSPORT_OPTIONS: {
 'visibility_timeout': 11700}
```
Tried this with RabitMQ also. Same issue exists.

</details>

# Steps to Reproduce
If I create a celery canvas with a `task - grouptask - task - task - grouptask - task`, it fails.
If I change it to `task - grouptask - task - grouptask - task`, it works

## Minimally Reproducible Test Case

```python
    @celery_app.task
    def print_task(val):
        print("Running print_task. val is: {}".format(val))

    final_task = celery.chain(
        print_task.si(val="Starter task"),
        celery.group([
            print_task.si(val='group1, task1'),
            print_task.si(val='group1, task2'),
        ]),
        print_task.si(val="group1, after-task"),
        print_task.si(val="group1, after-task2"),  # <---- commenting this makes it work
        celery.group([
            print_task.si(val='group2, task1'),
            print_task.si(val='group2, task2'),
        ]),
        print_task.si(val="FINAL task"),
    )
    r = final_task()
    print(r.get())
```

Also, when we do a `print(final_task)`, it shows:
```
print_task(val='Starter task')
| %(print_task([
		print_task(val='group1, task1'),
		print_task(val='group1, task2')
	], val='group1, after-task')
	| print_task(val='group1, after-task2')
) | %print_task([
		print_task(val='group2, task1'),
		print_task(val='group2, task2')
	], val='FINAL task')
```

## Required Dependencies

* **Minimal Python Version**: Python 3.6.4 :: Anaconda, Inc.
* **Minimal Broker Version**: Redis 4.0.9
* **Minimal Result Backend Version**: Redis 4.0.9
* **Minimal OS and/or Kernel Version**: Mac OSX 10.13, Linux CentOS7
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

I've also tried with latest git master versions of celery, kombu, amqp, redis-py, vine.

# Expected Behavior
The output should have executed the entire canvas:

```
Running print_task. val is: Starter task
Running print_task. val is: group1, task1
Running print_task. val is: group1, task2
Running print_task. val is: group1, after-task
Running print_task. val is: group1, after-task2
Running print_task. val is: group2, task1
Running print_task. val is: group2, task2
Running print_task. val is: FINAL task
```

# Actual Behavior
The tasks until `group1, after-task2` work fine. The `group1, after-task2` also completes execution according to celery logs.
```
Running print_task. val is: Starter task
Running print_task. val is: group1, task1
Running print_task. val is: group1, task2
Running print_task. val is: group1, after-task
Running print_task. val is: group1, after-task2
[2019-02-22 16:30:18,041: INFO/MainProcess] Task print_task[beaea403-5f2e-4b84-8f64-bcada7c07000] succeeded in 0.004693654947914183s: None
```

The redis-cli shows that is completed too:
```
127.0.0.1:6379> get celery-task-meta-beaea403-5f2e-4b84-8f64-bcada7c07000
"{\"status\": \"SUCCESS\", \"result\": null, \"traceback\": null, \"children\": [], \"task_id\": \"beaea403-5f2e-4b84-8f64-bcada7c07000\"}"
```
But for some reason, the `children` is empty - even though there are children.

**Comment by AbdealiJK** [comment]
I just tried changing it to:
```

    final_task = celery.chain(
        tc.print_task.si(val="Starter task"),
        celery.chord([
            tc.print_task.si(val='group1, task1'),
            tc.print_task.si(val='group1, task2'),
        ], tc.print_task.si(val="group1, after-task")),
        # tc.print_task.si(val="group1, after-task"),
        tc.print_task.si(val="group1, after-task2"),
        celery.chord([
            tc.print_task.si(val='group2, task1'),
            tc.print_task.si(val='group2, task2'),
        ], tc.print_task.si(val="FINAL task")),
    )
```
And this gave me a different structure:
```
print_task(val='Starter task')
| %(print_task([
		print_task(val='group1, task1'),
		print_task(val='group1, task2')
	], val='group1, after-task')
	| print_task(val='group1, after-task2')
	| %print_task([
			print_task(val='group2, task1'),
			print_task(val='group2, task2')
		], val='FINAL task')
)
```
And it works ...
So, I guess it's an issue with group tasks and how they are not converted to chords correctly in canvases.

**Comment by ryanhiebert** [comment]
I've come across this issue as well. With my test case looking like this, where `t` is a dummy task that print its arg.

```
@app.task
def t(arg):
    print(arg)
```

This

```python
(group([t.si('a')]) | t.si('b') | t.si('c') | group([t.si('d')])).delay()
```

Gave output of

```
[2019-08-11 04:30:23,076: WARNING/ForkPoolWorker-4] a
[2019-08-11 04:30:23,097: WARNING/ForkPoolWorker-1] b
[2019-08-11 04:30:23,122: WARNING/ForkPoolWorker-4] c
```

My workaround was to do the chain of the end, then add the first group to the beginning, like this:

```python
```

Which gave the expected result of

```
[2019-08-11 04:30:55,442: WARNING/ForkPoolWorker-1] a
[2019-08-11 04:30:55,449: WARNING/ForkPoolWorker-4] b
[2019-08-11 04:30:55,459: WARNING/ForkPoolWorker-3] c
[2019-08-11 04:30:55,477: WARNING/ForkPoolWorker-1] d
```

I may take a look into this bug more over the coming week, depending on what priorities are at work.

**Comment by AbdealiJK** [comment]
I've faced similar issues with 4.2 and 4.3

My workaround has been to always use a chord and never use a group.
When using a chord, and I don't want the task at the ending, I use a dummy
empty-task to make it look like a group.

**Comment by ryanhiebert** [comment]
Thank you for that tip, @AbdealiJK, it was a cleaner workaround for me than the other was, because of the details of my particular usage.
