### ISSUE TITLE
Celery task does not appear in queue after task.apply_async using countdown

### ISSUE THREAD

**Issue by Drau** [celery/celery#5360]
# Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have included all related issues and possible duplicate issues in this issue.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have tried reproducing the issue on more than one message broker and/or result backend.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

**ISSUE**
Working with celery 4.2.0 and Redis as broker and backend.

Having a task

```
@shared_task()
def add(a, b):
    return a+b
```
And while a worker is active, running the fallowing command:

`add.apply_async(countdown=60)
`Results in the task not being registered to the default celery queue, but still being executed after the period of time stated in countdown

Why is that, and how can I look for all pending tasks? Doing this would have worked if the task would be registered to the queue:

```
    with celery_app.pool.acquire(block=True) as conn:
        tasks = conn.default_channel.client.lrange('celery', 0, -1)
```
If I terminate the worker while task havent been started I get the fallowing:

> [WARNING/MainProcess] Restoring 1 unacknowledged message(s)

This tells me the task is kept somewhere else other then the queue, but why ?

**Comment by auvipy** [comment]
could you check this also occurs in celery==4.3rc1?

**Comment by Drau** [comment]
Sorry for the delay.
Yes it does.

Looks like the broker removes the first task from the queue even if there
is countdown , and holds it somewhere else until the right time.

**Comment by jheld** [comment]
A worker will grab it if it has room to reserve it. Depends on workers/worker config setup, but that is expected behavior.

**Comment by Drau** [comment]
Thanks @jheld, could you point me to the relevant worker configs?
Is there a way to disable workers reserving the task before its due time?

**Comment by jheld** [comment]
@Drau sure. The celery docs site is having certificate issues right now, but: https://docs.celeryproject.org/en/latest/userguide/optimizing.html?highlight=prefetch

Basically...it's possible, but not in the way you'd expect.
