### ISSUE TITLE
Option to replace billiard with multiprocessing

### ISSUE THREAD

**Issue by isaacleeai** [celery/celery#5362]
# Checklist

- [x] I have checked the issues list for similar or identical feature requests.
- [x] I have checked the commit log to find out if a feature was already implemented in master.

# Brief Summary

Instructions on how to change from using `billiard` to `multiprocessing` -- the reason is i need to use pytorch's multiprocessing library `torch.multiprocessing` which is 100% compatible with codes that use `multiprocessing`.

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
@thedrow

**Comment by thedrow** [comment]
I'm sorry but I'm 100% certain that this is not possible due to the way Celery works and is designed.
It will also be impossible in the future due to the fact that Celery will be async.
