### ISSUE TITLE
REST tasks?

### ISSUE THREAD

**Issue by andrewtmendoza** [celery/celery#5365]
In the Frequently Asked Questions topic "[Is Celery multilingual?](http://docs.celeryproject.org/en/v4.2.1/faq.html#is-celery-multilingual)", there is a paragraph that reads:

> Also, there’s another way to be language-independent, and that’s to use REST tasks, instead of your tasks being functions, they’re URLs. With this information you can even create simple web servers that enable preloading of code. Simply expose an endpoint that performs an operation, and create a task that just performs an HTTP request to that endpoint.

However, I can't find any other reference to REST tasks in the current docs. After some Googling, I found a mention to [HTTP Callback Tasks (Webhooks)](http://docs.celeryproject.org/en/2.5-archived/userguide/remote-tasks.html) in the docs for Celery v2.5. Is this feature deprecated?

**Comment by auvipy** [comment]
this is deprecated and removed. If you can support you could bring the old implementation on top of new version :)

**Comment by thedrow** [comment]
Also, flower has support for this.

I'm going to close this issue as Won't Fix for now.
