### ISSUE TITLE
Add documentation to the task_acks_on_failure_or_timeout setting

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5377]
# Description

#4970 did not include the proper documentation for the setting.

# Suggestions

We should ensure to document it's behaviour before 4.3 GA.

**Comment by huangsam** [comment]
@thedrow I submitted a PR based on the missing gaps I inferred from source code that used the `task_acks_on_failure_or_timeout` setting. I assume that the docs are built from the `celery.app.task` module so I applied my changes there.

**Comment by thedrow** [comment]
The configuration documentation is at https://github.com/celery/celery/blob/master/docs/userguide/configuration.rst.
I'll copy what you added, there.

**Comment by thedrow** [comment]
Oh, seems like this was not introduced as a setting as well.
I'm going to do so now.
