### ISSUE TITLE
Celery redis result backend error with Eventlet pool

### ISSUE THREAD

**Issue by valentin-ballester** [celery/celery#5380]
# Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included all related issues and possible duplicate issues in this issue.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery 4.2.1**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

Im using Celery with a eventlet execution pool and a redis task queue and a redis result backend but im having some trouble because i cant use AsyncResult. I isolate the problem trying to change the way i configure Celery and it is almost sure related to the Eventlet support because before that everything worked.

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

I would like to use my result backend with celery as i was before adding Eventlet to my project.

# Actual Behavior

    meta = self._get_task_meta_for(task_id)
    AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'

**Comment by auvipy** [comment]
try 4.3rc2

**Comment by thedrow** [comment]
Please include all the information we require to debug this problem. The issue template is there for a reason. 
The information you provided is not sufficient.

Due to that, I'm going to close this issue.

If you'll edit it with more information, we'll reopen.

**Comment by vermaat** [comment]
I'm having the same issue with celery==4.4.7. It only happens when my normal web app container uses eventless for Gunicorn and is trying to access the backend result. The Celery workers are running OK with eventless, so it only happens when I switch the normal app container to eventless. I will collect info and post it as a new issue later with the whole checklist.
