### ISSUE TITLE
How does celery let brokers send messages to workers?

### ISSUE THREAD

**Issue by zuoakang** [celery/celery#5381]
# Description

# Suggestions

**Comment by othalla** [comment]
@zuoakang can you provide more details regarding the issue?

**Comment by zuoakang** [comment]
@othalla Sorry for this issue, actually I want to ask how the Broker sends the tasks to the worker. I have always thought that the worker took the initiative to get the tasks in the Broker. Is this my knowledge wrong?

**Comment by othalla** [comment]
My comprehension is that celery app push tasks to the broker (redis for example) and workers pulls it from it.

Le 12 mars 2019 08:58:16 GMT+01:00, zuoakang <notifications@github.com> a écrit :
>@othalla Sorry for this issue, actually I want to ask how the Broker
>sends the tasks to the worker. I have always thought that the worker
>took the initiative to get the tasks in the Broker. Is this my
>knowledge wrong?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/celery/celery/issues/5381#issuecomment-471894197

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by zuoakang** [comment]
@othalla workers pulls it from broker instead of broker push to worker ？ It seems that this explanation is reasonable

**Comment by othalla** [comment]
I don't think that broker app can push message by itself. My mind is that worker consume events from brokers with celery/kombu library!
I let others correct me if i'm wrong.

**Comment by othalla** [comment]
@thedrow can you confirm ?
If i'm not wrong, i guess we can close it!

**Comment by thedrow** [comment]
It depends on which broker.
AMQP pushes messages according to the prefetch multiplier.
Redis has a Pub/Sub mechanism we use.
We poll from SQS since that's how it works.
