### ISSUE TITLE
Celery 4.3.0rc2 is not python 2.7 compatible

### ISSUE THREAD

**Issue by glestel** [celery/celery#5383]
Hello,

Using `celery-4.3.0rc2-py2.7` I have an exception on the file `base.py` because of  `ModuleNotFoundError` that doesn't exist in python 2.7 
```
File "/usr/local/lib/python2.7/dist-packages/celery-4.3.0rc2-py2.7.egg/celery/bin/base.py", line 285, in execute_from_commandline
     except ModuleNotFoundError as e:
 NameError: global name 'ModuleNotFoundError' is not defined

```
This was introduced with commit acd6025b7dc4db112a31020686fc8b15e1722c67 

Best regards, and thanks for the work

Guillaume

**Comment by georgepsarakis** [comment]
Nice catch! Indeed this [exception](https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError) was added in 3.6.
