### ISSUE TITLE
`task.apply_async(ignore_result=True)` does not ignore result

### ISSUE THREAD

**Issue by iwinux** [celery/celery#5398]
## Checklist

- [x] I have included the output of `celery -A proj report` in the issue.
- [x] I have included all related issues and possible duplicate issues in this issue.
- [x] I have included the contents of `pip freeze` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Related Issues and Possible Duplicates

* #4707
* #4709
* #4721

## Environment & Settings

**Celery version**: 4.3.0rc1

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
$ celery -A bug report

software -> celery:4.3.0rc1 (rhubarb) kombu:4.4.0 py:3.7.2
            billiard:3.6.0.0 redis:3.2.1
platform -> system:Linux arch:64bit
            kernel version:4.9.125-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/0

broker_url: 'redis://redis:6379/0'
result_backend: 'redis://redis:6379/0'
```

</p>
</details>

### Required Dependencies

* **Minimal Python Version**: Python 3.5
* **Minimal Broker Version**: Redis 3.0
* **Minimal Result Backend Version**: Redis 3.0
* **Minimal OS and/or Kernel Version**: Linux (Docker for Mac)
* **Minimal Broker Client Version**: redis-py 3.2.1
* **Minimal Result Backend Client Version**: redis-py 3.2.1

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.4.2               # via kombu
billiard==3.6.0.0         # via celery
celery[redis]==4.3.0rc1
kombu==4.4.0
pytz==2018.9              # via celery
redis==3.2.1              # via celery
vine==1.3.0               # via amqp
```

</p>
</details>

### Minimally Reproducible Test Case

<details>
<p>

```python
# bug/celery.py
from celery import Celery
from redis import StrictRedis

REDIS_URL = 'redis://redis:6379/0'

app = Celery(
    'bug',
    broker=REDIS_URL,
    backend=REDIS_URL,
)

redis = StrictRedis.from_url(REDIS_URL)


@app.task(ignore_result=True)
def ignore_me_A(key, value):
    redis.set(key, value)


@app.task
def ignore_me_B(key, value):
    redis.set(key, value)
    
# bug/main.py
from time import sleep, time
from .celery import ignore_me_A, ignore_me_B, redis

KEY_PATTERN = 'celery-task-meta-*'


def value_equals(key, expected):
    raw = redis.get(key)
    if raw:
        return raw.decode('utf-8') == expected
    return False


def test_task_result(task):
    assert len(list(redis.scan_iter(KEY_PATTERN))) == 0

    key = f'results/{task.name}'
    value = str(time())
    task.apply_async((key, value), ignore_result=True)

    while not value_equals(key, value):
        print(f'waiting for result of {key}')
        sleep(1.0)

    redis.delete(key)
    assert len(list(redis.scan_iter(KEY_PATTERN))) == 0
    print('result of `ignore_me_A` is not persisted')


def main():
    for key in redis.scan_iter(KEY_PATTERN):
        redis.delete(key)

    test_task_result(ignore_me_A)
    test_task_result(ignore_me_B)


if __name__ == "__main__":
    main()
```

</p>
</details>

### Expected Behavior

Start Celery worker (`celery -A bug worker`) and execute `python3 -m bug.main` - **there should be no "celery-task-meta-*" keys in Redis**, and the output should be:

```
waiting for result of results/bug.celery.ignore_me_A
...
result of `ignore_me_A` is not persisted
    
waiting for result of results/bug.celery.ignore_me_B
...
result of `ignore_me_B` is not persisted
```

### Actual Behavior

`python3 -m bug.main` exits with error:

```
waiting for result of results/bug.celery.ignore_me_A
...
result of `ignore_me_A` is not persisted
    
waiting for result of results/bug.celery.ignore_me_B
...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/bug/main.py", line 39, in <module>
    main()
  File "/src/bug/main.py", line 35, in main
    test_task_result(ignore_me_B)
  File "/src/bug/main.py", line 26, in test_task_result
    assert len(list(redis.scan_iter(KEY_PATTERN))) == 0
AssertionError
```

And `redis-cli keys *` shows:

```
1) "_kombu.binding.celery"
2) "_kombu.binding.celeryev"
3) "celery-task-meta-8406a282-ea03-439c-bc49-91a56e201860"
4) "_kombu.binding.celery.pidbox"
```

**Comment by thedrow** [comment]
Thanks for the detailed bug report.
I'll look into it.

**Comment by Fernandoize** [comment]
what about this promble, i prepare working on it

**Comment by thedrow** [comment]
I haven't had the time to deal with this yet.
If you have a solution, PRs are welcome.

**Comment by alwaysused** [comment]
The ignore_result in apply_sync ensure that the controller side doesn't send 'subscribe celery-task-meta-xxx' to redis.However there is another way to produce the key:
  the @app.task() if ignore_result is not set it's default to be false in which way after the worker finish the job(ignore_me_ B) it store the result to the key using (publish celery-task-meta-xxx).
[https://github.com/celery/celery/blob/master/celery/backends/base.py#L145](url)
So maybe it's not a bug :)

**Comment by yshaban** [comment]
Having the same issue but with rabbitmq.

**Comment by auvipy** [comment]
feel free to fix it using a failing test case

**Comment by anhzhi** [comment]
this bug also confused me a lot

ignore_result won't take effect when passed to apply_async
```
t = dispatch_task.apply_async(
    args=[...],

    # options below are useless: accepted but no effect
    store_errors_even_if_ignored=False,
    ignore_result=True,
)
```

it takes effect only when dispatch_task registed
```
@shared_task(ignore_result=True)
def dispatch_task(...):
    return NotSerializable(...)
```

when dispatch_task.apply_async called, the result and status won't return to the controller
```
t = dispatch_task.apply_async(
    args=[...],
)
>>> t.status
u'PENDING'
>>> t.result is None 
True
```

**_but_** the result can be obtained from the flower
```
>>> t.id
'341010d7-7263-4547-acdd-e22f34561e95'    

http://127.0.0.1:5555/task/341010d7-7263-4547-acdd-e22f34561e95
```

the behavior is really hard to understatnd

**Comment by auvipy** [comment]
it seems to be common for most result back ends

**Comment by davidgu** [comment]
In addition, it seems that if you have a task decorated with `@shared_task(ignore_result=True)` if you then try to call it with `my_task.apply_async(ignore_result=False)` the results will still be ignored. It seems like this flag has no effect at all.

**Comment by thedrow** [comment]
I have moved this issue to the top of the backlog.

**Comment by thedrow** [comment]
My initial investigation shows that this is covered by our unit tests:
https://github.com/celery/celery/blob/bf5b2bceffd52707bcde0fe30935182ba96e3c80/t/unit/tasks/test_tasks.py#L1394-L1402

and our integration tests:
https://github.com/celery/celery/blob/bf5b2bceffd52707bcde0fe30935182ba96e3c80/t/integration/test_tasks.py#L99-L102

Both of them pass.
This does not mean there is no bug here. It means that we haven't covered an edge case.

**Comment by thedrow** [comment]
I can confirm that the result is not ignored in redis.
Instead, `result.get()` returns None since the result is flagged as ignored.

**Comment by thedrow** [comment]
There's another reason why we missed this. The saving of the result happens asynchronously.
If we sleep for a second, it appears in Redis.

**Comment by thedrow** [comment]
Indeed the logic does not refer to ignore_result being passed when using `apply_async`.
https://github.com/celery/celery/blob/bf5b2bceffd52707bcde0fe30935182ba96e3c80/celery/app/trace.py#L320-L328
