### ISSUE TITLE
worker_process_init and solo concurrency

### ISSUE THREAD

**Issue by neg3ntropy** [celery/celery#5405]
v4.2.1

It seems to me that the `worker_process_init` signal should be emitted with the `solo` concurrency as well as `prefork`: it is a worker process initializing even if it's not a child process.

It has been a source of confusion and bugs since I usually use solo for debugging and ended up with different behavior.

If anybody else hits this, a workaround is:
```
@signals.worker_init.connect
def celery_worker_init(sender, **kwargs):
    if sender.pool_cls == "solo": 
        celery_worker_process_init(sender=None, **kwargs)
```
But it's not exaclty the same in term of signal order.

**Comment by auvipy** [comment]
if you dont mind, could you please try celery 4.3rc3?

**Comment by thedrow** [comment]
Could you explain why do you think we should call `celery_worker_process_init()` when using the solo pool?
What behaviour are you expecting?

**Comment by neg3ntropy** [comment]
@thedrow I expect uniform behavior of signals between pools. Even when not spawning a proper subprocess, the "solo" process is still a worker process that requires initialization before it can run tasks.

**Comment by thedrow** [comment]
In that case, PRs are weclome :)

**Comment by mezgerj** [comment]
I took a shot at this one in [5562](https://github.com/celery/celery/pull/5562)

**Comment by auvipy** [comment]
@neg3ntropy what issue are you facing? which version you are using?

**Comment by neg3ntropy** [comment]
this is solved, but the shutdown signal is still not being sent. Either I did not notice before or it's a regression.
