### ISSUE TITLE
celery worker fails to remove stale pidfile when run as non-privileged user

### ISSUE THREAD

**Issue by nmgeek** [celery/celery#5409]
This is bug straightforward and exists in master as well as the latest 3.1 branch.

I would think it is best to run celery workers as non-privileged users so it is surprising this bug has not been reported already.

If you have a stale pidfile, a pidfile holding the process id of a process that has already terminated, you will get this message when trying to start the worker with the following command.

Message:
```
celery beat v3.1.25 (Cipater) is starting.
ERROR: Pidfile (/path/writable/by/this/user/celery-beat.pid) already exists.
Seems we're already running? (pid: 2646)
```
Command:
```
/path/to/virtualenv/bin/celery beat --pidfile=/path/writable/by/this/user/celery-beat.pid --logfile=/path/writable/by/this/user/celery-beat.log --loglevel=INFO --app=my_app --workdir=/my_app/root
```

The bug is here: https://github.com/celery/celery/blob/master/celery/platforms.py#L202

When you try to kill a non-existent process as a non-privileged user you get errno==1, not errno.ESRCH (which evaluates to 3):

```
>>> os.kill(2646, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 1] Operation not permitted
```

So the fix is to update that line from,
```
            if exc.errno == errno.ESRCH:
```
to,
```
if exc.errno == errno.ESRCH or exc.errno == errno.EPERM:
```

I suspect you no longer publish updates to the 3.1.x version so I will plan to work around this by wrapping the "celery" script with a stale pid checker.

But please fix it in your master branch.

**Comment by nmgeek** [comment]
Here is my workaround wrapper script.
[celery-wrapper.py.txt](https://github.com/celery/celery/files/2998317/celery-wrapper.py.txt)

**Comment by auvipy** [comment]
please send a PR with the fix and test.

**Comment by thedrow** [comment]
I suspect that this is more of a deployment problem than a bug but I'm not sure yet.
Howcome the PIDfile is owned by another user?
Could it be that you've previously run Celery as root or as another user which does not have permission to the PIDfile?

**Comment by nmgeek** [comment]
The PIDfile is not owned by a different user.  The problem is that the code assumes kill() will set errno to ESRCH if the process does not exist but that only works if it is running as root.  For a non-privileged user, kill() sets errno to EPERM if that user has no such process.

**Comment by nmgeek** [comment]
PR with the fix and test submitted

**Comment by qguv** [comment]
Any update on this? The error message is annoying.

**Comment by auvipy** [comment]
this will be in master now for celery==4.4.0
