### ISSUE TITLE
Minor bug in celery utils time.py file

### ISSUE THREAD

**Issue by ajaykmr2292** [celery/celery#5411]
There is a function named remaining in the celery.utils.time.py file. In that function, I think the statement start = start.replace(tzinfo=now.tzinfo) (line 211) has to be replaced with start = start.astimezone(now.tzinfo).

I hope the expected working by using the statement (`start = start.replace(tzinfo=now.tzinfo)`) is to change the `start` variable's date and time according to the `now` variable's timezone. But the replace function in the above mentioned statement is just replacing the timezone of the `start` variable without changing the values of its date and time. I thought `astimezone` is the method required for our purpose (which converts the date and time in `start` variable to the given timezone argument).

So, I think `start = start.replace(tzinfo=now.tzinfo)` must be changed to `start = start.astimezone(now.tzinfo)`.

Please correct me incase I am wrong.

Module versions:
Python 3.5.2
celery==4.2.1
django-celery-beat==1.4.0

**Comment by thedrow** [comment]
I think that we should be calling [`make_aware()`](https://github.com/celery/celery/blob/master/celery/utils/time.py#L285) instead of doing a replace.

**Comment by ajaykmr2292** [comment]
I would like to...But was something changed in `5.0-devel` branch? I dont find that `start = start.replace(tzinfo=now.tzinfo)` line itself. So, I would like to know whether the issue is taken care of already. Else, I would issue a PR. Please let me know.

**Comment by thedrow** [comment]
`make_aware` also eventually calls `astimezone`.

**Comment by ajaykmr2292** [comment]
So, I think the bug can be resolved by just removing the following lines https://github.com/celery/celery/blob/59547c5ccb78d2f30d53cb7fedf9db147f2153c8/celery/utils/time.py#L210-L212
The reason is that even if both the `start` and `now` variables are in different timezones, the line https://github.com/celery/celery/blob/59547c5ccb78d2f30d53cb7fedf9db147f2153c8/celery/utils/time.py#L216 (subtraction of two datetimes) will take care of the timezone difference and return the time difference accordingly. 
So, I hope I dont think I need to do a PR for this minor change.

**Comment by esh-b** [comment]
So, I think the bug can be resolved by just removing the following lines https://github.com/celery/celery/blob/59547c5ccb78d2f30d53cb7fedf9db147f2153c8/celery/utils/time.py#L210-L212
The reason is that even if both the `start` and `now` variables are in different timezones, the line https://github.com/celery/celery/blob/59547c5ccb78d2f30d53cb7fedf9db147f2153c8/celery/utils/time.py#L216 (subtraction of two datetimes) will take care of the timezone difference and return the time difference accordingly. 
So, I hope I dont think I need to do a PR for this minor change.

**Comment by thedrow** [comment]
I'm quite busy with Celery 5.
If you can prove that's the case with a unit test and a contribution, go ahead and do so.

**Comment by esh-b** [comment]
Hey, I just found that in `5.0-devel` branch, the above mentioned lines have already been removed. 
https://github.com/celery/celery/blob/7ee75fa9882545bea799db97a40cc7879d35e726/celery/utils/time.py#L180-L207
So, the issue might have been taken care already. 
If the unit-test contribution is still needed, then please let me know.

**Comment by thedrow** [comment]
I think we still need this on 4.3 and I don't think there was a test added to that.

**Comment by ajaykmr2292** [comment]
hey..I can do that. Can you please tell me how to add a test and give PR? Sorry but I dont have much knowledge about unittests.

**Comment by esh-b** [comment]
Just need some clarification on the specification about scheduling:
Suppose user in America/Los_Angeles timezone schedules a task to run like this (he schedules during summer): 10:00 AM, 11th day of the month, once in 6 months.
So, what is the expected scheduling?
1. When the task runs in summer, it will run on 10:00 AM PDT time and during winter, it will run at 10:00 AM PST time. 
OR
2. It will run on 10:00 AM PDT time during summer and 9:00 AM PST (equivalent of 10:00 AM PDT) during winter.
