### ISSUE TITLE
task squence data cache?

### ISSUE THREAD

**Issue by jonyjeffry** [celery/celery#5413]
i use celery version 4.2.0 
when i copy a tasks document which define my tasks,  i don't change tasks name. then i changed celery include config, mod,after that, i run celery worker. i found worker still run tasks in the old document. i'm very confused, how can this come. is it cause by task sequence data cache?

**Comment by thedrow** [comment]
I don't understand what you are asking.
What do you mean that the worker still runs tasks in the old document?
I'm not familiar with a `task sequence data cache` as you put it.

My apologies but I don't understand you enough to help.
