### ISSUE TITLE
RPCBackend: state lost if read twice while multiple tasks are polled

### ISSUE THREAD

**Issue by lafrech** [celery/celery#5414]
# Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have included all related issues and possible duplicate issues in this issue.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings

**Celery version**: 4.3.0rc3 (rhubarb)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0rc3 (rhubarb) kombu:4.4.0 py:3.5.3
            billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Linux arch:64bit
            kernel version:4.9.0-8-amd64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc:///

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'rpc:///'
include: ['pyodhean.interface']
```

</p>
</details>

# Steps to Reproduce

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.4.2
appdirs==1.4.3
astroid==2.2.5
autopep8==1.4.3
Babel==2.6.0
billiard==3.6.0.0
-e git+ssh://git@github.com/celery/celery@e1f84b06dc812d1a4520f717948328fbae7486be#egg=celery
flake8==3.6.0
flower==0.9.3
isort==4.3.4
kombu==4.4.0
lazy-object-proxy==1.3.1
mccabe==0.6.1
nose==1.3.7
pkg-resources==0.0.0
ply==3.11
pycodestyle==2.4.0
pyflakes==2.0.0
pylint==2.3.1
Pyomo==5.5.1
pytz==2018.9
PyUtilib==5.6.3
six==1.11.0
tornado==5.1.1
typed-ast==1.3.1
vine==1.3.0
wrapt==1.10.11
```
</p>
</details>

## Minimally Reproducible Test Case

```python
import time
from celery import Celery


app = Celery(
    'test',
    backend='rpc://',
    broker='pyamqp://',
)


@app.task
def task():
    return True


task_id = task.delay()
dummy_task_id = '00000000-0000-0000-0000-000000000000'

time.sleep(1)
assert app.AsyncResult(dummy_task_id).state == 'PENDING'
assert app.AsyncResult(task_id).state == 'SUCCESS'
assert app.AsyncResult(task_id).state == 'SUCCESS'  # This fails
```

# Expected Behavior

`assert app.AsyncResult(task_id).state` should always pass

# Actual Behavior

The second `assert app.AsyncResult(task_id).state` fails.

I believe the issues resides in [`get_task_meta`](https://github.com/celery/celery/blob/master/celery/backends/rpc.py#L236):

```py
    def get_task_meta(self, task_id, backlog_limit=1000):
        buffered = self._out_of_band.pop(task_id, None)
        if buffered:
            return self._set_cache_by_message(task_id, buffered)

        # Polling and using basic_get
        latest_by_id = {}
        prev = None
        for acc in self._slurp_from_queue(task_id, self.accept, backlog_limit):
            tid = self._get_message_task_id(acc)
            prev, latest_by_id[tid] = latest_by_id.get(tid), acc
            if prev:
                # backends aren't expected to keep history,
                # so we delete everything except the most recent state.
                prev.ack()
                prev = None

        latest = latest_by_id.pop(task_id, None)
        for tid, msg in items(latest_by_id):
            self.on_out_of_band_result(tid, msg)

        if latest:
            latest.requeue()
            return self._set_cache_by_message(task_id, latest)
        else:
            # no new state, use previous
            try:
                return self._cache[task_id]
            except KeyError:
                # result probably pending.
                return {'status': states.PENDING, 'result': None}
```

When polling only task_id, the `out_of_band` buffer is never used, and `latest` is always requeued.

However, when another task is polled, the return message of the task_id task is buffered in `out_of_band` and never requeued, so it is returned correctly on the next call but then it is lost because it is popped from `out_of_band`.

I get the correct behaviour with any of those two fixes:

```py
    def on_out_of_band_result(self, task_id, message):
        if self.result_consumer:
            self.result_consumer.on_out_of_band_result(message)
        self._out_of_band[task_id] = message
        message.requeue()  # <-- requeue
```

```py
    def get_task_meta(self, task_id, backlog_limit=1000):
        buffered = self._out_of_band.pop(task_id, None)
        if buffered:
            buffered.requeue()  # <-- requeue
            return self._set_cache_by_message(task_id, buffered)
        [...]
```

This is as far as I could get. It took me a few hours to figure that out. Hopefully this report provides enough information to be helpful.

**Comment by Helumpago** [comment]
I could be misreading, but this might be addressed in [this documentation](http://docs.celeryproject.org/en/latest/userguide/tasks.html#rpc-result-backend-rabbitmq-qpid):

> The RPC result backend (rpc://) is special as it doesn’t actually store the states, but rather sends them as messages. This is an important difference as it means that a result can only be retrieved once, and only by the client that initiated the task.

**Comment by auvipy** [comment]
can you send the docs improvement PR?

**Comment by thedrow** [comment]
RPC results are meant to be consumed once.

**Comment by lafrech** [comment]
Thanks for answering.
I think I was mislead by the fact that it happens to work when only one task is polled, thanks to the `requeue`.
My patch "fixed" it for me, but it may be totally shortsighted. Looks like I should be using another backend in the first place.
I saw the warning in the docs but didn't really get the meaning and the implications. My bad. Sorry for the noise.

**Comment by lafrech** [comment]
@auvipy, not sure who you're asking to. I don't think I can send a doc improvement PR. Obviously, the whole thing is a bit too blurry to me.

(But I'll be happy to read the new wording to get a better understanding !)

**Comment by Helumpago** [comment]
Re @auvipy:

> can you send the docs improvement PR?

The quote I used above is taken directly from the current documentation. I personally do not think it needs much clarification, I was providing it here to see if it would help @lafrech. If anyone has any suggestions for improvements, I'm happy to help write it up. Thanks.

**Comment by thedrow** [comment]
In my opinion the documentation clearly specifies that this behaviour is expected.
If anyone can think on a way to improve the documentation, we will reopen.
