### ISSUE TITLE
DeprecationWarning with python 3.6.7

### ISSUE THREAD

**Issue by elnikej** [celery/celery#5421]
Hello,

after changing with django + celery to python 3.6.7 I get a DeprecationWarning for
../celery/utils/imports.py:

kind regards Jens

- [x ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included all related issues and possible duplicate issues in this issue.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

<details>
<p>

```python 3.6.7
```
problem is not visible with pyhton3.5.x
same output for celery 4.3.rc2 or 4.2.1

</p>
</details>

# Expected Behavior
no Deprecation Warning for python 3.6.7 like before in python 3.5

# Actual Behavior
Output of `/venvdir/dev367/bin/python -Wd manage.py runserver 0.0.0.0:8000` :
`/venvdir/dev367/lib/python3.6/site-packages/celery/utils/imports.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp as _imp`

`/venvdir/dev367/bin/celery -A client report                                                                      
software -> celery:4.3.0rc2 (rhubarb) kombu:4.4.0 py:3.6.7
            billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Linux arch:64bit, ELF
            kernel version:4.14.92-boot2docker imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:django-db`

**Comment by auvipy** [comment]
could you try celery 4.3 stable release?

**Comment by thedrow** [comment]
I'm pretty sure this is resolved in 4.3 GA.
See https://github.com/celery/celery/commit/4c6c609273dedc75ef4af9f4fa402e4de6a9344b
If that's not the case, please comment and I'll reopen.
