### ISSUE TITLE
client_recent_max_output_buffer continue to increase

### ISSUE THREAD

**Issue by ppdollhhh** [celery/celery#5424]
I use celery as MQ for a project about face recognization. 

I have three task queues task_gpu0、task_gpu1、task_download to provide service for gunicorn flask server, which use redis as broker and backend.

When I use jemter to stress the server, after about 20 min, the program raise a exception:
OperationalError: Error 104 while writing to socket. Connection reset by peer.

Then checking redis log,I find client_recent_max_output_buffer continue to increase in info clients.But when I check the key-value by redis desktop manager,  the result is ok.

I don't know why the redis output buffer continue to increase, which is a hidden trouble.

redis log:15:M 01 Apr 2019 09:11:18.113 # Client id=58081 addr=172.16.3.22:33832 fd=54 name= age=428 idle=0 flags=P db=1 sub=74995 psub=0 multi=-1 qbuf=79 qbuf-free=32689 obl=0 oll=452 omem=9267808 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.

**Comment by ppdollhhh** [comment]
my celery config:

result_serializer = 'msgpack'
task_serializer = 'msgpack'
accept_content = ['json', 'msgpack']
broker_url = "redis://:redis@172.16.3.22:7369/1"
result_backend = "redis://:redis@172.16.3.22:7369/1"
worker_concurrency = 8
task_queues = (
    Queue('gpu_0', exchange=Exchange('gpu_0'), routing_key='gpu_0'),
    Queue('gpu_1', exchange=Exchange('gpu_1'), routing_key='gpu_1'),
    Queue('download', exchange=Exchange('download'), routing_key='download'),
)

task_routes = {
                'celery_app_tmp.task0.faceRec': {'queue': 'gpu_0', 'routing_key': 'gpu_0'},
                'celery_app_tmp.task1.faceRec': {'queue': 'gpu_1', 'routing_key': 'gpu_1'},
                'celery_app_tmp.task0.featureExtract': {'queue': 'gpu_0', 'routing_key': 'gpu_0'},
                'celery_app_tmp.task1.featureExtract': {'queue': 'gpu_1', 'routing_key': 'gpu_1'},
                'celery_app_tmp.task_download.download': {'queue': 'download', 'routing_key': 'download'},
                'celery_app_tmp.task_download.delFile': {'queue': 'download', 'routing_key': 'download'}
}

**Comment by thedrow** [comment]
Please avoid reporting bugs without our template.
You may file a new issue with all the information provided in it.

**Comment by ppdollhhh** [comment]
info clients:
connected_clients:587
client_recent_max_input_buffer:4
client_recent_max_output_buffer:55524832
blocked_clients:2
