### ISSUE TITLE
How to use Django wsgi with celery without no external worker/cache backend

### ISSUE THREAD

**Issue by aslkolkata** [celery/celery#5429]
# Description
Django integration is present in this repo. But not clearly documented.

Need a Simple Django with celery integration that can run as WSGI application, without any external message broker. 

Use of django-celery-result is not found, and django-celery is out dated.

Any alternative like django-celery with latest django and celery.

# Suggestions
Please add a Django example to use Django default cache and db back-end for celery that will help for the user developing micro service using, sample example must not use any external message broker and can run as WSGI application with out any additional command.

**Comment by thedrow** [comment]
There's no need for Celery without a message broker.

The "memory" broker is used only for testing and we do not support embedding Celery in an existing process for now and probably for ever.

The name of the package is [`django-celery-results`](https://github.com/celery/django-celery-results) as specified in it's documentation.
