### ISSUE TITLE
Fix Windows Build

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5430]
Following the release of vine 5.0.0a1 and py-amqp 5.0.0a1 the AppVeyor build started failing.

This happened since we were using `python setup.py test` in that environment instead of tox.
That command installs dependencies using `easy_install` which apparently does not implement [PEP-440](https://www.python.org/dev/peps/pep-0440/). Therefore, it picks the latest available version although it is an alpha version unlike pip which requires the `--pre` option to install alpha versions.

An attempt was made to migrate that build environment to tox, but tox installs our extra dependencies such as pycurl which does not release wheels for Windows.

We can either:

- Create a tox environment for Windows which avoids installing any extras.
- Work our way to resolve each and every build issue of our dependencies.

In addition we don't test all our supported versions on Windows.

**Comment by Igonato** [comment]
> pycurl which does not release wheels for Windows.
It does, but not each version for each python Python... It's kind of weird,
it's no longer available for 7.43.0.2 and that's what breaks the build. Maybe the hard requirement from 47d3ef152cb22ba1291d1935235e88d1fb2e5634 should now be reverted?

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/6104#event-3345741416
