### ISSUE TITLE
celery.get() interval argument can't be set lower than default (500ms) in 4.3.0 

### ISSUE THREAD

**Issue by dwappu** [celery/celery#5445]
I noticed the issue when I re-deployed my application and by default it downloaded the latest version of celery (4.3.0). 

When deploying my application with 4.3.0 the response time from redis is at least 500ms which previously was lower as we set interval to 0.001.

```
celery==4.3.0
librabbitmq==2.0.0
redis==3.2.1

celery.get(interval=0.001) # response time from redis remains at 500ms
```

```
celery==4.2.1
librabbitmq==2.0.0
redis==2.10.6

celery.get(interval=0.001) # response time from redis avg below 10ms
```

**Comment by thedrow** [comment]
Please use our bug reporting template.
It's there for a reason.
