### ISSUE TITLE
celery.get() interval argument can't be set lower than default (500ms) in 4.3.0

### ISSUE THREAD

**Issue by dwappu** [celery/celery#5446]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6
* **Minimal Celery Version**: 4.3
* **Minimal Kombu Version**: 4.5.0
* **Minimal Broker Version**: rabbitmq 3.7.13
* **Minimal Result Backend Version**: redis 3.2.10
* **Minimal OS and/or Kernel Version**: python 3.6 docker image
* **Minimal Broker Client Version**: librabbitmq 2.0.0
* **Minimal Result Backend Client Version**: redis 3.2.1

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

Initially the application is using the below version of python libraries celery, librabbitmq and redis.

celery==4.2.1
librabbitmq==2.0.0
redis==2.10.6

celery.get(interval=0.001) # response time from redis avg below 10ms

After re-deployment the 3 dependencies above were updated to their latest version and eventually the celery.get(interval=0.001) is not working and it's defaulting to 500ms

celery==4.3.0
librabbitmq==2.0.0
redis==3.2.1

celery.get(interval=0.001) # response time from redis avg 500ms

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Setting interval= 0.001 should decrease the number of waiting time to extract results from redis backend

# Actual Behavior

The waiting time always defaults to 500ms even if interval is changes to a lower number

**Comment by mezgerj** [comment]
It's [documented](https://docs.celeryproject.org/en/latest/_modules/celery/result.html#AsyncResult.get) that the Redis result backend don't use polling and that the interval argument has no effect. You can try using CELERY_DISABLE_RATE_LIMITS=True as noted in a similar issue raised [here](https://github.com/celery/kombu/issues/94) .
