### ISSUE TITLE
vine version is now 5+ but this release is supposed to be Python 2.7 compatible

### ISSUE THREAD

**Issue by aJetHorn** [celery/celery#5448]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.3

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

no import errors

# Actual Behavior
This release is supposed to be Python 2.7 compatible, but the most recent release of vine is 5+, which is Python 3. This breaks the build. I believe the vine version should be pinned to pre v5. I was able to fix it by doing this.

Defined to only use vine 5 in requirements.txt:

```
pytz>dev
billiard>=3.6.0,<4.0
kombu>=4.5.0,<5.0
vine>=5.0.0a1
```

```
File "/opt/buildagent/work/b2a7d77aec4cc7de/tmp/env/virtualenv/lib/python2.7/site-packages/vine-5.0.0a1-py2.7.egg/vine/abstract.py", line 8
[11:44:54]W:     [Step 2/2]     class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover
[11:44:54]W:     [Step 2/2]                                       ^
[11:44:54]W:     [Step 2/2] SyntaxError: invalid syntax
```

**Comment by auvipy** [comment]
vine 5 shouldn't be used with celery 4.3

**Comment by georgepsarakis** [comment]
[vine 5.0.0a1](https://github.com/celery/vine/tree/v5.0.0a1) is not yet released in PyPI. New installations would only break if it was released, since [vine is a py-amqp dependency](https://github.com/celery/py-amqp/blob/master/requirements/default.txt) and versions greater than 1.1.3 are specified as valid.

@aJetHorn can you please describe your installation steps?

**Comment by aJetHorn** [comment]
@georgepsarakis I see that I was looking at the master branch for that requirements.txt rather than the tagged version. On closer inspection, it seems that this project I am working on pulls from a dev version of pypi, which is why I got that version of vine. Sorry for the false alarm, was investigating a build of a large legacy project for pretty much the first time.

**Comment by georgepsarakis** [comment]
No worries @aJetHorn , glad you resolved it!

**Comment by thedrow** [comment]
> [vine 5.0.0a1](https://github.com/celery/vine/tree/v5.0.0a1) is not yet released in PyPI. New installations would only break if it was released, since [vine is a py-amqp dependency](https://github.com/celery/py-amqp/blob/master/requirements/default.txt) and versions greater than 1.1.3 are specified as valid.
> 
> @aJetHorn can you please describe your installation steps?

It is on PyPi but pip won't install it anyway since it's a pre-release.
