### ISSUE TITLE
drop billiard from celery 5.x

### ISSUE THREAD

**Issue by dulmandakh** [celery/celery#5449]
# Brief Summary
 
Celery 5.x is going to support Python 3.x only, and it might be appropriate to drop billiard and use multiprocessing from python 3 directly, as billiard is fork of multiprocessing module. It would a lot less code to maintain.

**Comment by thedrow** [comment]
Thanks for your interest in Celery. You are absolutely correct and it's something we already thought of.
Closing as a duplicate of #4407.
