### ISSUE TITLE
HTTPS broken on documentation website (invalid common name)

### ISSUE THREAD

**Issue by wjdp** [celery/celery#5453]
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

Google links to the HTTPS version of the website

![image](https://user-images.githubusercontent.com/1690934/55884807-a012ea80-5ba0-11e9-8a12-82879efc4346.png)

Which gets you a nice big 

![image](https://user-images.githubusercontent.com/1690934/55884844-b456e780-5ba0-11e9-9fde-8d50ff35467d.png)

Chrome is a little clearer, seems to be RTFD has given you the wrong cert:

![image](https://user-images.githubusercontent.com/1690934/55884905-d2bce300-5ba0-11e9-890f-f882be5640c1.png)

**Comment by wjdp** [comment]
This also affects the search function on the site, all search result links here are HTTPS.

**Comment by auvipy** [comment]
this is a duplicatr of ceeryproject site repo issue. thanks for reporting anyway
