### ISSUE TITLE
Task is executed more than once concurrently, either because of on_after_finalize signal or child processes of worker?

### ISSUE THREAD

**Issue by sandeepkumarmunige** [celery/celery#5459]
I have a task which runs with signal `on_after_finalize` as below

@app.on_after_finalize.connect
def get_abc(sender, **kwargs):
	print('get_flow_schema is running -->{}'.format(datetime.now()))

I have noticed that some of the times this is executed more than once by the concurrent processes of the worker. Using the default prefork pool, it has concurrency till 8. The logs are as below for the task. 

![image](https://user-images.githubusercontent.com/3057466/55957139-2e5f9d00-5c83-11e9-97da-df200b8f2527.png)

The same works well when the other signals of worker like celeryd_init and celeryd_after_setup are used (task runs only once).  Also when the concurrency is set to 1, it runs once as expected, but don't want to limit concurrent processes. Is this an issue with `on_after_finalize` signal or worker running in `prefork` pool?

Note: This is not always happening in every worker setup

**Comment by auvipy** [comment]
could you elaborate your celery setup and problems in more detail?

**Comment by sandeepkumarmunige** [comment]
Celery worker is running in a Debian stretch based docker container, with RabbitMQ broker topic exchange. Celery app is defined along with a django project which also uses django celery beat. 
In celery app setup, defined a task with decorator `on_after_finalize` 
```
app = Celery('project_name', include = ['django_app.tasks'])

@app.on_after_finalize.connect
def get_abc(sender, **kwargs):
    print('get_flow_schema is running -->{}'.format(datetime.now()))
```
running celery worker 
`celery worker --app=django_project.celeryapp:app --hostname=django_web_host`
It is using default `prefork` pool and running 8 concurrent processes for single worker. On running the worker, it is seen that the task `get_abc` is running multiple times by the concurrent workers sometimes (not always). when the concurrency is set to 1, it runs only once.

Using other signals celeryd_init and celeryd_after_setup  instead of on_after_finalize, is working fine. 

Is this an issue with signal `on_after_finalize` or  with `prefork` pool?

**Comment by auvipy** [comment]
post your support questions to mailing list or IRC first
