### ISSUE TITLE
(Django) Celery fails with weird error if KeyError exception in settings.py

### ISSUE THREAD

**Issue by python273** [celery/celery#5463]
# Checklist

- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.2.1 (windowlicker)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
... traceback removed ...
KeyError: 'test'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
# settings.py
raise KeyError('test')
```

</p>
</details>

# Expected Behavior

Traceback with `KeyError: 'test'`

# Actual Behavior

Actual traceback when running `celery -A proj beat -l DEBUG`:
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/celery/utils/collections.py", line 134, in __getattr__
   return self[k]
 File "/usr/local/lib/python3.6/dist-packages/celery/utils/collections.py", line 442, in __getitem__
   return self.__missing__(key)
 File "/usr/local/lib/python3.6/dist-packages/celery/utils/collections.py", line 275, in __missing__
   raise KeyError(key)
KeyError: 'beat_schedule_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/bin/celery", line 11, in <module>
   sys.exit(main())
 File "/usr/local/lib/python3.6/dist-packages/celery/__main__.py", line 16, in main
   _main()
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 322, in main
   cmd.execute_from_commandline(argv)
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
   super(CeleryCommand, self).execute_from_commandline(argv)))
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 298, in execute_from_commandline
   return self.handle_argv(self.prog_name, argv[1:])
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 488, in handle_argv
   return self.execute(command, argv)
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 420, in execute
   ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 302, in run_from_argv
   sys.argv if argv is None else argv, command)
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 385, in handle_argv
   *self.parse_options(prog_name, argv, command))
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 421, in parse_options
   self.parser = self.create_parser(prog_name, command)
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 437, in create_parser
   self.add_arguments(parser)
 File "/usr/local/lib/python3.6/dist-packages/celery/bin/beat.py", line 116, in add_arguments
   '-s', '--schedule', default=c.beat_schedule_filename)
 File "/usr/local/lib/python3.6/dist-packages/celery/utils/collections.py", line 138, in __getattr__
   type(self).__name__, k))
AttributeError: 'Settings' object has no attribute 'beat_schedule_filename'
```

**Comment by auvipy** [comment]
could you try celery 4.3 and updated Django integration packages and your settings properly?

**Comment by python273** [comment]
The same error on 4.3.0:
```
AttributeError: 'Settings' object has no attribute 'beat_schedule_filename'
```

Just to be clear I already fixed it and the point of issue is that the error is confusing when `KeyError` happens in `settings.py` file

Here's similar stackoverflow question (I couldn't find it since the error was happening only for `beat`, so took some time to notice):
https://stackoverflow.com/questions/40915735/start-celery-worker-throws-no-attribute-worker-state-db

**Comment by auvipy** [comment]
configure django-celery-beat properly. if can;t post on mailing list.
