### ISSUE TITLE
The beat_schedule parameter of the celery beat module needs to add the callback parameter function 

### ISSUE THREAD

**Issue by vallee11** [celery/celery#5466]
# Checklist

- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

A. Implementation
> 

    class BeatCallBacl(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        LOG.info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret

	class Scheduler(object):
    	def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBacl) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBacl) else v for k, v in entry.kwargs.items()}
	            LOG.info(entry_args)
	            LOG.info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

B. Instructions

>
	beat_schedule = {
	    'gen_course_records-every-5-minutes': {
	        'task': 'test',
	        'schedule': 300,
	        'kwargs': {
	            "current": BeatCallBack(datetime.datetime.now)
	        }
	    }
	}

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by vallee11** [comment]
> 

    class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret


	class Scheduler(object):
    	def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by vallee11** [comment]
> 

    class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret

> 

	class Scheduler(object):
    	def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by vallee11** [comment]
> 

    class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret

> 

    class Scheduler(object):
    	def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by vallee11** [comment]
>     class BeatCallBack(object):
> 	    def __init__(self, func, *args, **kwargs):
> 	        self._func = func
> 	        self._func_params = {
> 	            "args": args,
> 	            "kwargs": kwargs
> 	        }
> 	
> 	    def __call__(self):
> 	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
> 	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
> 	        return ret
> 
> 
> 
> 	class Scheduler(object):
> 		def apply_async(self, entry, producer=None, advance=True, **kwargs):
>         	# Update time-stamps and run counts before we actually execute,
>         	# so we have that done if an exception is raised (doesn't schedule
>         	# forever.)
> 	        entry = self.reserve(entry) if advance else entry
> 	        task = self.app.tasks.get(entry.task)
> 	
> 	        try:
> 	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
> 	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
> 	            info(entry_args)
> 	            info(entry_kwargs)
> 	            if task:
> 	                return task.apply_async(entry_args, entry_kwargs,
> 	                                        producer=producer,
> 	                                        **entry.options)
> 	            else:
> 	                return self.send_task(entry.task, entry_args, entry_kwargs,
> 	                                      producer=producer,
> 	                                      **entry.options)
> 	        except Exception as exc:  # pylint: disable=broad-except
> 	            reraise(SchedulingError, SchedulingError(
> 	                "Couldn't apply scheduled task {0.name}: {exc}".format(
> 	                    entry, exc=exc)), sys.exc_info()[2])
> 	        finally:
> 	            self._tasks_since_sync += 1
> 	            if self.should_sync():
> 	                self._do_sync()

**Comment by vallee11** [comment]
class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret



	class Scheduler(object):
		def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by vallee11** [comment]
class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret



	class Scheduler(object):
		def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by vallee11** [comment]
class BeatCallBack(object):
	    def __init__(self, func, *args, **kwargs):
	        self._func = func
	        self._func_params = {
	            "args": args,
	            "kwargs": kwargs
	        }
	
	    def __call__(self):
	        ret = self._func(*self._func_params["args"], **self._func_params["kwargs"])
	        info("beat call: {}, ret:{}".format(self._func.__name__, ret))
	        return ret



	class Scheduler(object):
        def apply_async(self, entry, producer=None, advance=True, **kwargs):
        	# Update time-stamps and run counts before we actually execute,
        	# so we have that done if an exception is raised (doesn't schedule
        	# forever.)
	        entry = self.reserve(entry) if advance else entry
	        task = self.app.tasks.get(entry.task)
	
	        try:
	            entry_args = [v() if isinstance(v, BeatCallBack) else v for v in entry.args]
	            entry_kwargs = {k: v() if isinstance(v, BeatCallBack) else v for k, v in entry.kwargs.items()}
	            info(entry_args)
	            info(entry_kwargs)
	            if task:
	                return task.apply_async(entry_args, entry_kwargs,
	                                        producer=producer,
	                                        **entry.options)
	            else:
	                return self.send_task(entry.task, entry_args, entry_kwargs,
	                                      producer=producer,
	                                      **entry.options)
	        except Exception as exc:  # pylint: disable=broad-except
	            reraise(SchedulingError, SchedulingError(
	                "Couldn't apply scheduled task {0.name}: {exc}".format(
	                    entry, exc=exc)), sys.exc_info()[2])
	        finally:
	            self._tasks_since_sync += 1
	            if self.should_sync():
	                self._do_sync()

**Comment by auvipy** [comment]
can you come with a PR with proper testcase?

**Comment by vallee11** [comment]
> can you come with a PR with proper testcase?

which branch could I commit to？

**Comment by auvipy** [comment]
master

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/5558
