### ISSUE TITLE
Task's `update_state` calls `store_result` without the request object

### ISSUE THREAD

**Issue by adimux** [celery/celery#5470]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

https://github.com/celery/celery/issues/5100

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.3.0

<details>
<summary><b><code>
celery -A proj report
</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:2.7.12
            billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Linux arch:64bit, ELF
            kernel version:4.15.0-47-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 2.7
* **Minimal Celery Version**: 4.0.1 (added support for task request)
* **Minimal Kombu Version**: N/A
* **Minimal Broker Version**: N/A
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: N/A
* **Minimal Broker Client Version**: N/A
* **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
Relevant dependencies:
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery==4.3.0
kombu==4.5.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
I was trying to create a new back-end that stored the results of tasks in a different place depending on the tenant for which the task was started, which worked initially, but when I used `update_state` in one of my tasks, my back-end failed because `request` was not present among the arguments.

This is a dummy implementation of the back-end:
`multi_tenant_backend.py`
```python
from collections import defaultdict

class MultiTenantBackend(BaseBackend):
    def __init__(self, *args, **kwargs):
        super(BaseBackend, self).__init__(*args, **kwargs)
        self.store = defaultdict(dict)

    def store_result(self, task_id, result, state, traceback=None, request=None, **kwargs):
        tenant = request.get("_tenant")
        self.store[tenant][task_id] = (result, state)

    def ensure_chords_allowed(self):
        pass

    def as_uri(self, *args, **kwargs):
        return None

    def get_state(self, task_id):
        return None

    def get_status(self, task_id):
        return None

    def get_result(self, task_id):
        return None

    def get_traceback(self, task_id):
        return None

    def _get_task_meta_for(self, task_id):
        return {}

    def wait_for(self, *args, **kwargs):
        pass
```
`tasks.py`
```python
@celery_app.task(bind=True)
def do_something(task):
    sleep(3)
    task.update_state(state="DOING_SOMETHING")
```

</p>
</details>

# Expected Behavior

I would expect the back-end's `store_result` method to be called with the task's `request` as an argument when calling `task.update_state(state=..., meta=...)`.

# Actual Behavior

Calling `update_state` fails, because the back-end's `store_result` method is called without the task's `request` which is used by the back-end to retrieve information.
```
Traceback (most recent call last):
worker_1_e608e69813d9 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 385, in trace_task
worker_1_e608e69813d9 |     R = retval = fun(*args, **kwargs)
worker_1_e608e69813d9 |   File "/data/alaya/api/common/celery_app.py", line 113, in __call__
worker_1_e608e69813d9 |     return super(RequestContextTask, self).__call__(*args, **kwargs)
worker_1_e608e69813d9 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
worker_1_e608e69813d9 |     return self.run(*args, **kwargs)
worker_1_e608e69813d9 |   File "/data/alaya/api/scheduleoptimization/alns/core/alns.py", line 70, in do_something
worker_1_e608e69813d9 |     "some": "metadata",
worker_1_e608e69813d9 |   File "/data/alaya/api/common/celery_app.py", line 140, in update_state
worker_1_e608e69813d9 |     super(RequestContextTask, self).update_state(request=request, **args)
worker_1_e608e69813d9 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 930, in update_state
worker_1_e608e69813d9 |     self.backend.store_result(task_id, meta, state, **kwargs)
worker_1_e608e69813d9 |   File "/data/alaya/api/common/multi_tenant_backend.py", line 51, in store_result
worker_1_e608e69813d9 |     tenant = request.get('_tenant')
worker_1_e608e69813d9 | AttributeError: 'NoneType' object has no attribute 'get'
```

Of course, I can solve the issue by passing `task.request` when calling `update_state`, but I don't want to bother doing that just because my back-end depends on it. I could do it in a custom `Task` class, but I'd prefer if it was the default behavior of `celery`.

A potential fix is to default to passing the task's request here https://github.com/celery/celery/blob/master/celery/app/task.py#L919 when it's not present, the same as we are doing with `task_id` (i.e `if task_id is None: task_id = self.request.id`.

That said, maybe I am missing something and the reason why the `request ` is not passed by default is because the `request` is not available in some special cases.

**Comment by auvipy** [comment]
could you send a pr with the appropriate test?

**Comment by adimux** [comment]
Do you mean a fix for this issue?

**Comment by adimux** [comment]
Here is the PR https://github.com/celery/celery/pull/5474
