### ISSUE TITLE
Prevent tasks overlapping per worker (useful for simple, single-worker deployments)

### ISSUE THREAD

**Issue by ciarancourtney** [celery/celery#5471]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

Forgive me if this is already trivially possible, but the [docs](http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time) suggest it isn't.

For the simplest case, it would be nice to have an option to not allow tasks to overlap per worker i.e. where by _simplest case_ I mean a single instance with one worker running _Periodic Tasks_ for example (non-distributed)

# Design

## Architectural Considerations

Current behavior would remain default

## Proposed Behavior

Each worker checks if the task is already running on itself. Exponential backoff comes free?

## Proposed UI/UX

* Checkbox on django-celery-beat admin maybe?

## Diagrams

N/A

## Alternatives

Implement locking as per http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time, a heavy burden compared to the proposal.

**Comment by auvipy** [comment]
should this move to django-celery-beat repo?

**Comment by matteius** [comment]
@ciarancourtney You really need to use a lock construct that would be outside the scope of this Celery library -- for example, if you are using the Redis backend then you could also use Redis to set and expire a lock -- I wrote a decorator for my company that does such a thing.   See this redis command is the simplest one command way to utilize Redis to produce a simple lock construct:  https://redis.io/commands/setnx

The problem of providing it here is that we support multiple backends, and so while it would be trivial to add for Redis, if you relied only on Rabbit MQ you would not be able to implement such a lock interface for a distributed system:  https://aphyr.com/posts/315-jepsen-rabbitmq

**Comment by ciarancourtney** [comment]
@matteius OK I gather that its not a trivial feature to implement in celery without backend caveats. I'm looking to move to redis from memcached/rabbitmq workloads so will keep SETNX in mind. Thanks
