### ISSUE TITLE
Celerybeat doesn't write full data to its log

### ISSUE THREAD

**Issue by roman-kachanovsky** [celery/celery#5472]
# Expected Behavior

Entries in beat.log like:

```
[2019-04-17 08:00:00,123: INFO/MainProcess] Scheduler: Sending due task apps.example.tasks.some_task (apps.example.tasks.some_task)
```

# Actual Behavior

I see only the short configuration summary in the log file after starting:

```
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-04-17 10:45:20
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
```

Except this, celerybeat works well and celeryd workers successfully receive and execute scheduled tasks.

# Package versions

Ubuntu 16.04.2 LTS
RabbitMQ 3.6.15
Python 3.6.6
supervisord 3.2.0
Celery 4.3.0
Kombu 4.5.0

# supervisord configuration

```
[program:example-celerybeat]
command=/home/ubuntu/example/venv/bin/celerybeat_start
user=ubuntu
numprocs=1
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
redirect_stderr=true
stdout_logfile=/home/ubuntu/example/venv/logs/beat.log
priority=1000
```

I have the same problem when I use `stderr_logfile` option instead of `redirect_stderr`.

# celerybeat_start

```
#!/bin/bash

cd /home/ubuntu/example
. /home/ubuntu/example/venv/bin/activate
. /home/ubuntu/example/venv/bin/postactivate

exec celery -A apps.taskapp beat --loglevel=INFO
```

**Comment by auvipy** [comment]
sample test case please?

**Comment by matteius** [comment]
Is the app in your apps.taskapp using a different Python logging configuration/alternate log file path than your supervisord configuration?
