### ISSUE TITLE
CELERY_TASK_RESULT_EXPIRES should be CELERY_RESULT_EXPIRES

### ISSUE THREAD

**Issue by jonbesga** [celery/celery#5473]
# Checklist

- [X] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

The [documentation](https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-result_expires) uses `CELERY_TASK_RESULT_EXPIRES` but that setting does not have any effect in the celery config. `CELERY_RESULT_EXPIRES` does.
# Suggestions

**Comment by auvipy** [comment]
would you mind sending a doc improvement pr?

**Comment by jonbesga** [comment]
Sure, I'll do that
