### ISSUE TITLE
Documentation site serves invalid ssl certificate

### ISSUE THREAD

**Issue by kalekseev** [celery/celery#5477]
Google provide links to https version of the docs https://docs.celeryproject.org/ but it serves  *.readthedocs.org certificate

<img width="1075" alt="Снимок экрана 2019-04-22 в 14 21 04" src="https://user-images.githubusercontent.com/367259/56498355-f6b9e600-6509-11e9-886c-c74814e06c3b.png">

**Comment by kalekseev** [comment]
Dup sorry

**Comment by daredevil82** [comment]
Still getting this issue.  https://docs.celeryproject.org/en/latest/reference/celery.schedules.html, for example

**Comment by daredevil82** [comment]
seems to be a dupe of https://github.com/celery/celeryproject/issues/24
