### ISSUE TITLE
Celery puts django database connections into invalid state after fork

### ISSUE THREAD

**Issue by Chronial** [celery/celery#5483]
Django db connections are not fork-safe. For this reason, celery contains cleanup code to handle this after a fork: https://github.com/celery/celery/blob/3d387704d4a18db5aea758e9a26c1ee4d71659df/celery/fixups/django.py#L141-L151

That code is supposed to do two things:
1. Manually close the file handles for django's db connections
2. Tell django to close the db connections

The first step is necessary so the second step doesn't actually close the db connections of the parent process that they where inherited from.

Unfortunately, the second step was broken by #4292, with this change: https://github.com/celery/celery/pull/4292/files#diff-7da7bceb78d87096e818d34c80115d18L186.

It is important that the connections are actually closed – otherwise they are left in an invalid state (remember – we force-closed the file descriptor). But `close_if_unusable_or_obsolete` only sometimes closes the connection.

To elaborate: In the django default config, `CONN_MAX_AGE` is set to `0`, and then `close_if_unusable_or_obsolete` actually always closes the connection. See https://github.com/django/django/blob/76990cbb/django/db/backends/base/base.py#L513 in combination with https://github.com/django/django/blob/76990cbb/django/db/backends/base/base.py#L190.

But if `CONN_MAX_AGE` is set to anything but `0`, `close_if_unusable_or_obsolete` will not always close the connection. That leaves the connection in an invalid state, causing these bugs: https://github.com/celery/django-celery-results/issues/58 and https://github.com/celery/celery/issues/4878.

**Comment by auvipy** [comment]
thanks for the report!

**Comment by Jokairui** [comment]
so, what exactly should we deal with this 'mysql server has gone away' bug? @Chronial  @auvipy

**Comment by Chronial** [comment]
@Jokairui you need to undo the changes of #4116. Until this is fixed in celery, you can either set `CONN_MAX_AGE` to `0` to avoid triggering the bug or you can do correct db handling yourself. This should do it:

```py
def fix_django_db(**kwargs):
    # Calling db.close() on some DB connections will cause the inherited DB
    # conn to also get broken in the parent process so we need to remove it
    # without triggering any network IO that close() might cause.
    for c in django.db.connections.all():
        if c and c.connection:
            try:
                os.close(c.connection.fileno())
            except (AttributeError, OSError, TypeError,
                    django.db.InterfaceError):
                pass
        try:
            c.close()
        except django.db.InterfaceError:
            pass
        except django.db.DatabaseError as exc:
            str_exc = str(exc)
            if 'closed' not in str_exc and 'not connected' not in str_exc:
                raise

celery.signals.worker_process_init.connect(fix_django_db)
```
