### ISSUE TITLE
SSL Cert sometimes invalid

### ISSUE THREAD

**Issue by carlio** [celery/celery#5484]
# Checklist

- [* ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [*] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [*] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [*] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

## Related Issues and Possible Duplicates
None as far as I can tell

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
SSL certificate for celeryproject.org is sometimes serving the wrong certificate for readthedocs.org

# Suggestions
No suggestions I have no idea how you host this :-)

![Capture](https://user-images.githubusercontent.com/682175/56667423-17bb3c00-66ae-11e9-95ad-e919b908c5c2.PNG)

**Comment by auvipy** [comment]
closing as dulicate, check open issues on celeryproject repo
