### ISSUE TITLE
Chain tasks cannot get parent update_state on 4.3.0

### ISSUE THREAD

**Issue by hu6360567** [celery/celery#5494]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Environment & Settings

**Celery version**: 4.3.0

<summary><b><code>celery report</code> Output:</b></summary>

```
software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:3.7.3
            billiard:3.6.0.0 redis:3.2.1
platform -> system:Linux arch:64bit
            kernel version:4.15.0-45-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost/'
```

# Steps to Reproduce

## Minimally Reproducible Test Case

```python
from celery import Celery

app = Celery('tq-test', broker='redis://localhost', backend='redis://localhost')


@app.task(bind=True)
def ttt(self, test_str):
    self.update_state(meta={'message': test_str})

def on_raw_message(body):
    try:
        msg = body['result']['message']
    except:
        msg = body
    print(msg)


if __name__ == '__main__':
    chain = app.signature('ttt', args=tuple("a"))
    chain |= app.signature('ttt', args=tuple("b"), immutable=True)
    print(chain.apply_async().get(on_message=on_raw_message))
```

# Expected Behavior
In Celery 4.2.2, update_state in both tasks are shown, as below.
```
a
b
```

# Actual Behavior
In Celery 4.3.0, only update_state in the task of the end of the chain is shown, as below.
```
b
```

**Comment by hu6360567** [comment]
FYI, the celery version of the worker does not affect the behavior.

**Comment by auvipy** [comment]
sorry?

**Comment by hu6360567** [comment]
I run the worker with the celery 4.3.0 and the main function with 4.2.2. I can get the expected behavior. 
But if the main function with 4.3.0, it can only get the update state from the end task of the chain.

**Comment by auvipy** [comment]
what is the proposed resolution of you?

**Comment by hu6360567** [comment]
> what is the proposed resolution of you?

Sorry, I haven't use the new version from then...

**Comment by auvipy** [comment]
i am closing this for now. lots of changes were made in canvas in the mean time. will revisit after celery 5.2 release.
