### ISSUE TITLE
Nested group(chain(group)) fails

### ISSUE THREAD

**Issue by p-eli** [celery/celery#5496]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- Subsequent groups within a chain fail #3585
- Consecutive groups in chain fails #4848 
- task/group chains fails in some scenarios #5467

## Environment & Settings

**Celery version**: 4.3.0

<details>
<summary><b><code>celery report</code> Output:

software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:3.5.3
billiard:3.6.0.0 redis:3.2.1
platform -> system:Linux arch:64bit
kernel version:4.19.32-1-MANJARO imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/1

broker_url: redis://redis:6379/1
result_backend: redis://redis:6379/1

</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce
## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import  group, chain
from tasks import task as t

# failing sequence
task = group([ t.si(),t.si(), chain( t.si(), group([ t.si(), t.si()]))])

# working sequence
task = group([ t.si(),t.si(), chain( t.si(), group([ t.si(), t.si()]), t.si())])

async_result = task.apply_async()
result = async_result.get()


```

</p>
</details>

# Expected Behavior

Calling `get` return group result. 

# Actual Behavior

All task finish success but calling `.get()` fail with traceback:

```
Traceback (most recent call last):
  File "/my_app.py", line 111, in add_to_queue
    result = async_result.get()
  File "/root/.cache/pypoetry/virtualenvs/my_app/lib/python3.7/site-packages/celery/result.py", line 697, in get
    on_interval=on_interval,
  File "/root/.cache/pypoetry/virtualenvs/my_app/lib/python3.7/site-packages/celery/result.py", line 815, in join_native
    on_message, on_interval):
  File "/root/.cache/pypoetry/virtualenvs/my_app/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 137, in iter_native
    if node._cache:
AttributeError: 'GroupResult' object has no attribute '_cache'

```

**Comment by tothegump** [comment]
This can be reproduced on master and I used RabbitMQ as broker.
Because nested `group(signature, chain(group))` get results like `GroupResult(AsyncResult, GroupResult)`, but the GroupResult do not have attribute `_cache`.
The problem is, you can not simplely change the statetment to `if hasattr(node, '_cache') and node._cache`, for that will have new issue.

**Comment by auvipy** [comment]
please provide a sample test case

**Comment by tothegump** [comment]
@p-eli provide a test case that can be used.
First, the task file: `myapp.py`
```
from celery import Celery

app = Celery(
    'myapp',
    broker='amqp://guest@localhost//',
    backend='redis://localhost:6379/0'
)

@app.task
def t():
    print('t-t-t')


if __name__ == '__main__':
    app.start()
```
then send tasks by:
```
from celery import  group, chain
from myapp import t

# failing sequence
task = group([ t.si(),t.si(), chain( t.si(), group([ t.si(), t.si()]))])

# working sequence
task = group([ t.si(),t.si(), chain( t.si(), group([ t.si(), t.si()]), t.si())])

async_result = task.apply_async()
result = async_result.get()
```

**Comment by tothegump** [comment]
Need a PR to fix it.

**Comment by Jerrynet** [comment]
Actually this still failed:
```
task_chain = task(0) | group(task(1), group(task(2), task(3)), task(4), group(task(5) | task(6), task(7))) | task(8) | group(task(9), task(10))
```
You are unable to retrieve AsyncResult for task(5)

**Version:** 4.4.0rc3
