### ISSUE TITLE
Celery: no logs when starting and crashing

### ISSUE THREAD

**Issue by BenVerKai** [celery/celery#5505]
Hi everyone,

I am using celery (**v4.2.2**) with redis and to start a worker I use celery multi as follow : `celery multi start 1 -A worker -c 2 --logfile=$PERSREF/logs/worker_%n%I.log --pidfile=$PERSREF/run/worker_%n.pid -Q mpr --loglevel=DEBUG`

### My problem
Recently, I encountered a problem: celery was stopping after starting without any log.
With the help of strace, I understood it was because the lib redis-py was missing in my environment :/

### Questions
But my point is: why there was no log about this? 
When the worker is operational, logs are logged in the worker log file as expected.
Do you know how/where to catch the celery starting process logs?

Thank you,

Ben

**Comment by auvipy** [comment]
please use the latest version and post your problem to IRC or mailing list. after that, if it seems to be a celery bug report here to reopen the issue.
