### ISSUE TITLE
How do I check task with args?

### ISSUE THREAD

**Issue by dwengticorp** [celery/celery#5509]
I want to check active or scheduled task, by name and args. I have a sample task like below

{u'celery@DW-LAP1': [{u'acknowledged': True,
   u'args': u"(<MainStreetDeal: WSSBC 2019 Rifle Raffle>, u'reconcile', {u'action': u'reconcile', u'priority': u'1'})",
   u'delivery_info': {u'exchange': u'celery',
    u'priority': 0,
    u'redelivered': None,
    u'routing_key': u'celery'},
   u'hostname': u'celery@DW-LAP1',
   u'id': u'228d5d93-562f-4af9-a580-58fcd475f5f8',
   u'kwargs': u'{}',
   u'name': u'main.celery.tasks.ms_deal_raffle_op',
   u'time_start': 1557465938.223,
   u'worker_pid': 7964}]}

The args is a string u"(<MainStreetDeal: WSSBC 2019 Rifle Raffle>, u'reconcile', {u'action': u'reconcile', u'priority': u'1'})"

I can search existing task by name, after that, I need compare the args. I need know how celery encode the args to string like above.

The serialize setting is CELERY_TASK_SERIALIZER = 'pickle'

But when I am not sure how pickle can serialize args to a string like that.

**Comment by auvipy** [comment]
post questions to mailing list or IRC. github is mosty for bug report.
