### ISSUE TITLE
 celery +rabbitmq - how to connect to Alibaba Cloud's rabbitmq

### ISSUE THREAD

**Issue by zhaowenjun333** [celery/celery#5510]
I want to send a task from java to the message queue. Celery-java doesn't seem to support redis, so I changed it to Alibaba Cloud's rabbitmq, but it doesn't seem to support it. Can this support rabbit cloud of Alibaba Cloud?  api of Alibaba is here：https://github.com/AliwareMQ/amqp-demos/tree/master/amqp-python-demo

**Comment by auvipy** [comment]
You can initially create your own package of aliware rabbitmq extension for celery and share with US. later when the package is more stable and community has more interest for the package we could consider adding its official support.

**Comment by thedrow** [comment]
Why is it not supported? If you can use pika to connect to it, you should be able to use py-amqp and thus Celery.
What's not supported exactly?

**Comment by carlhoerberg** [comment]
RocketMQ doesn't support AMQP (at least not 0-9-1). I would recommend using CloudAMQP and provision a RabbitMQ server in Alibaba cloud instead.

**Comment by auvipy** [comment]
rabbitmq need an extension to support amqp 1.0
