### ISSUE TITLE
Can not get complete message content if it is long 

### ISSUE THREAD

**Issue by rhuab** [celery/celery#5513]
Which version I use?
4.3.0

What problem I encounter?
Recently I find that if I send a large json string to RabbitMQ via celery.send_task, the worker can receive the string completely. If I execute celery.app.control.Inspect.active and some other monitor methods, what I get is only part of the string such as

{
"id": "6c8ce3e8-3b8f-4479-97ac-b00ed77c40ba",
"name": "accelerated_pack",
"args": "('{"components": {"CAP_BUILD": {"repo_name": "cap_build", "commit_git": "a617e6321605470e838211ef9034fb82e9384c91", "source_path": "/tmp/all_source/cap_build", "install_dir": "/tmp/all_install/cap_build", "build_dir": "/tmp/all_build/cap_build", "artifact_id": "2b215641c4249980337ae5a0e00ea890"}, "CENSE": {"repo_name": "licensing", "commit_git": "ce52f024829174e5f654211db478db237fd28b82", "source_path": "/tmp/all_source/cense", "install_dir": "/tmp/all_install/cense", "build_dir": "/tmp/all_build/cense", "artifact_id": "b7c41ef521922baf527c72fe5f135f33"}, "DAP_4_0": {"repo_name": "dap4.0", "commit_git": "0f6adcc6e54d86c3904c16a8fa1a39273e0c9ded", "source_path": "/tmp/all_source/dap4.0", "install_dir": "/tmp/all_install/dap4.0", "build_dir": "/tmp/all_build/dap4.0", "artifact_id": "c10e64c6ec6f708c8b1bdd47426fec40"}, "REDIS": {"repo_name": "redis", "commit_git": "8b838e2a4eb655c6aa1004c3ad3d50ff4128492a", "source_path": "/tmp/all_source/redis", "install_dir": "/tmp/all_install/redis",...',)",
"kwargs": "{}",
"type": "accelerated_pack",
"hostname": "test@85aa72eff43c",
"time_start": 1557480202.127367,
"acknowledged": true,
"delivery_info": {
"exchange": "",
"routing_key": "test",
"priority": 0,
"redelivered": false
},
"worker_pid": 11
}

You can find at the end of the key "args",  some unexpected characters "." appears, it just represents the rest part of the string. I debug the celery and its dependencies and can't get any clue.

**Comment by jheld** [comment]
You can increase the args and kwargs and return repr size on the worker to mitigate/work around this. But yes there may be other ways to do so, as specified via the referenced PR.

**Comment by thedrow** [comment]
When reporting bugs, please use the issue template. It's there for a reason.

**Comment by auvipy** [comment]
> When reporting bugs, please use the issue template. It's there for a reason.

SHould we enforce this strictly? I would be closing issues not following instructions?

**Comment by thedrow** [comment]
I think so. It makes reading issues so much easier.

**Comment by auvipy** [comment]
ok

**Comment by rhuab** [comment]
> You can increase the args and kwargs and return repr size on the worker to mitigate/work around this. But yes there may be other ways to do so, as specified via the referenced PR.

In this PR I keep args and kwargs in repr format but also add two object members for getting complete information

**Comment by auvipy** [comment]
closing in favor of https://github.com/celery/celery/commit/0f1883374b788302f5bfb8e1fdcf9c13b199b17c
