### ISSUE TITLE
Installing  celery[sqs] fails

### ISSUE THREAD

**Issue by saschametz** [celery/celery#5519]
If I try to install this package I'm getting the following error:

```
Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.

Error:  An error occurred while installing celery[sqs]!

This is likely caused by a bug in celery. Report this to its maintainers.
```

**Comment by auvipy** [comment]
> If I try to install this package I'm getting the following error:
> 
> ```
> Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.
> 
> Error:  An error occurred while installing celery[sqs]!
> 
> This is likely caused by a bug in celery. Report this to its maintainers.
> ```

Requirement already satisfied, skipping upgrade: amqp<3.0,>=2.4.0 in /usr/local/lib/python3.7/dist-packages (from kombu<5.0,>=4.4.0->celery[sqs]) (2.4.2)
Requirement already satisfied, skipping upgrade: s3transfer<0.3.0,>=0.2.0 in /usr/local/lib/python3.7/dist-packages (from boto3>=1.4.6; extra == "sqs"->celery[sqs]) (0.2.0)
Requirement already satisfied, skipping upgrade: botocore<1.13.0,>=1.12.130 in /usr/local/lib/python3.7/dist-packages (from boto3>=1.4.6; extra == "sqs"->celery[sqs]) (1.12.130)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from boto3>=1.4.6; extra == "sqs"->celery[sqs]) (0.9.4)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.20; python_version >= "3.4" in /usr/lib/python3/dist-packages (from botocore<1.13.0,>=1.12.130->boto3>=1.4.6; extra == "sqs"->celery[sqs]) (1.24.1)
Requirement already satisfied, skipping upgrade: docutils>=0.10 in /usr/local/lib/python3.7/dist-packages (from botocore<1.13.0,>=1.12.130->boto3>=1.4.6; extra == "sqs"->celery[sqs]) (0.14)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python3.7/dist-packages (from botocore<1.13.0,>=1.12.130->boto3>=1.4.6; extra == "sqs"->celery[sqs]) (2.8.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.13.0,>=1.12.130->boto3>=1.4.6; extra == "sqs"->celery[sqs]) (1.12.0)
 this is what i get in my PC. you need to install PyCurl first on your system.

**Comment by auvipy** [comment]
Please see PycURL documentation for how to specify the SSL backend manually.

**Comment by saschametz** [comment]
It's working now after adding this env variables:
```
export PYCURL_SSL_LIBRARY=openssl
export LDFLAGS=-L/usr/local/opt/openssl/lib;export CPPFLAGS=-I/usr/local/opt/openssl/include
```

**Comment by auvipy** [comment]
yup, its pycurl issue, not celery.
