### ISSUE TITLE
Add Example of Router Function to Documentation

### ISSUE THREAD

**Issue by mago3421** [celery/celery#5521]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

Requesting that Celery's documentation include an example using a router function when calling apply_async() to determine the queue for the task. Currently, I need to route tasks to different workers on different servers with the queue name determining the server and worker on which to execute the task. My router function itself will query which workers are not busy and return the alphabetically first non-busy worker/queue (one worker per queue in my case). There are no examples of using a router function to dynamically select the queue within the documentation. Please add.

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
Please proceed with a PR
