### ISSUE TITLE
Some of the links old docs don't work

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#5522]
When I click the docs chooser, some of the links don't work.

I'm working on a project that uses the legacy < 1.4 project layout and I can't really change it, so was trying to see what how celery was when django settings.py lived in the project root.

![image](https://user-images.githubusercontent.com/179677/57701996-0635d600-7655-11e9-8838-ceb1a9ae281b.png)

**Comment by auvipy** [comment]
which ceery version are you using with django 1.4 < ?

**Comment by stuaxo** [comment]
Django is up to date(ish), it's 1.11.1.

But the project layout has settings.py in the root directory, which last seems to have been the default Django 1.4 times.


Celery version is currently 3.1.25.   I'm hoping to have more luck in getting celery updated - though in ${current workplace} it's not always quick or straightforward.

**Comment by auvipy** [comment]
you need django-celery package than.

**Comment by auvipy** [comment]
https://github.com/celery/celery/tree/3.1/docs

**Comment by stuaxo** [comment]
Cheers for the help.

Would be good to fix (or remove) the broken links from the doc widget I posted at the top of this ticket.
(try clicking one of the older "archived" links and they go to this page:

![image](https://user-images.githubusercontent.com/179677/57708521-6763a680-7661-11e9-8cdf-ab5c207471b7.png)

**Comment by stuaxo** [comment]
What would help me in the case here for upgrading, is if there are any security issues in older versions (unlikely - but then I get an upgrade), or if I can find out something definite about whether support for 3.x is finished / likely to finish soon.

**Comment by auvipy** [comment]
I am moving this to site repo
