### ISSUE TITLE
Celery 3.x Need sponsor to get extended support and upgrades to celery 4

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5526]
If you or your company need to keep celery 3.x supported please contact me to support my time.

related https://github.com/celery/django-celery/issues/568

https://opencollective.com/celery

**Comment by Jamim** [comment]
Hello @auvipy,
Does the closure of this issue mean that the team decided to drop support for Celery 3.x?
To be clear, I don't use Celery 3.x, but I believe that transparency matters in this case.
Thanks!

**Comment by auvipy** [comment]
> Hello @auvipy,
> Does the closure of this issue mean that the team decided to drop support for Celery 3.x?
> To be clear, I don't use Celery 3.x, but I believe that transparency matters in this case.
> Thanks!

Didn't get enough response. If any company willing to support that version, I will keep that updated.
