### ISSUE TITLE
Clarification about how to initialize a task context in a worker

### ISSUE THREAD

**Issue by jpays** [celery/celery#5530]
Hello, 

We are using celery for executing tasks that require a lengthy initialization phase.

Namely in this case, we are running deep learning models that are pretty fast but require pre-loading in memory first, but it could be anything like loading a huge pickle file from disk or loading data from a database for example...

The goal is to initialize everything once and for all when the worker starts, so that the actual tasks executions can be faster.

At first glance, using a custom Task class with the initialization phase in `__init__` and the actual task code in `run `seems a good fit, but from reading extensive discussions about this, it is clearly discouraged in the current versions of Celery, and we can see that `__init__` is run at the registering phase, and also whenever `inspect `or `status `commands are used for example, which is clearly not the desired behaviour. The code from `__init__ `should be run only in the actual worker process/thread.

Could you clarify what is the correct way to implement this in Celery in the current version ?

Thanks in advance
Jerome

**Comment by auvipy** [comment]
post questions in mailing list and irc first
