### ISSUE TITLE
CassandraBackend has no attribute _save_group

### ISSUE THREAD

**Issue by shaunakgodbole** [celery/celery#5537]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: celery==4.2.1

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
    job.save(backend=tasks.cel.backend)
  File "/Users/shaunak/instabase-repo/instabase/venv/lib/python2.7/site-packages/celery/result.py", line 887, in save
    return (backend or self.app.backend).save_group(self.id, self)
  File "/Users/shaunak/instabase-repo/instabase/venv/lib/python2.7/site-packages/celery/backends/base.py", line 399, in save_group
    return self._save_group(group_id, result)
AttributeError: 'CassandraBackend' object has no attribute '_save_group'
```

</p>
</details>

# Steps to Reproduce
1. Start celery with Cassandra as a backend
```
import celery
import time

cel = celery.Celery(
  'experiments',
  backend='cassandra://',
  broker='amqp://localhost:5672'
)

cel.conf.update(
  CELERYD_PREFETCH_MULTIPLIER = 1,
  CELERY_REJECT_ON_WORKER_LOST=True,
  CELERY_TASK_REJECT_ON_WORKER_LOST=True,
  CASSANDRA_SERVERS=['localhost'],
)
```

2. Create a group and try to save the result
```
  job = group_sig.delay()
  job.save(backend=tasks.cel.backend)
```

# Expected Behavior

We expect that the result will be saved without throwing an error.

# Actual Behavior

We see the following error:
```
    job.save(backend=tasks.cel.backend)
  File "/Users/shaunak/instabase-repo/instabase/venv/lib/python2.7/site-packages/celery/result.py", line 887, in save
    return (backend or self.app.backend).save_group(self.id, self)
  File "/Users/shaunak/instabase-repo/instabase/venv/lib/python2.7/site-packages/celery/backends/base.py", line 399, in save_group
    return self._save_group(group_id, result)
AttributeError: 'CassandraBackend' object has no attribute '_save_group'
```

**Comment by auvipy** [comment]
could you try celery 4.3 or master?

**Comment by shaunakgodbole** [comment]
Just tried with celery 4.3.  It doesn't work.  

Also, looked at cassandra.py file: https://github.com/celery/celery/blob/master/celery/backends/cassandra.py.  The function `_save_group` doesn't exist there yet. 

Also the function `_save_group` is only implemented in the `KeyValueStoreBackend`: https://github.com/celery/celery/blob/master/celery/backends/base.py#L720

So, unless it is officially supported by celery, I'll have to duplicate the functionality to do save and restore myself.

**Comment by mezgerj** [comment]
I'm looking at this one

**Comment by auvipy** [comment]
feel free to contribute
