### ISSUE TITLE
Celery excessive logging

### ISSUE THREAD

**Issue by Narzhan** [celery/celery#5554]
### Some relevant info:
Celery 4.3.0
Environment: Ubuntu 18.04  in Docker
Celery start celery -A main worker --autoscale=9,2 --loglevel=info --logfile=/opt/celery.log

I've experienced issue with Celery logging. Task processing is handled by several classes each with a dedicated log file. I've observed that in the autoscaling scenario task can have several log entries as if it was being processed by a several workers. Redacted example, there are several more log entries: 

```
2019-05-28 09:54:38,664 - 124 - INFO - Status: success, {"sth":"test"}
2019-05-28 09:54:38,664 - 124 - INFO -Status: success, {"sth":"test"}
.....
```
This also happens for the Celery log. Is my configuration incorrect or should I do something differently?

**Comment by auvipy** [comment]
you shoud post support questions to maling list or irc untill it is identified as bug
