### ISSUE TITLE
Unit test failing with kombu 4.6

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5555]
――――――――――――――― test_security.test_disable_insecure_serializers ――――――――――――――――
self = <t.unit.security.test_security.test_security object at 0x7fca6d959780>
>   ???
E   AssertionError: assert 'application/json' in {'application/x-msgpack', 'application/x-python-serialize', 'application/x-yaml'}
t/unit/security/test_security.py:59: AssertionError

**Comment by vallee11** [comment]
Removed dangerous default mutable arguments from function definitions… (

#1040)

def disable_insecure_serializers(allowed=['json']):
      pass

Not equivalent

def disable_insecure_serializers(allowed=None):
      allowed = ['json'] if not allowed else allowed

**Comment by vallee11** [comment]
case:  disable_insecure_serializers(allowed=None)

before:
     allowed=None

after:
     allowed = ["json"] 

so test case go error

**Comment by auvipy** [comment]
so what do you propose to fix it? I wil implement as you suggest

**Comment by vallee11** [comment]
if I were you, I will modify the test case, and use 'or' to solve ‘default value’ problem

    def disable_insecure_serializers(allowed=None):
          allowed = allowed or ['json'] 

use "or"

**Comment by browniebroke** [comment]
The above snippet, using `or` would not help, you'd still have the same problem. So either we change the test assertions in Celery to reflect, or we use a Sentinel value instead of `None` as default: https://github.com/celery/kombu/pull/1055
