### ISSUE TITLE
Exception message as a string is still being unpacked

### ISSUE THREAD

**Issue by kamikaze** [celery/celery#5564]
Here: https://github.com/celery/celery/blob/master/celery/backends/base.py#L282
Following code:
```
exc_msg = 'SHOULDBETOGETHER'
print(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
```
results in:
```
S H O U L D B E T O G E T H E R
```

**Comment by georgepsarakis** [comment]
Nice catch. I think this has to do with operator precedence, probably the following illustrates it better:

```python
print(*(exc_msg if isinstance(exc_msg, tuple) else exc_msg))
```
