### ISSUE TITLE
What type of pool is created for redis broker

### ISSUE THREAD

**Issue by okomarov** [celery/celery#5567]
# Checklist
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- Potentially related to #2616 although quite dated

#### Possible Duplicates

- None

# Description
The documentation is unclear on the following points:
1. What happens when the number of pool connections goes above the limit specified by [broker_pool_limit](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_pool_limit) and [redis_max_connections](http://docs.celeryproject.org/en/latest/userguide/configuration.html#redis-max-connections)
2. Which setting prevails?
3. Is there a way to choose the type of Redis pool?

# Suggestions
1. By default Redis creates a [`redis.connection.ConnectionPool`](https://redis-py.readthedocs.io/en/latest/#redis.ConnectionPool) which raises a `redis.exceptions.ConnectionError` when celery attempts to execute a new task and all of the connections in the pool are exhausted. 
In contrast, the [`redis.connection.BlockingConnectionPool`](https://redis-py.readthedocs.io/en/latest/#redis.BlockingConnectionPool) does not raise an error and waits until a connection becomes available in the pool. 
The docs should warn that `redis_max_connections` will raise a redis exception in case the connections exceed the maximum. 

2. Unsure and untested, so not clear what to suggest here.

3. The docs should probably mentions under `redis_max_connections` that choosing the type of redis pool is unsupported.

**Comment by auvipy** [comment]
can you create a pr for docs improvement?

**Comment by okomarov** [comment]
@auvipy I will add some clarifications to the `redis_max_connections` setting which will partially solve the issue above. 

The comprehensive solution would test how `redis_max_connections` behaves with the `broker_pool_limit` and report that in the docs, e.g. not specifying any setting, effectively sets `redis_max_connections` to the `broker_pool_limit` default of 10 connections or setting the `redis_max_connections` sets the broker pool limit, and also what happens when both are passed...

Finally, it makes sense to have a bool setting `redis_blocking_pool` which defaults to `False` and instantiates a `redis.connection.BlockingConnectionPool()` in case of True for all those use cases where the Redis connections are limited but you want ot avoid exceptions, e.g. pricing plans that price redis by number of connections.

**Comment by SBhat2615** [comment]
@okomarov I'm using celery with redis backend. Not very clear on `redis_max_connections` and `broker_pool_limit`.
Can you help in understanding the difference between the two?
