### ISSUE TITLE
Unit and Integration tests failures

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5568]
―――――――――――――――――――――――――― test_chain.test_parent_ids ――――――――――――――――――――――――――
self = <t.integration.test_canvas.test_chain object at 0x7ff13ca21438>
manager = <celery.contrib.testing.manager.Manager object at 0x7ff13cafd438>
num = 10
    @flaky
    def test_parent_ids(self, manager, num=10):
>       assert manager.inspect().ping()
E       assert None
E        +  where None = <bound method Inspect.ping of <celery.app.control.Inspect object at 0x7ff13ca491d0>>()
E        +    where <bound method Inspect.ping of <celery.app.control.Inspect object at 0x7ff13ca491d0>> = <celery.app.control.Inspect object at 0x7ff13ca491d0>.ping
E        +      where <celery.app.control.Inspect object at 0x7ff13ca491d0> = <bound method ManagerMixin.inspect of <celery.contrib.testing.manager.Manager object at 0x7ff13cafd438>>()
E        +        where <bound method ManagerMixin.inspect of <celery.contrib.testing.manager.Manager object at 0x7ff13cafd438>> = <celery.contrib.testing.manager.Manager object at 0x7ff13cafd438>.inspect
t/integration/test_canvas.py:127: AssertionError

**Comment by auvipy** [comment]
assert excinfo.value.__class__.__name__ == 'RuntimeError'
>       assert str(excinfo.value) == 'aap'
E       assert "['aap']" == 'aap'
E         - ['aap']
E         + aap
t/unit/backends/test_amqp.py:244: AssertionError

**Comment by D3X** [comment]
@auvipy for the latter issue (the `RuntimeError` serialization):
When serializing the exception, the arguments are stored as a tuple:
https://github.com/celery/celery/blob/f79894e0a2c7156fd0ca5e8e3b652b6a46a7e8e7/celery/backends/base.py#L261
This makes sense, except when using JSON serializer (like in this test), tuples get converted to arrays.
When deserializing, they end up being lists.
`exception_to_python` checks if the message is a tuple and if it is - it unpacks it before passing to the exception class. Perhaps it should check for lists too?
https://github.com/celery/celery/blob/f79894e0a2c7156fd0ca5e8e3b652b6a46a7e8e7/celery/backends/base.py#L282-L285

**Comment by auvipy** [comment]
can you come with a PR?

**Comment by D3X** [comment]
@auvipy thanks for merging that! As for the other issue... I can't get the integration tests to run at all on my local. `pytest` hangs at `collecting...`. I tried running just `pytest` and via `tox`, same result. I'm sure I'm missing something in my setup, just not sure what that could be. Any clues?

**Comment by auvipy** [comment]
there was issue in kombu, and some old assert
