### ISSUE TITLE
chan(group1, group2), tasks of group2 runs while tasks of group1 is running.

### ISSUE THREAD

**Issue by tothegump** [celery/celery#5574]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #5467
- #2573

#### Possible Duplicates

- #1163

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.0rc1 (cliffs) kombu:4.6.1 py:3.6.6
            billiard:3.6.0.0 py-amqp:2.5.0
platform -> system:Darwin arch:64bit
            kernel version:18.5.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'redis://localhost:6379/0'

```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
# myapp.py
from celery import Celery

app = Celery(
    'myapp',
    broker='amqp://guest@localhost//',
    backend='redis://localhost:6379/0'
)

@app.task
def b(zz):
    import time
    print('start: {}'.format(zz))
    time.sleep(5)
    print('end: {}'.format(zz))
    return zz

@app.task
def a(zz):
    print(zz)
    return zz
if __name__ == '__main__':
    app.start()
```
and run celery worker with concurrency=3
```shell
worker -A myapp -l debug --concurrency=3
```
send tasks:
```python
group1 = group(b.si('group1 job1'), b.si('group1 job2'))
group2 = group(a.si('group2 job1'), a.si('group2 job2'))
res = chain(group1, group2)
```
</p>
</details>

# Expected Behavior

tasks in group2 not run until group1 returns
expect output:
```
start: group1 job1
start: group1 job2
end: group1 job1
end: group1 job2
group2 job1
group2 job2
```
# Actual Behavior
they are run in parallel and the out put is:
```
start: group1 job1
start: group1 job2
group2 job1
group2 job2
end: group1 job1
end: group1 job2
```

**Comment by auvipy** [comment]
could you try celery from master once?

**Comment by tothegump** [comment]
Yes, I did try it from master.
Actually, I have a question for the source code in the file `celery.canvas.Signature#__or__`,
maybe the comment `# group() | group() -> single group` is not right.
`chain(group1, group2)` is not the same as `group(group1, group2)`.

**Comment by thedrow** [comment]
There's another related issue here: #2573.
It's the source of this problem...

**Comment by tothegump** [comment]
> There's another related issue here: #2573.
> It's the source of this problem...

I tried cases in the discussions, and worked fine after this PR for me.
Maybe need unit test or integration test for #2573.

**Comment by tothegump** [comment]
#5615 add integration test to that complex case.

**Comment by auvipy** [comment]
only rabbit tests a failing
