### ISSUE TITLE
Django documentation for celeryd is not clear

### ISSUE THREAD

**Issue by Vigrond** [celery/celery#5582]
As a new celery user I cannot discern if celeryd should be ran with with both /etc/default/celeryd config AND Django settings.py, or one or the other?  If just Django settings.py, how does the /etc/init.d/celeryd script know that it is there?  If both, why are there duplicate settings?   Or maybe /etc/default/celeryd isn't needed with django as the project claims it can pull everything from Django settings?

None of the above questions are answered in the documentation.  The documentation just sort of lays out options to try and I have to do each one experimentally and see if the result works or not.

**Comment by auvipy** [comment]
celeryd is needed for Daemonizing. post your questions in mailing list or IRC first.
