### ISSUE TITLE
RabbitMQ docker instructions: incorrect port number

### ISSUE THREAD

**Issue by glexey** [celery/celery#5593]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

The "first-steps-with-celery" advises to use the following docker command to start RabbitMQ instance:

docker run -d -p 5462:5462 rabbitmq

However this won't work, as the default port for rabbit is 5672, not 5462.

# Suggestions

replace 5462 with 5672.

**Comment by auvipy** [comment]
plz review https://github.com/celery/celery/pull/5595

**Comment by glexey** [comment]
Looks good to me
