### ISSUE TITLE
Document and code are inconsistent about task_reject_on_worker_lost config

### ISSUE THREAD

**Issue by Hsiny** [celery/celery#5598]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

In the latest version of the documentation about  [task_reject_on_worker_lost](http://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=task_reject_on_worker_lost), it says `Enabling this can cause message loops`

But actually, enabling this will not cause message loops, tasks only execute twice.Tasks that have been redelivered will not be redelivered again, [source code](https://github.com/celery/celery/blob/master/celery/worker/request.py#L518)

# Suggestions

If it is a documentation error,  it is best to remove the warning from the document.
If the document is ok, it is need to modify the code.
I can help modify the document or code.

**Comment by auvipy** [comment]
feel free to come with a PR?

**Comment by Hsiny** [comment]
Sure, here's a PR  #6103   @auvipy
