### ISSUE TITLE
celery worker request

### ISSUE THREAD

**Issue by YXinAndy** [celery/celery#5608]
If we use beat and worker at the same time, we will find that beat is very good. In a few days, the worker will suddenly get stuck inexplicably, and there will be no Received task

**Comment by YXinAndy** [comment]
Celery version for 3.1.25, I found there seems to be a lot of similar problems on the BBS, is there a solution?

**Comment by matteius** [comment]
Have you considered upgrading to the celery 4 series?  Seems you may need to set a broker_heartbeat of 0 to get nonblocking sockets, but I agree sometimes certain errors can stall a worker depending on the conditions and it won't reconnect.   It seemed to happen more on Celery 3 though, and on 4 I actually know some of the combinations that can cause it such as using a results backend with heartbeats currently is a bug being worked in other issue reports.
