### ISSUE TITLE
Query regarding celery scalability

### ISSUE THREAD

**Issue by baymaxx-12121** [celery/celery#5610]
I have few questions regarding celery. Please help me with that.

**Sorry for posting this here**. I asked the same in stackoverflow (https://stackoverflow.com/questions/56681692/queries-regarding-celery-scalability) but no reply.

1. Do we need to put the project code in every celery worker? If yes, if I am increasing the number of workers and also I am updating my code, what is the best way to update the code in all the worker instances (without manually pushing code to every instance everytime)?

2. Using `-Ofair` in celery worker as argument disable prefetching in workers even if have set `PREFETCH_LIMIT=8 or so`?

3. IMPORTANT: Does rabbitmq broker assign the task to the workers or do workers pull the task from the broker?

4. Does it make sense to have more than one celery worker (with as many subprocesses as number of cores) in a system? I see few people run multiple celery workers in a single system.

5. To add to the previous question, whats the performance difference between the two scenarios: single worker (8 cores) in a system or two workers (with concurrency 4)

**Comment by clokep** [comment]
Unfortunately the answer to many of these question is "it depends".

1. Each celery worker individually needs access to the code, yes. The celery workers will run whatever code they have loaded, so if you make a change to a task implementation you'll need to reload it into each celery worker. The short answer is "Yes, you'll need to get your code on each instance."

2. I haven't used this option, sorry.

3. RabbitMQ is a FIFO, I believe the workers pull though by asking for more tasks.

4. My current set-up runs multiple workers on a single system. We do this to process different queues with slightly different options. This really depends on what you're trying to accomplish.

5. Two workers will have some overhead:
    * (Assuming you're using prefork.) The parent worker process will be duplicated in each process.
    * They'll have individual connections open to the broker and the backend.

   I don't think this is a recommendation *not* to have multiple workers though. It depends on your configuration.

**Comment by DylanYoung** [comment]
I'd recommend two workers with 4 children each given the number of worker crashes we've seen in prod.

**Comment by miraculixx** [comment]
@baymaxx-12121 just stumbled upon this and provided my 5cents https://stackoverflow.com/a/60353606/890242. Hope its still useful
