### ISSUE TITLE
Inspect doesn't work(Solved)

### ISSUE THREAD

**Issue by thawhtetkaung-private** [celery/celery#5628]
May be this is already known issue or reported by someone. When you inspect a worker, return None(it is my python print result). 
Here is the system information:
software -> celery:4.3.0 (rhubarb) kombu:4.6.1 py:3.6.8
            billiard:3.6.0.0 redis:3.2.1
platform -> system:Linux arch:64bit
            kernel version:4.15.0-54-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379/0

But when you downgrade the kombu version to 4.5.0 you will get the inspect result(registered, reserved, active,...)

If this is not a bug or something unnecessary, you can close this issue.

**Comment by netrix** [comment]
Can you provide an explanation what is changed? Why it's returning None know or give anything related to that?

Unfortunately the documentation doesn't provide anything on topic: https://docs.celeryproject.org/en/latest/reference/celery.app.control.html#celery.app.control.Inspect.active

**Comment by thawhtetkaung-private** [comment]
> Can you provide an explanation what is changed? 

First, I am not expert in using celery. So, I can't provide a detail explanation. The changes I made is just one thing. That is change `kombu` version(`kombu:4.6.1` to  `kombu:4.5.0`. If you ask me how I know the solution, I have two linux machine - development and mainframe. If I'm not wrong. The program work in my development machine and doesn't work in mainframe. When I check many thing, I found `kombu` version is not same. So, I change it. 

> Why it's returning None know or give anything related to that?

I don't know why it is returning None. But `None` is result of python result.
```i = app.control.inspect()``` 
When I print `i` , it show `None`. I want to know is reserved tasks by using the following code.
`reserved_tasks = i.reserved()` but when `i` is `None`, I can't determined the tasks. The code work in my development machine but it doesn't work in mainframe. After checking everything, it solve by changing `kombu` version.

I am an amateur in celery. So I can't tell you a deep explanation. All I know is there is a problem and I solved like that. I don't know what is wrong or what is right.  The conclusion I can say is the celery is not compatible with `kombu:4.6.1` (in my case) or higher than `kombu:4.5.0` (possibly).
I don't know it is the answer you are seeking but I glad it can help you a little.

**Comment by auvipy** [comment]
can you try celery==4.4.0rc2 with the latest kombu?

**Comment by thawhtetkaung-private** [comment]
@auvipy Sorry for inconvenience. I can't try celery==4.4.0rc2 with the latest kombu because I can't access mainframe and working in another project. Moreover, the project which I worked has no intention to upgrade celery version now.

**Comment by auvipy** [comment]
I am not sure it's a celery/kombu bug or not? should we close this?

**Comment by thawhtetkaung-private** [comment]
> I am not sure it's a celery/kombu bug or not? should we close this?
Since the problem is solved by changing kombu version, I closed this issue.
