### ISSUE TITLE
Chord Body not Called after Headers execute

### ISSUE THREAD

**Issue by tarekM** [celery/celery#5630]
# Checklist

- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [X ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.3.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

 -------------- celery@Parths-MacBook-Pro v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Darwin-18.2.0-x86_64-i386-64bit 2019-07-02 21:57:47
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x10fe5bba8 (.default.Loader)
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://localhost/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6
* **Minimal Celery Version**: 4.3.0
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: rabbitmq 3.7
* **Minimal Result Backend Version**: Redis 3.2.1
* **Minimal OS and/or Kernel Version**: N/A 
* **Minimal Broker Client Version**: N/A 
* **Minimal Result Backend Client Version**: N/A 

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
from celery import current_app

import os
import json

RABBITMQ_URL = os.getenv('RABBITMQ_URL', 'amqp://localhost')
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost')

CELERY_GLOBAL_CONFIG = {
    'accept_content': ['json'],
    'enable_utc': True,
}

CELERY_BROKER_CONFIG = {
    'broker_url': RABBITMQ_URL,
    'task_queue_ha_policy': 'all', # replicate queue to all broker nodes
}

CELERY_RESULT_BACKEND_CONFIG = {
    'result_backend': REDIS_URL,
    'result_compression': 'gzip',
    'result_serializer': 'json',
    'result_chord_join_timeout': 60*120, # 2hrs
}

CELERY_TASK_CONFIG = {
    'task_serializer': 'json',
    'task_time_limit': 60*240, # 4hrs
    'task_routes': json.load(open('src/task_routes.json', 'rb')),
}

current_app.conf.update(CELERY_GLOBAL_CONFIG)
current_app.conf.update(CELERY_BROKER_CONFIG)
current_app.conf.update(CELERY_RESULT_BACKEND_CONFIG)
current_app.conf.update(CELERY_TASK_CONFIG)
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
@app.task
def consumer(doc_list, **kwargs):
    chord([process_document.s(doc) for doc in doc_list])(aggregate.s())

@app.task
def process_document(doc):
    return output

@app.task
def aggregate(document_outputs):
    request.post(url, document_outputs, timeout=120)
```

</p>
</details>

# Expected Behavior

I expect the aggregate callback to be called consistently after processing all the documents.

# Actual Behavior

The aggregate callback is ONLY called when there are 1 or 2 documents, but not consistently called for any number of documents, even though headers are completing successfully.

**Comment by auvipy** [comment]
could you also try celery 4.4.rc2?

**Comment by auvipy** [comment]
and post this to mailing list

**Comment by NickLamping** [comment]
(I'm working with @tarekM) We upgraded to 4.4.rc2 and that seemed to fix the chord callback issue. Do you still want us to post this to the mailing list?

**Comment by NickLamping** [comment]
Also, since we're looking to use chords in a production environment, we don't want to use a release candidate version in our application. Is there a timeline for when the next stable release is?

**Comment by auvipy** [comment]
very soon

**Comment by NickLamping** [comment]
How soon is very soon?
