### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host and retry=False not working

### ISSUE THREAD

**Issue by MufidJamaluddin** [celery/celery#5634]
The Celery 4.3.0 execute long task always WinError 10054 every 200 - 500 seconds with Python 3.7.3, RabbitMQ 3.7.14 and Erlang 22.0. 
This error makes Celery run infinite retry the task from beginning and the retry=False is not working.

![Celery Error](https://user-images.githubusercontent.com/28973632/60754504-18584300-a00c-11e9-8b76-3bacfc56490a.PNG)

![Celery Error2](https://user-images.githubusercontent.com/28973632/60754507-21e1ab00-a00c-11e9-8911-a8ec9f260eaa.PNG)

**Comment by auvipy** [comment]
it is suggested to post on mailing list for support questions.
