### ISSUE TITLE
Allow redelivered to be ignored if task_reject_on_worker_lost is set

### ISSUE THREAD

**Issue by groves** [celery/celery#5641]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/issues/5106 feels like it may be fixed by this as well, but I'm not sure that it fixes their exact issue
- https://github.com/celery/celery/issues/5598 mentions that the docs don't describe this redelivered behavior

#### Possible Duplicates

- None

# Brief Summary

If task_acks_late and task_reject_on_worker_lost are set, a task will be requeued the first time it fails due to losing a worker. However if the message has the `redelivered` flag set to True, [requeue will be set to false](https://github.com/celery/celery/blob/master/celery/worker/request.py#L518). That means a second worker lost failure doesn't get retried.

We're running on Heroku and it's possible we'll get workers killed back to back if we release new code and then do a config change right after, as one example. We'd like to continue to requeue the task regardless of the redelivered flag.

# Design

## Architectural Considerations

None

## Proposed Behavior

Add a configuration flag task_requeue_on_redelivered that if set to True, causes the task to be requeued regardless of the redelivered flag.

I'm happy to put together a PR to do this if it seems like a reasonable approach.

## Diagrams

N/A

## Alternatives

The way we work around this now is by overriding Request and always setting redelivered to False:

```
class NeverRedeliveredRequest(Request):
    def __init__(self, message, **kwargs):
        if message.delivery_info:
            message.delivery_info['redelivered'] = False
        super().__init__(message, **kwargs)
```

I don't like obliterating information that might be used elsewhere though, so I'd prefer this to be in Celery itself.

**Comment by auvipy** [comment]
are you planning to come with a PR with a test?

**Comment by groves** [comment]
If this is an approach you like, absolutely.

**Comment by Usiel** [comment]
I feel like a nice solution would be to actually honor the `autoretry` settings for the task. If for example I configure my task with `autoretry_for=(WorkerLostError,)` and `max_retries=3` I would expect to be requeued 3 times in case of a `WorkerLostError`.

The additional flag `reject_on_worker_lost` would still make sense, as it makes sure that someone who uses `autoretry_for=(Exception,)` won't suddenly have the tasks being retried for `WorkerLostError` (with the issues for mid-execution crashes described [here](https://docs.celeryproject.org/en/latest/faq.html#should-i-use-retry-or-acks-late)).

**Comment by groves** [comment]
@Usiel I agree! I'd prefer that the retry settings were just honored, but doing that would change the existing behavior. I worried that would break people who are expecting redelivery to trump retry settings, so I didn't propose going that way.

**Comment by dipAch** [comment]
@groves @auvipy Is this being worked on?

**Comment by raomuyang** [comment]
Agree! The `task_reject_on_worker_lost` flag allows the message to be re-queued once again rather than always, this is not pointed in the document.

This problem is frequent repetition when I deploy the celery worker in docker although the `task_reject_on_worker_lost ` is set:
Celery workers running in a  docker container with limited resources (CPU / Memory), that some processes of workers may be killed by docker if the using of resources excess using the limited quota (in most cases is CPU)

I'm using the same way to resolve this problem currently

```python
class AlwaysRedeliveryRequest(request.Request):

    def __init__(self, message, **kwargs):
        if message.delivery_info:
            message.delivery_info['redelivered'] = False
        super(AlwaysRedeliveryRequest, self).__init__(message, **kwargs)


# noinspection PyAbstractClass
class BaseTask(celery.Task):
    Request = AlwaysRedeliveryRequest


@app.task(base=BaseTask)
def demo():
     pass

```
