### ISSUE TITLE
Should overriding __call__() in custom Task class call self.run() or super().__call__()

### ISSUE THREAD

**Issue by colosi** [celery/celery#5643]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- #4993 

# Description

The [Abstract Tasks](https://docs.celeryproject.org/en/latest/userguide/application.html#abstract-tasks) section of your documentation says that if you override `__call__()` to do something every time the task body is run, then you should call `super().__call__()` to run that task.  This breaks some tests in my app which I'll describe below.  calling `self.run()` instead of `super().__call__()` from within `__call__()` to run the body works properly.  #4993 specifically asked about this and the recommendation was to use `super().__call__()`, not `self.run()`.

The test code that is failing effectively does the following:
1. enqueue task with the delay() method
2. process task, - fail and enqueue for retry
3. process task

We have mimicked the code [here](https://github.com/celery/celery/blob/v4.1.0/celery/contrib/testing/worker.py#L122) to manually process a task by creating a WorkerController and calling `wait_for_task()` followed by `process_queued_task()`.

When I use `super().__call__()` instead of `self.run()`, the second call to process the task fails with a `TimeoutError`.  Effectively, the initial running of the task works, but something with the retry flow is failing to re-enqueue the task.

Running in the debugger, I discovered
- The `celery.app.task.Task.__call__()` method is never called if I don't call this manually with `super().__call__()` from my custom Task class' `__call__()` method.
- The execution of the task body is triggered from `celery.app.trace.build_tracer.trace_task()`, which directly calls the `run()` function if the custom task class has not defined `__call__()`
- The task_trace function calls the same surrounding management code as `Task.__call__()` (in addition to a bunch of other things), so it seems like it would be a bad idea to call `Task.__call__()` from within this.

I'm not sure if anything particular to my configuration is causing the flow to go through `trace_task()` rather than `Task.__call__()`.

Here are some code comments and snippets which may be useful:
https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L284
```python
# If the task doesn't define a custom __call__ method
# we optimize it away by simply calling the run method directly,
# saving the extra method call and a line less in the stack trace.
fun = task if task_has_custom(task, '__call__') else task.run
```
https://github.com/celery/celery/blob/v4.1.0/celery/app/task.py#L146
```
    """Task base class.
    Note:
        When called tasks apply the :meth:`run` method.  This method must
        be defined by all tasks (that is unless the :meth:`__call__` method
        is overridden).
    """
```

# Suggestions

Either help me understand what I'm doing wrong and provide documentation to explain that to future users in the Abstract Tasks section of the documentation, or change the code snippet to the following:
```python
from celery import Task

class DebugTask(Task):

    def __call__(self, *args, **kwargs):
        print('TASK STARTING: {0.name}[{0.request.id}]'.format(self))
        return self.run(*args, **kwargs)
```

**Comment by colosi** [comment]
Given the following snippets, I believe that the documentation has to be updated to be in line with optimizations made to Celery at some point prior to 4.3.

https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L606
```python
def _install_stack_protection():
    # Patches BaseTask.__call__ in the worker to handle the edge case
    # where people override it and also call super.
    #
    # - The worker optimizes away BaseTask.__call__ and instead
    #   calls task.run directly.
    # - so with the addition of current_task and the request stack
    #   BaseTask.__call__ now pushes to those stacks so that
    #   they work when tasks are called directly.
    #
    # The worker only optimizes away __call__ in the case
    # where it hasn't been overridden, so the request/task stack
    # will blow if a custom task class defines __call__ and also
    # calls super().
```
I'm not sure why this does seem to still break retries

https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L334
```python
def trace_task(uuid, args, kwargs, request=None):
    # ...
    # This function is very long because we've unrolled all the calls
    # for performance reasons,
```

https://github.com/celery/celery/blob/v4.1.0/celery/app/trace.py#L9
```python
# ## ---
# This is the heart of the worker, the inner loop so to speak.
# It used to be split up into nice little classes and methods,
# but in the end it only resulted in bad performance and horrible tracebacks,
# so instead we now use one closure per task class.
```

**Comment by auvipy** [comment]
feel free to contribute

**Comment by colosi** [comment]
@auvipy, submitted a PR for a doc fix.

**Comment by bob-r** [comment]
Is it correct to call self.run() in case of autoretry, when run is replaced. Should it be `getattr(self, '_orig_run', self.run)()` instead?
