### ISSUE TITLE
Incorrect migrate command in "Getting Started With Django" web tutorial

### ISSUE THREAD

**Issue by albydeca** [celery/celery#5659]
- [x ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues
(actually a pull request)
- https://github.com/celery/celery/pull/5437

#### Possible Duplicates

- None

# Description
Correct fix in #5437 has been merged yet still shows incorrect migration command on the website. https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

# Suggestions
Review the web page and make sure the change in the repo is reflected in the website.

**Comment by auvipy** [comment]
its will be visible when 4.4.0 will be released
