### ISSUE TITLE
Outdated testing docs?

### ISSUE THREAD

**Issue by gforcada** [celery/celery#5669]
# Checklist
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
It seems to me that the [testing documentation](https://github.com/celery/celery/blob/master/docs/userguide/testing.rst) is a bit outdated. At the very beginning you are given an example async task that has a `self.retry` on the `except` clause, which looks strange, as it is a function not a method of a class/instance.

Moreover when searching at how to handle tracebacks from tasks, I ended up at http://docs.celeryproject.org/en/latest/userguide/calling.html#linking-callbacks-errbacks which looks like the modern practice? :thinking: 

# Suggestions
Rework the first snippet of code and mention how to use linking from a testing perspective? :thinking:

**Comment by thedrow** [comment]
Specifying `@task(bind=True)` means that you do get a self argument as the first argument and can use the Task class' methods and attributes.

That code is correct.
Is there any other issue?
