### ISSUE TITLE
 Task object has no  custom attribute

### ISSUE THREAD

**Issue by kioipp** [celery/celery#5670]
Hi dear ,  I have to design a system like that :

```python

class sub_worker(Task):
    def run(self):
        self.countdown = 0
        while self.countdown < 30:
            self.countdown += 1
            time.sleep(10)

@celery.task(bind=True)
def root_manager(self):
    sub_worker_instance = celery.register_task(sub_worker())
    tick_count = 0
    sub_worker_instance.delay()
    while tick_count < 30:
        self.update_state(state='PROGRESS', meta=str(sub_worker_instance.countdown))
        tick_count += 1
        time.sleep(5)
```

When calling root_manger() , the error showed : 

> AttributeError: 'sub_worker_instance' object has no attribute 'countdown'

Is it a bug ? Or how could I update a sub celery task woker  custom info as meta in a main celery worker ?

Many thanks for this !

**Comment by shekhar-kamble** [comment]
Since celery is running in a different process, it needs to import any code that is going to run as a celery task. Since `run` is not called, `countdown` is not initialised in your object as of yet.
Also Your generated callable is only registered after the initiation of the celery process, so celery's way of moving around references to callables doesn't work.

However I can suggest a possible way

```
import celery
import time
c = celery.Celery()
class sub_worker(celery.Task):
    countdown = 0
    def run(self):
        while self.countdown < 30:
            self.countdown += 1
            time.sleep(10)

@c.task(bind=True)
def root_manager(self):
    tick_count = 0
    sub_worker_instance.delay()
    while tick_count < 30:
        self.update_state(state='PROGRESS', meta=str(sub_worker_instance.countdown))
        tick_count += 1
        time.sleep(5)

sub_worker_instance = c.register_task(sub_worker())
```

**Comment by thedrow** [comment]
If there's nothing more we can do here, I'm closing this issue.
Feel free to comment if you want me to reopen.
