### ISSUE TITLE
Can we modify how long finished tasks are kept in memory?

### ISSUE THREAD

**Issue by razabc** [celery/celery#5673]
Hi,

Running Celery 4.3.0.
I want to be able to get the status of a task (via AsyncResult) many hours after it has finished. Say, 24 or 48 hours past success or failure.

Currently, I noticed the task object gets deleted a few hours after it has finished (can't tell exactly how many, but less than 24 hours).

Is it possible?

Thanks.

**Comment by auvipy** [comment]
please post support questions to mailing list or IRC
