### ISSUE TITLE
Celery Worker Dies Completely Silently if Error Occurs During Startup

### ISSUE THREAD

**Issue by macdjord** [celery/celery#5691]
# Checklist

* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [ ] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
  * Forbidden by company policy
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: 4.2.1

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>
Cannot include this due to company security policy
</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>
Cannot include this due to company security policy
</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

* Set `broker_url` to an string without a protocol
* Start Celery worker with `multi start`, with a logfile specified with `--logfile=`
* `multi start` claims the worker started successfully, when in fact it died immediately. No error message is written to STDOUT or STDERR and nothing at all is written to the logfile

</p>
</details>

# Expected Behavior

* **At least one** of the following:
  * `multi start` reports the worker _did not_ start successfully
  * An error message or traceback is written to STDOUT or STDERR
  * The error is recorded in the logfile

# Actual Behavior

```text
[REDACTED_PROMPT]$ ~/tools/python/bin/celery multi start worker -A [REDACTED_PACKAGE].celery:APP --pidfile=celery-worker.pid --logfile=celery-worker.log --detach -O fair -l debug
celery multi v4.2.1 (windowlicker)
> Starting nodes...
        > worker@[REDACTED_HOST]: OK
[REDACTED_PROMPT]$ # multi start reports the worker started successfully, and no error message was printed, yet...
[REDACTED_PROMPT]$ ps -aux | grep celery  
foo_user 17792  0.0  0.0   9092   676 pts/0    S+   19:29   0:00 grep --color=auto celery
[REDACTED_PROMPT]$ # The worker is not running
[REDACTED_PROMPT]$ cat celery-worker.log
[REDACTED_PROMPT]$ # And nothing is in the log, either
```

**Comment by auvipy** [comment]
could you please try celery 4.3 or 4.4.0rc3? I am not sure it's your code or celery issue. You should post to https://groups.google.com/forum/#!forum/celery-users first to verify its a celery issue at all.

**Comment by macdjord** [comment]
@auvipy:

- Confirmed in 4.3
- The fact that Celery died was my fault - I had an invalid 'broker_url'. The fact that it died *without emitting any sort of error message* is a celery issue.

**Comment by auvipy** [comment]
confirmed with celery 4.4.0rc3 as well?

**Comment by macdjord** [comment]
@auvipy: Confirmed with 4.4.0rc3.

**Comment by auvipy** [comment]
> @auvipy: Confirmed with 4.4.0rc3.

can you confirm this again with celery 4.4.6/5.x.x release?

**Comment by odoublewen** [comment]
Using celery-5.1.1 I've also come across this behavior:  `celery multi start` just starts and then exits -- without even a non-zero exit code.

```
$ celery multi start w1 -A myapp.celery --logfile=/path/to/my/celery.log -c 2 -Q long,short,default
celery multi v5.1.1 (sun-harmonics)
> Starting nodes...
        > w1@node1: OK

$ echo $?
0
```

No doubt I've got something misconfigured, but this behavior makes diagnosis very difficult.

**Comment by palfrey** [comment]
Possibly related to https://github.com/celery/celery/issues/7358 which is now fixed on master

**Comment by auvipy** [comment]
> Possibly related to #7358 which is now fixed on master

closing as per this
