### ISSUE TITLE
Unable to install celery 4.3.0, 4.4.0rc3 or master on python 2.7.16

### ISSUE THREAD

**Issue by chrissinclairedited** [celery/celery#5699]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
v4.3.3 and v4.4.0rc3
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
<empty>
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
python2 -m pip install celery==4.3.0
```

</p>
</details>

# Expected Behavior

Celery package installs

# Actual Behavior

Celery package fails to install when installing `more-itertools`, from `zipp`, from `importlib-metadata`, from `kombu`:

```
> python2 --verson
Python 2.7.16

> python2 -m pip --version
pip 19.2.3 from <venv directory>

> python2 -m pip install celery==4.3.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, http://pypi.edtd.net/EDITED/dev/
Collecting celery==4.3.0
  Using cached https://files.pythonhosted.org/packages/5c/a1/a3dd9d8bfa09156ec2cba37f90accf35c0f4ecc3980d96cb4fb99e56504b/celery-4.3.0-py2.py3-none-any.whl
Collecting pytz>dev (from celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Collecting billiard<4.0,>=3.6.0 (from celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/68/1d/2aea8fbb0b1e1260a8a2e77352de2983d36d7ac01207cf14c2b9c6cc860e/billiard-3.6.1.0.tar.gz
Collecting vine>=1.3.0 (from celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Collecting kombu<5.0,>=4.4.0 (from celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/bb/22/58104fd214fb32008f2f4d64a1918c81e353f23e7beee9605674f9ecd6b2/kombu-4.6.4-py2.py3-none-any.whl
Collecting amqp<3.0,>=2.5.1 (from kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/a1/ef/a62ff9dde89e6b75976a746aa5b828ccb3c839ac6fcdc283edd88d7cf90b/amqp-2.5.1-py2.py3-none-any.whl
Collecting importlib-metadata>=0.18 (from kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/ad/aa/25fcbded2ab4ed4ff3071d1e000cd4f8f9c65653d2d7157dd105a8e81d42/importlib_metadata-0.19-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting configparser>=3.5; python_version < "3" (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/ab/1a/ec151e5e703ac80041eaccef923611bbcec2b667c20383655a06962732e9/configparser-3.8.1-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting pathlib2; python_version == "3.4.*" or python_version < "3" (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0)
  Using cached https://files.pythonhosted.org/packages/67/c6/4dbf5dfdbe1140cadf765c3896acc098578626c35721bc7d3eb35f6a8fc1/pathlib2-2.3.4-py2.py3-none-any.whl
Collecting more-itertools (from zipp>=0.5->importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0)
  Downloading http://pypi.edtd.net/root/pypi/%2Bf/409/cd48d4db7052a/more-itertools-7.2.0.tar.gz (73kB)
     |████████████████████████████████| 81kB 1.0MB/s
ERROR: Package 'more-itertools' requires a different Python: 2.7.16 not in '>=3.4'
```

**Comment by auvipy** [comment]
this is not a celery issue. please upgrade your pip.

**Comment by chrissinclairedited** [comment]
Not sure I follow - as per the output I'm using `pip 19.2.3`, which is the latest per https://pypi.org/project/pip/#history?

**Comment by wyaadarsh** [comment]
This isn't a pip issue because i am on latest pip and still getting same issue. It has something to do with conflicting requirements with other packages from requirements file. I am able to install it using easy_install after removing it from requirements.txt. Please help

**Comment by auvipy** [comment]
try celery==4.4.2?

**Comment by Akash1602** [comment]
its not working

**Comment by auvipy** [comment]
python 2 is not supported use python 3.7+ and celery 5.1.x or 5.2.0rc1
