### ISSUE TITLE
Manage celery v3 and v4 parallely

### ISSUE THREAD

**Issue by sp1rs** [celery/celery#5701]
I have 2 micro-service. 1 service runs on celery v3.1.25 and the 2nd service runs on celery v4.2.1
**The celery broker and result backend is same on both the service.**

What our current flow is, we are call a task in service 1 and fetching the result of it in service 2.
(Service 2 knows the `task_id`).

While fetching the data in service 2, we face with the below error.
```
DecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Any idea how to fix this problem?

**Comment by auvipy** [comment]
Please post support questions to the celery-users mailing list or #celery IRC channel
