### ISSUE TITLE
Celery's ssl_cert_reqs names do not match Redis's

### ISSUE THREAD

**Issue by arel** [celery/celery#5702]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- #5371 this issue has to do with confusion about specifying `ssl_cert_reqs` as a constant (`ssl.CERT_REQUIRED` versus a string `'CERT_REQUIRED'`.)

#### Possible Duplicates

- None

# Brief Summary

The official redis python library expects `ssl_cert_reqs` to be one of: `'none'`, `'optional'`, or `'required'`.

See: https://github.com/andymccurdy/redis-py/blob/3.3.7/redis/connection.py#L793

Celery expects this to be one of `'CERT_NONE'`, `'CERT_OPTIONAL'`, or `'CERT_REQUIRED'`.

This can lead to confusion because the same redis URL cannot be used for both celery, with a redis backend, and redis directly.

For example, the following redis urls are incompatible:

```bash
"rediss://:${REDIS_TOKEN}@${REDIS_HOST}?ssl_cert_reqs=none"  # works for redis, not celery
"rediss://:${REDIS_TOKEN}@${REDIS_HOST}?ssl_cert_reqs=CERT_NONE"  # works for celery, not redis
```

This confusion could be avoided by reconciling the two formats.

To avoid future confusion, and remaining backward compatible, I propose _at a minimum_ letting celery recognize the redis `ssl_cert_reqs` strings.

Ideally, the documentation would also be updated to prefer the standard redis strings (mentioning that the `CERT_*` strings are also valid but deprecated).

# Design

## Architectural Considerations

None

## Proposed Behavior

Change celery to map both formats to the same value, such as:

```python
            ssl_string_to_constant = {'CERT_REQUIRED': CERT_REQUIRED,
                                      'CERT_OPTIONAL': CERT_OPTIONAL,
                                      'CERT_NONE': CERT_NONE,
                                      'required': CERT_REQUIRED,
                                      'optional': CERT_OPTIONAL,
                                      'none': CERT_NONE}
```

## Diagrams

N/A

## Alternatives

Live with the disparity of URL formats and make it painfully clear in the documentation that celery's choice is non-standard.

**Comment by Roman513** [comment]
Hello!
Now redis-py library have `ssl_cert_reqs="required"` by default that makes `ssl_cert_reqs` optional. So if we have properly configured redis URL for redis-py it could not work with Celery. Maybe it is worth to make the same defaults in celery backends and celery broker.

About broker: currently documentation is kind of vague for broker URLs. It is not clear is it possible to use the same `ssl_cert_reqs` parameter or it is required to use separate `broker_use_ssl` parameter with rediss:// scheme or not nd which defaults do we have here. I guess better to make it consistent.
