### ISSUE TITLE
Missed AMQP heartbeats on long running tasks

### ISSUE THREAD

**Issue by mprahl** [celery/celery#5707]
One of my Celery tasks calls `subprocess.run`, which can take a few minutes to complete. During this time, I've noticed the following in the RabbitMQ logs when running this locally:
```
rabbitmq_1        | 2019-08-30 18:54:25.268 [error] <0.650.0> closing AMQP connection <0.650.0> (172.19.0.5:53526 -> 172.19.0.4:5672):
rabbitmq_1        | missed heartbeats from client, timeout: 60s
rabbitmq_1        | 2019-08-30 18:55:21.020 [error] <0.675.0> closing AMQP connection <0.675.0> (172.19.0.6:45400 -> 172.19.0.4:5672):
rabbitmq_1        | missed heartbeats from client, timeout: 60s
```

I'm using version 4.2.1 of Celery and version 2.5.0 of PyAMQP.

How does the AMQP heartbeat work? Does it run on a separate thread? Any suggestions to resolve the issue?

Thank you for your help and please let me know if I need to direct this question elsewhere.

**Comment by auvipy** [comment]
try celery==4.4.0rc3 plz & report

**Comment by thomas-riccardi** [comment]
@mprahl so is it resolved with celery 4.4.0rc3 ?

**Comment by drfb** [comment]
I ran into this issue using version 4.3.0 of celery. It also causes memory leak as discussed in #4843 (leak happens during rabbitmq reconnection).

4.4.0rc3 resolves the missed heartbeat issue and minimizes the leak. I'll either use rc3 and wait for 4.4.0 or downgrade to 4.1

**Comment by auvipy** [comment]
can you try celery==4.4.0rc4?
