### ISSUE TITLE
Why does Celery block during GroupResult get() call?

### ISSUE THREAD

**Issue by dave7280** [celery/celery#5709]
Hi,

Python version: 3.7.3
Celery version: 4.3.0
ResultBroker: redis
CeleryBroker: redis
OS: Ubuntu 18.04 x64

I dont understand why following code blocks?

1. The code blocks at second **_get()_** call in **GroupResult**, after restoring  task with same ID again.
2. The block happens only, when another function such as **ready()** is being called, right before using **get()**
3. If we delete line having **ready()**, the code is not gonna block.
4. If you try to do same thing with **AsyncResult**, instead of **GroupResult** - it's not gonna block. Only **GroupResult** blocks.

GroupResult example (it blocks):

```


app = Celery('tasks', backend='redis://localhost', broker='redis://localhost')

gr = GroupResult.restore('5af1c3c4-f522-452b-a053-602ccab91fff')
print("TRY1 START")
print(gr.ready())
print(gr.get())
print("TRY1 FINISHED")

gr = GroupResult.restore('5af1c3c4-f522-452b-a053-602ccab91fff')

print("TRY2 START")
print(gr.ready())
print(gr.get()) //BLOCKS HERE
print("TRY2 FINISHED")
```

Console output:

> TRY1 START
> True
> MINE RESULT HERE
> TRY1 FINISHED
> TRY2 START
> True

Now with AsyncResult (this does not block)

```
gr = AsyncResult('bcf8392d-ff97-4aad-9790-a6a7b1a0bd92')
print("TRY1 START")
print(gr.ready ())
print(gr.get ())
print("TRY1 FINISHED")

gr = AsyncResult('bcf8392d-ff97-4aad-9790-a6a7b1a0bd92')
print("TRY2 START")
print(gr.ready ())
print(gr.get()) //Does NOT block.
print("TRY2 FINISHED")
```

> TRY1 START
> True
> MINE RESULT HERE
> TRY1 FINISHED
> TRY2 START
> True
> MINE RESULT HERE
> TRY2 FINISHED

I'd like to retrieve GroupResult status (such as ready() and if ready() then display results) using web API i'm writing. However because of such behaviour, on second request for same task id.. everything hangs.
Any solutions?

//I found out i can just use GroupResult.results instead of get(), but still curious why does it block.

**Comment by auvipy** [comment]
plz, post support question to the celery-users mailing list or IRC channel first.
