### ISSUE TITLE
Appveyor builds fail because of windows and a test I added a while back

### ISSUE THREAD

**Issue by matteius** [celery/celery#5711]
When we accepted one of my prior works to fix 
I added two tests `test_with_autoscaler_file_descriptor_safety` and `test_with_file_descriptor_safety`  here:  https://github.com/celery/celery/blame/master/t/unit/worker/test_worker.py#L797

These two tests have always caused the appveyor build to crash at that point because it runs on Windows, and I recall having worked on the underlying windows socket issue when I was submitting that prior PR but I didn't quite get it figured out.   I am reporting this to track that it still needs to get resolved, and to try and recall what I remember the issues were about it.

Apparently I lost whatever branches I had on that progress, but it had something to do with how windows initializes blocking/non-blocking pipes differently than unix pipes.    I will update this issue when I figure out more about what was happening again, but you can see an example here of: t\unit\worker\test_worker.py ..................................s......Command exited with code 1

https://ci.appveyor.com/project/ask/celery/builds/26904785/job/628wbsjwqefqtsbu

Most appveyor builds get far enough to get that failure I helped introduced, and so I want to help fix it without destroying those tests because they pass in linux.

**Comment by matteius** [comment]
Ok running locally I can get the individual stack traces on Windows:

fetytest t/unit/worker/test_worker.py -k test_with_autoscaler_file_descriptor_saf
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\matteius\projects\celery_matt, inifile: setup.cfg
plugins: case-1.5.3
collected 67 items / 66 deselected / 1 selected

t\unit\worker\test_worker.py FE                                          [100%]

=================================== ERRORS ====================================
_ ERROR at teardown of test_WorkController.test_with_autoscaler_file_descriptor_safety _

tp = <class 'AssertionError'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
>           raise value

..\..\.virtualenvs\celery\lib\site-packages\six.py:693:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

request = <SubRequest 'threads_not_lingering' for <Function test_with_autoscaler_file_descriptor_safety>>

    @pytest.fixture(autouse=True)
    def threads_not_lingering(request):
        yield
>       assert request.session._threads_at_startup == alive_threads()
E       AssertionError: assert [<_MainThread(MainThread, started 16332)>] == [<_MainThread(MainThread, started 16332)>, <Supervisor(Thread-3, started daemon 10956)>, <TaskHandler(Thread-4, started daemon 9176)>, <TimeoutHandler(Thread-5, started daemon 1692)>, <ResultHandler(Thread-6, started daemon 12744)>]
E        +  where [<_MainThread(MainThread, started 16332)>] = <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1>._threads_at_startup
E        +    where <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1> = <SubRequest 'threads_not_lingering' for <Function test_with_autoscaler_file_descriptor_safety>>.session
E        +  and   [<_MainThread(MainThread, started 16332)>, <Supervisor(Thread-3, started daemon 10956)>, <TaskHandler(Thread-4, started daemon 9176)>, <TimeoutHandler(Thread-5, started daemon 1692)>, <ResultHandler(Thread-6, started daemon 12744)>] = alive_threads()

t\unit\conftest.py:168: AssertionError
================================== FAILURES ===================================
_______ test_WorkController.test_with_autoscaler_file_descriptor_safety _______

self = <t.unit.worker.test_worker.test_WorkController object at 0x0000022212BD9400>

    @pytest.mark.nothreads_not_lingering
    @mock.sleepdeprived(module=autoscale)
    def test_with_autoscaler_file_descriptor_safety(self):
        # Given: a test celery worker instance with auto scaling
        worker = self.create_worker(
            autoscale=[10, 5], use_eventloop=True,
            timer_cls='celery.utils.timer2.Timer',
            threads=False,
        )
        # Given: This test requires a QoS defined on the worker consumer
        worker.consumer.qos = qos = QoS(lambda prefetch_count: prefetch_count, 2)
        qos.update()

        # Given: We have started the worker pool
        worker.pool.start()

        # Then: the worker pool is the same as the autoscaler pool
        auto_scaler = worker.autoscaler
        assert worker.pool == auto_scaler.pool

        # Given: Utilize kombu to get the global hub state
        hub = get_event_loop()
        # Given: Initial call the Async Pool to register events works fine
        worker.pool.register_with_event_loop(hub)

        # Create some mock queue message and read from them
        _keep = [Mock(name='req{0}'.format(i)) for i in range(20)]
        [state.task_reserved(m) for m in _keep]
        auto_scaler.body()

        # Simulate a file descriptor from the list is closed by the OS
        # auto_scaler.force_scale_down(5)
        # This actually works -- it releases the semaphore properly
        # Same with calling .terminate() on the process directly
>       for fd, proc in worker.pool._pool._fileno_to_outq.items():
E       AttributeError: 'Pool' object has no attribute '_fileno_to_outq'

t\unit\worker\test_worker.py:829: AttributeError
============================== warnings summary ===============================
c:\users\matteius\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334
  c:\users\matteius\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.nothreads_not_lingering - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 1 failed, 66 deselected, 1 warnings, 1 error in 0.66 seconds =========
(celery)

**Comment by matteius** [comment]
matt.davis@MBP-1014333 MINGW64 ~/shared-projects/celery_matt (master)
$ pytest t/unit/worker/test_worker.py -k test_with_file_descriptor_safety
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\matt.davis\shared-projects\celery_matt, inifile: setup.cfg
plugins: case-1.5.3
collected 67 items / 66 deselected / 1 selected

t\unit\worker\test_worker.py FE                                          [100%]

=================================== ERRORS ====================================
__ ERROR at teardown of test_WorkController.test_with_file_descriptor_safety __

tp = <class 'AssertionError'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
>           raise value

..\..\.virtualenvs\celery\lib\site-packages\six.py:693:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

request = <SubRequest 'threads_not_lingering' for <Function test_with_file_descriptor_safety>>

    @pytest.fixture(autouse=True)
    def threads_not_lingering(request):
        yield
>       assert request.session._threads_at_startup == alive_threads()
E       AssertionError: assert [<_MainThread(MainThread, started 19220)>] == [<_MainThread(MainThread, started 19220)>, <Supervisor(Thread-3, started daemon 20376)>, <TaskHandler(Thread-4, started daemon 20776)>, <TimeoutHandler(Thread-5, started daemon 19744)>, <ResultHandler(Thread-6, started daemon 5852)>]
E        +  where [<_MainThread(MainThread, started 19220)>] = <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1>._threads_at_startup
E        +    where <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1> = <SubRequest 'threads_not_lingering' for <Function test_with_file_descriptor_safety>>.session
E        +  and   [<_MainThread(MainThread, started 19220)>, <Supervisor(Thread-3, started daemon 20376)>, <TaskHandler(Thread-4, started daemon 20776)>, <TimeoutHandler(Thread-5, started daemon 19744)>, <ResultHandler(Thread-6, started daemon 5852)>] = alive_threads()

t\unit\conftest.py:168: AssertionError
================================== FAILURES ===================================
____________ test_WorkController.test_with_file_descriptor_safety _____________

self = <t.unit.worker.test_worker.test_WorkController object at 0x0000024E23089320>

    @pytest.mark.nothreads_not_lingering
    @mock.sleepdeprived(module=autoscale)
    def test_with_file_descriptor_safety(self):
        # Given: a test celery worker instance
        worker = self.create_worker(
            autoscale=[10, 5], use_eventloop=True,
            timer_cls='celery.utils.timer2.Timer',
            threads=False,
        )

        # Given: This test requires a QoS defined on the worker consumer
        worker.consumer.qos = qos = QoS(lambda prefetch_count: prefetch_count, 2)
        qos.update()

        # Given: We have started the worker pool
        worker.pool.start()

        # Given: Utilize kombu to get the global hub state
        hub = get_event_loop()
        # Given: Initial call the Async Pool to register events works fine
        worker.pool.register_with_event_loop(hub)

        # Given: Mock the Hub to return errors for add and remove
        def throw_file_not_found_error(*args, **kwargs):
            raise OSError()

        hub.add = throw_file_not_found_error
        hub.add_reader = throw_file_not_found_error
        hub.remove = throw_file_not_found_error

        # When: Calling again to register with event loop ...
        worker.pool.register_with_event_loop(hub)
>       worker.pool._pool.register_with_event_loop(hub)
E       AttributeError: 'Pool' object has no attribute 'register_with_event_loop'

t\unit\worker\test_worker.py:876: AttributeError
============================== warnings summary ===============================
c:\users\matt.davis\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334
  c:\users\matt.davis\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.nothreads_not_lingering - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 1 failed, 66 deselected, 1 warnings, 1 error in 0.42 seconds =========
(celery)
matt.davis@MBP-1014333 MINGW64 ~/shared-projects/celery_matt (master)
$

**Comment by matteius** [comment]
matteius@MBP-1014333 MINGW64 ~/projects/celery_matt (master)
$ pytest t/unit/worker/test_worker.py -k test_with_file_descriptor_safety
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\matteius\projects\celery_matt, inifile: setup.cfg
plugins: case-1.5.3
collected 67 items / 66 deselected / 1 selected

t\unit\worker\test_worker.py FE                                          [100%]

=================================== ERRORS ====================================
__ ERROR at teardown of test_WorkController.test_with_file_descriptor_safety __

tp = <class 'AssertionError'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
>           raise value

..\..\.virtualenvs\celery\lib\site-packages\six.py:693:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
..\..\.virtualenvs\celery\lib\site-packages\six.py:693: in reraise
    raise value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

request = <SubRequest 'threads_not_lingering' for <Function test_with_file_descriptor_safety>>

    @pytest.fixture(autouse=True)
    def threads_not_lingering(request):
        yield
>       assert request.session._threads_at_startup == alive_threads()
E       AssertionError: assert [<_MainThread(MainThread, started 19220)>] == [<_MainThread(MainThread, started 19220)>, <Supervisor(Thread-3, started daemon 20376)>, <TaskHandler(Thread-4, started daemon 20776)>, <TimeoutHandler(Thread-5, started daemon 19744)>, <ResultHandler(Thread-6, started daemon 5852)>]
E        +  where [<_MainThread(MainThread, started 19220)>] = <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1>._threads_at_startup
E        +    where <Session celery_matt exitstatus=0 testsfailed=1 testscollected=1> = <SubRequest 'threads_not_lingering' for <Function test_with_file_descriptor_safety>>.session
E        +  and   [<_MainThread(MainThread, started 19220)>, <Supervisor(Thread-3, started daemon 20376)>, <TaskHandler(Thread-4, started daemon 20776)>, <TimeoutHandler(Thread-5, started daemon 19744)>, <ResultHandler(Thread-6, started daemon 5852)>] = alive_threads()

t\unit\conftest.py:168: AssertionError
================================== FAILURES ===================================
____________ test_WorkController.test_with_file_descriptor_safety _____________

self = <t.unit.worker.test_worker.test_WorkController object at 0x0000024E23089320>

    @pytest.mark.nothreads_not_lingering
    @mock.sleepdeprived(module=autoscale)
    def test_with_file_descriptor_safety(self):
        # Given: a test celery worker instance
        worker = self.create_worker(
            autoscale=[10, 5], use_eventloop=True,
            timer_cls='celery.utils.timer2.Timer',
            threads=False,
        )

        # Given: This test requires a QoS defined on the worker consumer
        worker.consumer.qos = qos = QoS(lambda prefetch_count: prefetch_count, 2)
        qos.update()

        # Given: We have started the worker pool
        worker.pool.start()

        # Given: Utilize kombu to get the global hub state
        hub = get_event_loop()
        # Given: Initial call the Async Pool to register events works fine
        worker.pool.register_with_event_loop(hub)

        # Given: Mock the Hub to return errors for add and remove
        def throw_file_not_found_error(*args, **kwargs):
            raise OSError()

        hub.add = throw_file_not_found_error
        hub.add_reader = throw_file_not_found_error
        hub.remove = throw_file_not_found_error

        # When: Calling again to register with event loop ...
        worker.pool.register_with_event_loop(hub)
>       worker.pool._pool.register_with_event_loop(hub)
E       AttributeError: 'Pool' object has no attribute 'register_with_event_loop'

t\unit\worker\test_worker.py:876: AttributeError
============================== warnings summary ===============================
c:\users\matteius\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334
  c:\users\matteius\.virtualenvs\celery\lib\site-packages\_pytest\mark\structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.nothreads_not_lingering - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 1 failed, 66 deselected, 1 warnings, 1 error in 0.42 seconds =========
(celery)

**Comment by matteius** [comment]
So in linux this worked, but in Windows `worker.pool._pool.register_with_event_loop(hub)` gets E AttributeError: 'Pool' object has no attribute 'register_with_event_loop'  for both of these tests, any ideas why?

**Comment by auvipy** [comment]
probably kombu master with celery worth a try?

**Comment by matteius** [comment]
@auvipy It was worth a try and actually is what my above stack trace is based off of in Windows 10 git shell (mingw64) -- I was actually surprised celery bootstrapped just fine the default and test requirements and then I uninstalled kombu and installed the latest master as an egg, ran pytest and got the above stack trace.  I created a new python 3.7.1 virtualenv with the following thats installed:
```$ pip freeze
amqp==2.5.1
asn1crypto==0.24.0
aspy.yaml==1.3.0
atomicwrites==1.3.0
attrs==19.1.0
aws-xray-sdk==0.95
billiard==3.6.1.0
boto==2.49.0
boto3==1.9.220
botocore==1.12.220
case==1.5.3
certifi==2019.6.16
cffi==1.12.3
cfgv==2.0.1
chardet==3.0.4
colorama==0.4.1
cryptography==2.7
docker==4.0.2
docutils==0.15.2
ecdsa==0.13.2
future==0.17.1
identify==1.4.7
idna==2.8
importlib-metadata==0.20
Jinja2==2.10.1
jmespath==0.9.4
jsondiff==1.1.1
jsonpickle==1.2
-e git+git@github.com:matteius/kombu.git@a2704c7f76a1563e0c1b72727f331c4a573a9b7c#egg=kombu
linecache2==1.0.0
MarkupSafe==1.1.1
mock==3.0.5
more-itertools==7.2.0
moto==1.3.7
msgpack==0.6.1
nodeenv==1.3.3
nose==1.3.7
packaging==19.1
pluggy==0.12.0
pre-commit==1.18.3
py==1.8.0
pyaml==19.4.1
pycparser==2.19
pycryptodome==3.9.0
pyparsing==2.4.2
pypiwin32==223
pytest==4.6.5
python-dateutil==2.8.0
python-jose==2.0.2
pytz==2019.2
pywin32==224
PyYAML==5.1.2
requests==2.22.0
responses==0.10.6
s3transfer==0.2.1
six==1.12.0
toml==0.10.0
traceback2==1.4.0
unittest2==1.1.0
urllib3==1.25.3
vine==1.3.0
virtualenv==16.7.4
wcwidth==0.1.7
websocket-client==0.56.0
Werkzeug==0.15.5
wrapt==1.11.2
xmltodict==0.12.0
zipp==0.6.0
```

I think that something on windows either by default or a bug is causing the 
E AttributeError: 'Pool' object has no attribute 'register_with_event_loop'

**Comment by matteius** [comment]
Made some progress on this -- it seems that on Windows 10, my test `test_with_file_descriptor_safety` the lines referencing `worker.pool._pool` resolve to different classes on linux vs windows.  For Windows 10 its a billiard Pool
<billiard.pool.Pool object at 0x0000021E6D132588>
<class 'billiard.pool.Pool'>
Whereas in Linux its a Celery AsyncPool:
<celery.concurrency.asynpool.AsynPool object at 0x7f4ab1ea9e10>
<class 'celery.concurrency.asynpool.AsynPool'>

In both cases `worker.pool` are the same `celery.concurrency.prefork.TaskPool` so I think something is going on with the _pool.   Maybe someone else knows more than me about this?

**Comment by matteius** [comment]
OK here is the problem -- in conjunction with my last comment, here is the line that determines which Pool to use:  `Pool = (self.BlockingPool if self.options.get('threads', True) else self.Pool)`
https://github.com/celery/celery/blob/master/celery/concurrency/prefork.py#L105

So for windows, which uses threads, it will use the `self.BlockingPool` which is just from billiard `from billiard.pool import Pool as BlockingPool` whereas `self.Pool` which linux will use by default, gets self.Pool which is Celery's own sub-class of billiard Pool `AsynPool` which has the method on_poll_start and some others that BlockingPool don't have.

For the record and as expected, if I try to just use AsynPool for Windows, I get:
        # Given: We have started the worker pool
>       worker.pool.start()

t\unit\worker\test_worker.py:859:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
celery\concurrency\base.py:132: in start
    self.on_start()
celery\concurrency\prefork.py:116: in on_start
    **self.options)
celery\concurrency\asynpool.py:448: in __init__
    self.create_process_queues(): None for _ in range(processes)
celery\concurrency\asynpool.py:448: in <dictcomp>
    self.create_process_queues(): None for _ in range(processes)
celery\concurrency\asynpool.py:1111: in create_process_queues
    inq = _SimpleQueue(wnonblock=True)
..\..\.virtualenvs\celery\lib\site-packages\billiard\queues.py:339: in __init__
    duplex=False, rnonblock=rnonblock, wnonblock=wnonblock,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

duplex = False, rnonblock = False, wnonblock = True

    def Pipe(duplex=True, rnonblock=False, wnonblock=False):
        '''
        Returns pair of connection objects at either end of a pipe
        '''
        assert not rnonblock, 'rnonblock not supported on windows'
>       assert not wnonblock, 'wnonblock not supported on windows'
E       AssertionError: wnonblock not supported on windows

**Comment by mchataigner** [comment]
This has been fixed on master by ignoring file_descriptor_safety tests on windows ;) as it's using BlockingPool and not AsyncPool as you mentioned.

**Comment by auvipy** [comment]
python 38 builds has been canceled
