### ISSUE TITLE
Performance Problem (long running task)

### ISSUE THREAD

**Issue by fatihhcelik** [celery/celery#5725]
I have function to scan all ports for a given ip. It takes 5-10 seconds to complete without celery but if I use the celery to run this function, it takes approximately 15 minutes. I observed that function without celery consuming approximately %90 cpu power but with celery this value is %2-%3 so task takes 15 minutes to finish. This causes a serious performance problem for me. How to increase a cpu power for a specific task or any idea to solve this problem?

**Comment by auvipy** [comment]
post questions to celery-user mailing list/celery IRC channel on Freenode.
