### ISSUE TITLE
Using exchange with blank routing key fails to deliver on RabbitMQ

### ISSUE THREAD

**Issue by bivald** [celery/celery#5728]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None (I've looked, don't see any, probably to odd corner case)

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: celery==4.3.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
Sorry, I don't have a celery project setup. The error is when using send_task (the worker and the queuer of the tasks doesn't share any code base)
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: Unknown (I'm on 3.6.3)
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
alembic==1.1.0
amqp==2.5.1
billiard==3.6.1.0
blinker==1.4
cachetools==3.1.1
celery==4.3.0
certifi==2019.9.11
chardet==3.0.4
Click==7.0
debtcollector==1.22.0
Flask==1.0.2
Flask-Classful==0.13.1
Flask-JSON==0.3.0
Flask-Migrate==2.0.1
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.0
gcloud==0.18.3
google-api-core==1.14.2
google-api-python-client==1.7.9
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-cloud-core==1.0.3
google-cloud-datastore==1.8.0
google-cloud-pubsub==1.0.0
google-cloud-storage==1.16.1
google-resumable-media==0.4.0
googleapis-common-protos==1.6.0
grpc-google-iam-v1==0.12.3
grpcio==1.9.1
gunicorn==19.6.0
httplib2==0.13.1
idna==2.8
importlib-metadata==0.22
itsdangerous==1.1.0
Jinja2==2.10.1
kombu==4.6.4
Mako==1.1.0
MarkupSafe==1.1.1
monotonic==1.5
more-itertools==7.2.0
oauth2client==4.0.0
pbr==5.4.3
protobuf==3.6.1
psycopg2==2.7.3.2
psycopg2-binary==2.8.3
pyasn1==0.4.7
pyasn1-modules==0.2.6
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.2
PyYAML==3.12
ratelimitingfilter==0.5.dev1
raven==6.10.0
requests==2.22.0
rsa==4.0
six==1.11.0
SQLAlchemy==1.3.8
statsd==3.3.0
tenacity==3.4.0
uritemplate==3.0.0
urllib3==1.25.3
vine==1.3.0
Werkzeug==0.15.6
wrapt==1.11.2
zipp==0.6.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
1. Setup an exchange with a blank routing key in Rabbitmq

```python
celeryapp.send_task("task, ["data"],exchange="your_exchange",routing_key='',connection=conn)
```

</p>
</details>

# Expected Behavior

I would expect a message sent with an exchange and a blank (but not None) routing key to be sent using the exchange and the blank routing key. 

# Actual Behavior

Background:
Due to legacy reasons I'm not capable of changing the routing structure in RabbitMQ.

Using a blank routing key, the message is sent to the default queue. The issue originates from [amqp.py](https://github.com/celery/celery/blob/master/celery/app/amqp.py#L529):

```python
            if (not exchange or not routing_key) and exchange_type == 'direct':
                exchange, routing_key = '', qname
``` 

Using not discards the blank routing key. 

I am not too well versed on advanced routing, but if you want to I can try to create a pull request changing it to:

```python
            if (not exchange or routing_key is None) and exchange_type == 'direct':
                exchange, routing_key = '', qname
``` 

As a quirky short term work around, you can do:

```python
celeryapp.send_task(
    "task", 
    ["data"],
    exchange="your_exchange",
    routing_key='',
    exchange_type='anything_but_direct_here',
    connection=conn
)
```

Which won't trigger the offending if-bransch. 

I'm mostly creating this ticket so future Googlers can find it if they have the same problem. If you would accept a PR let me know.

**Comment by auvipy** [comment]
if you can provide a failing test case with the suggested change, it would be easier for us to comment about it

**Comment by AndrewWinterman** [comment]
this is a really old issue, but:

a direct exchange uses the queue name as the routing key. You cannot bind a queue with the empty name (the server generates a name), so this is working as intended for a direct exchange.

**Comment by loucadufault** [comment]
^ the above is false. This is the case for default exchanges, not direct exchanges.

Ref: https://www.rabbitmq.com/tutorials/amqp-concepts#exchange-default

**Comment by auvipy** [comment]
you can come with a failing test and a possible fix in a draft PR if you think it is an issue.
