### ISSUE TITLE
Finalized flag set as True in app inside task

### ISSUE THREAD

**Issue by HHead26** [celery/celery#5740]
from celery import Celeryapp = Celery()app.conf.update (    enable_utc=True,    timezone='UTC')app.conf.beat_schedule = {    'test': {        'task': 'test',        'schedule': 5,    }}@app.task(bind=True, name='test')def test(self):    if self.app.finalized:        raise ValueError("APP finalized.")
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: v4.3.0

<details>
<summary><b><code>celery -A example worker -B -E --loglevel=info</code> Output:</b></summary>
<p>

 -------------- celery@user v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Linux-5.2.11-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine 2019-09-19 16:57:03
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f88ce002978
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . test

[2019-09-19 16:57:03,962: INFO/Beat] beat: Starting...
[2019-09-19 16:57:03,993: INFO/Beat] Scheduler: Sending due task test (test)
[2019-09-19 16:57:04,083: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2019-09-19 16:57:04,096: INFO/MainProcess] mingle: searching for neighbors
[2019-09-19 16:57:05,149: INFO/MainProcess] mingle: all alone
[2019-09-19 16:57:05,186: INFO/MainProcess] celery@user ready.
[2019-09-19 16:57:05,186: INFO/MainProcess] Received task: test[73cb77be-6111-4a61-a882-32b4ccd7890e]  
[2019-09-19 16:57:05,290: ERROR/ForkPoolWorker-5] Task test[73cb77be-6111-4a61-a882-32b4ccd7890e] raised unexpected: ValueError('APP finalized.',)
Traceback (most recent call last):
  File "/misc-VAl3-rUJ/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/misc-VAl3-rUJ/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/.../example.py", line 19, in test
    raise ValueError("APP finalized.")
ValueError: APP finalized.

</p>
</details>

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
-i https://pypi.org/simple
amqp==2.5.1
billiard==3.6.1.0
celery==4.3.0
importlib-metadata==0.23
kombu==4.6.4
more-itertools==7.2.0
pytz==2019.2
vine==1.3.0
zipp==0.6.0
```

</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery()
app.conf.update (
    enable_utc=True,
    timezone='UTC')

app.conf.beat_schedule = {
    'test': {
        'task': 'test',
        'schedule': 5,
    }
}


@app.task(bind=True, name='test')
def test(self):
    if self.app.finalized:
        raise ValueError("APP finalized.")
```

</p>
</details>

# Expected Behavior

I expected that the app.finalized be false, once that the app itself is running this task.

# Actual Behavior

Flag is True

**Comment by auvipy** [comment]
can you verify this with celery master or 4.4.0rc3?
