### ISSUE TITLE
CELERY_TASK_ANNOTATIONS or CELERY_ANNOTATIONS

### ISSUE THREAD

**Issue by AbdealiJK** [celery/celery#5741]
# Checklist
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

# Description
I was trying to add "task_annotations" to my celery configuration, I read the docs:
https://docs.celeryproject.org/en/latest/userguide/configuration.html#task-annotations
And in the list above, saw CELERY_TASK_ANNOTATIONS. I used that and realized after a while that it didn't work.

After a while of debugging CELERY_ANNOTATIONS worked.

# Suggestions
While debugging, I saw that in:
https://github.com/celery/celery/blob/240ef1f64c8340bfffc31359f842ea4a6c8c493a/celery/app/defaults.py#L250
The value for `__old__` is `celery_{}` and not `celery_task_{}`

I'm assuming this issue is there for a bunch of the other configs like `acks_late` and `always_eager` and others too probably.
The docs seem to say use CELERY_TASK, but looks like the namespace in the code is CELERY_

In the task configs, I seem to only use CELERY_TASK_SERIALIZER, and here I can see that the value for `old` is explicitly set and so it works:
https://github.com/celery/celery/blob/240ef1f64c8340bfffc31359f842ea4a6c8c493a/celery/app/defaults.py#L289

**Comment by auvipy** [comment]
CELERY_TASK_ANNOTATIONS is the old way and deprecated. use lower case configurations.

**Comment by AbdealiJK** [comment]
True, but my understanding was that the configs are supposed to be backward compatible as of 4.3 at least. 
Currently, it doesn't look like  CELERY_TASK_ANNOTATIONS works

**Comment by sillycube** [comment]
If CELERY

> CELERY_TASK_ANNOTATIONS

If CELERY_TASK_ANNOTATIONS is depreated, can you please update the [django doc](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html)? It still suggests using CELERY namespace.
