### ISSUE TITLE
Clarify task routing when two workers are consuming the same queue

### ISSUE THREAD

**Issue by SHxKM** [celery/celery#5745]
# Checklist

- [x ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

Currently using `Celery 4.2.1` with `Redis 2.10.6`.

# Description
I have two workers, `backgroundworker` which consumes the queues `regular` and `important`, and `importantworker` which consumers only the queue `important`:

```
backgroundworker: celery -A my_app worker -c 6 -Q regular, important -l info -Ofair 
importantworker: celery -A my_app worker -c 6 -Q important -l info -Ofair 
```

There are instances when there are already 1000s of tasks being sent to the `regular` queue, and therefore handled exclusively by `backgroundworker`, but when a task is sent to the `important` queue, it is still handled by `backgroundworker` and not by `importantworker`, even though the former should be "busy" (or busier..).

Is this intended? anyway to mitigate that? I was pretty sure that before Celery would route this task to the worker which was consuming less tasks (in this case `importantworker`), in hopes to "balance the load".

# Suggestions

If this is intended, is there anywhere where I can read more about how Celery routes tasks in this scenario? (this scenario: multiple separate workers sharing some of their queues, not the other way around)

**Comment by auvipy** [comment]
can you post this to celery-users mailing list?

**Comment by SHxKM** [comment]
@auvipy just did but I don’t see my post. Is this a docs issue or is Celery just supposed to behave this way?

**Comment by auvipy** [comment]
https://groups.google.com/forum/#!topic/celery-users/qK93GnFIoUs

**Comment by auvipy** [comment]
closing until reaching a conclusion on mailing list
