### ISSUE TITLE
Terminated producer does not revoke tasks

### ISSUE THREAD

**Issue by PeterPan4d** [celery/celery#5746]
Hi,

I have a producer which executes a few hundred tasks. Each task takes around 1-2 minutes and is processed by a worker. I want to make the environment as robust as possible and in the rare case that a producer is terminated I don't see a possibility to revoke the tasks given by this machine from the queue.

Is there any chance to see on a worker side if the task is still valid? It could even be that the worker got restarted within a second and a heartbeat check would return True. So I need to know in specific if the task executed by a producer is still valid

Thanks for any help!

**Comment by auvipy** [comment]
post your support questions to celery users mailing list first.
