### ISSUE TITLE
How to use custom inspect commands in "app.control.inspect()"?

### ISSUE THREAD

**Issue by 40huo** [celery/celery#5750]
There is a scenario where I need to periodically get information about the CPU, memory, IP, etc. of each celery worker. The task result cannot be obtained through the broadcast task, so the custom inspect_command implementation is selected, and a new scheduled task is obtained by app.control.inspect().custom_command(). However, the actual function will not be found.

Here is example code:
```python
@inspect_command()
def resource_usage(state):
    result = get_resource_usage()
    result = result.__dict__
    logger.warning(result)
    return {"a": result}


@shared_task(name=TaskName.OverWatch.GET_WORKER_STATS.value)
def get_worker_stats():
    from tasks import app

    i = app.control.inspect()
    results = i.resource_usage()
    logger.info(results)
```

Error information:
```
AttributeError: 'Inspect' object has no attribute 'resource_usage'
```
How could I use that custom inspect command function correctly? Thanks!

**Comment by auvipy** [comment]
the version you are using?

**Comment by 40huo** [comment]
> the version you are using?

4.3.0

**Comment by mstxq17** [comment]
how to solve this？

**Comment by mstxq17** [comment]
i alse met this issue， can you provie me a solution? thanks

**Comment by mstxq17** [comment]
> > the version you are using?
> 
> celery v4.3.0 (rhubarb)
> Darwin-18.7.0-x86_64-i386-64bit

hello, Did you solved this question?

**Comment by auvipy** [comment]
what celery version are u using?
