### ISSUE TITLE
Support for priority with 'chord_unlock'

### ISSUE THREAD

**Issue by dtilloy-criteo** [celery/celery#5766]
# Brief Summary

Celery ```celery.chord_unlock``` does not support ```priority``` (both 4.3.0 and 4.4.0rc3 releases). A short test shows this special task is always set with default priority (even if it's possible to set the queue where to schedule this task).

This is annoying because when trying to execute tasks with high priority (in a specific chord) to complete it before the others, as the ```chord.unlock``` task for this chord will be set with same priority than the other chord's task, your "prefered" chord will not be able to complete first and as soon as possible.

## Proposed Behavior

Set priority for ```chord_unlock``` same ways Celery set the queue.

**Comment by auvipy** [comment]
your pr need tests

**Comment by jarshwah** [comment]
Should this issue be closed considering the 4.4.3 release notes suggest it's fixed? https://docs.celeryproject.org/en/v4.4.7/changelog.html
