### ISSUE TITLE
Https on Elasticsearch backend

### ISSUE THREAD

**Issue by Mdslino** [celery/celery#5779]
`[2019-10-17 18:22:19,379: ERROR/MainProcess] Pool callback raised exception: RequestError(400, '<html><head><title>400 The plain HTTP request was sent to HTTPS port</title></head><body bgcolor="white">\<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center></body></html>', None)`

I cannot send a result to elasticsearch over https. How can I setup elasticsearch backend to use https?

**Comment by georgepsarakis** [comment]
GitHub issues are mainly used for bug reports. For questions and help requests communication channels please see [here](https://docs.celeryproject.org/en/latest/getting-started/resources.html#getting-help).

To answer your question, an example of HTTPS configuration can be found in the [test cases](https://github.com/celery/celery/blob/2eb563275032ef1773c824f42cff4dc4869e6314/t/unit/backends/test_elasticsearch.py#L88).
