### ISSUE TITLE
 ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:15672//: timed out.

### ISSUE THREAD

**Issue by tvanzo** [celery/celery#5781]
I am new to celery and the community, and have spent many hours trying to figure this one out, would be so grateful for any pointers.  Simply trying to get a basic worker running using celery (with rabbitmq) -A proj worker -l info.  I cloned the django example proj from GitHub, everything is exactly the same as there.  

It says I can't connect to 127.0.0.1:15672// ..but if I go to my browser and connect to it (but without the last two slashes) it brings me to the rabbitmq dashboard..with the last two slashes I can not connect either.  Why is it always trying to connect to the address with the two slashes at the end? I don't understand the meaning of it and can not get the worker to run.  

So appreciative of any help.
Thanks!

**Comment by auvipy** [comment]
it is suggested to post questions in celery-users mailing list or celery IRC channel

**Comment by jainal09** [comment]
Try now I have added a pr and is merged so git pull might fix the issue;
if not its a typo in `proj/settings.py` where CELERY_BROKER_URL had an extra 2 slash at the end of the URL which may have caused the error. So try removing that
`CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'` 
**change above to :**
`CELERY_BROKER_URL = 'amqp://guest:guest@localhost'`

**Comment by jainal09** [comment]
> I am new to celery and the community, and have spent many hours trying to figure this one out, would be so grateful for any pointers. Simply trying to get a basic worker running using celery (with rabbitmq) -A proj worker -l info. I cloned the django example proj from GitHub, everything is exactly the same as there.
> 
> It says I can't connect to 127.0.0.1:15672// ..but if I go to my browser and connect to it (but without the last two slashes) it brings me to the rabbitmq dashboard..with the last two slashes I can not connect either. Why is it always trying to connect to the address with the two slashes at the end? I don't understand the meaning of it and can not get the worker to run.
> 
> So appreciative of any help.
> Thanks!
Try now I have added a pr and is merged so git pull might fix the issue;
if not its a typo in proj/settings.py where CELERY_BROKER_URL had an extra 2 slash at the end of the URL which may have caused the error. So try removing that
CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'
change above to :
CELERY_BROKER_URL = 'amqp://guest:guest@localhost'

**Comment by auvipy** [comment]
e9159cf4266db964da3b7fd033731ddfd7c5e147 does this solve the issue?

**Comment by tvanzo** [comment]
What exactly did you change @jainal09? I redownloaded the example and no change. The celery broker is also the second (correct one) it does not have any "/" at the end. I am still getting the error that it can not connect to : amqp://guest:**@127.0.0.1:5672// (with two slashes)

**Comment by tvanzo** [comment]
Also, if I am running it on dev for now should/can I still use rabbitmq? the following link made me confused https://stackoverflow.com/questions/18133249/django-celery-cannot-connect-to-amqp-guest127-0-0-80005672 . (I tried it that way and it didn't work either same error)
