### ISSUE TITLE
[Query]: Does Celery Reassign the task on process dead.

### ISSUE THREAD

**Issue by sreedharbukya** [celery/celery#5783]
Hey Team, 

Sorry to ask this question here. I am been using celery since last 6 months. I am running  celery workers in Kubernetes cluster with supervisor to start celery process.

If a task "A" is scheduled (RECEIVED) and assigned to worker "X". If Worker X received but worker has dead because any reason. Will that task "A" is reassigned to another active worker?

If it doesn't reassigned, what should be done to that task from application?

**Comment by auvipy** [comment]
please ask questions on the mailing list or IRC channel
