### ISSUE TITLE
Storing custom meta fields in celery results

### ISSUE THREAD

**Issue by ZeeshanSultan** [celery/celery#5798]
I want to store parts of my parsed result as fields in mongodb backend, so i can query (MapReduce) them at the end of my execution cycle which is not possible with standard result stored in celery.

The default fields are :
id,status,date_done,traceback,results,children

I want to store status_code field as well.
Update State is not effective since the metadata is not stored in backend

**Comment by auvipy** [comment]
I suggest you post your support question to the celery-user mailing list first.
