### ISSUE TITLE
Connection to broker lost. Trying to re-establish the connection: OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by tedivm** [celery/celery#5802]
For some reason after running for about a day our worker loses it's connection to rabbitmq and is unable to reconnect.

I initially encountered this issue with 4.2, so I upgraded to the latest version (4.3.0) and am still encountering the issue. I've also found several issues related to this, but since they are all closed I am opening this new one (and referencing them below).

The application I am encountering this with is open source, so you can view it in the [Nebula](https://github.com/tedivm/nebula) repository. 

# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #4457
- #5499

#### Possible Duplicates

- #4457

## Environment & Settings

**Celery version**: 4.3.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 4.2.0
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: Docker
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

https://raw.githubusercontent.com/tedivm/nebula/master/requirements.txt

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

I can't reproduce on demand unfortunately.

# Expected Behavior

The worker should stay connected to the broker, or it should reconnect successfully.

# Actual Behavior

```
consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.6/site-packages/celery/worker/loops.py", line 50, in asynloop
    obj.controller.register_with_event_loop(hub)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 219, in register_with_event_loop
    description='hub.register',
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/components.py", line 179, in register_with_event_loop
    w.pool.register_with_event_loop(hub)
  File "/usr/local/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 134, in register_with_event_loop
    return reg(loop)
  File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 482, in register_with_event_loop
    for fd in self._fileno_to_outq]
  File "/usr/local/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 482, in <listcomp>
    for fd in self._fileno_to_outq]
  File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 216, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 167, in add
    self.poller.register(fd, flags)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/eventio.py", line 67, in register
    self._epoll.register(fd, events)
OSError: [Errno 9] Bad file descriptor
```

**Comment by auvipy** [comment]
can you give celery master a try to verify?

**Comment by tedivm** [comment]
The problem is that I can only catch this in production- it takes at least 24 hours before this bug appears. I can still give it a shot but I'll have to build new containers to do so, rather than using the ones I'm hosting publicly on dockerhub.

**Comment by mahaffey** [comment]
@tedivm any update?

**Comment by auvipy** [comment]
with celery==4.4.0?

**Comment by mahaffey** [comment]
I am using 4.3.0

I will try 4.4.0

**Comment by davesave** [comment]
any news?

**Comment by mahaffey** [comment]
I solved this issue by throwing a bigger EC2 (compute optimized C5.Large from a T3.Large) at my celery workers and the issue stopped occurring for me. I am running Celery in K8s with node anti-affinity on the hostname (no two workers on the same node). I also was sure to make sure the concurrency level was correct for my vCPU count.
