### ISSUE TITLE
celery.execute.send_task should respect CELERY_ALWAYS_EAGER

### ISSUE THREAD

**Issue by kmike** [celery/celery#581]
Trying to figure out why CELERY_ALWAYS_EAGER doesn't work I found that celery.app.base.BaseApp.send_task (and thus celery.execute.send_task) doesn't respect CELERY_ALWAYS_EAGER. 

I think CELERY_ALWAYS_EAGER should be respected both for direct task invocations (via task.delay) and for indirect invocations (via execute.send_task).

**Comment by BeOleg** [comment]
Proper solution?

**Comment by BeOleg** [comment]
@ask ?

**Comment by auvipy** [comment]
ask do not maintain celery anymore.

**Comment by dhavenstein** [comment]
It's 2024, still no proper solution... Sad

**Comment by Dufran** [comment]
Just encountered same behavior. 
For me workaround was using 
```python 
task_signature = app.signature(
                "app.tasks.some_task",
                args=[1, 2],
            )
            task_signature.delay()
```
This gets task to be called when running tests with  `CELERY_TASK_ALWAYS_EAGER=True`
