### ISSUE TITLE
Release 4.4.0

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5816]
Version: 4.4.0
Release PR: TDB

# Checklist

- [x] Release PR drafted
- [x] Release PR reviewed
- [x] The master branch build passes

    [![Build Status](https://travis-ci.org/celery/celery.svg?branch=master)](https://travis-ci.org/celery/celery)
- [x] Release Notes
- [x] What's New

# Release Blockers
https://github.com/celery/celery/milestone/22

# Potential Release Blockers
https://github.com/celery/kombu/milestone/6

**Comment by thedrow** [comment]
@auvipy Can you please bring me up to speed?
What needs to be done?
What's blocking us from a release?

**Comment by auvipy** [comment]
1. https://github.com/celery/celery/issues/5607 this one is main blocker. among other blocker, some issues are already closed. I will update you the remaning tomorrow.

**Comment by auvipy** [comment]
I will release a 4.4rc4 by 7, Nov and planning to make a stable release by 14/15 nov. I will work dedicatedly from today to cea the blocker an release 4.4rc3 by 7 November.

**Comment by auvipy** [comment]
a release note with project standard + 1 integration fail error. expect 30 nov as the stable release day

**Comment by Darkheir** [comment]
Awesome, thanks !

**Comment by lpsinger** [comment]
How is Celery 4.4.0 coming?

**Comment by auvipy** [comment]
this week end :)

**Comment by xirdneh** [comment]
@auvipy Is there anything I can do to help?

**Comment by auvipy** [comment]
> @auvipy Is there anything I can do to help?

yes please https://github.com/celery/celery/pull/5817 :D if you have time

**Comment by xirdneh** [comment]
@auvipy  I've started going through the commits and seeing what's missing. Will continue over the weekend.

**Comment by auvipy** [comment]
Considering the fact that we added some new features and bug fixes in the 4.4.x master development branch, I have released another release candidate https://github.com/celery/celery/releases/tag/4.4.0rc5 and proposing the final release in 1 week.

**Comment by lioncui** [comment]
Hi, What time to merge with  https://github.com/celery/celery/pull/5482 ?
I want to fix the memory leek problem.
Thank you very much!

**Comment by auvipy** [comment]
> Hi, What time to merge with #5482 ?
> I want to fix the memory leek problem.
> Thank you very much!

can you add unit and integration test for that PR?

**Comment by thedrow** [comment]
@lioncui We haven't merged the PR since we don't know if it fixes the issue and if it does, we don't know why it fixes the issue.

See https://github.com/celery/celery/pull/5482#issuecomment-486181247.

It's possible that after the release we'll introduce a setting to turn this behavior off if you experience a memory leak.

**Comment by thedrow** [comment]
I'm nearly done with the what's new but I need to rewrite the changelog to be up to the project's standard.
We're very close to a release.

**Comment by auvipy** [comment]
I have released the 4.4.0 version on PyPI. with minimal what's new on 4.4.0. we can fix the bugs and release notes as per-project standards on 4.4.x milestone. thank you all for your support. This was my first ever major release of celery, so there were some mistakes in the release process and timing. My apologies for those and I have learn a lot in the meantime.

**Comment by thedrow** [comment]
So you released before we were ready for it?
I don't get it.
