### ISSUE TITLE
What does [...] or -*- means in -*-_DB_SHORT_LIVED_SESSIONS

### ISSUE THREAD

**Issue by jorge-fresh4cast** [celery/celery#5819]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

The documentation https://docs.celeryproject.org/en/latest/history/whatsnew-4.0.html#latentcall-django-admonition is inconsistent when it comes to -\*-_DB_SHORT_LIVED_SESSIONS. 

I can't find guidance about what does -*- represents and what should be the final name on that setting.

I have tried CELERY_DEFAULT_DB_SHORT_LIVED_SESSIONS but the 2006 MySQL problem is supposed to fix continues to happen so I assume the setting is wrong. We need a clearer doc on how to use that setting.

# Suggestions

Give an example on how the configuration should look in a Django file and explain what -*- represents. Also, I have seen it as [...] in other places so it should be consistent unless it's meant to be intentionally different.

**Comment by thedrow** [comment]
I have to say, I honestly don't know what this setting is or what it does. :sweat:

**Comment by auvipy** [comment]
you should use the lowercase database_short_lived_sessions instead

**Comment by jorge-fresh4cast** [comment]
> you should use the lowercase database_short_lived_sessions instead

Does that apply for Django settings as well?

**Comment by auvipy** [comment]
for celery related yes

**Comment by jess7575** [comment]
-*- encoding declaration 
*args
**kwargs
