### ISSUE TITLE
Celery use redis cluster with error

### ISSUE THREAD

**Issue by abersheeran** [celery/celery#5826]
When I use Celery with redis cluster, some error be raised.

```
redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot
```

Version: Celery 4.3 - Redis 5.0

**Comment by abersheeran** [comment]
By the way, I am sorry that my cat has pressed the Enter key when I have not entered the title.

**Comment by cyan-T** [comment]
> When I use Celery with redis cluster, some error be raised.
> 
> ```
> redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot
> ```
> 
> Version: Celery 4.3 - Redis 5.0

Have you solved the problem? I met the problem too.

**Comment by guige** [comment]
mee too , I don't resolve it.

**Comment by thedrow** [comment]
Please open a new issue with all the required details.
We need a way to reproduce this.
