### ISSUE TITLE
Invocation via .delay() not working in some cases

### ISSUE THREAD

**Issue by empeje** [celery/celery#5827]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- Task invocation via `.delay()` not working, in our case is with django_templated_email

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:
* celery==4.3.0
* django-celery-beat==1.5.0
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
/usr/local/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
 
 -------------- celery@worker-deployment-695fbd498-rmln6 v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Linux-4.14.138+-x86_64-with-debian-10.1 2019-11-12 17:00:00
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         app:0x7f694a5ba160
- ** ---------- .> transport:   redis://10.0.0.3:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . accounting.tasks.generate_payment_receipt_by_collection_id
  . loans.tasks.send_loan_approval_email
  . loans.tasks.send_loan_approval_sms
  . loans.tasks.send_loan_disbursement_sms
  . loans.tasks.send_loan_rejection_email
  . loans.tasks.send_loan_rejection_sms
  . loans.tasks.send_loan_revision_sms
  . loans.tasks.update_repayments_by_loan_id

[2019-11-12 17:00:01,232: INFO/MainProcess] Connected to redis://10.0.0.3:6379/0
[2019-11-12 17:00:01,313: INFO/MainProcess] mingle: searching for neighbors
[2019-11-12 17:00:02,423: INFO/MainProcess] mingle: sync with 1 nodes
[2019-11-12 17:00:02,424: INFO/MainProcess] mingle: sync complete
[2019-11-12 17:00:02,510: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-11-12 17:00:02,511: INFO/MainProcess] celery@worker-deployment-695fbd498-rmln6 ready.
[2019-11-12 17:00:27,433: INFO/MainProcess] missed heartbeat from celery@worker-deployment-594c7656c-llbh5
[2019-11-12 17:57:57,857: INFO/MainProcess] Received task: loans.tasks.send_loan_approval_sms[fbc8eefe-2155-4754-983a-2409ef2e544a]  
[2019-11-12 17:57:58,008: INFO/ForkPoolWorker-1] Running loans.tasks task
[2019-11-12 17:57:59,486: INFO/ForkPoolWorker-1] Successfully sent SMS
[2019-11-12 17:57:59,487: INFO/ForkPoolWorker-1] <Response [200]>
[2019-11-12 17:58:00,761: ERROR/ForkPoolWorker-1] An error occured when sending an SMS
[2019-11-12 17:58:00,762: ERROR/ForkPoolWorker-1] Traceback
[2019-11-12 17:58:00,765: ERROR/ForkPoolWorker-1] 400 Client Error:  for url: https://endpoint.api.infobip.com/sms/2/text/single
[2019-11-12 17:58:00,766: INFO/ForkPoolWorker-1] Task loans.tasks.send_loan_approval_sms[fbc8eefe-2155-4754-983a-2409ef2e544a] succeeded in 2.8980900809401646s: None

```

</p>
</details>

# Steps to Reproduce

I encountered this issue when doing the following

* I have a task definition like this

```python
@shared_task
def send_loan_approval_email(loan_id):
    from loans.models import Loan
    from templated_email import get_templated_mail
    loan = Loan.objects.get(pk=loan_id)

    # some code here

    email_borrower.send()
    email_guarantor.send()

@shared_task
def send_loan_approval_sms(loan_id):
    from loans.models import Loan
    from app.services import sms_service
    loan = Loan.objects.get(pk=loan_id)
    log.info(f"Running {__name__} task")
    sms_service.send(
      # some code here
    )
```

* I have code invocation here

```python
class Loan:
    def approve(self, by=None):
        send_loan_approval_sms.delay(self.id)
        send_loan_approval_email.delay(self.id)
```

* When I run `approve()` somehow the sms run but the email doesn't, but sometime it works too, sms consistently running, but the email sometime work sometime broken. Any idea why?

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
asn1crypto==0.24.0
backports.ssl-match-hostname==3.7.0.1
bcrypt==3.1.6
cached-property==1.5.1
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cryptography==2.6.1
Django==1.11.26
django-storages==1.7.2
docker==3.7.2
docker-compose==1.24.0
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
functools32==3.2.3.post2
idna==2.7
ipaddress==1.0.22
jsonschema==2.6.0
paramiko==2.4.2
pyasn1==0.4.5
pycparser==2.19
PyNaCl==1.3.0
pytz==2019.3
PyYAML==3.13
requests==2.20.1
six==1.12.0
texttable==0.9.1
urllib3==1.24.2
websocket-client==0.56.0

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Both `send_loan_approval_sms` and `send_loan_approval_email` should emitted to worker.

# Actual Behavior

Only `send_loan_approval_sms` emitted to worker.

**Comment by auvipy** [comment]
can you try this with celery==4.4.0rc4?

**Comment by empeje** [comment]
@auvipy let me try

**Comment by thedrow** [comment]
Are you sure the second message never reaches the broker?

**Comment by empeje** [comment]
I'm sure, I waited for long nothing coming @thedrow

**Comment by empeje** [comment]
@thedrow and @auvipy I trid to use the rc version, but no luck.

I see that it's always the last task that not received, should I group the task to be run in parallel? using `groups` function?

reference: https://docs.celeryproject.org/en/latest/userguide/canvas.html#groups

**Comment by empeje** [comment]
Problem is I can make it work in my local but can't make it work in my "production" environment, I'll investigate further.

**Comment by empeje** [comment]
@auvipy and @thedrow I think the issue is not in the celery, but we just realized that we have two environments (production and staging) in which we shared Redis, and worker in production pick our task that supposed to be picked by our staging.

Sorry about this. You can close this issue.

**Comment by thedrow** [comment]
@auvipy I think my labeling makes more sense no?

**Comment by auvipy** [comment]
Before verifying, leveling an issue as bug report doesn't really make sense actually. also this is actually a user mistake. so NO :)

**Comment by thedrow** [comment]
Well it is bug report but it's not a bug.

**Comment by auvipy** [comment]
let us follow the widely accepted norm on this. it seems to be a bug t the reporter, but actually not :D so tagging this as bug report doesn't go well with existing real bug reports :dagger:
