### ISSUE TITLE
About CELERYD_MAX_TASKS_PER_CHILD not work

### ISSUE THREAD

**Issue by Jruing** [celery/celery#5828]
## question
I would like to ask about the celery configuration item (CELERYD_MAX_TASKS_PER_CHILD = 5). This configuration item is automatically restarted after 5 tasks are executed. But I found out through PID that it is still the previous PID after the completion of 5 tasks. Can you explain it?

## version
celery :3.1.26.post2

**Comment by auvipy** [comment]
please try the latest version and post your questions to https://groups.google.com/forum/#!forum/celery-users
