### ISSUE TITLE
Worker does not receive all tasks

### ISSUE THREAD

**Issue by PeterPan4d** [celery/celery#5829]
Hi!

I am using RabbitMQ as my broker and 2 workers (celery 4.4). The workers have a queue size of 1 and prefetch only 1 job at a time (because they are long-running jobs).

I send 25 tasks to the queue and they all start working on them. But between 2 and 4 jobs are not executed and I don't know why. I don't revoke them, and I can guarantee that no worker receives them. It's pretty vague, but does this behaviour sound familiar to anyone? Thanks!

**Comment by auvipy** [comment]
ask your support questions to https://groups.google.com/forum/#!forum/celery-users
