### ISSUE TITLE
Questions regarding processing a stream of tasks individually, then retrieve them as a batch

### ISSUE THREAD

**Issue by oliverhowden** [celery/celery#5832]
Our pipeline involves uploading ~150 images from our frontend via web socket as they are imported into the web app. As they hit the backend, each is added to the celery queue individually using a `signature`, which is then run on a seperate set of worker servers processing the images immediately, and the results are put into the result backend as they're completed. 

From the signature, the task ID is sent back to the frontend, where it waits until our users click analyse. When the user clicks analyse, (which can happen before or after all the image results are ready), all task IDs are sent to the backend, formed into an `AsyncResult`, and retrieved via `result.get()`.

My problem is, that sending 150 task_ids at once, requesting all their results (some of which are ready, some are not) clogs up our web sockets. Obviously, one way is to send batches of task_ids, retrieve them, then send the next batch - though I was hoping to handle this at the celery level. 
Is there any way to stream results into some form of group as they are uploaded, then collect them into a single action? Ideally images would arrive sequentially, be added to celery under a parent id of some sort, though begin processing immediately individually by the remote workers. That way, when the user clicked Analyse, I would be possible to send a single fetch request, which would then return results that are currently ready, and others as they became ready.

Please let me know if this needs further clarification, though I've dug through all documentation and cannot work out a way to go about this. 
Any other suggestions would be very welcome

**Comment by auvipy** [comment]
the best place to ask help is celery-users mailing list or IRC.
