### ISSUE TITLE
celery worker has --quiet to suppress banner output but celery beat does not

### ISSUE THREAD

**Issue by anlutro** [celery/celery#5836]
Sorry for leaving out the issue template but I believe this is fairly trivial and straight-forward.

In master, there is code to enable the suppressing of printing the banner when running `celery worker` with `--quiet`:
https://github.com/celery/celery/blob/9773eba837982c84380c93bd3788470273e7674d/celery/apps/worker.py#L138-L139

This conditional is not present in the code that runs `celery beat`:
https://github.com/celery/celery/blob/9773eba837982c84380c93bd3788470273e7674d/celery/apps/beat.py#L77-L78
https://github.com/celery/celery/blob/9773eba837982c84380c93bd3788470273e7674d/celery/apps/beat.py#L100

This causes a few issues for us because we expect all our services to only emit JSON.

**Comment by auvipy** [comment]
do you have the time to send improvements?

**Comment by anlutro** [comment]
I do, with a little guidance. Do I just need to add the `quiet` kwarg to `on_before_init` in `beat.py`? Or is there something more I need to do to make sure that I can figure out whether `--quiet` was passed or not?

**Comment by anlutro** [comment]
ping :)

**Comment by auvipy** [comment]
> I do, with a little guidance. Do I just need to add the `quiet` kwarg to `on_before_init` in `beat.py`? Or is there something more I need to do to make sure that I can figure out whether `--quiet` was passed or not?

you really need to dig the code to figure out that
