### ISSUE TITLE
Worker exited prematurely: signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by xiazhibin** [celery/celery#5852]
OS: ubuntu 16.04
python: 2.7.15
celery: 4.2.0
kombu: 4.2.1
billiard: 3.5.0.2

There is sentry error log:
```
kombu.pidbox: pidbox received method enable_events() [reply_to:None ticket:None]

celery.worker.strategy: Received task: gizmocloud.celery_tasks.convert.mesh_convert[471350ae-0278-42b9-9568-c694204074b8]  

kombu.pidbox: pidbox received method enable_events() [reply_to:None ticket:None]

multiprocessing: Supervisor: cleaning up worker 0

multiprocessing: Supervisor: worked 0 joined

multiprocessing: Process 'PoolWorker-1' pid:11 exited with 'signal 11 (SIGSEGV)'

celery.worker.request: Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)

exception: WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

My celery command is `celery -A proj worker  -l INFO  --max-tasks-per-child=5 --concurrency=4`

It seems that worker was broken when received the task.

Is there any idea to figure out the problem. Or what can I do to find more information to locate the problem

**Comment by auvipy** [comment]
closing this for not reporting with either celery 4.3 / 4.4.0rc4 / master branch.
