### ISSUE TITLE
A workaround to multiple executions issue using redis as broker

### ISSUE THREAD

**Issue by IterableTrucks** [celery/celery#5868]
Long running task will be executed multiple times due to AMQP implementation based on redis pub/sub. There are some posts suggest increasing visibility_timeout value in broker_transport_options.
But it's more accommodative to acknowledge the task right after being received.

```
from celery.signals import task_recevived
@app.task(name='long_task')
def long_task():
    do_something()
@task_received.connect
def task_received_handler(request=None,**kwargs):
    if request.message.headers['task']=='long_task':
        request.acknowledge()
```

**Comment by adw1n** [comment]
`@app.task(name='long_task', acks_late=False)` does the same thing

**Comment by adw1n** [comment]
@IterableTrucks @auvipy please close this issue. There is nothing to be done here.

**Comment by auvipy** [comment]
thanks for verifying
