### ISSUE TITLE
Outdated optimization note about usage of librabbitmq

### ISSUE THREAD

**Issue by Alireza2n** [celery/celery#5872]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

#4693 

#### Possible Duplicates

- None

# Description
In current documentation, in the "Optimizing" section, [this paragraph](https://docs.celeryproject.org/en/latest/userguide/optimizing.html#librabbitmq) recommends using librabbitmq but in #4693 it's mentioned librabbitmq is not the best performing package anymore.

# Suggestions
I'd suggest to mark [this paragraph](https://docs.celeryproject.org/en/latest/userguide/optimizing.html#librabbitmq)  as "old" or remove it to prevent users from using it as a "best practice".

**Comment by auvipy** [comment]
contribution is welcome

**Comment by Alireza2n** [comment]
@auvipy Sure. I just wanted to make sure this still holds true.
Will make a PR as soon as possbile.
