### ISSUE TITLE
Segfault in python 3.7 with SQS broker

### ISSUE THREAD

**Issue by kidzik** [celery/celery#5901]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.0 (cliffs) kombu:4.6.7 py:3.7.0
            billiard:3.6.1.0 sqs:N/A
platform -> system:Linux arch:64bit
            kernel version:5.0.0-37-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled

broker_url: 'sqs://***:********@localhost//'
task_default_queue: 'inference'
broker_transport_options: {
 'region': 'us-west-2'}
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7.0 (conda)
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery[sqs]
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
import os
from celery import Celery
from kombu.utils.url import quote

aws_access_key = # AWS access key
aws_secret_key = # AWS secret key

broker_url = "sqs://{aws_access_key}:{aws_secret_key}@".format(
    aws_access_key=aws_access_key, aws_secret_key=aws_secret_key,
)

app = Celery('default', broker=broker_url)
app.conf.broker_transport_options = {'region': 'us-west-2'}

@app.task
def add(x, y):
    return x + y
```

</p>
</details>

# Expected Behavior

Start a worker

# Actual Behavior

```
 -------------- celery@kidzik-XPS-8900 v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid 2020-01-03 19:10:18
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         infrence:0x7f1e39811be0
- ** ---------- .> transport:   sqs://***:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> default        exchange=default(direct) key=default
                

[tasks]
  . app.add

[2020-01-03 19:10:19,095: INFO/MainProcess] Connected to sqs://***:**@localhost//
[2020-01-03 19:10:19,369: INFO/MainProcess] celery@kidzik-XPS-8900 ready.
Segmentation fault (core dumped)
```

**Comment by kidzik** [comment]
Works find with `python==3.6.9` from conda

**Comment by auvipy** [comment]
celery is not tested with 3.7 (conda), can you try plain python 3.7.x or 3.8.x?

**Comment by thedrow** [comment]
In addition, we can't remotely debug your core dumps.
Please include it with all the relevant debug symbols.

If you're on a system with systemd see [coredumpctl](https://www.freedesktop.org/software/systemd/man/coredumpctl.html).

**Comment by kidzik** [comment]
I switched to `python==3.6.9` in conda so everything works ok for me now, thank you!
