### ISSUE TITLE
kombu.exceptions.OperationalError: Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists

### ISSUE THREAD

**Issue by fangqimingCSDN** [celery/celery#5903]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

Has recently been used celery for multi-process concurrent tasks, met a very difficult problem, I tried to solve, but to collect a variety of methods, failed to solve my problem.
Problem: Celery multitasking program, the task using inherited classes encapsulate Celery. Task type of task to complete my task, task, of course, include my success and failure of rewriting method.My program is not important, of course, just a program will appear, **kombu. Exceptions. OperationalError** mistake, **Cannot route message for exchange 'reply.celery.pidbox': Table emply or key no longer exists**, I'll find related to explain the key as redis reply. Celery. Pidbox ousted, lead to the routing problem, which I doubt is redis configuration problem, I tried to existing have been fighting for using redis cluster, will quote us pidbox ousted, same problem.Then I was celery there may be some problems, please the great god still hope to give directions, thank you very much

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:
python 3.6.5
celery 4.3.0
redis 3.2.1 （Using the cluster）
kombu 4.6.2 (4.6.4 4.6.5 Try to release)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
kombu.exceptions.OperationalError：
Cannot route message for exchange 'reply.celery.pidbox': Table emply or key no longer exists

RuntimeError: pubsub connection not set: did you forget to call subscribe() or psubscribe()?
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by auvipy** [comment]
try celery==4.4.0 and report again

**Comment by fangqimingCSDN** [comment]
> try celery==4.4.0 and report again
Hi, first of all, thanks for your answer. I have tried celery4.4.0, and I repeated the same question in both docker and k8s environments
The error message is as follows
kombu.exceptions.OperationalError：Cannot route message for exchange 'reply.celery.pidbox': Table emply or key no longer exists
During handling of the above exception, another exception occurred
BrokenPipeError: [Errono 32] Broken pipe

**Comment by fangqimingCSDN** [comment]
@auvipy 
Hi, first of all, thanks for your answer. I have tried celery4.4.0, and I repeated the same question in both docker and k8s environments
The error message is as follows
kombu.exceptions.OperationalError：Cannot route message for exchange 'reply.celery.pidbox': Table emply or key no longer exists
During handling of the above exception, another exception occurred
BrokenPipeError: [Errono 32] Broken pipe

**Comment by iMerica** [comment]
Which version should we downgrade to in the interim?

**Comment by ohyang326** [comment]
celery 4.4.0
kombu 4.6.7

meet the same problem

**Comment by pfdtk** [comment]
celery==5.1.2
kombu==5.1.0

meet the same problem

**Comment by mahmudtopu3** [comment]
Still facing the problem ? Any solution ?
