### ISSUE TITLE
git tags: missing `v` prefix since 4.4.*

### ISSUE THREAD

**Issue by thomas-riccardi** [celery/celery#5909]
Unit 4.3.0 release the git tags had a leading `v`: https://github.com/celery/celery/releases/tag/v4.3.0
Since 4.4.* the git tags dont have the leading `v` anymore, making it harder to guess the tag name (and distinguish tags and potential maintenance branches). (For example, I was trying to list all new commits in the 4.4.0 release: https://github.com/celery/celery/compare/v4.3.0...v4.4.0 doesn't work).

Was this change a mistake or a voluntary choice?

**Comment by auvipy** [comment]
it was intentional

**Comment by auvipy** [comment]
you should be comparing v4.3 against the master. no 4.4.x branch has been created yet.

**Comment by thedrow** [comment]
> it was intentional

Why? It's not per project standards?

**Comment by matusvalo** [comment]
Not sure why it was decided to break the standard. Even github recommends to prefix tag with v,

This has also another side effect. The documentation is broken since the readthedocs shows as stable and latest the last release beginning with v - see similar bug:

https://github.com/celery/kombu/issues/1204

**Comment by auvipy** [comment]
> Not sure why it was decided to break the standard. Even github recommends to prefix tag with v,
> 
> This has also another side effect. The documentation is broken since the readthedocs shows as stable and latest the last release beginning with v - see similar bug: [celery/kombu#1204](https://github.com/celery/kombu/issues/1204)

I think i miss judged the side effect, as I had less experience in releasing.

**Comment by thomas-riccardi** [comment]
> > Not sure why it was decided to break the standard. Even github recommends to prefix tag with v,
> > This has also another side effect. The documentation is broken since the readthedocs shows as stable and latest the last release beginning with v - see similar bug: [celery/kombu#1204](https://github.com/celery/kombu/issues/1204)
> 
> I think i miss judged the side effect, as I had less experience in releasing.

So, what about improving the situation by re-tagging with the "standard" `v` prefix for all 4.4.x tags that don't have it yet? (we could keep the old tags too: no need to break things more)

**Comment by thomas-riccardi** [comment]
> new releases are with v prefix

Yes I saw that, that's great news!
In addition to that I was suggesting to also create the missing `v4.4.*` tags so we have all celery releases as git tags with a `v` prefix.
