### ISSUE TITLE
Set an expiration time on a periodic task

### ISSUE THREAD

**Issue by lsemel** [celery/celery#591]
Let's say I have a periodic task set up to execute ever minute.  For some reason Celery's workers get stuck and Celery needs to be restarted - the now have a backup of one copy of that periodic task for every minute they weren't performing work.  When I restart the Celery workers, they start executing many copies of the periodic task.

For normal tasks I can do this by adding an expires parameter to the call to apply_async, but periodic tasks are defined by a decorator.

Is there a way to set an expiration time on the periodic task, so it'll execute, say, between 0 and 10 minutes from the time it's fired off, or be discarded?

**Comment by rciorba** [comment]
The `options` work in the celerybeat schedule(using celery==4.0.0):
```python
app.conf.beat_schedule = {
    'import': {
        'task': 'importer.tasks.import_last_5_minutes',
        'schedule': 60, 
        'args': (),
        'options': {
            # ensure we don't accumulate a huge backlog of these if the workers are down
            'expires': 60
        }
    },
}
```

**Comment by suzaku** [comment]
I'm using celery==4.1.0, neither `expires=3600` nor `options={"expires": 3600}` works in the decorator.
It's a supported parameter that expires the whole task, not for messages, so after the time you set, no more new messages are sent.

**Comment by est** [comment]
@suzaku  well that's disappointing.

somewhat related:

https://github.com/celery/celery/issues/2786
