### ISSUE TITLE
Celery tasks wait without being processed

### ISSUE THREAD

**Issue by YXinAndy** [celery/celery#5923]
![微信图片_20200116211115](https://user-images.githubusercontent.com/47964538/72527912-c5a5f080-38a4-11ea-87ba-a8f53e20f83f.jpg)
Hello, I met a problem in the use of celery, need help, the problem is as follows, our celery after receiving the task have been waiting for, but does not perform task, and we are executing task is empty, this should not have to do?Above, I use a flower monitoring data, waiting for more tasks, our celery is blocked, I restart the service, these services are performed again, and normal

**Comment by auvipy** [comment]
follow the issue template properly
