### ISSUE TITLE
tasks can not be terminate when using --pool=solo

### ISSUE THREAD

**Issue by zippies** [celery/celery#5929]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7.4 or 2.7
* **Minimal Celery Version**: 4.4.0
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
alembic==1.3.2
aliyun-python-sdk-core==2.13.13
aliyun-python-sdk-core-v3==2.13.11
aliyun-python-sdk-kms==2.9.0
amqp==2.5.2
billiard==3.6.1.0
celery==4.4.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
configparser==4.0.2
crcmod==1.7
Flask==1.1.1
Flask-Caching==1.8.0
Flask-Migrate==2.5.2
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
gevent==1.4.0
gitlab==1.0.2
greenlet==0.4.15
gunicorn==20.0.4
idna==2.8
importlib-metadata==1.4.0
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.4
kombu==4.6.7
lxml==4.4.2
Mako==1.1.0
MarkupSafe==1.1.1
more-itertools==8.1.0
oss2==2.9.1
pycryptodome==3.9.4
pymongo==3.10.0
PyMySQL==0.9.3
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
redis==3.3.11
requests==2.22.0
six==1.13.0
SQLAlchemy==1.3.12
urllib3==1.25.7
vine==1.3.0
Werkzeug==0.16.0
zipp==2.0.0

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```bash
        celery -A tasks worker --loglevel=info --pool=solo
```

</p>
<p>

```python
        from tasks import celery_app
        task_id = "some_task_id"
        logger.info("stoping task: %s" % task_id)
        celery_app.control.revoke(task_id, terminate=True, signal='SIGKILL')
```

</p>
</details>

# Expected Behavior

task should be terminated
# Actual Behavior

task can't be terminate

when using  "celery -A tasks worker --loglevel=info ~~--pool=solo~~" to start celery, There is no problem

**Comment by Pawel-Kranzberg** [comment]
The actual behaviour actually looks in line with what the [docs](https://docs.celeryproject.org/en/stable/userguide/workers.html) expect. Task termination by `revoke` is a remote control command "only supported by prefork".

**Comment by thedrow** [comment]
This is not a bug. Unfortunately, there's no way to terminate a task while using the solo pool other than killing the entire worker.
