### ISSUE TITLE
Extend config of Redis backend

### ISSUE THREAD

**Issue by Seleznev-nvkz** [celery/celery#5936]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
I was trying to change config of Redis backend connections (not Kombu _broker_transport_options_). 
This is not a problem for `socket_timeout` and `socket_connect_timeout` (I've set `CELERY_REDIS_SOCKET_TIMEOUT` and `CELERY_REDIS_SOCKET_CONNECT_TIMEOUT`), but problem to change `socket_keepalive` and `retry_on_timeout`.
I think this can be helpful - sometimes I catching `TimeoutError` from Beat on `'SUBSCRIBE'` event.

# Suggestions
I propose add `socket_keepalive` and `retry_on_timeout` to connparams of `RedisBackend`:
https://github.com/celery/celery/blob/240ef1f64c8340bfffc31359f842ea4a6c8c493a/celery/backends/redis.py#L185-L194

**Comment by dejlek** [comment]
There are all sorts of Redis connection errors that could cause problems with Celery that we deal on a daily basis... Most typical ones are timeout errors. `retry_on_timeout`, as far as I know, does it only once, so it is almost useless...

**Comment by Seleznev-nvkz** [comment]
> There are all sorts of Redis connection errors that could cause problems with Celery that we deal on a daily basis... Most typical ones are timeout errors. `retry_on_timeout`, as far as I know, does it only once, so it is almost useless...

Sometimes I catch TimeoutError on the start of periodic task (on "SUBSCRIPTION" event). This rare and important task and I think this retry can be helpful:

https://github.com/andymccurdy/redis-py/blob/ff69f0d77284643909462ee6d1e37233c6677672/redis/client.py#L877-L893

**Comment by dejlek** [comment]
Yep, it will definitely help in this case.

**Comment by thedrow** [comment]
What about using [`result_backend_trasport_options`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#result-backend-transport-options)?

**Comment by Seleznev-nvkz** [comment]
> What about using [`result_backend_trasport_options`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#result-backend-transport-options)?

Thank you for your feedback. 
I've tried to use this (set as `app.conf.result_backend_trasport_options` and as `CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS` in Django settings):
```{'socket_timeout': 10, 'socket_connect_timeout': 60, 'socket_keepalive': True, 'retry_on_timeout': True}```

But nothing happened. I mean I started Beat and I've debugged a few places, for example:
1) `celery.backends.redis.RedisBackend._create_client `
2) `redis.connection.Connection.__init__`
And parameters are:
 ```{'host': '127.0.0.1', 'port': 6379, 'db': 0, 'password': None, 'max_connections': None, 'socket_timeout': 120.0, 'socket_connect_timeout': None}```

But when I set `CELERY_REDIS_SOCKET_TIMEOUT = 10` and `CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = 60` - parameters changed:
```{'host': '127.0.0.1', 'port': 6379, 'db': 0, 'password': None, 'max_connections': None, 'socket_timeout': 10.0, 'socket_connect_timeout': 60.0}```

And I suggested setting socket_keepalive and retry_on_timeout like that.
