### ISSUE TITLE
sending CTRL+C to the worker 

### ISSUE THREAD

**Issue by ra7bi** [celery/celery#5937]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

https://stackoverflow.com/questions/16493364/stopping-celery-task-gracefully

#### Possible Duplicates

- None

# Brief Summary

Im using celery to execute python subprocess (Bash script ) in the background , My bash script will keep running until it receive **CTRL+C** to stop and do some **cleaning in the OS** ,  i tried to use 

`app.control.revoke('d9078da5-9915-40a0-bfa1-392c7bde42ed',terminate=True, signal='SIGINT')`

But the task keep running in the background , i read the docs and issues list and i could not get clear answer how i can send CTRL+C to the running worker telling him to stop the task using CTRL+C not terminating the task by killing the process because if i kill the process , my background process will break my OS , 

Example :
My background program (Bash script) doing some analytic and it will never stop until i click ctrl+c , when i click ctrl+c the bash script will restore all settings to default , in other hand if i kill the process the settings will remain changed .

**How i can send CTRL+C to the running process ?**

I tried 
http://docs.celeryproject.org/en/latest/userguide/workers.html#revoke-revoking-tasks
https://docs.python.org/dev/library/signal.html#module-signal
but nothing works .

FYI , im  using latest version of celery and python 3.7 with debain

**Comment by frost-nzcr4** [comment]
Does you've use `--pool=solo`?

**Comment by georgepsarakis** [comment]
In order to properly propagate signals in your Bash script, you need to use trap or `exec` in the script. Perhaps [this article](https://veithen.io/2014/11/16/sigterm-propagation.html) would help you understand the issue further. As this does not seem as a Celery issue, I am closing it, but let me know if you have further questions!
