### ISSUE TITLE
example code doesn't match description in "Next Steps"

### ISSUE THREAD

**Issue by wamcvey** [celery/celery#5940]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

`docs/getting-started/next-steps.rst` includes the text:

> The backend argument specifies the result backend to use, It's used to keep track of task state and results. While results are disabled by default I use the RPC result backend here because I demonstrate how retrieving results work later, you may want to use a different backend for your application

However, the code that is included is `examples/next-steps/proj/celery.py` which uses the amqp backend.

## Screenshot of the issue:
![image](https://user-images.githubusercontent.com/82541/73284238-45478f80-41c2-11ea-95bc-2471c2320267.png)

# Suggestions

Simply change the next-steps.rst doc file to say "I use the AMQP/Rabbitmq result backend here because..."

**Comment by auvipy** [comment]
care to send a PR?

**Comment by auvipy** [comment]
we can switch to rpc backend in both docs and codes as well......

**Comment by auvipy** [comment]
but checking the code i can see 
![image](https://user-images.githubusercontent.com/6212603/108460953-ed376b80-72a3-11eb-8866-10fee68b9643.png)

**Comment by auvipy** [comment]
its already fixed here https://github.com/celery/celery/issues/6459
