### ISSUE TITLE
How do I open a normal issue for celery ?

### ISSUE THREAD

**Issue by BrunoDesthuilliers** [celery/celery#5957]
ATM I can choose between a "Minor Version Release Checklist" template marked "for maintainers only", and sub-projects (kombu / billiard / etc) subtrackers...  And the "If this doesn’t look right, choose a different type" link brings me back to the same set of choices ;-)

**Comment by martey** [comment]
The issue templates for the repository are currently broken. This should be fixed once my pull request #5955 is merged.

**Comment by thedrow** [comment]
Fixed. You can close this issue.
