### ISSUE TITLE
Celery workers getting restarted while publishing messages on pub-sub

### ISSUE THREAD

**Issue by rohanjaswal2507** [celery/celery#5961]
Problem I have encountered:
I am running a celery task which pulls messages in batches(20 in one go) from a pubsub topic, does some minor manipulations in the message data and then again publishes those messages to another topic on Pub-Sub.

While this above task runs, celery worker abruptly gets restarted and worker processes sometimes receive "SIGNAL 11".
Process 'ForkPoolWorker-1' pid:28 exited with 'signal 11 (SIGSEGV)'

What I expected to happen:
The task should run smoothly and be able to publish as many messages to the target topic.

Steps to reproduce:
Well, the steps to reproduce could be little time taking.
1. Create a celery app
2. Write a task which publishes messages in bulk to a pub-sub topic
3. Start the celery worker
4. Execute the task

Other information (workarounds I have tried, documentation consulted, etc):

Here is what my requirements file looks like in my django application running in an Python 3.6.6 environment.

django==2.0.5
djangorestframework==3.8.2
djangorestframework-jwt==1.11.0
gunicorn==19.9.0
django-cors-headers==2.3.0
google-cloud-logging==1.6.0
google-cloud-storage==1.11.0
raven==6.9.0
uwsgi==2.0.17
requests==2.22.0
redis==3.3.11
tldextract==2.2.2
slackclient==1.3.0
kombu==4.6.3
celery==4.2.1
django-celery-beat==1.1.1
newrelic==5.4.1.134
google-cloud-pubsub==0.41.0

While looking for solutions on internet, I stumbled upon some segmentation fault issues with grpc. I have tried the following versions of grpcio, but still not able to get rid of the problem. grpc versions that I tried:
1. 1.9.0
2. 1.26.0
3. 1.27.2

The same piece of code that is used to publish messages works fine when runs in the main django application(web server) instead of celery worker. We had the segmentation fault issues in the web server as well, but that was solved after tweaking some wsgi configuration.
New config values which solved the problem in wsgi web server are:
UWSGI_LAZY_APPS=1
UWSGI_WSGI_ENV_BEHAVIOR=holy
UWSGI_ENABLE_THREADS=true

Please let me know if I doing anything wrong here and what I can I do to solve this issue. I have raised the issue on Google issue tracker as well.
https://issuetracker.google.com/issues/149715225

**Comment by auvipy** [comment]
please try celery==4.4.0+ django==2.2.x at least

**Comment by rohanjaswal2507** [comment]
@auvipy Have there been significant upgrades between these versions? Appreciate if you could share the Change log.

**Comment by auvipy** [comment]
actually tons of changes. you can check the docs in github

**Comment by rohanjaswal2507** [comment]
Okay. Thanks @auvipy

**Comment by thelinuxer** [comment]
Hi @rohanjaswal2507 

It seems like I am facing the exact same issue. How were you able to pin down the cause of the restarts ? Did upgrading celery to 4.4.0 fix the issue ? Did you need to upgrade django too ?

Appreciate your help.

**Comment by lucas03** [comment]
seeing same issue on `celery[pytest]==5.1.1` and `google-cloud-pubsub==2.4.1`

> Process "ForkPoolWorker-1" pid:21 exited with "signal 11 (SIGSEGV)"

**Comment by thelinuxer** [comment]
@lucas03 Can you please try to set environment variable GRPC_POLL_STRATEGY=poll for your celery instances ? That helped me fix my issue. Google Pub/Sub uses gRPC internally and it was the cause of celery crashes. Here's also the [list](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) of gRPC related environment variables

**Comment by lucas03** [comment]
Thanks for suggestion, however I am not able to test it easily. moving import inside celery task already fixed the issue for me and I could not easily reproduce this on testing apps :(
