### ISSUE TITLE
Getting the SVG logo of Celery

### ISSUE THREAD

**Issue by ranrib** [celery/celery#5981]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

# Request
Hi there! I would love to have the celery logo as an SVG please. Can you share it in the repo please?

**Comment by auvipy** [comment]
what will you do with that?

**Comment by ranrib** [comment]
I'm part of [Epsagon](https://epsagon.com), where we trace the call and visualize them on a graph. We would love to put the celery logo on the graph when the users trace these calls, and we rather prefer to use an SVG instead of a png.

**Comment by ranrib** [comment]
Hi @georgepsarakis @auvipy - any updates please?

**Comment by georgepsarakis** [comment]
Hi @ranrib , I don't think that a SVG format image exists in the project asset files, but I managed to find a large PNG (512px) [here](https://github.com/celery/celery/blob/master/docs/images/celery_512.png). Not sure if it helps though :disappointed: .

**Comment by mmyjona** [comment]
[celery_512.svg.zip](https://github.com/celery/celery/files/4849674/celery_512.svg.zip)
here u go

**Comment by ranrib** [comment]
Thanks @mmyjona ! super appreciate it :)
