### ISSUE TITLE
How to link a task to an other running task

### ISSUE THREAD

**Issue by NullYing** [celery/celery#5982]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

How to link a task to an other running task

like this?
```python
result = celery.AsyncResult(parents_task.task_id)
result.add_children(new_task_id)
```
## Diagrams

N/A

## Alternatives

None

**Comment by jheld** [comment]
There might be a way to do this, but if the task is running you are going to have a race against time (the task may have finished before you can act, not to mention needing to build a custom command on the worker to do the linking logistics). You will likely have a low success rate, as a human.

**Comment by NullYing** [comment]
yes, It maybe have problem. so I check the redis queue and add task when the task finish
