### ISSUE TITLE
TLS-enabled Redis configuration: the ssl_cert_reqs is wrongly documented

### ISSUE THREAD

**Issue by NBardelot** [celery/celery#5988]
See source file: celery/backends/redis.py

The documentation says:

> Note that the ssl_cert_reqs string should be one of required, optional, or none (though, for backwards compatibility, the string may also be one of CERT_REQUIRED, CERT_OPTIONAL, CERT_NONE).

But with 'required':

`AttributeError: module 'ssl' has no attribute 'required'`

It seems that CERT_REQUIRED, CERT_OPTIONAL and CERT_NONE *must* be used...

**Comment by auvipy** [comment]
can you send a PR to fix the doc and mention me?

**Comment by NBardelot** [comment]
I don't know if it's the documentaiton that should be fixed or the code that should match the behaviour described in the doc...

**Comment by auvipy** [comment]
thanks!
