### ISSUE TITLE
TypeError: _iter_meta() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by zeonn** [celery/celery#5990]
bug in version celery 4.4.1

version celery 4.4.0 works well

redis version 5.0

pyton packege redis version 3.4.1

file: celery/backends/redis.py, line 150
`for meta in result._iter_meta(**kwargs):`

**Comment by auvipy** [comment]
its fixed in master. expect a hot fix soon

**Comment by zeonn** [comment]
thanks for the fast answer
