### ISSUE TITLE
Questions about the gunicorn and flask and celery and redis ask congestion

### ISSUE THREAD

**Issue by LinXiaoJian** [celery/celery#6008]
python 3.7  flask 1.1.1 Redis 3.3.11

When I use the flask and celery, I found my task will be jam, I sent the task have not received any response, after I restart the program, all blocked tasks will appear together, I have ruled out the problem on the business code, at the moment, I really think that other possibilities

This is my setup

```python
def celery_task(app):
    celery = Celery(name, backend=backend, include=['app.service.celery_task_service'])
    celery.conf.update(
        broker_url=broker_url,
        task_default_queue=queue,
        worker_log_format='%(asctime)s - %(name)s - %(filename)s - %(levelname)s - %(lineno)d - %(message)s',
        worker_concurrency=4,
        worker_max_tasks_per_child=200,
        result_expires=1200
    )

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    ext.celery = celery
    ext.celery.start(argv=['celery', 'worker', '-Q', queue, '-l', 'info', '-n', name])
```

gunicorn

```gunicorn
import multiprocessing

workers = multiprocessing.cpu_count()
bind = "0.0.0.0:8080"
threads = multiprocessing.cpu_count() * 5
loglevel = 'info'
timeout = 300
```

requirements.txt
```python
pika
aniso8601==8.0.0
arrow==0.15.5
attrs==19.3.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
docopt==0.6.2
enum34==1.1.6
Flask==1.1.1
Flask-Caching==1.8.0
Flask-Cors==3.0.8
future==0.18.2
idna==2.8
importlib-metadata==1.4.0
itsdangerous==1.1.0
Jinja2==2.10.3
MarkupSafe==1.1.1
more-itertools==8.1.0
mypy==0.761
mypy-extensions==0.4.3
packaging==20.0
peewee==3.13.1
phonenumbers==8.11.1
pluggy==0.13.1
protobuf==3.11.2
py==1.8.1
pycparser==2.19
PyMySQL==0.9.3
pyparsing==2.4.6
pytest==5.3.2
python-dateutil==2.8.1
pytz==2019.3
redis==3.3.11
requests==2.22.0
six==1.13.0
tablestore==5.1.0
typed-ast==1.4.0
typing-extensions==3.7.4.1
urllib3==1.25.7
validator.py==1.3.0
wcwidth==0.1.8
Werkzeug==0.16.0
yarg==0.1.9
zipp==0.6.0
sentry-sdk==0.14.0
yunpian_python_sdk==1.0.0
upyun==2.5.4
pyencrypt-plus==1.0.0
Flask-APScheduler==1.11.0
dacite==1.2.0
Celery==4.4.1
pypinyin==0.37.0
Crypto==1.4.1
```

This happens a lot, and I later configured task_time_limit and used the timer to resend the task to resolve the blockage, which worked fine, but I was still confused about the cause of the jam.

I doubt it has anything to do with gunicorn, as I haven't had this problem with directly booting flask locally

Any ideas? Thanks

**Comment by mrfox321** [comment]
I have been getting this as well.  

API request come in -> task hangs (need results back) -> gunicorn timeout (60s) -> client retry -> .... 5 minutes later ->  all the previous requests hit the queue and process like mad

Are you getting similar behavior?  

What specific settings did you set to fix it for yourself?

**Comment by nguyenhaiquoc** [comment]
Sound like the time to open connection between your app and celery broker is very high. Where is the backend broker? It is on same machine with your web app?

**Comment by mrfox321** [comment]
It was unrelated, we were being dDOS'd.
