### ISSUE TITLE
Handle SIGABRT and Getting Info About The Worker

### ISSUE THREAD

**Issue by aeroheart-c6** [celery/celery#6021]
### Environment
software -> celery:4.3.0 (rhubarb) kombu:4.6.8 py:3.6.10
            billiard:3.6.3.0 redis:3.4.1
platform -> system:Linux arch:64bit
            kernel version:4.9.125-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: 'redis://redis:6379/0'
broker_pool_limit: 0
worker_concurrency: 5
worker_prefetch_multiplier: 1
task_acks_late: True
task_default_queue: 'default'
task_default_exchange: 'default'

I tried to look for my question but didn't seem to come up any. I hope I am not mistaken. (Also, I can't seem to find how to post an Issue Type: Question issue)

### Background
I am working on a fork of Airflow in our company and my task involves making sure tasks are aborted properly when we restart the celery worker (to update the system). I've done some digging around and realised, I can extend the Worker class and attach the signal handler there. Currently, I'm testing it on SIGABRT but I'm thinking of moving it to SIGTERM when I'm done.

There are three API calls I need to do on SIGABRT in order for me to complete my logic:

- get queues (`Control.broadcast("active_queues")`)
- cancel consumer on those queues (`Control.broadcast("cancel_consumer")`)
- get active tasks (`Control.broadcast("active")`)

If I get these, then I can go and properly abort the Airflow tasks currently being executed by a specific worker node.

When I do this on the Python REPL or as a separate script, these API calls work flawlessly. But when I implement them inside the Worker, I get empty results and when my function ends, I get an exception about

```
kombu.exceptions.OperationalError:
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
```

I created a sample project that contains only the code I am working on [in this repository](https://github.com/aeroheart-c6/samples-celery)

This also contains the extra script I describe about getting the worker statistics and some other convenience command to run a task and send the SIGABRT signal.

Want to shed some light in this, if my approach is wrong, or if I do not need to call any API then would like to know how.

Thanks in advance.

**Comment by auvipy** [comment]
you should try latest celery and report back again.
