### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by leetcode-xu** [celery/celery#6028]
CELERYBEAT_SCHEDULE = {
        'celery_app':{
            'task':'celery_app.task_add.add',
            'schedule':timedelta(seconds=10),
            'args':(2,8),
            },
        'celery_crontab':{
            'task':'celery_app.task_crontab.crontab_mul',
            'schedule':celery.schedules.crontab(hour=10,minute=30),
            'args':(4,5),
            },
        }
在celeryconfig.py中添加上面的就出现异常，求帮忙

**Comment by SAmmer0** [comment]
I have the same issue, but it cannot be repeated everytime I run the program, sometimes it occurs, sometimes it doesn't appear, that's strange
