### ISSUE TITLE
maintain a connection to mqtt broker in worker

### ISSUE THREAD

**Issue by mttbx** [celery/celery#6034]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

How should I maintain a connection to broker in worker so that when I do the task, I can publish messages to broker?
# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
I would suggest you ask your support question to StackOverflow or celery-users mailing list first.
