### ISSUE TITLE
'settings' object has no attribute 'result_serializer'

### ISSUE THREAD

**Issue by karambaq** [celery/celery#6038]
## Environment & Settings

**Celery version**: 4.4.2 (cliffs)

While migrating from OS X to Linux I've faced the following issue:

```
$ celery -A mkstat worker -B -l INFO
Error: 
Unable to load celery application.
'settings' object has no attribute 'result_serializer'
```

my settings.py:
```
CELERY_BROKER_URL = "redis://localhost:6379"

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Moscow"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
CELERY_RESULT_BACKEND = "redis://" + REDIS_HOST + ":" + REDIS_PORT
CELERY_BEAT_SCHEDULE = {
    "update_db": {"task": "stats.tasks.update_db", "schedule": 15.0,},
}
```

python version is 3.8

**Comment by georgepsarakis** [comment]
Hello @karambaq , thanks for the report. I think we need some more information. Would you mind attaching the output of the worker command with debug-level logging enabled (`-l DEBUG`)?

**Comment by auvipy** [comment]
looking for your feedback @karambaq

**Comment by karambaq** [comment]
I've switched to another Linux version and issue disappeared, thanks.
