### ISSUE TITLE
Missing changelog for 4.4.1 and 4.4.2

### ISSUE THREAD

**Issue by thomas-riccardi** [celery/celery#6041]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- #5875 for the last changelog update: 4.4.0

#### Possible Duplicates

- None

# Description
There is no changelog for 4.4.1 and 4.4.2 versions

# Suggestions
Add "changelog update" to the release checklist, even for patch releases.

**Comment by thedrow** [comment]
@auvipy Please don't release without a changelog.
This is not how we manage this project.

**Comment by auvipy** [comment]
added missing changelog 9ebe30dbf9aa34eb98fecfe1e84f8e3890755647 & 15a1edc0d4b23fd3009187da2de6d1bbba96335a
