### ISSUE TITLE
Add Ability To Specify Scheme For ElasticsearchBackend 

### ISSUE THREAD

**Issue by ctaylor4874** [celery/celery#6045]
# Checklist

Please add the ability to specify `https` scheme for results backend. Right now, it seems that http is the default with no way to change it. If this already exists can you please point me to it?

https://github.com/celery/celery/blob/6be45237355f0f61ad9e68b018ea1c007fa66f78/celery/backends/elasticsearch.py#L38

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by georgepsarakis** [comment]
Hello @ctaylor4874 . As far as I can tell, the HTTPS scheme should already be supported:

https://github.com/celery/celery/blob/6be45237355f0f61ad9e68b018ea1c007fa66f78/celery/backends/elasticsearch.py#L58

Can you provide a sample of your results backend configuration?

**Comment by ctaylor4874** [comment]
> Hello @ctaylor4874 . As far as I can tell, the HTTPS scheme should already be supported:
> 
> https://github.com/celery/celery/blob/6be45237355f0f61ad9e68b018ea1c007fa66f78/celery/backends/elasticsearch.py#L58
> 
> Can you provide a sample of your results backend configuration?
I've tried putting `https` in several places and it doesn't work.

If you look at the _parse_url function it does not look like it supports https.
```python
def url_to_parts(url):
    # type: (str) -> urlparts
    """Parse URL into :class:`urlparts` tuple of components."""
    scheme = urlparse(url).scheme
    schemeless = url[len(scheme) + 3:]
    # parse with HTTP URL semantics
    parts = urlparse('http://' + schemeless)
    path = parts.path or ''
    path = path[1:] if path and path[0] == '/' else path
    return urlparts(
        scheme,
        unquote(parts.hostname or '') or None,
        parts.port,
        unquote(parts.username or '') or None,
        unquote(parts.password or '') or None,
        unquote(path or '') or None,
        dict(parse_qsl(parts.query)),
    )
_parse_url = url_to_parts  # noqa
```

**Comment by ctaylor4874** [comment]
> Hello @ctaylor4874 . As far as I can tell, the HTTPS scheme should already be supported:
> 
> https://github.com/celery/celery/blob/6be45237355f0f61ad9e68b018ea1c007fa66f78/celery/backends/elasticsearch.py#L58
> 
> Can you provide a sample of your results backend configuration?

I've tried putting `https` in several places and it doesn't work. I may just be putting it in the wrong place though. Do you have an example? Here's my configuration without knowing where to put `https`

`CELERY_RESULT_BACKEND = 'elasticsearch://username:password@elasticurl.esstg.com:9243/data-stream/_doc'`

If you look at the _parse_url function it does not look like it supports https.
```python
def url_to_parts(url):
    # type: (str) -> urlparts
    """Parse URL into :class:`urlparts` tuple of components."""
    scheme = urlparse(url).scheme
    schemeless = url[len(scheme) + 3:]
    # parse with HTTP URL semantics
    parts = urlparse('http://' + schemeless)
    path = parts.path or ''
    path = path[1:] if path and path[0] == '/' else path
    return urlparts(
        scheme,
        unquote(parts.hostname or '') or None,
        parts.port,
        unquote(parts.username or '') or None,
        unquote(parts.password or '') or None,
        unquote(path or '') or None,
        dict(parse_qsl(parts.query)),
    )
_parse_url = url_to_parts  # noqa
```

**Comment by georgepsarakis** [comment]
`_parse_url` seems to support the HTTPS scheme as well:

```python
In [4]: _parse_url('https://a:b@hostname:9243/path')
Out[4]: urlparts(scheme='https', hostname=u'hostname', port=9243, username=u'a', password=u'b', path=u'path', query={})
```

Could you please try the following and report back:

```python
CELERY_RESULT_BACKEND = 'elasticsearch+https://username:password@elasticurl.esstg.com:9243/data-stream/_doc'
```

**Comment by georgepsarakis** [comment]
@ctaylor4874 any updates? :smile:

**Comment by auvipy** [comment]
let us know the update, Cody!

**Comment by ctaylor4874** [comment]
> @ctaylor4874 any updates? 😄

Yes! @georgepsarakis your recommendation worked!
