### ISSUE TITLE
docs: undocumented use of CELERY_CACHE_BACKEND in result_backend Configuration 

### ISSUE THREAD

**Issue by rob101** [celery/celery#6047]
When using `django-celery-results` with the `CELERY_RESULT_BACKEND = 'django-cache'` setting, it is possible to use the `CELERY_CACHE_BACKEND`to specify a Django cache other than default.

[Fix 5301](https://github.com/celery/celery/pull/5639) amended the docs for `django-celery-results` but the [Configuration ](http://docs.celeryproject.org/en/v4.2.0/userguide/configuration.html#std:setting-cache_backend)page of the user guide describes this setting as "no longer used" and suggests it can be set directly in the [results_backend](http://docs.celeryproject.org/en/v4.2.0/userguide/configuration.html#std:setting-result_backend) setting which is not documented.

**Comment by georgepsarakis** [comment]
Thanks for the report @rob101. Have you verified this behavior with latest versions?

If yes, then would you like perhaps to open a Pull Request with the suggested documentation fixes?

**Comment by auvipy** [comment]
would love to know the current status and glad to see a PR!
