### ISSUE TITLE
Is MongoDB suported as result backend?

### ISSUE THREAD

**Issue by rafaelreuber** [celery/celery#6074]
The [documentation](https://docs.celeryproject.org/en/stable/userguide/configuration.html#task-result-backend-settings) about result backend settings does not shows MongoDB as a suported option.

The options available are:
* rpc
* database (SQLAlchemy)
* redis
* cache
* cassandra
* elasticsearch
* ironcache
* couchbase
* arangodb
* couchdb
* cosmosdbsql (experimental)
* filesystem
* consul
* azureblockblob
* s3

**Comment by thedrow** [comment]
Yes we do support MongoDB as a result backend.
Would you mind issueing a PR to fix the documentation?

**Comment by rafaelreuber** [comment]
I'm using the the Formiko to edit the .rst files. But it shows so much errors. 
There is a way to generate an html vesion as showed on https://docs.celeryproject.org?
