### ISSUE TITLE
Revoked LimitedSet add/update not respecting TTL/expires consistently

### ISSUE THREAD

**Issue by jheld** [celery/celery#6076]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

When a task is revoked and/or worker is mingling and receives revoked task data, when adding or updating it's store with the new info, it should always purge it's data (let the purge function do it's job by asking the data to decide which IDs have expired and should be discarded). It doesn't seem clear to me why this isn't the case (rational/history, etc).

# Actual Behavior

When revoking a task (whether by expiration or some other process/control), the documentation for the data structure on each worker holding the revoked task IDs says that when adding a task to it, if the maxlen is reached, or other items have reached expiration, those respective items will be removed from the LimitedSet data structure.

Docs for the LimitedSet arguments (specifically on expires): https://docs.celeryproject.org/en/stable/internals/reference/celery.utils.collections.html#celery.utils.collections.LimitedSet say that when an item is added, items that should be expired will be. The add docs only mention maxlen logic being applied, for when purge is internally called. Now, I understand why this check is made, but it also leads to a bug where we're waiting (for who knows how long), for the next task to be revoked...and eventually we hope to reach the max, or another worker will come online and force us to update our set, and that method will do the proper thing, in a _small_/_wishful_ thinking number of cases. It only works well (on revoke sharing and general revocation) if maxlen is reached.

Bug in the docs and in the source code for the logic in add: https://docs.celeryproject.org/en/stable/internals/reference/celery.utils.collections.html#celery.utils.collections.LimitedSet.add (the source code for `add` only purges if maxlen is hit).

**Comment by auvipy** [comment]
sorry for the late. would you mind coming with a PR with a failing test case? even just a failing test case without any fix is also cool.

**Comment by jheld** [comment]
No worries!

This is just a downstream issue from the other one. Once I read the code comments and the latest PR more I understood more why the code is written this way. I do think the documentation could still use some minor edits, but based on the background info I don't think there is a bug anymore.

**Comment by jheld** [comment]
I'm going to close this (for now). I do think it may be worth adjusting the docs, but per the PR it is working as designed.

**Comment by auvipy** [comment]
thanks
