### ISSUE TITLE
I have problem with celery beat on windows 10 

### ISSUE THREAD

**Issue by fatemehloni** [celery/celery#6080]
I try to run celery on windows 10,
I use python 2.7+ flask and celery version=4.1.0 
I run below comment for celery beat:
'celery -A app.celery beat'

and I faced with this error:
"[2020-05-09 11:56:51,474: ERROR/MainProcess] beat: Connection error: [Errno 10061] No connection could be made because the target machine actively refused it."

rabbitmq and redis are start and I tried some of solution but problem did not solved yet:((

please get me advice.

**Comment by auvipy** [comment]
use celery 4.4.2 and post your support question to celery-users mailing list
