### ISSUE TITLE
celery containers exits imeediately with apache superset

### ISSUE THREAD

**Issue by billy-odera** [celery/celery#6083]
I am running superset with celery in docker using the below docker run to allow asynchronus calls

> sudo docker run --detach -e REDIS_SERVER_IP=xxx.xxx.xx.xx -e REDIS_PASSWORD=myredispassword -e POSTGRES_SERVER_IP=xxx.xxx.xx.xx -e POSTGRES_PASSWORD=mypostgrespassword --volume $PWD:/etc/superset --volume $PWD:/var/lib/superset amancevice/superset celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair

but the container exits immediately after starting and I ma unable to run sql queries in superset
![image](https://user-images.githubusercontent.com/12785557/81662949-f78c2580-9446-11ea-8b92-0d6e6da9a95b.png)

**Comment by auvipy** [comment]
I'm not sure it's a celery issue. can you try eventlet? -Ofair should be default from celery 4.0. you should be using celery==4.4.*

**Comment by auvipy** [comment]
use the support mailing list for help first
