### ISSUE TITLE
Celery worker stops receiving tasks

### ISSUE THREAD

**Issue by gundeepsn84** [celery/celery#6087]
Following is my celery config object file:
```
CELERY_BROKER_URL = mongo_settings.CELERY_BROKER_URI
CELERY_RESULT_BACKEND = "mongodb"
CELERY_MONGODB_BACKEND_SETTINGS = {
    "host": mongo_settings.HOST,
    "port": mongo_settings.PORT,
    "database": "queue" + os.getenv('Env'),
    'user': mongo_settings.USER,
    'password': mongo_settings.PASSWORD,
    'options': {"ssl": False},
    "taskmeta_collection": "taskmeta_collection" + os.getenv('Env'),
}
CELERY_INCLUDE = ["Operations.clustering", "Operations.pptExport", "Operations.notifications",
                  "Operations.sync_responses", "Operations.text_analysis_dump"]
CELERY_DEFAULT_QUEUE = 'default-' + os.getenv("Env")
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERYD_MAX_TASKS_PER_CHILD = 2
CELERY_DEFAULT_ROUTING_KEY = 'default'
CELERY_QUEUES = (
    Queue('default-' + os.getenv("Env"), Exchange('default', 'direct'), routing_key='default'),
    Queue('ta-dump-' + os.getenv("Env"), Exchange('ta-dump', 'direct'), routing_key='ta-dump'),
    Queue('clustering-' + os.getenv("Env"), Exchange('clustering', 'direct'), routing_key='clustering'),
    Queue('ppt-export-' + os.getenv("Env"), Exchange('ppt-export', 'direct'), routing_key='ppt-export'),
    Queue('notifications-' + os.getenv("Env"), Exchange('notifications', 'direct'), routing_key='notifications')
)
CELERY_ROUTES = {
    'PptExport': {
        'queue': 'ppt-export-' + os.getenv("Env"),
        'routing_key': 'ppt-export'
    },
    'PushNotifications': {
        'queue': 'notifications-' + os.getenv("Env"),
        'routing_key': 'notifications'
    },
    'TextAnalysisDump': {
        'queue': 'ta-dump-' + os.getenv("Env"),
        'routing_key': 'ta-dump'
    }
}

CELERYBEAT_SCHEDULE = {
    'move_partial_to_final': {
        'task': 'MovePartial2Final',
        # Every 10 minutes
        'schedule': crontab(minute="*/10"),
        'options': {'queue': 'default-' + os.getenv('Env')}
    },
    'do_keywords_clustering': {
        'task': 'AutoClustering',
        # After every 2 days
        'schedule': crontab(minute=0,hour=0,day_of_month="*/2"),  # minute=0,hour=0,day_of_month="*/2"
        'options': {'queue': 'clustering-' + os.getenv('Env')}
    }
}
```

After sometime the tasks keeps cluttering in the broker but are not executing by worker. Please help me resolve this issue as it occurs randomly.

**Comment by auvipy** [comment]
please update the issue with appropriate template and guideline

**Comment by gundeepsn84** [comment]
> please update the issue with appropriate template and guideline

What information else do you need for this?

**Comment by auvipy** [comment]
celery versions, the code you are running / failing test case, traceback

**Comment by gundeepsn84** [comment]
**celery version: 4.3.0 (rhubarb)**

Unexpected Behavior: After executing some tasks the worker stops executing new coming tasks and it does not even give any error or traceback.

When i restart the celery worker then it starts executing those cluttered tasks.

Expected behavior: Worker should execute each and every task which is being received.

**Comment by auvipy** [comment]
try the latest or master branch

**Comment by adi-** [comment]
@gundeepsn84 Check out https://docs.celeryproject.org/en/stable/userguide/workers.html#time-limits and set `soft-time-limit`. I had similar symptoms. Problem was with connection error which never failed and blocked worker.

**Comment by auvipy** [comment]
> @gundeepsn84 Check out https://docs.celeryproject.org/en/stable/userguide/workers.html#time-limits and set `soft-time-limit`. I had similar symptoms. Problem was with connection error which never failed and blocked worker.

should this be closed?

**Comment by gundeepsn84** [comment]
> > @gundeepsn84 Check out https://docs.celeryproject.org/en/stable/userguide/workers.html#time-limits and set `soft-time-limit`. I had similar symptoms. Problem was with connection error which never failed and blocked worker.
> 
> should this be closed?

Yes, it solves the issue
