### ISSUE TITLE
Celery class based task is not retrying

### ISSUE THREAD

**Issue by nanduajith** [celery/celery#6117]
I defined a class-based celery task defined as follows:

```python
class MyTask(Task):  
    name = "MY_TASK"
    autoretry_for = (Exception, )
    retry_kwargs = {'max_retries': 5}
    retry_backoff = True
    retry_backoff_max = 700
    retry_jitter = False

    def run(self, *args, **kwargs):
        pass
        # do something
        # return some value

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        # can extend failure method if needed
        super().on_failure(exc, task_id, args, kwargs, einfo)


app.tasks.register(MyTask())
```
### Issue
My task is executing perfectly. But when an exception occurs, the task is not retried

### Expected behaviour
The task should retry

**Comment by mchataigner** [comment]
It's not an issue. By default Celery does not restart tasks. You have to catch the exception and raise self.retry() special method yourself. This will trigger the retry.
All is documented here => https://docs.celeryproject.org/en/stable/userguide/tasks.html#retrying

**Comment by nanduajith** [comment]
@mchataigner Then what is the purpose of `autoretry_for=(Exception, )`. I defined it in my task class, So the task should retry in case of an exception right? 
https://docs.celeryproject.org/en/stable/userguide/tasks.html#automatic-retry-for-known-exceptions

**Comment by mchataigner** [comment]
My bad, I missed that, sorry.
@auvipy could you reopen this issue?

**Comment by nanduajith** [comment]
@mchataigner  @auvipy  
The `autoretry_for` worked when I used it in the task decorator. But didn't work when I defined the task as a class.

**Comment by art-vasilyev** [comment]
Figured out that auto-retry is added only to function based tasks, submitted a pull request that fixes this issue.

**Comment by auvipy** [comment]
thanks!
