### ISSUE TITLE
Question: missed schedules in celery beat

### ISSUE THREAD

**Issue by ajaykmr2292** [celery/celery#6124]
I am using celery beat to trigger my scheduled tasks. Suppose, my scheduler was down for some time and there were scheduled tasks in that down period. When I restart the scheduler later, will the pending task be triggered? If not, how can I trigger tasks that were missed during the down period.

**Comment by auvipy** [comment]
use the celery-users mailing list for a question.

**Comment by ajaykmr2292** [comment]
I asked this question 10 days ago. But I didnt get any reply from the `celery-users` mailing list.
