### ISSUE TITLE
Celery 4.4.4 raises TypeError: set() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by robvdl** [celery/celery#6155]
This doesn't happen on 4.4.3, only on 4.4.4.

Here is a traceback:

```
celery_default_1      | [2020-06-04 19:51:47,723: ERROR/MainProcess] Pool callback raised exception: TypeError('set() takes 3 positional arguments but 4 were given',)
celery_default_1      | Traceback (most recent call last):
celery_default_1      |   File "/usr/share/dashboard/venv/lib/python3.6/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
celery_default_1      |     fun(*args, **kwargs)
celery_default_1      |   File "/usr/share/dashboard/venv/lib/python3.6/site-packages/celery/worker/request.py", line 528, in on_failure
celery_default_1      |     store_result=self.store_errors,
celery_default_1      |   File "/usr/share/dashboard/venv/lib/python3.6/site-packages/celery/backends/base.py", line 169, in mark_as_failure
celery_default_1      |     traceback=traceback, request=request)
celery_default_1      |   File "/usr/share/dashboard/venv/lib/python3.6/site-packages/celery/backends/base.py", line 443, in store_result
celery_default_1      |     request=request, **kwargs)
celery_default_1      |   File "/usr/share/dashboard/venv/lib/python3.6/site-packages/celery/backends/base.py", line 858, in _store_result
celery_default_1      |     self.set(self.get_key_for_task(task_id), self.encode(meta), state)
celery_default_1      | TypeError: set() takes 3 positional arguments but 4 were given
```

I am running on Python 3.6 on Bionic.

For now I've stuck to 4.4.3 as 4.4.4 keeps throwing this exception.

# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

4.4.4

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.4 (cliffs) kombu:4.6.10 py:3.6.10
            billiard:3.6.3.0 py-amqp:2.6.0
platform -> system:Linux arch:64bit, ELF
            kernel version:5.3.0-51-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6.10
* **Minimal Celery Version**: 4.4.4
* **Minimal Kombu Version**: 4.6.10
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: Ubuntu 18.04 + 5.3 kernel
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.6.0
argh==0.26.2
asgiref==3.2.7
Babel==2.8.0
backcall==0.1.0
billiard==3.6.3.0
celery==4.4.4
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
coverage==5.1
decorator==4.4.2
defusedxml==0.5.0
Django==2.2.13
django-celery-beat==2.0.0
django-celery-results==1.2.1
django-crispy-forms==1.9.1
django-csp==3.6
django-extensions==2.2.9
django-nose==1.4.6
django-redis==4.12.1
django-timezone-field==4.0
djangorestframework==3.11.0
flower==0.9.3
ftputil==3.4
future==0.18.2
gunicorn==20.0.4
hiredis==1.0.1
icalendar==4.0.6
idna==2.9
importlib-metadata==1.6.0
ipdb==0.13.2
ipdbplugin==1.5.0
ipython==7.15.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.0
jsonfield==2.0.2
kombu==4.6.10
lxml==4.3.5
nose==1.3.7
parso==0.7.0
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==5.4.1
prompt-toolkit==3.0.5
psycopg2==2.8.5
ptyprocess==0.6.0
pycodestyle==2.6.0
pyflakes==2.2.0
Pygments==2.6.1
python-crontab==2.5.1
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.2
raven==6.10.0
redis==3.5.3
requests==2.23.0
single-beat==0.4.1
six==1.15.0
sqlparse==0.3.1
suds-jurko==0.6
tornadis==0.8.1
tornado==5.1.1
traitlets==4.3.3
urllib3==1.25.9
vine==1.3.0
watchdog==0.9.0
wcwidth==0.2.3
whitenoise==5.1.0
zipp==3.1.0
```

</p>
</details>

### Other Dependencies

<details>
<p>

```
Ubuntu 18.04
Redis
Postgres 10
```

</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by auvipy** [comment]
@mchataigner can you check, please?

**Comment by robvdl** [comment]
I am using Redis as a broker.

I thought this info could help too possibly from my Django settings.py

```
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_BACKEND = 'django-cache'
CELERY_RESULT_EXPIRES = timedelta(minutes=30)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
```

We don't really care about results so don't really use that part.

**Comment by mchataigner** [comment]
I'm having a look.

**Comment by mchataigner** [comment]
I don't reproduce locally.
I would suggest to either running again `python setup.py install` or to recreate your virtualenv.

**Comment by robvdl** [comment]
I use Docker and rebuild all the time. It's fine I will investigate it some time later at work but it might be a while as I have a lot of other things going on and 4.4.3 is OK for now. Thanks for trying though.

**Comment by mchataigner** [comment]
to give you a bit more context, I added state to set method in KeyValueStoreBackend and applied the modification on all impacted backends.
Your error looks like some part of your application got the update and is trying to call store_result and set with this new argument state, but for some reason, your redis backend does not have this third arg.
The fact that the path in the traceback is `/usr/share/dashboard/venv/lib/python3.6/site-packages/celery/backends/base.py` made me think about a corrupted venv.

**Comment by robvdl** [comment]
Nah we just install our virtualenv in a weird place
/usr/share/dashboard/venv where dashboard is the application name

We rebuild the venv each time I do docker-compose rebuild, even tried
removing the image so I'm sure it's not that.

Thanks for your help though, I'll check out upgrading later and for now
stick to 4.4.3

**Comment by callorico** [comment]
@mchataigner It looks like @robvdl is using the `django-cache` results backend which as I understand it is part of the `django-celery-results` project. I think the culprit is that the set method in the cache backend in that project is missing the `state` argument:

https://github.com/celery/django-celery-results/blob/49ca37d2e00324488da6e8c2de46946371d7a4c6/django_celery_results/backends/cache.py#L21

**Comment by robvdl** [comment]
Thank you very much for narrowing it down. I don't have to use django-cache as a results backend I could completely disable it as I don't care for results.

But I think it should probably get fixed now that we know what the issue is, but does that mean the issue is in the django-celery-results package instead of celery itself?

**Comment by robvdl** [comment]
Here is the same ticket on django-celery-results:

https://github.com/celery/django-celery-results/issues/150

**Comment by auvipy** [comment]
got it thanks! will release a new compatible release soon
