### ISSUE TITLE
Expose config option to set retry_policy on (Redis) ResultBackend

### ISSUE THREAD

**Issue by ashb** [celery/celery#6166]
# Checklist

# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+) for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+) for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master) to find out if the if the same feature was already implemented in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue (If there are none, check this box anyway).

# Brief Summary

In debugging another problem I noticed that the default connection timeout for the Redis result backend is unconfigurable, and the timeout is hardcoded at 20s (20 x 1s retries)

This appears to be only actually an issue for the Redis backend (RPC is the only other backend that appears to do anything in `on_task_call`)

`task.apply_async()` calls  these functions

https://github.com/celery/celery/blob/d3863d909759f1fd618f2a1af1766ce54c16d39b/celery/app/base.py#L776-L780

https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/redis.py#L342-L344

https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/redis.py#L167-L177

https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/redis.py#L124-L133

`_ensure` is set via https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/redis.py#L97

to be https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/redis.py#L352-L358

But ensure is never passed any kwargs, nor is it set anywhere other than in the Backend supclass https://github.com/celery/celery/blob/bf6139bf651b20bc04b895a5f6eb8d50320bc252/celery/backends/base.py#L106-L111

# Design

The "most obvious" way of doing this would be to add a new top-level `result_backend_options` config key that feeds in to the constructor.

**Comment by auvipy** [comment]
I'll be lookin forward to a PR

**Comment by ashb** [comment]
Will find time to open one.

I'm still not that familiar with the internals of Celery/Kombu so wanted to check this all though first
