### ISSUE TITLE
celery 4.4.5 doesn't listen to `CELERY_RESULT_BACKEND` setting

### ISSUE THREAD

**Issue by kuba-lilz** [celery/celery#6182]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

Minimal Python Version: python 3.5
Minimal Celery Version: celery 4.3
Minimal Kombu Version: N/A or Unknown
Minimal Broker Version: redis 6.0.5
Minimal Result Backend Version: redis 6.0.5
Minimal OS and/or Kernel Version: osx 10.15.5, ubuntu 20.04
Minimal Broker Client Version: redis==3.5.3
Minimal Result Backend Client Version: redis==3.5.3

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Results should be stored when `CELERY_RESULT_BACKEND` config setting is specified.
# Actual Behavior

`CELERY_RESULT_BACKEND` is ignored. `result_backend` works as expected.

**Comment by auvipy** [comment]
can you provide more detail?

**Comment by kuba-lilz** [comment]
When running a real celery worker with `CELERY_RESULT_BACKEND` option, I get error:
```
Cannot mix new and old setting keys, please rename the
following settings to the new format:

CELERY_RESULT_BACKEND                -> result_backend
```

which, while not quite in line with documentation
( https://docs.celeryproject.org/en/stable/userguide/configuration.html#new-lowercase-settings )
that states that both new and old style settings are both honored, isn't too bad - error message is clear.

Things get more complex with py.test celery worker fixtures.

### When using py.test celery worker fixture with config['CELERY_RESULT_BACKEND'] set: 
- worker starts without raising any error, correctly processes tasks
- no tasks results/states are stored in backend (redis in my case)
	
### When using py.test celery worker fixture with config['result_backend'] set:
- tasks results/states are stored in backend, e.g.

	{
		"status": "SUCCESS",
		"result": null,
		"traceback": null,
		"children": [],
		"date_done": "2020-06-26T01:13:16.142240",
		"task_id": "835f3453-50fd-476e-81a0-f8d74f48cfca"
	}

**Comment by auvipy** [comment]
use this result_backend nd don't mix old settings with new lowercase.
