### ISSUE TITLE
@app.task should copy __annotations__ from the task function like @functools.wraps

### ISSUE THREAD

**Issue by davidparsson** [celery/celery#6186]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Proposed Behavior

Celery tasks created with `@app.task` should support `typing.get_type_hints(my_celery_task)`.

It can be solved by copying the `__annotations__` from the decorated function when available. This is done by `functools.wraps()` in Python 3.0+, if I understand [PEP 3107](https://www.python.org/dev/peps/pep-3107/) correctly. Without this `typing.get_type_hints(my_celery_task)` raises an exception.

It is my understanding that some other similar properties that `functools.wraps` handles are already copied: https://github.com/celery/celery/blob/d3863d909759f1fd618f2a1af1766ce54c16d39b/celery/app/base.py#L453-L454

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
we will consider this in near future

**Comment by davidparsson** [comment]
Thanks! Let me know if help is needed for this to be implemented.

**Comment by auvipy** [comment]
for celery 4.5 which will be python 3.6+ only

**Comment by davidparsson** [comment]
For anyone finding this before it's fixed, I have the following work-around:
```
@functools.wraps(decorated_function, assigned=('__annotations__',))
@celery_app.task(bind=True, base=base, priority=priority, name=name)
def task(): ...
```

**Comment by thedrow** [comment]
I think that's certainly desirable for Celery 5. We can also backport to 4.x.

@daviddavis Care to help us with that?

**Comment by davidparsson** [comment]
@thedrow, I guess you're asking me although you pinged someone else. Yes, I'll give it a shot, but it might be a few weeks until I find the time.

**Comment by thedrow** [comment]
I mentioned the wrong guy by accident. My apologies.
Edited for clarity.

**Comment by davidparsson** [comment]
#6419 is open.

@thedrow, https://github.com/celery/celery/issues/6186#issuecomment-702110825 mentions backporting, but the information on https://docs.celeryproject.org/en/master/contributing.html#maintenance-branches seems to be out-dated. Are there any branches for the versions to which this should be backported?

**Comment by thedrow** [comment]
> #6419 is open.
> 
> @thedrow, [#6186 (comment)](https://github.com/celery/celery/issues/6186#issuecomment-702110825) mentions backporting, but the information on https://docs.celeryproject.org/en/master/contributing.html#maintenance-branches seems to be out-dated. Are there any branches for the versions to which this should be backported?

Yes. We need to backport to the v4.5 branch.

**Comment by davidparsson** [comment]
@thedrow, please see https://github.com/celery/celery/pull/6428
