### ISSUE TITLE
own importlib No module named 'xxx'

### ISSUE THREAD

**Issue by SoryegeToon** [celery/celery#6191]
celery version: 4.4.6
python version: 3.7
My project structure
app
├── test1
│   └── b.py
├── test2
│   └── c.py
└── test.py

When not in use celery:
#test.py 
from test1.b import daoru
print(daoru())

#test1/b.py
import celery
import time
backend='redis://127.0.0.1:6379/3'
broker='redis://127.0.0.1:6379/4'
app=celery.Celery('test',backend=backend,broker=broker)
import importlib

@app.task()
def daoru():
    test = importlib.import_module('test2.c')
    return test

#test2/c.py
def add(name):
    return name

![图片](https://user-images.githubusercontent.com/58411533/85858069-8c779200-b7ed-11ea-8e7d-0a3f47f1c780.png)
Importlib was successful

but i use celery:

edit test.py
#test.py 
daoru.delay()

start celery
celery worker -A test1.b -l info
run test.py
![图片](https://user-images.githubusercontent.com/58411533/85858394-26d7d580-b7ee-11ea-96ae-854453d626f9.png)
celery was importlib No module named 'test2'

i try sys.append('./test2') sys.append('../test2')
and move test2 in test1 dir 
But it still doesn't work of celery
I'm not very good at Python or it's my problem，thanks

**Comment by SoryegeToon** [comment]
#test.py
from test1.b import daoru
daoru.delay()

![图片](https://user-images.githubusercontent.com/58411533/85858938-03f9f100-b7ef-11ea-8a52-25ee2a0366f0.png)
![图片](https://user-images.githubusercontent.com/58411533/85858969-0fe5b300-b7ef-11ea-9e90-91d44eb68530.png)

**Comment by thedrow** [comment]
This is your problem.
You need an `__init__.py` file.

Next time, please ask on StackOverflow as this is not related to Celery.
