### ISSUE TITLE
how to improve publish rate in celery.

### ISSUE THREAD

**Issue by xcTorres** [celery/celery#6192]
When I test on my Mac, I sent 1000 tasks every second with only one producer, and every task is about 4KB. But the published rate is just 150/s, which is far below my expectation.  I have checked the memory usage, and there is no memory issue.

**Comment by xcTorres** [comment]
I used group tasks function in tests. I found the 'group(tasks).apply_async()' costs more than 2 seconds. But if I don't use group method and just send task one by one, the time of ending all tasks(1k) is just about 400 ms, which result in published rate 1500/s.

**Comment by auvipy** [comment]
use mailing list for help
