### ISSUE TITLE
Fetching time within the celery task.

### ISSUE THREAD

**Issue by waqashamid** [celery/celery#6193]
Hey guys,
Hope everyone here is doing really well.
I have specific celery and celery beat related problem.
So, what we're trying to do is generate a report every two hours and collect data for the past 2 hours.
For ex. if a task is scheduled to run at 8am, 10am and 12pm and so on - every two hours.
I need to get two values from which equals 8-2 which is 6am and and to which is 8-1=7am.
Using these times I need to collect all the data generated in the above time slot and run some reports.
The problem I am facing is that I am unable to get this time within the celery task which is 8am for example.
I could do a timezone.now() inside the task to get the current time but that wouldn't be accurate since it might take some time for beat to queue that task and make it visible to the workers.
So, I basically need to figure out a way to get the time and schedule provided to celery beat at which it was expected to get triggered.
While I understand that there are ways to get this time from my settings.py that I had provided to celery beat but in my specific use case, I cannot do a lookup there.
I tried going through the documentation to figure this out but I did not find a way to get this time within every task.
What are the possible ways to get the exact time from beat? Are there hooks in celery or maybe sys that I can leverage for my use case?
Thanks in advance :slightly_smiling_face:

**Comment by auvipy** [comment]
use the mailing list and then follow the issue templates as suggested.
