### ISSUE TITLE
celery任务调用无响应

### ISSUE THREAD

**Issue by YXinAndy** [celery/celery#6195]
我在使用celery分布式调用时，调用某些异步任务，在debug级别下，无响应，也无任何日志，最后导致任务积压堵塞。
是否有什么方式可以确认异常如何发生，发生在哪里?谢谢

**Comment by thedrow** [comment]
We're sorry. We don't speak Chinese.

In any case, there's not enough information for us to help you resolve this bug.
Please fill the template we provided.
