### ISSUE TITLE
Acl, user permission for celery tasks

### ISSUE THREAD

**Issue by jen-soft** [celery/celery#6198]
Acl, user permission for celery tasks

Hello, i am sorry i wasn't find solution for my problem.
may be some one know how it resolve.
---
at my website, django-users are able start celery tasks.
but i need to display for user only his own tasks. - need to create view "my tasks"

i see two aways
1) one away - use exra args for task
- add to celery-task extra args like user-id 
- then  receive at django-view all celery-tasks
- and filter tasks by user-id 

2) another away
create new table user-tasks with two fields
user = forignkey to django-user model
celery-task-id = char field
and after start task add new recrd to table user-tasks
and at "my tasks" view just select tasks for user fo last 24 hours.

may be is passable use queue or add username to rout or tasks name
and then filter ti.

---
thanks for any idea : )

**Comment by thedrow** [comment]
Please file this issue in https://github.com/celery/django-celery-beat.
