### ISSUE TITLE
CELERY_DB_REUSE_MAX possibly broken by #6134

### ISSUE THREAD

**Issue by thomas-riccardi** [celery/celery#6216]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/celery/pull/6134
- https://github.com/celery/celery/issues/4116

## Environment & Settings

**Celery version**:
today master: 39209f2db2021eb0b685603ae4b6d0e3a5894849

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
https://github.com/celery/celery/blob/39209f2db2021eb0b685603ae4b6d0e3a5894849/celery/fixups/django.py#L180
Here maybe it should be `_close_database(force=True)`, following #6134: when celery db max reuse is reached we probably do want to really close everything and not ask django to maybe close them according to django settings.

# Actual Behavior

**Comment by whtsky** [comment]
Makes sense to me.

I didn't know about `CELERY_DB_REUSE_MAX` earlier; I can’t find it in documentation expect from [the changelog of version 1.0.2](https://github.com/celery/celery/blob/b2668607c909c61becd151905b4525190c19ff4a/docs/history/changelog-1.0.rst#102) . It is still supported or should be deprecated?

**Comment by thedrow** [comment]
You haven't provided the necessary debugging information and you didn't describe the actual behavior.
As such we cannot help you with this issue at this time.

We will close it until you will edit the original issue with all the details required.

**Comment by thomas-riccardi** [comment]
@thedrow 
> You haven't provided the necessary debugging information and you didn't describe the actual behavior.
> As such we cannot help you with this issue at this time.
> 
> We will close it until you will edit the original issue with all the details required.

This is a potential issue I found while browsing the code and the recent change in it by #6134 , not at runtime.
I did not test anything, thus the partial bug report, but since the change was fresh I assumed reporting this potential issue would be of value for the project: avoid an unnecessary regression.
