### ISSUE TITLE
Run celery as daemon: ModuleNotFoundError: No module named '-n'

### ISSUE THREAD

**Issue by FPEPOSHI** [celery/celery#6224]
I'm trying to run celery as a service in ubuntu but I'm having this error:
`ModuleNotFoundError: No module named '-n'`

```
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '-n'
celery multi v4.4.6 (cliffs)
```

I can't find any other issue related to this one

**Comment by thedrow** [comment]
@auvipy Why did you close this issue?

**Comment by auvipy** [comment]
this didn't follow proper issue reporting. so closed without any further ado.

**Comment by FPEPOSHI** [comment]
@auvipy you are right but it would be great to let us know the reason why you closed it, just saying.

**Comment by thedrow** [comment]
@FPEPOSHI Feel free to file a new issue with all the details and a reproducible test case.
