### ISSUE TITLE
Wrong handling of options when place before the subcommand

### ISSUE THREAD

**Issue by JulienPalard** [celery/celery#6228]
The `_relocate_args_from_start` from 25eb48a7e42bfbf56520400955dbe06ff7ecd594 treats doubly-dashed options differently than singly-dashed options, giving an inconsistency:

- `celery -A hkis worker --loglevel debug` works as expected (no handling via `_relocate_args_from_start` needed)
- `celery -A hkis worker -l debug` works as expected (no handling via `_relocate_args_from_start` needed)
- `celery -l debug -A hkis worker` works as expected (`-l debug` is moved to the end via `_relocate_args_from_start`)
- `celery --loglevel debug -A hkis worker` gives a usage, because it gets transformed by `_relocate_args_from_start` into `celery  debug -A hkis worker --loglevel`.

The usage given by `celery --loglevel debug -A hkis worker` is not helpfull as it don't mention `-l` or `--loglevel` at all, and it probably can't easily be made usefull as it's triggered by the fact that `debug` was tried as a command, but is not, we lost the fact that the command was `worker` at this step (`-l` / `--loglevel` is documented in the `worker` subcommand).

This is related to https://github.com/celery/celery/issues/4558 which is partially fixed by *not* giving to `_relocate_args_from_start` the arguments that were understood by the general parser, but `--loglevel` is an option of `worker`, not a general option, so it's kept after parsing general options, and is given to `_relocate_args_from_start`.

It could maybe be fixed by making `_relocate_args_from_start` aware of the arguments, to let it check if they're `store_true`/`store_const` style or if they except arguments. It would greatly complexify the work of `_relocate_args_from_start`, probably introducing some other subtle bugs in the process (as I often say, Errors = MoreCode²).

Argument parsing in Celery looks already complicated, I would favor deprecating the practice of putting subcommands argument *before* the subcommand name, which looks never mentionned in the doc, as far as a rapid grep of the doc tells me, but could be used in the wild.

It would obviously need a deprecation period issuing a warning in `_relocate_args_from_start` when it in fact relocate arguments to avoid breaking stuff too fast, but it would allow to remove `_relocate_args_from_start` and this issue.

What do you think?

**Comment by auvipy** [comment]
Julien, as celery moved to click in v5.x, would you mind revisit this issue considering that?

**Comment by JulienPalard** [comment]
Wow, I see celery 5 deprecated having the argument in strange orders like giving subparsers argument before subparsers, like:

    celery --loglevel debug -A hkis worker

This is the right move, and it probably have cleaned a lot of very hard to fix code, and added consistency, happy to see this.

**Comment by auvipy** [comment]
> Wow, I see celery 5 deprecated having the argument in strange orders like giving subparsers argument before subparsers, like:
> 
> ```
> celery --loglevel debug -A hkis worker
> ```
> 
> This is the right move, and it probably have cleaned a lot of very hard to fix code, and added consistency, happy to see this.

thanks for your helpful feedback :)
