### ISSUE TITLE
How to get queue length from RabbitMQ broker?

### ISSUE THREAD

**Issue by rwillmer** [celery/celery#623]
Is this possible from within celery? 

I know I could do a horrible hack to get it by declaring a low-level queue and checking the queue_declare return, but that seems an ugly way to do it.

**Comment by almasudme** [comment]
This is 2019 we can do it using kombu. 
Here is a piece of code where you can get a dictionary of informations related to a specific queue
import kombu

requested_queues = ["queue_1","queue_2"]

conn = kombu.Connection('amqp://user:password@host_ip_address:5672/vhost')
conn.connect()
client = conn.get_manager()
queues = client.get_queues('vhost')
for queue in queues:
    if queue.get("name") in requested_queues:
        print(queue["name"])
        print(queue["messages_ready"])
        print(queue['messages_unacknowledged'])


this should print the mdepth of queue with queue name, number of tasks still needs to be consumed by a worker, number of tasks currently running. Hope if someone is looking for the answer in 2019 will help.
