### ISSUE TITLE
Celery with SQS - Unrestored task 

### ISSUE THREAD

**Issue by jainraj** [celery/celery#6242]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.2.1 (windowlicker) kombu:4.6.7 py:3.6.5
            billiard:3.5.0.5 sqs:N/A
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled

BROKER_TRANSPORT_OPTIONS: {
    'polling_interval': 1,
    'queue_name_prefix': 'celery_dev-',
    'region': 'eu-west-1',
    'sqs-creation-attributes': {'KmsMasterKeyId': '********'},
    'visibility_timeout': 3600,
    'wait_time_seconds': 10}
BROKER_URL: 'sqs://localhost//'
CELERYBEAT_SCHEDULE: {***}
CELERYD_LOG_FORMAT: ('%(asctime)s %(name)s '
 '%(process)d-0@local '
 '[%(levelname)s] %(pathname)s:%(lineno)d '
 '%(funcName)s(): %(module)s: %(message)s')
CELERY_ACKS_LATE: True
CELERY_ENABLE_REMOTE_CONTROL: False
CELERY_ENABLE_UTC: True
CELERY_SEND_EVENTS: False
CELERY_TIMEZONE: 'Asia/Kolkata'
DEBUG: True
DEFAULT_VISIBILITY_TIMEOUT: 3600
REGION_NAME: 'eu-west-1'
USE_API_AUTH: '********'
crontab: <class 'celery.schedules.crontab'>
env: 'dev'
gethostname: <built-in function gethostname>
CELERY_INCLUDE: ['tasks.generic_tasks']
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: Python 3.6.5 
* **Minimal Celery Version**: 4.2.1
* **Minimal Kombu Version**: 4.6.7
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.2
aws-requests-auth==0.4.2
awscli==1.16.53
billiard==3.5.0.5
boto3==1.9.161
botocore==1.12.182
celery==4.2.1
certifi==2019.11.28
chardet==3.0.4
circus==0.15.0
click==6.7
colorama==0.3.9
docutils==0.14
elasticsearch==6.2.0
elasticsearch-curator==5.8.0
flasgger==0.9.2
Flask==1.0.2
gunicorn==19.9.0
idna==2.7
importlib-metadata==1.3.0
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
jsonpickle==1.0
jsonschema==2.6.0
kombu==4.6.7
MarkupSafe==1.0
mistune==0.8.4
more-itertools==8.0.2
mysqlclient==1.3.13
psutil==5.4.8
pyasn1==0.4.4
pycurl==7.43.0.1
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
pyzmq==16.0.4
redis==2.10.6
requests==2.19.1
requests-aws4auth==0.9
rsa==3.4.2
s3transfer==0.2.1
six==1.11.0
SQLAlchemy==1.2.14
tornado==4.5.3
urllib3==1.22
vine==1.3.0
voluptuous==0.11.7
Werkzeug==0.14.1
zipp==0.6.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
Obtained this issue once in production
</p>
</details>

# Expected Behavior

Task should be processed by other available consumers

# Actual Behavior

## Context

- We have 3 machines in prod for celery workers and have a one-by-one deployment strategy. Hence, at any time, we have 2 workers available to pick up tasks 
- As mentioned above, the visibility timeout is kept 1 hr 
- We have one task which is triggered by 2 crons. One cron @ 5th, 35th and 50th minute of every hour. Another @ 20th minute. (The difference is in parameters passed to the task) 

## Issue 
- Around 9:20 PM, we had a deployment for the celery worker machines. The beat machine was deployed later. 
- A task, T1, was scheduled successfully. Verified by the "Sending due task" logs from beat machine
- Ideally within a few seconds, the task is picked up by the worker machines, but no logs are found. I checked the logs of "Received task" 
- Around 10:20 PM, beat schedules another task (T2). Verified by the "Sending due task" logs from beat machine
- This time, we see the "Received task" logs twice. 
- Verified that they are not the same task "instance" by comparing the task ids. This also rules out the possibility that SQS gave double delivery (at least once effort)

## Hypothesis
The task, T1, was received by the master process in one machine. This triggered the visibility timer at SQS. The task was not yet passed to the worker threads. During sigterm, the task was not restored to SQS and thus, after the visibility timeout = 1 hr, the task got picked up and executed 

## Callouts 
- This issue has occurred once as per our knowledge (I discovered this while root causing another issue). Thus, unsure if this is happening already multiple times but not getting caught.
- Unable to reproduce this on local / beta machines

## Expectation from the community
1. Does the hypothesis imply the issue? 
2. Any ideas on how to reproduce such a condition successfully? 
3. What logs would be better to switch on at celery side so that we can catch this issue next time it happens. (We can't possibly move to debug level because the sheer volume is too high)

**Comment by auvipy** [comment]
before reporting an issue, you should try the latest release from PyPI which is 4.4.6. I will reopen after you update your reported celery version to the latest.

**Comment by thedrow** [comment]
@jainal09 Part of the checklist is to check if the bug is reproducible with master as well.
We don't expect you to upgrade if you can't. We do expect you to try reproducing the problem with at least the latest version before reporting.

**Comment by jainal09** [comment]
@thedrow i think you tagged the wrong person 😄.
I guess It was for @jainraj.

**Comment by pbudzon** [comment]
Sounds like may another one be related to: https://github.com/celery/kombu/pull/2049
