### ISSUE TITLE
dependency on future module breaks many things (including vim ultisnips)

### ISSUE THREAD

**Issue by graingert** [celery/celery#6250]
the dependency on future-0.18.2 adds many packages that squat on py3 stdlib names eg:

```
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/_dummy_thread/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/_markupbase/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/_thread/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/builtins/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/copyreg/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/future-0.18.2.dist-info/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/future/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/html/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/http/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/libfuturize/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/libpasteurize/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/past/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/queue/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/reprlib/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/socketserver/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/tkinter/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/winreg/*
    /home/graingert/.virtualenvs/celery2/lib/python2.7/site-packages/xmlrpc/*
```

this breaks packages that rely on feature detection of these modules.

I propose replacing future with six because:

* future does not provide a wheel, six has a wheel
* future last release Oct 31, 2019, six released Oct 31, 2019
* future is 829.2 kB, six is (11.0 kB) 
* celery already depends on six, via kombu and importlib-metadata, and so swapping out future with six would save 829.2 kB, rather than just 818.2 kB

# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by graingert** [comment]
@auvipy can you cut a release for this fix please, (even if in rc)?

**Comment by auvipy** [comment]
this Friday morning!

**Comment by graingert** [comment]
@auvipy amazing, thanks!
