### ISSUE TITLE
Security policy?

### ISSUE THREAD

**Issue by caleb15** [celery/celery#6262]
There isn't any security policy defined in https://github.com/celery/celery/security
I can't find any section on where to report security vulnerabilities in the readme or wiki either.

I found a security [wiki article](https://docs.celeryproject.org/en/master/userguide/security.html?highlight=security) but no contact information was listed.

* Where should I report a vulnerability?
* Can a security policy be added to https://github.com/celery/celery/security please?
* Can a link to above security policy be added to the `security` wiki article?

if you click on "start setup" in https://github.com/celery/celery/security/policy it gives you a nifty template that can be filled out.

**Comment by georgepsarakis** [comment]
Good point! @thedrow maybe we could consider it in a CEP?

References:
- https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

**Comment by thedrow** [comment]
There was a security policy but I wasn't handed access to the email address where security issues were reported.
We need to think this one and write a CEP.

@caleb15 Are you up for it?

**Comment by caleb15** [comment]
what is a CEP? I can make a PR adding a link in the "security" page in the docs to the security policy but as for the policy itself I'm not qualified to create it as I don't know who security issues should be reported to or how celery is maintained in general.

**Comment by auvipy** [comment]
It is done in master branch
