### ISSUE TITLE
Restore pydocstyle in CI

### ISSUE THREAD

**Issue by thedrow** [celery/celery#6278]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

I'm not sure when pydocstyle was removed from the build matrix but we I wasn't made aware of it.
We need this to ensure our documentation coverage and style are in check.

# Design

Just revert the commit which removed it.

## Architectural Considerations

None

## Proposed Behavior

N/A

## Proposed UI/UX

N/A

## Diagrams

N/A

## Alternatives

None

**Comment by graingert** [comment]
@thedrow pydocstyle is still run, via flake8

**Comment by georgepsarakis** [comment]
Adding my comment here for completeness https://github.com/celery/celery/pull/6281#issuecomment-668229523

**Comment by graingert** [comment]
@geoffreybauduin flake8-docstrings is an official pycqa wrapper of pydocstyle in the same way flake8 wraps pycodestyle, all tools maintained by the pycqa team

**Comment by thedrow** [comment]
Got it. :+1:
