### ISSUE TITLE
stop loading pytest plugin by default

### ISSUE THREAD

**Issue by graingert** [celery/celery#6280]
currently celery, by default, will add a set of fixtures and a mark, which can be confusing to new developers on a project when running `pytest --fixtures` and begin using them even through we've not yet opted into and started configuring them.

An alternative is to use an approach like https://github.com/aio-libs/pytest-aiohttp/ where there is a shim package that just lists an entrypoint, and depends on aiohttp.

Those that don't want to install the shim package can add `pytest_plugins = 'celery.contrib.pytest'` to their `pytest.ini`

# Checklist

- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by thedrow** [comment]
I'll address this later but note that we have a template for feature requests/enhancements.

**Comment by graingert** [comment]
@thedrow I'm happy to make the PR, I'm just looking for a concept ack

**Comment by thedrow** [comment]
We can create a pytest-celery shim package for Celery 5.0.0 if you'd like.

**Comment by ddangu525** [comment]
`pytest_plugins` option is not available in pytest.ini file. So I tried to put that in conftest.py but it raises error in task decorator.(`module object is not callable`)

**Comment by graingert** [comment]
@ddangu525 docfix is here: https://github.com/celery/celery/pull/6387

**Comment by graingert** [comment]
@ddangu525 did you try installing `pytest-celery` or `celery[pytest]`?
