### ISSUE TITLE
unignore    `F821,  # undefined name '...'`

### ISSUE THREAD

**Issue by graingert** [celery/celery#6283]
F821 is one of the most useful flake8 rules, however it's currently disabled because type comments reference undefined names.

it can be fixed with a conditional dependency on `typing` or importing typing in an `if False:` block, see discussion here: https://github.com/PyCQA/pyflakes/issues/501

# conditional dep
```
# requirements.txt
typing; python_version < '3.5'
```

```python
# some_annotated.py
from typing import Any, Tuple

if typing.TYPE_CHECKING:
    from celery import Celery
```

# `if False:`
```python
# some_annotated.py

if False:
    from typing import Any, Tuple
    from celery import Celery
```

@auvipy @thedrow do you have a preferred `typing` import approach? mine is to add the conditional dep

# Checklist

- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [ ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by graingert** [comment]
@thedrow I saw you upvoted this, do you have a view on which approach to use?

**Comment by thedrow** [comment]
We should just cover Celery 5's code base with type annotations since master now supports the `typing` module natively.
