### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).

### ISSUE THREAD

**Issue by wyq984700527** [celery/celery#6291]
### The Error
**When a large number of tasks generated with high concurrency, it may randomly happen** 

![image](https://user-images.githubusercontent.com/52362142/89605849-2af11b80-d8a1-11ea-8cc4-8fa4aad9a5c2.png)

![image](https://user-images.githubusercontent.com/52362142/89605902-4825ea00-d8a1-11ea-95e0-7675aff45fca.png)

### The config

> 
    BROKER_URL = 'redis://:****@xxx:6379/6'
    CELERY_RESULT_BACKEND = 'redis://:****@xxx:6379/8'
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_ENABLE_UTC = True  
    CELERY_TIMEZONE = 'Asia/Shanghai'  
    CELERYD_HIJACK_ROOT_LOGGER = False  
    CELERYD_MAX_TASKS_PER_CHILD = 1  
    CELERYD_FORCE_EXECV = True

### The worker
`celery -A pro worker -E --loglevel=INFO --autoscale=15,3 `
### Env

> Linux xxx 3.10.0-1062.9.1.el7.x86_64
celery==4.4.6
Python 3.7.4

**pls help me fix it, thanks a lot.**

**Comment by 2m** [comment]
We also noticed similar crashes recently (SIGSERV). We reverted [`grpcio`](https://pypi.org/project/grpcio/) module back to `1.30.0` and it stopped crashing.

**Comment by wyq984700527** [comment]
> We also noticed similar crashes recently (SIGSERV). We reverted [`grpcio`](https://pypi.org/project/grpcio/) module back to `1.30.0` and it stopped crashing.

Change pool to `gevent` may be also work. after tasks about one hundred thousand consumed, no exception was generated.  thanks a lot.

**Comment by Kazauwa** [comment]
Same here. Unfortunately, we cannot downgrade `grpcio` as we don't have this dependency

**Comment by 2m** [comment]
> Unfortunately, we cannot downgrade grpcio as we don't have this dependency

Check if you are not getting this dependency transitively through other dependencies.

**Comment by Kazauwa** [comment]
It's not present in `pip freeze` output at all

**Comment by wyq984700527** [comment]
> It's not present in `pip freeze` output at all

Change pool to `gevent` maybe work, you can try it.

**Comment by wyq984700527** [comment]
> > Unfortunately, we cannot downgrade grpcio as we don't have this dependency
> 
> Check if you are not getting this dependency transitively through other dependencies.

In my project，it

**Comment by wyq984700527** [comment]
> > Unfortunately, we cannot downgrade grpcio as we don't have this dependency
> 
> Check if you are not getting this dependency transitively through other dependencies.

I have check the requirements in a test pro，there is no `grpcio` also.

**Comment by Kazauwa** [comment]
That's what I'm talking about. We don't have `grpcio`, but workers get SIGTERMed anyways

**Comment by wyq984700527** [comment]
> That's what I'm talking about. We don't have `grpcio`, but workers get SIGTERMed anyways

Change pool to `gevent` work for my pro, you could have a try.

**Comment by simion** [comment]
> We also noticed similar crashes recently (SIGSERV). We reverted [`grpcio`](https://pypi.org/project/grpcio/) module back to `1.30.0` and it stopped crashing.

We had many many `Worker exited prematurely: signal 11 (SIGSEGV)` errors. Downgrading `grpcio` to `1.30.0` fixed it.

**Comment by lgonzalezonestic** [comment]
Random segfaults after some uptime.

`billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM)`

Same problem here after unfreezing grpcio and installing 1.32.0. 

We are back to 1.30.0.

**Comment by qbx2** [comment]
`gevent` has an issue that freezes when I call streaming (for me, bidirectional) rpc call.
