### ISSUE TITLE
Celery Worker not starting with queue

### ISSUE THREAD

**Issue by lshreyasharmal** [celery/celery#6292]
`celery -A proj worker --autoscale=6,4 --loglevel=INFO -n worker_name -Q queue1,queue2`

I am using django-celery to run a task which in turn schedules another task in the 2nd queue. I am using redis as the broker. The problem is that with the above command, the worker isn't running, there's no message being printed in the logs about the task after the worker is "ready" as seen below:

> Logged in Successfully
> System check identified some issues:
> 
> WARNINGS:
> ?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
>  
>  -------------- celery@worker_name v3.1.25 (Cipater)
> ---- **** ----- 
> --- * ***  * -- Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
> -- * - **** --- 
> - ** ---------- [config]
> - ** ---------- .> app:         proj:0x7f0d03316eb8
> - ** ---------- .> transport:   redis://127.0.0.1:6379//
> - ** ---------- .> results:     redis://127.0.0.1:6379/
> - *** --- * --- .> concurrency: {min=4, max=6} (prefork)
> -- ******* ---- 
> --- ***** ----- [queues]
>  -------------- .> queue1           exchange=queue1(direct) key=queue1
>                 .> queue2           exchange=queue2(direct) key=queue2
> 
> [tasks]
>   . proj.celery.debug_task
>   . task1
>   . task2
> 
> [2020-07-31 14:53:31,916: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
> [2020-07-31 14:53:31,926: INFO/MainProcess] mingle: searching for neighbors
> [2020-07-31 14:53:32,933: INFO/MainProcess] mingle: all alone
> [2020-07-31 14:53:32,956: WARNING/MainProcess] {path}/superenv/lib/python3.6/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
>   warnings.warn('Using settings.DEBUG leads to a memory leak, never '
> [2020-07-31 14:53:32,956: WARNING/MainProcess] celery@worker_name ready.

celery==3.1.25

Django==2.1

django-celery==3.2.1

The weird thing is that this command used to work earlier but now I have to run a worker separately in order to get it work using-> celery -A proj  worker --loglevel=info

any ideas what I'm missing?

**Comment by auvipy** [comment]
Try latest version.
