### ISSUE TITLE
--max-tasks-per-child for gevent

### ISSUE THREAD

**Issue by oaosman84** [celery/celery#6312]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary
With `prefork`, there are a couple parameters `--max-tasks-per-child` and `--max-memory-per-child` that can help control memory usage in case of memory leaks. Those parameters aren't compatible with `gevent`. It would be awesome if there was a way to handle memory leaks with eventlets, where a restart or cleanup can be triggered 

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by thedrow** [comment]
Since gevent support is going away soon as we're migrating to an event loop ourselves in Celery 6.0 and the 4.x branch is no longer accepting new features I'm going to have to close this issue unfortunately.
