### ISSUE TITLE
How can i run 2 django different projects a daemon?

### ISSUE THREAD

**Issue by Hamza-Lachi** [celery/celery#6329]
Hi, My Question is How can i run 2 django different celery projects as a daemon?

i have 2 projects:

- emailv

- marla3

but now i have only 1 celeryd conf file which is in /etc/default so now what is the name i should use for marla3

to run

because celeryd file has a conf of emailv and that is running

but now i want to run marla3 also

what is the name of the marla3 file should i use?

**Comment by thedrow** [comment]
See explanation [here](https://github.com/celery/celery/blob/a1fb557b6ecc494514e3480518be57b985d0927d/extra/generic-init.d/celeryd#L22-L29).
