### ISSUE TITLE
4.4 "What's New" mis-reports configuration CELERY_TASK_RESULT_EXPIRES change

### ISSUE THREAD

**Issue by stringfellow** [celery/celery#6349]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- Half of the docs were reverted here: https://github.com/celery/celery/issues/6240 https://github.com/celery/celery/pull/6303 but this does not fix entirely

#### Possible Duplicates

- None

# Description

https://github.com/celery/celery/blob/v4.4.7/docs/whatsnew-4.4.rst#configuration states that `CELERY_TASK_RESULT_EXPIRES` has changed to `CELERY_RESULT_EXPIRES` but the new setting is ignored. Note that this change is not mentioned in the changelog, it is on the what's new page and has been recently reverted on the configuration page.

The code also seems to still require CELERY_TASK_RESULT_EXPIRES - e.g. https://github.com/celery/celery/blob/v4.4.7/celery/app/defaults.py#L213

# Suggestions

Change https://github.com/celery/celery/blob/v4.4.7/celery/app/defaults.py#L213 to `celery_result_expires` - I think this fixes the issue, or change both the "what's new" and configuration options pages to be the same.

**Comment by stringfellow** [comment]
I revoke my suggestion of changing the code to match the documents - the number of hours I have wasted making and provisioning changes to several repos because this config option supposedly changed its name is _absurd_... 

Please leave it as CELERY_TASK_RESULT_EXPIRES and revert docs 🙏

**Comment by auvipy** [comment]
I think only change needed is in whats new

**Comment by auvipy** [comment]
https://github.com/celery/celery/commit/197e419a38eaa4cdde300e147e7243a18be92724
