### ISSUE TITLE
Can I have multiple celery instances in Production.

### ISSUE THREAD

**Issue by sulaiman35** [celery/celery#6359]
Hi Team,

I have deployed celery in Production and at this time we have single instance, and I would like to have multiple instances that can work with redis cluster.
I have tried to use multiple celery instances but jobs are being processed by both celery instances separately which is an issue, so can you please help me in this ?

**Comment by georgepsarakis** [comment]
Hello @sulaiman35 ! GitHub issues are used mainly for reporting bugs and feature requests, for questions regarding [using Celery](https://docs.celeryproject.org/en/stable/community.html) you can use IRC, the mailing list of StackOverflow. Thank you.
