### ISSUE TITLE
RabbitMQ task_queue_ha_policy has no effect

### ISSUE THREAD

**Issue by mattbennett** [celery/celery#6361]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

The RabbitMQ setting [task_queue_ha_policy](https://docs.celeryproject.org/en/stable/userguide/configuration.html#task-queue-ha-policy) no longer has any affect, as [described in the release notes for version 3](https://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/).

This was [reported to the mailing list here](https://groups.google.com/u/1/g/celery-users/c/hiZPiz2JWo8/m/2_q_Q5sM0BIJ) (in 2013!) and the answer then was that it's deprecated and will be removed.

# Suggestions

Remove the configuration parameter and maybe reference the blog post and/or docs on how to set a policy.

**Comment by auvipy** [comment]
contributions are wellcome

**Comment by mattbennett** [comment]
@auvipy @safwanrahman The fix that has been merged here does not address the problem.

The [RabbitMQ release notes](https://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/) describe how **it is no longer possible** to configure HA at queue declaration time. You have to use a policy, which is set on the broker and cannot be controlled by the client.
