### ISSUE TITLE
[5.0.0] Celery does NOT start with both -D and -E options enabled

### ISSUE THREAD

**Issue by iamdavidcz** [celery/celery#6362]
Hi,

I've just installed Celery 5.0.0 and noticed that it doesn't start when both `-D` and `-E` options enabled:

Only `-E` options works fine:
```
$ celery -A sample.celery worker -E

 -------------- celery@MacBook-Pro.local v5.0.0 (singularity)
--- ***** -----
-- ******* ---- Darwin-19.6.0-x86_64-i386-64bit 2020-09-24 15:59:59
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         sample:0x7fc944afebd0
- ** ---------- .> transport:   amqp://guest:**@192.168.0.101:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: ON
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
```

But both `-D` and `-E` options doesn't work. It exits with exit code 0 and nothing happens...
```
$ celery -A sample.celery worker -D -E
```

**Info:**
Python 3.7.9
Celery 5.0.0 on macOS 10.15 Catalina.

**Comment by auvipy** [comment]
celery has some breaking changes in v5 please check them

**Comment by thedrow** [comment]
> celery has some breaking changes in v5 please check them

This sounds like a bug.
When detaching, all options should preserve.

**Comment by thedrow** [comment]
I just checked it myself. This is indeed a bug.
I'm looking into it.

**Comment by thedrow** [comment]
@iamdavidcz Can you please try the patch in #6394?
I'm pretty sure it fixes the issue.
