### ISSUE TITLE
celery 5.0.0 with Django==3.0.10 emits CDeprecationWarning. Following the advise breaks the app 

### ISSUE THREAD

**Issue by bastbnl** [celery/celery#6366]
Congrats on the v5 release 👏 and thank you for maintaining such a wonderful piece of software. Much appreciated.

I updated from `celery==4.4.7` to `celery==5.0.0` today and I'm using celery with Django 3.0.10. Celery produces this message - and others - after starting: 
```
[2020-09-25 11:31:17,362: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,364: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERYBEAT_SCHEDULE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the beat_schedule instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,364: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,365: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_ACCEPT_CONTENT' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the accept_content instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,365: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,366: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,367: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,367: WARNING/MainProcess] /var/www/brwnppr/dev/env/lib/python3.7/site-packages/celery/app/utils.py:206: CDeprecationWarning:
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  alternative=f'Use the {_TO_NEW_KEY[setting]} instead')

[2020-09-25 11:31:17,367: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
```

I ran the `celery upgrade` command on the Django project settings and it worked beautifully. Unfortunately the application appears to block after the upgrade command and I think that blocking is caused by celery falling back to amqp while the project I'm working on uses redis as the broker. The Django application itself blocks due to it trying to starting a task which fails for the same reason.

Reverted the settings - thanks for keeping a `.orig`  and it's up and running again. 

Now I have been looking through the code to see if I could come up with a PR to suppress this message, but that appears to be kind of hard due to the way the configuration is processed. I'll see if I can come up with something.

**Comment by craigds** [comment]
also getting this (with django 2.2.15)

**Comment by auvipy** [comment]
task_serializer is suggested from celery 4.0 which you are not using. not the caps CELERY_TASK_SERIALIZER

**Comment by craigds** [comment]
We're using the django-style configuration suggested in the docs, which has uppercase names prefixed with `CELERY_`: https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

> The uppercase name-space means that all Celery configuration options must be specified in uppercase instead of lowercase, and start with CELERY_, so for example the task_always_eager setting becomes CELERY_TASK_ALWAYS_EAGER, and the broker_url setting becomes CELERY_BROKER_URL. This also applies to the workers settings, for instance, the worker_concurrency setting becomes CELERY_WORKER_CONCURRENCY.

**Comment by auvipy** [comment]
> We're using the django-style configuration suggested in the docs, which has uppercase names prefixed with `CELERY_`: https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html
> 
> > The uppercase name-space means that all Celery configuration options must be specified in uppercase instead of lowercase, and start with CELERY_, so for example the task_always_eager setting becomes CELERY_TASK_ALWAYS_EAGER, and the broker_url setting becomes CELERY_BROKER_URL. This also applies to the workers settings, for instance, the worker_concurrency setting becomes CELERY_WORKER_CONCURRENCY.
> 
> Perhaps I should have led with that, I guess I assumed it. Code looks like:
> 
> ```python
> app.config_from_object('django.conf:settings', namespace='CELERY')
> ```

Does this seem to be inconsistent?

**Comment by thedrow** [comment]
This is indeed a problem.
The code which detects the deprecated settings does not distinguish between Django style settings and Celery's deprecated settings.
This is exactly one of the reasons I didn't remove support for the deprecated setting names.

https://github.com/celery/celery/blob/f05e82a32a737c4222ece0b446e7fb2fd8cc883f/celery/app/utils.py#L233-L287

We can adjust it to ensure it doesn't warn incorrectly, though I'm not sure how currently.

**Comment by thedrow** [comment]
> Running `celery upgrade settings --django` on the settings file produces no changes.

@craigds TBH, I'm not familiar with what the command does in detail.
I do believe that if the command makes no changes, then we should not be issuing a deprecation warning for those settings.

**Comment by bastbnl** [comment]
@thedrow I was thinking about that and I found a couple of possible fixes. The first is really simple and it just doesn't invoke `maybe_warn_deprecated_settings` (https://github.com/celery/celery/blob/v5.0.0/celery/apps/worker.py#L144) when `app._config_source == 'django.conf:settings'`. I didn't really like it, but it would work

The next, and that's the one I'm currently working on, is a fix where instead of using `django.conf:settings` you would use something like `celery.contrib.django:settings` which takes care of a lot of things, including changing the case on the keys. A difficulty with this approach is the prefix or namespace is not easily shared with the module.

**Comment by thedrow** [comment]
At this point I prefer quick solutions as we are working on our configuration subsystem as well.

The first solution you suggested certainly works.

**Comment by asottile-sentry** [comment]
is there an eventual "fix" for this?  will capitalized settings be supported indefinitely?

I'm still seeing this warning in celery==5.3.5 and django==3.2.23 and applying the suggestion breaks django due to it [requiring upper-cased settings](https://github.com/django/django/blob/2dca98f4f76e1296b842b183a9287086ec416b58/django/conf/__init__.py#L121-L122)
