### ISSUE TITLE
Celery 4.4.7 attempts to use amqp despite being given Redis broker_url & result_backend

### ISSUE THREAD

**Issue by bsolomon1124** [celery/celery#6370]
## Reproducible example

Install Celery 4.4.7:

```bash
python3 -m pip install -U 'celery[redis]==4.4.7'
```

Start Redis on 6395:

```bash
redis-server --daemonize yes --port 6395
```

Create `celeryfoo.py`:

```python
import time
from celery import Celery

celery = Celery("hi")

redis_host = "redis://127.0.0.1:6395/0"
celery.conf.broker_url = redis_host
celery.conf.result_backend = redis_host
celery.conf.beat_schedule = {
    "update-foo": {
        "task": 'celeryfoo.update',
        "schedule": 15,
        "args": (1, 2, 3)
    },
}
celery.conf.worker_redirect_stdouts = False
celery.conf.worker_log_color = False

@celery.task
def update(a, b, c):
    with open("foo.log", "a") as f:
        f.write(str(time.time()) + "\n")
    return a, b, c
```

Start celery worker:

```bash
celery --no-color -A celeryfoo:celery worker --detach -l DEBUG --logfile celery.log
```

Check `tail -f celery.log`:

```bash
[2020-09-28 11:01:51,908: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-09-28 11:02:24,029: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-09-28 11:02:56,118: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-09-28 11:03:28,221: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 32.00 seconds... (16/100)
```

## Mandatory Debugging Information

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
$ redis-cli -p 6395 PING
PONG
$ celery --version
4.4.7 (cliffs)
$ python3 --version
Python 3.8.5
```

**Comment by bsolomon1124** [comment]
Related:

- https://github.com/celery/celery/issues/2240
- https://serverfault.com/questions/1004382/celery-redis-django-errno-111-connection-refused
- https://askubuntu.com/questions/604072/celery-trying-to-connect-to-wrong-broker

**Comment by yifeiwu** [comment]
I think you need to install the additional dependencies to get redis to work or it'll default to something else https://docs.celeryproject.org/en/stable/getting-started/brokers/redis.html#broker-redis

**Comment by bsolomon1124** [comment]
@yifeiwu I receive the same amqp-related issue with the Redis Python client installed. (Already had it installed, but will update the post above to be more explicit.)

**Comment by bsolomon1124** [comment]
This appears to be related to use of [`--detach`](https://github.com/celery/celery/blob/f6b3e13f5cb69eb4fef5ff202b54f8e8a51737b1/celery/bin/worker.py#L292) arg to celery worker.

When I drop `--detach` and `--logfile`, and run

```bash
celery --no-color -A celeryfoo:celery worker -l DEBUG
```

I see, correctly,

```
- ** ---------- .> transport:   redis://127.0.0.1:6395/0
- ** ---------- .> results:     redis://127.0.0.1:6395/0

...

[2020-09-29 20:29:11,575: INFO/MainProcess] Connected to redis://127.0.0.1:6395/0
```

**Comment by bsolomon1124** [comment]
Yep, more confirmation with `C_FAKEFORK` shows wrong transport

```
$ C_FAKEFORK=1 celery --no-color -A celeryfoo:celery worker --detach -l DEBUG --logfile celery.log

- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
```

**Comment by bsolomon1124** [comment]
@thedrow @auvipy this looks to be a bug with `celery worker --detach`.

**Comment by bsolomon1124** [comment]
Looks to be a duplicate of https://github.com/celery/celery/issues/6304 and https://github.com/celery/celery/issues/6285.

Regression introduced in Celery 4.4.7. Downgrading to 4.4.6 makes `--detach` work.

This is a huge regression for a minor version bump!

**Comment by thedrow** [comment]
I agree.
If you have suggestions on how to fix it, please issue a PR.

**Comment by chescales** [comment]
+1, this broke our production servers until we noticed, as the OP said, it's a pretty big issue considering it's just a minor change right? Will downgrade for now. Thanks for posting the issue @bsolomon1124

**Comment by thedrow** [comment]
Again, our resources are very limited.
If you'd like to get this fixed, please suggest a fix and open a PR.

**Comment by latusaki** [comment]
For any future readers, this is not a problem with 5.0.2.

**Comment by thedrow** [comment]
> For any future readers, this is not a problem with 5.0.2.

Can you try to track which commit fixed it?

**Comment by auvipy** [comment]
this is probably the PR that caused the regression https://github.com/celery/celery/pull/6223 [ https://github.com/celery/celery/releases/tag/v4.4.7 ]

**Comment by jjorissen52** [comment]
5.0.5, can confirm that this is an issue.

**Comment by auvipy** [comment]
closing as we do not support 4.x branch anymore and it doesn't happen in v5+

**Comment by dejlek** [comment]
This bug hit us many times, so we were forced to downgrade to 4.4.6 ... Decision not support the previous stable major branch is just terrible.

**Comment by thedrow** [comment]
@dejlek We'd appreciate the help in maintaining 4.x.

**Comment by frankiedrake** [comment]
The bug still exists in `5.2.3` :(

**Comment by auvipy** [comment]
can you please share more detail?

**Comment by brunerm99** [comment]
I am using version `5.1.2` which seems to still have the issue. 

Starting the task in the background by adding `&` to the end of the worker start command (e.g., `celery -A celery_app worker -l INFO --logfile="celery.log" &`) seemed to work for me. This is in place of the `--detach` flag. 

Hope this helps anyone else looking here.

**Comment by eupharis** [comment]
For anyone else who finds this via Google, the problem might also be a bonehead misconfiguration :)

You have to import the `app` from your `celery.py` file somewhere.

You can put this in an `__init__.py` file:

```
# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app

__all__ = ('celery_app',)
```

**Comment by aqari-dev** [comment]
> Starting the task in the background by adding `&` to the end of the worker start command (e.g., `celery -A celery_app worker -l INFO --logfile="celery.log" &`) seemed to work for me. This is in place of the `--detach` flag.

It worked for me on `5.2.7`. Just curious, how did you figure this out?

**Comment by brunerm99** [comment]
> > Starting the task in the background by adding `&` to the end of the worker start command (e.g., `celery -A celery_app worker -l INFO --logfile="celery.log" &`) seemed to work for me. This is in place of the `--detach` flag.
> 
> 
> 
> It worked for me on `5.2.7`. Just curious, how did you figure this out?

Haven't thought of this bug for a while so I'm not sure how I figured it out. I'm sure just randomly trying a bunch of solutions out of desperation😂

**Comment by coreyb42** [comment]
Just ran into this myself. It took a combo of the advice above to get a worker running along with a Django management command that can push stuff to the worker.

1. Specify the broker/backend when you're creating the celery app:
    ```app = Celery('my_app', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')```
2. Right next to that, in `__init__.py`, import the app:
```from .celery import app as celery_app

__all__ = ('celery_app',)```

The first step was enough to get the worker running with this command:

```
celery -A infinity_renders worker -l info
```

The second step was necessary to get my management command to successfully add stuff to the queue via `@shared_task`.

If someone could update the docs, that would save a lot of hassle for random people running into this.

**Comment by auvipy** [comment]
> Just ran into this myself. It took a combo of the advice above to get a worker running along with a Django management command that can push stuff to the worker.
> 
>     1. Specify the broker/backend when you're creating the celery app:
>        `app = Celery('my_app', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')`
> 
>     2. Right next to that, in `__init__.py`, import the app:
> 
> 
> `from .celery import app as celery_app` `__all__ = ('celery_app',)`
> 
> The first step was enough to get the worker running with this command:
> 
> `celery -A infinity_renders worker -l info`
> 
> The second step was necessary to get my management command to successfully add stuff to the queue via `@shared_task`.
> 
> If someone could update the docs, that would save a lot of hassle for random people running into this.

Isn't this already documented?

**Comment by IvesFeng** [comment]
I have the same problem.
I solved it in a not-so-good way.
`vim /home/ubuntu/Project/env/lib/python3.10/site-packages/kombu/connection.py`
before
`    def _init_params(self, hostname, userid, password, virtual_host, port,
                     insist, ssl, transport, connect_timeout,
                     login_method, heartbeat):
        transport = transport or 'amqp'
        if transport == 'amqp' and supports_librabbitmq():`
after:
`    def _init_params(self, hostname, userid, password, virtual_host, port,
                     insist, ssl, transport, connect_timeout,
                     login_method, heartbeat):
        transport = transport or 'amqp'
        transport = 'redis'
        if transport == 'amqp' and supports_librabbitmq():`
I don't know why my "tansport" is "amqp", I have set the "BROKER_URL" to redis

**Comment by MOHANKRISHNA33** [comment]
> > Just ran into this myself. It took a combo of the advice above to get a worker running along with a Django management command that can push stuff to the worker.
> > ```
> > 1. Specify the broker/backend when you're creating the celery app:
> >    `app = Celery('my_app', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')`
> > 
> > 2. Right next to that, in `__init__.py`, import the app:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `from .celery import app as celery_app` `__all__ = ('celery_app',)`
> > The first step was enough to get the worker running with this command:
> > `celery -A infinity_renders worker -l info`
> > The second step was necessary to get my management command to successfully add stuff to the queue via `@shared_task`.
> > If someone could update the docs, that would save a lot of hassle for random people running into this.
> 
> Isn't this already documented?

This just help me. Thanks a lot

**Comment by Curiouspaul1** [comment]
Guys if you're still experiencing this, you need to set `<celery_instance>.conf.broker_transport` to whatever transport you're using, in my case I wanted to use redis so for my usecase I had to do the following:

```python
celery.conf.broker_transport = 'redis'  # if you're using 'sqs' change to `sqs`, and so on and so forth.
```

**Comment by open2bonobo** [comment]
faced the same issue celery 5.4

![Image](https://github.com/user-attachments/assets/ffb41c4a-825f-4bb9-b095-5617f55524d0)

![Image](https://github.com/user-attachments/assets/71a20d77-7206-40e1-a689-ed79292a1507)

![Image](https://github.com/user-attachments/assets/509a0c9a-61af-417d-81ed-ed125f9c1e69)pip

**Comment by Nusnus** [comment]
@open2bonobo 
> faced the same issue celery 5.4
> 
> ![Image](https://github.com/user-attachments/assets/ffb41c4a-825f-4bb9-b095-5617f55524d0)
> 
> ![Image](https://github.com/user-attachments/assets/71a20d77-7206-40e1-a689-ed79292a1507)
> 
> ![Image](https://github.com/user-attachments/assets/509a0c9a-61af-417d-81ed-ed125f9c1e69)pip

Can’t reproduce on `main`:
### myapp.py
```python
from celery import Celery

app = Celery("backend.backend", backend="redis://localhost:6379/0", broker="redis://localhost: 6379/0")

app.conf.broker_transport = "redis"
app.conf.broker_url = "redis://localhost:6379/0"
app.conf.result_backend = "redis://localhost:6379/0"
app.conf.result_serializer = "json"
app.conf.accept_content = ["json"]
app.conf.task_serializer = "json"
app.conf.result_serializer = "json"
app.conf.timezone = "UTC"
app.conf.enable_utc = True
app.conf.broker_host = None
app.conf.broker_login_method = None
app.conf.broker_password = ""
app.conf.broker_pool_limit = 10
app.conf.broker_port = None
app.conf.broker_read_url = None
app.conf.broker_transport = ""

app.autodiscover_tasks()


@app.task(bind=True)
def debug_task(self):
    print(f"Request: {self.request!r}”)

```
### celery -A myapp worker -l INFO
`cd examples/app`
```console
celery -A myapp worker -l INFO
 
 -------------- celery@Tomers-MacBook-Pro.local v5.5.0rc4 (immunity)
--- ***** ----- 
-- ******* ---- macOS-15.3.1-arm64-arm-64bit 2025-02-16 00:27:43
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         backend.backend:0x102d44cd0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 10 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . myapp.debug_task

[2025-02-16 00:27:43,574: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-02-16 00:27:43,578: INFO/MainProcess] mingle: searching for neighbors
[2025-02-16 00:27:44,596: INFO/MainProcess] mingle: all alone
[2025-02-16 00:27:44,635: INFO/MainProcess] celery@Tomers-MacBook-Pro.local ready.
^C
worker: Hitting Ctrl+C again will initiate cold shutdown, terminating all running tasks!

worker: Warm shutdown (MainProcess)
```

<!-- Uploading "CleanShot 2025-02-16 at 00.26.23@2x.png"... —>

**Comment by open2bonobo** [comment]
I soleved it already, but have no idea why it did not work before.

**Comment by vignesh-aufait** [comment]
I have the same issue in Celery 5.4.0
