### ISSUE TITLE
Question: celeryev queues

### ISSUE THREAD

**Issue by Cylix** [celery/celery#6371]
Hey all,

I'm not too sure where to ask this and there does not seem to be issues templates for questions.
We are using celery to process background tasks on production, and we would like to better understand how the `celeryev` queues work.

## Context
We are using the following:
- django 1.10.6
- celery 3.1.25
- rabbitMQ 3.5.7

We run celery workers on 6 dedicated machines and our tasks are split between 15 different queues. Workers are configured with a concurrency of 8.

Different machines can process the same queues. Workers are started with `python manage.py celery worker -l info --settings=settings -E -Q webinterface_third_part_apis --maxtasksperchild=100 -Ofair`

Recently, we got an issue that we are having a hard time tracking down.

One of celery worker suddenly starts to consume a lot of memory, leading to high read IOPS and CPU usage when the machine is running out of memory. We are not clear yet what is causing this (is it a task of ours? if so, which one? why the OOM killer is not invoked on time? ...), but that's not the point of this ticket.

When this issue happens, the affected machine becomes completely unresponsive from the rest of the world (including all our internal infrastructure). This is normal since the CPU and read IOPS becomes so high that the machine just can't process anything anymore.

Now, when this happens, what we notice is that the `celeryev` queues that are usually empty suddenly start to fill up with thousands of messages.

For example, here is our normal queues state from RabbitMQ:

```bash
whova@REDACTED:~$ sudo rabbitmqctl list_queues name messages_ready messages_unacknowledged -p REDACTED
Listing queues ...
aliveness-test	0	0
beat_ems	0	0
beat_webinterface	0	0
bizcard	0	0
celery@REDACTED.celery.pidbox	0	0
celery@REDACTED.celery.pidbox	0	0
celery@REDACTED.celery.pidbox	0	0
celery@REDACTED.celery.pidbox	0	0
celery@REDACTED.celery.pidbox	0	0
celery@REDACTED.celery.pidbox	0	0
celeryev.0045d3f9-0e44-4949-870b-a5f1645ab30c	0	0
celeryev.01a5598e-5f22-4477-bbbe-19053b866ae0	0	0
celeryev.05320662-56a0-42a2-81d4-708c85a74659	0	0
celeryev.0ee6aaf1-7b42-4196-9eb7-b4931a7b3d54	0	0
celeryev.106329d7-a06e-4485-b5a3-cfef419ea4b0	0	0
celeryev.18810998-1a29-4123-b2fd-4baee4cca8d3	0	0
celeryev.1f8d6388-f1f3-4531-8b8d-168db39d3255	0	0
celeryev.20eaf7bb-2718-4d98-be1d-2e0753885f6c	0	0
celeryev.26fe0ec7-ddad-4a09-b2d0-0a707a923f19	0	0
celeryev.31726250-a1b7-4364-9110-571287554884	0	0
celeryev.378ac469-194a-4947-b4f8-0e4258905fc9	0	0
celeryev.45f28ba6-5d24-404d-822a-4fd536871d32	0	0
celeryev.46dd43aa-1fa8-4e8f-af1c-725a60eb4c29	0	0
celeryev.4b7369f1-e492-4dc2-9593-4735ca829790	0	0
celeryev.4ecc34b8-7b73-4cfd-b82b-e6628ed8beee	0	0
celeryev.666a3649-3f5a-43e5-a5c2-3670aafab7ff	0	0
celeryev.673246ca-547c-46b2-9917-3e1df43e139c	0	0
celeryev.742a56b6-63eb-4427-87e2-c73c8a65b486	0	0
celeryev.750796e0-6b11-4bbd-8b3e-e51237e0cd57	0	0
celeryev.7ada4853-3a90-4d03-a1b7-264442dec26a	0	0
celeryev.7dfe5ab5-3471-4eec-b433-3db618393baa	0	0
celeryev.811a82eb-c925-4539-bd37-cfeefedbec54	0	0
celeryev.81c40019-6c92-4fc4-8e43-846ec172bae3	0	0
celeryev.84c92120-3149-4cc7-ba71-918199a7b56d	0	0
celeryev.85f57170-a666-4ede-a2ed-4bb8f2bc801e	0	0
celeryev.8c5feb0c-16c2-4ba7-93df-e009936bcf34	0	0
celeryev.8cb04628-8871-41c2-97c8-6b307537fc84	0	0
celeryev.906ece70-b3d2-4e10-8e40-4b6654d7e22d	0	0
celeryev.97b34785-0dd9-463f-89e6-b3da0328b41e	0	0
celeryev.996e98c7-8daf-436b-86d1-68389cfbd11a	0	0
celeryev.9c012848-6292-41b7-b32e-1ee62e330cd6	0	0
celeryev.9d702524-3510-4872-bbc0-7687f4036af4	0	0
celeryev.a016d57e-9cb6-4da3-99d7-f471d2a049d4	0	0
celeryev.a733b89e-74dd-41d0-b452-e08352ed7c41	0	0
celeryev.b3be63ce-bfb9-403b-bc06-c7d6b1940fc7	0	0
celeryev.b70f3df7-79c0-4115-bb73-1e7e870ca0e1	0	0
celeryev.c096a6b5-e1e4-423a-83ce-ffbfe7f73957	0	0
celeryev.c393b3e5-131b-4b19-9ea0-b5250d8a0fae	0	0
celeryev.cd3c63c8-3f4d-47d0-8a51-9592060e5a4b	0	0
celeryev.cda1d736-ab68-4ec1-b91b-d2a11691a891	0	0
celeryev.d4944f7c-3575-4ca8-93f2-83bd38f076fd	0	0
celeryev.d894d634-d97c-4996-ba47-3a8b53f3ab00	0	0
celeryev.da7e06c5-be51-4277-97cb-bea51ab68959	0	0
celeryev.dfcad6b7-6562-4f2e-8832-794405774dc2	0	0
celeryev.e1eb5dde-cf2d-4768-bfb3-7edcc7c2758d	0	0
celeryev.e4e1f8d3-441e-408b-be0e-9c1093b06c15	0	0
celeryev.e7e51bb3-7c33-45a4-8b8c-35ab73e4d547	0	0
celeryev.f122c2ea-fa49-48f9-af11-0ae7bdafe374	0	0
default_ems	0	50
default_webinterface	0	3656
ebb	0	0
email_send	0	634
ems	0	41
event_report_pdf	0	0
stats	0	0
webinterface_push	0	0
webinterface_third_part_apis	0	8
xems	0	0
xems_import	0	0
xems_pdf	0	0
```

As you can see, we have a bunch of empty `celeryev` queues. I guess those are empty either because no messages are generated, or these messages are consumed very fast.

However, when the above inciden happens, some of these `celeryev` queues get filled as shown below (extract of a monitoring email: the number is the number of messages in `messages_ready` state):

```
The following celery queues appear to be stuck.

Queue Name | Ready Tasks
-- | --
celeryev.5d8ed984-85c7-40d3-9d1e-3e328f834dfe | 9687
celeryev.63b09ac1-308d-45df-ac5f-4d0e0f104ff1 | 27189
celeryev.72f064cb-aca7-4efd-9454-ffc56f50b180 | 27235
celeryev.93a5c7a4-df47-41a8-8d48-8055a6f14729 | 24084
celeryev.9bec9b88-1300-4c09-970d-e9d6f3ff84a4 | 27184
celeryev.ac5a0f54-7a85-46c3-9e94-458294b46a61 | 27181
celeryev.b213b975-7ea0-4107-9355-f4fdfa97a5bb | 24532
celeryev.c10f422b-d0c8-469e-8f0d-a883ec9fa470 | 27239
celeryev.cedecf0a-ce12-4ec3-8d56-295ade90542e | 27197
```

This number will continuously increase and we've seen it go as high as 75K per `celeryev` queue. Note that not all `celeryev` queue gets filled up like that. Out of about 50 `celeryev` queues, usually 6 to 9 end up being filled up, the other ones remain empty.

These queues will keep filling up until we reboot the faulty machine hosting the celery workers (as I mentioned earlier, we have 6 machines running celery workers, only one is down at a time when the issue happens, so we only reboot that one). But even then, it can take several minutes (sometimes as early as 2 minutes, sometimes as late as 20 minutes) for the `celeryev` queues to drop back to 0 `messages_ready`, even though the celery workers on the faulty machine are back online and correctly processing tasks.

## Question
From there, we would like to better understand what are those `celeryev` queues: how are the messages generated? how are they consumed? by who? ...

We checked a bit online, but we are not fully clear with the documentation regarding these queues. I mostly checked the official documentation [here](https://docs.celeryproject.org/en/stable/userguide/monitoring.html#events) and a handful of StackOverflow posts.

What we understand is that these queues contain monitoring events that can be consumed by monitoring tools like celery flower, and that we can possibly disable them with `CELERY_SEND_EVENTS = False` (or, probably by removing the `-E` option from the command lines arguments when we start celery).

As I understand it, since we are using the `-E` option, `-E` enables the worker to send celery events (most likely to the `celeryev` queue?). However, the documentation does not mention anything about consuming these events and we do not use any monitoring tool like flower.

So now, there are a few things we are quite unclear:
- Since we run celery workers with the `-E` option, I assume that all of our workers are sending messages to the `celeryev` queues all the time?
- If that's the case, our celery queues always appear empty and we do not have any monitoring tool consuming these, so who consumes the content of these tasks? I suppose this is consumed by the workers themselves?
- I'm a bit surprised by the number of messages our unresponsive machine can generate in the `celeryev`, considering it is unresponsive and does not process any tasks from our logs. Does that mean these sudden spike of `celeryev` messages can come from another machine detecting this machine is not responsive?
- When we bring back the machine online and restart the celery workers, the number of messages in the `celeryev` queues do not drop back to 0 right away. In fact, most of the time, it continues to increase for several minutes, even if we manually purge these queues. Why is that so? And why does it suddenly drop back to 0?

Thanks!

**Comment by YoungMagic** [comment]
- same celery version
- django 1.4.22.
- rabbitMQ 3.7.14
We currently run into similar problem. Our application have about 14 pods and about 70 workers.  The celeryev exchanges publish about 700 messages per second. The broker  connection raise up to 10,000 at most.
I tried to start the worker with --without-gossip  --without-mingle, but the worker process dies after several hours.
Any help would be appreciate.

**Comment by Cylix** [comment]
Circling back on this issue.

I spent some time reading a bit of the celery code to get a better understanding of these `celeryev` queues, so I'll put a brief summary here in case it can help others. In the long term, it would probably be great to have a dedicated section in the documentation too.

For the `celeryev` queues, our understanding is as follows:
- Each worker creates a `celeryev` queue for itself and consumes the events it receives. If your instance is running multiple workers, each of these workers will create its own unique `celeryev` queue
- Every two seconds, all the workers, across all of the EC2 instances, broadcast a health check to all the other workers using the `celeryev` queues. As you can see, we have 9 workers on each celery app server (4 servers), and 6 workers on each celery ems server (2 servers). This creates 48 events every two seconds, or about 1,500 events per minute.
- When an instance becomes unresponsive, the system is running very slow and the celery workers are unable to process the `celeryev` events. As you can see, you can easily end up with 1000 messages in each `celeryev` queue per minute, so it will quickly increase.
- Sometimes, even after a reboot, the queue continues to increase. Our understanding is that it is some zombie queues not deleted properly. Restarting rabbitmq solves it in that kind of case. This means there is nothing to consume these queues, but everyone keeps broadcasting to it until these queues are deleted.

In the end, these `celeryev` queues backlogs are symptoms, not cause. The root cause of our machines become unresponsive is that one of our tasks was consuming a very large amount of memory unpredictably due to another library (lassie). Somehow, the OOM killer is not called properly to kill the process, and the machine becomes unresponsive.

For us, disabling the celeryev does not sound like a good option. In the end, it appears to be a reliable way to detect unresponsive machines. Instead, putting efforts into identifying the task causing this memory consumption is what matters.

Finally, here are some answers to my own questions:

> Since we run celery workers with the -E option, I assume that all of our workers are sending messages to the celeryev queues all the time?

Yes, see my explanation above

> If that's the case, our celery queues always appear empty and we do not have any monitoring tool consuming these, so who consumes the content of these tasks? I suppose this is consumed by the workers themselves?

It is consumed by the worker itself. The worker will consume the heartbeat signals from other workers.

> I'm a bit surprised by the number of messages our unresponsive machine can generate in the celeryev, considering it is unresponsive and does not process any tasks from our logs. Does that mean these sudden spikes of celeryev messages can come from another machine detecting this machine is not responsive?

Yes, as described above. The other machines will keep publishing their hearbeat into the queues of the unresponsive machine.

> When we bring back the machine online and restart the celery workers, the number of messages in the celeryev queues do not drop back to 0 right away. In fact, most of the time, it continues to increase for several minutes, even if we manually purge these queues. Why is that so? And why does it suddenly drop back to 0?

As mentioned above, sometimes these queues are not deleted properly when we reboot the instance. They will then be orphaned: they exist in rabbitmq and other workers can continue pushing content to it, but there is nobody anymore to consume the messages. When restarting the workers on the unresponsive machine, they actually create brand new celeryev queues.
