### ISSUE TITLE
Specify default priority

### ISSUE THREAD

**Issue by thenewguy** [celery/celery#6391]
I have been working through task priorities using the redis backend.  The default priority when priority isn't specified is the highest priority.  It would be helpful if it could be set so that unspecified is medium priority.  That way tasks can be more or less priority than the unspecified default.

I was unable to find a setting for this.  Perhaps this setting should apply to all backends?

**Comment by thedrow** [comment]
There is the [`task_default_priority`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-task_default_priority) setting for Redis & RabbitMQ.
You can set it to determine the default priority.

**Comment by thenewguy** [comment]
@thedrow great thanks!
