### ISSUE TITLE
Using lowercase loglevel argument like in the documentation throws error

### ISSUE THREAD

**Issue by alimony** [celery/celery#6395]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

When starting workers like [some examples in the documentation](https://docs.celeryproject.org/en/stable/userguide/workers.html#starting-the-worker) that uses lowercase `info` as argument to loglevel I get this error: `Error: Invalid value for '-l' / '--loglevel': invalid choice: info. (choose from DEBUG, INFO, WARNING, ERROR, CRITICAL, FATAL)`. I assume this is because of the change to Click in 5.0.

# Suggestions

Review documentation for instances of lowercase loglevel being passed and update them to use uppercase.

**Comment by thedrow** [comment]
Actually this is a bug and not a documentation bug.
I didn't intend to break it.

**Comment by ddevault** [comment]
You ought to ship a 5.0.1 release with this fix included. This is going to silently break service files.

**Comment by thedrow** [comment]
I agree. This is part of the 5.0.1 milestone.

**Comment by ddevault** [comment]
Rather, you ought to ship a timely fix, deferring the rest of 5.0.1 to 5.0.2. Regressions are more severe than bugs.

**Comment by thedrow** [comment]
I'm doing my best here.

**Comment by ddevault** [comment]
I know. Thank you. It just seems like the priorities in the coming release are a bit too broad.

**Comment by thedrow** [comment]
I'm currently fixing the most urgent regressions (detaching, celery multi, this one).
The previous release has some regressions and prioritizing isn't that easy.
