### ISSUE TITLE
Following Application examples lead to Instance of 'Celery' has no 'worker_main' member

### ISSUE THREAD

**Issue by razerraz** [celery/celery#6404]
# Checklist

- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [ x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
I'm running celery inside a django project, from a python script. Until 5.0, I was able to run celery using worker_main() method : 
```
from celery import Celery
app = Celery()
app.worker_main()
```

From the [application related documentation page](https://docs.celeryproject.org/en/stable/userguide/application.html), nothing points out the fact that worker_main() method seems gone.

I suppose I miss something somewhere, but maybe because of some lack of clarity from documentation

**Comment by NullYing** [comment]
It's the same as 
```
app.start()
```

**Comment by maybe-sybr** [comment]
@thedrow - Looks like some doco changes which didn't get captured in the click CLI refactor work you did prior to 5.0 (01651d2).

**Comment by razerraz** [comment]
@NullYing

`app.start()
AttributeError: 'Celery' object has no attribute 'start'`

**Comment by razerraz** [comment]
Seems that this worker_main issue is not the only one causing problems.

I've followed django related doc step by step, I can't get any working process. It just stops without any error message. 

Uppercase config options beginning with a defined namespace (as explained in the doc) lead to regressions messages, and it seems impossible to define any specific config variables this way.

After 4 hours of fight, I give it up. Celery 5.0 is unusable for me, and not having an up to date configuration doesn't help. Unfortunatly, downgrading to 4.4 is the only way to have something working.

Appreciate the efforts though, but seems to me that some pieces are missing right now

**Comment by mxklabs** [comment]
I have the same issue with `celery==5.0.1`.

**Comment by ronid** [comment]
Hi, any updates?

**Comment by thedrow** [comment]
> Uppercase config options beginning with a defined namespace (as explained in the doc) lead to regressions messages, and it seems impossible to define any specific config variables this way.

This is fixed in 5.0.2.

**Comment by thedrow** [comment]
@maybe-sybr is correct. This seems like an oversight on my part.
I'll address this shortly.

**Comment by thedrow** [comment]
Now I remember why I removed those methods.
It's harder to implement the same with Click.

I also don't understand why you'd need to pass the command line arguments as a list here.

**Comment by thedrow** [comment]
Still looking into this.
Using the `CliRunner` from `click.testing` fails to run `celery worker`.

I think I can provide the `start` method without any overrides which is not enough.

**Comment by Hoohaha** [comment]
Hey man,

I met the same issue on python3.8. 

```
Traceback (most recent call last):
  File "celery_worker.py", line 90, in <module>
    app.worker_main(argv)
AttributeError: 'Celery' object has no attribute 'worker_main'
```

**Comment by thedrow** [comment]
Please try the PR.
