### ISSUE TITLE
Travis doesn't run pypy3 unit tests

### ISSUE THREAD

**Issue by maybe-sybr** [celery/celery#6409]
I noticed that the pypy3 job in travis doesn't seem to be doing anything except building and installing into the toxenv. Is that on purpose? Check out [0] as an example job. I think the TOXENV isn't being set properly - it's just "pypy3" instead of "pypy3-unit"

[0] https://travis-ci.org/github/celery/celery/jobs/735267307

**Comment by maybe-sybr** [comment]
Oh, I picked the doco report since this isn't really a code bug.

**Comment by thedrow** [comment]
Yes you are correct. The TOXENV is incorrect.
