### ISSUE TITLE
Celery 4.4.7 receives task then hangs whenever I try to use it with S3Fs(Pythonic file interface to AWS S3)

### ISSUE THREAD

**Issue by TWEEDOriginal** [celery/celery#6415]
# Checklist

- [ x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: celery 4.4.7 

<details> 
<summary><b><code>celery report</code> Output: </b></summary>
<p>

```
```
No output.
</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: python 3.8
* **Minimal Celery Version**: celery 4.4.7
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
  I expect this line of  code `fs = s3fs.S3FileSystem(anon=True)` to work, but whenever it reaches this stage celery hangs.

# Actual Behavior
 Nothing Happens.

**Comment by thedrow** [comment]
You haven't provided all the details required for us to resolve this issue.
Please fill all the required fields. Make sure to provide us with a reproducible test case.

**Comment by achimgaedke** [comment]
Hmmm, I think, I have to follow this through to the bitter end... The solution suggested above does not work in all cases.

This is a "big deal", because it prevents celery being useful processing data from s3 via pandas/fsspec. I.e.:

```python
pandas.read_csv(f"s3://{BUCKET_NAME}/test.data")
```
will hang under certain circumstances.

This is my test program illustrating the problem:

```python
import s3fs
from celery import Celery

app = Celery(
    name="celery_s3fs",
    broker="redis://localhost:6379/0",
    backend="redis://localhost:6379/1",
)

BUCKET_NAME = "test-bucket-achim"

# uncomment the next line to make the worker stuck
# s3fs.S3FileSystem(skip_instance_cache=True)

@app.task
def create_data():
    print("instantiating")
    fs = s3fs.S3FileSystem(skip_instance_cache=True)
    # fs.connect(refresh=True)

    print("opening")
    with fs.open(f"{BUCKET_NAME}/test.data", "w") as f:
        print("writing")
        f.write("0" * 2**12)
    print("done")

if __name__ == "__main__":
    app.send_task("celery_s3fs.create_data")
```

I start the workers with `celery --app celery_s3fs worker --purge --loglevel=INFO` and `python celery_s3fs.py` to run the task using a `redis 7.0.0` server.

The program works fine, as long as you don't instantiate an `S3FileSystem` instance outside the callback (that probably translates to "don't instantiate an s3fs instance in the main worker process").

Once you do this (see uncommented line above), the worker process hangs eventually.

Here are some versions:

```
 celery report

software -> celery:5.2.7 (dawn-chorus) kombu:5.2.4 py:3.10.5
            billiard:3.6.4.0 py-amqp:5.1.1
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-1080-aws imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

and `s3fs 2022.5.0`.

And yes, it is probably a combination of limited functionality from `s3fs` (wants forkserver), and `celery` (doensn't provide fork server out of the box).
