### ISSUE TITLE
Celery cannot connect to redis >6.0 using ACL user:password broker url

### ISSUE THREAD

**Issue by Insension** [celery/celery#6422]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**5.0.0**:

# Expected Behavior

I'm a new celery user, not quite sure if I should report this as a bug or feature request and I'm not quite sure how to best fix this myself, so I hope you'll bear with me :-)

Redis 6.0 or greater implements users in the form of ACL (see https://redis.io/topics/acl), however, celery throws an WRONGPASS error when using the following broker URL:

```redis://user:password@localhost:6379/0```

We would expect celery to connect to redis using the correct user:password combination and not throw a password error. Older redis versions did not implement ACL; looking at _params_from_url function on line 277 in celery/backend/redis.py, it seems like celery currently only implements a broker URL containing a password and no username, as indicated by line 278:

```scheme, host, port, _, password, path, query = _parse_url(url)```

I would expect celery to implement the user:password@host scheme, as well as the current password@host scheme in order to correctly handle the ACL introduced in redis >6.0

# Actual Behavior

Celery throws this error:
``` 
[2020-10-18 02:35:54,748: ERROR/MainProcess] consumer: Cannot connect to redis://user:**@localhost:6379/0: WRONGPASS invalid username-password pair.

Trying again in 18.00 seconds... (9/100)```

**Comment by matusvalo** [comment]
Hi @Insension. I am not sure if I understand. the URL is passed as `broker_url` or as `result_backend`?

**Comment by gainskills** [comment]
> Hi @Insension. I am not sure if I understand. the URL is passed as `broker_url` or as `result_backend`?

Run into the same issue when using the string as broker_url.

**Comment by Insension** [comment]
> Hi @Insension. I am not sure if I understand. the URL is passed as `broker_url` or as `result_backend`?

Hi @matusvalo , sorry for the late reply; yes this issue arose when attempting to connect to redis as a message broker using 'user:password@localhost:6379/0' `broker_url` format, similar to what @gainskills is experiencing. When using this URL as `result_backend` string, the same issue also occurs.

I can see that my suggestion that this can possibly be traced back to /celery/backend/redis.py could lead to confusion. Is this not the script that handles connecting to redis for both `broker_url` and `result_backend` though?

**Comment by gainskills** [comment]
> > Hi @Insension. I am not sure if I understand. the URL is passed as `broker_url` or as `result_backend`?
> 
> Hi @matusvalo , sorry for the late reply; yes this issue arose when attempting to connect to redis as a message broker using 'user:password@localhost:6379/0' `broker_url` format, similar to what @gainskills is experiencing. When using this URL as `result_backend` string, the same issue also occurs.
> 
> I can see that my suggestion that this can possibly be traced back to /celery/backend/redis.py could lead to confusion. Is this not the script that handles connecting to redis for both `broker_url` and `result_backend` though?

figured my issue out: it caused by a special character in the password string. It back to work after I removed it.

**Comment by thedrow** [comment]
> > > Hi @Insension. I am not sure if I understand. the URL is passed as `broker_url` or as `result_backend`?
> > 
> > 
> > Hi @matusvalo , sorry for the late reply; yes this issue arose when attempting to connect to redis as a message broker using 'user:password@localhost:6379/0' `broker_url` format, similar to what @gainskills is experiencing. When using this URL as `result_backend` string, the same issue also occurs.
> > I can see that my suggestion that this can possibly be traced back to /celery/backend/redis.py could lead to confusion. Is this not the script that handles connecting to redis for both `broker_url` and `result_backend` though?
> 
> figured my issue out: it caused by a special character in the password string. It back to work after I removed it.

Care to share a test case with us?

**Comment by ArtyomKozyrev8** [comment]
I have absolutely the same issue as OP, I am trying to use Redis as broker and backend. 

`
R_LOGIN = "myuserlogin"
R_PSWD = "xfjhdsfhsjdfhk123123sddsfdsf24fdsfr43"
R_HOST = "127.0.0.1"

celery_app = Celery(
    'tasks',
    broker=f"redis://{R_LOGIN}:{R_PSWD}@{R_HOST}:6379/0",
    backend=f"redis://{R_LOGIN}:{R_PSWD}@{R_HOST}:6379/1"
)
`

Command `celery -A  celery_app worker --loglevel=INFO`

Error: 

`
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x2b48d8dd088
- ** ---------- .> transport:   redis://myuserlogin:**@127.0.0.1:6379/0
- ** ---------- .> results:     redis://myuserlogin:**@127.0.0.1:6379/1
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery_app.add

[2020-11-02 17:09:56,047: ERROR/MainProcess] consumer: Cannot connect to redis://myuserlogin:**@127.0.0.1:6379/0: WRONGPASS invalid username-password pair.
Trying again in 2.00 seconds... (1/100)

[2020-11-02 17:09:56,368: INFO/SpawnPoolWorker-11] child process 80676 calling self.run()

`

**Comment by matusvalo** [comment]
Unfortunatelly without investigation cannot help with this issue. In any case if we are talking about `broker_url` the problem is connected to kombu because the connection string is passed there.

**Comment by ArtyomKozyrev8** [comment]
> Unfortunately without investigation cannot help with this issue. In any case if we are talking about `broker_url` the problem is connected to kombu because the connection string is passed there.

Actually it seems that handler just drops login for Redis:

https://github.com/celery/celery/blob/master/celery/backends/redis.py

```
    def _params_from_url(self, url, defaults):
        #  no login - _ it is not used:
        scheme, host, port, _, password, path, query = _parse_url(url)
        connparams = dict(
            defaults, **dictfilter({
                'host': host, 'port': port, 'password': password,
                'db': query.pop('virtual_host', None)})
        )
```

**Comment by thedrow** [comment]
Because I think Redis used to not have a username. I might be wrong.
@ArtyomKozyrev8 Care to provide a fix?

**Comment by ArtyomKozyrev8** [comment]
> Because I think Redis used to not have a username. I might be wrong.
> @ArtyomKozyrev8 Care to provide a fix?

Yes it is a new feature available from Redis 6.0.0 Actually it is not really new, I have Redis 6 in production for at least 6 month already.

[https://redis.io/commands/acl-cat](https://redis.io/commands/acl-cat)

@thedrow yes I would like to have the feature, since Redis 6.0 make you to use login if you want to use password.

**Comment by auvipy** [comment]
> > Because I think Redis used to not have a username. I might be wrong.
> > @ArtyomKozyrev8 Care to provide a fix?
> 
> Yes it is a new feature available from Redis 6.0.0 Actually it is not really new, I have Redis 6 in production for at least 6 month already.
> 
> https://redis.io/commands/acl-cat
> 
> @thedrow yes I would like to have the feature, since Redis 6.0 make you to use login if you want to use password.

please feel free to come with a PR so that we can also provide input

**Comment by thedrow** [comment]
@ArtyomKozyrev8 Any chance you'll reach to this soon?

**Comment by zyv** [comment]
FYI @ArtyomKozyrev8 Heroku ist going to phase out Redis 4/5 and force-switch everybody to Redis 6 on June 30, 2021:

https://devcenter.heroku.com/changelog-items/2078

**Comment by thedrow** [comment]
I've fixed this because it's getting pressing but I'd like to have more contributions to our Redis backend so it'll be maintained sustainably.
If you are using it, I can invite you to the Redis Task Force.

**Comment by thedrow** [comment]
I forgot to open a PR for the fix. 😅
