### ISSUE TITLE
extraneous "-" character

### ISSUE THREAD

**Issue by cariaso** [celery/celery#6423]
There seems to be an unintended hyphen on line 9

https://github.com/celery/celery/blob/b50b178f41c798f63aad77c0e4908c8a7139a753/extra/systemd/celery.service#L9

Also, is there any reason for the inconsistent use of braces and quotes around variables?

as a concrete example
ExecReload=/bin/sh -c '${CELERY_BIN} -A $CELERY_APP multi restart $CELERYD_NODES \
	--pidfile=${CELERYD_PID_FILE} --logfile=${CELERYD_LOG_FILE} \
	--loglevel="${CELERYD_LOG_LEVEL}" $CELERYD_OPTS'

${CELERY_BIN}
$CELERY_APP
"${CELERYD_LOG_LEVEL}"

**Comment by thedrow** [comment]
It means that if the file does not exist, no error or warning should be emitted.
It was there originally so I kept it.

See the answer [here](https://unix.stackexchange.com/a/404202/2781).
