### ISSUE TITLE
Adding new command-line options no longer works

### ISSUE THREAD

**Issue by mfkrason** [celery/celery#6439]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

## Related Issues and Possible Duplicates

# Description
https://docs.celeryproject.org/en/stable/userguide/extending.html#extending-commandoptions

The described code no longer works in celery 5+

Looking at celery's source code, 'user_options' are now expected to be a set(). In fact they are initialized to a defaultdict(set())

I believe that one should provide a click.option, but when i tried that things still fell apart as click is later accessing whatever is provided.opts

# Suggestions

Upgrade the documentation to support click or modify the code to allow the above example to work

**Comment by auvipy** [comment]
@mfkrason check this PR plz https://github.com/celery/celery/pull/6501
