### ISSUE TITLE
Whats the Asyncio support feature of Celery since version 5.x has released

### ISSUE THREAD

**Issue by openalmeida** [celery/celery#6449]
HI,

Thanks for the release of Celery 5.x.
It seems Celery still not suport Asyncio ?
I've checked last document/commit log/changelog/issues/faq.

**Comment by auvipy** [comment]
it is intended to be in celery 5.1 or in 6.x

**Comment by thedrow** [comment]
The target is 6.0.
We're working on a roadmap that you can see in celery/ceps#28.

**Comment by ahopkins** [comment]
Not to hold your feet to the fire on this, is there a target date for v6.0? December? Q1? Q2?

**Comment by thedrow** [comment]
> Not to hold your feet to the fire on this, is there a target date for v6.0? December? Q1? Q2?

We need to sort some things out first.
We'll publish our goals and milestones by the end of the year.

**Comment by ahopkins** [comment]
Sure, I'd be happy to help get this working. Any pointers on where to get started? I've spent the last six months trying several strategies to add wrappers and asyncio layers on top of tasks. Having native support would be huge!

**Comment by thedrow** [comment]
If you can, let's schedule a call.
Send me an email.

**Comment by ahopkins** [comment]
Sent
