### ISSUE TITLE
`publish_result` is False when tasks are eager and and we DON'T want to ignore results

### ISSUE THREAD

**Issue by tomwojcik** [celery/celery#6476]
#### Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- #5398 
- https://github.com/celery/django-celery-results/issues/49

#### Possible Duplicates

- None

### Python Packages

Latest, not released django-celery-results
https://github.com/celery/django-celery-results/pull/172/commits/b4acbf24ea3521ecfdbf821ece7ca62e49ff2765
Currently published version doesn't support Celery 5.x, but all versions are affected

## Minimally Reproducible Test Case

Source of the issue
https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/app/trace.py#L323

```python
import pytest

@pytest.mark.parametrize(
    "eager,ignore_result,publish_result",
    [
        (True, True, False),
        (True, False, True),  # fails
        (False, True, False),
        (False, False, True),
    ]

)
def test_publish_result_current(eager, ignore_result, publish_result):
    actual_publish_result = not eager and not ignore_result
    assert publish_result == actual_publish_result


@pytest.mark.parametrize(
    "eager,ignore_result,publish_result",
    [
        (True, True, False),
        (True, False, True),
        (False, True, False),
        (False, False, True),
    ]

)
def test_publish_result_desired(eager, ignore_result, publish_result):
    actual_publish_result = not ignore_result
    assert publish_result == actual_publish_result
```

# Expected Behavior

``always_eager`` exists so we can use Celery in unit tests. I want to execute a task eagerly and later on check result from the backend. 

# Actual Behavior
When task is eager and it's set NOT to ignore the result, the result will be ignored.

**Comment by auvipy** [comment]
did you try the latest release & share your feedback?

**Comment by auvipy** [comment]
it would be great if you can share a possible solution

**Comment by tomwojcik** [comment]
I tried the latest release.

It appears to me that someone made the decision that whenever a task is eager, nothing should be saved to the backend. But not only I struggle to understand what would be the purpose of this feature but also it's not documented anywhere (AFAIK). So could you please confirm that the current behavior is not the desired behavior?

Once you confirm I'll be happy to fix it.

**Comment by thedrow** [comment]
I think we do need to save the result. However, if this was never done before in any version of Celery then this is not a bug but a feature request.

I'd like to have some input from @celery/core-developers.

**Comment by auvipy** [comment]
> I tried the latest release.
> 
> It appears to me that someone made the decision that whenever a task is eager, nothing should be saved to the backend. But not only I struggle to understand what would be the purpose of this feature but also it's not documented anywhere (AFAIK). So could you please confirm that the current behavior is not the desired behavior?
> 
> Once you confirm I'll be happy to fix it.

based on the issues raised https://github.com/celery/django-celery-results/issues/49 I believe we should save the results, however, we should carefully check the possible side effects.
@tomwojcik still up for this?

**Comment by tomwojcik** [comment]
Yes @auvipy . I already tried to fix this but some tests started to fail due to some side effects but I think some are to be expected. I will give it another try over the weekend and let you know if I won't manage to fix this myself.

**Comment by matusvalo** [comment]
I personally, haven't used eager execution of the task. But if I understand it correctly that it execute task locally without sending it to the queue, it makes sense to me that the result is not stored to result storage (since it is executed directly by the caller). But still haven't used it so maybe there is need for storing it in result store.

**Comment by auvipy** [comment]
> Yes @auvipy . I already tried to fix this but some tests started to fail due to some side effects but I think some are to be expected. I will give it another try over the weekend and let you know if I won't manage to fix this myself.

don't hesitate to come with A draft PR as well. so that if you are not sure about something, we could share our insight with you.

**Comment by tomwojcik** [comment]
@auvipy please review. 

I was thinking about that for quite some time and even though I still consider this to be a bug (or I simply don't understand why it's the way it is) I think we shouldn't change the behavior of eager + not ignore result as many projects might depend on this setup. Or, if anything, that's something to consider for the next major version bump.

I've decided to add a new setting as that's the only safe option and guarantees there will be no regressions.

**Comment by tomwojcik** [comment]
@matusvalo I agree it makes sense but not if you are using eager for testing. And, even though 

> The eager mode enabled by the task_always_eager setting is by definition not suitable for unit tests.

most of us do use it for testing as it's good enough.

In order to prove it affects quite a few people there's this bug https://github.com/celery/django-celery-results/issues/49 and a few SO questions [Make Django test case database visible to Celery](https://stackoverflow.com/questions/46530784/make-django-test-case-database-visible-to-celery/46564964#46564964) and [Make Celery use Django's test database without task_always_eager](https://stackoverflow.com/questions/42058295/make-celery-use-djangos-test-database-without-task-always-eager) but then these solutions result in problems with DB transactions.

So I'd rather use eager + saving results on the backend.

**Comment by auvipy** [comment]
thanks, Tomasz! your findings are very helpful to fix a long-standing issue. highly appreciated.
