### ISSUE TITLE
celery inspect registered hangs

### ISSUE THREAD

**Issue by kaldown** [celery/celery#6480]
`celery inspect -t 3 registered` hangs with no output

How to at least get some info about the matter of that problem?
Is there any attempt to connect outside of localhost or what (looks like not, because timeout doesn't raise)?

celery 5.0.2

**Comment by auvipy** [comment]
can you try celery master?

**Comment by auvipy** [comment]
also, we need to see your code

**Comment by kaldown** [comment]
Not an issue anymore.
Decided to use sqsd.

Thanks
