### ISSUE TITLE
Exception while handling exception

### ISSUE THREAD

**Issue by Ixiodor** [celery/celery#6496]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce
Make a task fail with an unhandled exception and see exception getting exception while handling the exception throwing the exception again.

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Expecting to get exception one time and resolve with job failure.

# Actual Behavior

> [2020-11-23 17:33:17,485: ERROR/ForkPoolWorker-1] Chord 'f8c9088d-5340-496e-bbec-eab167c43ac1' raised: ValueError('could not broadcast input array from shape (3,336,244) into shape (3,336,256)')
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 409, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 701, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
>     ret = task.retry(exc=exc, **retry_kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/task.py", line 703, in retry
>     raise_with_context(exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
>     return task._orig_run(*args, **kwargs)
>   File "/var/www/django_projects/earthalytics-api/api_v3/nodes/BuildingsClassification50cm.py", line 38, in execute
>     predictor.predict(input_path, output_path)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/predictor.py", line 94, in predict
>     labels = inferer.predict(x)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/backend/inferer.py", line 160, in predict
>     temp[:x.shape[0], :x.shape[1]] = x
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 147, in trigger_callback
>     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 746, in join
>     value = result.get(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 219, in get
>     self.maybe_throw(callback=callback)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 335, in maybe_throw
>     self.throw(value, self._to_remote_traceback(tb))
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 328, in throw
>     self.on_ready.throw(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/promises.py", line 234, in throw
>     reraise(type(exc), exc, tb)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/utils.py", line 30, in reraise
>     raise value
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)

**Comment by thedrow** [comment]
Please include a test case.
We specifically ask for one and you keep ignoring what we need to actually help you.

**Comment by Ixiodor** [comment]
Same conclusione as #6495
