### ISSUE TITLE
Don't use smart quotes in pytest example code segment on site.

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#6497]
The tiny code segment below uses smart quotes, this doesn't work when you paste it into your code.

https://docs.celeryproject.org/en/stable/userguide/testing.html#enabling

![image](https://user-images.githubusercontent.com/179677/99993479-a83c8f80-2daf-11eb-9094-203da98efe91.png)

**Comment by thedrow** [comment]
We'd welcome a PR.

**Comment by stuaxo** [comment]
Oh, I didn't realise this was in this repo :)

**Comment by maybe-sybr** [comment]
@stuaxo looks like the  change that got linked above would be easy to merge. Could you make a PR for us?

**Comment by stuaxo** [comment]
Thanks, looks like I didn't hit the button :) https://github.com/celery/celery/pull/6507
