### ISSUE TITLE
celery worker  -q --quiet seems not working with 4.4.7

### ISSUE THREAD

**Issue by huyidao625** [celery/celery#6517]
Running celery 4.4.7   [not woking]
Running celery 4.4.6   [ok]
Running celery 4.4.1   [ok]

commands :

> celery -A proj worker --loglevel=info  -P eventlet --quiet
> celery -A proj worker --loglevel=info  -P eventlet -q

**Comment by auvipy** [comment]
did you try 5.0.x versions?

**Comment by strokirk** [comment]
I've recently tried this with the latest celery version (5.0.5), and the issue remains. 

The reason seems to be that in [`celery.bin.worker.worker`](https://github.com/celery/celery/blob/master/celery/bin/worker.py#L326) the `ctx.obj.quiet` option is not passed. 

The fixed code would look something like this:

```python
    worker = app.Worker(
        hostname=hostname, pool_cls=pool_cls, loglevel=loglevel,
        logfile=logfile,  # node format handled by celery.app.log.setup
        pidfile=node_format(pidfile, hostname),
        statedb=node_format(statedb, hostname),
        no_color=ctx.obj.no_color,
        quiet=ctx.obj.quiet,
        **kwargs)
```

**Comment by auvipy** [comment]
would you mind checking this https://github.com/celery/celery/pull/6599?

**Comment by auvipy** [comment]
> I've recently tried this with the latest celery version (5.0.5), and the issue remains.
> 
> The reason seems to be that in [`celery.bin.worker.worker`](https://github.com/celery/celery/blob/master/celery/bin/worker.py#L326) the `ctx.obj.quiet` option is not passed.
> 
> The fixed code would look something like this:
> 
> ```python
>     worker = app.Worker(
>         hostname=hostname, pool_cls=pool_cls, loglevel=loglevel,
>         logfile=logfile,  # node format handled by celery.app.log.setup
>         pidfile=node_format(pidfile, hostname),
>         statedb=node_format(statedb, hostname),
>         no_color=ctx.obj.no_color,
>         quiet=ctx.obj.quiet,
>         **kwargs)
> ```

@thedrow
