### ISSUE TITLE
Django Celery beat 5.x does not execute periodic_task

### ISSUE THREAD

**Issue by venomone** [celery/celery#6520]
I'm currently trying to migrate from celery 4.x to 5.x but I'm unable to get celery beat to process a periodic_task. Celery beat simply does not touche the code here it seems. Processing tasks I call manually from a view is not a problem at all and working fine for the worker process. So I would at least expect that my settings are fine but I don't understand why the 
periodic_task are not processed. Can smb help? did I forget to call something?!

Also see docs here: https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html

settings.py

    # Celery Settings:
    BROKER_URL = 'redis://' + ':' + env.str('REDIS_PWD') + '@' + env.str('REDIS_HOST') + ":" + env.str('REDIS_PORT')
    BROKER_TRANSPORT = 'redis'
    CELERY_RESULT_BACKEND = 'django-db'
    CELERY_TASK_RESULT_EXPIRES = 3600
    CELERY_REDIS_HOST = env.str('REDIS_HOST')
    REDIS_PWD = env.str('REDIS_PWD')
    CELERY_REDIS_PORT = env.str('REDIS_PORT')
    CELERY_REDIS_DB = env.str('REDIS_CACHE_DB')
    CELERY_CACHE_BACKEND = 'default'
    CELERY_ACCEPT_CONTENT = ['application/json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'GMT'
    CELERYD_TASK_SOFT_TIME_LIMIT = 900

celery.py

    from __future__ import absolute_import, unicode_literals
    import os
    from celery import Celery
    import environ
    from django.conf import settings
    from MyApp import settings
    
    env = environ.Env()
    
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyApp.settings")
    
    app = Celery(settings.SITE_NAME)
    app.config_from_object('django.conf:settings')
    
    # Load task modules from all registered Django app configs.
    app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
    
    
    @app.task(bind=True)
    def debug_task(self):
        print('Request: {0!r}'.format(self.request))

tasks.py

    @app.on_after_configure.connect
    def setup_periodic_tasks(sender, **kwargs):
        sender.add_periodic_task(10.0, self_check_beat.s('Celery Beat self check'))  # Calls task every 10 seconds.
        sender.add_periodic_task(crontab(minute=5), drop_object_views.s('Drop Post object views'), expires=10)
    
    
    
    @app.task
    def self_check_beat():
        return "Celery Self-Check Task says <<HELLO>>"
    
    

    @app.task
    def drop_object_views():
        view_validity = timezone.now() - datetime.timedelta(minutes=5)
        Views.objects.filter(date_added__lte=view_validity).delete()

output after start:

    celery-beat      | celery beat v5.0.3 (singularity) is starting.
    celery-beat      | __    -    ... __   -        _
    celery-beat      | LocalTime -> 2020-12-04 08:24:43
    celery-beat      | Configuration ->
    celery-beat      |     . broker -> redis://:**@redis:6379//
    celery-beat      |     . loader -> celery.loaders.app.AppLoader
    celery-beat      |     . scheduler -> celery.beat.PersistentScheduler
    celery-beat      |     . db -> /home/user123/celerybeat-schedule
    celery-beat      |     . logfile -> [stderr]@%INFO
    celery-beat      |     . maxinterval -> 5.00 minutes (300s)
    celery-beat      | [2020-12-04 08:24:43,605: INFO/MainProcess] beat: Starting...

And that's already everything I get back from the celery-beat process after start.

Many thanks in advance

**Comment by thedrow** [comment]
Why do you need the signal?
Can't you just use the [`beat_schedule`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-beat_schedule) setting?

**Comment by venomone** [comment]
That again was working at the moment the issue first occurred for me ... Anyways I already fixed the issue and the migration from celery 4.x to 5.x was successful

**Comment by anuj9196** [comment]
@venomone How did you solved the issue? I'm also struggling with defining periodic tasks in tasks.py file in v5+
