### ISSUE TITLE
setup_default_app doesn't use app argument (or the current_app fixture does nothing)

### ISSUE THREAD

**Issue by akx** [celery/celery#6525]
# Checklist
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* Version: Celery 4.4.7, 5.0.2, and `master`

# Problem
I was trying to set up testing for a project using Celery using py.test and while wondering why `celery_app` didn't seem to have an effect (accessing `celery.current_app` printed out a decidedly non-test app), I think I may have found a bug in the implementation of `setup_default_app` (which is used by the `celery_app` fixture).

If you look at the implementation below (which is the same in 4.4.7, https://github.com/celery/celery/blob/d50c6cfc448e9e31384190b23f285254cb44e8a2/celery/contrib/testing/app.py), the `app` argument is actually never assigned to the current state globals. I believe this problem has existed for a long while, effectively making `setup_default_app` a no-op unless the trap is enabled.

https://github.com/celery/celery/blob/f50cf7d9944558167b85c14d73e8f790da251730/celery/contrib/testing/app.py#L68-L109

The `celery_app` pytest fixture attempts to use `setup_default_app()`: https://github.com/celery/celery/blob/c3e041050ae252be79d9b4ae400ec0c5b2831d14/celery/contrib/pytest.py#L40-L41

but when the trap argument is False, no change is done to the ambient current app setting.

https://github.com/celery/celery/issues/6007 may be vaguely related to this.

**Comment by auvipy** [comment]
might be fixed by https://github.com/celery/celery/pull/7503
