### ISSUE TITLE
Upgrade required pymongo version to 3.11.1

### ISSUE THREAD

**Issue by thedrow** [celery/celery#6529]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- #5928 

#### Possible Duplicates

- None

# Brief Summary

`db.authenticate()` is deprecated starting from [pymongo 3.5](https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-5).

It is being used in our backend:

https://github.com/celery/celery/blob/ee13eae8e20896beadd89dec8f521bd781522416/celery/backends/mongodb.py#L266-L277

Celery 5.1.0 will introduce official support for Python 3.9 and so we require our dependencies to support it.

# Design

Remove usage of `db.authenticate()` as we already authenticate when creating the `MongoClient` instance.

## Architectural Considerations

None as the newer pymongo versions do not drop support for MongoDB versions.

## Proposed Behavior

The backend should behave exactly the same.

## Proposed UI/UX

The same exception should be raised in case of an authentication failure.

## Diagrams

N/A

## Alternatives

None

**Comment by maybe-sybr** [comment]
@thedrow - should we be pushing this back beyond 5.1 or do we need to sanity test what changes might need to be made to run against a mongo backend before then? We might be best off deferring #6662 in favour of a PR which pins us to `>=3.3,<3.5` depending on the timeline, but to spring that in rc1 might be a bit rude.

**Comment by thedrow** [comment]
I agree.

**Comment by maybe-sybr** [comment]
Per my comment [0] on #6662 - pinning like I suggested in my previous comment is unnecessary and will probably cause annoyance due to dependency resolution on celery upgrades if we were to do it.

It still makes sense to defer this from 5.1 since it's a substantive code change to authenticate mongo clients rather than the top level `Database` instance. But AFAICT, merging #6662 won't really help us solve #5928, so we probably don't need to merge it for 5.1 either.

* [0] https://github.com/celery/celery/pull/6662#issuecomment-835936882

**Comment by auvipy** [comment]
@naomielst you can handle both of this

**Comment by naomielst** [comment]
> @naomielst you can handle both of this

Nice! Will look into this
