### ISSUE TITLE
Add backends and brokers usage and advantages documentation.

### ISSUE THREAD

**Issue by danthegoodman1** [celery/celery#6539]
I am proposing adding some documentation to talk a bit about some of (at least the more popular) brokers and backends. Possibly in such a format like the following. It could be valuable for others to see how the different transports and result stores could be best suited for their use case.

Backends and brokers
====================

Celery has the ability to communicate and store with many different backends (Result Stores) and brokers (Message Transports).

Redis
-----

Redis can be both a backend and a broker.

**As a Broker:** Redis works well for fast transport of small messages. Large messages can congest the system. Furthermore, the Redis broker is based on lightweight Pub/Sub. As a result if tasks are queued while no worker is currently listening to the broker, they will be lost.

**As a Backend:** Redis is a super fast K/V store, making it very efficient for fetching the results of a task call.

RabbitMQ
--------

RabbitMQ is a broker.

**As a Broker:** RabbitMQ handles larger messages better than Redis. RabbitMQ also has the capabilities of holding tasks in a queue, meaning that if a task is called and no workers are currently listening, once a worker connects it will pick up the task.

*Note: RabbitMQ (as the broker) and Redis (as the backend) are very commonly used together. If more guaranteed long-term persistence is needed from the result store, consider using PostgreSQL or MySQL (through SQLAlchemy), Cassandra, or a custom defined backend.*

**Comment by auvipy** [comment]
can you put some effort into this?

**Comment by danthegoodman1** [comment]
> can you put some effort into this?

I had initially made a PR but thought getting someone opinions first might be nice.

Yes, I can but I’m definitely not familiar with all of the options and didn’t want to make a PR for something that only had a few of the plethora of options.

I’ll make that PR again.

**Comment by matusvalo** [comment]
Fixed in #6557
