### ISSUE TITLE
'celery --help' doesn't work with current version 

### ISSUE THREAD

**Issue by sh4nks** [celery/celery#6545]
Hey, I am not able to get the help command working with the current celery (commit: https://github.com/celery/celery/commit/8bceb446e6a07682d4b8dd6199cdac450bd63578). The issue exists with Celery ``5.0.3`` and ``5.0.4``. When downgrading to ``5.0.2`` the command ``celery`` or ``celery --help`` returns the expected help message.

See the Traceback in section '**Actual Behavior**'

# Checklist
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information
- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.4 (singularity) *(master @ commit 8bceb446e6a07682d4b8dd6199cdac450bd63578)*
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.0.4 (singularity) kombu:5.0.2 py:3.9.0
            billiard:3.6.3.0 py-amqp:5.0.2
platform -> system:Linux arch:64bit, ELF
            kernel version:5.9.14-zen1-1-zen imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: Python 3.9.0 - not sure about other versions
* **Minimal Celery Version**: >= 5.0.3
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: ``Arch Linux 5.9.14-zen1-1-zen #1 ZEN SMP PREEMPT``
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.2
billiard==3.6.3.0
-e git+https://github.com/celery/celery.git@8bceb446e6a07682d4b8dd6199cdac450bd63578#egg=celery
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
kombu==5.0.2
prompt-toolkit==3.0.8
pytz==2020.4
six==1.15.0
vine==5.0.0
wcwidth==0.2.5
```

</p>
</details>

### Other Dependencies
<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

1. ``git clone https://github.com/celery/celery <your/git/clone/celery/folder>``
2. ``cd <your/git/clone/celery/folder>``
3. ``mkvirtualenv celery -a .``
4. ``which python``  # verify that you are using the correct virtualenv
5. ``pip install -e .``
6. enter: ``celery`` or ``celery --help``
</p>
</details>

# Expected Behavior
When installing ``celery==5.0.2`` this issue doesn't exist.

# Actual Behavior

```
$ git --no-pager log --oneline -1

8bceb446e (HEAD -> master, origin/master, origin/HEAD) Fix type error in S3 backend (#6537)
```

Traceback
```
$ celery

Traceback (most recent call last):
  File "/home/peter/.virtualenvs/celery/bin/celery", line 33, in <module>
    sys.exit(load_entry_point('celery', 'console_scripts', 'celery')())
  File "/home/peter/Development/celery/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/peter/Development/celery/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/peter/Development/celery/celery/bin/celery.py", line 128, in celery
    click.echo(ctx.get_help())
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 1137, in format_options
    self.format_commands(ctx, formatter)
  File "/home/peter/.virtualenvs/celery/lib/python3.9/site-packages/click/core.py", line 1200, in format_commands
    help = cmd.get_short_help_str(limit)
AttributeError: 'function' object has no attribute 'get_short_help_str'
```

**Comment by auvipy** [comment]
did you check all the dependencies?

**Comment by auvipy** [comment]
click should be below v 8 for current celery

**Comment by sh4nks** [comment]
See the ``pip freeze`` output.

**Comment by thedrow** [comment]
This appears to be fixed in #6543.
Please try master to confirm.

**Comment by sh4nks** [comment]
Yes, it works again @ master! Thanks for the fast fix!

**Comment by thedrow** [comment]
> Yes, it works again @ master! Thanks for the fast fix!

I'll release 5.0.5 today.
