### ISSUE TITLE
celery=4.4.6, broadcast not work.

### ISSUE THREAD

**Issue by minofmax** [celery/celery#6549]
celery version: 4.4.6
redis version: 2.8
I am using celery with redis as broker in django.
broadcast queue setting
```python3
CELERY_QUEUES = (
    Queue("default", Exchange("default"), routing_key="default"),
    Broadcast("test_queue"),
)
CELERY_ROUTES = {
    'test_celery': {"queue": "test_queue", "routing_key": "test_router"},
}
```
the ```test_celery``` method
```python3
@app.task(name='test_celery', ignore_result=True)
def test_celery(x, y):
    print(x * y)
```
and I call the method like this
```python3
test_celery.delay(5, 6)
```
The project of mine used flower and some other components, so it's too hard to upgrade or downgrade celery version.

_Originally posted by @minofmax in https://github.com/celery/celery/issues/3934#issuecomment-745292244_

**Comment by clokep** [comment]
I don't think broadcast works with Redis as a broker, see #2638.

**Comment by minofmax** [comment]
> I don't think broadcast works with Redis as a broker, see #2638

@clokep Thanks for your comment.
I see this issue before, but I am curious about why not support. Redis is one of the offical recommend broker.
Hmm, one of the comment under the issue said redis6.0.8 can be used as a broker in broadcast, see [2638](https://github.com/celery/celery/issues/2638#issuecomment-631862957)
I will try it, if works, I will comment in this issue.

**Comment by clokep** [comment]
> I see this issue before, but I am curious about why not support.

Probably because it is either not possible or no one has implemented it.

**Comment by minofmax** [comment]
> > I see this issue before, but I am curious about why not support.
> 
> Probably because it is either not possible or no one has implemented it.


I try to upgrade redis to 6.0.3, it not works also. So, I decide to use rmq as a broker.
Yes, rmq works.
