### ISSUE TITLE
task.request.hostname no longer contains worker node name but only the hostname

### ISSUE THREAD

**Issue by freedrikp** [celery/celery#6555]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
-- https://groups.google.com/g/celery-users/c/uqCUtMUu8XY 
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.5 (singularity)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.0.5 (singularity) kombu:5.0.2 py:3.7.6
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Darwin arch:64bit
            kernel version:17.7.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://lo
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: 5.0.0
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.2
billiard==3.6.3.0
celery @ git+https://github.com/celery/celery.git@491054f2724141cbff20731753379459af033bfd
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
importlib-metadata==3.3.0
kombu==5.0.2
prompt-toolkit==3.0.8
pytz==2020.4
redis==3.5.3
six==1.15.0
typing-extensions==3.7.4.3
vine==5.0.0
wcwidth==0.2.5
zipp==3.4.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

app.py
```
from celery import Celery

app = Celery(broker='redis://localhost:6379/0', backend='redis://localhost:6379/0')

@app.task(bind=True)
def worker_name(self):
    return self.request.hostname
```

main.py
```
from app import worker_name

res = worker_name.delay()
print(res.get())
```
</p>
</details>

# Expected Behavior

As described in the documentation `task.request.hostname` should be the node name of the worker instance executing the task. See https://docs.celeryproject.org/en/latest/userguide/tasks.html#task-request-info

# Actual Behavior

`task.request.hostname` no longer contains the node name of the worker. Only the hostname of the worker. For example if the worker is started with `-n whoopsie@%h` only the `%h` bit is included in `task.request.hostname`. In fact if the worker is started `-n whoopsie@computer` it will still only report the hostname of the worker machine and not what has been put into the node name.

This issue appeared between v4.4.7 and v5.0.0 and is present in current master. It is really useful for debugging purposes to know what exact worker instance a task is executed in if there are multiple workers on the same host.

It appears that the worker is at least aware of its worker name based on the worker logs:
<details>
<summary><b><code>celery -A app.app  worker -n whoopsie@computer --loglevel=DEBUG</code></b></summary>
<p>

```
[2020-12-22 10:40:06,971: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2020-12-22 10:40:06,973: DEBUG/MainProcess] | Worker: Building graph...
[2020-12-22 10:40:06,974: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2020-12-22 10:40:06,986: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2020-12-22 10:40:06,987: DEBUG/MainProcess] | Consumer: Building graph...
[2020-12-22 10:40:07,014: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Tasks, Control, Agent, Gossip, event loop}
 
 -------------- whoopsie@computer v5.0.5 (singularity)
--- ***** ----- 
-- ******* ---- Darwin-17.7.0-x86_64-i386-64bit 2020-12-22 10:40:07
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x10f0db990
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . app.worker_name
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap

[2020-12-22 10:40:07,041: DEBUG/MainProcess] | Worker: Starting Hub
[2020-12-22 10:40:07,041: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:07,042: DEBUG/MainProcess] | Worker: Starting Pool
[2020-12-22 10:40:07,237: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:07,238: DEBUG/MainProcess] | Worker: Starting Consumer
[2020-12-22 10:40:07,239: DEBUG/MainProcess] | Consumer: Starting Connection
[2020-12-22 10:40:07,286: INFO/MainProcess] Connected to redis://localhost:6379/0
[2020-12-22 10:40:07,287: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:07,287: DEBUG/MainProcess] | Consumer: Starting Events
[2020-12-22 10:40:07,310: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:07,311: DEBUG/MainProcess] | Consumer: Starting Heart
[2020-12-22 10:40:07,317: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:07,317: DEBUG/MainProcess] | Consumer: Starting Mingle
[2020-12-22 10:40:07,317: INFO/MainProcess] mingle: searching for neighbors
[2020-12-22 10:40:08,397: INFO/MainProcess] mingle: all alone
[2020-12-22 10:40:08,397: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:08,397: DEBUG/MainProcess] | Consumer: Starting Tasks
[2020-12-22 10:40:08,405: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:08,405: DEBUG/MainProcess] | Consumer: Starting Control
[2020-12-22 10:40:08,422: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:08,423: DEBUG/MainProcess] | Consumer: Starting Gossip
[2020-12-22 10:40:08,446: DEBUG/MainProcess] ^-- substep ok
[2020-12-22 10:40:08,446: DEBUG/MainProcess] | Consumer: Starting event loop
[2020-12-22 10:40:08,446: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2020-12-22 10:40:08,447: INFO/MainProcess] whoopsie@computer ready.
[2020-12-22 10:40:08,448: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2020-12-22 10:40:16,492: INFO/MainProcess] Received task: app.worker_name[d5f96484-0a00-4726-ac54-222765aa0901]  
[2020-12-22 10:40:16,493: DEBUG/MainProcess] TaskPool: Apply <function _trace_task_ret at 0x10f05b3b0> (args:('app.worker_name', 'd5f96484-0a00-4726-ac54-222765aa0901', {'lang': 'py', 'task': 'app.worker_name', 'id': 'd5f96484-0a00-4726-ac54-222765aa0901', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'd5f96484-0a00-4726-ac54-222765aa0901', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen3304@Fredriks-MacBook-Pro.local', 'reply_to': 'a0afc794-880a-3e05-970f-5013e0b0ed61', 'correlation_id': 'd5f96484-0a00-4726-ac54-222765aa0901', 'hostname': 'whoopsie@computer', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}, 'args': [], 'kwargs': {}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2020-12-22 10:40:16,495: DEBUG/MainProcess] Task accepted: app.worker_name[d5f96484-0a00-4726-ac54-222765aa0901] pid:3300
[2020-12-22 10:40:16,513: INFO/ForkPoolWorker-2] Task app.worker_name[d5f96484-0a00-4726-ac54-222765aa0901] succeeded in 0.016767310000000535s: 'Fredriks-MacBook-Pro.local'
```

</p>
</details>

**Comment by auvipy** [comment]
so it was OK with celery 4.4.6?

**Comment by freedrikp** [comment]
Yes, all 4.x.x versions follow the documentation and works as I would expect. The bug was introduced in 5.0.0 and since then it no longer works and only reports the hostname.

**Comment by freedrikp** [comment]
I've done some debugging and digging through the code. I think I've found where the hostname is being overwritten.

Apparently the issue seem to be in `celery/app/trace.py` in `_trace_task_ret` where this piexe of code exists:

```
    hostname = gethostname()
    request.update({
        'args': args, 'kwargs': kwargs,
        'hostname': hostname, 'is_eager': False,
    }, **embed or {})
```

This code is the same between 4.4.7 and 5.0.0. However, I note that in 4.4.7 the `_trace_task_ret` function is not used and instead `_fast_trace_task` is used which do not overwrite the hostname using the gethostname function. If i remove this hostname overwriting it works as I would expect.

I have no idea what these functions do or why they overwrite hostname so simply removing that bit is bound to break other things.

**Comment by freedrikp** [comment]
I have managed to bisect the issue to:

```
commit 01651d2f5d9ad20dfb9812d92831510147974b23 (HEAD)
Author:     Omer Katz <omer.drow@gmail.com>
AuthorDate: Wed Aug 19 20:19:45 2020 +0300
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Aug 19 20:19:45 2020 +0300

    Refactor CLI to use Click instead of our custom argparse based framework (#5718)
```

**Comment by auvipy** [comment]
> I have managed to bisect the issue to:
> 
> ```
> commit 01651d2f5d9ad20dfb9812d92831510147974b23 (HEAD)
> Author:     Omer Katz <omer.drow@gmail.com>
> AuthorDate: Wed Aug 19 20:19:45 2020 +0300
> Commit:     GitHub <noreply@github.com>
> CommitDate: Wed Aug 19 20:19:45 2020 +0300
> 
>     Refactor CLI to use Click instead of our custom argparse based framework (#5718)
> ```

@thedrow mind having a look?

**Comment by matusvalo** [comment]
> 
> 
> I've done some debugging and digging through the code. I think I've found where the hostname is being overwritten.
> 
> Apparently the issue seem to be in `celery/app/trace.py` in `_trace_task_ret` where this piexe of code exists:
> 
> ```
>     hostname = gethostname()
>     request.update({
>         'args': args, 'kwargs': kwargs,
>         'hostname': hostname, 'is_eager': False,
>     }, **embed or {})
> ```
> 
> This code is the same between 4.4.7 and 5.0.0. However, I note that in 4.4.7 the `_trace_task_ret` function is not used and instead `_fast_trace_task` is used which do not overwrite the hostname using the `gethostname()` function. If i remove this call to `gethostname()` and use the one already in `request` it works as I would expect.
> 
> I have no idea what these functions do or why they overwrite hostname so simply removing that bit is bound to break other things.

I did some investigation. Here is the reason why it happens:
In https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/worker/request.py#L630-L632
the parameter `trace` is having different value.

Celery v 4.X.X:
```
[2020-12-23 01:47:19,835: WARNING/MainProcess] <function _fast_trace_task at 0x7f57a42bcb80>
[2020-12-23 01:47:19,835: WARNING/MainProcess] trace_task_ret
[2020-12-23 01:47:19,836: WARNING/MainProcess] <function _fast_trace_task at 0x7f57a42bcb80>
```
Celery v 5.X.X
```
[2020-12-23 01:49:11,972: WARNING/MainProcess] trace
[2020-12-23 01:49:11,972: WARNING/MainProcess] <function _trace_task_ret at 0x7f9c2edb15e0>
[2020-12-23 01:49:11,972: WARNING/MainProcess] trace_task_ret
[2020-12-23 01:49:11,972: WARNING/MainProcess] <function _fast_trace_task at 0x7f9c2edb1670>
```

Now, the difficult part:
1. the `create_request_cls` is not called with `trace` parameter hence all the time default value is used but the default value magically changes during runtime. (don't ask me why)
https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/worker/strategy.py#L127
2. The value `trace_task_ret` (default value of `trace`) magically changed during runtime here:
https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/app/trace.py#L652-L655

Hence, it seems (it's just my theory) that introducing Click framework reloads imported module which is resetting default value of `trace`.

**Comment by matusvalo** [comment]
OK I was able to fix the issue (this is only dirty not complete fix). Basically, instead of dirty rewriting globals of modules, I have added a dirty global flag to Celery Application object :-). Here's the diff:

```diff
diff --git a/celery/app/trace.py b/celery/app/trace.py
index f9b8c83e6..ccb0ba1c6 100644
--- a/celery/app/trace.py
+++ b/celery/app/trace.py
@@ -606,6 +606,8 @@ def _fast_trace_task(task, uuid, request, body, content_type,
     )
     return (1, R, T) if I else (0, Rstr, T)

+fast_trace_task = _fast_trace_task  # noqa: E305
+

 def report_internal_error(task, exc):
     _type, _value, _tb = sys.exc_info()
@@ -622,7 +624,6 @@ def report_internal_error(task, exc):

 def setup_worker_optimizations(app, hostname=None):
     """Setup worker related optimizations."""
-    global trace_task_ret

     hostname = hostname or gethostname()

@@ -649,16 +650,11 @@ def setup_worker_optimizations(app, hostname=None):
         hostname,
     ]

-    trace_task_ret = _fast_trace_task
-    from celery.worker import request as request_module
-    request_module.trace_task_ret = _fast_trace_task
-    request_module.__optimize__()
+    app.use_fast_trace_task = True


-def reset_worker_optimizations():
+def reset_worker_optimizations(app):
     """Reset previously configured optimizations."""
-    global trace_task_ret
-    trace_task_ret = _trace_task_ret
     try:
         delattr(BaseTask, '_stackprotected')
     except AttributeError:
@@ -667,8 +663,7 @@ def reset_worker_optimizations():
         BaseTask.__call__ = _patched.pop('BaseTask.__call__')
     except KeyError:
         pass
-    from celery.worker import request as request_module
-    request_module.trace_task_ret = _trace_task_ret
+    app.use_fast_trace_task = False


 def _install_stack_protection():
diff --git a/celery/worker/request.py b/celery/worker/request.py
index 81c3387d9..fa5212f1e 100644
--- a/celery/worker/request.py
+++ b/celery/worker/request.py
@@ -15,7 +15,7 @@ from kombu.utils.objects import cached_property

 from celery import signals
 from celery.app.task import Context
-from celery.app.trace import trace_task, trace_task_ret
+from celery.app.trace import trace_task, trace_task_ret, fast_trace_task
 from celery.exceptions import (Ignore, InvalidTaskError, Reject, Retry,
                                TaskRevokedError, Terminated,
                                TimeLimitExceeded, WorkerLostError)
@@ -627,15 +627,18 @@ class Request:
         return self._request_dict.get('group_index')


-def create_request_cls(base, task, pool, hostname, eventer,
+def create_request_cls(app, base, task, pool, hostname, eventer,
                        ref=ref, revoked_tasks=revoked_tasks,
-                       task_ready=task_ready, trace=trace_task_ret):
+                       task_ready=task_ready, trace=None):
     default_time_limit = task.time_limit
     default_soft_time_limit = task.soft_time_limit
     apply_async = pool.apply_async
     acks_late = task.acks_late
     events = eventer and eventer.enabled

+    if trace is None and hasattr(app, 'use_fast_trace_task') and app.use_fast_trace_task:
+        trace = fast_trace_task
+
     class Request(base):

         def execute_using_pool(self, pool, **kwargs):
diff --git a/celery/worker/strategy.py b/celery/worker/strategy.py
index 8fb1eabd3..6adc3b82c 100644
--- a/celery/worker/strategy.py
+++ b/celery/worker/strategy.py
@@ -124,7 +124,7 @@ def default(task, app, consumer,
     limit_task = consumer._limit_task
     limit_post_eta = consumer._limit_post_eta
     Request = symbol_by_name(task.Request)
-    Req = create_request_cls(Request, task, consumer.pool, hostname, eventer)
+    Req = create_request_cls(app, Request, task, consumer.pool, hostname, eventer)

     revoked_tasks = consumer.controller.state.revoked
```

**Comment by thedrow** [comment]
> 
> 
> > I have managed to bisect the issue to:
> > ```
> > commit 01651d2f5d9ad20dfb9812d92831510147974b23 (HEAD)
> > Author:     Omer Katz <omer.drow@gmail.com>
> > AuthorDate: Wed Aug 19 20:19:45 2020 +0300
> > Commit:     GitHub <noreply@github.com>
> > CommitDate: Wed Aug 19 20:19:45 2020 +0300
> > 
> >     Refactor CLI to use Click instead of our custom argparse based framework (#5718)
> > ```
> 
> @thedrow mind having a look?

@auvipy Sorry, I missed it. I just commented on the PR.

**Comment by auvipy** [comment]
> > I've done some debugging and digging through the code. I think I've found where the hostname is being overwritten.
> > Apparently the issue seem to be in `celery/app/trace.py` in `_trace_task_ret` where this piexe of code exists:
> > ```
> >     hostname = gethostname()
> >     request.update({
> >         'args': args, 'kwargs': kwargs,
> >         'hostname': hostname, 'is_eager': False,
> >     }, **embed or {})
> > ```
> > 
> > 
> > This code is the same between 4.4.7 and 5.0.0. However, I note that in 4.4.7 the `_trace_task_ret` function is not used and instead `_fast_trace_task` is used which do not overwrite the hostname using the `gethostname()` function. If i remove this call to `gethostname()` and use the one already in `request` it works as I would expect.
> > I have no idea what these functions do or why they overwrite hostname so simply removing that bit is bound to break other things.
> 
> I did some investigation. Here is the reason why it happens:
> In
> 
> https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/worker/request.py#L630-L632
> 
> the parameter `trace` is having different value. I have printed `trace` and `trace_task_ret`:
> 
> ```
> def create_request_cls(base, task, pool, hostname, eventer,
>                        ref=ref, revoked_tasks=revoked_tasks,
>                        task_ready=task_ready, trace=trace_task_ret):
>     default_time_limit = task.time_limit
>     default_soft_time_limit = task.soft_time_limit
>     apply_async = pool.apply_async
>     acks_late = task.acks_late
>     events = eventer and eventer.enabled
> 
>     class Request(base):
> 
>         def execute_using_pool(self, pool, **kwargs):
>             task_id = self.task_id
>             if (self.expires or task_id in revoked_tasks) and self.revoked():
>                 raise TaskRevokedError(task_id)
> 
>             time_limit, soft_time_limit = self.time_limits
>             print('trace', trace)
>             print('trace_task_ret', trace_task_ret)
>             result = apply_async(
> ```
> 
> Celery v 4.X.X ():
> 
> ```
> [2020-12-23 01:47:19,835: WARNING/MainProcess] trace
> [2020-12-23 01:47:19,835: WARNING/MainProcess] <function _fast_trace_task at 0x7f57a42bcb80>
> [2020-12-23 01:47:19,835: WARNING/MainProcess] trace_task_ret
> [2020-12-23 01:47:19,836: WARNING/MainProcess] <function _fast_trace_task at 0x7f57a42bcb80>
> ```
> 
> Celery v 5.X.X
> 
> ```
> [2020-12-23 01:49:11,972: WARNING/MainProcess] trace
> [2020-12-23 01:49:11,972: WARNING/MainProcess] <function _trace_task_ret at 0x7f9c2edb15e0>
> [2020-12-23 01:49:11,972: WARNING/MainProcess] trace_task_ret
> [2020-12-23 01:49:11,972: WARNING/MainProcess] <function _fast_trace_task at 0x7f9c2edb1670>
> ```
> 
> Now, the difficult part:
> 
>     1. the `create_request_cls` is not called with `trace` parameter hence all the time default value is used but the default value magically changes during runtime. (don't ask me why)
>        https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/worker/strategy.py#L127
> 
>     2. The value `trace_task_ret` (default value of `trace`) magically changed during runtime here:
>        https://github.com/celery/celery/blob/3546059338bea70bab7ef9d961b00c161938b15e/celery/app/trace.py#L652-L655
> 
> 
> Hence, it seems (it's just my theory) that introducing Click framework reloads imported module which is resetting default value of `trace`.

interesting!

**Comment by auvipy** [comment]
> # Checklist
> 
>     * [x]  I have verified that the issue exists against the `master` branch of Celery.
> 
>     * [x]  This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
>       -- https://groups.google.com/g/celery-users/c/uqCUtMUu8XY
> 
>     * [x]  I have read the relevant section in the
>       [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
>       on reporting bugs.
> 
>     * [x]  I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
>       for similar or identical bug reports.
> 
>     * [x]  I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
>       for existing proposed fixes.
> 
>     * [x]  I have checked the [commit log](https://github.com/celery/celery/commits/master)
>       to find out if the bug was already fixed in the master branch.
> 
>     * [x]  I have included all related issues and possible duplicate issues
>       in this issue (If there are none, check this box anyway).
> 
> 
> ## Mandatory Debugging Information
> 
>     * [x]  I have included the output of `celery -A proj report` in the issue.
>       (if you are not able to do this, then at least specify the Celery
>       version affected).
> 
>     * [x]  I have verified that the issue exists against the `master` branch of Celery.
> 
>     * [x]  I have included the contents of `pip freeze` in the issue.
> 
>     * [x]  I have included all the versions of all the external dependencies required
>       to reproduce this bug.
> 
> 
> ## Optional Debugging Information
> 
>     * [x]  I have tried reproducing the issue on more than one Python version
>       and/or implementation.
> 
>     * [x]  I have tried reproducing the issue on more than one message broker and/or
>       result backend.
> 
>     * [ ]  I have tried reproducing the issue on more than one version of the message
>       broker and/or result backend.
> 
>     * [x]  I have tried reproducing the issue on more than one operating system.
> 
>     * [x]  I have tried reproducing the issue on more than one workers pool.
> 
>     * [x]  I have tried reproducing the issue with autoscaling, retries,
>       ETA/Countdown & rate limits disabled.
> 
>     * [x]  I have tried reproducing the issue after downgrading
>       and/or upgrading Celery and its dependencies.
> 
> 
> ## Related Issues and Possible Duplicates
> #### Related Issues
> 
>     * None
> 
> 
> #### Possible Duplicates
> 
>     * None
> 
> 
> ## Environment & Settings
> 
> **Celery version**: 5.0.5 (singularity)
> `celery report` Output:
> # Steps to Reproduce
> ## Required Dependencies
> 
>     * **Minimal Python Version**: N/A or Unknown
> 
>     * **Minimal Celery Version**: 5.0.0
> 
>     * **Minimal Kombu Version**: N/A or Unknown
> 
>     * **Minimal Broker Version**: N/A or Unknown
> 
>     * **Minimal Result Backend Version**: N/A or Unknown
> 
>     * **Minimal OS and/or Kernel Version**: N/A or Unknown
> 
>     * **Minimal Broker Client Version**: N/A or Unknown
> 
>     * **Minimal Result Backend Client Version**: N/A or Unknown
> 
> 
> ### Python Packages
> `pip freeze` Output:
> ### Other Dependencies
> ## Minimally Reproducible Test Case
> # Expected Behavior
> 
> As described in the documentation `task.request.hostname` should be the node name of the worker instance executing the task. See https://docs.celeryproject.org/en/latest/userguide/tasks.html#task-request-info
> # Actual Behavior
> 
> `task.request.hostname` no longer contains the node name of the worker. Only the hostname of the worker. For example if the worker is started with `-n whoopsie@%h` only the `%h` bit is included in `task.request.hostname`. In fact if the worker is started `-n whoopsie@computer` it will still only report the hostname of the worker machine and not what has been put into the node name.
> 
> This issue appeared between v4.4.7 and v5.0.0 and is present in current master. It is really useful for debugging purposes to know what exact worker instance a task is executed in if there are multiple workers on the same host.
> 
> It appears that the worker is at least aware of its worker name based on the worker logs:
> `celery -A app.app worker -n whoopsie@computer --loglevel=DEBUG`

@freedrikp would you mind testing https://github.com/celery/celery/pull/6598 locally?

**Comment by freedrikp** [comment]
Hi! Yes I can confirm that #6598 solves this problem for me! :)

**Comment by auvipy** [comment]
> Hi! Yes I can confirm that #6598 solves this problem for me! :)

thanks for your report!
