### ISSUE TITLE
Encapsulate each task in it's own process

### ISSUE THREAD

**Issue by crazyscientist** [celery/celery#6556]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- #4551
- #4525

#### Possible Duplicates

- #4551

# Brief Summary

Memory leaks can be difficult to track down, especially when they are caused by 3rd party packages. In theory these obviously should be fixed, but in real life, where one needs to keep things running, one might be happy enough if the memory leaks were contained.

So I'd like to propose a solution to _quarantene_ memory leaks in task specific processes in order to avoid an increasing memory usage of the Celery workers, which appears to be a common reason for restarting the workers.

# Design

## Architectural Considerations
None

## Proposed Behavior

My proposal looks as follows:

* The Celery workers fork/spawn/... a new child process before executing a task.
* Task execution is done in this child process. 
* The result is retrieved from the child process
* The child process is terminated.
* The results is handed to the result backend by the worker process

In a variation, this proposal might be extended to allow processing of a chunk in child process or the delegation of the task execution might be made optional.

In all other regards (e.g. errors, exceptions) this feature should behave identically to the current behavior.

## Diagrams

![scratch_1](https://user-images.githubusercontent.com/1128117/102881655-7883b480-444d-11eb-8a47-dddb27fb8e73.png)

This diagram illustrates the basic idea. If a task leaks memory, the memory consumption will rise until the Worker process (e.g. the Celery systemd service) is restarted. If the execution of such a task is contained in a separate child process, memory is freed after each task.

## Alternatives

Instead of including this feature in Celery itself, one could implement this feature in a subclass of `celery.Task`?

**Comment by auvipy** [comment]
you might check this https://github.com/celery/billiard/issues/326

**Comment by crazyscientist** [comment]
@auvipy Yes, that is the idea.

**Comment by auvipy** [comment]
OK cool, do you have any implementation prototype on your mind?

**Comment by crazyscientist** [comment]
> do you have any implementation prototype on your mind?

Sorry, I have only the abstract idea at the moment. As this is a bigger issue for me (one of my tasks is really huge and can occupy easily 10GB RAM) I'm currently looking under the hood of Celery in order to figure out how my proposed alternative would be implemented.

**Comment by auvipy** [comment]
> > do you have any implementation prototype on your mind?
> 
> Sorry, I have only the abstract idea at the moment. As this is a bigger issue for me (one of my tasks is really huge and can occupy easily 10GB RAM) I'm currently looking under the hood of Celery in order to figure out how my proposed alternative would be implemented.

did you figure the root cause of the memory usage of your task?

**Comment by crazyscientist** [comment]
> did you figure the root cause of the memory usage of your task?

I'm pretty sure which Python bindings built with Swig are the problem, but I'm not too eager to have a closer look at this 3rd party code, yet. Yesterday I spent most of the time refactoring my code (calling functions from this 3rd party package) so that instead of having one big task (runtime: 20-26 hours, mem usage: 10GB) I end up with approx. 800 tasks. (Please refrain from comments regarding _my_ code's quality; it was ported from C to Python and handed down many generations of maintainers; I got plenty of cleaning up ahead of me).

Let's switch the topic. Would my proposal be something, that improves Celery?

**Comment by matusvalo** [comment]
-1 for me. This can problems for users who wants optimize number of tasks processed in time. Spawning new process for each task is adding too much overhead. I propose to have configurable option where you can specify # of tasks processed by worker after which is killed by manager and started as a fresh one - e.g. uWSGI has something similar - see [1]

[1] https://uwsgi-docs.readthedocs.io/en/latest/Options.html#max-requests

**Comment by ahopkins** [comment]
I agree. This should not be a forced behavior, if implemented. I like the idea and see its utility, but having tasks in a single process also is helpful and necessary when creating certain patterns that rely upon stateful instances. But more implementation options certainly sounds beneficial.

**Comment by crazyscientist** [comment]
Thanks for pointing these things out, @matusvalo @ahopkins, my proposal obviously should not negatively impact other more common use cases :+1:

**Comment by matusvalo** [comment]
@crazyscientist just for a curiosity. Is viable solution for executing task code in separate process using the following code snippet?
```python
import concurrent.futures

def mylogic():
    # here is defined logic of task
    pass

@app.task
def create_user():
    with concurrent.futures.ProcessPoolExecutor() as executor:
        # run the logic of task in separate temporary process
        f = executor.submit(mylogic)
        return f.result()
```

**Comment by crazyscientist** [comment]
@matusvalo yes, this is the basic idea. 

However the Python standard library will not be any help here, because `multiprocessing.Process` will raise an AssertionError, because it does not allow to spawn/fork a new high-level process from a daemon process (Celery worker processes are daemon processes). I'm using `billiard.pool.Pool` instead of `ProcessPoolExecutor` for my tests at the moment.

Yes, handling the process encapsulation in my tasks (instead of Celery) will certainly work. But I was looking at a few GitHub issues and noticed that memory leaks are a _problem_ for others as well. So I figured it might be a good idea to discuss implementation in Celery in order to reduce some boilerplate code in task definitions :wink:

**Comment by crazyscientist** [comment]
Sorry for wasting all our time. I could have just used the [--max-tasks-per-child](https://docs.celeryproject.org/en/stable/reference/cli.html#cmdoption-celery-worker-max-tasks-per-child) option. With a value of **1** I would basically get exactly what I was looking for :facepalm:
