### ISSUE TITLE
no module named celery.task

### ISSUE THREAD

**Issue by brahim024** [celery/celery#6558]
from celery import shared_task
from .models import Test, Prices

from celery.decorators import periodic_task
from celery.task.schedules import crontab
import requests 
@shared_task
def create_price_items(name):
    Test.objects.create(name=name)
    

@periodic_task(run_every=(crontab(minute='*/1')))
def run_create_items():
    create_price_items.delay(name='new2020')
-------error----------
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\acer\Desktop\django\open source\dj-blog\src\dj-bitcoin-tracker-api\prices\tasks.py", line 5, in <module>
    **from celery.task.schedules import crontab
ModuleNotFoundError: No module named 'celery.task'**

**Comment by thedrow** [comment]
The module was deprecated and therefore was removed in 5.0.
Please refer to the documentation.

**Comment by jnns** [comment]
For anyone wondering: it seems the module was removed in 5.0.0rc2 [in this commit](https://github.com/celery/celery/commit/757101358222dde4a72a2d1ce1edb5411591ab96)  and it has been advised to use `celery.shared_task` [in the docs since 4.0.0](https://docs.celeryproject.org/en/4.0/userguide/tasks.html#basics). I couldn't find any deprecation notes in the changelogs for [version 4](https://docs.celeryproject.org/en/4.0/changelog.html) or [version 5](https://docs.celeryproject.org/en/v5.0.0/changelog.html).

From the docs: 
> #### How do I import the task decorator? And what’s “app”?
> 
> The task decorator is available on your Celery application instance, if you don’t know what this is then please read First Steps with Celery.
> 
> If you’re using Django (see First steps with Django), or you’re the author of a library then you probably want to use the shared_task() decorator:
> 
> ```python
> from celery import shared_task
> 
> @shared_task
> def add(x, y):
>     return x + y
> ```

**Comment by thedrow** [comment]
Seems like I missed it in the migration guide and the changelog. https://docs.celeryproject.org/en/v5.0.0/whatsnew-5.0.html
@jnns A PR to fix this is most welcome.

**Comment by thedrow** [comment]
The What's New document for celery 4 briefly mentions this deprecation.
See https://docs.celeryproject.org/en/4.0/whatsnew-4.0.html#modules

**Comment by JensTimmerman** [comment]
I come from the documentation and read: https://docs.celeryproject.org/en/stable/internals/deprecation.html

This page claims to be the deprecation and compatibility guide for the task
it states

```python


    This means you need to change:

    from celery.decorators import task

    Into:

    from celery import task

```


But this is failing with.
`ModuleNotFoundError: No module named 'celery.task'`


so how is ` Please refer to the documentation.` the correct answer to this issue?

**Comment by auvipy** [comment]
from celery import Task this works 
![image](https://user-images.githubusercontent.com/6212603/135868796-8e6eef90-cffc-4da0-9296-d00c6e78287f.png)

**Comment by auvipy** [comment]
yes thats not

**Comment by ihonomic** [comment]
So in summary, we can use the 'shared_task' decorator in place of 'tasks'? .

**Comment by auvipy** [comment]
yes https://github.com/celery/celery/blob/master/celery/app/__init__.py#L25

**Comment by JensTimmerman** [comment]
Yes, I tried to make this more clear in the current documentation via https://github.com/celery/celery/pull/6981

if it's still unclear, or stated otherwise somwhere, can you point me to the wrong parts, I can make a new pr :)
