### ISSUE TITLE
Celery creates useless *.pidbox queues

### ISSUE THREAD

**Issue by alexpirine** [celery/celery#6575]
Hello,

Celery creates useless, empty, never-used `*.pidbox` queues:

![image](https://user-images.githubusercontent.com/1610035/101693567-1c468b00-3a72-11eb-948a-06f7f959f78d.png)

![image](https://user-images.githubusercontent.com/1610035/101693602-2a94a700-3a72-11eb-82eb-f708f45e7758.png)

I would like to have a way to remove them to keep the system as tidy as possible.

**Comment by thedrow** [comment]
You should set [`worker_enable_remote_control`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#worker-enable-remote-control) to `False`.
Please refer to the documentation next time.
