### ISSUE TITLE
Why does Celery Worker think uid=1000640000 euid=1000640000 is superuser privilege?

### ISSUE THREAD

**Issue by Homopatrol** [celery/celery#6579]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
https://github.com/DefectDojo/django-DefectDojo/pull/3582
## Environment & Settings

# Steps to Reproduce
I have come across this when running using OpenShift restricted SCC
```
oc logs defect-dojo-defectdojo-celery-worker-78dbb86b48-2rxn2
uid=1000640000(1000640000) gid=0(root) groups=0(root),1000640000
Waiting for database to be reachable [06/Jan/2021 13:40:58] INFO [dojo.models:3474] enabling audit logging
[06/Jan/2021 13:41:00] INFO [dojo.models:3474] enabling audit logging
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!
If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).
User information: uid=1000640000 euid=1000640000 gid=0 egid=0
```
## Required Dependencies

* **Minimal Python Version**: N/A
* **Minimal Celery Version**: 4.1.1
* **Minimal Kombu Version**: 4.1 
* **Minimal Broker Version**: N/A 
* **Minimal Result Backend Version**: N/A 
* **Minimal OS and/or Kernel Version**: N/A 
* **Minimal Broker Client Version**: N/A 
* **Minimal Result Backend Client Version**: N/A 

## Minimally Reproducible Test Case

# Expected Behavior
I believe that GID=0 doesn't give superuser privileges, so am not sure why the celery checks are implemented in this manner.

# Actual Behavior
The gid (and egid) being 0 does not give superuser prvilieges
 as stated - https://unix.stackexchange.com/questions/44077/what-does-it-mean-to-be-in-group-0 and https://docs.celeryproject.org/en/stable/userguide/daemonizing.html#running-the-worker-with-superuser-privileges-root

**Comment by auvipy** [comment]
> Running a worker with superuser privileges when the
> worker accepts messages serialized with pickle is a very bad idea!
> If you really want to continue then you have to set the C_FORCE_ROOT
> environment variable (but please think about this before you do).
> User information: uid=1000640000 euid=1000640000 gid=0 egid=0

Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!
If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).
User information: uid=1000640000 euid=1000640000 gid=0 egid=0

-- celery is telling not to use root ... and telling current egid n gid = 0 means you are not a superuser right now, so what is celery doing wrong?

**Comment by namloc2001** [comment]
@auvipy celery is telling us not to run as root, which I can completely agree with. And we are not running as root (as shown by the output we are running as uid=1000640000). However the [code](https://github.com/celery/celery/blob/master/celery/platforms.py#L789) is causing our container to terminate.
```
def check_privileges(accept_content):
    uid = os.getuid() if hasattr(os, 'getuid') else 65535
    gid = os.getgid() if hasattr(os, 'getgid') else 65535
    euid = os.geteuid() if hasattr(os, 'geteuid') else 65535
    egid = os.getegid() if hasattr(os, 'getegid') else 65535

    if hasattr(os, 'fchown'):
        if not all(hasattr(os, attr)
                   for attr in ['getuid', 'getgid', 'geteuid', 'getegid']):
            raise SecurityError('suspicious platform, contact support')

    if not uid or not gid or not euid or not egid:
        if ('pickle' in accept_content or
                'application/x-python-serialize' in accept_content):
            if not C_FORCE_ROOT:
                try:
                    print(ROOT_DISALLOWED.format(
                        uid=uid, euid=euid, gid=gid, egid=egid,
                    ), file=sys.stderr)
                finally:
                    sys.stderr.flush()
                    os._exit(1)
        warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
            uid=uid, euid=euid, gid=gid, egid=egid,
```

and we get the message as shown in `ROOT_DISALLOWED`:
```
ROOT_DISALLOWED = """\
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!
If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).
User information: uid={uid} euid={euid} gid={gid} egid={egid}
"""
```

**Comment by namloc2001** [comment]
To test this, I've created a user with uid=1000 and gid=0. I then run the code below (which is a stripped down version of what celery `platforms.py` is currently doing:
```
#!/usr/bin/env python

import os
import sys

def main():
    uid = os.getuid() if hasattr(os, 'getuid') else 65535
    gid = os.getgid() if hasattr(os, 'getgid') else 65535
    euid = os.geteuid() if hasattr(os, 'geteuid') else 65535
    egid = os.getegid() if hasattr(os, 'getegid') else 65535

    if hasattr(os, 'fchown'):
        if not all(hasattr(os, attr)
                   for attr in ['getuid', 'getgid', 'geteuid', 'getegid']):
            raise SecurityError('suspicious platform, contact support')

    if not uid or not gid or not euid or not egid:
        sys.stdout.write('Something is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
    else:
        sys.stdout.write('Nothing is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')

if __name__ == '__main__':
    main()
```

Here's confirm of my user configuration prior to running the script:
```
id
uid=1000(matt) gid=0(root) groups=0(root),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(lxd),114(netdev),999(docker)
```

The result of running the script is:
```
./platform.py
Something is zero. uid=1000 euid=1000 gid=0 egid=0
```

If I then update the sample script so that it only checks if uid or euid is 0:
```
    if not uid or not euid:
    #if not uid or not gid or not euid or not egid:
        sys.stdout.write('Something is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
    else:
        sys.stdout.write('Nothing is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
```

The result of running the script is:
```
./platform.py
Nothing is zero. uid=1000 euid=1000 gid=0 egid=0
```

And thus this would then (correctly) not invoke the `ROOT_DISALLOWED` message in `platforms.py`.

**Comment by auvipy** [comment]
> To test this, I've created a user with uid=1000 and gid=0. I then run the code below (which is a stripped down version of what celery `platforms.py` is currently doing:
> 
> ```
> #!/usr/bin/env python
> 
> import os
> import sys
> 
> def main():
>     uid = os.getuid() if hasattr(os, 'getuid') else 65535
>     gid = os.getgid() if hasattr(os, 'getgid') else 65535
>     euid = os.geteuid() if hasattr(os, 'geteuid') else 65535
>     egid = os.getegid() if hasattr(os, 'getegid') else 65535
> 
>     if hasattr(os, 'fchown'):
>         if not all(hasattr(os, attr)
>                    for attr in ['getuid', 'getgid', 'geteuid', 'getegid']):
>             raise SecurityError('suspicious platform, contact support')
> 
>     if not uid or not gid or not euid or not egid:
>         sys.stdout.write('Something is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
>     else:
>         sys.stdout.write('Nothing is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> Here's confirm of my user configuration prior to running the script:
> 
> ```
> id
> uid=1000(matt) gid=0(root) groups=0(root),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(lxd),114(netdev),999(docker)
> ```
> 
> The result of running the script is:
> 
> ```
> ./platform.py
> Something is zero. uid=1000 euid=1000 gid=0 egid=0
> ```
> 
> If I then update the sample script so that it only checks if uid or euid is 0:
> 
> ```
>     if not uid or not euid:
>     #if not uid or not gid or not euid or not egid:
>         sys.stdout.write('Something is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
>     else:
>         sys.stdout.write('Nothing is zero. uid=' + str(uid) + ' euid=' + str(euid) + ' gid=' + str(gid) + ' egid=' + str(egid) + '\n')
> ```
> 
> The result of running the script is:
> 
> ```
> ./platform.py
> Nothing is zero. uid=1000 euid=1000 gid=0 egid=0
> ```
> 
> And thus this would then (correctly) not invoke the `ROOT_DISALLOWED` message in `platforms.py`.

thanks! are able to send a possible fix?

**Comment by namloc2001** [comment]
@auvipy I've raised #6600.

**Comment by thedrow** [comment]
This is not a problem on Linux but I don't know where it might be.

> Unlike user 0 (the root user), group 0 does not have any special privilege at the kernel level.
> Traditionally, group 0 had special privileges on many unix variants — either the right to use su to become root (after typing the root password), or the right to become root without typing a password. Basically, the users in group 0 were the system administrators. When group 0 has special privileges, it is called wheel

[Source](https://unix.stackexchange.com/a/44086/2781)
