### ISSUE TITLE
How to handle tasks that affect each other?

### ISSUE THREAD

**Issue by verilog15** [celery/celery#6585]
# Checklist

- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

I have a form in my Django app which creates an object `car` (it does not matter that I use Django, it's just to explain the main idea). I use celery to run operations, once new object `car` was created (by using `post_save` signal). I have an option to delete the `car`. So it should delete it from the database and it should run deleting operations with Celery. I use `pre_save` for that. 

The problem is as following: The creating operations can take some time (a few minutes). This means, that user can create a new `car` and while running the Celery creation operation, he will ask to delete the object. The celery tasks:
```
@app.task(bind=True)
def create_car(self, car_pk):
    from cars.models import car
    if car_pk is None or not isinstance(car_pk,int):
        return False
    car_obj = car.objects.get(pk=car_pk)
    
    # Creation operations
    
    car_obj.save()
    return creation_status

@app.task(bind=True)
def delete_car(self, car_pk):
    from cars.models import car
    if car_pk is None or not isinstance(car_pk,int):
        return False
    car_obj = car.objects.get(pk=car_pk)
    
    # deletion operations
    
    return deletion_status
```
So my question is - how should I handle this case? Can I somehow "stop" the creation task? Or can I somehow "wait" until the creation task finish and then do the deletion operations?

If both cases can be achieved, I would be glad to see them both.

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
are you looking for scheduling the tasks? did you check celery beat / django celery beat?

**Comment by verilog15** [comment]
Thank for the comment @auvipy. I'm not sure how beat should help us here. I guess it's not possible to "stop" a task. But is it possible to make a task wait for another task to finish and then run?

**Comment by olii** [comment]
You can terminate your task if you are running a `prefork` worker model. See the docs for [`revoke()`](https://docs.celeryproject.org/en/latest/userguide/workers.html#revoke-revoking-tasks).

**Comment by auvipy** [comment]
> Thank for the comment @auvipy. I'm not sure how beat should help us here. I guess it's not possible to "stop" a task. But is it possible to make a task wait for another task to finish and then run?

I'm not 100% sure about your requirements but can you please check https://docs.celeryproject.org/en/latest/userguide/workers.html#time-limits if it's helpful anyway?

**Comment by thedrow** [comment]
You can use `celery.result.allow_join_result()` but you should know that it may hang the worker.
Please refer to this [section ](https://docs.celeryproject.org/en/stable/userguide/tasks.html#avoid-launching-synchronous-subtasks) in the docs for assistance.
