### ISSUE TITLE
Is continuous integration pipeline working?

### ISSUE THREAD

**Issue by kuba-lilz** [celery/celery#6605]
I looked at output of a few recent github actions pipeline 
( e.g. run https://github.com/celery/celery/actions/runs/494397875 triggered on 2021 01 17)

and all the important jobs it runs, like `run tox`, `run pytest`, `run pip install`, `run pytest doctest` fail with import errors, but are forced to return exit code 0, fooling pipeline into thinking it succeeded.
I assume that's achieved with defining commands like this:
`pytest . || true`

What is the purpose of running continuous integration pipeline like this?
In what way is that useful rather than hiding problems?

**Comment by auvipy** [comment]
The linting action is not perfect. the other jobs only run the unit tests & hang while try to run integration tests as we haven't completely added the capability to that. but we are working on it to improve.

**Comment by kuba-lilz** [comment]
Roger that, thank you for the response.

I appreciate this is an open source project, you guys generously invest your personal time into it, and I'm trying to be gentle with feedback here. Now, one would be amiss saying errors like 
```
Run pip install -r requirements.txt || true
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```
are integration tests issues and hard to fix.

Well, hope CI pipeline will improve in due time.

**Comment by auvipy** [comment]
something like that could fix it. the error you are seeing contributed by another guy. though it was not fully functional, I accepted to improve it later
https://github.com/celery/celery/blob/master/.github/workflows/python-package.yml#L47

**Comment by mjhoffman65** [comment]
@auvipy are there any pieces of the CI improvements I can help out?

**Comment by auvipy** [comment]
integration tests with docker containers in CI. we can do it collaborately next week

**Comment by mjhoffman65** [comment]
> integration tests with docker containers in CI. we can do it collaborately next week

Looking forward to it

**Comment by thedrow** [comment]
It is working now.
Our integration suite is in bad shape at the moment but we're working on that.
