### ISSUE TITLE
Celery 5.1 release

### ISSUE THREAD

**Issue by auvipy** [celery/celery#6618]
Since we are going to following SemVar from Now on, Should we consider celery 5.1 release with few dependency updates, bug fixes and few new features or enhancements? this way we can release smaller 5.1/5.1.1, 5.2, 5.3  etc releases faster with fewer issues IMHO.

Version: 5.1.0
Release PR: #6762

# Checklist

- [x] Release PR drafted
- [x] Release PR reviewed
- [x] The master branch build passes

    [![Build Status](https://github.com/celery/celery/actions/workflows/python-package.yml/badge.svg
)](https://github.com/celery/celery/actions/workflows/python-package.yml)
- [x] Release Notes
- [x] What's New

# Process

## Betas

- [x] Beta 1
- [x] Beta 2

## Release Candidates

- [x] RC 1

# Release Blockers

- [x] #6721
- [x] #6763

# Potential Release Blockers

**Comment by thedrow** [comment]
Heh we need to update the template to use the Github Actions badge.

**Comment by tomwojcik** [comment]
Do you have a date in mind for the release of 5.1? Do you want to close all the issues from [this board](https://github.com/orgs/celery/projects/4#card-55595111) before the release?

I'm asking out of curiosity. I think with all the tickets that are already done, 5.1 will be pretty big.

**Comment by thedrow** [comment]
I have a serious family emergency. I'm trying to work through it.
Ideally, we'd like to get some of it done.
If you'd like to help, I'll gladly accept the help.

**Comment by auvipy** [comment]
I will be reevaluating the milestone issues and release a 5.1.0b1 sometime next week with kombu 5.1.0b1 too so  that some erly adapters can try it, and in the mean time we could add the remaining issues which we want to be included in 5.1.0 final version which @thedrow want to release.

**Comment by thedrow** [comment]
@auvipy The board now has a backlog column which we can use to move issues from To Do.
Whatever you think is too hard to resolve or has a lower priority should move to the backlog column.
Bugs should be fixed before new features are introduced (unless there is a PR for them already).

**Comment by thedrow** [comment]
I'd like to release a second beta after we merge all the new features I'm working on.
Stay tuned.

**Comment by thedrow** [comment]
@tomwojcik Did you get a chance to look at the project board? Is there anything that interests you to work on?

**Comment by tomwojcik** [comment]
@thedrow Sorry but I don't have time to focus on it and I won't have in the foreseeable future.

**Comment by thedrow** [comment]
I just released Beta 2.
Please test it in your staging environments.

I'm going to start writing the release notes.

**Comment by thedrow** [comment]
@celery/core-developers Would you say #6763 is a blocker?
It is a security issue.

**Comment by auvipy** [comment]
it is a blocker then

**Comment by thedrow** [comment]
I'll work on finishing the release notes today and release RC1.

**Comment by thedrow** [comment]
5.1.0 is now GA. :tada:
