### ISSUE TITLE
remove misleading Task.autoregister documentation (and the unused field)

### ISSUE THREAD

**Issue by LaughInJar** [celery/celery#6623]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

The documentation for celery.app.Task describes an attribute `autoregister` and implies that if set to true the task will be registered automatically ("If disabled this task won’t be registered automatically."). However this feature has sadly been removed with the celery 4.0 release.
https://docs.celeryproject.org/en/latest/reference/celery.app.task.html#autoregister

The attribute doesn't appear to be used anywhere, a quick search of the code base found only one other occurrence in the changelog for v1.0.

# Suggestions
Either re-add the automatic registration for class based tasks, remove the field or clarify the documentation.

**Comment by auvipy** [comment]
would you mind sending a PR to clean this up?

**Comment by LaughInJar** [comment]
Sure, here you are: https://github.com/celery/celery/pull/6624
