### ISSUE TITLE
celery event dont include queue name

### ISSUE THREAD

**Issue by zhenlei** [celery/celery#6686]
want to celery queue name as a cluster name, in order to recognize different worker or task from different cluster. I need to know queue name from event. For now it seems that queue name is not included.

such as worker event:
{'hostname': 'w1@host1', 'utcoffset': -8, 'pid': 44900, 'clock': 10800, 'freq': 2.0, 'active': 2, 'processed': 6, 'loadavg': [2.19, 1.94, 1.88], 'sw_ident': 'py-celery', 'sw_ver': '4.4.7', 'sw_sys': 'Darwin', 'timestamp': 1616049305.3960252, 'type': 'worker-heartbeat', 'local_received': 1616049305.457537}

**Comment by thedrow** [comment]
Feel free to send a PR :)

**Comment by tomharvey** [comment]
The task-sent event includes attributes for  `queue` and `name` (the task name).

I'm using (and I think this is the recommended approach) an event receiver to store these attributes in state as they are emitted by the task-sent. Then, in task-* I'm retrieving the queue name and task name as needed based on the task UUID.

**Comment by thedrow** [comment]
> 
> 
> The task-sent event includes attributes for `queue` and `name` (the task name).
> 
> I'm using (and I think this is the recommended approach) an event receiver to store these attributes in state as they are emitted by the task-sent. Then, in task-* I'm retrieving the queue name and task name as needed based on the task UUID.

Yes, you are right.
The event the OP describes has no relation to a queue. It's a worker heartbeat.
