### ISSUE TITLE
Celery 4.0 lowercase name change

### ISSUE THREAD

**Issue by Avamander** [celery/celery#6689]
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

## Related Issues and Possible Duplicates

None I could find on the issue tracker.

# Brief Summary

The [Celery 4.0 lowercase name change](https://docs.celeryproject.org/en/stable/userguide/configuration.html#new-lowercase-settings) brings zero benefit for developer but causes downsides in the form of name and style collisions in existing configuration files/classes.

# Design

## Architectural Considerations
None

## Proposed Behavior
Allow people to keep the old behaviour because the new one isn't beneficial.

## Diagrams
N/A

## Alternatives
There isn't a way to avoid name collisions in a simple way because Celery decided to namesquat randomly. Separate file maybe. The lack of configuration option owner prefix can't really be worked around trivially.

**Comment by auvipy** [comment]
I am closing this issue as not useful. we can do docs improvements

**Comment by Avamander** [comment]
There's always the chance to revert the change and/or rename configuration keys to have a proper prefix.

**Comment by Avamander** [comment]
@auvipy Docs won't fix the issue.

**Comment by thedrow** [comment]
There's no chance we'll re-introduce this old functionality.
It complicates the code and it has no benefit to our users.

**Comment by Avamander** [comment]
It certainly has a benefit to your users, I don't know why you're saying otherwise. 

If you're not fixing the erroneous lowercasing, add a prefix, it's short-sighted how there's an assumption none of those config keys are used by anyone else.

**Comment by clokep** [comment]
> If you're not fixing the erroneous lowercasing, add a prefix, it's short-sighted how there's an assumption none of those config keys are used by anyone else.

You can add a prefix, see https://docs.celeryproject.org/en/stable/history/whatsnew-4.0.html#latentcall-django-admonition

**Comment by Avamander** [comment]
@clokep that seems django-specific, is it not?

**Comment by clokep** [comment]
> @clokep that seems django-specific, is it not?

It is not, it just gives the example that makes sense with Django. You can use `app.config_from_settings` in your project however you want. See https://docs.celeryproject.org/en/stable/userguide/application.html#config-from-object

**Comment by Avamander** [comment]
@clokep 

Cool, that's probably usable, thanks. 

The documentation should probably focus on the functionality in general and just mention it's useful with Django, not that it's for Django and useful for others.

**Comment by thedrow** [comment]
> 
> 
> @clokep
> 
> Cool, that's probably usable, thanks.
> 
> The documentation should probably focus on the functionality in general and just mention it's useful with Django, not that it's for Django and useful for others.

PRs for improving the docs are always welcome.
