### ISSUE TITLE
Celery inspect expected extra argument

### ISSUE THREAD

**Issue by codeasashu** [celery/celery#6705]
I am trying to inspect a task which I can see in my redis broker as `SUCCESS`, however, it was never logged by celery application.

I then tried inspecting it, but I am unable to do so, getting following error

![image](https://user-images.githubusercontent.com/1492350/113293545-8af66f80-9313-11eb-910a-d44eea9745e1.png)

Output of `celery report`

```
software -> celery:5.0.2 (singularity) kombu:5.0.2 py:3.6.9
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-1038-aws imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis.xyz.service:6379/0
```

**Comment by thedrow** [comment]
This is indeed a bug.
Thank you!
