### ISSUE TITLE
How to define periodic_task in v5.x

### ISSUE THREAD

**Issue by anuj9196** [celery/celery#6707]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

My Django application has lots of periodic tasks defined in different applications. 
In the previous version of Celery (v4.x), I used to define the periodic task like
```
from celery.task import periodic_task

@periodic_task(name='authentication.periodic_task.clear_refresh_token', run_every=timedelta(days=1))
def clear_refresh_token():
    pass
```

After the removal of the `periodic_task` decorator from v5.x, it is unclear how to define the auto-discoverable periodic tasks.

From the period task documentation https://docs.celeryproject.org/en/4.4.0/userguide/periodic-tasks.html#entries, It requires the `app` module to define the signal under which the periodic tasks has to be registered.

This is fine when the periodic tasks are defined in the root module (main application module), but what for the other module?

Also previously, it was easy to define the periodic tasks by using the decorator, and thus have the flexibility to define periodic tasks to any method, as per the new update, do I need to create separated `shared_task` first and then register them as a periodic task under the signal receiver?

# Suggestions

**Comment by thedrow** [comment]
The easiest way to define periodic tasks in Celery 5.x is by using the [beat_schedule](https://docs.celeryproject.org/en/4.4.0/userguide/configuration.html#std:setting-beat_schedule) setting.

**Comment by anuj9196** [comment]
@thedrow and the `beat_schedule` will be defined in the base `celery.py` file in Django's main application module and for every other application, I'll have to define each task in the `celery.py` file. 

So, let's say I have 100 periodic tasks across the applications, I will have to define all tasks in a single file `celery.py` under the `beat_schedule`.

How the auto_discover feature helps in the periodic task then?

**Comment by thedrow** [comment]
It doesn't other than the fact that it discovers the tasks and registers them with Celery.

**Comment by eredotpkfr** [comment]
As I understand, I was write some code may be you can use it. 

#### You can override `on_bound` method
You can override `on_bound` method in `Task` class. So `on_bound` method called when the task is bound to an app. You can schedule your tasks there.

Here is the source code of celery 5.0.5: https://github.com/celery/celery/blob/master/celery/app/task.py#L347
In celery 4.4.7 `on_bound` method like this: https://github.com/celery/celery/blob/v4.4.7/celery/task/base.py#L258

```python
#!/usr/bin/python3

from celery import Task, Celery

celery = Celery(
    broker='redis://localhost:6379/0',
    backend = 'redis://localhost:6379/0'
)

class MyTask(Task):

    @classmethod
    def on_bound(cls, app):
        app.conf.beat_schedule[cls.name] = {
            'task': cls.name,
            'schedule': cls.run_every,
            'args': (),
            'kwargs': {},
            'options': cls.options or {},
            'relative': cls.relative,
        }

@celery.task(base=MyTask, run_every=2, options={}, relative=False)
def test_task_1():
    print('foo')

@celery.task(base=MyTask, run_every=3, options={}, relative=False)
def test_task_2():
    print('bar')


#
# `celery -A main worker -l INFO -B`
#
 
```

#### Also you can use metaclass for class based tasks
```python
#!/usr/bin/python3

from celery import Task, Celery

celery = Celery(
	broker='redis://localhost:6379/0',
	backend = 'redis://localhost:6379/0'
)

class MyMeta(type):

	def __new__(cls, clsname, bases, attrs):
		bases = (*bases, MyTask)

		class_ = super().__new__(cls, clsname, bases, attrs)
		celery.register_task(class_())

		return class

class TestTask(metaclass=MyMeta):

	name = 'test_task_2'
	run_every = 3 # seconds
	options = {}
	relative = False

	def run(self):
		print('bar')


#
# `celery -A main worker -l INFO -B`
#
```

I hope it will helped. Ty

**Comment by devanghingu** [comment]
Nice explaination. i got too much idea from this. 
i have 1 question, where i can learn celery architecture?

**Comment by thedrow** [comment]
Unfortunately, the internal docs are very much incomplete.
@devanghingu Feel free to contribute in that area.
