### ISSUE TITLE
How to make subtasks(queue) of celery tasks in celery-5.0.5?

### ISSUE THREAD

**Issue by divyanshugit** [celery/celery#6716]
I am building a system where I activated multiple features at a time with the help of `Celery.Tasks`
But with time I have updated the system and now features have sub-features. So, I wanted to make the subtasks(queue) of celery tasks. 
Problem:
How to make subtasks(queue) of celery tasks in celery-5.0.5 cause I am unable to find this feature in this version?

**Comment by thedrow** [comment]
I'm not sure what you mean by subtasks queue.
In any case, the issue tracker is not the place to ask questions.
We have a mailing list and you can use StackOverflow to ask questions.

**Comment by divyanshugit** [comment]
I am so sorry for this. I was just looking for the answer
