### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by guettli** [celery/celery#6717]
I guess there is typo in the documentation:

![image](https://user-images.githubusercontent.com/414336/114084564-9d8f1c80-98b0-11eb-90b2-94181bb95b06.png)

URL: https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend

**Comment by auvipy** [comment]
you can check the codes to be sure

**Comment by guettli** [comment]
@auvipy I don't understand your comment.

I see two cases:

case1: there is a typo

case2: there is no typo. Nevertheless I think this looks strange and confuses new users. Hence, it makes sense to update the docs.

Since I am new to celery, I am not the right person to update the docs.

**Comment by thedrow** [comment]
CELERY_RESULT_BACKEND is what appears in the docs. I'm not sure where you see the typo.
I'm going to close this. If I missed something, please comment and we'll reopen.
![image](https://user-images.githubusercontent.com/48936/114303072-cee83200-9ad4-11eb-898d-2c31a9605966.png)
