### ISSUE TITLE
task results disappeared itself with Redis backend

### ISSUE THREAD

**Issue by labbbirder** [celery/celery#6719]
I cannot understand what it is happening that the result stored in Redis always automatically deleted.With this problem, I cannot get result by AsyncResult, but the result can be seen in flower.(for some reason, it's not convenient for me to use flower)

I am sure that I have configured Redis as the backend correctly, and I am using the latest stabled version of Celery+Redis+Flower.

I want to persistent any of my results which comes from heavy job,So I gived a big number for `result_expire`,and I can confirm the number by typing `ttl <task_result>` in Redis .
However, the task results disappeared in one day even if ttl has a positive big value.

what should I do to ensure the availability of `AsyncResult(task-id)`?
should I implement the result-persistent function manually?

**Comment by thedrow** [comment]
This is not likely to be Celery's fault.
Redis is usually configured as an LRU cache.
If you have too many keys in memory and you're reaching the maximum configured capacity, Redis will evict some of the keys that haven't been used for a long period of time.

This is done using the `maxmemory-policy` configuration setting for Redis. Please refer to their [documentation](https://raw.githubusercontent.com/redis/redis/6.0/redis.conf) for details.
