### ISSUE TITLE
config_from_object not working

### ISSUE THREAD

**Issue by lgamtj** [celery/celery#6725]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: celery:5.1.0b1 (singularity)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.0b1 (singularity) kombu:5.1.0b1 py:3.9.2
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Darwin arch:64bit
            kernel version:20.3.0 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

backend: 'amqp://guest:********@test//'
broker: 'redis://test/'
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

config_from_object work correctly.
# Actual Behavior

I want to use config_from_object to load my configurations from a python module, but it seems not work, and get the output:
![image](https://user-images.githubusercontent.com/18317103/114701303-36acb000-9d55-11eb-8dc6-82f86885cddc.png)
I define broker and backend in celeryconfig.py:
backend = 'amqp://guest:guest@test//'. # test is hostname, == 127.0.0.1
broker = 'redis://test/'

It works fine if I give the broker and backend directly while define celery instance.

**Comment by auvipy** [comment]
backend: 'amqp://guest:********@test//' is removed you can try other result backends like rpc

**Comment by lgamtj** [comment]
Yes, I change the broker and backend, but I still get the same error.
![image](https://user-images.githubusercontent.com/18317103/114706436-8a21fc80-9d5b-11eb-9a83-bea33f90cab4.png)
![image](https://user-images.githubusercontent.com/18317103/114706476-97d78200-9d5b-11eb-9f60-17a4c01a2f99.png)

The celery always use the localhost rather than test.

**Comment by lgamtj** [comment]
Sorry, I mad a mistake.

In the celeryconfig.py, I write the wrong broker and backend variables. It should be broker_url and result_backend.
