### ISSUE TITLE
Is there a way to redirect to a web page on_success after a celery tasks completes successfully? It would be very kind of you if you can help.

### ISSUE THREAD

**Issue by rajdeepmondal1** [celery/celery#6728]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by thedrow** [comment]
Please avoid asking for help with implementation of tasks on our issue tracker.
You can use the mailing list, IRC or StackOverflow to do so.

The answer would be to wait for the task to complete in the view and return 301 redirect or something.
