### ISSUE TITLE
Result object for groups containing chords which have a chain as their body time out

### ISSUE THREAD

**Issue by maybe-sybr** [celery/celery#6734]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case
This is the guts of the integration test I'm going to put up in #6733 :

<details>
<p>

```python
child_chord = chord(identity.si(42), chain((identity.s(), )))
group_sig = group((child_chord, ))
res = group_sig.delay()
res.get(timeout=ARBITRARY)
```

</p>
</details>

# Expected Behavior
 * result object should be able to be gotten

# Actual Behavior
 * `res.get()` raises `TimeoutError` no matter how long you set your timeout value (AFAICT)
 * A subsequent call to `res.get()` gets the result properly since the task(s) do run and by that time the results have probably landed

**Comment by maybe-sybr** [comment]
Discovered while experimenting with tests for #6721 in #6733. #6733 should land an xfailing test for this issue.

I think this might be due to the promise in the `GroupResult` not being fulifled since the chain has to be re-delayed from the serialised request stored as the chord's body. If that's the case then this issue is tangentially related to #6411 but would need to be solved in some other way.

My gut feel is that we might want to add a final check prior to allowing a timeout to bubble up, to see if the results we were waiting for have actually landed or if we truly did timeout.

**Comment by maybe-sybr** [comment]
I wonder if #6746 will fix this...

**Comment by auvipy** [comment]
I guess we can close this now or push to 5.2.x milestone

**Comment by auvipy** [comment]
will re assign to 5.2.x in case it isnt fixed properly.

**Comment by dobosevych** [comment]
What should be expected behavior? The test is marked still by xfailed.
