### ISSUE TITLE
“Load task modules from all registered Django app configs”

### ISSUE THREAD

**Issue by aruseni** [celery/celery#6738]
Hey, I think this phrase should be changed.

https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

```
# Load task modules from all registered Django app configs.
app.autodiscover_tasks()
```

We actually load the “tasks” modules from the apps themselves.

In other words, app configs do not have “tasks” modules, apps do.

So it would probably be better to say precisely that:

_Load task modules from all registered Django apps._

**Comment by auvipy** [comment]
let's change it. need not to open issue for this type of tiny changes in docs

**Comment by aruseni** [comment]
Sure. Just wanted any of you guys to confirm. Thanks.
