### ISSUE TITLE
Ability to customize `Received task` message

### ISSUE THREAD

**Issue by daveisfera** [celery/celery#6756]
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary
Currently `LOG_SUCCESS` and friends allows customizing the messages, but `Received task` is fixed. It would be good for this to be customizable and include the same values in `extra` (i.e. use `celery.app.trace.info` rather than `logging.info`). I was thinking something like this:
```
info('Received task: %s', {
    'name': req.name,
    'id': req.id,
})
```

# Design

## Architectural Considerations
Should be a non-breaking change that only adds a customization point

## Proposed Behavior
Add `LOG_RECEIVED` so it can be customized as well

## Proposed UI/UX
N/A

## Diagrams
N/A

## Alternatives
None that I can think of

**Comment by thedrow** [comment]
Pull requests are welcome!
