### ISSUE TITLE
Kwargs are nested multiple times

### ISSUE THREAD

**Issue by reibuildots** [celery/celery#6764]
# Checklist
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings
**Celery version**: 5.0.5 (singularity)
<details>
<summary><b><code>celery report</code> Outputsoftware -> celery:5.0.5 (singularity) kombu:5.0.2 py:3.7.7
            billiard:3.6.3.0 py-amqp:5.0.2
platform -> system:Darwin arch:64bit
            kernel version:20.3.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:******

ABSOLUTE_URL_OVERRIDES: {
 }
ADMINS: []
ALLOWED_HOSTS: ['*']
APPEND_SLASH: False
AUTHENTICATION_BACKENDS: {'auth.auth0backend.Auth0',
 'django.contrib.auth.backends.ModelBackend'}
AUTH_PASSWORD_VALIDATORS: '********'
AUTH_USER_MODEL: 'users.CustomUser'
BASE_DIR: '*******'
BROKER_ADDRESS: None
BROKER_TYPE: None
CACHES: {
 'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}
CACHE_MIDDLEWARE_ALIAS: 'default'
CACHE_MIDDLEWARE_KEY_PREFIX: '********'
CACHE_MIDDLEWARE_SECONDS: 600
CACHE_TIMEOUT: 345600
CELERY_ACCEPT_CONTENT: ['pickle', 'json']
CELERY_BROKER_TRANSPORT_OPTIONS: {
 'visibility_timeout': 172800}
CELERY_IMPORTS: ['******.orchestrator.tasks',
 '******.positioning_pipeline.pipeline_tasks',
 '******.positioning_pipeline.tasks_consumers',
 '******.services_settings.celery_commands']
CELERY_RESULT_BACKEND: '******'
CELERY_RESULT_CHORD_RETRY_INTERVAL: 0.5
CELERY_RESULT_EXTENDED: True
CELERY_RESULT_SERIALIZER: 'json'
CELERY_TASK_QUEUES: [<unbound Queue celery -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue renderer_tasks -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue small_tasks -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue medium_tasks -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue big_tasks -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue users_tasks -> <unbound Exchange ''(direct)> -> >]
CELERY_TASK_ROUTES: [<bound method Router.route_task of <class '******.services_settings.celery_routing.Router'>>]
CELERY_TASK_SERIALIZER: 'pickle'
CELERY_TASK_TRACK_STARTED: True
CELERY_WORKER_CONCURRENCY: 1
CELERY_WORKER_LOG_FORMAT: '%(message)s'
CELERY_WORKER_MAX_MEMORY_PER_CHILD: 3145728
CELERY_WORKER_PREFETCH_MULTIPLIER: 1
CORS_ALLOW_CREDENTIALS: True
CORS_ORIGIN_ALLOW_ALL: True
CORS_URLS_REGEX: '/api/.*/.*-image/.*'
CSRF_COOKIE_AGE: 31449600
CSRF_COOKIE_DOMAIN: None
CSRF_COOKIE_HTTPONLY: False
CSRF_COOKIE_NAME: 'csrftoken'
CSRF_COOKIE_PATH: '/'
CSRF_COOKIE_SAMESITE: 'Lax'
CSRF_COOKIE_SECURE: False
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS: []
CSRF_USE_SESSIONS: False
DATABASES: {
    'default': {   'ATOMIC_REQUESTS': False,
                   'AUTOCOMMIT': True,
                   'CONN_MAX_AGE': 0,
                   'ENGINE': 'django.db.backends.sqlite3',
                   'HOST': '',
                   'NAME': '******',
                   'OPTIONS': {},
                   'PASSWORD': '********',
                   'PORT': '',
                   'TEST': {   'CHARSET': None,
                               'COLLATION': None,
                               'MIGRATE': True,
                               'MIRROR': None,
                               'NAME': None},
                   'TIME_ZONE': None,
                   'USER': ''}}
DATABASE_INFO_TO_USE: {
    'ATOMIC_REQUESTS': False,
    'AUTOCOMMIT': True,
    'CONN_MAX_AGE': 0,
    'ENGINE': 'django.db.backends.sqlite3',
    'HOST': '',
    'NAME': '******',
    'OPTIONS': {},
    'PASSWORD': '********',
    'PORT': '',
    'TEST': {   'CHARSET': None,
                'COLLATION': None,
                'MIGRATE': True,
                'MIRROR': None,
                'NAME': None},
    'TIME_ZONE': None,
    'USER': ''}
DATABASE_ROUTERS: '********'
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS: 1000
DATETIME_FORMAT: 'N j, Y, P'
DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M']
DATE_FORMAT: 'N j, Y'
DATE_INPUT_FORMATS: ['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG: True
DEBUG_PROPAGATE_EXCEPTIONS: False
DEBUG_TOOLBAR_CONFIG: {
 'SHOW_TOOLBAR_CALLBACK': '******.settings.show_toolbar'}
DECIMAL_SEPARATOR: '.'
DEFAULT_CHARSET: 'utf-8'
DEFAULT_EXCEPTION_REPORTER: 'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL: 'webmaster@localhost'
DEFAULT_HASHING_ALGORITHM: 'sha256'
DEFAULT_INDEX_TABLESPACE: ''
DEFAULT_TABLESPACE: ''
DISALLOWED_USER_AGENTS: []
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST: 'localhost'
EMAIL_HOST_PASSWORD: '********'
EMAIL_HOST_USER: ''
EMAIL_PORT: 25
EMAIL_SSL_CERTFILE: None
EMAIL_SSL_KEYFILE: '********'
EMAIL_SUBJECT_PREFIX: '[Django] '
EMAIL_TIMEOUT: None
EMAIL_USE_LOCALTIME: False
EMAIL_USE_SSL: False
EMAIL_USE_TLS: False
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
FILE_UPLOAD_HANDLERS: ['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
FILE_UPLOAD_PERMISSIONS: 420
FILE_UPLOAD_TEMP_DIR: None
FIRST_DAY_OF_WEEK: 0
FIXTURE_DIRS: []
FORCE_SCRIPT_NAME: None
FORMAT_MODULE_PATH: None
FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS: []
INSTALLED_APPS: ['social_django',
 '******',
 '******',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'rest_framework',
 'debug_toolbar',
 '******.django_celery_results']
INTERNAL_IPS: ['127.0.0.1']
IS_PRODUCTION_OR_DEMO: False
IS_REAL_PRODUCTION: False
JWT_AUTH: {
    'JWT_ALGORITHM': 'RS256',
    'JWT_AUDIENCE': '******',
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_ISSUER': '******',
    'JWT_PAYLOAD_GET_USERNAME_HANDLER': 'auth.auth0user.jwt_get_username_from_payload_handler',
    'JWT_PUBLIC_KEY': '********'}
LANGUAGES: [('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ar-dz', 'Algerian Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('hy', 'Armenian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('ig', 'Igbo'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('ky', 'Kyrgyz'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('tg', 'Tajik'),
 ('th', 'Thai'),
 ('tk', 'Turkmen'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('uz', 'Uzbek'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI: ['he', 'ar', 'ar-dz', 'fa', 'ur']
LANGUAGE_CODE: 'en-us'
LANGUAGE_COOKIE_AGE: None
LANGUAGE_COOKIE_DOMAIN: None
LANGUAGE_COOKIE_HTTPONLY: False
LANGUAGE_COOKIE_NAME: 'django_language'
LANGUAGE_COOKIE_PATH: '/'
LANGUAGE_COOKIE_SAMESITE: None
LANGUAGE_COOKIE_SECURE: False
LOCALE_PATHS: []
LOGGING: {
 }
LOGGING_CONFIG: 'logging.config.dictConfig'
LOGIN_REDIRECT_URL: '/'
LOGIN_URL: '/login/auth0'
LOGOUT_REDIRECT_URL: '******'
MANAGERS: []
MAX_AGE_FOR_DB_CONNECTION_SECONDS: 300
MAX_CACHE_ENTRIES: 1000
MEDIA_ROOT: ''
MEDIA_URL: '/'
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE: ['data.middleware.******',
 'data.routers.RouterMiddleware',
 'data.middleware.log_performance_middleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'data.middleware.bind_site_username_middleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'data.middleware.******']
MIGRATION_MODULES: {
 }
MONTH_DAY_FORMAT: 'F j'
NUMBER_GROUPING: 0
OPTIONAL_CACHES: {
    'dummycache': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'},
    'loccache': {   'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                    'OPTIONS': {'MAX_ENTRIES': 1000},
                    'TIMEOUT': 345600},
    'memcached': {   'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
                     'LOCATION': None,
                     'OPTIONS': {'server_max_value_length': 33554432},
                     'TIMEOUT': 345600}}
OPTIONAL_DATABASES: {
    'sqlite': {   'ATOMIC_REQUESTS': False,
                  'AUTOCOMMIT': True,
                  'CONN_MAX_AGE': 0,
                  'ENGINE': 'django.db.backends.sqlite3',
                  'HOST': '',
                  'NAME': '******',
                  'OPTIONS': {},
                  'PASSWORD': '********',
                  'PORT': '',
                  'TEST': {   'CHARSET': None,
                              'COLLATION': None,
                              'MIGRATE': True,
                              'MIRROR': None,
                              'NAME': None},
                  'TIME_ZONE': None,
                  'USER': ''},
    'sqlite-tests': {   'ENGINE': 'django.db.backends.sqlite3',
                        'NAME': ':memory:'}}
PASSWORD_HASHERS: '********'
PASSWORD_RESET_TIMEOUT: '********'
PASSWORD_RESET_TIMEOUT_DAYS: '********'
PREPEND_WWW: False
PROJECT_DIR: '******'
REST_FRAMEWORK: {
    'DEFAULT_AUTHENTICATION_CLASSES': (   'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
                                          'rest_framework.authentication.SessionAuthentication',
                                          'rest_framework.authentication.BasicAuthentication'),
    'DEFAULT_PERMISSION_CLASSES': (   'data.******.utils.views_utils.ProjectViewerEndpoint',),
    'DEFAULT_RENDERER_CLASSES': [   'rest_framework.renderers.JSONRenderer',
                                    'rest_framework.renderers.BrowsableAPIRenderer'],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning'}
ROOT_URLCONF: '******.urls'
SECRET_KEY: '********'
SECURE_BROWSER_XSS_FILTER: True
SECURE_CONTENT_TYPE_NOSNIFF: False
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
SECURE_HSTS_PRELOAD: False
SECURE_HSTS_SECONDS: 0
SECURE_PROXY_SSL_HEADER: None
SECURE_REDIRECT_EXEMPT: []
SECURE_REFERRER_POLICY: 'same-origin'
SECURE_SSL_HOST: None
SECURE_SSL_REDIRECT: False
SELF_ADDRESS: 'http://localhost:7000'
SERVER_EMAIL: 'root@localhost'
SESSION_CACHE_ALIAS: 'default'
SESSION_COOKIE_AGE: 1209600
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_NAME: '******'
SESSION_COOKIE_PATH: '/'
SESSION_COOKIE_SAMESITE: 'Lax'
SESSION_COOKIE_SECURE: False
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
SESSION_FILE_PATH: None
SESSION_SAVE_EVERY_REQUEST: False
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE: '******.settings'
SHORT_DATETIME_FORMAT: 'm/d/Y P'
SHORT_DATE_FORMAT: 'm/d/Y'
SHOULD_PROXY_AUTH_TABLES: False
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS: []
SOCIAL_AUTH_AUTH0_AUDIENCE: '******'
SOCIAL_AUTH_AUTH0_DOMAIN: '******'
SOCIAL_AUTH_AUTH0_JWKS: ('{"keys": [{"alg": "RS256", "kty": "RSA", '
 '"use": "sig", "n": '
 '"******", '
 '"e": "AQAB", "kid": '
 '"******", '
 '"x5t": '
 '"******", '
 '"x5c": '
 '["******"]}, '
 '{"alg": "RS256", "kty": "RSA", "use": "sig", '
 '"n": '
 '"******", '
 '"e": "AQAB", "kid": "kd5L2gFzHj_oIGFj3dAQb", '
 '"x5t": "******", "x5c": '
 '["******"]}]}')
SOCIAL_AUTH_AUTH0_KEY: '********'
SOCIAL_AUTH_AUTH0_SCOPE: ['openid', 'profile']
SOCIAL_AUTH_AUTH0_SECRET: '********'
SOCIAL_AUTH_PIPELINE: 
    ('social_core.pipeline.social_auth.social_details',
 'social_core.pipeline.social_auth.social_uid',
 'social_core.pipeline.social_auth.social_user',
 'social_core.pipeline.user.get_username',
 'social_core.pipeline.social_auth.associate_by_email',
 'social_core.pipeline.user.create_user',
 'social_core.pipeline.social_auth.associate_user',
 'social_core.pipeline.social_auth.load_extra_data',
 'social_core.pipeline.user.user_details')
SOCIAL_AUTH_REDIRECT_IS_HTTPS: False
*****: '******'
STATICFILES_DIRS: []
STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT: '******'
STATIC_URL: '/backend_static/'
TEMPLATES: [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS: []
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR: ','
TIME_FORMAT: 'P'
TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE: 'UTC'
USE_I18N: False
USE_L10N: False
USE_THOUSAND_SEPARATOR: False
USE_TZ: True
USE_X_FORWARDED_HOST: True
USE_X_FORWARDED_PORT: True
WSGI_APPLICATION: '******.wsgi.application'
X_FRAME_OPTIONS: 'DENY'
YEAR_MONTH_FORMAT: 'F Y'
is_overridden: <bound method Settings.is_overridden of <Settings "******.settings">>
deprecated_settings: None
:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies
* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages
<details>
<summary><b><code>pip freeze</code> Output:amqp==5.0.6
celery==5.0.5
pickleshare==0.7.5</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies
<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case
<details>
<p>
import pickle
from celery.canvas import chord
from io import BytesIO

dict(pickle.load(BytesIO(pickle.dumps(chord([])))))
</p>
</details>

# Expected Behavior
I expect that after pickle load I will get the same object as I dumped

# Actual Behavior
dumped:
{'task': 'celery.chord',
 'args': (),
 'kwargs': {'kwargs': {}, 'header': [], 'body': None},
 'options': {},
 'subtask_type': 'chord',
 'immutable': False,
 'chord_size': None}
 
 loaded:
 {'task': 'celery.chord',
 'args': (),
 'kwargs': {'kwargs': {'kwargs': {}}, 'header': [], 'body': None},
 'options': {'chord_size': None},
 'subtask_type': 'chord',
 'immutable': False,
 'chord_size': None}

kwargs added multiple times.

**Comment by maybe-sybr** [comment]
We had a similar issue which came up a while ago relating to an exponential slowdown in task serialisation which I worked out was caused by this - #5286. I had planned to come back to that once I had some more time so this report comes at a useful moment. I'll re-assign myself to that one to track the work.

**Comment by maybe-sybr** [comment]
Thanks for the report, btw @reibuildots . If you have any ideas on a fix, feel free to put them here or make a PR :) otherwise I'll try to find time to dig into this soon :TM:

**Comment by maybe-sybr** [comment]
Having spent some time this morning looking into #5286, I am pretty sure that this is a separate issue which could be contributing but it unlikely to be the primary cause of slowness there. So I think I'll look into how kwargs are treated during serialisation of canvas types when I have some free time.

**Comment by rainbowtux** [comment]
@reibuildots could you test again against the master branch? Looks to be a duplicate of #6810 #6959 which I wrote a PR for that is now accepted. In our software it fixes the issues.

**Comment by reibuildots** [comment]
it looks good, Thank you!

`c = chord([])
for i in range(10):
     c = pickle.load(BytesIO(pickle.dumps(c)))
print(dict(c))`


Results on master:
{'task': 'celery.chord', 'args': (), 'kwargs': {'kwargs': {}, 'header': [], 'body': None}, 'options': {}, 'subtask_type': 'chord', 'immutable': False}


Results on current version:
{'task': 'celery.chord', 'args': (), 'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {'kwargs': {}}}}}}}}}}}, 'header': [], 'body': None}, 'options': {}, 'subtask_type': 'chord', 'immutable': False}

**Comment by auvipy** [comment]
> @reibuildots could you test again against the master branch? Looks to be a duplicate of #6810 #6959 which I wrote a PR for that is now accepted. In our software it fixes the issues.

closing in favor of this. thanks both for cross check and the contributed fix! <3
