### ISSUE TITLE
AsyncResult memory leak on task producers 

### ISSUE THREAD

**Issue by hpurohit-pp** [celery/celery#6772]
AsyncResult memory leak on task producers when producers retrieves task results from redis results backend. We are using redis as broker and results backend. 

This is issue is similar to https://github.com/celery/celery/pull/4839. I have attempted to backport this fix: https://github.com/celery/celery/pull/5332 with vine 1.3 + celery 4.2.2. However, leak of AsyncResult objects continues to happen for task that retrieves the results from redis backend. Tasks that ignores the results do not exhibit this leak when changes are backported from https://github.com/celery/celery/pull/5332. Only patch that worked for me was removing __del__ method completely: https://github.com/celery/celery/blame/v4.2.2/celery/result.py#L382
 
Celery version: 4.2.2
Kombu: 4.2.2
Vine: 1.3.0
Python: 2.7

I have attempted to reproduce the issue with celery 4.1.1 but it works on that version.

# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ x] I have included the contents of ``pip freeze`` in the issue.
- [x ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

**Comment by auvipy** [comment]
closing as its on a EOL version. will reopen if still reproduced in 5.2
