### ISSUE TITLE
Release 5.0.6

### ISSUE THREAD

**Issue by thedrow** [celery/celery#6783]
Version: 5.0.6
Release PR: 

This release should only contain backported bug fixes to the CLI in case our users don't wish to upgrade to 5.1 at the time being.

# Checklist

- [ ] Release PR drafted
- [ ] Release PR reviewed
- [ ] The master branch build passes

    [![Build Status](https://github.com/celery/celery/actions/workflows/python-package.yml/badge.svg)](https://github.com/celery/celery/actions/workflows/python-package.yml)
- [ ] Release Notes
- [ ] What's New

# Release Blockers

# Potential Release Blockers

**Comment by auvipy** [comment]
do we maintain the 5.0 branch to backport?

**Comment by thedrow** [comment]
I created it today.
I backported all the CLI bug fixes.

I'd like someone to review them before I release them.
