### ISSUE TITLE
Revoking a task causes state to be RETRY

### ISSUE THREAD

**Issue by djungic** [celery/celery#6793]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

Issue #6158 is about REVOKED states not always being reflected, but I believe this issue is more specific (e.g. the state should not be RETRY).

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:  5.1.0 (sun-harmonics)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
$ celery -A celery_revoke_retry report

software -> celery:5.1.0 (sun-harmonics) kombu:5.1.0 py:3.7.9
            billiard:3.6.4.0 redis:3.5.0
platform -> system:Linux arch:64bit, ELF
            kernel version:3.10.0-1160.11.1.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://localhost:6379/0'
deprecated_settings: None
worker_concurrency: 1
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python

import threading
import time
from celery import Celery

app = Celery('celery_revoke_retry', broker='redis://localhost:6379/0', backend='redis://localhost:6379/0')
app.conf.update(worker_concurrency=1)

@app.task
def sleep(sleep_time):
    time.sleep(sleep_time)

def main():
    argv = ['--app=celery_revoke_retry', 'worker', '--loglevel=DEBUG']
    threading.Thread(target=app.worker_main, args=(argv,)).start()
    time.sleep(5)
    print('Celery should be up now')

    r = sleep.s(sleep_time=60).apply_async()
    # Note: waiting for the task to start before revoking it will still cause result.state == RETRY
    r.revoke(terminate=True)

    for _ in range(5):
        print(f"State is: {r.state}")
        time.sleep(1)

if __name__ == '__main__':
    main()
```

</p>
</details>

# Expected Behavior
After revoking the task, the expectation is that the state will not be RETRY. The state should be REVOKED, but my understanding is that there are other known issues that cause an un-received task to not have state=REVOKED after it is revoked. 

Note that even if the code sample above waiting for the task to be started before executing the revoke, the state will still become RETRY.

This appears to be a Celery 5.x regression. The previous 4.x version I was on did not exhibit this behaviour.

# Actual Behavior

The code above will print the following:

```
State is: PENDING
Terminating 289825dd-4c07-4018-907a-9f9763e941fe (Signals.SIGTERM)
State is: RETRY
State is: RETRY
State is: RETRY
State is: RETRY
```

Note that the state should be REVOKED, not RETRY. I believe the previous behaviour was that a task that was never received would stay PENDING if it is revoked.

**Comment by djungic** [comment]
The state only becomes `RETRY` when `terminate=True` is supplied to `revoke`. Otherwise the state does not become `REVOKED` and just stays the same (e.g. `PENDING` or `STARTED`, depending on `task_track_started`), even when the task is running while it is revoked.

**Comment by thedrow** [comment]
Does this reproduce in 5.0.5?
If it doesn't, it could be related to the changes in #6654.

**Comment by djungic** [comment]
It does not reproduce in 5.0.5. The example script prints `REVOKED`, as expected.

**Comment by leomermelstein** [comment]
Seems line 526 here might be the culprit:
(https://github.com/celery/celery/commit/934a2271c1636364486eb737a598d224e5184cf8#diff-db65a0e57511553adc360b2e485e25b09e0768b47d76d4e48147ab99994dbbb9R526)
```
            if self.message.channel.connection and not self._already_revoked:
                # This is a special case where the process
                # would not have had time to write the result.
                self._announce_revoked(
                    'terminated', True, str(exc), False)
            elif not self._already_cancelled:  # <-- **Cancelled after _already_revoked!**
                self._announce_cancelled()
```

Should this be:
```
            if self.message.channel.connection: #  <-- **Connection alive**
                if not self._already_revoked:
                    # This is a special case where the process
                    # would not have had time to write the result.
                    self._announce_revoked(
                        'terminated', True, str(exc), False)
            elif not self._already_cancelled:  # <-- **No connection**
                self._announce_cancelled()
```

**Comment by auvipy** [comment]
> Seems line 526 here might be the culprit:

would you mind working for providing a possible fix?

**Comment by leomermelstein** [comment]
> would you mind working for providing a possible fix?

Opened pr https://github.com/celery/celery/pull/6812
