### ISSUE TITLE
IRC moved to libera.chat

### ISSUE THREAD

**Issue by dromer** [celery/celery#6811]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
Freenode is dead, so the IRC channel moved to irc.libera.chat - however the README still mentions freenode

# Suggestions
modify the README so that users can find the correct IRC channel

**Comment by thedrow** [comment]
@celery/core-developers We need to prioritize this.
I'm still +1 on Gitter with bridges to other clients.

**Comment by dromer** [comment]
> I'm still +1 on Gitter with bridges to other clients.
With "bridges" you mean a bot that copies messages back and forth?

Those ruin chat and I'm 100% against that.

**Comment by thedrow** [comment]
> > I'm still +1 on Gitter with bridges to other clients.
> 
> With "bridges" you mean a bot that copies messages back and forth?
> Those ruin chat and I'm 100% against that.
> 
> Actually I think gitter is all based on Matrix these days, so you can create a Matrix channel that actually bridges (as in connects the network and its users) to libera.chat and gitter (afaik)
> 
> Please don't use a bot, you will lose people if that's how you think chat should work.

No, not a bot. Gitter has a relay with IRC.
I didn't know they are based on matrix now.

**Comment by dromer** [comment]
What do you mean with relay?

Gitter used to have an irc-gateway you could connect to with an irc client, but I don't think that's still the case.

**Comment by xirdneh** [comment]
@dromer is correct. I looked into this a few months back, and Gitter doesn't act as a bridge.

I vote for keeping the IRC channel and Google forum. Then use Gitter for contributor's chat.

We get the most traffic on the forum.

**Comment by xirdneh** [comment]
I'll login tomorrow and send you a DM.

**Comment by graingert** [comment]
@dromer https://gitter.im/celery/celery and #celery on libera are now bridged

**Comment by thedrow** [comment]
Thank you everyone!
