### ISSUE TITLE
No statement about version interoperability in docs?

### ISSUE THREAD

**Issue by jreuter60** [celery/celery#6820]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

I could not find any statement in the documentation (or bug reports) about whether or not Celery supports interoperability across versions among the participants using a Celery queue.

Background: I am working on upgrading a development environment that has long been unmaintained.  It has a user component that distributes work through celery to 100+ workers.  I am upgrading the user component, including a newer Celery version (4,4,7) than the workers (3,1.26).  That almost works but not entirely; digging in internal structures shows "error" strings, the details of which are not pertinent to this request and I would have to dig through the Celery code and messages to understand them.  First I'll downgrade so all parts are using the same version to see if that fixes my problem.

What I really wanted to do was to see if Celery claims support for interoperability across versions. But I could not find anything in the documentation regarding cross-version interoperability or non-support of such a thing.  Because Celery enables distribution of work, it would be great if here was some interoperability across versions, but I cannot even determine if that is an intended part of the design.

# Suggestions

First, I'm just looking for a statement about support or non-support of interoperability across versions.  If it is supported, then something about the constraints about what versions can be mixed, e.g. it's ok across minor versions but not major versions.

Maybe this is documented somewhere, but I could not come up with any searches to find it.  This sort of thing does not lend itself to nice targeted searches.

**Comment by auvipy** [comment]
we are currently trying to following Semantic Versioning Scheme, in some release we didn't strictly follow though, but from v5.x streams its quite there. this was documented long ago.

**Comment by auvipy** [comment]
btw you should try 4.4.6 then 5.2.x
