### ISSUE TITLE
Celery task is not being created when called from browser

### ISSUE THREAD

**Issue by irshad-io** [celery/celery#6831]
Hi,
I am using the updated version of celery but I don't know why the task is not created when I call the function from the browser.
Here is the code

```
from flask import Flask, session
from celery import Celery
import logging

app = Flask(__name__)
app.secret_key = "asasdadasdaiuhuywe76"
mycelery = Celery(app.name)


mycelery.conf.update({
    'broker_url': 'filesystem://',
    'broker_transport_options': {
        'data_folder_in': 'app/broker/out',
        'data_folder_out': 'app/broker/out',
        'data_folder_processed': 'app/broker/processed'
    },

    'result_persistent': False,
    'task_serializer': 'json',
    'result_serializer': 'json',
    'accept_content': ['json']})

logger = logging.getLogger(__name__)

@mycelery.task(bind=True, name='codewriting')
def codewriting(self,code):
     with open('textfiles/readme.txt', 'w') as f:
     f.write(f'Current code is {code}')


app.route('/<string>')
def myfunction(string):
task = codewriting.delay(string)
return f"<h1>Task ID is { task }</h1>"

```

When I run flask from cmd and try to visit ```http://127.0.0.1:5000/newcode``` It doesn't create a task inside `app/broker/out` but when I run this code from IDE (PyCharm) by adding a new line after the above code as 
```
myfunction("newcode")
```
It creates a celery task inside the folder given. Why is the same thing not functioning when visited from the web?

**Comment by thedrow** [comment]
This is an issue tracker for Celery bugs.
This is not a Celery bug but a Flask usage question. The problem is probably there and the upgrade to a later version of Celery did not cause the issue.
You can verify by downgrading Celery and reproducing the same issue.
