### ISSUE TITLE
celery concurrency not working, need help

### ISSUE THREAD

**Issue by 0xaeff0** [celery/celery#6839]
Hi
I'm running celery on an ARM ec2 instance, 2 cores / 0.5gb RAM, and i am not able to run a celery worker with concurrency set to 15, i don't know why?

My tasks file (cel.py) file
```
from celery import Celery

app = Celery('cel', broker='redis://guest@localhost//')

@app.task
def hello():
    return 'hello world'
```
Running this command will lead to my CPU usage getting from 0 to 100% and the output below: celery -A cel worker --loglevel=INFO --concurrency 15
```
/usr/local/lib/python3.8/dist-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@ip-172-31-0-82 v4.2.0 (windowlicker)
---- **** ----- 
--- * ***  * -- Linux-5.4.0-1045-aws-aarch64-with-glibc2.29 2021-07-02 23:09:37
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         ce;:0xffff89d005e0
- ** ---------- .> transport:   redis://guest@localhost:6379//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 15 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . cel.hello

Killed
```

I don't understand why is this happening, i have a single worker and im assigning 15 threads to it, can someone explain why is this happening? And what could be a fix? The tasks themselves which i am willing to put are very simple and don't need a lot of CPU and RAM, but i just can't get to run 15 of them concurrently on celery

Thanks

**Comment by wangha81** [comment]
The concurrency count will be cpu count as default.
The EC2 instance maybe bursted with credit. Please check out your instance type which could be cpu bursted with extra credit.

**Comment by auvipy** [comment]
are you using celery 5.1.2? you should have use a template

**Comment by wangha81** [comment]
Yes 5.1.2. but no template

Follow the official you would learn it.

The process was killed. It maybe something to check like OS capacity, ec2 limited etc.

Maybe you could try set log level to debug for more information. (`--loglevel=DEBUG`). 
Or Check sys log for that process

**Comment by marrocksd** [comment]
Afaik you will have to use evenlet or gevent worker for async tasks.
The prefork worker with c=15 will simply uses 15 threads (you only have 2 in this case)

**Comment by 0xaeff0** [comment]
So after some investigation, i found out that the process kswapd0 is what's using all of the CPU resulting in this problem, more explanation regarding kswapd0 https://askubuntu.com/questions/259739/kswapd0-is-taking-a-lot-of-cpu#:~:text=81,programs%20to%20access%20information%20quickly.
So if i increase the RAM size, everything will be OK

But here is the thing, with evenlet / green threads, i can easily add a lot of workers without the need for more memory, i used this other python queue library https://github.com/coleifer/huey which supports greenlets and i was able to add 30 green threads just fine

Is there a way i can use green threads in celery?

**Comment by 0xaeff0** [comment]
Apologies for asking without taking a look at the documentation, ill go try this out now :)

**Comment by 0xaeff0** [comment]
My issue is fixed with using greenlets, thanks!!

**Comment by SnoozeFreddo** [comment]
> Afaik you will have to use evenlet or gevent worker for async tasks.
> The prefork worker with c=15 will simply uses 15 threads (you only have 2 in this case)

That's what i did, but Celery tells me that my function has never been awaited. I though Celery doesn't support async, but how do i combine await keywords and async stuff into Celery?

**Comment by marrocksd** [comment]
> > Afaik you will have to use evenlet or gevent worker for async tasks.
> > The prefork worker with c=15 will simply uses 15 threads (you only have 2 in this case)
> 
> That's what i did, but Celery tells me that my function has never been awaited. I though Celery doesn't support async, but how do i combine await keywords and async stuff into Celery?
> 
> I mean if i can't make use of that, why to run eventlet or gevent at all?

Celery doesn't support native asyncio and greenlet doesn't work like what you are thinking
Just write normal synchronous code (for example: requests.get) and gevent will run them on lightweight coroutines called greenlets.
Just like asyncio, greenlet is sequential and stack switching, so don't treat it like parallel ones

**Comment by SnoozeFreddo** [comment]
> Celery doesn't support native asyncio and greenlet doesn't work like what you are thinking
> Just write normal synchronous code (for example: requests.get) and gevent will run them on lightweight coroutines called greenlets.
> Just like asyncio, greenlet is sequential and stack switching, so don't treat it like parallel ones

Hey, this was exactly what i was looking for. I was wondering how to tell gevent to use my request module, because i've read in the docs how to do it and there they picked their own request library which was under

from eventlet.green.urllib.request 


Will a normal request (from the import request module) get automatically converted if i don't use the requests library in their own submodule?

**Comment by marrocksd** [comment]
> > Celery doesn't support native asyncio and greenlet doesn't work like what you are thinking
> > Just write normal synchronous code (for example: requests.get) and gevent will run them on lightweight coroutines called greenlets.
> > Just like asyncio, greenlet is sequential and stack switching, so don't treat it like parallel ones
> 
> Hey, this was exactly what i was looking for. I was wondering how to tell gevent to use my request module, because i've read in the docs how to do it and there they picked their own request library which was under
> 
> from eventlet.green.urllib.request
> 
> Will a normal request (from the import request module) get automatically converted if i don't use the requests library in their own submodule?

Yes, It's really confused that we don't know in advanced which modules are able to be converted, you will have to test. But yes in case of requests

**Comment by jerrychong25** [comment]
@mo08472 @marrocksd @wangha81 @SnoozeFreddo 

Hi all, 

I have one question to clarify on how to increase Celery concurrency using gevent.

My end faced issue that Celery concurrency always 1, regardless of how I increase cocurrency more than 1 in configuration via Python config file **(Not CLI method)**.

Do I missed out anythings?

Here is my Celery settings output (Output show that concurrency is 1):
```
 -------------- celery@project v4.4.2 (cliffs)
--- ***** -----
-- ******* ---- Linux-5.15.0-56-generic-x86_64-with-glibc2.29 2023-01-13 11:09:12
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         project:0x7fcd17b6caf0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
-------------- [queues]
```

Here is my configuration file:
```
from __future__ import absolute_import, unicode_literals

import os

from celery import Celery
from kombu import Queue
from celery.schedules import crontab

from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')

app = Celery('project', broker='redis://localhost:6379/0')

app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

app.conf.beat_schedule = {
    'task1': {
        'task': 'project.tasks.task1',
        'schedule': 1,
        # 'args': ()
    },
    'task2': {
        'task': 'project.tasks.task2',
        'schedule': 1,
        # 'args': ()
    }
}

app.conf.timezone = 'Asia/Singapore'
app.conf.task_default_queue = 'default'
app.conf.task_queues = (
    Queue('default', routing_key='task.#'),
    Queue('queue', routing_key='queue.#'),
)
app.conf.worker_pool = "gevent"
app.conf.update(
    worker_concurrency=50
)

app.config_from_object('django.conf:settings', namespace='CELERY')

app.autodiscover_tasks()
```

Thank you in advance!

**Comment by marrocksd** [comment]
> @mo08472 @marrocksd @wangha81 @SnoozeFreddo
> 
> Hi all,
> 
> I have one question to clarify on how to increase Celery concurrency using gevent.
> 
> My end faced issue that Celery concurrency always 1, regardless of how I increase cocurrency more than 1 in configuration via Python config file **(Not CLI method)**.
> 
> Do I missed out anythings?
> 
> Here is my Celery settings output (Output show that concurrency is 1):
> 
> ```
>  -------------- celery@project v4.4.2 (cliffs)
> --- ***** -----
> -- ******* ---- Linux-5.15.0-56-generic-x86_64-with-glibc2.29 2023-01-13 11:09:12
> - *** --- * ---
> - ** ---------- [config]
> - ** ---------- .> app:         project:0x7fcd17b6caf0
> - ** ---------- .> transport:   redis://localhost:6379/0
> - ** ---------- .> results:     disabled://
> - *** --- * --- .> concurrency: 1 (gevent)
> -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
> --- ***** -----
> -------------- [queues]
> ```
> 
> Here is my configuration file:
> 
> ```
> from __future__ import absolute_import, unicode_literals
> 
> import os
> 
> from celery import Celery
> from kombu import Queue
> from celery.schedules import crontab
> 
> from django.conf import settings
> 
> os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
> 
> app = Celery('project', broker='redis://localhost:6379/0')
> 
> app.config_from_object('django.conf:settings')
> app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
> 
> app.conf.beat_schedule = {
>     'task1': {
>         'task': 'project.tasks.task1',
>         'schedule': 1,
>         # 'args': ()
>     },
>     'task2': {
>         'task': 'project.tasks.task2',
>         'schedule': 1,
>         # 'args': ()
>     }
> }
> 
> app.conf.timezone = 'Asia/Singapore'
> app.conf.task_default_queue = 'default'
> app.conf.task_queues = (
>     Queue('default', routing_key='task.#'),
>     Queue('queue', routing_key='queue.#'),
> )
> app.conf.worker_pool = "gevent"
> app.conf.update(
>     worker_concurrency=50
> )
> 
> app.config_from_object('django.conf:settings', namespace='CELERY')
> 
> app.autodiscover_tasks()
> ```
> 
> Thank you in advance!

According to the doc.

worker_pool
Default: "prefork" (celery.concurrency.prefork:TaskPool).

Name of the pool class used by the worker.

Eventlet/Gevent
Never use this option to select the eventlet or gevent pool. You must use the [-P](https://docs.celeryq.dev/en/latest/reference/cli.html#cmdoption-celery-worker-P) option to celery worker instead, to ensure the monkey patches aren’t applied too late, causing things to break in strange ways.
