### ISSUE TITLE
I need to run a function on specific date, do I need celery?

### ISSUE THREAD

**Issue by AlenSci** [celery/celery#6850]
I usually use celery in my django project to run tasks. But, today I have very simple tasks that need to be run in specific dates. So, I thought it is not worth using celery now.
Instead I am using this function called `create_task`  is it safe doing it this way? can I depend on it to run forever? 
Also, as you can see `create_task` will create multiple instance of is `loop = asyncio.get_event_loop()`. Is it safe to reuse `create_task` or should I use one  instance of`loop = asyncio.get_event_loop()` and keep adding tasks to it
```
# my tasks management function
import asyncio

import datetime


async def wait_until(dt):
    # sleep until the specified datetime
    now = datetime.datetime.now()
    await asyncio.sleep((dt - now).total_seconds())


async def task(dt, coro):
    await wait_until(dt)
    return await coro


def create_task(myTask, task_date):
    loop = asyncio.get_event_loop()
    loop.create_task(task(task_date, myTask()))
    loop.run_forever()

```

```
# usage


def run_me():
    print('xx')

def test_run_at_time(self):
    create_task(run_me, datetime.datetime(2021, 7, 11, 0, 0))
    print('do it anyway')
```

**Comment by auvipy** [comment]
you can try celerybeat
