### ISSUE TITLE
Missing celery.task is not innocuous, breaks pydoc

### ISSUE THREAD

**Issue by ferdnyc** [celery/celery#6859]
In #6558 the lack of `celery.task` was closed as "not a bug", but because `task` is still in the `__all__` for the `celery` <s>module</s> package (in `celery/__init__.py`), among other things the missing module breaks `pydoc`:

```bash
$ python3 -m venv .
$ . ./bin/activate
$ python3 -m pip install celery
[...]
$ python3 -m pydoc celery
No module named 'celery.task'

$
```

Other introspection tools, not to mention freezing/packaging tools, will likely also be affected.

# Checklist

- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [X] I have included the contents of ``pip freeze`` in the issue.
- [X] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #6558

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.1.2 (sun-harmonics)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>
```sh
$ celery report
software -> celery:5.1.2 (sun-harmonics) kombu:5.0.2 py:3.9.6
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit, ELF
            kernel version:5.12.15-200.fc33.x86_64 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```
</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
billiard==3.6.4.0
celery==5.1.2
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
kombu==5.1.0
prompt-toolkit==3.0.19
pytz==2021.1
six==1.16.0
vine==5.0.0
wcwidth==0.2.5
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

```bash
$ python3 -m venv .
$ . ./bin/activate
$ python3 -m pip install celery
[...]
$ python3 -m pydoc celery
No module named 'celery.task'

$
```

# Expected Behavior

Module documentation is displayed

# Actual Behavior

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/6558#issuecomment-750281219 celery.task was removed so try new API

**Comment by ferdnyc** [comment]
@auvipy 

I understand that, the issue is not that the API has changed. As I tried to explain, the issue is that `task` is still listed in the package's module list:

https://github.com/celery/celery/blob/bb8030562752dbcd1d130a878f4a0326ad93fc02/celery/__init__.py#L28-L35

Having `task` listed there breaks introspection. Pydoc will try to scan `celery.task`, and when it cannot open the module, will abort with a hard error instead of displaying documentation.

**Comment by auvipy** [comment]
oh got it. that should be removed

**Comment by ferdnyc** [comment]
Actually, I'm wrong about the location of the problem, sorry. It's actually this mapping:

https://github.com/celery/celery/blob/ca489c6f7767ed796bce10400321fe08b4820c0c/celery/__init__.py#L164

Remove that, pydoc works again. (Removing it from `__all__` couldn't hurt either.)

Context for the above:
https://github.com/celery/celery/blob/ca489c6f7767ed796bce10400321fe08b4820c0c/celery/__init__.py#L149-L174

**Comment by auvipy** [comment]
ok cool. go ahead for a PR?

**Comment by ferdnyc** [comment]
Sure, will do.

There are also a few references to `celery.task` in the docstrings — the ones to `celery.task.base.Task` I assume can be replaced with just `celery.Task` (yes?), but I'm not 100% sure where to redirect ":class:`celery.task.DeleteExpiredTaskMetaTask`.".

Then there's this:
https://github.com/celery/celery/blob/bb8030562752dbcd1d130a878f4a0326ad93fc02/celery/local.py#L402-L404

Hopefully that method isn't actually called by anything.

**Comment by auvipy** [comment]
you can come with a half baked pr as well to kickstart
