### ISSUE TITLE
'False' will be ignored in Celery kwargs config

### ISSUE THREAD

**Issue by gundam78** [celery/celery#6865]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.1.2

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

celery@Guan-Johns-MacBook.local v5.1.2 (sun-harmonics)

macOS-10.15.7-x86_64-i386-64bit 2021-07-20 16:30:46

[config]
.> app:         tasks:0x10ccc9f40
.> transport:   redis://localhost:6379//
.> results:     disabled://
.> concurrency: 1 (prefork)
.> task events: ON

[queues]
.> celery           exchange=celery(direct) key=celery

[tasks]
  . tasks.add

[2021-07-20 16:30:46,948: INFO/MainProcess] Connected to redis://localhost:6379//
[2021-07-20 16:30:46,957: INFO/MainProcess] mingle: searching for neighbors
[2021-07-20 16:30:47,994: INFO/MainProcess] mingle: all alone
[2021-07-20 16:30:48,014: INFO/MainProcess] celery@Guan-Johns-MacBook.local ready.

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.8.5
* **Minimal Celery Version**: 5.1.2
* **Minimal Kombu Version**: 5.1.0
* **Minimal Broker Version**: Redis 6.2.4
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: macOS-10.15.7
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```
from celery import Celery
app = Celery('tasks',
    broker='redis://localhost',
    broker_transport_options = {'visibility_timeout': 0},
    task_acks_late=True,
    task_acks_on_failure_or_timeout=False,
)
print(app.conf['task_acks_on_failure_or_timeout'])

```
</p>
</details>

# Expected Behavior

expected 'False' output. 

# Actual Behavior

but 'True' output. I can not set task_acks_on_failure_or_timeout to False (default:True)

I think the reason is __autoset(), 'if value' will filter out all False value.
https://github.com/celery/celery/blob/master/celery/app/base.py#L325
```
    def __autoset(self, key, value):
        if value:
            self._preconf[key] = value
            self._preconf_set_by_auto.add(key)
```

**Comment by thedrow** [comment]
Thanks for the bug report. This should be easy to fix.
You're welcome to contribute a PR to fix this issue.
