### ISSUE TITLE
Missing messages in RabbitMQ queue using send_task function

### ISSUE THREAD

**Issue by CesarRoaldes** [celery/celery#6883]
I have a script calling Celery's `send_task` function 3047 times in a specific queue called `vv`. Using `rabbitmqadmin list queues` command, I noticed that only 2870 messages were present in the queue, without any worker connected to the `vv` queue.

Did you experienced this kind of behavior yourself? Is it only a displaying bug from `rabbitmqadmin`?

Thank you in advance for your help, if you need more details about the script I'll complete my question!

**Comment by auvipy** [comment]
please follow proper templates for opening issue otherwise thats tough to answer
