### ISSUE TITLE
docs/userguide/tasks.rst#task-naming-relative-imports section is misleading

### ISSUE THREAD

**Issue by iamahuman** [celery/celery#6903]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

As of 3cf5072ee5f95744024f60e0f4a77eb2edb8959f, [Tasks § Automatic naming and relative imports][1] states:

https://github.com/celery/celery/blob/3cf5072ee5f95744024f60e0f4a77eb2edb8959f/docs/userguide/tasks.rst#L260-L266

However, it goes on to say:

https://github.com/celery/celery/blob/3cf5072ee5f95744024f60e0f4a77eb2edb8959f/docs/userguide/tasks.rst#L309-L313

Hence, the documentation is inconsistent in saying whether or not new-style relative imports lead to inconsistent automatic task name generation for tasks contained within the imported module.

# Suggestions

- **Celery 5.x**: Celery 5.0 dropped support for Python 2 and only supports Python 3. Since Python 3 does not support old-style relative imports, the entire section can be dropped.
- **Celery 4.x**: Change the description to the following:

  > For example if the client inside the ``"myapp"`` module imports the module ``"myapp.tasks"`` as ``"tasks"``, and the worker imports the module as ``"myapp.tasks"``, the generated names won't match and an :exc:`~@NotRegistered` error will be raised by the worker.

[1]: https://docs.celeryproject.org/en/master/userguide/tasks.html#automatic-naming-and-relative-imports

**Comment by auvipy** [comment]
are you up for a contribution?

**Comment by iamahuman** [comment]
> are you up for a contribution?

Following GitHub code contribution workflow would mean there would be _two_ separate but otherwise trivial (as in no attribution requested) pull requests that would require manual review.

If you agree to the suggestion above then I'll submit patches matching the description above against both `master` and `4.x` branches.
