### ISSUE TITLE
django  celery  Received unregistered task of type 'demoapp.tasks.add'. The message has been ignored and discarded.  

### ISSUE THREAD

**Issue by Brookeyou** [celery/celery#6918]
project_tree
d_celery
--de_celery
----__pycache__
----__init__.py
----asgi.py
----celery.py
----celeryconfig.py
----settings.py
----urls.py
----wsgi.py
--demoapp
----__pycache__
----migrations
----__init__.py
----admin.py
----apps.py
----models.py
----tasks.py
----views.py

celery.py

`from __future__ import absolute_import, unicode_literals
import os
from celery import Celery
from d_celery import celeryconfig

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'd_celery.settings')

app = Celery('d_celery')

app.config_from_object(celeryconfig)

app.autodiscover_tasks()

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))`
``

celeryconfig.py

`broker_url = 'redis://:wo123456@127.0.0.1:6379/3'
result_backend = 'redis://:wo123456@127.0.0.1:6379/3'

task_serializer = 'json'
result_serializer = 'json'
accept_content = ['json']
timezone = 'Europe/Oslo'
enable_utc = True
`

tasks.py

`from __future__ import absolute_import, unicode_literals
from os import name
from celery import shared_task

@shared_task
def add(x, y):
    return x + y`

error-message:
`celery -A celery worker -l info -P eventlet
 
 -------------- celery@you v5.1.2 (sun-harmonics)
--- ***** -----
-- ******* ---- Windows-10-10.0.19041-SP0 2021-08-18 16:01:40
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         default:0x191464c2f10 (.default.Loader)
- ** ---------- .> transport:   redis://:**@127.0.0.1:6379/3
- ** ---------- .> results:     redis://:**@127.0.0.1:6379/3
- *** --- * --- .> concurrency: 4 (eventlet)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]

[2021-08-18 16:01:40,147: INFO/MainProcess] Connected to redis://:**@127.0.0.1:6379/3
[2021-08-18 16:01:40,165: INFO/MainProcess] mingle: searching for neighbors
[2021-08-18 16:01:41,231: INFO/MainProcess] mingle: all alone
[2021-08-18 16:01:41,242: INFO/MainProcess] celery@you ready.
[2021-08-18 16:01:41,258: INFO/MainProcess] pidbox: Connected to redis://:**@127.0.0.1:6379/3.
[2021-08-18 16:06:12,343: ERROR/MainProcess] Received unregistered task of type 'demoapp.tasks.add'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[1, 2], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (81b)
Traceback (most recent call last):
  File "c:\users\jigao\celeryenv\lib\site-packages\celery\worker\consumer\consumer.py", line 581, in on_task_received    
    strategy = strategies[type_]
KeyError: 'demoapp.tasks.add'`

**Comment by thedrow** [comment]
Please use the bug reporting template for reporting bugs.
Thank you!
