### ISSUE TITLE
celery==3.1.26.post2 and flower 0.9.5 dependency conflicts

### ISSUE THREAD

**Issue by minicloudsky** [celery/celery#6920]
I used django and celery,however i missed dependency conflicts
my python version is python3.8.2 and my pip version is  21.1.2

ERROR: Cannot install -r requirements.txt (line 37), -r requirements.txt (line 56), -r requirements.txt (line 70) and celery==3.1.26.post2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested celery==3.1.26.post2
    celery-once 3.0.1 depends on celery
    django-celery 3.3.0 depends on celery<4.0 and >=3.1.15
    flower 0.9.5 depends on celery>=4.3.0; python_version >= "3.7"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by auvipy** [comment]
you are using unsupported celery. try 5.1.x
