### ISSUE TITLE
Mac can not find celery process with ps -ef | grep celery command

### ISSUE THREAD

**Issue by minicloudsky** [celery/celery#6927]
I started celery successfully,however,i can not find celery process with `ps -ef | grep celery` command,under the centos i can use the above command can find the process.My mac version is 10.15.7 
![image](https://user-images.githubusercontent.com/32286819/130570927-e2e90bda-3884-4b8b-b60a-dd523f41ebce.png)
![image](https://user-images.githubusercontent.com/32286819/130570969-04ebc7e8-432c-41bd-afb9-21b2baad1fdf.png)

**Comment by thedrow** [comment]
The only explanation is that Celery isn't up.
This is not likely to be a bug in Celery. Please ask in StackOverflow or elsewhere.
