### ISSUE TITLE
the same task is repeated. Is this normal

### ISSUE THREAD

**Issue by TryReboot** [celery/celery#6928]
Python 3.8.3
celery 5.1.2 (sun-harmonics)

I am learning Celery, and I find that the same task is repeated. Is this normal?

```
# Version:
# Python 3.8.3
# celery 5.1.2 (sun-harmonic)


from celery import Celery

app = Celery("celery_app", broker="redis://localhost:6379/0",
             backend="redis://localhost:6379/0")


@app.task(bind=True, max_retries=10)
def work(self):
    try:
        raise self.retry(countdown=5)
    except Exception:
        raise self.retry(countdown=5)


if __name__ == '__main__':
    res = work.delay()
    print(res)

```
![image](https://user-images.githubusercontent.com/43699658/130577138-195209fe-e2a1-4ba8-8cdf-fe3c184b322d.png)

![image](https://user-images.githubusercontent.com/43699658/130577081-18a2fe29-da28-40bd-becb-2eedc415cd7f.png)

**Comment by thedrow** [comment]
Please refrain from asking questions in our issue tracker.
Since you are retrying the task, of course it is executed multiple times.

**Comment by TryReboot** [comment]
I set the countdown to 5 s for a maximum of 10 retries, but it executed 50 times. I've noticed a pattern where the number of tasks increases as countdown increases.

**Comment by thedrow** [comment]
Please open a new issue using our bug reporting template and provide all the necessary details to reproduce the problem.

**Comment by TryReboot** [comment]
ok
