### ISSUE TITLE
Mention that worker kills child processes on systems supporting `prctl. PR_SET_PDEATHSIG `

### ISSUE THREAD

**Issue by matusvalo** [celery/celery#6945]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
Documentation https://docs.celeryproject.org/en/master/userguide/workers.html#stopping-the-worker is outdated due merged PR #6942. 

# Suggestions
Documentation should mention that Celery worker main process running on systems supporting `prctl. PR_SET_PDEATHSIG ` should be able to kill all child processes using SIGKILL signal.

**Comment by auvipy** [comment]
i  should have suggest the document change in the PR which i forgot!

**Comment by matusvalo** [comment]
Yeah I will try to update the docs ASAP. It's not big deal just few sentences needs to be added/updated.
