### ISSUE TITLE
[Celery4] Worker crashing after upgrading RabbitMQ [ v3.8.6 -> v3.8.21]

### ISSUE THREAD

**Issue by daadu** [celery/celery#6954]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.7

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 4.4.7
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: RabbitMQ v3.8.21
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
arabic-reshaper==2.1.3
asgiref==3.4.1
autopep8==1.5.7
bcrypt==3.2.0
billiard==3.6.4.0
bitstring==3.1.9
blurhash-python==1.1.1
boto3==1.18.24
botocore==1.21.24
CacheControl==0.12.6
cachetools==4.2.2
celery==5.1.2
celery-prometheus-exporter==1.7.0
certifi==2020.12.5
cffi==1.14.6
chardet==4.0.0
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
cryptography==3.4.7
defusedxml==0.7.1
Deprecated==1.2.12
diff-match-patch==20200713
Django==3.2.6
django-admin-tools==0.9.1
django-admintool-command==0.1.1
django-celery-beat==2.2.1
django-celery-results==2.2.0
django-compat==1.0.15
django-extensions==3.1.3
django-import-export==2.5.0
django-ipware==3.0.7
django-oauth-toolkit==1.5.0
django-prometheus==2.1.0
django-shortuuidfield==0.1.3
django-silk==4.1.0
django-storages==1.11.1
django-sympycharfield==0.4.1
django-timezone-field==4.2.1
djangorestframework==3.12.4
drf-recaptcha==2.0.4
ecdsa==0.17.0
esptool==3.1
et-xmlfile==1.1.0
fcm-django==1.0.5
firebase-admin==5.0.2
future==0.18.2
google-api-core==1.31.2
google-api-python-client==2.17.0
google-auth==2.0.0
google-auth-httplib2==0.1.0
google-cloud-core==1.7.2
google-cloud-firestore==2.2.0
google-cloud-storage==1.42.0
google-crc32c==1.1.2
google-resumable-media==1.3.3
googleapis-common-protos==1.53.0
gprof2dot==2021.2.21
grpcio==1.39.0
html5lib==1.1
httplib2==0.19.1
idna==2.10
Jinja2==3.0.1
jmespath==0.10.0
jwcrypto==1.0
kombu==5.1.0
MarkupPy==1.14
MarkupSafe==2.0.1
mpmath==1.2.1
msgpack==1.0.2
oauthlib==3.1.1
odfpy==1.4.1
openpyxl==3.0.7
packaging==21.0
paho-mqtt==1.5.1
phonenumberslite==8.12.30
Pillow==8.3.1
pip-chill==1.0.1
pkg-resources==0.0.0
prometheus-client==0.11.0
prompt-toolkit==3.0.19
proto-plus==1.19.0
protobuf==3.17.3
psycopg2-binary==2.9.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.7.0
pycparser==2.20
pycryptodome==3.10.1
Pygments==2.10.0
pyparsing==2.4.7
PyPDF2==1.26.0
pyserial==3.5
python-bidi==0.4.2
python-crontab==2.5.1
python-dateutil==2.8.2
pytz==2021.1
PyYAML==5.4.1
qrcode==7.2
reedsolo==1.5.4
reportlab==3.6.1
requests==2.25.1
rsa==4.7.2
s3transfer==0.5.0
sentry-sdk==1.3.1
shortuuid==1.0.1
six==1.16.0
sqlparse==0.4.1
sympy==1.8
tablib==3.0.0
termcolor==1.1.0
toml==0.10.2
uritemplate==3.0.1
urllib3==1.26.2
uWSGI==2.0.19.1
vine==5.0.0
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.12.1
xhtml2pdf==0.2.5
xlrd==2.0.1
xlwt==1.3.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
I am using latest version of Celery 4 with RabbitMQ broker.

Recently I upgrade my RabbitMQ broker and started getting crashes, with following critical error in log:
`Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')`

Doing some google searching lead me to [a thread on RabbitMQ user group](https://groups.google.com/g/rabbitmq-users/c/X-x3DKVJb8k), this mentions that "ack timeout" was added from v3.8.15. This is new (unexpected) behaviour with the broker upgrade, earlier with  `v3.8.6` it did not happen.

Now is this known issue and fixed in Celery5 or is it new? I do not see any issues in the list regarding it.

Already posted this in [celery-user group](https://groups.google.com/g/celery-users/c/fsSACtCz8U4), but no response.

# Actual Behavior
Proper ackhnowledgments should be sent before timeout that is causing crash.

**Comment by auvipy** [comment]
we didnt get any report like this before so cant coment on that

**Comment by auvipy** [comment]
you can try with celery v5.2b2/b3

**Comment by alphavector** [comment]
I tried to reproduce your problem. I raised two simple `worker` and `rabbitmq` containers. All run with your dependencies from the pip freeze.
Tested the combinations:
`python:3.7-slim-buster rabbitmq:3.8.6-management-alpine`
`python:3.7-slim-buster rabbitmq:3.8.15-management-alpine`
`python:3.8-slim-buster rabbitmq:3.8.6-management-alpine` 
`python:3.8-slim-buster rabbitmq:3.8.15-management-alpine`

Everything works correctly as expected. Probably the problem is in the rabbitmq update, which is not related to celery

**Comment by alphavector** [comment]
version `rabbitmq:3.8.21-management-alpine` also works fine

**Comment by auvipy** [comment]
thanks

**Comment by daadu** [comment]
@alphavector It used to crash after about 30minutes which is the default timeout

**Comment by daadu** [comment]
I verified that the issue is still there with latest stable release v5.1.2.

**Comment by alphavector** [comment]
Yes, I found mentions of this problem:
https://github.com/apache/airflow/issues/15799
https://stackoverflow.com/questions/67907336/celery-task-with-a-long-eta-and-rabbitmq
The solution is to set `consumer_timeout = false` or more than 30 minutes in `rabbitmq.conf`
Anyway I played with the parameters, set `consumer_timeout = 1` and still could not reproduce the problem

**Comment by rafalmp** [comment]
I think I found a way to reproduce it - it seems to happen when Celery receives a task with ETA set far enough in the future, that the ack timeout happens before that task is actually executed. See for example an excerpt from my logs (with timeout set to 3600s):
```bash
wrz 27 19:19:40 server systemd[1]: Started Celery worker for backend project..
wrz 27 19:19:42 server celery[6508]: [2021-09-27 19:19:42,137: INFO/MainProcess] Connected to amqp://backend:**@127.0.0.1:5672/backend
wrz 27 19:19:42 server celery[6508]: [2021-09-27 19:19:42,147: INFO/MainProcess] mingle: searching for neighbors
wrz 27 19:19:43 server celery[6508]: [2021-09-27 19:19:43,192: INFO/MainProcess] mingle: sync with 1 nodes
wrz 27 19:19:43 server celery[6508]: [2021-09-27 19:19:43,194: INFO/MainProcess] mingle: sync complete
wrz 27 19:19:43 server celery[6508]: [2021-09-27 19:19:43,228: INFO/MainProcess] celery@backend ready.
wrz 27 19:19:43 server celery[6508]: [2021-09-27 19:19:43,248: INFO/MainProcess] Received task: backend.celery_main.tasks.mail_customer[d18601c4-a292-494e-817e-7ec5c00f1d2a]  ETA:[2021-09-28 03:12:23.374066+02:00]
wrz 27 19:19:43 server celery[6508]: [2021-09-27 19:19:43,249: INFO/MainProcess] Received task: backend.celery_main.tasks.mail_customer[38497539-7f28-4d7e-a260-367c11344e45]  ETA:[2021-09-28 02:52:36.411955+02:00]
```
and after an hour:
```bash
systemctl status celery-backend-worker-celery                                                                                                                                                                                        
● celery-backend-worker-celery.service - Celery worker for backend project.
   Loaded: loaded (/etc/systemd/system/celery-backend-worker-celery.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-09-27 20:20:44 CEST; 1min 28s ago
  Process: 6508 ExecStart=/home/backend/.local/share/virtualenvs/backend-0GyUaNJR/bin/celery -A backend.celery_main worker -Q celery -c 4 -l info -n celery@backend (code=exited, status=1/FAILURE)
 Main PID: 6508 (code=exited, status=1/FAILURE)

wrz 27 20:20:43 server celery[6508]:     callback(channel, method_sig, buf, None)
wrz 27 20:20:43 server celery[6508]:   File "/home/backend/.local/share/virtualenvs/backend-0GyUaNJR/lib/python3.6/site-packages/amqp/connection.py", line 518, in on_inbound_method
wrz 27 20:20:43 server celery[6508]:     method_sig, payload, content,
wrz 27 20:20:43 server celery[6508]:   File "/home/backend/.local/share/virtualenvs/backend-0GyUaNJR/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
wrz 27 20:20:43 server celery[6508]:     listener(*args)
wrz 27 20:20:43 server celery[6508]:   File "/home/backend/.local/share/virtualenvs/backend-0GyUaNJR/lib/python3.6/site-packages/amqp/channel.py", line 280, in _on_close
wrz 27 20:20:43 server celery[6508]:     reply_code, reply_text, (class_id, method_id), ChannelError,
wrz 27 20:20:43 server celery[6508]: amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 3600000 ms. This timeout value can be configured, see consumers doc guide to learn more
wrz 27 20:20:44 server systemd[1]: celery-backend-worker-celery.service: Main process exited, code=exited, status=1/FAILURE
wrz 27 20:20:44 server systemd[1]: celery-backend-worker-celery.service: Failed with result 'exit-code'.
```
Obviously, `task_acks_late` must be enabled for that.

**Comment by daadu** [comment]
@rafalmp good job, nailing this down. I to use long eta and that could be the reason.

Will increase the timeout and let you know if the issue remains.

**Comment by daadu** [comment]
Also if that is the case then this should be mentioned in docs somewhere.

**Comment by auvipy** [comment]
a PR to improve the doc is always welcome

**Comment by daadu** [comment]
@auvipy I am verifying it on my end first, we have really long ETAs so could take some time.

Also you think this needs to be handled on celery end (i am unaware how celery internal works) or should be caveat mentioned in doc?

**Comment by daadu** [comment]
@rafalmp I can confirm I was having this issue with default (disabled) `task_acks_late`. Although the queue was configuered in "lazy mode", not sure if that has to do anything with it.

Apart from that all settings as default.

**Comment by daadu** [comment]
I can confirm that the issue does not exists when setting `consumer_timeout` > than max celery `countdown` used.

@auvipy Should we mention this in doc or is this an issue that needs to be fixed?

**Comment by auvipy** [comment]
> I can confirm that the issue does not exists when setting `consumer_timeout` > than max celery `countdown` used.
> 
> @auvipy Should we mention this in doc or is this an issue that needs to be fixed?

@celery/core-developers what is your consensus on this?

**Comment by thedrow** [comment]
This is a duplicate of #6760. The same behavior is causing this error.
