### ISSUE TITLE
settings namings should follow django style

### ISSUE THREAD

**Issue by newearthmartin** [celery/celery#6961]
Celery 5 breaks Django's convention of having CAPITAL_LETTER_NAMES in settings. Currently, Celery settings are the only lowercase settings in my whole settings.py file. Also by removing the CELERY_ prefix, it's not easy to know that these settings belong to celery.

For example, there is the Django `TIME_ZONE` setting and then celery adds a `timezone` setting. It would be  respectful if Celery could mark these names as CELERY_. **Imagine if all apps started doing what Celery did, how would the settings file look like?**

**Comment by auvipy** [comment]
the settings were changed in version 4, v5 just removed the deprecated old settings

**Comment by auvipy** [comment]
anyway I am closing this for now. if any future consensus is reached to rechange it, will reopen.

**Comment by newearthmartin** [comment]
I guess going back to the pre v4 settings will make everyone in celery look like a fool. But it breaks the Django settings naming convention, it is self-centered and it doesn't play well with other apps.

**Comment by newearthmartin** [comment]
All apps prefix their settings with the app name AFAIK. And all apps use uppercase. If there was consensus about that it would be great. It used to be the case with Celery and I'm not sure why it was changed in the first place.

**Comment by LincolnPuzey** [comment]
@newearthmartin you can still use upper case name with a `CELERY_` prefix.

See https://docs.celeryproject.org/en/stable/history/whatsnew-4.0.html#latentcall-django-admonition
and https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html#using-celery-with-django
