### ISSUE TITLE
Redis ResponseError: Wrong number of arguments for 'subscribe' command

### ISSUE THREAD

**Issue by Venkatesh283** [celery/celery#6993]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [X] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [X] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/andymccurdy/redis-py/issues/1351

## Environment & Settings
**Celery version**:
- celery = 5.1.2
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```

software -> celery:5.1.2 (sun-harmonics) kombu:5.1.0 py:3.8.10
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-88-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None

```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: python-3.8
* **Minimal Celery Version**: 5.1.2
* **Minimal Kombu Version**:  5.1.0
* **Minimal OS and/or Kernel Version**: Ubuntu-18.04
* **Minimal Broker Client Version**: 3.5.3
* **Minimal Result Backend Client Version**: 3.5.3

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
anyio==3.3.2
asgiref==3.4.1
billiard==3.6.4.0
block-timer==0.2.0
catalogue==1.0.0
celery==5.1.2
certifi==2021.5.30
fastapi==0.70.0
fasttext==0.9.2
fuzzywuzzy==0.18.0
geotext==0.4.0
h11==0.12.0
hjson==3.0.2
kombu==5.1.2
pydantic==1.8.2
pyenchant==3.2.2
PyJWT==2.2.0
pymongo==3.12.0
pyparsing==2.4.7
python-datauri==1.0.0
python-dateutil==2.8.2
python-decouple==3.5
python-json-logger==2.0.2
python-Levenshtein==0.12.2
pytz==2021.3
redis==3.5.3
regex==2021.9.30
requests==2.26.0
scikit-learn==0.22.2.post1
scipy==1.7.1
seaborn==0.11.2
urllib3==1.26.7
uvicorn==0.15.0
vine==5.0.0
Wand==0.6.7
wasabi==0.8.2
wcwidth==0.2.5
xlrd==2.0.1
```
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

I'm Using celery with FastAPI and uvicorn as web server. Redis as broker/backend.

This issue occurs exactly, when I try using fetch the result using get() method
```
result = task.get(timeout=60, interval=0.5)
```
Command used to start the worker,
```
celery -A proj worker -l INFO --concurrency=6   -n worker0 --without-gossip --without-mingle -Ofair

```

</p>
</details>

# Expected Behavior
- Expecting celery tasks to be completed successfully.

# Actual Behavior
- Getting the following error
```
Traceback (most recent call last):
    result = task.get(timeout=60, interval=0.5)
  File "/usr/local/lib/python3.8/dist-packages/celery/result.py", line 224, in get
    return self.backend.wait_for_pending(
  File "/usr/local/lib/python3.8/dist-packages/celery/backends/asynchronous.py", line 199, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/lib/python3.8/dist-packages/celery/backends/asynchronous.py", line 265, in _wait_for_pending
    for _ in self.drain_events_until(
  File "/usr/local/lib/python3.8/dist-packages/celery/backends/asynchronous.py", line 54, in drain_events_until
    yield self.wait_for(p, wait, timeout=interval)
  File "/usr/local/lib/python3.8/dist-packages/celery/backends/asynchronous.py", line 63, in wait_for
    wait(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/celery/backends/redis.py", line 152, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'subscribe' command

```

**Comment by auvipy** [comment]
check the related patch please

**Comment by hexvolt** [comment]
Unfortunately, it's still an issue https://github.com/celery/celery/pull/7040#issuecomment-1040785011

**Comment by thedrow** [comment]
@hexvolt Did you try master?
