### ISSUE TITLE
python 3.10.0 and celery 5.2.0

### ISSUE THREAD

**Issue by naomielst** [celery/celery#7064]
### Discussed in https://github.com/celery/celery/discussions/7063

<div type='discussions-op-text'>

<sup>Originally posted by **swuecho** November  9, 2021</sup>
After upgrade celery and python, get the following error. (no code change in my project, only upgrade deps necessary to make pip install all requirement.txt)

```
app/tasks.py:21: in <module>

	    from .celery import app

	app/celery.py:5: in <module>

	    from celery import Celery

	E   ImportError: cannot import name 'Celery' from 'celery' (/app/.venv/lib/python3.10/site-packages/celery/__init__.py)
```

anybody has similar issues? Thanks!</div>

**Comment by swuecho** [comment]
check version of importlib-metadata version first if anyone have similar problem.

**Comment by auvipy** [comment]
https://github.com/celery/celery/discussions/7063#discussioncomment-1616148 closing

**Comment by auvipy** [comment]
@naomielst it was a false positive.

**Comment by auvipy** [comment]
> check version of importlib-metadata version first if anyone have similar problem.

but yes we can upgrade min version required

**Comment by sahilklanto** [comment]
> check version of importlib-metadata version first if anyone have similar problem.

If anyone else is stuck with this error and has the most recent importlib-metdata, check if you have the version that's supported with your python version. 

https://github.com/python/importlib_metadata
importlib_metadata | stdlib
                            -- | --
                         4.8 | 3.11
                         4.4 | 3.10
                         1.4 | 3.8
