### ISSUE TITLE
New pytest-celery plugin

### ISSUE THREAD

**Issue by naomielst** [celery/celery#7149]
# Checklist
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
* [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues
* #6773 

#### Possible Duplicates
* None

# Brief Summary
Create a new major version (1.0.0) of the pytest-celery plugin. 

## Motivation
We want to refactor the Celery integration test suite so that it will be up and running again. We will make the integration tests more readable and flexible and ergonomic to us.

We also want to enable Celery users to test the integration easily and reliably, which is why the changes will eventually be available to all users via the pytest-celery plugin.

## Scope 
The scope of this project is to migrate the Celery integration suite since it is broken. 

In this major version we will only address our use-cases. In the next one, we will begin planning and implementing features which could be important to our userbase as well.

#### Memory and CPU efficiency
The plugin must support GH Actions as this is the CI service we use.

It should support other commonly used CI services (such as Azure Pipelines, Circle CI or other similar CI services for open source).

We will run dependencies in Docker using the testcontainers library.
The containers our plugins runs will be reused from test to test for efficiency instead of tearing them down and re-running them in each test.
When we require multiple instances of the same docker image (e.g. using the same container for the message broker and result backend), a separate virtual host will be created for each service our test requires. 
This provides logical separation which is good enough for testing purposes as usually security is not an issue in CI and therefore, we don't need to separate services by using stronger guarantees of isolation such as separate containers or even virtual machines.

#### Resource leak prevention
The only resource that is opened for each test by default is a queue. Queues will be given an expiration date so that unexpected shutdowns and failures do not cause memory leaks.
Containers are removed when the test suite is torn down. As a consequence, this will make all virtual hosts disappear. 
Note that if a test is forced to quit (if you hit ctrl+c twice or if the pytest process is killed for whatever reason) , its virtual hosts will not immediately be removed. However, each time the test suite is completed, it tears down all virtual hosts, so this is manageable.

#### Run on the entire matrix of optional dependencies in parallel. 
A test must be able to receive multiple options for each dependency. 
The test will run on the Cartesian product of all optional dependencies.

This should also work in parallel with pytest-xdist.

#### Meaningful error messages
Error messages must be meaningful and grouped. 
When the same test runs in parallel on several configurations, and some configurations fail for the same reason, we will batch those failures together.

All relevant logs will be attached to pytest's report when something goes wrong, including the container logs and the Celery worker(s) logs.

## Timeline 
ASAP: release version 0.1.0 to pytest-celery plugin.
Celery 5.x (next minor release): deprecation pending for version 0.1.0
Celery 6.0: pytest-celery version 1.0.0 released, version 0.1.0 deprecated
Celery 6.1: pytest-celery version 0.2.0 released which includes the code in `celery/contrib/pytest.py`
Celery 7.x: delete code for version 0.1.0

# Design
## Architectural Considerations

None

## Proposed UI/UX

The API design will be added soon.

## Diagrams
N/A

## Alternatives
None

**Comment by auvipy** [comment]
are the content of celery/contrib/pytest.py will be the starting point? are we going to move the contents in the plugin and improve that?

**Comment by thedrow** [comment]
As the timeline suggests, we will eventually remove the code from `celery/contrib/pytest.py`.

@naomielst You should clarify that in the issue.

**Comment by Nusnus** [comment]
The new pytest plugin development has taken a different route from this ticket and is being developed under different assumptions & goals, in sync & with the approval of @thedrow.
I will close this issue as part of a cleanup for Milestone 5.3.0.

This does not mean the actual task is done, but that this ticket will not be used anymore to communicate the progress on the development of the new pytest-celery v1.0.0 plugin.

**Comment by willsthompson** [comment]
Hi @Nusnus, is there an issue for the new plugin plans?

**Comment by Nusnus** [comment]
@willsthompson 
> Hi @Nusnus, is there an issue for the new plugin plans?

Hey there, no, at the moment.
I am progressively working on the project/updating the issues on GitHub, so hopefully I'll be able to communicate better sometimes soon.

Many issues I'm working on take a relatively small amount of time to work on (by themselves), so I'm trying to find the balance between what's worth communicating out and what's better to just work on and get going, assuming we want a fast rate of development and I am the only active contributor at the moment which means I have a lot on my plate, so I apologize for the lack of proper transparency.

**Comment by auvipy** [comment]
> Hi @Nusnus, is there an issue for the new plugin plans?

you can follow the new plugin project in the mean time

**Comment by willsthompson** [comment]
@Nusnus sure, thanks for giving this your attention.

@auvipy which project? The pytest-celery repo?

**Comment by auvipy** [comment]
> which project? The pytest-celery repo?

yes

**Comment by Nusnus** [comment]
@willsthompson [FYI](https://github.com/celery/pytest-celery/issues/39#issuecomment-1891093397)
