### ISSUE TITLE
Sqs broker + fifo queues = MissingParameter MessageGroupId.

### ISSUE THREAD

**Issue by 0ssigeno** [celery/celery#7151]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

# Expected Behavior

I can have the following sqs broker configuration

```
    broker_transport_options={
        "predefined_queues": {
            "MY_QUEUE": {
                "url": "MYURL.fifo"
            },
    },
```

And no error will raise when calling my tasks.

# Actual Behavior

```
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.9/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 177, in publish
    return _publish(
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 524, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 199, in _publish
    return channel.basic_publish(
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 604, in basic_publish
    return self._put(routing_key, message, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/SQS.py", line 392, in _put
    c.send_message(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MissingParameter) when calling the SendMessage operation: The request must contain the parameter MessageGroupId.
```

# Explanation of the bug:
In the [konbu](https://docs.celeryproject.org/projects/kombu/en/stable/_modules/kombu/transport/SQS.html) documentation there is the following lines that manage this exception.

```python3
        if queue.endswith('.fifo'):
            if 'MessageGroupId' in message['properties']:
                kwargs['MessageGroupId'] = \
                    message['properties']['MessageGroupId']
            else:
                kwargs['MessageGroupId'] = 'default'
```

Since `Konbu` checks that  `routing_key` ends with `.fifo`, and not what it has been configured inside celery as `MY_URL`, means that the property `MessageGroupId` is never set, and the `botocore` error is raised.

I can see why this is not a celery bug, or not a bug at all, but I would say this case should be at least documented: having to force celery queues name to follow the SQS paradigm, in my opinion, can mislead people.

**Comment by n0061q** [comment]
Hi,

as you mentioned it is a kombu bug. It is fixed now and will be available in the next kombu release: https://github.com/celery/kombu/pull/1450
