### ISSUE TITLE
Docs seem to suggest that ignore_result can be set on `delay`

### ISSUE THREAD

**Issue by RenWal** [celery/celery#7203]
# Checklist
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- introduced by: PR #4745

#### Possible Duplicates

- None

# Description
The [user guide for tasks](https://github.com/celery/celery/blob/7f9daab9d3007d2a52f7813cf12dd7fa5666c98b/docs/userguide/tasks.rst#tips-and-best-practices) states:  "Results can be enabled/disabled on a per-execution basis, by passing the `ignore_result` boolean parameter, when calling `apply_async` _or `delay`_" (emphasis mine)

To me, this seems to suggest that you could so something like `mytask.delay(ignore_result=True)`. However, that will just cause the kwarg to be passed through to the task itself, or rather, it causes an exception:

    TypeError: mytask() got an unexpected keyword argument 'ignore_result'

Looking at the [user guide on calling tasks](https://github.com/celery/celery/blob/7f9daab9d3007d2a52f7813cf12dd7fa5666c98b/docs/userguide/calling.rst#basics), it becomes clear that `delay` is just a "Shortcut to send a task message, _but doesn’t support execution options_" (emphasis mine) and hence `apply_async` must be used instead.

# Suggestions
Unless I'm completely misunderstanding something here, I suggest that it is made more clear in the user guide for tasks that usage of `apply_async` rather than `delay` is required to use the `ignore_result` kwarg.

**Comment by thedrow** [comment]
You're right. You can pass `ignore_result` to `apply_async()` but not to `delay()`. Care to issue a PR to fix this?

**Comment by auvipy** [comment]
> You're right. You can pass `ignore_result` to `apply_async()` but not to `delay()`. Care to issue a PR to fix this?

PR created https://github.com/celery/celery/pull/7209/files, if you want to mention in some part that passing the parameter to delay will cause type erros I can add that elaborate description too
