### ISSUE TITLE
Version 5.3

### ISSUE THREAD

**Issue by thedrow** [celery/celery#7238]
Version: 
Release PR: 

# Description

# Checklist

- [ ] Release PR drafted
- [ ] Milestone is 100% done
- [ ] Merge Freeze
- [ ] Release PR reviewed
- [ ] The master branch build passes

    [![Build Status](https://github.com/celery/celery/actions/workflows/python-package.yml/badge.svg)](https://github.com/celery/celery/actions/workflows/python-package.yml)
- [ ] Release Notes
- [ ] What's New

# Process

# Alphas

- [ ] Alpha 1

## Betas

- [ ] Beta 1

## Release Candidates

- [ ] RC 1

# Release Blockers

# Potential Release Blockers

**Comment by auvipy** [comment]
any expected time line? I want to release at least one point release for v5.2.x

**Comment by auvipy** [comment]
closing in favor or https://github.com/celery/celery/issues/7605
