### ISSUE TITLE
Allow run task from another microservice and get the result

### ISSUE THREAD

**Issue by jefer94** [celery/celery#7293]
In the normal cases of use, the celery tasks are defined in the same code, but should be a great idea can trigger this tasks by other microservice thought of a app id and a task name, and this should run in synchrony and asynchrony mode, with this API I think celery should be the first option for python developer think in build many real microservices

```py
app.run('killer.kenny', 1, 2, 3, a=4, b=5)
```

**Comment by WilliamDEdwards** [comment]
From https://docs.celeryproject.org/en/stable/userguide/calling.html

> Tip
> 
> If the task isn’t registered in the current process you can use [send_task()](https://docs.celeryproject.org/en/stable/reference/celery.html#celery.Celery.send_task) to call the task by name instead.

**Comment by jefer94** [comment]
I'm trying to use this method, it look to be the solution but just appear as documentation reference and this is more used to the Celery team and contributors, but for the users generally see the common cases of uses, see the descriptions of arguments I can do it with `ctrl + click` or with the docstring, also the name `send_task` is not the first thing a developer think should be the name of this type of this function, is necessary document the case of use and their seo

**Comment by jefer94** [comment]
It should be a example work for me

```py
from celery import Celery

app = Celery('auth')

app.config_from_object('auth.settings')
app.conf.task_routes = {'auth.*': {'queue': 'worker'}}

app.send_task('auth.validate_token', (123123123, )).get()
```

**Comment by thedrow** [comment]
We welcome documentation fixes as PRs. However, this is supported as others have mentioned.
