### ISSUE TITLE
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'

### ISSUE THREAD

**Issue by mymusise** [celery/celery#7340]
## Info
version: 5.2.3
MQ: rabbitMQ:3

## code

**app.py**
```python
celery_app = Celery("worker", broker=my_broker)
```

**task.py**
```python
import celery

from .app import celery_app

@celery_app.task
def test_add(args):
    x = args[0]
    y = args[1]
    with open('../logs/test.log', 'w') as f:
        f.write('test')
    return x + y
```

**server.py**
```python
from apps.workers.app import celery_app


task_name = "workers.task_example.test_add"

task = celery_app.send_task(task_name, args=[(12, 1)])
task.result()
```

## Desc
Hi, I met this error when I call `task.result()`

```
File ~/pro/asynchronous-template/env/lib/python3.8/site-packages/celery/result.py:417, in AsyncResult._get_task_meta(self)
    415 def _get_task_meta(self):
    416     if self._cache is None:
--> 417         return self._maybe_set_cache(self.backend.get_task_meta(self.id))
    418     return self._cache

File ~/pro/asynchronous-template/env/lib/python3.8/site-packages/celery/backends/base.py:609, in Backend.get_task_meta(self, task_id, cache)
    607 while True:
    608     try:
--> 609         meta = self._get_task_meta_for(task_id)
    610         break
    611     except Exception as exc:

AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'

```

But it work if I add a `backend` in `Celery` like `celery_app = Celery("worker", backend="redis://localhost", broker=broker)`.

Is `backend` necessary?

**Comment by FarisHijazi** [comment]
if you're on windows, it's been answered [here](https://github.com/celery/celery/issues/4178#issuecomment-321070667) that celery on windows could be the issue

**Comment by thedrow** [comment]
You are attempting to fetch the result and you cannot do so without the backend.
In your example, a result backend is necessary.

**Comment by alfredodeza** [comment]
If the problem is that there is no backend, the error should be that there is no backend, not a basic/generic `AttributeError` . This bug could be repurposed to improve the error reporting when this happens.

**Comment by A-Najmabadi** [comment]
I fix this problem by adding a variable named `CELERY_RESULT_BACKEND` with exat value of `CELERY_BROKER_URL` in `settings.py` file.
