### ISSUE TITLE
docs site is down: https://docs.celeryproject.org/

### ISSUE THREAD

**Issue by timotei-za** [celery/celery#7353]
documentation website is down

**Comment by CodePint** [comment]
duplicate of https://github.com/celery/celery/issues/7351

**Comment by miguelrochajr** [comment]
If you need to take a look at the Docs now, you can find the 5.1.0 version here in the [Web Archive](https://web.archive.org/web/20210615213743/https://docs.celeryproject.org/en/stable/)

Hope it helps :)

**Comment by lowercase00** [comment]
@miguelrochajr life saver, thanks a lot.

**Comment by caffeinatedMike** [comment]
Glad it's not just me. I resorted to web archive as well.

**Comment by adhy57** [comment]
Ping @auvipy

**Comment by binb4sh** [comment]
the site seems under attacking by somebody? The site certificate name is 4rdcom.com, this domain registered by apinheiro78@hotmail.com

**Comment by auvipy** [comment]
new domain https://docs.celeryq.dev/en/stable/
