### ISSUE TITLE
Docs literally aren't reachable on the main website

### ISSUE THREAD

**Issue by yotamss** [celery/celery#7369]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
Did you all notice: http://celeryproject.org/ is not available?
This docs domain DO work: https://docs.celeryq.dev/en/stable/
I guess the first one is important because it is the website google indexes -> you can reach it from google.

# Suggestions
(:

**Comment by auvipy** [comment]
please check issues and repo web link before opening any issues, https://docs.celeryq.dev/en/stable/

**Comment by yotamss** [comment]
> please check issues and repo web link before opening any issues, https://docs.celeryq.dev/en/stable/

Yup, I checked it, look what I wrote

**Comment by jnns** [comment]
@yotamss @hassanselim0 You will find more information about this issue in ticket https://github.com/celery/celeryproject/issues/52
