### ISSUE TITLE
Why are old docs linked to beget.com?

### ISSUE THREAD

**Issue by YPCrumble** [celery/celery#7376]
The old docs, docs.celeryproject.org, are now linked to beget.com. 

Does this mean that every link on the internet that refers to Celery documentation has been irreversibly broken?

Would it be possible to help by adding a 301 redirect from the old site to the new site? If the old site was not renewed, would it be possible to ask ICANN to re-instate it so that the old links are no longer broken?

**Comment by jnns** [comment]
https://github.com/celery/celeryproject/issues/52 has more infos.

**Comment by tisdall** [comment]
The README.rst has been updated with https://docs.celeryq.dev/ but pypi still has the broken links.

**Comment by pkilla** [comment]
oh shit, did not know that the domain was hijacked in the past, I thought it was controlled by the "celery team", thought it was a DNS config error

**Comment by YPCrumble** [comment]
Closing in favor of [#52](https://github.com/celery/celeryproject/issues/52). For what it's worth my personal workaround has been to install this chrome extension with a redirect: https://einaregilsson.com/redirector/

**Comment by tisdall** [comment]
@pkilla if you could put a 301 permanent redirect in there to https://docs.celeryq.dev/ , that'd be good.  👍 

It seems like the domain name never got transferred to the project and I guess it expired and someone else picked it up?  I'm not sure the details.  WHOIS is obfuscated.

**Comment by tisdall** [comment]
That's freaking awesome!  I wonder how long it'll stay like that.

**Comment by auvipy** [comment]
the old domain is now under PSF control, they will redirect it
