### ISSUE TITLE
Celery website is down!

### ISSUE THREAD

**Issue by adampl** [celery/celery#7386]
The entire project website is down, both https://celeryproject.org and https://docs.celeryproject.org

**Comment by confuzeus** [comment]
Looks like it's redirecting to a Russian web host. I Hope they didn't get hacked.

Meanwhile, browse the docs using Wayback machine: https://web.archive.org/web/20220122212712/https://docs.celeryproject.org/en/stable/

**Comment by sammyzord** [comment]
Old domain has been compromised
New documentation website: [docs.celeryq.dev](https://docs.celeryq.dev/)

**Comment by krystofbe** [comment]
no way to restore the original domain? there are so many links on stackoverflow/tutorials/blogs/whatnot that are broken now

**Comment by koleror** [comment]
> no way to restore the original domain? there are so many links on stackoverflow/tutorials/blogs/whatnot that are broken now

And on Pypi: https://pypi.org/project/celery/

**Comment by JSv4** [comment]
Anyone from the project have any clarity on what's up here? Was the domain compromised?

**Comment by auvipy** [comment]
did any of you check github repo website link? we changed the domain for now https://docs.celeryq.dev/en/stable/ , the older domain was registered & owned by creator & former maintainer of the project @ask who died few months ago. we are working with PSF to get an hold of the former domain.
