### ISSUE TITLE
Is celery in pypi safe?

### ISSUE THREAD

**Issue by tisdall** [celery/celery#7389]
You already know about the issues around `docs.celeryproject.org` and `celeryproject.org` and I see that things are being transitioned to a new domain.  However, I'm concerned that one of the admins in pypi is using a `@celeryproject.org` email address which could allow the new owners of that domain to add new compromised releases into pypi.  

Is there any way to address this concern?  I looked at a project I'm an owner of and it doesn't seem to be possible for me to see the email address used by other collaborators.  However, if 2FA has been turned on for all collaborators in pypi, that might be sufficient.

Also, I was intending to pin celery in my project to a particular version, but it seems like it's [possible to replace older versions in pypi by adding build numbers](https://stackoverflow.com/a/63944201/918558).

**Comment by clokep** [comment]
See https://github.com/celery/celeryproject/issues/52#issuecomment-1073823186
