### ISSUE TITLE
Celery documentation links return 404 errors

### ISSUE THREAD

**Issue by Carewen** [celery/celery#7391]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description
The documentation page (https://pypi.org/project/celery/) has four broken links to webpages/documents. All links are to pages/documents that are no longer there. 404 errors are returned:

- [Web link at the top of the page](https://docs.celeryproject.org/en/stable/index.html)
Get Started section:
- [First Steps with Celery](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html)
- [Next Steps](http://docs.celeryproject.org/en/latest/getting-started/next-steps.html)
Documentation Section:
- [Latest Documentation](https://docs.celeryproject.org/en/latest/)

# Suggestions
Please fix those links so that both documents render as expected. As a developer completely new to Celery these missing documents leave quite a gap.  Thanks in advance for your support and maintaining this library. I look forward to learning what Celery can do and making the most of it.

**Comment by stcrestrada** [comment]
Yeah this one has been going on for well over a week. Pretty frustrating because our team is finally adopting celery after lots of push back from leadership and now it's just not a good look that all the documentation links are breaking. Hope this gets resolved soon.

**Comment by j-bennet** [comment]
Dear Celery developers, 

Your whole documentation website has been down for a few days now.

<img width="976" alt="image" src="https://user-images.githubusercontent.com/637013/161677148-739754c2-46da-4ce1-aafd-6c36ae302855.png">

Please fix it.

**Comment by auvipy** [comment]
the new link is up for more then a week https://docs.celeryq.dev/en/stable/

**Comment by stcrestrada** [comment]
> the new link is up for more then a week https://docs.celeryq.dev/en/stable/

sure but if you google python celery, it's not the first link that appears, it's actually what @j-bennet posted above. +1, please fix.

**Comment by elenageo** [comment]
> the new link is up for more then a week https://docs.celeryq.dev/en/stable/

That's true but all links @ https://pypi.org/project/celery/ are pointing to the old website.

**Comment by fuho** [comment]
> the new link is up for more then a week https://docs.celeryq.dev/en/stable/

But how do people find that link?
Why no redirects? Did you lose the domain?  
As a temp fix I currently add `-site:celeryproject.org` to my [google searches](https://www.google.com/search?q=celery+list+jobs+-site%3Aceleryproject.org).

**Comment by atleta** [comment]
> Why no redirects? Did you lose the domain? 

It doesn't seem so. At least if they did register it themselves and not through some 3rd party that had control over it. WHOIS says it's been registered since 2009 and that it will only expire in June and that it hasn't changed since last May.

```
Domain Name: CELERYPROJECT.ORG
Registry Domain ID: D156435169-LROR
Registrar WHOIS Server: whois.enom.com
Registrar URL: http://www.enom.com
Updated Date: 2021-05-01T05:08:39Z
Creation Date: 2009-06-15T19:30:15Z
Registry Expiry Date: 2022-06-15T19:30:15Z
```

**Comment by auvipy** [comment]
we were able to recover the domain with the help of psf. the redirects will be done soon.

**Comment by Uninen** [comment]
This ticket is about the link on PyPI. Is there anything we can help with to change those links? (Didn't see that metadata in the repo.)

**Comment by auvipy** [comment]
a new release soon

**Comment by daredevil82** [comment]
https://flataas.vareminnesider.no/memorial_page/memorial_page_personal_info.php?order_id=3957458&set_site_id=831&cat=home&sign=bf0ba6c7eb4ed19e97572a293d4d1ef2

From what I understand the original celery documentation domain and certs were under Ask's control, and looks like he passed away mid December 2021.

**Comment by auvipy** [comment]
yes, but now the psf took it over

**Comment by auvipy** [comment]
> if link is working , can we close this ticket ?

we still need a release from master branch.

**Comment by auvipy** [comment]
a 5.3.0a1 release was pushed to pypi

**Comment by Uninen** [comment]
Thank You for your work @auvipy 🙏
