### ISSUE TITLE
Celery worker stuck

### ISSUE THREAD

**Issue by jaroslawporada** [celery/celery#7462]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:
5.2.2 (dawn-chorus)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.2.2 (dawn-chorus) kombu:5.2.2 py:3.10.1
            billiard:3.6.4.0 redis:3.5.3
platform -> system:Linux arch:64bit
            kernel version:5.10.90+ imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:{my_redis_transport} results:{my_redis_result}

accept_content: ['json', 'pickle']
beat_schedule: {...}
beat_schedule_filename: 'celerybeat-schedule'
broker_transport_options: {
    'confirm_publish': True,
    'fanout_patterns': True,
    'fanout_prefix': True,
    'socket_connect_timeout': 10,
    'socket_timeout': 50,
    'visibility_timeout': 86400}
broker_url: {broker_url}
queues: [...]
redis_socket_connect_timeout: 10
result_backend: {my_result}
result_expires: 3600
result_serializer: 'json'
task_always_eager: False
task_compression: 'zlib'
task_create_missing_queues: True
task_default_exchange: 'celery'
task_default_exchange_type: 'direct'
task_default_queue: 'celery'
task_default_routing_key: '********'
task_eager_propagates: False
task_ignore_result: False
task_queues: [...]
task_routes: {...}command
task_serializer: 'json'
task_soft_time_limit: 300
task_time_limit: 360
timezone: 'America/Los_Angeles'
worker_cancel_long_running_tasks_on_connection_loss: True
worker_hijack_root_logger: False
worker_max_memory_per_child: 500000
worker_max_tasks_per_child: 500
worker_prefetch_multiplier: 1
worker_redirect_stdouts: True
worker_send_task_events: True
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.10.1
* **Minimal Celery Version**: 5.2.2
* **Minimal Kombu Version**: 5.2.2
* **Minimal Broker Version**: redis_version:5.0.14
* **Minimal Result Backend Version**: redis_version:5.0.14
* **Minimal OS and/or Kernel Version**:  system:Linux arch:64bit   kernel version:5.10.90+
* **Minimal Broker Client Version**: redis==3.5.3
* **Minimal Result Backend Client Version**: redis==3.5.3

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
...
-   kombu==5.2.2
-   django-redis==5.0.0
-   hiredis==2.0.0
-   redis==3.5.3
-   celery==5.2.2
-   vine==5.0.0
-   amqp==5.0.6
...
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
After some time Celery worker stuck.

Logs just before getting stuck:

> ```
> child process exiting after exceeding memory limit (2424980KiB / 500000KiB)
> {}
> could not ensure all messages were consumed prior to exiting
> "Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 155 Job: 144954.')"
> ```

</p>
</details>

# Expected Behavior

Celery worker is responsive, consume tasks and  is visible in "celery inspect ping" command.
# Actual Behavior

Never ending loop occurred, it lasted few hours and only restart of worker helped. I tried to figure out what exactly happened so I used pdb debugger started with env CELERY_RDBSIG=1 and USR2 signal. I noticed that in this case:

 - self._active_writers contain 1 element,
 - gen_not_started(gen)) for this element returns False,
 - owned_by is empty dict.
 - self.maintain_pool() don't change self.active_writers (I checked that with breakpoint in line 1037),
so the while loop never ends.

![Screenshot from 2022-04-12 15-49-43](https://user-images.githubusercontent.com/78016744/163346097-0b36f35f-4f51-4efe-9295-bf22b1ee5559.png)

**Comment by Nusnus** [comment]
I tried to reproduce this issue, but the worker handles the error in my case:
```bash
2023-12-10 19:09:12 [2023-12-10 17:09:12,272: INFO/MainProcess] Task t.smoke.tasks.long_running_task[33ca76f2-1735-48c3-add9-de4c4e7bcb49] received
2023-12-10 19:09:12 [2023-12-10 17:09:12,274: INFO/ForkPoolWorker-8] t.smoke.tasks.long_running_task[33ca76f2-1735-48c3-add9-de4c4e7bcb49]: Starting long running task
2023-12-10 19:09:18 [2023-12-10 17:09:18,920: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:16 exited with 'signal 9 (SIGKILL)'
2023-12-10 19:09:19 [2023-12-10 17:09:19,834: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 0.')
2023-12-10 19:09:19 Traceback (most recent call last):
2023-12-10 19:09:19   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
2023-12-10 19:09:19     raise WorkerLostError(
2023-12-10 19:09:19 billiard.einfo.ExceptionWithTraceback: 
2023-12-10 19:09:19 """
2023-12-10 19:09:19 Traceback (most recent call last):
2023-12-10 19:09:19   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
2023-12-10 19:09:19     raise WorkerLostError(
2023-12-10 19:09:19 billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 0.
2023-12-10 19:09:19 """
2023-12-10 19:09:48 [2023-12-10 17:09:48,414: INFO/MainProcess] missed heartbeat from smoke_tests_worker@37a9eb26f147
2023-12-10 19:09:48 missed heartbeat from smoke_tests_worker@37a9eb26f147
2023-12-10 19:09:49 [2023-12-10 17:09:49,966: INFO/MainProcess] Task t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4] received
2023-12-10 19:09:49 Task t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4] received
2023-12-10 19:09:49 [2023-12-10 17:09:49,967: INFO/ForkPoolWorker-11] t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4]: Starting long running task
2023-12-10 19:09:50 [2023-12-10 17:09:50,971: INFO/ForkPoolWorker-11] t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4]: Finished long running task
2023-12-10 19:09:50 [2023-12-10 17:09:50,974: INFO/ForkPoolWorker-11] Task t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4] succeeded in 1.0072212089999937s: True
2023-12-10 19:09:50 Task t.smoke.tasks.long_running_task[43bab33c-c7b1-4df3-9b06-04d7e71fb6d4] succeeded in 1.0072212089999937s: True
```

```python
@shared_task
def long_running_task(
    seconds: float = 1,
    verbose: bool = False,
    allocate: int | None = None,
    exhaust_memory: bool = False,
) -> bool:
    from celery import current_task
    from celery.utils.log import get_task_logger

    logger = get_task_logger(current_task.name)

    logger.info("Starting long running task")

    if allocate:
        # Attempt to allocate megabytes in memory
        _ = [0] * (allocate * 10**6 // getsizeof(int()))

    if exhaust_memory:
        mem = []
        while True:
            mem.append(' ' * 10**6)  # 1 MB of spaces

    for i in range(0, int(seconds)):
        sleep(1)
        if verbose:
            logger.info(f"Sleeping: {i}")

    logger.info("Finished long running task")

    return True
```

I run `long_running_task.si(exhaust_memory=True)` then `long_running_task.si(1)` and the worker gives the log above.

---

@jaroslawporada do you have a better way to reproduce the issue?

**Comment by jaroslawporada** [comment]
I did not saw this problem for a while. I will close the issue.
