### ISSUE TITLE
Python 3.10 + celery 5.2.4 deprecationwarning

### ISSUE THREAD

**Issue by tgross35** [celery/celery#7528]
### Discussed in https://github.com/celery/celery/discussions/7527

<div type='discussions-op-text'>

<sup>Originally posted by **tgross35** May 17, 2022</sup>
Running with the mentioned versions raises the following error:

```
 /usr/local/lib/python3.10/site-packages/celery/utils/imports.py:145: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for ep in entry_points().get(namespace, []):
```

This appeared in kombu and was an easy fix: https://github.com/celery/kombu/issues/1339

I have been unsuccessful trying to submit an issue on this subject</div>

**Comment by auvipy** [comment]
should be fixed by https://github.com/celery/celery/pull/7785
