### ISSUE TITLE
Trailing comma in python_requires descriptor field

### ISSUE THREAD

**Issue by AsserHic** [celery/celery#7533]
Dear Celery authors,

Setup.py defines the required python version as ">=3.7," and it seems that the trailing comma is causing issues in some Poetry environments (observed with Poetry 1.2.0b1). Not sure if the trailing comma is strictly legal, but removing the unnecessary and troublesome character would make the package easier to approach.

https://github.com/celery/celery/blob/726b664840b6a1fcea9225b254a393e665363ad0/setup.py#L166

Thank you very much for the great Python package!

**Comment by auvipy** [comment]
seems we can remove it https://github.com/celery/celery/pull/7534 , https://github.com/celery/kombu/blob/master/setup.py#L116
