### ISSUE TITLE
celery.security.key PrivateKey does not check returned key type

### ISSUE THREAD

**Issue by qrmt** [celery/celery#7645]
If for some reason the private key used as `broker_use_ssl.keyfile` is not an RSA private key,  Celery will crash without  telling the root cause, leading to difficult debugging. This affects current celery master branch.

This is due to celery.security.key.PrivateKey `__init__` method not checking the returned key type from `load_pem_private_key` (from `cryptography.hazmat`). If the returned key is, for example, [EllipticCurvePrivateKey](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey), the `sign` method of PrivateKey later will crash with `TypeError: sign() takes 3 positional arguments but 4 were given` as it expects that `self._key` is instance of `RSAPrivateKey`. Furthermore, this (opaque) exception is followed by many more exceptions of type "TypeError: catching classes that do not inherit from BaseException is not allowed". See reproduction for a complete crash log.

`cryptography` library load_pem_private_key  [documentation](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/) explicitly states that "Many serialization formats support multiple different types of asymmetric keys and will return an instance of the appropriate type. You should check that the returned key matches the type your application expects when using these methods."

I propose that the type of the returned key should be checked and appropriate errors raised if the key type is not supported. This would inform the user that the problem they are facing is not a bug in celery or their implementation, but rather that their certificates are not supported by celery.

# Checklist

- [X] I have verified that the issue exists against the `master` branch of Celery.
- [X] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [X] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [X] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- None that I could find

#### Possible Duplicates

- None that I could find

## Environment & Settings
```
$ celery --version
5.0.5 (singularity)
```

`cryptography==37.0.4`

# Steps to Reproduce
```
app = Celery('test', include=[])
broker_use_ssl = {
        'keyfile': 'broker_client.key',  # private key is ECDSA signed
        'certfile': 'broker_client.crt',
        'ca_certs': 'root.pem',
        'cert_reqs': ssl.CERT_REQUIRED
}

app.conf.update(
        broker_use_ssl=broker_use_ssl,
        security_key='private.key',
        security_certificate='public.crt',
        security_cert_store='security_store/*.pem
)

app.setup_security()
app.start()
```
This should result in traceback
```
 [2022-07-22 14:16:20,309: CRITICAL/MainProcess] Unrecoverable error: EncodeError(SecurityError("Unable to serialize: TypeError('catching classes that do not inherit from BaseException is not allowed')"))

 Traceback (most recent call last):
   File "/venv/lib/python3.8/site-packages/celery/security/utils.py", line 24, in reraise_errors
     yield
   File "/venv/lib/python3.8/site-packages/celery/security/key.py", line 32, in sign
     return self._key.sign(ensure_bytes(data), padd, digest)
 TypeError: sign() takes 3 positional arguments but 4 were given
 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/venv/lib/python3.8/site-packages/celery/security/utils.py", line 24, in reraise_errors
     yield
   File "/venv/lib/python3.8/site-packages/celery/security/serialization.py", line 39, in serialize
     signature=self._key.sign(body, self._digest),
   File "/venv/lib/python3.8/site-packages/celery/security/key.py", line 32, in sign
     return self._key.sign(ensure_bytes(data), padd, digest)
   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
     self.gen.throw(type, value, traceback)
   File "/venv/lib/python3.8/site-packages/celery/security/utils.py", line 25, in reraise_errors
     except errors as exc:
 TypeError: catching classes that do not inherit from BaseException is not allowed
... Above type error repeated many times ...
```

**Comment by auvipy** [comment]
TypeError: catching classes that do not inherit from BaseException is not allowed -- based on this can you work on intended fix?

**Comment by qrmt** [comment]
@auvipy I can work on a fix. As far as I can see, only `cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey` works with the `PrivateKey.sign` method, in which case checking it would be enough to check the returned key type and raise ValueError (which is correctly caught by `reraise_errors` context manager) if it is not of instance `rsa.RSAPrivateKey`. If this seems like a good solution to you, I'll create a pull request.

**Comment by auvipy** [comment]
you can come with a failing test and a possible fix, we can discuss there
