### ISSUE TITLE
Visibility timeout set in celery config does not work, celery still using the default 1 hour 

### ISSUE THREAD

**Issue by la-luo-unit21** [celery/celery#7651]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

Here is how we write the configs file:
```
result_expires = 60
task_acks_late = True  # enables retry on task failure
worker_prefetch_multiplier = 1  # reserving one task at a time
accept_content = ['json']
result_extended = True
broker_transport_options = {
    'queue_order_strategy': 'round_robin',
    'visibility_timeout': 7200  # by seconds, 2 hours
}
task_send_sent_event = True
```
Here is how we configure the worker:
```
        celery = Celery(
            __name__,
            broker=config.CELERY_BROKER_URL,
            backend=config.CELERY_RESULT_BACKEND
        )

        os.environ.setdefault(
            'CELERY_CONFIG_MODULE',
            'celeryconfigs.default'
        )
        celery.config_from_envvar('CELERY_CONFIG_MODULE')
        celery.conf.ONCE = {
            'backend': 'celery_once.backends.Redis',
            'settings': {
                'url': config.CELERY_BROKER_URL,
                'default_timeout': 60 * 60
            }
        }
```
However, tasks running long still get redelivered after 1 hour as the default visibility timeout, not 2 hours as we set. We are following the docs https://docs.celeryq.dev/en/stable/userguide/configuration.html#broker-transport-options What could we possibly miss?
#### Possible Duplicates

- None

# Description

# Suggestions

**Comment by andyzheung** [comment]
do you solve this problem? @la-luo-unit21

**Comment by la-luo-unit21** [comment]
> do you solve this problem? @la-luo-unit21

Hi we are still experiencing this and see if someone can shed some light here

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/7696 is a duplicate

**Comment by auvipy** [comment]
you are using redis or SQS transports right? and this is happening in 5.3.0b1?

**Comment by srijan-scanova** [comment]
Hi there, I'm using celery with SQS and having the same issue with the `countdown` 30 min in `apply_async` args. Please, if you could prioritise this bug, then this would be a great help!

**Comment by sVathis** [comment]
After a lot of testing I found that in order changes in  `visibility_timeout` value to take effect, one must set it all, celery config, result backend & transport options, as follows :
`    visibility_timeout = 600
    result_backend_transport_options = broker_transport_options = {
    'visibility_timeout': 600
    }
`

**Comment by auvipy** [comment]
> After a lot of testing I found that in order changes in `visibility_timeout` value to take effect, one must set it in all, celery config, result backend & transport options, as follows : ` visibility_timeout = 600` `result_backend_transport_options = broker_transport_options = { 'visibility_timeout': 600 }` So the reported behavior might not be a product defect per se, just lack of proper documentation

would you mind sending a PR to improve the documentation?

**Comment by pangyuteng** [comment]
To those using rabbitmq as broker, please checkout the "Warning" section under "Calling - ETA and Countdown".
https://docs.celeryq.dev/en/stable/userguide/calling.html#eta-and-countdown
Due to rabbitmq version updates, your rabbitmq config may need to be updated to bump the consumer timeout to a very large value, e.g. `consumer_timeout = 31622400000`.

**Comment by nguyenvanhuybk99** [comment]
```python
import datetime as dt
import time
import numpy as np
import tqdm
from celery import Celery
from kombu import Queue, Exchange

app = Celery(
    f"Celery app",
    broker= "redis://localhost:6379/0",
    backend="redis://localhost:6379/1",
)
app.conf.update(
    task_acks_late=True,  # ack only when task is finished
    visibility_timeout=14400,  # 4 hours
    worker_pool_restarts=True,  # restarting by remote control
    worker_max_tasks_per_child=1,
    worker_max_memory_per_child=1024 * 1024,  # 1GB
    worker_prefetch_multiplier=1,  # prefetch 1 task per worker
    worker_concurrency=10,  # will be overridden by autoscale
    broker_heartbeat=60,
    broker_connection_retry=True,
    broker_connection_retry_on_startup=True,
    broker_connection_max_retries=0,
    broker_connection_timeout=10,
    broker_transport_options={"visibility_timeout": 14400},  # 4 hours
    result_backend_transport_options={"visibility_timeout": 14400},  # 4 hours
    task_queues=(
        Queue("queue_a"),
        Queue("queue_b"),
    ),
    task_routes={
        f"run_a": {"queue": "queue_a"},
        f"run_b": {"queue": "queue_b"},
    },
)

@app.task(name="test_visibility_timeout", queue="queue_a")
def test_visibility_timeout(num: int):
    print("test_visibility_timeout started at", dt.datetime.now())
    # Custom tqdm update: only update progress every 10 seconds to reduce log spam
    with tqdm.tqdm(total=num) as pbar:
        last_update = time.time()
        last_i = 0
        for i in range(num):
            if time.time() - last_update >= 10 or i == num - 1:
                pbar.update(i + 1 - last_i)
                last_i = i + 1
                last_update = time.time()
        x = np.random.rand() + np.random.rand()
    print("test_visibility_timeout finished at", dt.datetime.now())
    return "Hello, World!"

if __name__ == "__main__":
    test_visibility_timeout.delay(int(1.2e10))
``` 

```log
[2025-10-17 08:19:52,377: WARNING/ForkPoolWorker-1] 
 79%|#######8  | 39274011342/50000000000 [1:00:20<16:45, 10670401.99it/s]
[2025-10-17 08:19:55,863: WARNING/ForkPoolWorker-3] 
 27%|##6       | 26666119417/100000000000 [41:20<1:54:32, 10670580.93it/s]
[2025-10-17 08:20:02,377: WARNING/ForkPoolWorker-1] 
 79%|#######8  | 39382022702/50000000000 [1:00:30<16:31, 10709558.59it/s]
[2025-10-17 08:20:05,863: WARNING/ForkPoolWorker-3] 
 27%|##6       | 26773413227/100000000000 [41:30<1:54:11, 10688158.55it/s]
[2025-10-17 08:20:12,377: WARNING/ForkPoolWorker-1] 
 79%|#######8  | 39489799757/50000000000 [1:00:40<16:19, 10729938.98it/s]
[2025-10-17 08:20:15,864: WARNING/ForkPoolWorker-3] 
 27%|##6       | 26881819965/100000000000 [41:40<1:53:31, 10733850.45it/s]
[2025-10-17 08:20:16,077: INFO/MainProcess] Task test_visibility_timeout[c54e735a-48e5-40b2-9e6b-f03c33308bab] received
[2025-10-17 08:20:16,078: WARNING/ForkPoolWorker-2] test_visibility_timeout started at
[2025-10-17 08:20:16,079: WARNING/ForkPoolWorker-2]  
[2025-10-17 08:20:16,079: WARNING/ForkPoolWorker-2] 2025-10-17 08:20:16.078829
[2025-10-17 08:20:16,080: WARNING/ForkPoolWorker-2] 
  0%|          | 0/50000000000 [00:00<?, ?it/s]
[2025-10-17 08:20:22,377: WARNING/ForkPoolWorker-1] 
 79%|#######9  | 39597100869/50000000000 [1:00:50<16:09, 10729928.71it/s]
[2025-10-17 08:20:25,864: WARNING/ForkPoolWorker-3] 
 27%|##6       | 26987980178/100000000000 [41:50<1:53:44, 10698436.08it/s]
[2025-10-17 08:20:26,081: WARNING/ForkPoolWorker-2] 
  0%|          | 107399182/50000000000 [00:10<1:17:25, 10739902.07it/s]
[2025-10-17 08:20:32,378: WARNING/ForkPoolWorker-1] 
 79%|#######9  | 39701813615/50000000000 [1:01:00<16:06, 10652271.92it/s]
[2025-10-17 08:20:35,864: WARNING/ForkPoolWorker-3] 
 27%|##7       | 27093002309/100000000000 [42:00<1:54:12, 10639498.02it/s]
[2025-10-17 08:20:36,081: WARNING/ForkPoolWorker-2] 
  0%|          | 215971186/50000000000 [00:20<1:16:45, 10808725.81it/s]
[2025-10-17 08:20:42,378: WARNING/ForkPoolWorker-1] 
 80%|#######9  | 39807507343/50000000000 [1:01:10<15:59, 10627339.44it/s]
[2025-10-17 08:20:45,864: WARNING/ForkPoolWorker-3] 
 27%|##7       | 27198869104/100000000000 [42:10<1:54:12, 10623583.78it/s]
```

Hi guys, I still have visibility_timeout issue

1. I have 1 heavy tasks that need to run in 1.2 hours
2. After run in 1 hour, the redis redelivery that task to celery workers. At that time celery workers serve 2 task is same
3. How can I adjust the visibility_timeout to 4 hours correctly?
You can see the log, after 1 hour, ForkPoolWorker-1 still running but ForkPoolWorker-2 is spawn to do the same job as ForkPoolWorker-1
Thank you.

**Comment by nguyenvanhuybk99** [comment]
Resolved with re-deploy redis to clear cache
