### ISSUE TITLE
Celery 5.3.0b1: billiard 4.0.1 causes a problem

### ISSUE THREAD

**Issue by woutdenolf** [celery/celery#7672]
See https://github.com/celery/billiard/issues/371

So either `billiard < 4.0.1` or make a new `billiard` release with a fix.

**Comment by auvipy** [comment]
will release 4.0.2 tomorrow

**Comment by woutdenolf** [comment]
I can confirm the issue is fixed with the new billiard release. Thanks @auvipy !
