### ISSUE TITLE
DynamoDB backend calls CreateTable API for an existed table raise AWS cost

### ISSUE THREAD

**Issue by lyajedi** [celery/celery#7710]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/issues/6622

#### Possible Duplicates

- None

# Brief Summary
https://github.com/celery/celery/blob/v5.2.7/celery/backends/dynamodb.py#L204
This always calls CreatTable even the table existed already.
Each call will have an AWS CloudTrail management event for CreateTable API call with ResourceInUseException error.
Each CouldTrail management event cost 0.00002 USD in AWS US West (Oregon) region.
I have 10M+ tasks everyday and they produce 10M+ such events, and AWS charges me for 200+ USD.

# Design

## Architectural Considerations

None

## Proposed Behavior
Just like what proposed in https://github.com/celery/celery/issues/6622, check existence of table with another boto3 call first instead of just calling create table

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
I am going to close this as duplicate, let continue discussion there? can you try to contribute the fix?
