### ISSUE TITLE
completed_count reports only successfully completed tasks

### ISSUE THREAD

**Issue by emilroz** [celery/celery#7713]
Not sure if that's on purpose but it looks like `completed_count` only takes into account the tasks that have completed successfully:

https://github.com/celery/celery/blob/3db7c9dde9a4d5aa9c0eda8c43a219de1baa9f02/celery/result.py#L633

Would it make more sense to report:
```
return sum(int(result.ready()) for result in self.results)
```
the task count in the "ready" state?

Happy to open a PR if that's an acceptable change.

**Comment by thedrow** [comment]
One might say that a task has been completed only if it hasn't failed.
Otherwise, the execution of the task is halted and it is not completed.

I don't think we should change the public API between minor versions but I'm open to amending the documentation.

**Comment by emilroz** [comment]
Sounds good to me. I'm more than happy to contribute the changes.

**Comment by emilroz** [comment]
:thumbsup:

**Comment by auvipy** [comment]
or should we keep this open for prospective future API changes?
