### ISSUE TITLE
EagerResult doesn't seem to poplate name

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#7715]
Sometimes I run my tasks with `CELERY_TASK_ALWAYS_EAGER` to aid debugging, it seems like the `name` property of EagerResult isn't populated, which makes this sort of investigation more tricky.

I have some code I use to list my tasks in a django app, and part of this is to grab the task name.

When running eagerly, the EagerResult task status is SUCCESS, so I would have expected `name` to be available at this point.

**Comment by auvipy** [comment]
do you have any failing test/implementation detail in mind to share?

**Comment by stuaxo** [comment]
I'll see what I can find, I'm no longer working at the organisation I did that project for, but it is open source so I still have that work and can share it :)

**Comment by auvipy** [comment]
BTW, I am a contractor too

**Comment by stuaxo** [comment]
I really wish that every contract had a budget to put towards open source projects they use - I did raise this @ the last place, but probably not in the right places.

The furthest I've got is submitting patches to projects used.

**Comment by auvipy** [comment]
we have to revert this for a regression.
