### ISSUE TITLE
long latency with redis single worker with no prefetch and acks late

### ISSUE THREAD

**Issue by shahar-lev** [celery/celery#7718]
# Checklist
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information
- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings
**Celery version**: 5.3.0b1 (dawn-chorus)
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.0b1 (dawn-chorus) kombu:5.3.0b1 py:3.9.6
            billiard:3.6.4.0 redis:4.3.4
platform -> system:Darwin arch:64bit
            kernel version:20.6.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost/'
deprecated_settings: None
worker_concurrency: 1
worker_prefetch_multiplier: 1
task_acks_late: True
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies
* **Python Version**: 3.9.6
* **Celery Version**: 5.3.0b1
* **Kombu Version**: 5.3.0b1
* **Broker Version**: redis 7.0.2
* **Result Backend Version**: redis 7.0.2
* **OS and/or Kernel Version**: MacOS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: RELEASE_ARM64_T8101 arm64 arm Darwin
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages
<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.1.1
anyio==3.6.1
async-timeout==4.0.2
billiard==3.6.4.0
celery @ file:///Users/shahar/work/sources/celery
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
Cython==0.29.32
Deprecated==1.2.13
fastapi==0.78.0
flower==1.0.0
greenlet==1.1.2
h11==0.13.0
humanize==4.2.0
idna==3.3
kombu==5.3.0b1
packaging==21.3
prometheus-client==0.14.1
prompt-toolkit==3.0.30
pydantic==1.9.1
pyparsing==3.0.9
pytz==2022.2.1
redis==4.3.4
six==1.16.0
sniffio==1.2.0
starlette==0.19.1
tornado==6.1
typing-extensions==4.2.0
uvicorn==0.18.1
vine==5.0.0
wcwidth==0.2.5
wrapt==1.14.1
```

</p>
</details>

### Other Dependencies

<details>
<p>
using redis 7.0.2 as broker and backend.
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery
import time

app = Celery('bug', broker='redis://localhost', backend='redis://localhost')
app.conf.worker_concurrency = 1
app.conf.worker_prefetch_multiplier = 1
app.conf.task_acks_late = True

@app.task
def func():
    time.sleep(1)

def func_duration():
    ts = time.perf_counter()
    func.delay().get()
    return time.perf_counter() - ts 

def main(count=5):
    func_duration()
    latency = (sum(func_duration() for _ in range(count)) / count) - 1
    print(f'{latency}')

if __name__ == '__main__':
    main()
```

</p>
</details>

# Expected Behavior

I expect that enabling `task_acks_late` will not increase the latency by a factor of 10.
 
# Actual Behavior

Running the script with acks late disabled results in a ~20ms latency.
Running the script iwht acks late enabled results in a ~500ms latency.

# Analysis

Running profiler reveals that our single worker, between sending the result of the previous task and popping the next task, spends most of its time in the event loop's poll:  https://github.com/celery/kombu/blob/master/kombu/asynchronous/hub.py#L315

The event loop will usually wait the default timeout of one whole second (when there's no pending event), even in the case where popping the next task should happen as soon as possible.

Changing the order in the event loop so that the tick callbacks will be executed after the todo callbacks seems to resolve the issue.

**Comment by auvipy** [comment]
thanks
