### ISSUE TITLE
RFE: update for `billiard` 4.x

### ISSUE THREAD

**Issue by kloczek** [celery/celery#7719]
https://github.com/celery/celery/blob/d4146ebd5afa7c7078da68be48df1c089d202e62/setup.cfg#L26-L27

**Comment by auvipy** [comment]
thanks for the report

**Comment by kloczek** [comment]
Is it anythig else which needs to be finished before release final 5.3.0? (just asking) 🤔

**Comment by auvipy** [comment]
yeah some new API bugs are ironing out
