### ISSUE TITLE
non working example of using celery_worker pytest fixture (celery.exception.NotRegistered)

### ISSUE THREAD

**Issue by hq9000** [celery/celery#7750]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

the part of the documentation describing `celery_app` and `celery_worker` fixtures has a test example that doesn't pass:

https://github.com/celery/celery/blame/master/docs/userguide/testing.rst#L152

![image](https://user-images.githubusercontent.com/21345604/189285498-fe7efa52-3a6e-45ae-bddf-a4610bc8ddff.png)

if we use this test as it is, it will fail because the task does not get registered in the worker:

![image](https://user-images.githubusercontent.com/21345604/189286212-410e8958-f55c-4d59-b830-755f94f7a2c2.png)

`celery.exceptions.NotRegistered: 'test_create_task.mul'`

# Suggestions

the problem is that executed this way, the tasks are not registered in the worker. The way I found working is to override the `celery_app` fixture:

```python
from celery import Celery
from celery.contrib.testing.worker import TestWorkController
from celery.result import AsyncResult
import pytest

@pytest.fixture
def celery_app(celery_app: Celery):

    @celery_app.task(name='xyz')
    def mul(x, y):
        """register a task named 'test_create_task.mul'"""
        return x * y

    return celery_app



def test_create_task(celery_app: Celery, celery_worker: TestWorkController):    
    result: AsyncResult = celery_app.send_task('xyz', kwargs = {"x": 2, "y": 2})
    result.wait()
    assert result.get() == 4
```

![image](https://user-images.githubusercontent.com/21345604/189286546-3977cede-1719-4cc7-b8af-42e52fc536d6.png)

**Comment by auvipy** [comment]
would you mind sending a patch to improve this?

**Comment by hq9000** [comment]
> would you mind sending a patch to improve this?

will do in a couple of days
