### ISSUE TITLE
Arguments of type `date` are being passed as `datetime` to the task.

### ISSUE THREAD

**Issue by mvaled** [celery/celery#7754]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.0b1 (dawn-chorus) kombu:5.3.0b1 py:3.10.5
            billiard:4.0.2 redis:4.3.4
platform -> system:Linux arch:64bit, ELF
            kernel version:5.15.60-1-MANJARO imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: 'redis://localhost:6379//'
task_acks_late: True
deprecated_settings: None
```

The actual commit of `celery` is ebdf9e53d4b5edd9aa66cb7faf413776dd5d74a5 (see PR #7755).

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.8
* **Minimal Celery Version**: master, 5.3.0b1
* **Minimal Kombu Version**: 5.3.0b1
* **Minimal Broker Version**: Redis 5, 6
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: N/A
* **Minimal Broker Client Version**: redis==4.3, hiredis==2.0
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.1.1
asttokens==2.0.8
async-timeout==4.0.2
backcall==0.2.0
billiard==4.0.2
-e git+https://gitlab.merchise.org/merchise/celery.git@ebdf9e53d4b5edd9aa66cb7faf413776dd5d74a5#egg=celery
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
decorator==5.1.1
Deprecated==1.2.13
executing==1.0.0
hiredis==2.0.0
ipython==8.5.0
jedi==0.18.1
kombu==5.3.0b1
matplotlib-inline==0.1.6
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.31
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
pytz==2022.2.1
redis==4.3.4
six==1.16.0
stack-data==0.5.0
traitlets==5.3.0
vine==5.0.0
wcwidth==0.2.5
wrapt==1.14.1
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>

<p>The client sends an argument of type `datetime.date`, but the
task receives an instance of `datetime.datetime`.

I have updated the `app/myapp.py` example with a simple `echo` task (see
#7755) like this:

```python
@app.task
def echo(d):
    print(repr(d))
```

I'm running the worker like this:

```bash
$ celery_broker_url="redis://localhost/" python myapp.py worker -l INFO
```

And the client like this:

```bash
$ celery_broker_url="redis://localhost/" python -c "import myapp, datetime; myapp.echo.delay(datetime.date.today())"
```

</p>
</details>

# Expected Behavior

The worker should receive a `datetime.date`.  Expected log:

```
[2022-09-11 12:16:52,824: WARNING/ForkPoolWorker-8] datetime.date(2022, 9, 11)
```

# Actual Behavior

The worker receives a `datetime.datetime`.  Actual log:

```
[2022-09-11 12:16:52,823: INFO/MainProcess] Task myapp.echo[6e6eabbf-b4ad-4a21-aee9-69b27d6767dd] received
[2022-09-11 12:16:52,824: WARNING/ForkPoolWorker-8] datetime.datetime(2022, 9, 11, 0, 0)
[2022-09-11 12:16:52,824: INFO/ForkPoolWorker-8] Task myapp.echo[6e6eabbf-b4ad-4a21-aee9-69b27d6767dd] succeeded in 0.00020399800268933177s: None
```

**Comment by mvaled** [comment]
@thedrow 

Hum... I tried to reproduce the issue with kombu alone (i.e a simple modification of the [simple task queue](https://github.com/celery/kombu/tree/master/examples/simple_task_queue); I will push it) but there `date`s were `date`s and `datetime`s, `datetime`s. 

Diff to the example is:

```diff
diff --git a/examples/simple_task_queue/client.py b/examples/simple_task_queue/client.py
index bc2d180f..e4cc9379 100644
--- a/examples/simple_task_queue/client.py
+++ b/examples/simple_task_queue/client.py
@@ -1,3 +1,4 @@
+from datetime import date, datetime
 from kombu.pools import producers
 
 from .queues import task_exchange
@@ -27,6 +28,8 @@ if __name__ == '__main__':
 
     from .tasks import hello_task
 
-    connection = Connection('amqp://guest:guest@localhost:5672//')
-    send_as_task(connection, fun=hello_task, args=('Kombu',), kwargs={},
+    connection = Connection('redis://localhost')
+    send_as_task(connection, fun=hello_task, args=(datetime(2022, 9, 22, 1, 0),), kwargs={},
+                 priority='high')
+    send_as_task(connection, fun=hello_task, args=(date(2022, 9, 22),), kwargs={},
                  priority='high')
diff --git a/examples/simple_task_queue/tasks.py b/examples/simple_task_queue/tasks.py
index 2810f7a8..de56dd90 100644
--- a/examples/simple_task_queue/tasks.py
+++ b/examples/simple_task_queue/tasks.py
@@ -1,2 +1,2 @@
 def hello_task(who='world'):
-    print(f'Hello {who}')
+    print(f'Hello {who}', type(who))
diff --git a/examples/simple_task_queue/worker.py b/examples/simple_task_queue/worker.py
index 66ad9c30..1c8b4d0b 100644
--- a/examples/simple_task_queue/worker.py
+++ b/examples/simple_task_queue/worker.py
@@ -36,7 +36,7 @@ if __name__ == '__main__':
     # setup root logger
     setup_logging(loglevel='INFO', loggers=[''])
 
-    with Connection('amqp://guest:guest@localhost:5672//') as conn:
+    with Connection('redis://localhost') as conn:
         try:
             worker = Worker(conn)
             worker.run()
```

And the prints from the worker are:

```
Connected to redis://localhost:6379//
Got task: hello_task(datetime.datetime(2022, 9, 22, 1, 0))
Hello 2022-09-22 01:00:00 <class 'datetime.datetime'>
Got task: hello_task(datetime.date(2022, 9, 22))
Hello 2022-09-22 <class 'datetime.date'>
```

That's why I assumed it was a celery issue.  In any case, this is a new behavior (and it's actually breaking some of my tasks).  Celery 5.2 passes `date`s as dates. 

Should we open an issue in kombu?  Is there any rationale to "upgrade" a `date` to `datetime`?

**Comment by mvaled** [comment]
@thedrow @auvipy 

I can confirm that after changing the `JSONEncoder` with this:

```patch
diff --git a/kombu/utils/json.py b/kombu/utils/json.py
index a5a020c1..95a05a68 100644
--- a/kombu/utils/json.py
+++ b/kombu/utils/json.py
@@ -38,10 +38,13 @@ class JSONEncoder(_encoder_cls):
             return reducer()
         else:
             if isinstance(o, dates):
+                marker = "__date__"
                 if not isinstance(o, datetime):
                     o = datetime(o.year, o.month, o.day, 0, 0, 0, 0)
+                else:
+                    marker = "__datetime__"
                 r = o.isoformat()
-                return {"datetime": r, "__datetime__": True}
+                return {"datetime": r, marker: True}
             elif isinstance(o, times):
                 return o.isoformat()
             elif isinstance(o, uuid.UUID):
@@ -71,6 +74,8 @@ def dumps(s, _dumps=json.dumps, cls=None, default_kwargs=None, **kwargs):
 
 def object_hook(dct):
     """Hook function to perform custom deserialization."""
+    if "__date__" in dct:
+        return datetime.datetime.fromisoformat(dct["datetime"]).date()
     if "__datetime__" in dct:
         return datetime.datetime.fromisoformat(dct["datetime"])
     if "__bytes__" in dct:
```

Celery regains the `date`s being `date`s property... I'm going to open a PR in kombu and close the current PR here.

**Comment by mvaled** [comment]
@thedrow @auvipy I've created PR https://github.com/celery/kombu/pull/1598

**Comment by auvipy** [comment]
thanks!
