### ISSUE TITLE
redis password parsing error

### ISSUE THREAD

**Issue by fuyanghulin** [celery/celery#7864]
My project redis password ends with "#", As shown below.
`redis://:123456xxx#@192.168.1.100:6379/0`
When I boot, an exception occurs as follows：
`ValueError: Port could not be cast to integer value as '123456xxx' `

**Comment by auvipy** [comment]
you should have open a discussion first with more detail to reproduce the issue

**Comment by fuyanghulin** [comment]
caused by ''Python38/Lib/urllib/parse.py'
