### ISSUE TITLE
Update the solar function docs to reflect that it accepts floats and not only ints

### ISSUE THREAD

**Issue by Kaju-Bubanja** [celery/celery#7875]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary
The docs for celery.schedules.solar state that long and lat are ints. This triggers a warning for some linters and also the example on the page uses the function with floats:

```
lat (int): The latitude of the observer.
lon (int): The longitude of the observer.
```

```
from celery.schedules import solar

app.conf.beat_schedule = {
    # Executes at sunset in Melbourne
    'add-at-melbourne-sunset': {
        'task': 'tasks.add',
        'schedule': solar('sunset', -37.81753, 144.96715),
        'args': (16, 16),
    },
}
```

# Design

## Architectural Considerations

None

## Proposed Behavior
Change the docstring to float

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
can you share any testcase/example? and what warnings you are facing?

**Comment by Kaju-Bubanja** [comment]
@auvipy The example is in the issue...

**Comment by auvipy** [comment]
can you please contribute?

**Comment by max-muoto** [comment]
Fixing this in https://github.com/celery/celery/pull/8114.
