### ISSUE TITLE
ignore_result in task-decorator is ignored

### ISSUE THREAD

**Issue by der-joel** [celery/celery#7939]
Occurring in celery 5.2.7

When using celery with redis result-backend, passing `ignore_result` to the task decorator has no influence on the task result being stored.

```python3
@celery.task(ingore_result=True)
def task_2(*args, **kwargs):
    return "t2 return"

# these calls will create a celery-task-meta-<task_id> key in the corresponding redis result-backend
task_2.apply_async(ignore_result=False)
task_2.apply_async()
# this call will not store anything in the result backend
task_2.apply_async(ignore_result=True)
```

According to the [docs](https://docs.celeryq.dev/en/latest/userguide/tasks.html#ignore-results-you-don-t-want) the option precedence order is:

1.  Global [task_ignore_result](https://docs.celeryq.dev/en/latest/userguide/configuration.html#std-setting-task_ignore_result)
2.  [ignore_result](https://docs.celeryq.dev/en/latest/reference/celery.app.task.html#celery.app.task.Task.ignore_result) option
3.  Task execution option ignore_result

So i would expect `task_2.apply_async()` to ignore its result.

**Comment by Nusnus** [comment]
Did you notice the typo in `@celery.task(ingore_result=True)`?
`ingore_result` vs `ignore_result`.

Try fixing it and please report if the issue still persists.

**Comment by Nusnus** [comment]
I've tested it just for fun, and I'm pretty positive this is the reason @der-joel 

<img width="672" alt="CleanShot 2022-12-04 at 21 43 34@2x" src="https://user-images.githubusercontent.com/4662342/205511876-e6d7c1c8-f8fa-45c6-9932-7e02273025a1.png">
<img width="641" alt="CleanShot 2022-12-04 at 21 42 52@2x" src="https://user-images.githubusercontent.com/4662342/205511879-65ea8823-3ef9-4f48-a3bc-50f1e788aa1a.png">

**Comment by der-joel** [comment]
I'm officially an idiot. Tested it and can confirm that it was indeed the typo.

**Comment by auvipy** [comment]
> I'm officially an idiot. Tested it and can confirm that it was indeed the typo.

It happens! human being are prone to mistakes. from the next time please try to start with a discussion first rather then reporting an issue.

**Comment by Nusnus** [comment]
> I'm officially an idiot. Tested it and can confirm that it was indeed the typo.

Haha don't worry friend, it happens to the best of us 💪 

> It happens! human being are prone to mistakes. from the next time please try to start with a discussion first rather then reporting an issue.

You can also try to replicate whatever issue you have with a unit/integration test, this could speed up fixing it or help you find your own stuff independently ;)
