### ISSUE TITLE
Documentation for worker_direct exchange is outdated

### ISSUE THREAD

**Issue by alessio-b2c2** [celery/celery#7972]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/issues/2492

#### Possible Duplicates

- None

# Description

The documentation for the exchange to use for `worker_direct` is outdated.
The documentation says to use `C.dq`: https://docs.celeryq.dev/en/stable/userguide/configuration.html?highlight=worker_direct#worker-direct:~:text=using%20the%20C.dq%20exchange
But the codebase uses `C.dq2`: https://github.com/celery/celery/blob/f67931b998113c5cce334d771722d51d6a49d6e5/celery/utils/nodenames.py#L12

# Suggestions

Update the docs to use `C.dq2`

**Comment by auvipy** [comment]
would you mind contributing this doc improvement?

**Comment by alessio-b2c2** [comment]
Done: https://github.com/celery/celery/pull/7973
