### ISSUE TITLE
Celery sucks!

### ISSUE THREAD

**Issue by venomone** [celery/celery#8000]
Celery sucks by simply don't processing jobs in a gevent pool, jobs simply dangling forever, there is no fail-safe mechanism at all. Task simply block themselves until they die in the queue blocking the whole worker, especially long-running I/O tasks. I'm really done with this crappy project, have a nice day.

**Comment by venomone** [comment]
Not to forget dying sql connection you have to fix with a hack like this:

```
def possible_reconnect_required():
    try:
        for name, config in settings.DATABASES.items():
            module = importlib.import_module(config["ENGINE"] + ".base")

            def ensure_connection(self):
                if self.connection is not None:
                    try:
                        with CursorWrapper(self.create_cursor(), self) as cursor:
                            cursor.execute("SELECT 1")
                        return
                    except Exception:
                        pass

                with self.wrap_database_errors:
                    self.connect()

            module.DatabaseWrapper.ensure_connection = ensure_connection
        connection.ensure_connection()
    except django.db.utils.OperationalError:
        connection.close()
        connection.connect()
```

Otherwise, tasks don't keep the connection to the DB except they are running just for a couple of seconds ...

**Comment by auvipy** [comment]
@venomone avoid doing this any further. you can gracefully open a discussion in github forum.

**Comment by auvipy** [comment]
@venomone you will get blocked if you this again ever in any open source projects.
