### ISSUE TITLE
Database results backend is serializing results with pickle

### ISSUE THREAD

**Issue by peteris-zealid** [celery/celery#8003]
Root of the problem is on this line.
https://github.com/celery/celery/blob/e54780f8003a16295ff91009f6eb380d8c0e1a06/celery/backends/database/models.py#L24

The documentation says that since version 4.0 the default for `result_serializer` is supposed to be json. It is expected that database backend would respect this default and not have pickle hard-coded.
https://docs.celeryq.dev/en/latest/userguide/configuration.html#result-serializer

Relevant investigation:
- in `celery/backends/base.py` class `BaseKeyValueStoreBackend` method `_store_result` internally calls `self.encode(meta)`.
- in `celery/backends/database/__init__.py` class `DatabaseBackend` method `_store_result` does NOT call `self.encode`.
- the inherited method `_get_result_meta` does not attempt to encode the result.
- in the whole file `celery/backends/database/__init__.py` there is no reference to `encode`.

Main issue from my perspective here is security as well as being unable to use custom serializers.

**Comment by auvipy** [comment]
yes, I think there are related PR to this https://github.com/celery/celery/pull/5907

**Comment by peteris-zealid** [comment]
You are correct. I did look at the existing issues but somehow did not find this. Sorry about that.

**Comment by auvipy** [comment]
no worries. your report was right anyway.
