### ISSUE TITLE
Receive data as dictionary when using group and chunk

### ISSUE THREAD

**Issue by hasanisaeed** [celery/celery#8009]
# Brief Summary
I have a task where I need to send more than a million records to a worker:

```python
# signature
@celery_app.task
def send_records(*args, **kwargs):
    # ....

# records are list of million dictionary data
records = [...]
CHUNK_SIZE = len(records) / 1024
group = chunks(send_records.s(), records, CHUNK_SUZE).group()
group.apply_async(queue='specific_queue')
```

The data is sent as a dictionary. But unfortunately, the dictionary is not received on the consumer side and receives it as a tuple.

For example, the following dictionary that is sent, I lose the value and only receive the keys as a tuple.
```python 
# Data sent:
{
    'name': 'John',
    'age': 31
}

# Received amount:
('name', 'age')

```

> can I have the dictionary in consumer side?

**Comment by auvipy** [comment]
please open a discussion instead of opening issue.
