### ISSUE TITLE
Deprecate pytz and use zoneinfo

### ISSUE THREAD

**Issue by wongcht** [celery/celery#8078]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the if the same enhancement was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

Considering `pytz` is deprecating in Django and will be removed in 5.0, suggest follow approaches in Django
- use `zoneinfo` to replace `pytz`
- backport by `backports.zoneinfo`

Ref: https://docs.djangoproject.com/en/4.1/releases/4.0/

# Design

## Architectural Considerations

None

## Proposed Behavior

No changes

## Proposed UI/UX

No changes

## Diagrams

N/A

## Alternatives

None

**Comment by wongcht** [comment]
I'm happy to help develop, thanks!

**Comment by auvipy** [comment]
ping me with your draft PR please when it is in progress
