### ISSUE TITLE
Deprecate iso8601 module

### ISSUE THREAD

**Issue by wongcht** [celery/celery#8080]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the if the same enhancement was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

`celery.utils.iso8601` is historic module which `.parse_iso8601()` can be replaced by `datetime.datetime.fromisoformat()` as Python 3.7 or above is now supported.

Suggest deprecate this module and use `datetime.datetime.fromisoformat()` internally.

# Design

## Architectural Considerations

None

## Proposed Behavior

- `iso8601` module is still usable before v6.0.0, but with addition of deprecation warning
- remove `iso8601` module in v6.0.0
- replace all usage of `parse_iso8601()` in the library by `datetime.datetime.fromisoformat`, with compatibility of Python 3.7 to 3.11

## Proposed UI/UX

N/A

## Diagrams

N/A

## Alternatives

None

**Comment by wongcht** [comment]
#8081 submitted PR

**Comment by auvipy** [comment]
if that is the case lets do it.
