### ISSUE TITLE
sent_task to non durable queue

### ISSUE THREAD

**Issue by oleks-popovych** [celery/celery#8097]
I'm creating queues at runtime. So far everything works. 

Currently I'm trying to optimize my solution and delete queues that not in use already. I'm relying on `auto-delete` feature of rabbitmq, which deletes queue if there are no consumers. On the other hand I don't want it to be durable.

When I use `celery.send_task` I get an error that celery expect queue to be durable, is there a way to inform celery that it is not. I assume I should pass something into `celery.send_task`, but so far I did not found anything

 

> When you define a queue, mark it as non-durable. Refer to the [docs](http://docs.celeryproject.org/en/latest/userguide/routing.html#defining-queues) to understand how to define queues.
> The constructor of Queue accepts a durable argument which in your case should be set to False e.g. `Queue('myqueue`, durable=False)`.

_Originally posted by @thedrow in https://github.com/celery/celery/issues/4538#issuecomment-366727088_

**Comment by auvipy** [comment]
I am not sure opening a new issue was imminent?

**Comment by oleks-popovych** [comment]
@auvipy sorry, my bad. I misunderstood github's interface
