### ISSUE TITLE
test in timer2.py needs adjusting to suite pypy

### ISSUE THREAD

**Issue by idella** [celery/celery#811]
Initially filed in pypy.org;     https://bugs.pypy.org/issue1187
- Testing of dev-python/celery-2.5.5 with PyPy 1.8 (Python 2.7)...
  ............................................................................................................................................
  ....................................................................SSSSSSSSSSSSSSSSSE..............................
  - Tokyo Tyrant not installed. Will not execute related tests.
    SSSSS.............................................S.S..........S...........SSSSSS...S...............SSSS...............
    .............SSSSSSSSSSSSSSSSSS.........................................................................................
    ...............................................................................................................................................
    ...............................................................................................................................

Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/celery-2.5.5/work/celery-2.5.5/celery/utils/timer2.py", line 190, in apply_entry
    entry()
  File "/usr/lib64/pypy1.8/site-packages/mock.py", line 983, in **call**
    return _mock_self._mock_call(_args, *_kwargs)
  File "/usr/lib64/pypy1.8/site-packages/mock.py", line 1038, in _mock_call
    raise effect
ValueError
................................................................................................................................................
# ...............................................
## ERROR: test_cleanup (celery.tests.test_backends.test_mongodb.TestBackendMongoDb)

Traceback (most recent call last):
  File "/usr/lib64/pypy1.8/site-packages/mock.py", line 1224, in patched
    return func(_args, *_keywargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/celery-2.5.5/work/celery-2.5.5/celery/tests/test_backends/test_mongodb.py", line 275, in test_cleanup
    self.backend.cleanup()
  File "/mnt/gen2/TmpDir/portage/dev-python/celery-2.5.5/work/celery-2.5.5/celery/backends/mongodb.py", line 203, in cleanup
    "$lt": self.app.now() - self.expires,
  File "/usr/lib64/pypy1.8/lib_pypy/datetime.py", line 1857, in **sub**
    if not isinstance(other, datetime):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

---

Ran 876 tests in 28.491s

FAILED (SKIP=54, errors=1)
- ERROR: dev-python/celery-2.5.5 failed (test phase):
-   Testing failed with PyPy 1.8 (Python 2.7) in testing() function

code that appears to trigger this fail is

  File "/usr/lib64/pypy1.9/site-packages/mock.py", line 983, in **call**
    return _mock_self._mock_call(_args, *_kwargs)
  File "/usr/lib64/pypy1.9/site-packages/mock.py", line 1038, in _mock_call

from    celery-2.5.5/work/celery-2.5.5/celery/utils/timer2.py", line 190, in apply_entry

From maintainers of pypy from issue filed; last comment entered;

The celery maintainers already adapted their code to support pypy.  I suppose 
they could take this one as well...
Replacing standard objects by something that does not work is never a good idea, 
unexpected parts of the interpreter may need them.

**Comment by webknjaz** [comment]
FTR I've faced the very same issue in aio-libs/aiohttp, caused by mocking datetime.datetime.
PyPy3.5 v5.10.1
It fails on is_instance call inside of `datetime.datetime.__sub__()`, it doesn't fail in CPython, because it has C-implementation, while PyPy has pure-python version of it.

**Comment by auvipy** [comment]
care to send a pr on master?

**Comment by webknjaz** [comment]
I just posted an explanation, because I met this issue in aiohttp, but googling lead me here. I posted it so if someone else faces it and lands here they would know the answer. My "fix" was to skip the test under PyPy. Though I saw someone on StackOverflow fixing this with subclassing.

**Comment by auvipy** [comment]
great!
