### ISSUE TITLE
Task key error when broker is shutting down in Celery

### ISSUE THREAD

**Issue by YoonseongHeo** [celery/celery#8165]
## Environment & Settings
**Celery version**: 5.2.7
**Python version**: 3.11.0
**RabbitMQ version**: 3.11.11

## Problem
- runner : Application that sends_task 6 worker_task to worker queue every minute
- Worker: An application that executes worker_task accumulated in the worker queue

When RabbitMQ, which is being used as a broker in the structure, is rebooted due to a resource problem, 2 tasks out of 6 send_task in the runner have a key error and the remaining 4 tasks are performed well.

The log for the contents is as follows.

```
Received unregistered task of type 'worker_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[["2023-03-28T23:56:00", "test"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (109b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'worker_task', 'id': '6e971bee-466c-4c3d-9e2c-b8bac384769a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '6e971bee-466c-4c3d-9e2c-b8bac384769a', 'parent_id': None, 'argsrepr': "[datetime.datetime(2023, 3, 28, 23, 56), 'test']", 'kwargsrepr': '{}', 'origin': 'gen7@runner', 'ignore_result': False}

The delivery info for this task is:
{'consumer_tag': 'None9', 'delivery_tag': 142, 'redelivered': False, 'exchange': '', 'routing_key': 'worker'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'worker_task'
```

**Comment by Savisrisundar** [comment]
Hi,
the problem is that the task has not been registered, when you are running your file the worker is not able to identify the location of the task so you would be getting like this 
[fastapi_test-worker-1  |
fastapi_test-worker-1  |
fastapi_test-worker-1  | [tasks]
fastapi_test-worker-1  |    ]

to solve this problem you need to give the exact location of your task in your celery command so that the task will be identified
