### ISSUE TITLE
SQLAlchemy should not be considered as non-stable result backend

### ISSUE THREAD

**Issue by mdeshmu** [celery/celery#8187]
# Checklist

- [x ] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [ x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

I have couple of questions about the [backends-and-brokers](https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/index.html) page.

1. I see under [RabbitMQ note](https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/index.html#rabbitmq), it is written,

`If more guaranteed long-term persistence is needed from the result store, consider using PostgreSQL or MySQL (through SQLAlchemy).`

Whereas under [SQLAlchemy](https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/index.html#sqlalchemy) it is written, 

`Historically, SQLAlchemy has not been the most stable result backend so if chosen one should proceed with caution.`

IMO, these are either two conflicting statements. IMO, The second statement is inaccurate & misleading considering the fact that SQLAlchemy ORM has developed a lot and is very stable. We have been using Airflow + Celery + MySQL as a result backend for more than four years without a single issue. We have been using the open-source tool Apache Superset which is totally dependent on SQLAlchemy and there are no major or consistent issues reported with SQLAlchemy in that project as well. 

IMO, SQLAlchemy should not be considered a non-stable result backend.

2. There is no configuration reference URL for SQLAlchemy like it is present for other backends. I think we can add a reference to this [configuration page section](https://docs.celeryq.dev/en/latest/userguide/configuration.html#database-backend-settings).  

# Suggestions
If you agree then I am happy to raise a PR to remove this line from the doc. 

`Historically, SQLAlchemy has not been the most stable result backend so if chosen one should proceed with caution.`

and add the above-said configuration doc reference for SQLAlchemy. 

You just have to let me know which GitHub file in this repo I have to update.

**Comment by auvipy** [comment]
yeah SQLA is now reliable back end. you can proceed with a PR

**Comment by max-muoto** [comment]
Put out a PR fixing this: https://github.com/celery/celery/pull/8188
