### ISSUE TITLE
Why does celery pin `4.4.0` as the upper limit of redis?

### ISSUE THREAD

**Issue by baseplate-admin** [celery/celery#8216]
Hi Thanks for creating Celery. Its one of the best python queue management solution.

https://github.com/celery/celery/blob/4bcac7a074c6aa1b23fcf0b89e79261735ddad0e/requirements/extras/redis.txt#L1

so it seems that celery pins `4.4.0` as the upper limit.

Which raises this CVE

![image](https://user-images.githubusercontent.com/61817579/234474726-ea3d6367-4ff1-4e4e-b211-f2169b397582.png)

is there any particular reason for this upper pin?

**Comment by auvipy** [comment]
1. this is a false positive CVE as celery use python 3.7+
2. upgrading version cause atleast one test to fail iin kombu.

**Comment by sr-verde** [comment]
Can you please tell me why Python 3.7+ should fix this problem? I haven't found a reason.

**Comment by auvipy** [comment]
I learnt that from redis-py maintainers

**Comment by sr-verde** [comment]
Thanks for your fast answer but that sounds like "trust me bro". Is there any public source for this information? :grimacing:

**Comment by auvipy** [comment]
https://github.com/redis/redis-py/pull/2672 and I am open to contribution to upgrade the version! trust me bro! :D

**Comment by eukreign** [comment]
This constraint makes `celery[redis]` unuseable/conflict with the latest django `channels-redis`:

```
The conflict is caused by:
    celery[redis] 5.3.0b2 depends on redis<4.4.0 and >=4.2.2; extra == "redis"
    channels-redis 4.1.0 depends on redis>=4.5.3
```

https://github.com/django/channels_redis/commit/dbf4f30177d0e10ea6eb8b14088981a42d225251

**Comment by auvipy** [comment]
contributions are welcome

**Comment by auvipy** [comment]
its fixed in main branch now
