### ISSUE TITLE
Set allow_extra_args to True in context_settings of shell and purge commands

### ISSUE THREAD

**Issue by dpdoughe** [celery/celery#8259]
# Checklist

- [ x ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [ x ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [ x ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the if the same enhancement was already implemented in the
  main branch.
- [ x ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

https://github.com/sontek/pyramid_celery/issues/101

#### Possible Duplicates

- None

# Brief Summary

The  [pyramid-celery](https://github.com/sontek/pyramid_celery) package adds `ini` and `ini-var` options to the standard commands. These allow the standard Pyramid `ini` configuration files to config Celery. With current Celery however, only the `worker`, `beat`, and `events` are able to be hooked into pyramid-celery's approach because those commands are set with.

```
context_settings={
    'allow_extra_args': True
}
```
See `beat` for example: https://github.com/celery/celery/blob/f3a2cf45a69b443cac6c79a5c85583c8bd91b0a3/celery/bin/beat.py#L11

The `shell` and `purge` commands for some reason do not have context_settings and so do not set `allow_extra_args`. See for example in `shell`, https://github.com/celery/celery/blob/f3a2cf45a69b443cac6c79a5c85583c8bd91b0a3/celery/bin/shell.py#LL82C1-L117C24

The consequence is that the `ini` command options cause errors since these are extra and unknown args to these commands. Excluding the `ini` config casues  `shell` when it comes up to not get the task registration configs and `purge` isn't able to see queues.

# Design

## Architectural Considerations

[pyramid-celery](https://github.com/sontek/pyramid_celery) is on [pypi](https://pypi.org/project/pyramid-celery). Allows you to use pyramid .ini files to configure celery and have your pyramid configuration inside celery tasks.

## Proposed Behavior

This should not affect Celery functionality, but will allow pyramid-celery to function as expected. See related issue tracked in pyramid-celery here https://github.com/sontek/pyramid_celery/issues/101

## Proposed UI/UX

Celery should add `context_settings` with `allow_extra_args`,
```
context_settings={
    'allow_extra_args': True
}
```
to both the `shell` and `purge` commands. This will allow projects like pyramid-celery to hook in their own custom configuration options using the recommended (by Celery) `celery_app.user_options['preload'].add()` and/or `celery_app.user_options[option].add()` approaches. See [here](https://github.com/celery/celery/blob/e7b47a62d789557cf18ed0e56e2dfb99a51a62f7/docs/userguide/extending.rst#adding-new-command-line-options). This will also make `shell` and `purge` commands consistent with other commands like `worker`, `beat`, and `events` that already have these settings.

## Diagrams

N/A

## Alternatives

None

**Comment by dpdoughe** [comment]
The inability to configure and run `purge` or `shell` commands with pyramid_celery persists with Celery v5.3.1

**Comment by auvipy** [comment]
I am open to contributions in this regard. my expectation is adding adding missing tests for the newly proposed/missing features

**Comment by dpdoughe** [comment]
The allow_extra_args aspect of this seems to be also required and related to #8049

**Comment by dpdoughe** [comment]
@auvipy as I am new to Celery's testing suite, I left some questions for you in https://github.com/celery/celery/pull/8374. Let me know if you have any thoughts. Thank you
