### ISSUE TITLE
result.id is causing celery beat to fail when using transaction.on_commit()

### ISSUE THREAD

**Issue by Raghavsalotra** [celery/celery#8372]
https://github.com/celery/celery/blob/811ed96edbf7d7ae0681ae67ced63e6994a6e63a/celery/beat.py#L285

Reason for asking this question:
We have transaction.on_commit wrapper for out celery tasks which defers the execution of task until the transaction is committed to database. In that case the result returned will be None and celery beat will fail with this error:

`[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="self.apply_entry(entry, producer=self.producer)"
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="  File "/lib/python3.8/site-packages/celery/beat.py", line 292, in apply_entry"
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="    "
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="debug('%s sent. id->%s', entry.task, result.id)"
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="AttributeError"
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message=": "
[celery.redirected] level=WARNING MainProcess (2023-07-13 09:29:06,184 trace_id="short_id:TEih9A3Q2mEm4J;" [log.write:232] process=96566 thread=8631279104)  message="'NoneType' object has no attribute 'id'"
`

Is there a way using configuration parameter so that we do not end up in this issue or We might need to have a fork just for this change.

**Comment by bmrobin** [comment]
i get this error too;  to get unblocked i just don't use `transaction.on_commit` with Celery tasks invoked via Beat.

would be nice not to have to do that deviation though

**Comment by auvipy** [comment]
I am open to accept any improvement here with appropriate test cases

**Comment by bmrobin** [comment]
@auvipy i haven't contributed to this repo and don't know that i am the right person to suggest how to best accommodate this;   however, it seems safe enough to wrap this `debug` statement in some checks to see if the properties being logged are non-`None` ?
<img width="667" alt="image" src="https://github.com/celery/celery/assets/4059210/74f6d666-6520-474b-8c9e-ce21ae7dcf43">

https://github.com/celery/celery/blob/811ed96edbf7d7ae0681ae67ced63e6994a6e63a/celery/beat.py#L285

**Comment by auvipy** [comment]
please don't worry about mistakes. come with a draft PR with what you suggested in your last comment.
