### ISSUE TITLE
backend.get_task_meta ignores the result_extended config parameter in mongodb backend

### ISSUE THREAD

**Issue by ycc140** [celery/celery#8387]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

【version】
celery 5.3.1

【bug info】
When you set the result_extended config parameter to True extra task meta data is stored in the backend.
But when you call backend.get_task_meta those extra meta data values are not returned. The code is ignorant of the config parameter.

I looked at which extra meta data that is saved, and the awareness of the config parameter  in backends.base._get_result_meta method and applied the same logic to the backends.mongodb._get_task_meta_for method, like this:

    def _get_task_meta_for(self, task_id):
        """Get task meta-data for a task by id."""
        obj = self.collection.find_one({'_id': task_id})
        if obj:
            if self.app.conf.find_value_for_key('extended', 'result'):
                return self.meta_from_decoded({
                'name': obj['name'],
                'args': obj['args'],
                'task_id': obj['_id'],
                'queue': obj['queue'],
                'kwargs': obj['kwargs'],
                'status': obj['status'],
                'worker': obj['worker'],
                'retries': obj['retries'],
                'children': obj['children'],
                'date_done': obj['date_done'],
                'traceback': obj['traceback'],
                'result': self.decode(obj['result']),
            })
            return self.meta_from_decoded({
                'task_id': obj['_id'],
                'status': obj['status'],
                'result': self.decode(obj['result']),
                'date_done': obj['date_done'],
                'traceback': obj['traceback'],
                'children': obj['children'],
            })
        return {'status': states.PENDING, 'result': None}

**Comment by auvipy** [comment]
You are welcome to contribute in this area
