### ISSUE TITLE
Link in the top notification is not using `main` branch but `master` branch

### ISSUE THREAD

**Issue by shuuji3** [celery/celery#8453]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- #7968

#### Possible Duplicates

- None

# Description

<img width="996" alt="Screenshot 2023-08-23 at 11 56 25" src="https://github.com/celery/celery/assets/1425259/0b1e0581-becd-4614-8fdd-18ef20744d6e">

https://docs.celeryq.dev/en/main/index.html

Hi, the link target here uses `master` as the default branch which causes a 404 not found link.

- Current: https://docs.celeryq.dev/en/master/index.html
- Expected: https://docs.celeryq.dev/en/main/index.html

# Suggestions

With #7968, the `master` branch was renamed to `main` and linked all links in the docs. But it looks like the above autogenerated link uses the default branch setting and changing it requires configuring from the admin page of Read the Docs.

ref. Configuration file v2 (.readthedocs.yaml) — Read the Docs user documentation - https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface

Thanks!

**Comment by Nusnus** [comment]
`sphinx_celery` with the matching fix was release.
It is now fixed on `main` and will be fixed officially from v5.4.
Can be seen here: https://docs.celeryq.dev/en/main/

@lewisemm FYI and thank you!

![CleanShot 2024-01-11 at 15 35 01@2x](https://github.com/celery/celery/assets/4662342/013ea9ca-b060-4a0e-b8e4-76b423d48db6)

**Comment by Nusnus** [comment]
The latest/stable still shows the previous `master`, but that’s expected until the next release.
![CleanShot 2024-01-11 at 15 38 20@2x](https://github.com/celery/celery/assets/4662342/27db41f5-917f-4b80-98a1-7eea23901d28)
