### ISSUE TITLE
the document is not corect for django config

### ISSUE THREAD

**Issue by shifenhutu** [celery/celery#8483]
I am sorry that my english is not well

celery:  v 5.3.1  ,  v5.3.4

# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

https://docs.celeryq.dev/en/stable/userguide/configuration.html#new-lowercase-settings

the `CELERYD_LOG_FORMAT`  should be `CELERY_WORKER_LOG_FORMAT`

the `CELERY_WORKER_TASK_LOG_FORMAT`  should be `CELERY_WORKER_TASK_LOG_FORMAT`

thank you 

# Suggestions

please update the document

**Comment by auvipy** [comment]
thanks for the report and PR to fix it. did you find any other incorrect config names in the list?

**Comment by shifenhutu** [comment]
sorry ，   i never used others  CELERYD_* now ,    my english is not well ,   to verify others  CELERYD_*  is too difficult for me
