### ISSUE TITLE
`celery worker` outputs sql debug messages regardless of loglevel

### ISSUE THREAD

**Issue by hidde-jan** [celery/celery#849]
Hi,

I just updated to 3.0 and suddenly the worker starts outputting debug info about sql queries performed during the execution of the tasks. I use celery and djcelery and never had logging enabled for django's orm. The log entries look as follows:

```
[2012-07-09 14:18:14,398: DEBUG/MainProcess] 
(0.001) SELECT "matches_matchcategory"."id", "matches_matchcategory"."name", "matches_matchcategory"."slug", "matches_matchcategory"."order", "matches_matchcategory"."icon_path" 
    FROM "matches_matchcategory" ORDER BY "matches_matchcategory"."order" ASC; args=()
```

I have no idea where these debug messages come from, and apart from this, celery seems to respect the loglevel setting. The following is only displayed with a loglevel of WARNING or higher:

```
[2012-07-09 14:20:17,526: WARNING/MainProcess] celery@mac.local has started.
```

Does anyone have a clue why this is happening?

Cheers, hj

**Comment by arthur-barsegyan** [comment]
@mishu- Maybe it happens because you have Debug=True? Read more in [docs](https://docs.djangoproject.com/en/2.1/topics/logging/#django-db-backends)

**Comment by ranjur** [comment]
'django.db.backends': {
                'handlers': ['console'],
                'level': 'DEBUG',
                'propagate': False,
            },

Added this in the LOGGING and seems its okay now.
