### ISSUE TITLE
Celery 5.3.4: Memory leak in Celery master process

### ISSUE THREAD

**Issue by narva8916** [celery/celery#8521]
### Discussed in https://github.com/celery/celery/discussions/8514

<div type='discussions-op-text'>

<sup>Originally posted by **narva8916** September 18, 2023</sup>
Recently we upgrade from celery 4.4.3 to 5.3.4 in order to overcome a memory leak issue we were experiencing.

After that we see there's a minimum change about ram consumption but anyway the workers still consuming ram even when no task are executed.

This is the ram memory consumption from one of the workers, from 15 to 18 there were no task executed, anyway the worker is consuming memory.

![Screen Shot 2023-09-18 at 10 16 29 AM](https://github.com/celery/celery/assets/3817743/1bac2df5-efb9-46b0-9b95-14f9d6536bad)

We are using celery 5.3.4 and python 3.9.0.

Someone have experience this same issue? how do you fix it?
</div>

**Comment by sushanksaj** [comment]
@narva8916 For that I am using `--max-tasks-per-child=1`.

REF: https://docs.celeryq.dev/en/latest/userguide/workers.html#max-tasks-per-child-setting

**Comment by Hoohaha** [comment]
Try with 5.2.7?

In my environment, 5.2.7 works well all time.
But since we upgrade to 5.3.4, something unexpected errors frequently happened.
So we have to downgrade to 5.2.7.

**Comment by marcaurele** [comment]
We tried to upgrade to Celery 5.2.7 but had issue with memory leaks as you show here. We are using AWS SQS as a backend. For now we are stuck with Celery 5.1.x which was the highest version we could get to. All 5.2.x had the problem.

**Comment by lamuria** [comment]
We are on the same position here. Same problem, same celery versions. I know this issue was moved to the release 5.4 but does anybody know if there's any movement in order to fix it?

**Comment by auvipy** [comment]
we need some one to try this https://github.com/celery/celery/discussions/8514#discussioncomment-7058711 and let us know

**Comment by jfmlima** [comment]
We've been observing the same pattern on Celery 5.2 when adding multiple workers with no autoscaling for the same queues (50 for the first queue, and 20 to the second queue). 
We've tried the latest version as in this issue but it got worse (leaking with single worker).
Here's how our memory consumption looks like (we also tried bumping memory to see if it would help, but to no avail)
<img width="824" alt="image" src="https://github.com/celery/celery/assets/5619521/3ab77c64-59f7-4ee7-9c7b-7443712bef8d">

@auvipy Is it recommended to use multiple workers for the same queue or are there any disadvantages on doing so?

**Comment by esauser** [comment]
We're seeing similar behavior, for both `celery beat` and `celery flower` on 5.3.4.  The only time the memory ever seems to reduce is when we roll the pods or Kubernetes kills them because they are consuming too much memory.  Below is the last two days for `celery flower`.
![image](https://github.com/celery/celery/assets/24945592/4e35454f-ae2b-4470-947c-125c62c66895)

**Comment by graysonpike** [comment]
Still experiencing this issue on v5.4.0. Memory usage almost immediately jumps to the maximum we allocate for the container running the celery worker. (The worker only receives a handful of tasks per day.)

Is this an acknowledged issue by anyone on the core dev team? Is this the same as #4843 ?

**Comment by narva8916** [comment]
We identify the dd tracer agent package for python were responsible for the memory consumption. Upgrading the version solve the issue.

**Comment by ehi-moment** [comment]
> Still experiencing this issue on v5.4.0. Memory usage almost immediately jumps to the maximum we allocate for the container running the celery worker. (The worker only receives a handful of tasks per day.)
> 
> Is this an acknowledged issue by anyone on the core dev team? Is this the same as #4843 ?

Did you eventually get this resolved?

**Comment by ammirsm** [comment]
Experiencing the same issue on the v5.4.0, it increases and kills the server. For now, I added `--max-tasks-per-child=50` to restart the server after finishing 50 as a workaround.

<img width="728" alt="image" src="https://github.com/user-attachments/assets/93854926-f9e1-4ebc-8984-50a0817be20f" />

**Comment by CharlesFarhat** [comment]
Same issue here....
