### ISSUE TITLE
Getting Started has Circular Import Issue

### ISSUE THREAD

**Issue by david-waterworth** [celery/celery#8561]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

[getting-started/next-steps.html](https://docs.celeryq.dev/en/stable/getting-started/next-steps.html) has an example as follows

### Project Structure
```
proj/__init__.py
    /celery.py
    /tasks.py
```

### celery.py
``` python
from celery import Celery

app = Celery('proj',
             broker='amqp://',
             backend='rpc://',
             include=['proj.tasks'])

# Optional configuration, see the application user guide.
app.conf.update(
    result_expires=3600,
)

if __name__ == '__main__':
    app.start()
```

I cannot get this to work - how can you import `Celery` from the `celery` module in a file also called `celery` - won't that create a circular import? 

Also the error from running `celery -A proj worker -l INFO` in the project root is 

``` bash
Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
Module 'proj.celery' has no attribute 'celery'
```

This implies that its expecting the `Celery` instance to be called `celery` not `app` I think. In either case the examples don't seem to work without modification.

I've been using celery in projects fine, but I had to follow third party tutorials - which used a different pattern (i.e. using `celeryapp.py` as the filename, and explicitly specifying the celery instance in the worker run command). I couldn't get started using the official guides though.

# Suggestions

**Comment by frolenkov-nikita** [comment]
This problem is mentioned in the documentation.

https://github.com/celery/celery/blob/b838b058710a3d8d09745859b9c8e7e3b60703c3/docs/getting-started/next-steps.rst?plain=1#L73

However, I think that the documentation can be improved for this case if we add a folder above in the project structure, like src/proj

Please consider my pull request.
