### ISSUE TITLE
Task is requeued with compression header but the body is not compressed

### ISSUE THREAD

**Issue by mathieu-lemay** [celery/celery#8625]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.3.4

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.4 (emerald-rush) kombu:5.3.3 py:3.11.5
            billiard:4.2.0 redis:4.6.0
platform -> system:Linux arch:64bit, ELF
            kernel version:6.5.9-arch2-1 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: 5.3.0
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.2.0
billiard==4.2.0
celery==5.3.4
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
kombu==5.3.3
prompt-toolkit==3.0.39
python-dateutil==2.8.2
redis==4.6.0
six==1.16.0
tzdata==2023.3
vine==5.1.0
wcwidth==0.2.9
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery()


@app.task(autoretry_for=(Exception,), max_retries=1, retry_backoff=1)
def task():
    print("Executing task")
    raise Exception("whoopsie")


if __name__ == "__main__":
    app.send_task(name="main.task", compression="zlib")
```

1. Run the worker with `celery -A main worker`
2. Trigger the task with `python main.py`

</p>
</details>

# Expected Behavior

The task should be requeued, run a 2nd time and then raise the Exception

# Actual Behavior

When the task is requeued, the compression header is set to
`application/x-gzip`, but the body is not compressed. When the worker tries do
read the message, it tries to decompress a non compressed message and crashes
with the following exception:

```
[2023-11-08 12:23:26,377: CRITICAL/MainProcess] Can't decode message body: TypeError("a bytes-like object is required, not 'str'") [type:'application/json' encoding:'utf-8' headers:{'lang': 'py', 'task': 'main.task', 'id': '6923bf1e-5008-4bee-9619-d8ac9ce9397a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 1, 'timelimit': [None, None], 'root_id': '6923bf1e-5008-4bee-9619-d8ac9ce9397a', 'parent_id': '6923bf1e-5008-4bee-9619-d8ac9ce9397a', 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen2321095@xenomorph', 'ignore_result': False, 'stamped_headers': None, 'stamps': {}, 'compression': 'application/x-gzip'}]

body: '[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/home/mathieu/.cache/pypoetry/virtualenvs/celery-compresion-issue-jmrSpK9z-py3.11/lib/python3.11/site-packages/kombu/message.py", line 95, in _reraise_error
    reraise(*self.errors[0])
  File "/home/mathieu/.cache/pypoetry/virtualenvs/celery-compresion-issue-jmrSpK9z-py3.11/lib/python3.11/site-packages/kombu/exceptions.py", line 35, in reraise
    raise value
  File "/home/mathieu/.cache/pypoetry/virtualenvs/celery-compresion-issue-jmrSpK9z-py3.11/lib/python3.11/site-packages/kombu/message.py", line 82, in __init__
    body = decompress(body, compression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathieu/.cache/pypoetry/virtualenvs/celery-compresion-issue-jmrSpK9z-py3.11/lib/python3.11/site-packages/kombu/compression.py", line 72, in decompress
    return get_decoder(content_type)(body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

This issue was introduced in Celery 5.3.0. Prior to that, the compression
header would _not_ be included when requeuing the message. I have reproduced it
with both a rabbitmq and a redis backend. The error message is different with
redis, but indicates the exact same problem.

Setting `task_compression='zlib'` is a workaround. If this config is set, the
body will be compressed as expected.

**Comment by mathieu-lemay** [comment]
It's probably related to #7555. The compression header is now sent when retrying whereas it wasn't before. But the payload is only compressed if `task_compression` is set, potentially leading to a discrepancy.

**Comment by auvipy** [comment]
Reviewing the PR, now it seems that it might need more work. Can you at least try to give it a shot?

**Comment by mathieu-lemay** [comment]
I can confirm that reverting PR #7555 fixes the bug. The following patch also fixes the bug:
```patch
diff --git a/celery/app/task.py b/celery/app/task.py
index a23254d3a..5d55a747b 100644
--- a/celery/app/task.py
+++ b/celery/app/task.py
@@ -104,7 +104,7 @@ class Context:
     def _get_custom_headers(self, *args, **kwargs):
         headers = {}
         headers.update(*args, **kwargs)
-        celery_keys = {*Context.__dict__.keys(), 'lang', 'task', 'argsrepr', 'kwargsrepr'}
+        celery_keys = {*Context.__dict__.keys(), 'lang', 'task', 'argsrepr', 'kwargsrepr', 'compression'}
         for key in celery_keys:
             headers.pop(key, None)
         if not headers:
```

**Comment by auvipy** [comment]
I guess except reverting just adding 'compression' to the key could be a solution, right? correct me if I'm wrong

**Comment by mathieu-lemay** [comment]
Yes, it does fix the issue for me. I have no idea if that could cause other side effects, but from my very limited knowledge of the inner workings of celery, I think it's safe.

**Comment by auvipy** [comment]
from the test coverage report, it seems already covered by existing tests and code seems to work. perhaps can you share some code to reproduce it to be use in the unit tests? or integration test?

**Comment by auvipy** [comment]
thanks for the report and tracking it down!

**Comment by mathieu-lemay** [comment]
Thanks for fixing it. I didn't see your previous message until today as I was on vacation. I'll see if I can still write some integration test for it, I wouldn't mind contributing to the project myself!

**Comment by auvipy** [comment]
you are more then welcome for further contribution! thanks
