### ISSUE TITLE
celery tasks using botocore 1.31.81 or greater does not execute tasks from sqs queue

### ISSUE THREAD

**Issue by stevegaunt** [celery/celery#8641]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

Since boto3core version 1.31.1.81 , tasks are not being executed, however 1.31.90 and less this is fine,

If there is a change for how json format messages are being posted there is no documentation to cover this for the sqs examples

this is the stricture of adding the message to the sqs queue

        # generate celery task message
            msg_id = str(uuid.uuid4())

            msg_envelope = {
                "content-encoding": "utf-8",
                "content-type": "application/json",
                "headers": {},
                "properties": {
                    "body_encoding": "base64",
                    "correlation_id": msg_id,
                    "delivery_info": {
                        "exchange": "",
                        "routing_key": ""
                    },
                    "delivery_tag": ""
                }
            }

            msg_body = {
                "task": task_name,
                "args": task_arg,
                "kwargs": task_kwargs,
                "id": msg_id,
                "retries": 0
            }
            msg_envelope["body"] = base64.b64encode(json.dumps(msg_body).encode('utf8')).decode('utf8')
            msg = base64.b64encode(json.dumps(msg_envelope).encode('utf8')).decode('utf8')
            enrtry = {

                'MessageBody': msg,
                'Id':msg_id
            }

If there is a new structure to be defined since the Botocore upgrade for json documents  should this be reflected within the documentation?  Or is there something that has changed on Botocore that is a bug or breaking change?

**Comment by auvipy** [comment]
it is a SQS client issue. not entirely celery issue. for now users have to be pin specific boto/botocore version before the new SQS stuff is implemented in kombu

**Comment by alexalligator** [comment]
Am also seeing this same issue.

**Comment by auvipy** [comment]
this PR might fix the problem, can you guys check? https://github.com/celery/kombu/pull/1807

**Comment by nickdjones** [comment]
Discussion taking place here https://github.com/celery/celery/discussions/8627

**Comment by auvipy** [comment]
this should be fixed with kombu v5.3.4 release. please let us know if that is not the case

**Comment by lopezm1** [comment]
Hi @auvipy, I can confirm Kombu `v5.3.4` fixed this issue for us. We were seeing issues with SQS executing messages on botocore `1.31.85` but the new Kombu patch fixed it. 

I can also confirm that Kombu `v5.3.1` and botocore `1.31.85` was not compatible.

**Comment by auvipy** [comment]
Thanks a lot!

**Comment by stevegaunt** [comment]
awesome 👍

**Comment by selintunr** [comment]
Hi @lopezm1, which versions of celery and botocore used with  Kombu v5.3.4 fixed the problem?
