### ISSUE TITLE
Terminate job implementation for gevent concurrency backend

### ISSUE THREAD

**Issue by azulzaietz** [celery/celery#8687]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same feature was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/pull/6917

#### Possible Duplicates

- https://github.com/celery/celery/issues/4019

# Brief Summary

Current implementation of TaskPool which is based on gevent library does not support terminating jobs.
Revoking with terminate=True or terminating task raises NotImplementedError: <class 'celery.concurrency.gevent.TaskPool'> does not implement kill_job exception while task continues to run.

# Design

Modify the celery/concurrency/gevent.py file following the changes made in celery/concurrency/eventlet.py file for implementing the same feature.

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by HungPhann** [comment]
+1

**Comment by zwwangoo** [comment]
+1

**Comment by mixtah** [comment]
+1

**Comment by thedrow** [comment]
This is already done in #9083.
