### ISSUE TITLE
Modify parameters of a tasks with ack late wich is reenqueued

### ISSUE THREAD

**Issue by bdoublet91** [celery/celery#8716]
# Brief Summary
When a task with acks_late to true is not ack (because of celery restart for example), the task is pushed at the end of the queue without the possibility to modify the parameters like priority with a retry handler or something else.
For our use case, we have a chain of tasks with a callback task and if some tasks are reenqueued without higher priority, the callback task will be delayed because of new tasks queued.

For example
```
queue default: 1000 tasks

group_tasks_job1: 2 tasks + callback task

group_tasks_job1 -> celery_process_tasks_job1.1 -> success -> ACK
                                 -> celery_process_tasks_job1.2 -> celery_restart -> NOT_ACK -> re-queued
tasks_job1.2 is the 999th task in the queue default so the group_tasks_job1 have to wait for all the 998 tasks to be processed and then start the callback task for this group.

I didn't find any solution to trigger this event and change the priority ?
```

Thanks for your help

**Comment by ShaheedHaque** [comment]
When re-queueing, shouldn't the default behaviour be to use ALL the settings it was originally created with?
