### ISSUE TITLE
celery[sqs] no longer available?

### ISSUE THREAD

**Issue by selintunr** [celery/celery#8809]
## SQS Celery Issue
I'm unable to download sqs version for celery via `pip install celery[sqs]` as shown [here](https://docs.celeryq.dev/en/v5.3.6/getting-started/backends-and-brokers/sqs.html) ,it returns:

```bash

zsh: no matches found: celery[sqs]

```

**Comment by Nusnus** [comment]
This is a doc bug.
`pip install 'celery[sqs]’` works.

**Comment by 50-Course** [comment]
> This is a doc bug.
pip install 'celery[sqs]' works.

@Nusnus this should be reopened as an issue - and included back into the docs

**Comment by Nusnus** [comment]
Fixed: https://docs.celeryq.dev/en/main/getting-started/backends-and-brokers/sqs.html#installation
