### ISSUE TITLE
任务总是卡住

### ISSUE THREAD

**Issue by Robin528919** [celery/celery#8902]
<img width="1726" alt="image" src="https://github.com/celery/celery/assets/45855146/f9e4dd3d-d606-48a0-99aa-1ec8befdecc5">

<img width="1198" alt="image" src="https://github.com/celery/celery/assets/45855146/96ae0bf8-e8d7-4ff5-878a-e9f18cfce086">

如何解决?
是哪里的问题导致的?

**Comment by Robin528919** [comment]
<img width="885" alt="image" src="https://github.com/celery/celery/assets/45855146/3c356ba6-14fa-4cce-8dab-e1337c920955">
都是一样的设置、

**Comment by Robin528919** [comment]
celery+ amqp 任务结果放到的是 redis中

**Comment by thedrow** [comment]
Please open bug reports in English as we do not understand your language.
