### ISSUE TITLE
subprocess command call inside a task is not executing

### ISSUE THREAD

**Issue by palewire** [celery/celery#891]
I'm trying to run a `subprocess.call` to execute a system command from inside a celery task. My logging shows that everything around the call is working correctly, but it appears as if the command itself is simply not executing. if I executing the task as a Python function from inside Django's shell, it also runs fine. 

Is there something about doing this inside celery that I do not understand?

**Comment by bakztfuture** [comment]
agree with @ghost running ffmpeg as a task inside Celery is giving me an error too, have tried subprocess and delegator.py (a follow up to the envoy library)

**Comment by tayabsoomro** [comment]
I am having the same issue where my celery task skips over the command that runs `subprocess`. I tried using `envoy`, `delegator` and `subprocess.Popen` but nothing seems to be working. It just skips over the line that needs to run shell command and returns the function. Any suggestions?

**Comment by spreadsomejelly** [comment]
I am fashionably late to this thread, however I had an issue running a particular Celery task that utilized a subprocess.Popen call to run a standalone executable (all of my other Celery tasks would run fine), and wanted to share my hacky solution for posterity.  I was using a virtualenv, and daemonized Celery/Celerybeat via systemd.  The dependencies for the standalone executable **were not installed system-wide, only inside the virtualenv**.  To complicate the matter, the standalone executable required Python.  I found if I invoked the virtualenv Python with the command line switch (python -m) inside the subprocess.Popen command **(by calling it from the virtualenv bin folder)**, the executable would run.

i.e. 
`subprocess.Popen("<executable that requires Python>", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` -> **didn't work**

`subprocess.Popen("<path to virtualenv python>/python -m <executable that requires Python>", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` -> **worked**

**Comment by thedrow** [comment]
> 
> 
> I am fashionably late to this thread, however I had an issue running a particular Celery task that utilized a subprocess.Popen call to run a standalone executable (all of my other Celery tasks would run fine), and wanted to share my hacky solution for posterity. I was using a virtualenv, and daemonized Celery/Celerybeat via systemd. The dependencies for the standalone executable **were not installed system-wide, only inside the virtualenv**. To complicate the matter, the standalone executable required Python. I found if I invoked the virtualenv Python with the command line switch (python -m) inside the subprocess.Popen command **(by calling it from the virtualenv bin folder)**, the executable would run.
> 
> i.e.
> `subprocess.Popen("<executable that requires Python>", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` -> **didn't work**
> 
> `subprocess.Popen("<path to virtualenv python>/python -m <executable that requires Python>", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` -> **worked**

I'm very much surprised.😮 
Would you mind issuing a PR to document this?

**Comment by hzbd** [comment]
```
@task(name="cmdb.task.test")
def test():
    result = subprocess.check_output(["ls", "-al"], cwd="/usr/bin")
```
