### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [celery/celery#8925]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did maintainers of this project receive free github copilot access on June 2022? If you don't recall, it might be helpful to check if maintainers are currently elgiible ([https://github.com/github-copilot/free_signup](https://github.com/github-copilot/free_signup))
2) My thesis is especially focused on understanding hierarchical structures. Is there a publicly available list of of individuals in this project with triage/write/maintain/admin access in this project?

Happy to chat further if you have questions, and thank you for your time!

**Comment by Nusnus** [comment]
> Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
> 

Hey there @liaochris ! 
Nice to meet you 😃

> 1. Did maintainers of this project receive free github copilot access on June 2022? If you don't recall, it might be helpful to check if maintainers are currently elgiible (https://github.com/github-copilot/free_signup)

Good question!
As far as I know, we did not receive a free license to Copilot, worth checking though!

> 2. My thesis is especially focused on understanding hierarchical structures. Is there a publicly available list of of individuals in this project with triage/write/maintain/admin access in this project?
> 

Yes and no.
Yes - https://github.com/orgs/celery/teams
No - Currently, there are only 3 main maintainers, @thedrow, @auvipy, and myself, so the team’s page may be misleading as it has not been updated for years.

There’s also a hierarchical structure over PyPI’s, which is not 1:1 matching to GitHub.

> Happy to chat further if you have questions, and thank you for your time!

Anything else I can help you with?

**Comment by liaochris** [comment]
Thanks for your response! This will be very helpful

**Comment by Nusnus** [comment]
> Thanks for your response! This will be very helpful

Glad I could help. Feel free to ask more questions and I'll try to do my best to answer 😊

**Comment by auvipy** [comment]
Also this should be asked in Discussion forum section https://github.com/celery/celery/discussions
