### ISSUE TITLE
use fastapi+celery，run task failed， cause an error

### ISSUE THREAD

**Issue by Amariswade** [celery/celery#8957]
[2024-04-11 19:03:49,417: ERROR/MainProcess] Task handler raised error: ValueError('not enough values to unpack (expected 3, got 0)')
billiard.einfo.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\app\trace.py", line 664, in fast_trace_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by Amariswade** [comment]
python  version:  3.10

**Comment by suryan-s** [comment]
@Amariswade could you provide more details like sample code etc?

**Comment by linkedlist771** [comment]
> [2024-04-11 19:03:49,417: ERROR/MainProcess] Task handler raised error: ValueError('not enough values to unpack (expected 3, got 0)') billiard.einfo.RemoteTraceback: """ Traceback (most recent call last): File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\billiard\pool.py", line 361, in workloop result = (True, prepare_result(fun(*args, **kwargs))) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\app\trace.py", line 664, in fast_trace_task tasks, accept, hostname = _loc ValueError: not enough values to unpack (expected 3, got 0)

I have solved it, it seems that the new version of the celery works not well with windows, if you are using `windows` , you could choose to use it with the `WSL` or `Docker`.

**Comment by thedrow** [comment]
There's not enough information to resolve this issue. Please reopen and file the issue with our template.

**Comment by dominicdawes** [comment]
WINDOWS USERS: 

The latest versions of Celery (5.x and above) have some known compatibility issues with Windows due to differences in how multiprocessing and signal handling work across operating systems. 

```bash
# use the solo flag for now (in mvp/development)
celery -A tasks worker --loglevel=info -P solo
```

The `solo` pool is a single-threaded option that can be used as a workaround on Windows. This pool is not suitable for production environments because it's limited to processing one task at a time, but it is helpful for development and debugging.

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/10397
