### ISSUE TITLE
In the flask application I wrote, when using gunicorn and worker_class = "eventlet", the request sent to the celery task through the interface is always in the pending state.

### ISSUE THREAD

**Issue by yc2768** [celery/celery#9016]
gunicorn_config.py
`import multiprocessing

workers = 4  
timeout = 120  
worker_class = "eventlet"
loglevel = (
    "debug"  
)
accesslog = "./logs/gunicorn_access.log"  
errorlog = "./logs/gunicorn_error.log"  
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(D)s'`

执行下面命令，celery 任务不执行，
gunicorn -b  myweb.com:8081  main:app --config gunicorn_config.py&
celery -A mytasks.tasks.celery worker -Q generateImg --loglevel=info --concurrency=1  -n generateImg@myhost -P eventlet &，

gunicorn==22.0.0
celery==5.3.6
eventlet==0.36.1

**Comment by thedrow** [comment]
There's not enough information for us to reproduce this issue. Please use our issue template and report what you're expecting to happen, what isn't happening etc.
