### ISSUE TITLE
Execute custom task termination by celery

### ISSUE THREAD

**Issue by xiaoxieya** [celery/celery#9085]
When I use Redis and Celery as asynchronous task processing mechanisms in Flask, an asynchronous task is customized and called in my task program. This asynchronous task uses a self-defined function. When executing this asynchronous task, the cellery process automatically ends without any errors when the custom function is executed in the middle. What's going on?
![Snipaste_2024-06-20_09-49-16](https://github.com/celery/celery/assets/91840179/9ae62261-1142-4c70-81d3-3c9a06a8b0b5)

**Comment by thedrow** [comment]
There's not enough information for us to debug this issue.
Please use our issue template to report bugs.
