### ISSUE TITLE
Cannot disconnect a signal receiver after using Signal.connect(retry=True)

### ISSUE THREAD

**Issue by mgedmin** [celery/celery#9119]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.3.1

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A
- **Minimal Celery Version**: Unknown
- **Minimal Kombu Version**: N/A
- **Minimal Broker Version**: N/A
- **Minimal Result Backend Version**: N/A
- **Minimal OS and/or Kernel Version**: N/A
- **Minimal Broker Client Version**: N/A
- **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

I expect to be able to use `worker_process_init.disconnect(my_handler)` after using

```python
@worker_process_init.connect(retry=True):
def my_handler(**kw):
    ...
```

More specifically, I use this in a pytest fixture in my conftest.py to disable my_handler which normally sets up database connections and everything.  The disconnect worker fine until I added `retry=True` to the connect.

# Actual Behavior

The disconnection doesn't work, my_handler gets called in the middle of my test suite and loops, retrying forever.

Looking closer at the problem I see that it's caused by https://github.com/celery/celery/blob/bd3b3c6afb8b0c44b416f469b3db6a725d71b609/celery/utils/dispatch/signal.py#L165-L172

which replaces fun = my_handler with a wrapper that does the retrying, but also remembers the id() of the original function as dispatch_uid so that the original function can be disconnected later.

But I no longer have the original function -- the Python decorator syntax means `my_handler` is replaced with the return value of the decorator, which is set by `return fun` executed _after_ the `fun = _retry_receiver(fun)` statement.  So when I call `.disconnect()`, I'm passing the wrapper, and it doesn't match the dispatch_uid computed from the original function.

(I've planned to create a PR with a failing test case and complete all the checklists before submitting the issue, but this tab's already open for a couple of days I'm afraid of losing what I've already written to a browser restart or something.  I'll try to come back and complete it.)

**Comment by mgedmin** [comment]
> I've planned to create a PR with a failing test case

I now have a [failing unit test in a branch](https://github.com/celery/celery/compare/main...mgedmin:celery:failing-test-for-issue-9119), but some time has passed and I'm uncertain about the next step in the process.  Should I create a PR with the failing test?

**Comment by thedrow** [comment]
Yes, please. Mark it as `xfail`ed so we won't forget to fix it later.
If you can come up with a solution to this bug, that's even better.

**Comment by pachewise** [comment]
I opened a [small PR](https://github.com/celery/celery/pull/9247), but need some guidance as to whether this approach is desirable or not. IMO, if we are supporting both the decorator and non-decorator usecases, then we need a way to tell `disconnect()` to compare the uid to the original function's. The other thing we can do is to simply use the uid for the retry-wrapped function (implicitly, `_make_id(_retry_receiver(fun))`), but that seems to break the original retry tests in test_dispatcher.py
