### ISSUE TITLE
`time_limit` is not respected if it is shorter than `soft_time_limit`

### ISSUE THREAD

**Issue by jmsmkn** [celery/celery#9125]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [x] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
poetry run celery --version
5.4.0 (opalescent)
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: Observed with Python 3.11 and 3.12, using prefork worker and/or celery-pytest
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: Observed with SQS, Redis and RabbitMQ
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: Observed on Linux and MacOS
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.2.0
billiard==4.2.0
celery==5.4.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
debugpy==1.8.2
decorator==5.1.1
docker==7.1.0
idna==3.7
iniconfig==2.0.0
kombu==5.3.7
packaging==24.1
pluggy==1.5.0
prompt_toolkit==3.0.47
psutil==6.0.0
py==1.11.0
pytest==8.2.2
pytest-celery==1.0.0
pytest-docker-tools==3.1.3
python-dateutil==2.9.0.post0
redis==5.0.7
requests==2.32.3
retry==0.9.2
six==1.16.0
tzdata==2024.1
urllib3==2.2.2
vine==5.1.0
wcwidth==0.2.13
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

```python
from celery import shared_task
import time

@shared_task(time_limit=5, soft_time_limit=15)
def long_task(*args, **kwargs) -> None:
    time.sleep(10)
    return "OK"
```

```python
import pytest 

@pytest.fixture
def default_worker_tasks(default_worker_tasks: set) -> set:
    import tasks

    default_worker_tasks.add(tasks)
    return default_worker_tasks

def test_hello_world(celery_setup):
    from tasks import long_task

    assert long_task.s().apply_async().get() != "OK"
```

# Expected Behavior

Task is aborted with `TimeLimitExceeded` as `time_limit` was exceeded.

We discovered this behaviour due to a misconfiguration in our application. An alternative to raising `TimeLimitExceeded` could be that user is informed that the task has been improperly configured.

# Actual Behavior

Task exits successfully despite `time_limit` being exceeded.

**Comment by yogesh1801** [comment]
Can i work on this issue??
