### ISSUE TITLE
Improved ETA support for quorum queues

### ISSUE THREAD

**Issue by mwarkentin** [celery/celery#9149]
> One issue was that ETA may saturate de prefetch queue and block incoming new job.
> 
> You should have a test that generate a lots of ETA tasks, and then still try to schedule new tasks to see if the prefetch count is updated accordingly and the task is executed (which was what the global_qos was doing).

Thank you. That was a hint in the right direction.

I’ve created a [PR](https://github.com/celery/celery/pull/9121) that adds support to quorum queues without ETA tasks support, but with proper documentation and an automatic warning in the worker log to ensure it won’t go unnoticed.

> While this solution works for us, we experienced a task loss issue with RabbitMQ cluster using quorum queue. We did some digging and it turned out that we also want to add `app.conf.broker_transport_options = {"confirm_publish": True}` possibly due to the [implementation differences](https://groups.google.com/g/rabbitmq-users/c/LAflf1l4LtY#:~:text=A%20quorum%20queue%20ignores%20messages%20published%20by%20a%20closed%20channel%20and%20a%20classic%20queue%20does%20not.%20That%27s%20an%20implementation%20detail.) of quorum queue and classic queue when handling messages from closed channel.
> 
> refs - #5410, https://groups.google.com/g/rabbitmq-users/c/LAflf1l4LtY

I’ve also added a warning per this comment from @cbwchuck, so you’ll know you need to enable confirm publish when using quorum queues.

---

My implementation basically adds two new feature flags:
1. `worker_detect_quorum_queues` which is set by default to `True`: Auto-detect if at least one queue (including the default queue) is set to quorum and disables the global QoS.
2. `task_default_queue_type` which is set by default to `”classic"`: Can be set to `”quorum"` to automatically change the default `celery` queue type to quorum-queue. This means that if you don’t provide your own queue (using the queue argument accordingly), you can just do `app.conf.task_default_queue_type = “quorum”` (not forgetting `app.conf.broker_transport_options = {"confirm_publish": True}`), and the worker will create a quorum default queue and turn off the global QoS (per flag no 1).

ETA support will need to be developed separately to allow progressive support for quorum queues as to not hold back the currently proposed solution which might be enough for many users.

For more details see the PR changes.
It includes proper documentation for these flags, a new example project and 100% test coverage, so it should be clear what was changed from all angles.

EDIT:
Here are screenshots of the documentation from the PR’s build.
![CleanShot 2024-07-08 at 00 27 56@2x](https://github.com/celery/celery/assets/4662342/c77b29c4-a4ac-4b89-8f0b-87e70e2b133b)
![CleanShot 2024-07-08 at 00 28 07@2x](https://github.com/celery/celery/assets/4662342/3a26598d-0d77-4f17-9df6-1f3e35f33dad)

_Originally posted by @Nusnus in https://github.com/celery/celery/issues/6067#issuecomment-2212577881_

**Comment by mwarkentin** [comment]
@Nusnus hope you don't mind, but I figured I'd open a follow up issue for improving the ETA support based on the findings from the initial support for quorum queues. :)

**Comment by Nusnus** [comment]
> @Nusnus hope you don't mind, but I figured I'd open a follow up issue for improving the ETA support based on the findings from the initial support for quorum queues. :)

Thank you!

Do you already have a lead on a possible solution?

**Comment by mwarkentin** [comment]
I do not, but we have a bunch of ETA / countdown tasks in our code base, so wanted to make sure there was a follow up issue in case someone does have an idea.

**Comment by ulgens** [comment]
@Nusnus What was the resolution here? I guess the relation implementation is updated but the issue doesn't have a PR attached. Can we attach the PR if that's the case?

**Comment by froblesmartin** [comment]
JFYI, this was done at the commit https://github.com/celery/celery/commit/fa5d7ff09c93516c9d5712351f56db3d22876395 and appeard for the first time in version https://github.com/celery/celery/releases/tag/v5.5.0rc2.

The PR https://github.com/celery/celery/pull/9207 is gone from GitHub; it seems the GitHub User @thedrow who made the PR does not exist anymore either.
