### ISSUE TITLE
`setuptools` >= v72 removes `setuptools.command.test`

### ISSUE THREAD

**Issue by cclauss** [celery/celery#9157]
https://setuptools.pypa.io/en/stable/history.html#v72-0-0

https://github.com/celery/celery/blob/5e26553219da10f65f14d59573de18b5e366a693/setup.py#L7
* pypa/setuptools#931
    * pypa/setuptools#4458
* celery/django-celery-beat#771
* celery/django-celery-beat#772

**Comment by sevdog** [comment]
That import is also completely useless since currently in there are no other references to the test command of setuptools.

The usage of such element was removed in 1baca0ca90b5bd7f38e3d2ae2d513f24cc0613ea leaving just the unused import.
