### ISSUE TITLE
Children tasks in sync/EAGER mode in a celery worker lose their request context

### ISSUE THREAD

**Issue by nikatlas** [celery/celery#9199]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [x] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

software -> celery:5.4.0 (opalescent) kombu:5.3.7 py:3.8.10
            billiard:4.2.0 redis:5.0.8
platform -> system:Darwin arch:64bit
            kernel version:23.2.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:11000/

... A BUNCH of app-specific ENV_VARS ...

is_overridden: <bound method Settings.is_overridden of <Settings "xxxxxxx.settings_test">>
deprecated_settings: None
timezone: 'UTC'
</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
django==4.2.14
celery==5.4.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

I have a bound task that schedules itself like this:

```python
    @app.task(bind=True)
    def recursive_task(self, *args, retries=2, **kwargs):
        assert self.request.headers.get('test') == 123
        if retries > 0:
            return recursive_task.apply_async(
                kwargs={"retries": retries - 1},
                headers={'test': 123},
            )
        return True
```

I run a celery worker with `celery -A proj worker` (uses redis as a queue) in EAGER mode.
I push a new task with some options to this task. Specifically the `headers={'test':123}`

</p>
</details>

Reproducible test case using pytest-celery:

<details>
<summary><b>tasks.py</b></summary>
<p>

```python
from celery import shared_task


@shared_task(bind=True)
def bug_test(self, retry: bool = False):
    try:
        assert self.request.headers.get('foo') == 'bar'
    except AttributeError as exc:
        raise RuntimeError(f"Task expected to fail: retry={retry}, request={vars(self.request)}", exc)

    if retry:
        bug_test.apply(
            headers=self.request.headers,
        )
    return "bug"
```

</p>
</details>

Test file
<details>
<summary><b>test_celery_context_on_children.py</b></summary>
<p>

```python
from __future__ import annotations

import pytest
from celery import Celery, shared_task
from celery.canvas import Signature
from celery.result import AsyncResult

from pytest_celery import RABBITMQ_PORTS
from pytest_celery import CeleryBackendCluster
from pytest_celery import CeleryBrokerCluster
from pytest_celery import CeleryTestSetup
from pytest_celery import RabbitMQContainer
from pytest_celery import RabbitMQTestBroker
from pytest_celery import RedisTestBackend
from pytest_celery import ping

from . import tasks


###############################################################################
# RabbitMQ Management Broker
###############################################################################


class RabbitMQManagementTestBroker(RabbitMQTestBroker):
    def get_management_url(self) -> str:
        """Opening this link during debugging allows you to see the RabbitMQ
        management UI in your browser."""
        ports = self.container.attrs["NetworkSettings"]["Ports"]
        ip = ports["15672/tcp"][0]["HostIp"]
        port = ports["15672/tcp"][0]["HostPort"]
        return f"http://{ip}:{port}"


@pytest.fixture
def default_rabbitmq_broker_image() -> str:
    return "rabbitmq:management"


@pytest.fixture
def default_rabbitmq_broker_ports() -> dict:
    # Expose the management UI port
    ports = RABBITMQ_PORTS.copy()
    ports.update({"15672/tcp": None})
    return ports


@pytest.fixture
def celery_rabbitmq_broker(default_rabbitmq_broker: RabbitMQContainer) -> RabbitMQTestBroker:
    broker = RabbitMQManagementTestBroker(default_rabbitmq_broker)
    yield broker
    broker.teardown()


@pytest.fixture
def celery_broker_cluster(celery_rabbitmq_broker: RabbitMQTestBroker) -> CeleryBrokerCluster:
    cluster = CeleryBrokerCluster(celery_rabbitmq_broker)
    yield cluster
    cluster.teardown()


###############################################################################
# Redis Result Backend
###############################################################################


@pytest.fixture
def celery_backend_cluster(celery_redis_backend: RedisTestBackend) -> CeleryBackendCluster:
    cluster = CeleryBackendCluster(celery_redis_backend)
    yield cluster
    cluster.teardown()


@pytest.fixture
def default_redis_backend_image() -> str:
    return "redis:latest"


###############################################################################
# Worker Configuration
###############################################################################


@pytest.fixture(scope="session")
def default_worker_celery_version() -> str:
    return "5.2.7"


@pytest.fixture(scope="session")
def default_worker_celery_log_level() -> str:
    return "INFO"


@pytest.fixture(scope="session")
def default_worker_celery_worker_queue() -> str:
    return "celery"


@pytest.fixture
def default_worker_command(default_worker_command: list[str]) -> list[str]:
    return default_worker_command + [
        "--without-gossip",
        "--without-mingle",
        "--without-heartbeat",
    ]


@pytest.fixture
def default_worker_app(default_worker_app: Celery) -> Celery:
    app = default_worker_app
    # app.conf...  # Add any additional configuration here
    return app


@pytest.fixture
def default_worker_tasks(default_worker_tasks: set) -> set:
    default_worker_tasks.add(tasks)
    return default_worker_tasks


###############################################################################
# Bug Reproduction
###############################################################################

def test_issue_9199(celery_setup: CeleryTestSetup):
    r = tasks.bug_test.apply_async(kwargs={"retry": True}, headers={"foo": "bar"})
    assert r.get() == "bug"
```

</p>
</details>

# Expected Behavior

I expect all task recursive iterations to have a Context propagated with the options I request.

# Actual Behavior

Debugging the celery worker, the task initially has the proper context. 
But on the upcoming recursion  the self.request is empty apart from args, kwargs which are persisted.

This does not happen:
- In my pytest unit tests
- When I run the celery worker in normal/async mode and I use apply_async

It happens only:
- With a celery worker set in EAGER mode.
- With a normal/async worker and using `apply`.

Debugging the code it seems the context is properly persisted up to this point:
https://github.com/celery/celery/blob/78ac69cfed7c485ba32726deaeaf6401d5e7bc1f/celery/app/trace.py#L408-L409

But then at this line where the actual method is being run:

https://github.com/celery/celery/blob/78ac69cfed7c485ba32726deaeaf6401d5e7bc1f/celery/app/trace.py#L453

The stack_protection kicks-in (which seems to be only available in workers:

https://github.com/celery/celery/blob/78ac69cfed7c485ba32726deaeaf6401d5e7bc1f/celery/app/trace.py#L713-L739

This causes a push in the request stack with a poor Context (only args, kwargs)

https://github.com/celery/celery/blob/78ac69cfed7c485ba32726deaeaf6401d5e7bc1f/celery/app/task.py#L407-L414

https://github.com/celery/celery/blob/78ac69cfed7c485ba32726deaeaf6401d5e7bc1f/celery/app/task.py#L1117

My expectation would be the Context to persist. 
I expect to have task information in a bound task regardless of whether it was called synchronously or asynchronously.

Note: 
 I am not sure, if I am missing something, whether a worker should never run in EAGER mode or this is expected somehow. My 
 use-case includes adding custom headers to all celery tasks and allowing propagation of those via a Custom Task.

**Comment by thedrow** [comment]
Thank you for the in-depth analysis. A worker in production should not run in eager mode usually. This is why it's less tested.
Would you be able to come up with a fix?

You can use the [stamping feature](https://docs.celeryq.dev/en/stable/userguide/canvas.html#stamping) to add custom metadata to tasks and canvases and see if that helps.

**Comment by nikatlas** [comment]
@thedrow The problem occurs even when I use `apply` in a normal async worker to call the same task and that is what troubles me the most. 

You can see the test case I added above:
```python
@shared_task(bind=True)
def bug_test(self, retry: bool = False):
    try:
        assert self.request.headers.get('foo') == 'bar'
    except AttributeError as exc:
        raise RuntimeError(f"Task expected to fail: retry={retry}, request={vars(self.request)}", exc)

    if retry:
        bug_test.apply(
            headers=self.request.headers,
        )
    return "bug"
```

I would be willing to contribute a fix for this but it seems this happens on purpose to protect the stack.
Without proper context, I am not sure I can come up with a proper fix.

**Comment by nikatlas** [comment]
@thedrow I made a PR #9208 with a fix. 
As I said, I have little context about the internals and the whole idea behind the stack protection, but it seems to me that this was added so that it works well with the tracer 🤷‍♂️ 

Maybe my fix should be placed somewhere else.
