### ISSUE TITLE
Use -P threads, the time_limit not work 

### ISSUE THREAD

**Issue by LiangPier-haha** [celery/celery#9203]
# Checklist

- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [ ] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by LiangPier-haha** [comment]
> Please give me a sample code to check this bug?

celery -A xxxx worker -P threads --loglevel=INFO

@celery_app.task(time_limit=10, soft_time_limit=10)
def test_time_limit():
    time.sleep(15)
    return None

log：
[2024-08-26 11:42:55,303: INFO/MainProcess] Task app.tasks.common.test_time_limit[89a15d07-0dc5-459e-aa73-db68fed496fa] received
[2024-08-26 11:43:10,449: INFO/MainProcess] Task app.tasks.common.test_time_limit[89a15d07-0dc5-459e-aa73-db68fed496fa] succeeded in 15.145238870999492s: None

**Comment by ashm-dev** [comment]
@LiangPier-haha seems that your problem lies elsewhere.

The value of `soft_tile_limit` must be less than `time_limit`.

**Comment by LiangPier-haha** [comment]
> @LiangPier-haha seems that your problem lies elsewhere.
> 
> The value of `soft_tile_limit` must be less than `time_limit`.

when time_limit=10, soft_time_limit=8, the problem still exists.

**Comment by mht2953658596** [comment]
#9196  I encountered the same problem but haven’t found a solution.

**Comment by thedrow** [comment]
As far as I know, there's no way to cancel a running thread so time limits do not work with threads.

**Comment by mht2953658596** [comment]
@thedrow What is the significance of setting the parameters time_limit and soft_time_limit?

**Comment by thedrow** [comment]
@mht2953658596 You can read about it in the docs [here ](https://docs.celeryq.dev/en/stable/userguide/configuration.html#task-time-limit) and [here](https://docs.celeryq.dev/en/stable/userguide/configuration.html#task-soft-time-limit).

**Comment by mht2953658596** [comment]
@thedrow  Alright, according to the document you mentioned：
```
task_time_limit
Default: No time limit.

Task hard time limit in seconds. The worker processing the task will be killed and replaced with a new one when this is exceeded.
```


So, for the issue mentioned in #9196, the final runtime shouldn't be 70 seconds because, according to the document, if the task_time_limit is exceeded, the worker processing the task will be killed and replaced with a new one. Therefore, a new worker should be executing the task by the 65th second, and it should have exceeded 70 seconds by then.

Additionally, the documentation states: 'The SoftTimeLimitExceeded exception will be raised when this is exceeded. For example, the task can catch this to clean up before the hard time limit comes.' It might be that the soft_time_limit was exceeded, but no timeout information was printed in the console, no retries were performed, and the task completed at 70 seconds. I have read the documentation, but I just don't understand why setting these two parameters doesn't seem to have any effect.
