### ISSUE TITLE
Add option for database backends: create tables on startup

### ISSUE THREAD

**Issue by MarcBresson** [celery/celery#9218]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same feature was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/issues/4653

#### Possible Duplicates

- None

# Brief Summary

this option called `database_create_tables_on_startup` would not wait for the first task before creating tables.

@Alexis-Jacob proposed a [workaround](https://github.com/celery/celery/issues/4653#issuecomment-400029147) but I believe it would make sense to have it as an option.

Our issue was that right after creating the first task, we query celery's database. But because celery did not have time to create the table yet, we have an error 

```
psycopg2.errors.UndefinedTable: relation "celery_taskmeta" does not exist
```

# Design

## Architectural Considerations

None

## Proposed Behavior

is `True` in the config, Celery would attempt to create the tables as soon as it is initialized. 

## Proposed UI/UX

It would be part of the [configuration of the backend](https://docs.celeryq.dev/en/stable/userguide/configuration.html#database-backend-settings)

## Diagrams

N/A

## Alternatives

As suggested in [this message](https://github.com/celery/celery/issues/4653#issuecomment-400029147):

```python
from celery.backends.database import SessionManager

app = Celery('celery', broker=BROKER_URL, backend=BACKEND_URL)

session = SessionManager()
engine = session.get_engine(app.backend.url)
session.prepare_models(engine)
```

**Comment by thedrow** [comment]
We have no maintainer for this backend. Feel free to contribute a setting that creates the tables on startup.
