### ISSUE TITLE
apply_async hangs indefinitely with confirm_publish=True

### ISSUE THREAD

**Issue by MZauchner** [celery/celery#9259]
# Bug description

I recently encountered an issue that only occurs when the `confirm_publish` option is set to `True`. 
The issue causes a process that calls a celery task to hang indefinitely when waiting for the publish confirmation.
It always occurs in connection with `NotFound` exceptions, although it could potentially be caused by other exceptions that leave the connection in an unusable state. 

I have added a minimal reproducer below which is adapted from: [issue](https://github.com/celery/py-amqp/issues/276).
By adding the commented option `broker_pool_limit=0` to the configuration file, the issue is resolved, however I think it should still work without this option.

Do you think it is feasible to remove broken connections from the broker connection pool and replace them with new ones?

Thank you very much for you time and help. Please let me know if you require and further information.

 
# Checklist

- [ -] I have verified that the issue exists against the `main` branch of Celery.
- [ x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x ] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ -] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).

- [-] I have verified that the issue exists against the `main` branch of Celery.
- [ -] I have included the contents of ``pip freeze`` in the issue.
- [ x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ -] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [- ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ -] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ -] I have tried reproducing the issue on more than one operating system.
- [ -] I have tried reproducing the issue on more than one workers pool.
- [ -] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ -] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- [Related](https://github.com/celery/py-amqp/issues/276)

#### Possible Duplicates

- None

## Environment & Settings

**5.3.4 (emerald-rush)**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.4 (emerald-rush) kombu:5.3.2 py:3.10.12
            billiard:4.1.0 py-amqp:5.1.1
platform -> system:Linux arch:64bit, ELF
            kernel version:5.14.0-295.el9.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis://127.0.0.1:61379/

broker_transport_options:
 'confirm_publish': True}
broker_url: 'amqp://localhost:********@127.0.0.1:61672//'
result_backend: 'redis://127.0.0.1:61379/'
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: 3.10.12
- **Minimal Celery Version**: 5.3.4 (emerald-rush)
- **Minimal Kombu Version**: 5.3.2
- **Minimal Broker Version**:  RabbitMQ 3.11.10
- **Minimal Result Backend Version**:  Redis 7.0.12
- **Minimal OS and/or Kernel Version**: Linux  5.14.0
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
The test case is separated into a minimal tasks.py file to configure the celery worker, celeryconfig.py for configuration options and add.py file which calls a simple task with apply_async.

**add.py:** 
```python
from kombu import Connection, Producer, Queue
import uuid
from amqp.exceptions import NotFound
import logging
import tasks
from tasks import app


with app.connection_or_acquire(pool=True) as c:
    p = Producer(c)
    q = Queue("my-queue-{}".format(uuid.uuid4()), channel=c)
    q.declare()
    p.publish(
        {"foo": "bar"},
        routing_key=str(uuid.uuid4()),
        retry=False,
    )

    q.delete()
    try:
        q.get()
    except NotFound:
        logging.exception("Not Found")
        q.declare()


result = tasks.add.apply_async(args=[1, 3]).get()
logging.info(f"Result: {result}")
```
**tasks.py:** 
```python
from celery import Celery
from celery.utils.log import logging

app = Celery("myproj")
default_config = "celeryconfig"
app.config_from_object(default_config)


@app.task
def add(x, y):
    logging.info(f"{app.conf}")
    return x + y
```
**celeryconfig.py:**
```python
broker_transport_options = {"confirm_publish": True}
# broker_pool_limit = 0
broker_url = "pyamqp://localhost:localhost@127.0.0.1:61672"
result_backend = "redis://127.0.0.1:61379"
```

</p>
</details>

# Expected Behavior
Even though an error occured when using a connection from the connection pool, the broken connection should be replaced with a new one and the apply_async call should return.

# Actual Behavior
running add.py hangs indefinitely. This can be resolved by disabling the broker_pool by using the setting 
`broker_pool_limit=0`. However it should also work without this setting, as broken connections should be replaced.

### py-spy output: 
```
Thread 4013756 (idle): "MainThread"
    _read (amqp/transport.py:627)
    read_frame (amqp/transport.py:294)
    blocking_read (amqp/connection.py:530)
    drain_events (amqp/connection.py:525)
    wait (amqp/abstract_channel.py:99)
    basic_publish_confirm (amqp/channel.py:1820)
    _publish (kombu/messaging.py:208)
    _ensured (kombu/connection.py:556)
    publish (kombu/messaging.py:186)
    send_task_message (celery/app/amqp.py:517)
    send_task (celery/app/base.py:798)
    apply_async (celery/app/task.py:594)
    <module> (myproj/add.py:27)
```

**Comment by thedrow** [comment]
This is definitely a bug. Do you have a potential fix for it?

**Comment by MZauchner** [comment]
@thedrow I am not that familiar with the celery codebase, but a monkeypatch like this  seems to solve the issue in this minimal example (if the `try` `except` block is instead placed around the entire context in *app.py*):
*tasks.py*:
```python
@contextmanager
def connection_or_acquire(self, connection=None, pool=False):
    if connection is not None:
        yield connection
    else:
        connection = self.pool.acquire(block=True)
        try:
            yield connection
        except:
            setattr(connection, "broken", True)
            raise

Celery.connection_or_acquire = connection_or_acquire

def release(self, resource):
    if self.limit:
        self._dirty.discard(resource)
        self.release_resource(resource)
        if hasattr(resource, "broken"):
            if resource.broken:
                resource = self.prepare(self.new())
        self._resource.put_nowait(resource)
    else:
        self.close_resource(resource)

kombu.resource.Resource.release = release
```

So a full solution would probably require some attribute in the `kombu.Connection` and `kombu.Producer` classes to keep track if the connection is unusable and then the `kombu.resources.Resource.release` method needs to be modified to check that attribute and potentially replace the resource.
