### ISSUE TITLE
celery breaks libs using sys.stdout.fileno() or sys.stderr.fileno()

### ISSUE THREAD

**Issue by iksaif** [celery/celery#928]
Some libraries (portage in my case) are (sanely) expecting that sys.stdout and sys.stderr have a working fileno() (to use dup()/pipe()/fork() and other low level stuff).

With celery, it's broken, because LoggingProxy always returns None for fileno().

I see two solutions:
- Add a fake fd (using os.pipe()) to each LoggingProxy instance, use it in fileno(), and read from it in each close()/write()/flush() call. Close the pipe in **del**() (issue: an fd is hard to poll safely on windows).
- Allow user to define their own LoggingProxy class (Celery already have some kind of support for alternate Logging classes, but Iḿ not sure how to use it and it's not documented).

**Comment by pavelfeldman** [comment]
@ask : In our case, Playwright use case linked above, it is Python's subprocess itself assuming fileno() is there, could you recommend a workaround for our users?
