### ISSUE TITLE
adding a backend for valkey

### ISSUE THREAD

**Issue by amirreza8002** [celery/celery#9295]
# Checklist

- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [ x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same enhancement was already implemented in the
  main branch.
- [ x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- https://github.com/celery/celery/issues/9092

#### Possible Duplicates

- None

# Brief Summary

valkey is a free licenced alterantive to the redis project, it has similar API, and can be implemented as a backend rather easily.

# Design

## Architectural Considerations

the valkey-py library(also has an optional C ibrary)
the packaging need to be adjucted to include valkey-py as an optional extra dependency

## Proposed Behavior

it adds a new backend, which has free licenced and can possibly become popular in near future.

## Diagrams

N/A

## Alternatives

i could make it a 3-rd party package if you don't want to have it in here, but i perfer it in celery

**Comment by auvipy** [comment]
why you opened a duplicate issue instead of commenting on existing one?

**Comment by amirreza8002** [comment]
> why you opened a duplicate issue instead of commenting on existing one?

hello
that issue was a request 
I'm saying i want to write it

since you have different tags for each subject, and a section to mention related issues, it seemed clear that you want this to be a separate issue
