### ISSUE TITLE
celery下使用cv2.reize程序异常退出

### ISSUE THREAD

**Issue by qianliyx** [celery/celery#9320]
# 环境
1. Python 3.12.5
2. celery 5.4.0
3. opencv-python 4.10.0.84
4. macos-15

# 启动命令
1. celery -A start_task.celery_app worker --loglevel=info
2. 程序截图：
![WechatIMG377](https://github.com/user-attachments/assets/b93d5ce3-43b2-46b3-9646-0bd8660b0b09)

# 报错信息
![WechatIMG378](https://github.com/user-attachments/assets/c24472e2-2a7e-4bf6-8e30-37b740566ce6)

**Comment by thedrow** [comment]
We don't understand Chinese. Please report this bug in English and use our template for reporting bugs.
