### ISSUE TITLE
Accessing a website within a Celery task may be blocked by Cloudflare security.

### ISSUE THREAD

**Issue by whilefoxfox** [celery/celery#9321]
###########
# audio_test.py
###########
import os
from groq import Groq
client = Groq()
filename = os.path.dirname(__file__) + "/sample_audio.m4a"
def my_test():
    with open(filename, "rb") as file:
        transcription = client.audio.transcriptions.create(
          file=(filename, file.read()),
          model="whisper-large-v3",
          prompt="Specify context or spelling",  # Optional
          response_format="json",  # Optional
          language="en",  # Optional
          temperature=0.0  # Optional
        )
        print(transcription.text)
#############
# main.py
#############
from celery import Celery
from audio_test import my_test

celery_app = Celery(
    "tasks",
    broker="amqp://***:***@127.0.0.1:5672",
)

celery_app.config_from_object('config')
celery_app.conf.broker_connection_retry_on_startup = True
celery_app.autodiscover_tasks(['app.tasks'])

@celery_app.task(name='app.tasks.audio_tasks')
def audio_transcription():
    my_test()

audio_transcription.delay()

**Comment by Nusnus** [comment]
Please use our bug report template, thank you.
