### ISSUE TITLE
Allow custom hostname for celery_worker in celery.contrib.pytest / celery.contrib.testing.worker

### ISSUE THREAD

**Issue by SlowMo24** [celery/celery#9404]
# Checklist

- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same enhancement was already implemented in the
  main branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

During testing I would like to mimic my production behaviour. In production I use a custom hostname because I fully separate the sender from the worker and therefore need to have stable worker names.

I would like to define a custom hostname for the `celery_worker` fixture as well.

# Design

## Architectural Considerations

None

## Proposed Behavior

The proposed changed will be a backward compatible new optional configuration parameter `hostname` of the `celery_worker_params` pytest fixture used to init the `celery_worker` pytest fixture.

## Diagrams

The suggestion is to write 

```python
        hostname=kwargs.pop("hostname", anon_nodename()),
```

https://github.com/celery/celery/blob/b468b91cbb84e3a0b84946607af5a90a58f0a643/celery/contrib/testing/worker.py#L158

I'm happy to pour this into a MR.

## Alternatives

I currently use a 'superior' pytest patch fixture to fix the shortcoming myself:

```python
@pytest.fixture
def patch_pytest_celery_worker_hostname():
    with patch('celery.contrib.testing.worker.anon_nodename', return_value='test_plugin@localhost') as p:
        yield p


@pytest.fixture
def celery_worker(patch_pytest_celery_worker_hostname, celery_worker):
    return celery_worker
```

**Comment by Nusnus** [comment]
Interesting change - please tag me for review if you want to offer a PR.

Thanks!
