### ISSUE TITLE
celery MainProcess stuck in write() to defunct worker process

### ISSUE THREAD

**Issue by public** [celery/celery#957]
Celery 3.0.7. Redis broker.

Seems to happen just after the worker restarts due to MAX_TASKS.

This particular queue is doing little more than opening an SSL socket to a remote server and cramming some data down it. I don't get any errors from the worker and it seems to be completing it's job just fine before exiting.

This happens very reliably with this task. However if I set PREFETCH_MULTIPLIER = 0. It seems much happier.

**Comment by kichooo** [comment]
Just for the sake of people trying to debug that in 2017.

I'm still getting this on 3.1.25, with the same symptoms and conditions. Knowing that big tasks might be culprits here is helpful for me for debugging.
