### ISSUE TITLE
Task retries max at 3 attempts

### ISSUE THREAD

**Issue by trent** [celery/celery#976]
Python 2.6.5
Celery 3.0.9
Redis 2.4.16

I wrote a very simple task to better understand retry functionality:

```
@task
def retry_test():
    logger.info("retry_test id:%s", retry_test.request.id)
    logger.info("retries:%s", retry_test.request.retries)

    foo = {'bar': 0}

    if retry_test.request.retries > 10:
        return True
    else:
        try:
            foo['foo']
        except KeyError as exc:
            retry_test.retry(exc=exc, countdown=5)
```

I am finding that the task is only retried 3 times, but I would prefer that the task is retried indefinitely.  I have tried setting BROKER_CONNECTION_MAX_RETRIES, but that doesn't seem to change the retry attempts.  Is there another setting I should be looking at?

**Comment by cosenal** [comment]
I am still curious about @trent's question, that is, whether there exists a global setting for the number of max retries for tasks. In my project it makes sense to have a max_retries=10 and without a default settings, I'll have to change it in every single task.

**Comment by ask** [comment]
@cosenal,

I'm not sure if this is what you want, but you can specify a default by doing:


```py

    app = Celery()
    app.Task.max_retries = 10

```

or by configuration:

```py

    CELERY_TASK_ANNOTATIONS = {'*': {'max_retries': 10}}

```

**Comment by cosenal** [comment]
Thank you, @ask, that's exactly what I was looking for.
