### ISSUE TITLE
Expires not respected on task retry

### ISSUE THREAD

**Issue by trent** [celery/celery#980]
Python 2.6.5
Celery 3.0.9
Redis 2.4.16

I am retrying a task due to an expected error, but the expires value on the originating task is not passed to the retried task.  Is that intentional?  I thought all values from the original task were passed to the retried task.

**Comment by matt-snider** [comment]
It doesn't seem to be the case anymore that expires is carried over to the task on retries. Is this intentional? 

The only way I seem to be able to get this to work is something like:
```python
@app.task(bind=True)
def add(self, x, y):
    expires = datetime.strptime(self.request.expires, '%Y-%m-%dT%H:%M:%S.%f')
    if some_condition:
        self.retry(expires=expires)
    return x + y
```
